### ISSUE TITLE
Support for working on a target & its dependencies simultaneously

### ISSUE THREAD

**Issue by robrix** [Carthage/Carthage#10]
Either we need to rebuild things, or we need to ensure that Xcode rebuilds things. The latter is going to be a better experience for the user I think.

**Comment by jspahrsummers** [comment]
I was able to get automatic rebuilding by using the following shell script:

```sh
/usr/local/bin/carthage build "$SRCROOT"
```

inserted into the Build Phases as follows:

![screen shot 2015-01-04 at 00 24 48](https://cloud.githubusercontent.com/assets/432536/5605297/1fa294b4-93a8-11e4-9a9f-84e6eeab8a26.png)

So this all appears to work, although it's kind of agonizing not having build progress while the script runs.

Is this generally useful enough to be documented somewhere? If so, where?

**Comment by jspahrsummers** [comment]
> Is this generally useful enough to be documented somewhere? If so, where?

@Carthage/carthage _bump_

**Comment by robb** [comment]
> Is this generally useful enough to be documented somewhere? If so, where?

Generally yes, but I'd wait until we have platform specific builds for this.
