### ISSUE TITLE
Dependency has no shared framework schemes

### ISSUE THREAD

**Issue by djih** [Carthage/Carthage#1008]
Hello,

We're trying to add Carthage support for our open-source library: https://github.com/amplitude/Amplitude-iOS. If I run `carthage build --no-skip-current`, I get `Dependency "Amplitude-iOS" has no shared framework schemes`, although I have marked 2 of our schemes as shared, [you can see them here](https://github.com/amplitude/Amplitude-iOS/tree/master/Amplitude.xcodeproj/xcshareddata/xcschemes). I was able to run `xcodebuild -scheme Amplitude -project Amplitude.xcodeproj build` and have it build successfully (with 1 warning).

Is there something that we're missing? If it helps we're using Carthage v0.11.0 (via Homebrew).

Any help is appreciated, thanks!

**Comment by mdiep** [comment]
Your schemes are shared, but they build a _static library_, not a _dynamic framework_. Carthage only supports the latter. :smile:

**Comment by djih** [comment]
@mdiep ah thanks for the explanation.
