### ISSUE TITLE
Carthage fails to clone repos when git URLs have SCP-syntax without user name.

### ISSUE THREAD

**Issue by inamiy** [Carthage/Carthage#1012]
For example:

```Cartfile
# SCP-syntax WITHOUT username.
# This will fail with error: "The following dependencies are duplicates"
git "github.com:antitypical/Result.git"
git "github.com:antitypical/Assertions.git"



# SCP-syntax with username. This will work.
#git "git@github.com:antitypical/Result.git"
#git "git@github.com:antitypical/Assertions.git"

# HTTPS-based. This will work too.
#git "https://github.com/antitypical/Result.git"
#git "https://github.com/antitypical/Assertions.git"
```

It seems `GitURL.normalizedURLString` always return empty string for above case
(`NSURL(string: URLString)` generally parses SCP-syntax well).
I think such URLs should have either current logged-in username or "git" by default.

**Comment by ikesyo** [comment]
Thank you for the report, I'll investigate this.

**Comment by mdiep** [comment]
> It seems GitURL.normalizedURLString always return empty string for above case

Apart from the case noted here, it seems like an error to have it ever return an empty string.
