### ISSUE TITLE
Cannot build iOS CryptoSwift using Carthage

### ISSUE THREAD

**Issue by danwatco** [Carthage/Carthage#1016]
Told to ask here.

Having a problem with the crypto swift carthage build.

When I try `carthage update --platform iOS` I get a build error and it cannot build the framework. The error is to large for here. The last few lines are,

`error: could not build module 'Foundation'
<unknown>:0: error: could not build Objective-C module 'CryptoSwift'
A shell task failed with exit code 65`

**Comment by NachoSoto** [comment]
Could you paste some more information from the error? Adding `--verbose` might help to.

**Comment by danwatco** [comment]
Heres some more when using verbose 

```
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/danwatkinson/Documents/Swift/SnapLoad/Carthage/Checkouts/CryptoSwift/Sources/CryptoSwift/Foundation/String+LinuxFoundation.swift
	CompileSwift normal arm64 /Users/danwatkinson/Documents/Swift/SnapLoad/Carthage/Checkouts/CryptoSwift/Sources/CryptoSwift/PKCS7.swift
	CompileSwift normal arm64 /Users/danwatkinson/Documents/Swift/SnapLoad/Carthage/Checkouts/CryptoSwift/Sources/CryptoSwift/SHA2.swift
	CompileSwift normal arm64 /Users/danwatkinson/Documents/Swift/SnapLoad/Carthage/Checkouts/CryptoSwift/Sources/CryptoSwift/Foundation/Utils+Foundation.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)
```
There is much more to the error. Shall I paste all of it?

**Comment by NachoSoto** [comment]
Yeah, could you paste information about those 5 failures? In any case this seems to be a problem with the library, but looking at those will shed more light.

**Comment by danwatco** [comment]
This is all of it. https://gist.github.com/danwatco/f1e07f1545a5d927421f

**Comment by NachoSoto** [comment]
That looks like [this radar](http://www.openradar.me/22993940), which the last version of Carthage has a workaround for. What version are you using?

**Comment by danwatco** [comment]
Currently on 0.8.0, an update is needed, that would probably fix it. Let me check.

**Comment by danwatco** [comment]
Fixed, all it needed was an update. Sorry to bother you, thanks.
