### ISSUE TITLE
Carthage build not working

### ISSUE THREAD

**Issue by reshadf** [Carthage/Carthage#1018]
Hello, 

I have several libraries build with Carthage. But on this particular framework I get the error 

SwiftHTTP was compiled with optimization - stepping may behave oddly; variables may not be available.

I think because its building on release configuration rather than the debug config. How can I solve this problem?

**Comment by mdiep** [comment]
`carthage` has a `--configuration` parameter that you can pass `Debug` to. Try `carthage help build`.
