### ISSUE TITLE
Carthage Continues to Build at a Tag Even After the Tag has been Deleted

### ISSUE THREAD

**Issue by matthewcarroll** [Carthage/Carthage#1027]
Carthage got stuck building a dependency at a tag, even after I deleted that tag in the dependency's project. 

Steps to reproduce:
1. Add tag a to a dependent project
2. Add the dependency to a cartfile and specify no version or branch
3. Run carthage update
4. Build succeeds
5. Delete the tag in the dependent project
6. Run carthage update
7. Build succeeds

After running rm -rf ~/Library/Caches/org.carthage.CarthageKit/, the build fails as expected with "No tagged versions found for github".

Let me know if I can help.

**Comment by NachoSoto** [comment]
Hardest problem in Software Development: cache invalidation.
