### ISSUE TITLE
Carthage incorrectly checking for parent repo submodules in checkouts

### ISSUE THREAD

**Issue by kballard** [Carthage/Carthage#1029]
After installing the current master (1f9d588b41bee6dcf58ec0ee9e1908a50a6eea32), `carthage bootstrap` fails in my project with the error:

```
Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD PostmatesKit/PMKCore) but encountered: 
```

(`PostmatesKit/PMKCore` is a submodule in the current repo)

After hacking up Carthage to print some more info, it turned out it was running this `git ls-tree` command from within the `Carthage/Checkouts/CocoaLumberjack` folder.

I have no idea what it's trying to do with submodules, but it certainly shouldn't be looking for them from within a Checkouts folder, because those things aren't git repos, they're just working trees, so any git commands executed from within that folder end up using the info from the parent project.

**Comment by NachoSoto** [comment]
And `0.11.0` is working fine?

**Comment by kballard** [comment]
Yes, the official release of `0.11.0` works just fine.

**Comment by kballard** [comment]
I haven't done much digging but a likely culprit is e1677cdf667c5bb03a77660a49735ce0cba126de (Ignore certain subdirectories when searching for projects to build)

**Comment by kballard** [comment]
Incidentally, since I suspect it matters, I do _not_ use `--use-submodules`, so my Checkouts are always just bare working trees. I imagine this issue does not affect people who use `--use-submodules` because their Checkouts will be git repos instead of just working trees.

**Comment by NachoSoto** [comment]
Right. I don't use `--use-submodules` either, so thanks for catching this! I mentioned this issue in #892.

**Comment by mdiep** [comment]
This is going to take a bit of work to fix up, I think. We need to correctly identify submodules for dependencies that are checked out with `--no-use-submodules`.

**Comment by kballard** [comment]
One possible solution is to detect the subdirectory we're in and filter the submodule list to just ones in that directory. To be correct you really need to know that subdirectory path anyway because the path given to `git ls-tree` is relative to the current directory, so if you're in a subdirectory you need to make sure the path is relative to that subdirectory.

That said, it's better to skip checking submodules entirely when looking at a `--no-use-submodules` Checkout because otherwise Carthage will be reading the submodules list and checking for relative path to repo root repeatedly for every single dependency, which is a waste of time. Carthage already spends long enough preparing to build dependencies, there's no sense in doing work that we know is useless.

**Comment by mdiep** [comment]
> That said, it's better to skip checking submodules entirely when looking at a --no-use-submodules Checkout because otherwise Carthage will be reading the submodules list and checking for relative path to repo root repeatedly for every single dependency, which is a waste of time

Carthage needs to correctly identify and ignore submodules inside `--no-use-submodules` checkouts. Otherwise, it will try to build projects inside those submodules. That's the intent of the problematic code.

But where we currently assume that the checkout is a git checkout with its own accessible `.gitmodules`, we'll need to directly access the correct `.gitmodules` file for that checkout.

**Comment by kballard** [comment]
Why would there be a submodule inside a `--no-use-submodules` checkout? Surely Carthage created the directory for the checkout. Does Carthage not actually consider it an error for there to be a pre-existing subdirectory inside of a path to one of its `--no-use-submodules` checkouts when it attempts to perform the checkout?

**Comment by mdiep** [comment]
Because a repository doesn't need to manage all (or even any) of its dependencies with Carthage. For instance, https://github.com/ReactiveCocoa/RockemSockem currently has some dependencies inside an `External` folder, managed with submodules.

**Comment by kballard** [comment]
Yeah, but those submodules aren't in `Carthage/Checkouts`. It makes sense for Carthage to detect what folders are submodules of the original project, my point is just that whenever it's looking at any of its non-submodule Checkouts, there's no point in looking at submodules from the original project unless you actually think it's possible for some project to have a submodule at `Carthage/Checkouts/Foo/External` while still using Carthage to actually generate the contents of `Carthage/Checkouts/Foo` to begin with.

**Comment by mdiep** [comment]
> It makes sense for Carthage to detect what folders are submodules of the original project, my point is just that whenever it's looking at any of its non-submodule Checkouts, there's no point in looking at submodules from the original project

I think we're saying the same thing.

Here's what's currently happening. Carthage notices a `--no-submodule` checkout at `Carthage/Checkouts/Foo`. While looking to see what projects it should build from `Foo`, it wants to check if `Foo` has any submodules. So it does something like `cd Carthage/Checkouts/Foo; git submodule list` (that's not an actually command; it's illustrative)—expecting to get the submodules from `Foo`. But since `Foo` isn't itself a submodule, the git command returns the submodule information from the parent project.

**Comment by kballard** [comment]
Why would it expect `Foo` to have any submodules, since it already knows it's a `--no-submodule` checkout? The only way I can think of for that to do anything is if someone actually adds the `Carthage/Checkouts/Foo` folder to the parent project and then inserts a submodule in it. Is that even a supported configuration?

**Comment by mdiep** [comment]
If you run `carthage update --no-use-submodules` with this `Cartfile`:

```
github "ReactiveCocoa/RockemSockem"
```

Then `Carthage/Checkouts/RockemSockem` will have its submodules cloned into the relative `External` directory, such as `Carthage/Checkouts/RockemSockem/External/CocoaHTTPServer `.

**Comment by kballard** [comment]
(assuming you meant to include `--no-use-binaries`)

Interesting, but I don't see how that's relevant at all. There are no git repos in `Carthage/Checkouts` when I do that. `Carthage/Checkouts/RockemSockem` isn't a git repo. Nor is `Carthage/Checkouts/RockemSockem/External/CocoaHTTPServer`. I can see why you'd want to skip the externals, but running `git config --blob HEAD:.gitmodules -z ...` from within `Carthage/Checkouts/RockemSockem` isn't going to do anything at all to detect these submodules, since it's testing the parent repo. And even if you modify that to use `git config --file .gitmodules -z ...` instead, there's still no reason to run `git ls-tree -z HEAD $path` because `Carthage/Checkouts/RockemSockem` isn't a git repo.

**Comment by kballard** [comment]
Basically, as near as I can figure, unless `Carthage/Checkouts/Foo` is itself a submodule, there's no reason to ever expect to find submodules nested inside of `Carthage/Checkouts/Foo`. Reading `Carthage/Checkouts/Foo/.gitmodules` to figure out what would have been a submodule had that been an actual git clone seems reasonable, but there's no reason to actually run any `git` commands inside of that directory.

Of course, if `Carthage/Checkouts/Foo` *is* a submodule, then the current behavior is reasonable. But the default behavior is to not use submodules, which means for most people `Carthage/Checkouts/Foo` is not going to be a submodule.

**Comment by mdiep** [comment]
The point is to not build projects in `Carthage/Checkouts/RockemSockem/External/CocoaHTTPServer`, regardless of whether there are any submodules on disk.
