### ISSUE TITLE
When AlamofireImage is added to a watchOS extension target Xcode complains that the watchOS framework was built for iOS when installed through Carthage

### ISSUE THREAD

**Issue by ivan-konov** [Carthage/Carthage#1031]
I get this error when I try to add the 2 frameworks(Alamofire & AlamofireImage) to my WatchKit Extension target. It actually does not matter from which platform Build folder I will add the frameworks. It always shows the same error.
``
ld: building for watchOS simulator, but linking against dylib built for iOS, file '/Some-Project-Filder/Carthage/Build/iOS/AlamofireImage.framework/AlamofireImage' for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
``

**Comment by NachoSoto** [comment]
That's probably because you have `Carthage/iOS` in the `FRAMEWORK_SEARCH_PATHS` setting of your `watchOS` target.

**Comment by mdiep** [comment]
Are you using carthage 0.11? We had to make some fixes to work around Xcode issues.

**Comment by ivan-konov** [comment]
That was the problem. Sorry for the noob question!

**Comment by NachoSoto** [comment]
@ivan-konov no need to apologize! Xcode should not require us to configure all this stuff manually.

![it just works](https://cloud.githubusercontent.com/assets/685609/12206123/0172b810-b5f4-11e5-88e1-1996ddfe4302.jpg)

**Comment by ivan-konov** [comment]
The "paths" build settings are always a tricky matter I just forgot to check it. Every time I have such a problem I think I should file a radar to Apple so they create separate UI for that! :D
Thanks again!

**Comment by ecaselles** [comment]
Spent 1h looking for the cause of this error and kept going in circles with the carthage's copy-frameworks step... Thanks @NachoSoto!
