### ISSUE TITLE
xcodebuild output can be found in ...

### ISSUE THREAD

**Issue by dowhilenet** [Carthage/Carthage#1036]
carthage update

then 

xcodebuild output can be found in /var/folders/nd/3mqk8hv15_5c1ddlftjnzncw0000gp/T/carthage-xcodebuild.SEnHtt.log

**Comment by NachoSoto** [comment]
Please post more information about your issue.

**Comment by dowhilenet** [comment]
![](http://7s1rp2.com1.z0.glb.clouddn.com/QQ20160112-0.png)

**Comment by dowhilenet** [comment]
before i use cocoapods  then  i delete cocoapods from my project by [cocoapods-deintegrate](https://github.com/CocoaPods/cocoapods-deintegrate)   

when i use carthage , run carthage update a waring output

**Comment by mdiep** [comment]
This [seems to be a warning](https://duckduckgo.com/?q=%22failed+to+load+addressbook+class+cncontactnameformatter%22&t=osx) from `xcodebuild`, unrelated to Carthage.
