### ISSUE TITLE
`carthage build` takes 35 seconds before building anything

### ISSUE THREAD

**Issue by kballard** [Carthage/Carthage#1037]
In my project I have 10 direct dependencies, and a total list of 14 dependencies (according to Cartfile.resolved). Running `carthage build --platform ios,watchos` takes a full 35 seconds before it prints the first line saying that it's building my first dependency. Terminal.app says this 35 seconds is spent running both `grep` and `xcodebuild`, so I assume it's searching through the build settings of the various dependencies. But 35 seconds is quite excessive for this, which makes me wonder just how many times it's doing this.

**Comment by mdiep** [comment]
Is this with `0.11` or with `master`?

**Comment by kballard** [comment]
Both

**Comment by ikesyo** [comment]
Closing this for now.
