### ISSUE TITLE
Add build command option that allows specification of custom toolchain.

### ISSUE THREAD

**Issue by calebd** [Carthage/Carthage#1039]
`xcodebuild` has a `-toolchains` argument that can be used to specify a custom toolchain. This is handy now that Xcode 7.3 allows the use of open source Swift toolchains.

**Comment by tkrajacic** [comment]
Is there actually a way of how to build using the open source snapshots with Carthage at the moment? Carthage doesn't seem to respect the environment variable for setting the toolchain it seems.

**Comment by mdiep** [comment]
No, I think an argument would need to be added to `carthage` for that.

**Comment by calebd** [comment]
Trying to wade through the code to build this. Currently you only either provide `TOOLCHAINS=swift` or you don't. There isn't much else to customize. I had initially thought there should be a `--toolchains swift` argument but now I think we should have a `--use-swift-toolchains` or other similarly named boolean argument instead.

**Comment by mdiep** [comment]
We should probably follow the form of `xcodebuild` and use `--toolchain NAME`.

**Comment by tkrajacic** [comment]
Is anyone working on this?

Carthage uses `xcodebuild` right?

Sorry if that's a stupid question but can't we just make `-toolchain` a passthrough argument then?

**Comment by mdiep** [comment]
> Is anyone working on this?

Not that I know of.

> Carthage uses xcodebuild right?

Right.

> Sorry if that's a stupid question but can't we just make -toolchain a passthrough argument then?

Yes! Pull requests welcome. ☺️

**Comment by tkrajacic** [comment]
It's my first pull request on any open source project, so be gentle ;)

I don't know much about _ReactiveCocoa_ btw, so it was a bit of a pain to follow flow of execution. Hope I didn't miss anything.

**Comment by mdiep** [comment]
> It's my first pull request on any open source project, so be gentle ;)

That's great! Congratulations! 😄
