### ISSUE TITLE
Custom resolution endpoint/path for binaries

### ISSUE THREAD

**Issue by lyptt** [Carthage/Carthage#1042]
I think one useful feature might be to be able to archive all of the frameworks you've built locally then reuse those binaries in future builds. At the moment it looks like archival and binary resolution is on a per-dependency basis rather than being something end consumers of multiple dependencies can use to bundle up what they've already built.

For my CI build I'd want to only be building new versions of my dependencies when there have been changes, whereas beta/prod builds would always build from scratch. This would allow a shorter feedback loop during development.

I suppose this would sit somewhere around the current workflow of one person running update, and the others running bootstrap. The person updating the dependencies might be able to run archive which would bundle up everything they've built, then bootstrap would have an extra argument for where to look for these dependencies.

I'd be happy to hear anyone's thoughts on this, or any tips on where to go about adding this functionality myself if there's not much interest in this feature being generally available.

**Comment by mdiep** [comment]
This project by @guidomb might be what you're looking for: https://github.com/guidomb/carthage_cache.

**Comment by guidomb** [comment]
@lyptt carthage_cache uploads a zip file of all your dependencies binaries to a bucket in S3. All the developer in your team can share this as a cache. Your CI can also download the archive and avoid having to build all the dependencies every time, which in environments like TravisCI could take up to half an hour.

Let me know if you need any help.

**Comment by lyptt** [comment]
Nice! This looks like exactly what I'm looking for. Thanks for the help :)
