### ISSUE TITLE
Opinionated example of a library

### ISSUE THREAD

**Issue by fulldecent** [Carthage/Carthage#1043]
I have several awesome libraries already on Cocoapods. My process is always:

 1. Already making an application
 2. Oh maybe this part should be modular
 3. Oh shit, how do people make modular projects nowadays?
 4. `pod lib create MYModule`
 5. Put stuff in there, make it work
 6. Publish

FYI, by default, their template gives you a library, a demo app and testing, and gets it all working so you can start hacking. This has been VERY helpful for me.

Since I think of Carthage as a replacement for Cocoapods, I am looking here for an opinionated template that helps me get started as a library author. Does such a template exist?

**Comment by mdiep** [comment]
I'm not aware of any templates. Carthage is somewhat unopinionated about project structure.

I usually begin with the Xcode template, rename a few directories, add a workspace that loads contains submodule checkouts of the dependencies, and maybe add an example app.

If you wanted to create a template repository, that might be something we could host under the Carthage org. Otherwise some documentation would be very welcome.

**Comment by aral** [comment]
@fulldecent This explains my process exactly (although I don’t use Cocoapods). My process is currently:

1. Create a new workspace
2. Create and add a framework project to the workspace
3. Create and add an app project to the workspace for the demo

I’ve had trouble using Carthage to actually load the dependencies for the demo app (as I keep the folder containing the workspace and projects in the same git repo) so I link the framework manually for the example. (I’d love to use Carthage for that to demonstrate its use.)

Also, there’s a bunch of configuration each time for setting up Framework Search Paths, etc.

I was on the verge of automating all this with a script this morning before deciding it would be too much yak shaving at this point but your post is very timeline and just wanted to +1 a real-world use case for it.

**Comment by fulldecent** [comment]
@aral thanks for sharing. FYI, back with Obj-C / Cocoapods, it wasn't even necessary to use a framework, just make any project and then the pod file selects the class you want to extract.

I like your way a lot better!

**Comment by fulldecent** [comment]
I have created an example framework and an example consuming test app.

https://github.com/fulldecent/carthage-example-framework

https://github.com/fulldecent/carthage-example-app

I am sure these can be improved, but I wanted to get something working and contributed back to the project. It took me all day to figure this out, and a million things went wrong. But having the final product and this experience will help me next time.

I would love to hear from other people that million things that go wrong and then address those items in a Q&A in these repositories.

@mdiep is there a chance for me to contribute this to the Carthage GitHub organization?

**Comment by mdiep** [comment]
@fulldecent Sorry that it has taken me so long to reply. I've been swamped and this has unfortunately been a lower priority item.

I've been thinking about this, and I don't think it makes sense to add this to the Carthage organization. Mostly I don't want the Carthage org to be responsible for maintaining it when we're already lacking contributors. I'd also rather focus on improving any deficiencies in our documentation. (If you have any suggestions there, a pull request would be very welcome!)

But I did notice something that I wouldn't consider a best practice: You've checked in the full sources of `carthage-example-framework` in `carthage-example-app`. This definitely a supported configuration, but I would recommend either using submodules or not checking in the code.

**Comment by fulldecent** [comment]
Thanks for the reply I will close this issue -- but also the Gil of this issue is being achieved elsewhere. I am now working on the CocoaPods/pod-template project and hoping to make that much more usable. (Anyone interested please see my PR.) By default, the `pod lib create` command will support Carthage (and SPM) and well as testing and CI. I am hoping it will be a good way for simple people like me to start new projects :-)

**Comment by mdiep** [comment]
> By default, the pod lib create command will support Carthage (and SPM) and well as testing and CI.

That's _fantastic_ news! ✨

**Comment by fulldecent** [comment]
FYI I have created a recipe and template for people that want to make Swift modules that work from Carthage. There is actually is a little bit of magic in there. (i.e. manually editing the Info.plist location setting after you rename a folder, to compensate for an Xcode bug.) All these little steps are documented.

 > https://github.com/fulldecent/swift3-module-template

Y'all probably know all this stuff in here. But feel free to share with anyone else that is asking these types of questions.
