### ISSUE TITLE
How does Carthage know where the xcodeproj is?

### ISSUE THREAD

**Issue by onmyway133** [Carthage/Carthage#1047]
How does Carthage get to know the `xcodeproj` and fetch it?

Like I have https://github.com/onmyway133/Warlock, which is made of `pod lib create`. Hence I have that project structure. The `Warlock.xcodeproj` is actually inside `Example` folder. Does Carthage perform a scan? What if there are many `xcodeproj` inside my repo?

**Comment by mdiep** [comment]
> The Warlock.xcodeproj is actually inside Example folder. Does Carthage perform a scan? What if there are many xcodeproj inside my repo?

The current version of Carthage (0.11) selects the first `.xcodeproj`—where first means root-most directory and then alphabetical order.

The next version of Carthage (0.12) will build *all* frameworks in the current project.

**Comment by victorgama** [comment]
@mdiep I'm actually having a little issue with Carthage and multiple `xcodeproj`s. See, I have two of those files, where one of them is on the repository root, and the other in a folder. For some reason I couldn't yet understand, Carthage tries to build not the _root-most_, but the one that is in the mentioned folder (and hangs right after, no output, no timeout, even when `--verbose` is provided).

Actually using version `0.11.0`.

**Comment by mdiep** [comment]
There are some additional qualifications: there must be a shared framework scheme, for example.

**Comment by victorgama** [comment]
Nah. The `xcodeproj` it is trying to use does not have any shared framework scheme. In fact, I'm guessing it is a `xcodebuild` issue: I managed to get the command Carthage issued with `ps aux`, and ran it manually, which produced the expected list of targets and build configurations, but it never exits.

**Comment by victorgama** [comment]
@mdiep Is there a way to specify which `xcodeproj` Carthage should use?

**Comment by mdiep** [comment]
> Is there a way to specify which xcodeproj Carthage should use?

No. But as I said, in 0.12 Carthage will build all frameworks in all `.xcodeproj`s in the repository. (Looking at my comment again, that may not have been clear enough.)

**Comment by victorgama** [comment]
I see. Thank you. (:

**Comment by onmyway133** [comment]
@mdiep thanks. In the root of my project, there is `_Pods.xcodeproj` which is a symbolic link to `Example/Pods/Pods.xcodeproj`. But I see Carthage build it as `Warlock.framework`. So Carthage use the repo name as the built framework name?

**Comment by mdiep** [comment]
Carthage doesn't do anything to the name of the built framework. It just builds the framework with Xcode and uses whatever name it was given there.

**Comment by megastep** [comment]
I am actually trying to add Carthage support to the AudioKit project (http://github.com/audiokit/AudioKit).

The main issue is that this repository contains frameworks for iOS, tvOS and OS X. Each of these versions have their own `.xcodeproj` nested within a couple of subdirectories. Each of these projects also creates an AudioKit.framework for the particular OS - there is no differentiation in the name itself. So you end up with 3 separate AudioKit.framework, one for each supported OS. Realistically only one of those is going to be used in a given project.

Ideally, we'd like to be able to tell Carthage which xcodeproj to use to build the framework depending on which OS the project is building for. But failing that, we'd like to at least be able to specify one particular Xcode project in the Cartfile since it doesn't make sense for an iOS developer to build binaries for the other systems. And there is the more pressing issue of being able to inform Carthage of where the files are.

Are we going to have to wait for 0.12 to do something like this?

**Comment by mdiep** [comment]
> Are we going to have to wait for 0.12 to do something like this?

Yes. I'm hoping to release 0.12 within the next week, FWIW.

**Comment by oflannabhra** [comment]
Currently on `v 0.11` I'm running into an issue where Carthage is not grabbing the root-most `.xcodeproj`. It is grabbing an example project 2 folders deep in the directory structure that does not have any shared schemes and is attempting to build it and will permanently hang. 

I know that `v 0.12` should fix this, just making a note here in case anyone else on `v 0.11` runs into this issue before `v0.12` releases.

**Comment by oflannabhra** [comment]
Updated to `v 0.12` and still have the same issue: Carthage is not grabbing the root-most `.xcodeproj`, and is not attempting to build all `.xcodeproj`s in the repository. `carthage update` fails after the first `xcodebuild` times out.

**Comment by mdiep** [comment]
@oflannabhra Is this a public repository?

In order for Carthage to build from a project, it must include a shared scheme for a dynamic framework. Your project must be failing one of those criteria.

**Comment by oflannabhra** [comment]
Yes, it is a public repository. The repository is [victorgama/NSLogger](https://github.com/victorgama/NSLogger). The structure of the project is:
```
* NSLogger.xcodeproj
\
 | Desktop Viewer
 * NSLoggerViewer.xcodeproj
```
a simple Cartfile with
`github "victorgama/NSLogger" "carthage-support"`
results in
```
~ carthage update
*** Fetching NSLogger
*** Checking out NSLogger at "v1.6.9"
Failed to discover shared schemes in project NSLoggerViewer.xcodeproj — either the project does not have any shared schemes, or xcodebuild timed out.

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/victorgama/NSLogger/issues/new
```

Carthage never even touches the root `NSLogger.xcodeproj`

**Comment by victorgama** [comment]
@mdiep There's also a `test` branch, in which I tried to mess with project's internal files and such. The last tag of this fork points probably to the last commit of this `test` branch.

**Comment by victorgama** [comment]
@mdiep Also: I can successfully build the `carthage-support` branch, while @oflannabhra can't. Did I do something wrong configuring the project?

**Comment by mdiep** [comment]
So I just took a look at the `test` branch. Carthage _does_ find buildable schemes in `NSLogger.xcodeproj`. But unfortunately, `xcodebuild` times out with `NSLoggerViewer.xcodeproj`, which causing Carthage to error. We should maybe be a little more tolerant of this case and continue to build the other schemes.

If you run this command:

```
xcodebuild -list -project Carthage/Checkouts/NSLogger/Desktop\ Viewer/NSLoggerViewer.xcodeproj/
```

then `xcodebuild` just hangs.

**Comment by oflannabhra** [comment]
:+1: thanks @mdiep
