### ISSUE TITLE
How does Carthage know where the Cartfile is?

### ISSUE THREAD

**Issue by onmyway133** [Carthage/Carthage#1048]
I'm reading https://robots.thoughtbot.com/creating-your-first-ios-framework and its repo is https://github.com/jakecraige/RGB

In that repo, there is `Cartfile` with content

```
github "thoughtbot/Curry"
```

So Carthage only looks for `Cartfile` in the root of the repo to see next dependencies to fetch?

**Comment by mdiep** [comment]
> So Carthage only looks for Cartfile in the root of the repo to see next dependencies to fetch?

Correct.
