### ISSUE TITLE
Which is the preferred way of using Carthage?

### ISSUE THREAD

**Issue by onmyway133** [Carthage/Carthage#1049]
Hi, I 've been using Cocoapods for a while. I like the simple approach of Carthage, however, with adding frameworks into `Link Binaries With Libraries`, I can't see the framework source

I'm reading https://robots.thoughtbot.com/creating-your-first-ios-framework in which they use the `workspace` approach, and add each framework as a project into this workspace. This way I can see the framework source as well as building it. Is this OK?

**Comment by mdiep** [comment]
Yup, that's a supported and common workflow.
