### ISSUE TITLE
Parse error: unexpected trailing characters in line: github “matthewpalmer/Locksmith”

### ISSUE THREAD

**Issue by ZHONGHuanGit** [Carthage/Carthage#1050]
when I use "carthage update" in command tool, it show me following:
Parse error: unexpected trailing characters in line: github “matthewpalmer/Locksmith”
I don't know why it can't understand my meanings, why it parse error.
My computer system is EI Capitan
Xcode version is 7.2

**Comment by ikesyo** [comment]
`“` and `”` are not valid characters for Cartfile. Please use `"`.
