### ISSUE TITLE
Appstore Submission Error with most recent version of Carthage 0.11

### ISSUE THREAD

**Issue by rroy1590** [Carthage/Carthage#1052]
Hi we are experiencing problems submitting to the App Store using Carthage frameworks. The upload process complains about invalid architectures. I was under the impression that the `copy-frameworks` script removes the simulator builds from the `.framework` files.

To get around this issue we manually performed the steps outlined [here](http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/#n27) and then have added a new run script phase before the `copy-frameworks` phase.

This issue first appeared for us this past week after updating to Xcode 7.2.

**Comment by calebd** [comment]
@rroy1590 I have submitted many times with 0.11 without any issues.

Are you sure you don't have a separate embed frameworks or copy bundle resources phase that is mistakenly copying the frameworks again? 

Have you looked in an archived app bundle to see where these frameworks are?

**Comment by ikesyo** [comment]
As @calebd  answered, `copy-frameworks` command should work correctly.

Closing this for now. Feel free to reopen if you have any updates or further information!
