### ISSUE TITLE
No shared schemes found when running carthage build --no-skip-current

### ISSUE THREAD

**Issue by pedromancheno** [Carthage/Carthage#1058]
I forked XLPagerTabStrip project to make it Carthage compatible, at https://github.com/pedromancheno/XLPagerTabStrip

I marked the only scheme as Shared then I ran `carthage build --no-skip-current` I get the following output:

```
*** xcodebuild output can be found in /var/folders/xp/t_46hvf51jq41rb0xx3cwz5c0000gn/T/carthage-xcodebuild.aKvPL6.log
*** Skipped building XLPagerTabStrip due to the error:
Dependency "XLPagerTabStrip" has no shared framework schemes
```

I ran `xcodebuild -scheme XLPagerTabStrip build` and the project build without problems

Am I missing something here?

Thanks!

(The latest commit in master show the changes to the Scheme Shared)

**Comment by ikesyo** [comment]
What you shared is a scheme for an application target (`XLPagerTabStrip.app`). As the error message says, there is no framework schemes. You should create a new dynamic framework target (maybe `XLPagerTabStrip.framework`) and share a scheme for the target.

https://github.com/pedromancheno/XLPagerTabStrip/commit/3b4d413761e52ccf7d45b5159f3ec59866abb89c#diff-68f4f9dd4678f8eb16eb6fa75d940b85R18

**Comment by pedromancheno** [comment]
Thanks! That was not clear to me. =)
