### ISSUE TITLE
Could not read architectures for <Framework>

### ISSUE THREAD

**Issue by AndrewSB** [Carthage/Carthage#1059]
Hey! Getting an error (Invalid architecture: Could not read architectures from <framework in derived data>) on my build phase `copy-frameworks` with one [framework](https://github.com/ParsePlatform/ParseFacebookUtils-iOS). I'm sure the problem must be that right now I'm not using Carthage to build the framework (waiting on https://github.com/ParsePlatform/ParseFacebookUtils-iOS/issues/21) so I've been building it manually through their xcodeproj and then dragging it into `Carthage/Build/iOS`.

Any way I can remove the error/ build the framework differently to have the architectures properly shown for Carthage?

**Comment by ikesyo** [comment]
Carthage expects a universal framework (supports both simulator and device) for `copy-frameworks` command. Looks like the framework you placed will not be universal. If you do that operation, you should create a universal one by yourself using `lipo` command.
