### ISSUE TITLE
`carthage version` should return either the SHA that it was compiled with, or the git tag version

### ISSUE THREAD

**Issue by younata** [Carthage/Carthage#1060]
I might end up making a pull to do this, but leaving this issue in case someone else with more free time than I wants to take it on.

The basic idea is:

`carthage version` should return either the SHA that it was compiled at (e.g. at the current master, this would be `a8cf57478166165d75bdb0d62f9b61f6ab7ee904`), or the tag version that the SHA corresponds with (e.g. instead of `38cafc2b60df1d4a6d22cd26bdad865d46012414`, it would return `0.11`).

**Comment by Ashton-W** [comment]
Should be closed by #1114
