### ISSUE TITLE
tvOS Apps using frameworks via Carthage has issue on iTunesConnect

### ISSUE THREAD

**Issue by toshi0383** [Carthage/Carthage#1061]
I'm struggling uploading tvOS app to iTC.🙃 Please help.

1. It turns out that upload fails if I set `carthage copy-frameworks` script phase.
   <img width="582" alt="screen shot 2016-01-23 at 21 17 20" src="https://cloud.githubusercontent.com/assets/6007952/12530111/be5f86aa-c216-11e5-9d2b-00ee2c6bccf7.png">

   I removed it, then uploading is successfully. I'm using Xcode Organizer.
   <img width="586" alt="screen shot 2016-01-23 at 21 01 32" src="https://cloud.githubusercontent.com/assets/6007952/12530057/8acc3a42-c214-11e5-8c0f-81f6291ec103.png">

   Frameworks are imported at "Linked Frameworks and Libraries" . I have both FRAMEWORK_SEARCH_PATHS and LIBRARY_SEARCH_PATHS correctly set: `$(PROJECT_DIR)/Carthage/Build/tvOS` (or whereever the frameworks are located at).
   BTW, this is what Organizer looks like when uploading.
   <img width="581" alt="screen shot 2016-01-23 at 21 08 12" src="https://cloud.githubusercontent.com/assets/6007952/12530089/c15b1f0a-c215-11e5-8c01-7cc0f8c44814.png">

2. Then now, I got this error on iTunesConnect. There is no further log, so I don't even know what that really means. Without using any frameworks via Carthage, looks like it's okay (at build 0.1.13)
<img width="962" alt="screen shot 2016-01-23 at 20 29 05" src="https://cloud.githubusercontent.com/assets/6007952/12530054/3e959ff6-c214-11e5-946d-a780ebe78774.png">

Anyone has clue ?

**Comment by ikesyo** [comment]
What is the version of carthage you are using?

**Comment by toshi0383** [comment]
I'm using 0.11.0

**Comment by NachoSoto** [comment]
Is this `APIKit.framework` that you're using built by you or did you download it precompiled? It's possible that it got built with an older version of `Carthage` that didn't include the symbol maps.

**Comment by toshi0383** [comment]
You are right, that `APIKit.framework` is prebuilt in other project and I just copied only `APIKit.framework`, not symbol maps.

I `carthage update` from own Cartfile, then it's finally looking good on iTC.

Thank you guys so much !

**Comment by NachoSoto** [comment]
No problem, glad we could help!
