### ISSUE TITLE
`carthage update` fails with "Parse error: expected submodule commit SHA in ls-tree output:"

### ISSUE THREAD

**Issue by exalted** [Carthage/Carthage#1063]
`carthage version`: `0.11.0` (installed via `brew`).

Looking at #135 first, below I wanted to list out my current status...

`git status` outputs:

```
On branch whatever
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

    modified:   ../README.md
    new file:   ../script/bootstrap
    new file:   Cartfile

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    Cartfile.resolved
```

`git submodule` outputs:

```
 885b3aca758383524070b5252ec734d15b909fdf ../lib/KYCircularProgress (0.5.1-1-g885b3ac)
 7e7b24be9c049611e68364a8090ff1142f006c71 ../lib/PFGridView (heads/master)
 524b5815e740a3e3e511d7fd342c351d226b5fd2 ../lib/PTDownloadManager (remotes/origin/HEAD)
 3a6461b8ab37d38aba750e4081ee3cd0cfe36008 ../lib/PTShowcaseViewController (remotes/origin/HEAD)
 b14a4906b0ab879103d9a4f3a7e11e8ec9389d0b ../lib/PdfReportKit (remotes/origin/HEAD)
```

`.git/config` contains:

```
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
    ignorecase = true
    precomposeunicode = false
[remote "origin"]
    url = https://github.com/user/repo.git
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
    remote = origin
    merge = refs/heads/master
[submodule "lib/PTShowcaseViewController"]
    url = https://github.com/exalted/PTShowcaseViewController.git
[submodule "lib/PTDownloadManager"]
    url = https://github.com/exalted/PTDownloadManager.git
[submodule "lib/PdfReportKit"]
    url = https://github.com/Apex-net/PdfReportKit.git
[submodule "lib/KYCircularProgress"]
    url = https://github.com/kentya6/KYCircularProgress
[submodule "lib/PFGridView"]
    url = https://github.com/Apex-net/pf-gridview.git
```

I run `carthage update` in a subdirectory (i.e., `src/`) that contains `Cartfile`, although git root is `../` which results to this error message:

```
*** Fetching RSBarcodes_Swift
Parse error: expected submodule commit SHA in ls-tree output: 
```

At this point I tried a longer version (`carthage update --verbose --no-build --use-submodules`) mentioned in #135 (without actually caring how/why is it better):

```
*** Fetching RSBarcodes_Swift
Parse error: expected submodule commit SHA in ls-tree output: 
```

At this point I have no idea how to fix this.

Any ideas?

Thank you.

**Comment by brentleyjones** [comment]
I think the issue is you are running carthage from a subdirectory. I've run into this before and I'm not sure if Carthage can handle being in a subdirectory. I believe this is a bug.

**Comment by mdiep** [comment]
Can you try with 0.12? The error here has been improved.

**Comment by brentleyjones** [comment]
For myself, on 0.12, I still have this issue:

I run carthage from **src/ios**, I have a submodule that in .git/config is listed as such:

**Comment by brentleyjones** [comment]
For myself, on 0.12, I still have this issue:

I run carthage from **src/ios**, I have a submodule that in .git/config is listed as such:
```
[submodule "src/ios/exampleSubmodule"]
        url = https://git.company.com/git/example.git
```

And the error from carthage is:
```
Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD src/ios/exampleSubmodule) but encountered:
```

But if I instead run the command:
```
git ls-tree -z HEAD exampleSubmodule
```

I get the response:
```
160000 commit cbab1df4f24d3cfa8b1b53a1239746b8fe04511d	exampleSubmodule% 
```

Because, at the directory that I'm running carthage, it's ** exampleSubmodule**, not ** src/ios/exampleSubmodule**.

**Comment by brentleyjones** [comment]
It seems like carthage should run the `git ls-tree -z HEAD` command from the directory that `.git` is in (in this case, for my above example, **../../**).

**Comment by TofPlay** [comment]
Same issue here with Carthage 0.16.2 
`Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD Carthage/Checkouts/Alamofire) but encountered:`
What should I do to fix it?

**Comment by exalted** [comment]
I am going to close this, but please feel free to re-open if interested.
