### ISSUE TITLE
Carthage finds another package in the module cache

### ISSUE THREAD

**Issue by kennebecstars** [Carthage/Carthage#1064]
I have added Carthage to a second application build directory and my cart file is the same. On the new build, I get this error that the modules conflict in precompiling the headers. What am I missing?

error: PCH was compiled with module cache path '.../appA/Carthage/Carthage/Checkouts/ocmock/Source/dd/ModuleCache/2FY8Q70TX76AX', but the path is currently '.../appB/Carthage/Carthage/Checkouts/ocmock/Source/dd/ModuleCache/2FY8Q70TX76AX'

**Comment by mdiep** [comment]
Did you copy any of the files? I would try deleting `Carthage/Build` and rebuilding with Carthage.

**Comment by kennebecstars** [comment]
I started the build of "appB" by creating a new Carthage folder with the same cartfile, that's all. There is a hitch, okay I'll come clean! 8-]  I had found a bug in a package I wanted to use in Carthage, so I split the build, purposefully, so that after the 'carthage update', I could copy the version of that package's fix (not yet released as a new version) and then manually ran 'carthage build'. 

The good news is that even with the module clashing above, if I add the framework and framework.dSYM folders from the original Carthage/Build area, and then updating FRAMEWORK_SEARCH_PATHS, I was able to run.

I'll try redoing the build in the new area.

Since, for this effort, I'm mostly using Carthage to save me time gathering test-oriented packages like specta, KIF, OCmock, maybe I would be better off using a single Carthage build folder and linking to that one folder, but as a rule, my rule about application product builds is to be self-contained, even for test; maybe *especially* even for test.

**Comment by kennebecstars** [comment]
I was able to finally test this using the package release version I needed so I didn't have to stop carthage from updating and then going straight to the build phase. The clean Carthage build worked fine.

**Comment by kennebecstars** [comment]
I was able to update and build, but copy-frameworks does not copy the framework folders I have added as inputs on my unit test target, it only copies the .dSYM inputs.

**Comment by ikesyo** [comment]
> but copy-frameworks does not copy the framework folders I have added as inputs on my unit test target, it only copies the .dSYM inputs.

Closing this since you filed the dedicated issue: #1070
