### ISSUE TITLE
No such module 'CarthageKit' but do find ReactiveTask

### ISSUE THREAD

**Issue by puttin** [Carthage/Carthage#1065]
```swift
import ReactiveTask
import CarthageKit
```

will generate `No such module 'CarthageKit'` error

Cartfile:
```
github "Carthage/Carthage"
```

Cartfile.resolved:
```
github "thoughtbot/Argo" "v2.1.0"
github "jdhealy/PrettyColors" "v3.0.0"
github "antitypical/Result" "0.6.0-beta.5"
github "Carthage/Commandant" "0.7.0-beta.1"
github "ReactiveCocoa/ReactiveCocoa" "v4.0.0-alpha.3"
github "Carthage/ReactiveTask" "0.8.0-beta.1"
github "Carthage/Carthage" "0.11"
```

Already turned off code sign by "Don't Code Sign"

I only dragged `CarthageKit.framework` to `Embedded Binaries`

**Comment by NachoSoto** [comment]
Make sure you have `$(PROJECT_DIR)/Carthage/Build/iOS` in `FRAMEWORK_SEARCH_PATHS`.

**Comment by puttin** [comment]
Actually it's for Mac, So it have `$(PROJECT_DIR)/Carthage/Build/Mac`

**Comment by puttin** [comment]
The strange thing is that I can `import ReactiveTask` which is a framework we know inside CarthageKit

**Comment by puttin** [comment]
After `carthage bootstrap --platform Mac --verbose --no-use-binaries` and all `BUILD SUCCEEDED`.

I can `import CarthageKit` correctly now.

**Comment by puttin** [comment]
So is it the binary problem?

**Comment by mdiep** [comment]
Possibly. We may need to revisit how the zip is created in the `Makefile`.

**Comment by jeffreybergier** [comment]
I'm not sure if it helps. But I also ran into this exact issue with Xcode 7.2.1 (7C1002) and carthage 0.11.0. Using carthage bootstrap --platform Mac resulted in this issue. Using bootstrap --platform Mac --no-use-binaries resolved this issue.

Let me know if there is any way I can help with troubleshooting.
