### ISSUE TITLE
carthage-fish-completion file missing

### ISSUE THREAD

**Issue by SandyChapman** [Carthage/Carthage#1069]
I just installed the 0.11 pkg file and the `carthage-fish-completion` file is missing from the install:

    $> ls /Library/Frameworks/CarthageKit.framework/Versions/A/Scripts/
    carthage-bash-completion carthage-zsh-completion

**Comment by ikesyo** [comment]
fish completion script is added after 0.11 release by #962. So that would be included in next 0.12 release. Closing this.
