### ISSUE TITLE
No Shared Scheme but carthage build on the framework builds

### ISSUE THREAD

**Issue by teemobean** [Carthage/Carthage#1075]
I have a iOS framework (https://github.com/teemobean/RestSwiftly/) that I've built to support Carthage. I "shared" the default scheme that Xcode created. When I do "carthage build --no-skip-current" its able to build an iOS framework (under Carthage/Build/iOS/RestSwiftly.framework).

I have another app where I'm trying to use this Carthage framework. When I run "carthage update --platform iOS" it reports that RestSwiftly has no shared framework schemes for iOS.

My projects are really simple - the framework has one source file and my app has nothing added yet.

I'm using the latest Xcode (7.2) and Carthage 0.11 (from home-brew).

**Comment by mdiep** [comment]
Does the version in your app's `Cartfile.resolved` match the version where you're using `--no-skip-current`?

**Comment by teemobean** [comment]
Yes it should be. My framework has 6 commits and the tag is at head.
But actually I noticed something interesting - if I load the framework (RestSwiftly) that Carthage pulled, there are no schemes in that project. Is that the issue?

**Comment by ikesyo** [comment]
Your scheme checked in is not a shared one, that is in `xcuserdatad`: https://github.com/teemobean/RestSwiftly/tree/v0.1-alpha/RestSwiftly.xcodeproj/xcuserdata/tim.xcuserdatad/xcschemes

Shared schemes should be in `.xcodeproj/xcshareddata/xcschemes`. You should check the checkbox of “Shared” for your desired scheme and the shared scheme would be created by Xcode.

<img width="1502" alt="2016-01-31 16 00 51" src="https://cloud.githubusercontent.com/assets/909674/12700788/22c1b7ee-c834-11e5-8ea0-f3346741964d.png">

**Comment by teemobean** [comment]
Thank you! That was the issue. I had created the shared scheme but for some reason Xcode wasn't adding the `.xcodeproj/xcshareddata/xcschemes` files. Adding it, pushing it, and creating a new release - it all works now. Thank you so much!
