### ISSUE TITLE
copy-frameworks does not copy the internal modules directory

### ISSUE THREAD

**Issue by shantanubharadwaj** [Carthage/Carthage#1076]
Am building a framework(ABC) where I have included few other 3rd party swift frameworks. Upon building it with carthage, the 3rd party frameworks have a **Modules** directory which has the .modulemap file. When we include the frameworks into our ABC's target, it finds the .modulemap file. But when we build ABC, the copy-frameworks script copies the framework to its designated path, but skips the Modules directory inside the 3rd party frameworks. This is causing as issue if we want to distribute our ABC as it fails to find the swift frameworks due to the missing .modulemap file.

**Comment by ikesyo** [comment]
The `Modules` directory is needed for build time, not runtime. There is no need to copy the directory in `carthage copy-fraemworks`. Closing.
