### ISSUE TITLE
Error build robrix/Either using Carthage 0.12 (0.11 works)

### ISSUE THREAD

**Issue by siemensikkema** [Carthage/Carthage#1080]
Using a Cartfile with only `github "robrix/Either"` I get the following output. 
```
> carthage update --platform iOS --no-use-binaries
*** Fetching Either
*** Fetching Prelude
Could not pick a version for github "robrix/Prelude", due to mutually incompatible requirements:
	"a2c66881a5df6ccdb46f16e39523982c05e565c8"
	"master"
```
Currently master is at the commit with the above hash so both point to the same commit.

**Comment by erichoracek** [comment]
I'm seeing similar behavior as well with different levels of verbosity in SHAs in `0.12`:
```
Could not pick a version for github "specta/specta", due to mutually incompatible requirements:
	"c4bde15c321ef83e5a94c5a5d9dd7ac2f5c05b07"
	"c4bde15"
```

**Comment by kballard** [comment]
I'm seeing the same issue in my own project:

```
Could not pick a version for github "postmates/PMJSON", due to mutually incompatible requirements:
	"9862ec7333155cfdcc0855c107f2e9c28a0102a5"
	"master"
```

postmates/PMJSON is a dependency of a single project (which declares it as depending on `"master"` in Cartfile). `carthage update` works fine in that project, but in my parent project that depends on it, I get this error. The only place the SHA exists is in the Cartfile.resolved (and it's the same in both the parent project and the child project).

**Comment by kballard** [comment]
If I update the Cartfile of the middle project to specify the SHA instead of `"master"` the error goes away, but that's really annoying.

**Comment by kevinmlong** [comment]
I just updated to Carthage 0.12 and having the same issues

**Comment by ikesyo** [comment]
This might be the same as #765?

**Comment by kballard** [comment]
It does sound like the same issue.
