### ISSUE TITLE
v0.12 fails during bootstrapping with --use-ssh flag

### ISSUE THREAD

**Issue by hyperspacemark** [Carthage/Carthage#1082]
I have a few dependencies in my Cartfile that are located on Github Enterprise. HTTPS access is only possible when on our company VPN. 

For this reason I bootstrap my project with `carthage bootstrap --platform iOS --use-ssh` when not on the VPN. In Carthage 0.11 this worked as expected; dependencies are checked out and fetched over SSH.

When running `carthage bootstrap --platform ios --use-ssh` with 0.12, it fails with
```sh
*** Fetching GZIP

A shell task failed with exit code 128:
fatal: unable to access 'https://github.*****.com/*****/GZIP.git/': The requested URL returned error: 403
```

Strangely, running `carthage checkout --use-ssh` completes without error.

**Comment by mdiep** [comment]
Are you still seeing this? What do `carthage fetch` do? What's the output of `carthage checkout`?

**Comment by hyperspacemark** [comment]
I was seeing this in versions 0.12 and 0.13 but it doesn't seem to be happening on 0.14. Not sure what changed, but if you have a rough idea of where this could've gone wrong, I'd be happy to submit a PR with a regression test to make sure that the SSH flag is getting propagated correctly.

**Comment by mdiep** [comment]
I'm not sure what would have fixed it, but I'm happy to hear that it's working now!
