### ISSUE TITLE
carthage build --no-use-binaries fails on 0.12

### ISSUE THREAD

**Issue by ratkins** [Carthage/Carthage#1084]
````
$ carthage build --verbose --platform iOS --no-use-binaries
Unrecognized arguments: --no-use-binaries
````

This works in 0.11. If this is a deliberate change, it's not mentioned in the [release notes](https://github.com/Carthage/Carthage/releases/tag/0.12).

**Comment by ikesyo** [comment]
`--no-use-binaries` is not a valid option for `build` command since before. That is for `update`, `bootstrap` and `checkout` commands. Those invalid options which are not parsed by a command now outputs the errors.
