### ISSUE TITLE
github shortcut in Cardfile do not use given url

### ISSUE THREAD

**Issue by karstenlitsche** [Carthage/Carthage#1087]
In case 1 below carthage downloads from an unexpected url (via https) instead of using my url (via ssh).

carthage version: 0.12.0

(1 - failed unexpected because of port limitations in my company)
Cardfile:
github "ssh://git@github.com/AliSoftware/OHHTTPStubs.git" ~> 4.7.0
Result:
*** Fetching OHHTTPStubs
A shell task failed with exit code 128:
fatal: unable to access 'https://github.com/AliSoftware/OHHTTPStubs.git/': Failed to connect to github.com port 443: Operation timed out

(2 - success as expected)
Cardfile:
git "ssh://git@github.com/AliSoftware/OHHTTPStubs.git" ~> 4.7.0
Result:
*** Fetching OHHTTPStubs
*** Checking out OHHTTPStubs at "4.7.0"
*** Building scheme "OHHTTPStubs iOS Framework" in OHHTTPStubs.xcworkspace
*** Building scheme "OHHTTPStubs" in OHHTTPStubsDemo.xcworkspace

**Comment by ikesyo** [comment]
Could you please trying to use `--use-ssh` option?

**Comment by ikesyo** [comment]
IIRC `"ssh://git@github.com/AliSoftware/OHHTTPStubs.git"` is not a expected input for `github` origin.

**Comment by karstenlitsche** [comment]
Ah, cool. The parameter "--use-ssh" works for me, but it changes all defined framework urls. Therefore it's only a workaround. Not?

**Comment by mdiep** [comment]
This is as-designed. The choice of SSH or HTTPS is something that the end user makes—not the framework writer.

**Comment by karstenlitsche** [comment]
Ok I understand your point.
But what if own git-server only supports one solution and github (or another git-server) is only reachable about the other one. A carthage update may be impossible then. Isn't it better to use the configuration the framework developer choosed in that case? Yeah I know it's hypothetical.

**Comment by mdiep** [comment]
`git` URLs are passed through unchanged. The logic I mentioned only applies to `github` URLs.
