### ISSUE TITLE
Sparse Checkout

### ISSUE THREAD

**Issue by roberte3** [Carthage/Carthage#1094]
I'm working on a project that consists of a Project with a subProject inside of a folder on git. 

Folder Structure is like this: 
ProjectA/ProjectB/ProjectBFramework 

I'm trying to configure a carthage script to grab ProjectB and build it. 

Looking around I'm finding something called Sparse Checkout in git that might do it. Does anyone have any experience making it work with Carthage?

**Comment by jeeftor** [comment]
Carthage checks out into the `Carthage` directory - you could do a submodule checkout perhaps to do this for you - but i'm a little confused about your question.

**Comment by ikesyo** [comment]
Closing this for now.
