### ISSUE TITLE
TTTAttributedLabel shared framework scheme not found

### ISSUE THREAD

**Issue by mathiasnagler** [Carthage/Carthage#1098]
I am trying to integrate `TTTAttributedLabel` into my project using Carthage at version `0.12.0` but unfortunately Carthage does not find the shared framework scheme. There definitely is a shared framework scheme, so I don't know why this is happening.

Here's the issue in the `TTTAttributedLabel` project: https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/642

Also, it seems that carthage should build shared framework schemes from all `.xcodeproj` since version `0.12.0` so this should work I think.

**Comment by ikesyo** [comment]
We are filtering out `Carthage` directory by the changes of #892, and the `TTTAttributedLabel.xcodeproj` is in `Carthage` dir. We should ignore `Carthage/Checkouts` directory instead.
