### ISSUE TITLE
Broke nested dependencies

### ISSUE THREAD

**Issue by delannoyk** [Carthage/Carthage#1102]
Hi,
After upgrading to 0.12, I found that I couldn't update my dependencies anymore.
I'm using one of my frameworks as a dependency for my project and when I run `carthage update` it won't even clone repo.

Here is my Cartfile:
```
github "delannoyk/SoundcloudSDK"
```
This framework has nested dependencies to UICKeychainStore and OnePassword-App-Extension (so the repo has its own `Cartfile`).

With 0.11, it works great. Since 0.12, it exits with the following result:
```
*** Fetching SoundcloudSDK
*** Fetching onepassword-extension
*** Fetching UICKeyChainStore
Could not pick a version for github "AgileBits/onepassword-extension", due to mutually incompatible requirements:
	"22d595de49f6f2ccd18d0087ef80a4b0c9311c13"
	"add-framework-support"
```

The thing is, I'm not referencing any commit and the Cartfile, I'm just referencing the branch `add-framework-support`.

Do you have any idea what goes wrong?

**Comment by ikesyo** [comment]
This is a dupulicate of #1080. This is already fixed in `master` and that will be included in a next release.

Sorry for the inconvenience. :bow:

**Comment by delannoyk** [comment]
Oh ok, didn't see that one. Thanks!
