### ISSUE TITLE
Why are sub-frameworks being added ?

### ISSUE THREAD

**Issue by memmons-ntst** [Carthage/Carthage#1105]
I have a framework, FrameworkA. It has a dependency on Argo. So, in the FrameworkA project, its cartfile has that dependency. However, the carthage copy script is not added to the build phases. If I build FrameworkA from its project, it builds correctly -- there are no frameworks embedded in the FrameWorkA.framework. However, if I add FrameworkA as a dependency in another project -- TestProject -- when I rebuild the frameworks via `carthage update` and look in the Carthage/Build/iOS directory, FrameworkA.framework now has Argo as a sub-framework.

Is there some step I am missing here? Why is a sub-framework being added to FrameworkA?

**Comment by NachoSoto** [comment]
> -- when I rebuild the frameworks via carthage update and look in the Carthage/Build/iOS directory, FrameworkA.framework now has Argo as a sub-framework.

That's precisely because it's marked as a "public" dependency: it's in `FrameworkA`'s `Cartfile`. If you want to "hide" this detail, you'll want to put `Argo` in [`Cartfile.private`](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfileprivate).

**Comment by memmons-ntst** [comment]
@NachoSoto Thanks for the info! Completely missed that feature in carthage.
