### ISSUE TITLE
Carthage does not build main framework from project

### ISSUE THREAD

**Issue by srikanth-vm** [Carthage/Carthage#1106]
Lets say 2 Frameworks A & B are created. Inside framework A, using Cartthage framework B is included. Now when I include framework A in a project using carthage, it checks out both of them but only builds B.

What should I do to get framework A also built ?

Cartfile for framework A:

    git "http://location/to/fwk/b" "branch"

Cartfile for Project:

    git "http://location/to/fwk/a" "branch"

Once I run `carthage update` from the project location, I can see from the logs that both frameworks are checked out but in the build location I can only see Framework B.
    
Also tried adding framework B to Cartfile.private but it didnt help

**Comment by NachoSoto** [comment]
My guess is that framework `A` doesn't contain any scheme to build. Could you share more details about this project?

**Comment by virus001** [comment]
Open project framework A and select shared scheme from Manage scheme. Then run the command carthage update.
