### ISSUE TITLE
Dependency "xxx" has no shared framework schemes

### ISSUE THREAD

**Issue by jalakoo** [Carthage/Carthage#1109]
Running “carthage update” on a test project results in the following error:

`
Dependency “(framework name)” has no shared framework schemes
`

Cartfile is pointing to a private repo (for testing) using 

`
git "(private repo address)" == (latest tag version)
`

HAVE CONSULTED FOLLOWING SIMILAR ISSUES
https://github.com/Carthage/Carthage/issues/1075
https://github.com/Carthage/Carthage/issues/691
https://github.com/Carthage/Carthage/issues/1058
https://github.com/Carthage/Carthage/issues/387
https://github.com/Carthage/Carthage/issues/299
http://stackoverflow.com/questions/35054788/carthage-no-shared-framework-schemes-for-ios-platform-for-my-own-framework

HAVE ATTEMPTED:
- Using a precompiled framework created on own and using “carthage build —-no-skip-current” with source files. (successful)
- “carthage build —no-skip-current” above did not produce any errors.
- Using a normal project, not a workspace
- Framework building project’s scheme: Shared option checked ON
- Test Project’s target scheme: Shared option also checked ON
- cartfile.resolved has the CORRECT matching version 
- Dynamic framework was created (not application or static library)
- Rerunning “carthage update” multiple times produced no change
- “rm -rf ~/Library/Caches/org.carthage.CarthageKit” and re-attempting “carthage update” produced no change

VERSIONS
Carthage version: 0.13.0
Xcode version: 7.2
Git version: 2.6.4

**Comment by NachoSoto** [comment]
> Framework building project’s scheme: Shared option checked ON

Could you provide some more information about the scheme and the target?

**Comment by weissazool** [comment]
I actually just ran into a similar thing while trying to add Carthage to a project. Are you certain that the shared schemes (something like `.xcodeproj/xcshareddata/xcschemes`) are checked into your repository?

**Comment by jalakoo** [comment]
@weissazool Yup, the test project's shared scheme is in the repo [here](https://github.com/jalakoo/test/tree/master/UIKitCatalog.xcodeproj/xcshareddata/xcschemes).  Shared schemes are also in the framework's building project's repo (private).  I believe this is an issue with the precompiled framework and not the test project.  

@NachoSoto Framework project's scheme is for Release with no arguments, default options and set to shared. Target is a Cocoa Touch Framework targeting arm64, armv7, armv7s with Build Active Arch set to No. Anything else that might help?

**Comment by ikesyo** [comment]
The shared `UIKitCatalog` scheme's target is an app, not a framework.

**Comment by jalakoo** [comment]
@ikesyo I'm not following, why does the test project's target need to be a framework?

It makes sense that the builder project's target is a framework (which it is, but no link provided because it's in a private repo)

**Comment by ikesyo** [comment]
Ah, https://github.com/jalakoo/test is not a framework project? Sorry for the misunderstanding. If so there is no need to share the scheme of test project's app.

If yor are refering to https://github.com/jalakoo/test, which is in the `Cartfile` of that test project, it seems to me that have no any shared framework schemes.

**Comment by jbarros35** [comment]
So thats it? no solution provided?

**Comment by besabestin** [comment]
What happened to this?

**Comment by mdiep** [comment]
> What happened to this?

One user had a configuration issue. Once it was diagnosed, the ticket was closed.

**Comment by besabestin** [comment]
> > What happened to this?
> 
> One user had a configuration issue. Once it was diagnosed, the ticket was closed.

Can you also probably look at my SO post please? https://stackoverflow.com/questions/53228649/is-it-possible-to-distribute-binary-ios-framework-using-carthage

**Comment by ChungMai** [comment]
I fought with this error. I realized that default "Shared option checked ON" (- when you create project, Shared option checked ON),  is not created the shared schemes in  `.xcodeproj/xcshareddata/xcschemes`

You must deleted existing scheme in Manage Scheme and add agains.

**Comment by francofadini** [comment]
ChungMai solution works for me. But only unchecking and checking again was necessary
