### ISSUE TITLE
Repo with no Xcode schema just the framework

### ISSUE THREAD

**Issue by ptaneja** [Carthage/Carthage#1111]
Hello,

I want to setup a repo with just .framework file and no xcode schema. one of my user wants to include the framework with the help of carthage in his app. I tried including the framework file in git releases but carthage only checkouts the framework but it doesn't copy in Carthage/Build folder and doesn't link with the project file.

Would it be possible?

**Comment by mdiep** [comment]
We only support distribution of binary `.framework` files through GitHub releases. You'd need to figure out why that's not working.

**Comment by ptaneja** [comment]
What if there is only .Framework file on GithHub and no code base?

**Comment by mdiep** [comment]
If the repository is empty, that should still work as long as the end user doesn't use the `--no-use-binaries` flag.

**Comment by ptaneja** [comment]
Well, Repo is not empty, it has a Framework file and no code base. Because we don't share our source code but we ourselves deliver the end product as .framework file.

Will carthage checkout the Framework file from GitHub into Carthage/Checkout folder and then copy it to the Carthage/Build folder and then link it to the project?

**Comment by mdiep** [comment]
Carthage will only take binary `framework` files from GitHub releases.
