### ISSUE TITLE
Guidance on building only some dependencies

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#1117]
Carthage Build says

```
[[]]
	the dependency names to build
```

Exactly what name am i supposed to use?  The name of the framework?  The name of the github repo?  The name of the scheme?

My cart file is:

    #DataManager
    git "git://mustache.COMPANY.org/otto/datamanager.git" "develop"
    #MapData
    git "git://mustache.COMPANY.org/otto/ottomapdata.git" "master"
    #JSONParsing
    github "SwiftyJSON/SwiftyJSON"

I've tried

```bash
carthage build SwiftyJSON
carthage build SwiftyJSON/SwiftyJSON
carthage build [SwiftyJSON]
```

And it always seem to also build all the other dependencies while its at it.

**Comment by ikesyo** [comment]
You can use the `carthage build SwiftyJSON` form, but this does not work in 0.13 and already fixed in `master`. See also #1107 and #1108.
