### ISSUE TITLE
Error while building for iOS

### ISSUE THREAD

**Issue by flexaddicted** [Carthage/Carthage#1119]
Following the section "If you're building for iOS, tvOS, or watchOS", I added a script file on my Build Phases like the following:

    $(PROJECT_DIR)/External/Carthage/Build/iOS/Kingfisher.framework
    $(PROJECT_DIR)/External/Carthage/Build/iOS/ObjectMapper.framework

Each time the script run (to export an ipa), I receive the following:

The following build commands failed:

    PhaseScriptExecution Carthage\ Run\ Script PATH_TO_BUILD/Script-AEDC50FE1C4E5AF900102515.sh

I'm running the latest version of Carthage. In a previous version (0.8), the script was running correctly.

Any clue on this?

**Comment by ikesyo** [comment]
Could you please follow this comment? https://github.com/Carthage/Carthage/issues/1079#issuecomment-178575036

**Comment by flexaddicted** [comment]
Thanks.
