### ISSUE TITLE
Forked Carthage, Carthage Can't Compile Its Dependencies

### ISSUE THREAD

**Issue by murdocdv** [Carthage/Carthage#1123]
- I installed Carthage 0.14.0
- ForkedCarthage and cloned. 
- Ran "carthage update"

Expected: Carthage compiled all dependencies
Actual: Compilation failed with "ld: '/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE) or obtain an updated library from the vendor for architecture arm64"

I've attached the whole build log.

[carthage-xcodebuild.qVQ0sA.log.zip](https://github.com/Carthage/Carthage/files/128648/carthage-xcodebuild.qVQ0sA.log.zip)

**Comment by ikesyo** [comment]
That is an known issue: https://github.com/Quick/Nimble/issues/213 and https://github.com/Quick/Quick/issues/422

Carthage uses a workspace to integrate its dependencies, not use built binaries in `Carthage/Build`. So you don't need to build the dependencies by Carthage, and it would be okay if you use `carthage update --no-build` and open `Carthage.xcworkspace`.

**Comment by murdocdv** [comment]
@ikesyo thanks!
