### ISSUE TITLE
The order of resolving dependencies

### ISSUE THREAD

**Issue by uny** [Carthage/Carthage#1128]
* Carthage: 0.14.0
* Cartfile:
```
github "A/A"
github "B/B"
```

* "A/A" itself uses "B/B".
* First build after deleting carthage cache (`~/Library/Caches/org.carthage.CarthageKit`).

-----
Then, `carthage bootstrap` and `carthage build` will build "A/A" before "B/B".
So, when building "A/A", the command will abort with the error:
```
The following build commands failed:
	CompileSwift normal arm64 /path/to/A/AFile.swift
(1 failures)
/path/to/A/AFile.swift:10:8: error: no such module 'B'
A shell task failed with exit code 65:
** BUILD FAILED **
```

-----

Now, we have to 
* `carthage checkout`
* `carthage build B`
* `carthage build`

Is there any better solutions?

**Comment by ikesyo** [comment]
What is the Cartfile of "A/A" and the carthage version you are using?

**Comment by uny** [comment]
The Cartfile of "A/A" is below:
```
github "B/B"
```

Actrually, "B/B" is "kishikawakatsumi/KeychainAccess" and "A/A" is a private framework on Github Enterprise.
The Cartfile of the application project is below:
```
github "kishikawakatsumi/KeychainAccess"
gihtub "https://ghe.xxx.xxx/rxxx/AXXAuth"
```

The carthage version is `0.14.0`.

There is no difference (all failed) between:
* `carthage bootstrap` / `carthage build`
* `--no-use-binaries` / none
* `--platform iOS` / none

**Comment by ikesyo** [comment]
What happens if you remove `github "kishikawakatsumi/KeychainAccess"` from Cartfile of your application project?

**Comment by uny** [comment]
Same error.

1. Remove `github "kishikawakatsumi/KeychainAccess"` from Cartfile of your application project
2. `carthage update --platform iOS --no-use-binaries`

```
Building scheme "AXXAuth" in AXXAuth.xcodeproj
The following build commands failed:
...
...: error: no such module 'KeychainAccess'
```

**Comment by ikesyo** [comment]
Could you also share your `Cartfile.resolved`?

**Comment by uny** [comment]
Cartfile.resolved of the application project (including `kishikawakatsumi/KeychainAccess`):
```
github "kishikawakatsumi/KeychainAccess" "v2.3.3"
github "https://ghe.xxx.xxx/rxx/AXXAuth" "1.0.2"
``` 

Cartfile.resolved of AXXAuth
```
github "kishikawakatsumi/KeychainAccess" "v2.3.3"
```

**Comment by ikesyo** [comment]
Are you sure that the Cartfile of `AXXAuth` is in the root directory of that repo? If not, Carthage can't detect the file and the repo will be considered having no dependencies.

**Comment by uny** [comment]
Yes, it's in the root directory of the repository.
We can see Cartfile and Cartfile.resolved on the file list on `https://ghe.xxx.xxx/rxx/AXXAuth`.

------
Sorry, after I rebooted my machine this morning, the problem does not happen...
I don't know why, but the issue can be closed.

**Comment by ikesyo** [comment]
> Sorry, after I rebooted my machine this morning, the problem does not happen...
I don't know why, but the issue can be closed.

Oh, it's weird... :astonished: But I'm glad to hear that!

**Comment by uny** [comment]
@ikesyo 
This issue was solved by https://github.com/Carthage/Carthage/commit/be73616a62e7ea925310705b0ccd2336cabb70c9.
Thank you for your help! (and I would like the commit to be released early...)
