### ISSUE TITLE
Notify developers of new releases

### ISSUE THREAD

**Issue by Bogidon** [Carthage/Carthage#1130]
A "breaking change" with the documentation was recently discussed in https://github.com/Carthage/Carthage/pull/1023#issuecomment-184966951. A few weeks ago, there was a change (namely with `copy-frameworks`) that required the docs to be updated for a newer Carthage release.

Unfortunately for me, I was still on an older version of Carthage and when I tried using the directions in the newer docs, my App Store submissions began to fail. It took me a little while before I realized my Carthage was out of date.

We evaluated a few solutions:
1. Add notes in the docs for each "breaking change". @calebd and @hyperspacemark thought the readme should reflect the most recent release and this approach would be unmaintainable. I agree.
2. @calebd suggested creating a `CHANGELOG.md`. Personally, I don't think this improves visibility much more than the releases tab does.
3. I suggested warning developers that new releases are available ala Cocoapods. @mdiep liked that idea. 
![](https://cloud.githubusercontent.com/assets/3252307/13098187/d629e220-d4f5-11e5-92ba-e49bb2b58204.jpg)

Thoughts?

**Comment by Bogidon** [comment]
@ikesyo so you agree? Can I work on a PR?

**Comment by mdiep** [comment]
We'd be very happy to accept a PR that added this. :smile:

**Comment by Bogidon** [comment]
Great. I'll work on it when I get some time
