### ISSUE TITLE
Forking + adding Cartfile (to specify a transient dependency) on Github fork doesn't seem to work

### ISSUE THREAD

**Issue by fatuhoku** [Carthage/Carthage#1132]
[MZFormSheetPresentationController](https://github.com/m1entus/MZFormSheetPresentationController) depends on [MZAppearance](https://github.com/m1entus/MZAppearance). You can see this from the `.podspec`.

But I wanted to use Carthage, of course. It doesn't (at the time of writing) have a `Cartfile`.

So I [created one in my own fork of the project](https://github.com/fatuhoku/MZFormSheetPresentationController/blob/master/Cartfile).

... and I update my `Cartfile` thus:

`github "fatuhoku/MZFormSheetPresentationController"`

... and I go `carthage update MZFormSheetPresentationController --platform iOS`.  I expected it to just all resolve and work (MZAppearance is reportedly Carthage-compatible) but Carthage gives me compile errors:

```
fatal error: 'MZAppearance/MZAppearance.h' file not found
...
fatal error: 'MZAppearance/MZAppearance.h' file not found
```

Why?

**Comment by fatuhoku** [comment]
Issue #917 looks relevant.

**Comment by ikesyo** [comment]
It seems that Carthage support of `MZAppearance` is added in https://github.com/m1entus/MZAppearance/pull/7 and a new release including it is not released. So you should specify a branch or commit hash in your Cartfile as `github "m1entus/MZAppearance" "master"` for now.

**Comment by ikesyo** [comment]
And also, `MZFormSheetPresentationController.xcodeproj` is not correctly set up to use `MZAppearance.framework` in `Carthage/Build` or integrate `MZAppearance.xcodeproj` in `Carthage/Checkouts`.

**Comment by fatuhoku** [comment]
@ikesyo Ah of course — specifying the master branch is pretty important. That probably means neither projects are really ready for Carthage yet. I'll decide whether I want to Carthage-ize them later.
