### ISSUE TITLE
calling update or bootstrap always builds from schemes although a binary framework exists

### ISSUE THREAD

**Issue by ahmednawar** [Carthage/Carthage#1133]
I have this simple test repo https://github.com/ahmednawar/Tunis

I successfully build and archive from my local machine. I push to repo with a public release tag but every time I call `update` or `bootstrap` it checks out the code and builds from XCode schemes although there is a binary framework in the repo. Any ideas what is happening?

**Comment by ikesyo** [comment]
You don't have any GitHub Releases which have a prebuilt binary of `Tunis.framework.zip` created by `carthage archive` command.

**Comment by ahmednawar** [comment]
thanks @ikesyo! 

So maybe I am missing something. But before pushing I call `git tag v1` for instance then I push with the `--tags` option. Is this sufficient or right?

**Comment by ikesyo** [comment]
Could you please check this?

https://help.github.com/articles/about-releases/

**Comment by ahmednawar** [comment]
@ikesyo it worked..sorry I assumed that tags were enough..my bad..thanks for your time
