### ISSUE TITLE
When using Carthage: "Nimble was compiled with optimization - stepping may behave oddly; variables may not be available."

### ISSUE THREAD

**Issue by fatuhoku** [Carthage/Carthage#1135]
https://www.google.co.uk/?q="carthage"+was+compiled+with+optimization+-+stepping+may+behave+oddly%3B+variables+may+not+be+available

How do I prevent optimisation from happening in the build phase for test frameworks?

**Comment by mdiep** [comment]
You can use Carthage's `--configuration` flag to build all frameworks using the Debug configuration. There's not currently a way to do this only for test frameworks.

But that should only affect the innards of Nimble. You should still be able to step through your test code.

**Comment by poolqf** [comment]
> There's not currently a way to do this only for test frameworks

@mdiep can we workaround it by manually doing the line below for each test framework?

`carthage build Nimble --platform iOS --configuration Debug --verbose`

By the output it seems that it is working

```
/usr/bin/xcrun xcodebuild -project /Users/polquintana/XCode/Redbooth/teambox-ios-universal/redbooth-ios-sdk/Carthage/Checkouts/Nimble/Nimble.xcodeproj -scheme Nimble-iOS -configuration Debug -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= clean
....
```
