### ISSUE TITLE
Fetch Dependencies without updating Cartfile.resolved

### ISSUE THREAD

**Issue by sprint84** [Carthage/Carthage#1138]
This is more a question than an issue, but is there a way to fetch and build dependencies without updating them (not changing the Cartfile.resolved)

I guess the equivalent of this in CocoaPods would be ```pod install```, when ```pod update``` actually fetches the newest version.

Sometimes I just want to rebuild the Carthage folder without dealing with possible API changed in the dependencies.

Thanks

**Comment by ikesyo** [comment]
`carthage bootstrap` is what you are looking for, I think. If you just want to rebuild the dependencies, you can use `carthage build` as well (`carthage help` shows the available commands).
