### ISSUE TITLE
Carthage doesn't lipo embedded frameworks together

### ISSUE THREAD

**Issue by BobElDevil** [Carthage/Carthage#1141]
In our project we have to mark our Frameworks with the 'embedded content contains swift' flag, otherwise the unit tests will crash during CI, because xcode does not include the libswift* frameworks in the test bundle. The trouble arises when said framework is set up as a carthage dependency, and then you have a test bundle that uses it in some way. This test bundle needs those libswift frameworks, but it crashes when looking for it. Simulator logs show:
```(dlopen_preflight(/path/to/SomeTests.xctest): Library not loaded: @rpath/libswiftAVFoundation.dylib
      Referenced from: /path/to/repo/Carthage/Build/iOS/SwiftFramework.framework/SwiftFramework
      Reason: no suitable image found.  Did find:
        /path/to/repo/Carthage/Build/iOS/SwiftFramework.framework/Frameworks/libswiftAVFoundation.dylib: no matching architecture in universal wrapper)```

Running lipo shows that while we properly merged the binaries of the framework itself, the sub-frameworks (i.e., the swift ones) only have device architectures. I filed a radar with apple a while ago about libswift not getting included for test bundles, getting lost in the 'duplicate' black hole, though the duplicate is still marked open. However it would be nice if carthage merged anything it found embedded if it can.

Attaching a zip file that contains a sample framework repository. If you add it as a dependency, and run a `carthage update`, you can reproduce this.
```
$ cd Carthage/Build/iOS/FrameworkWithSwift.framework                                        
$ lipo -i FrameworkWithSwift                      
Architectures in the fat file: FrameworkWithSwift are: i386 x86_64 armv7 arm64 
$ lipo -i Frameworks/libswiftAVFoundation.dylib   
Architectures in the fat file: Frameworks/libswiftAVFoundation.dylib are: armv7 armv7s arm64 
```

I've worked around this in the meantime by making the other test bundle import all the frameworks that the dependent framework does just to force it to have simulator architectures at a higher level.

**Comment by BobElDevil** [comment]
[FrameworkWithSwift.zip](https://github.com/Carthage/Carthage/files/138904/FrameworkWithSwift.zip)

**Comment by mokagio** [comment]
@BobElDevil I had the same issue this morning and solved it by following the last tip in Carthage's README regarding "[Adding frameworks to unit tests or a framework](https://github.com/Carthage/Carthage/blob/master/README.md#adding-frameworks-to-unit-tests-or-a-framework)"Y=:

> In rare cases, you may want to also copy each dependency into the build product (e.g., to embed dependencies within the outer framework, or make sure dependencies are present in a test bundle). To do this, create a new “Copy Files” build phase with the “Frameworks” destination, then add the framework reference there as well.

This is the relevant commit in my demo project HighLevelFramework, which depends on LowLevelFramework, and is consumed by a SampleApp: https://github.com/mokagio/HighLevelFramework/commit/fa340d1645cfe019943fbef3ea9430bb02c50475

**Comment by BobElDevil** [comment]
The issue isn't the lack of framework copying, it's the fact that when carthage is done building, libswift* isn't a fat binary like the rest of the framework. At the point where we invoke copy-frameworks it's too late, since the libswift* libraries are already missing the appropriate architectures

**Comment by mdiep** [comment]
Have you tried turning off _Embedded Content Contains Swift Code_ in your framework and instead including a Swift file in your unit tests? I believe I've worked around this issue that way before.

**Comment by BobElDevil** [comment]
I think I have confused folks with the libswift example. There's plenty of workarounds, we've definitely got it working. Not looking for a solution to that. I was more filing this because it seems that it should be merging embedded items together. Imagine an embedded (non-carthage created) binary in its bundle. The final result is a fat framework for all archs with less fat embedded content.

**Comment by ikesyo** [comment]
I believe setting the `Embedded Content Contains Swift Code` (`EMBEDDED_CONTENT_CONTAINS_SWIFT`) build setting at the unit test target should be the right way for the case. Carthage does not support nested frameworks (frameworks in a framework) those are problematic for App Store submission validation (should be rejected by the validator). Closing.
