### ISSUE TITLE
Missing .bcsymbolmap files when submitting to Apple

### ISSUE THREAD

**Issue by maciekish** [Carthage/Carthage#1142]
I just installed `Carthage` today and am facing the `.bcsymbolmap` issue (#853). As i installed today on a fresh Mac i assume I'm on the latest version. I added Hue `github "hyperoslo/Hue"`. It runs and archives fine. When i submit it says it's missing Hue's `.bcsymbolmap` file (I could tell by `mdfind UUID` which pointed me to `Hue`) :(

I have followed all the `Carthage` installation instructions including adding the copy-script.

Please advise.

**Edit:**

Here is an `Archive Post Action Script` (**not** a Build Phase Script) that fixes the issue temporarily

    cp "${SRCROOT}/Carthage/Build/iOS/"*.bcsymbolmap "${ARCHIVE_PATH}/BCSymbolMaps/

**Comment by maciekish** [comment]
Apparently i set up the Carthage script incorrectly. Looks like this solves the issue:
 ![](https://s3.amazonaws.com/f.cl.ly/items/1p1J1b0F1I3U1n290W2Y/Screen%20Shot%202016-02-24%20at%2010.36.21.png?v=6f366ff6)

**Comment by qnoid** [comment]
@maciekish can you please clarify what you had setup incorrectly before and how the new setup fixes the issue? Thanks!

**Comment by maciekish** [comment]
I had the the shell as `/usr/local/bin/carthage copy-frameworks` and the input files as the script instead of actual input files.

That gave me the `.bcsymbolmap` error on archive, and after exercising some `Google-fu` i found the setup above which seems to be working (no more `.bcsymbolmap` errors).
