### ISSUE TITLE
Carthage checkout fails for dependency with submodules after #1125

### ISSUE THREAD

**Issue by erichoracek** [Carthage/Carthage#1145]
As of #1125, I'm seeing the following failure when attempting to `checkout` a repo that has submodules:

```
A shell task failed with exit code 128:
fatal: Not a valid object name <dependency tag>
```

This is due to the changes introduced in #1125, which uses the output of `git rev-parse --show-toplevel` in place of the project URL passed as a parameter to `submodulesInRepository(_:revision:)`.

On my machine, when I run `git rev-parse --show-toplevel` in any of the repos in `~/Library/Caches/org.carthage.CarthageKit/dependencies/`, I get a newline as the only output (no absolute path). As such, when the `submoduleSHAForPath(_:_:revision:)` method is called with an empty string, I get the above shell task failure, since Carthage is attempting to run
```
git ls-tree -z <dependency tag> Carthage/Checkouts/Dependency
```
in the current working directory, where no such tag exists.

To reproduce this locally, create a `Cartfile`:
```
github "Mantle/Mantle"
```
And run `carthage bootstrap --no-use-binaries` with latest.

On my machine, I'm using git 2.7.1. This reproduces regardless of whether the repo exists in the cache before the checkout begins.

cc @NachoSoto @bhargavg

**Comment by bhargavg** [comment]
Hi @erichoracek, the issue is that, when running `carthage bootstrap --no-use-binaries`, the repositories are cloned as `bare` in `~/Library/Caches/org.carthage.CarthageKit/dependencies/` directory.

The `git rev-parse --show-toplevel` command will fail inside `bare` repositories (my bad).

Will raise a PR that fixes this.
