### ISSUE TITLE
How to detect if running under Carthage

### ISSUE THREAD

**Issue by schwa** [Carthage/Carthage#1148]
Is there any environment variable we could use to detect if a build is running under Carthage?

I checked docs and couldn't find anything.

I'd like to modify the behavior of carthage frameworks builds - in this case I want to disable swiftlint from running inside a carthage module (due to bugs in swiftlint).

**Comment by mdiep** [comment]
I don't think there's anything currently, but it sounds like a good idea. A pull request would be very welcome.
