### ISSUE TITLE
Unable to execute command: Segmentation fault: 11 - Xcode 7.3 beta 4 (7D152p)

### ISSUE THREAD

**Issue by fnazarios** [Carthage/Carthage#1152]
I'm receiving the ` Segmentation fault: 11` when i try run `carthage build` using `Xcode 7.3 beta 4`.

```
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by mdiep** [comment]
Is that output that's in the xcodebuild log? It doesn't sound like Carthage is segfaulting; it sounds like swift is segfaulting trying to compile the project.

**Comment by NachoSoto** [comment]
Yeah that's Xcode failing to compile your project. I recommend that you try to build it yourself using Xcode to see more details on what's wrong, and possibly file a radar since you hit a compiler crash.
