### ISSUE TITLE
Exit code 128 in travis for private repos

### ISSUE THREAD

**Issue by diogoguimaraes** [Carthage/Carthage#1155]
I'm having an issue running `carthage update --platform iOS --configuration ProductionRelease --use-ssh` on travis using a private repository. Here's the log:
```
A shell task failed with exit code 128:
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists. 
```
It works fine on my local machine and the travis cache is not configured.
Do you have an idea of what might be causing this?

**Comment by mdiep** [comment]
What happens if you try to clone a repository over SSH on Travis using `git clone`?

**Comment by diogoguimaraes** [comment]
I've just git cloned a repo before performing the `carthage update --platform iOS --configuration ProductionRelease --use-ssh` on travis and it went fine.

**Comment by mdiep** [comment]
Either the repo doesn't exist, you're not authenticated, or you're authenticated with an account that doesn't have access to that repo.

**Comment by diogoguimaraes** [comment]
The repo where the clone fails is `https://github.com/hyperoslo/Hue` and there are 2 strange facts: 
* I can perfectly perform a `carthage update --use-ssh` or `git clone` on my machine without any errors.
* If instead of using `carthage update --use-ssh`, I use `carthage checkout --use-ssh` on travis the clone happens without any errors.

Can it be that there is some step during `carthage update --use-ssh` that is causing this error?

**Comment by mdiep** [comment]
Possibly? But if you're trying to do CI builds, you should _not_ be using `carthage update`—that will upgrade to newer versions of your dependencies. You should use `carthage bootstrap` instead.

**Comment by diogoguimaraes** [comment]
Yes you're right, `carthage bootstrap` fixed the issue. 
Thanks.

**Comment by mdiep** [comment]
What's the output when you run `carthage bootstrap`? What happens if you use `carthage fetch` to fetch the repository?

**Comment by diogoguimaraes** [comment]
Using `carthage bootstrap` I've managed to get all my dependencies working on travis. 
When I get the chance I'll try `carthage fetch` to check its output.
