### ISSUE TITLE
Errors compiling danthorpe/Operations on a case sensitive file system

### ISSUE THREAD

**Issue by wmalloc** [Carthage/Carthage#1156]
https://github.com/danthorpe/Operations/issues/200

**Comment by danthorpe** [comment]
Hi - I'm investigating this issue at the moment. I don't think it has anything to do with a case sensitive file system - just that carthage is trying to build some example projects which use CocoaPods to setup their dependencies on the framework.

**Comment by danthorpe** [comment]
Suggest closing this for now. I am investigating, and will report back if I can determine that this issue is ultimately due to Carthage.

**Comment by mdiep** [comment]
Thanks @danthorpe!
