### ISSUE TITLE
build process consumes whooping 60 gb when using a framework provided by carthage

### ISSUE THREAD

**Issue by aboweb** [Carthage/Carthage#1162]
I started using carthage yesterday. I added the GRDB framework to my project. I added it to the 'Linked Frameworks and Libraries' section. Later on I also had to include it in the 'Embedded Library' section otherwise it wouldn't deploy on my device.
I had to manually correct the 'search paths' because the automatically added entries were messed up.

Finally the framework integration worked fine but Xcode now keeps on indexing and consumes gigabytes of memory. It takes about 5 minutes to finish but after that I run into the same problems when it actually tries to build the project.
<img width="388" alt="screen shot 2016-02-28 at 17 25 36" src="https://cloud.githubusercontent.com/assets/2025115/13380355/9058d1de-de73-11e5-99c3-aac80d2a5ac4.png">

I removed the references of the framework from the project but that didn't solve the problem. The only way was to remove all carthage folders from the project folder.

My next idea was to have the carthage folders outside of my project folder but that didn't work either.

What am I doing wrong here?

**Comment by ikesyo** [comment]
Sorry for the late response, but this does not look related to Carthage itself for me. Closing this for now.
