### ISSUE TITLE
Any guide available on how to create a Carthage framework?

### ISSUE THREAD

**Issue by idokleinman** [Carthage/Carthage#1164]
readme.md is primarily focused on how to use Carthage deps in your project but not how to create one.

**Comment by mdiep** [comment]
Did you read [this](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework)?

**Comment by dcaunt** [comment]
If you're looking for more detail, [this guide](https://robots.thoughtbot.com/creating-your-first-ios-framework) is pretty good. Creating a Framework with a shared scheme as described is about all that is required.

**Comment by idokleinman** [comment]
Thanks!
