### ISSUE TITLE
Dependency <...> has no shared framework schemes

### ISSUE THREAD

**Issue by idokleinman** [Carthage/Carthage#1165]
I created a framework target called "ParticleSDK" with its _shared scheme_ inside a similarly named project that sits under a .xcworkspace file named "Spark-SDK" the whole thing is in `github "spark/spark-ios-sdk`.

When I add a `Cartfile` containing `github "spark/spark-sdk-ios"` I get an error: 
```
*** Skipped building spark-sdk-ios due to the error:
Dependency "spark-sdk-ios" has no shared framework schemes
```
but it does! 

Is there some project/folder structure/naming convention I am overlooking here? Any ideas?

**Comment by ikesyo** [comment]
If you are using `github "spark/spark-sdk-ios"` without specifying any version or branch, Carthage fetches its latest tagged version, currently 0.3.4. Since the version does not have `spark-sdk-ios/Example/ParticleSDK/ParticleSDK.xcodeproj`, you should specify `"master"` branch in your Cartfile or cut a new release including the project.

**Comment by idokleinman** [comment]
Thank you very much for the help. Adding `"master"` solved that, but now I am getting the following error:
```
The following build commands failed:
	CompileC /Users/ido/Library/Developer/Xcode/DerivedData/spark-sdk-dmjaxlhdvmmndrddoihgcyywmqgg/Build/Intermediates/ParticleSDK.build/Release-iphoneos/ParticleSDK.build/Objects-normal/armv7/SparkDevice.o /Users/ido/projects/Spark/particle-sdk-ios/test_cart/Carthage/Checkouts/spark-sdk-ios/Pod/Classes/SDK/SparkDevice.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/ido/Library/Developer/Xcode/DerivedData/spark-sdk-dmjaxlhdvmmndrddoihgcyywmqgg/Build/Products/Release-iphoneos/AFNetworking.framework/Headers/AFNetworking.h:60:9: fatal error: 'AFNetworking/AFNetworkActivityIndicatorManager.h' file not found
/Users/ido/projects/Spark/particle-sdk-ios/test_cart/Carthage/Checkouts/spark-sdk-ios/Pod/Classes/SDK/SparkDevice.m:11:9: fatal error: could not build module 'AFNetworking'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/ido/Library/Developer/Xcode/DerivedData/spark-sdk-dmjaxlhdvmmndrddoihgcyywmqgg/Build/Intermediates/ParticleSDK.build/Release-iphoneos/ParticleSDK.build/Objects-normal/armv7/SparkDevice.o /Users/ido/projects/Spark/particle-sdk-ios/test_cart/Carthage/Checkouts/spark-sdk-ios/Pod/Classes/SDK/SparkDevice.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Situation is: AFNetworking is a dependency for my library - I created a `Cartfile` in my framework project folder pulling `"afnetworking/afnetworking"` in, dropping the `.xcodeproj` created in `Carthage/Checkouts` into my framework project and linked `AFNetworking.framework` into my target. It builds fine. Why would it fail now as a dependency?
