### ISSUE TITLE
Weird permissions for ...Caches/org.carthage.CarthageKit 

### ISSUE THREAD

**Issue by snej** [Carthage/Carthage#1170]
The directory ~/Library/Caches/org.carthage.CarthageKit has some very weird permissions on my system:
```
d-wxrw--wt   3 snej  staff   102B Nov  6 22:11 org.carthage.CarthageKit/
```
Looks like `0362`? (I'm not even sure what `t` means.) I can't think of any way that those permissions could make sense; I wonder if the mode parameter to the mkdir call was garbage for some reason…

(I just updated Carthage today, but the directory was created Nov 6; don't know what version I was using then.)

**Comment by mdiep** [comment]
This was fixed in #1073.
