### ISSUE TITLE
0.15 inserts duplicate entries with different versions in Cartfile.resolved

### ISSUE THREAD

**Issue by calebd** [Carthage/Carthage#1172]
This did not happen in 0.14.

**Comment by mdiep** [comment]
Can you share a Cartfile where this occurs?

**Comment by calebd** [comment]
This appears to be related to the fact that GitHub references are case-sensitive. I noticed that this also happens when specifying dependency names in any commands that accept them.

- Cartfile `A` brings in frameworks `B` and `C`
- `B` lists `github "alisoftware/dip"
- `C` lists `github "Alisoftware/Dip"
- `A/Cartfile.resolved` will contain an entry for each instead of one single entry

**Comment by calebd** [comment]
Correction to my previous statement: this issue does occur in 0.14. I first noticed it when we added a new dependency around the same time that I updated to 0.15.

**Comment by bhargavg** [comment]
You are right, turns out dependency names are case-sensitive (`dip` vs `Dip` in your case) I guess.

Working on a fix.
