### ISSUE TITLE
Ok on the device but generate "Undefined symbols for architecture x86_64" with simulator

### ISSUE THREAD

**Issue by TofPlay** [Carthage/Carthage#1175]
Hi,

**My config**
- Xcode 7.2.1 (7C1002)
- Carthage 0.15

**The issue**
I exactly follow the instructions on section [If you're building for iOS, tvOS, or watchOS](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos) 
When I build and run the application on the device everything is perfect but when I select the simulator like **iPhone 6** on **iOS 9.2** at the build I have a couple of errors:
`Undefined symbols for architecture x86_64`

Any ideas?

**Comment by TofPlay** [comment]
After some investigations It's associate with this 2 components (Cartfile):
```
...
github "stripe/stripe-ios" == 6.2.0
github "algolia/algoliasearch-client-swift" == 2.2.1 
...
```
Why these components? I don't know 😓

**Comment by mdiep** [comment]
I'm not sure. Are you downloading pre-built binaries for those frameworks? Or building them from scratch? (`--no-use-binaries`)

**Comment by TofPlay** [comment]
I just run the command 
```
carthage update --platform iOS
```
The output is:
```
*** Fetching algoliasearch-client-swift
*** Fetching stripe-ios
*** Downloading stripe-ios.framework binary at "Version 6.2.0"
*** Checking out stripe-ios at "v6.2.0"
*** Checking out algoliasearch-client-swift at "2.2.1"
```
I feel that Carthage takes a  pre-built binaries for stripe. For Algolia I don't know.

**Comment by jflinter** [comment]
Hmm, I'm one of the maintainers of http://github.com/stripe/stripe-ios. This feels like a bug in Carthage based on the console output @TofPlay included.

We do attach some build artifacts to our Github releases (e.g. https://github.com/stripe/stripe-ios/releases/tag/v6.2.0), but they're not prebuilt via Carthage - they're static libraries wrapped up in a `.framework`, and are intended for legacy users and not Carthage.

According to the [Carthage Documentation](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file), Github release assets need to contain `.framework` in their name for Carthage to try and use them as a prebuilt framework. Ours do not. That line in the above comment that claims Carthage is `*** Downloading stripe-ios.framework binary at "Version 6.2.0"` makes me think it's doing so erroneously.

I've done some extremely cursory poking around, and it appears that check occurs on https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Project.swift#L453 - perhaps it's being skipped somehow? Thoughts @mdiep?

**Comment by ikesyo** [comment]
@jflinter I tries this and actually the binary is not downloaded:

```bash
$ carthage update 
*** Cloning stripe-ios
*** Downloading stripe-ios.framework binary at "Version 6.2.0"
*** Checking out stripe-ios at "v6.2.0"
*** xcodebuild output can be found in /var/folders/xr/w_d70m8j2xdbfvfhw1g0kfmw0000gn/T/carthage-xcodebuild.jOiT85.log
*** Building scheme "StripeOSX" in Stripe.xcworkspace
*** Building scheme "StripeiOS" in Stripe.xcworkspace
```

[This line](https://github.com/Carthage/Carthage/blob/98bcd1f/Source/CarthageKit/Project.swift#L447) outputs `*** Downloading stripe-ios.framework binary at "Version 6.2.0"`, but the actual download process would happen later [here](https://github.com/Carthage/Carthage/blob/98bcd1f/Source/CarthageKit/Project.swift#L464-L466). And as seen above, the project is correctly checked out and built locally. So this is just an incorrect event output, I think.
