### ISSUE TITLE
Require a specific carthage version

### ISSUE THREAD

**Issue by ffittschen** [Carthage/Carthage#1181]
Hi,
given the scenario:
- Developer A updates `carthage` on his local machine, edits the code of the project and commits everything to the repo.
- Developer B (who still has the older `carthage` version) checks out the new commits and runs `carthage bootstrap`

Is there any way to require a specific carthage version, or warn if the `Cartfile.resolved` has been created with a newer `carthage` version, when Developer B runs `carthage bootstrap`? Because after the two steps of the scenario, both developers _could_ have a different codebase.

**Comment by mdiep** [comment]
No, there's not. We do have an issue open to alert users if there's a newer version of Carthage available, but it hasn't been implemented. And while this could be an issue, we do try to maintain compatibility as much as possible.

**Comment by ffittschen** [comment]
@mdiep Okay, I just had this in the back of my mind, because I ran into something similar, when the "Copy dSYM" Build Phase was obsolete, because the functionality had been integrated into `copy-frameworks`
