### ISSUE TITLE
Failed to read file or folder for FMWK

### ISSUE THREAD

**Issue by feifanzhou** [Carthage/Carthage#1185]
I'm trying to build [Atlas](https://github.com/feifanzhou/Atlas-iOS) with Carthage. Running `carthage update`, the build log shows `** BUILD SUCCEEDED **`, but then `Failed to read file or folder at /Users/User1/Library/Developer/Xcode/DerivedData/Atlas-dqpmapvvvmkltocjqujgngzsalfc/Build/Products/Release-iphoneos/Atlas.framework`. 

The same "Failed to read" error appears in the `copy-frameworks` build script, preventing the main project from building correctly. 

Atlas does have its bundle type [set to FMWK](https://github.com/layerhq/Atlas-iOS/commit/4a14e38925062e575a57af855f0dbcd811c75170), as per https://github.com/Carthage/Carthage/issues/1096

**Comment by mdiep** [comment]
It sounds like you may have listed the incorrect path in the input files for the script in Xcode.  What did you list there?

**Comment by feifanzhou** [comment]
`$(SRCROOT)/Carthage/Build/iOS/Atlas.framework`
"Failed to read" also appears at the end of `carthage update`, before I even try building the main Xcode project.

**Comment by feifanzhou** [comment]
To repro:

```
mkdir /tmp/test && cd $_
echo 'github "feifanzhou/atlas-ios" "master"' > Cartfile
carthage update
```

Output is
```
*** Fetching releases-ios
*** Checking out atlas-ios at "ad9f5d6d7a029293d548111dd06cfef99921bb57"
*** Downloading releases-ios.framework binary at "v0.19.4"
*** Checking out releases-ios at "v0.19.4"
*** xcodebuild output can be found in /var/folders/j2/m7xr28jd6gz1lrdf_c1ckgh80000gn/T/carthage-xcodebuild.5xHLkU.log
*** Building scheme "Atlas" in Atlas.xcworkspace
Failed to read file or folder at /Users/User1/Library/Developer/Xcode/DerivedData/Atlas-csxtykzrentvvyclgviebinagfwm/Build/Products/Release-iphoneos/Atlas.framework
```

Build log says `** BUILD SUCCEEDED  **` at the bottom

**Comment by mdiep** [comment]
It's failing because Atlas's `Info.plist` doesn't contain a `CFBundleExecutable` key.

**Comment by feifanzhou** [comment]
Thanks @mdiep

**Comment by feifanzhou** [comment]
@mdiep adding that key fixes the build but breaks App Store submission: http://stackoverflow.com/questions/32096130/unexpected-cfbundleexecutable-key

The app runs fine without that key — why is it being checked and breaking the build?

**Comment by mdiep** [comment]
I'm not sure why Carthage checks this key. This will require investigation.

**Comment by ikesyo** [comment]
`CFBundleExecutable` is used in [`binaryURL`](https://github.com/Carthage/Carthage/blob/0.15.2/Source/CarthageKit/Xcode.swift#L1510-L1512). The function is used for [picking up architectures in a framework](https://github.com/Carthage/Carthage/blob/0.15.2/Source/CarthageKit/Xcode.swift#L1351-L1410), [stripping a specific architecture](https://github.com/Carthage/Carthage/blob/0.15.2/Source/CarthageKit/Xcode.swift#L1338-L1349), and [picking up UUIDs for each architecture in a framework](https://github.com/Carthage/Carthage/blob/0.15.2/Source/CarthageKit/Xcode.swift#L1351-L1410).

The key is a standard one and is included by default in `Info.plist` of a fresh framework target created from Xcode's template.

**Comment by ikesyo** [comment]
@feifanzhou The problems is that `AtlasResource.bundle` that is [built by CocoaPods](https://github.com/layerhq/Atlas-iOS/blob/v1.0.19/Atlas.podspec#L19) shares the same `Resources/Info.plist` with `Atlas.framework`. Since `AtlasResource.bundle` does not contain any executable, that is rejected by the validator. You should use separated `Info.plist` for `Atlas.framework` and `AtlasResource.bundle`.

**Comment by Picosu** [comment]
I actually got that error. I solved it by editing manually the xcodeproj. 
My error came from an update of SocketIOClientSwift, renamed into SocketIO only. So my manual edition solved the problem.

**Comment by baoshan** [comment]
Note the `Bundle OS Type code` should be `FMWK`. The issue also happens when the `Bundle OS Type code` is `APPL` by mistake.
