### ISSUE TITLE
Weird issue related to swift generic

### ISSUE THREAD

**Issue by zwang** [Carthage/Carthage#1189]
I got a weird issue while using two libraries with Carthage. It was ok to use with CoacoPods. I spent hours trying to fix it but no luck. And I didn't find anywhere mentioning similar case as mine. So I come here looking for some help (confirmation). It seems to me this might be related to the "Known Issues" mentioned in the Readme file but I am not sure. 

Any help is appreciated! Thanks.  

I have created a demo project at here: https://github.com/zwang/ChattoDiff to show the issue

In the demo project, I have two simple iOS project, both created using Xcode default single page application template with one extra source file `DemoMessagePresenter.swift`. The two project share exactly the same source files.

However, in CApp project using Carthage for dependency management, the source code can not be compiled. In PApp project using CocoaPods for dependency management, everything compiles.

The compilation error show as below:

`/Users/zhao/workspace/ChattoDiff/Sources/DemoMessagePresenter.swift:122:38: Cannot convert value of type 'InteractionHandlerT?' to expected argument type '_?'`

The DemoMessagePresenter and DemoMessagePresenterBuilder is exactly the same as TextMessagePresenter and TextMessagePresenterBuilder in the `ChattoAdditions` library. I just simply changed the names

![screen shot 2016-03-13 at 11 48 12 pm](https://cloud.githubusercontent.com/assets/1171212/13737455/ad277524-e97a-11e5-96b2-8c13c18f33d4.png)

I also reported the issue at the library repo: https://github.com/badoo/Chatto/issues/60

**Comment by mdiep** [comment]
That error looks like a type inferencing error from Swift. I'm not sure how to fix it. I'm not sure why CocoaPods avoids it—it's likely a Swift bug that's specific to how the code is combined. You might try with the latest Xcode 7.3 beta to see if it's fixed there. If not, I'd suggest filing a Radar.

**Comment by zwang** [comment]
@mdiep  thanks for looking into this and the advice. I will try Xcode 7.3 beta soon and update if this fix the issue. Thanks.

**Comment by zwang** [comment]
There is an workaround mentioned here https://github.com/badoo/Chatto/issues/60. I am going to close this issue since it seems to be related to Swift, bug also has been filed with swift.
