### ISSUE TITLE
updating carthage to the latest version.

### ISSUE THREAD

**Issue by Dershowitz011** [Carthage/Carthage#1194]
How to update carthage to the latest version using homebrew?

**Comment by bhargavg** [comment]
Like you do for every other package, `brew update && brew upgrade carthage`

**Comment by Dershowitz011** [comment]
Brew update takes such a long time and i wonder if it is actually happening. Is it the same for you too?

**Comment by mdiep** [comment]
It look a while here too, but it does work and that is how you upgrade via homebrew.

**Comment by Ronaldoh1** [comment]
👍

**Comment by AdrianBinDC** [comment]
@Dershowitz011 Keep an eye on the titlebar of the Terminal window. Even though the screen might look like it's doing nothing, the title bar of the Terminal window will change to tell you it's doing something.

**Comment by Shinehah-Gnolaum** [comment]
What would happen if I typed "brew install carthage" when an older version of Carthage is already installed with Homebrew? Would it do any harm?

**Comment by blender** [comment]
Brew will complain and tell you to upgrade instead

**Comment by walsht** [comment]
I am still seeing the old version 

tim$ brew update && brew upgrade carthage
Already up-to-date.
Error: carthage 0.31.2 already installed
tim$ carthage version 
Please update to the latest Carthage version: 0.31.2. You currently are on 0.31.0
0.31.0

**Comment by blender** [comment]
You are not using the version of Carthage you think you are.

**Comment by walsht** [comment]
When you upgrade carthage, should it start using that? Or at very least remove the old version?

**Comment by blender** [comment]
Carthage from brew is at 0.31.2, your Carthage says that it's 0.30.0. You are probably not using the Carthage from brew.  

Try 

```
brew unlink carthage #
carthage version  
``

If this still works, clearly you're not using brew's version.

So then, run `which carthage` to find out which carthage you're using.

**Comment by RajChanchal** [comment]
> Carthage from brew is at 0.31.2, your Carthage says it is at 0.30.0. You are probably not using Carthage from brew.
> 
> Try
> 
> ```
> $ brew unlink carthage
> $ carthage version  
> ```
> If this still works, clearly you're not using brew's version.
> 
> So then, run `which carthage` to find out which carthage you're using.

Ran `which carthage`, it shows:
/usr/local/bin/carthage

**Comment by teogeos** [comment]
In case you get here from google, after running `brew upgrade carthage` you actually need to run `brew switch carthage 99.99.99` to actually use the latest version (replace 99.99.99 with the version you want to use).

**Comment by Kaushal0812** [comment]
## As  of writing this comment the current version is 0.35.0

If `brew upgrade carthage` command is not working for you, then it means you have not used `homebrew` during Carthage installation.

So to upgrade using `homebrew`, use the following steps:

Use `which carthage` command. 

It will show the current path of carthage
In my case it is ***"/usr/local/bin/carthage"***. Delete the existing carthage here.

Then use 
`brew install carthage
`
This will install the latest version of carthage.

**Comment by drosenstark** [comment]
Actually something's odd with 0.35.1

```
$/usr/local/Cellar/carthage/0.35.1/bin/carthage version
Please update to the latest Carthage version: 0.35.1. You currently are on 0.35.0
0.35.0
```

You can uninstall and reinstall and unlink all day. 35.1 reports that it's 35.

**Comment by damonZDM** [comment]
我使用 brew upgrade carthage 指令更新到了最新的Carthage。
但是运行时还是提示我当前版本为0.35.0.
Please update to the latest Carthage version: 0.35.1. You currently are on 0.35.0

**Comment by tmspzz** [comment]
0.36.0 is out

**Comment by chinwy22** [comment]
didn't work

**Comment by tmspzz** [comment]
> didn't work

You have to wait for brew to build https://github.com/Homebrew/homebrew-core/pull/61303 or use the .pkg attached to the release on the Carthage repo.
