### ISSUE TITLE
Force `xcodebuild` to build against hardware

### ISSUE THREAD

**Issue by dcunited001** [Carthage/Carthage#1195]
I'm working on a 3D graphics lib called Spectra.  For iOS, MetalKit requires hardware to compile against and won't even recognize symbols if the iOS target isn't set to build against connected hardware.  

When I try to import this library into another project, it's a mess.  I can't get carthage to call `xcodebuild` with the appropriate settings or target.  I'm not very familiar with these command line tools and I don't know of very many libraries that have constraints like this.  Is there any way to get carthage to manage this library?  

The only way I know of to get this lib into another project is to clone it and pull it into a workspace, then build an archive of the framework. And AFAIK, it has to be a runtime version of the framework. It's pretty messy, but it works, I guess.

**Comment by mdiep** [comment]
> MetalKit requires hardware to compile against and won't even recognize symbols if the iOS target isn't set to build against connected hardware

Really? :flushed:

You should be able to use Carthage's `--use-submodules` workflow. Basically, use that flag to check out, don't build with `carthage` on the command line, and add your dependencies' `xcodeproj`s directly to your project or workspace.
