### ISSUE TITLE
Symbol not Found (Xcode 7.3 beta, Carthage 0.15.2)

### ISSUE THREAD

**Issue by mike-engel** [Carthage/Carthage#1198]
Hey Carthage team,

I'm trying to use the [SwiftSVG](https://github.com/mchoe/SwiftSVG) framework in my project, and running into an error when running my app on the device.

FYI, I'm running
- Xcode 7.3 beta (7D162j)
- Carthage 0.15.2
- SwiftSVG 1.1.3
- OS X 10.11.4 Beta (15E64a)

The error I'm getting is
```
dyld: Symbol not found: __TMPdCSs18_HeapBufferStorage
  Referenced from: /private/var/containers/Bundle/Application/8A2DA53C-FC7F-4806-BFE3-133E737734C4/cinematic-aspect.app/Frameworks/SwiftSVGiOS.framework/SwiftSVGiOS
  Expected in: /private/var/containers/Bundle/Application/8A2DA53C-FC7F-4806-BFE3-133E737734C4/cinematic-aspect.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/8A2DA53C-FC7F-4806-BFE3-133E737734C4/cinematic-aspect.app/Frameworks/SwiftSVGiOS.framework/SwiftSVGiOS
```

I've added the run script to my project, added the Input file, and added the SwiftSVG framework to the `Linked Frameworks and Libraries` section. It may be important to note I'm not actually `import`ing the framework anywhere in my code yet. If I remove the framework from the `Linked frameworks and libraries` section, it builds fine. 

Let me know if any more info is needed. Thanks!

**Comment by nickskull** [comment]
Did you add the framework to the embedded binaries?

**Comment by mdiep** [comment]
Are you building the frameworks with `carthage`? If so, what version of Xcode were they compiled with? (`xcodebuild -version`)

**Comment by NachoSoto** [comment]
This look like the same as #1200.

**Comment by mdiep** [comment]
I think #1200 is about seeing this error in Carthage itself, while this issue is about seeing it in another library while using Carthage.

**Comment by mike-engel** [comment]
@mdiep I just re-ran `carthage update` this morning after downloading the public release of Xcode 7.3. Everything seems to be working now, so I assume this was a bug with the beta versions of Xcode 7.3. In case you're still wondering here's my version of xcodebuild:

```
Xcode 7.3
Build version 7D175
```

Thanks!

**Comment by JanC** [comment]
Hi,
I have the same issue. I updated `carthage`, re-run `carthage update` and I'm using the public Xcode 7.3.

**Comment by ikesyo** [comment]
@JanC That is because that the prebuilt binary of [PermissionScope's latest release](https://github.com/nickoneill/PermissionScope/releases/tag/1.0.2) should be built with Swift 2.1, but there is no binary compatibility between Swift 2.1 and Swift 2.2. In that case, you should rebuild the framework on your side by `carthage update --no-use-binaries`.

**Comment by JanC** [comment]
Thanks, that was indeed the problem. cheers!
