### ISSUE TITLE
Dragging framework to General → Linked Frameworks vs. Build Phases → Link Binary With Libraries (for frameworks)

### ISSUE THREAD

**Issue by aral** [Carthage/Carthage#1199]
1. Create a new dynamic framework project (iOS) and drag a Carthage-built framework into General → Linked Frameworks and Libraries

Errors encountered:

1. Successful build, followed by following error:

![aral_2016-mar-21 1](https://cloud.githubusercontent.com/assets/41798/13924318/2053d04c-ef84-11e5-9041-8906249819ce.jpg)

Which gets resolved, e.g., by:

![aral_2016-mar-21](https://cloud.githubusercontent.com/assets/41798/13924303/13fb6d5a-ef84-11e5-9539-d6886d19dd99.jpg)

*bangs head on desk*

2. Not sure what I changed afterwards but then the errors became 'Async is not a module'.

Fix:

Drag the same framework(s) to Build Phases → Link Binary With Libraries

Am I (a) missing something basic here (b) losing my mind (c) …? :)

**Comment by mdiep** [comment]
Can you share your project somewhere?

**Comment by aral** [comment]
Sure. I’m going to upgrade to Xcode 7.3 today, verify that the problem still exists and then I’ll draw up detailed instructions to reproduce and a isolated sample project and submit them.

**Comment by aral** [comment]
@mdiep Tested with two identical new workspaces/projects with Xcode 7.3 but could not reproduce this morning. Closing.

**Comment by mdiep** [comment]
That's great news! :sparkles:

**Comment by aral** [comment]
@mdiep Yeah, it was one of those weird ones (that I was able to replicate from scratch the other day). If I run into again I’ll report back. Hoping not :)
