### ISSUE TITLE
Incorrect `copy-frameworks` target path for test targets in Xcode 7.3

### ISSUE THREAD

**Issue by ali-rantakari** [Carthage/Carthage#1203]
It looks like Carthage currently copies frameworks to `${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}`. For _unit test targets_, these paths look something like this:

    /Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyAppTests.xctest/Frameworks/

However Xcode 7.3 installs the `.xctest` bundle in `${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}`. These paths look something like this:

    /Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/Frameworks/

So if you want to include Carthage framework dependencies in a unit test target, they will get installed into the wrong location, resulting in error messages like this when you try to run your tests:

    Failed to load test bundle from file:///Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/../MyAppTests.xctest/: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/MyAppTests): Library not loaded: @rpath/SomeThing.framework/SomeThing
      Referenced from: /Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/MyAppTests
      Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/MyAppTests, NSDebugDescription=dlopen_preflight(/Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/MyAppTests): Library not loaded: @rpath/SomeThing.framework/SomeThing

Here’s what Apple’s [Xcode build settings documentation][buildsettingdocs] has to say about `TARGET_BUILD_DIR`:

[buildsettingdocs]: https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW88

> Run Script build phases that operate on product files of the target that defines them should use the value of this build setting. But Run Script build phases that operate on product files of other targets should use BUILT_PRODUCTS_DIR instead.

**Comment by ali-rantakari** [comment]
Fixing this by making `carthage copy-frameworks` copy files to `${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}` instead of `${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}` is probably an appropriate way to fix this.

This change _should_ be backwards compatible (for versions of Xcode older than 7.3) — I have verified at least that both of those resolve to the same path in Xcode 7.2.1.

**Comment by taiheng** [comment]
As a quick fix until there's a new release I'm re-exporting `BUILT_PRODUCTS_DIR` for that run phase. 

````
export BUILT_PRODUCTS_DIR=$TARGET_BUILD_DIR
/usr/local/bin/carthage copy-frameworks
````

My copy frameworks step is also the last step, however a quick test seems to indicate that `BUILT_PRODUCTS_DIR` should revert back to default outside of this script.

**Comment by ratkins** [comment]
I'm not using `carthage copy-frameworks` in my test target build phases at all. Instead, we added another "Copy Files" phase with "Destination: Frameworks", as directed by this [somewhat obliquely worded section](https://github.com/Carthage/Carthage#adding-frameworks-to-unit-tests-or-a-framework) in the README ("in rare cases"—which cases? What other way is there to do it?).

All I can report is this works for us on Xcode 7.3, and our tests run on simulator and on device with no problems.

**Comment by mdiep** [comment]
> Making carthage copy-frameworks copy files to ${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH} instead of ${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH} is probably an appropriate way to fix this.
> 
> This change should be backwards compatible (for versions of Xcode older than 7.3) — I have verified at least that both of those resolve to the same path in Xcode 7.2.1.

That sounds reasonable. Would you be interested in opening a pull request?
