### ISSUE TITLE
Build framework regardless of prebuilt version

### ISSUE THREAD

**Issue by dersvenhesse** [Carthage/Carthage#1205]
I'd really like an option to force build a framework regardless of a prebuilt version in the releases folder. This might be really helpful, especially when the latest prebuilt version was build with an old version of Xcode. A flag like `carthage update --ignore-prebuild` would check out all projects instead downloading the *.framework versions. 

Or am I missing something and this is already possible?

**Comment by ikesyo** [comment]
`--no-use-binaries` is what you want.
