### ISSUE TITLE
copy-frameworks does not strip *.swiftmodule files

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#1206]
I was going over our `.ipa` to figure out why it was so big, and I noticed that these `swiftmodule` files are there for every architecture:

<img width="255" alt="screen shot 2016-03-22 at 5 52 55 pm" src="https://cloud.githubusercontent.com/assets/685609/13972562/05636ff8-f057-11e5-9caf-71d04d55bb6c.png">

I have no idea what they are, and it doesn't make any sense that one of our framework's (which is super small) are much bigger than `RAC`'s. Either way, this would save a lot of space! :)

**Comment by ikesyo** [comment]
IIRC this is done in #837. See also #383.

**Comment by NachoSoto** [comment]
Hmm weird. When I reported this I must have certainly been using a version that included #837 :/

**Comment by NachoSoto** [comment]
Confirmed, this is not an issue anymore 👍 Thanks @ikesyo!
