### ISSUE TITLE
Build failed with Xcode 7.3

### ISSUE THREAD

**Issue by huv** [Carthage/Carthage#1207]
With Xcode 7.3, run "carthage bootstrap --no-use-binaries --platform ios --use-submodules"
The following build commands failed:
	CompileSwift normal arm64 $/Carthage/Checkouts/Nimble/Nimble/Adapters/NimbleXCTestHandler.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by dcaunt** [comment]
I think you need to upgrade Nimble to [v3.2.0](https://github.com/Quick/Nimble/releases/tag/v3.2.0), which supports Xcode 7.3.
