### ISSUE TITLE
No way to disambiguate between multiple schemes for a platform

### ISSUE THREAD

**Issue by snej** [Carthage/Carthage#1209]
If an Xcode project contains more than one scheme for a specific platform, there doesn't seem to be a way to tell Carthage which of those schemes should be built. This is especially problematic if both schemes produce a framework with the same name.

For example, the [Couchbase Lite](https://github.com/couchbase/couchbase-lite-ios/) project (which I work on) contains four shared Mac OS schemes, of which one builds the regular CouchbaseLite.framework, and another builds a CouchbaseLite.framework that uses an embedded copy of SQLCipher instead of the regular system SQLite dylib. Two problems:
1. The SQLCipher-based version requires first building or downloading a copy of SQLCipher. We don't build it as a submodule because IIRC it's hard to build (I didn't work on this so I'm vague on the details.) This means that the Carthage build will fail, because the expected SQLCipher library is missing.
2. Even if that build succeeded, both this scheme and the regular Mac scheme produce a product named `CouchbaseLite.framework`. This is important to us because (a) we don't have to have two different versions of our sample code with different `#import` statements in them, and (b) the developer can switch from one to the other without having to edit all their source code to change their `#imports`. But if Carthage builds both of these into the same directory, one framework will of course overwrite the other.

**Comment by ikesyo** [comment]
> Even if that build succeeded, both this scheme and the regular Mac scheme produce a product named CouchbaseLite.framework. This is important to us because (a) we don't have to have two different versions of our sample code with different #import statements in them, and (b) the developer can switch from one to the other without having to edit all their source code to change their #imports. But if Carthage builds both of these into the same directory, one framework will of course overwrite the other.

You should be able to differentiate a module name from a product name by using the `PRODUCT_MODULE_NAME` build setting, for example:

- `PRODUCT_MODULE_NAME`: `CouchbaseLite`
- `PRODUCT_NAME`: `CouchbaseLite-SQLCipher` (`CouchbaseLite-SQLCipher.framework` will be created and that can be imported by `import CouchbaseLite` because its module name is `CouchbaseLite`)

**Comment by snej** [comment]
Interesting. Even if `import CouchbaseLite` works, will `#import <CouchbaseLite/CouchbaseLite.h>` work? Not everyone is using modular framework imports.

Also, note that this is a "static framework", i.e. it contains a static library not a dylib. Xcode knows how to build with these (merging the library contents in at link-time) but I'm not sure that Obj-C's `@import` syntax works with this.

**Comment by ikesyo** [comment]
> Interesting. Even if import CouchbaseLite works, will #import <CouchbaseLite/CouchbaseLite.h> work? Not everyone is using modular framework imports.

I'm not sure.

> Also, note that this is a "static framework", i.e. it contains a static library not a dylib.

Since Carthage only builds dynamic frameworks, the scheme will be ignored.

**Comment by snej** [comment]
Oops, I forgot Carthage is dynamic-only! We also have dynamic framework targets, which is what Carthage would use, so forget what I said about static libraries.

**Comment by snej** [comment]
However, this doesn't address the primary problem that there's no way to configure which target Carthage should build, for a given platform.

There's a further problem: the developer may need to build _multiple_ targets for the same platform. Our project also builds a CouchbaseLiteListener framework, and some apps need to use both frameworks.

**Comment by mdiep** [comment]
Carthage will build all dynamic framework targets in the repository. So as long as they have different names on disk, they will all be accessible for consumers.

**Comment by snej** [comment]
OK. That still leaves the other problem: we have schemes that will not build without semi-manual intervention (copying a static library into the source tree.) See fuller description above. Currently Carthage fails to build the Mac version of the couchbase-lite-ios repo [sic] because the first scheme it tries to build, `CBL Mac+SQLCipher`, is one of those schemes. Then it stops, without building the regular `CBL Mac` scheme.

I think we need a way to tell Carthage _not_ to build specific schemes (or conversely, to build _only_ specific schemes.)

As a workaround, if we could deterministically control what order Carthage builds schemes, we could put the troublesome one(s) at the end of the ordering. (I don't know where it's currently getting the ordering from. It's not the same order the schemes appear in Xcode.)

**Comment by mdiep** [comment]
If there are dependencies between your targets, then you should add those dependencies in Xcode. Then you'll be able to build with Carthage.

If you need to copy something, you can always do it as a Run Script phase.

**Comment by snej** [comment]
It's not a dependency between targets, nor a local copy. It's _downloading_ an external binary (a precompiled build of SQLCipher.) Yes, we could add a script build phase to download it with curl, but I really dislike hiding that sort of stuff inside a build operation.
