### ISSUE TITLE
Take advantage of the terminal (colors, column width, etc.)

### ISSUE THREAD

**Issue by robrix** [Carthage/Carthage#121]
When running in a terminal we could do terminal-y things:

- Per [a comment](https://github.com/Carthage/Carthage/pull/117#discussion_r20728285) by @robb, we could take the Terminal width into account.

- Per @jspahrsummers’ reply, bold/underlining.

- :sparkles: pretty colours :sparkles:

**Comment by jdhealy** [comment]
Hey, I just publish a library designed to start dealing with this terminal stuff.

Named it [PrettyColors](https://github.com/jdhealy/PrettyColors), [after @robrix's comment](https://github.com/Carthage/Carthage/issues/121#issue-49752203)  — *although sans “u” to match `NSColor` and `UIColor`…*

[I've opened a RFC issue here](https://github.com/jdhealy/PrettyColors/issues/1) and I'd love to get your feedback on how it would work best with Carthage.
