### ISSUE TITLE
Nested dependencies are not downloaded

### ISSUE THREAD

**Issue by hovox** [Carthage/Carthage#1213]
Nested dependencies are not downloaded in my project's `Carthage/Build` folder.  I can add them from `Carthage/Checkouts/SomeLibThatDependsFromOtherFramework/Carthage/Build/iOS/SomeFramework.framework` but the thing is that we have added `Carthage/Checkouts` into `.gitignore`,  we are publishing to the server only  `Carthage/Build` folder.  As I understand from `Readme` nested dependencies should be downloaded into my `Carthage/Build` folder.

> If the framework you want to add to your project has dependencies explicitly listed in a Cartfile, Carthage will automatically retrieve them for you. You will then have to drag them yourself into your project from the Carthage/Build folder.

Did I misunderstood something or this is a bug ?

My carthage version is 0.14.0 , installed through `brew`.

My library's `Cartfile` contains only one line `github "BoltsFramework/Bolts-ObjC" == 1.6.0` , my main project's `Cartfile` contains a few GitHub projects but not Bolts, for updating carthage dependencies I'm always calling update command like this `carthage update --platform iOS`. Please let me know if I can provide more info. Thanks in advance.

**Comment by mdiep** [comment]
Please update to 0.15.2 and see if you're still seeing the same behavior.

**Comment by hovox** [comment]
`brew upgrade carthage` gives me this error :

> Error: carthage 0.14 already installed

Do I need to update by downloading the .pkg file or  there is a way to upgrade through `brew` ?

**Comment by ikesyo** [comment]
You should run `brew update` at first.

**Comment by hovox** [comment]
@mdiep I have updated to the 0.15.2 version, and the issue still exists

**Comment by jlawton** [comment]
Carthage should be symlinking Build directories.

As a quick fix, have you tried deleting your root Build directory and bootstrapping? Or `ln -sFi ../../../../Carthage/Build Carthage/Checkouts/SomeLibThatDependsFromOtherFramework/Carthage/Build`?

**Comment by mdiep** [comment]
Could you share `SomeLibThatDependsFromOtherFramework` or another project that exhibits the issue you're seeing?

**Comment by hovox** [comment]
Hi @jlawton. The thing is that we don't want to push `Checkouts` folder. We only pushing `Build` folder into server.


Hi @mdiep to reproduce the case I have created two projects [`carthage-nested-dependency-issue`](https://github.com/hovox/carthage-nested-dependency-issue) and[ `carthage-nested-dependency-issue-app`](https://github.com/hovox/carthage-nested-dependency-issue-app). First one is a lib that contains another lib `Bolts`, second one is a simple project depending from first one.

After calling `carthage update --platform iOS` on the second one, my projects `Carthage/Build/iOS` folder contains only `Bolts` framework,  I expected the opposite ( that my project should contain only project from first repository. I'm confused. Am I doing something wrong ?

**Comment by hovox** [comment]
Don't know what I have changed but now 

> After calling carthage update --platform iOS on the second one, my projects Carthage/Build/iOS folder contains only Bolts framework, I expected the opposite ( that my project should contain only project from first repository.

this behavior is gone, and I can reproduce my case. 

I have noticed another issue.  I have created branch `without-bolts` in `carthage-nested-dependency-issue` repo and when I have changed `Cartfile` in `carthage-nested-dependency-issue-app` to this `github "hovox/carthage-nested-dependency-issue" "without-bolts"` and called `carthage update` it's printing this

> Checking out carthage-nested-dependency-issue at "f32d7d80f45d359d1b7af6854bc0218e6cedd8f3" 

But my `without-bolts` shows on `04b7ef5a1a531ed4a4929d55d778fc995c246403 ` commit.

**Comment by hovox** [comment]
After calling `carthage fetch https://github.com/hovox/carthage-nested-dependency-issue.git` the issue that commit is not updating resolved,  I think it's related to this issue [1191](https://github.com/Carthage/Carthage/issues/1191)

**Comment by mdiep** [comment]
Yeah, I think you're partly hitting #1191.

It looks like the other issue is that your `Cartfile` is in a subdirectory. Your `Cartfile` must be in the root directory of your project.

**Comment by hovox** [comment]
Seems fixed. Thank you very much @mdiep .
I think it would be good to mention that in Readme.
