### ISSUE TITLE
Cannot build framework

### ISSUE THREAD

**Issue by jozsef-vesza** [Carthage/Carthage#1215]
Carthage version: 0.10.0 (installed w/ Homebrew)

I am trying to add Carthage support on the Mac to the [Typhoon project](https://github.com/appsquickly/Typhoon). [Here's the branch](https://github.com/jozsef-vesza/Typhoon/tree/carthage-support) I'm working on.

Steps I've done:
- added a new Cocoa framework target called "Typhoon OSX"
- shared the new scheme, also called "Typhoon OSX"
- the product name for both the iOS and the Mac frameworks are the same ("Typhoon")
- ran this command successfully: `xcodebuild -project Typhoon.xcodeproj -scheme "Typhoon OSX"`

When I try to run `carthage build --no-skip-current`, it just hangs, and stops, and produces no errors or logs.

The interesting thing is that there were a few times, where `carthage build --no-skip-current --platform mac` ran successfully, although I don't understand how.

I have tried integrating Typhoon in a sample project with the following Cartfile:
```
github "jozsef-vesza/Typhoon" "carthage-support"
```

The command I used:
```
carthage update --platform mac
```

The result is the same, the command hangs then stops, no errors, no logs.

I'm sure that I'm missing something obvious here, but I have no clue how to go on. Any help would be appreciated!

**Comment by ikesyo** [comment]
The version you are using is fairly old. Could you please update it by `brew update` and `brew upgrade carthage`, then try again?

**Comment by jozsef-vesza** [comment]
I am experiencing the same with 0.15.2.

**Comment by jozsef-vesza** [comment]
I just ran a test build again. Even though it appears to stop at xcodebuild, if I just let it sit there for a while, it starts to build, and eventually finds Typhoon and Typhoon OSX as well. Sorry for bothering you, the real issue here might be just me being impatient :sweat_smile:

**Comment by ikesyo** [comment]
Yeah, I tried `carthage build --no-skip-current` on that branch too and worked well. Closing. :smiley:
