### ISSUE TITLE
Issue After Upgrade to Xcode 7.3, ld failure 

### ISSUE THREAD

**Issue by pedantix** [Carthage/Carthage#1220]
Hi! I am new to carthage, it was working great before xcode 7.3 though, now I am getting a link failure with the following message. 

```sh
ld: warning: ignoring file ~/Library/Developer/Xcode/DerivedData/{app name}-dzriqjvxyycsjqakltbjomlrxtmh/Build/Products/Debug-iphonesimulator/Runes.framework/Runes, file was built for x86_64 which is not the architecture being linked (i386): ~/Library/Developer/Xcode/DerivedData/{app name}-dzriqjvxyycsjqakltbjomlrxtmh/Build/Products/Debug-iphonesimulator/Runes.framework/Runes

#note ${app name} is just a placeholder
```

Any guidance, thoughts, or ideas as to how to solve this issue would be great! thanks

**Comment by mdiep** [comment]
* What version of `carthage` are you using?
* Are you using binaries or specifying `--no-use-binaries`?
* Are you compiling your dependencies with `carthage` or adding their `.xcodeproj`s to your project?
* If you're compiling with carthage, have you run `carthage build` since you switched to Xcode 7.3?

**Comment by pedantix** [comment]
* 0.15.2
 * I am not specifying ```--no-user-binaries```
 * compiling dependencies with carthage
 * I have gone as far as clearing the carthage cache and project Carthage directory since updating to Xcode 7.3

thanks!

**Comment by mdiep** [comment]
Have you tried deleting that derived data directory?

Can you share a `Cartfile` that exhibits the problem?

**Comment by pedantix** [comment]
I just deleted the derived data directory, it got rid of the error now the iOS simulator is a blank white screen. App works well on iPhone 6/6s.. err well thanks for helping me! 
```
github "Alamofire/Alamofire" ~> 3.3
github "Alamofire/AlamofireImage" ~> 2.4
github "thoughtbot/Runes"
github "thoughtbot/Argo"
github "thoughtbot/Curry"
```

**Comment by mdiep** [comment]
I'm glad that worked! :sweat_smile:
