### ISSUE TITLE
`carthage update` isn't fetching dependencies specified by branch

### ISSUE THREAD

**Issue by kballard** [Carthage/Carthage#1223]
I'm having a really weird issue right now where Carthage refuses to fetch any dependencies that are specified by branch name. It doesn't produce any errors, it just skips fetching them. Even if I specify the dependency directly with `carthage update DepName` it still doesn't fetch the dependency.

This is happening with v0.15.2. It worked correctly with v0.14.0.

**Comment by ikesyo** [comment]
Sorry for the inconvenience, but fortunately this is already fixed in #1202.
