### ISSUE TITLE
SwiftyJson not recognized when use the mobile devise 

### ISSUE THREAD

**Issue by dimuth** [Carthage/Carthage#1225]
I have updated the Xcode to the latest version (7.3). and my mobile OS (9.3). I am using carthage and updated libraries also.

I could run my project in Xcode simulator without error. but when i try to run the project on my mobile devise it gives a JSON error.

Simulator version also 9.3

Use of undeclared type 'JSON'
Simulator version also 9.3

**Comment by mdiep** [comment]
Can you please give more detail about the error you're hitting?

**Comment by dimuth** [comment]
Error is "Use of undeclared type 'JSON'"

When run the app on my devise it does not recognize "JSON"

**Comment by mdiep** [comment]
Is that a compile-time error? Can you post a screenshot of Xcode?

**Comment by dimuth** [comment]
When i select the devise it gives above error where it have "JSON". but when i selects the simulator it works fine. 

Sorry, I could not have screen shot because i downgraded the Xcode version.
