### ISSUE TITLE
Carthage won't check out sub-dependencies

### ISSUE THREAD

**Issue by VictorVanDoom** [Carthage/Carthage#1231]
Hi,

I've been trying to integrate Carthage with one of my projects that uses quite a few jointly used sub-dependencies.

`Example:`
Root-project A uses dependency B, C and D where B is also used by C.

Right now I'll have to define the dependency B as part of my root-project risking that my version of B might not be the same as in the Cartfile of B. From the documentation I understood that sub-dependencies are pulled automatically, but if I remove B from my root-projects Cartfile it is no longer available in my checkout-folder.

`Side note:`
The dependencies are iOS Swift-Frameworks with B being linked to C as optional.
The root-project is a regular iOS Swift-App.
To checkout the dependencies I use the following command
```
carthage update --no-use-binaries --no-build
```

**Comment by ikesyo** [comment]
This might be a duplicate of #1230, Cartfile is not in the root directory of each dependencies, isn't it?

**Comment by VictorVanDoom** [comment]
@ikesyo Yes, thats exactly the problem. Than you. Don't know how I could miss that.
