### ISSUE TITLE
How do one suppress deprecation warnings from Carthage build?

### ISSUE THREAD

**Issue by idokleinman** [Carthage/Carthage#1234]

**Comment by mdiep** [comment]
Are you getting deprecation when build Carthage itself? Or building dependencies with Carthage?

Carthage itself hasn't been updated yet to avoid deprecation warnings. That will probably happen for the next release.

If your dependencies are giving you warnings, you'll need to update to new versions.

**Comment by idokleinman** [comment]
When building dependencies with Carthage..

Got a framework which uses good amount of elements that have been deprecated in iOS 9 and `carthage update` build log looks dirty, trying to avoid that till all deps are updated.
