### ISSUE TITLE
I'd love to enable Carthage for a project, but its framework name clashes with its main class name

### ISSUE THREAD

**Issue by fatuhoku** [Carthage/Carthage#1235]
I was looking at helping [MZFormSheetPresentationController](https://github.com/m1entus/MZFormSheetPresentationController) support Carthage.

This requires the creation of `MZFormSheetPresentationController.h` the public framework header.
But `MZFormSheetPresentationController.h` is already the header file for ``MZFormSheetPresentationController.m`. This is a name clash.

We could change the name of the framework but there's existing code whose imports look like `#import <MZFormSheetPresentationController/MZFormSheetPresentationController.h>` which in my opinion should not change at all just because we've changed the dependency manager.

So what are the options in these cases? Is the framework wrong to be called exactly the same name as the main class in it?

What's Carthage's take on this situation? @jspahrsummers

**Comment by tomguthrie** [comment]
You can add a custom module map that changes the name of the umbrella header:

```
framework module MZFormSheetPresentationController {
  umbrella header "MZFormSheetPresentationControllerUmbrella.h"

  export *
  module * { export * }
}
```

Put that in a `module.modulemap` file somewhere (next to the `Info.plist` probably) and then add the path to it in `Build Settings > Packaging > Module Map File`.

The `module.modulemap` Xcode creates for Swift frameworks is slightly different. I've never tried this with a Swift framework, but I imagine you need to include the second bit to be able to access Swift classes from ObjC etc:

```
framework module MyFramework {
  umbrella header "MyFramework.h"

  export *
  module * { export * }
}

module MyFramework.Swift {
    header "MyFramework-Swift.h"
}
```

**Comment by mdiep** [comment]
You should be able to use the existing header as the public framework header. That's what I did with [MDPSplitView](https://github.com/mdiep/MDPSplitView).

Otherwise, you can try using a custom module map. (But beware that Xcode caches them very aggressively. IME, you need to restart Xcode after changing a module map.)

If you hit any issues with these approaches, feel free to reopen the issue. :relaxed:
