### ISSUE TITLE
`carthage bootstrap` resulting in "GitHub API request failed: Maximum number of login attempts exceeded"

### ISSUE THREAD

**Issue by hamchapman** [Carthage/Carthage#1236]
* `carthage version`: 0.15.2
* `xcodebuild -version`: 7D175
* Are you using `--no-build`? n/a
* Are you using `--no-use-binaries`? n/a
* Are you using `--use-submodules`? n/a
* Relevant library: [pusher-websocket-swift (PusherSwift)](https://github.com/pusher-community/pusher-websocket-swift)

**Cartfile**
```
github "ashleymills/Reachability.swift"
github "krzyzanowskim/CryptoSwift"
github "daltoniam/Starscream"
```

**Carthage Output**
```
*** Cloning CryptoSwift
*** Cloning Reachability.swift
*** Cloning Starscream
*** Skipped downloading CryptoSwift.framework binary due to the error:
	"GitHub API request failed: Maximum number of login attempts exceeded. Please try again later."
*** Checking out CryptoSwift at "0.3.1"
*** Skipped downloading Starscream.framework binary due to the error:
	"GitHub API request failed: Maximum number of login attempts exceeded. Please try again later."
*** Checking out Starscream at "1.1.3"
*** Skipped downloading Reachability.swift.framework binary due to the error:
	"GitHub API request failed: Maximum number of login attempts exceeded. Please try again later."
*** Checking out Reachability.swift at "v2.3.3"
*** xcodebuild output can be found in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/carthage-xcodebuild.ACofmP.log
*** Building scheme "CryptoSwift watchOS" in CryptoSwift.xcodeproj
** BUILD FAILED **
The following build commands failed:
	CompileSwift normal armv7k /Users/travis/build/pusher/pusher-websocket-swift/Carthage/Checkouts/CryptoSwift/Sources/CryptoSwift/BlockMode/CipherBlockMode.swift
	CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
(2 failures)
A shell task failed with exit code 65:
** BUILD FAILED **
The following build commands failed:
	CompileSwift normal armv7k /Users/travis/build/pusher/pusher-websocket-swift/Carthage/Checkouts/CryptoSwift/Sources/CryptoSwift/BlockMode/CipherBlockMode.swift
	CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
(2 failures)
The command "carthage bootstrap" failed and exited with 1 during .
```

I'm not really sure why this has started happening but running `carthage bootstrap` now causes errors saying `"GitHub API request failed: Maximum number of login attempts exceeded. Please try again later."`. This seems to only happen on TravisCI, see one of the failing builds here: https://travis-ci.org/pusher/pusher-websocket-swift/jobs/120027278

**Comment by mdiep** [comment]
I'm not sure. Carthage doesn't hit a login endpoint. It just uses the credentials from git, if available, and tries to download releases. :confused:

**Comment by dcaunt** [comment]
I think this is due to rate limiting, even though the error message suggests otherwise. If you set a `GITHUB_ACCESS_TOKEN` environment variable (I'd use a secure one) does it work?

**Comment by hamchapman** [comment]
Adding a `GITHUB_ACCESS_TOKEN` env variable seems to have done the job. See here: https://travis-ci.org/pusher/pusher-websocket-swift/jobs/120574100

Thanks!
