### ISSUE TITLE
Cartfile.resolved outputs are different from the former ones

### ISSUE THREAD

**Issue by ikesyo** [Carthage/Carthage#1240]
I'm sorry that I didn't notice the change, as of #1197 outputs of GitHub repositories in `Cartfile.resolved` now looks like the following:

```
github "https://github.com/thoughtbot/Argo" "v2.3.0"
github "https://github.com/thoughtbot/Curry" "v1.4.0"
github "https://github.com/Quick/Nimble" "v3.2.0"
github "https://github.com/jdhealy/PrettyColors" "v3.0.2"
github "https://github.com/Quick/Quick" "v0.9.1"
github "https://github.com/antitypical/Result" "1.0.2"
github "https://github.com/jspahrsummers/xcconfigs" "ec5753493605deed7358dec5f9260f503d3ed650"
github "https://github.com/Carthage/Commandant" "0.9.0"
github "https://github.com/ReactiveCocoa/ReactiveCocoa" "v4.0.1"
github "https://github.com/Carthage/ReactiveTask" "0.9.1"
github "https://github.com/mdiep/Tentacle" "0.1.1"
```

Formerly those are written as “name with owner” format something like `github "thoughtbot/Argo" "v2.3.0"`. This is because of the `Tentacle.Repository.description` implementation: https://github.com/mdiep/Tentacle/blob/0.1.1/Tentacle/Repository.swift#L35-L36.

The old `GitHubRepository` implementation is:

```swift
extension GitHubRepository: CustomStringConvertible {
	public var description: String {
		let nameWithOwner = "\(owner)/\(name)"
		switch server {
		case .GitHub:
			return nameWithOwner

		case .Enterprise:
			return "\(server)/\(nameWithOwner)"
		}
	}
}
```

@mdiep Is this the expected change or a mistake?

**Comment by mdiep** [comment]
We should change this back. Good catch.

**Comment by ikesyo** [comment]
Thank you for the confirmation. Should this be handled on Carthage or Tentacle?

**Comment by mdiep** [comment]
I think we should do this in Carthage. I don't think it's a good idea to depend on the value of `description`.
