### ISSUE TITLE
I want my static library to support carthage, could I do it ?

### ISSUE THREAD

**Issue by huangminlinux** [Carthage/Carthage#1242]
* `carthage version`: 0.15
* `xcodebuild -version`: xocode 7.2
* Are you using `--no-build`?
* Are you using `--no-use-binaries`?
* Are you using `--use-submodules`?

I don't want to open source .So I have compiled a static library . and I want make it support carthage.
I know carthage'target only support dynamic framework.
I just wonder could I compile my static library to dynamic framework?

this is my project https://github.com/jpush/jpush-ios-carthage.git

**Comment by mdiep** [comment]
Instead of creating a static library, you should be able to create a dynamic framework. I don't know if you can convert an existing static library into a dynamic framework, but I doubt that you can.

**Comment by huangminlinux** [comment]
You mean that convert an existing static library into a dynamic framework is wrong way ?

**Comment by mdiep** [comment]
I mean, you can't convert a `.a` into a `.framework`. But you can update your project to create a `.framework` instead of a `.a`.
