### ISSUE TITLE
How does Carthage know which is the framework and which is the demo app?

### ISSUE THREAD

**Issue by fulldecent** [Carthage/Carthage#1247]
I have a framework:

https://github.com/fulldecent/carthage-example-framework

And a demo app:

https://github.com/fulldecent/carthage-example-app

They work great separately. But how do I combine them?

In CocoaPods times I would make a workspace and my podfile would just list the files that are exportable. In Carthage I am left wondering:

 * If the demo framework and demo app are the same repo, can I still use Carthage?
 * Is this documented?
 * How do other projects that depend on my framework know that they want the my framework and not my demo app?
 * Are there any best practices to look out for?

Sorry if this is pedantic. I want to do everything correctly because I want to contribute these two repositories to the project as a "best practices" example.

**Comment by mdiep** [comment]
> If the demo framework and demo app are the same repo, can I still use Carthage?

Yes. Carthage only builds shared dynamic framework schemes. If you want to include a demo app, it just can't include its own shared dynamic framework schemes. It can be in the same workspace as the framework or in its own.

If this is unclear from the documentation, a pull request would be very welcome!

**Comment by fulldecent** [comment]
@mdiep Thank you for the clarification. Just a couple more questions:

 * Will Carthage consider the root only or projects in any folder in a repository?
 * If there are multiple shared dynamic frameworks somewhere in that repository then what will happen?

**Comment by mdiep** [comment]
> Will Carthage consider the root only or projects in any folder in a repository?

Any folder in a repository.

> If there are multiple shared dynamic frameworks somewhere in that repository then what will happen?

It will build all of them.

**Comment by fulldecent** [comment]
Fixing a broken link. For a new example of EXACTLY EVERY STEP to create a new Swift project that you want to share with others using Carthage (and SPM and CocoaPods), see the RECIPE at:

https://github.com/fulldecent/swift3-module-template
