### ISSUE TITLE
Dependency "ThoMoNetworking" has no shared framework schemes

### ISSUE THREAD

**Issue by ryandary** [Carthage/Carthage#1248]
* `carthage version`: 0.15.2
* `xcodebuild -version`: Version 7.3 (7D175)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "ryandary/ThoMoNetworking" "master"
```

**Carthage Output**
```
*** Checking out ThoMoNetworking at "e7c32de0dc5043b95005f4d6ee98993310bd8234"
*** xcodebuild output can be found in /var/folders/m6/qn2rp9t54vdftvqxlcxq_fyw0000gn/T/carthage-xcodebuild.XVJdik.log
*** Skipped building ThoMoNetworking due to the error:
Dependency "ThoMoNetworking" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/ryandary/ThoMoNetworking/issues/new
```

I tried running "carthage update" at commit 1213870ec07e51efeb045d4fc79ac1228887bce6 of the above-mentioned repo.

At commit 8c43887f92a370331e879f4fc660593de0ed586e I updated the shared schemes.

**Comment by mdiep** [comment]
Try running `carthage fetch https://github.com/ryandary/ThoMoNetworking` and then building again. You're probably hitting #1191, which will be fixed in the next release.

**Comment by ryandary** [comment]
Yes, it does build now.  Thanks, and glad to know this will be fixed in next release.  Should I close this issue, or do you guys do that?
