### ISSUE TITLE
Carthage is stripping debug symbols when xcodebuild is not (maybe)

### ISSUE THREAD

**Issue by daku** [Carthage/Carthage#1252]
I can't explain why I am seeing .dSYM files for my Carthage builds when "Strip Linked Product" is set to "No" for my Debug builds. I don't see .dSYM files for the corresponding `xcodebuild`. See details below.

* `carthage version`: 
0.15.2
* `xcodebuild -version`: 
Xcode 7.3
Build version 7D175
* Are you using `--no-build`?
no
* Are you using `--no-use-binaries`?
no
* Are you using `--use-submodules`?
no

**Carthage Output**
```
$ carthage update --configuration Debug
...
*** xcodebuild output can be found in /var/folders/cv/9cr0ckh57dvfhw00hv0b4wt80000gq/T/carthage-xcodebuild.u4U6Rm.log
```

DETAILS:

**The output below shows that debug symbols are getting stripped(?) from frameworks even when "Strip Linked Product" is set to "No".**

This is where the framework was built (obtained from `cat /var/folders/cv/9cr0ckh57dvfhw00hv0b4wt80000gq/T/carthage-xcodebuild.u4U6Rm.log`)

```
... /Developer/Xcode/DerivedData/CloudSDK-hfuvdnbbpqmbeqauzkiwvnvkevst/Build/....
```

No dSYMs from `xcodebuild` for `CDKCore.framework` in the build directory:

```
$ ls -d /Users/adua/Library/Developer/Xcode/DerivedData/CloudSDK-hfuvdnbbpqmbeqauzkiwvnvkevst/Build/Products/Debug-iphoneos/CDKCore*
/Users/adua/Library/Developer/Xcode/DerivedData/CloudSDK-hfuvdnbbpqmbeqauzkiwvnvkevst/Build/Products/Debug-iphoneos/CDKCore.framework
```

However, dSYM exists in the carthage build directory:

```
adua-mac02:ios-thunderdome-testapp adua$ ls -d Carthage/Build/iOS/CDKCore*
Carthage/Build/iOS/CDKCore.framework      Carthage/Build/iOS/CDKCore.framework.dSYM
```

**Comment by mdiep** [comment]
Carthage creates a `.dsym` as part of the build process. But this doesn't mean that the debug symbols are being stripped from the framework.

**Comment by daku** [comment]
Great, just what i needed to know. Thank you for responding.
