### ISSUE TITLE
v0.16: Archiving an iOS App lists the app unter "Other Items"

### ISSUE THREAD

**Issue by patricks** [Carthage/Carthage#1259]
* `carthage version`: 0.16
* `xcodebuild -version`: Xcode 7.3 Build version 7D175
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? YES
* Are you using `--use-submodules`? NO

If I archive a project via Build -> Archive the archive is now listed unter "Other Items" and I am not able to upload anything to iTunes Connect.

I switched back to carthage version 0.15.2 now everything works again.

**Comment by ikesyo** [comment]
It seems that the problem is `bcsymbolmap`s and `dSYM`s are copied into `xcarchive`'s `Products` directory.

**Comment by Artwalk** [comment]
I have the same issue.

**Comment by TofPlay** [comment]
Same issue here. Thanks for the fix 👍 😊

**Comment by endotronic** [comment]
I'm still having this issue in Carthage 0.16.2. The dSYMs are being copied to Products/Applications in the xcarchive package. Any idea why? What information can I provide that could provide useful context?

**Comment by mjhpretorius** [comment]
@endotronic I am experiencing the same issue but with Xcode 7.3 and 0.16.2. When archiving my app it is showing up as a Generic Xcode Archive. I tried downgrading to 0.15.2 but am still seeing the same issue.

carthage version: 0.16.2
xcodebuild -version: Xcode 7.3 Build version 7D175
Are you using --no-build? No
Are you using --no-use-binaries? YES
Are you using --use-submodules? NO

**Comment by mdiep** [comment]
You may need to do a clean build—Xcode doesn't clean up files in `DerivedData` automatically, so your your archived build may still be picking up `bcsymbolmap`s and `dSYM`s.

While using 0.16.2, can you try deleting the `bcsymbolmap`s and `dSYM`s in `Carthage/Build/` and then archiving?

**Comment by endotronic** [comment]
That worked for me! I removed the dSYMs and did a clean build (I didn't have any bcsymbolmap files), and the package that resulted from the archive build was valid (as in, could be submitted to the app store). However, as you'd probably expect from the solution, it did not have symbols for any dependencies in the dSYMs folder (of the package). The only dSYM there was for the application itself.
