### ISSUE TITLE
Carthage not checking out right commit SHA until manual fetch

### ISSUE THREAD

**Issue by lcoderre** [Carthage/Carthage#1266]
**Problem**

Basically:   `carthage update`, `checkout`, `bootstrap`  all didn't point at the right commit (master) when fetching the repo.  After a `carthage fetch git@github.com:MyOrg/someTroublesomeRepo.git`, the next command successfully checked out the right commit (for master branch). 

Between every try I did `git clean -xfd` in order to clean my Cartfile.* and Cartfile/*
Thanks guys.

**Info**
* `carthage version`: 0.16 (also buggy on 15.3 before I updated. Rest of the team using 14.x is ok)
* `xcodebuild -version`: Xcode 7.3   Build version 7D175
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "MyOrg/someTroublesomeRepo" "master"

# other 3rd party repos
```

**Error Carthage Output**
```
*** Skipped downloading someTroublesomeRepo.framework binary due to the error:
	"API rate limit exceeded for ........ (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"
*** Checking out someTroublesomeRepo at "2c808b4319fa397ae9dc3d6263b520565790b0d1"
```

**Good Carthage Output**
```
*** Skipped downloading someTroublesomeRepo.framework binary due to the error:
	"API rate limit exceeded for ........ (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"
*** Checking out someTroublesomeRepo at "0cb93dab7ed2e7577b75a561bb8ebc8cd99e26af"
```

**Comment by mdiep** [comment]
1. What `carthage` command are you running?
2. Does `carthage` output a `*** Fetching` line?
3. What are the permissions of `~/Library/Caches/org.carthage.CarthageKit`?

**Comment by lcoderre** [comment]
1. In order: `update`, `checkout` (but not the right use case, so error'ed), `bootstrap`, `fetch`, `bootstrap`
2. Yes
3. `drwxr-xr-x`  *BUT* I removed it yesterday to clean up the cache and retry 😨  (but it worked for now 👊) .

**Comment by regis-leray** [comment]
1.  ```carthage update --no-use-binaries --use-ssh --platform iOS --configuration Debug```
2. 
```
** Fetching CSwiftV
*** Fetching Quick
*** Fetching Nimble
*** Fetching SwiftDate
*** Checking out CSwiftV at "44a432c0cb883fbc04b3c0845af80beb770ded70"
*** Checking out Nimble at "1a9e53e2d74363e1d6320a87a5028bc234c9a4d4"
*** Checking out Quick at "4f3ab19ebb2ebaf8d55f5950aee9eb696b14c351"
*** Checking out SwiftDate at "f492c98bfb25e3fc99b08673541ca3c643887a03"
*** xcodebuild output can be found in /var/folders/20/6w8yfj9d3x7gwcxh_tk4nxt80000gn/T/carthage-xcodebuild.5iLmFM.log
*** Building scheme "CSwiftVIOS" in CSwiftV.xcodeproj
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Quick-iOS" in Quick.xcworkspace
*** Building scheme "SwiftDate-iOS" in SwiftDate.xcodeproj
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
```

3. ```ls -alh ~/Library/Caches | grep CarthageKit``` 
 rwxr-xr-x   4 regis  staff   136B  7 Mar 14:59 org.carthage.CarthageKit

**Comment by jerryzhoujw** [comment]
I have got this problem with `carthage update` on Carthage(0.25.0), and fixed by removing the lib in ~/Library/Caches/org.carthage.CarthageKit/dependencies/<the lib name> . then do the `carthage update` again.
