### ISSUE TITLE
Bitcode incompatibility for XCTest dependent frameworks on tvOS and watchOS

### ISSUE THREAD

**Issue by phatblat** [Carthage/Carthage#1268]
I'd like to discuss the possibility of better Carthage support for test frameworks on platforms that require bitcode.

* `carthage version`: 0.16
* `xcodebuild -version`: Xcode 7.3, Build version 7D175

## Situation

Apps built for a tvOS device are required to be built with bitcode. This causes problems for frameworks like Quick and Nimble that link to XCTest as it does not contain bitcode.

**Carthage Output**
```
$ carthage build --no-skip-current --platform tvos
*** xcodebuild output can be found in /var/folders/96/rcjvzrkn5lzfl0_krn8c151h0000gn/T/carthage-xcodebuild.TE6TlH.log
*** Building scheme "Quick-tvOS" in Quick.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Ld /Volumes/DerivedData/Quick-dshynvhuyaarriayewbsnvjxqrux/Build/Products/Release-appletvos/Quick.framework/Quick normal arm64
(1 failure)
ld: warning: Auto-Linking supplied '/Applications/Xcode7.3.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode7.3.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE) or obtain an updated library from the vendor
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/phatblat/dev/ios/pods/Quick/Quick.xcworkspace -scheme Quick-tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Ld /Volumes/DerivedData/Quick-dshynvhuyaarriayewbsnvjxqrux/Build/Products/Release-appletvos/Quick.framework/Quick normal arm64
(1 failure)
```

Whenever we get [XCTest on watchOS](https://openradar.appspot.com/21760513) this will be an issue there as well.

These frameworks are not intended to be included with apps submitted to the app store. It would be nice if they could be included in device builds for local development testing. However, for platforms other than OS X, their primary environment is the various platform simulators.

## Affected Frameworks

- Quick/Nimble#213
- Quick/Quick#422

This is a total Catch-22 situation that Apple has put us in and I'm hoping that Carthage can make it a little less painful.

There are [workarounds](https://github.com/Quick/Nimble/issues/213#issuecomment-202496390) to this issue. Also, if Apple ever relaxes the bitcode requirement on tvOS and watchOS or adds bitcode to the XCTest framework, this will become a non-issue.

## Proposal

It is incredibly convenient for development that Carthage builds fat binaries with both device and simulator slices. However, when building a unit testing framework for a platform that requires bitcode this is a bit of a problem.

Since there is not presently a way to tell Carthage to only build for simulator architectures, what if the framework project's `ENABLE_BITCODE` setting of `NO` plus the combination of a platform that requires bitcode (`tvOS` and `watchOS`) were to disable generating the device architecture slices?

### Example tvOS Framework

- platform: `tvOS`
- `ENABLE_BITCODE`: `YES`
- generated slices: `x84_64`, `arm64`

### Example tvOS Test Framework

- platform: `tvOS`
- `ENABLE_BITCODE`: `NO`
- generated slices: `x84_64`

### Example watchOS Framework

- platform: `watchOS`
- `ENABLE_BITCODE`: `YES`
- generated slices: `i386`, `armv7k`

### Example watchOS Test Framework

- platform: `watchOS`
- `ENABLE_BITCODE`: `NO`
- generated slices: `i386`

Setting `ENABLE_BITCODE` to `NO` in most cases is an error on these platforms so I could see Carthage generating some sort of "are you sure?" warning. This approach seems simpler to me than something fancy like detecting that the framework links to XCTest or some other framework that isn't built with bitcode.

**Comment by mdiep** [comment]
Doesn't Xcode throw a fit if you set `ENABLE_BITCODE` to no for these platforms? Can that be set to no for testing frameworks?

**Comment by phatblat** [comment]
It does, but only when building for a device. Here I've added a User-Defined build setting of `ENABLE_BITCODE`=`NO`

![screen shot 2016-04-13 at 8 22 29 am](https://cloud.githubusercontent.com/assets/28851/14496626/f4f166e2-0150-11e6-8f0a-eb984f73adfa.png)

When the destination is a simulator it doesn't care about this setting.

![screen shot 2016-04-13 at 8 25 32 am](https://cloud.githubusercontent.com/assets/28851/14496713/55e51106-0151-11e6-8436-33f4cd05871a.png)

**Comment by mdiep** [comment]
That sounds like a good plan to me then! 👍

**Comment by phatblat** [comment]
Sweet! I'll take a stab at implementing this.
