### ISSUE TITLE
Argument to build only iOS or OS X targets

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#127]
Building a large dependency graph can take some time. If you know that you'll only need the frameworks for a particular platform, the process could be expedited with a flag like `--platform Mac` or something like that.

**Comment by jspahrsummers** [comment]
Split the Cartfile option out into #262. This issue can encompass _just_ the command line flag.

**Comment by wbarksdale** [comment]
My issue here is that if carthage builds frameworks 1 & 2, in that order, and I only need framework 2, if carthage fails to build framework 1, i'm SOL

**Comment by ikesyo** [comment]
@wbarksdale Why not specify `--platform iOS`?

**Comment by drosenstark** [comment]
For those of us who just got here from the Internet, @ikesyo is giving you a legit command

`carthage build --platform iOS?`

Which is great if you need to avoid a platform like tvOS. Check your Carthage/Build directory to see the output.

**Comment by martnst** [comment]
as just comment here from the Internet, is there an option to specify it in the Cartfile?

**Comment by drosenstark** [comment]
@martnst you mean to specify the platform in the Cartfile? I'm pretty sure there isn't.

**Comment by martnst** [comment]
Yes, as I am working on a simple iOS app there is no need to wast time on building for macOS or tvOS.

**Comment by martinlindhe** [comment]
a Makefile would be a good fit for project-specific build commands like these. no need to extend the Cartfile

**Comment by capnslipp** [comment]
@wbarksdale How about two `Cartfile`s in two directories named `macOS` & `watchOS`, each with their own `.xcodeproj`?  The codebase could still be shared (outside of those two dirs), and there could still be a `.xcworkspace` for general programming & building either-or.

**Comment by ZaBlanc** [comment]
Would love to see this as well, though no Makefiles. Keep it simple. Just allow an option for the entire Cartfile to only build for X platforms. Ala:

platform :ios, :tvos

**Comment by mehdico** [comment]
I'm using
**carthage update --platform macOS**
but it's built for all platforms!

my Cartfile contents:

**github "realm/realm-cocoa"**

**Comment by capnslipp** [comment]
@mehdico Currently, the `build` command supports `--platform` while the `update` command does not.  So the way to accomplish that is with `carthage update --no-build && carthage build --platform macOS`.

_Like all command-line stuff, you could create a tiny script to macro this as `carthage-update-and-build --platform macOS` or something like that with a bash script not much more complicated than `cathage update --no-build && carthage build "$@"`._
