### ISSUE TITLE
Carthage builds leaf node dependencies of prebuilt frameworks 

### ISSUE THREAD

**Issue by jgraves** [Carthage/Carthage#1270]
* `carthage version`: 0.16.2
* `xcodebuild -version`: 7.3
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
 
Carthage is building dependencies of prebuilt frameworks that aren't referenced anywhere else in the project.

**Comment by ikesyo** [comment]
Dependencies of prebuilt frameworks would be not necessarily prebuilt frameworks, so those would be built if required.

**Comment by mdiep** [comment]
Yeah, you still need to include the dependencies of prebuilt frameworks in your app.

**Comment by jgraves** [comment]
that makes sense. thanks!
