### ISSUE TITLE
carthage update fails if you don't pair the iOS Simulator with watchOS

### ISSUE THREAD

**Issue by sprint84** [Carthage/Carthage#1275]
* `carthage version`:  0.16.2
* `xcodebuild -version`: Xcode 7.3 Build version 7D175
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

I found this issue reported in other repos, such as Alamofire, but I couldn't find the issue listed here. Sorry if I'm posting a dup.

So the problem is, if you remove your simulators from the Devices window, and re-add just the ones you need (e.g. iOS Simulator 9.3), `carthage update` can fail for some repositories that require watchOS or tvOS builds.

The workaround for that is to go to your Simulators list and make sure you have at least one iOS Simulator paired with an watchOS Simulator. Or to run `carthage update --platform "iOS"`every time.

I'm not sure what the possible solutions for this, or even if it is possible for carthage to check that pairing (I don't understand why it is necessary).
Maybe you should consider the possibility to specify in the `Cartfile` the platform it should always build for, skipping the others. Or skip the watchOS/tvOS/OSX builds if they fail and continue with the next package?

Throwing out ideas, here.

**Cartfile**
```
github "yeahdongcn/UIColor-Hex-Swift" ~> 2.1
```

**Carthage Output**
```
sprint-mbp:Example sprint$ carthage update
*** Fetching UIColor-Hex-Swift
*** Checking out UIColor-Hex-Swift at "2.1"
*** xcodebuild output can be found in /var/folders/06/dgpth9f15tsb1r1_j34528x40000gn/T/carthage-xcodebuild.7WlqSJ.log
*** Building scheme "HEXColor-watchOS" in HEXColor.xcodeproj
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/sprint/Documents/iPhone_projects/Example/Carthage/Checkouts/UIColor-Hex-Swift/HEXColor.xcodeproj -scheme HEXColor-watchOS -configuration Release -sdk watchsimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by mdiep** [comment]
> Maybe you should consider the possibility to specify in the Cartfile the platform it should always build for, skipping the others

That's been suggested in #356.

> Or skip the watchOS/tvOS/OSX builds if they fail and continue with the next package?

That's been suggested in #864.

I don't think there's really anything for us to do here. Since the suggestions have been covered by other issues, I'm going to go ahead and close this.
