### ISSUE TITLE
How to deal with copy-frameworks for a debug-only framework?

### ISSUE THREAD

**Issue by mrubin** [Carthage/Carthage#1284]
* `carthage version`: 0.9.4
* `xcodebuild -version`: 7D175 

I would like one of my frameworks to be debug-only. That is, when I am making a Release build, I don't want that framework in my .app. By leaving it in the `/usr/local/bin/carthage copy-frameworks` step at all, it's being copied.

What are some strategies for not copying over a given framework for a Release build? Thank you.

**Comment by mdiep** [comment]
That's a very old version of `carthage`. You should consider upgrading. :smile:

Your best bet is probably to add a Run Script phase that checks if it's a Release build and deletes the copy of the framework. Carthage doesn't have a built-in way to handle that scenario.

**Comment by mrubin** [comment]
Thanks on both counts! Having separate Run Script phases is working fine.

**Comment by Performat** [comment]
@mrubin I'm not yet a jedi master of run scripts (WIP) but I think I'm on the right way! 

Xcode fails to compile bitcode after deleting the framework in my run script, would you please consider posting yours?
