### ISSUE TITLE
Derived Data Location

### ISSUE THREAD

**Issue by calebd** [Carthage/Carthage#1285]
Is there any reason Carthage couldn't put its derived data in a local folder instead of the Xcode default? Clearing global derived data breaks Xcode when products are compiled outside of a given Xcode project and I don't remember to use the new build flag every time. If that is not a valid option, could a Cartfile option or environment variable be used that would allow the behavior to be automatic?

**Comment by mdiep** [comment]
No, there's not. #459 has been open for a while to cover the idea of a per-project derived date. There's also a `--derived-data` command-line option that was added in a recent version.
