### ISSUE TITLE
Carthage Help, Suggestion, Feedback

### ISSUE THREAD

**Issue by hardikdevios** [Carthage/Carthage#1288]
>First of all i am not pointing anything to any support Teams or devs of Carthage, Its just what i have observe and want things to be better if possible.nothing personal :)

Ok So, I have started **Carthage** over **Cocoapods** for a quite while now and its really awesome and its improve my build time which is +1 for me.
But some of the things which may don't know or might not be possible to do with **Carthage**.

_**One more thing i have searched some threads for the issues that i am having but due to threads getting longer i am not getting exact output so it may possible that i am already adding those point which already been closed, but its become hard to search and please forgive me if the question was asked too much before, My idea behind this to help those who has just started using Carthage but may need some help and my be there issue get solved by just checking this thread**_

# 1. Fetching things 

> Command : 
`carthage update netfox --platform iOS`

![fetching only which i update](https://cloud.githubusercontent.com/assets/6657591/14941095/6a6a757a-0fad-11e6-9669-cc1e06194010.png)

- As you can see that i want to just update `netfox` lib only but its still fetching all other things and i know it wont download later on it will just update only that lib so is it possible to fetch only `netfox` lib and skip other.

# 2. Warning from libs
![screen shot 2016-05-01 at 3 19 13 pm](https://cloud.githubusercontent.com/assets/6657591/14941183/5aca3fda-0fb0-11e6-9f42-0b37d93179c7.png)

- Not having much issue with this, But can we do any thing during building schema to make it silent not to be verbose because it increase scrolling and hard to check the sequence sometime.

# 3. Run script and input file

![screen shot 2016-05-01 at 3 30 05 pm](https://cloud.githubusercontent.com/assets/6657591/14941224/ab281dac-0fb1-11e6-8e15-3eaeb2d77487.png)

- This part of **Carthage** is bit annoying sometime not in terms of adding those lines everytime during new lib but its becoming very tough to maintain that . 
Reason is that if we remove any lib from our **Cartfile** we have to search and remove those manually and also if the lib which we are removing having 2-3 more submodules at that time it become very tough to check which submodules of that lib was having and have to remove all this manually. if we can do this with some short of script or something which is possible to make it easy ?

# 4. Number of Terminal commands

> Command : 
`carthage help`

![screen shot 2016-05-01 at 3 54 56 pm](https://cloud.githubusercontent.com/assets/6657591/14941355/26e8247a-0fb5-11e6-8e3a-f83cba0ca7f6.png)

- So far so good, But i want to know other commands to be display in the help documentation as well, if possible. for e.g. `--platform iOS`, which might don't know and may fix problem for someone.Let me know if any page which have listed all the commands

**Comment by mdiep** [comment]
> As you can see that i want to just update netfox lib only but its still fetching all other things and i know it wont download later on it will just update only that lib so is it possible to fetch only netfox lib and skip other.

That's a known bug (#1081). I've been wanting to fix it, but have been busy reviewing PRs and responding to issues here and on other repositories. ☺️ Pull requests welcome!

> Not having much issue with this, But can we do any thing during building schema to make it silent not to be verbose because it increase scrolling and hard to check the sequence sometime.

There's not currently an option for that, but I'd be amenable to one.

> if we can do this with some short of script or something which is possible to make it easy ?

This is being discussed in #1131.

> But i want to know other commands to be display in the help documentation as well, if possible. for e.g. --platform iOS, which might don't know and may fix problem for someone.Let me know if any page which have listed all the commands

That's an option, not a command. `carthage help` will give you the available commands. `carthage help update` will give you the list of options for `carthage update`, which includes `--platform iOS`.

**Comment by hardikdevios** [comment]
@mdiep
**Thanks mate for your time and detail explanation to each of my concerns.**

1. I will make PR if i get time.
2. No problem i am also open for the discussion for that.
3. I have read the discussion its somewhat same so i just want to ask is it good idea to put in **"Embedded Binaries"** instead of **Run-script**, in this way we don't have to maintain the Run-Script every time. Don't know much about that never put any app for submission with **"Embedded Binaries"** so don't know much about the pros and cons on this.
4. Very great-full this solved my issue, If you can add this last in README.md it may help others for sure by knowing the other options just a suggestion. I know people are expert now a days but sometimes due to having multiple issue for e.g.bugs or too many projects they may forget the basics so by adding this in README.md might help the others.

**Comment by mdiep** [comment]
> 2. No problem i am also open for the discussion for that.

Want to open a separate issue for that?

> 3. I have read the discussion its somewhat same so i just want to ask is it good idea to put in "Embedded Binaries" instead of Run-script, in this way we don't have to maintain the Run-Script every time. Don't know much about that never put any app for submission with "Embedded Binaries" so don't know much about the pros and cons on this.

The `copy-frameworks` command works around [this App Store issue](http://www.openradar.me/radar?id=6409498411401216).

> 4. Very great-full this solved my issue, If you can add this last in README.md it may help others for sure by knowing the other options just a suggestion

Would you be up for opening a PR to do this?

---

I'm going to go ahead and close this since most of these are covered by other issues. But it's also better to keep issues single-focused.
