### ISSUE TITLE
Carthage and define 

### ISSUE THREAD

**Issue by TofPlay** [Carthage/Carthage#1290]
* `carthage version`: 0.16.1
* `xcodebuild -version`:  Xcode 7.3 Build version 7D175
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
Original version
```
github "PureLayout/PureLayout" == 3.0.1
github "tristanhimmelman/AlamofireObjectMapper" == 3.0.0
github "stripe/stripe-ios" == 6.2.0
github "algolia/algoliasearch-client-swift" == 2.3
github "ashleymills/Reachability.swift" == 2.3.3
github "realm/realm-cocoa" == 0.98.7

```
On `Xcode > Project > Build Settings > Swift Compiler - Custom Flags > Other Swift Flags > Debug` I define `-DPURELAYOUT`
Can I create a Cartfile like the following?
```
#if PURELAYOUT
github "PureLayout/PureLayout" == 3.0.1
#endif
github "tristanhimmelman/AlamofireObjectMapper" == 3.0.0
github "stripe/stripe-ios" == 6.2.0
github "algolia/algoliasearch-client-swift" == 2.3
github "ashleymills/Reachability.swift" == 2.3.3
github "realm/realm-cocoa" == 0.98.7
```

**Comment by mdiep** [comment]
Carthage doesn't support anything like this, but there has been talk of adding some form of per-project settings (#1126).

**Comment by TofPlay** [comment]
@mdiep do you some documentations about per-project settings?

**Comment by mdiep** [comment]
Per-project settings haven't been implemented. They've just been proposed.

**Comment by TofPlay** [comment]
Ok :)
