### ISSUE TITLE
Expected time for Carthage Copy script

### ISSUE THREAD

**Issue by hardikdevios** [Carthage/Carthage#1291]
- `carthage version`: 0.16.2
- `xcodebuild -version`: 
  Xcode 7.3
  Build version 7D175

This is more likely question rather than a issue.
How much time we should expect for this script to run?

> `/usr/local/bin/carthage copy-frameworks`

I am having Almost **1 minute** each time i compile. is it something normal or something not common ?

**Here is the screen shot with Input files**
![screen shot 2016-05-03 at 12 44 13 am](https://cloud.githubusercontent.com/assets/6657591/14965037/bebf21d6-10c8-11e6-861c-c6596484116a.png)

**And here is the screen shot of time affected with this script**
![screen shot 2016-05-03 at 12 39 20 am](https://cloud.githubusercontent.com/assets/6657591/14965087/0b268622-10c9-11e6-9961-78bae62732e0.png)

If its something uncommon please give me any tips which can help me to improve this time.
Does something **"Run script while installing only"** or is it having too many 3rd party Libs causing   build time slow?  
**_Let me know if i am expecting too much from carthage.Happy Coding_**

**Comment by mdiep** [comment]
That does seem like a long time. It's mostly copying the frameworks, which depends on your disk speed. Do you have an SSD?

We could try parallelizing it, but it might be disk bound already.

**Comment by hardikdevios** [comment]
I am having 7200 rpm Harddisk normal not SSD. so i guess issue is from my side 
Is there any thing which i can verbose in this script? I mean what is happening in this script. Because i was not having this issue before and i am afraid some lib or something else is causing.

**Comment by hardikdevios** [comment]
I have did something This and remove 

> "/usr/local/bin/carthage copy-frameworks"

![screen shot 2016-05-03 at 3 51 18 pm](https://cloud.githubusercontent.com/assets/6657591/14980556/0dddee22-1147-11e6-93eb-abfe015f28e3.png)

I have added one **Copy files phase** and referenced those binary with this and **Code sign on copy** is already checked. 
This is successfully Archived and completed the process in fraction of seconds.

Now what is the difference in both of them does my **ipa** not approved by Apple as i have not added a workaround of Copy-frameworks? or it will approved by Apple but this is not a Recommended solution ?

**Comment by mdiep** [comment]
`copy-frameworks` works around [this AppStore issue](http://www.openradar.me/radar?id=6409498411401216). Carthage frameworks have both device and simulator code. The app store won't accept frameworks that have simulator code in them, so `copy-frameworks` strips it out.

You could develop with an ordinary `Copy Files` phase, but you'll need to use `copy-frameworks` when you submit to the app store.

**Comment by hardikdevios** [comment]
I have done some more Debug 
![screen shot 2016-05-04 at 3 19 50 pm](https://cloud.githubusercontent.com/assets/6657591/15010828/ec194d3e-120b-11e6-9569-eabab20c34bd.png)
Its copy `DSYM` files every time and the Folder size is almost **150-160 MB **got replace which does take some time, Can we disable the `.dSYM` file for in Debug mode ? and only enable for release ? anything to cheer about this mate because i am almost stuck in this.

**Comment by mdiep** [comment]
> Can we disable the .dSYM file for in Debug mode ? and only enable for release ?

The `.dSYM` files let you step through the code in your dependencies. That's pretty important.

I think your best bet is a caching strategy like #1222.

**Comment by hardikdevios** [comment]
Well @mdiep i love the approach of `--cache-builds` will be a huge for **Carthage** for sure. i am eagerly waiting for this  feature. I don't know if somebody have this issue or not, or might be all are using **_SSD_** lols. But my request is to you that keep open this issue until `--cache-builds` or any other workaround because if somebody have this issue i hope no body would have but just in case someone have large amount of dependencies and still may face and may have some workaround, then It will help me a lot. Because i wont be going back to **Cocoapods** for this issue. Well All i can say, Good luck 👍

**Comment by sunhao92** [comment]
I have got the same problem. And I found that "carthage version" taken 1 min too. So I guess the reason is that my network is not connected to the Internet. After my mac connecting to the Internet, "carthage copy-framework" become fast.

**Comment by ikesyo** [comment]
Closing this in favor of #1810 and #1841.
