### ISSUE TITLE
carthage bootstrap silently fails when attempted for a package which does not yet exist in Cartfile.resolved

### ISSUE THREAD

**Issue by mz2** [Carthage/Carthage#1292]
I'm not sure if this is intentional behaviour, but `carthage bootstrap` silently fails when attempted for a package which does not yet exist in Cartfile.resolved. I can understand that it would not behave normally if for instance the principle is that `carthage bootstrap` should never as a side effect modify `Cartfile.resolved`. But at least it should then give me a clear error message that I should first do something else (like `carthage update`?).

I'm happy to resolve this myself if you tell me what (if anything) should be done about it, and some pointers of the places I am expected to change.

**Comment by mdiep** [comment]
We definitely shouldn't fail silently. An error message that says (1) that the dependency doesn't exist in `Cartfile.resolved` and (2) you may want to use `update` seems totally in order.

A PR would be great! I think you'll want to start by looking at [`Bootstrap.swift`](https://github.com/Carthage/Carthage/blob/master/Source/carthage/Bootstrap.swift).

**Comment by ikesyo** [comment]
Closed by #1294.
