### ISSUE TITLE
Import not working: File not found

### ISSUE THREAD

**Issue by itinance** [Carthage/Carthage#1293]
* `carthage version`: 0.16.2
* `xcodebuild -version`: Xcode 7.3.1
* Are you using `--no-build`? Don't know
* Are you using `--no-use-binaries`? Don't know
* Are you using `--use-submodules`? Don't know

**Cartfile**
```
github "mutualmobile/MMWormhole" ~> 2.0.0
```

**Carthage Output**
```
$ carthage update
*** Fetching MMWormhole
*** Checking out MMWormhole at "2.0.0"
*** xcodebuild output can be found in /var/folders/qh/1pzf72wj3dqd2c14dfsdh39r0000gn/T/carthage-xcodebuild.nddzqS.log
*** Building scheme "MMWormhole-Mac" in MMWormhole.xcodeproj
*** Building scheme "MMWormhole-iOS" in MMWormhole.xcodeproj
```

I followed all the steps mentioned in the readme (see screenshots) to use the framework MMWormhole. But when i wanted to import the "MMWormhole.h", i get "File not found".

![screen shot 2016-05-04 at 20 11 22](https://cloud.githubusercontent.com/assets/1758597/15024303/a44ca158-1234-11e6-93fd-0df6cbd99bbd.png)

![screen shot 2016-05-04 at 20 11 33](https://cloud.githubusercontent.com/assets/1758597/15024315/ac21b99a-1234-11e6-9879-05928e8cc3ec.png)

![screen shot 2016-05-04 at 20 11 38](https://cloud.githubusercontent.com/assets/1758597/15024321/b14973a4-1234-11e6-9469-3e1cc3ea5218.png)

![screen shot 2016-05-04 at 20 11 57](https://cloud.githubusercontent.com/assets/1758597/15024325/b4f043a2-1234-11e6-9217-6dff126ad328.png)

![screen shot 2016-05-04 at 20 12 08](https://cloud.githubusercontent.com/assets/1758597/15024329/b7689120-1234-11e6-8d44-b5f0772052f1.png)

In StartViewController.c

```
#import "StartViewController.h"
#import "MMWormhole.h"

```
I don't know if it's a bug or missing (wrong?) documentation or stupid misinterpreting all this on my side?

**Comment by mdiep** [comment]
> But when i wanted to import the "MMWormhole.h", i get "File not found".

Can you show where you've done that?

**Comment by itinance** [comment]
In StartViewController.c

```
#import "StartViewController.h"
#import "MMWormhole.h"

```

**Comment by ikesyo** [comment]
You should do as follows: `#import <MMWormhole/MMWormhole.h>`
