### ISSUE TITLE
Dependency "IOS-DFU-Library" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by t2wu** [Carthage/Carthage#1295]
* `carthage version`:  0.16.2
* `xcodebuild -version`:  Xcode 7.3
Build version 7D175
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "t2wu/IOS-DFU-Library"
```

**Carthage Output**
```
*** Fetching IOS-DFU-Library
*** Checking out IOS-DFU-Library at "v1.0.1"
*** xcodebuild output can be found in /var/folders/3m/1ck8851d549f71p9ljftx_lw0000gp/T/carthage-xcodebuild.Xa8XpH.log
*** Skipped building IOS-DFU-Library due to the error:
Dependency "IOS-DFU-Library" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/t2wu/IOS-DFU-Library/issues/new
```

The IOS-DFU-Library is from https://github.com/NordicSemiconductor/IOS-DFU-Library. I noticed that it does not have a shared scheme. So I fork it and create it. But the error persists.

**Comment by ikesyo** [comment]
Your changes are not included in any tagged releases but only in `master`. So you should specify the branch in your Cartfile: `github "t2wu/IOS-DFU-Library" "master"`

**Comment by t2wu** [comment]
Thank you so much for your help. So quickly as well!
