### ISSUE TITLE
docs on migrating from pod

### ISSUE THREAD

**Issue by tcurdt** [Carthage/Carthage#1305]
* `carthage version`: 0.16.2
* `xcodebuild -version`: Xcode 7.3.1, Build version 7D1014
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
NA
```

**Carthage Output**
```
NA
```

To me it's not clear form the docs how I can turn a `podspec` like [this](https://github.com/CocoaPods/Specs/blob/master/Specs/TestFairy/1.7.4/TestFairy.podspec.json) into something consumeable by Carthage. There must be some documentation I am missing.

**Comment by mdiep** [comment]
I don't think we have any documentation that's specific to podspecs. But there is [documentation](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework) for supporting Carthage for your framework.

It's a pretty simple process:

1. Share your Xcode schemes
2. Resolve build failures
3. Tag stable releases
4. (Optionally) Archive prebuilt frameworks into one zip file

If you have specific questions, we can try to help.

**Comment by tcurdt** [comment]
Well, the pod points to:

  http://app.testfairy.com/ios-sdk/TestFairySDK-1.7.4.zip

Given that's a static library it's not even supported via Carthage, right?
If they built and released it as a framework - how would one point to that zip?
I know `github` and `git` is supported inside a `Cartfile` ([but that's it - isn't it](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md)?).

**Comment by mdiep** [comment]
> Given that's a static library it's not even supported via Carthage, right?

That's correct. Carthage only supports dynamic frameworks.

> If they built and released it as a framework - how would one point to that zip?
> I know github and git is supported inside a Cartfile (but that's it - isn't it?).

Yes, that's right.

The one option for distributing pre-compiled frameworks is to attach them to GitHub Releases. You could create an empty GitHub repository for your app and create Releases that have the `.frameworks` attached.

**Comment by tcurdt** [comment]
Thanks for the quick answers, @mdiep.

Is there a plan to at least change the later?

Having to create a git repo for a pre-compiled framework zip feels very very cumbersome. Being able to specify a zip file directly would be nice.

**Comment by mdiep** [comment]
There's no plan, but there's been some discussion (#722).

The issue is that if there's no way to discover versions, then there's very little benefit to using Carthage.
