### ISSUE TITLE
Carthage `--use-submodules` creates dirty submodule repos

### ISSUE THREAD

**Issue by scott-ce** [Carthage/Carthage#1306]
* `carthage version`: 0.16.2
* `xcodebuild -version`: 7.3.1 (701014)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? Yes

**Cartfile**
```
# None
```

**Cartfile.private**
```
# NSLogging
github "CareEvolution/NSLogger" "CEVAdditions"

# Testing only
github "erikdoe/ocmock" ~> 3.2
github "luisobo/Nocilla" ~> 0.10.0
```

**Carthage Output**
```
*** Fetching Nocilla
*** Fetching NSLogger
*** Fetching ocmock
*** Checking out Nocilla at "0.10.0"
*** Checking out NSLogger at "a9b6d0c1a90c60f085a064c184728d3ce0d5a79c"
*** Checking out ocmock at "v3.3"
*** xcodebuild output can be found in /var/folders/z3/c0qb1jxs6msct09g_sx96vhr0000gn/T/carthage-xcodebuild.biOl24.log
*** Building scheme "Nocilla" in Nocilla.xcworkspace
*** Building scheme "NSLogger" in NSLogger.xcodeproj
*** Building scheme "OCMock iOS" in OCMock.xcodeproj
```

This came up in issue #263, which was closed. However, my issue isn't with a relative vs. absolute Carthage/Build symlink created in the submodule directories. The problem is that the symlink is created at all, which marks the dependency's submodule as dirty and prevents committing the parent repo.

Is there any reason why this symlink needs to be created?

```bash
# After running carthage update --use-submodules --platform iOS...
$ git diff Carthage
diff --git a/Carthage/Checkouts/NSLogger b/Carthage/Checkouts/NSLogger
--- a/Carthage/Checkouts/NSLogger
+++ b/Carthage/Checkouts/NSLogger
@@ -1 +1 @@
-Subproject commit a9b6d0c1a90c60f085a064c184728d3ce0d5a79c
+Subproject commit a9b6d0c1a90c60f085a064c184728d3ce0d5a79c-dirty
diff --git a/Carthage/Checkouts/Nocilla b/Carthage/Checkouts/Nocilla
--- a/Carthage/Checkouts/Nocilla
+++ b/Carthage/Checkouts/Nocilla
@@ -1 +1 @@
-Subproject commit c8251035339da2a7216a10f2ee54d452994d4411
+Subproject commit c8251035339da2a7216a10f2ee54d452994d4411-dirty

$ git submodule foreach 'git status'
Entering 'Carthage/Checkouts/NSLogger'
HEAD detached at a9b6d0c
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Carthage/

nothing added to commit but untracked files present (use "git add" to track)
Entering 'Carthage/Checkouts/Nocilla'
Not currently on any branch.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Carthage/

nothing added to commit but untracked files present (use "git add" to track)
Entering 'Carthage/Checkouts/ocmock'
Not currently on any branch.
nothing to commit, working directory clean
```

OCMock does not have this issue because it includes `Carthage` in its .gitignore file.

In #263 @jspahrsummers mentioned that he adds Carthage's Build folder to his global .gitignore, but we would like to commit built frameworks in our parent repo to track them. And it might be helpful to mention this issue in the submodule section of the README.

**Comment by mdiep** [comment]
The dependencies may need access to their dependencies inside `Carthage/Build`. Personally, I recommend that frameworks ignore that folder.

> In #263 jspahrsummers mentioned that he adds Carthage's Build folder to his global .gitignore, but we would like to commit built frameworks in our parent repo to track them. And it might be helpful to mention this issue in the submodule section of the README.

You should try adding it to your global `.gitignore` but adding a `!/Carthage/Build` rule to your parent repo's `.gitignore`. I'm not sure whether that will work, but it might.

**Comment by scott-ce** [comment]
If I worked by myself, then changing my global gitignore would be an easy solution. But of course I don't, and anything that requires a change to the global .gitignore means that anyone who needs to build this repo with submodules also needs to change their global settings.

Unless I'm missing something… it sounds as though there are only 3 viable options?

 1. Always use `--use-submodules --no-build` together, and add all our dependencies as subprojects. I know people do this, but it got confusing quickly for us, especially when an internal framework is a dependency for an app and an intermediate framework. Xcode ended up with multiple copies of source files.

 2. Avoid `--use-submodules`. Unfortunately this makes working with internal dependencies much more difficult (per issue #177).

 3. Go back to Cocoapods or script our own submodule solution.

**Comment by mdiep** [comment]
> I know people do this, but it got confusing quickly for us, especially when an internal framework is a dependency for an app and an intermediate framework. Xcode ended up with multiple copies of source files.

This shouldn't happen if your intermediate framework builds its dependency through a workspace.

```
Intermediate.xcodeproj -- Contains shared scheme to build Intermediate.framework
Intermediate.xcworkspace -- Contains Intermediate.xcodeproj and Internal.xcodeproj
```

But why don't you add `Carthage/Build/` to the `.gitignore` of the intermediate project?

**Comment by scott-ce** [comment]
Our intermediate project is a workspace, but the dependent projects are nested within the main project of that workspace. It sounds as though you are recommending putting dependent projects at the top level, so the intermediate xcodeproj can be included without any nested dependencies. However, we would lose the ability to use Xcode's automatic handling of target dependencies, since those can only reference targets found within within the same project. Have you done this along with `--no-build`, and do you need to manually build each target in order in Xcode and/or configure this by hand in each of your build schemes?

>  But why don't you add Carthage/Build/ to the .gitignore of the intermediate project?

That doesn't affect the duplicate source files (if dependent projects are nested), and it doesn't solve the original problem because the .gitignore of the intermediate project cannot override how the submodule views the auto-generated Carthage/Build folder. We could give up trying to include Carthage/Build in git, but these paths still get created in the submodules for external dependencies too.

I looked into wrapping the `carthage bootstrap|update` call in a script that uses `git submodule foreach` to post-process and manually delete the Carthage/Build symlinks. I noticed that any repo which does have Carthage/Build committed to the repo also gets replaced by a symlink and assume this is to ensure the same framework is used by the main app and any dependencies and resetting the HEAD to override the symlink and use the committed frameworks could create issues.

**Comment by mdiep** [comment]
> Our intermediate project is a workspace, but the dependent projects are nested within the main project of that workspace. It sounds as though you are recommending putting dependent projects at the top level, so the intermediate xcodeproj can be included without any nested dependencies.

Basically, yes. The intermediate project should have an `xcodeproj` and an `xcworkspace`. The `xcodeproj` has implicit references to dependencies and has to be included in another workspace or project. The `xcworkspace` exists to develop the project by itself and includes the required dependencies.

> However, we would lose the ability to use Xcode's automatic handling of target dependencies, since those can only reference targets found within within the same project.

That's not true. If you add the dependencies as siblings in the workspace, then the `xcodeproj` can form references to the dependencies that will be resolved by the workspace. If you then include the `xcodeproj` in a different project or workspace that also includes those dependencies, everything will work correctly.

> Have you done this along with --no-build, and do you need to manually build each target in order in Xcode and/or configure this by hand in each of your build schemes?

I have done this. It's the setup that many of our open source projects follow. [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa) and [Tentacle](https://github.com/mdiep/Tentacle), for example.

No manual editing is required. Just drag the projects into your workspace and go. (You do still have to configure your project to use it.) This setup simultaneously supports using `--build`.

> That doesn't affect the duplicate source files (if dependent projects are nested), and it doesn't solve the original problem because the .gitignore of the intermediate project cannot override how the submodule views the auto-generated Carthage/Build folder. We could give up trying to include Carthage/Build in git, but these paths still get created in the submodules for external dependencies too.

If all of your projects include `Carthage/Build/` in their `.gitignore`, then you won't have any dirty submodules.

**Comment by scott-ce** [comment]
> If you add the dependencies as siblings in the workspace, then the xcodeproj can form references to the dependencies that will be resolved by the workspace. If you then include the xcodeproj in a different project or workspace that also includes those dependencies, everything will work correctly.

Thanks for the explanation. I've been using Xcode for years, but never realized it can [implicitly discover dependencies within a workspace](https://developer.apple.com/library/ios/featuredarticles/XcodeConcepts/Concept-Workspace.html#//apple_ref/doc/uid/TP40009328-CH7-DontLinkElementID_2) if they aren't explicitly defined in a target's build phase.

I tried this approach with `--no-build` and it seems to be working. The only downside seems to be that some third party projects export several project build schemes, but we can probably live with manually hiding them.

Thanks again.
