### ISSUE TITLE
 Umbrella header not found for OHHTTPStubs since XCode 7.3.

### ISSUE THREAD

**Issue by kanekin** [Carthage/Carthage#1309]
I came across with an error when building my test using OHHTTPStubs v5.0.0.

When I build `OHHTTPStubs ` with `carthage update --platform ios`, the build completes successfully. However, when I build the test which has dependency to OHHTTPStubs, I get the following error:
```
<MY_PROJECT>/Carthage/Checkouts/OHHTTPStubs/OHHTTPStubs/Supporting Files/module.modulemap:2:19: error: umbrella header 'OHHTTPStubsUmbrella.h' not found
  umbrella header "OHHTTPStubsUmbrella.h"
                  ^
<unknown>:0: error: could not build Objective-C module 'OHHTTPStubs'
```
I find it strange that the error is caused by a missing file in `/Carthage/Checkouts/` folder. I am not sure why the project is looking for a file in `/Checkouts` during build process.

Just to add some information, I have never had problem with OHHTTPStubs until v5.0.0, possibly because the previous releases had a pre-built framework. The reason that the latest release does not have the prebuild framework is to provide compatibility for the projects in both of XCode 7.2 and XCode7.3. (also explained in the [issue](https://github.com/AliSoftware/OHHTTPStubs/issues/168) on OHHTTPStubs repo.)

I would very much appreciated, if anyone could provide any tips or insightful information, since I am not very familiar with what Carthage does under the hood. 
Thanks in advance. :)

* `carthage version`: 0.15.2
* `xcodebuild -version`:  7.3.1 (7D1014)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "realm/realm-cocoa" == 0.98.6
github "JustHTTP/Just" == 0.4.4
github "krzyzanowskim/CryptoSwift" == 0.2.2
github "kanekin/JSONSchemaValidation" == 1.5.0
github "SwiftyJSON/SwiftyJSON" == 2.3.3
github "AliSoftware/OHHTTPStubs" == 5.0.0
```

**Carthage Output** (Omitting outputs from unrelated repos)
```
*** Fetching OHHTTPStubs
*** Checking out OHHTTPStubs at "5.0.0"
*** xcodebuild output can be found in /var/folders/_1/_qbj0z3j4qq3hf07j4knn_jr0000gn/T/carthage-xcodebuild.rTWAgU.log
*** Building scheme "OHHTTPStubs iOS Framework" in OHHTTPStubs.xcworkspace
*** Building scheme "OHHTTPStubs" in OHHTTPStubsDemo.xcworkspace
```

**Comment by mdiep** [comment]
That's odd. The OHHTTPStubs module map even specifies `OHHTTPStubs-umbrella.h` as the umbrella header. (That's different than the header your error suggests.)

What are the search path build settings for your unit test target? (`Framework Search Paths`, `Header Search Paths`, `Library Search Paths`)

You could also try searching for `Carthage/Checkouts` in the build settings for your unit test target to see if anything comes up.

**Comment by kanekin** [comment]
Thanks for the reply.

**Framework Search Paths**:
```
$(PROJECT_DIR)/Carthage/Build/iOS
```
**Runpath Search Paths**
```
@loader_path/Frameworks
@executable_path/Frameworks
$(PROJECT_DIR)/Carthage/Build/iOS
```
**Header Search Paths**
```
```

I will post the updates about adding `Carthage/Checkouts` in search path, when I test it.

**Comment by mdiep** [comment]
I'm not sure what's going on. It's hard to tell without seeing your project.

Your best bet at this point is to either:

1. Try adding OHHTTPStubs to your project again from scratch. Maybe you missed a step when you added it the first time?

2. Create a small project that exhibits the problem so you can share it.

**Comment by kanekin** [comment]
Making a small project to share sounds like a good idea.
I will be offline now until the end of tomorrow, so I will post the updates within 2 days.
Thx.

**Comment by kanekin** [comment]
Hi @mdiep, I created a small project and built OHHTTPSubs with a new small project, and the problem does not appear. So I think the problem is in my project settings. Sorry for not trying this before posting the question.
I will investigate further and post the updates.

**Comment by devValley** [comment]
@kanekin I encountered the same issue. Any updates on this?

**Comment by kanekin** [comment]
@devValley Yes. I forgot to post the updates. Thanks for the reminder.
I looked through the settings for my test target, and I found `../**` in ```User Header Search Paths```.
This was causing XCode to look everything under the parent directory of the test directory.
I removed `../**` from ```User Header Search Paths```, and the test was built successfully.
