### ISSUE TITLE
Create a framework with dependencies that does not support Carthage

### ISSUE THREAD

**Issue by TofPlay** [Carthage/Carthage#1315]
## Carthage
* `carthage version`:  0.16.2
* `xcodebuild -version`:  Xcode 7.3.1 Build version 7D1014
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

## Define `MyFramework`
I created a framework that has the following file Cartfile:
```
github "Alamofire/Alamofire" == 3.4.0
github "Hearst-DD/ObjectMapper" == 1.2.0
github "tristanhimmelman/AlamofireObjectMapper" == 3.0.0
github "stripe/stripe-ios" == 6.2.0
github "algolia/algoliasearch-client-swift" == 2.3
github "realm/realm-cocoa" == 0.102.1
```
This framework need also some others frameworks but unfortunately these frameworks are not compatible with Carthage 😢. I'm obliged to use Cocoapods and I defined a Podfile like this:
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'MyFramework iOS' do
  pod 'OneSignal', '1.13.2'
end

target 'MyFramework iOS Firebase' do
  pod 'OneSignal', '1.13.2'
  pod 'Firebase', '2.5.1'
end
```

When I build my framework manually I execute the following commands:
```
$ pod install
$ carthage update --platform iOS
```
Everything works well

## Use `MyFramework` with a project

Now I want to use `MyFramework` with a project. So I set a Cartfile like this one:
```
github "WorldCompagny/MyFramework" == 1.0.0
```
When I execute the command:
```
$ carthage update --platform iOS
```
I have this error:
```
cd "/WorldCompany/MyProject/Carthage/Checkouts/MyFramework"
    /bin/sh -c \"/Users/me/Library/Developer/Xcode/DerivedData/MyFramework-ewystxrihdfgriagevtvfcwjrent/Build/Intermediates/MyFramework.build/Release-iphoneos/MyFramework\ iOS.build/Script-E9E21DF5F548A3205B19EF4C.sh\"
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
## My question
How can I specify in the Cartfile file to launch the command `pod install` before carthage build MyFramework for my project?

**Comment by mdiep** [comment]
You basically have 2 options:

1. Add `pod install` as a run script phase to your target. This will require all users of your framework have cocoa pods installed.

2. Check the artifacts from CocoaPods into your repository so that you don't need to run `pod install` before building.

**Comment by TofPlay** [comment]
@mdiep following I add the section `🔷 Run Pod Install if necessary` my build phases:
![image](https://cloud.githubusercontent.com/assets/1082222/15464472/e2d8da6e-20cf-11e6-8222-3d220278cb03.png)

CocoaPods generate this error:
![image](https://cloud.githubusercontent.com/assets/1082222/15464541/4a8c2012-20d0-11e6-8579-89743333e2de.png)
`export LANG=en_US.UTF-8` is already define on my script

Anyway I don't think is good solution to add script in build phases to run `pod install` because `pod install` will change the project itself that xcodebuild is currently executing 

`pod install` must be executed before xcodebuild build the project
Only carthage can run a script before xcodebuild is launch. And I guess that only place we can specify to Carthage to run a command is under the Cartfile.
