### ISSUE TITLE
Missing required modules while running the dynamic library in another application

### ISSUE THREAD

**Issue by priyapy** [Carthage/Carthage#1316]
carthage version: 0.16.2
xcodebuild -version: Xcode 7.3.1 Build version 7D1014
Are you using --no-build? No
Are you using --no-use-binaries? No
Are you using --use-submodules? No

**Cartfile**
```
github "Alamofire/Alamofire" ~> 3.3
github "Hearst-DD/ObjectMapper" ~> 1.2
github "DaveWoodCom/XCGLogger" ~> 3.3
github "SwiftyJSON/SwiftyJSON"
github "krzyzanowskim/CryptoSwift"
github "iosdevzone/IDZSwiftCommonCrypto"
github "ashleymills/Reachability.swift"
github "ViccAlexander/Chameleon"
github "Alamofire/AlamofireImage" ~> 2.0
github "akosma/SwiftMoment"
```

I am creating a dynamic framework which contains all this frameworks. My dynamic framework got build properlly. But when i use my dynamic framework in my app project I am getting the following error 

> Missing required modules : 'Alamofire','XCGlogger','SwiftMoment','AlamofireImage','Chameleon','Reachability','IDZSwiftCommonCrypto','CryptoSwift','SwiftyJSON','ObjectMapper'

Do i have to do anything extra to link my carthage> build > ios frameworks into my project

**Comment by mdiep** [comment]
You need to include all of those frameworks in your project as well. Carthage should build them for you and place them in `Carthage/Build/iOS`.

**Comment by priyapy** [comment]
yes , i have added these frmeworks to "linked frameworks and binaries a" and also i have added them to copy files in Build settings. Even then i am getting this error. 

Just for info I am attaching the screen shot of my framework structure.
<img width="808" alt="screenshot 2016-05-21 21 53 26" src="https://cloud.githubusercontent.com/assets/15901889/15449595/96dca6e4-1f9f-11e6-8224-c1182ad80012.png">

**Comment by priyapy** [comment]
Why these module folder is missing inthis structure? can you help me out for this

**Comment by mdiep** [comment]
Your framework shouldn't nest frameworks—don't copy them into the framework bundle. Instead, your application should copy the framework and its dependencies into its bundle.

**Comment by priyapy** [comment]
@mdiep  can you be little more specific on this point

**Comment by mdiep** [comment]
There are instructions [in the README](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application).
