### ISSUE TITLE
`scheme` argument not escaped

### ISSUE THREAD

**Issue by danielgindi** [Carthage/Carthage#1318]
* `carthage version`: 0.16.2
* `xcodebuild -version`: 7.3
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Carthage Output**
```
cd Charts && carthage bootstrap  
Cloning ios-snapshot-test-case  
Skipped downloading ios-snapshot-test-case.framework binary due to the error:  
Maximum number of login attempts exceeded. Please try again later.  
Checking out ios-snapshot-test-case at "2.1.1"  
*** xcodebuild output can be found in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/carthage-xcodebuild.9gsod9.log  
*** Building scheme "FBSnapshotTestCase iOS" in FBSnapshotTestCase.xcworkspace  
*** Building scheme "FBSnapshotTestCase tvOS" in FBSnapshotTestCase.xcworkspace  

** BUILD FAILED **





The following build commands failed:

	Ld /Users/travis/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-bxqdwtzedguggmawxzyipupldvjd/Build/Products/Release-appletvos/FBSnapshotTestCase.framework/FBSnapshotTestCase normal arm64

(1 failure)

A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/travis/build/danielgindi/Charts/Charts/Carthage/Checkouts/ios-snapshot-test-case/FBSnapshotTestCase.xcworkspace -scheme FBSnapshotTestCase tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:

** BUILD FAILED **
```

It seems like the `scheme` argument is not escaped. "FBSnapshotTestCase tvOS" should be quoted, as the space separates a new argument...

Also - `BITCODE_GENERATION_MODE=bitcode` is also causing trouble. It requires core frameworks to include bitcode which they don't... If I run this command locally I get an interesting error.

**Comment by ikesyo** [comment]
This should be closed by https://github.com/facebook/ios-snapshot-test-case/pull/169 and #1280.

**Comment by ikesyo** [comment]
https://github.com/facebook/ios-snapshot-test-case/pull/169 is merged. Closing.

**Comment by mdiep** [comment]
Are we escaping the scheme though? That seems like an important thing to do regardless.

**Comment by ikesyo** [comment]
Since `xcodebuild` did start a build, a space-containing scheme name were successfully passed  to the command (that should be handled in `NSTask.arguments`). What I wanted to say is that the original question is not the reason for the build failure.

If this should be a problem, that is in a `description` implementation of `Task` in `ReactiveTask`: https://github.com/Carthage/ReactiveTask/blob/0.10.0/ReactiveTask/Task.swift#L49-L53. Does changing the impl to the following make sense?

```swift
extension Task: CustomStringConvertible {
	public var description: String {
		return "\(launchPath) \(arguments.map { $0.stringByReplacingOccurrencesOfString(" ", withString: "\\ ") }.joinWithSeparator(" "))"
	}
}
```

**Comment by ikesyo** [comment]
Or

```swift
extension Task: CustomStringConvertible {
	public var description: String {
		let arguments = self.arguments.map { argument -> String in
			if argument.containsString(" ") {
				return "\"\(argument)\""
			} else {
				return argument
			}
		}
		return "\(launchPath) \(arguments.joinWithSeparator(" "))"
	}
}
```

**Comment by ikesyo** [comment]
The original build failure is fixed by https://github.com/facebook/ios-snapshot-test-case/pull/169. Quoting space-containing arguments in a task description should be handled in ReactiveTask.

**Comment by ikesyo** [comment]
Submitted a PR in ReactiveTask: https://github.com/Carthage/ReactiveTask/pull/63
