### ISSUE TITLE
version compatibility

### ISSUE THREAD

**Issue by ehuynh** [Carthage/Carthage#1319]
* `carthage version`: 0.15.2
* `xcodebuild -version`: Xcode 7.2
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "foo/bar" ~> 1.0.0
```

**Carthage Output**
```
Checking out bar at "1.1.0"
```

I have a question around what is considered a compatible version when using `carthage update`. I expected by doing `carthage update bar` that i would update to 1.0.x  (something like e.g. 1.0.1), but instead it updated to `1.1.0`.

I had a read of the https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#version-requirement but it didn't really make sense to me what compatibility meant in my scenario.  

 My intention is to only update to patch version. Is this possible in carthage?

**Comment by mdiep** [comment]
> My intention is to only update to patch version. Is this possible in carthage?

No, it is not. Carthage expects packages to follow [semantic versioning](http://semver.org). That determines which packages are compatible.

**Comment by ehuynh** [comment]
thanks 👍
