### ISSUE TITLE
Ability to skip building dependencies with `carthage build`

### ISSUE THREAD

**Issue by mz2** [Carthage/Carthage#1320]
It would be great if during development I could skip building the dependencies of a package I've asked `carthage build` to build. Here's an example:

```
mz2@mpro ~/P/Manuscripts> carthage build --platform mac Extensions
*** xcodebuild output can be found in /var/folders/sz/f5rfb5nx0svg8v85ngcw47z80000gn/T/carthage-xcodebuild.JoPx8Z.log
*** Building scheme "Freddy" in Freddy.xcodeproj
*** Building scheme "MPRateLimiter" in MPRateLimiter.xcodeproj
*** Building scheme "MPTimer" in MPTimer.xcodeproj
*** Building scheme "OHHTTPStubs Mac Framework" in OHHTTPStubs.xcworkspace
*** Building scheme "RegexKitLite" in RegexKitLite.xcodeproj
*** Building scheme "SWXMLHash OSX" in SWXMLHash.xcworkspace
*** Building scheme "Extensions" in Extensions.xcodeproj
```

In actual fact I know in this case that the dependencies are unchanged and will be resolved just fine by the `Extensions` build, which I'd like to complete as fast as possible.

(`Extensions` is a framework target which has six Carthage expressed dependencies itself).

Perhaps I am missing some already existing flag?

**Comment by mdiep** [comment]
There's not such a flag, but there's been a proposal to add caching in #1222.
