### ISSUE TITLE
Placement of carthage copy-frameworks run script

### ISSUE THREAD

**Issue by cutz** [Carthage/Carthage#1321]
Having read and followed the instructions in the README on [building for ios](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos), I was still running into the dreaded invalid architectures error when submitting builds to iTunes connect.  I eventually tracked my issue down to the copy-frameworks run script being run prior to "Embed Frameworks" build phase.  In hindsight it seems obvious that copy-frameworks needs to occur after "Embed Frameworks" but it took me longer than I care to admit to figure that out.  Perhaps it might help others to include a sentence in the README that explicitly states where in the build phases the copy-frameworks step needs to be placed.

**Comment by ikesyo** [comment]
A Run Script phase of `carthage copy-frameworks` is a replacement for "Embed Frameworks".
