### ISSUE TITLE
[Question] What is the proper way to consume .framework files without Carthage

### ISSUE THREAD

**Issue by Iftahh** [Carthage/Carthage#1322]
I've built my framework using carthage and integrating it into an example project worked great.

However, how do I distribute it to non-Carthage users?
I can give them the .framework files that were created in Carthage/Build/iOS folder -  but how should I instruct the non-Carthage users to integrate it into their project?

The instructions I followed here https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos assume the user has Carthage installed.

I can't tell the non-Carthage users to add a run script "`/usr/local/bin/carthage copy-frameworks`" because they don't have Carthage installed...

**Comment by Iftahh** [comment]
Reading http://code.hootsuite.com/an-introduction-to-creating-and-distributing-embedded-frameworks-in-ios/
It seems you can just add the .framework files to the "Embedded Binaries" section and for iOS projects and it works just fine, with no problems with app submission.

Perhaps you should update the docs to just add the frameworks to the "Embedded Binaries" if you are using Xcode 7+

**Comment by mdiep** [comment]
`copy-frameworks` is needed because because of an [App Store submission bug](http://www.openradar.me/radar?id=6409498411401216). We wouldn't want to remove those instructions without confirmation that you can submit fat frameworks to the app store.

**Comment by Iftahh** [comment]
I believe the blog post I referenced mentions this bug (or maybe a very similar bug?) 
See http://code.hootsuite.com/an-introduction-to-creating-and-distributing-embedded-frameworks-in-ios/#xcode  
He says this issue was resolved at Xcode 6.3.2

**Comment by dmvjs** [comment]
I have submitted fat frameworks to iTunes Connect successfully (using the kodmunki approach https://kodmunki.wordpress.com/2015/09/22/ios-9-universal-cocoa-touch-frameworks/). Also there is no App Rejection Code for frameworks being rejected for having debug slices. https://developer.apple.com/app-store/review/guidelines/

This doesn't mean that in the future this won't still become an issue again however, the first line of updates in the hootsuite link says that the "bug" resurfaced in 7.1

**Comment by Iftahh** [comment]
Doh!
@dmvjs you are right, I forgot about that comment at the top.

So I'll have to instruct users of the framework to install Carthage and update their project settings ?!
Or tell them to add slice removal build scripts?

Or do you think its better I supply two .framework files - one with Simulator arch and one without?
And if this is a good idea - how would the consumer specify one framework to use for debugging and another to use for release?  (sorry for the newbie questions...)

**Comment by dmvjs** [comment]
@Iftahh The kodmunki approach (URL above^^^) gives you a Release and Debug folder and uses $CONFIGURATION to pick which one gets used when. IMO it's the simplest approach for now.

**Comment by Iftahh** [comment]
Thank for your help.
