### ISSUE TITLE
Unable to build enterprise Carthage module that contains public github dependencies

### ISSUE THREAD

**Issue by jonbrooks** [Carthage/Carthage#1323]
I am developing a framework for distribution through a private Enterprise Github instance.  This framework has its own Cartfile with dependencies that are hosted on github.  In order for a project to include my framework, a host project must use the `--use-ssh` flag, but this seems to cause the checkout of the framework's dependencies from succeeding.

So, it seems the Cartfile of the framework will only work without the `--use-ssh` flag, but the Cartfile of the host app will only work with the `--use-ssh` flag.  

Is there a way to have some dependencies be checked out ussing ssh but not others?  Or have a Cartfile specify how its dependencies should be checked out?

* `carthage version`: 0.11.0
* `xcodebuild -version`:  Xcode 7.3.1 Build version 7D1014
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no 
* Are you using `--use-submodules`? no

**Cartfile**
(Of Framework:)
```
github "mxcl/PromiseKit" ~> 3.2

github "swisspol/GCDWebServer" ~> 3.2.5

#github "ZipArchive/ZipArchive"
github "GWStuartClift/ZipArchive" "carthage-support"

github "drmohundro/SWXMLHash" ~> 2.1

github "jonbrooks/HockeySDK-iOS" "carthage"

github "jonbrooks/MenuItemKit" "carthage"

github "isalkind/JTSImageViewController" "carthage"

github "jonbrooks/Firebase-Carthage.git" "master"

github "krzyzanowskim/CryptoSwift"

github "jonbrooks/JSONWebToken.swift" "Carthage-iOS"

github "jonbrooks/ObjCTryCatch" "master"
```

host app Cartfile:
```
github "https://my.enterprise.github.instance.com/my-framework" "my-branch"
```

**Carthage Output**
```
*** Fetching my-framework
*** Fetching ObjCTryCatch
*** Fetching JSONWebToken.swift
A shell task failed with exit code 128:
Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by jonbrooks** [comment]
I have verified that first checking out the enterprise repo by other means, and then using a host app Cartfile without `--use-ssh` using the local file urls builds successfully:
```
git "file:///Users/me/temp/my-framework" "my-branch"
```

This isn't really a workable solution, but I thought this might be useful information

**Comment by mdiep** [comment]
> So, it seems the Cartfile of the framework will only work without the --use-ssh flag, but the Cartfile of the host app will only work with the --use-ssh flag.

There's not, no. `--use-ssh` is currently all or nothing.

But you should be able to add an SSH key to GitHub.com and then clone with Carthage. If you can close from both GitHub.com and your Enterprise instance with the same authentication type, then you should be able to do so with Carthage.
