### ISSUE TITLE
Carthage multi archive

### ISSUE THREAD

**Issue by czaku** [Carthage/Carthage#1331]
Hi guys,

Is it possible to do multi archive of carthage frameworks so that there is one .zip file generated with all required frameworks?

Thanks

**Comment by mdiep** [comment]
```
$ carthage help archive
Archives built frameworks into a zip that Carthage can use

[--output (string)]
	the path at which to create the zip file (or blank to infer it from the first one of the framework names)

[--project-directory (string)]
	the directory containing the Carthage project

[--color (color)]
	whether to apply color and terminal formatting (one of ‘auto’, ‘always’, or ‘never’)

[[]]
	the names of the built frameworks to archive without any extension (or blank to pick up the frameworks in the current project built by `--no-skip-current`)
```


You can also create a `.zip` yourself. Carthage just examines the contents and doesn't what the structure is.

**Comment by czaku** [comment]
I meant for my project, for all frameworks I have could I potentially zip them all so that carthage build would be using the local .zip file? Because all the documentation mentions is Github-Release. 

So let's assume I am using `SomeA.framework` and `SomeB.framework` I zip them up into `carthage.framework.zip` and place the zip file in my project directory, then whenever I call `carthage build` or `carthage update` it is using the zip file instead of building everything over again. It is to shorten the build time on the CI environment which currently takes just too long.

**Comment by mdiep** [comment]
Ah, okay! There's not a way to do that, but there are a couple projects that let you cache builds:

- https://github.com/guidomb/carthage_cache
- https://github.com/146BC/RomeBuild

**Comment by czaku** [comment]
Thanks @mdiep and sorry for not being clear at the beginning :)
