### ISSUE TITLE
carthage update     ERROR:GitHub API request failed: NetworkError

### ISSUE THREAD

**Issue by CNiceToUpp** [Carthage/Carthage#1334]
* `carthage version`: 0.16.2

**Cartfile**
```
github "ReactiveCocoa/ReactiveCocoa" ~> 3.0
```

**Carthage Output**
```
HCdeMacBook-hechao:Calculate hechao$ carthage update
*** Cloning ReactiveCocoa
*** Cloning Result
*** Cloning Box

`GitHub API request failed: NetworkError(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7ff2c2d134f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://api.github.com/repos/robrix/Box/releases/tags/1.2.2?, NSErrorFailingURLKey=https://api.github.com/repos/robrix/Box/releases/tags/1.2.2?, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.})`

```
before executing `carthage update`,I execute `brew update`.but `brew update` ERROR, so I uninstall brew,and I install brew again,than I install carthage by `brew install carthage`

**Comment by mdiep** [comment]
It looks like the request to GitHub just timed out. If you try again, do you get the same error?

**Comment by CNiceToUpp** [comment]
@mdiep yes,I think so.but I try in home and in company，but I get same error.

**Comment by CNiceToUpp** [comment]
@mdiep yes,I think so.but I try in home and in company, but I get same error.

**Comment by mdiep** [comment]
What happens if you try to run `curl https://api.github.com` on the command line?

**Comment by pfitz** [comment]
Got the same problem here.

**Comment by pfitz** [comment]
For me the problem solved itself. Seems there where an outage on Github.

**Comment by Asteroidhaha** [comment]
same problem “GitHub API request failed: NetworkError(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSURLSessionDownloadTaskResumeData=<CFData 0x7fb132e305e0 [0x7fff75f55440]”

**Comment by mdiep** [comment]
This indicates that you have a network connectivity issue. This could be due to:

1. A GitHub outage
2. A flaky/down LAN connection
3. A flaky/down WAN connection
4. Faulty proxy
