### ISSUE TITLE
Can Carthage build fat framework

### ISSUE THREAD

**Issue by domrotX** [Carthage/Carthage#1342]
Hello. I have just started using Carthage and I am really happy with it's simplicity. I have created a Swift framework project and I am about to consume it in an app, using Carthage. I have noticed that Carthage offers the ability to strip off x86/i386 slices from fat binaries.  However I miss the ability to let Carthage automatically creates fat binaries when building a framework. Is this a possible extensions or do I have to create custom scripts using lipo?

**Comment by mdiep** [comment]
Carthage automatically builds fat binaries if you use `carthage build`—built frameworks will support the device and the simulator. You don't need to opt-in to this.

Is that what you're asking?

**Comment by domrotX** [comment]
Hello. Yes, you got the question right. For some strange reason, the first framework project  tried to build did only include the armv7 and arm64 slices. The next framework I tried with worked as expected, so there must be some issue in my first project causing this.  Thanks for your reply!
