### ISSUE TITLE
Outdated not working as expected

### ISSUE THREAD

**Issue by schjonhaug** [Carthage/Carthage#1343]
* `carthage version`: 0.16.2
* `xcodebuild -version`: 7.3.1 (7D1014)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "Alamofire/Alamofire" == 3.4.0
```
**Carthage Output**
```
*** Fetching Alamofire
All dependencies are up to date.
```

However, AlamoFire is at version 3.4.1: https://github.com/Alamofire/Alamofire. If I update the Cartfile to 3.4.1 and run carthage install, it fetches and builds the correct version.

**Comment by ikesyo** [comment]
This is captured in #1260. Could you please track the issue? Closing. 😉
