### ISSUE TITLE
issue with dyld: Symbol not found: __TMPdCSs18_HeapBufferStorage

### ISSUE THREAD

**Issue by stefat** [Carthage/Carthage#1349]
* `carthage version`: 0.6.12
* `xcodebuild -version`: Xcode 7.3 Build version 7D175
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
github "UrbanApps/Armchair"
**Cartfile resolved**
github "UrbanApps/Armchair" "0.1.2"

**Carthage Output**
<..>$ carthage update
*** Fetching Armchair
*** Downloading Armchair.framework binary at "0.1.2"
*** xcodebuild output can be found in /var/folders/xx/zhysw05j1pn9jw3vypwb3rrw0000gn/T/carthage-xcodebuild.ky9ANZ.log```

[Carthage.zip](https://github.com/Carthage/Carthage/files/318207/Carthage.zip)

#####################################################################
I was having at first an issue with an 'image not found' message as I missed to add the framework library (Armchair) in the Embed Frameworks section of Build Phases (Xcode 7.3). 
Done that I was happily waiting the sw run but I also got an unexpected 'symbol not found' error message:

`dyld: Symbol not found: __TMPdCSs18_HeapBufferStorage
  Referenced from: /Users/<..>/Library/Developer/Xcode/DerivedData/JotAgenda-gazubqkikzwwstckckciztnqufsb/Build/Products/Debug-iphonesimulator/Armchair.framework/Armchair
  Expected in: /Users/<..>/Library/Developer/CoreSimulator/Devices/C61B939F-2F90-4314-AA8C-B36C15E2D8C0/data/Containers/Bundle/Application/058F8711-F90C-48FC-A7B4-31D0298D97B9/JotAgenda.app/Frameworks/libswiftCore.dylib
 in /Users/<..>/Library/Developer/Xcode/DerivedData/JotAgenda-gazubqkikzwwstckckciztnqufsb/Build/Products/Debug-iphonesimulator/Armchair.framework/Armchair
`
Am I missing something else? Is it an issue related to the framework generation ? 
I also attach the Carthage zipped folder coming out the update command. BTW: the checkout folder is not generated. 
Is that correct ?.
Thank you for any help.

Stefano
#######################################################################

**Comment by ikesyo** [comment]
Looks like this is a binary compatibility issue, the prebuilt binary was built with a different version of Xcode. In this case you should use `--no-use-binaries` option to disable prebuilt binary usage. Then, the repository will be checked out and the framework should be built from the sources.

> BTW: the checkout folder is not generated. 
Is that correct ?.

This is just because prebuilt binary is used as the log message says:

> Downloading Armchair.framework binary at "0.1.2"

**Comment by stefat** [comment]
Thank you for your prompt answer.
I run again as follows:
`iMac-5:JotTheDate 5.3 work <..>$ carthage update --no-use-binaries
*** Fetching Armchair
*** Checking out Armchair at "0.1.2"
*** xcodebuild output can be found in /var/folders/xx/zhysw05j1pn9jw3vypwb3rrw0000gn/T/carthage-xcodebuild.lRbQJU.log
*** Building scheme "ArmchairMac" in Armchair.xcworkspace
*** Building scheme "Armchair" in Armchair.xcworkspace
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:951:44: warning: '++' is deprecated: it will be removed in Swift 3
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1700:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1701:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1702:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:951:44: warning: '++' is deprecated: it will be removed in Swift 3
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1696:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1697:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1698:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:951:44: warning: '++' is deprecated: it will be removed in Swift 3
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1696:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1697:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1698:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:951:44: warning: '++' is deprecated: it will be removed in Swift 3
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1696:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1697:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1698:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:951:44: warning: '++' is deprecated: it will be removed in Swift 3
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1696:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1697:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Volumes/G-DRIVE/Documents/WORK_DATA/SW/DEV_iOS/iOS/JOTTHEDATE/JotTheDate 5.3 work/Carthage/Checkouts/Armchair/Source/Armchair.swift:1698:74: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
iMac-5:JotTheDate 5.3 work <..>$ 
`
Unfortunately the error is still there:
dyld: Symbol not found: __TMPdCSs18_HeapBufferStorage

The checkout folder is now generated, as expected.
The Armchair.framework is in:
Link Binary With Libraries
Copy Bundle Resources
Embed Frameworks
Build Rules ($(SRCROOT)/Carthage/Build/iOS/Armchair.framework as the file, with custom script: /usr/local/bin/carthage copy-frameworks)

Any other clue ?
