### ISSUE TITLE
Supporting Carthage for library

### ISSUE THREAD

**Issue by f2prateek** [Carthage/Carthage#1356]
I'm trying to support Carthage for my library (relevant branch https://github.com/segmentio/analytics-ios/tree/carthage).

I've marked the scheme as shared (as seen here https://cloudup.com/c0BqapjPgqg) and committed it to source control (as seen here https://github.com/segmentio/analytics-ios/tree/carthage/Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes).

The scheme also seems to show up with `xcodebuild -project _Pods.xcodeproj -list` correctly as far as I can tell: https://cloudup.com/ceuTTQsP6Uz.

Additionally, the library was created using https://github.com/CocoaPods/pod-template which should support Carthage out of the box.

However, when I try to build it into an app, I keep getting the error "Dependency "analytics-ios" has no shared framework schemes" (see details below).

* `carthage version`: 0.16.2
* `xcodebuild -version`: Xcode 7.3.1, Build version 7D1014
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "segmentio/analytics-ios" "carthage"
```

**Carthage Output**
```
*** Fetching analytics-ios
*** Checking out analytics-ios at "1fdce04d4f8a6288283e46e88c25c9e550750f83"
*** xcodebuild output can be found in /var/folders/1s/1x5806js3g9cmlt55w69ld8h0000gn/T/carthage-xcodebuild.4m3N8L.log
*** Skipped building analytics-ios due to the error:
Dependency "analytics-ios" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/segmentio/analytics-ios/issues/new
```

Am I missing any other additional setup? What's the right way to make sure that Carthage detects the shared scheme correctly?

**Comment by mdiep** [comment]
It works for me. 😕 

```
$ carthage update
*** Cloning analytics-ios
*** Checking out analytics-ios at "1fdce04d4f8a6288283e46e88c25c9e550750f83"
*** xcodebuild output can be found in /var/folders/xj/sydx1wkd0p147x0k_7v667940000gn/T/carthage-xcodebuild.jpFdSo.log
```

**Comment by mdiep** [comment]
Carthage only builds dynamic frameworks. Your project is configured to build a static library.

**Comment by f2prateek** [comment]
Thanks, that gives me enough of a hint to dig in more!
