### ISSUE TITLE
Add `--toolchain` option to select build toolchain in Xcode 8

### ISSUE THREAD

**Issue by rpowelll** [Carthage/Carthage#1357]
So if people have caught up with the announcements from WWDC16, you might have heard that Xcode 8 ships with two Swift toolchains. One targets Swift 3.0, the new hotness, and the other targets Swift 2.3, a minor update to Swift 2.2 which is compatible with the iOS 10 SDK. 

Right now if you want to build dependencies for a Swift 3.0 project with Carthage, things work as expected. But if you want to build your dependences under Swift 2.3, you have to specify a `TOOLCHAINS` environment variable, which is non-obvious and requires a bit of searching around to discover.

My suggestion is that we add the toolchain to use as a command line option using an options flag like `--toolchain`. This would also make it easier for those working with Swift open source snapshots to use Carthage, but the main goal is to make the (much more common) use case of using Swift 2.3 in Xcode 8 as painless as possible.

How do people feel about adding this option?

**Comment by mdiep** [comment]
This option was added in #1303, but it looks like that hasn't made it to a release yet. I'll try to create a release tomorrow that includes that PR.

**Comment by rpowelll** [comment]
Oh awesome. Yeah I'd updated my Carthage install before opening the PR to make sure this wasn't already a thing, but I should've searched the issues as well. Thanks for the quick response!
