### ISSUE TITLE
Using carthage makes app way bigger than with manual

### ISSUE THREAD

**Issue by yangcaimu** [Carthage/Carthage#1358]
- `carthage version`: 0.16.2
- `gym -version`: 2.6.3
- `xcodebuild -version`: Xcode 7.3.1 (Build version 7D1014)
- Are you using `--no-build`? No
- Are you using `--no-use-binaries`? No
- Are you using `--use-submodules`? No

**Cartfile**

```
github "SVProgressHUD/SVProgressHUD"
github "AFNetworking/AFNetworking"
github "rs/SDWebImage"
```

I created a new project and add a few files. Compare add third-party libraries with manual or carthage. When use carthage, I add `/usr/local/bin/carthage copy-frameworks` script to strip unnecessary symbols.

And generate ipa and dSYM file by gym.

```
gym build --clean --use_legacy_build_api
```

**With carthage**
- ipa file size **1MB**
- dSYM file size **2.7MB** (include AFNetworking.framework.dSYM, SVProgressHUD.framework.dSYM, WebImage.framework.dSYM)

**With manual**
- ipa file size **183KB**
- dSYM file size **83KB**

I found the app by unzip ipa file, more than one folder containing framework files with carthage, it has 5.5MB, I don't know why the framework files are so big.

**Comment by mdiep** [comment]
The size of the files created with Carthage are the same as the size of the files created when building with Xcode itself. (Once you account for the fact that Carthage includes simulator and device slices.)

I'm not familiar with `gym` or what it may be doing. Although the README does say that `dSYM`s are compressed. I'd encourage you to investigate more. If there's something that Carthage can do to shrink sizes, we'd love to do it!

**Comment by andresilvagomez** [comment]
@mdiep I have the same problem, my app with carthage build is around 140 MB, but I use xcodebuild in each dependency and finally the app build reduce 50 MB in total I have 22 dependencies .

**Comment by mdiep** [comment]
> my app with carthage build is around 140 MB

What are you measuring the size of and how are you measuring it?

**Comment by andresilvagomez** [comment]
@mdiep archiving the app.

**Comment by dunqi** [comment]
So using Carthage isn't good, if you want a small app size or your app has a lot of dependencies ?

**Comment by mdiep** [comment]
I'm not sure the measurements above actually affect the app size for users. There's a lot that happens (and a lot that's stripped) between archiving and downloading from the app store.

**Comment by dcaunt** [comment]
Looking at a project which I recently migrated to Carthage from CocoaPods, the binary size reported in iTunes Connect did not increase due to Carthage.

**Comment by ikesyo** [comment]
Thanks @dcaunt. Closing this for now

**Comment by sheehanm** [comment]
For anyone who stumbles across this while Googling, Carthage doesn't listen to the stripping settings set in the xcodeproj. Because the binaries built by Carthage are not stripped they'll be bigger. I think Carthage should listen to the settings in the xcodeproj.

I think binary size in iTunes Connect is a bad way to verify an issue, because it's relatively black boxed and doesn't verify all use cases, such as when not using bitcode and thinning (or w/e newfangled Apple things).

**Comment by jdhealy** [comment]
@sheehanm, you should weigh in on https://github.com/Carthage/Carthage/issues/2485, more info there:
<blockquote>

for [context on the decision to set `STRIP_INSTALLED_PRODUCT` to `NO`](https://github.com/Carthage/Carthage/pull/2334#issue-164416797), quoting @abrindam:

> This change is necessary [since Carthage moved to using the "archive" command](https://github.com/Carthage/Carthage/pull/2158) to build. Most products have `STRIP_INSTALLED_PRODUCT` set to true, but this does not kick in unless you have `DEPLOYMENT_POSTPROCESSING` set to true as well, and that is false for most products. However, using "archive" instead of "build" magically overrides `DEPLOYMENT_POSTPROCESSING` to true, resulting in the product being stripped of debug symbols. As a result dSYM generation produces effectively no information for builds that are built with "archive" (e.g. OSX and iOS device, but not iOS simulator)
> 
> This also restores the 0.25 behavior that built frameworks are not stripped. Prior to [fix](https://github.com/Carthage/Carthage/pull/2334), stripping was happening with the archive command, which may have caused additional issues that were not reported. With this change, we are back to the old behavior and stripping is done at framework copy time.
</blockquote>

**Comment by sheehanm** [comment]
@jdhealy Thanks, I didn't see that, I'll weigh in. I got here by Googling _why is framework bigger_
