### ISSUE TITLE
Unnecessary builds

### ISSUE THREAD

**Issue by alejandro-isaza-hs** [Carthage/Carthage#1365]
* `carthage version`: 0.16.2
* `xcodebuild -version`: 7.3.1

When executing `carthage build --platform iOS --verbose SDWebImage` carthage always cleans and builds from scratch:

```
$ carthage build --platform iOS --verbose SDWebImage 
*** Building scheme "WebImage" in SDWebImage.xcworkspace
/usr/bin/xcrun xcodebuild -workspace /Users/alejandroi/dev/HootsuiteComposer/Carthage/Checkouts/SDWebImage/SDWebImage.xcworkspace -scheme WebImage -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
```

Note the **clean**.

 For projects with many dependencies this means that running `carthage update` takes forever. A related ticket is #432 but it was closed for #459 which doesn't change the fact that carthage is executing a `clean` every time.

**Comment by alejandro-isaza-hs** [comment]
This seems to be the culprit https://github.com/Carthage/Carthage/blob/242288351852a9c0118ce9befec95a40d2cc3c7a/Source/CarthageKit/Xcode.swift#L935

**Comment by mdiep** [comment]
This was an intentional change made in #1028. You can read about the rationale there.

I don't think getting rid of `clean` is the right thing to do, but there are probably some other measures we can take. You might be interested in #1222.

**Comment by alejandro-isaza-hs** [comment]
What about adding an option to skip cleaning if you know there is no folder changes. `--no-clean`?

**Comment by mdiep** [comment]
That's a decent idea, but I think I'd rather see effort be put into #1222. I don't really want people to get in the habit of `--no-clean` since it's a little dangerous.
