### ISSUE TITLE
Carthage Update Freezes, Sometimes

### ISSUE THREAD

**Issue by cbh2000** [Carthage/Carthage#1370]
Whenever I run `carthage update`, it freezes after logging "*** Fetching izevent". But it worked one time. Commenting out lines from the Cartfile one by one increases the chances of a successful build. Running on a 2012 Mac mini quad core i7 with OS X 10.11.5.

To be clear, there's an element of chance here. Sometimes it locks up, sometimes it doesn't. The more libraries I add to my Cartfile, the higher the chance it'll freeze up.

* `carthage version`: 0.17.1
* `xcodebuild -version`: 7.3.0 (and 7.3.1)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "izeni-team/izevent" ~> 0.3.0
github "xmartlabs/Eureka" ~> 1.6
github "adamwaite/Validator"
github "intuit/LocationManager"
github "jdg/MBProgressHUD" ~> 0.9.2
github "realm/realm-cocoa" ~> 1.0
github "iziz/libPhoneNumber-iOS"
github "mamaral/Neon"
github "izeni-team/izeni-ios" ~> 0.9
```

**Carthage Output**
```
*** Fetching izeni-ios
*** Fetching Neon
*** Fetching libPhoneNumber-iOS
*** Fetching realm-cocoa
*** Fetching MBProgressHUD
*** Fetching LocationManager
*** Fetching Validator
*** Fetching Eureka
*** Fetching izevent
```

Carthage 0.16.2 and 0.16.1 and 0.13.0 don't have this problem, as far as I can tell. I'm using 0.16.2 as a temporary workaround.

**Comment by mdiep** [comment]
Thanks for reporting this! I can reproduce it. I'll try to take a deeper look in the next week.

**Comment by mdiep** [comment]
Still trying to figure out what's happening here.

In the meantime, you should be able to work around this by running `carthage update --no-checkout && carthage bootstrap`.

**Comment by TofPlay** [comment]
Same issu as @cbh2000 with Cartfile:
```
github "Alamofire/Alamofire" == 3.4.0
github "Hearst-DD/ObjectMapper" == 1.2.0
github "tristanhimmelman/AlamofireObjectMapper" == 3.0.0
github "stripe/stripe-ios" == 6.2.0
github "algolia/algoliasearch-client-swift" == 2.3
github "robbiehanson/CocoaAsyncSocket" == 7.4.3
```
Carthage update freezes every time
Obliged to reinstall version 0.16.2

**Comment by mdiep** [comment]
You should be able to work around this by running `carthage update --no-checkout && carthage bootstrap`.

**Comment by cbh2000** [comment]
Thanks for looking into this! I really appreciate it. And feel free to let me know if there is anything you need.

**Comment by mdiep** [comment]
Okay, I tracked this down. It's due to a ReactiveCocoa bug that was fixed but hasn't been released yet. I'll try to create new releases of RAC and Carthage tonight or in the morning.

**Comment by hientrq** [comment]
I experience the same problem. Try to run `carthage update --no-checkout && carthage bootstrap` doesn't work for me. I'm using version `0.26.2`. Any idea?

**Comment by mdiep** [comment]
Please open a new issue with a Cartfile that reproduces the issue.
