### ISSUE TITLE
Code signing is required for product type 'Framework' in SDK 'iOS 10.0'

### ISSUE THREAD

**Issue by TofPlay** [Carthage/Carthage#1378]
Hi,
I try to build a project with Xcode 8. This project manage multiple frameworks with Carthage.
On the main project I include xcodeproj of all frameworks as a sub-projects. Like this I can put a break point on the source if it's need it.  
When I open this project with Xcode 8 for all frameworks I have this error:
```
Signing for <framework> requires a development team. Select a development team in the Target Editor.
Code signing is required for product type 'Framework' in SDK 'iOS 10.0'
``` 
For my framework it's ok I can define a development team. But for others they are public frameworks they don't have to define a team.
How we can manage this case? With Carthage do we have an option like `--team` to force a team on each framework? Do we have to sign binary framework for close source framework?

**Comment by ikesyo** [comment]
IIUC that does not cause any problem on Carthage to build a framework. Just checking off `Automatically manage signing` should be enough.

**Comment by mdiep** [comment]
Frameworks do need to be signed, but they don't need to be signed at compile team because they'll be re-signed when you include them in your app.

Carthage completely disables code signing when it builds frameworks because of this.

**Comment by ikesyo** [comment]
Yes, there should be no problem for building frameworks by `carthage update/build`. But if you are integrating checked out projects into your project, some code signing related build settings should be modified in the frameworks' project to completely disable code signing, as seen in https://github.com/ikesyo/Himotoki/pull/130.

**Comment by TofPlay** [comment]
@ikesyo For sur I can change the setting of the projects locally but I can not commit this change. The projects on the checkout folder are not my projects. Each time I will do a git clone or even a `carthage update` I will be obliged to change the setting again 😥

**Comment by ikesyo** [comment]
Carthage can not control the project settings neither when you use manual integration. So you should change the settings at a forked repository and submit a pll request to its upstream (or directly use the forked repo in your Cartfile).

**Comment by TofPlay** [comment]
@ikesyo Even if I uncheck `Automatically manage signing` on a sub-project. I still have the message:
```
Signing for MyFramework requires a development team. Select a development team in the Target Editor.
Code signing is required for product type 'Framework' in SDK 'iOS 10.0'
```
Submit a pull request for the project with uncheck `Automatically manage signing` setting will not help. 
Include project framework as sub-project is very useful to debug unexpected behavior of a framework.
I know is not Carthage issue more an issue with Xcode 8

**Comment by ikesyo** [comment]
Please see https://github.com/ikesyo/Himotoki/pull/130 as an example. You should add `CODE_SIGNING_REQUIRED=NO` user-defined setting and set `CODE_SIGN_IDENTITY=` (select `Don't Code Sign` for `Code Signing Identity` setting). `Automatically manage signing` is not the point.

**Comment by TofPlay** [comment]
> Please see ikesyo/Himotoki#130 as an example

OK i will check. Thanks @ikesyo :)

**Comment by TheMrugraj** [comment]
An error is occurring in this case, I have embedded frameworks generated by Carthage Build into my project and it is not able to archive and upload to iTunes because of the error:

`Code signing "CocoaAsyncSocket.framework" failed.`

![image](https://user-images.githubusercontent.com/6426983/50599993-b3ddef00-0ed5-11e9-967c-8d5ff660f11b.png)

**Comment by ardalahmet** [comment]
Hi @TheMrugraj 

Did you manage to find a solution for this code signing problem?

**Comment by ednew2018** [comment]
@ardalahmet  @TheMrugraj Check out this solution https://stackoverflow.com/a/41416964/4654659

**Comment by relikd** [comment]
They've updated the README for Xcode 11 yesterday. Following the not-embed and copy-frameworks procedure fixed it for me. Super happy about the timing 😃
