### ISSUE TITLE
Redefinition of module 'libxml2' error when using nested frameworks

### ISSUE THREAD

**Issue by daehn** [Carthage/Carthage#1383]
I ran into an issue using [Fuzi](https://github.com/cezheng/Fuzi) via Carthage and nested frameworks. Framework A has a dependency to Fuzi and is itself a dependency of framework B.
Fuzi defines a [module map](https://github.com/cezheng/Fuzi/blob/master/libxml2/module.modulemap) to expose `libxml2`, A and B don't define custom module maps.
> Fuzi ← A ← B

Building framework A alone works fine, however framework B ends up with 2 identical module maps and a `redefinition of module 'libxml2'` error. When bootstrapping framework B the `libxml2` module map is  present twice in framework B with the following build error:

```
/Users/silvandaehn/Developer/Framework_B/Carthage/Checkouts/Fuzi/libxml2/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 [system] {
       ^
/Users/silvandaehn/Developer/Framework_A/Carthage/Checkouts/Fuzi/libxml2/module.modulemap:1:8: note: previously defined here
module libxml2 [system] {
       ^
<unknown>:0: error: could not build Objective-C module 'Fuzi'
```

What surprised me is that Xcode references my local framework A that is located in the same parent directory as framework B, framework B builds fine as soon as I delete the Carthage/ folder in the framework A. I am new to custom module maps and am unsure this issue is caused by Carthage, but am thankful for any information.

**Comment by mdiep** [comment]
_Sorry for the delayed response. I've been taking some vacation time and have been overwhelmed with notifications._

It's really hard to diagnose this sort of thing without access to the code. Could you put together a couple sample projects that demonstrate the issue?

Some questions:

- Are you building with Carthage or including dependency projects in your Xcode project?
- Are you embedding frameworks? (Does `A.framework` contain a copy of `Fuzy.framework` or does `B.framework` contain a copy of either?)
- If you look for the `xcodebuild` command used by Carthage (which can be found in the xcodebuild log), can you reproduce the issue using just `xcodebuild` on the command line?

Xcode can definitely be a little finicky when it comes to module maps.

You might also look at the search paths is your project.

**Comment by daehn** [comment]
Thanks for the response, unfortunately I was unable to reproduce the issue in a sample project yet, but might try that again soon. We moved to a different XML library to circumvent this in the meantime, but the issue happened both when building with Carthage as well as when including the dependencies locally in the Xcode project. The issue was reproducible for us using `xcodebuild` on the command line.

**Comment by mdiep** [comment]
It sounds like this isn't Carthage specific. But please try to update here if you figure out what was causing the problem!
