### ISSUE TITLE
carthage update fail

### ISSUE THREAD

**Issue by ceekay1991** [Carthage/Carthage#1388]
* `carthage version`: 0.16.2
* `xcodebuild -version`: Xcode 7.3.1 Build version 7D1014
* Are you using `--no-build`?NO
* Are you using `--no-use-binaries`?NO
* Are you using `--use-submodules`?NO

**Cartfile**
```
github "facebook/react-native"
```

**Carthage Output**
```
*** Fetching react-native
*** Checking out react-native at "v0.29.1"
*** xcodebuild output can be found in /var/folders/84/xk7tnsws0d959wqxg_80plsm0000gn/T/carthage-xcodebuild.GPZuNo.log
xcodebuild timed out while trying to read 2048.xcodeproj 😭
```

**Comment by dcaunt** [comment]
#1310 has a good explanation of this issue.
