### ISSUE TITLE
Is it possible to have different Cartfiles for different targets?

### ISSUE THREAD

**Issue by sirvon** [Carthage/Carthage#1408]
I'm using targets like flavors are used in gradle projects while building android apps..
Targets would represent totally different but kinda similar versions of the same app.

I would like to get these targets different dependencies.

Is it possible to assign a Cartfile for each target within the same project, and if yes how?

Thank you.

**Comment by mdiep** [comment]
No, Carthage only supports a single `Cartfile`.

But if you build all the dependencies up front, then each app target can choose to use a different subset of them.

**Comment by sirvon** [comment]
can you point to information on how to build all dependencies up front?
thanks

**Comment by mdiep** [comment]
`carthage bootstrap` or `carthage build`.
