### ISSUE TITLE
Simpler API for carthage build --no-skip-current

### ISSUE THREAD

**Issue by 3lvis** [Carthage/Carthage#1411]
- `carthage version`: 0.16.2
- `xcodebuild -version`: Xcode 7.3.1 Build version 7D1014
- Are you using `--no-build`? No
- Are you using `--no-use-binaries`? No
- Are you using `--use-submodules`? No
# Feature request:

I have to Google every single time I use `carthage build --no-skip-current` is there a simpler API for `carthage build --no-skip-current`? Something more memorable like:

`carthage build --archive`

So then I can do

`carthage archive`

Or maybe

`carthage archive --building`, so I can skip the build command?

Thanks for your help.

**Comment by mdiep** [comment]
`carthage help build` might be helpful. ☺️ 

But I do think it'd be worth adding a variant that both builds and archives.

**Comment by 3lvis** [comment]
Tried looking into this but it's quite difficult, I get an error in currying the BuildCommand inside the method `evaluate`.

>Binary operator '<|' cannot be applied to operands of type 'CommandMode' and 'Argument<[Any]>'

**Comment by mdiep** [comment]
I think you just need to change `defaultValue: nil` to `defaultValue: false`. Since `public let archive: Bool`, `nil` isn't a valid value. This causes type inference to fail, leading to the unhelpful error that you shared above.
