### ISSUE TITLE
Update to README: Linking dynamic frameworks to embedded frameworks requires as well linking them to the app target

### ISSUE THREAD

**Issue by evgeniyd** [Carthage/Carthage#1427]
See #1401

As @mdiep stated:

> Carthage doesn't support nested frameworks.
> 
> Nesting frameworks doesn't let you reuse those frameworks. For instance, if `A.framework`and `B.framework` both depend on `Other.framework`, then neither of them can nest `Other.framework`—otherwise you might end up with 2 different versions, and the correct one might not be chosen at runtime.
> 
> The correct way to do this is to list it as a dependency, but link it into the app target.

I suggest to add this point to the [README's Adding frameworks to unit tests or a framework](https://github.com/Carthage/Carthage#adding-frameworks-to-unit-tests-or-a-framework).

**Comment by mdiep** [comment]
Care to open a pull request? There's already a section on nested frameworks, and this would make a fine addition.

**Comment by evgeniyd** [comment]
@mdiep could you please review the PR?

**Comment by mdiep** [comment]
Fixed by #1441.
