### ISSUE TITLE
Ability to store carthage configuration in a repository

### ISSUE THREAD

**Issue by mz2** [Carthage/Carthage#1437]
It would be useful to be able to store carthage configuration to be used per command as a `.carthagerc` file in a repository. For instance I often use Carthage `bootstrap` and `update` commands in projects where I always need to remember to issue `--use-submodules --use-ssh --platform mac`. Forgetting any one of these flags is easy and can result in build issues on noob developers on the project who are not necessarily aware of the precise way in which Carthage based dependencies would need to be pulled in in the project without it being documented. I appreciate this can be automated with scripts placed in the repository, but it is a generic enough a problem that it IMO would warrant helping with it on the level of Carthage itself.

**Comment by ikesyo** [comment]
Thanks for bringing up the thought! However, I think this is already captured in the following issues: #262, #356, #357 and #426. I'm closing this for now and can you please follow the issues instead? 🙏

**Comment by mz2** [comment]
@ikesyo I'm a bit confused based on these issues – #426 has been marked closed, but the issue blocking all of these from completion is the OGDL parsing? Or is that complete? Am I able to at the moment pass some but not all of these per project settings in a Cartfile.private? Is it documented somewhere? Sorry!

**Comment by ikesyo** [comment]
#426 is still open.
