### ISSUE TITLE
Can carthage be used for closed-source projects?

### ISSUE THREAD

**Issue by malhobayyeb** [Carthage/Carthage#1439]
A feature request is sent to Google and Firebase to support Carthage but they claim that Carthage is meant for open-source projects only.

[Carthage Support - Firebase Google Group](https://groups.google.com/forum/#!topic/firebase-talk/ewsVc_FN8N0)
> We can't use Carthage because it mandates a few things we don't support:
> - Carthage is iOS 8+, dynamic frameworks only
> - **Carthage wants open source only (it builds frameworks directly from Github source)**
>
> Since we're a closed source, ios 7+ static framework, we'd be unable to deal with these requirements.

Another place where they claim this: [Hacker News](https://news.ycombinator.com/item?id=11727533)

> Firebase iOS engineer here:
>
> First off, I'm glad you like the new feature additions. We'd love to hear your feedback on Storage and FCM :)
>
> Secondly, I'd love Carthage support as well, but there are a few things (built into Carthage) that prevent us from adding this:
>
> 1.  Carthage requires iOS 8+ (dynamic frameworks only). Firebase supports 7+, and we build static "frameworks", so we'd lose that (which is still relevant in a lot of our developers).
>
> 2.  **Carthage is designed for open source (git based origins only), and while we'd love to get there, we currently ship everything as a pre-built framework.**

If the open-source requirement is not true, then how to use it for closed source projects? Any resources?

Thank you

**Comment by ikesyo** [comment]
That should be tracked in #1308.
