### ISSUE TITLE
Compatibility with Xcode 8

### ISSUE THREAD

**Issue by mdiep** [Carthage/Carthage#1440]
It seems like we've lost compatibility with Xcode 8. We should fix that so Carthage will build correctly on macOS Sierra.

**Comment by ikesyo** [comment]
I'm working on it.

**Comment by miniBloq** [comment]
I tried today on an XCode 8 Beta 6 project and got the following message when linking:

"The following binaries use incompatible versions of Swift"

**Comment by mdiep** [comment]
This issue is about compiling Carthage itself with Xcode 8.
