### ISSUE TITLE
A shell task (/usr/bin/env git clone --quiet https://github.com/Alamofire/Alamofire.git

### ISSUE THREAD

**Issue by jordanekay** [Carthage/Carthage#1446]
Since updating my Cartfile, this is the message I see every time after the checkout process is done. Then Carthage terminates before building anything. I'm unable to share my actual Cartfile at this time. I've noticed I can fix the issue simply by changing one of my dependency's dependency to point to my [own fork](http://www.github.com/jordanekay/SwiftTask), rather than [upstream](http://www.github.com/ReactKit/SwiftTask). However, I would prefer to point not to have to use this workaround.

* `carthage version`: 0.17.2
* `xcodebuild -version`: Xcode 8.0 Build version 8S201h
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No

**Comment by mdiep** [comment]
Are you pointing to the same commit on both repos? Have you tried deleting Carthage's shared cache? (`~/Library/Caches/org.carthage.CarthageKit`)

**Comment by jordanekay** [comment]
I'm pointing to one commit later actually (the merge commit) but that shouldn't make a difference. (I've also tried pointing to the exact same commit, with no luck.) Deleting the shared cache seems to have no effect.

**Comment by mdiep** [comment]
I'm able to build http://www.github.com/ReactKit/SwiftTask with Carthage, so I'm a little confused about what's going on.

**Comment by jordanekay** [comment]
This seems to have resolved itself. Thanks for looking into it!
