### ISSUE TITLE
xcodebuild timed out while trying to read ATMobileAnalytics.xcworkspace 😭

### ISSUE THREAD

**Issue by d-theo** [Carthage/Carthage#1450]
Hi, I have some problems integrating my swift3 framework into a project :

* `carthage version`: 0.17.2
* `xcodebuild -version`: Xcode 8.0 Build version 8S201h (xcode 8 beta 6)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "at-internet/atinternet-ios-swift-sdk" "swift3"
```

**Carthage Output**
```
~ $ carthage update
*** Fetching atinternet-ios-swift-sdk
*** Checking out atinternet-ios-swift-sdk at "c29dc7c754c64d75e7567ab11a70cb45b27e18aa"
*** xcodebuild output can be found in /var/folders/2q/bzkzqxl556nd22530jy3dc800000gp/T/carthage-xcodebuild.iQp8Vk.log
xcodebuild timed out while trying to read ATMobileAnalytics.xcworkspace 😭

~ $ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/2q/bzkzqxl556nd22530jy3dc800000gp/T/carthage-xcodebuild.j4cFKr.log
xcodebuild timed out while trying to read ATMobileAnalytics.xcworkspace 😭
```

The log file in the output are empty. However building with xcodebuild -workspace ATMobileAnalytics.xcworkspace -scheme Tracker build succeed without any problem (same for all scheme available)

Any ideas about it ?

Best regards

**Comment by dcaunt** [comment]
#1310 has a good explanation of this issue. TLDR: It's an `xcodebuild` bug :/
