### ISSUE TITLE
carthage update failure code 65

### ISSUE THREAD

**Issue by xianzhiliao** [Carthage/Carthage#1453]
* `carthage version`: 0.17.2
* `xcodebuild -version`: Xcode 7.3.1 Build version 7D1014
* Are you using `--no-build`?N
* Are you using `--no-use-binaries`?N
* Are you using `--use-submodules`?N
![2016-08-25 3 37 23](https://cloud.githubusercontent.com/assets/11209617/17960730/6c31df0a-6ada-11e6-819b-16450f23617d.png)

**Cartfile**
```
<YOUR CARTFILE>
```
github "ReactiveCocoa/ReactiveCocoa" == 4.2.1
github "mxcl/PromiseKit" == 3.4.0

**Carthage Output**
```
<OUTPUT>
```

**Comment by mdiep** [comment]
Please look in the xcodebuild log (or use `--verbose`). The details of why the build failed aren't visible there.

**Comment by xianzhiliao** [comment]
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btsevar/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.fBSBZN.log...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
:...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework

** CLEAN SUCCEEDED **
:...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework

** CLEAN SUCCEEDED **

=== BUILD TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===
:...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework

** CLEAN SUCCEEDED **

=== BUILD TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies
:...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework

** CLEAN SUCCEEDED **

=== BUILD TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
:...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework

** CLEAN SUCCEEDED **

=== BUILD TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqy:...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework

** CLEAN SUCCEEDED **

=== BUILD TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build/PromiseKit-generated-files.hmap
:...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework

** CLEAN SUCCEEDED **

=== BUILD TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build/PromiseKit-generated-files.hmap
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqy:...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework

** CLEAN SUCCEEDED **

=== BUILD TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build/PromiseKit-generated-files.hmap
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build/Promi:...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework

** CLEAN SUCCEEDED **

=== BUILD TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build/PromiseKit-generated-files.hmap
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build/PromiseKit.hmap
:...skipping...
/usr/bin/xcrun xcodebuild -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build

Clean.Remove clean /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework
    builtin-rm -rf /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Release/PromiseKit.framework

** CLEAN SUCCEEDED **

=== BUILD TARGET PMKOSX OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build/PromiseKit-generated-files.hmap
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Release/PMKOSX.build/PromiseKit.hmap
write-file /var/root/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqy

**Comment by xianzhiliao** [comment]
I have try xcodebuild -scheme PMKiOS -project /Users/xiabzhiliao/Documents/iOSSpace/GrapeLife/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj build

Signing Identity:     "iPhone Developer: li yuan (AE4K86DQBY)"
Provisioning Profile: "iOS Team Provisioning Profile: *"
                      (cc2248e7-5397-4fae-a571-105ce3d190d5)

    /usr/bin/codesign --force --sign C4584F41A9C3055E34F442A624C2EDF45A1D802D --deep --entitlements /Users/xiabzhiliao/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Intermediates/PromiseKit.build/Debug-iphoneos/PMKiOSUITests.build/PMKiOSUITests.xctest.xcent --timestamp=none /Users/xiabzhiliao/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Debug-iphoneos/PMKiOSUITests-Runner.app
/Users/xiabzhiliao/Library/Developer/Xcode/DerivedData/PromiseKit-btseifraqrqyzhgzllkazvbllkts/Build/Products/Debug-iphoneos/PMKiOSUITests-Runner.app: replacing existing signature

**Comment by mdiep** [comment]
I don't see any errors in that log output.

**Comment by buscarini** [comment]
I'm seeing the same thing with Xcode 8 on el Capitan. The build log shows no errors, but the update fails with:

`A shell task (/usr/bin/xcrun xcodebuild -project /Users/josanchez/prog/Audioguide/code/Carthage/Checkouts/ReSwift/ReSwift.xcodeproj -scheme ReSwift-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **
`

**Comment by mdiep** [comment]
What happens if you run that task manually?

**Comment by buscarini** [comment]
In my case it was my fault. I started the update to Xcode 8 but I hadn't finished it, so obviously all the frameworks requiring Xcode 8 wouldn't work.
