### ISSUE TITLE
Feature request: copy-frameworks and rsync

### ISSUE THREAD

**Issue by stanislaw** [Carthage/Carthage#1455]
Hello,

> Is there a reason why `carthage copy-frameworks` doesn't use `rsync -a` under the hood?

> (Taken from [here](https://twitter.com/sbpankevich/status/768589559638663168)).

See also the scripts from @robb's that contain rsync: https://github.com/Carthage/Carthage/issues/188#issuecomment-66267828.

Thanks.

**Comment by mdiep** [comment]
I don't think there's a reason other than no one thought to use it.

A pull request for this would be very welcome! But I'd like to see some benchmarks included with it.

**Comment by stanislaw** [comment]
Here is the script we're currently evaluating for our developer workflow (works on both simulator and devices): https://gist.github.com/stanislaw/f1f56d59fc82e0d32b607dbc31be5b0f.

There is a limitation that makes me doubt about if this approach fits Carthage: script doesn't re-copy and re-codesign frameworks if they exist so that makes a developer to clear the cache when upgrading the frameworks. That's totally not an issue for us, since we value precious seconds of the build time over the disadvantage of cleaning a cache when upgrading, however I am not sure about the general purpose usage.

## Performance results

We have 27 frameworks, 89 MB total. Basically the difference will be made by copying these 89 MB and then codesigning and not copying/codesigning them.

1) The first run when copy happens:

```
real	0m12.300s
user	0m4.039s
sys  0m2.908s
```
2) The subsequent run when script's rsync skips existing files, and codesign is not run:

```
real	0m0.443s
user	0m0.149s
sys  0m0.235s
```

I run these test multiple times using iPad. The difference between `12 seconds` and `0.45 seconds` is quite stable across my tests so that is 25x faster.

**Comment by stanislaw** [comment]
Aside note: versions of `cp` newer than the default one on Mac OS X have `-u` feature which is enough for this script to work. However `rsync` is there on default Mac OS X so it is safer to use.

**Comment by mdiep** [comment]
> There is a limitation that makes me doubt about if this approach fits Carthage: script doesn't re-copy and re-codesign frameworks if they exist so that makes a developer to clear the cache when upgrading the frameworks

Yeah, I don't think that's a good fit for Carthage.

It would be interesting to compare how just switching to `rsync -a` affects the speed.

I'll be looking forward to next year when AppleFS ships and copies are near instantaneous.

**Comment by stanislaw** [comment]
Thanks for confirmation!

It seems to be not possible to "just switch" to rsync because codesigns changes the modification date / size / checksum and this makes rsync to act like copy without performance advantages.

I'm closing this.
