### ISSUE TITLE
Carthage unable to Clone private repos from GitHub

### ISSUE THREAD

**Issue by Baza207** [Carthage/Carthage#1456]
* `carthage version`: 0.17.2
* `xcodebuild -version`: Xcode 7.3.1 Build version 7D1014
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? Yes

I recently setup a new Mac, pulled down a few projects and tried to run `carthage bootstrap --use-submodules` to set them up. However when I did that, I got the following. (I've remove the output from the public repos that work fine).

If I try `carthage update --use-submodules` or `carthage fetch MyPrivateRepo` I get the same thing. 

However, if I then run `carthage build`, it seems to build just fine. 😕

I found a few old issues regarding this and also tried searching the GitHub help page, but couldn't find anything that fixed my problem. Has anyone got any ideas?

**Cartfile**
```
github "MyCompany/MyPrivateRepo" ~> 1.0
```

**Carthage Output**
```
$ carthage bootstrap --use-submodules
*** Cloning MyPrivateRepo
*** Checking out MyPrivateRepo at "1.0.3"
*** Cloning MyPrivateRepo
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/MyCompany/MyPrivateRepo.git /Users/<user>/Library/Caches/org.carthage.CarthageKit/dependencies/MyPrivateRepo) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

**Comment by mdiep** [comment]
Try cloning your repository directly with git. If you're able to clone with git, then you'll be able to clone with Carthage. (Carthage just uses git's authentication.)

If you're using SSH keys, you'll need to pass the `--use-ssh` flag to carthage.

**Comment by Baza207** [comment]
@mdiep Yep, sorry, my bad. New computer setup step added to my list. 😉 Thanks for the hint.

**Comment by rafarmachado** [comment]
Any news on the case?

**Comment by mdiep** [comment]
> Try cloning your repository directly with git. If you're able to clone with git, then you'll be able to clone with Carthage. (Carthage just uses git's authentication.)
>
> If you're using SSH keys, you'll need to pass the --use-ssh flag to carthage.

**Comment by rob-nash** [comment]
This solution does not work for me. I get no problems using any other tools, just carthage.

Roberts-iMac:Records robertnash$ carthage update --use-ssh
*** Fetching Dequable
A shell task (/usr/bin/env git fetch --prune --quiet origin refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/robertnash/Library/Caches/org.carthage.CarthageKit/dependencies/Dequable)) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

carthage version 0.26.2

Cartfile
git "git@github.com:rob-nash/Dequable.git" "master"
or
github "rob-nash/Dequable.git" "master"

**Comment by nhatle-setel** [comment]
https://github.com/Carthage/Carthage/issues/1456#issuecomment-242888750
`carthage update --use-ssh` worked for me
