### ISSUE TITLE
not support Masonry ？

### ISSUE THREAD

**Issue by liuious** [Carthage/Carthage#1457]
* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`?
* Are you using `--no-use-binaries`?
* Are you using `--use-submodules`?

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```

**Comment by ikesyo** [comment]
Can you provide more details? We are not sure what is happening.

**Comment by ikesyo** [comment]
Looks like you should follow the issue on that repository: https://github.com/SnapKit/Masonry/issues/350

**Comment by liuious** [comment]
ok，i try to follow the issue on that repositor
