### ISSUE TITLE
How to use local git repository as a dependency?

### ISSUE THREAD

**Issue by lolgear** [Carthage/Carthage#1458]
How to use local git repositories as a dependency?

Tries:
- github "../../"
- github "../../" master
- github "/Users/user/Projects/Github/etc/MyProjectFolderWithGit"
- github "/Users/user/Projects/Github/etc/MyProjectFolderWithGit" master
- github "file:///Users/user/Projects/Github/etc/MyProjectFolderWithGit"
- github "file:///Users/user/Projects/Github/etc/MyProjectFolderWithGit" master

Errors:
- invalid GitHub repository identifier

Please, update Cartfile reference with solution.

**Comment by lolgear** [comment]
Forgot about `git` and `github`.

**Comment by SandeepAggarwal** [comment]
@lolgear How you have solved this issue?

**Comment by blender** [comment]
@SandeepAggarwal use 
`git "file://path/to/git/repo.git" "branch or tag"`

**Comment by SandeepAggarwal** [comment]
@blender  If I use 
`git "file://path/to/git/repo.git" "branch or tag"`
I get following error:
_Parse error: unexpected trailing characters in line:_

If I use 
`git "file://path/to/git/repo.git"`
I get following error:
_Parse error: invalid GitHub repository identifier_

**Comment by blender** [comment]
Can you paste your actual Cartfile and Cartfile.resolved?

**Comment by SandeepAggarwal** [comment]
Cartfile:

`github "https://github.com/netguru/ResponseDetective.git" "develop"
github "marmelroy/PhoneNumberKit"
github "nickoneill/PermissionScope" ~> 1.0
github "andreamazz/BubbleTransition"
github "Alamofire/Alamofire" ~> 4.1.0
github "https://github.com/SandeepAggarwal/cloudinary_ios.git" "master"
github "danielgindi/Charts" ~> 3.0.2
github "file:///Users/SandeepAggarwal/My Applications/LiquidFloatingActionButton.git"`

Cartfile.resolved:

`github "Alamofire/Alamofire" "4.5.0"
github "andreamazz/BubbleTransition" "2.0.2"
github "danielgindi/Charts" "v3.0.2"
github "Quick/Nimble" "v7.0.1"
github "nickoneill/PermissionScope" "1.1.1"
github "marmelroy/PhoneNumberKit" "1.2.3"
github "Quick/Quick" "v1.1.0"
github "netguru/ResponseDetective" "7f7a1a8c09f42d666cf7d1286bbf5830275fbdda"
github "SandeepAggarwal/cloudinary_ios" "ea77a5a6f13bfe867c2bf987295de7095926f195"
`

**Comment by blender** [comment]
I can see that you are specifying `github` and not `git` for your local repo

Change this: 

`github "file:///Users/SandeepAggarwal/My Applications/LiquidFloatingActionButton.git"`

to this

`git "file:///Users/SandeepAggarwal/My Applications/LiquidFloatingActionButton.git"`

**Comment by SandeepAggarwal** [comment]
Oh! I am sorry I didn't realised that but it is still not working

_fatal: '/Users/SandeepAggarwal/My Applications/LiquidFloatingActionButton.git' does not appear to be a git repository
fatal: Could not read from remote repository._

**Comment by blender** [comment]
Try removing the `.git` extension

**Comment by SandeepAggarwal** [comment]
@blender Thank you so much.

**Comment by mac-daddie** [comment]
Note that if you switch from using a github link to a local file link, Carthage will now think it's a completely different dependency, and will not be able to resolve upstream dependencies upon the same thing if they normally refer to the remote link. This is because unlike CocoaPods, Carthage does not let you give a unique identifier (e.g., a name, such as "Alamofire") to each dependency, so therefore it has no way to know whether `git "file:///path/to/my/sick/repo"` is supposed to be an alternate source for `github "https://github.com/mySick/repo"` or a different, new dependency. Sad.
