### ISSUE TITLE
Support for mercurial as origin

### ISSUE THREAD

**Issue by dirkz** [Carthage/Carthage#1461]
Being able to use mercurial as origin would be really nice, and actually needed for some projects.

E.g.:
`hg https://cacert.pep.foundation/dev/repos/pEpiOSAdapter`

**Comment by mdiep** [comment]
This strikes me as an unlikely improvement. It would require quite a bit more code, increase the maintenance burden, and marginal benefit. If you personally require a mercurial repo, you may not find the benefit marginal. But the reality is that the overwhelming majority of Cocoa projects are hosted with Git.

**Comment by adamn** [comment]
Seems unlikely.  This is the only hg repo that doesn't seem to have a git mirror that I can find.  Anyway, that URL uses an untrusted certificate authority so doesn't even work (on Chrome).

**Comment by dirkz** [comment]
Would a pull request be accepted (this is purely hypothetical)? The CA used is CAcert btw.

**Comment by mdiep** [comment]
I don't think we can support this. The maintenance cost would be too high. Sorry. 😞
