### ISSUE TITLE
Xcode does not show symbolicated stack trace for framework while debugging

### ISSUE THREAD

**Issue by andrey-krukovskiy** [Carthage/Carthage#1465]
- `carthage version`: 0.17.2
- `xcodebuild -version`: Xcode 7.3.1 Build version 7D1014
- Are you using `--no-build`? No
- Are you using `--no-use-binaries`? No
- Are you using `--use-submodules`? No

**Cartfile**

```
github "ParsePlatform/Parse-SDK-iOS-OSX" "master"
```

When debugging my app I have crash in Parse.framework. But Xcode does not symbolicate stack trace, it just shows disassembling.

I have run script build phase with `carthage copy-frameworks`. It places framework's dSYMs in the same folder as my app (just near it, not inside app bundle). Is it correct?
What should I do to make Xcode show me framework code while debugging it?

**Comment by andrey-krukovskiy** [comment]
Later today, after forking ParseSDK project and opening it in Xcode to fix some bugs, Xcode start to show source code, when stopped on exception in Parse.framework.

So, I have 2 assumptions.
1. xcode not show framework source code when stopped due to EXC_BAD_ACCESS error but not on exception breakpoint.
2. xcode start showing framework source code after indexing files when i have opened Parse.framework project.

**Comment by NachoSoto** [comment]
I'd recommend that you report this with Apple, I don't think they support this. Crashlytics for example does allow sending DSYM files for 3rd party frameworks.

Good luck getting Apple to do anything about it though 🙃
