### ISSUE TITLE
How to build with XCode8 GM Seed

### ISSUE THREAD

**Issue by netgfx** [Carthage/Carthage#1467]
* `carthage version`: 
* `xcodebuild -version`: 8 
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

I'm wondering how can I build with XCode 8 GM seed (I have both XCode 7 and 8 on my machine). Should I add something to cartfile or if the project that I'm trying to build has Swift 3.0 support it will pick the correct xcodebuild?

**Comment by ikesyo** [comment]
Just use `sudo xcode-select -s /path/to/Xcode_8` to switch your command line tools then run `carthage build`, or `DEVELOPER_DIR=/path/to/Xcode_8 carthage build`. Those are normal `xcodebuild` workflows.

**Comment by netgfx** [comment]
Thanks!
