### ISSUE TITLE
Need help for an "Undefined symbols for architecture x86_64"

### ISSUE THREAD

**Issue by TofPlay** [Carthage/Carthage#1468]
* `carthage version`: 0.18
* `xcodebuild -version`: Xcode 7.3.1 Build version 7D1014
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "OneSignal/OneSignal-iOS-SDK" == 2.1.5
```

**Carthage Output**
```
*** Fetching OneSignal-iOS-SDK
*** Checking out OneSignal-iOS-SDK at "2.1.5"
*** xcodebuild output can be found in /var/folders/rw/gbr9wvs91cz91mcpgdxv4q340000gn/T/carthage-xcodebuild.78v01e.log
*** Building scheme "OneSignal-Dynamic" in OneSignal.xcodeproj
```

No problem to build the module. The issue occurs when we try to build the project. 
Xcode generate a message like this one:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_OneSignal", referenced from:
      type metadata accessor for __ObjC.OneSignal in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
``` 

The bug was reported on the project OneSignal in the [ticket 73](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/73) but I'm not sure if it's related to the project or to Carthage.
OneSignal is written in Objective-C and the project is written in Swift 2.2. With `module.modulemap` we should be use OneSignal as Swift module.
Any help would be appreciated

**Comment by mdiep** [comment]
I don't think this is Carthage related. (The ticket you referenced mentions that the problem occurs when the project is manually built as well.)

That error means that the `OneSignal` class wasn't defined after linking. Usually this means that (a) that class wasn't included in the target or (b) the framework wasn't linked against your app.

**Comment by TofPlay** [comment]
Hi @mdiep thanks for your reply I will check the point (a) and (b)

**Comment by TofPlay** [comment]
OneSignal is linked with my project
![image](https://cloud.githubusercontent.com/assets/1082222/18437342/c3f745c4-78fc-11e6-958a-060a24c5cefc.png)
