### ISSUE TITLE
--no-clean option for the build command

### ISSUE THREAD

**Issue by mz2** [Carthage/Carthage#1469]
I'd like to have some more control over the `carthage build` command whereby the xcodebuild tasks executed by it would not include cleaning the target being built prior to building (i.e. make the `["clean", "build"]` tasks optionally to just `["build"]` in the function `buildScheme` in Xcode.swift.

In the case where I don't need a public release grade definite clean builds, this would commonly fit my needs and speed up my work, especially for libraries that have multiple Carthage based dependencies itself.

I've made a prototype implementation of the idea which I'm happy to polish up into a pull request if this is a feature you'd like to have included. Hopefully I have not overseen some existing functionality that already provides this some other way?

**Comment by mdiep** [comment]
Our hope is that instead of adding a `--no-clean` option, we can transparently skip unchanged dependencies: #1222.

**Comment by mz2** [comment]
I figured you'd say that :-) Thing is, this is achievable as a tiny (i.e. safe) change and I'm proposing it as a non-default option. Arguably it would be made redundant indeed by the work needed to complete #1222 successfully, though you may still want to be more lenient even with that in.

**Comment by falcon283** [comment]
Any news on `--no-clean`
It will tremendously speed up the Private Libraries development adding them as submodule and rebuild only the changed files

**Comment by ikesyo** [comment]
Closed by #2102.
