### ISSUE TITLE
Just for debug purpose how I can add dSYM files on the device? 

### ISSUE THREAD

**Issue by TofPlay** [Carthage/Carthage#1470]
- `carthage version`: 0.18
- `xcodebuild -version`:  Xcode 7.3.1 Build version 7D1014
- Are you using `--no-build`? No
- Are you using `--no-use-binaries`? No
- Are you using `--use-submodules`? No

**Cartfile**

```
github "tristanhimmelman/AlamofireObjectMapper" == 3.0.2
```

**Carthage Output**

```
*** Fetching AlamofireObjectMapper
*** Fetching ObjectMapper
*** Fetching Alamofire
*** Checking out Alamofire at "3.5.0"
*** Checking out ObjectMapper at "1.5.0"
*** Checking out AlamofireObjectMapper at "3.0.2"
*** xcodebuild output can be found in /var/folders/rw/gbr9wvs91cz91mcpgdxv4q340000gn/T/carthage-xcodebuild.jaQvVD.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
*** Building scheme "AlamofireObjectMapper iOS" in AlamofireObjectMapper.xcworkspace
```

When I test my application on the device a crash occurs on ObjectMapper. 
Just for debug purpose how I can add dSYM files on the device?

**Comment by mdiep** [comment]
The `dSYM`s should get copied as part of `carthage copy-frameworks`. Are they not?

**Comment by TofPlay** [comment]
Hi Matt
dSYM exists on: 
```
/Users/Tof/Library/Developer/Xcode/DerivedData/MyApp-croepzyhkerjplhjhwiyrgbbmpdx/Build/Products/Debug-iphoneos
```

But not under the folder `Frameworks` on my application: 
```
/Users/Tof/Library/Developer/Xcode/DerivedData/MyApp-croepzyhkerjplhjhwiyrgbbmpdx/Build/Products/Debug-iphoneos/MyApp.app/Frameworks
```
On this folder I just have `*.framework` without `*.dSYM`

**Comment by camill-a** [comment]
Any fix about this?

**Comment by xandros6** [comment]
I have the same problem, breakpoint on framework code, but not variable inspection
Can someone help us please?

**Comment by ikesyo** [comment]
Copying dSYM files on a device should not have any effect for debugging. Closing.
