### ISSUE TITLE
 How to use Carthage with iMessage or Sticker Pack Applications?

### ISSUE THREAD

**Issue by timwah** [Carthage/Carthage#1473]
* `carthage version`:  0.17.2
* `xcodebuild -version`:  Xcode 8.0 Build Version 8A218a (GM Seed)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

Create a vanilla `iMessage Application`. Note that these are different than just extensions for existing apps. This creates two targets by default, one is an app which houses the extension (really just a shell and not a normal app), and the message extension itself, which has normal build configuration elements like `Build Phases` where we add our Carthage copy-frameworks stuff. This works great for all our builds except for when it comes time to validate to the App Store, and we get this error:  

    iTunes Store operation failed.
    Invalid Bundle. The bundle at '***.app/PlugIns/MessagesExtension.appex' contains disallowed file 'Frameworks'.

The copy-frameworks call works by copying our frameworks into the frameworks directory of the extension, when it really needs to be in the frameworks directory of the shell app, under: `***.app/Frameworks` (we tested moving them manually and testing to see the app still runs). Unfortunately there's not an obvious way to get these copied to the right location. Possible solutions are: setting up our Carthage dependencies to work with Cocoapods, linking to the source directly (http://www.mokacoding.com/blog/carthage-no-build/) or create a secondary target that moves the frameworks into the correct folder which seems hacky.

**Comment by mdiep** [comment]
This sounds like something that Carthage should handle.

Would you be interested in opening a PR to fix this? The code for this [is pretty self-contained](https://github.com/Carthage/Carthage/blob/master/Source/carthage/CopyFrameworks.swift). It's harder for me to fix it because I don't have an iMessage or Sticker Pack application to test/submit.

In the meantime, it sounds like moving the frameworks manually will enable you to submit?

**Comment by NachoSoto** [comment]
Why not out the copy-frameworks phase in the app target then, if it's needed there?

**Comment by a2** [comment]
@NachoSoto You can't put the copy-frameworks phase in the app target because Xcode doesn't show the Build Phrases tab for iMessage app containers.

**Comment by sprint84** [comment]
@a2 Can you share the solution of how to make it work for iMessage app extensions?

**Comment by a2** [comment]
@sprint84 Sure!

1. Create the `copy-frameworks` phase as normal in the extension target.
2. Open `MyApp.xcodeproj/project.pbxproj` in your editor of choice. (I used Atom, but that's not important.)
3. Search in The Mess™ for "Run Script" or even `copy-frameworks`.
4. Find the "id" of that build phase.
5. Search the pbxproj for that id. You'll find it in a list of other build phases for your extension target.
6. Move that line from into the containing app target.

Hope this helps! I can try to do screenshots if anything is unclear?

**Comment by sprint84** [comment]
No, no need for screenshots.
I was able to follow your steps.

I submitted to the store and it was validated. Let's see how the other steps go!

Thanks.

**Comment by adomanico** [comment]
@a2 your steps didn't seem to work for me. Maybe I was not following correctly.

- Both the main app target and the iMessage target have copy frameworks run scripts with the copy-framewrosk
- Found the run script in the iMessage target in the pbxproj 
- Moved the id from the build phases in iMessage target build phases, to the main target build phases

**Comment by ph1ps** [comment]
@a2 Can you explain step 5-6 a little more please?

**Comment by otymartin** [comment]
@a2 can you add screenshots, I actually tried but it failed again.

**Comment by a2** [comment]
@otymartin Sure! I added screenshots (marked up with Preview.app 😂) to [my post above](https://github.com/Carthage/Carthage/issues/1473#issuecomment-248057162).

**Comment by otymartin** [comment]
@a2 THANKS so much for taking the time. Much appreciated :)

**Comment by ikesyo** [comment]
We should check [the document](https://developer.apple.com/library/content/qa/qa1936/_index.html#//apple_ref/doc/uid/DTS40017538-CH1-COPYING) for correct understanding (and also https://github.com/CocoaPods/CocoaPods/issues/5860, https://github.com/CocoaPods/CocoaPods/pull/5953). Looks like the issue will be fixed in a future Xcode version.

**Comment by timwah** [comment]
Looks like Xcode 8.1 beta has added the 'Build Phases' tab to the containing app target. Adding the copy-frameworks build phase to this app target instead of the extension target seems to work.

**Comment by ikesyo** [comment]
Xcode 8.1 is officially released so this should be closed now.
