### ISSUE TITLE
carthage update specific dependencies

### ISSUE THREAD

**Issue by tcurdt** [Carthage/Carthage#1481]
* `carthage version`: 0.17.2
* `xcodebuild -version`: Xcode 8.0. Build version 8A218a
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
NA

**Carthage Output**
NA

Just to describe my process of updating specific dependencies:
1. comment out all dependencies in Cartfile.private
2. comment out all dependencies I do not want to touch in `Cartfile`
3. delete the checkout of the dependencies I want to update
3. carthage update - to update the dependencies in question
4. uncomment all dependencies in `Cartfile` and `Cartfile.private`
5. restore the old `Cartfile.resolved` and update the updated deps

Come on guys - there must be a better way!

One would hope `carthage update --platform iOS SomeDependency  OtherDependency` would just work.

**Comment by dcaunt** [comment]
What's not working here? `update` does take a list of dependencies to be updated.

**Comment by tcurdt** [comment]
@dcaunt maybe in theory https://github.com/Carthage/Carthage/issues/1418

**Comment by ikesyo** [comment]
This should just work. You should try re-installing carthage or clearing `Carthage` directory.

**Comment by tcurdt** [comment]
@ikesyo it "should" that's true. But just closing the issue does not make this go away.

How would one ever be able to reproduce this problem with a clear `Carthage` directory?

**Comment by ikesyo** [comment]
`carthage update` also works as expected:

```bash
$ carthage update Quick Nimble Reachability.swift --platform iOS
*** Fetching Nimble
*** Fetching Quick
*** Fetching Reachability.swift
*** Fetching KeychainAccess
*** Fetching unbox
*** Fetching Alamofire
*** Fetching Rex
*** Fetching ReactiveCocoa
*** Fetching SnapKit
*** Fetching Result
*** Checking out Nimble at "v4.1.0"
*** Checking out Quick at "v0.9.3"
*** Checking out Reachability.swift at "v2.4"
*** xcodebuild output can be found in /var/folders/ch/frqqndbn45l5dxldwqprh0jr0000gn/T/carthage-xcodebuild.scxji8.log
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Quick-iOS" in Quick.xcworkspace
*** Building scheme "Reachability" in Reachability.xcodeproj
```
