### ISSUE TITLE
Swift 3.0 - Some object files have incompatible Objective-C category definitions

### ISSUE THREAD

**Issue by agiguere** [Carthage/Carthage#1482]
- `carthage version`: 0.17.2 and 0.18
- `xcodebuild -version`: 8A218a
- Are you using `--no-build`? no
- Are you using `--no-use-binaries`? no
- Are you using `--use-submodules`? no

After migrating my iOS Dynamic Cocoa Touch Framework to Swift 3.0, I got this warning after running the Carthage update command line for my app:

`ld: warning: Some object files have incompatible Objective-C category definitions. Some category metadata may be lost. All files containing Objective-C categories should be built using the same compiler.`

My framework has a static library from a third party vendor (Infinite Peripherals), this is a library in objective-c for establishing a connection between iOS devices and the sleeves (scanner).

I have created a Swift Class that abstract the vendor API (Objective-C) inside the framework and our enterprise app use this framework for code sharing

All our apps where working fine before, on Xcode 7.x, iOS 9.3, Carthage 0.17.2

Now if I ran my app (build with Xcode 8) on an iOS 9.3 device it works but if I ran it on iOS 10 it does not works

when I say it does not work, I mean the communication between the barcode reader (LinePro5) and the iPod is not establish)

If I create the same framework and drag it inside my app (instead of using Carthage) it will works on iOS 10, so I doubt this bug is related to the vendor library

any idea ?

thanks

**Comment by mdiep** [comment]
Is carthage downloading binaries for any of your dependencies? If so, you probably need to use `--no-use-binaries` for now.

Otherwise, try deleting `~/Library/Developer/Xcode/DerivedData/`? It sounds like something somewhere was built with Xcode 7.x.
