### ISSUE TITLE
Will too many dynamic frameworks make App launch time increase?

### ISSUE THREAD

**Issue by foobra** [Carthage/Carthage#1483]
* `carthage version`: 0.18
* `xcodebuild -version`: Xcode 8.0 Build version 8A218a
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

According to WWDC2016 Session 406
http://asciiwwdc.com/2016/sessions/406 

> " So, I have an app here that currently has 26 dylibs, And it's taking 240 milliseconds just to load those, but if I change it and merge those dylibs into two dylibs, then it only takes 20 milliseconds to load the dylibs. 
> 
> So I can still have dylibs, I can still use them to share, functionality between my app and my extension, but, limiting them will be very useful." 

So, every dependency build with carthage is dynamic framework, **will too many dynamic frameworks make app launch time increase?**, and how can we avoid it?
@ref https://github.com/Carthage/Carthage/issues/1379

Btw, we use carthage as our inhouse components dependency solutions, we have 50+ components, are we abuse carthage this way?

**Comment by foobra** [comment]
There are two cocoapods plugin try to resolve this problem
https://github.com/Ruenzuo/cocoapods-amimono
https://github.com/johnno1962/Accelerator

**Comment by mdiep** [comment]
Yes, more dynamic frameworks will increase app launch time. You'll need to decide for yourself whether that's a price worth paying.

Unfortunately, there's nothing that Carthage can do about this AFAIK. Ideally, Apple would provide some way to merge dynamic frameworks or something, but they don't.
