### ISSUE TITLE
Checkouts aren't symlinked under submodules

### ISSUE THREAD

**Issue by mdiep** [Carthage/Carthage#1484]
- `carthage version`: 0.18
- `xcodebuild -version`: Xcode 8.0.0
- Are you using `--no-build`? no
- Are you using `--no-use-binaries`? no
- Are you using `--use-submodules`? yes

**Cartfile**

```
github "thoughtbot/Argo" "4b57653"
```

Argo's Rune dependency isn't symlinked because Argo is checked out as a submodule.

**Comment by edwardaux** [comment]
Hi @mdiep ... I raised the initial issue in Argo, and just thought I'd add some more info to give a totally reliable test case - you may already have it, but I figured it can't hurt 😄 

	mkdir test
	cd test
	git init
	echo github \"thoughtbot/Argo\" \"master\" > Cartfile
	carthage bootstrap --use-submodules

whereas running the same set of commands without the `--use-submodules` switch compiles just fine.

**Comment by edwardaux** [comment]
Just a quick FYI... I've finally gotten around to re-checking this one, and the problem is fixed with Carthage 0.22.0 (possibly earlier, but this is the version I tested with). I just closed https://github.com/thoughtbot/Argo/issues/412, so I think this can be closed too

**Comment by mdiep** [comment]
Ah, yup. Fixed by #1715. Thanks for reporting back!
