### ISSUE TITLE
Large repository causing issues, even when using prebuilt tagged releases. 

### ISSUE THREAD

**Issue by seivan** [Carthage/Carthage#1485]
carthage version: 0.17.2 and 0.18
xcodebuild -version: 8A218a
Are you using --no-build? no
Are you using --no-use-binaries? no
Are you using --use-submodules? no

Using this as an example: 
`github "ReactiveCocoa/ReactiveCocoa" == 4.2.1`

Is there a way Carthage could fetch the prebuilt archives from Github releases without cloning the repository? 

For our private closed source, we're having some issues with new checkouts that take too long because the repository with all its history become around 6 gigs. Now, granted that's only the first time, still looking to see if there is a way around it.

I mean if you're specifying a tag, why would it need to fetch so much? 

Edit: 
Occasionally, this pops up

```
Cloning Sample
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/seivan/Sample.git /Users/dev/Library/Caches/org.carthage.CarthageKit/dependencies/Sample) failed with exit code 128:
fatal: unable to open /Users/dev/Library/Caches/org.carthage.CarthageKit/dependencies/Sample/objects/pack/tmp_pack_jponnc: No such file or directory
fatal: index-pack failed
```

**Comment by mdiep** [comment]
This is possible, but it would require some work. And fetching the repo might still be required for running `carthage update`.

Ideally, passing `--no-checkout` would result in the behavior you describe.

PRs welcome. ☺️

**Comment by seivan** [comment]
@mdiep Would --no-checkout use the prebuilt binaries directly without checking out the entire tree? 
That's not the current behaviour on my end. But I'll look into it again. Thanks.

Would there be anything that would prevent binaries being used? I've noticed that it sometimes doesn't use them but instead just checks it out. 
Build/ is empty and Checkouts/ contain the repository. 

Does the name of the binary matter? 
I currently rename it from MyStuff.framework.zip to MyStuff_1.1.1.framework.zip - would that cause any issue? 

Will try --no-checkout again. Thanks!

**Comment by mdiep** [comment]
> Would --no-checkout use the prebuilt binaries directly without checking out the entire tree? 
> That's not the current behaviour on my end. But I'll look into it again. Thanks.

I think that'd be ideal, yes. But it's probably not the current behavior for a number of reasons.

> Does the name of the binary matter? 
> I currently rename it from MyStuff.framework.zip to MyStuff_1.1.1.framework.zip - would that cause any issue?

Nope, the name doesn't matter.

**Comment by seivan** [comment]
That sounds great. I think I have enough for looking into implementing this (if it's okay with you).
Do you want to close the ticket or leave it open?

**Comment by mdiep** [comment]
> That sounds great. I think I have enough for looking into implementing this (if it's okay with you).

Awesome! If you get stuck, open a PR with comments and I'll try to help out.

> Do you want to close the ticket or leave it open?

Let's leave it open.

**Comment by ikesyo** [comment]
Would this conflict with #1466?

**Comment by mdiep** [comment]
I don't think so. If it's hidden behind `--no-checkout` it should be okay? But it would require that all frameworks are pre-built. 😕 

It's probably not a great idea.
