### ISSUE TITLE
Carthage Community

### ISSUE THREAD

**Issue by geoffreywiseman** [Carthage/Carthage#1487]
I can't find an officially sanctioned Carthage community -- a place to ask questions, discuss. Is there one that I'm falling to find, and if not, shouldn't there be one? When you have a question, you could open a GitHub issue, but that doesn't seem like a great way to go about it.

**Comment by mdiep** [comment]
Questions are welcome here. There isn't anything else ATM.

**Comment by geoffreywiseman** [comment]
A project I'm working on has an internal dependency which depends on another internal dependency which depends on [marmelroy/Zip](https://github.com/marmelroy/Zip/), and there's been a longstanding issue that I need to do a carthage bootstrap or update on the internal dependency in order to avoid "Missing required module: minizip". I've been watching [an issue associated with that](https://github.com/marmelroy/Zip/issues/24), and it was recently closed with the comment "I couldn't find a Carthage solution". I'm no Carthage expert, so I thought I'd see if I could find people who knew it better, and could suggest a path that might help, but... then I couldn't find anywhere to discuss it. ;)

Anyway -- if there's nowhere else for now, and anyone has any suggestions that would help marmelroy (or even me, via a PR), I'm happy to hear it. This might be a simple problem with a simple solution, or it might not -- I'm new enough to Carthage to admit that I don't know, I just don't like the end effect -- that I get errors unless I bootstrap.

**Comment by ikesyo** [comment]
Looks like the project now re-added Carthage support:

- https://github.com/marmelroy/Zip/commit/355962fa13094ad639f3dfe69b9eaab862d41981
- https://github.com/marmelroy/Zip/issues/45

**Comment by mdiep** [comment]
Does that resolve your issue, @geoffreywiseman?

**Comment by geoffreywiseman** [comment]
Well, at least Zip is back on Carthage, but whether it solves the bootstrap-or-update problem, i guess I won't truly learn until I move to Swift 3. If I get a chance, I'll try making a sample Swift 3 project that depends on Zip to find out.
