### ISSUE TITLE
SemVer tilde ranges (~>) vs. behavior in other frameworks

### ISSUE THREAD

**Issue by khawkins** [Carthage/Carthage#1490]
* `carthage version`: 0.18
* `xcodebuild -version`: Xcode 8.0 Build version 8A218a
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "khawkins/TestCarthageReleases" ~> 1.0.0
```

**Carthage Output**
```
*** Fetching TestCarthageReleases
*** Downloading TestCarthageReleases.framework binary at "Release 1.1.1"
*** xcodebuild output can be found in /var/folders/pm/kr4s7mn573z5yf061bj218g0tkb0l4/T/carthage-xcodebuild.8KZjQU.log
```

I've been toying with the consumption of Carthage dependencies using tilde ranges, to get a feel for what limitations exist.  Off the bat, I know that different packaging/dependency frameworks have different expectations for what a given range looks like, based on the client setting.

For example, both [Ruby](http://guides.rubygems.org/patterns/#pessimistic-version-constraint) and [CocoaPods](http://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions) go "up" a version demarcator in determining their support.  For example:

- "project" ~> 1.2 := >= 1.2.0 && < 2.0
- "project" ~> 1.2.0 := >= 1.2.0 && < 1.3.0

Whereas [npm](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1) looks at its range from the last version demarcator specified, at least down to the minor version.  E.g.:

- "project" ~> 1.2 := >= 1.2.0 && < 1.3.0
- "project" ~> 1.2.0 := >= 1.2.0 && < 1.3.0
- "project" ~> 1 := >= 1.0.0 && < 2.0.0

But while both of these approaches are slightly (if fundamentally) different, there is one part of the approach that they both do the same: make progressive versioning decisions based on the presence of the major, minor, or patch version in the tilde range specifier of the consumer.  Carthage does not seem to do this.  Instead, my trials seem to suggest that, aside from the 0.x special case support, it's otherwise hard-coded to only consider the major version field as the meaningful field of the range demarcator.

It would be nice if Carthage conformed to one of the progressive range validation approaches above—IMO the ideal would be the CocoaPods/Ruby progressive versioning approach, as I personally find the npm approach to be unnecessarily overwrought.

**Comment by mdiep** [comment]
Carthage follows [the Semantic Versioning spec](http://semver.org). According to Semantic Versioning, there's no reason not to update up-to-but-below the next major API version.

**Comment by khawkins** [comment]
The other projects I mentioned leverage Semantic Versioning as well.  And configurable range specifications in all of these dependency management frameworks, including Carthage's, is written completely independently of the SemVer spec—SemVer makes no allowances one way or another for range specifications, other than general recommendations for API break changes across versions.

You can hold to the line that SemVer doesn't think it's necessary.  But all of these other major dependency management frameworks have determined that more granular configuration is useful—probably based on the consumption trends of the thousands of SemVer-compatible packages that they support.

Anyway, I'll adjust my configuration of Carthage support accordingly.

**Comment by shehabic** [comment]
@mdiep it's quite common in many dependency manager to limit upgrades to patches if you specify them and to minor version if you don't specify minor  e.g.  Composer, NPM as @khawkins mentioned, also looking at the iOS / Swift community the vast majority of vendors of the most common dependencies simply use minor version update to change compiled swift version. e.g. Alamofire, ReactiveExtensions, Swinject and many others.
so for example having   `~> 4.5.0` behaving exactly like `~> 4.5' is a bit dangerous, I hope that you reconsider this change in the near future.

**Comment by gdoublev** [comment]
Piggy-backing on what @khawkins and @shehabic said... would love it if Carthage respected minor and patch version demarcators.
#### Example:
`~> 4.5` being `>= 4.5.0 && < 5.0`
`~> 4.5.0` being `>= 4.5.0 && < 4.6`

**Comment by jamezilla** [comment]
I came here to file a bug, but I guess this is a feature enhancement. I recognize that Carthage follows SemVer and SemVer says 1.2 is backwards compatible with 1.1, but in the real world this is not always the case. It is useful to be able to say "I only want patch versions". 

For a real example, we have Google's Firebase SDK in our app. Today someone ran `carthage update` and it updated Firebase from `5.8.0` to `5.18.0`. Backwards compatible right? It's not. From _Google_.

With the absence of a range operator, or compound version constraint, there is no workaround to achieve "only patch versions". Carthage is the only dependency manager I know of that treats the pessimistic operator this way. Since the pessimistic operator isn't part of the SemVer spec, I guess Carthage is free to do whatever it wants, but I'd like to propose this be reopened as a feature enhancement to bring it into alignment with the conventions of RubyGems, CocoaPods, and npm.

**Comment by mdiep** [comment]
> Backwards compatible right? It's not. From _Google_

Google's SDKs are usually some of the worst. I tend to expect less from them. 🤷🏻‍♂️

**Comment by jamezilla** [comment]
@mdiep would a pull request for this feature enhancement be accepted?

**Comment by mdiep** [comment]
No, I don't think so

**Comment by jamezilla** [comment]
Is there a workaround? The docs indicate the only options are `==`, `>=`, and `~>`.

**Comment by mdiep** [comment]
You can use `==` and complain to Google that they're not following semantic versioning.
