### ISSUE TITLE
carthage update - failed with exit code 65

### ISSUE THREAD

**Issue by NithyaVenkat** [Carthage/Carthage#1491]
Apples-MacBook-Pro:SystemStatus apple$ carthage update
*** Fetching BRYXBanner
*** Checking out BRYXBanner at "0.7.0"
*** xcodebuild output can be found in /var/folders/nc/jrryg2gs72vg47hjnbsyhn700000gn/T/carthage-xcodebuild.6TClaL.log
*** Skipped building BRYXBanner due to the error:
Dependency "BRYXBanner" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/bryx-inc/BRYXBanner/issues/new
Apples-MacBook-Pro:SystemStatus apple$ 

Please help me to resolev the issue with carthage update command..

**Comment by ikesyo** [comment]
That should be a issue on https://github.com/bryx-inc/BRYXBanner, the library actually does not support Carthage. Please file an issue on that repository. Closing.

**Comment by ikesyo** [comment]
https://github.com/bryx-inc/BRYXBanner/commit/14690e5ae70fe642745c839f2bef202646432479#commitcomment-19093242
