### ISSUE TITLE
github api request fails ( timeout ) when behind a proxy

### ISSUE THREAD

**Issue by pav1790** [Carthage/Carthage#1492]
* `carthage version`: 0.17.2
* `xcodebuild -version`: 7.3.1
* Are you using `--no-build`? No.
* Are you using `--no-use-binaries`? No.
* Are you using `--use-submodules`? No.

**Cartfile**
```
# Used for HTTP routing
github "marekcirkos/RoutingHTTPServer"

# Used for USBOverHTTP
github "marekcirkos/peertalk"

# Used for XPath
github "marekcirkos/KissXML"
```

**Carthage Output**
```
carthage bootstrap
GitHub API request failed: NetworkError(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7fcceac15110 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://api.github.com/repos/marekcirkos/KissXML/releases/tags/5.0.5?, NSErrorFailingURLKey=https://api.github.com/repos/marekcirkos/KissXML/releases/tags/5.0.5?, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.})
```
I am running this behind a proxy. I can curl this url and get the info but it always fails via carthage. I have the environment variables and git config variables for proxy setup ( git config --global http.proxy ).

**Comment by wuaschtikus** [comment]
Did you export your proxy address in terminal ?
```
E.g.
export https_proxy=http://******:8080
export http_proxy=http://******:8080
```

**Comment by pav1790** [comment]
Yes. I did find a solution. I had to configure the proxy in the settings --> network preferences, since it looked like a part of the code was ignoring the proxy specs.

**Comment by RuiAAPeres** [comment]
@pav1790 if you found a solution, please close this issue.

**Comment by pav1790** [comment]
@RuiAAPeres Well, I do feel carthage should honor the proxy environment variables set in the system. I am closing it however.

**Comment by jagtu** [comment]
how configure the proxy in the settings ? help!!!
