### ISSUE TITLE
Can't build Bean-iOS-OSX-SDK

### ISSUE THREAD

**Issue by alex-vasenin** [Carthage/Carthage#1494]
* `carthage version`: 0.16.2
* `xcodebuild -version`:  Xcode 8.0 Build version 8A218a
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? yes

**Cartfile**
```
github "PunchThrough/Bean-iOS-OSX-SDK" ~>3.0
```

**Carthage Output**
```
*** Fetching Bean-iOS-OSX-SDK
*** Fetching PromiseKit
*** Checking out Bean-iOS-OSX-SDK at "3.0.0"
*** xcodebuild output can be found in /var/folders/x9/_m8tmjpx2d3f8wrlnb1r43jr0000gn/T/carthage-xcodebuild.YcMCPN.log
*** Skipped building Bean-iOS-OSX-SDK due to the error:
Dependency "Bean-iOS-OSX-SDK" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/PunchThrough/Bean-iOS-OSX-SDK/issues/new
```

**Comment by alex-vasenin** [comment]
It looks like it's simply can't find `.xcodeproj` which located in subdirectory. I was able to build the project manually with `xcodebuild -project ./Bean\ OSX\ Static\ Library/Bean\ OSX\ Library.xcodeproj/ -target "Bean iOS Library"`. How could I pass those options to Carthage?

**Comment by ikesyo** [comment]
Carthage does not support static frameworks, so the library is not Carthage compatible. Closing.
