### ISSUE TITLE
Is there a plan to support setting options for each?

### ISSUE THREAD

**Issue by RyogaK** [Carthage/Carthage#1496]
Carthage has some options such as
- --no-use-binaries
- --toolchain

and more.

There, there is a case we want to use `--no-use-binaries` for just a part of those libraries. However, there is no clean way for now.
We can run `carthage bootstrap` for each library. but this way has no scalability and annoys developers while setting up the project after checkout.

Is there a plan to deal with this? or do you know the clean solution?

I hope the way as following:

Cartfile
```
github "foo/bar" ~> 1.0.3, no-use-binary, toolchain=com.apple.dt.toolchain.Swift_2_3
github "baz/qux" == 1.1.3
```

**Comment by ikesyo** [comment]
It doesn't seem to work (specifically `--toolchain` option) for me. You can't mix Swift (2.2|2.3) binaries and Swift 3 binaries since there is no ABI compatibility yet.

**Comment by RyogaK** [comment]
@ikesyo Yeah, I know. but that is bad example. sorry.
At least, I just want to mention about `--no-use-binary`.

**Comment by mdiep** [comment]
#262 covers this, but no one is actively working on it AFAIK.

I don't think Carthage is ready to add this complexity. There are more important improvements to be made atm.
