### ISSUE TITLE
"carthage update" work with Xcode8 Swift3.0 will degrade framework

### ISSUE THREAD

**Issue by zhangxiaolian1991** [Carthage/Carthage#1498]
* `carthage version`:  0.18.
* `xcodebuild -version`:  Build version 8A218a
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO

**Cartfile**
```
<YOUR CARTFILE>
github "teambition/AMRAudioSwift"
github "teambition/Alamofire" "ios8-support"
github "teambition/BadgeListView"
github "teambition/BadgeNumberView"
github "teambition/CardStyleTableView"
github "CocoaLumberjack/CocoaLumberjack"
github "krzyzanowskim/CryptoSwift"
github "teambition/DropdownMenu"
github "teambition/GrowingTextView"
github "teambition/HanziPinyin"
github "teambition/KeyboardAvoiding"
github "onevcat/Kingfisher"
github "matthewpalmer/Locksmith"
github "mdiep/MMMarkdown"
github "teambition/MaskProgressView"
github "kgn/NSDate-TimeAgo" "swift3"
github "teambition/NotificationView"
github "Hearst-DD/ObjectMapper"
github "teambition/PhotoPicker"
github "teambition/Queue"
github "teambition/RRuleSwift"
github "teambition/RazzleDazzle" "master"
github "ashleymills/Reachability.swift"
github "teambition/RefreshView"
github "ReactiveX/RxSwift"
github "teambition/SegmentedControl"
github "SnapKit/SnapKit"
github "teambition/Snapper-swift"
github "malcommac/SwiftDate" "feature/swift-3.0"
github "teambition/SwiftyEmojiKeyboard"
github "SwiftyJSON/SwiftyJSON"
github "teambition/SwipeableTableViewCell"
github "teambition/TBEmptyDataSet"
github "teambition/ViewFaster"
github "teambition/WeChatSDK"
github "teambition/WebBrowser"
github "ibireme/YYText"
github "intercom/intercom-ios"
github "iziz/libPhoneNumber-iOS"
github "teambition/mixpanel-iphone"
github "AgileBits/onepassword-extension" "add-framework-support"
github "teambition/FilePreviewController"
github "teambition/JSONWebToken"
github "teambition/MessageKit"
github "teambition/PhotoBrowser"
github "teambition/RecurrencePicker"
github "teambition/STTableBoard" "0.2.0"
github "teambition/SimpleActionSheet" "v2.0"
github "teambition/SimplePasscode" "v2.0"

```

**Carthage Output**
```
<OUTPUT>
[carthage-xcodebuild.OykViv.txt](https://github.com/Carthage/Carthage/files/491670/carthage-xcodebuild.OykViv.txt)


```
My Cartfile has many dependencies, Run "carthage update " degrade my  dependencies version, and project cannot build. Any idea, or help?

**Comment by ikesyo** [comment]
We are not sure what's happening from the description. Could you please provide more details or a minimal reproducible case?

**Comment by zhangxiaolian1991** [comment]
I have a framework [STTableBoard](https://github.com/teambition/STTableBoard) which release tag is 0.2.0, But when I run ```carthage update```, The checkout version is 0.0.18 or other earlier version. I really have no idea

**Comment by mdiep** [comment]
Can you please provide a copy of your `Cartfile` and the output of running `carthage update`?

**Comment by zhangxiaolian1991** [comment]
I am running in a clean project, is there any  reason could infect the framework version when run ```carthage update```?

**Comment by mdiep** [comment]
One of your other dependencies could be specifying a different version. If you don't provide your `Cartfile` and the output of `Carthage update`, there's nothing we can do for you.

**Comment by zhangxiaolian1991** [comment]
@mdiep I have edit the deatil of this issue.  This time ```[PhotoBrowser](https://github.com/teambition/PhotoBrowser) ``` is not right version which lastest version is 0.5.0 . But what I checkout is 0.0.1 .   By the way, [PhotoPicker](https://github.com/teambition/PhotoPicker) has a dependency on the  ** PhotoBrowser**

**Comment by lottadot** [comment]
@zhangxiaolian1991 try clearing ~/Library/Caches/org.carthage.CarthageKit I've seen it "stick" to an old dependency that's been cached in there. Note that I've yet to make it happen repeatedly.

**Comment by zhangxiaolian1991** [comment]
@lottadot It's not working

**Comment by mdiep** [comment]
@zhangxiaolian1991 I think you're hitting a bug where non-semantic tagged versions lead to choosing incorrect constraints. This is a known issue that I'm trying to address, but don't have a fix for yet. (#469)

In the meantime, you can probably work around the issue by specifying versions for your dependencies in your Cartfile. This has nothing to do with Xcode 8 or Swift 3.

**Comment by zhangxiaolian1991** [comment]
@mdiep OK ，thanks
