### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftQuartzCore.dylib

### ISSUE THREAD

**Issue by skyylex** [Carthage/Carthage#1500]
I updated Carthage version to 0.18 (previously had older version), using Homebrew. After that carthage commands constantly print this error. I tried to reinstall, clean CarthageKit and etc, without any result.

* `carthage version`: 0.18
* `xcodebuild -version`: Xcode 8.0 Build version 8A218a
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Carthage Output**
```
$ carthage
dyld: Library not loaded: @rpath/libswiftQuartzCore.dylib
  Referenced from: /Library/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by ikesyo** [comment]
Looks like you previously installed Carthage with pkg installer, right? You should need to remove `/Library/Frameworks/CarthageKit.framework` to avoid a conflict with homebrew installation in that case.

**Comment by skyylex** [comment]
@ikesyo thanks for quick response. I saw this solution for old versions and tried it, unfortunately without any success. Still have the same error.

**Comment by mdiep** [comment]
Try also removing `/Library/Frameworks/ReactiveCocoa.framework/`.

**Comment by skyylex** [comment]
@mdiep removal of the framework works! Thanks a lot! I also removed several other frameworks which produced the same result until I got proper output from `carthage` call. Issue could be closed.
