### ISSUE TITLE
Carthage update fetches only the first prebuilt framework from release

### ISSUE THREAD

**Issue by Antondomashnev** [Carthage/Carthage#1501]
Hi there, I'm running the command `carthage update` and the only dependency I have is a repo with 5 prebuilt frameworks in the release.

* `carthage version`: 0.18
* `xcodebuild -version`: Xcode 8.0 Build version 8A218a
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "conichiGMBH/ios-utilities.git" >= 3.0 //this is a private repo
```

**Carthage Output**
Carthage finishes with success, but in the build folder I have only one framework which is the first in the release page.
I think I could provide a demo project if needed.

**Comment by ikesyo** [comment]
That is an expected behavior. You need to attach single zip file which contains multiple frameworks.

**Comment by Antondomashnev** [comment]
@ikesyo thanks for the quick reply, do I need to create that single zip manually or I can do it with carthage?

**Comment by ikesyo** [comment]
You can do it with Carthage: `carthage archive Foo Bar --output ios-utilities.framework.zip`

**Comment by Antondomashnev** [comment]
Amazing, thanks
