### ISSUE TITLE
macOS Sierra supports?

### ISSUE THREAD

**Issue by SethCody** [Carthage/Carthage#1502]
* `carthage version`: 0.18
* `xcodebuild -version`: 8A218a
* Are you using `--no-build`?No
* Are you using `--no-use-binaries`?No
* Are you using `--use-submodules`?No

<YOUR CARTFILE>
github "SVProgressHUD/SVProgressHUD" ~> 1.0
github "ReactiveCocoa/ReactiveSwift"
github "Alamofire/Alamofire" ~> 4.0

In Sierra,I can't find the methods of ReactiveSwift.

**Comment by ikesyo** [comment]
That's not related to Sierra at all. Carthage will pick up a latest non-prerelease tag if you don't specify a version constraint for a dependency, and ReactiveSwift currently only have one prerelease tag of `1.0.0-alpha.1` You should need to explicitly specify the tag in this case: `github "ReactiveCocoa/ReactiveSwift" "1.0.0-alpha.1"`.

**Comment by ikesyo** [comment]
Please don't duplicate a issue (https://github.com/ReactiveCocoa/ReactiveSwift/issues/41). Closing.
