### ISSUE TITLE
`fetch` fails when using HTTP access on Github Enterprise

### ISSUE THREAD

**Issue by takizawa-hiroki** [Carthage/Carthage#1505]
* `carthage version`: 0.18
* `xcodebuild -version`: Xcode 8.0 Build version 8A218a
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "http://ghe.foobar.local/anytime/anywhere"
```

**Carthage Output**
```
Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.

Illegal instruction: 4
```

I am not prepare a SSL certificate for Github Enterprise.
The above error occurs when execute `carthage fetch`.
It seems to implement that `preferHTTPS` always becomes `true` in `Fetch.swift`.
Is it intended?

// That does not matter because it is no probrem to use SSH.

thanks

**Comment by ikesyo** [comment]
Thanks for filing the issue and sorry for the inconvenience. This should be related to https://github.com/mdiep/Tentacle/pull/42 and will be hopefully fixed in a next release. Temporarily you would be able to work around the issue by downgrading Carthage to 0.17.2 I think.

**Comment by takizawa-hiroki** [comment]
@ikesyo Awesome! I am looking forward to a new release.
Thank you :-)
