### ISSUE TITLE
Handling nested frameworks (building when unnecessary)

### ISSUE THREAD

**Issue by gbrhaz** [Carthage/Carthage#1506]
- `carthage version`: 0.18
- `xcodebuild -version`: 7.3
- Are you using `--no-build`? NO
- Are you using `--no-use-binaries`? YES
- Are you using `--use-submodules`? NO

**APP Cartfile**

```
github "internal/frameworkA" "1.0"
github "internal/frameworkB" "1.0"
```

**FrameworkA Cartfile**

```
github "CocoaLumberjack/CocoaLumberjack" ~> 2.3
github "kishikawakatsumi/KeychainAccess" ~> 2.3.5
```

**FrameworkB Cartfile**

```
github "Alamofire/Alamofire" ~> 3.2
github "Hearst-DD/ObjectMapper" ~> 1.3
github "kasketis/netfox" ~> 1.7.2
github "internal/frameworkA" "1.0"
```

So as you can see, App depends on FrameworkA and FrameworkB.

FrameworkB also depends on FrameworkA.

This all works fine, but I'm wondering whether I can make it so Carthage doesn't need to rebuild all the nested dependencies (such as Alamofire, ObjectMapper etc) if I only make changes in the projects of FrameworkA and FrameworkB? Right now if I do a `carthage update FrameworkB` it fetches and builds all of the other nested dependencies like so:

**Output**

```
*** Fetching FrameworkB
*** Fetching netfox
*** Fetching ObjectMapper
*** Fetching Alamofire
*** Fetching KeychainAccess
*** Fetching CocoaLumberjack
*** Checking out Alamofire at "3.5.0"
*** Checking out CocoaLumberjack at "2.4.0"
*** Checking out KeychainAccess at "v2.4.0"
*** Checking out netfox at "1.8"
*** Checking out ObjectMapper at "1.5.0"
*** Checking out FrameworkA at "1.0"
*** Checking out FrameworkB at "1.0"
*** xcodebuild output can be found in bla bla
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "CocoaLumberjack" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjack-iOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift-iOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift" in Lumberjack.xcworkspace
*** Building scheme "KeychainAccess" in KeychainAccess.xcworkspace
*** Building scheme "netfox_ios" in netfox.xcodeproj
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
*** Building scheme "FrameworkA" in WorldRemitCore.xcodeproj
*** Building scheme "FrameworkB" in WorldRemitNetworking.xcodeproj
```

If I only do a one line change in FrameworkB, it rebuilds all these and takes a good few minutes. Any way around this?

**Comment by mdiep** [comment]
No, there isn't. Right now, dependencies will always get rebuilt for a project is built.

#1222 should help with this.

**Comment by tariq235** [comment]
@mdiep  @ikesyo  @gbrhaz I am wondering if there is an alternate solution for this problem. Is this included in Carthage feature roadmap at all ?

Similar to Cocoapods - Dependent framework will not be downloaded at all if we have already downloaded the same version earlier.

So as per original issue - If do pod update FrameworkB then it can fetch all the FrameworkB code but it should not download Alamofire and other framework at all.

**Comment by mdiep** [comment]
I'm focused on correctness, testability, and speed of existing features. So this is not on my personal roadmap. There's not a Carthage roadmap because this is a community project driven by individual contributors.

**Comment by ikesyo** [comment]
Closing this in favor of #1654. And also you can make use of `--cache-builds` option nowadays.
