### ISSUE TITLE
-bash: github: command not found

### ISSUE THREAD

**Issue by yokesharun** [Carthage/Carthage#1508]
- `carthage 0.18`: 
- `xcodebuild -7.3`: 
- Are you using `--no-build`?
- Are you using `--no-use-binaries`?
- Are you using `--use-submodules`?

**Cartfile**

```
<YOUR CARTFILE>
```

**Carthage Output**

```
<OUTPUT>
```

**Comment by mdiep** [comment]
Can you please provide your `Cartfile` and the output from running `carthage`?
