### ISSUE TITLE
Nested dependencies with static libraries. Framework feels bad.

### ISSUE THREAD

**Issue by lolgear** [Carthage/Carthage#1514]
I develop a framework with only one dependency.

podspec configured well. Everything works.

One dependency.

Now I am trying to add Carthage support.

Top folder of the project contains Cartfile with dependency: `github name/name`

Build this framework by carthage.
And fails, of course, because framework doesn't know where is the library at `carthage update` phase.

How it should be configured?
Does it need special folder/project file for dependencies?

**Comment by ikesyo** [comment]
Carthage does not support static frameworks as stated in the README.
