### ISSUE TITLE
Xcode 8 Can not build with carthage

### ISSUE THREAD

**Issue by stevenwy** [Carthage/Carthage#1520]
I'm migrating my project from 7.3.1 to 8.0, and I have some code written in old version of Swift, so I set Use Legacy Swift Language Version to YES. When I build and run, I get this
```
Module file was created by an older version of the compiler; rebuild 'Charts' and try again
```
This is kind of Swift compatibility problems, then I use carthage `update --no-use-binaries`, and I get error from xcodebuild.

See below for details

* `carthage version`: 0.18-19-g743fa0f
* `xcodebuild -version`: Xcode 8.0    Build version 8A218a
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? YES
* Are you using `--use-submodules`? NO

**Cartfile**
```
github "SnapKit/SnapKit" >= 0.15.0
github "danielgindi/Charts" == 2.3.0
github "ReactiveCocoa/ReactiveCocoa"
```

**Carthage Output**
```
*** Fetching ReactiveCocoa
*** Fetching Charts
*** Fetching SnapKit
*** Fetching Result
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "v1.1.0"
*** Checking out Charts at "v2.3.0"
*** Checking out Result at "2.1.3"
*** Checking out ReactiveCocoa at "v4.2.2"
*** Checking out SnapKit at "3.1.0"
*** xcodebuild output can be found in /var/folders/n4/ly193t_d7d1326f41qn6d7fr0000gn/T/carthage-xcodebuild.xnRGEX.log
*** Building scheme "Realm" in Realm.xcworkspace
2016-10-08 17:10:14.761 xcodebuild[18149:896423] [MT] DVTPlugInManager: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for KSImageNamed.ideplugin (com.ksuther.KSImageNamed) not present
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/jieding/Desktop/hfsparent/Carthage/Checkouts/SnapKit/SnapKit.xcworkspace -scheme "SnapKit OSX" -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
2016-10-08 17:10:34.535 xcodebuild[18361:897289] [MT] DVTPlugInManager: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for KSImageNamed.ideplugin (com.ksuther.KSImageNamed) not present
xcodebuild: error: Scheme SnapKit OSX is not currently configured for the clean action.
```

**Comment by mdiep** [comment]
Try clearing `~/Library/Developer/Xcode/DerivedData`. You've got some old files from Xcode around that need to be cleared.

**Comment by stevenwy** [comment]
Thank you @mdiep, It works, I cleared DerivedData and changed Cartfile.
`
github "SnapKit/SnapKit" == 0.22.0
github "danielgindi/Charts" == 2.3.0
github "realm/realm-cocoa" "master"
`

**Comment by dsqrbAES** [comment]
I have the same issue.  I tried the solution recommended by @mdiep, but I still have the same problem.  Any other ideas?

**Comment by ivanyang1984** [comment]
The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/roro_latrobe/wanda/workspace/tools/debug/json-viewer-ios-swift/Carthage/Checkouts/Bond/Bond.xcodeproj -scheme Bond -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
2016-10-19 13:49:33.363 xcodebuild[37818:2740095] [MT] DVTPlugInManager: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for KSImageNamed.ideplugin (com.ksuther.KSImageNamed) not present
** CLEAN FAILED **

**Comment by hcaohr** [comment]
Go to this website: https://github.com/Carthage/Carthage/releases, download 'Carthage.pkg' and double click to install, this method resolve my question, hope this can resolve this issue.
