### ISSUE TITLE
Carthage only differentiating on repo name, not using organisation name breaks git checkout

### ISSUE THREAD

**Issue by lindskogen** [Carthage/Carthage#1522]
- `carthage version`: 0.18.1
- `xcodebuild -version`: Xcode 8.0 Build version 8A218a
- Are you using `--no-build`? No
- Are you using `--no-use-binaries`? No
- Are you using `--use-submodules`? No

**Cartfile**

```
github "mxcl/PromiseKit" ~> 4.0
github "PromiseKit/Alamofire" ~> 1.0
```

**Carthage Output**

```
*** Fetching Alamofire
*** Fetching PromiseKit
*** Fetching Alamofire
*** Checking out Alamofire at "4.0.1"
*** Checking out Alamofire at "1.0.2"
A shell task (/usr/bin/env git checkout --quiet --force 1.0.2) failed with exit code 1:
error: pathspec '1.0.2' did not match any file(s) known to git.
```

**Comment by oddysee** [comment]
Another afflicted user.

**Comment by ikesyo** [comment]
Rationale: https://github.com/Carthage/Carthage/issues/1769#issuecomment-281675598
