### ISSUE TITLE
Carthage archive on private repo

### ISSUE THREAD

**Issue by soheilbm** [Carthage/Carthage#1525]
* `carthage version`: 0.18.1
* `xcodebuild -version`: 8.0
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO

**Cartfile**
```
git "git@github.com:soheil/Poi.git" "v1.0.0"
```

I'm using a private repo "Poi" which contains a zip archive framework in the release version. 
I noticed that when I run carthage update, it never download the archived file, instead it clone and build the Poi repo. But when I change the "Poi" repo to Public repo, it download the archive file.

Is there anything I need to do for private repos to be able to use archive framework?

**Comment by ikesyo** [comment]
Carthage downloads prebuilt binaries which are attached to GitHub releases. So `git` origin does not support that feature currently. See #722 and #1308 for the details.
