### ISSUE TITLE
Looking for an appropriate workflow

### ISSUE THREAD

**Issue by gbrhaz** [Carthage/Carthage#1526]
I want to switch to Carthage for my project, which has grown to a significant size. Xcode takes about 7 minutes building this project (on a 2015 Macbook Pro), and a significant amount of time just indexing. I also want to split out the project into a few smaller domain-specific frameworks, to more easily create extensions.

Some people seem to gitignore Checkouts and Builds; other people just ignore one and not the other. What are the pros and cons? I can imagine checking in Checkouts is similar to checking in Cocoapods: they don't need to be fetched, and you have the libraries available even if they disappear from the internet. Builds are a different story - the frameworks are normally much larger in size, but one of my main reasons for doing this is to speed up build times. Now I have also noticed that Carthage has capability to archive these frameworks. How can I utilise this so I reduce repository size and have access to the pre-built frameworks? What about CI?

I quite like what [Automatic did with their workflow](https://blog.automatic.com/xcode-can-handle-your-scale-speeding-up-your-workflow-with-prebuilt-frameworks-f7c6e4499545#.pxov0tmzb); they seem to have solved similar issues to what I'm now having. I'm a bit lost with their "quick and easy" way of integrating their frameworks into the workspace to quickly work on them. How does versioning and source control function with such a case? 

It would be great to understand the different workflows available to me so I can best work out what would be best.

**Comment by mdiep** [comment]
> How can I utilise this so I reduce repository size and have access to the pre-built frameworks?

This is covered in the README. Please read that first. Then I'll be happy to answer any questions.

**Comment by gbrhaz** [comment]
I feel like the README for archiving doesn't explain itself properly, or perhaps I'm using it incorrectly. Since creating this comment I have created a separate repo with a private Cartfile with all the necessary dependencies for another app; I am then archiving those dependencies and attaching the `.framework.zip` file to a release. The Cartfile of the main app is then just that one repo. Great, except, when I'm archiving I have to specify each individual dependency. From this I understand archiving should probably be on a per-framework basis rather than multiple (even though it does actually work)? Could this be a feature request? I.e., could it be possible to look at the Cartfile (or Builds folder) when doing `carthage archive` to zip up all dependencies?

**Comment by mdiep** [comment]
Yes, binary releases are only intended to work on the repository that provides the framework. We don't want to be archiving all the frameworks of an app together. But there are some third-party extensions that do that: https://github.com/guidomb/carthage_cache and https://github.com/146BC/RomeBuild.

**Comment by izouxv** [comment]
I write a tool, may be you can try it. It can wget github release or something else URL . github.com/izouxv/cartool
