### ISSUE TITLE
Carthage version 0.18.1 named 0.18-19-g743fa0f

### ISSUE THREAD

**Issue by danielaRiesgo** [Carthage/Carthage#1528]
I wanted to use the new release of carthage and so I downloaded the 0.18.1 release, but when I run `carthage version` it says `0.18-19-g743fa0f`.

I installed it with the following commands:
```
curl -s -L -O https://github.com/Carthage/Carthage/releases/download/0.18.1/Carthage.pkg
sudo installer -pkg Carthage.pkg -target
```

**Comment by guidomb** [comment]
This is currently breaking our bootstrap scripts that automate the process of setting up everything needed to build an iOS project. We can patch our scripts for this special case but I think that the command line tool should report the correct version number. Is this a bug or is there any reason for this version name?

**Comment by mdiep** [comment]
I just replaced the `.pkg` with one that uses the correct version.

The one that was on there was built on Travis. It must not have had the tag, which is why it had that version.
