### ISSUE TITLE
homebrew installation and Xcode 8+

### ISSUE THREAD

**Issue by JetForMe** [Carthage/Carthage#1539]
Hi. Quick question. The Readme seems to say you can only use the homebrew version of Carthage with Xcode 7, implying that I should use the package installation for Xcode 8 and later. Is the case? The reason I'd like to be able to use the homebrew version is that it makes setting up a build environment a lot easier (we have a long list of dependencies, so far everything except Xcode is installable via homebrew).

Could you please clarify if I can keep using Carthage via Homebrew (BTW, I currently have the homebrew version 0.18.1 installed, and it seemed to work just fine with Xcode 8).

Thanks!

**Comment by mdiep** [comment]
That's out of date. It should be Xcode 7.3.1+ now (including Xcode 8).

Any chance you'd like to open a PR to fix it?

**Comment by JetForMe** [comment]
Sure, I can take a stab at fixing the docs. So, from Xcode 7-on, we can use Carthage as supplied via Homebrew?

**Comment by JetForMe** [comment]
Or is 7.3.1 the minimum?

**Comment by ikesyo** [comment]
There should be no Xcode version requirement for just using Carthage (bottoled binaries are used for homebrew installation). The README description is about building Carthage itself. Building Carthage requires Xcode 7.3+ (Swift 2.2 or Swift 2.3).

**Comment by JetForMe** [comment]
That's not at all what the installation instructions say. They offer three options: download an installer, use homebrew "only on Xcode 7.x," or build from sources.

**Comment by ikesyo** [comment]
`brew install carthage` will use bottled binaries and will not build from the source (except if you specify `--HEAD` option). So just installing Carthage by homebrew will not need Xcode normally.

**Comment by JetForMe** [comment]
I understand that. What I'm saying is the current Readme makes no restrictions on Xcode version for the purposes of building, only for the purposes of using Homebrew to install. If you're telling me the Readme is wrong, that's fine, and I'll adjust my PR for the readme that @mdiep requested.

But currently the readme only specifies an Xcode version in the context of using homebrew to install. Perhaps you're saying that's out of date because homebrew _used_ to build from source, and now that it pours from bottle that restriction is no longer applicable. But @mdiep said above it still needed 7.3.1.

**Comment by ikesyo** [comment]
README should be wrong currently then.

**Comment by JetForMe** [comment]
I've modified the Readme. PR: https://github.com/Carthage/Carthage/pull/1540

**Comment by JetForMe** [comment]
By the way, are you able to build with both Swift 2.x and 3.x? How do you do that? No problems with APIs that changed?

**Comment by mdiep** [comment]
We're currently building with both Swift 2.2 and Swift 2.3—with some help from some wrapper APIs.

We've held off on switching to Swift 3 because we'll lose support for building with older Xcode versions. That's caused problems for some users in the past.

**Comment by JetForMe** [comment]
Okay, I fixed that in my PR as well.

**Comment by ikesyo** [comment]
Resolved by #1540.
