### ISSUE TITLE
Can we have a centralized list of projects?

### ISSUE THREAD

**Issue by ColinEberhardt** [Carthage/Carthage#154]
Firstly, great project - very interesting!

Your README states:

> By contrast, Carthage has been created as a decentralized dependency manager. There is no central list of projects, which reduces maintenance work and avoids any central point of failure. However, project discovery is more difficult—users must resort to GitHub’s Trending pages or similar.

Carthage doesn't rely on a central list of projects, which i understand. But I presume it in no way prohibits someone (perhaps the Carthage team) from creating a list of projects that are compatible?

My feeling is that this is necessary for this idea to be a success.

**Comment by modohash** [comment]
I'm contemplating building a site that would essentially allow you to register your carthage compatible project and it will give you metadata about the project and where to find it.

@ColinEberhardt do you still think that this is something that is useful for the community?

I totally agree that the decentralised nature of carthage is key, but a registry where you can lookup a project seems pretty useful. I know it's something I'd like to have.

Food for thought...

**Comment by ColinEberhardt** [comment]
@modohash I'm sure people would find this useful.

**Comment by andrew** [comment]
Yesterday I added support for Carthage to Libraries.io: https://libraries.io/carthage

It finds packages by finding all the open source repositories referenced in all the Cartfiles across every open source project on GitHub, so far it's found about 450.

**Comment by modohash** [comment]
That's pretty sweet, I'll be sure to use this when looking for carthage packages!

**Comment by bvbvyoy** [comment]
安裝軟件包Spectre.Console-版本0.31.0
