### ISSUE TITLE
Carthage auto-selecting clean action for Cocoapods target rather than the framework's target

### ISSUE THREAD

**Issue by maxkramerbcgdv** [Carthage/Carthage#1541]
Hi there,

I'm switching over to Carthage from Cocoapods given the need for significantly faster build times (that don't require re-building 6/7 dependencies from scratch frequently). Everything has worked great and it has been a very simple process thus far. One of our dependencies `ACSPinKit`: https://github.com/arconsis/ACSPinKit does not support Carthage outright, but has no reason not to. 

I followed the Supporting Carthage guide (https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework) and the project already adheres to all of the requirements, but when attempting to build it from within our project, and within the ACSPinKit project itself (fresh clone), we are getting the error below.
- `carthage version`:  0.18.1
- `xcodebuild -version`: 
  Xcode 8.0
  Build version 8A218a
- Are you using `--no-build`? no
- Are you using `--no-use-binaries`? no
- Are you using `--use-submodules`? no

**Cartfile**

```
none
```

**Carthage Output**
`carthage build --no-skip-current --verbose`

```
A shell task (/usr/bin/xcrun xcodebuild -workspace /private/tmp/ACSPinKit/Example/ACSPinKit.xcworkspace -scheme Pods-ACSPinKit-ACSPinKit -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme Pods-ACSPinKit-ACSPinKit is not currently configured for the clean action.
```

What appears to be the problem is that for some reason the auto-selected scheme is incorrect, and it should be selecting `ACSPinKit` instead. Having tried to execute the same command with the correct scheme, the project builds as expected.

`/usr/bin/xcrun xcodebuild -workspace /private/tmp/ACSPinKit/Example/ACSPinKit.xcworkspace -scheme Pods-ACSPinKit-ACSPinKit -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean`

From what I've seen so far, there doesn't seem to be a way of specifying the scheme/target that the workspace should build with, so I was wondering what you recommend to fix the error.

Cheers!
Max.

**Comment by mdiep** [comment]
Carthage is trying to ask for information about that scheme. (The `clean` is added to work around an Xcode 8 bug where `xcodebuild -showBuildSettings` will hang.)

Either Carthage will need to be updated to handle this case or ACSPinKit will need to be reconfigured.

Carthage examines all shared schemes and builds all shared, dynamic framework schemes.

**Comment by maxkramerbcgdv** [comment]
Hi @mdiep thanks for the 'swift' reply!

Clean makes sense, what exactly would need to be reconfigured within the project to make it only see the framework scheme (and thereafter to build the correct framework)?

**Comment by mdiep** [comment]
Sorry, I meant that either (a) the scheme would need to be configured for the clean action or (b) the scheme would need to be unshared.

Carthage can't know what this scheme if it can't ask for the build settings.

**Comment by orschaef** [comment]
Does #1572 fix this?

**Comment by mdiep** [comment]
#1572 should fix this. Please reopen if you're still encountering an issue.

**Comment by maxkramerbcgdv** [comment]
@orschaef @mdiep thanks for the good work! Will test later
