### ISSUE TITLE
Is it possible to avoid installing Carharge to make builds?  (I.e. remove the dependency on `carthage copy-frameworks`)

### ISSUE THREAD

**Issue by rsaunders100** [Carthage/Carthage#1543]
- `carthage version`: 0.18.1
- `xcodebuild -version`: Xcode 8.0 Build version 8A218a
- Are you using `--no-build`? No
- Are you using `--no-use-binaries`? No
- Are you using `--use-submodules`? No

**Cartfile**

```
github "braintree/braintree_ios"  == 4.5.0
```
### Use case
- We want to reduce build time on Travis CI.  
- Cocoapods take 2 mins to compile pods.
- We think that Carthage should be faster (since frameworks are precompiled)
### Problem
- `carthage copy-frameworks` requires a Carthage
- Carthage takes a few mins to intall on Travis
- Also means every developer must install Carthage

I was wondering if there was any way to remove the need to install Carthage to make builds?
### Possible solutions
- If someone can describe what [`copy-frameworks`](https://github.com/Carthage/Carthage/blob/bbb975d1abca40d5b83828e495d3dc9250eb3437/Source/carthage/CopyFrameworks.swift) does I can try to replace it with a shell script?
- Can it be converted it to a standalone swift script?

**Comment by rsaunders100** [comment]
Ok it looks like from reading this issue https://github.com/Carthage/Carthage/issues/188 that the original script was in fact a portable shell script then it got merged with the cartharge codebase as part of https://github.com/Carthage/Carthage/pull/208.  So to get what I want I think I need to use this script.  

```

copy_framework $(SRCROOT)/Carthage/Build/iOS/Braintree3DSecure.framework
# ...
# ...

copy_framework ()
{
    local framework=$1
    local frameworks_folder="${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"

    mkdir -p "${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
    rsync -av "$framework" "$frameworks_folder"

    local framework_path="$frameworks_folder/`basename $framework`"
    local file_path="$framework_path/`basename $framework .framework`"

    if [[ ! "$VALID_ARCHS" =~ "$i386" ]];
    then
        lipo -remove i386 "$file_path" -output "$file_path"
    fi

    if [[ ! "$VALID_ARCHS" =~ "$x86_64" ]];
    then
        lipo -remove x86_64 "$file_path" -output "$file_path"
    fi

    if [[ "$CODE_SIGNING_REQUIRED" -eq YES ]];
    then
        codesign --force --sign "$EXPANDED_CODE_SIGN_IDENTITY" --preserve-metadata=identifier,entitlements,resource-rules "$framework_path"
    fi
}

```

Can anyone confirm if this will work?

**Comment by kenji21** [comment]
same issue... running tests on a simulator is so slow...

Found a quick fix: add your frameworks in embedded binaries (General tab of your target). And then, move the carthage build phase below xcode manage one called : "Embed Frameworks"
And make copy, only when archiving app:

````
# Embedded binaries only when archiving
if [ $ACTION -eq "archive" ] ; then
    /usr/local/bin/carthage copy-frameworks
fi
````

**Comment by kenji21** [comment]
By doing this, the answer to your question is YES for builds that don't archive app (to push to testflight via CI for example)

**Comment by AndrewSB** [comment]
@kenji21 is including the carthage frameworks directly through Xcode without slimming them down (i.e. not running this: 

```bash
if [[ ! "$VALID_ARCHS" =~ "$i386" ]];
    then
        lipo -remove i386 "$file_path" -output "$file_path"
    fi

    if [[ ! "$VALID_ARCHS" =~ "$x86_64" ]];
    then
        lipo -remove x86_64 "$file_path" -output "$file_path"
    fi

    if [[ "$CODE_SIGNING_REQUIRED" -eq YES ]];
    then
        codesign --force --sign "$EXPANDED_CODE_SIGN_IDENTITY" --preserve-metadata=identifier,entitlements,resource-rules "$framework_path"
    fi
```

) alright?

**Comment by kenji21** [comment]
yes, because when having "big" dependencies, copy framework build phase takes too long (for simulator & device):

The build phase to get time:

````
#if [ $ACTION -eq "archive" ] ; then
time    /usr/local/bin/carthage copy-frameworks
#fi
````

Simulator build (each time I run unit tests...):
````
real	0m7.248s
user	0m1.509s
sys	0m3.946s
````

Device build:
````
real	0m15.984s
user	0m5.081s
sys	0m5.504s
````

The Cartfile:

````
git "https://github.com/openium/SwiftiumKit" ~> 1.0
git "https://github.com/Hearst-DD/ObjectMapper" ~> 2.1
git "https://github.com/radex/SwiftyUserDefaults" ~> 3.0
git "https://github.com/Alamofire/Alamofire" ~> 4.0
git "https://github.com/tristanhimmelman/AlamofireObjectMapper" ~> 4.0
git "https://github.com/realm/realm-cocoa" ~> 1.1.0
git "https://github.com/Alamofire/AlamofireNetworkActivityIndicator" ~> 2.0
git "https://github.com/SVProgressHUD/SVProgressHUD" ~> 2.0
````

Sorry @rsaunders100, my initial reply was to answer your question about removing the carthage dep. (and it have a nice benefit)

**Comment by kenji21** [comment]
i386 / x86_64 slices present when sending a build to iTunesConnect with xcode8 is still present. ACTION env var is setted to `install` (not `archive` as I was thinking, due to running `xcodebuild archive` command...)

**Comment by ikesyo** [comment]
One correction against the original description:

> Carthage takes a few mins to intall on Travis

Carthage is preinstalled on Travis so you don't need to do that manually.
