### ISSUE TITLE
Question about how to deal with the conflict dependencies

### ISSUE THREAD

**Issue by KimSmitth** [Carthage/Carthage#1544]
Hi all, I have a question about how to deal with the _conflict_ dependencies, 

My Cartfile is something looks like:

```
github "ReactiveCocoa/ReactiveCocoa" "5.0.0-alpha.1"
github "octokit/octokit.objc"
```

The octokit has an old version of ReactiveCocoa.

What should I do to keep both framework works together? 

> Nested dependencies
> 
> If the framework you want to add to your project has dependencies explicitly listed in a Cartfile, Carthage will automatically retrieve them for you. You will then have to drag them yourself into your project from the Carthage/Build folder.
> 
> If the embedded framework in your project has dependencies to other frameworks you must link them to application target (even if application target does not have dependency to that frameworks and never uses them).

I read through the README and here something I don't understand well:

> You will then have to drag them yourself into your project from the Carthage/Build folder.

Does it mean drag them into the `Linked Frameworks and Libraries` section or the top project hierarchy to create a workspace?

> If the embedded framework in your project has dependencies to other frameworks you must link them to application target

How to link to the application target? Could it be more specific ?

**Comment by mdiep** [comment]
> The octokit has an old version of ReactiveCocoa.
> 
> What should I do to keep both framework works together?

You'll need to use a version of ReactiveCocoa that's compatible with OctoKit. Carthage can't do anything to let you use RAC 4 and RAC 5—an application can't use both.

You could try opening a PR to OctoKit that switches it to https://github.com/ReactiveCocoa/ReactiveObjC or using https://github.com/mdiep/Tentacle instead of OctoKit.

> Does it mean drag them into the Linked Frameworks and Libraries section or the top project hierarchy to create a workspace?

`Linked Frameworks and Libraries`

> How to link to the application target? Could it be more specific ?

Add them to `Linked Frameworks and Libraries`
