### ISSUE TITLE
Question on bundling multiple frameworks as prebuilt framework

### ISSUE THREAD

**Issue by karthiksaligrama** [Carthage/Carthage#1546]
Suppose i have more than 1 framework being built from a single repo and all for a single platforms. Whats the best way to bundle them on Github releases?

Should i have to do something like A.framework.zip, B.framework.zip and so on. Or can i do one top level zip file containing all the framework?

**Comment by karthiksaligrama** [comment]
What if i have more than 2 say 10 frameworks?

**Comment by seivan** [comment]
The name was just an example and not a required pattern. Sorry if confused you.

**Comment by ikesyo** [comment]
@seivan Thanks for the right answer. Closing.
