### ISSUE TITLE
Failed to write framework file. The file couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by plivesey** [Carthage/Carthage#1547]
* `0.13.0`
* `Xcode 8.0`: `Build version 8A218a`
* Not using `--no-build`?
* Not using `--no-use-binaries`?
* Not using `--use-submodules`?

**Cartfile**
```
github "linkedin/RocketData"
```

**Carthage Output**
`$ carthage build --no-skip-current --verbose`
```
*** Building scheme "ConsistencyManager" in ConsistencyManager.xcodeproj
// Lot's of build output
Touch /Users/plivesey/Library/Developer/Xcode/DerivedData/ConsistencyManager-easboxjpxgkhdmduxqifplmmjtno/Build/Products/Release/ConsistencyManager.framework
    cd /Users/plivesey/Desktop/CarthageTest/Carthage/Checkouts/ConsistencyManager-iOS
    /usr/bin/touch -c /Users/plivesey/Library/Developer/Xcode/DerivedData/ConsistencyManager-easboxjpxgkhdmduxqifplmmjtno/Build/Products/Release/ConsistencyManager.framework

** BUILD SUCCEEDED **

Failed to write to /Users/plivesey/Desktop/CarthageTest/Carthage/Build/Mac/ConsistencyManager.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “ConsistencyManager.framework” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/plivesey/Library/Developer/Xcode/DerivedData/ConsistencyManager-easboxjpxgkhdmduxqifplmmjtno/Build/Products/Release-iphoneos/ConsistencyManager.framework, NSUnderlyingError=0x7f8ea27296a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

1st note: The command succeeds if you run with `--platform ios` option. I'm the producer of this library and people are confused why this is necessary and are wasting time trying to work this out: https://github.com/linkedin/RocketData/issues/42 https://github.com/linkedin/ConsistencyManager-iOS/issues/42

So, the problem seems to be that it's looking for the framework in the wrong folder. You can see in the last line of the build it puts the framework in `.../Products/Release/` but Carthage is looking in `.../Products/Release-iphoneos/`.

Note that when I run `$ xcodebuild build -workspace RocketData.xcworkspace -scheme RocketData` from my project it works.

Is there a way in which I could give Carthage a hint on where to find this framework so people can avoid the unnecessary `--platform` argument?

**Comment by plivesey** [comment]
Update: It looks like the iOS target builds fine. It's just the mac target which fails. So a couple of things:

1 - How can I fix the mac target?
2 - Perhaps Carthage shouldn't stop on failures, but continue to attempt to build other platforms?

**Comment by plivesey** [comment]
Fixed in my project: https://github.com/linkedin/ConsistencyManager-iOS/pull/43

Reason: Carthage would always attempt to find the built framework in a location based of the explicitly set SDKROOT=iphoneos.

So removed this from the project.

**Comment by ikesyo** [comment]
Looks like that's your project configuration issue. Closing.

And also it would be better to use newer versions (you are using 0.13.0 which is a bit old).
