### ISSUE TITLE
Option to build specific target only

### ISSUE THREAD

**Issue by tbaranes** [Carthage/Carthage#1552]
I search but didn't found any issue related, my apologies if I have failed my search 😬
Is there any way to tell to Carthage to build a specific target framework instead of build all? In my case, I'm using [Moya](https://github.com/Moya/Moya) which generates 3 frameworks:

- Moya
- Moya + RxSwift
- Moya + ReactiveSwift

I can understand that we can't specify it in the Cartfile, but it would be great if I can ask carthage to build only a specific Moya's framework target (`carthage build --target TargetNamed`). 
The main reason I'd like that is that is, for example, if one of the reactive framework compilation is failing (whatever the reason), I will still be able to build Moya without issue.

**Comment by ikesyo** [comment]
This is a duplicate of #1227.

**Comment by yo2bh** [comment]
Get the error "**Unrecognized arguments: --target**"

Would you please tell me is there any alternate way to Carthage 0.29 Or Need any extra setting to run only specific target? Thank you in advance.

**Comment by blender** [comment]
There is no target selection in Carthage. Carthage will build all shared schemes.
