### ISSUE TITLE
Checking git address

### ISSUE THREAD

**Issue by CodeEagle** [Carthage/Carthage#1555]
Carthage :v18.1
address with
`git "xx.xx.xx:xxx/xxx.git"`
private git will stall, no tips

**Comment by ikesyo** [comment]
Could you provide more details? We could do nothing without more information.

**Comment by mdiep** [comment]
What happens if you try to `git clone` the repo?

**Comment by CodeEagle** [comment]
The address is not right, and got no tips for it.
`git clone` also fail.
but it should break the action and throws error

**Comment by ikesyo** [comment]
I've examined this with the following Cartfile and exited with error:

```
git "xx.xx.xx:xxx/xxx.git"
```

```
*** No Cartfile.resolved found, updating dependencies
*** Cloning xxx
A shell task (/usr/bin/env git clone --bare --quiet xx.xx.xx:xxx/xxx.git /Users/ikesyo/Library/Caches/org.carthage.CarthageKit/dependencies/xxx) failed with exit code 128:
ssh: Could not resolve hostname xx.xx.xx: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Closing.
