### ISSUE TITLE
How can I know what library requires dependency library?

### ISSUE THREAD

**Issue by pocket7878** [Carthage/Carthage#1557]
* `carthage version`: 0.18.1
* `xcodebuild -version`: 
Xcode 8.1
Build version 8B62
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? NO

Sometimes(now..) some dependency library failed to build with carthage. 
And found it has newer release.
Then I want to report to update dependent version to XXX library.
But how can I know XXX library? Carthage.resolved only showed resolved library list. 
So I can't see any relationship between libraries.

**Comment by mdiep** [comment]
There's not currently a way to view which library brought in a given dependency with Carthage.

But you could look at the Cartfiles themselves to figure it out.
