### ISSUE TITLE
Upgrade to Swift 3

### ISSUE THREAD

**Issue by mdiep** [Carthage/Carthage#1558]
Xcode 8.2 won't include Swift 2, so now is the time to start upgrading to Swift 3.

**Comment by ikesyo** [comment]
Xcode 8.2 still includes Swift 2.3 (that is the final release supporting 2.3) but switching to Swift 3 now should be good anyway.

**Comment by ikesyo** [comment]
Dependencies status:

- [ ] ReactiveTask `"master"`
- [x] Commandant `~> 0.11.2`
- [ ] PrettyColors `"development"`
- [x] ReactiveSwift `"1.0.0-alpha.3"`
- [ ] Tentacle
- [x] Quick `~> 0.10`
- [x] Nimble `~> 5.0`

**Comment by ikesyo** [comment]
I'm planning have some pre-migration tasks for easier review, those makes diff volumes of an actual migration pull request fewer:

- Adopt API Design Guidelines (mainly functions, methods)
- Make enum cases lowercased
- Rename `URL` to `url`
- Drop `NS` prefixes using `typealias`
- `dynamictype` -> `typeof()`
- ...

**Comment by mdiep** [comment]
What's the best way for me to help with this?

It seems that Xcode 8.3 is just around the corner, so we should try to finish this up.

**Comment by ikesyo** [comment]
Thank you @mdiep. I'd like to submit an actual migration pull request once #1734 and #1735 are merged.

**Comment by ikesyo** [comment]
This should have been done (except for entirely following API Design Guidelines).

**Comment by mdiep** [comment]
💖
