### ISSUE TITLE
Is it possible to add a local dependency from within the same repository?

### ISSUE THREAD

**Issue by kypselia** [Carthage/Carthage#1560]
In my repository, I have a framework project that builds against several 3rd-party frameworks, and an app project that builds against that framework and some other 3rd-party frameworks. 

I would like to use Carthage to manage these dependencies, but it seems like I can only do that if I put my framework project in another repository than my app project's. 

Is there a way to express this internal dependency and have it resolved by Carthage?

**Comment by mdiep** [comment]
We don't intentionally support a workflow of using Carthage to build a framework within the same repository. (How would versions be resolved?)

The correct way to do this would be to use Carthage to build the 3rd party frameworks, but to include your internal framework's Xcode project in your app's Xcode project and build the internal framework that way.

**Comment by kypselia** [comment]
Yeah that's what I ended up doing. 

If at least we could say to Carthage "here, take what's in the Cartfile in that folder, add it to the main Cartfile, eliminate duplicates and resolve the whole" that would be enough to somewhat preserve encapsulation and make me happy :) 


Envoyé de mon iPhone
