### ISSUE TITLE
Can't build framework because of shared scheme.

### ISSUE THREAD

**Issue by hgonzalez94** [Carthage/Carthage#1573]
* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`No
* Are you using `--no-use-binaries`No
* Are you using `--use-submodules`No

**Cartfile**
```
github "hgonzalez94/IBTools"
```
**Carthage Output**
```
*** Fetching IBTools
*** Checking out IBTools at "1.0"
*** xcodebuild output can be found in /var/folders/dq/y6hkknc17xs7k8zkjr4mh3k40000gn/T/carthage-xcodebuild.D0X2wS.log
*** Skipped building IBTools due to the error:
Dependency "IBTools" has no shared framework schemes
```

I built a cocoa touch framework and have exposed the necessary headers, however when I try running this carthage build command, I keep getting this error. I exposed my only scheme as shared too on the repo...anyone have any suggestions?

**Comment by ikesyo** [comment]
Carthage uses the latest release (tag) if you don't specify a version constraint. And your shared scheme is not included in your `1.0` release, only in `master`: https://github.com/hgonzalez94/IBTools/compare/1.0...master.
