### ISSUE TITLE
Compile time with Carthage is exponentially longer than compiling with Xcode/xcodebuild

### ISSUE THREAD

**Issue by bensarz** [Carthage/Carthage#1581]
Our custom framework for our app is taking exponentially longer to build with Carthage than with xcodebuild or Xcode itself. Building with the UI/xcodebuild takes about 30 secs, building with Carthage takes about 8mins.

* `carthage version`: 0.18.1
* `xcodebuild -version`: 8.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "org/repo" "feature/my-branch"
```

**xcodebuild Output**
```
$ date; xcodebuild -workspace [redacted].xcworkspace -scheme [redacted] clean build; date
Tue 15 Nov 2016 08:22:58 EST
=== CLEAN TARGET [redacted] OF PROJECT [redacted] WITH CONFIGURATION Debug ===
...
** CLEAN SUCCEEDED **

=== BUILD TARGET [redacted] OF PROJECT [redacted] WITH CONFIGURATION Debug ===
...
** BUILD SUCCEEDED **

Tue 15 Nov 2016 08:23:34 EST
```

**Carthage Output**
```
$ date; carthage update --use-ssh; date
Tue 15 Nov 2016 09:11:14 EST
*** Fetching [redacted]
*** Checking out [redacted] at "6bc57896a8bf0d09d6e968c986d6cfd77a721382"
*** xcodebuild output can be found in /var/folders/mt/xyqwwnr92dgbg8987kt45prr0000gn/T/carthage-xcodebuild.si3bQr.log
*** Building scheme "[redacted]" in [redacted].xcworkspace
Tue 15 Nov 2016 09:19:55 EST
```

**Comment by mdiep** [comment]
`carthage update` does a lot more than just build. How does carthage fair if you run `carthage build`?

**Comment by bensarz** [comment]
Ok so after a deeper dive, it seems that the time is justified since our framework is being build for 4 architectures (arm, arm64, i386 and x86_64) and each takes about 1m30s to build.

**Comment by dcaunt** [comment]
@bensarz you may find the --platform flag useful
