### ISSUE TITLE
[Question/Feature] Specify build directories on a per dependency basis

### ISSUE THREAD

**Issue by adomanico** [Carthage/Carthage#1583]
* `carthage version`:  18.1
* `xcodebuild -version`: Xcode 8.1 Build version 8B62
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? No

Is there a way to specify a build directory for a dependency? 

Essentially what I'm trying to do is something like this:

github "ReactiveCocoa/ReactiveObjC" == 1.0.2 -o ./Build/iOS/Foo/
github "kean/Nuke" == 4.1.2 -o ./Build/iOS/Bar/
github "SnapKit/SnapKit" == 3.0.2 -o ./Build/iOS/Bar/

**Comment by mdiep** [comment]
No, there is not.

Why do you want to do that?

**Comment by adomanico** [comment]
Essentially what we want are different build output folders for different targets.

We want to have each target have its own Carthage folder for its own framework search paths

**Comment by adomanico** [comment]
I'm going to try going at this myself. 

Before I start, are there any philosophical reasons for not supporting this?

**Comment by adomanico** [comment]
Obviously not set on the syntax above but from a high level are there any objections?

**Comment by mdiep** [comment]
We don't yet have a way to specify per-dependency options.

That's something that's been planned for some point, but I'm not comfortable adding it right now. The codebase needs to be cleaned up and some bugs need to be fixed. I'm very hesitant to add additional complexity until we have the existing complexity under control.

**Comment by ldstreet** [comment]
I'm wondering if there is anything new in Carthage that might relate to this? I would love to do exactly what @adomanico was trying to do. I would really like to switch my teams project that has a plugin architecture from Cocoapods to Carthage, but this is currently a pain point.

**Comment by blender** [comment]
Nothing has changed. Build outputs are always in `Carthage/Build/<platform>`. I don't see a good reason to change this. If you want to shuffle things around just run a pre-build script.
