### ISSUE TITLE
How to update individual frameworks

### ISSUE THREAD

**Issue by kevinmlong** [Carthage/Carthage#1587]
As referenced here: https://github.com/Carthage/Carthage#upgrading-frameworks

How does one know what to specify if we only want to update individual frameworks. Is it the name of the framework that results from the build - e.g. TestFramework.framework would be specified as TestFramework?

**Comment by ikesyo** [comment]
The input should be the dependency name, not the built framework name. So if you have the following Cartfile, you can do like this: `carthage update DEF`

```
# "DEF" is the dependency name.
github "ABC/DEF"
```

**Comment by kevinmlong** [comment]
Thanks! What about if you are using the path to include a private repository?

**Comment by mdiep** [comment]
It will then be the last path component.

**Comment by kevinmlong** [comment]
So - if I have the following in the Cartfile:

git "ssh://git@gitdserver.company.com:port/project/repo.git" "develop"

I tried using `carthage update repo.git` and it returned `No entry found for dependency repo.git in Cartfile.

**Comment by kevinmlong** [comment]
Disregard - by specifying repo (sans .git) it worked great. Thanks!
