### ISSUE TITLE
Error while updating Carthage

### ISSUE THREAD

**Issue by itsaark** [Carthage/Carthage#1589]
This is the first time I'm using Carthage. So please exuse me if I sound silly. I'm trying to use Watson iOS-SDK. When I'm trying to update the Cartfile, I get the following error **WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "-" is not installed**

I even tried to set `code signing identiy` to `Don't Code Sign` in my xcode project. But it didn't work either.

Can someone please help me out?

**Comment by mdiep** [comment]
Please check your carthage version. (There's a reason that's part of the issue template!)

You must have a very old version. Current is 0.18.1.

**Comment by itsaark** [comment]
I have just update to the current version, but unfortunately, I'm getting the same error.

**Comment by mdiep** [comment]
What's the output of `carthage version`?

**Comment by itsaark** [comment]
Damn it's `0.10.0` 

But I just updated it like 2 times. And the second time I got this output `Already up-to-date.` `Error: carthage 0.18.1 already installed`

**Comment by mdiep** [comment]
You probably installed via two different methods (both homebrew and the `.pkg` installer) and you're picking up the wrong one.

**Comment by itsaark** [comment]
Thanks so much for figuring this out @mdiep 
It works now!
