### ISSUE TITLE
Binary releases ignore --platform flag

### ISSUE THREAD

**Issue by cuyogomez** [Carthage/Carthage#1596]
* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.1
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
github "SwiftyJSON/SwiftyJSON"
github "DenHeadless/DTTableViewManager" ~> 5.1.0
github "Swinject/Swinject" "2.0.0-beta.2"

**Carthage Output**
All builds successful

I'm trying to update all the dependencies in the Cartfile file, but I would like to update only for iOS platform, since if it's compile for all it takes more time. I'm running the command:

`carthage update --platform iOS`

But, it's still generating all the build for all the platforms (iOS macOS tvOS watchOS).

Have this command changed or is it not working anymore?

Thanks in advance.

**Comment by mdiep** [comment]
Carthage isn't building all platforms. It's downloading the binaries, which contain all platforms, and copying _all_ of them to the build directory.

Binary releases probably should respect this flag, but it's not actually building the projects for those platforms, so it shouldn't slow down your builds.

**Comment by cuyogomez** [comment]
So, should I add the flag `--no-use-binaries` to remove all all other platforms?

**Comment by mdiep** [comment]
Yes

**Comment by ikesyo** [comment]
I'm not going to address this. Closing.
