### ISSUE TITLE
V0.18 Archive upload failed : Invalid Signature .Code project is not signed at all ...

### ISSUE THREAD

**Issue by yunlai** [Carthage/Carthage#1603]
* `carthage version`: 0.18.1
* `xcodebuild -version`: 8.1
* Are you using `--no-build`?
* Are you using `--no-use-binaries`?
* Are you using `--use-submodules`?

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```

Everything works on simulator, but when submit to app store,i got this error:

"Archive upload failed : ERROR : ITMS-90035L Invalid Signature .Code project is not signed at all ..."

I have already add run script "/usr/local/bin/carthage copy-frameworks" in build phases

**Comment by yunlai** [comment]
If i delete copy-frameworks script ,this error will dismiss,so i'm pretty sure carthage cause the sign error.
I found CODE_SIGNING_ALLOWED BUILT_PRODUCTS_DIR in CopyFrameworks.swift,should i set CODE_SIGNING_ALLOWED BUILT_PRODUCTS_DIR somewhere?

**Comment by ikesyo** [comment]
We are not sure what is happening here. What you omitted from the original erroro message will describe the root cause as seen in stackoverflow questions like this: http://stackoverflow.com/questions/29788601/error-itms-90035-xcode

**Comment by yunlai** [comment]
@ikesyo thanks for your reply, it's not carthage's fault. The reason is a project's build setting was incorrect, carthage got wrong environment variable

**Comment by RemyDCF** [comment]
@yunlai What did you modified in your project's build setting ?
