### ISSUE TITLE
Carthage hanging on cloning/fetching

### ISSUE THREAD

**Issue by adrianodiasx93** [Carthage/Carthage#1606]
It hangs on "facebook-ios-sdk"  which is cloned because of facebook-sdk-swift carthage's file. It takes hours and then starts fetching Bolts-ObjC (cloned because of facebook-ios-sdk) multiple times.

* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.1 Build version 8B62
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Using `carthage update --platform iOS`

I also tried using --verbose, but it gave me no extra information.

**Cartfile**
```
github "SwiftyJSON/SwiftyJSON"
github "facebook/facebook-sdk-swift"
github "Alamofire/Alamofire" == 4.0.1
github "Alamofire/AlamofireNetworkActivityIndicator"
github "Alamofire/AlamofireImage"
github "SwiftKickMobile/SwiftMessages"
github "SnapKit/SnapKit" ~> 3.0
github "ninjaprox/NVActivityIndicatorView"
github "teambition/TBEmptyDataSet" ~> 2.1
github "realm/realm-cocoa"
github "optonaut/ActiveLabel.swift"
github "Ramotion/animated-tab-bar"
```
I also tried specifying the version of facebook-sdk-swift. No change.

Any suggestions?

**Comment by mdiep** [comment]
If you specify version requirements for your dependencies, that should help.

There's an issue where the dependency resolver struggles to find compatible versions of all the dependencies—so it tries older and older versions. Specifying version requirements prunes the search field.

This is something that Carthage _should_ do better, but it requires a lot of work to get there.

**Comment by adrianodiasx93** [comment]
Some (several) cleans and specifying the version for each dependency did the trick.

Hope you guys eventually get there. Thanks for the assistance and great work!

**Comment by adrianodiasx93** [comment]
@mdiep have you seen some case where the checked version of the dependency is older than the one specified in the cartfile?

Older versions are often checked when I have to update some dependencies. For instance, this last weekend I specified `~> 4.0` to Alamofire, but it checked`2.0.0-beta.3` out. Similar situation happened to realm-cocoa.

**Comment by mdiep** [comment]
Yes, that's a separate issue that occurs with non-semantic-version tags like `2.0.0-beta.3`

**Comment by adrianodiasx93** [comment]
Is there a way to help avoiding it?

**Comment by mdiep** [comment]
You can manually adjust your `Cartfile.resolved` so that `carthage bootstrap` works correctly.
