### ISSUE TITLE
'No such module'

### ISSUE THREAD

**Issue by beno** [Carthage/Carthage#1607]
* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.1 Build version 8B62
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "apollostack/apollo-ios"
```

Everything seems to build just fine, I drag the framework in place, but all I ever get is `No such module 'Apollo'`. I have tried the Framework Search Path and some other Build Phase trick I found here and there, but nothing helps and not even a hint to what the issue might be. The same seems to be the case for other frameworks I tried. I really want to like/use Carthage, but this is making it really hard.

**Comment by ikesyo** [comment]
> `No such module 'Apollo'`

That means that the framework does not copied into your app bundle. So it looks like you missed copying the framework by using `carthage copy-frameworks` build phase noted here: https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

**Comment by beno** [comment]
Thanks for your answer, but I had already tried all that, perhaps I should have been more specific. Everything looks like it's installed correctly, but it doesn't work at all.

**Comment by beno** [comment]
To clarify: this is on a brand new Mac, with everything in pristine condition and up to date, a brand new Xcode project and an installation by the book (as far as I can tell). Yet it completely fails without any suggestion as to why. I don't think this issue should be closed. Anyway, I'm off to Cocoapods.

**Comment by ikesyo** [comment]
I'm sorry but we are not sure what's happenig with the information. If you provide a sample project that reproduce the issue we can investigate it deeper.

**Comment by beno** [comment]
As it turned out I placed my Cartfile and builds next to my Xcode project instead of inside it. My mistake (although I actually thought this kind of flexibility was one of Carthage's USPs), but maybe at some point either Carthage or Xcode should warn that this is not allowed? Anyway, problem fixed, onward!
