### ISSUE TITLE
Failed to check out repository into ... : No object named "swift-3.0" exists

### ISSUE THREAD

**Issue by nikolasburk** [Carthage/Carthage#1610]
* `carthage version`: 0.16
* `xcodebuild -version`: Xcode 8.1 Build version 8B62
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? tried with and without
* Are you using `--use-submodules`? no

**Cartfile**
```
github "ReSwift/ReSwift"
```

**Carthage Output**
```
*** Fetching Quick
*** Fetching Nimble
Failed to check out repository into /Users/nburk/Library/Caches/org.carthage.CarthageKit/dependencies/Quick: No object named "swift-3.0" exists
```

I am trying to build the `ReSwift-Router` project from [here](https://github.com/ReSwift/ReSwift-Router) but `carthage update` fails with the above info. I tried to delete cached data using `mv ~/Library/Caches/org.carthage.CarthageKit/dependencies/ReSwift-Router  ~/.Trash` but that didn't work. Any ideas how to fix this?

**Comment by ikesyo** [comment]
That is the problem of `Cartfile.private` in `ReSwift-Router`. There is no `swift-3.0` branch in `Quick/Quick` listed in the file. You need to update the file.

**Comment by nikolasburk** [comment]
it works, thanks for the help!!
