### ISSUE TITLE
Carthage Local Cache Manipulation

### ISSUE THREAD

**Issue by wuaschtikus** [Carthage/Carthage#1614]
Hi,

I am forced to publish my artefacts on a Artifactory instance. I wonder if there is a way to create something similar to GitHub Releases to provide binaries.

I already read of some issues where some users want to use e.g. Gitlab Releases with Carthage Prebuilt Frameworks and I would highly appreciate such a feature. Since not all users are able to use extern code sources - it is a bad idea to limit this feature only for github. 

I also took a look at the Carthage Cache - but unfortunately it uses Amazons Cloud and I am forced to keep artefacts local. It is because I am working in a high security environment.

So targeting Artifactory to store Frameworks requires me to write some logic myself. 

My Question: Is there a way to put Prebuilt Frameworks in the `~/Library/Caches/org.carthage.CarthageKit` manually and force Carthage to use them? I assume Carthage would use them automatically?

Cheers.

**Comment by mdiep** [comment]
There's not, but you could write something. If there's a `carthage-foo` executable in your path, then `carthage foo` will work automatically.

I'm not sure whether placing binaries in there would cause them to be used. I don't think it would, but I haven't tried.

**Comment by wuaschtikus** [comment]
Ok thank you for the response. I think i will write a minimal *.swift Script to handle Publish und Deployment of artefacts for Artifactory.

I find it quite odd that Carthage only works with Github Releases. Carthage has a great potential - since it does not mess up your build settings like Cocoapods... It would be awesome if it would support more than that. What so you say? ;)

**Comment by mdiep** [comment]
GitHub Releases is a programmatic choice—that's where most of the code that people use lives.

#1308 discussed an additional JSON-specified version, but no one has implemented it.
