### ISSUE TITLE
How to specify a particular project to build from a repo

### ISSUE THREAD

**Issue by CoderXpert** [Carthage/Carthage#1618]
We have a repo which includes two frameworks and demo apps. If we do `Carthage update` it will build only one framework. Is there a way I can specify XCode project in the repo to be build.
I think we should be able to pass an optional argument to `Carthage update ` command which specifies the project name one intended to build.

**Comment by jpsim** [comment]
If you make an Xcode workspace containing both projects in the root of your repo, Carthage will build both frameworks.

**Comment by CoderXpert** [comment]
We want them separate projects as they do different things. If we have two workspaces in one repo will Carthage build both?

**Comment by jpsim** [comment]
I don't think so. You can have separate projects while also having a workspace with links to both those projects....

**Comment by ikesyo** [comment]
We already should support multi projects without workspaces. Is the scheme is correctly shared, or is it a dynamic framework? If that is a static framework scheme, that will be skipped.

**Comment by CoderXpert** [comment]
We have dynamic frameworks. Our repo structure is like this
1. MainFramework.xcodeproj
2. SecondaryFramework.workspace (include main framework as dependency)
3. SecondaryFramrwork.xcodeproj
