### ISSUE TITLE
Code signing fails during archive export

### ISSUE THREAD

**Issue by nbrice88** [Carthage/Carthage#1619]
carthage version:
0.18.1
xcodebuild -version:
Xcode 8.1
Build version 8B62
Are you using --no-build?
No
Are you using --no-use-binaries?
No
Are you using --use-submodules?
No

After running: "carthage update --platform iOS" I'm unable to export an archive for distribution, with the Xcode export tool fails with the error "An error occurred during export. Codesign failed".

Running on Simulator works fine (no codesigning needed) as does running directly on a device. The failure occurs on the first framework when attempting to codesign. In this case Alamofire.

I'm running "/usr/local/bin/carthage copy-frameworks" as a build phase script as well as have User-Defined build settings CODE_SIGNING_ALLOWED = YES and CODE_SIGNING_REQUIRED = YES. Setting the build settings = YES was required to build on device.

Critical log output is: ```2016-11-30 21:19:42 +0000 [MT] Presenting: Error Domain=IDEFoundationErrorDomain Code=1 "Codesign failed" UserInfo={NSLocalizedDescription=Codesign failed}```

End of IDECodeSignResolver.log (partially sanitized): ```2016-11-30 21:19:27 +0000  Filtering based on profile type: universal
2016-11-30 21:19:27 +0000  Accepting: <DTDKProvisioningProfile 0x7fd349fd6540: UUID: *UUID1*, name: *profile 1 name*, team: ****, platform: iOS>
2016-11-30 21:19:27 +0000  Rejecting: <DTDKProvisioningProfile 0x7fd2eaa12210: UUID: *UUID2*, name: XC iOS Ad Hoc: *App ID*, team: ****, platform: iOS> (Profile type universal doesn't allow profile: profile type requires an empty list of devices)
2016-11-30 21:19:27 +0000  selecting top entry in sorted array: (
    "<DTDKProvisioningProfile 0x7fd349fd6540: UUID: *UUID1*, name: *profile 1 name*, team: ****, platform: iOS>"
)```

I've also tried disabling codesigning build option entirely in my build settings. Exporting from command-line also fails in the same way.

Sorry if this has been answered elsewhere, but I haven't been able to figure out a working solution. If you need any additional information please let me know.

**Comment by mdiep** [comment]
You shouldn't need to code sign the frameworks individually—they get signed as part of the app.

**Comment by nbrice88** [comment]
Apologies, the error was on my end. 

I was importing an internally developed framework - that used carthage for its own dependencies - which contained a "copy frameworks" build phase in the iOS target to run the test suite. 

From what I can tell this caused the linked frameworks to be bundled in twice with the top-level app which caused xcodebuild choke when it tried to codesign.

Removing the "copy frameworks" build phase fixed the issue and my app is now codesigning properly.

Cheers and closing!
