### ISSUE TITLE
[Feature Request]  Option to pass additional Xcode build flags?

### ISSUE THREAD

**Issue by larryonoff** [Carthage/Carthage#1622]
I'm curious if maintainers accept this feature, because it's possible that I'll be able start implementing this feature.

**Comment by mdiep** [comment]
Could you detail more specifics about what you're thinking?

**Comment by larryonoff** [comment]
simply saying I need to pass with ENABLE_TESTABILITY flag set to YES for Release configuration in certain case.

**Comment by ikesyo** [comment]
Today's workaround may be use the `XCODE_XCCONFIG_FILE` environment variable noted in `man xcodebuild`.

```bash
XCODE_XCCONFIG_FILE="/path/to/xcconfig_file" carthage build
```

**Comment by ikesyo** [comment]
Closing this for now in favor of `XCODE_XCCONFIG_FILE`.
