### ISSUE TITLE
Anti-tweak，not work

### ISSUE THREAD

**Issue by skcwiiur** [Carthage/Carthage#1624]
* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.1  Build version 8B62

**Cartfile**
```
github "danielgindi/Charts" ~> 3.0.0
```

If i want to Anti-tweak, do with this:
Build Settings->Other Linker Flags
```
-Wl,-sectcreate,__RESTRICT,__restrict,/dev/null
```

The project will not work.
Is there a way out?

**Comment by ikesyo** [comment]
I'm not sure what you are saying:

- What is `Anti-tweak`?
- What does `The project will not work.` mean?
- Is this really related to Carthage? Does that work well if you integrate the project's Xcode project directly?

**Comment by skcwiiur** [comment]
Console log:
dyld: warning, LC_RPATH @executable_path/Frameworks in /var/containers/Bundle/Application/F943E506-2D55-4798-BBAF-8AC19BC7145F/boss.app/boss being ignored in restricted program because of @executable_path
dyld: Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: /var/containers/Bundle/Application/F943E506-2D55-4798-BBAF-8AC19BC7145F/boss.app/boss
  Reason: image not found

Reference link:
http://www.jianshu.com/p/46d2aa81eff4
http://bbs.iosre.com/t/tweak-app-app-tweak/438

**Comment by ikesyo** [comment]
From the error message, it looks like you are missing `copy-frameworks` step noted in README: https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos.

**Comment by skcwiiur** [comment]
Hi:
Other Linker Flags without the code:
 `-Wl,-sectcreate,__RESTRICT,__restrict,/dev/null`
or  replace with
`-Wl,-sectcreate,__RRSTRICT,__restrict,/dev/null`
The project works well.

The real reson is that dyld loader  ignore the Dynamic library becauseof __RESTRICT section exist.

dyld code source：
https://opensource.apple.com/source/dyld/dyld-210.2.3/src/dyld.cpp
and search this in the code source:
`dyld::log("dyld: DYLD_ environment variables being ignored because ")`

Thank you for you reading

**Comment by ikesyo** [comment]
A similar issue: https://github.com/realm/realm-cocoa/issues/3026

**Comment by ikesyo** [comment]
Anyway, I think that should not be Carthage specific issue.
