### ISSUE TITLE
brew install should warn if it notices CarthageKit.framework

### ISSUE THREAD

**Issue by sleekweasel** [Carthage/Carthage#1628]
Rather than a comment in the README, it would be more helpful if Carthage's brew install printed a warning if it detected the CarthageKit.framework directory:

```
WARNING: Recommend you delete conflicting (obsolete)  /Library/Frameworks/CarthageKit.framework/
```

* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.1 Build version 8B62
* Are you using `--no-build`? n/a
* Are you using `--no-use-binaries`? n/a
* Are you using `--use-submodules`? n/a

**Cartfile**
```
n/a
```

**Carthage Output**
```
n/a
```

**Comment by ikesyo** [comment]
This can be closed now by #2055 and #2059.
