### ISSUE TITLE
Selecting deployment target

### ISSUE THREAD

**Issue by GreatApe** [Carthage/Carthage#1629]
I need to have a deployment target of 9.3, but Carthage seems to build everything to 10.1. Is there a way to control this?

Carthage logs that it's e.g. "building scheme Dollar in Dollar.xcodeproj" but the only scheme I can find in the dollar project is for macOS, so I'm not even sure how to do this manually.

http://stackoverflow.com/questions/40952678/select-deployment-target-for-carthage-dependency

**Comment by mdiep** [comment]
Maybe dollar uses a universal target?

Carthage should be respecting the settings of the project.

**Comment by GreatApe** [comment]
I didn't know that was possible!

OK, so then the problem could be that Carthage doesn't manage to change the deployment target of the "universal target". I did it manually and it seems to work. There are other issues with Dollar in Carthage.

Anyway, thank you for the information that Carthage respects the project deployment target, that wasn't clear to me.
