### ISSUE TITLE
Dependency resolution + strange build behavior with Moya

### ISSUE THREAD

**Issue by AndrewSB** [Carthage/Carthage#1637]
Hey Carthage team! I'm a maintainer of [Moya](https://github.com/Moya/Moya), and we had https://github.com/Moya/Moya/issues/835 reported about some strange behavior with Carthage.

* `carthage version`: 0.18.1 
* `xcodebuild -version`: unsure, but Xcode: 8.0
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "Moya/Moya"
```

**Carthage Output**
```
$ carthage update --platform iOS
*** Fetching Moya
*** Fetching RxSwift
*** Fetching Alamofire
*** Fetching Result
*** Checking out Alamofire at "3.5.1"
*** Checking out Result at "2.1.3"
*** Checking out ReactiveCocoa at "v4.2.2"
*** Checking out RxSwift at "2.6.1"
*** Checking out Moya at "7.0.4"
*** xcodebuild output can be found in /var/folders/1n/81b947wj2_12d0s_xnps_ptw0000gn/T/carthage-xcodebuild.hgN728.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
A shell task (/usr/bin/xcrun xcodebuild -project /Users/nah/Data/Projects/My/Carthage/Checkouts/Moya/Demo/Pods/Pods.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'Pods.xcodeproj' from folder '/Users/nah/Data/Projects/My/Carthage/Checkouts/Moya/Demo/Pods'.
Reason: Project /Users/nah/Data/Projects/My/Carthage/Checkouts/Moya/Demo/Pods/Pods.xcodeproj cannot be opened because it is missing its project.pbxproj file.
```

If you look at https://github.com/Moya/Moya/issues/835, you'll see two things that are strange.

1. In https://github.com/Moya/Moya/issues/835#issue-194737589, @nahung89's `Cartfile` is:

```
github "Alamofire/Alamofire"
github "SwiftyJSON/SwiftyJSON"
github "realm/realm-cocoa"
github "Hearst-DD/ObjectMapper"
github "Moya/Moya"
```

Cartfile.resolved:
```
github "Alamofire/Alamofire" "4.2.0"
github "Moya/Moya" "3.0.0"
github "Hearst-DD/ObjectMapper" "2.2.1"
github "SwiftyJSON/SwiftyJSON" "3.1.3"
github "realm/realm-cocoa" "v2.1.1"
```

   strangely, `carthage` chooses to resolve Moya at a version from last October (https://github.com/Moya/Moya/releases/tag/3.0.0). It doesn't look as if any of his sub-dependencies depend on Moya, so I'm not sure why `carthage` would resolve such an old version.

2. (not repro-able by me): @nahung89's machine is having building `Moya@8.0.0-beta5` inconsistently. His output in https://github.com/Moya/Moya/issues/835#issuecomment-266340701 crashes, and looks different from other maintainer's output in https://github.com/Moya/Moya/issues/835#issuecomment-266413883, for example. @nahung89's machine is parsing our `Demo/Pods.xcodeproj`, which shouldn't be happening (and isn't on my machine, or machines of other Moya maintainers that commented on the issue).

His output was 

> *** xcodebuild output can be found in /var/folders/1n/81b947wj2_12d0s_xnps_ptw0000gn/T/carthage-xcodebuild.MApVEr.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
A shell task (/usr/bin/xcrun xcodebuild -project /Users/nah/Data/Projects/My/Carthage/Checkouts/Moya/Demo/Pods/Pods.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'Pods.xcodeproj' from folder '/Users/nah/Data/Projects/My/Carthage/Checkouts/Moya/Demo/Pods'.
Reason: Project /Users/nah/Data/Projects/My/Carthage/Checkouts/Moya/Demo/Pods/Pods.xcodeproj cannot be opened because it is missing its project.pbxproj file.

Here are the schemes in `Demo/Pods.xcodeproj`:

<img width="725" alt="screen shot 2016-12-12 at 9 51 21 am" src="https://cloud.githubusercontent.com/assets/3814772/21110074/aa37b42a-c050-11e6-9bcc-96b5db298899.png">

**Comment by mdiep** [comment]
Having looked over the thread and built Moya myself, the issue appears to have been with the clone of  the repo in `~/Library/Caches/org.carthage.CarthageKit`. For some reason, the fetch doesn't appear to have worked.

This explains both behaviors:

1. When not given a version number, Carthage picked what it thought was the latest—3.0.

2. When given a version number for which it had no compatible versions, it picked a non-semantic version tag. (This is an existing bug.)

This is confirmed by the fact that deleting the cache fixed the issue for that user.

Sorry for the confusion. It's unclear to me why this would happen. If anyone reports it again, please ask them to zip up the copy of the relevant repo's repository from `~/Library/Caches/org.carthage.CarthageKit`. That should be helpful in reproducing and fixing the error.

**Comment by AndrewSB** [comment]
I see, thank you for explaining the problem Matt!

He seems to have been able to resolve the issue, so I'll close this.

If I see what I think to be a fetching problem again, I'll ask them to zip
their cache folder and send it your way 🙃
