### ISSUE TITLE
--fast-build option

### ISSUE THREAD

**Issue by drekka** [Carthage/Carthage#1642]
I'd like to request a new option on `update` and `build`.

I would like a `--fast-build` option which can be used during development, most especially when dealing with large dependency trees with few updates. Here's a simplified example

    Alchemic (v2.2.11)
      -> StoryTeller (v1.8.5)
           -> PEGKit (develop:c073643cce704f781c3af63a97d9a6daaeeea045)

The scenario is that Alchemic has updated to v2.2.12, yet StoryTeller and PEGKit are still the same. 

At the start of the build, carthage would store the versions and hashes of the versions from Cartfile.resolved. 

After checkout, the versions would be checked and only the changed ones (Alchemic v2.2.12) would be re-built. The others would assume to have not changed and not be rebuilt.

**Comment by mdiep** [comment]
There's work underway for this. #1222 #1489

**Comment by drekka** [comment]
Brilliant. Thanks
