### ISSUE TITLE
Carthage commands failure behaviour

### ISSUE THREAD

**Issue by netbe** [Carthage/Carthage#1647]
* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

Hi,

I am new to Carthage (couple of months on a client's project) and one of the difficulty I found in using it is the way it behaves with command arguments. For example when checking out a dependency that does not exist `carthage checkout GCDWebServers` (typo **GCDWebServers** instead of **GCDWebServer**) , carthage will default to checkout all my dependencies, instead of returning an error saying dependency not found.

* Actual behavior:
``` 
carthage checkout GCDWebServers
*** Checking out Alamofire at "3.5.1"
*** Checking out GCDKit at "1.3.0"
```

* Expected behavior:
```
carthage checkout GCDWebServers
***  Could not found GCDWebServers in your Cartfile
```

The actual behavior can lead to wasted time especially when you don't know that checking or fetching other dependencies is not needed and your cartfile is big.

Let me know if that's something that could be changed or it is intended behavior, I would be happy to help in that matter.

**Comment by mdiep** [comment]
There's an open issue for this: #1517. PRs welcome!
