### ISSUE TITLE
Odd cloning issue

### ISSUE THREAD

**Issue by criticalmatter** [Carthage/Carthage#1648]
* `carthage version`:  0.18.1-140-g4593455
* `xcodebuild -version`: 8.1 (8B62)
* Are you using `--no-build`? Yes
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? Yes

**Cartfile**
```
# Realm
github "realm/realm-cocoa" ~> 2.0 
```

**Carthage Output**
```
$ carthage update --no-build --use-submodules --no-use-binaries
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "v2.1.1"
```

When cloning Realm 2.1.1 via Carthage, the following files never appear in Checkouts:
```
Realm/RLMSyncErrorResponseModel.h
Realm/RLMSyncErrorResponseModel.m
```

I've replicated this on multiple systems using both Xcode 8.1 and Xcode 8.2, using Carthage 0.18.1 installed via .pkg and the current master branch built from source.  When cloning realm via a standard terminal command:
```
git clone https://github.com/realm/realm-cocoa.git
```

both files are cloned as expected.  My working hypothesis is that there's something about the file name that's causing issues somewhere.  "ErrorResponse" seems like a convenient coincidence!  I poked around the Carthage source and dependency sources using grep however and didn't see anything that stood out however.  Bizarre?

@jpsim

**Comment by mdiep** [comment]
`RLMSyncErrorResponseModel` doesn't exist in version 2.1.1 of realm-cocoa.

**Comment by ikesyo** [comment]
You are cheecking out `v2.1.1` tag and the files does not exist in the tag. Those are only in current `master` branch. That is the reason. Closing.

**Comment by criticalmatter** [comment]
Doh!  Long day...  My apologies.
