### ISSUE TITLE
Improvement. Avoid always coping Carthage dependencies on each build

### ISSUE THREAD

**Issue by RomanVolkov** [Carthage/Carthage#1649]
I want to suggest script that  prevents copy-framework step for each build.
Instead, after full rebuild it create files (like a flag that dependencies copied) with amount of dependencies

FILE="${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/Carthage-Installation-Flag"
if [ -f "$FILE" ]; then
    while read -r line
    do
        if [ "$line" != "$SCRIPT_INPUT_FILE_COUNT" ]; then
            echo "warning: count of Carthage files has changed. Make Clean & Build"
        fi
    done < "$FILE"
    exit 0
fi
touch "$FILE"
echo -e $SCRIPT_INPUT_FILE_COUNT >> "$FILE"

/usr/local/bin/carthage copy-frameworks

When you'll add new dependency it warns you that you have to Clean & Build again. In other cases it copies all libs only once (and don't on each incremental build).

**Comment by mdiep** [comment]
This is discussed in #1635.
