### ISSUE TITLE
platforms parameter for "carthage update"

### ISSUE THREAD

**Issue by ivan-konov** [Carthage/Carthage#1652]
Hey guys have you thought of adding the option to specify which platforms should be build after an update. I think it will be really useful since I (and I suppose many others) have the issue of waiting for the building of ALL platforms after an update where they just need to build for iOS for example.

Thanks in advance!

**Comment by ikesyo** [comment]
We already have: `carthage update -- platform ios` I recommend you to see the outputs of `carthage help update` or other commands.

**Comment by ivan-konov** [comment]
Is this something new? Thanks!

**Comment by mdiep** [comment]
Nope. This is a very old option. ☺️

**Comment by ivan-konov** [comment]
I should have executed a very poor research on that. Better ask than sorry :) Thanks again guys!
