### ISSUE TITLE
Carthage hangs when downloading

### ISSUE THREAD

**Issue by bsarrazin** [Carthage/Carthage#1657]
* `0.18.1`: 
* `Build version 8C1002`: 
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "[REDACTED]/ios-dependencies"
```

**Carthage Output**
```
$ carthage update --platform iOS --verbose
*** Fetching ios-dependencies
*** Downloading ios-dependencies.framework binary at "0.0.1"
```

Running the carthage command just hangs during the download of the binary but the file is actually downloaded in full:

![](https://cloud.githubusercontent.com/assets/1077441/21461224/996d9058-c91d-11e6-8999-cd47905292c9.png)

Our ios-dependencies is a simple repo with no iOS code. It just holds our dependencies with a few fastlane scripts. Frameworks like Fabric and Crashlytics are added to the binary for easy downloading.

The content of the repo:

![](https://cloud.githubusercontent.com/assets/1077441/21461189/4e3369d2-c91d-11e6-90b8-eab6103ca9f8.png)

Here's the GitHub release
![](https://cloud.githubusercontent.com/assets/1077441/21461176/31350f2a-c91d-11e6-8326-1047a2914358.png)

Why is Carthage hanging? Is it checking for anything like iOS code within the repo?

**Comment by mdiep** [comment]
The only thing it'll look for within the repo is the tags for versions. It looks like it's already resolved those, so I'm not sure where or why it'd be hanging. 😕

**Comment by Tchelow** [comment]
The Same thing is happening to me, but I have `--no-use-binaries` on it.

**Comment by bensarz** [comment]
@mdiep I've created a reproducible example.
The dependencies: https://github.com/bensarz/ios-dependencies
The project: https://github.com/bensarz/carthage-playground

1. Clone the project:
    ```zsh
    $ git clone git@github.com:bensarz/carthage-playground
    ```
1. Bootstrap the dependencies:
    ```zsh
    $ carthage bootstrap
    ```

Result: carthage hangs when attempting to download the file
![2017-01-03 at 2 06 pm](https://cloud.githubusercontent.com/assets/1077441/21619503/f5797242-d1bd-11e6-9770-fb92752f7f48.png)

**Comment by mdiep** [comment]
Thanks! That's super helpful. It does hang on my machine. I'll try to take a deeper look in the next week.

**Comment by ikesyo** [comment]
This is really a real word example of #346:

```
$ unzip ios-dependencies.framework.zip 
Archive:  ios-dependencies.framework.zip
   creating: Carthage/
   creating: Carthage/Build/
   creating: Carthage/Build/iOS/
   creating: Carthage/Build/iOS/Crashlytics.framework/
  inflating: Carthage/Build/iOS/Crashlytics.framework/.DS_Store  
  inflating: Carthage/Build/iOS/Crashlytics.framework/Crashlytics  
   creating: Carthage/Build/iOS/Crashlytics.framework/Headers/
  inflating: Carthage/Build/iOS/Crashlytics.framework/Headers/ANSCompatibility.h  
  inflating: Carthage/Build/iOS/Crashlytics.framework/Headers/Answers.h  
  inflating: Carthage/Build/iOS/Crashlytics.framework/Headers/CLSAttributes.h  
  inflating: Carthage/Build/iOS/Crashlytics.framework/Headers/CLSLogging.h  
  inflating: Carthage/Build/iOS/Crashlytics.framework/Headers/CLSReport.h  
  inflating: Carthage/Build/iOS/Crashlytics.framework/Headers/CLSStackFrame.h  
  inflating: Carthage/Build/iOS/Crashlytics.framework/Headers/Crashlytics.h  
  inflating: Carthage/Build/iOS/Crashlytics.framework/Info.plist  
   creating: Carthage/Build/iOS/Crashlytics.framework/Modules/
  inflating: Carthage/Build/iOS/Crashlytics.framework/Modules/module.modulemap  
  inflating: Carthage/Build/iOS/Crashlytics.framework/run  
  inflating: Carthage/Build/iOS/Crashlytics.framework/submit  
  inflating: Carthage/Build/iOS/Crashlytics.framework/uploadDSYM  
   creating: Carthage/Build/iOS/Fabric.framework/
  inflating: Carthage/Build/iOS/Fabric.framework/.DS_Store  
  inflating: Carthage/Build/iOS/Fabric.framework/Fabric  
   creating: Carthage/Build/iOS/Fabric.framework/Headers/
  inflating: Carthage/Build/iOS/Fabric.framework/Headers/FABAttributes.h  
  inflating: Carthage/Build/iOS/Fabric.framework/Headers/Fabric.h  
  inflating: Carthage/Build/iOS/Fabric.framework/Info.plist  
   creating: Carthage/Build/iOS/Fabric.framework/Modules/
  inflating: Carthage/Build/iOS/Fabric.framework/Modules/module.modulemap  
  inflating: Carthage/Build/iOS/Fabric.framework/run  
  inflating: Carthage/Build/iOS/Fabric.framework/uploadDSYM  
replace Carthage/Build/iOS/Crashlytics.framework/.DS_Store? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
```

**Comment by bensarz** [comment]
@ikesyo awesome! thanks for pinpointing the problem!
I have a question though, how can the zip file contain 4 different entries for the same file/folder?
If you take a look at the fastlane script, there really isn't anything special, it is simply zipping the archive that is on disk.

**Comment by bensarz** [comment]
@ikesyo @mdiep 
After fixing my archive, I get to the point where Carthage fails because of "Invalid architecture":

```zsh
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 58          |
| 💥   | carthage                            | 23          |
+------+-------------------------------------+-------------+

[10:45:56]: fastlane finished with errors

[!] Exit status of command 'carthage update --use-ssh --platform iOS' was 1 instead of 0.
*** Fetching realm-cocoa
*** Fetching ios-dependencies
*** Fetching RxRealm
*** Fetching RxSwift
*** Downloading ios-dependencies.framework binary at "0.0.1"
Invalid architecture UUIDs: Could not parse UUIDs using dwarfdump from /Users/ben/Development/Projects/[REDACTED]/Carthage/Build/iOS/Fabric.framework/Fabric
```

I realize I'm using Carthage as a vehicle to achieve a goal but that it might not have been intended to be used in this way. Is there a way to around this?

**Comment by ikesyo** [comment]
Seems that the frameworks are static frameworks and Carthage does not support static frameworks.
