### ISSUE TITLE
xcodebuild timed out while trying to read Bolts.xcodeproj

### ISSUE THREAD

**Issue by filyakov** [Carthage/Carthage#1667]
Hello

I'm getting "xcodebuild timed out while trying to read Bolts.xcodeproj". I saw a similar issue was resolved previously, but I guess not for this use case. Is this because of a time out parameter passed to xcodebuild by Carthage?

* `carthage version`: v0.18.1
* `xcodebuild -version`: Xcode 8.2 Build version 8C38
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO

**Cartfile**
```
github "BoltsFramework/Bolts-ObjC" == 1.8.4
```

**Carthage Output**
```
Vladislavs-MacBook-Pro:*** vladf$ carthage update
*** Fetching Bolts-ObjC
*** Checking out Bolts-ObjC at "1.8.4"
*** xcodebuild output can be found in /var/folders/91/hjw75_894jvds2kfm4mzsn8c0000gn/T/carthage-xcodebuild.uzaKgR.log
xcodebuild timed out while trying to read Bolts.xcodeproj 😭
```

**Comment by mdiep** [comment]
`xcodebuild` has a bug where it sometimes hangs forever.

To work around this issue, Carthage has a timeout on these calls. It sounds like this is one of those cases. Unfortunately, there's nothing we can do about it.
