### ISSUE TITLE
Carthage copy-frameworks failing on Jenkins box

### ISSUE THREAD

**Issue by rbaumbach** [Carthage/Carthage#1676]
* `carthage version`: 0.18.1 installed via Homebrew
* `xcodebuild -version`: Xcode 8.2.1, Build version 8C1002
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO

I have an interesting issue.  I'm unable to archive a project on my Jenkins machines, and it looks like it fails when executing the run script:

`The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/jenkins-box/Library/Developer/Xcode/DerivedData/App-dmlhmdhnjciyftunbgeakoqguxjg/Build/Intermediates/ArchiveIntermediates/App/IntermediateBuildFilesPath/App.build/Release-iphoneos/App.build/Script-347146A51DBFDEE510FF292C.sh
(1 failure)`

What's interesting is if I ssh into the Jenkins box directly and run my fastlane task that archive a build, everything works fine (it also executes fine locally on my development machine), but always (and only) gives this error when a Jenkins build is executed.

Since the run script just uses this: `/usr/local/bin/carthage copy-frameworks` is it possible at all to get any additional information from this command?  I didn't notice any "verbose" setting for this command that could potentially shed any light on this issue.

**Comment by mdiep** [comment]
Hmm… that's very odd. Maybe it's a permissions issue with your jenkins user? The only other thing I can think of is some environment variable is different or messing things up. But I have no idea how to diagnose that.

You're right that there's no verbose setting. I would expect Carthage to print an error if one occurred. But I'm not super familiar with that code, so I can't say that it actually would with certainty.

**Comment by codeOfRobin** [comment]
Getting the same issue on Travis as well. My `Run-Script` would just go on indefinetly until the build would shut down.

**Comment by mdiep** [comment]
Failing and hanging sound like different issues.

**Comment by rbaumbach** [comment]
After investigation I discovered that there was an issue with keychains and code signing on my Jenkins box.  I'm closing issue, but do you @mdiep think it's a good idea to open up a feature request to give a more verbose output to the copy-frameworks command?

**Comment by mdiep** [comment]
Absolutely. If you can provide detail about how to reproduce the issue, that'd be especially helpful.

**Comment by nikhilsh** [comment]
@rbaumbach I think I might be encountering the same issue you had. Could you provide any insights as to how to go about solving this? Thank you!

**Comment by pertau** [comment]
We ran into the same problem. After we had a closer look on the failing "xcodebuild archive" task, we found out that there was a problem with codesigning. For us the solution was to unlock the keychain which includes the ios certificates, before running the xcodebuild job.
