### ISSUE TITLE
[Enhancement] Support http_proxy

### ISSUE THREAD

**Issue by JeromeTan1997** [Carthage/Carthage#1682]
* `carthage version`:  0.18.1
* `xcodebuild -version`:  8C1002
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

Carthage can't use proxy server to download prebuilt binaries.
It's a much needed feature for developers in China.

**Comment by ikesyo** [comment]
I think the underlying `NSURLSession` automatically uses system proxy setting: https://developer.apple.com/reference/foundation/urlsession

> The URLSession class natively supports the data, file, ftp, http, and https URL schemes, with transparent support for proxy servers and SOCKS gateways, as configured in the user’s system preferences.

**Comment by JeromeTan1997** [comment]
@ikesyo It works only if I configure proxy for the whole system. If I want to use proxy to execute one command, I would execute `export http_proxy=http://xxxx` and `export https_proxy=http://xxxx` first. However, these environment variables doesn't work for Carthage.

**Comment by xiongmao86** [comment]
It would be better to also support socks5 proxy as well.
