### ISSUE TITLE
copy-frameworks hanging on travis-CI

### ISSUE THREAD

**Issue by codeOfRobin** [Carthage/Carthage#1687]
* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.2.1
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
<Private library>
github "robb/Cartography"
github "matthewpalmer/Locksmith" "swift-3.0"
github "onevcat/Kingfisher" ~> 3.0
github "andreyz/Pantry" "swift3"
github "codeOfRobin/ParkedTextField" "master"
github "alikaragoz/MCSwipeTableViewCell" >= 2.1.4
github "AgileBits/onepassword-extension" "add-framework-support"
github "codeOfRobin/simple-touch" "master"
github "mixpanel/mixpanel-iphone"
github "SVProgressHUD/SVProgressHUD"
github "skywinder/ActionSheetPicker-3.0"
```
Carthage builds all of my dependencies successfully, but `copy-frameworks` hangs on travis CI (runs fine on my local machine).

**Comment by nikosxondros** [comment]
let the spirit free

**Comment by nikosxondros** [comment]
le

**Comment by fabioknoedtbcgdv** [comment]
Same for me here.
@codeOfRobin did you find the solution?

**Comment by codeOfRobin** [comment]
@fabioknoedtbcgdv Yes I did. Uploaded my fastfile here: https://gist.github.com/codeOfRobin/3d01d2ee7feabc35b3a65bd6b319f84c

**Comment by guidomb** [comment]
What was the solution? enabled_bitcode? I am having the same issue.

**Comment by guidomb** [comment]
Well, that didn't work for me.

**Comment by guidomb** [comment]
The weird thing is that in my case it only happens with the schema that is used for adhoc. Everything works fine for debug builds. But problem only happens in Travis and Bitrise. I cannot reproduce it locally.

**Comment by guidomb** [comment]
I am starting to think this is a fastlane / xcpretty issue. Here are some possible related issues

 * https://github.com/fastlane/fastlane/issues/7802
 * https://github.com/fastlane/fastlane/issues/7747
 * https://github.com/fastlane/fastlane/issues/5163

**Comment by guidomb** [comment]
Well after much trial and error the problem in my case was caused by creating a new keychain for match to download certificates and provisioning profiles. Having a new keychain for some reason made copy-frameworks to hang.

**Comment by codeOfRobin** [comment]
@guidomb yup. Actually it's an issue with sierrra where the GUI issues a pop up asking for access to the keychain(and therefore does nothing on a CI system). If you look at my fastfile, I have a create_keychain step precisely for this reason(so it won't prompt and just use the password I provide)

**Comment by leoMehlig** [comment]
I have the same problem on Travis. 
I also did create a keychain with all the same parameters that @codeOfRobin used.

While using the travis debug mode, I discovered that the `codesign`  command is the one that fails. 
Does anyone have any idea on how to configure the keychain to make `codesign`  work? Or an other idea?

**Comment by dcaunt** [comment]
An explanation of the problem and solution can be found here: http://stackoverflow.com/questions/39868578/security-codesign-in-sierra-keychain-ignores-access-control-settings-and-ui-p

**Comment by leoMehlig** [comment]
Thanks for the link @dcaunt !!!
Adding `sh("security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{ENV["KEYCHAIN_PASSWORD"]} #{ENV["KEYCHAIN_NAME"]}")` to my Fastfile after performing sign and cert fixed it 🎉
