### ISSUE TITLE
Support for target-based dependencies (specify which target dependencies are for)

### ISSUE THREAD

**Issue by eneko** [Carthage/Carthage#1692]
* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.2.1  /  Build version 8C1002
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

I've searched for this question but could not find it, so apologies if this is a duplicate.

Given an application with multiple targets (eg.multiple platforms) I would like to specify dependencies for only one target or a subset of those targets. Currently it seems like there is no support to do this in `Cartfile`.

Consider also multiple targets for the same platform (eg. multiple targets for iOS with some unique dependencies)

Thanks!
Eneko

**Comment by mdiep** [comment]
Carthage has a `--platform` flag that let's the consumer choose which platforms they're interested in.

**Comment by Neko42** [comment]
@mdiep  I think what @eneko  means is that if project has target A and target B, there should be an option to specify which target to builds. That has nothing to do with the different platforms.

**Comment by eneko** [comment]
Correct, you can have an iOS only project with multiple targets. Currently is impossible to add a third party dependency to a subset of those targets. It's all or nothing. 

For comparison, Cocoa Pods makes this very easy via  `target "MyApp" do` blocks (see https://guides.cocoapods.org/syntax/podfile.html#podfile).

**Comment by Neko42** [comment]
@eneko That is what I understood as well. 
It seems Carthage implies the target name from the git/github url.

@mdiep  How complex would it be to add support for that ?

**Comment by mdiep** [comment]
> It seems Carthage implies the target name from the git/github url.

Nope. Carthage doesn't do anything with target names. Carthage builds all shared schemes which contain a dynamic framework.

> How complex would it be to add support for that ?

We're not going to get into the subspecs game. Carthage's simplicity is a virtue.
