### ISSUE TITLE
The synchronization between the different developers

### ISSUE THREAD

**Issue by cjsliujie** [Carthage/Carthage#1699]
* `carthage version`: 0.18.1
First,Sorry,I'm a Chinese and my English is not well。
A question , for example ：
beginning
developer Tom's cartfile is : github "xxx" == 1.1, Cartfile.resolved is : github "xxx" "1.1"
developer Jerry's cartfile is : github "xxx" == 1.1,Cartfile.resolved is : github "xxx" "1.1"
then 
Tom update cartfile to : github "xxx" == 1.2 , and push to SCM
then 
Jerry update the cartfile and Cartfile.resolved , then build project. All is OK。
question: How will Jerry know Tom has updated the  xxx framework。
In cocoapods ,it use Podfile.lock and Pods/Manifest.lock and use a shell to determine whether the two files are the same,if not,then has a tip , so how to solve this problem in Carthage

**Comment by mdiep** [comment]
`Cartfile.resolved` is Carthage's version of `Podfile.lock`. It should be checked into source control and shared. Developers who want to download dependencies, but not upgrade to newer versions, should run `carthage bootstrap`.

**Comment by cjsliujie** [comment]
Thanks,but I mean is that how should Tom know Jerry has updated the xxx's version , because Tom will not execute 'cargthage bootstrap' every time , In cocoapods,it will give a hint like 'The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation',so ,if Tom see this ,he will know he should execute 'pod install' ,but in carthage ,I have not found a mechanism like this , I  think execute 'carthage bootstrap' every time after update project is tedious.

**Comment by mdiep** [comment]
I usually only run `carthage bootstrap` if my build fails—indicating that we now rely on a later version of one of our dependencies. Hopefully something like #1222 will let you run `bootstrap` every time but just speed it up immensely.

**Comment by cjsliujie** [comment]
OK Thanks ~
