### ISSUE TITLE
The synchronization between the different developers question-Reopen

### ISSUE THREAD

**Issue by cjsliujie** [Carthage/Carthage#1704]
#1699 
Thanks,but I mean is that how should Tom know Jerry has updated the xxx's version , because Tom will not execute 'cargthage bootstrap' every time , In cocoapods,it will give a hint like 'The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation',so ,if Tom see this ,he will know he should execute 'pod install' ,but in carthage ,I have not found a mechanism like this , I think execute 'carthage bootstrap' every time after update project is tedious.

**Comment by ikesyo** [comment]
Please reopen #1699 instead of creating a new issue.
