### ISSUE TITLE
Issue with selecting correct version tag

### ISSUE THREAD

**Issue by srdanrasic** [Carthage/Carthage#1707]
I'm experiencing an issue when transitioning my framework to a non-v prefixed version tags. Previously I had tags like _v5.1.2_, but now I released a beta of v6 and tagged it _6.0.0-beta.1_ and the Carthage is not picking it up when Cartfile specifies the version as _~> 6.0_. If I tag it as _v6.0.0-beta.1_ everything works. 

* `carthage version`: 0.18
* `xcodebuild -version`: 8.2.1
* Are you using `--no-build`? Yes and no
* Are you using `--no-use-binaries`? Yes and no
* Are you using `--use-submodules`? Yes and no

**Cartfile**
```
github "ReactiveKit/Bond" ~> 6.0
```

**Carthage Output**
```
$ carthage update --platform iOS Bond
*** Fetching Bond
*** Checking out Bond at "v5.0.0-beta9"
```

Note that the repo contains, among others, following tags: v5.0.0, v5.1.0, ..., v5.4.0, 6.0.0-beta.1, 6.0.0-beta.2 and 6.0.0-beta.3 so checking out _v5.0.0-beta9_ is completely wrong 😄

**Comment by mdiep** [comment]
Carthage won't select `6.0.0-beta.3` if you've specified `~> 6.0` because prerelease versions don't specify version requirements. You'll need to specify `github "ReactiveKit/Bond" "6.0.0-beta.3"`.

Its selection of `v5.0.0-beta9` is definitely a bug. I recently rewrote the test suite to make it easier to test bugs like this. I'll add this as a test.

**Comment by srdanrasic** [comment]
But it will select `v6.0.0-beta.X` when present. Is that a bug too?

Maybe I'm missing something here, but is that really how Carthage is supposed to work? One would expect that there would be a way to specify any v6 beta version. More specifically, one would expect that if there are no release versions, it would select latest prerelease version.

**Comment by mdiep** [comment]
> But it will select v6.0.0-beta.X when present. Is that a bug too?

Yes, sadly.

> Maybe I'm missing something here, but is that really how Carthage is supposed to work? One would expect that there would be a way to specify any v6 beta version. More specifically, one would expect that if there are no release versions, it would select latest prerelease version.

It's just how Carthage currently works. We'd like to have logic for prerelease versions, we just don't currently. It's a tricky thing to get right from a UX perspective.

**Comment by srdanrasic** [comment]
Ah, ok then :)

**Comment by eMdOS** [comment]
Today, I changed my `Cartfile`:

```
github "ReactiveKit/ReactiveKit" ~> 3.2
github "ReactiveKit/Bond" "bond-6"
```

and for now, it is working.

**Comment by blender** [comment]
Samantic Version improvements should close this issue #2412
