### ISSUE TITLE
Documentation should state how to run a project that uses Carthage

### ISSUE THREAD

**Issue by alper** [Carthage/Carthage#1709]
I'm trying out a project that uses Carthage and I can't find in the documentation (quickly) how to get it to run.

I have no interest in becoming an expert in Carthage, I just want to get this one project to run.

**Comment by alper** [comment]
Reading a bit further into it, it seems there is not one command to bootstrap a project with. That seems like a major oversight.

**Comment by dcaunt** [comment]
IMHO it's up to the project you're working with to document exactly how it should be bootstrapped, but you're probably looking for `carthage bootstrap`.

If your project is only for one platform (i.e. an iOS or Mac app) you can use `carthage bootstrap --platform iOS` to avoid building frameworks for other platforms.

If the project use Carthage to manage git submodules, you may need to add the `--use-submodules` flag.
