### ISSUE TITLE
Playground Issue:  xcodebuild: WARNING: Unable to open project file

### ISSUE THREAD

**Issue by verticon** [Carthage/Carthage#1728]
Folks,

From the Carthage output below you can see that there is some difficulty regarding the workspace's playground file. If I remove the playground file reference from the workspace then the warnings do not occur. If I replace the playground file with a new, empty playground file (i.e. is it something about the playground's content?) then the warnings return. If I open the workspace which Carthage downloaded in Xcode then all is okay. The reason that I care, even though it is only a warning, is that I do not want RNCryptor's users to experience doubt or dismay.

When I google "xcodebuild: WARNING: Unable to open project file" I get a lot of results; most of which bring me back here to github projects and Carthage: [RxSwift](https://github.com/ReactiveX/RxSwift/issues/856), [SDCAlertView](https://github.com/sberrevoets/SDCAlertView/issues/175), [Haneke](https://github.com/Haneke/HanekeSwift/issues/329), etc. But nowhere do I find a resolution to the warning - often folks are experiencing other difficulties related to swift migration.

I am not knowledgable enough to be able to determine the source of the issue: xcodebuild? Carthage? The interaction of the two? Please provide some guidance.

* `carthage version`:  0.18.1
* `xcodebuild -version`:  8.2.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
# github "RNCryptor/RNCryptor" ~> 5.0
github "verticon/RNCryptor" "master"
# github "SwiftyJSON/SwiftyJSON" ~> 3.0
```

**Carthage Output**
```
~/Development/iOS/RNCryptor/CarthageTestApp$Carthage update
*** Fetching RNCryptor
*** Checking out RNCryptor at "85372ccd39111ef4921fbbbe5377eae556df7530"
*** xcodebuild output can be found in /var/folders/2f/xk9410s97qj7zmwft5n74xfw0000gn/T/carthage-xcodebuild.Sy00cK.log
*** Building scheme "RNCryptor" in RNCryptor.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/Users/Robert/Development/iOS/RNCryptor/CarthageTestApp/Carthage/Checkouts/RNCryptor/Example.playground' in workspace '/Users/Robert/Development/iOS/RNCryptor/CarthageTestApp/Carthage/Checkouts/RNCryptor/RNCryptor.xcworkspace'.
--- xcodebuild: WARNING: Unable to open project file '/Users/Robert/Development/iOS/RNCryptor/CarthageTestApp/Carthage/Checkouts/RNCryptor/Example.playground' in workspace '/Users/Robert/Development/iOS/RNCryptor/CarthageTestApp/Carthage/Checkouts/RNCryptor/RNCryptor.xcworkspace'.
*** Building scheme "RNCryptor-OSX" in RNCryptor.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/Users/Robert/Development/iOS/RNCryptor/CarthageTestApp/Carthage/Checkouts/RNCryptor/Example.playground' in workspace '/Users/Robert/Development/iOS/RNCryptor/CarthageTestApp/Carthage/Checkouts/RNCryptor/RNCryptor.xcworkspace'.
*** Building scheme "RNCryptor-Performance" in RNCryptor.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/Users/Robert/Development/iOS/RNCryptor/CarthageTestApp/Carthage/Checkouts/RNCryptor/Example.playground' in workspace '/Users/Robert/Development/iOS/RNCryptor/CarthageTestApp/Carthage/Checkouts/RNCryptor/RNCryptor.xcworkspace'.
--- xcodebuild: WARNING: Unable to open project file '/Users/Robert/Development/iOS/RNCryptor/CarthageTestApp/Carthage/Checkouts/RNCryptor/Example.playground' in workspace '/Users/Robert/Development/iOS/RNCryptor/CarthageTestApp/Carthage/Checkouts/RNCryptor/RNCryptor.xcworkspace'.
~/Development/iOS/RNCryptor/CarthageTestApp$
```

**Comment by mdiep** [comment]
This is an Xcode/xcodebuild issue. We can do nothing about it.

It should be harmless. Also, the next version of Carthage won't pass those warnings through automatically.

**Comment by verticon** [comment]
Thank you, Matt.
