### ISSUE TITLE
ERROR ITMS-90035 when submitting to App Store, no entitlements on Frameworks

### ISSUE THREAD

**Issue by twodayslate** [Carthage/Carthage#1737]
* `carthage version`:  0.18.1
* `xcodebuild -version`:  Xcode 8.2.1 Build version 8C1002
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "lorentey/BigInt" ~> 2.1
github "bitstadium/HockeySDK-iOS" "master"
```

**Carthage Output**
```
$ carthage update
*** Fetching HockeySDK-iOS
*** Fetching BigInt
*** Fetching SipHash
*** Checking out HockeySDK-iOS at "93551df117994834340a18dc362997e9e82b75e0"
*** Checking out SipHash at "v1.1.0"
*** Checking out BigInt at "v2.1.1"
*** xcodebuild output can be found in /var/folders/kc/ss77c7655fjfwstkrth0k_mm0000gn/T/carthage-xcodebuild.bPufhT.log
*** Building scheme "HockeySDK Framework" in HockeySDK.xcodeproj
*** Building scheme "SipHash-tvOS" in SipHash.xcodeproj
*** Building scheme "SipHash-macOS" in SipHash.xcodeproj
*** Building scheme "SipHash-watchOS" in SipHash.xcodeproj
*** Building scheme "SipHash-iOS" in SipHash.xcodeproj
*** Building scheme "BigInt-macOS" in BigInt.xcworkspace
*** Building scheme "BigInt-tvOS" in BigInt.xcworkspace
*** Building scheme "BigInt-watchOS" in BigInt.xcworkspace
*** Building scheme "BigInt-iOS" in BigInt.xcworkspace
warning: /var/folders/g9/mxr37xcs33g38q39zkf76xb00000gp/C/com.apple.DeveloperTools/7.2-7C68/Xcode/SharedPrecompiledHeaders/OCMockLib-Prefix-aguhwhqcwfsriffwgjqlwwuendhr/OCMockLib-Prefix.pch.pch: No such file or directory
warning: /var/folders/g9/mxr37xcs33g38q39zkf76xb00000gp/C/com.apple.DeveloperTools/7.2-7C68/Xcode/SharedPrecompiledHeaders/OCMockLib-Prefix-efhbsnkhmearojbasgiitukrjnoo/OCMockLib-Prefix.pch.pch: No such file or directory
warning: /var/folders/g9/mxr37xcs33g38q39zkf76xb00000gp/C/com.apple.DeveloperTools/7.2-7C68/Xcode/SharedPrecompiledHeaders/OCMockLib-Prefix-efeadqrgtnidxwbadwtohuxejrdb/OCMockLib-Prefix.pch.pch: No such file or directory
warning: /var/folders/g9/mxr37xcs33g38q39zkf76xb00000gp/C/com.apple.DeveloperTools/7.2-7C68/Xcode/SharedPrecompiledHeaders/OCMockLib-Prefix-bxixbexkmoooetbthjtvimnkelbz/OCMockLib-Prefix.pch.pch: No such file or directory
```

Getting the following error when trying to submit to the App Store (Test Flight)
```
ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

```

Here are my signing settings and App Store submission results
http://imgur.com/a/KRVWG

Is there an order that the copy-frameworks run script should be in? I am just running Carthage update in the project directory, is there something else I should be doing?

I apologize if this is not a Carthage issue but I can submit an application without Carthage frameworks. 

Thanks and let me know if you need any more information!

**Comment by mdiep** [comment]
Well you should need to add the frameworks from Carthage to the "Linked Frameworks and Libraries" section. Xcode often "helpfully" handles that automatically when launching directly from Xcode. But it probably doesn't work outside of Xcode.

**Comment by twodayslate** [comment]
I've tried it without adding the frameworks and adding the frameworks and I still get the same error

<img width="124" alt="screen shot 2017-01-30 at 8 04 29 am" src="https://cloud.githubusercontent.com/assets/1085707/22424121/fb175c54-e6c2-11e6-86a3-8915c73fd8dc.png">
<img width="124" alt="screen shot 2017-01-30 at 8 09 42 am" src="https://cloud.githubusercontent.com/assets/1085707/22424269/d4be6e34-e6c3-11e6-95e1-434d923834b0.png">
<img width="124" alt="screen shot 2017-01-30 at 8 11 50 am" src="https://cloud.githubusercontent.com/assets/1085707/22424268/d4a0e33c-e6c3-11e6-948c-8405c6198340.png">

**Comment by twodayslate** [comment]
I switched to cocoa-pods and everything worked fine.

**Comment by aalenliang** [comment]
Wow, thank you for your suggestion.
When i archive and validate my App, the log says:
```
Alamofire.framework: code object is not signed at all
```

and in my Build phases, i put embed frameworks below run script section. lol.
after reorder them, issue fixed.
