### ISSUE TITLE
Move Pie segment in front of the hole

### ISSUE THREAD

**Issue by mineschan** [Carthage/Carthage#1738]
Hi everyone,

I'm using the PieChartView with the hole, however I wanted to move one of the pie in front of the hole like the image I've uploaded, is that possible to do so? Thanks!

<img width="642" alt="2017-01-30 7 48 35" src="https://cloud.githubusercontent.com/assets/897340/22422057/66022f14-e725-11e6-84b8-20b74b06dbbc.png">

**Comment by ikesyo** [comment]
Please file an issue on that library's repository.
