### ISSUE TITLE
Should `--no-build` be the default behavior for carthage bootstrap/update?

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#174]
With submodule support, Carthage is becoming increasingly useful for simply managing dependencies, and not always _building_ them. This causes friction for new users, who may not know that a project uses the `--no-build` flag.

Some setting could maybe go into the Cartfile, but that quickly gets confusing. For example, what does it mean for a _framework_ Cartfile to specify `--no-build`, but an application to specify `--build`? We don't really support mixing and matching like that.

Instead, maybe our philosophy for each command should be “do as little work as possible, unless more is requested,” which would be nice and UNIX-y too.

@Carthage/carthage Thoughts?

/cc @dannygreg @alanjrogers

**Comment by mxcl** [comment]
Don’t underestimate the importance of “it just works” for adoption.

Currently carthage builds with all architectures. This is different to how the user will build their own sources at *any* stage, leading to likely build errors. The ones I've seen from my users are mis-configured provisioning.

Stuff they *will* need to fix, but they don't need to fix right now. Right now when they are trying out Carthage and trying out my frameworks. Then they will give up on Carthage or my stuff or everything.

**Comment by jspahrsummers** [comment]
> Don’t underestimate the importance of “it just works” for adoption.

@mxcl This is exactly _why_ Carthage builds by default, and builds every architecture. Upon a successful build, you have a framework that should Just Work™ in every case you'd care about (running in the simulator, running on device, distributing your library, etc).

> Currently carthage builds with all architectures.

Carthage builds for both device and simulator, but it uses the architecture and provisioning settings provided in the project.

It should be the same result you'd get when using Xcode subprojects, then building separately for device and simulator. If users are having provisioning problems, they would have them with device builds for subprojects too.

> The ones I've seen from my users are mis-configured provisioning.

For the specific case of not having an appropriate codesigning identity for the intended platform, we're [already discussing](https://github.com/Carthage/Carthage/issues/281#issuecomment-77608854) how to automatically work around that case.

**Comment by mxcl** [comment]
> For the specific case of not having an appropriate codesigning identity for the intended platform, we're already discussing how to automatically work around that case.

That'll do the trick then (hopefully). Sorry for this noise, I saw this old post while hunting for something and felt obliged to say something but now I feel the usual remorse.

**Comment by jspahrsummers** [comment]
@mxcl No worries! I'm more than happy to hear any and all feedback. :smile:
