### ISSUE TITLE
Linking a framework to your project for multiple platforms

### ISSUE THREAD

**Issue by ivan-konov** [Carthage/Carthage#1744]
<img width="261" alt="screen shot 2017-01-31 at 2 03 00 pm" src="https://cloud.githubusercontent.com/assets/5302709/22486359/0caaf86c-e7be-11e6-9c0f-353fabdd01ad.png">
* `carthage version`: 0.18.1
* `xcodebuild -version`: 8.2.1
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO

**Cartfile**
```
github "rs/SDWebImage" ~> 4.0
```
I will use SDWebImage for an example but my question is general.
I want to link SDWebImage to my project and use it for the iOS and watchOS apps. Following Carthage instructions I do this for both platforms(targets).
`On your application targets’ “General” settings tab, in the “Linked Frameworks and Libraries” section, drag and drop each framework you want to use from the Carthage/Build folder on disk.`
But this adds BOTH framework bundles from BOTH the iOS and watchOS Build folders. This makes it look like I added a project entry for the same frameworks as seen in the attached screenshot. What is the best practice for that case? Ideally I would like to see just one framework entry there.

**Comment by mdiep** [comment]
That's just how Xcode is. You may want to create platform-specific groups inside the `Frameworks` group.

**Comment by ivan-konov** [comment]
Yeah I was just hoping you have better suggestion. I guess we all hope for some changes on this side in Xcode 9 this summer.
Anyway thanks for the great work on Carthage!
