### ISSUE TITLE
Bootstrapping error when trying to use SSH to clone private repository

### ISSUE THREAD

**Issue by mattia** [Carthage/Carthage#1747]
* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.2.1 Build version 8C1002
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
git "ssh://git@bitbucket.org:organization/fakeproject.git" "branch"
```

When I run `carthage bootstrap --platform iOS` I get this output

**Carthage Output**
```
A shell task (/usr/bin/env git clone --bare --quiet https://bitbucket.org/organization/fakeproject.git /Users/user/Library/Caches/org.carthage.CarthageKit/dependencies/fakeproject) failed with exit code 128:
fatal: could not read Username for 'https://bitbucket.org': terminal prompts disabled
```

It seems that Carthage is trying to clone the repository using HTTPS, but it should be using SSH.
I also tried running `carthage bootstrap --use-ssh --platform iOS` but got the same result.
(running `git clone git@bitbucket.org:organization/fakeproject.git` works correctly)

Am I doing something wrong? Any hints?
Thanks for the awesome work!

**Comment by mdiep** [comment]
I don't think Carthage would be doing anything here. It's possible to configure git to rewrite URLs like that. Are you sure you don't have something like that in your git config?

**Comment by mattia** [comment]
Hi! First things first thank you for the answer.

> It's possible to configure git to rewrite URLs like that. Are you sure you don't have something like that in your git config?

I checked my git config but there was nothing strange. Your hint directed me to the solution of the problem.
Carthage is doing the right thing, it's the git URL that is wrong. Bitbucket when choosing to clone using the web interface gives you an address like this
`git@bitbucket.org:organization/fakeproject.git`
but the correct URL to use is this
`git@bitbucket.org*/*organization/fakeproject.git`
Making this change allowed Carthage to clone the repo without issues.

Thanks again!
