### ISSUE TITLE
Use a fork in all dependencies

### ISSUE THREAD

**Issue by iandundas** [Carthage/Carthage#1751]
Is there a way to get all dependencies to use a specific fork of a certain project?

For example:

My project A requires dependency B, which itself depends on a regular release of C.

I want to use my own fork of C throughout my project - is it possible to get B to use the fork without modifying B itself, just by adding my fork of C to A's cartfile?

When I tried it, Carthage compiles both the original and the forked version - I guess I could just ignore the .framework of the original? But is there a way to be explicit about this - i.e. specify overrides 

I hope that makes sense 🤔

Cheers

(Rationale: C doesn't compile in Xcode 8.3b1, and B depends on it - I want B to use my forked version of C that I've  repaired, and I'm wondering if this can be done top-down from A's Cartfile)

**Comment by mdiep** [comment]
Carthage should be comparing dependencies on the name of the repository (without the name of the owner). So this should just work. B might still build its own copy of C—but you can just link against yours.

**Comment by iandundas** [comment]
> you can just link against yours.
Ah perfect - thanks!
