### ISSUE TITLE
Try to update lot of branches from same repo. The following dependencies are duplicates

### ISSUE THREAD

**Issue by epodkorytov** [Carthage/Carthage#1753]
* `carthage version`: 0.18.1
* `xcodebuild -version`: 8.2.1 (8C1002)
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO

Hi!
My repo consist different Frameworks in lot of branches

"https://bitbucket.company.net/components/OCTextInput" "(TextInput)1.0.1"
"https://bitbucket.company.net/components/OCTextInput.git" "(Popup)1.0.1"

When I try to update getting error : The following dependencies are duplicates: "https://bitbucket.company.net/components/OCTextInput" "(TextInput)1.0.1" (found in Cartfile)

How I can update components from repo? Thanks!

**Comment by mdiep** [comment]
Carthage can only check out one version of a given repository. (Otherwise we'd face a lot of issues: like where do you put it in the `Carthage/Checkouts/` folder.)

If you want to use a repo with multiple projects, they'll need to be versioned together.

**Comment by epodkorytov** [comment]
thanks a lot. but i didn't understand about "If you want to use a repo with multiple projects, they'll need to be versioned together". explain please.

**Comment by epodkorytov** [comment]
Sorry mistake in repo path:

"https://bitbucket.company.net/components.git" "(TextInput)1.0.1"
"https://bitbucket.company.net/components.git" "(Popup)1.0.1"

**Comment by mdiep** [comment]
I mean you'd need to do:

```
git "https://bitbucket.company.net/components.git" "1.0.1"
```

And have both frameworks in that one version.

**Comment by epodkorytov** [comment]
I can't set same tag in all branches.

**Comment by mdiep** [comment]
You can only use one branch. You can't use multiple branches.

**Comment by epodkorytov** [comment]
Resolved.
Create Cartfile.master and bash script ...

Cartfile.master
"https://bitbucket.company.net/components.git" "(TextInput)1.0.1"
"https://bitbucket.company.net/components.git" "(Popup)1.0.1"

updateCarthage.sh
#!/bin/sh
while read line; do
if [ "$line" = "${line%#*}" -a "$line" ]; then
echo $line > Cartfile
carthage update
fi
done < ./Cartfile.master
