### ISSUE TITLE
Consider more descriptive error messaging deployment target scenario

### ISSUE THREAD

**Issue by dcow** [Carthage/Carthage#1759]
I encountered a scenario similar to https://github.com/Carthage/Carthage/issues/950. Understood this is not Carthage's fault, it is problematic because people might think Carthage is broken when it's likely an issue with the dependency. In my case, the dependency I was trying to use had not specified a deployment target. During the build Xcode attempted to target the latest version 10.2 even though my Xcode (version 8.1) does not have support for that platform version yet. This manifests as, for example:

```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:32AD388D-029B-4391-9867-FBADC95790C7 }

	Ineligible destinations for the "Lottie" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
A shell task (/usr/bin/xcrun xcodebuild -project <project-dir>/Carthage/Checkouts/lottie-ios/Lottie.xcodeproj -scheme Lottie -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,id=32AD388D-029B-4391-9867-FBADC95790C7" -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 70:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:32AD388D-029B-4391-9867-FBADC95790C7 }

	Ineligible destinations for the "Lottie" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
```

I don't think we can expect people to always be using the latest Xcode version when using Carthage. Maybe there's a better way to communicate the issue or, initially, at least prompt people to update.

**Comment by ikesyo** [comment]
Sorry for the late response, but I'm not sure how this would hapeen.

> During the build Xcode attempted to target the latest version 10.2

That should mean that you were using Xcode 8.2 somehow.

**Comment by ikesyo** [comment]
Looks like an issue is filed and closed on the upstream: https://github.com/airbnb/lottie-ios/issues/80. Closing.
