### ISSUE TITLE
Carthage is not downloading pre-built framework

### ISSUE THREAD

**Issue by HazAT** [Carthage/Carthage#1768]
* `carthage version`: `0.19.1`
* `xcodebuild -version`: 
```
Xcode 8.2.1
Build version 8C1002 
```

* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO 

**Cartfile**
```
github "getsentry/sentry-swift" "2.1.1"
github "kstenerud/KSCrash" "1.15.3"
```

**Carthage Output**
```
carthage update --platform iOS
*** Checking out KSCrash at "1.15.3"
*** Downloading sentry-swift.framework binary at "2.1.1"
*** xcodebuild output can be found in /var/folders/_v/tf559h3x4g78km9jwq3dcw680000gn/T/carthage-xcodebuild.bUmFfA.log
*** Building scheme "KSCrash-iOS" in iOS.xcworkspace
```

Hey ... I am having issues with Carthage downloading and using a prebuilt framework.
The output says that everything is fine but `Sentry.framework` isn't in the build folder.

<img width="821" alt="screenshot 2017-02-16 09 33 53" src="https://cloud.githubusercontent.com/assets/363802/23013528/53e12bba-f42b-11e6-84c4-279bd81be890.png">

If I use `--no-use-binaries` it works fine.
There is also just `KSCrash` in the checkouts folder.

**Comment by ikesyo** [comment]
See https://github.com/getsentry/sentry-swift/issues/131#issuecomment-280272676.
