### ISSUE TITLE
Importing different frameworks with the same name results in failure

### ISSUE THREAD

**Issue by olbrichj** [Carthage/Carthage#1769]
Detected while trying to import PromiseKits OMGHTTPURLRQ. It seems like having different frameworks with the same name result in overriding one framework with the other during checkout. Which results in an error.

Promisekit worked around it, but basically having two frameworks with the same name (in this case mxcl/OMGHTTPURLRQ and PromiseKit/OMGHTTPURLRQ) needed to be checked out results in the below error.

Xcode 8.2.1 with Swift 3

Cartfile:

github "mxcl/PromiseKit"
github "PromiseKit/OMGHTTPURLRQ" ~> 1.0

Error:

*** Checking out OMGHTTPURLRQ at "1.0.0"
A shell task (/usr/bin/env git checkout --quiet --force 1.0.0) failed with exit code 1:
error: pathspec '1.0.0' did not match any file(s) known to git.

**Comment by mxcl** [comment]
I have renamed the `PromiseKit/OMGHTTPURLRQ` repo, but this should still be resolved, collisions like this are inevitable.

**Comment by mdiep** [comment]
Carthage considers repos with same name (without owner) to be identical. So `mxcl/OMGHTTPURLRQ` and `PromiseKit/OMGHTTPURLRQ` both refer to the project `OMGHTTPURLRQ`. This is done so that an app can switch to a fork while maintaining compatibility with its dependencies.

**Comment by mxcl** [comment]
I see. Well this won't be the first time you get this report, for sure.

**Comment by jblack10101** [comment]
Ran into this issue and wasted time on it as well.  We had branched off a repo for iOS to make some updates, and that now makes our tvOS builds fail.  So if this isn't going to be fixed, we're going to have to use the same repo for both iOS and tvOS projects now.
