### ISSUE TITLE
Add Option for ignoring architecture i386 

### ISSUE THREAD

**Issue by CodeEagle** [Carthage/Carthage#1771]
* `carthage version`: 0.19.1
* `xcodebuild -version`: 8.2
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

More and more SDKs provide by third-party vendor is removed that architecture.
But using Carthage to build it will crash

**Comment by mdiep** [comment]
Can you point to an example SDK that crashes?

**Comment by CodeEagle** [comment]
The situation is that:
I wrap a static library such as `libSomething.a` in to a framework target written in swift.
Because that static library only contain `armv7 x86_64 arm64`, no `i386`
when build this repo `--no-skip-current` with `Carthage`
will stop lacking `i386`

**Comment by mdiep** [comment]
It'll be much easier for someone to fix this if you can point to an example project.

**Comment by CodeEagle** [comment]
But it's a trend that, more and more third-party will drop `i386`, `QQ` come first

![image](https://cloud.githubusercontent.com/assets/2311352/23241296/449fc314-f9ad-11e6-94af-2ab2630f3251.png)

The latest SDK， already remove `i386`.

**Comment by ikesyo** [comment]
Looks like you should remove `i386` from `VALID_ARCHS` build setting in your framework target.

**Comment by CodeEagle** [comment]
![image](https://cloud.githubusercontent.com/assets/2311352/23648781/03440dfe-0357-11e7-9ffe-a659dc2fa3a1.png)

Does `$(ARCHS_STANDARD)` contains `i386`?

**Comment by ikesyo** [comment]
See the differences between the two of the followings:

```
xcodebuild -showBuildSettings -scheme Result-iOS -sdk iphoneos | grep ARCHS
    ARCHS = armv7 arm64
    ARCHS_STANDARD = armv7 arm64
    ARCHS_STANDARD_32_64_BIT = armv7 arm64
    ARCHS_STANDARD_32_BIT = armv7
    ARCHS_STANDARD_64_BIT = arm64
    ARCHS_STANDARD_INCLUDING_64_BIT = armv7 arm64
    ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
    VALID_ARCHS = arm64 armv7 armv7s
```

```
xcodebuild -showBuildSettings -scheme Result-iOS -sdk iphonesimulator | grep ARCHS
    ARCHS = i386 x86_64
    ARCHS_STANDARD = i386 x86_64
    ARCHS_STANDARD_32_64_BIT = i386 x86_64
    ARCHS_STANDARD_32_BIT = i386
    ARCHS_STANDARD_64_BIT = x86_64
    ARCHS_STANDARD_INCLUDING_64_BIT = i386 x86_64
    ARCHS_UNIVERSAL_IPHONE_OS = i386 x86_64
    VALID_ARCHS = i386 x86_64
```

**Comment by ikesyo** [comment]
You should be able to setup your framework target like this:

<img width="668" alt="2017-03-08 0 35 11" src="https://cloud.githubusercontent.com/assets/909674/23663870/3b8f7a28-0397-11e7-950f-3fe3cefdd6bc.png">

**Comment by CodeEagle** [comment]
Thanks,that helps a lot!
