### ISSUE TITLE
version 0.19.1 release contains malformed PackageInfo

### ISSUE THREAD

**Issue by apettinen** [Carthage/Carthage#1773]
* `carthage version`:  0.19.1
* `xcodebuild -version`: Not Applicable
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

The PackageInfo inside Carthage.pkg in version 0.19.1 contains malformed PackageInfo, specifically the version string is set to agvtool error message instead of the actual version:
```
version="There are multiple projects in this directory.  agvtool does not work with multiple projects in 
the same directory.  agvtool - Apple-generic versioning tool for Xcode projects   usage:     agvtool help     
agvtool what-version | vers [-terse]     agvtool [-noscm | -usecvs | -usesvn] next-version | bump [-all]  
   agvtool [-noscm | -usecvs | -usesvn] new-version [-all] &lt;versNum&gt;     agvtool [-noscm | -usecvs 
| -usesvn] tag [-force | -F] [-noupdatecheck | -Q] [-baseurlfortag]     agvtool what-marketing-version |
 mvers [-terse | -terse1]     agvtool [-noscm | -usecvs | -usesvn] new-marketing-version
&lt;versString&gt;" 
```

To best of my knowledge, this due to two .xcodeproj files in the source dir (Carthage.xcodeproj and XCDBLD.xcodeproj).

This causes problems when distributing the software to our clients via Munki/Autopkg.

**Comment by mdiep** [comment]
It looks like this can be fixed by adding a `cd Carthage` to the `Makefile`.

```
VERSION_STRING=$(shell cd Carthage && agvtool what-marketing-version -terse1)
```

How can I test the results? I'm not sure how to see the `PackageInfo` inside the `.pkg`.

**Comment by apettinen** [comment]
You can e.g. expand the package via:
```pkgutil --expand /path/to/carthage.pkg /path/to/where/expanded```

And then you can just open the PackageInfo (or use ```less```or whatever :) )

**Comment by dcaunt** [comment]
I can't see a solution for this using `agvtool` without moving the project. Perhaps we should simply `git describe --tags` as in `script/update-cli-version`

**Comment by apettinen** [comment]
Disclaimer: just a newbie in Swift but:

Quickly tested by moving XCDBLD.xcodeproj under Sources and fixing the paths, header etc. Ran ```make install``` succesfully and ```agvtool what-marketing-version -terse1``` reports correctly (0.19.1). Also the resulting pkg reports the version correctly:
```
<pkg-info overwrite-permissions="true" relocatable="false" identifier="org.carthage.carthage" 
postinstall-action="none" version="0.19.1" format-version="2" generator-version="InstallCmds-611 
(16E163f)" install-location="/" auth="root">
```

Hope this helps.

**Comment by jdhealy** [comment]
Should the [git-describing version string](https://github.com/Carthage/Carthage/pull/1114/commits/8b0099a28e43e7d2e4fcd3ead5d77ad97b0478a1) from #1114 be what we put in PackageInfo — so, that it mirrors `carthage version` output?

if so, we could add another line to [the `update-cli-version` script](https://github.com/Carthage/Carthage/blob/95f0c0bd57615e3735fb6a33adbf5129076bca51/script/update-cli-version) to output a plain-text version string file, which the Makefile could simply read in (with `/bin/cat`, I guess).
