### ISSUE TITLE
Output from build of secondary dependency not available for build of primary dependency

### ISSUE THREAD

**Issue by verticon** [Carthage/Carthage#1778]
* `carthage version`: 0.18.1
* `xcodebuild -version`: 8.2.1
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? NO

**Cartfile**
```
github "verticon/MoBetterBluetooth" "master"
```

**Carthage Output**
```
~/Development/iOS/ButtonLed$carthage update
*** Fetching MoBetterBluetooth
*** Fetching VerticonsToolbox
*** Checking out VerticonsToolbox at "23453eaca3a0b4648e5748fa70e209a7a99abaeb"
*** Checking out MoBetterBluetooth at "541696139a851bae3a576a16f025252eea316b37"
*** xcodebuild output can be found in /var/folders/2f/xk9410s97qj7zmwft5n74xfw0000gn/T/carthage-xcodebuild.6E0VSI.log
*** Building scheme "VerticonsToolbox" in VerticonsToolbox.xcodeproj
*** Building scheme "MoBetterBluetooth" in MoBetterBluetooth.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/Robert/Development/iOS/ButtonLed/Carthage/Checkouts/MoBetterBluetooth/MoBetterBluetooth/Utilities.swift:11:8: error: no such module 'VerticonsToolbox'
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Robert/Development/iOS/ButtonLed/Carthage/Checkouts/MoBetterBluetooth/MoBetterBluetooth.xcodeproj -scheme MoBetterBluetooth -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

```

My Cartfile specifies a dependency upon 'MoBetterBluetooth'. The MoBetterBluetooth repository contains a Cartfile which specifies a dependency upon 'VerticonsToolbox' As we can see, Carthage discovers the secondary dependency and builds VerticonsToolbox. Why is VerticonsToolbox.framework not available to the build of MoBetterBluetooth?

**Comment by mdiep** [comment]
It should be _available_. But MoBetterBluetooth may not be using it.

You should see VerticonsToolbox under both `Carthage/Builds/(platform)/` and `Carthage/Checkouts/` inside `Carthage/Checkouts/MoBetterBluetooth`.

**Comment by verticon** [comment]
Hi Matt,

Thank you for getting back to me. Your comment "But MoBetterBluetooth may not be using it" has helped me to see that I am confused.

What is the correct way to handle this type of situation: App depends on FrameworkA; FrameworkA depends on FrameworkB?

Is there any way to configure MoBetterBluetooth's project file such that it will find the VerticonsToolbox that carthage built?

**Comment by mdiep** [comment]
You may need to set `MoBetterBluetooth`s `FRAMEWORK_SEARCH_PATHS` to `Carthage/Build/(platform)/`

**Comment by verticon** [comment]
Matt, I now understand what is happening. Thank you for your help!
