### ISSUE TITLE
Parse error: unexpected trailing characters in line for binary

### ISSUE THREAD

**Issue by rob-nash** [Carthage/Carthage#1781]
* `carthage version`: 0.18
* `xcodebuild -version`: Xcode 8.2.1 Build version 8C1002
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? yes

**Cartfile**
```
github "rob-nash/robstoolbox" == 1.0
binary "https://www.nash.codes/release/wdo/framework.json"
```

**Carthage Output**
```
Parse error: unexpected trailing characters in line: binary "https://www.nash.codes/release/wdo/framework.json"
```

**framework.json**
```
{
    "4.19.0": "https://nash.codes/release/wdo/bolts_4190.framework.zip",
    "4.19.0": "https://nash.codes/release/wdo/fbsdkcorekit_4190.framework.zip",
    "4.19.0": "https://nash.codes/release/wdo/fbsdksharekit_4190.framework.zip"
}
```

**https**
```
https is currently unavailable at nash.codes. I'm working on getting an SSL cert in place, but this shouldn't be the cause of the parse error, above.
```

Either the documentation is a little flakey around binary only frameworks, or I'm just not getting it. Probably the latter.

**Comment by ikesyo** [comment]
Carthage 0.18 does not support `binary` origin, the support is added since 0.19.

**Comment by rob-nash** [comment]
Thanks
