### ISSUE TITLE
carthage build and carthage archive -passed but Builds folder is empty when install

### ISSUE THREAD

**Issue by af-fess** [Carthage/Carthage#1782]
* `carthage version`:  `0.18.1`
* `xcodebuild -version`: 

```
Xcode 8.2
Build version 8C38
```

* Are you using `--no-build`? - no
* Are you using `--no-use-binaries`? - no
* Are you using `--use-submodules`? - no

**Cartfile**
```
github "AppsFlyerSDK/AppsFlyerFWTestBuild" == 4.6.493
```

**Carthage Output**
```
$ carthage update --platform iOS
*** Fetching AppsFlyerFWTestBuild
*** Downloading AppsFlyerFWTestBuild.framework binary at "4.6.493"
*** Checking out AppsFlyerFWTestBuild at "4.6.493"
*** xcodebuild output can be found in /var/folders/ms/ls1sh5ms47v4m_z825k2f1q40000gn/T/carthage-xcodebuild.N1FYrX.log
```

We use build machine that builds our project and generates Carthage.

So output zip file you can find here: [https://github.com/AppsFlyerSDK/AppsFlyerFWTestBuild/releases](https://github.com/AppsFlyerSDK/AppsFlyerFWTestBuild/releases)

From build machine:

```
/usr/local/bin/carthage build --no-skip-current

*** xcodebuild output can be found in /var/folders/kv/8l5w0tqj4cdg0qkwxfk27b4w0000gn/T/carthage-xcodebuild.F7IHZs.log
*** Building scheme "AppsFlyerTracker" in AppsFlyerLib.xcodeproj

/usr/local/bin/carthage archive

*** Found Carthage/Build/iOS/AppsFlyerTracker.framework
*** Found Carthage/Build/iOS/AppsFlyerTracker.framework.dSYM
*** Found Carthage/Build/iOS/DD7C4B3E-3D9D-35BD-8C6B-BE6CB26C78E3.bcsymbolmap
*** Found Carthage/Build/iOS/7DFB3419-B33A-36DC-8D66-A9BE695FA3A7.bcsymbolmap
*** Found Carthage/Build/iOS/E94665FA-ABD1-3D64-A7BC-EBC77B636542.bcsymbolmap
*** Found Carthage/Build/iOS/45DD0271-5EEA-3CB4-BC5D-BD18818B17C2.bcsymbolmap
*** Created AppsFlyerTracker.framework.zip
```

After that it uploads zip file to github.

**The problem is: `Carthage/Build` folder is empty.** 

## This is a upload process:

```
"https://uploads.github.com/repos/AppsFlyerSDK/AppsFlyerFWTestBuild/releases/5508179/assets"
curl -H "Authorization: token 1ca2a1481e59d972534434d8e7065323714b7c20" -H "Content-Type: multipart/form-data;" -H "Content-Type: application/zip" --data-binary @/Users/appsflyer/workspace/ios_sdk_framework_test/AppsFlyerLib/AppsFlyerTracker.framework.zip --fail --silent --show-error ""https://uploads.github.com/repos/AppsFlyerSDK/AppsFlyerFWTestBuild/releases/5508179/assets"?name=AppsFlyerTracker.framework.zip"

```

Maybe I miss some flag that should allow you to download this zip file?

**Comment by af-fess** [comment]
I found that if:
- I download `AppsFlyerTracker.framework.zip` file
- delete it from release
- upload the same file through drag&drop

Everything starts to work.

So the reason might be: Carthage don't have permissions to download zip file for some reason.

**Comment by af-fess** [comment]
@ikesyo I don't think it should be closed till you guys provide the reason of failure. Carthage doesn't provide any logs

**Comment by ikesyo** [comment]
I assume that the attached zip file through your `curl` command somehow missed `.framework` in its file name. Carthage reqires that the part is included in its file name and if it's not the case, falls back to regular checkout-and-build process.

**Comment by af-fess** [comment]
@ikesyo not at all. it has the same size as working copy. Please take a look on this: [https://github.com/AppsFlyerSDK/AppsFlyerFWTestBuild/releases/tag/4.6.492](https://github.com/AppsFlyerSDK/AppsFlyerFWTestBuild/releases/tag/4.6.492)  

`AppsFlyerTracker.framework.zip` contains everything to make it work. However it doesn't work.

**Comment by af-fess** [comment]
Please reopen this issue to avoid me to open the same issues with other title

**Comment by ikesyo** [comment]
> This is a upload process:

I understand now that the problem is the content type of your asset is `multipart/form-data` and not `application/zip` which Carthage expects.

https://api.github.com/repos/AppsFlyerSDK/AppsFlyerFWTestBuild/releases/tags/4.6.492
