### ISSUE TITLE
Idea: A Carthage Compatibility Badge

### ISSUE THREAD

**Issue by robb** [Carthage/Carthage#179]
As hinted at in #154, it would be cool to have a service that offers a _Works in Carthage_ badge similar to those snazzy build status badges you see:

![](https://camo.githubusercontent.com/b6ed46c7b1aaeb83b73c72f090f5215e095a96ec/68747470733a2f2f7472617669732d63692e6f72672f726f62622f417374657269736d2e7376673f6272616e63683d6d6173746572)

**Comment by jspahrsummers** [comment]
Since Carthage is available on Homebrew, which comes preinstalled in Travis CI VMs, the following sequence of commands should suffice to test any particular project:

```sh
brew update
brew install carthage
carthage bootstrap --no-build
carthage build --no-skip-current
```

I'm still not sure how this could be automated, but I'm pretty satisfied with the above as a solution for projects to validate _for themselves_ that they are (and remain) Carthage-compatible.

**Comment by 0xced** [comment]
I recently stumbled upon [Update Github Pages with Travis CI](http://words.steveklabnik.com/update-github-pages-with-travis-ci), maybe this could inspire someone to automate the process.

**Comment by sebbean** [comment]
Curious if Carthage could be used to pull in project dependencies of custom frameworks on CI platforms before running the project's tests.

Having an issue with building dependencies on Travis's server:
```
The following build commands failed:
	Check dependencies
(1 failure)
```

Assuming this is code sign related. see #235 specifically [this comment](https://github.com/Carthage/Carthage/issues/235#issuecomment-69409228)

**Comment by jspahrsummers** [comment]
I quite like the badge used in https://github.com/robocat/MiawKit/blob/64f77f2db0f057b9c796212a037fede6a97fef3a/README.md:

![](https://img.shields.io/badge/Carthage-compatible-4BC51D.svg?style=flat)

I think we should just mention that in the README, and call it a day. The rest of the work here is extremely :sunny::rainbow: stuff.
