### ISSUE TITLE
[0.20.0] `carthage update` builds the checked out version instead of the resolved version.

### ISSUE THREAD

**Issue by andersio** [Carthage/Carthage#1798]
* `carthage version`: 0.20.0
* `xcodebuild -version`: Xcode 8.2.1 (8C1002)
* Are you using `--no-build`? No.
* Are you using `--no-use-binaries`? No.
* Are you using `--use-submodules`? No.

**Cartfile**
```
github "ReactiveCocoa/ReactiveCocoa" ~> 5.0
```

**Carthage Output**
```
*** Fetching ReactiveCocoa
*** Fetching Quick
*** Fetching Nimble
*** Fetching ReactiveSwift
*** Fetching Result
*** Checking out Nimble at "v5.1.1"
*** Checking out Quick at "v0.10.0"
*** Downloading Result.framework binary at "3.1.0"
*** Downloading ReactiveSwift.framework binary at "1.1.0"
*** Downloading ReactiveCocoa.framework binary at "5.0.0"
*** xcodebuild output can be found in /var/folders/2f/tfw7zlgd5bv8jnthjc52xn000000gn/T/carthage-xcodebuild.WzkRZG.log
*** Building scheme "Nimble-macOS" in Nimble.xcodeproj
*** Building scheme "Quick-macOS" in Quick.xcworkspace
*** Building scheme "Result-Mac" in Result.xcodeproj
*** Building scheme "ReactiveSwift-macOS" in ReactiveSwift.xcworkspace
*** Building scheme "ReactiveCocoa-macOS" in ReactiveCocoa.xcworkspace
```

#### Issue
> *** Downloading ReactiveSwift.framework binary at "1.1.0"

Carthage has resolved a new version `1.1.0` over the existing `1.0.1`. But assuming I haven't done anything wrong on my end, what it built is actually the old version `1.0.1`.

Verified this by attempting to autocomplete new types introduced in ReactiveSwift 1.1.0, but got nothing.

**Comment by mdiep** [comment]
This was discussed a bit more in the ReactiveSwift slack.

ReactiveCocoa is configured to build with its submodule version of ReactiveSwift—which was 1.0.1 in this case. That's the correct and expected behavior. It caused an issue in this case because ReactiveSwift 1.1 wasn't semver compatible with 1.0.1 due to how some deprecations were handled.
