### ISSUE TITLE
[0.20.0] has a write permissions issue on second run.

### ISSUE THREAD

**Issue by marcvanolmen** [Carthage/Carthage#1808]
* `carthage version`: 0.20.0 was before on release 0.17.2
* `xcodebuild -version`: 8.2.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`? yes (but I think not related)

**Cart File**

for the dependency with the issue here below we specified it as:

```
git "git@....OUR SERVER..../Carpaccio-iOS.git"   "tvos_carthage"

```

Just upgraded from 0.17.2 to 0.20.0.

When I delete the Carthage folder, everything works fine on first run.

On second run:

When I try:

```
/usr/local/bin/carthage bootstrap --platform iOS --no-use-binaries --verbose
```

or I try

```
/usr/local/bin/carthage bootstrap --cache-builds --platform iOS --no-use-binaries --verbose
```

or I try

```
carthage bootstrap --cache-builds --platform iOS
````

I get the following output: 

**Carthage Output**
```
*** Checking out analytics-ios at "4bce7687c937bce0bf444e26dc8da0e90acd8d0a"
*** Checking out analytics-swift at "12714d377d565f437303d6e39b149768b5c93271"
*** Checking out Aspects at "d6e88120e0776ae68220323dc368033e61397e6a"
*** Checking out FXForms at "c7a40f2000c7c08a7dd987ec7666da1b11bf3fcf"
*** Checking out FXKeychain at "88cb592b4a274a2087b3bacf79db520e34e04ff7"
*** Checking out GoogleCast at "e43b881d0a4f3204d773fa27a92f012a9c634861"
*** Checking out GoogleVR at "a89d8f8f5860cdc9352fee101e498e123bb3255c"
*** Checking out JLRoutes at "069f4e2a08e1e038bd163be2609967f90d93d014"
*** Checking out Mantle at "8a7d38e40581e893599eeeb7088fbdf69d9ddd70"
*** Checking out Carpaccio-iOS at "58e6ead18aa26e6c39c5cd353afabb608331d155"
Failed to write to /Users/rtv/Jenkins_slave/workspace/RTV_iOS_Unit_Tests/Carthage/Checkouts/Carpaccio-iOS/Carthage/Checkouts/analytics-ios: Error Domain=NSCocoaErrorDomain Code=516 "The file “analytics-ios” couldn’t be saved in the folder “Checkouts” because a file with the same name already exists." UserInfo={NSFilePath=/Users/rtv/Jenkins_slave/workspace/RTV_iOS_Unit_Tests/Carthage/Checkouts/Carpaccio-iOS/Carthage/Checkouts/analytics-ios, NSUnderlyingError=0x7fa4d34817a0 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
```

* the version 0.17.2 was working fine. 
* I installed Carthage using the Carhage.pkg downloaded from the github release.

**Comment by marcvanolmen** [comment]
I cloned the project on computer and was able to get the exact breakpoint where it stopped and also the folder structure it had. I think there is an sub dependency issue ...

I included 2 screenshots.
![folder_at_moment_of_breakpoint](https://cloud.githubusercontent.com/assets/512457/23490396/7492f5e6-fec6-11e6-8691-bc62d19637b3.png)
![xcode_debugger_at_breakpoint](https://cloud.githubusercontent.com/assets/512457/23490397/74997ef2-fec6-11e6-832c-147edb1c705a.png)

**Comment by jdhealy** [comment]
Hey @marcvanolmen, thanks for submitting this and debugging.

This seems similar to #1794, but I'm hesitant to say it’s a true duplicate any of the conditions listed there.

If you’d like to patch in #1805 and give that a try, there's a decent chance it addresses the error you’re hitting. Thanks again!

**Comment by marcvanolmen** [comment]
I will try your patch later, but I think indeed this is the same problem. where a root level dependency is also a dependency of the sub dependency and then the Symbolic link is failing to create on second run.

**Comment by mhillebrand** [comment]
I'm having the same problem after upgrading to 0.20.0. :(

**Comment by mhillebrand** [comment]
Maybe this issue shouldn't have been closed?

**Comment by mdiep** [comment]
This can be closed. It's definitely the same issue as #1794.
