### ISSUE TITLE
Unable to build scheme for CocoaLumberjackSwift version using carthage

### ISSUE THREAD

**Issue by devIleaf** [Carthage/Carthage#1824]
* `carthage version`: 0.20.0

* `xcodebuild -version`: 1

* Are you using `--no-build`? 
I tried to call carthage update including `--no-build`. But that didn't work either.

* Are you using `--no-use-binaries`? 
I tried to call carthage update including `--no-use-binaries`. But that didn't work either.

* Are you using `--use-submodules`? 
I didn't use this.

* Are you using `--cache-builds`? 
I didn't use this.

**Cartfile**
```
[Cartfile.zip](https://github.com/Carthage/Carthage/files/826880/Cartfile.zip)

```

**Carthage Output**
```

LBTA-12181:GGDining harikrishnan$ carthage update
*** Fetching CocoaLumberjack
*** Fetching SlideMenuControllerSwift
*** Fetching NaOH
*** Checking out CocoaLumberjack at "3.1.0"
*** Checking out NaOH at "1.5"
*** Checking out SlideMenuControllerSwift at "3.0.1"
*** xcodebuild output can be found in /var/folders/_w/wqjl00fx7mngk6lq3mv0g9yr0000gn/T/carthage-xcodebuild.wE5Isz.log
*** Building scheme "CocoaLumberjack-iOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift-macOS" in Lumberjack.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/bobinlouis/Desktop/Projects/GGDining/Carthage/Checkouts/CocoaLumberjack/Framework/Lumberjack.xcworkspace -scheme CocoaLumberjackSwift-macOS -configuration Release -derivedDataPath /Users/bobinlouis/Library/Caches/org.carthage.CarthageKit/DerivedData/CocoaLumberjack/3.1.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/_w/wqjl00fx7mngk6lq3mv0g9yr0000gn/T/carthage-xcodebuild.wE5Isz.log

```

I was trying to use carthage to integrate CocoaLumberJack to my iOS Source code.But it is showing error provided above, when I am doing it via Terminal by giving the command "carthage update". I think it is happening because of the code mismatches between different swift versions. The error is happening when it is building scheme for CocoaLumberjackSwift.Please help me to sort out this problem.

The problem I am facing is in building scheme for CocoaLumberjackSwift. I changed "Use Legacy Swift Language Version" from 'NO' to 'Yes' in build settings of my Project & Targets.But that didn't work either.

**Comment by ikesyo** [comment]
Could you please check the actual Xcode build log first? That would indicate what the problem is.

> Please check the xcodebuild log for more details: /var/folders/_w/wqjl00fx7mngk6lq3mv0g9yr0000gn/T/carthage-xcodebuild.wE5Isz.log

**Comment by devIleaf** [comment]
=== BUILD TARGET CocoaLumberjackSwift-macOS OF PROJECT Lumberjack WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)


This is what I have seen in the log.

**Comment by ikesyo** [comment]
Couldn't reproduce it locally, the dependency built successfully.

> `xcodebuild -version`: 1

This is odd. You should have something like:

```
Xcode 8.2.1
Build version 8C1002
```

Are you sure that you are selecting Xcode 8's command line tools?

**Comment by devIleaf** [comment]
I am using Mac OS X Terminal for carthage update. In terminal, I moved to the source code directory and executed carthage update.


Xcode version : Version 8.2 (8C38)

**Comment by ikesyo** [comment]
See https://github.com/CocoaLumberjack/CocoaLumberjack/issues/848#issuecomment-284991010. This is not related to Carthage.
