### ISSUE TITLE
xcodebuild -list can hang when no schemes are shared

### ISSUE THREAD

**Issue by justinmakaila** [Carthage/Carthage#183]
I'm not sure if this is a flaw in the `SwiftyJSON` framework or in `Carthage`, but my project hangs on `carthage update`.

Cartfile

```
...
# Require SwiftyJSON
github "SwiftyJSON/SwiftyJSON" ~> 2.1.1
...
```

Output

```
*** Fetching Alamofire
*** Fetching SwiftyJSON
*** Fetching Swell
*** Checking out Alamofire at "1.1.1"
*** Checking out Swell at "1.0"
*** Checking out SwiftyJSON at "2.1.1"
*** xcodebuild output can be found in /var/folders/pj/0_h5pbg1787dcz5j24_rs36m0000gn/T/carthage-xcodebuild.L5T5LY.log
```

^ That's where it hangs

Process (as seen in `htop`)
![screen shot 2014-12-01 at 8 46 54 pm](https://cloud.githubusercontent.com/assets/1638996/5256748/3c59c00e-799b-11e4-91f0-657042c0c068.png)

It looks like it tries to build the `Example.xcodeproj` and hangs up there.

Any suggestions?

**Comment by aral** [comment]
@jspahrsummers Re: codesigning, I’m having SwiftyJSON fail for me because of the iOS target when I’m trying to use it in a Mac project. Is it worth (possible/feasible) to force only a Mac build and/or an iOS build?

**Comment by jspahrsummers** [comment]
@aral That'll be possible after https://github.com/Carthage/Carthage/issues/127 is implemented.
