### ISSUE TITLE
iTunes Store operation failed. No suitable application records were found. Verify your bundle identifier 'org.alamofire.Alamofire' is correct.

### ISSUE THREAD

**Issue by perryprog** [Carthage/Carthage#1834]
* `carthage version`: 0.20.1
* `xcodebuild -version`: Xcode 8.2.1
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "Alamofire/Alamofire" ~> 4.4
github "SwiftyJSON/SwiftyJSON"
github "evgenyneu/Cephalopod" ~> 1.0
github "TakeScoop/SwiftyButton"
github "ViccAlexander/Chameleon"
```

---

I'm very new to iOS app development. I am using Swift 3, and just switched from CocoaPods to Carthage. I've been trying to verify my Archive to upload to the App Store, but I get the error:

```
iTunes Store operation failed.
No suitable application records were found. Verify your bundle identifier 'org.alamofire.Alamofire' is correct.
```

I also got an error similar to this when using CocoaPods, which also was one of the reasons I'm switching to Carthage. I'm not 100% sure what I am doing, so it's probably some silly mistake.

GH Link: <https://github.com/germantownacademySOS/GASOS> (You won't be able to run — you need special hardware)

**EDIT:** I haven't pushed my Carthage version yet to GitHub. If you need me to, I can.
**EDIT 2:** Possible dupe of #188? I don't really understand everything that's going on their. Maybe someone could explain how to do this? (If that issue is even related?)

**Comment by ikesyo** [comment]
Looks unrelated to Carthage, closing.

**Comment by perryprog** [comment]
@ikesyo I guess it is :/

For anyone coming here, make sure your certificates are valid.
