### ISSUE TITLE
Why do I need to fetch the code? There should be a way to fetch just the .framework file

### ISSUE THREAD

**Issue by gagoyal** [Carthage/Carthage#1837]
* `carthage version`: 0.20.1
* `xcodebuild -version`: 8C1002
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`?  YES
* Are you using `--use-submodules`?  NO
* Are you using `--cache-builds`?  NO

**Cartfile**
github "AFNetworking/AFNetworking" ~> 3.0
<YOUR CARTFILE>
github "AFNetworking/AFNetworking" ~> 3.0

**Carthage Output**
```
<OUTPUT>

This fetches complete code base for AFNetworking. I am instead interested in only fetching the framework file that meets my version criteria.

**Comment by mdiep** [comment]
Carthage needs to fetch AFNetworking so it can discover its versions and dependencies.

**Comment by gagoyal** [comment]
I checked again. Its ok to fetch code to detect version and dependencies but when the compiled framework is attached already then why is it building again!! Is there a way to use the pre compiled framework that is fetched from Github? if yes then please specify the command and the way to check if it worked or not.

**Comment by dcaunt** [comment]
If you provide the `--no-use-binaries`, Carthage will not use binaries. If the flag is omitted and the binary is not compatible with the current version of Swift, Carthage will rebuild it.
