### ISSUE TITLE
OS X 10.12. brew install carthage error，report support for this pre-release version.

### ISSUE THREAD

**Issue by miuchen** [Carthage/Carthage#1838]
* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Cloning https://github.com/Carthage/Carthage.git
Updating /Users/test/Library/Caches/Homebrew/carthage--git
==> Checking out tag 0.17.2
Synchronizing submodule url for 'Carthage/Checkouts/Curry'
Synchronizing submodule url for 'Carthage/Checkouts/Runes'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Supporting Files/Configuration'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/ReactiveCocoa'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Argo'
Synchronizing submodule url for 'Carthage/Checkouts/Curry'
Synchronizing submodule url for 'Carthage/Checkouts/OHHTTPStubs'
Synchronizing submodule url for 'Carthage/Checkouts/ReactiveCocoa'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/Curry'
Synchronizing submodule url for 'Carthage/Checkouts/Runes'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
==> make prefix_install PREFIX=/usr/local/Cellar/carthage/0.17.2
Last 15 lines from /Users/test/Library/Logs/Homebrew/carthage/01.make:

** CLEAN FAILED **

The following build commands failed:
	Check dependencies
	Check dependencies
	Check dependencies
(3 failures)
make: *** [clean] Error 65
make: *** Waiting for unfinished jobs....
*** Bootstrapping Carthage/Checkouts/Commandant...
*** Bootstrapping Carthage/Checkouts/ReactiveCocoa...
*** Bootstrapping Carthage/Checkouts/ReactiveTask...
*** Bootstrapping Carthage/Checkouts/ReactiveCocoa...

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

**Comment by ikesyo** [comment]
Your homebrew is outdated. Please run `brew update` before `brew upgrade carthage`.

**Comment by asciifaceman** [comment]
I am receiving this and brew is perfectly up to date.
