### ISSUE TITLE
Task failed with exit code 65 

### ISSUE THREAD

**Issue by tariq235** [Carthage/Carthage#1843]
* `carthage version`: 0.20.1
* `xcodebuild -version`: Xcode 8.2.1
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? Yes
* Are you using `--cache-builds`? No

**Cartfile**
```
git "git@github.com:tariq235/Test.git" "master"
```

**Problem**
We have lot of small private libraries like Service (with Alamofire), Utilities (with some internal classes and some more utilities frameworks ) etc. So goal is if anyone create any sample project then he/she should be able to add internal private libraries using carthage
But I am always getting Build failed error. However I am able to build the framework.

For testing purpose i have created sample repositories. 

Test Project - https://github.com/tariq235/Test
 with Cartfile ```github "Alamofire/Alamofire" ~> 4.4```
This is working fine and I can import and access alamofire easily.

Then I have created a Sample project https://github.com/tariq235/Sample
 using cartfile ```git "git@github.com:tariq235/Test.git" "master"```

so when i am running carthage update i am getting following error —

```*** Fetching Test
*** Checking out Test at "f895a1ceb0684e4934676087b7ca616c4c0c536d"
*** xcodebuild output can be found in /var/folders/bt/j__yxjps32ng06sdbz3txqlh0000gn/T/carthage-xcodebuild.sOIJDm.log
*** Building scheme "Test" in Test.xcodeproj
Build Failed
    Task failed with exit code 65:

/usr/bin/xcrun xcodebuild -project /Volumes/Work/Sample/Sample/Carthage/Checkouts/Test/Test/Test.xcodeproj -scheme Test -configuration Release -derivedDataPath /Users/tariq/Library/Caches/org.carthage.CarthageKit/DerivedData/Test/f895a1ceb0684e4934676087b7ca616c4c0c536d -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/bt/j__yxjps32ng06sdbz3txqlh0000gn/T/carthage-xcodebuild.oYSuLW.log
```

Note - Strange part is that if I use this repo in my cartfile then it's working fine.
https://github.com/tariq235/KGNCache

**Comment by leon7pro** [comment]
Were you able to find a solution? I am having a similar issue.

**Comment by moiseslugoa** [comment]
i have the same issue, help please

**Comment by mdiep** [comment]
> ** Please check the xcodebuild log for more details:**

**Comment by alextakahashi** [comment]
I'm definitely still new at this, and I don't know where the xcodebuild log is located.  I'm looking for the location of 

`/var/folders/qb/82lnd6t96l5f72_jtzrkzd_4xd0_fn/T/carthage-xcodebuild.YB720J.log`

but I am not sure what directory it is telling me to look in?

**Comment by mdiep** [comment]
That's the full path where it's located.

You can do `open -e /var/folders/qb/82lnd6t96l5f72_jtzrkzd_4xd0_fn/T/carthage-xcodebuild.YB720J.log` in the terminal to view it.
