### ISSUE TITLE
Build Failed when run 'carthage update --platform iOS'

### ISSUE THREAD

**Issue by Ashxvi** [Carthage/Carthage#1848]
* `carthage version`: 
0.20.1
* `xcodebuild -version`: 
Xcode 8.2.1
Build version 8C1002

Are you using --no-build?
no
Are you using --no-use-binaries?
no
Are you using --use-submodules?
no
Are you using --cache-builds?
no

**Cartfile**
github "Ashxvi/watson-ios-sdk" "NLU-features"
**Carthage Output**

*** Fetching watson-ios-sdk
*** Checking out watson-ios-sdk at "c42fd816a8fbc36e616026aadae88bf0b0410a03"
*** xcodebuild output can be found in /var/folders/3q/p_hl8bf14m3g18wqy829n3lm0000gn/T/carthage-xcodebuild.H2QzyJ.log
*** Building scheme "RestKit" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "DocumentConversionV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "NaturalLanguageClassifierV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "ToneAnalyzerV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "DialogV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "RetrieveAndRankV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "RelationshipExtractionV1Beta" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "AlchemyDataNewsV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "LanguageTranslatorV2" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "PersonalityInsightsV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "TextToSpeechV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "SpeechToTextV1" in WatsonDeveloperCloud.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project "/Users/Desktop/WatsonAPI/Carthage/Checkouts/watson-ios-sdk/WatsonDeveloperCloud.xcodeproj" -scheme SpeechToTextV1 -configuration Release -derivedDataPath /Users/Library/Caches/org.carthage.CarthageKit/DerivedData/watson-ios-sdk/c42fd816a8fbc36e616026aadae88bf0b0410a03 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/3q/p_hl8bf14m3g18wqy829n3lm0000gn/T/carthage-xcodebuild.H2QzyJ.log

**Output of carthage-xcodebuild.H2QzyJ.log**

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by ikesyo** [comment]
Could you please take a deeper look at the log file by yourself first? The message just reports that the build failed, that is not the root failure reason.

> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details

**Comment by ikesyo** [comment]
Looks like https://github.com/watson-developer-cloud/swift-sdk/pull/593 broke the build. `SpeakerLabel.swift` is mistakenly added to `AlchemyDataNewsV1` target,  not to `SpeechToTextV1` target. Closing.
