### ISSUE TITLE
Issue in updating Carthage file - XCode8.2.1 & Swift3.0

### ISSUE THREAD

**Issue by Sakash** [Carthage/Carthage#1851]
I followed steps from here:
https://www.raywenderlich.com/109330/carthage-tutorial-getting-started

But on updating Alamofire version,its giving me error.

[carthage-xcodebuild.joop7I.log.zip](https://github.com/Carthage/Carthage/files/875069/carthage-xcodebuild.joop7I.log.zip)

* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 

**Cartfile**
github "Alamofire/Alamofire" == 2.0
github "SwiftyJSON/SwiftyJSON" ~> 2.3.0
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
*** Fetching Alamofire
*** Fetching SwiftyJSON
*** Skipped downloading Alamofire.framework binary due to the error:
	"Bad credentials"
*** Checking out Alamofire at "2.0.0"
*** Skipped downloading SwiftyJSON.framework binary due to the error:
	"Bad credentials"
*** Checking out SwiftyJSON at "2.4.0"
*** xcodebuild output can be found in /var/folders/5r/vsqvz8dj619cc31xk5zk7gpw0000gn/T/carthage-xcodebuild.joop7I.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/sakshijain/Desktop/extKey/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme "Alamofire iOS" -configuration Release -derivedDataPath /Users/sakshijain/Library/Caches/org.carthage.CarthageKit/DerivedData/Alamofire/2.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/5r/vsqvz8dj619cc31xk5zk7gpw0000gn/T/carthage-xcodebuild.joop7I.log

**Comment by dcaunt** [comment]
The tutorial is outdated, you need to use Alamofire version 4.0.0 or newer, and SwiftyJSON 3.0.0 or newer with Swift 3.

**Comment by Sakash** [comment]
am totally new in carthage.
As per your comments i have updated both versions,but still some error it throws
[carthage-xcodebuild.F0KgiR.log.zip](https://github.com/Carthage/Carthage/files/875172/carthage-xcodebuild.F0KgiR.log.zip)



Skipped downloading Alamofire.framework binary due to the error:
	"Bad credentials"
*** Checking out Alamofire at "4.4.0"
*** Skipped downloading SwiftyJSON.framework binary due to the error:
	"Bad credentials"
*** Checking out SwiftyJSON at "3.1.4"

**Comment by ikesyo** [comment]
That is just failing to access GitHub APIs for downloading prebuilt binaries which is similar to https://github.com/Carthage/Carthage/issues/1338. The actual builds ended successfully.
