### ISSUE TITLE
carthage with configurable Xcode(build) Path

### ISSUE THREAD

**Issue by schmichri** [Carthage/Carthage#1852]
Hi all, 

we are facing the issue that we have multiple Xcode.app installed on our headless buildservers.
Some of the projects we build on Xcode8.2.1 and the others already on 8.3 (will become more soon). 

I know that i can switch with 'sudo xcode-select -s <path>' always the Xcode.app but this helperscripts are always a bit nasty.

Do you see a way to implement the behavior to carthage to give this as parameter? 
e.g. **carthage bootstrap -platform ios -xcodepath /Applications/xcode/8.3/Xcode.app**
or maybe in "Cartfile"

**Comment by ikesyo** [comment]
You can use `DEVELOPER_DIR` environment variable for that purpose. See `man xcode-select` for the details.

**Comment by schmichri** [comment]
If I do it outside of carthage I can use xcodeselect as well. DEVELOPER_DIR  doesn't sound like an option. Sorry

**Comment by ikesyo** [comment]
> If I do it outside of carthage I can use xcodeselect as well. DEVELOPER_DIR doesn't sound like an option. Sorry

Could you please elaborate this? I'm not sure what you worry about.

I'm just saying you can do something like this: `DEVELOPER_DIR=/Applications/xcode/8.3/Xcode.app carthage update`

**Comment by schmichri** [comment]
Okay I see. This might be a durable way of using it.
