### ISSUE TITLE
Versioning not quite right i think

### ISSUE THREAD

**Issue by grangej** [Carthage/Carthage#1855]
* `carthage version`: 20.1

When using major.minor.patch in your cartfile I would expect to only get patch levels not minor updates, but if the tags are not all major.minor.patch then it will pick up the next minor version.

Cartfile: ~> 2.0.0

Git Repo has the following Tags

...
v2.0.0
v2.0.1    <------ I expect this tag to be pulled
v2.1  <----- Instead this tag is pulled

**Comment by mdiep** [comment]
`~> 2.0.0` should always pull 2.1—whether it's tagged as `v2.1` or `v2.1.0`.

2.1 is compatible with 2.0.*, so there's no reason not to.

**Comment by grangej** [comment]
I see, thanks for the clarification.

**Comment by grangej** [comment]
This is confusing in the docs then: 

> According to SemVer, any 0.x.y release may completely break the exported API, so it's not safe to consider them compatible with one another. Only patch versions are compatible under 0.x, meaning 0.1.1 is compatible with 0.1.2, but not 0.2. This isn't according to the SemVer spec but keeps ~> useful for 0.x.y versions.

If I read this it says minor version should be respected.

**Comment by BobElDevil** [comment]
That part of the documentation is specific to 0.* versions. It's in reference to this part of the semver spec
>Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable. 
The Carthage documentation is pointing out that carthage deviates from that a little by assuming _some_ compatibility via minor versions. But this applies only when the major version is 0.

**Comment by grangej** [comment]
Got it.
