### ISSUE TITLE
Support for custom Log paths

### ISSUE THREAD

**Issue by aaroncrespo** [Carthage/Carthage#1860]
* `carthage version`:  0.20.1
* `xcodebuild -version`:  Xcode 8.3 Build version 8E162

We are looking to capture build logs as part of our Artifacts. It would be nice if carthage supported a `--log-path` option on commands that generate a log.
As you can see in the Screenshot it's tricky to reconcile which builds belong to what build on the box. 

<img width="359" alt="screen shot 2017-03-30 at 2 19 22 pm" src="https://cloud.githubusercontent.com/assets/431662/24519845/52d71f8c-1554-11e7-8fb9-76fd8dc6f9db.png">

A workaround for us at the moment is to nuke all the old logs. Or we could capture the last line of `carthage build` and grab it from there.

**Comment by mdiep** [comment]
I think that's a great idea. Pull requests welcome! ☺️
