### ISSUE TITLE
Carthage builds dependency even if binary dependency is available for proper version of Swift

### ISSUE THREAD

**Issue by bsarrazin** [Carthage/Carthage#1864]
* `carthage version`: 0.20.1
* `xcodebuild -version`: Xcode 8.2.1 Build version 8C1002
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "[redacted]/ios-[redacted]Kit"
github "[redacted]/ios-[redacted]Kit"
github "realm/realm-cocoa"
github "Swinject/Swinject"
```

**Carthage Output**
```
$ carthage bootstrap
*** Downloading ios-[redacted]Kit.framework binary at "1.11.0"
*** Downloading realm-cocoa.framework binary at "v2.5.0"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.1 and the local version is 3.0.2."
*** Checking out realm-cocoa at "v2.5.0"
*** Downloading RxSwift.framework binary at "Hashimoto.1"
*** Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.1 and the local version is 3.0.2."
*** Checking out RxSwift at "3.3.1"
*** Downloading ios-[redacted]Kit.framework binary at "0.0.1"
*** Checking out Swinject at "2.0.0"
*** xcodebuild output can be found in /var/folders/fm/5l94j7_d65d1vylgk2fs9v900000gn/T/carthage-xcodebuild.VYoruV.log
*** Building scheme "Realm" in Realm.xcworkspace
^C
```

<img width="1002" alt="pasted_image_2017-03-31__10_42_am" src="https://cloud.githubusercontent.com/assets/1077441/24555559/9c379d18-15ff-11e7-9bc9-fea0eec66ca4.png">

<img width="621" alt="pasted_image_2017-03-31__10_46_am" src="https://cloud.githubusercontent.com/assets/1077441/24555489/6217ed18-15ff-11e7-95c7-55300c2c485d.png">

**Comment by ikesyo** [comment]
See the `Incompatible Swift version` message. This is an expected behavior.

**Comment by bsarrazin** [comment]
@ikesyo but the binary _does contain_ the valid swift version binary. Why is Carthage not using the 3.0.2 version?

**Comment by mdiep** [comment]
Carthage doesn't currently have logic to select a version based on the Swift version.

**Comment by ikesyo** [comment]
> the binary does contain the valid swift version binary

I'm not sure what does it mean 🤔 The binaries are built with Swift 3.1 and you are using Swift 3.0.2. I assume that there is no binary compatibility between Swift 3.1 and Swift 3.0. So how does this work?

**Comment by ikesyo** [comment]
Hm I got it, realm-swift-2.5.0.zip of https://github.com/realm/realm-cocoa/releases/tag/v2.5.0 actually contains binaries for multiple Swift versions, but Carthage uses `Carthage.framework.zip` not the former by convention.

**Comment by akolov** [comment]
I'm having the same issue. Now with Realm 2.5.1 binary contained in the `Carthage.framework.zip` and built with Swift 3.1:
```
✗ carthage update --platform iOS stylight-ios-lib-2
*** Cloning TSMessages
*** Cloning Bureaucracy
*** Cloning CircularGallery
*** Cloning ios_sdk
*** Cloning AlamofireImage
*** Cloning Reachability.swift
*** Cloning UIViewLayoutHelper
*** Cloning HexColors
*** Cloning YouTubePlayer
*** Cloning stylight-ios-lib-2
*** Cloning Alamofire
*** Cloning realm-cocoa
*** Checking out Alamofire at "4.4.0"
*** Checking out HexColors at "4.0.0"
*** Downloading realm-cocoa.framework binary at "v2.5.1"
*** Downloading stylight-ios-lib-2.framework binary at "4.3.6"
*** xcodebuild output can be found in /var/folders/9p/c9tml4dj3kvdxd3yvvt5v9yr0000gn/T/carthage-xcodebuild.HnKv8c.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "HexColors" in HexColors.xcodeproj
*** Building scheme "Realm" in Realm.xcworkspace```

Note how Carthage is Downloading `realm-cocoa.framework` binary as well as our internal `stylight-ios-lib-2.framework`. Both have Swift 3.1 binaries, and both are rebuilt from the source despite this.

**Comment by ikesyo** [comment]
> Both have Swift 3.1 binaries, and both are rebuilt from the source despite this.

That should mean that you are using Xcode 8.2 / Swift 3.0.2.

**Comment by akolov** [comment]
Sorry, but no Xcode 8.3 and Swift 3.1
![screen shot 2017-04-06 at 12 49 07 pm](https://cloud.githubusercontent.com/assets/142354/24750802/7f4cd44e-1ac7-11e7-87e6-b54408c20113.png)

**Comment by ikesyo** [comment]
Another possibility is you are hitting the rate limit of GitHub API so Carthage falls back to regular checkout and build.

**Comment by BobElDevil** [comment]
You may be hitting #1836. Carthage builds the 'checkout' folder if present, regardless of whether it downloaded a binary (bad behavior, but that's how it is). So if you had previously checked out Realm, then later got a  binary download for it, it'll still do the source build. A workaround is to remove the Checkouts/<dependenty> folder

**Comment by ikesyo** [comment]
We will not support `realm-swift-x.y.z.zip` which contains multiple Swift version frameworks.

Another possibility is something similar to Swift Package Manager's ["Handling version-specific logic"](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#handling-version-specific-logic).
