### ISSUE TITLE
Carthage fatigue

### ISSUE THREAD

**Issue by groue** [Carthage/Carthage#1867]
* `carthage version`: 0.20.1
* `xcodebuild -version`: Xcode 8.3, Build version 8E162
* Are you using `--no-build`?  NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO

**Cartfile**

I'm running `carthage build --no-skip-current` so that I can check if Carthage supports my library. It does not.

**Carthage Output**

```
*** xcodebuild output can be found in /var/folders/5p/dm0blh350879m1kd0d98vbnr0000gn/T/carthage-xcodebuild.kh3mXm.log
*** Building scheme "GRDBWatchOS" in GRDB.xcworkspace
*** Building scheme "GRDBOSX" in GRDB.xcworkspace
*** Building scheme "GRDBCipheriOS" in GRDB.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/groue/Documents/git/groue/GRDB.swift/GRDB.xcworkspace -scheme GRDBCipheriOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/5p/dm0blh350879m1kd0d98vbnr0000gn/T/carthage-xcodebuild.kh3mXm.log
```

Of course the project itself compiles. Outside of Carthage.

I'm a library developer. I want to be nice to my users, and let them install [GRDB](http://github.com/groue/GRDB.swift) with Carthage. Currently working on [this branch](https://github.com/groue/GRDB.swift/tree/modulemapRefactor).

But I have a big Carthage fatigue. I just can't make it work. I've spent hours tweaking my stuff to accommodate your tool, and I'm wasted. Maybe you can help:

First problem: Carthage insists on building all shared schemes. But one can share schemes for others reasons than exposing them to Carthage users. For exemple, GRDB share schemes so that it can run tests.

Second problem: some schemes that build in Xcode won't build with Carthage. So now some schemes that were shared for some Carthage-unrelated reason have Carthage fail to build the schemes it should build. There is still no way to tell Carthage which scheme to build, which at least cold be a workaround. **The `--platform` option is not enough.**

Maybe you need some context: GRDB is an Swift wrapper for SQLite. It works with the system-provided SQLite, or a custom build of SQLite, or SQLCipher (which is an encrypted variant of SQLite). On three platforms (macOS, iOS, watchOS). Count: that makes a lot of frameworks, and SQLite has a tricky building process. That tricky build process is handled perfectly by Xcode. It is not handled perfectly by Carthage.

I don't expect you to help debugging those errors - unless you have a lot of time to spend. I'm requesting you to **let application developers tell Carthage which scheme they want to build**. I'd update my documentation accordingly, once and for good, this would prevent extra schemes that Carthage is unable to build to block the whole process, and I'd never hear about Carthage issues again. Is it too much to ask?

**Comment by mdiep** [comment]
Hello @groue!

I'd love to help. Sorry that this has been a frustrating experience for you. I totally get that. I've been there. ☺️ 

> First problem: Carthage insists on building all shared schemes. But one can share schemes for others reasons than exposing them to Carthage users. For exemple, GRDB share schemes so that it can run tests.

Carthage builds any scheme that (1) is shared and (2) builds a dynamic framework target. `GRDBCipheriOS` is the framework that's failing to build. Is that a framework that your users will want to use?

> Second problem: some schemes that build in Xcode won't build with Carthage. So now some schemes that were shared for some Carthage-unrelated reason have Carthage fail to build the schemes it should build. There is still no way to tell Carthage which scheme to build, which at least cold be a workaround. The --platform option is not enough.

`GRDBCipheriOS` is failing to build. This isn't entirely Carthage specific. Carthage builds the project with `xcodebuild`. (You can see the command itself if you look inside the log file that Carthage prints to the console.)

In this case building with `xcodebuild` as Carthage does also produces an error:

```
/usr/bin/xcrun xcodebuild -workspace /Users/mdiep/Downloads/tmp/Carthage/Checkouts/GRDB.swift/GRDB.xcworkspace -scheme GRDBCipheriOS -configuration Release -derivedDataPath /Users/mdiep/Library/Caches/org.carthage.CarthageKit/DerivedData/GRDB.swift/311ad6b94072fb020654d8d7c24454b937842348 -sdk iphoneos BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
```

The troublesome bit seems to be `-sdk iphoneos`. Any idea why that's a problem here?

It looks like SQLCipher only gets built for x86. When Carthage specifies the SDK, the build fails because `configure` fails for arm. (It appears to need the `--host` flag, as it complains about, to make it a cross-compiled build.)

**Comment by groue** [comment]
Hello @mdiep 

> Carthage builds any scheme that (1) is shared and (2) builds a dynamic framework target. `GRDBCipheriOS` is the framework that's failing to build. Is that a framework that your users will want to use?

`GRDBCipheriOS` is indeed a framework that Carthage can't build. It is also a framework that users could indeed want to use.

But it is not shared because I want users to be able to use it with Carthage. It is shared because automated testing in a [Makefile](https://github.com/groue/GRDB.swift/blob/50e50e82e17689cd77963df896c465fc502b7722/Makefile#L109) with `xcodebuild` requires a shared scheme.

The fact that Carthage can't build this framework is something I wish I could live with. I today document other techniques than Carthage so that users can add this framework to their app. Unfortunately, Carthage today *requires* all shared framework to be buildable with Carthage. If one framework won't compile with Carthage, Carthage won't build other, legitimate, frameworks. And there is no way to tell Carthage which framework to build (and avoid failing ones).

> `GRDBCipheriOS` is failing to build. This isn't entirely Carthage specific. Carthage builds the project with xcodebuild. (You can see the command itself if you look inside the log file that Carthage prints to the console.)

Excuse me: it is totally Carthage-specific. The failing `xcodebuild` command is generated by Carthage. Xcode is able to build this framework.

> In this case building with xcodebuild as Carthage does also produces an error [...] The troublesome bit seems to be `-sdk iphoneos`. Any idea why that's a problem here?

I only have a very tiny idea, which is that the targeted sdk is not persistent across the full building process: `GRDBCipheriOS` depends on an Xcode project that ships with [SQLCipher](http://github.com/sqlcipher/sqlcipher), and contains sdk-agnostics targets. The `xcodebuild` command generated by Carthage eventually loses its way, and fails building the whole stuff.

Debugging this issue is immensely difficult, time consuming, frustrating, and to say it shortly, beyond both my skills and patience.

Unfortunately, this problem is *blocking* because of Carthage insistance at building every shared scheme that builds a dynamic framework target.

Carthage fails as soon as it fails building one scheme. This means that other schemes that it could build are *not* built.

You see? I won't stop sharing `GRDBCipheriOS` because of Carthage. This would turn the testing process of GRDB into a manual chore. Has Carthage any right to tell me how my time has to be spent, or telling me how I'm supposed to organize my public schemes? *Is it true that I MUST have `GRDBCipheriOS` support Carthage so that Carthage can reliably build other frameworks?* Personally, I prefer saying that today, Carthage doesn't support GRDB, rather than GRDB doesn't support Carthage.

Hence this issue, and its title. I just wish I could tell users how to build specific schemes with Carthage, and call it a day. That would be so simple.

**Comment by mdiep** [comment]
> I just wish I could tell users how to build specific schemes with Carthage, and call it a day. That would be so simple.

That would be simple for _you_. But it hoists a number of issues onto Carthage, its developers, and its users.

#1227 is already tracking the request to skip some schemes. But I don't think that's likely to happen anytime soon. Sorry.

**Comment by groue** [comment]
> That would be simple for you

I understand that. Really. I at least hope that the context described here shows that #1227 is not only a matter of convenience, as you may see it.
