### ISSUE TITLE
How to make Carthage only builds one scheme from a repo?

### ISSUE THREAD

**Issue by edopelawi** [Carthage/Carthage#1874]
* `carthage version`: 0.20.1
* `xcodebuild -version`: Xcode 7.3.1, Build version 7D1014
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  yes

**Cartfile**
```
github "Moya/Moya" "5.0.0"
github "RxSwift/RxSwift" "2.6.0"
```

**Carthage Output**
(when errors)
```
*** Building scheme "RxMoya iOS" in Moya.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/ricardopramanasuranta/Documents/Projects/bluebird_mybb_client_ios/Carthage/Checkouts/Moya/Moya.xcodeproj -scheme "RxMoya iOS" -configuration Release -derivedDataPath /Users/ricardopramanasuranta/Library/Caches/org.carthage.CarthageKit/DerivedData/Moya/5.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
```

I'm currently handling a legacy project, and wanted to move from Cocoapods to Carthage. I got a dependency conflict between Moya 5.0.0 and RxSwift 2.6.0. Carthage checks out and builds every scheme in Moya, which includes RxMoya that depends on RxSwift 2.0.0-beta.2. This caused conflict - either the RxMoya build fails (because of RxSwift 2.6.0) or the carthage build succeeds, but the project can't be built because of syntax difference.

Any help is greatly appreciated. Thanks in advance!

**Comment by mdiep** [comment]
It's not currently possible to build only one scheme from a repo. Sorry! #1227

**Comment by edopelawi** [comment]
Welp, okay then. Thanks for the answer!
