### ISSUE TITLE
How to use Carthage to implement subspec like Cocoapods

### ISSUE THREAD

**Issue by zixun** [Carthage/Carthage#1876]
I have a framework named `A`, and a sub framework named `A-Core` in it, `A` is dependented on `A-Core`, they are in the same repo. 

in Cocoapods, just create a subspec, and how to write the `Cartfile` in Carthage at this case

**Comment by mdiep** [comment]
Carthage doesn't have subspecs. Carthage will build all the frameworks in the repo.
