### ISSUE TITLE
Module compiled with Swift 3.0.1 cannot be imported in Swift 3.1:

### ISSUE THREAD

**Issue by rowland-smith** [Carthage/Carthage#1878]
* `carthage version`:  0.20.1
* `xcodebuild -version`: Xcode 8.3.1 Build version 8E1000a
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "FutureKit/FutureKit.git"
github "artman/Signals"
github "OneSignal/OneSignal-iOS-SDK"
github "bignerdranch/Freddy"
github "envoy/Embassy.git"
github "envoy/Ambassador.git"
github "rhodgkins/SwiftHTTPStatusCodes.git"
```

**Carthage Output**
```
*** No Cartfile.resolved found, updating dependencies
*** Fetching OneSignal-iOS-SDK
*** Fetching SwiftHTTPStatusCodes
*** Fetching Ambassador
*** Fetching Embassy
*** Fetching Freddy
*** Fetching FutureKit
*** Fetching Signals
*** Checking out Embassy at "v3.1.0"
*** Checking out Ambassador at "v3.0.0"
*** Checking out Freddy at "3.0.2"
*** Checking out FutureKit at "3.0.0"
*** Checking out OneSignal-iOS-SDK at "2.5.2"
*** Checking out Signals at "4.0.1"
*** Checking out SwiftHTTPStatusCodes at "3.1.1"
*** xcodebuild output can be found in /var/folders/1q/w5qxkj791mx5hf3382mhggb40000gn/T/carthage-xcodebuild.rvVDkW.log
*** Building scheme "Embassy-iOS" in Embassy.xcworkspace
*** Building scheme "Ambassador-iOS" in Ambassador.xcworkspace
*** Building scheme "MobileFreddy" in Freddy.xcodeproj
*** Building scheme "FutureKit iOS" in FutureKit.xcworkspace
*** Building scheme "OneSignal-Dynamic" in OneSignalSDK.xcworkspace
*** Building scheme "Signals iOS" in Signals.xcodeproj
*** Building scheme "HTTPStatusCodes" in HTTPStatusCodes.xcodeproj
```

I only have one version of Xcode installed on my system (iMac 5K). I'm building my project with Swift 3.1. 

Carthage builds my dependencies, however I get the following error when I try to build my project in Xcode:

Showing Recent Issues
/Users/rowland/Projects/PeaceKeeper/PeaceKeeper/API/HypertextResponse.swift:10:8: Module compiled with Swift 3.0.1 cannot be imported in Swift 3.1: /Users/rowland/Projects/PeaceKeeper/PeaceKeeper/Freddy.framework/Modules/Freddy.swiftmodule/arm64.swiftmodule

I have tried the following:

    - cleaned my project
    - option cleaned my project
    - deleted the derived-data directory

It appears that carthage is using the Swift 3.1 compiler to build my dependencies:

    cat Carthage/Build/iOS/Freddy.framework/Headers/Freddy-Swift.h 
    // Generated by Apple Swift version 3.1 (swiftlang-802.0.51 clang-802.0.41)

Thanks in advance,
Rowland

**Comment by ikesyo** [comment]
> /Users/rowland/Projects/PeaceKeeper/PeaceKeeper/Freddy.framework/Modules/Freddy.swiftmodule/arm64.swiftmodule

Seems that you don't use `Carthage/Build/Freddy/Freddy.framework`. That should be the problem.

I assume that you are using `Freddy.framework` which was built with Swift 3.0.1 and was checkd in to your project's git repository.

**Comment by rowland-smith** [comment]
Thank you so much for catching that. Indeed, the Freddy.framework was copied into my project directory and was not left in Carthage/Build/iOS and referenced from there. All is working now.

Again, thank you,
Rowland Smith

**Comment by rowland-smith** [comment]
Thank you very much for catching that - I did indeed have an old copy of Freddy in the root of my project and it was being referenced instead of the recently built version in Carthage/Build/iOS/
