### ISSUE TITLE
iOS frameworks built with Carthage cannot be submitted to the App Store

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#188]
From @soffes in https://github.com/Carthage/Carthage/issues/174#issuecomment-65187702:

> I've been dragging the projects into my project and setting up dependencies in Xcode for building. You can't submit iOS frameworks with x86. Couldn't find a way to do a "release build" in carthage so that was my work around.

IOW, our fat binary is inadmissable to the App Store, apparently.

**Comment by dreambt** [comment]
Not work.
Must execute above, why?

    lipo -remove i386 Carthage/Build/iOS/Base32.framework/Base32 -output Carthage/Build/iOS/Base32.framework/Base32
    lipo -remove x86_64 Carthage/Build/iOS/Base32.framework/Base32 -output Carthage/Build/iOS/Base32.framework/Base32

**Comment by jspahrsummers** [comment]
@dreambt Please open a new issue, and detail _exactly what you've tried_, and what's not working about it. We can't help unless you provide more information.

**Comment by ricardolpd** [comment]
hi guys, i am looking into using carthage for a set of frameworks i am building for my employee, is this issue still an issue?

**Comment by ikesyo** [comment]
> is this issue still an issue?

I think so. At the time of Xcode 7 GM, it might change or not. :sweat_smile:

**Comment by pietbrauer** [comment]
It is not an issue anymore (that's why this issue was closed), I am successfully submitting apps that contain carthage built frameworks to the AppStore.

**Comment by ricardolpd** [comment]
@ikesyo so how do you guys work around it? build two framewoks a fat one and a non-fat one and switching with a script??

**Comment by ikesyo** [comment]
@ricardolpd Did you check [the README section](https://github.com/Carthage/Carthage/blob/5fd867c4895b4f59d70181dec169a1644f4430e3/README.md#if-youre-building-for-ios)?

**Comment by ikesyo** [comment]
> I think so.

This is about Xcode/App Store submission bug to which @jspahrsummers referred above: https://github.com/Carthage/Carthage/issues/188#issuecomment-66523227

**Comment by ricardolpd** [comment]
ikesyo, sorry i never got around reading the section of the readme file about the script. thanks it makes sense now

**Comment by ikesyo** [comment]
No worries!

**Comment by adammendoza** [comment]
I'm using Carthage for AFNetwork and I also have to uncheck Include app symbols for your application to receive symbolicated crash logs from Apple.

**Comment by izouxv** [comment]
add shell after copy framework section
cartool strip -v $EXPANDED_CODE_SIGN_IDENTITY -a $METAL_LIBRARY_OUTPUT_DIR -os $PLATFORM_NAME
this will remove all debug info
cartool at github.com/izouxv/cartool
