### ISSUE TITLE
Carthage issue with binary source

### ISSUE THREAD

**Issue by buscarini** [Carthage/Carthage#1880]
* `carthage version`: 
0.20.1
* `xcodebuild -version`: 
Xcode 8.3
Build version 8E162
* Are you using `--no-build`? 
no
* Are you using `--no-use-binaries`? 
no
* Are you using `--use-submodules`? 
no
* Are you using `--cache-builds`? 
no

**Cartfile**
```
binary "https://internal_url/PackageName.json" ~> 0.6.0
```

**Carthage Output**
```
No available version for binary "https://internal_url/PackageName.json" satisfies the requirement: ~> 0.6.0
```

I have some internal frameworks prepackaged as binaries. I just updated one of the packages from version 0.5.2 to version 0.6.0. I checked and the json is correct, and the version is published in the correct url, but carthage won't pick it. This is the command I'm running:

```
carthage update PackageName --platform ios --verbose
```

I also tried cleaning the cache but no dice:

```
rm -rf ~/Library/Caches/org.carthage.CarthageKit
```

**Comment by mdiep** [comment]
Could you share a copy of the json file?

**Comment by buscarini** [comment]
I'm not sure if I'm allowed to share the real url, but there's not much to it:

```
{
    "0.6.0": "https://internal_url/0.6.0/ListModel.framework.zip"
}
```

The zip url works, and carthage was working before, when the version was 0.5.2.

**Comment by mdiep** [comment]
That's odd. 🤔 

Have you tried reproducing on another computer?

**Comment by rereveneq** [comment]
Odd

**Comment by buscarini** [comment]
I didn't try on a different computer, but I tried yesterday and it worked. Today I made a new release (0.6.1) and it's not working again. I think if I restart the computer then some kind of cache gets cleared and Carthage detects the new version, but otherwise it's not picking the changes.

This should be relatively easy to reproduce: make a binary framework with any version, call carthage update, then add a new version, update the Cartfile and try carthage update again.

**Comment by buscarini** [comment]
It seems I was removing the wrong cache files. I solved it by doing this:

`rm -rf ~/Library/Caches/carthage`

**Comment by mdiep** [comment]
That probably means that we're caching them to the wrong directory. Thanks for following up!

**Comment by pvegh** [comment]
This bug is still there.
I just solved it by deleting ~/Library/Caches/carthage

**Comment by michaelmcguire** [comment]
I tried to recreate this and could not.  But looking at `~/Library/Caches/carthage`, I noticed the URL caching database is there.  My guess is that the web servers serving up the binary framework definition file are instructing `carthage` to cache the response and that is why it is not picking up the update.

We could turn off caching at the `URLSession` when downloading the `.json` definition, but seems like the real solution is for people to make sure their servers are properly configured when it comes to caching.

**Comment by nidegen** [comment]
still there. just happened to me, `rm -rf ~/Library/Caches/carthage` solved it, after not solving it the first time i used it..🤨

**Comment by ikesyo** [comment]
That ahould be `URLSession`s cache, so you should revisit your server's `Cache-Control` header handling.

- https://developer.apple.com/documentation/foundation/url_loading_system
- https://developer.apple.com/documentation/foundation/url_loading_system/accessing_cached_data
- https://developer.apple.com/documentation/foundation/nsurlrequest/cachepolicy/useprotocolcachepolicy

**Comment by nidegen** [comment]
ah, that sounds more like it, good point!

**Comment by nidegen** [comment]
Error handling tip: Open the json URL in Safari, I think this will help refresh the cache

**Comment by badboy** [comment]
This is still happening to me on macOS Catalina, Carthage v0.34.0.
