### ISSUE TITLE
Crash after adding invalid github entry

### ISSUE THREAD

**Issue by catnapgames** [Carthage/Carthage#1882]
I got a crash when running carthage update for a Cartfile that looked like this:

    github "https://github.com/rs/SDWebImage"

The exception and crash dump that followed were not informative. After realizing my mistake I edited the entry to just the author/repo format and it worked. It would be nice to check for mistakes like this and warn the user.

**Comment by ikesyo** [comment]
This is a duplicate of https://github.com/Carthage/Carthage/issues/1869. Please update your Carthage installation.
