### ISSUE TITLE
Do I need to add framework dependencies to my project?

### ISSUE THREAD

**Issue by dannymout** [Carthage/Carthage#1886]
Example: Let's say I've added a Cartfile to my project, and I run `carthage update`. Carthage gets the frameworks that I specified in the Cartfile. Now, I need to drag the framework to my Xcode project.

Question: Moya(a framework) has two dependencies which also go to the build folder, Alamofire and Result. Do I need to add the dependencies(Alamofire, Result) to my project as well?

**Comment by mdiep** [comment]
> Do I need to add the dependencies(Alamofire, Result) to my project as well?

Yes.
