### ISSUE TITLE
Dependency "MaskedLabel" has no shared framework schemes

### ISSUE THREAD

**Issue by darincon** [Carthage/Carthage#1890]
* `carthage version`: 0.20.1
* `xcodebuild -version`: Xcode 8.3.1 Build version 8E1000a
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "darincon/MaskedLabel" ~> 0.9.1
```

**Carthage Output**
```
*** Fetching MaskedLabel
*** Checking out MaskedLabel at "0.9.1"
*** xcodebuild output can be found in /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.7usTdB.log
*** Skipped building MaskedLabel due to the error:
Dependency "MaskedLabel" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/darincon/MaskedLabel/issues/new
```

I already set the MaskedLabel scheme to be shared, the scheme was uploaded to the repo, and `xcodebuild -scheme MaskedLabel -project MaskedLabel.xcodeproj build` succeeded.

If I run `carthage build --no-skip-current`, I get the following output:

```
*** xcodebuild output can be found in /var/folders/xg/ngtfmvjs2lb5c3tv42fcz09w000gnw/T/carthage-xcodebuild.m5oUo8.log
*** Skipped building MaskedLabel due to the error:
Dependency "MaskedLabel" has no shared framework schemes
```

**Comment by ikesyo** [comment]
Looks like what you shared is a scheme for application target. Please make it sure that you have a framework target and create / share a scheme for that target.

**Comment by darincon** [comment]
It's working now. Thank you for your help

**Comment by rezakhmf** [comment]
@ikesyo/ @darincon  I've updated my project cocoa pods to carthage but I have a problem for some old libraries e.g.  which are just available through pods. I have tried to clone them to my local but I don't know how "Please make it sure that you have a framework target and create/share a scheme for that target.". Could you please help me for this? thanks
