### ISSUE TITLE
assets from Checkouts folder are embeded in app

### ISSUE THREAD

**Issue by vhosune** [Carthage/Carthage#1894]
* `carthage version`: 0.20.1
* `xcodebuild -version`: 8.3.2
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "facebook/facebook-ios-sdk"
```

**Carthage Output**
```
```

sdk-version-4.21.0

When I compile for release I get some assets from the facebook sdk that are not supposed to be in the framework, they are in the Carthage/Checkouts/facebook-ios-sdk 
(for exemple I pin pointed some assets come from the sample/Catalog/Assets.xcassets folder)

When I delete the Carthage/Checkouts folder after build they do not get embeded in my app (expected behaviour)

**Comment by mdiep** [comment]
> When I compile for release I get some assets from the facebook sdk that are not supposed to be in the framework, they are in the Carthage/Checkouts/facebook-ios-sdk

`Carthage/Checkouts/facebook-ios-sdk` is just the contents of that repo.

You must have configured your project to copy the files into your app.

**Comment by vhosune** [comment]
ok turns out it is cocoapods script looking for other xcassets in the project folder
