### ISSUE TITLE
Checkouts Directory Not Cleaned

### ISSUE THREAD

**Issue by kndl** [Carthage/Carthage#1895]
* `carthage version`: 0.20.1
* `xcodebuild -version`: 
Xcode 8.3.1
Build version 8E1000a
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

**Cartfile**
```
github "ruslanskorb/RSKImageCropper"
```

**Carthage Output**
```
*** xcodebuild output can be found in /var/folders/09/4mczyqvj73v002m058rc7lq800007q/T/carthage-xcodebuild.7IDMRP.log
*** Building scheme "RSKImageCropper" in RSKImageCropper.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/Shared/Jenkins/Desktop/polymer-ios/Carthage/Checkouts/RSKImageCropper/RSKImageCropper.xcworkspace -scheme RSKImageCropper -configuration Release -derivedDataPath /Users/Shared/Jenkins/Library/Caches/org.carthage.CarthageKit/DerivedData/RSKImageCropper/1.6.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/09/4mczyqvj73v002m058rc7lq800007q/T/carthage-xcodebuild.7IDMRP.log
```

RSKImageCropper has a release that purportedly fixes the issue above. The issue is a result of module redefinition and only manifests itself with Xcode 8.3. Simply updating the dependency doesn't work, however. RSKImageCropper resolved the issue by renaming a file. The way that Carthage is implemented, it doesn't seem to clean the checkout directory before checking out a working copy to it. As a result, I had both the old and new file lying around in the checkout directory. The build succeeded once I deleted the old one.

I think it would make sense for Carthage to deal with this renaming issue.

**Comment by josefdolezal** [comment]
I am currently experiencing the same issue with Result + ReactiveSwift frameworks on TravisCI (same setup). For me, everything works fine locally and worked fine on Travis with carthage `0.20.0` and Xcode `8.2`. Any temporary workaround?

**Comment by kndl** [comment]
@josefdolezal My workaround was to delete the offending file within the `Carthage/Checkouts` directory.

**Comment by josefdolezal** [comment]
Thanks! I deleted the whole `Checkouts` folder and bootstrapped it again, pretty huge diff.. I guess I will leave out Carthage from git repo next time..
