### ISSUE TITLE
"Run Script Phase" doc in Getting Started can be replaced by "Copy Files Phase"

### ISSUE THREAD

**Issue by GuillaumeRossolini** [Carthage/Carthage#1898]
* `carthage version`: 0.11.0
* `xcodebuild -version`: Xcode 8.3.2, Build version 8E2002
* Are you using `--no-build`? default settings
* Are you using `--no-use-binaries`? default settings
* Are you using `--use-submodules`? default settings
* Are you using `--cache-builds`? default settings

**Cartfile**
```
github "rs/SDWebImage"
```

**Carthage Output**
The build works, but the app crashes:
```
dyld: Library not loaded: @rpath/SDWebImage.framework/SDWebImage
  Referenced from: /Users/me/Library/Developer/CoreSimulator/Devices/88326CA6-BA26-41C3-A2AB-6ABCBA123D6A/data/Containers/Bundle/Application/E4966C62-A20E-4F1F-8F2F-ED8BDB95A538/FoodTracker.app/FoodTracker
  Reason: image not found
(lldb) 
```

**Suggested fix**
The problem seems to be bullet point number 4 here:
https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

Someone suggested a fix here, which worked in my case:
https://github.com/Alamofire/Alamofire/issues/101#issuecomment-167518833

=> I deleted the Run Script Phase and added a Copy Files Phase with Destination: Frameworks and selected said framework. Build/Run worked at that point.

**Comment by ikesyo** [comment]
`copy-frameworks` is actually needed, please see the description:

> This script works around an App Store submission bug triggered by universal binaries and ensures that necessary bitcode-related files and dSYMs are copied when archiving.

The version you use is outdated so could you please upgrade it first?

**Comment by GuillaumeRossolini** [comment]
Oh, I thought I'd tried that first. Will do, thanks.

**Comment by GuillaumeRossolini** [comment]
@ikesyo Yeah the problem wasn't even the outdated version, simply an error in pasting a path somewhere. Sorry for the noise.
