### ISSUE TITLE
Exclude certain frameworks from Carthage

### ISSUE THREAD

**Issue by nicksnyder** [Carthage/Carthage#1899]
As a library publisher, I want to have a shared scheme in my project for development purposes, but I don't want Carthage consumers of my library to fetch build that scheme because (1) it is an internal implementation detail to the project (similar to the sample app) and (2) it is a waste of time to build.

Is there a way to accomplish what I want?

**Comment by mdiep** [comment]
No there is not. #1227

**Comment by nicksnyder** [comment]
That linked issue is about library consumers being able to specify which targets to build. I am a library author and know that I have a target that should be ignored by Carthage. Is there anything I can do as a library author other than make the scheme not shared?

**Comment by mdiep** [comment]
Nope.
