### ISSUE TITLE
Submodules of dependencies are not committed

### ISSUE THREAD

**Issue by beseder42** [Carthage/Carthage#1903]
We are committing our `checkout` folder to be able to build without a checkout in CI.

Now we discovered that e.g. Realm uses submodules for inner dependencies. We include realm in our Cartfile like this:

`github "realm/realm-cocoa" "v2.5.0"`

This is the [`.gitmodules`](https://github.com/realm/realm-cocoa/blob/master/.gitmodules) file of realm
```
[submodule "Realm/ObjectStore"]
path = Realm/ObjectStore
url = https://github.com/realm/realm-object-store.git
branch = master
```

The content of the submodule is checked out correctly on a local machine which runs a normal `carthage bootstrap`. On our CI system this submodules however is missing since the content for the submodule rests in the `.git` in realm's checkout folder and is therefore not committed. Our build in CI fails then because the submodule is not there.

So how could we also commit the submodules of your dependencies? Otherwise committing the checkout folder is useless. Or are we missing anything?

**Comment by mdiep** [comment]
Which version of Carthage are you using?

I'm not sure what the behavior of this is.

Is there a reason you don't use submodules for your dependencies? That shouldn't be any slower.

**Comment by beseder42** [comment]
We use 0.20.1

Would the behavior be any different concerning submodules of dependencies when we include our dependencies as submodules? For me it seems to be a design question about how git works. Committing the contents of a submodule as part of the parent repository is not wanted by design of git. And that would be what we need in this case.

**Comment by mdiep** [comment]
> Would the behavior be any different concerning submodules of dependencies when we include our dependencies as submodules?

If your CI does `git submodule sync --recursive && git submodule update --init --recursive`, then you'd have everything.

Otherwise you should use `carthage checkout`.

**Comment by beseder42** [comment]
Yes the problem can be solved to build with git or an `carthage checkout`, that's ok. But we want all the dependencies to be committed to be able to build just from our repository - what should be the result of committing the checkout folder.

So it seems impossible with submodules in dependencies to commit _everything_ to be able to build without any sync at build time?!

**Comment by mdiep** [comment]
It don't believe it's currently possible, no.

**Comment by beseder42** [comment]
Ok we will see how to find a fitting workflow. Thanks for the fast help!! 👍
