### ISSUE TITLE
Suggestion: add a way to force https for github submodules that use ssh if `--use-ssh` is not specified

### ISSUE THREAD

**Issue by klundberg** [Carthage/Carthage#1916]
* `carthage version`: 0.22
* `xcodebuild -version`: 8.2.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

Since we've started using carthage at work, a lot of people are caught off guard by ssh key issues. We don't use `--use-ssh` typically, but we've found that ssh keys linked to github accounts are still required to fully check out dependencies that explicitly specify submodules that use ssh. For example, this cartfile:

```
github "seanscal/card.io-iOS-source" == 5.4.2
```

points to a repo that has a git submodule with the remote url `git@github.com:card-io/card.io-dmz.git` which is not ideal for those who don't know they need to add their ssh key on their work machine to their github account. What I'd love to have carthage do (if at all possible) would be to rewrite the remote url to use https for github repos where we know they exist. Perhaps a `--use-https` or `--force-https` flag could make this happen. I suspect it might not be easy, since changing the remote URL for a manually submodule would at the very least make that checkout dirty if `--use-submodules` is used for carthage. 

Is this a reasonable feature to ask for, and is there anything else that might prevent it from working that I'm not thinking of?

**Comment by mdiep** [comment]
If you want to force https, you can add this to your `.gitconfig`:

```
[url "https://github.com/"]
    insteadOf = git://github.com/
[url "https://github.com/"]
    insteadOf = git@github.com:
```

That will force https for _all_ GitHub repos.

**Comment by klundberg** [comment]
Oh, fascinating! Thanks for the tip. I suppose that sort of thing can't be provided as an argument to git on a per-command-basis? I'm not sure if anyone on my team would have an objection to doing that for all repos they access or not.

**Comment by mdiep** [comment]
I'm not sure if there's a way for us to pass that as a custom config to git commands.

**Comment by klundberg** [comment]
OK, thank you! I'll close this then if we can't do it in carthage itself.
