### ISSUE TITLE
'Carthage update' with multiple prebuilt frameworks in a separate repo

### ISSUE THREAD

**Issue by gbrhaz** [Carthage/Carthage#1923]
* `carthage version`: 0.22.0
* `xcodebuild -version`: 8.2.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

As an example:
**Cartfile**
```
github "example/example_frameworks" == 1.0.0
```

**Carthage Output**
```
Fetching example_frameworks
Downloading example_frameworks.framework binary at "1.0.0"
Skipped installing example_frameworks.framework due to the error:
    "Unable to determine framework Swift version"
Checking out example_frameworks

... etc
```

I am archiving (so I did "carthage archive ReactiveSwift Alamofire", for example) a few dependencies I have for a project and putting them into a release on a separate repo. I then want to use this separate repo as just a way to fetch the dependencies. I know Carthage can do this, but it seems to require a "parent" dependency with the same name as above for it to work. I essentially just want Carthage to download and unarchive the Build folder. Is this possible without adding in a .framework with the same name?

**Comment by mdiep** [comment]
That's not a supported workflow. The expectation is that the pre-built frameworks in the release zip would be built in the framework itself.

Doing this will remove Carthage's ability to actually resolve dependencies.

I'd suggest trying the `--cache-builds` flag instead.

**Comment by blender** [comment]
shameless plug: https://github.com/blender/Rome . Maybe @gbrhaz this can help you.

**Comment by gbrhaz** [comment]
How can `--cache-builds` work when using multiple CI agents?

**Comment by BobElDevil** [comment]
Currently there's no built-in way to handle that. What my team has done for our builds is our common script for running carthage will archive/unarchive the Carthage/Build folder into a folder we created in ~/Library/Caches. This isn't perfect, as every agent is maintaining it's own cache, but after half a days worth of builds, all agents are up to date, so it works well enough. 

The Rome project that blender linked above is a more complete solution if that's something you want to look into. 

As for an official solution, #1920 was opened to explore that possibility, though no details have been discussed yet.
