### ISSUE TITLE
Supporting Carthage for your framework

### ISSUE THREAD

**Issue by SandeepAggarwal** [Carthage/Carthage#1925]
Supporting Carthage for your framework:

If my framework itself is dependent upon some other framework eg. Alamofire, then how can I make it show as a dependency.
In cocoapods we have an option like this
`s.dependency ‘Alamofire’, ‘~> 4.1’ `
So how can I replicate it in case of carthage?

**Comment by blender** [comment]
Add to your `Cartfile`
```
github "Alamofile/Alamofire" ~> 4.1
```

**Comment by ikesyo** [comment]
Thanks @blender
