### ISSUE TITLE
Strange Error with mistyped parameter

### ISSUE THREAD

**Issue by aaroncrespo** [Carthage/Carthage#1926]
* `carthage version`: 0.22.0
* `xcodebuild -version`: `Xcode 8.3.2 Build version 8E2002`
* Are you using `--no-build`? NA
* Are you using `--no-use-binaries`? NA
* Are you using `--use-submodules`? NA
* Are you using `--cache-builds`? NA

**Cartfile**
```
NA
```

**Carthage Output**
```
$ carthage update -platform
Unrecognized arguments: -armpfolt
```
probably an issue with Command parsing?

**Comment by mdiep** [comment]
That's because you've mistakenly used only 1 `-`. `--key` vs `-k`.

```
$ carthage update --platform
Missing argument for --platform
```

**Comment by aaroncrespo** [comment]
I know, i just think the error message could be better, the longer the command the worse it gets.
