### ISSUE TITLE
Correct way to make an Umbrella framework available using Carthage

### ISSUE THREAD

**Issue by SanjoDeundiak** [Carthage/Carthage#1927]
What is the correct way to make Umbrella framework available using Carthage?

1. I have C++ framework (framework 1) for which I created Objective-C++ wrapper framework (framework 2) for further use from Objective-C code.
2. Framework 2 embeds framework 1 into its Frameworks directory.
3. Framework 2 is available using Carthage

Problem: when I add framework 2 to iOS application, validation of Archive (when uploading to AppStore) fails with "Found an unexpected Mach-O header code: 0x72613c21" error, however while debugging all works great on both simulator and device.
Framework 2 (including Framework 1 inside Frameworks dir) can be found here:
https://github.com/VirgilSecurity/virgil-foundation-x/tree/2.1.0
Sample application can be found here:
https://github.com/SanjoDeundiak/CarthageTest
Log:
[CarthageTest_2017-05-12_11-18-34.842.xcdistributionlogs.zip](https://github.com/Carthage/Carthage/files/995485/CarthageTest_2017-05-12_11-18-34.842.xcdistributionlogs.zip)

**Comment by ikesyo** [comment]
> Framework 2 embeds framework 1 into its Frameworks directory.

Those nested frameworks should be rejected by App Store validation (e.g http://stackoverflow.com/questions/40930258/codesigning-fails-during-ipa-validation-with-nested-frameworks) so that will not be an option. You must link and embed all the frameworks on app level unfortunately.

**Comment by ikesyo** [comment]
See also #688, #773, #844.

**Comment by SanjoDeundiak** [comment]
@ikesyo thank you for reply, what's my option if nested framework doesn't support distribution using Carthage? Can I add fake scheme in my Framework 2 project which will just copy Framework 1?

**Comment by SanjoDeundiak** [comment]
@ikesyo and can you tell me what exactly "/usr/local/bin/carthage copy-frameworks" does, because I see that even if I doesn't include my nested framework to Input Files it works.

**Comment by mdiep** [comment]
You can still build all frameworks—you just can't _embed_ them.

`copy-frameworks` copies the frameworks and strips unneeded architectures. This is needed because iTunes Connect won't let you submit builds that have simulator slices.

**Comment by SanjoDeundiak** [comment]
@mdiep Thank you. How can I distribute framework 2 using Carthage if it depends on framework 1, which is unavailable using Carthage, but located in framework 1 git repository?

**Comment by mdiep** [comment]
Just build both frameworks within a shared scheme in your repo.

**Comment by SanjoDeundiak** [comment]
@mdiep I don't really get what you're proposing.
I'll try to depict my situation from other point of view:
1. I have repository 2 with xcodeproject and shared scheme for building framework 2, which I want to distribute using Carthage.
2. Framework 2 depends on framework 1, which is not going to be distributed using Carthage, stored in its own repository.
3. I have prebuilt framework 1, with binaries for all architectures, copied to my repository 2.
How can I distribute framework 2 from repository 2 using Carthage in a way such that framework 1 will be downloaded as well?
At first, I solved this problem embedding framework 1 into framework 2, which turned out to be a bad solution.

**Comment by mdiep** [comment]
Ah, you can't _prebuild_ framework 1 and copy in the binary. You'd need to build framework 1 as part of your scheme.

**Comment by SanjoDeundiak** [comment]
@mdiep and what if I create shared scheme with dummy framework and replace this framework with my prebuilt one using script in Build phases

**Comment by mdiep** [comment]
That might work. I dunno.

This isn't something that we're going to explicitly support. But you can probably find a way to make it work.
