### ISSUE TITLE
--log-path option appears to be broken

### ISSUE THREAD

**Issue by michaelmcguire** [Carthage/Carthage#1928]
* `carthage version`: 0.22.0
* `xcodebuild -version`: 8.3.2 8E2002
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "ReactiveCocoa/ReactiveCocoa"
```

**Carthage Output**
```
$ carthage bootstrap --log-path mylog.log
*** No Cartfile.resolved found, updating dependencies
*** Cloning ReactiveCocoa
*** Fetching ReactiveSwift
*** Fetching Result
*** Checking out Result at "3.2.1"
*** Checking out ReactiveSwift at "1.1.2"
*** Downloading ReactiveCocoa.framework binary at "5.0.3"
Failed to write to /var/folders/q4/xrj10h0n20zg_b2jwt5f84t4wlq244/T: Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"
```

Using the `--log-path` option seems to break Carthage.  I've tried specifying a specific file, a specific directory with relative and absolute paths, but I always get this error.  My guess is that something further down the line is assuming the temporary directory is being created but it doesn't when you use this option.

**Comment by michaelmcguire** [comment]
I think my initial guess was incorrect.  It appears that the error coming back is not correct.  The method `private func openLoggingHandle(_ options: Options) -> SignalProducer<(FileHandle, URL?), CarthageError>` in `Build.Swift` maps an error trying to open the log to a new temporary directory URL?  I'm not sure why it would do that.  

The actual error seems to be in `private func openLogFile(_ path: String?) -> SignalProducer<(FileHandle, URL), NSError>` of the same file.  It uses `FileHandle(forUpdatingAtPath:)` which appears to expect an existing file.  I tried creating an empty file at the log location but then Carthage crashes later with an invalid file descriptor.  I'm still digging to see what the fix might be, but it seems like it will also involve a better error message.

**Comment by drkibitz** [comment]
Just noticed this is broken too.
