### ISSUE TITLE
Don't produce dsym unless specified in target

### ISSUE THREAD

**Issue by ianbytchek** [Carthage/Carthage#1930]
While attempting to build a framework I noticed that carthage tries to explicitly extract debug symbols with `/usr/bin/xcrun dsymutil … -o …` despite the fact that `DEBUG_INFORMATION_FORMAT` is set to `DWARF`. This causes `Build Failed: Task failed with exit code 1`, which is expected in my case, because of the way target is built. On other side, why not simply copy `dSYM` produced by standard build command, check if it exists and copy or skip if it's not?

**Comment by erichoracek** [comment]
This should be fixed in #1379, which will be included in the next Carthage release.

**Comment by ianbytchek** [comment]
Is this Christmas or WHAT?!?!? 🎉🍾
