### ISSUE TITLE
swift compiler error (Found this candidate)

### ISSUE THREAD

**Issue by shanyanhai** [Carthage/Carthage#1931]
version 0.22

import EZSwiftExtensions(framework)
import  Material(framework)
when 
EZSwiftExtensions and Material have same extension.
e.g  extension CGPoint {
  var x:CGFloat .......
}

now 

let point    = CGPoint.zero
point.x ----->>>>  !!!!!(Xcode will  error   --  swift compiler error (Found this candidate))

case "x" as   function  
i can use    first.CGPoint.x    build succeed
case "x" as property
(use Cocoapods i can del one)   use Carthage  I don't know  ----- I need help - -!

Addition My Cartfile

github "CosmicMind/Material"
github "goktugyil/EZSwiftExtensions"

**Comment by ikesyo** [comment]
This is not related to Carthage. Please file issues on that frameworks' repositories.
