### ISSUE TITLE
Prevent Duplicate Framework Copies

### ISSUE THREAD

**Issue by bladebunny** [Carthage/Carthage#1944]
Apologies if this has been answered, I couldn't find a specific thread with this question.

I need to share some code between two different targets and/or apps.  (As a dynamic framework)
Conceptually say I have a workspace (just for organizational convenience) that looks like:
```
MyAppSuite
- MyFirstClient
- MySecondClient
```

I'd really like to split out some shared UI code into a common component, call it MyAppKit (catchy).
My workspace now looks like:
```
MyAppSuite
- MyFirstClient
- MySecondClient
- MyAppKit
```

I really like SnapKit, and want to use it both within my shared lib and within my app targets.  So, conceptually, they look like:
```
MyAppSuite
- MyFirstClient
-- SnapKit
-- MyAppKit
- MySecondClient
-- SnapKit
-- MyAppKit
- MyAppKit
-- SnapKit
```

I'm adding the respective dependencies via Carthage.  I put the app targets in a workspace just so I can work on them all at once.  But really, each target has its own Cartfile and they are getting their built frameworks from a common Carthage directory in the workspace root.

The problem is that, though this works, each built app target includes SnapKit within its frameworks folder and again within the frameworks folder within MyAppKit.  e.g.

```
MyFirstClient
- Frameworks:
-- SnapKit
-- MyAppKit
--- Frameworks:
---- SnapKit
```

I'm sure I'm just misunderstanding the limitations here -- but I would have thought there was a way for my libraries to either bind to a shared copy of SnapKit in the app target or, alternatively, allow the app target to bind to the version within MyAppKit.

Its really the redundancy of possible multiple includes/copies of shared dependencies that I don't like here.

One alternative, I suppose might be to have just 1 project.  Make each 'client' a different target, and then share my common code between them.  Would allow me to have just 1 Cartfile for my common dependencies yet still have some code separation between the 2 'client' targets.  But, of course, would require me to drop encapsulating shared logic into frameworks.

**Comment by mdiep** [comment]
You've done things mostly correctly. Don't copy `SnapKit` into `MyAppKit.framework`—just bundle in in the app's frameworks directory. Frameworks shouldn't be embedded. Frameworks link against all their dependencies, but the actual `.frameworks` are only ever copied into the app—never into the framework.
