### ISSUE TITLE
Where are all the options documented?

### ISSUE THREAD

**Issue by drkibitz** [Carthage/Carthage#1946]
* `carthage version`: 0.23.0
* `xcodebuild -version`: NA
* Are you using `--no-build`? Options like this,
* Are you using `--no-use-binaries`? this,
* Are you using `--use-submodules`? this,
* Are you using `--cache-builds`? and this.

and potentially more, that take digging though various pages and examples.

Would be wonderful if the cli mentioned accepted options for each subcommand.
Like this:
```sh
git -h
git remote -h
git add -h
```
or this:
```sh
swift package -h
swift package edit -h
```

So what I'm looking for is basically:
```sh
carthage -h
carthage bootstrap -h
carthage build -h
```

etc..

**Comment by drkibitz** [comment]
I should also mention that cocoapods cli also works like this:
```sh
pod -h
pod clean -h
pod install -h
```

**Comment by ikesyo** [comment]
`carthage help bootstrap`. is what you are looking for.

**Comment by michaeleisel** [comment]
it should be mentioned in `carthage help` that you can run `carthage help <command>`, I think it's hard to discover otherwise

**Comment by Blackjacx** [comment]
This is definitely worth an improvement since these options are totally different from the standard and therefore undiscoverable until you fid this post.
