### ISSUE TITLE
Deployment target issue

### ISSUE THREAD

**Issue by tylerlong** [Carthage/Carthage#1951]
* `carthage version`:  0.23.0
* `xcodebuild -version`: Xcode 8.1   Build version 8B62
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`?  No

**Cartfile**
```
github "ringcentral/ringcentral-swift"
```

**Command**

```
carthage update --platform iOS
```

**Carthage Output**
```
....
/Users/tyler.liu/src/test/Carthage/Checkouts/ringcentral-swift/Source/RestClient.swift:11:8: error: module file's minimum deployment target is ios10.1 v10.1: /Users/tyler.liu/src/test/Carthage/Checkouts/ringcentral-swift/Carthage/Build/iOS/Async.framework/Modules/Async.swiftmodule/arm64.swiftmodule
import Async
       ^

** BUILD FAILED **
```

But the [duemunk/Async](https://github.com/duemunk/Async) project claims to support iOS 8.0+.

**Comment by ikesyo** [comment]
Looks like the library does support iOS 8 in its podspec: https://github.com/duemunk/Async/blob/2.0.3/AsyncSwift.podspec#L10 but the generated Xcode project by `swift package generate-xcodeproj` does not. So please file an issue on that repository.

**Comment by ikesyo** [comment]
Looks related to this https://github.com/duemunk/Async/pull/115

cc @toshi0383
