### ISSUE TITLE
Moving a submodule from one service provider to another

### ISSUE THREAD

**Issue by rob-nash** [Carthage/Carthage#1955]
My parent project has submodules. One of the submodules is named robstoolbox. It was hosted in Github but I have moved it to bitbucket.

For some reason Carthage is remembering the GitHub URL. See below.

* `carthage version`: 0.19.1
* `xcodebuild -version`: 8.3.2 8E2002
* Are you using `--no-build`? yes
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? yes
* Are you using `--cache-builds`? no

When I make this change, from A to B, like so

**Cartfile A**
```
git "git@bitbucket.org:rob-nash/wdo_eventmodel.git" == 1.0.14
git "git@bitbucket.org:rob-nash/zip.git" == 1.0
github "rob-nash/robstoolbox.git" == 1.2.12
```

**Cartfile B**
```
git "git@bitbucket.org:rob-nash/wdo_eventmodel.git" == 1.0.14
git "git@bitbucket.org:rob-nash/zip.git" == 1.0
git "git@bitbucket.org:rob-nash/robstoolbox.git" == 1.2.12
```

Fetching for robstoolbox happens twice. 

**Carthage Output**
```
*** Fetching robstoolbox
*** Fetching zip
*** Fetching wdo_eventmodel
*** Fetching robstoolbox
*** Checking out robstoolbox at "1.2.12"
*** Checking out robstoolbox at "1.2.12"
*** Checking out zip at "1.0.0"
*** Checking out wdo_eventmodel at "1.0.14"
```

If I remove robstoolbox from GitHub (keeping Cartfile B in place), Carthage gets upset that robstoolbox is missing from GitHub.

I have tried deleting the Carthage.resolved file and clearing ~/Library/Cache/org.carth...

**Comment by mdiep** [comment]
If you run `git submodule sync --recursive`, does that fix it?

**Comment by rob-nash** [comment]
Hi,

Just tried it.

```
Roberts-MacBook-Pro:wdo_eventparser nashsoftwareconsultingltd$ git submodule sync --recursive
Synchronizing submodule url for 'Carthage/Checkouts/robstoolbox'
Synchronizing submodule url for 'Carthage/Checkouts/project'
Synchronizing submodule url for 'Carthage/Checkouts/project/Carthage/Checkouts/robstoolbox'
Synchronizing submodule url for 'Carthage/Checkouts/project/Carthage/Checkouts/zip'
Synchronizing submodule url for 'Carthage/Checkouts/zip'
```

Seems to still fetch from two locations.

With Cartfile B in place, I have subsequently run carthage update --no-build

```
*** Please update to the latest Carthage version: 0.23.0. You currently are on 0.19.1
*** Fetching robstoolbox
*** Fetching zip
*** Fetching wdo_eventmodel
*** Fetching robstoolbox
*** Checking out robstoolbox at "1.2.12"
*** Checking out robstoolbox at "1.2.12"
*** Checking out zip at "1.0.0"
*** Checking out wdo_eventmodel at "1.0.14"
```

:(

**Comment by rob-nash** [comment]
Hold the phone ! I think I've got it. Will confirm in a moment.

**Comment by rob-nash** [comment]
Got it!

robstoolbox was a dependency at the parent level at and the level of a downstream dependency

I updated the cartfile of the downstream dependency, run an update, committed, then returned to the parent and did the same.

thanks for your time
