### ISSUE TITLE
--cache-builds always rebuilds SwiftCheck dependency

### ISSUE THREAD

**Issue by broomburgo** [Carthage/Carthage#1956]
* `carthage version`: 0.23.0
* `xcodebuild -version`: Xcode 8.3.2 Build version 8E2002
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

**Cartfile**
```
github "typelift/SwiftCheck"
```

**Carthage Output**
```
*** Fetching SwiftCheck
*** Checking out SwiftCheck at "0.8.0"
*** xcodebuild output can be found in /var/folders/wr/nq3sp5c533q2tvy393w1_m900000gn/T/carthage-xcodebuild.3y8gQH.log
*** No cache found for SwiftCheck, building with all downstream dependencies
*** Building scheme "SwiftCheck-iOS" in Tutorial.xcworkspace
```

Hi, I'm having trouble in caching the SwiftCheck dependency: carthage always rebuilds it with message "Invalid cache found". I tried to just `carthage update --platform iOS --cache-builds` with a simple Cartfile with just SwiftCheck in an empty folder, and the output is always the same: carthage always builds.

Any ideas?

Thanks

**Comment by ikesyo** [comment]
Refs: https://github.com/typelift/SwiftCheck/issues/217

**Comment by Sealos** [comment]
Are you using multiple targets? I experience the same issue building SwiftyJSON with iOS and watchOS targets, for example, building the dependcy with a watchOS platform invalidates the iOS platform and viceversa (Or at least it seems like it):

> carthage build SwiftyJSON --platform **watchOS** --cache-builds
> *** xcodebuild output can be found in /var/folders/tk/gxhjkcf15fq72xpkvrth62f40000gn/T/carthage-xcodebuild.SU27RT.log
> *** **Valid** cache found for SwiftyJSON, skipping build
> 
> carthage build SwiftyJSON --platform **iOS** --cache-builds
> *** xcodebuild output can be found in /var/folders/tk/gxhjkcf15fq72xpkvrth62f40000gn/T/carthage-xcodebuild.68h9ZJ.log
> *** **Invalid** cache found for SwiftyJSON, rebuilding with all downstream dependencies
> *** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
> 
> carthage build SwiftyJSON --platform **iOS** --cache-builds
> *** xcodebuild output can be found in /var/folders/tk/gxhjkcf15fq72xpkvrth62f40000gn/T/carthage-xcodebuild.ftTdtT.log
> *** **Valid** cache found for SwiftyJSON, skipping build
> 
> carthage build SwiftyJSON --platform **iOS** --cache-builds
> *** xcodebuild output can be found in /var/folders/tk/gxhjkcf15fq72xpkvrth62f40000gn/T/carthage-xcodebuild.8YjQWR.log
> *** **Valid** cache found for SwiftyJSON, skipping build
> 
> carthage build SwiftyJSON --platform **watchOS** --cache-builds
> *** xcodebuild output can be found in /var/folders/tk/gxhjkcf15fq72xpkvrth62f40000gn/T/carthage-xcodebuild.GFhVnz.log
> *** **Invalid** cache found for SwiftyJSON, rebuilding with all downstream dependencies
> *** Building scheme "SwiftyJSON watchOS" in SwiftyJSON.xcworkspace

**Comment by ikesyo** [comment]
@Sealos That should be unrelated or separate one.

**Comment by broomburgo** [comment]
No, I only build with "--platform iOS".

I tried a Cartfile with all the typelift pinned repositories (save for Aquifer, which doesn't build), thus:

```
github "typelift/SwiftCheck"
github "typelift/Swiftz"
github "typelift/Focus"
github "typelift/Concurrent"
github "typelift/Alchemy"
```

and I noticed that the only one that's properly cached is Alchemy: all the others give the "invalid cache" message.

My command is still `carthage update --platform iOS --cache-builds`.

**Comment by ikesyo** [comment]
This is because SwiftCheck does not have `SwiftCheck-Swift.h` in the built framework. Carthage uses that file since #1896 to detect a framework's Swift version. I guess pure Swift frameworks which do not use `Foundation` at all will not have that header.

/cc @mdiep @erichoracek

**Comment by ikesyo** [comment]
I submitted https://github.com/typelift/SwiftCheck/issues/227 on the upstream. Closing.
