### ISSUE TITLE
Generate Acknowledgements Plist

### ISSUE THREAD

**Issue by Zyphrax** [Carthage/Carthage#1961]
I've created a modified version of a [SO python script](https://stackoverflow.com/a/21326485/136819) that generates a Acknowledgements Plist.  
This new version works great with Carthage and also contains a regex to reduce the number of newlines in the output.

Maybe useful for in the Documentation section?
Or maybe integrate something like this into carthage?

**Update: Moved script to a GitHub repository**
https://github.com/Building42/AckAck

Simply download the python script and run it.

**Comment by klundberg** [comment]
I'd love for something like this to live in carthage itself. I was planning on proposing the same thing today. Does your script specifically work with the settings bundle plist format? I haven't worked with that in a long time.

**Comment by mdiep** [comment]
FYI: If you name your script something like `carthage-acknowledgements` and put it in your path, then you should be able to run it like `carthage acknowledgements`.

**Comment by Zyphrax** [comment]
@klundberg Yes, it generates a plist that you can include in your Root.plist like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>StringsTable</key>
  <string>Root</string>
  <key>PreferenceSpecifiers</key>
  <array>
    <dict>
      <key>Type</key>
      <string>PSChildPaneSpecifier</string>
      <key>Title</key>
      <string>Acknowledgements</string>
      <key>File</key>
      <string>Acknowledgements</string>
    </dict>
  </array>
</dict>
</plist>
```
It is very similar to the one generated by CocoaPods.

Please note that the current version of the script requires that you run it in the folder of the script (or at least specify paths relative to the script's path). I'll try to fix that tomorrow.

Also when you look at the acknowledgements on your device (under iOS settings) you might notice a few extra newlines here and there. That's an Apple bug: https://stackoverflow.com/a/35632286/136819

**Comment by ikesyo** [comment]
Here is another solution: https://github.com/mono0926/LicensePlist

**Comment by Zyphrax** [comment]
I've created a new version that accepts a few options and splits the licenses into separate plist files (just like LicensePlist):

https://github.com/Building42/AckAck
