### ISSUE TITLE
Moving repo names causes infinite loops

### ISSUE THREAD

**Issue by codeOfRobin** [Carthage/Carthage#1963]
* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.3.2 Build version 8E2002
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

I had a framework that had 
`github "texturegroup/texture"` 

and an app(which used the framework) that had
`github "facebook/asyncdisplaykit"`(which is the same thing except they [moved](https://medium.com/@Pinterest_Engineering/introducing-texture-a-new-home-for-asyncdisplaykit-e7c003308f50) 

I did notice it looping over the dependencies(shut off the build after 2 hours, usually takes 20 minutes(
Removing `github "facebook/asyncdisplaykit"`fixed it, but I'm concerned this may be a bug

![screen shot 2017-05-30 at 4 48 41 pm](https://cloud.githubusercontent.com/assets/5009041/26583357/83557fe4-4562-11e7-9cf1-fa86e7e1cb90.png)

**Comment by mdiep** [comment]
Which carthage command are you running?

**Comment by codeOfRobin** [comment]
`carthage update --platform iOS`

**Comment by mdiep** [comment]
The resolver is probably getting stuck trying to find compatible versions of your dependencies. I'm not sure why renaming would cause this. Could you share your app and framework Cartfiles?

I would suggest running `carthage bootstrap` on CI. That will avoid this issue by having CI use whatever's in `Cartfile.resolved`. Since that should be whatever you've been using locally, this prevents discrepancies between your local machine and the CI machine.

**Comment by codeOfRobin** [comment]
> I would suggest running carthage bootstrap on CI. 
Ah, cool! Will do that from now on

Framework cartfile:
```
github "johnsundell/unbox"
github "johnsundell/wrap"
github "codeOfRobin/Birdsong" "v0.5"
github "aschuch/StatefulViewController" ~> 3.0
github "ninjaprox/NVActivityIndicatorView"
github "texturegroup/texture" "master"
```

App Cartfile:
```
github "hyperoslo/ImagePicker"
github "robb/Cartography"
github "matthewpalmer/Locksmith" "swift-3.0"
github "onevcat/Kingfisher" ~> 3.0
github "nickoneill/Pantry" ~> 0.3
github "codeOfRobin/ParkedTextField" "master"
github "alikaragoz/MCSwipeTableViewCell" >= 2.1.4
github "AgileBits/onepassword-extension" "add-framework-support"
github "codeOfRobin/simple-touch" "master"
github "mixpanel/mixpanel-iphone"
github "SVProgressHUD/SVProgressHUD"
github "facebook/AsyncDisplayKit"
github "skywinder/ActionSheetPicker-3.0"
<private framework>
```

**Comment by fish-red** [comment]
loop

**Comment by ikesyo** [comment]
> I had a framework that had 
`github "texturegroup/texture"` 
>
> and an app(which used the framework) that had
`github "facebook/asyncdisplaykit"`(which is the same thing except they [moved](https://medium.com/@Pinterest_Engineering/introducing-texture-a-new-home-for-asyncdisplaykit-e7c003308f50) 

Actually `facebook/asyncdisplaykit` is not moved to `texturegroup/texture`, they are different repositories. But `facebook/asyncdisplaykit` is moved to (renamed as) `facebookarchive/AsyncDisplayKit`.

So this should be something similar to #976, #1167, and so on. Closing.
