### ISSUE TITLE
cache repo need full path

### ISSUE THREAD

**Issue by fish-red** [Carthage/Carthage#1966]
because only repo name can't Specify a correct git. 
eg: 
A.git  github.com/A/A.git  
A.git  github.com/B/A.git   
you need use full path

**Comment by fish-red** [comment]
<img width="429" alt="screen shot 2017-06-01 at 10 48 11" src="https://cloud.githubusercontent.com/assets/27393326/26662642/fb1d88c2-46b7-11e7-8e77-2a45bea70511.png">
<img width="315" alt="screen shot 2017-06-01 at 10 47 52" src="https://cloud.githubusercontent.com/assets/27393326/26662644/fb2c4114-46b7-11e7-856b-d525d380b562.png">

**Comment by ikesyo** [comment]
Closing this as a duplicate of #2150.
