### ISSUE TITLE
How to remove a particular framework from carthage

### ISSUE THREAD

**Issue by vidhyasri2106** [Carthage/Carthage#1970]
* `carthage version`: 0.22.0

How to remove particular framework from list of frameworks installed using carthage in xcode project. Is there a command like carthage remove "github "Alamofire/Alamofire"" present?

**Comment by blender** [comment]
In Build Phases in your Xcode project:

- locate your carthage `copy-frameworks` phase
- remove the framework form the `Input Files` list of the phase

In your `Cartfile` and `Cartfile.resolved`:

- delete any mentions of the framework

**Comment by jcabreram** [comment]
I'd just add that the framework also needs to be removed from `Linked Frameworks and Libraries` from the _General_ tab in your Xcode project.
