### ISSUE TITLE
How can I provide a user name and password to the binary only frameworks host?

### ISSUE THREAD

**Issue by poborin** [Carthage/Carthage#1973]
Let's assume I have a private artefact repository. It requires an authentication in order to access stored files. How do I pass this authentication through carthage?

**Comment by mdiep** [comment]
Only way right now would be to put it in the URL. `https://username:password@www.example.com/`

**Comment by ikesyo** [comment]
Looks like if you have a credential in your keychain `URLSession` will look up that: https://developer.apple.com/documentation/foundation/urlsession

> By looking up Internet passwords and certificates in the user’s keychain (in macOS) or the app’s keychain (in iOS)
