### ISSUE TITLE
Carthage build use subdirectory's Xcode project instead of current directory

### ISSUE THREAD

**Issue by devxoul** [Carthage/Carthage#1974]
* `carthage version`: 0.23.0
* `xcodebuild -version`: 8.3.2

**Cartfile**
```
github "ReactiveX/RxSwift" >= 3.0
```

**Carthage Output**
```
carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/yk/ms2yrh7s2_g26y4rh4n9mpww0000gn/T/carthage-xcodebuild.qusjAH.log
*** Building scheme "ReactorKit" in Counter.xcworkspace
```

**What I Expected**

```diff
- *** Building scheme "ReactorKit" in Counter.xcworkspace     # (X)
+ *** Building scheme "ReactorKit" in ReactorKit.xcworkspace  # (O)
```

**How to Reproduce**

```bash
$ git clone https://github.com/ReactorKit/ReactorKit
$ cd ReactorKit
$ git checkout 0.4.5
$ swift package generate-xcodeproj
$ carthage bootstrap
$ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/yk/ms2yrh7s2_g26y4rh4n9mpww0000gn/T/carthage-xcodebuild.qusjAH.log
*** Building scheme "ReactorKit" in Counter.xcworkspace  # Expected ReactorKit.xcodeproj
```

**Current Workaround**

```
$ ...
$ rm -r Example
$ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/yk/ms2yrh7s2_g26y4rh4n9mpww0000gn/T/carthage-xcodebuild.xYSkSy.log
*** Building scheme "ReactorKit" in ReactorKit.xcodeproj  # Works
```

**Comment by mdiep** [comment]
Carthage always prefers to build through a workspace. This gives projects a chance to build versions of their own dependencies.

**Comment by devxoul** [comment]
I think xcodeproj in the root directory should have higher precedence than the workspace in the subdirectory, but you can close this issue if it is intended :)

**Comment by ikesyo** [comment]
It's intended––directory layouts would not guarantee any correctness. Closing

**Comment by devxoul** [comment]
@mdiep @ikesyo Do you have any idea of another possible workaround? Is it the best to remove example directory? 🤔

**Comment by mdiep** [comment]
Is it causing a problem as-is?

**Comment by devxoul** [comment]
Yeah, `carthage build` builds Example project instead of the library. I should remove the example project each time I build the framework. I'd like to know if there is a better solution.

**Comment by mdiep** [comment]
Even though it's building through the example workspace, it should be building the framework correctly.

One option is to convert the example to use a project instead of a workspace.

**Comment by devxoul** [comment]
Example projects are using CocoaPods and I was trying to add Carthage support to existing library. It's intended and I can just add `rm -r Examples` in the travis script so it's enough. Thanks for reply :)
