### ISSUE TITLE
dyld: Symbol not found: __TMO11CarthageKit10Dependency

### ISSUE THREAD

**Issue by RmondJone** [Carthage/Carthage#1980]
dyld: Symbol not found: __TMO11CarthageKit10Dependency
  Referenced from: /usr/local/bin/carthage
  Expected in: /Library/Frameworks/CarthageKit.framework/CarthageKit
 in /usr/local/bin/carthage
Abort trap: 6

**Comment by tjvanpat** [comment]
Since this is the first hit for this error, and RmondJone didn't provide anything useful when closing this, here is how I fixed it:

$ sudo rm -rf /Library/Frameworks/CarthageKit.framework
$ brew uninstall carthage
$ brew install carthage
