### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by TimBibb** [Carthage/Carthage#1981]
* `0.23.0`
* `8.3.3`
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
<github TimBibb/Zip #GitHub>
```

**Carthage Output**
```
<Parse error: expected string after dependency type in line:>
```

When calling ```Carthage update``` or ```Carthage build``` on the directory my Cartfile is stored in, it gives me this parse error. I'm not sure what I am supposed to do here.

**Comment by ikesyo** [comment]
> `github TimBibb/Zip`

As noted in [the documentation](https://github.com/Carthage/Carthage/blob/0.23.0/Documentation/Artifacts.md#github-repositories) you must quote the NWO: `github "TimBibb/Zip"`.

**Comment by TimBibb** [comment]
Parse error: expected string after dependency type in line: github “TimBibb/Zip” #github
This was the error given to me after I changed what you said to do

**Comment by ikesyo** [comment]
`“` is not `"`.

**Comment by TimBibb** [comment]
Thank you so much!

**Comment by sauravexodus** [comment]
I was using comments in my `Cartfile.resolved`. Something like this:
```ruby
# github "SomeAuthor/Dependecy" "2.0"
```
This was causing the same issue. Removing it worked for me :)
