### ISSUE TITLE
Carthage build incomplete framework

### ISSUE THREAD

**Issue by amereii** [Carthage/Carthage#1985]
* `carthage version`: 0.23.0
* `xcodebuild -version`: Xcode 8.3.2 Build version 8E2002
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "RooyeKhat-Media/IGProtoBuffLibrary" "build54"
```

**Carthage Output**
```
*** Checking out IGProtoBuffLibrary at "build54"
*** xcodebuild output can be found in /var/folders/nz/x8t9wb3d1t33b77ckz509p_w0000gn/T/carthage-xcodebuild.Uh3CE2.log
*** Building scheme "IGProtoBuff" in IGProtoBuff.xcodeproj
```

My problem is that when I run ```carthage update``` it build bad framework for example 
IGPConnectionSecuringResponse has no member igpHeartbeatInterval but If you see the source code
https://github.com/RooyeKhat-Media/IGProtoBuffLibrary/blob/master/IGProtoBuff/ProtoBuffs/ConnectionSecuring.proto.swift#L332-L340
it is exists

I re-run ```carthage update``` after Delete derived data and Carthage cache folder , but same issue

**Comment by mdiep** [comment]
If you look at the source code in `Carthage/Checkouts/IGProtoBuffLibrary`, does the method exist there?

**Comment by amereii** [comment]
Yes , the method is exist in `Carthage/Checkouts/IGProtoBuffLibrary`
Carthage checkout full version of "RooyeKhat-Media/IGProtoBuffLibrary" but build incomplete version

In the XCode ```IGPConnectionSecuringResponse``` has no member `igpHeartbeatInterval` but has `igpSymmetricKeyLength` , if You hold control and click on the `IGPConnectionSecuringResponse.igpSymmetricKeyLength` you can see in framework , `IGPConnectionSecuringResponse` is incomplete

**Comment by amereii** [comment]
@mdiep How can I solve this? is it a carthage bug?

**Comment by ikesyo** [comment]
I tested and couldn't reproduce it––`IGPConnectionSecuringResponse().igpHeartbeatInterval` can be accessed correctly. It seems that you don't set up Framework Search Paths correctly so you are linking to another/older `IGProtoBuff` framework which does not have `IGPConnectionSecuringResponse.igpHeartbeatInterval`.

<img width="918" alt="2017-06-13 14 10 13" src="https://user-images.githubusercontent.com/909674/27066886-433dde70-5042-11e7-9f87-6754d64ad810.png">

**Comment by amereii** [comment]
@ikesyo As I told before I delete all old frameworks , Carthage folder , derived data and Carthage cache folder

The Framework Search Paths is correct 
> $(inherited) $(PROJECT_DIR)/Carthage/Build/iOS $(PROJECT_DIR)

**Comment by amereii** [comment]
@ikesyo , @mdiep 
Any idea???

**Comment by blender** [comment]
Can you share your Copy Frameworks Phase

**Comment by ikesyo** [comment]
Unfortunately I couldn't reproduce this so I have no idea.

**Comment by SNThunderbolt** [comment]
@amereii 
Hi I'm trying to fork the iGap iOS Project but as you can see there are lots of frameworks missing, so i tried to download and add them manually...

but i can't find the IGProtoBuff.framework

can you please help me?
<img width="453" alt="screen shot 2017-09-26 at 10 01 06 am" src="https://user-images.githubusercontent.com/11421870/30845781-e2a31fc8-a2a1-11e7-90dd-20a6e5298fed.png">

**Comment by ikesyo** [comment]
@SNThunderbolt Just run `carthage bootstrap --platform ios`.

**Comment by ikesyo** [comment]
@SNThunderbolt I'm sorry but we are not sure about a build failure of a specific framework.
