### ISSUE TITLE
Dependency conflicts with forked repositories

### ISSUE THREAD

**Issue by DivineDominion** [Carthage/Carthage#1987]
I cannot checkout a local or remote fork of a repository here; either the latest official release wins, or I get the error below:

* `carthage version`:  0.23.0
* `xcodebuild -version`: Xcode 8.2.1, Build version 8C1002
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "DivineDominion/RxSwift" "patch-3"
github "RxSwiftCommunity/RxFileMonitor" "master"
```

I want to check out my custom patch version (`A`) but `RxFileMonitor` (`B`) seems to interfere with its dependency (`B -> A'`, not `B -> A`). 

**Carthage Output**

Using `--no-use-binaries` here because I'm on El Capitan and can't compile the latest Swift code, yet, so the attempt to download and use `RxSwift.framework` fails anyway.

```
$ carthage update --no-use-binaries --platform Mac
*** Fetching RxSwift
*** Fetching RxFileMonitor
*** Fetching RxSwift
*** Checking out RxSwift at "3.5.0"
*** Checking out RxFileMonitor at "0244dbe5467b60d5e65df06bafb6ec4713b2932b"
*** Checking out RxSwift at "8b2585d0351c62f14bf5b56bf31c4a0b2e0b255b"
A shell task (/usr/bin/env git checkout --quiet --force 8b2585d0351c62f14bf5b56bf31c4a0b2e0b255b) failed with exit code 128:
fatal: Unable to create '/Users/ctm/Library/Caches/org.carthage.CarthageKit/dependencies/RxSwift/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

```

**Comment by mdiep** [comment]
Try deleting this file: `/Users/ctm/Library/Caches/org.carthage.CarthageKit/dependencies/RxSwift/index.lock`

**Comment by DivineDominion** [comment]
Sorry, forgot to mention this: I tried that (file does not exist afterwards).

The `.lock` conflict stems from the 2 simultaneous attempts to check out and build RxSwift.

**Comment by DivineDominion** [comment]
So far, my best wild-assed guess is this: repository names ("RxSwift") don't suffice as repository identifiers. `ReactiveC/RxSwift` is checked out, and my own fork, and bam -- conflict.
