### ISSUE TITLE
Install packages are not signed with a developer ID

### ISSUE THREAD

**Issue by louisdh** [Carthage/Carthage#1988]
When trying to open ```Carthage.pkg```, macOS gives the following message:
"“Carthage.pkg” can’t be opened because it is from an unidentified developer."

(Yes, I know right click and selecting open will allow me to install it anyways, without me having to change my security settings.)

Any chance a developer ID could be registered for Carthage release packages?

**Comment by mdiep** [comment]
This is a dupe of #1186.

**Comment by louisdh** [comment]
I did actually search to make sure it wasn't a dupe, didn't find it for some reason 🤔. Anyways, consider this a +1 for #1186.
