### ISSUE TITLE
copy-frameworks scripts causes build error in Xcode 8.3.3

### ISSUE THREAD

**Issue by bsarrazin** [Carthage/Carthage#1998]
* `carthage version`: 0.23.0
* `xcodebuild -version`: Xcode 8.3.3 Build version 8E3004b
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "Alamofire/Alamofire"
github "Quick/Nimble"
github "Quick/Quick"
github "ReactiveX/RxSwift"
github "RxSwiftCommunity/RxRealm"
github "SVProgressHUD/SVProgressHUD"
github "SnapKit/SnapKit"
github "SwiftyBeaver/SwiftyBeaver"
github "Swinject/Swinject"
github "antitypical/Result"
github "ashleymills/Reachability.swift" ~> 3.0
github "malcommac/SwiftDate"
github "realm/realm-cocoa" "v2.8.1"
github "thii/SwiftHEXColors"
```

**Carthage Output**
```
$ carthage update --platform ios                                                                                                                          22:36:32  ‹2.4.1›
*** Fetching Result
*** Fetching SwiftyBeaver
*** Fetching SwiftHEXColors
*** Fetching SVProgressHUD
*** Fetching Reachability.swift
*** Fetching RxSwift
*** Cloning Quick
*** Cloning Alamofire
*** Cloning RxRealm
*** Cloning Swinject
*** Cloning Nimble
*** Cloning SnapKit
*** Cloning SwiftDate
*** Fetching realm-cocoa
*** Checking out Nimble at "v7.0.1"
*** Checking out Quick at "v1.1.0"
*** Checking out RxRealm at "0.6.0"
*** Checking out Result at "3.2.3"
*** Checking out Reachability.swift at "v3"
*** Downloading RxSwift.framework binary at "Mango"
*** Downloading realm-cocoa.framework binary at "v2.8.1"
*** Checking out Alamofire at "4.5.0"
*** Checking out SnapKit at "3.2.0"
*** Checking out SVProgressHUD at "2.1.2"
*** Checking out SwiftHEXColors at "1.1.1"
*** Checking out SwiftyBeaver at "1.2.2"
*** Checking out SwiftDate at "4.1.2"
*** Checking out Swinject at "2.1.0"
*** xcodebuild output can be found in /var/folders/3n/0zjn1g0s2gbfflyvp1vjjfhr0000gn/T/carthage-xcodebuild.ZlQzso.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Quick-iOS" in Quick.xcworkspace
*** Building scheme "Reachability" in Reachability.xcodeproj
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "RxRealm-iOS" in RxRealm.xcodeproj
*** Building scheme "SnapKit" in SnapKit.xcworkspace
*** Building scheme "SVProgressHUD-Framework" in SVProgressHUD.xcodeproj
*** Building scheme "SwiftDate" in SwiftDate.xcodeproj
*** Building scheme "SwiftHEXColors" in SwiftHEXColors.xcodeproj
*** Building scheme "SwiftyBeaver (iOS)" in SwiftyBeaver.xcodeproj
*** Building scheme "Swinject-iOS" in Swinject.xcodeproj
```

## Bug?

Using the build phase script causes this error (note that the framework, in this case Nimble) changes every time I run the tests:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: truncated or malformed fat file (offset plus size of cputype (12) cpusubtype (9) extends past the end of the file) /Users/ben/Library/Developer/Xcode/DerivedData/Pikachu-bbcbcozxsduipaggienfsckrilby/Build/Products/Debug-iphonesimulator/Nimble.framework.dSYM/Contents/Resources/DWARF/Nimble
```

![2017-06-17 at 11 24 pm](https://user-images.githubusercontent.com/1077441/27257829-425418ba-53b4-11e7-9a33-5f9ee1bb15cf.png)

## Not Using Script

Commenting out the script makes everything compile, but it cannot find the framework at runtime:

![2017-06-17 at 11 27 pm](https://user-images.githubusercontent.com/1077441/27257839-9dc0b0e6-53b4-11e7-91d8-f7298a114ad7.png)

## Pseudo Carthage

Ignoring the fact that my tests aren't passing (I wasn't running the backend module), creating a 'copy files' build phase and adding the frameworks to the phase seems to work fine.

![2017-06-17 at 11 32 pm](https://user-images.githubusercontent.com/1077441/27257847-3ef74376-53b5-11e7-8fb7-624c047fe800.png)

**Comment by bsarrazin** [comment]
Note that even with these extra build phases, I still get the error when running the test at the command line. Any help would be appreciated.

**Comment by ikesyo** [comment]
copy-frameworks is for woking around App Store submission limitation so you don't need to use it for your test targets. You can just use standard Embedded Binaries way.

**Comment by ikesyo** [comment]
> Note that even with these extra build phases, I still get the error when running the test at the command line.

So it would mean that the error is not releared to Carthage, right?

**Comment by bsarrazin** [comment]
@ikesyo I'm really not sure anymore... it seemed to be a Carthage problem.
I'm downloading Xcode 8.3.2 to see if Xcode is the problem.

**Comment by bsarrazin** [comment]
@ikesyo same problem with Xcode 8.3.2

This seems to be a bug that used to exist in Carthage, according to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1252255

**Comment by ikesyo** [comment]
The Firefox bug is completely unrelated (embedding frameworks into frameworks which Apple prohibits in their App Store submission validation).

**Comment by bsarrazin** [comment]
@ikesyo here's an update

We have a scheme that has the app, the testing target, the UI testing target, a non-embedded framework and its testing target (the ones with * has the carthage script):

- App (*)
- AppTests (*)
- AppUITests (*)
- MyKit
- MyKitTests (*)

My working theory right now is that when running the tests using this scheme, the carthage script is executed multiple times in parallel and possibly overwriting the frameworks/dSYM files which might be mid-copy when being used by a build process... causing the `lipo: truncated or malformed fat file` error.

**Comment by ikesyo** [comment]
As I said abobe could you please use `copy-frameworks` only for your app target?

**Comment by bsarrazin** [comment]
@ikesyo no because otherwise we get a crash in tests saying that libs aren't found, something along the lines of:
```
dyld: Library not loaded: @rpath/FrameworkTest.framework/FrameworkTest03
  Referenced from: /var/mobile/Applications/FA6BAAC8-1AAD-49B4-8326-F30F66458CB6/FrameworkTest03App.app/FrameworkTest03App
  Reason: image not found
```

Unless you have a solution to this?

**Comment by mdiep** [comment]
@bsarrazin You can use an ordinary _Copy Frameworks_ build phase for your unit tests. Add a _copy files_ build phase to your unit test target and set the destination to _Frameworks_.

**Comment by bsarrazin** [comment]
@mdiep ok I will make these changes.
Thanky you and @ikesyo for your help on this
