### ISSUE TITLE
Carthage Time Out

### ISSUE THREAD

**Issue by heleny** [Carthage/Carthage#2002]
* `carthage version`: 0.23.0
* `xcodebuild -version`: 8.3.2 (8E2002)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "Alamofire/Alamofire" == 4.0
github "SwiftyJSON/SwiftyJSON" ~> 2.3.0
```

**Carthage Output**
```
*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Checking out Alamofire at "4.0.0"
*** Downloading SwiftyJSON.framework binary at "2.4.0"
*** Skipped installing SwiftyJSON.framework binary due to the error:
	"Incompatible Swift version - framework was built with 2.3 and the local version is 3.1."
*** Checking out SwiftyJSON at "2.4.0"
*** xcodebuild output can be found in /var/folders/h4/1slt67613tx6c_xdd4ffp9nw0000gn/T/carthage-xcodebuild.XvG2pW.log
xcodebuild timed out while trying to read Alamofire.xcworkspace 😭

```

I am constantly running into timed out on the latest version of Carthage and Xcode.  Please advise. 

Thank you,
Helen

**Comment by heleny** [comment]
I also tested it on the latest version of Xcode 8.3.3 (8E3004b), same outcome.  
"xcodebuild timed out while trying to read NameOfTheFramework".  

Any advice will be appreciated.

Thanks, 
Helen

**Comment by blender** [comment]
Can you copy paste your Cartfile? Also, what command are you running?

**Comment by heleny** [comment]
This is the body of my cartfile: 
**"github "Alamofire/Alamofire" == 4.0
github "SwiftyJSON/SwiftyJSON" ~> 2.3.0**
"

I am running this command: 
**"carthage build --no-skip-current".**  

Here are my machine's settings:
xcrun version 32.

Xcode command line tool version:
xcode-select version 2347.

xcodebuild -version:
Xcode 8.3.3
Build version 8E3004b

Thank you,
Helen

**Comment by blender** [comment]
Any indications in the build logs? Note the line just before the build process hangs: 
```
*** xcodebuild output can be found in /var/folders/h4/1slt67613tx6c_xdd4ffp9nw0000gn/T/carthage-xcodebuild.XvG2pW.log
```

**Comment by heleny** [comment]
I have checked the log is empty though.

**Comment by blender** [comment]
I have tried with your same version of Xcode and Alamofire 4.0.0 and I don't have your issue.

I suggest deleting the carthage folder and the caches in 
```
~/Library/Caches/carthage
~/Library/Caches/org.carthage.carthage
~/Library/Caches/org.carthage.CarthageKit
```

**Comment by heleny** [comment]
I deleted all these folders and the xcode cach folder at ~/Library/Developer/Xcode/DerivedData, and then reboot my machine, same outcome.  I'm still getting timed out with xcodebuild.  

@blender what version of Carthage did you use?  v0.23.0?

Any carthage command will lead to timed out.  For example, "carthage build --no-skip-current", or "carthage update"...

**Comment by heleny** [comment]
I also deleted this folder: /Library/Framework/CarthageKit.framework/ and uninstall Carthage and then re-install.  Same result...

**Comment by mdiep** [comment]
Does it always fail with this error?

```
xcodebuild timed out while trying to read Alamofire.xcworkspace 😭
```

`xcodebuild` has bugs where it hangs sometimes. Sometimes you can work around it by opening the workspace in Xcode once.

**Comment by heleny** [comment]
Yes, always.

**Comment by blender** [comment]
can you run for both your project and for Alamofire

```
xcrun xcodebuild clean -showBuildSettings -skipUnavailableActions
xcrun xcodebuild -list
```

and see if any of these two commands hang?

also can you please run 

```
xcode-select -p
```

and check that it's pointing to the correct Xcode?

**Comment by heleny** [comment]
Both commands run, but it takes a while.  
```
xcode-select -p
```
does point to the right xcode, which is Xcode 8.3.3.  
I'm going to uninstall Xcode and carthage, and then reinstall them again. I ask one of my colleagues to test it for me... he is also running the latest carthage and Xcode, apparently, it works for him.

**Comment by heleny** [comment]
I have reinstalled Xcode 8.3.3 and carthage, the same issue remained.  
The only working version works for me is Xcode 7.3 and Carthage 0.18.1.  

Is there anything you would suggest me to do?  It's frustrating...

**Comment by mdiep** [comment]
This isn't really a Carthage issue—it's an Xcode issue that Carthage can't work around. I'm not sure what to suggest. 😞

**Comment by blender** [comment]
> Both commands run, but it takes a while.

How much is a while?

Carthage has a 60 seconds timeout to prevent Xcode from hanging indefinitely.  See https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/BuildSettings.swift#L45

**Comment by blender** [comment]
I suggest you build Carthage from source and change the timeout for your case. See if this helps.

**Comment by dcaunt** [comment]
In the past I've had some luck toggling the Shared Scheme box for the offending project/workspace. I know it's not ideal, but once Xcode gets past the timeout and lists the schemes, it usually continues to do so without the timeout.

**Comment by heleny** [comment]
> How much is a while?
@blender 2 mins. 
I will try to build from the source and change the timeout.  
Thank you all.

**Comment by heleny** [comment]
@blender Changing time out works.  Thank you!
