### ISSUE TITLE
Feature Request: Prune old build/checkout data for libraries that are no longer in Cartfile.resolved

### ISSUE THREAD

**Issue by klundberg** [Carthage/Carthage#2023]
* `carthage version`: 0.23
* `xcodebuild -version`: 8.3.2
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

I'd like to be able to automatically remove all libraries from the carthage subfolders that are no longer part of `Cartfile.resolved`. If for some reason I decide to remove a dependency in favor of another, this would make sure the old one isn't still available in framework search paths, or tools that might enumerate all the existing carthage checkouts won't pick up stale ones.

I would prefer something like this to just blowing away the entire folder, since I don't want to re-checkout stuff I need and I don't want to rebuild frameworks that can be preserved with `--cache-builds`

Is there demand for this sort of feature? If I or someone else were to implement it, would it make sense as a flag on `carthage update`/`carthage build`/`carthage bootstrap`, or would a `carthage prune` command be more appropriate?

**Comment by Lutzifer** [comment]
We ran into this same issue, is there any progress on this?

**Comment by mdiep** [comment]
PRs welcome. ☺️ 

It would probably makes sense to have both as a flag and as a command.
