### ISSUE TITLE
Include multiple frameworks in binary dependency

### ISSUE THREAD

**Issue by MikeKasperlik** [Carthage/Carthage#2024]
* `carthage version`:  0.23.0
* `xcodebuild -version`: Xcode 8.3.3 Build version 8E3004b
*  `carthage(use_binaries: true, platform: "iOS")`

We have the following project structure:
- FrameworkA: No dependencies
- FrameworkB: 
  - FrameworkA
  - Some other third party frameworks
- App
  - FrameworkB

Is there a way to include all dependencies in the binary distributed frameworkB without having having to worry about syncing the cartfile contents from frameworkB to the app?

Both frameworks are hosted on our own servers and are fetched via the `binary ...json` approach. 

My idea was to include the following command to our framework build process:
```
$ carthage archive --project-directory . FrameworkB FrameWorkA Realm RealmSwift ProtocolBuffers CryptoSwift
```
 instead of only doing (current state, working)
```
$ carthage archive --project-directory . FrameworkB
```

I then get the error printed below and have no Idea how to tackle this. The only solution right now is to archive only the frameworkB itself and add all dependencies to the main apps cartfile, which is not optimal.

The generated zip file from `$ carthage archive --project-directory . FrameworkB FrameWorkA Realm RealmSwift ProtocolBuffers CryptoSwift` looks correct to me, has all frameworks in the `Carthage/Builds/iOS/` folder but something seems to be broken there.

**Cartfile**

In FrameworkA:

```
Nothing here.
```

In FrameworkB:
```
github "realm/realm-cocoa" ~> 2.8.3
github "alexeyxo/protobuf-swift" ~> 3.0.10
binary "https://outinternalrepo.com/frameworkA.json" ~> 1.1
github "krzyzanowskim/CryptoSwift" ~> 0.6.9
```

In our app
```
binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" ~> 3.5
github "marketplacer/keychain-swift" ~> 8.0
github "SnapKit/SnapKit" ~> 3.2.0
binary "https://outinternalrepo.com/frameworkB.json" ~> 2.2.8
```

**Carthage Output**
```
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.39.2/fastlane_core/lib/fastlane_core/ui/interface.rb:143:in `shell_error!': [!] Exit status of command 'carthage bootstrap --platform iOS' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
*** Checking out keychain-swift at "8.0.3"
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
*** Downloading binary-only framework frameworkB at "https://outinternalrepo.com/frameworkB.json"
*** Downloading frameworkB.framework binary at "2.2.8"
Unable to determine framework Swift version.
```

**Comment by MikeKasperlik** [comment]
Figured out that the Frameworks embedded in the `FrameworkB.zip` are missing their respective `Framework-Swift.h` file. How comes that the `carthage archive` command misses them?

**Comment by mdiep** [comment]
> Is there a way to include all dependencies in the binary distributed frameworkB without having having to worry about syncing the cartfile contents from frameworkB to the app?

No.

> Both frameworks are hosted on our own servers and are fetched via the `binary ...json` approach

`binary` dependencies don't currently support dependencies of their own. (PRs welcome for that.)

> Figured out that the Frameworks embedded in the FrameworkB.zip are missing their respective Framework-Swift.h file. How comes that the carthage archive command misses them?

That's odd. You're sure the headers are there in the originals?

**Comment by MikeKasperlik** [comment]
>>Figured out that the Frameworks embedded in the FrameworkB.zip are missing their respective Framework-Swift.h file. How comes that the carthage archive command misses them?
>
>That's odd. You're sure the headers are there in the originals?

If I include this dependencies in the main app (also via carthage), they have this `-swift.h` file and as far as I understand the Carthage source, this headers are read to determine the swift version.

I assume that these files somehow get removed during compile with `carthage build`. I investigate this further and will report back / create a PR if I find a solution.

**Comment by wqzhang123** [comment]
@MikeKasperlik I have the same issue, missing the framework's -Swift.h file. Any solution yes?
