### ISSUE TITLE
Moving submodule from one user to another

### ISSUE THREAD

**Issue by rob-nash** [Carthage/Carthage#2028]
* `carthage version`: 0.23.0
* `xcodebuild -version`: Xcode 8.3.3 Build version 8E3004b
* Are you using `--no-build`? yes
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? yes
* Are you using `--cache-builds`? no

When changing Cartfile A to Cartfile B I got the below output.

**Cartfile A**
```
git "git@bitbucket.org:swiftcraft/storage.git" "master"
git "git@bitbucket.org:swiftcraft/interface.git" "master"
git "git@bitbucket.org:swiftcraft/styling.git" "master"
git "ssh://git@bitbucket.org/rob-nash/rotarywheelcontrol.git" "develop"
```

**Cartfile B**
```
git "git@bitbucket.org:swiftcraft/storage.git" "master"
git "git@bitbucket.org:swiftcraft/interface.git" "master"
git "git@bitbucket.org:swiftcraft/styling.git" "master"
git "ssh://git@bitbucket.org/robdashnash/rotarywheelcontrol.git" "develop"
```

Carthage is still attempting to use the older url.

**Carthage Output**
```
A shell task (/usr/bin/env git submodule --quiet update --init --recursive) failed with exit code 1:
repository access denied.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@bitbucket.org:rob-nash/rotarywheelcontrol.git' into submodule path '/Users/robertnash/Code/WDO Events/wdo/Carthage/Checkouts/wdo_entrysubmission/Carthage/Checkouts/rotarywheelcontrol' failed
Failed to clone 'Carthage/Checkouts/rotarywheelcontrol'. Retry scheduled
repository access denied.
fatal: Could not read from remote repository.
```

I did rm -r ~/Library/Caches/org.carthage.CarthageKit/
I did rm -r ${SRCROOT}/Carthage/Checkout
I did rm ${SRCROOT}/Cartfile.resolved

After this, git status showed no change to .gitmodules. So I changed my Cartfile to Cartfile C

**Cartfile C**
```
git "git@bitbucket.org:swiftcraft/storage.git" "master"
git "git@bitbucket.org:swiftcraft/interface.git" "master"
git "git@bitbucket.org:swiftcraft/styling.git" "master"
```

and run carthage update.

At this point, I could see the .gitmodules file had been updated to show the removal of the old url git@bitbucket.org:rob-nash/rotarywheelcontrol.git. Great!

I then changed my Cartfile back to Cartfile B and run carthage update.

git status showed .gitmodules had inserted an entry for  rotarywheelcontrol.git with the correct url git@bitbucket.org:robdashnash/rotarywheelcontrol.git. Great!

So I fixed the issue but it's worth noting here that changing the username of a submodule isn't enough for Carthage.

**Comment by jdhealy** [comment]
Thanks for reporting this: first glance, seems like #285/#569
