### ISSUE TITLE
Compiler version Checks Ignore Semver 

### ISSUE THREAD

**Issue by aaroncrespo** [Carthage/Carthage#2031]
I had some code locally compiled with Xcode9 beta 1 after updating to beta 2 I received:

"Incompatible Swift version - framework was built with swiftlang-900.0.43 clang-900.0.22.8 and the local version is swiftlang-900.0.45.6 clang-900.0.26."

https://github.com/Carthage/Carthage/pull/1984 made it so Carthage checked compiler version instead of Swift version. In the above error the major and minor versions match and only patch and tiny differ. 

Not knowing if a clang/swift patch versions signal changes in compiled output. If not maybe Carthage should treat these compilers as compatible with each other. With that I'm not sure if this is actually an issue since I can see even a patch version of a compiler should invalidate binary compatibility/interoperability leaving it open to discussion.

**Comment by mdiep** [comment]
Without ABI stability, compiled frameworks aren't compatible between different versions of Swift—even if only the patch differs. So this is the correct behavior.

**Comment by joshrl** [comment]
Wondering if we can revisit this -- seems to me the incompatibility check on a binary should be a warning not an error since, really, its going to fail in the app build later if there is a true incompatibility.

**Comment by blender** [comment]
This is still valid as downstream dependencies of frameworks will fail at link time causing Carthage to stop.
