### ISSUE TITLE
[Travis] Timeout before XCTest from `xcodebuild` with job `CI_BUILD_TEST`.

### ISSUE THREAD

**Issue by jdhealy** [Carthage/Carthage#2033]
@BobElDevil’s https://travis-ci.org/Carthage/Carthage/jobs/247271517 · succeeds
@ikesyo’s https://travis-ci.org/Carthage/Carthage/jobs/247103601#L4056 · fails:
```
Touch /Users/travis/Library/Developer/Xcode/DerivedData/Carthage-gwijrkzmhiisecaxyectdfrqrwea/Build/Products/Release/CarthageKitTests.xctest
    cd /Users/travis/build/Carthage/Carthage
    /usr/bin/touch -c /Users/travis/Library/Developer/Xcode/DerivedData/Carthage-gwijrkzmhiisecaxyectdfrqrwea/Build/Products/Release/CarthageKitTests.xctest



No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

Both jobs use the exact same Travis cache archives¹ , and both jobs are from [members of the Carthage org](https://github.com/orgs/Carthage/people) allowing for decrypted environment variables².

Key difference: @ikesyo’s PRs with head branches on Carthage/Carthage fail, @BobElDevil’s PR with head branch from fork succeeds.

But, why?

1： …but, that should be irrelevant regardless — as of now, those caches seemingly only effect SwiftPM builds.
2： correct me if I'm wrong, but this should also be irrelevant — I believe the only encrypted variable [became unused with this commit](https://github.com/Carthage/Carthage/commit/c0447a5a78e1567a54484ac497333d9e3f0cd89e#diff-25e68639ab0a24abb2dbc3fac1726cc1L30).

**Comment by ikesyo** [comment]
It appears that `master` also fails.

https://travis-ci.org/Carthage/Carthage/builds/248866113
