### ISSUE TITLE
Use Fabric, Crashlytics and Answers with Carthage

### ISSUE THREAD

**Issue by Zyphrax** [Carthage/Carthage#2036]
Below are binary definitions for Fabric, Crashlytics and Answers.
Each JSON points to the latest zip file directly provided by Fabric.

Just add the following to your Cartfile.
```ruby
binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Fabric.json"
binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Crashlytics.json"
binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Answers.json"
```

I've mailed the Fabric team asking them if they're willing to maintain the JSONs.

**Comment by Zyphrax** [comment]
Most likely you won't need the Answers framework because it seems to be integrated in the Crashlytics framework. But it is available if you want to use it without Crashlytics.

Don't forget to add the items to your Plist. For more info see:
https://fabric.io/kits/ios/crashlytics/install
https://fabric.io/kits/ios/answers/install

**Do not** add the frameworks to the Carthage copy script!
Otherwise archiving your app will fail with a Mach-O error about entitlements.

Can I maybe create a wiki for this? A lot of people are still using CocoaPods because Fabric doesn't officially support Carthage. Otherwise they can find this post for more information.

**Comment by Prince2k3** [comment]
@Zyphrax I think this should be added some where so that is it known there is some support. Right now this is only found through Google search at best

**Comment by eyeoashephard** [comment]
FYI @Zyphrax - I had to install the Answers framework in order to successfully reference it within my code, but only had to import Crashlytics as a module.

Other than that, works well! Thanks.

**Comment by dmiluski** [comment]
@Zyphrax Is it possible to just point to a GitHub releases to drive this rather than a separately hosted son file?

**Comment by Zyphrax** [comment]
@dmiluski Carthage needs a JSON file to describe the versions of the framework. As far as I know it isn't possible to directly use a zip file or GitHub releases page reference.

**Comment by ncatta** [comment]
Hello !  

Is it possible to provide JSON files for MacOS release ?

Thanks !

**Comment by mdiep** [comment]
Yes. Please refer to the Carthage documentation about the `binary` dependency specifier.

**Comment by Zyphrax** [comment]
@ncatta The MacOS specs are available at:
https://github.com/Building42/Specs/tree/master/Carthage/macOS

**Comment by RafaelPlantard** [comment]
When using `gym` from `fastlane` I'm getting the following error:
![screen shot 2018-01-16 at 12 15 29 pm](https://user-images.githubusercontent.com/5968478/34993273-fedf518a-fab6-11e7-9a33-d4b004aa8ba1.png)

**Comment by rgkobashi** [comment]
Thanks @Zyphrax for providing this! Very useful. Btw, did you receive response from Fabric? if they are going to maintain those JSONs

**Comment by Zyphrax** [comment]
@rgkobashi I've brought the specs to the attention of the Fabric team, but they don't seem to have made steps to host their own Carthage specs yet. For now I guess my repo will have to do 🙂

**Comment by dmiluski** [comment]
Hi @Zyphrax , I was attempting to provide a solution in Carthage here to drive spec creation from Github api for releases?
https://github.com/Carthage/Carthage/pull/2360

**Comment by Zyphrax** [comment]
@dmiluski For Fabric / Crashlytics that would be difficult. There doesn't seem to be a nice central repository for their releases. They seem to host the releases on their Amazon S3 infrastructure, not something like GitHub.

**Comment by prsolucoes** [comment]
Hi,

binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Fabric.json"
binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Crashlytics.json"

Dont work more.

Any working solution?

Thanks.

**Comment by prsolucoes** [comment]
I found the new URLs:

https://raw.githubusercontent.com/Building42/Specs/master/Carthage/iOS/Fabric.json
https://raw.githubusercontent.com/Building42/Specs/master/Carthage/iOS/Crashlytics.json

Thanks.

**Comment by Zyphrax** [comment]
@prsolucoes Sorry I forgot about this post. Because of the different platforms I had to do a bit of a clean up of the repository. The correct urls are these:

```ruby
binary "https://building42.github.io/Specs/Carthage/iOS/Fabric.json"
binary "https://building42.github.io/Specs/Carthage/iOS/Answers.json"
binary "https://building42.github.io/Specs/Carthage/iOS/Crashlytics.json"
```

You can always find the latest info at: https://building42.github.io/Specs/
I've also updated the first post in this topic.

Sorry for the incovenience!

**Comment by prsolucoes** [comment]
@Zyphrax 

I need put the answers framework?

Thanks.

**Comment by Zyphrax** [comment]
@prsolucoes The Answers framework is optional. Crashlytics does require Fabric.

**Comment by prsolucoes** [comment]
Thanks. Im updating all. Until now it is working. If i have any problems, i will post here.

**Comment by jiebe** [comment]
Thanks for the post...also came upon this issue last night but have resolved now. Thanks!

**Comment by SeRG1k17** [comment]
@Zyphrax How we can resolve it?
Crashlytics has moved the submit binary outside of Crashlytics.framework directory as of 3.4.1. Please change :crashlytics_path to `<PODS_ROOT>/Crashlytics/submit`
