### ISSUE TITLE
Bitcode enabled archive fails iTunes Connect processing

### ISSUE THREAD

**Issue by ctee-cormant** [Carthage/Carthage#2037]
* `carthage version`: 0.23.0
* `xcodebuild -version`: 9 beta 2
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "cruffenach/CRToast" 
github "RNCryptor/RNCryptor"
github "thii/FontAwesome.swift" "master"
github "kishikawakatsumi/KeychainAccess"
github "ashleymills/Reachability.swift" "v3"
github "rhodgkins/SwiftHTTPStatusCodes" 
github "Alamofire/Alamofire"
github "Alamofire/AlamofireImage" ~> 3.1
github "Hearst-DD/ObjectMapper"
github "slackhq/SlackTextViewController"
github "SnapKit/SnapKit" ~> 3.0.2
github "DaveWoodCom/XCGLogger" ~> 5.0.1
```

We've been trying to submit a build with bitcode enabled but so far, bitcode generation keeps on failing with CRToast.

Here's corresponding log from trying to export the archive for Ad Hoc deployments (troubleshooting based on this [article](https://developer.apple.com/library/content/technotes/tn2432/_index.html)) with bitcode compilation enabled. Not sure if this is CRToast specific or if I missed some carthage config but I decided to ask here first for help anyway. Thanks!

NOTE: I've already got `carthage copy-frameworks` set in the project's build phases.

****UPDATE**: Indicate that I've been exporting for ad hoc deployments to troubleshoot a failed iTunes Connect upload.

```
    "/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" "-arch" "armv7" "-dylib" "-compatibility_version" "1.0.0" "-current_version" "1.0.0.0.0" "-install_name" "@rpath/CRToast.framework/CRToast" "-ios_version_min" "8.0.0" "-rpath" "@executable_path/Frameworks" "-rpath" "@loader_path/Frameworks" "-dead_strip" "-syslibroot" "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk" "-sdk_version" "11.0.0" "-filelist" "/private/var/folders/st/jt22rm4j2mv6_t54x7trg5540000gn/T/CRToastqRK_MG/CRToast.armv7.out.LinkFileList" "-ignore_auto_link" "-allow_dead_duplicates" "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation.tbd" "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/lib/libobjc.A.tbd" "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/lib/libSystem.B.tbd" "/Applications/Xcode-beta.app/Contents/Developer/Platf
2017-06-29 07:41:47 +0000  orms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation.tbd" "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics.tbd" "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit.tbd" "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/lib/libobjc.A.tbd" "/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/lib/darwin/libclang_rt.ios.a" "-o" "/private/var/folders/st/jt22rm4j2mv6_t54x7trg5540000gn/T/CRToastqRK_MG/CRToast.armv7.out" 
    -= Output =-
    Undefined symbols for architecture armv7:
      "___llvm_profile_runtime", referenced from:
          __hidden#70_ in 1.o
          __hidden#70_ in 2.o
          __hidden#70_ in 3.o
          __hidden#70_ in 4.o
          __hidden#70_ in 5.o
    ld: symbol(s) not found for architecture armv7
    Exited with 1
    
    
    error: Failed to compile bundle: /var/folders/st/jt22rm4j2mv6_t54x7trg5540000gn/T/CRToastqRK_MG/CRToast.armv7.xar
```

**Comment by ikesyo** [comment]
Maybe you should need add the entries to your export option plist for `xcodebuild -exportArchive -exportOptionsPlist` option.

```plist
    <key>compileBitcode</key>
    <false/>
```

**Comment by ctee-cormant** [comment]
@ikesyo yes, the archive exports successfully if bitcode compilation is disabled. But I was trying to get Apple's "app thinning" feature to work, so I need to enable it.

**Comment by ikesyo** [comment]
I understand that you are saying about `Ad Hoc deployments` so that should not be related to app thinning.

**Comment by ikesyo** [comment]
Anyway I don't think this is related to Carthage, and should be the problem on CRToast library.

**Comment by ctee-cormant** [comment]
Sorry, I should have been more specific with why I was doing ad hoc deployments. I followed troubleshooting steps from this [article](https://developer.apple.com/library/content/technotes/tn2432/_index.html) because my build had failed iTunes Connect processing. It said to try exporting for ad hoc deployment as processing is similar to when you upload archives to iTunes Connect. 

I'll update the issue details above to better reflect this.

**Comment by ikesyo** [comment]
I'm still not sure this is really related to Carthage. You are using a beta version of Xcode so I recommend you to file a bug report on https://bugreport.apple.com/.
