### ISSUE TITLE
How to install a specific version of carthage?

### ISSUE THREAD

**Issue by abbeyjackson** [Carthage/Carthage#2039]
* `carthage version`: 0.18.1
* `xcodebuild -version`: 8.2.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

I am trying to install carthage v0.20.1. I used `brew install carthage@0.20.1` but I receive the error: 
    Error: No available formula with the name "carthage@0.20.1" 

My colleague is running this version so it exists. Am I missing a step? I ran this after it failed the first time:

     git -C "$(brew --repo homebrew/core)" fetch --unshallow

But it still failed the second time.

**Comment by jdhealy** [comment]
Off the top of my head (on mobile), `curl https://github.com/Homebrew/homebrew-core/raw/6d42f6048c327300c2969e23e06f75dd061ad34b/Formula/carthage.rb --output carthage.rb && brew install --force carthage.rb` should download the formula and download the precompiled bottle, overwriting what carthage might already be downloaded from brew.

**Comment by ikesyo** [comment]
Homebrew does not support installing a specific version normally. So as @jdhealy said you need to point a specific revision of the formula.

**Comment by ikesyo** [comment]
Just `brew install https://github.com/Homebrew/homebrew-core/raw/6d42f6048c327300c2969e23e06f75dd061ad34b/Formula/carthage.rb` should work.
