### ISSUE TITLE
Cannot use framework built by Carthage until I perform a touch on a bridging-header-file 

### ISSUE THREAD

**Issue by CharlesGrimont** [Carthage/Carthage#2040]
* `carthage version`: 0.23.0
* `xcodebuild -version`: Xcode 8.3.3 Build version 8E3004b
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no 
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "convertigo/C8oSDKiOS" "2.2.0-beta1-carthage"
```

**Carthage Output**
```
$ carthage update --platform iOS
*** Fetching SwiftyJSON
*** Fetching couchbase-lite-ios
*** Fetching Alamofire
*** Fetching AEXML
*** Checking out Alamofire at "4.4.0"
*** Checking out SwiftyJSON at "3.1.4"
*** Checking out couchbase-lite-ios at "04fbe5e6a522f375f2c9e33d26f1c98a1cfe2455"
*** Checking out AEXML at "4.1.0"
*** Checking out C8oSDKiOS at "2.2.0-beta1-carthage"
*** xcodebuild output can be found in /var/folders/yw/p4g_3w6x1xx0hfth3v8l62br0000gp/T/carthage-xcodebuild.XurNvG.log
*** Building scheme "AEXML iOS" in AEXML.xcodeproj
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "CBL iOS framework - Carthage" in CouchbaseLite.xcodeproj
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
*** Building scheme "C8oSDKiOS" in C8oSDKiOS.xcodeproj
```
# Context #
I have built a swift framework that i'm trying to import via Carthage into a Single View iOS-swift Application.

when running:
    $ carthage update --platform iOS
everything works fine

Then i open my .xcodeproj, and when i'm trying to build my app an error occurred:

    swiwt-carthage-test/Carthage/Checkouts/C8oSDKiOS/C8oSDKiOS/Couchbase-Lite-Bridging-
    Header.h:10:9: 'CBLRegisterJSViewCompiler.h' file not found'

When I perform a touch or change anything on this file error disappeared and everything works fine

# Steps to reproduce # 
    $ git clone https://github.com/CharlesGrimont/swiwt-carthage-test.git
    $ cd swiwt-carthage-test
    $ carthage update --platform iOS

As files built by carthage are already referenced by xcodeproj you do not need do drag and drop them again 

    $ xcodebuild build -project m3test.xcodeproj -scheme m3test  -destination 'platform=iOS 
      Simulator,name=iPhone 7 Plus,OS=10.3.1'

At this step an error will occurred ....

# Steps to resolve #
    cd Carthage/Checkouts/C8oSDKiOS/C8oSDKiOS/
    touch Couchbase-Lite-Bridging-Header.h

Have you any ideas ?

Thanks a lot.

CC: @nicolas-albert

**Comment by nicolas-albert** [comment]
Note that restore the *Couchbase-Lite-Bridging-Header.h* timestamp, clean and build cause the issue again : `touch -r Info.plist Couchbase-Lite-Bridging-Header.h`.
Weird behavior.

**Comment by BobElDevil** [comment]
You need to mark the header public so it gets exported with the framework when it is built by carthage. 

![screen shot 2017-07-05 at 3 10 03 pm](https://user-images.githubusercontent.com/1904161/27887221-71bcdc0c-6194-11e7-98a6-91fe4dcf3a91.png)


Closing this as it's not a Carthage issue.

**Comment by CharlesGrimont** [comment]
Thanks for your reply ...
but this is not fixing anything
