### ISSUE TITLE
Targets built with coverage data in Xcode 9

### ISSUE THREAD

**Issue by frankschlegel** [Carthage/Carthage#2056]
One of my test builds I just submitted to iTunes Connect (built with Xcode 9) failed processing with the following message:

> **Invalid Bundle** - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

This is caused by [this issue](https://forums.developer.apple.com/thread/81893). The new Xcode seems to build coverage data into all builds, not only for testing. From the changelog:

> Schemes with Code Coverage enabled (in the Test action) will now always build with Code Coverage, including for the Run and Launch actions. This reduces the need to build multiple versions of the application. Users who require code coverage to be off for their non-test actions can explicitly use a separate scheme with coverage disabled. (31848014)

When building frameworks during the "Archive" action Xcode seems to handle that. But since Carthage dependencies are built externally and copied into the bundle later, they still contain coverage data.

Somehow the Carthage build process needs to make sure that gathering coverage data is disabled during build, even though it's enabled in the project.

**Comment by ikesyo** [comment]
Thanks for filing the issue! I've submitted #2057 to address this.

**Comment by frankschlegel** [comment]
Wow, that was fast, thanks!

**Comment by ikesyo** [comment]
https://github.com/Carthage/Carthage/pull/2057#issuecomment-314432344

Looks like we will not be able to make `xcodebuild` to disable code coverage when building using command line options unfortunately.

**Comment by aabosh** [comment]
Running into the same issue.

**Comment by dbmrq** [comment]
I forked these two repositories, disabled coverage data and edited my Cartfile to use the forked versions:

https://github.com/dbmrq/RSBarcodes_Swift/commit/4306df0f32b251929117a366d67883fd3b6a25d8

https://github.com/dbmrq/SWXMLHash/commit/2f58a1981d09fee9908feac5b092c89312e8e7ed

I'm still getting the "Disallowed LLVM instrumentation" error though. Is there anything else I have to do? :/

**Comment by insidegui** [comment]
I'm having the same issue. Tried the same as @dbmrq, still getting the error from iTC.

**Comment by dbmrq** [comment]
I don't know much about how Carthage works, so I'm sorry if this is a silly question, but wouldn't it be possible for Carthage to use the Archive action when building the frameworks?

With the 2 frameworks I mentioned above I just disabled the `Skip Install` setting, archived, exported and copied the resulting frameworks myself.

I looked around here and found this: https://github.com/Carthage/Carthage/issues/833#issuecomment-145955350

So it seems this was an option for @mdiep. Why was it dismissed?

**Comment by jdhealy** [comment]
> I looked around here and found this: https://github.com/Carthage/Carthage/issues/833#issuecomment-145955350
>
> So it seems this was an option for @mdiep. Why was it dismissed?

From https://github.com/Carthage/Carthage/issues/169#issuecomment-68624884 — referred to by @ikesyo in <https://github.com/Carthage/Carthage/pull/2057#issuecomment-314444547>:

> Apparently `xcodebuild archive` does not work for the simulator SDK

**Comment by dbmrq** [comment]
Ah, I don't know how I missed that.

It seems that the `-exportFormat` option mentioned in https://github.com/Carthage/Carthage/issues/169#issuecomment-68624884 doesn't exist anymore though, and I did manage to successfully archive the frameworks I mentioned with `xcodebuild archive`. 

I just don't understand the simulator SDK part… that doesn't even come up for me:

```zsh
iOS/RSBarcodes_Swift [master] > xcodebuild archive RSBarcodes
xcodebuild: error: Unknown build action 'RSBarcodes'.
iOS/RSBarcodes_Swift [master] > xcodebuild archive -scheme RSBarcodes
=== BUILD TARGET RSBarcodes OF PROJECT RSBarcodes WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files

# …

** ARCHIVE SUCCEEDED **
```

**Comment by jdhealy** [comment]
Preventing the Carthage behavior to merge device and simulator builds into “one fat binary”, `xcodebuild archive` for simulator is still prohibited in Xcode 9.0.X (betas, as is the current extent of our knowledge).

```
$ xcodebuild -destination 'generic/platform=iOS Simulator' archive -scheme RSBarcodes
2017-09-11 00:26:09.026 xcodebuild[34407:8122792] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-13238.4/IDEFoundation/Execution/RunDestinations/IDERunDestinationManager.m:789
Details:  There are multiple run destinations that support deployment for the current scheme; selecting anyObject: {(
    <IDERunDestination:0x7fb1682bd340:'Generic iOS Simulator Device'>,
    <IDERunDestination:0x7fb1682c5c20:'Generic iOS Device'>
)}
Object:   <IDERunDestinationManager: 0x7fb168112390>
Method:   -genericRunDestinationForRunDestination:scheme:schemeCommands:executionEnvironment:requiresSupportsArchiving:requiresDeploymentPlatformMatches:allowMultipleRunDestinationMatches:allowNoRunDestinationMatches:error:
Thread:   <NSThread: 0x7fb163416180>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2017-09-11 00:26:09.038 xcodebuild[34407:8122792] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-13238.4/IDEFoundation/Execution/Schemes/IDEScheme.m:1431
Details:  Scheme <IDEScheme:0x7fb16834af00:'RSBarcodes'> was asked to build and archive, but the run destination <IDERunDestination:0x7fb1682bd340:'Generic iOS Simulator Device'> is not a deployment platform and this action shouldn't have been allowed.
Object:   <IDEScheme: 0x7fb16834af00>
Method:   -schemeOperationForSchemeOperationParameters:buildLog:overridingProperties:overridingBuildConfiguration:dontActuallyRunCommands:restorePersistedBuildResults:deviceAvailableChecker:error:completionBlock:
Thread:   <NSThread: 0x7fb163416180>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
xcodebuild: error: Failed to build project RSBarcodes with scheme RSBarcodes.
	Reason: You cannot archive for the iOS Simulator platform.

$ xcodebuild -version
Xcode 9.0
Build version 9M214v
```

**Comment by dbmrq** [comment]
Ah, I see. I didn't realize Carthage required the targer to be built for the simulator.

We're back to the first question then, why it still doesn't work after disabling coverage data.

**Comment by frankschlegel** [comment]
@dbmrq I went to the `Carthage/Checkout` of the affected projects, opened their project files in Xcode and unchecked the build setting. Then I did a `carthage build` and the problem was gone. Mind that the setting gets reset when doing a `update` or `bootstrap`.

As for the `archive` action: I also think this is the way to go. You could use `build` for the simulator part and `archive` for the ARM binary. The simulator binary gets stripped in the build phase anyways.
I tried to implement that in Carthage myself, but unfortunately the paths for the archived builds are different and I didn't have to time to dig deeper into Carthage.

**Comment by dbmrq** [comment]
@frankschlegel Aha! I checked the `Checkout` directory and the coverage data setting was still there, even if I changed it in my fork… so I tried specifying my commit in the Cartfile and Carthage complained about it not being in `Caches/org.carthage.CarthageKit`. I deleted that file and now it's all working fine. Thanks! @insidegui You might want to look into that.

About `xcodebuild archive`, I was just thinking about that... when you add a new Run Script Phase on Xcode there's the option to "run script only when installing". So instead of building a fat binary for all architectures it could be possible to use `xcodebuild archive` to build a different framework just for App Store submission. Then there would be something like the current `copy-frameworks` script, but it would use that "run script only when installing" option to replace the simulator frameworks with the archived ones. I guess this would add a little more complexity, but I think doing things the way Apple intends them to be done makes it worth it and would save other headaches on the long run. It would be even better if this could all be done with a single script, but I still think it's worth it.

> unfortunately the paths for the archived builds are different

`xcodebuild` allows you to specify the archive path with `-archivePath`, so that might help.

```
-archivePath xcarchivepath
Specifies the path for the archive produced by the archive action, or specifies the archive that should be exported when -exportArchive is passed.
```

**Comment by insidegui** [comment]
@dbmrq I manually set the "Enable Code Coverage Support" to NO on all dependencies and it worked :)

**Comment by zirinisp** [comment]
Has anyone builded a script to automate this? Is it even possible?

As waiting for all frameworks to disable code coverage or forking them and setting it ourselves will take some time.

**Comment by mbuchetics** [comment]
This is a big issue. It should at least be acknowledged in the readme.

**Comment by frankschlegel** [comment]
@zirinisp No real script, but I use grep to find the affected frameworks, fix the files and `build` them again:
`grep -R "codeCoverageEnabled" Carthage`

**Comment by zirinisp** [comment]
@frankschlegel Lifesaver for the moment. Hope this will be sorted soon.

**Comment by gunterhager** [comment]
Finding the affected frameworks is much faster when using: 
`grep -R "codeCoverageEnabled" --include *.xcscheme Carthage`
It just has to grep the `*.xcscheme` files.

**Comment by gunterhager** [comment]
OK, one more thing: if you want to do a quick fix of all frameworks affected:

`grep -lR "codeCoverageEnabled" --include *.xcscheme Carthage  | xargs sed -i '' -e 's/codeCoverageEnabled = "YES"/codeCoverageEnabled = "NO"/g'`

Then do a `carthage build` and you're good to submit i think.

**Comment by zirinisp** [comment]
@gunterhager thank you.

Do you want to create a reply on https://stackoverflow.com/questions/46160518/xcode-9-carthage-itunes-connect-error-invalid-bundle-disallowed-llvm-instr or should I do it.

**Comment by zirinisp** [comment]
Why not add a parameter that is running this script after updating the dependencies and before building them.

**Comment by muukii** [comment]
@gunterhager
Thanks for the nice script!
And, I have a question.
Can we also disable coverage flag with exporting `XCODE_XCCONFIG_FILE`?

**Comment by jdhealy** [comment]
Good question, @muukii — the answer is no and I’ll clarify:

There are two types of instrumentation for Code Coverage: [GCC Instrumentation][gcc] and [LLVM Instrumentation][llvm]. 

Disabling [GCC Instrumentation][gcc] for code coverage can be done via an xcconfig with both `GCC_INSTRUMENT_PROGRAM_FLOW_ARCS` and `CLANG_ENABLE_CODE_COVERAGE ` set `NO`.

Neither of those above settings (either in separate on combined) can disable [LLVM Instrumentation][llvm] for code coverage (in Xcode 9.0.X betas or GM, as is the current extent of our knowledge), to achieve that we would seemingly need the ability to remove particular flags from the Other C Flags (`OTHER_CFLAGS`) build setting string, particularly (`-fprofile-instr-generate` & `-fcoverage-mapping`). And we don’t have that ability.

[gcc]: https://developer.apple.com/library/content/qa/qa1964/_index.html#//apple_ref/doc/uid/DTS40017675-CH1-SOURCECODE1
[llvm]: https://developer.apple.com/library/content/qa/qa1964/_index.html#//apple_ref/doc/uid/DTS40017675-CH1-SOURCECODE2

**Comment by ikesyo** [comment]
I'm now tackling this with using `archive` action for device builds.

**Comment by skreutzberger** [comment]
Thanks for your PR @NachoSoto - today SwiftyBeaver 1.4.1 was released which disabled code coverage.

**Comment by mixmastertube** [comment]
This script did the trick for me.

find Carthage -type f -name "*.xcscheme" -print0 | xargs -0 perl -pi -e 's/codeCoverageEnabled = "YES"/codeCoverageEnabled = "NO"/g'

**Comment by ikesyo** [comment]
0.26 has been released.

https://github.com/Carthage/Carthage/releases/tag/0.26.0

**Comment by nasht** [comment]
Hey @ikesyo  -Thanks so much for the update. Am I right in my understanding that the `archive` directive is not going to solve the issue we face when we have specific versions of a third party framework with CodeCoverage set to YES? In this case, we still need to rely on scripts that modify the downloaded source before we build? Is this correct?

**Comment by eneko** [comment]
After running some tests with Carthage 0.26.2, seems like the issue is still there. With Code Coverage enabled in the schemes, the `otool` command finds the symbols in the framework.

```
$ carthage version
0.26.2
```

```
$ carthage build --no-skip-current --configuration Release
...
$ otool -l -arch all Carthage/Build/iOS/MyFramework.framework/MyFramework | grep __llvm_prf
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
$
```

Removing Code Coverage on the schemes seems to be the only way for the symbols to disappear:
```
$ carthage build --no-skip-current --configuration Release
...
$ otool -l -arch all Carthage/Build/iOS/MyFramework.framework/MyFramework | grep __llvm_prf
$
```

**Comment by ikesyo** [comment]
> otool -l -arch all

@eneko I think those are from simulator slices and they will be striped through `carthage copy-frameworks`. So that should not be an issue on App Store submission.

**Comment by eneko** [comment]
Thanks for the reply. We'll try again on Monday, hopefully it will work :)

**Comment by sarah-j-smith** [comment]
This issue is still there for me with v 0.27.0 for:
* https://github.com/jessesquires/JSQDataSourcesKit
* https://github.com/aws/aws-sdk-ios/tree/master/AWSCognitoIdentityProvider

I guess this issue is closed because its a _won't fix_ ....?

**Comment by ikesyo** [comment]
Carthage uses `Release` configuration by default so you don't need to specify it explicitly.
