### ISSUE TITLE
Private framework works with 0.23.0 and generate "Repository not found" with 0.24.0

### ISSUE THREAD

**Issue by TofPlay** [Carthage/Carthage#2058]
* `carthage version`: 0.24.0
* `xcodebuild -version`: Xcode 9.0 Build version 9M174d
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
git "git@github.com:MyCompany/MyFramework-iOS" == 1.0.37
```

**Carthage Output**
```
$ carthage update --platform iOS --no-use-binaries
*** Cloning MyFramework-iOS
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/com:MyCompany/MyFramework-iOS.git /Users/me/Library/Caches/org.carthage.CarthageKit/dependencies/MyFramework-iOS) failed with exit code 128:
remote: Repository not found.
fatal: repository 'https://github.com/MyCompany/MyFramework-iOS.git/' not found
```

**Comment by mdiep** [comment]
Well that URL doesn't look right in the shell task.

Does it work if you pass the `--use-ssh` flag?

**Comment by dcaunt** [comment]
Potentially caused by #1995

**Comment by TofPlay** [comment]
> Does it work if you pass the --use-ssh flag?

Yes it works with `--use-ssh` 👍 🙂

**Comment by blender** [comment]
I'll take care of this

**Comment by blender** [comment]
Hi, with the Cartfile you have provided Carthage executes correctly the following:

/usr/bin/env git clone --bare --quiet https://github.com/MyCompany/MyFramework-iOS.git 

Can you share more information?

**Comment by TofPlay** [comment]
@blender it's close source framework. I'm not authorised to give you more information. Sorry 😕

**Comment by blender** [comment]
@TofPlay I understand. Would be useful if you could come up with a name with a similar pattern to the actual name causing the problem.

**Comment by mdiep** [comment]
Can you try changing your Cartfile to `github "MyCompany/MyFramework-iOS" == 1.0.37` and running `carthage update --no-use-binaries`? I'm curious to see what error you get (or if you don't get an error).

**Comment by webfrogs** [comment]
Face the same problem.


Here is the error message, `IronThrone` is a private repository.:
```
*** Fetching IronThrone
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/ricebook/IronThrone.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/carl/Library/Caches/org.carthage.CarthageKit/dependencies/IronThrone)) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

I prefer to use ssh key instead of https.

**Comment by blender** [comment]
@webfrogs can you paste the Cartfile and Cartfile.resolved line for that repo?

**Comment by webfrogs** [comment]
Carfile:

`git "git@github.com:ricebook/IronThrone.git" "master"`

There is no Cartfile.resolved file because carthage failed.

**Comment by blender** [comment]
@webfrogs I believe Carthage is behaving correctly in your case. I see that it's trying to clone `https://github.com/ricebook/IronThrone.git` . Seems like your git client is having a hard time reading your credentials for https? If you want to use ssh try `--use-ssh`

**Comment by webfrogs** [comment]
It works with `--use-ssh` flag, Thanks.

But I think changing all GitHub repository url to https is not a very good idea, especially for private repositories.

**Comment by ikesyo** [comment]
> But I think changing all GitHub repository url to https is not a very good idea, especially for private repositories.

I understand your opinion, but FYI #1995 is an attempt to address #1644.

**Comment by webfrogs** [comment]
@ikesyo Got it. It seems that I should always use `--use-ssh` flag. A little bit inconvenient.

**Comment by mdiep** [comment]
I think this is working as expected.
