### ISSUE TITLE
`carthage update` *resolves* incompatible dependency requirements (it shouldn't)

### ISSUE THREAD

**Issue by NicholasTD07** [Carthage/Carthage#2067]
* `carthage version`: 0.24.0 (also tried a development build with commit https://github.com/Carthage/Carthage/commit/47c6559bbc473128b8d6f667da2f61de538112f2)
* `xcodebuild -version`:  Xcode 8.3.2 Build version 8E2002
* Are you using `--no-build`?  Yes
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

In the app we depends on a `networking` sdk and depends on two other dependencies which depend on the `networking` sdk. All managed by Carthage.

The problem is the app accepts any version of the networking sdk as long as it's compatible with `5.0.0` while the dependencies only accept the versions of networking sdk compatible with `4.0.0`.

Expected:
`carthage update` should fail and give a warning message about incompatible requirements.
Actual:
`cartahge update` resolves the dependency without any warning and the resolved version of the `networking` sdk is neither compatible with `4.0.0` nor with `5.0.0`.

Interestingly, when I created a demo project with similar setups (incompatible requirements), `carthage update` does fail and give the incompatible warning. So I figure, `cartahge update` is running into an edge case with our app's setup.

**Cartfiles**

Due to dependencies listed below are private repositories, I replaced the names with some dummy names. All repos under organazation `org-name` are "dummified". Plus the `AnotherInteralFramework` in the output log.

App:
```
git "git@github.com:org-name/networking.git" ~> 5.0.0
git "git@github.com:org-name/networking-dependency-one.git" ~> 2.0.1
git "git@github.com:org-name/networking-dependency-two.git" ~> 0.0.6
```
networking-dependency-one
```
git "git@github.com:org-name/networking.git" ~> 4.0.0
github "antitypical/Result" "3.1.0"
```
networking-dependency-two
```
git "git@github.com:org-name/networking.git" ~> 4.0.0
github "antitypical/Result" "3.1.0"
```

**Carthage Output**
```
$ carthage update --no-use-binaries --no-build --verbose
*** Fetching networking-dependency-one
*** Fetching networking-dependency-two
*** Fetching networking
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Alamofire
*** Fetching Result
*** Fetching Alamofire
*** Checking out networking at "0.0.9-Beta-1"
*** Checking out Alamofire at "3.1.3"
*** Checking out networking-dependency-one at "0.0.6"
*** Checking out networking-dependency-two at "2.0.1"
*** Checking out AnotherInteralFramework at "0.1.4-beta-1"
*** Checking out Result at "1.0.2"
```

If this helps, `AnotherInteralFramework` introduces `Alamofire`.

PS.
Thank all contributors for the great work to develop Carthage! Really appreciate the hard work poured into it.

**Comment by blender** [comment]
Can you paste your resolved file please?

**Comment by NicholasTD07** [comment]
@blender Would it help if I replace the info of private repos with the dummy info, like I did in the issue’s description?

**Comment by blender** [comment]
yes sure, as long as it's "dummy" correct

**Comment by NicholasTD07** [comment]
@blender cool. I will post that once I get access to the files.

**Comment by NicholasTD07** [comment]
@blender Sorry for the delay (got distracted by work 😂 ). Here's the resolved file.

```
github "Alamofire/Alamofire" "3.1.3"
github "antitypical/Result" "3.1.0"
github "org-name/AnotherInteralFramework" "0.1.4-beta-1"
github "org-name/networking" "0.0.9-Beta-1"
github "org-name/networking-dependency-one" "0.0.6"
github "org-name/networking-dependency-two" "2.0.1"
```

**Comment by jdhealy** [comment]
@NicholasTD07 One more ask: what are the tags for "git@github.com:org-name/networking.git"?

Could be [an aspect of issue #469](https://github.com/Carthage/Carthage/issues/469#issuecomment-111961809) — [seen in action in this gist](https://gist.github.com/jdhealy/4b5b83c6eb2d9d28454d).

**Comment by NicholasTD07** [comment]
@jdhealy 

```
0.0.1
0.0.10
0.0.10-Beta-1
0.0.10.1
0.0.11
0.0.11-Beta-1
0.0.11-Beta-2
0.0.11-Beta-FeatureA
0.0.12-Beta-FeatureA
0.0.12.1-Beta-FeatureA
0.0.12.2
0.0.12.3
0.0.12.4
0.0.12.5
0.0.12.6
0.0.13
0.0.14
0.0.15
0.0.16
0.0.17
0.0.18
0.0.19b1
0.0.19b2
0.0.2
0.0.20
0.0.21
0.0.22
0.0.22.1
0.0.23
0.0.24
0.0.25
0.0.26
0.0.27
0.0.28
0.0.29
0.0.3
0.0.30
0.0.31
0.0.32
0.0.33
0.0.34
0.0.35
0.0.36
0.0.4
0.0.5
0.0.6-beta
0.0.7
0.0.7-beta
0.0.8
0.0.8-beta
0.0.8.1-beta
0.0.9
0.0.9-Beta-1
0.12
1.0.0
1.0.0a
1.0.11
1.0.12
1.0.13
1.0.14
1.0.15
1.0.16
1.0.17
1.0.18
1.0.19
1.0.1b
1.0.20
1.0.2a
1.0.3-3-alpha
1.0.4-9-alpha
1.0.5
1.0.6
1.0.7
1.0.8
1.0.9
1.1.0
1.10.0
1.2.0
1.2.1
1.2.2
1.2.3
1.2.4
1.2.5
1.2.6
1.2.7
1.3.0
1.3.1
1.4.0
1.4.1
1.4.2
1.4.3
1.4.4
1.5.0
1.6.0
1.7.0
1.8.0
1.8.1
1.9.0
2.0.0
2.0.1
2.0.2
2.0.3
2.0.4
3.0.0
3.1
3.1.1
3.1.2
3.1.3
3.1.4
3.1.6
3.1.7
3.2.0
3.2.1
4.0.0
4.0.1
4.0.2
4.0.3
4.0.4
4.1
4.1.0
4.1.1
4.1.2
4.2.0
4.3.0
5.0.0
5.0.1
v1.0.4-5-alpha
```
