### ISSUE TITLE
Feature request: automatic adding/updating of copy-frameworks script

### ISSUE THREAD

**Issue by artemnovichkov** [Carthage/Carthage#2075]
According to 4-6 steps of [Getting Started](https://github.com/Carthage/Carthage#getting-started) guide, it is necessary to add the paths to Carthage frameworks. I made a little script named [Carting](https://github.com/artemnovichkov/Carting) to do it automatically. What do you think? Are there any ways to merge with script to Carthage?

**Comment by mdiep** [comment]
Unfortunately, no. We don't want to be in the business of editing project files.

But I do agree that this is a pain and it's great to see a community solution to this!

**Comment by artemnovichkov** [comment]
@mdiep, I agree, it is quiet dangerous to change project file and it can break the project one day, so I added warning to README. Crossing fingers and hoping this will not happen.

**Comment by CocoaGoofy** [comment]
@mdiep it's a feature — not a bug — that Carthage doesn't edit Xcode project files.
