### ISSUE TITLE
Mistakenly considers **duplicates**, although the **branches are different**

### ISSUE THREAD

**Issue by EvGeniyLell** [Carthage/Carthage#2078]
* `carthage version`: 0.24.0
* `xcodebuild -version`:  Version 8.3.3 (8E3004b)
* Are you using `--no-build`?  - No
* Are you using `--no-use-binaries`?   - No
* Are you using `--use-submodules`?   - No
* Are you using `--cache-builds`?   - No

**Cartfile**
```
git "git@github.com:/ardas/mobile-ifex-ios.git" "PageMenu.module"
git "git@github.com:/ardas/mobile-ifex-ios.git" "EmptyDataSet.module"
```

**Carthage Output**
```
iMac-Evgeniy:ifex.project evgeniyilyin$ carthage update --platform iOS
The following dependencies are duplicates:
	git "git@github.com:/ardas/mobile-ifex-ios.git" (found in /Users/evgeniyilyin/Work/IFEX/ifex.project/Cartfile)
```

**Comment by blender** [comment]
I don't think this is supposed to work. Dependencies are not uniqued based on their branches. Behaves as expected.

**Comment by EvGeniyLell** [comment]
But, i can build it in "hand mode"
1) build 1 line & commit
2) build 2 line & reset change (deleting) for 1 framework & commit all

Inside there are no collisions, restriction is artificial

**Comment by EvGeniyLell** [comment]
Want to secure, create inside a folder named repository + brunch
mobile-ifex-ios.git_ EmptyDataSet.module

**Comment by blender** [comment]
I'm not quire sure I understand what you mean with the example you gave.

You cannot specify the same dependency twice in a Cartfile. 

"PageMenu.module" and "EmptyDataSet.module", as far as Carthage is concerned, are different versions of the same dependency. Even if duplicate dependency where allowed that would generate an version ambiguity as version resolution time.

**Comment by mdiep** [comment]
Yeah, this works as expected. A dependency is defined by the repository; versions are defined by tags/branches/commits.

Just because you can structure a Git repository this way doesn't mean that you should. Use separate repositories for separate dependencies.
