### ISSUE TITLE
Have Carthage use Xcode-beta, rather than Xcode, when both installed on a Mac?

### ISSUE THREAD

**Issue by smhk** [Carthage/Carthage#2080]
While Xcode 9 is beta, I have the typical arrangement,

<img width="275" alt="screenshot" src="https://user-images.githubusercontent.com/3938526/28673039-0b5dd6b8-72a7-11e7-8f8f-4c5df914a69a.png">

however, when I carthage update indeed it tries to use the Xcode8 tools, so I get:

![screenshot 1](https://user-images.githubusercontent.com/3938526/28673032-04ed7568-72a7-11e7-8712-88f5e13fd367.png)

is there a way to tell Carthage to build with the "other" Xcode?

**Comment by mdiep** [comment]
> If you have multiple versions of the Apple developer tools installed (an Xcode beta, for example), use xcode-select to change which version Carthage uses.

https://github.com/Carthage/Carthage#resolve-build-failures

**Comment by smhk** [comment]
Excellent, thanks.  sorry I really couldn't find the info.  Perhaps this QA will help other googlers.
