### ISSUE TITLE
Unable to determine framework Swift version.

### ISSUE THREAD

**Issue by Elegia** [Carthage/Carthage#2083]
* `carthage version`: 0.24.0
* `xcodebuild -version`: Xcode 8.3.3 (build version 8E3004b)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
git "ssh://git@stash.reference.be:7999/trlib/mobile-library-ios-swift.git" "feature/carthage"
github "Alamofire/Alamofire" == 4.4
github "jrendel/SwiftKeychainWrapper" == 3.0.1
github "yeahdongcn/RSBarcodes_Swift" == 3.0.3
github "drmohundro/SWXMLHash" == 4.1.0
github "DaveWoodCom/XCGLogger" == 4.0.0
binary "https://armada.reference.be/carthage/Extra/xtra.json" == 2.1
```

**xtra.json**
```
{
    "2.1": "https://armada.reference.be/carthage/Extra/XtraIntegration_2.1.framework.zip"
}
```

**Carthage Output**
```
$ carthage update --verbose --platform ios
*** Fetching XCGLogger
*** Fetching mobile-library-ios-swift
*** Downloading binary-only framework xtra at "https://armada.reference.be/carthage/Extra/xtra.json"
*** Fetching Alamofire
*** Fetching RSBarcodes_Swift
*** Fetching SwiftKeychainWrapper
*** Fetching SWXMLHash
*** Checking out mobile-library-ios-swift at "ed59057622282649563aeb496aa8b8dbeb0b6bd6"
Unable to determine framework Swift version.
```

Everything works fine with the binary resource removed from the Cartfile. With the binary resource the output 'Unable to determine framework Swift version' is displayed.

Peeking into the frameworks' header file shows the following Swift version: 
```
// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
```
A cursory look into the CarthageKit source makes me believe that the regex used may be incorrect as it doesn't match the string when testing via [Regexr](http://regexr.com).
```
Apple Swift version ([0-9.]+) .*\\((.+)\\)
```

**Comment by ikesyo** [comment]
> A cursory look into the CarthageKit source makes me believe that the regex used may be incorrect as it doesn't match the string when testing via Regexr.

That is just because we require to escape `\` because of Swift's String interpolation feature. So `Apple Swift version ([0-9.]+) .*\((.+)\)` should just work for that website.

**Comment by ikesyo** [comment]
Could you try with the latest Carthage 0.25?

**Comment by ikesyo** [comment]
Closing this for now.
