### ISSUE TITLE
Per Package platform

### ISSUE THREAD

**Issue by mcfedr** [Carthage/Carthage#2087]
It seems to be that it would be great to be able to specify which packages are needed for which platforms. This could save a lot of build time in projects that have multiple platforms in a single project, e.g. an iOS app with embedded Watch app. Its very likely that the main app has deps that are not needed for Watch app, and the other way around.

Maybe the Cartfile could be extended to indicate this. Something like this.
```
github "package/a" ~> 1.0.0 :iOS,:watchOS
github "package/b" ~> 1.0.0 :watchOS
github "package/b" ~> 1.0.0 :iOS
```

**Comment by blender** [comment]
Linking this to #2294
