### ISSUE TITLE
Support Downloading `tar.bz2` and `tar.gzip` binary frameworks

### ISSUE THREAD

**Issue by lswith** [Carthage/Carthage#2091]
I just realised that no one really uses this but they could possibly in the future.

**Comment by lswith** [comment]
https://gist.github.com/lswith/85aa27309553bd932b336f234abf54e5 and https://gist.github.com/lswith/7ea8567a0c903dc031c0e8408c8688fc for an example.

**Comment by ikesyo** [comment]
Closed by #2092. Thanks @lswith!
