### ISSUE TITLE
Caught signal triggered by the Swift runtime!

### ISSUE THREAD

**Issue by qiuncheng** [Carthage/Carthage#2097]
* `carthage version`: 0.24.0
* `xcodebuild -version`: Xcode 8.3.3 Build version 8E3004b
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "realm/realm-cocoa"
```

**Carthage Output**
```
Caught signal triggered by the Swift runtime!
Segmentation fault

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.

Segmentation fault: 11

```

others: 
![image](https://user-images.githubusercontent.com/9990834/28932343-bccd070c-78ab-11e7-8e17-1566cfbe6c85.png)

**Comment by mdiep** [comment]
I can't reproduce this on my machine. Which `carthage` command are you running?

**Comment by mcfedr** [comment]
I have the same issue with facebook sdk, I reported it to them as well, https://developers.facebook.com/bugs/878290185642503/ 

This my Cartfile
```
github "facebook/facebook-ios-sdk" ~> 4.25
```

just running `carthage update` is enough to reproduce it.

**Comment by qiuncheng** [comment]
Hi @mdiep , I just run `carthage update --platform ios`.
But I couldn't get this issue at third time, then built successfully.
