### ISSUE TITLE
Only one project is built

### ISSUE THREAD

**Issue by dodikk** [Carthage/Carthage#210]
**Given :** a repo with three shared schemes

```
github "iAsync/iAsyncLite" == 0.4
```

![screen shot 2014-12-14 at 18 57 14](https://cloud.githubusercontent.com/assets/396451/5428215/15391e02-83c3-11e4-9645-9868a4f74972.png)

**When :** fetching a repo as dependence

**Then :** Only two frameworks are built.

``` bash
 dodikk$ ls -1 Carthage.build/iOS/
JFFAsyncOperations.framework
JFFUtils.framework
```

**Expected :** all three frameworks are built

``` bash
 dodikk$ ls -1 Carthage.build/iOS/
JFFAsyncOperations.framework
JFFScheduler.framework  ## <<<<<----- This one is missing
JFFUtils.framework
```

**Comment by CoderXpert** [comment]
Is there a way to tell Carthage to build particular project in the repo? We have a repo which includes two frameworks, now if we do `Carthage update ` it builds only the first project and ignores the second one. I know that it will build only first one if I do Carthage update, but is there a way I can specify a particular project? By doing that, I will run the command twice to build both frameworks.

**Comment by mdiep** [comment]
Please open a new issue
