### ISSUE TITLE
Feature Request: display warnings in Xcode

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#2103]
I've written a script that wraps the output from `Carthage Update` to print out warnings that will display in **Xcode** if your dependencies are out of date

(for example):

<img width="581" alt="carthage2" src="https://user-images.githubusercontent.com/6491743/29034555-a0749238-7b66-11e7-855c-0a6842a2d0c4.png">

I was wondering if we could add a flag so you could run

`carthage outdated --xcode-warnings`

and it would output an Xcode compatible warning message and nothing else - this way you could put it in your build phases to alert when things are out of date.

For those that are interested this is my build phase script:

```bash

# Capture output of carthage update - so we only need to run it once
outdated=$(carthage outdated | grep -v "\*\*\* Fetching" | grep -v "following dependencies" )

# Do some fancy grep action to turn the lines into approriate xcode style warnings
echo "$outdated" |  cut -d' ' -f1 | xargs -I _ grep _ $(realpath Cartfile) --with-filename --line-number --only-matching | perl -p -e "s/([^:]*:\w+:)(\w+)/\$1 warning:  \$2 is out of date -- run carthage update/" 


# If there is updates - fire off a notificaiton
if [ "$outdated" == "All dependencies are up to date." ]; then
   exit;
else
    title="${PRODUCT_NAME} -- Carthage"
    text="Dependencies are out of date - run carthage update"
    osascript -e "display notification \"$text\" with title \"$title\""
fi

exit 0
```

**Comment by mdiep** [comment]
I think that'd be a fine option! A pull request for this would be very welcome. 🙂

**Comment by jeeftor** [comment]
The ultimate goal is a pull request - but I'm not sure when i'll have time to work on it ...

**Comment by mdiep** [comment]
Done in #2209.
