### ISSUE TITLE
Build failure using Xcode9beta5 - Any way to tell Carthage which target to use? 

### ISSUE THREAD

**Issue by dhmspector** [Carthage/Carthage#2104]
* `carthage version`: 
0.24.0
* `xcodebuild -version`: 
Xcode 9.0
Build version 9M202q
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "realm/realm-cocoa" "master"
```

**Carthage Output**
```
xcodebuild timed out while trying to read RealmExamples.xcworkspace 😭
```

Carthage  seems to be picking up the wrong default build target by default - or perhaps Apple has chance he xcodebuild output.  This worked fine with Xcode9beta4 and below.

**Comment by ikesyo** [comment]
It may be an Xcode bug: https://www.reddit.com/r/iOSProgramming/comments/6s8f0p/does_xcodebuild_showbuildsettings_hang_for/

**Comment by mdiep** [comment]
This is definitely an Xcode bug. I've hit this today too and filed a radar.

**Comment by dhmspector** [comment]
Sorry, I should have mentioned  we (Realm) figured out its an xcode/xcodebuild bug where it times out trying to figure out the team signing info.  I filed a radar, its #33763197

**Comment by kerr-marinmiller-hs** [comment]
It would be great to leave this issue open, I can see a lot of people (myself included!) looking for information on this and having a hard time finding any info. I only arrived here via #2119.

**Comment by ikesyo** [comment]
Xcode 9 beta 6 has come. How about with the version?

**Comment by mdiep** [comment]
This bug appears to be fixed in ß6! 🎉

**Comment by sunchunqiang** [comment]
I still encounter the issue with xcode 10.1. 
Can carthage parameterize the time out value?

**Comment by mRs-** [comment]
One of my colleagues has exactly the same problem.

**Comment by mdiep** [comment]
I'd accept a PR that added a way to configure this via a parameter.
