### ISSUE TITLE
Carthage is stuck while running bootstrap

### ISSUE THREAD

**Issue by Sohil** [Carthage/Carthage#2105]
* `carthage version`: 0.24.0
* `xcodebuild -version`: Xcode 8.3.3 Build version 8E3004b
* Are you using `--no-build`? yes
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

I have changed the libraries name

**Carthage Output**
*** Checking out Library1 at "v4.0.0"
*** Checking out Library2 at "4.5.1"
*** Checking out Library3 at "v2.0.0"
*** Checking out Library4 at "v3.3.0"
*** Checking out Library5 at "commit-hash"
*** Checking out Library5 at "v4.2.0"

I also tried using --verbose but could not see any additional information for same.

**Comment by amreshkumar** [comment]
+1

**Comment by mdiep** [comment]
If you see this with public dependencies, please post your Cartfile. That will aid in reproducing and fixing the issue.

**Comment by jonah-neugass-ck** [comment]
+1

**Comment by mdiep** [comment]
`+1`s really aren't helpful.

These bugs are hard to fix unless we're able to reproducing them. So if you're not posting steps to reproduce, please don't comment!
