### ISSUE TITLE
No instructions for macOS "command line tool" template

### ISSUE THREAD

**Issue by codeOfRobin** [Carthage/Carthage#2107]
The macOS "Command Line Tool" app template doesn't have an "embedded frameworks" section in the project properties, which means this

> On your application targets’ “General” settings tab, in the “Embedded Binaries” section, drag and drop each framework you want to use from the Carthage/Build folder on disk.

doesn't work.

How do you add a Carthage framework to a command line tool? I tried adding it to "Linked Frameworks and Libraries" but no dice.

Here's a screenshot (github upload is messing with me, so it's imgur):

![](http://i.imgur.com/oLIAu6b.png)

**Comment by ikesyo** [comment]
Hi, that is a known limitation. Carthage itself works around it by creating a normal macOS application and extracting the binary (and required framework besides) from the app bundle.

You could see how does it set up in this project (`carthage` target).

**Comment by ikesyo** [comment]
See also https://github.com/Carthage/Commandant/issues/28. Closing.
