### ISSUE TITLE
Update Fails After Successful Bootstrap.

### ISSUE THREAD

**Issue by aaroncrespo** [Carthage/Carthage#2118]
* `carthage version`:  0.24.0
* `xcodebuild -version`: Xcode 8.3.3 Build version 8E3004b
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "fpillet/NSLogger"
```

**Carthage Output**
```
$ rm -rf ~/Library/Caches/org.carthage.CarthageKit
$ rm -rf ~/Library/Developer/Xcode/DerivedData

$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Cloning NSLogger
*** Downloading NSLogger.framework binary at "v1.8.3"
*** Checking out NSLogger at "v1.8.3"
*** xcodebuild output can be found in /var/folders/vx/hmnt9s3x0qn_bcdjc_9qrcnsgp2kq9/T/carthage-xcodebuild.pEWcMA.log
*** Building scheme "NSLogger" in NSLogger.xcodeproj
*** Building scheme "NSLoggerSwift" in NSLogger.xcodeproj

$ carthage update
*** Fetching NSLogger
*** Downloading NSLogger.framework binary at "v1.8.3"
*** Checking out NSLogger at "v1.8.3"
*** xcodebuild output can be found in /var/folders/vx/hmnt9s3x0qn_bcdjc_9qrcnsgp2kq9/T/carthage-xcodebuild.MAH74X.log
*** Building scheme "NSLogger" in NSLogger.xcodeproj
Failed to write to /Users/me/temp/Carthage/Build/iOS/NSLogger.framework/Modules/NSLogger.swiftmodule/i386.swiftdoc: Error Domain=NSCocoaErrorDomain Code=4 "The file “i386.swiftdoc” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/NSLogger/v1.8.3/Build/Products/Release-iphonesimulator/NSLogger.framework/Modules/NSLogger.swiftmodule/i386.swiftdoc, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/Users/me/temp/Carthage/Build/iOS/NSLogger.framework/Modules/NSLogger.swiftmodule/i386.swiftdoc, NSFilePath=/Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/NSLogger/v1.8.3/Build/Products/Release-iphonesimulator/NSLogger.framework/Modules/NSLogger.swiftmodule/i386.swiftdoc, NSUnderlyingError=0x7fa81fc294a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

Clearing CarthageKit Cache between steps resolves the issue. But our CI performs multiple Carthage passes to verify different schemes.

**Comment by aaroncrespo** [comment]
The file:
`/Library/Caches/org.carthage.CarthageKit/DerivedData/NSLogger/v1.8.3/Build/Products/Release-iphonesimulator/NSLogger.framework/Modules/NSLogger.swiftmodule/i386.swift` does actually exist in the source location.

**Comment by ikesyo** [comment]
Ref: https://github.com/fpillet/NSLogger/issues/234

**Comment by ikesyo** [comment]
Looks like this is a name collision of `NSLogger.framework` produced by both the `NSLogger` scheme and the `NSLoggerSwift` scheme.

Renaming `NSLoggerSwift`'s product name to `NSLoggerSwift.framework` (but keeping the module name as `NSLogger`) should resolve it.

**Comment by jjrscott** [comment]
I'm seeing the same issue. Looking at the file system it appear that `NSLogger.swiftmodule` doesn't exist at the destination. I wonder if that's the actual missing "file".

**Comment by ikesyo** [comment]
Let's track this at the upstream: https://github.com/fpillet/NSLogger/issues/234. Closing.
