### ISSUE TITLE
Timeout running `carthage build --no-skip-current`, Xcode 9, Swift 4

### ISSUE THREAD

**Issue by jhurray** [Carthage/Carthage#2124]
* `carthage version`: 0.24.0
* `xcodebuild -version`:  Xcode 9.0 Build version 9M202q
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO

I am running `carthage build --no-skip-current` and it times out

`SWIFT_VERSION` is `4.0`

**Cartfile**
N/A

**Carthage Output**
```
xcodebuild timed out while trying to read Ladybug.xcodeproj 😭
```

**Comment by mdiep** [comment]
This is an Xcode bug. See #2104.

Hopefully we'll get a ß6 this week with a fix.

**Comment by jhurray** [comment]
Lets hope so! thanks!
