### ISSUE TITLE
Publish new release before High Sierra

### ISSUE THREAD

**Issue by fxcoudert** [Carthage/Carthage#2127]
Hi, the fact that [Carthage 0.24 doesn't build on mac10.13 with Xcode 9](https://github.com/Carthage/Carthage/issues/2089) is a problem for [Homebrew](https://github.com/Homebrew/homebrew-core/issues/14418) as a distributor. The problem appears to be fixed on trunk, but we only ship released versions (unless the user asks for git head).

Given that High Sierra is coming in about a month, we hope that you will consider cutting a new release before then. Thanks!

**Comment by ikesyo** [comment]
Let's close this now.
