### ISSUE TITLE
Carthage not building transitive dependencies when running build/update with specified dependency

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#2130]
* `carthage version`:  0.24.0
* `xcodebuild -version`:  Xcode 8.3.3 Build version 8E3004b
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`?  No

**Cartfile**
```
github "nvzqz/RandomKit" ~> 5.2.3
```

**Carthage Command**
```
carthage update RandomKit --platform iOS
```

**Carthage Output**
```
*** Fetching RandomKit
*** Fetching ShiftOperations
*** Fetching Threadly
*** Checking out RandomKit at "v5.2.3"
*** xcodebuild output can be found in /var/folders/x7/pd6q3qp51cs1xm86457mm88m0000gn/T/carthage-xcodebuild.XGJRmK.log
*** Building scheme "RandomKit iOS" in RandomKit.xcodeproj
```

------------

This is [`RandomKit`'s `Cartfile`](https://github.com/nvzqz/RandomKit/blob/master/Cartfile):
```
github "nvzqz/ShiftOperations" ~> 1.0.2
github "nvzqz/Threadly" ~> 1.0
```

Notice how they are being fetched, but then only `RandomKit` is built.
If I don't specify `RandomKit` in the `build`/`update` command, it builds all 3 of them correctly.

**Comment by NachoSoto** [comment]
Huh now I can't reproduce this... Any chance this was due to GitHub rate limiting? Before this I had started seeing warnings regarding that. Either way Carthage shouldn't just skip building this if that were the case.

**Comment by mdiep** [comment]
I don't think that this would be the case. I can't think of anything that would cause this. 🤔

**Comment by NachoSoto** [comment]
I'll close this then :/
