### ISSUE TITLE
Any Idea how can I debug third party libraries on Carthage ?

### ISSUE THREAD

**Issue by Faisalcs** [Carthage/Carthage#2137]
* `carthage version`: 0.24.0
* `xcodebuild -version`: 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```

**Comment by mdiep** [comment]
Is `carthage build --configuration Debug` what you're looking for?

**Comment by Faisalcs** [comment]
What I'm looking for is I want to access the source code while I'm coding my own app. Like what I can do in cocoapods ? Should I add the third party lib beside my project ? or there is another way?

**Comment by blender** [comment]
@Faisalcs this is one example of how you can do what you are asking http://allocinit.io/ios/debugging-carthage-dependencies/

**Comment by Faisalcs** [comment]
@blender  Thanks a lot. I'll try it then I'll give you my feedback.

**Comment by DanielAsher** [comment]
I've found that simply including your framework (or a third party frameworks) project into a workspace is enough to allow Xcode to debug into it

**Comment by jkmathew** [comment]
> @Faisalcs this is one example of how you can do what you are asking http://allocinit.io/ios/debugging-carthage-dependencies/

HI @tmspzz , nice article. But I think the link to `develop.rb` is broken.

**Comment by JosephBergman** [comment]
@jkmathew I believe this is the same `develop.rb` from the article.
https://gist.github.com/tmspzz/ddf64f679f4a862c4e3279e7294d8a58
