### ISSUE TITLE
NewRelicAgent lib

### ISSUE THREAD

**Issue by Pitsko** [Carthage/Carthage#214]
I had pod 'NewRelicAgent', '~> 4.139' in pods file
How can I can migrate it to Cartfile

I tried something like: source "https://download.newrelic.com/ios_agent/NewRelic_iOS_Agent_4.139.zip" ~> 4.139, but it doesn't work

**Comment by vidhyasri2106** [comment]
Is it possible to install new relic with Carthage package manager in iOS?
