### ISSUE TITLE
Version 0.25.0 downgrades frameworks

### ISSUE THREAD

**Issue by Dschee** [Carthage/Carthage#2143]
* `carthage version`: 0.25.0
* `xcodebuild -version`: Xcode 8.3.3, Build version 8E3004b
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes

**Cartfile** (removed entries with no sub dependencies that didn't cause problems)
```
# AKSideMenu is a double side menu library with parallax effect.
github "Dschee/InteractiveSideMenu" "master"

# Network abstraction layer written in Swift.
github "Moya/Moya" ~> 9.0

# Convenient logging during development & release in Swift
github "SwiftyBeaver/SwiftyBeaver" ~> 1.1

# Swifty Sound is a simple library that lets you play sounds with a single line of code.
github "adamcichy/SwiftySound" ~> 0.6

# Drop-in replacement for UISlider with ticks, images & animated labels
github "SwiftArchitect/TGPControls" ~> 4.0
```

**Carthage Output** (command: `carthage update --platform iOS --cache-builds`)
```
*** Fetching InteractiveSideMenu
*** Fetching SwiftyBeaver
*** Fetching SwiftySound
*** Fetching TGPControls
*** Fetching Moya
*** Fetching Result
*** Fetching Alamofire
*** Fetching ReactiveSwift
*** Fetching RxSwift
*** Checking out Moya at "9.0.0-alpha.1"
*** Checking out InteractiveSideMenu at "ac47329a2c8d77e6483fde4d4a5cd13f6f5546d4"
*** Checking out Alamofire at "4.5.0"
*** Checking out TGPControls at "v4.0.0"
*** Checking out SwiftySound at "0.6.0"
*** Checking out ReactiveSwift at "2.0.1"
*** Checking out SwiftyBeaver at "1.3.3"
*** Downloading RxSwift.framework binary at "Oxygen.1"
*** Checking out Result at "3.2.3"
*** xcodebuild output can be found in /var/folders/2l/3tqwt0g91x18hql0jwsz0y280000gn/T/carthage-xcodebuild.2BQ3oQ.log
*** Valid cache found for Alamofire, skipping build
*** Valid cache found for InteractiveSideMenu, skipping build
*** Valid cache found for Result, skipping build
*** Valid cache found for ReactiveSwift, skipping build
*** Valid cache found for RxSwift, skipping build
*** Valid cache found for Moya, skipping build
*** Valid cache found for SwiftyBeaver, skipping build
*** Valid cache found for SwiftySound, skipping build
*** Valid cache found for TGPControls, skipping build
```

My problem is that since I have Carthage 0.25.0 installed a `carthage update --platform ios --cache-builds` downgrades some dependencies to previous versions. I'm not sure if this is an issue with the GitHub API or with Carthage, but I recognized this behavior and my colleagues who upgraded to Carthage 0.25.0 did see the same issue, too. We are now downgrading to 0.24.0 but this should probably be fixed.

Here's an extract of the changed `Cartfile.resolved` (red lines are deleted lines, green lines are the new ones) after running `carthage update`. As you can see several versions have downgraded.

![bildschirmfoto 2017-09-05 um 13 01 27](https://user-images.githubusercontent.com/6942160/30058331-d08eced0-923a-11e7-9f1f-71fef8463bef.png)

For one of my fellows, as an example, SwiftySound downgraded from 0.6.0 to 0.2.0. So it seems it doesn't behave the same for everybody ...

**Comment by mdiep** [comment]
This shouldn't be an issue with 0.25 specifically. Nothing has changed in the resolver, so most likely exists in 0.24 too.

This looks like another case of the non-semantic-version bug.

**Comment by Dschee** [comment]
I have just downgraded to 0.24.0 and it updates dependencies correctly.

I have no idea what „non-semantic-version bug“ is.

**Comment by mdiep** [comment]
Here's the `Cartfile.resolved` I get with 0.25:

```
github "Alamofire/Alamofire" "4.5.0"
github "Dschee/InteractiveSideMenu" "8323b9f36c3deae7d4c0f26fb3de575d1bfd0fc2"
github "Moya/Moya" "9.0.0"
github "ReactiveCocoa/ReactiveSwift" "2.0.1"
github "ReactiveX/RxSwift" "3.6.1"
github "SwiftArchitect/TGPControls" "v4.0.0"
github "SwiftyBeaver/SwiftyBeaver" "1.4.0"
github "adamcichy/SwiftySound" "0.6.0"
github "antitypical/Result" "3.2.3"
```

**Comment by jdhealy** [comment]
@Dschee “non-semantic-version bug” → https://github.com/Carthage/Carthage/issues/469#issuecomment-111931972

**Comment by Dschee** [comment]
@jdhealy If I understood the bug correctly, it doesn't apply to SwiftyBeaver being downgraded to 1.3.6 from 1.4.0, right?

@mdiep I already expected it to work for you, cause I know you guys test things out before you ship. But apparently there seemed to be a problem for us. But again, maybe that was only due to a bug on GitHub. Let's wait and see if anyone else has the same issue ...

**Comment by mdiep** [comment]
> If I understood the bug correctly, it doesn't apply to SwiftyBeaver being downgraded to 1.3.6 from 1.4.0, right?

Since Moya was changed to a non-semantic-version, all bets are off. That could be the root cause of th downgrade.

The only change that I can think of that might affect this is https://github.com/Carthage/Carthage/pull/2125.

**Comment by lastMove** [comment]
@Dschee I had this issue and I did the same thing (downgrade to 0.24.0 and it worked)

**Comment by Sealos** [comment]
I can also confirm this issue, with 0.24.0:
*** Checking out Charts at "v3.0.3"

With 0.25.0
*** Checking out Charts at "v3.0.0"

**Comment by Shunzi007** [comment]
I had this issue too.

**Comment by ngocluu** [comment]
I had the same issue. I downgraded Carthage to 0.24.0 and it worked.

**Comment by nomadplanet** [comment]
I have the same issue here, 0.25.0 resolves the wrong version of dependencies.

**Comment by einsteinx2** [comment]
Just happened to me a few days ago. Switched from my own fork to the upstream repo. Carthage kept finding some commit from 18 months ago even though I have it set to the master branch. Cleared the cache folder and it now sees the correct commit.

**Comment by ikesyo** [comment]
Locking the issue for a while.

**Comment by blender** [comment]
Is this still a bug? Even after #2412

**Comment by mdiep** [comment]
Yes, this is covered by #469.
