### ISSUE TITLE
No tagged versions found in 0.25.0

### ISSUE THREAD

**Issue by kdawgwilk** [Carthage/Carthage#2148]
* `carthage version`: 0.25.0
* `xcodebuild -version`: Xcode 9.0 beta 6 (9M214v)
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? yes
* Are you using `--cache-builds`? yes

**Cartfile**
```
github "SVProgressHUD/SVProgressHUD" == 2.1.2
github "ReactiveX/RxSwift" == 3.4.0
github "ccgus/fmdb" == 2.6.2
github "hkellaway/Gloss"
github "airbnb/lottie-ios" == 1.5.2
github "vivint/Woody" ~> 0.2.0
git "https://<redacted>/smsdk-ios.git" == 0.2.5
git "https://<redacted>/Constants.git" "master"
git "https://<redacted>/ios-unalytics.git" == 0.2.0
```

**Carthage Output**
```
*** Fetching auth-ios
*** Fetching Constants
*** Fetching SVProgressHUD
*** Fetching Gloss
*** Fetching smsdk-ios
*** Fetching RxSwift
*** Fetching ios-unalytics
*** Fetching fmdb
*** Fetching Woody
No tagged versions found for github "vivint/Woody"
```

This worked right before I upgraded to `0.25.0`

**Comment by kdawgwilk** [comment]
I downgraded back to `0.24.0` and it worked perfectly

**Comment by mdiep** [comment]
If you switch back to `0.25.0` and delete `~/Library/Caches/org.carthage.CarthageKit/dependencies`, does the issue go away?
