### ISSUE TITLE
Can't build Dollar.swift

### ISSUE THREAD

**Issue by searls** [Carthage/Carthage#215]
First: apologies. I'm a complete Carthage noob and just trying it for the very first time. I'm sure this isn't the kind of issue the team normally likes to see, since it's probably on my end. Your patience is appreciated.

The first dependency I wanted to use was [Dollar.swift](https://github.com/ankurp/Dollar.swift) but it failed and I don't understand the failure.

So my Cartfile just has:

```
github "ankurp/Dollar.swift"
```

When I run `carthage bootstrap` I got this output:

``` sh
$ carthage bootstrap
*** No Cartfile.lock found, updating dependencies
*** Cloning Dollar.swift
*** Checking out Dollar.swift at "2.0.0"
*** xcodebuild output can be found in /var/folders/jp/n8sns6k51ws2d2vdzj2k3l380000gn/T/carthage-xcodebuild.kXA6Wl.log
*** Building scheme "Cent" in Dollar.xcworkspace
Error Domain=org.carthage.ReactiveTask Code=0 "** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
" UserInfo=0x7fdb6a6394c0 {NSLocalizedDescription=** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
, ReactiveTaskErrorExitCode=65, ReactiveTaskErrorStandardError=** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
}
```

Any idea on what this might be?

**Comment by ankurp** [comment]
@searls This is fixed as part of [this issue](https://github.com/ankurp/Dollar.swift/issues/133). Checkout this sample project installing Dollar using Carthage https://github.com/ankurp/DollarCarthageApp
