### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by zirinisp** [Carthage/Carthage#2154]
* `carthage version`:  0.25.0
* `xcodebuild -version`: 9.0 9M214v
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
Contains sensitive information and is not relevant to the issue
```

**Carthage Output**
```
*** Skipped downloading Parse-SDK-iOS-OSX.framework binary due to the error:
"API rate limit exceeded for "my static ip". (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"
```

I created a GitHub personal access token and tried setting a couple of environmental variable to it. I also tried using --use-ssh flag, but I am still getting the same warning.

I am using Carthage on OS X. Can you please guide me on how to get the restriction removed by adding my personal access token or another method

**Comment by ikesyo** [comment]
Hi @zirinisp,

> Can you please guide me on how to get the restriction removed by adding my personal access 
token

You can use `GITHUB_ACCESS_TOKEN` env:

```bash
GITHUB_ACCESS_TOKEN=... carthage bootstrap
```

Or if you store a GitHub credential on your Keychain with the osxkeychain credential helper, that credential will be used. See https://help.github.com/articles/caching-your-github-password-in-git/ for the details.

**Comment by zirinisp** [comment]
@ikesyo I have tried both and none worked. I will see it tomorrow and send you what I did exactly and failed.

**Comment by 7ynk3r** [comment]
@zirinisp did you solve the issue?

**Comment by shahla00** [comment]
Any update on this? I am facing the same issue.

**Comment by JoeyBodnar** [comment]
Anyone solved this?

**Comment by toh-ableton** [comment]
For whoever reads this / FYI @ikesyo: the issue is that https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Project.swift#L242 doesn't use the `GITHUB_ACCESS_TOKEN`. However, it will take credentials from a `.netrc` into account if you pass `--use-netrc`.
