### ISSUE TITLE
WebRTC/RTCMacros.h file not found and failed to import Signal-Bridging-Header.h

### ISSUE THREAD

**Issue by timt** [Carthage/Carthage#2155]
* `carthage version`: 025.0
* `xcodebuild -version`: 8.3.3

I clone the latest from the repository, run carthage install and tried to build/run and see these errors.

.../Signal-iOS/Libraries/WebRTC/RTCAudioSession.h:14:9: error: 'WebRTC/RTCMacros.h' file not found
#import "WebRTC/RTCMacros.h"
        ^
<unknown>:0: error: failed to import bridging header '.../Signal-iOS/Signal/src/Signal-Bridging-Header.h'

**Comment by ikesyo** [comment]
Hi @timt, but we are not sure about the specific library. Could you file an issue on that repository?

**Comment by timt** [comment]
doh! Sorry made this into the wrong git issues log :/
