### ISSUE TITLE
App bundle icon getting replaced by icon in Checkouts folder

### ISSUE THREAD

**Issue by rpassis** [Carthage/Carthage#2161]
* `carthage version`: 0.25
* `xcodebuild -version`: 9.0 (9A235)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "ReactiveX/RxSwift"
```

This seems to be related to https://github.com/CocoaPods/CocoaPods/issues/7003#issuecomment-329591422

I have a Carthage checkouts folder with RxSwift in it. Inside the RxSwift checkout folder is a RxExample app - this folder also contains an assets bundle file called `Images.xcassets` with RxSwift app icons inside it.

My own bundle has a `Images.xcassets` assets bundle with my own app icons in it. This was all working fine with Xcode 8.3.3 but since I started building with Xcode 9 for some reason my own app icons get replaced with the icons under the RxSwift checkout folder. 

I have no idea why but my current work around is to remove the RxExample folder from the checkout directory and everything works. This is obviously not ideal when building using our CI server since we always bootstrap and build scratch using from the Cartfile sources.

In all honesty I'm not even sure this is a Carthage issue but since removing the RxExample folder under Checkouts is a valid workaround I thought I'd report it here in case anyone is experiencing a similar problem. 

Let me know if you need any more info to help fix this issue.
Thanks!
Rog

**Comment by ikesyo** [comment]
Hi @rpassis, I'm pretty not sure what is happening here.

If you could provide a minimal reproducible example with a fresh xcodeproj, that will be help. If this doesn't happen on a fresh environment, you should check your existing project settings or some automation scripts.

**Comment by rpassis** [comment]
I'll close this until I have time to gather further information. This is likely to be unrelated to Carthage but it is still unclear to me why an icon from the Checkouts folder is overwriting our own app bundle icon. If I rename the app bundle icon to something different the problem goes away.
