### ISSUE TITLE
Carthage update would build the framework without resources in it

### ISSUE THREAD

**Issue by NSFish** [Carthage/Carthage#2169]
* `carthage version`: 0.25.0
* `xcodebuild -version`: Build version 9A235
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "NSFish/DummyFramework" "master"
```

**Carthage Output**
```
*** Fetching DummyFramework
*** Checking out DummyFramework at "6d93f6138f357c783b726b422d8ecacf88baaef4"
*** xcodebuild output can be found in /var/folders/xm/f7fbkfsx53xbxrwhkc7m8kcw0000gn/T/carthage-xcodebuild.qb0rUI.log
*** Building scheme "DummyFramework" in DummyFramework.xcodeproj
```

**Description**
Use [proxychains-ng](https://github.com/rofl0r/proxychains-ng) with Carthage commands, like
```bash
proxychains4 carthage update --platform ios
```
Carthage will build the framework as expected, but the PNG file is missing.

**Comment by ikesyo** [comment]
I can't reproduce it locally. There is no difference between `carthage update` and `carthage build` and `Hide.png` exists on both cases.

**Comment by NSFish** [comment]
I retried my repo at home and Carthage just works.
The issue happened when I was in company and used proxychains-ng to access the internet.
I'll dig a little further later, close this issue right now..
