### ISSUE TITLE
Authenticity of host 'github.com' can't be established

### ISSUE THREAD

**Issue by danscan** [Carthage/Carthage#217]
While running `carthage update`, I keep getting an error after the check out phase, saying:

```
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? 
```

Which doesn't take any input.

[Output here](https://gist.github.com/danscan/3df1d2e95670d617b8c3)

**Comment by RefatIbnAnwar** [comment]
how to solve this??


Siums-Mac-mini:~ sium$ ssh -T git@github.com
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
Permission denied (publickey).
Siums-Mac-mini:~ sium$ ssh -T git@github.com
Permission denied (publickey).

**Comment by ikesyo** [comment]
Please see https://help.github.com/articles/connecting-to-github-with-ssh/ (not related to Carthage itself).

**Comment by xlualy** [comment]
My issue solved following the blog post here: 
http://zeeelog.blogspot.com/2017/08/the-authenticity-of-host-githubcom.html
