### ISSUE TITLE
Cartfile version requirement ignored and Tag Stable Releases behaviour not adhered to

### ISSUE THREAD

**Issue by antonys1** [Carthage/Carthage#2171]
* `carthage version`: 0.25.0
* `xcodebuild -version`: Xcode 9.0 Build version 9A235
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "ashleymills/Reachability.swift" == 3.0.0
```

**Carthage Output**
```
$ carthage update --platform ios
*** Fetching Reachability.swift
*** Checking out Reachability.swift at "v4.0-beta2"
*** xcodebuild output can be found in /var/folders/3s/22wrwzws75x95gdbmcmmndj40000gr/T/carthage-xcodebuild.XwmwPS.log
*** Building scheme "Reachability" in Reachability.xcodeproj
```

Two issues
1. Version requirement in Cartfile ignored.
2. [Tag Stable Releases](https://github.com/Carthage/Carthage#tag-stable-releases) described behaviour not adhered to.

> Tags without any version number, or with any characters following the version number (e.g., 1.2-alpha-1) are currently unsupported, and will be ignored.

**Expected**
```
*** Checking out Reachability.swift at "v3"
```
**Actual**
```
*** Checking out Reachability.swift at "v4.0-beta2"
```

**Comment by ikesyo** [comment]
Unfortunately `v3` is not a legal semantic versioning tag for us. At least two digits are required here (e.g. `v3.0`).

https://github.com/Carthage/Carthage/pull/508

**Comment by antonys1** [comment]
Thanks, I'll ask the repository owner to update the tag.

**Comment by antonys1** [comment]
@ikesyo May I ask why Carthage checked out `v4.0-beta2`?

**Comment by antonys1** [comment]
I forked the repository and added [tags](https://github.com/antonys1/Reachability.swift/tags) that conform to semantic versioning but the issue still remains.

**Comment by ikesyo** [comment]
Please remove `~/Library/Caches/org.carthage.CarthageKit/dependencies`.

**Comment by antonys1** [comment]
Thanks it's working now 👍
