### ISSUE TITLE
Issue with XCode Server Bots : carthage : command not found.

### ISSUE THREAD

**Issue by ncatta** [Carthage/Carthage#2175]
* `carthage version`:  0.25.0
* `xcodebuild -version`:  XCode 9
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes

Hello !

I'm trying to setup an xcode server, with XCode 9. While it is working correctly with my project without carthage, my bots don't find carthage when remotely launched. In logs, I have this : 
```
/Users/xcodeserver/Library/Caches/XCSBuilder/Bots/09f32c6c861fac87a33d0e485f07b212/DerivedData/Build/Intermediates.noindex/project.build/Debug/project.build/Script-98D57C6C1F75499B00ADA4E6.sh: line 2: carthage: command not found
Command /bin/sh failed with exit code 127
```
However, with the xcode server user, I can launch carthage on the server... This only happens with the bots.
The call to carthage is in a "run script" build phase, and works well on server and other clients.

I can't find any sign of similar issue elsewhere, so I just ask here... 

Does someone have an idea ? 

Thanks by advance

**Comment by ikesyo** [comment]
Could you please check $PATH is correctly set up on that script phase or use full `/usr/local/bin/carthage`?

**Comment by ncatta** [comment]
Seems like you are right... And I am a little bit ashamed ... Thanks anyway !
