### ISSUE TITLE
Add Quickstart to Documentation

### ISSUE THREAD

**Issue by Stunner** [Carthage/Carthage#2179]
Following the steps to get up and running with Carthage is cumbersome. You direct users to verbose pages that don't make obvious what is required to get up and running with Carthage. Addressing this will only help expand your appeal.

A less verbose version of [this raywenderlich guide](https://www.raywenderlich.com/165660/carthage-tutorial-getting-started-2) would be ideal.

**Comment by mdiep** [comment]
PRs welcome!

**Comment by blender** [comment]
In progress in #2447
