### ISSUE TITLE
`Carthage update X` doesn't build X's dependencies for newly added X

### ISSUE THREAD

**Issue by SanjoDeundiak** [Carthage/Carthage#2188]
* `carthage version`: 0.25.0
* `xcodebuild -version`: 9.0
* Are you using `--no-build`? No 
* Are you using `--no-use-binaries`?  Yes (Problem doesn't reproduce without this flag if binaries are present)
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

When adding new dependency X (that depends on Y) to Cartfile. `carthage update X` doesn't build Y.

Sample project:
git clone https://github.com/SanjoDeundiak/carthage-bug-sample
carthage update virgil-sdk-x --no-use-binaries

**Comment by ikesyo** [comment]
Thanks for filing the issue!

**Comment by vincentsaluzzo** [comment]
I confirm, I've the same problem at this time when I'm trying to add `hyperoslo/Lightbox` to my project

**Comment by blender** [comment]
Fixed by https://github.com/Carthage/Carthage/pull/2321
