### ISSUE TITLE
`carthage checkout` hangs when accessing git repo that requires authentication if credentials aren't already set

### ISSUE THREAD

**Issue by gfontenot** [Carthage/Carthage#219]
If you specify a private repo in your `Cartfile` and your credentials aren't set up for https access, `carthage checkout` will get to the point where it needs authentication and hang. The user will be prompted for their username, but after entering it they are never prompted for their password.

The workaround for this is to make sure your credentials will be saved (with `osxkeychain`, for example) and then force authentication by cloning a private repo through https elsewhere on your system. After that, `carthage checkout` works as expected.

I'm assuming this has to do with some asynchronous behavior around the checking out of repos, but I haven't looked into it yet.

**Comment by angerman** [comment]
Just got bitten by this as well. Why doesn't the `launchGitTask` time out?

**Comment by jspahrsummers** [comment]
@angerman Because it hasn't been written. :blush: 

If you'd like to submit a pull request, we'd happily review it!

**Comment by ctava** [comment]
If you've been using ssh with 2FA to clone repos and are using carthage to clone private repos (which is using https) here's the workaround for you:

setup an access token for command line use:
https://help.github.com/articles/creating-an-access-token-for-command-line-use/

when prompted enter your github.com username and for your github.com password, enter the access token that you have just generated. caching of username/password is handled.

**Comment by jarsen** [comment]
Ran into this issue this morning. One thing the original poster alluded to but I had never done before and so caused me some more confusion was be sure to enable git to cache your credentials. Instructions are here https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by pizthewiz** [comment]
Just ran into this after upgrading from 0.7.0 to 0.7.1 for a Cartfile of only public repos…

**Comment by mdiep** [comment]
0.7.2 was released, which should fix this issue for anyone using Xcode 6.3+.

**Comment by hansott** [comment]
+1

``$ carthage checkout``
``Username for 'https://github.com': hansott``

``$ carthage version``
``0.7.4``

``$ git version``
``git version 2.4.3``

**Comment by mdiep** [comment]
@hansott What's the output of `git config --get credential.helper`?

**Comment by hansott** [comment]
@mdiep  `osxkeychain`

**Comment by mdiep** [comment]
@hansott **Don't post the output**, but what happens if you run `GIT_TERMINAL_PROMPT=0 echo "url=https://github.com"|git credential fill`? Does it prompt you for credentials?

**Comment by hansott** [comment]
@mdiep Yes, it does. :-)

**Comment by mdiep** [comment]
@hansott I just realized I messed up the command. Can you try `echo "url=https://github.com"|GIT_TERMINAL_PROMPT=0 git credential fill` to see if it prompts?

**Comment by hansott** [comment]
`fatal: could not read Username for 'https://github.com': terminal prompts disabled`

**Comment by mdiep** [comment]
I think the solution here is to use `GIT_TERMINAL_PROMPT=0` for all of our git tasks.

**Comment by billbonney** [comment]
The other option as a workaround instead of setting a token is to use --use-submodules and that forces carthage to clone using ssh

**Comment by paulfreeman** [comment]
I just upgraded to Carthage. 0.28.0 and I'm seeing this error for the first time. I have all my auth set up for normal git access via .ssh and its working fine.  

```
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/paulfreeman/cloudpickerframework.git /Users/paul/Library/Caches/org.carthage.CarthageKit/dependencies/cloudpickerframework) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
I have run 

 GIT_TERMINAL_PROMPT=0 echo "url=https://github.com"|git credential fill

and ensured that my correct credentials have been filled prior to running the Carthage update.   (I'm on Mac High Sierra, XCode 9.3b2)

**Comment by mdiep** [comment]
@paulfreeman Please open a new issue and include your `git --version` and the format of the `git credential fill` output.
