### ISSUE TITLE
Is there any possibility to install older versions of frameworks via carthage? 

### ISSUE THREAD

**Issue by darkForestCat** [Carthage/Carthage#2193]
* `carthage version`: 0.25.0
* `xcodebuild -version`: 8.3.3 & 9.0
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO

I've updated framework using carthage and that was a big mistake because it doesn't seem working good.Is there any way to downgrade it?

**Comment by ikesyo** [comment]
Just reverting your `Cartfile.resolved` and running `carthage bootstrap` (not `carthage update`) will be the way, right?
