### ISSUE TITLE
Feature Request: More Granular Distinction Between Minor / Bug Fix Versioning

### ISSUE THREAD

**Issue by monsantovernon** [Carthage/Carthage#2198]
"== 4.0" is ONLY interpreted as 4.0 OR 4.0.0
"~> 4.0" is interpreted as 4.x.y

Does this level of control currently exist?
"?" is interpreted as 4.0.x

If this already exists, or if another issue (I could not find one easily) covers this topic, please leave a comment so I can close this issue.

Minor versions versus bug fixes typically require more testing and therefore the timing of these upgrades needs more control.

What complicates this further is when there are 15+ frameworks and bug fixes are all that is required for this version.

Furthermore, a framework such as AWS sneaks in a minor version with API breaking changes (They violated the semantic versioning rules). Thus we hard code a "bug fix" version and will not be receiving any further bug fixes thereafter.

**Comment by mdiep** [comment]
No, something like that doesn't currently exist.

**Comment by monsantovernon** [comment]
Some suggestions:

"== 4" OR "~> 4" - The latest version 4.x.y
"== 4.0" OR "~> 4.0" The latest version 4.0.x
"~> 4.0.0" equates to "== 4.0.0"

**Comment by DCForever** [comment]
If a PR was submitted to do something like this, would it be considered?

**Comment by mdiep** [comment]
No, I don't think we want to enable such behavior. From a semantic versioning perspective, there's no reason to prefer to not upgrade to minor versions.
