### ISSUE TITLE
Unable to combine static frameworks into dylib

### ISSUE THREAD

**Issue by jsorge** [Carthage/Carthage#2203]
* `carthage version`: 0.25.0
* `xcodebuild -version`: 8.3.3
* Are you using `--no-build`? No 
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "rs/SDWebImage"
github "AgileBits/onepassword-extension"
github "hsousa/HCSStarRatingView"
# github "facebook/facebook-ios-sdk"
# Temporary Facebook SDK
github "sugoi-wada/facebook-ios-sdk" "780a72cd6086c57939d83a7143462ae13dfb9a74"
github "CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout"
github "card-io/card.io-iOS-source"
```

I'm able to build my dependencies using a build script as outlined in the [documentation here](https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md). Now I'm trying to merge my static frameworks into a dynamic one and running into problems. 

To start, I'm adding a single framework to the dylib target, I've disabled bitcode and added the following `OTHER_LDFLAGS`: `-all_load, -ObjC`. I'm starting small with the `HCSStarRatingView`. It has been added to they dylib target and that builds. 

To test this new combined framework I've added an app target. I can import the framework target and the app target recognizes it. However when I try to declare a new view with `let view = HCSStarRatingView(frame: .zero)` I'm getting the following error: `Use of unresolved identifier 'HCSStarRatingView'`.

I'm assuming that I don't import `HCSStarRatingView` directly because it's now part of my framework target. I'm also assuming that I don't have to add anything to my dynamic framework target's umbrella header to expose the linked static frameworks inside. Are those assumptions correct? Any idea what I could be missing here?

**Comment by jdhealy** [comment]
Hey, when you said [“If I continue having problems I'll open up a new issue”](https://github.com/Carthage/Carthage/issues/2200#issuecomment-335280911), I may have given you the wrong impression by thumbs up-ing that (my bad, assumed you were referring to additional Carthage crashes).

<a href="https://github.com/Carthage/Carthage/commit/83f1c49b068e4ae286ae7385ac6b5a862ae433d3#diff-04c6e90faac2675aa89e2176d2eec7d8R273"><blockquote>*Please note that a few caveats apply to [the preceding advise on static frameworks linked to in the README]:*
 - Swift static frameworks are not officially supported by Apple
 - This is an advanced workflow that is not built into Carthage, YMMV
</blockquote></a>

[To reiterate](https://github.com/Carthage/Carthage/issues/2200#issuecomment-334872739), “a better venue is probably StackOverflow for this aspect (if you post there, feel free to link to it in another comment in this issue [(issue 2203)] though)”.

**Comment by jsorge** [comment]
Oh my bad. I'll post an issue over there.

**Comment by jsorge** [comment]
[I created the question on SO here.](https://stackoverflow.com/questions/46675792/trying-to-merge-static-frameworks-using-carthage)

**Comment by sarunw** [comment]
@jsorge Did you manage to solve this? Got similar problem.
