### ISSUE TITLE
Carthage update dependency, ignores the dependency's Cartfile.resolved

### ISSUE THREAD

**Issue by serluca** [Carthage/Carthage#2205]
* `carthage version`: 0.26.0
* `xcodebuild -version`: Xcode 9.0 - Build version 9A235
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

I have a dependency called `A` on version `1.0.0` with the following Cartfile and Cartifile.resolved:
**Cartfile A**
```
github "B"
```
**Cartfile.resolved A**
```
github "B" 1.0.0
```
In my Main application I have `A` in my Cartfile and it gets resolved to this:

**Cartfile Main Application**
```
github "A"
```

**Carfile Resolved Main Application**
```
github "A" 1.0.0
github "B" 1.0.0
```

Everything looks as expected. 
Let's consider now the scenario where a new version of `B` gets released (for convenience called from now on 2.0.0) as well as a new version of `A` to 1.1.0 which uses the same `Carfile.resolved` as above (therefore `B` is still on 1.0.0)

If I run `carthage update A` in my main application, `A` gets updated, as expected, but `B` gets updated too even if not strictly required, outputting following results

**Carfile.resolved Main Application**
```
github "A" 1.1.0
github "B" 2.0.0      /// <= This should be on 1.0.0!
```

Is this the expected behavior or am I missing something in how Carthage is designed to be used?

**Comment by ikesyo** [comment]
That is expected behavior. If you need v1.x of B when resolved through A, you should need to write as follows in A's Cartfile:

```
github "B/B" ~> 1.0
```
