### ISSUE TITLE
Binaries aren't compatible in Xcode 9 -> 9.0.1

### ISSUE THREAD

**Issue by ichibod** [Carthage/Carthage#2219]
* `carthage version`: 0.26.2
* `xcodebuild -version`: 
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

Using binary frameworks, carthage says they're not compatible, even though everything runs and builds fine with the minor version update from Xcode 9 to 9.0.1. I'm not sure if this is expected behavior, but this should be allowed, especially in today’s world of Swift 3.2 and 4 compatibility.

**Carthage Output**
```
Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0 (swiftlang-900.0.65.2 clang-900.0.37).
```

**Comment by NachoSoto** [comment]
I'm not seeing this issue. If you have a sample project though please file it to Apple in http://bugs.swift.org, there's nothing we can do about this.

**Comment by mdiep** [comment]
This is intentional behavior on our part. The framework was built with a different version of the Swift compiler, so compatibility is **not** guaranteed. They may be compatible this time, but there's no way for Carthage to know that.

**Comment by NachoSoto** [comment]
Oh my bad, I thought this error was coming from Xcode. In that case, what @mdiep said :)

**Comment by NachoSoto** [comment]
It would be nice though to change that check to compare Swift version numbers, not including build number. I do think we can guarantee compatibility with that?

**Comment by BobElDevil** [comment]
We intentionally changed it from looking at swift version to swift compiler version, due to the fact that a compiler may support different versions of swift. For example, the current compiler can do both swift 3.2 and swift 4

**Comment by NachoSoto** [comment]
Right, but frameworks compiled with that version **are compatible with both** 3.2 and 4.0

**Comment by mdiep** [comment]
We look at the compiler version, not the language version. So if you distribute a 3.2 binary that was built with the same compiler version, then it's compatible with a 4.0 framework. If you distribute a 4.0 binary that was built with a different compiler version, then it's not compatible with a 4.0 framework.

Kinda makes you wish that the compiler version number was wholly different than the language version number.

**Comment by krzyzanowskim** [comment]
@NachoSoto Is there a way to provide a binaries for a single release that is compatible with Xcode 9 and 9.0.1?

**Comment by mdiep** [comment]
No there is not.

**Comment by fabiomassimo** [comment]
Maybe I'm seeing this in the wrong way but couldn't `Carthage` use semantic versioning constraints  to guarantee compatibility for different compiler versions?

e.g. `swiftlang`  version on Xcode 9 is `swiftlang-900.0.65`  while for Xcode 9.0.1 is `swiftlang-900.0.65.2`. This should guarantee the compatibility of the binaries. It works if we manually place the binaries (from Xcode 9.0.0) in the `Build` folder.

**Comment by mdiep** [comment]
> e.g. swiftlang version on Xcode 9 is swiftlang-900.0.65 while for Xcode 9.0.1 is swiftlang-900.0.65.2. This should guarantee the compatibility of the binaries. It works if we manually place the binaries (from Xcode 9.0.0) in the Build folder.

No, because swift explicitly does not guarantee compatibility between these versions. (It isn't versioned with semantic versioning wrt built binaries.)

**Comment by krzyzanowskim** [comment]
For prebuilt frameworks something like: search for the swift version in the filename would work as well, eg: `ReactiveCocoa-900.0.65.2.framework.zip` or something

**Comment by fabiomassimo** [comment]
😞 Thanks for explaining this.

I don't see this being a big issue (`Carthage` as fallback rebuilds the binary with new toolchain) if not for private sources, distributed via compiled binaries. What about using an option that ignores this check for dependencies included via the `binaries` mark?
