### ISSUE TITLE
Carthage cache should emphasize owner (possible forks) in separate directories

### ISSUE THREAD

**Issue by benjohnde** [Carthage/Carthage#2221]
For instance in `Cartfile`:
```
TheLevelUp/ZXingObjC
```

Results in:
```
/Users/bjohn/Library/Caches/org.carthage.CarthageKit/dependencies/ZXingObjC
```

And it should be:
```
/Users/bjohn/Library/Caches/org.carthage.CarthageKit/dependencies/TheLevelUp/ZXingObjC
```

Thus, working with different forks does not result in the pain of clearing the whole cache everytime you need a specific version of another fork.

**Comment by ikesyo** [comment]
This is a duplicate of #2143 and #2150.
