### ISSUE TITLE
Cartfile.resolved and dependency versions "branch name"

### ISSUE THREAD

**Issue by rob-nash** [Carthage/Carthage#2222]
I often use submodules and if I am actively developing a dependency:
1) I use "branch name" as the version for my dependency (in Cartfile).
2) I  use the source directly and pass the option --no-build.

When committing changes to a submodule, the Cartfile.resolved file must also be manually updated with the new commit. At times like these, I gitignore the file.

When running the option --use-submodles, would it be sensible to remove the Cartfile.resolved file? Maybe only remove it if the Cartfile has dependencies that point to "branch name"? Or keep it around but remove the commit position for dependencies that point to "branch name"?

**Comment by ikesyo** [comment]
> When committing changes to a submodule, the Cartfile.resolved file must also be manually updated with the new commit.

Aren't you using `carthage update` to updated the submodule? The command updates `Cartfile.resolved` so you don't need to update the file by hand.

**Comment by rob-nash** [comment]
So I should run carthage update after committing a submodule ?

**Comment by rob-nash** [comment]
To be clear, 'update the submodule' = modifying the source of the submodule i.e. writing code for the submodule.

**Comment by rob-nash** [comment]
My workspace will contain source from the checkouts folder and I may modify that source during development.

![screen shot 2017-10-19 at 12 48 06](https://user-images.githubusercontent.com/14126999/31769568-25d0e050-b4cc-11e7-879e-498b3c954d0c.jpg)

**Comment by rob-nash** [comment]
I will just ignore the Cartfile.resolved file permanently.
