### ISSUE TITLE
dyld: lazy symbol binding failed: __T07RxSwift10ObservableC4justACyxGxFZ

### ISSUE THREAD

**Issue by bobgodwinx** [Carthage/Carthage#2225]
* `carthage version`: 0.26.2
* `xcodebuild -version`: 9.0.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
github "ReactiveX/RxSwift" ~> 4.0.0
github "RxSwiftCommunity/Action" ~> 3.4.0
```

**Carthage Output**
```
[carthage-xcodebuild.db8vPq.log](https://github.com/Carthage/Carthage/files/1404005/carthage-xcodebuild.db8vPq.log)
```

**ERROR**

```
dyld: lazy symbol binding failed: Symbol not found: __T07RxSwift10ObservableC4justACyxGxFZ
  Referenced from: /Users/bob/Library/Developer/CoreSimulator/Devices/0D3E342D-7560-43B6-9A6D-33BC07968F05/data/Containers/Bundle/Application/3F4EC922-EC2E-4978-B1D6-2698C375474E/3.4.0.app/Frameworks/Action.framework/Action
  Expected in: /Users/bob/Library/Developer/CoreSimulator/Devices/0D3E342D-7560-43B6-9A6D-33BC07968F05/data/Containers/Bundle/Application/3F4EC922-EC2E-4978-B1D6-2698C375474E/3.4.0.app/Frameworks/RxSwift.framework/RxSwift

dyld: Symbol not found: __T07RxSwift10ObservableC4justACyxGxFZ
  Referenced from: /Users/bob/Library/Developer/CoreSimulator/Devices/0D3E342D-7560-43B6-9A6D-33BC07968F05/data/Containers/Bundle/Application/3F4EC922-EC2E-4978-B1D6-2698C375474E/3.4.0.app/Frameworks/Action.framework/Action
  Expected in: /Users/bob/Library/Developer/CoreSimulator/Devices/0D3E342D-7560-43B6-9A6D-33BC07968F05/data/Containers/Bundle/Application/3F4EC922-EC2E-4978-B1D6-2698C375474E/3.4.0.app/Frameworks/RxSwift.framework/RxSwift
```

**Test project**
https://github.com/orakaro/Test-Swift4

**Note***

I've tried all solution presented in #330 and removed even `brew + carthage` totally.
tried : 
```
sudo rm -rf /Library/Frameworks/CarthageKit.framework
rm -f /usr/local/bin/carthage
brew uninstall carthage
brew install carthage
```
Unlinked everything possible. Secondly the demo app of action works perfectly and when you do a manual build everything works. But as soon as you try using carthage you get the error above.
Please kindly help because I can't figure out what is happening underneath. 
[I also linked the issue on our repo `Action`](https://github.com/RxSwiftCommunity/Action/issues/112)

**Comment by ikesyo** [comment]
See https://github.com/RxSwiftCommunity/Action/issues/112#issuecomment-338385785. That is a project set up issue on RxSwiftCommunity/Action. Closing.
