### ISSUE TITLE
Build fails on Xcode 9 / macOS High Sierra (both for Swift 3.2 and 4.0)

### ISSUE THREAD

**Issue by ajaykoppisetty** [Carthage/Carthage#2226]
* `carthage version`: 0.25.0 
* `xcodebuild -version`: Xcode 9.0.1
Build version 9A1004
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes 

**Cartfile**
```
git "https://bitbucket.org/rapidbizapps/lehman-caves-dataengine-ios.git" "development"
github "gregttn/GTProgressBar" "master"
github "dzenbot/DZNEmptyDataSet"

```

**Carthage Output**
```
ubuntu:core-operator-ios AjayChander$ carthage build --platform iOS --cache-builds --no-skip-current
*** xcodebuild output can be found in /var/folders/pl/j6zmftqd0rg6js572wxckfn00000gp/T/carthage-xcodebuild.PcWjVp.log
*** Valid cache found for Alamofire, skipping build
*** Valid cache found for couchbase-lite-ios, skipping build
*** Valid cache found for DZNEmptyDataSet, skipping build
*** Valid cache found for GTProgressBar, skipping build
*** Valid cache found for IQKeyboardManager, skipping build
*** Valid cache found for pumbni-ios, skipping build
*** Valid cache found for Material, skipping build
*** Valid cache found for PopupDialog, skipping build
*** Valid cache found for sentry-cocoa, skipping build
*** Valid cache found for SwiftDate, skipping build
*** Valid cache found for dataengine-ios, skipping build
*** Building scheme "core-operator" in groundHog.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/user1/Documents/Bitbucket/core-operator-ios/project.xcodeproj -scheme core-operator -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/user1/Documents/Bitbucket/core-operator-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/pl/j6zmftqd0rg6js572wxckfn00000gp/T/carthage-xcodebuild.PcWjVp.log
```

```
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/user1/Documents/Bitbucket/core-operator-ios/project/Controllers/Inspections/PreopsVC.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

```

Trying to build custom framework but cannot build due to above errors. Cleaned up the directories and rebuild but no luck :(

**Comment by ikesyo** [comment]
Could you retry with upgrading Carthage to 0.26.2?

**Comment by ikesyo** [comment]
And also please check the actual xcodebuild log listed above to detect the more detailed error info.

> *** xcodebuild output can be found in /var/folders/pl/j6zmftqd0rg6js572wxckfn00000gp/T/carthage-xcodebuild.PcWjVp.log

**Comment by ajaykoppisetty** [comment]
@ikesyo I have upgraded the carthage to latest version but still no luck

```
ajs-MacBook-Pro-Touch:core-operator-ios user1$ carthage version
0.26.2
```

this is the error log from log file
```
** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/user1/Documents/Bitbucket/core-operator-ios/project/Controllers/Inspections/PreopsVC.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by ikesyo** [comment]
> The following build commands failed:

We don't get anything from the error message, so please found actual compiler errors. Or could you provide a minimal reproducible example project?

https://github.com/Carthage/Carthage/issues/2226#issuecomment-338832042

**Comment by ajaykoppisetty** [comment]
> We don't get anything from the error message, so please find actual compile errors. Or could you provide a minimal reproducible example project?

Is there any way to get the compile errors? because we are not seeing them in Xcode :(

Attaching the image of how the project structure is. Please go through the image once. We are facing the issue of building the Project X as framework from carthage. Through Xcode it is working fine. Hope this helps you in understanding the issue and guide me in correct direction

![screen shot 2017-10-24 at 10 03 35 am](https://user-images.githubusercontent.com/3489314/31924938-a1276768-b8a2-11e7-8687-30904edf3361.png)

**Comment by ikesyo** [comment]
From an xcodebuild log

> *** xcodebuild output can be found in /var/folders/pl/j6zmftqd0rg6js572wxckfn00000gp/T/carthage-xcodebuild.PcWjVp.log

**Comment by ajaykoppisetty** [comment]
[carthage-xcodebuild.PcWjVp.pdf](https://github.com/Carthage/Carthage/files/1409661/carthage-xcodebuild.PcWjVp.pdf)

**Comment by ikesyo** [comment]
I found the error from the log.

```
/Users/user1/Documents/Bitbucket/core-operator-ios/project/Controllers/Inspections/ PreopsVC.swift:87:41: error: use of unresolved identifier 'AnswersReferenceModel'
answersModel.append(AnswersReferenceModel(json: [VALUE: "", COMMENT: "", UPDATED_AT: "", CREATED_AT: ""])!)
^~~~~~~~~~~~~~~~~~~~~~~ DataEngine.OpsAnswerReferenceModel:1:47: note: did you mean
'OpsAnswerReferenceModel'?
@objc(OpsAnswerReferenceModel) public class OpsAnswerReferenceModel : NSObject,
CBLJSONEncoding {
^
DataEngine.UserReferenceModel:1:42: note: did you mean 'UserReferenceModel'?
@objc(UserReferenceModel) public class UserReferenceModel : NSObject, CBLJSONEncoding
{
^
```

**Comment by ajaykoppisetty** [comment]
@ikesyo  thank you so much (heart) It worked. I'm not sure why the Xcode build was successful with this.
