### ISSUE TITLE
How to provide carthage support for existing cocoa pod github repository.

### ISSUE THREAD

**Issue by KiranJasvanee** [Carthage/Carthage#2231]
I've tried to find exact step to step solution to integrate carthage support in my existing library - https://github.com/KiranJasvanee/KJCircularSlider.
Can you please provide a better approach to integrate carthage in existing GitHub public repos.

**Comment by blender** [comment]
Just share the scheme for the target you want carthage to build. That is clearly documented here: https://github.com/Carthage/Carthage#share-your-xcode-schemes

**Comment by mdiep** [comment]
If there are specific parts that you're struggling with, please ask about them specifically. Asking for "a better approach" isn't really actionable or helpful.
