### ISSUE TITLE
Build failure on carthage update from secondary dependencies

### ISSUE THREAD

**Issue by doctorcolinsmith** [Carthage/Carthage#2234]
* `carthage version`: 0.26.2
* `xcodebuild -version`: 9.0.1 / 9A1004
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`?  No

I have two framework projects.  The first depends on the AWS SDK, the second depends on the first.  I can build and run the unit tests for the first, but the second fails when running `carthage update`.  Looking on at the log file, the failure happens when building the first framework on the import of the AWS framework.

I created a stripped down example for testing.

https://github.com/doctorcolinsmith/carthage-problem-a is a framework that depends on the AWS SDK.  This framework builds fine and the unit tests run.

https://github.com/doctorcolinsmith/carthage-problem-b depends on framework-a.  When I run `carthage update` for this framework, it fails.

To reproduce the problem locally, it should be sufficient to pull down framework-b and run `carthage update`

This is a blocking issue for us to adopt Carthage for our apps.  And since my dev team is complaining about Cocoapods daily, any help solving this will be much appreciated!

**Comment by mdiep** [comment]
`Cartfile`s _must_ be in the root directory of the repository. That seems like the likely source of the error.

If moving the `Cartfile`s doesn't fix the issue, can you please post the error you get when running `carthage update`?

**Comment by doctorcolinsmith** [comment]
Thanks!  That comment was very insightful to solving the problem.  The full solution was to move both the Cartfile and project file up to the root of the repository.

Based on this, I would like to make two recommendations:
* The README should specify the required locations of the Cartfile and Xcode project file.
* A warning could be issued when pulling a framework from source and the Cartfile is not found in the correct location.
