### ISSUE TITLE
Carthage doesn't handle Finder-created binary zips

### ISSUE THREAD

**Issue by jlawton** [Carthage/Carthage#2237]
* `carthage version`: 0.26.2
* **Output**: Unable to determine framework Swift version.

I know that zipping a framework with Finder isn't the sanctioned way of creating binary archives, but I think it's reasonable to support it. The problem is that Finder adds OSX junk to the zip, including files that Carthage interprets as Frameworks.

```
MyFramework.framework/
└── Headers/
    └── MyFramework-Swift.h
__MACOSX/
└── MyFramework.framework/
    └── Headers/
        └── ._MyFramework-Swift.h
```

The Swift version check looks in `._MyFramework-Swift.h` and doesn't find the expected comment. Excluding the `__MACOSX` directory when checking out zip files would fix this.

**Comment by blender** [comment]
fixed in #2235
