### ISSUE TITLE
Should Carthage be modifying .xcscheme files?

### ISSUE THREAD

**Issue by tomcondon** [Carthage/Carthage#2238]
* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 9.0 Build version 9A235
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`?  No

**Cartfile**
```
Not Allowed to.
```

Carthage is modifying "/Users/me/Projects/xxx/xxx.xcworkspace/xcshareddata/xcschemes/xxx.xcscheme "  files where earlier version did not.  Is this expected behavior.

**Comment by mdiep** [comment]
Ideally, no. I haven't seen this. But if the `.xcscheme` is being modified, it's by Xcode (but perhaps because of an `xcodebuild` invocation). Either way, there's nothing that Carthage can do about it.
