### ISSUE TITLE
Passing the --no-build flag to the bootstrap command doesn't download the binaries

### ISSUE THREAD

**Issue by bsarrazin** [Carthage/Carthage#2245]
* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 9.1 Build version 9B55
* Are you using `--no-build`? Yes
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "AppsFlyerSDK/AppsFlyerFramework" "4.7.2"
github "RxSwiftCommunity/RxKeyboard"
```

**Carthage Output**
```
$ carthage bootstrap --use-ssh --no-build --platform iOS
...
[22:39:26]: ▸ *** Checking out AppsFlyerFramework at "4.7.2"
[22:39:26]: ▸ *** Cloning AppsFlyerFramework
[22:39:38]: ▸ *** Checking out RxKeyboard at "0.7.1"
[22:39:38]: ▸ *** Cloning RxKeyboard
...
```

** Problem **
Passing the `--no-build` flag to the `bootstrap` command doesn't download the binaries and there doesn't seem to be a `--use-binaries` in any other command.

The problem is caused by libraries that do not offer a way to build the binary by the consumer but does provide a prebuilt binary archive. It would be great if there was a way to `checkout + download bins` instead of `checkout` or `checkout + build` options only.

Thoughts?

**Comment by mdiep** [comment]
I see what you're saying, but I'm kinda on the fence about whether this is something we should try to enable. The workflow would be a little convoluted. Right now, binaries are considered an optimization on top of building, which is why they're treated as a single step.

**Comment by bsarrazin** [comment]
> binaries are considered an optimization
I agree with you, however that is not necessarily how the community uses the feature.
You can take a look at a conversation that happened on the RxKeyboard repo: https://github.com/RxSwiftCommunity/RxKeyboard/issues/45

Distributing the binary is the _only_ supported method.

**Comment by ikesyo** [comment]
> Distributing the binary is the only supported method.

In that cases `binary` origin should be used I think.

**Comment by bsarrazin** [comment]
@ikesyo I'm not sure what you mean, can you explain?

**Comment by ikesyo** [comment]
See https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-only-frameworks.

**Comment by bsarrazin** [comment]
Ah! Perfect! I totally missed that.
Then I believe this issue is resolved. Closing.
Thank you for your help!
