### ISSUE TITLE
module compiled with Swift 4.0.2 cannot be imported in Swift 3.2.1

### ISSUE THREAD

**Issue by Megatron1000** [Carthage/Carthage#2247]
* `carthage version`: 0.26.2
* `xcodebuild -version`: 9.1 (9B55)
* Are you using `--no-build`No
* Are you using `--no-use-binaries`Yes
* Are you using `--use-submodules`No
* Are you using `--cache-builds`No

**Cartfile**
```
github "Hearst-DD/ObjectMapper" == 2.2.9
```

**Carthage Output**
```
*** Fetching ObjectMapper
*** Checking out ObjectMapper at "2.2.9"
*** xcodebuild output can be found in /var/folders/9v/ln0zn4sx7cs1hdtw6x5z3wzw0000gn/T/carthage-xcodebuild.UifyRT.log
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
```

My build works locally but fails on Travis. I'm updating the app to work with Xcode 9. It's compiling with Swift 3.2. The build always fails on the first Swift file that imports the ObjectMapper dependency, which is the only thing I'm building the Carthage. 
The error is:
`module compiled with Swift 4.0.2 cannot be imported in Swift 3.2.1: /Users/travis/build/ConnectedHomes/myHomeIOS/Carthage/Build/iOS/ObjectMapper.framework/Modules/ObjectMapper.swiftmodule/x86_64.swiftmodule`
From what I make of this I've built dependency with the latest version of Swift but running `carthage update` but it doesn't like this because the Swift file using it wants to use Swift 3.2.1.However, I can't see a way of building with Swift 3.2.1, since that's not a toolchain that's in Xcode 9.x or Xcode 8.x.

**Comment by NachoSoto** [comment]
This isn't a Carthage issue. See https://github.com/travis-ci/travis-ci/issues/8700.
