### ISSUE TITLE
iTunes Сonnect dSYM (symbols) issue with Charts framework.

### ISSUE THREAD

**Issue by OlionCompany** [Carthage/Carthage#2250]
carthage version: 0.26.2
xcodebuild -version: Version 9.1 (9B55)
Are you using --use-submodules? : Yes

Dear developer,
We have discovered one or more issues with your recent delivery for "***". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
Too many symbol files - These symbols have no corresponding slice in any binary [DC4DB2ED-B5A7-3B56-A317-8811B5F13228.symbols, E39A1E57-05B2-36BF-A417-40FDC0F7133B.symbols]
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
Regards,
The App Store team

Charts framework for iOS platform.

**Comment by mdiep** [comment]
It sounds like you just have stale files in your `Carthage/Build/` directory.
