### ISSUE TITLE
No shared schemes found when overriding MACH_O_TYPE

### ISSUE THREAD

**Issue by Mazyod** [Carthage/Carthage#2251]
I've seen many posts that suggest using Xcode 9's native static framework support, but I'm not having any luck making it work. I made a simple xcconfig file to override the MACH_O_TYPE, but that leads to carthage not finding the schemes somehow:

```
MACH_O_TYPE = staticlib
DEBUG_INFORMATION_FORMAT = dwarf
```

* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 9.1 Build version 9B55
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "scalessec/Toast" ~> 3.1.0
```

**Carthage Output**
```
% export XCODE_XCCONFIG_FILE="carthage.xcconfig"
% carthage update --no-use-binaries --platform iOS                                                 ~/Developer/careem/ios-commons
*** Fetching Toast
*** Checking out Toast at "3.1.0"
*** xcodebuild output can be found in /var/folders/nm/hybvjjw14nqd6lypkrpf3prr0000gn/T/carthage-xcodebuild.8PCs6u.log
*** Skipped building Toast due to the error:
Dependency "Toast" has no shared framework schemes for any of the platforms: iOS
```

**Comment by ikesyo** [comment]
That is because Carthage now does not support static frameworks. See #1935 and #1379 for the details. Closing.
