### ISSUE TITLE
The file “Cartfile” couldn’t be opened because you don’t have permission to view it

### ISSUE THREAD

**Issue by gaponte1985** [Carthage/Carthage#2258]
* `carthage version`: 0.26.2 
* `xcodebuild -version`: Version 9.1 (9B55)
I am runing the command:   

**carthage update —platform iOS**

Rushs-MacBook-Pro:~ rush$ carthage update —platform iOS
Failed to read file or folder at /Users/rush/Cartfile: Error Domain=NSCocoaErrorDomain Code=257 "The file “Cartfile” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/rush/Cartfile, NSUnderlyingError=0x7ffc4860c430 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}

Can someone help me please? thanks.

**Comment by ikesyo** [comment]
Please examine the permission of the file as the error message says.

**Comment by bgates284** [comment]
I have the same issue but upon examining the file, I (admin) have read/write access and it's not locked
