### ISSUE TITLE
prebuilt binary in private Github repository release is "Downloading" but does not actually appear in the Carthage/Build folder

### ISSUE THREAD

**Issue by LeeA1985** [Carthage/Carthage#2259]
* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 8.3.2 Build version 8E2002
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
...
github "lumoslabs/unity_ios_export" == 0.1
...

**Carthage Output**
...
*** Downloading unity_ios_export.framework binary at "0.1"
*** Checking out unity_ios_export at "0.1"
...

***Additional Information***
An intermediate .unity_ios_export.version file is created in the Carthage/Build directory with these contents:

{
  "Mac" : [
  ],
  "watchOS" : [
  ],
  "tvOS" : [
  ],
  "commitish" : "0.1",
  "iOS" : [
  ]
}

Other prebuilt frameworks that we are already using seem to end up with some entries under each of the supported platforms where this one doesn't seem to be picking up the entry that should be under iOS.

Can anyone see anything I am missing? The private repository has a '0.1' release with an associated .framework.zip file uploaded to it that contains an Info.plist with DTPlatformName=iphoneos.

**Comment by LeeA1985** [comment]
@mdiep Any ideas on the cause of this issue or where to troubleshoot? I have seen recently closed issues around prebuilt binaries being inaccessible from private repos that have been fixed by using GITHUB_ACCESS_TOKEN, but that doesn't seem to be the issue here since it appears to be finding a release binary framework at the tag and attempting "Downloading" but failing to move to Carthage/Build for some reason.

**Comment by ikesyo** [comment]
Can you share the attached zip file? It will be a help.

**Comment by LeeA1985** [comment]
Thank you for the quick response 🙏 

Unfortunately, I cannot share the attached zip because it is built with some proprietary code that I cannot distribute outside of our published iOS app ( Lumosity ). The attached zip is named <unique_name>.framework.zip and contains a pre built <unique_name>.framework file that contains an  entry in the Info.plist with DTPlatformName=iphoneos entry.

- are there any other notable requirements of the .framework.zip or the contained .framework file needed to download correctly as a prebuilt binary?
- are there any notable steps that occur between the "Downloading...binary at..." event and actually unarchiving the binary framework to Carthage/Build folder?
- is there any additional logging that I can enable to see where an error might be occurring? --verbose seems to only add additional logs for checkout/build step

Note: As a quick test, I also tried uploading an existing .framework.zip already being used by another 3rd party ( Leanplum ) into our Github repository release, but the same behavior still occurs. This *may* imply that the issue is not with the .framework.zip artifact, but I'm not sure.

**Comment by ikesyo** [comment]
We are not using `DTPlatformName` so that is irrelevant (I suppose you are referring to  `DTSDKName`?): https://github.com/Carthage/Carthage/blob/8915f54a31fe61bbd46d3fd80c312eaacd0dedee/Source/CarthageKit/Project.swift#L1085-L1112

**Comment by LeeA1985** [comment]
Ah, I see. Yes, we have DTSDKName=iphoneos10.3

**Comment by LeeA1985** [comment]
Something is wrong with calling the Github REST API to upload the release asset in this case. If I upload the release asset manually through the Github website, the prebuilt binary is used by Carthage as expected. If I upload the same asset using the Github REST API, the asset is "Downloading..." but never copied to Carthage/Build. The only discernible difference that I can see is that 'label' for the asset uploaded through Github website is 'null' where it is '' when uploaded through Github REST API. I'm not sure if that is the cause but I'm looking into it now. Github REST API is supposed to support setting 'label' on upload but that doesn't seem to be working for me.

**Comment by LeeA1985** [comment]
Phew! It turns out that the problem was just a single character typo in "Content-Type: **application/zip**" when uploading the asset with Github REST API. The API was uploading without a reported failure and Carthage was attempting "Downloading" without a logged failure even though the prebuilt framework was actually being ignored because it was not of the expected content type. 🏁 

Consequently, we decided to instead use https://github.com/octokit/octokit.rb to interact with Github API more safely.
