### ISSUE TITLE
Supporting Carthage with dependency

### ISSUE THREAD

**Issue by sbarow** [Carthage/Carthage#2261]
I am trying to add support for Carthage to our project [uber/RIBs](https://github.com/uber/RIBs/tree/carthage) which has a dependency on `RxSwift` its not entirely clear how we get Carthage to know to download the `RxSwift` dependency?

In an example project if the `Cartfile` only contains:
```
github "uber/RIBs" "carthage"
```

It will download the project but fail on the build step as there is no `RxSwift`, updating our example apps `Cartfile` to be:
```
github "uber/RIBs" "carthage"
github "ReactiveX/RxSwift"
```
will successfully fetch & build.

Is there a way to get Carthage to download dependencies automatically without users having to add the additional `RxSwift` dep to their `Cartfile`? [RxAlamofire](https://github.com/RxSwiftCommunity/RxAlamofire) seems to be getting this right but I can't see what is different to our implementation and how you specify to download project dependencies?

**Comment by ikesyo** [comment]
`Cartfile` must be in a top level of a repository. Looks like you locate it in `ios` folder so that is the cause.

**Comment by sbarow** [comment]
Thanks @ikesyo - might be useful to put this in the docs?
