### ISSUE TITLE
Can I use static framework in Carthage?

### ISSUE THREAD

**Issue by sarunw** [Carthage/Carthage#2265]
* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 9.1(9B55)
* Are you using `--no-build`? Tried
* Are you using `--no-use-binaries`? Tried
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`?  NO

**Cartfile**
```
binary "file:///PATH_TO_JSON"
```

**Carthage Output**
```
Failed to read file or folder at /private/var/folders/dl/wz1qp1r50jzf08kvnv77mhh80000gn/T/carthage-archive.ZYnhYb/__MACOSX/IAPMicroApplication.framework: Error Domain=com.antitypical.Result Code=0 "the DTSDKName key in its plist file is missing" UserInfo={com.antitypical.Result.file=/tmp/carthage-20171014-5839-1rwellh/Source/CarthageKit/Project.swift, com.antitypical.Result.function=readFailed, com.antitypical.Result.line=1087, NSLocalizedDescription=the DTSDKName key in its plist file is missing}
```

I want to make my project as framework for main project to use, the problem is my project and main project need to use static framework.

I don't sure about the term, but I tried run `file FRAMEWORK_NAME.framework/FRAMEWORK_NAME` and result show `current ar archive` I have read some post and this considered static framework.

So my plan is to have `Cartfile` in both my main and my project that reference this static framework hoping Carthage will resolve dependency.

```
binary "file:///PATH_TO_LOCAL_JSON_FILE"
```

and in PATH_TO_LOCAL_JSON_FILE I have
```
{
  "1.0.0": "file:///PATH_TO_FRAMEWORK_ZIP"
}
```

When I run `carthage update` on my project I got something like this
```
Failed to read file or folder at /private/var/folders/dl/wz1qp1r50jzf08kvnv77mhh80000gn/T/carthage-archive.ZYnhYb/__MACOSX/IAPMicroApplication.framework: Error Domain=com.antitypical.Result Code=0 "the DTSDKName key in its plist file is missing" UserInfo={com.antitypical.Result.file=/tmp/carthage-20171014-5839-1rwellh/Source/CarthageKit/Project.swift, com.antitypical.Result.function=readFailed, com.antitypical.Result.line=1087, NSLocalizedDescription=the DTSDKName key in its plist file is missing}
```

Don't sure what should I do or even this is even possible in Carthage?

**Comment by blender** [comment]
Yes #2235
