### ISSUE TITLE
-bash: carthage: command not found

### ISSUE THREAD

**Issue by holyen** [Carthage/Carthage#2267]
* `carthage version`: 0.26.2
* `xcodebuild -version`: xcode9.1
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```
when i install from Carthage.pkg,then "carthage update" it show me "-bash: carthage: command not found"

**Comment by ikesyo** [comment]
Please make it sure that `usr/local/bin` is existing on your `$PATH`.
