### ISSUE TITLE
Ignore build directory on GitHub

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#2274]
I wasn't aware that this part of GitHub was open source, but today I ran into this: https://github.com/github/linguist/pull/3865

It would be awesome to do the same for `Carthage/Build/` 😀

**Comment by NachoSoto** [comment]
I'll send a PR today.

**Comment by NachoSoto** [comment]
https://github.com/github/linguist/pull/3920

**Comment by Medo3oo311** [comment]
#72270

**Comment by Medo3oo311** [comment]
#2274
