### ISSUE TITLE
Failed to copy framework to Carthage/Build/

### ISSUE THREAD

**Issue by chrisamanse** [Carthage/Carthage#2275]
* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 9.1 Build version 9B55
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "alexeyxo/protobuf-objc" "master"
```

**Carthage Output**
```
$ carthage update --platform iOS
*** Fetching protobuf-objc
*** Checking out protobuf-objc at "4048c115909469288cc1967aa23b0d5291e381c1"
*** xcodebuild output can be found in /var/folders/bx/4dknbg7j0vv6t1jt1rvlz33xgmjp_n/T/carthage-xcodebuild.BdZ4bW.log
*** Building scheme "ProtocolBuffers Framework" in ProtocolBuffers.xcodeproj
Failed to write to <user_path>/temp/SampleApp/Carthage/Checkouts/protobuf-objc/Carthage/Build/iOS/ProtocolBuffers.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “ProtocolBuffers.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///<user_path>/temp/SampleApp/Carthage/Checkouts/protobuf-objc/src/runtime/Build/ArchiveIntermediates/ProtocolBuffers%20Framework/BuildProductsPath/Release-iphoneos/ProtocolBuffers.framework, NSFilePath=<user_path>/temp/SampleApp/Carthage/Checkouts/protobuf-objc/src/runtime/Build/ArchiveIntermediates/ProtocolBuffers Framework/BuildProductsPath/Release-iphoneos/ProtocolBuffers.framework, NSUnderlyingError=0x7fb7e8c4b960 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

This project is using a legacy path for its build artifacts (relative to project instead of derived data), however, in [PR #2158 Source/CarthageKit/BuildSettings.swift#L186](https://github.com/Carthage/Carthage/pull/2158/files?diff=split#diff-2c8b811867554fe0cd24adead2bd16daR186), the archive directory pattern is hardcoded instead of using an Xcode project settings value (may be SYMROOT: `xcodebuild -showBuildSettings | grep SYMROOT`), thus, the build output can't be found.

Legacy path setting for build location can be found in `File > Project Settings > Advanced`:
![screen shot 2017-11-30 at 11 10 35 am](https://user-images.githubusercontent.com/12277586/33450586-220ad69a-d5c1-11e7-97e7-3da774c1c30b.png)

**Comment by ikesyo** [comment]
Unfortunately Carthage does not support Legacy build location (since it is legacy). Please switch to other options.
