### ISSUE TITLE
Some dependencies¹ NSCocoaErrorDomain Code=260 with `archive` builds · ⑴ Possibly AFNetworking, possibly constrained to versions around v3.1.0

### ISSUE THREAD

**Issue by gaofengwh** [Carthage/Carthage#2277]
* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 9.1 Build version 9B55
* Are you using `--no-build`?  yes
* Are you using `--no-use-binaries`?  no 
```
carthage update --no-use-binaries
*** Fetching AFNetworking
*** Checking out AFNetworking at "3.1.0"
*** xcodebuild output can be found in /var/folders/_0/8yz75xc560j4_y5l6nljr_7r0000gn/T/carthage-xcodebuild.IyOaSI.log
*** Building scheme "AFNetworking iOS" in AFNetworking.xcworkspace
Failed to write to /Users/gaofeng/Desktop/TestCarthage/Carthage/Build/iOS/AFNetworking.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “AFNetworking.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/gaofeng/Desktop/TestCarthage/Carthage/Checkouts/AFNetworking/build/ArchiveIntermediates/AFNetworking%20iOS/BuildProductsPath/Release-iphoneos/AFNetworking.framework, NSFilePath=/Users/gaofeng/Desktop/TestCarthage/Carthage/Checkouts/AFNetworking/build/ArchiveIntermediates/AFNetworking iOS/BuildProductsPath/Release-iphoneos/AFNetworking.framework, NSUnderlyingError=0x7f99fc64d130 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```
* Are you using `--use-submodules`? 
```
gaofeng:TestCarthage gaofeng$ carthage update  --use-submodules
*** Fetching AFNetworking
*** Checking out AFNetworking at "3.1.0"
A shell task (/usr/bin/env git submodule --quiet sync --recursive (launched in /Users/gaofeng/Desktop/TestCarthage)) failed with exit code 128:
fatal: Not a git repository (or any of the parent directories): .git
```
* Are you using `--cache-builds`? 
```
gaofeng:TestCarthage gaofeng$ carthage update  --cache-builds
*** Fetching AFNetworking
*** Downloading AFNetworking.framework binary at "3.1.0"
*** Checking out AFNetworking at "3.1.0"
*** No cache found for AFNetworking, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/_0/8yz75xc560j4_y5l6nljr_7r0000gn/T/carthage-xcodebuild.Oushrr.log
*** Building scheme "AFNetworking OS X" in AFNetworking.xcworkspace
Failed to write to /Users/gaofeng/Desktop/TestCarthage/Carthage/Build/Mac/AFNetworking.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “AFNetworking.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/gaofeng/Desktop/TestCarthage/Carthage/Checkouts/AFNetworking/build/ArchiveIntermediates/AFNetworking%20OS%20X/BuildProductsPath/Release/AFNetworking.framework, NSFilePath=/Users/gaofeng/Desktop/TestCarthage/Carthage/Checkouts/AFNetworking/build/ArchiveIntermediates/AFNetworking OS X/BuildProductsPath/Release/AFNetworking.framework, NSUnderlyingError=0x7fc658720fd0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```
**Cartfile**
```
github "AFNetworking/AFNetworking"
```

**Carthage Output**
```
Failed to write to /Users/gaofeng/Desktop/TestCarthage/Carthage/Build/Mac/AFNetworking.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “AFNetworking.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/gaofeng/Desktop/TestCarthage/Carthage/Checkouts/AFNetworking/build/ArchiveIntermediates/AFNetworking%20OS%20X/BuildProductsPath/Release/AFNetworking.framework, NSFilePath=/Users/gaofeng/Desktop/TestCarthage/Carthage/Checkouts/AFNetworking/build/ArchiveIntermediates/AFNetworking OS X/BuildProductsPath/Release/AFNetworking.framework, NSUnderlyingError=0x7fc658720fd0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by peres** [comment]
Did you solve your problem? I'm having it with AFNetworking, too, in Carthage 0.27.

**Comment by nomadplanet** [comment]
I personally had to switch back to carthage 0.24 to «fix» the issue

**Comment by mdiep** [comment]
I think this is related to Carthage's use of `xcodebuild archive`.

**Comment by c0diq** [comment]
Same problem here.

**Comment by ikesyo** [comment]
This may be a duplicate of #2220.

**Comment by maddanio** [comment]
anything we can do? this blocks our builds...:(

**Comment by ikesyo** [comment]
Please make it sure that you don’t have `SYMROOT` build setting as described in https://github.com/Carthage/Carthage/issues/2220#comment-337629280.

**Comment by maddanio** [comment]
the cartfile is super simple:
github "AFNetworking/AFNetworking" ~> 3.1
github "swisspol/GCDWebServer" ~> 3.2.5
github "SVProgressHUD/SVProgressHUD"
and then we just run carthage bootstrap --platform iOS

**Comment by maddanio** [comment]
ah, you mean in AFNetworking itself?

**Comment by maddanio** [comment]
i cannot find any symroot settings in afnetworking. also switching to 3.2 did not help.

**Comment by blender** [comment]
I just tried with the `Cartfile` you have indicated and I'm not seeing the issue. Try removing your Cartfile.resolved

carthage 0.28.0
Xcode 9.2

**Comment by maddanio** [comment]
no dice :(. removed the resolved file, deleted Carthage folder. same versions of XCode and carthage. The latter installed via homebrew. osx is 10.12.6 (sierra).

**Comment by blender** [comment]
Can you share a zip of a test project where this happens?

**Comment by maddanio** [comment]
Will do this afternoon. So you mean the Carthage dir after the failure?

**Comment by maddanio** [comment]
ok, i looked at the file system vs the error message. the error is:

Failed to write to /Users/daniel/Documents/git/game-on-ios/dependencies/Carthage/Build/iOS/AFNetworking.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “AFNetworking.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/daniel/Documents/git/game-on-ios/dependencies/Carthage/Checkouts/AFNetworking/build/ArchiveIntermediates/AFNetworking%20iOS/BuildProductsPath/Release-iphoneos/AFNetworking.framework, NSFilePath=/Users/daniel/Documents/git/game-on-ios/dependencies/Carthage/Checkouts/AFNetworking/build/ArchiveIntermediates/AFNetworking iOS/BuildProductsPath/Release-iphoneos/AFNetworking.framework, NSUnderlyingError=0x7fbf73d78d90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

and indeed, the folder Carthage/Checkouts/AFNetworking/build/ArchiveIntermediates does not exist. that build folder only contains the directories AFNetworking.build and Release-iphonesimulator.
also i grepped for "ArchiveIntermediates" and cannot find it mentioned anywhere, so I am not sure why it assumes it exists.

**Comment by AlessandroMulloni** [comment]
Also seeing this issue, with Xcode 9.3 and Carthage 0.29.0. 
No matter which project is in my Cartfile, I always end up with the same error where the file is looked for in the /.../ArchiveIntermediates/... folder.
Only reverting to Carthage 0.24.0 fixes the issue for me, any newer version is not working.

**Comment by AlessandroMulloni** [comment]
I just found a fix for this issue, it is a rather hidden XCode setting. Please refer to my latest comment on the thread here: https://github.com/Carthage/Carthage/issues/2220

Feel free to validate and close this issue.

**Comment by maddanio** [comment]
So what do i do? Can Carthage fix it? Or does, in my case, AFNetworking need to do this?

**Comment by jdhealy** [comment]
@maddanio I'm curious as to why @blender wasn’t able to reproduce the issue, and the answer may be attainable from the build settings from an AFNetworking build on your machine.

For you to grab those build settings would require cautiously making and reverting some changes to `~/Library/Preferences/com.apple.dt.Xcode.plist`, and then cautiously redacting some environment variables (which _all_ get output) from the `carthage` output. (Wish there was a better way…)

If you're okay with that, the instructions are below:

<details><summary>Instructions to Cautiously Follow, Remembering to Make Redactions on Output</summary>

1. Quit Xcode.
1. `cd /Users/daniel/Documents/git/game-on-ios && ditto ~/Library/Preferences/com.apple.dt.Xcode.plist /var/tmp && defaults write com.apple.dt.xcode BuildSettingsLogLevel -int 3 && defaults write com.apple.dt.xcode BuildSettingExpansionLogLevel -int 3 && defaults write com.apple.dt.xcode BuildLogLevel -int 3 && killall -u $USER cfprefsd`
1. `carthage … --verbose`
1. copy the output
1. inspect closely and make redactions — ⚠️ your environment variables will _all_ be in that output, so tread carefully
1. [upload it as a gist](https://help.github.com/articles/creating-gists/)
1. post the gist here
1. <ul><li><code>cd /Users/daniel/Documents/git/game-on-ios && defaults write com.apple.dt.xcode BuildSettingsLogLevel -int 1 && defaults write com.apple.dt.xcode BuildSettingExpansionLogLevel -int 1 && defaults write com.apple.dt.xcode BuildLogLevel -int 1 && killall -u $USER cfprefsd</code></li><li>❕<em>or — preferably, but more cautiously —</em> quit Xcode → overwrite <code>~/Library/Preferences/com.apple.dt.Xcode.plist</code> with <code>/var/tmp/com.apple.dt.Xcode.plist</code> → <code>killall -u $USER cfprefsd</code> and hope for the best</li></ul>
</details>

**Comment by AlessandroMulloni** [comment]
@maddanio apologies if my comment was misleading. The issue you mentioned was happening for me for **every** Carthage package, not just for AFNetworking. In that case I had to fix my local build setup.

If you remove AFNetworking do GCDWebServer and SVProgressHUD compile fine?

**Comment by maddanio** [comment]
But I did nothing on my machine. It’s Carthage downloading from github and building. Still I can check

Gruß!

Daniel Oberhoff

**Comment by maddanio** [comment]
Oh, you are saying those settings may be system wide? How evil...another reason to despise Xcode...

Gruß!

Daniel Oberhoff

**Comment by AlessandroMulloni** [comment]
@maddanio I did nothing either, still the setting was set to "Legacy" when I went checking. Maybe it's some setting that was kept from an older XCode version, I also use the beta versions every now and then. I honestly do not know why it was not set to the default.

**Comment by kas-kad** [comment]
having the same issue on 0.29.0, resolution of https://github.com/Carthage/Carthage/issues/2220 doesn't help. Only switching back to 0.25.0 helps.

**Comment by jdhealy** [comment]
@kas-kad, would you be [willing to (cautiously) share your build settings](https://github.com/Carthage/Carthage/issues/2277#issuecomment-377595623)? (If you’re using Xcode’s legacy build system, otherwise those instructions aren’t applicable.)

That would help us greatly in diagnosing and reproducing the issue.

**Comment by kas-kad** [comment]
@jdhealy I reproduced the issue on Carthage 0.30.1. Here are the logs https://gist.github.com/kas-kad/beefae3c83fa060db0cbe39b0f9e3510

**Comment by jdhealy** [comment]
@kas-kad infobip/mobile-messaging-sdk-ios has SYMROOT set ([here](https://github.com/infobip/mobile-messaging-sdk-ios/blob/ca4ff9c1444a883790b9de343a38a3aef265bf94/MobileMessaging.xcodeproj/project.pbxproj#L1332) and [here](https://github.com/infobip/mobile-messaging-sdk-ios/blob/ca4ff9c1444a883790b9de343a38a3aef265bf94/MobileMessaging.xcodeproj/project.pbxproj#L1389)).

See @ikesyo’s comment: https://github.com/Carthage/Carthage/issues/2277#issuecomment-374176655

I was able to build correctly with Carthage v0.29.0 after removing those lines, `cd`-ing to it’s directory, and running `carthage build --no-skip-current --verbose`.

- - -

When you mentioned “blank new project”: was that a framework that you created where you saw the `NSCocoaErrorDomain Code=260` error output when it was added to a Cartfile?

**Comment by kas-kad** [comment]
@jdhealy removing SYMROOT setting helped me. Thanks!

**Comment by bsabiston** [comment]
So is there an easy answer to this problem?  I am unable to update my Dropbox SDK via Carthage because of this error.  @maddanio what did you have to do to get it to work?

**Comment by bsabiston** [comment]
@jdhealy I read that, but my Derived Data build location is already set to 'Unique' ...

**Comment by maddanio** [comment]
Clearing Xcode State is the one usually

**Comment by maddanio** [comment]
Can we all agree that a (badly done) globally strateful buildsystem is a bad idea?

**Comment by zhouyuanbo** [comment]
@bsabiston   Update to the latest Carthage version: 0.31.2. It worked for me.
