### ISSUE TITLE
Please update to the latest Carthage version: 0.26.2. You currently are on 0.26.0

### ISSUE THREAD

**Issue by normida** [Carthage/Carthage#2278]
Hi

I tried many times to install the latest version of Carthage, I downloaded Cartage package 2.6.2 and upgraded my current version but It still not allow me to install in my Xcode project

Please update to the latest Carthage version: 0.26.2. You currently are on 0.26.0

**Comment by abhijithp2018** [comment]
I got the same issue :

**Comment by blender** [comment]
@abhijithp2018  Please run 
- `which carthage`
- `brew info carthage`

**Comment by Vkt0r** [comment]
@blender This is reproducible with the latest release `0.29.0`. When I run `carthage` I got:

```bash
Please update to the latest Carthage version: 0.29.0. You currently are on 0.28.0
```

**`which carthage`**:    
```bash
/usr/local/bin/carthage
```

**`brew info carthage`**
```bash
carthage: stable 0.28.0 (bottled), HEAD
Decentralized dependency manager for Cocoa
https://github.com/Carthage/Carthage
/usr/local/Cellar/carthage/0.28.0 (69 files, 26.7MB) *
  Poured from bottle on 2018-02-11 at 23:48:55
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/carthage.rb
==> Requirements
Build: xcode ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```

I tried `carthage update && brew upgrade carthage` unsuccessfully 😢.

**Comment by blender** [comment]
Homebrew formula is not merged yet. You can try brew upgrade carthage - - HEAD

**Comment by Vkt0r** [comment]
@blender Uhmm that is why. That made the trick 👍 thanks

**Comment by jcabreram** [comment]
@blender, I think you've got a couple of extra spaces there. It should be:
`brew upgrade carthage --HEAD`

**Comment by zshakeel123** [comment]
You can run below command to update carthage to latest version,

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by jdhealy** [comment]
To upgrade to the latest stable version via [Homebrew](https://brew.sh/): run `brew upgrade carthage`.

Alternatively, install a `Carthage.pkg` download from https://github.com/Carthage/Carthage/releases/.
