### ISSUE TITLE
Carthage breaks if the same dependency is pulled in multiple times.

### ISSUE THREAD

**Issue by bwhiteley** [Carthage/Carthage#2284]
The app depends on Frameworks `A` and `B`. `A` and `B` both depend on Framework `C`. 
It looks like Carthage tries to process `C` twice, thus causing a data race where they stomp on each other. 

Note there are multiple possible errors since it's a data race. Examples below include the `index.lock` problem as well as an attempt to copy the `description` file a second time. 

Multiple users are experiencing this with multiple projects. Note that if you try it enough times it may eventually work (since it's a race condition). Usually it fails though. 

This bug goes back to at least version 0.11.0. 

* `carthage version`: 0.26.2
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b
* Are you using `--no-build`? yes (or not)
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
<Multiple, Internal repos>
```

**Carthage Output**
(note: the `C` library below is `apicore`)
```
$ carthage update --no-build
...
*** Fetching apicore
...
*** Checking out apicore at "1.2.0"
*** Checking out apicore at "1.2.0"
...
A shell task (/usr/bin/env git checkout --quiet --force 1.2.0 (launched in ~/Library/Caches/org.carthage.CarthageKit/dependencies/apicore)) failed with exit code 128:
fatal: Unable to create '~/Library/Caches/org.carthage.CarthageKit/dependencies/apicore/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

```
Note: the `index.lock` file does not exist if you look for it afterward. It's already been cleaned up.

Alternate error: 
```
$ carthage update
*** Fetching ...
*** Cloning logger
*** Cloning logger
*** Cloning logger
*** Cloning logger
*** Cloning ...
A shell task (/usr/bin/env git clone --bare --quiet ssh://git@host.example.com:7999/project/logger.git
~/Library/Caches/org.carthage.CarthageKit/dependencies/logger) failed with exit code 128:
fatal: cannot copy '/Applications/Xcode-9.2.app/Contents/Developer/usr/share/git-core/templates/description' to '~/Library/Caches/org.carthage.CarthageKit/dependencies/logger/description': File exists
```
(in this case `C` was `logger`)

**Comment by ikesyo** [comment]
Could you share a reproducible case? We don't see such errors in Carthage's development itself with the Cartfile: https://github.com/Carthage/Carthage/blob/master/Cartfile

**Comment by bwhiteley** [comment]
It's possible this is a result of inconsistent repo URLs. Multiple hostnames resolve to the same git server. 
`-git "ssh://git@stash.example.com:7999/project/apicore.git" ~> 1.0`
vs. 
`-git "ssh://git@stash01.example.com:7999/project/apicore.git" ~> 1.0`

**Comment by mdiep** [comment]
That would definitely cause a problem. Carthage has no way of knowing that those resolve to the same repo.

**Comment by bwhiteley** [comment]
Closing: known/acceptable limitation.

**Comment by flockoffiles** [comment]
Is there some recommended work-around for this "acceptable" limitation?
In our case we host some dependencies locally, and the same repository is referred to (in the Cartfile) in two ways:
- Via a git ssh link
- Via a github link

Although it is exactly the same repository (and exactly the same tag), Carthage chokes on it, spitting out the "Unable to create" error.

Is there a way to prevent concurrent git updates with Carthage?

**Comment by olejnjak** [comment]
Well not sure if it is acceptable limitation, e.g. CI can genuinely trigger two exact same builds at the same time (more merge requests and merging a MR triggers deploy job), very often we now run into error mentioned above.

I'll try to prepare an example project, but this is an issue that makes Carthage mostly unusable on CI machines that run more jobs in parallel.

**Comment by tmspzz** [comment]
> Well not sure if it is acceptable limitation, e.g. CI can genuinely trigger two almost exactly same builds at the same time (more merge requests and merging a MR triggers deploy job), very often we now run into error mentioned above.
> 
> I'll try to prepare an example project, but this is an issue that makes Carthage mostly unusable on CI machines that run more jobs in parallel.

You're not supposed to run carthage in parallel

**Comment by BennettSmith** [comment]
A good example of this issue arises when trying to use the Amazon AWS Amplify frameworks.  Here is a Cartfile that seems like it should work, but does not because one of these Amazon frameworks has an internal dependency on the other.  The app with this Cartfile wants to make use of both Amplify and the underlying mobile SDK frameworks. 
```
github "aws-amplify/aws-sdk-ios"
github "awslabs/aws-mobile-appsync-sdk-ios"
```
If we are unable to pull in both of these frameworks, I fail to see how this is an "acceptable" limitation.  As @flockoffiles inquired above, is there a recommended work-around?

**Comment by jdhealy** [comment]
@BennettSmith, let me look into that particular case…
