### ISSUE TITLE
Does Carthage supports Static library in Swift 4?

### ISSUE THREAD

**Issue by sagargondaliya** [Carthage/Carthage#2285]
* `carthage version`:  0.26.2
* `xcodebuild -version`: Xcode 9.1(9B55)
* Are you using `--no-build`? :  No
* Are you using `--no-use-binaries`? : No
* Are you using `--use-submodules`?  : No
* Are you using `--cache-builds`? : No

**Carthage Output**
```
*** Skipped building poc_objc_static_lib due to the error:
Dependency "poc_objc_static_lib" has no shared framework schemes
```

**NOTE : I can not expose Carthage git Url, as it is private for organization.**
I have one Static library and schema for that marked as shared. But it fails to build it with `no shared framework schemes`.

Also question asked on [Stackoverflow](https://stackoverflow.com/questions/47674333/does-carthage-supports-static-library-in-swift-4).

**Comment by blender** [comment]
I can look into this

**Comment by blender** [comment]
Hi, Carthage does not support building static libraries. You can try with a static framework instead.
