### ISSUE TITLE
copy-frameworks fails with "Environment variable not set: FRAMEWORKS_FOLDER_PATH"

### ISSUE THREAD

**Issue by dyeazel** [Carthage/Carthage#2296]
* `carthage version`:  latest
* `xcodebuild -version`:  latest
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no

**Cartfile**
```
# Library for logging
# https://github.com/CocoaLumberjack/CocoaLumberjack
github "CocoaLumberjack/CocoaLumberjack"

# Nordic Semiconductor official iOSDFULibrary
# https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library
github "NordicSemiconductor/IOS-Pods-DFU-Library" # ~> x.y //Replace x.y with your required version
```

**Carthage Output**
```
Environment variable not set: FRAMEWORKS_FOLDER_PATH
Command /bin/sh failed with exit code 1
```

Subject says it all. copy-frameworks expects and environment variable called FRAMEWORKS_FOLDER_PATH. Where do I set this? It's not in any of the doc's.

**Comment by ikesyo** [comment]
`copy-frameworks` is meant to be run from Xcode's Run Script phases, so that will be set by Xcode automatically.

**Comment by dyeazel** [comment]
I did run it from the Run Script phase, as described in the readme. I still get the error.

**Comment by KevinGong2013** [comment]
@dyeazel for osx target no need that `Run Script phase.`
