### ISSUE TITLE
carthage not generate arm7

### ISSUE THREAD

**Issue by iOSleep** [Carthage/Carthage#2297]
* `carthage version`: 0.27.0
* `xcodebuild -version`: Xcode 9.2
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? YES
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO

**Cartfile**
```
github "hackiftekhar/IQKeyboardManager"
```

**Carthage Output**
```
*** Fetching IQKeyboardManager
*** Checking out IQKeyboardManager at "v5.0.7"
*** xcodebuild output can be found in /var/folders/xz/7kwyhf7j0_j4fpm7ym_3s_0c0000gn/T/carthage-xcodebuild.wGSaMY.log
*** Building scheme "IQKeyboardManagerSwift" in IQKeyboardManager.xcodeproj
*** Building scheme "IQKeyboardManager" in IQKeyboardManager.xcodeproj
```
![image](https://user-images.githubusercontent.com/26478957/34190444-c4fb08b0-e57b-11e7-9979-96d4759f2903.png)

I check the IQKeyboardManager, it supports `armv7` in **Build Setting** .
may the framework do some other things, what should i do to support `armv7`

**Comment by ikesyo** [comment]
iOS 11 is 64 bit only and the project's `IPHONEOS_DEPLOYMENT_TARGET` is set to `11.0`. So you should file an issue on that repo to request to lower that version.

**Comment by ikesyo** [comment]
Ref: https://github.com/hackiftekhar/IQKeyboardManager/issues/1186
