### ISSUE TITLE
WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "-" is not installed

### ISSUE THREAD

**Issue by yaroslav-zhurakovskiy** [Carthage/Carthage#2299]
* `carthage version`: 0.9.3
* `xcodebuild -version`:  Xcode 9.2 Build version 9C40b

**Cartfile**
```
github "alikaragoz/MCSwipeTableViewCell" >= 2.1.4
github "Quick/Nimble"
github "ReactiveX/RxSwift" ~> 4.0
github "realm/realm-cocoa"
github "WenchaoD/FSCalendar"
github "danielgindi/Charts" ~> 3.0.4
github "Exyte/Macaw" ~> 0.9.1
```

When I try to build some dependencies I get the following warning.

```
WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "-" is not installed
```

The problem is it builds for iOS Devices but it does not build frameworks for Simulators.
I really want to switch to Carthage, but it seems like it just does not work. 
Even frameworks like https://github.com/exyte/Macaw or Rxswift that claim to support Carthage do not build.

I hope you can help me. Thanks.

**Comment by ikesyo** [comment]
0.9.3 is too-oudated version. Please update to the latest version (currently 0.27.0).

**Comment by yaroslav-zhurakovskiy** [comment]
Thank you! It do not know why, but I had a very old version.
