### ISSUE TITLE
lips can't figure our the architecture type

### ISSUE THREAD

**Issue by yaroslav-zhurakovskiy** [Carthage/Carthage#2302]
* `carthage version`:  0.27.0
* `xcodebuild -version`:  Xcode 9.2 Build version 9C40b
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`?  Yes

**Cartfile**
```
github "alikaragoz/MCSwipeTableViewCell" >= 2.1.4
github "Quick/Nimble"
github "ReactiveX/RxSwift" ~> 4.0
github "realm/realm-cocoa"
github "WenchaoD/FSCalendar"
github "danielgindi/Charts" ~> 3.0.4
github "Exyte/Macaw" ~> 0.9.1
github "yaroslav-zhurakovskiy/PainlessInjection" "master"
binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Fabric.json"
binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Crashlytics.json"
github "patchthecode/JTAppleCalendar" ~> 7.0
```

When I build the project on my laptop. Everything works fine. But when I try to build using Xcode Build Server it get the following error.  It fails for different frameworks.
**An extract from the build log.**
```
Testing failed:
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't figure out the architecture type of: /Users/yaroslav/Library/Caches/XCSBuilder/Bots/acea34fd078b36393a0491235e00030c/DerivedData/Build/Products/Dev-iphonesimulator/RxCocoa.framework.dSYM/Contents/Resources/DWARF/RxCocoa
** TEST FAILED **


The following build commands failed:
	PhaseScriptExecution Carthage /Users/yaroslav/Library/Caches/XCSBuilder/Bots/acea34fd078b36393a0491235e00030c/DerivedData/Build/Intermediates.noindex/Tackler.build/Dev-iphonesimulator/Tackler.build/Script-C44939A21FEF921900E6D9D9.sh
```

**Comment by yaroslav-zhurakovskiy** [comment]
BTW. It is happening in the "/usr/local/bin/carthage copy-frameworks" phase.

**Comment by yaroslav-zhurakovskiy** [comment]
Thank you. I was able to resolve this issue one my own.

**Comment by nicopuri** [comment]
@yaroslav-zhurakovskiy How did you solve it?

**Comment by nicopuri** [comment]
@yaroslav-zhurakovskiy How did you solve it?

**Comment by yaroslav-zhurakovskiy** [comment]
@nicopuri As far as I remember the problem was that I tried to copy frameworks to the test bundle using "/usr/local/bin/carthage copy-frameworks". I had XCTest bundles that were using some frameworks. Initially I tried to copy those frameworks using "Carthage copy script". It was a mistake. You should use simple "Copy Frameworks" file phase. I hope it will help you.

<img width="847" alt="screen shot 2018-03-14 at 3 38 52 pm" src="https://user-images.githubusercontent.com/3489125/37405700-fe2c2a7e-279d-11e8-9c54-db53d743591d.png">

<img width="321" alt="screen shot 2018-03-14 at 3 41 13 pm" src="https://user-images.githubusercontent.com/3489125/37405770-316a0e56-279e-11e8-8aff-38f8bd687005.png">
