### ISSUE TITLE
Cache invalidated when an incompatible binary is available

### ISSUE THREAD

**Issue by olejnjak** [Carthage/Carthage#2308]
Hi, 

I like using Carthage as compared to Cocoapods it speeds up most of our build times especially on our CI server.

One thing that improved times the most are prebuilt binaries which are awesome as long as they are compiled using the same Swift version. Right now we have the issue that Realm provides binary compiled using Swift 4.0.2 and we are using 4.0.3. This means that while running `carthage update --cache-builds` or `carthage bootstrap --cache-builds` it is rebuilt every time which is quite annoying. 

I know this can be solved by adding `--no-use-binaries` to the command but I think it's a shame not to use compatible binaries when they are available.

Is there any chance or desire that `--no-use-binaries` could be implemented on per dependency basis defined in Cartfile? 

Thanks

* `carthage version`: 0.27.0
* `xcodebuild -version`: 9.2 (9C40b)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

**Cartfile**
```
github "realm/realm-cocoa"
```

**Carthage Output**
```
Jakub-Macbook:ACKReactiveExtensions olejnjak$ carthage update --platform iOS --cache-builds
*** Fetching realm-cocoa
*** Downloading realm-cocoa.framework binary at "v3.0.2"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
```

**Comment by mdiep** [comment]
Are you saying that the hosted binary invalidates the cached build? If so, that's a bug.

But there's not a way to specify `--no-use-binaries` on a per-dependency basis.

**Comment by olejnjak** [comment]
> Are you saying that the hosted binary invalidates the cached build? If so, that's a bug.

Yep cache is invalidated, can be reproduced easily

At first it is built which is correct
```
Jakub-Macbook:realm olejnjak$ echo 'github "realm/realm-cocoa"' > Cartfile
Jakub-Macbook:realm olejnjak$ carthage update --platform iOS --cache-builds
*** Fetching realm-cocoa
*** Downloading realm-cocoa.framework binary at "v3.0.2"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
```

If running with `--no-use-binaries` cache is valid and everything is fine
```
Jakub-Macbook:realm olejnjak$ carthage bootstrap --platform iOS --cache-builds --no-use-binaries
*** Checking out realm-cocoa at "v3.0.2"
*** xcodebuild output can be found in /var/folders/5g/dxznwg850518m5fx369sfmsc0000gn/T/carthage-xcodebuild.l4lOYc.log
*** Valid cache found for realm-cocoa, skipping build
```

If omitted the cache is overwritten by the binary from github so it is invalid so it is rebuilt
```
Jakub-Macbook:realm olejnjak$ carthage bootstrap --platform iOS --cache-builds
*** Downloading realm-cocoa.framework binary at "v3.0.2"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out realm-cocoa at "v3.0.2"
*** xcodebuild output can be found in /var/folders/5g/dxznwg850518m5fx369sfmsc0000gn/T/carthage-xcodebuild.MS6ETX.log
*** Invalid cache found for realm-cocoa, rebuilding with all downstream dependencies
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
```

**Comment by mdiep** [comment]
Would you be interested in trying to fix this? 😅

**Comment by olejnjak** [comment]
Sure I can try 😉

**Comment by olejnjak** [comment]
Well, I'll try to look into it. 

If you could please give me a hand from where to start, it would be awesome. I mean a hand with the code I already got to contribution and code style guide. :-)

**Comment by mdiep** [comment]
`VersionFile` is what's saved to disk to determine whether the framework should be rebuilt. I'd look to see what's in that file and determine why it's not considered a match.

**Comment by olejnjak** [comment]
Thanks, in the meantime I've been looking more into it and it seems like binaries are always copied to the project `Carthage/Build` directory before version files are compared to the binaries using `Project.unarchiveAndCopyBinaryFrameworks(zipFile:projectName:pinnedVersion:toolchain)` method so the SHA hash changes to the downloaded binary which is incompatible. Will try to fix that somehow.

**Comment by olejnjak** [comment]
I consider this issue a duplicate to #2317 so there is no need to keep two threads.

**Comment by olejnjak** [comment]
Hi, I think it might be useful to reopen this issue. Maybe the name of the ticket is not that accurate now but I think it is worth a shot.

The main problem for me was that Realm and RealmSwift take a long time to compile. So I've been digging into it and saw that there's new version of realm-cocoa which should fix that. However, it didn't, the provided framework was still compiled using Swift 4.0.2. 

So I tried to link both frameworks manually into an empty project and it worked. So I was wondering if it is desired behavior (or known issue) that Carthage seems to make 4.0.2 and 4.0.3 binaries incompatible even though they should work together? 

More info and example project can be found here - https://github.com/realm/realm-cocoa/issues/5538#issuecomment-360879857.

**Comment by mdiep** [comment]
> So I was wondering if it is desired behavior (or known issue) that Carthage seems to make 4.0.2 and 4.0.3 binaries incompatible even though they should work together?

Yes. Binaries created from Swift 4.0.2 and 4.0.3 are explicitly not guaranteed to be compatible. They may coincidentally be compatible, but there's no guarantee, so Carthage can't consider them compatible.

**Comment by olejnjak** [comment]
👍
