### ISSUE TITLE
Option to check that built dependencies are up to date

### ISSUE THREAD

**Issue by olejnjak** [Carthage/Carthage#2311]
Hi, 

I'd like to ask if there is an option to check that my locally built dependencies are up to date. I don't mean if they are using the latest version available (`carthage update`).

For several reasons we ignore the whole *Carthage* directory in gitignore so the case would be that the project uses some dependency in version let's say 1.0.0. Whole team works on it and someone updates it to 1.0.1 so *Cartfile.resolved* is updated. If in 1.0.1 version is no breaking change other wouldn't notice. 

My idea would be to store a copy of *Cartfile.resolved* in *Carthage* directory so we can add a build phase script which compares actual *Cartfile.resolved* and the version in *Carthage* directory, which would be almost similar to the behavior that Cocoapods do.

Thanks

**Comment by BobElDevil** [comment]
So there's a version file written for each build, for use with the `--cache-builds` flag (documented [here](https://github.com/Carthage/Carthage#caching-builds))  which can be passed to both `bootstrap` and `build`. When it detects that you're up to date it will skip building a dependency. That's not exactly what you want, as there's no command to check the cache values without a build being run, but the code exists so it could be a future enhancement to extract the code to run by itself in a separate command, and verify that bootstrap == the cache value. 

In the meantime if you get in the habit of running a bootstrap with '--cache-builds' you can at least run it without fear of waiting for redundant builds

**Comment by olejnjak** [comment]
Yep we use `--cache-builds` as this is the main reasons we switched from Cocoapods. If I find a while to look into this I could try to implement it if it would be a desired enhancement.

**Comment by ikesyo** [comment]
This may be what you want: https://github.com/Carthage/workflows/blob/master/README.md#carthage-verify

**Comment by olejnjak** [comment]
YES! Thanks!
