### ISSUE TITLE
How to compile framework without Armxxx? I just want to compile my framework for my simulator

### ISSUE THREAD

**Issue by willonboy** [Carthage/Carthage#2313]
* `carthage version`: 0.24.0
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b

How to compile framework without Armxxx? I just want to compile my framework for my simulator.
i use command 'carthage update --cache-builds' to compile my source code but it's so slowly. my friend tell me that carthage will compile  arm64 armv7 and  i386  x86_64 at the same time.

**Comment by jdhealy** [comment]
```shell
tee ${PWD}/Carthage/simulator-only.xcconfig <<-'EOF'
SUPPORTED_PLATFORMS = iphonesimulator
EOF

XCODE_XCCONFIG_FILE="${PWD}/Build/simulator-only.xcconfig" carthage build --platform iOS --no-skip-current --verbose
```

…and remove `--no-skip-current` if you’re not in your framework’s directory.

**Comment by willonboy** [comment]
Thank you very much!   ^_^

**Comment by jdhealy** [comment]
##### More correct.

```shell
tee ${PWD}/Build/simulator-only--more-correct.xcconfig <<-'EOF'
// Operating under the precondition that Carthage will be flagged `--platform iOS`…
PLATFORM_NAME[sdk=iphonesimulator*] = iphonesimulator
PLATFORM_NAME[sdk=iphoneos*] = iphonesimulator

// overwrite SUPPORTED_PLATFORMS into emptiness — exceptions being the modules and
// corresponding values that we will list (mostly, multi-platform, single scheme modules —
// see http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/ for
// more info…)
SUPPORTED_PLATFORMS__PRODUCT_MODULE_NAME_PrettyColors = iphonesimulator
SUPPORTED_PLATFORMS = $(SUPPORTED_PLATFORMS__PRODUCT_MODULE_NAME_$(PRODUCT_MODULE_NAME))
EOF

XCODE_XCCONFIG_FILE="${PWD}/Build/simulator-only--more-correct.xcconfig" carthage build --platform iOS --no-skip-current --verbose
```

…😪…and remove `--no-skip-current` if you’re not in your framework’s directory.

Tested with [Curry](https://github.com/thoughtbot/Curry), [PrettyColors](https://github.com/jdhealy/PrettyColors), [Nimble](https://github.com/Quick/Nimble), [ReactiveSwift](https://github.com/ReactiveCocoa/ReactiveSwift), [Result](https://github.com/antitypical/result) · Xcode 9C40b · [Carthage 0.27.0](https://github.com/Carthage/Carthage/releases/tag/0.27.0).

##### Watch this space.

I believe the possibility for a fairly simple patch to Carthage exists, which would allow a one line `xcconfig` (so, no having to list exceptions to `SUPPORTED_PLATFORMS` — in fact, premised on not having to modify `SUPPORTED_PLATFORMS` at all…). Will update when posted.

**Comment by jdhealy** [comment]
@willonboy, [you should see the above](https://github.com/Carthage/Carthage/issues/2313#issuecomment-357830342)…
