### ISSUE TITLE
Can you add some conflict tips into carthage ?

### ISSUE THREAD

**Issue by willonboy** [Carthage/Carthage#2314]
* `carthage version`: 0.24.0
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b
* Are you using `--no-build`?   NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? YES

My cartfile config some reference both use binary and source code 
Like:
binary "http://xxx...c.framework.json"  ~> 0.x.x
binary "http://xxx...d.framework.json"  ~> 0.x.x
binary "http://xxx...e.framework.json"  ~> 0.x.x
git "git@http://xxxx....A.git" "branch_name"
git "git@http://xxxx....B.git" "branch_name"

And A.git's Cartfile also reference c.framework, d.framework, e.framework
Like:
binary "http://xxx...c.framework.json"  ~> 0.y.y
binary "http://xxx...d.framework.json"  ~> 0.y.y
binary "http://xxx...e.framework.json"  ~> 0.y.y

And B.git's Cartfile also reference c.framework, d.framework, e.framework
Like:
binary "http://xxx...c.framework.json"  ~> 0.z.z
binary "http://xxx...d.framework.json"  ~> 0.z.z
binary "http://xxx...e.framework.json"  ~> 0.z.z

When i command 'carthage update --cache-builds ' to compile source, and then it's go wrong without any tips.

**Comment by willonboy** [comment]
i know i can use '==', but  in my scene, i must use "~>"

**Comment by mdiep** [comment]
I'm not sure what you're asking for.

**Comment by willonboy** [comment]
binary (framework) version conflict make command 'carthage update --cache-builds ' go wrong without any tips.
