### ISSUE TITLE
Archive was built with wrong Swift version

### ISSUE THREAD

**Issue by akantsevoi** [Carthage/Carthage#2315]
* carthage version `0.27.0`: 
* xcodebuild -version `Xcode 9.2 Build version 9C40b`: 
* xcrun swift -version `Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)`: 

I'm making my internal `X framework`

**X Framework .pbxproj**
`SWIFT_VERSION = 4.0;`

**X framework Cartfile**
```
github "SwiftyJSON/SwiftyJSON"
github "daltoniam/Starscream"
```

**X framework Carthage Output**
```
*** Checking out zlib-spm at "1.1.0"
*** Checking out Starscream at "3.0.3"
*** Checking out SwiftyJSON at "4.0.0"
*** Checking out common-crypto-spm at "1.1.0"
*** xcodebuild output can be found in /var/folders/v1/lq987zt117b5xjm7423p97nh0000gn/T/carthage-xcodebuild.eCZBjg.log
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
*** Building scheme "Starscream" in Starscream.xcodeproj
```

Everything is okay on that step.

Then I've created archive by script:

```
#/bin/sh

carthage build --no-skip-current --platform iOS --verbose
carthage archive XFramework
```

Then I upload my XFramework.zip, create manifest.json and try to use it in a different project:

**Project Carthage**
```
github "SwiftyJSON/SwiftyJSON"
github "daltoniam/Starscream"
binary "https://gitlab.path/to/manifest.json" == 1.0.0
```

**Project Carthage output**
```
*** Fetching Starscream
*** Fetching SwiftyJSON
*** Downloading binary-only framework manifest at "https://gitlab.path/to/manifest.json"
*** Fetching common-crypto-spm
*** Fetching zlib-spm
*** Checking out common-crypto-spm at "1.1.0"
Incompatible Swift version - framework was built with 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2).
```

And it's strange that my X framework was built with 3.0.2 swift.
Also I tried again with carthage cache cleaned `rm -rf ~/Library/Caches/org.carthage.CarthageKit` but it didn't help.

 Do you have any ideas what can be wrong?

**Comment by mdiep** [comment]
Carthage doesn't do anything with the Swift version specifically. If you look in the xcodebuild output from Carthage, find the `xcodebuild` invocation that creates the binary, and run that from the command-line, it should build with the same Swift version. Try checking what version you get out of that.

**Comment by akantsevoi** [comment]
Shame on me. I put wrong raw link. Because I had 2 almost the same repos.
1_000_000 Sorry for disturbing.
