### ISSUE TITLE
get libraries for carthrage project which are just available on cocoapod

### ISSUE THREAD

**Issue by rezakhmf** [Carthage/Carthage#2316]
I've updated my project from cocoa pods to carthage but I have a problem with some old libraries e.g. ACSPinKit, ABPadLockScreen which are just available through pods. Could you please help me for this? thanks

**Comment by mdiep** [comment]
1. Add a `.xcodeproj` or `.xcworkspace` if one doesn't exist
2. Create a dynamic framework target if one doesn't exist
3. Share the scheme for that target
4. Maybe tag a new version

There's some information in the README as well.

**Comment by rezakhmf** [comment]
thanks @mdiep I've ended up to keep cocoa pods as the number of pods which not supporting carthage are many on my project. luckily I had to copy over a framework manually on my project to make the cocoa pod happy to support mix of swift and obejt c code
