### ISSUE TITLE
How to config not build source code

### ISSUE THREAD

**Issue by willonboy** [Carthage/Carthage#2324]
* `carthage version`: 0.24.0
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`?  YES

My Cocoa Touch Framework Project named  "Helloworld"
**Cartfile**
```
binary "xxx.com/xx.json" ~>  x.x.x
binary "xxx.com/A.framework.json" ~>  x.x.x  # i link A.framework binary to my project
git "git@xxx.xxx.com...xxx.git"  "A.framework.branch"   # i just want to use some header file which not public 

```
In my case, i want to use some header file which not public in A.framework. (For some reason some header file can't public)
My 'Helloworld' project will build out a  Cocoa Touch Framework, so i have no need to compile A.framework source code. 
I config it  just want to carthage help me to checkout and update A.framework source code,
But when i want to build my 'Helloworld' project, it always compile A.framework source code.
How to config it .

**Comment by blender** [comment]
You can run `carthage checkout xxx.xxx.com`

**Comment by willonboy** [comment]
em...
i mean when i run command like this: (i need build out Helloworld.framework)
```
carthage build --platform iOS
```
then it's will compile A.framework source code that i configured in Cartfile. But i don't want to compile it.

**Comment by blender** [comment]
`carthage build --platform iOS list,of,framewroks,you,want,to,buid`
leave the frameworks you don't want to build out of the list.
