### ISSUE TITLE
Misleading prompt wording

### ISSUE THREAD

**Issue by kalkwarf** [Carthage/Carthage#2326]
When Carthage prompts to be updated, it uses the sentence:

> Please update to the latest Carthage version: 0.27.0. You currently are on 0.26.2

Which is great! Except I use `brew` to manage Carthage, which means I almost always mis-type this:

```
$ brew update carthage
Error: This command updates brew itself, and does not take formula names.
Use 'brew upgrade carthage' instead.
```

If the wording were changed to

> Please `upgrade` to the latest Carthage version: 0.27.0. You currently are on 0.26.2

it would save me 0.1 seconds of typing, each update.

**Comment by mdiep** [comment]
If you want to open a pull request for this, I'll merge it. ☺️

**Comment by jdhealy** [comment]
Yeah, I empathize with you @kalkwarf,  have the verb match brew makes a lot of sense when so many use it as the method to grab a newer carthage version.

I'm tentatively against shipping this change, though.

A troublesome aspect of outputting this message (at all) is that those who consume the output of `carthage` sometimes want to compare the output, and have methods of excluding the "Please update" message by string searching for that (or with more verbiage, but along the same line).

Weighing that breakage, with consideration that brew includes it’s own safeguarding, user-helping message about `update`, trends me towards :-1: on this…
