### ISSUE TITLE
Is XCGLogger not compatible?

### ISSUE THREAD

**Issue by mrgrauel** [Carthage/Carthage#233]
I try to use carthage cause I do like the simplicity over cocoapods, but I cannot get XCGLogger to work.

My Cartfile looks like:
github "DaveWoodCom/XCGLogger" ~> 1.8
github "realm/realm-cocoa" ~> 0.89.0

I get the Realm.framework but no XCGLogger.framework. Maybe because the xcodeproject file is in a subdirectory? Can I specify the subfolder in the command? I can't find anything in the man page.

**Comment by DaveWoodCom** [comment]
Merged that PR into XCGLogger. Thanks.
