### ISSUE TITLE
New release to support 4.1 snapshots

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#2330]
* `carthage version`: 0.27.0

Would it be possible to tag a new release to include #2282? 🙏 (I can't currently build from source because of #2331.)

I'm confused though cause I renamed the toolchain to the format that's supposedly currently understood by `Carthage 0.27.0`: (_see #1303 for how to find the toolchain ID_)
```bash
cd /Library/Developer/Toolchains
mv swift-4.1-DEVELOPMENT-SNAPSHOT-2018-01-18-a.xctoolchain swift-DEVELOPMENT-SNAPSHOT-2018-01-18-a.xctoolchain
```
And it's still failing:
```bash
$ carthage update --toolchain org.swift.4120180118a
*** Fetching ...
*** Checking out ... at "c7166692980176af87265746fe9b7af78c5d6ecd"
*** xcodebuild output can be found in /var/folders/x7/pd6q3qp51cs1xm86457mm88m0000gn/T/carthage-xcodebuild.H2HZnv.log
Unable to determine local Swift version.
```

When I open the `xcodebuild` log there's nothing in it, as in it doesn't actually build anything.

**Comment by mdiep** [comment]
https://github.com/Carthage/Carthage/releases/tag/0.28.0

Sorry for the delay! I should be back to more regular maintenance now.
