### ISSUE TITLE
On trying command carthage update, am getting update command not found

### ISSUE THREAD

**Issue by Sakash** [Carthage/Carthage#2337]
* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 

**Cartfile**
```
github "Alamofire/Alamofire" ~> 4.5
github "rs/SDWebImage"
github "ninjaprox/NVActivityIndicatorView"
```

**Carthage Output**
```
Error: Command "update" does not exist.
```
<img width="515" alt="screen shot 2018-01-29 at 6 53 21 pm" src="https://user-images.githubusercontent.com/5800576/35512440-d346ea5a-0525-11e8-9470-dcb197025dd0.png">

**Comment by mdiep** [comment]
What's the output of `carthage version`?

**Comment by Sakash** [comment]
<img width="531" alt="screen shot 2018-01-29 at 7 00 32 pm" src="https://user-images.githubusercontent.com/5800576/35512716-bb70339a-0526-11e8-82e4-990ff33ef5c4.png">

**Comment by mdiep** [comment]
That's not the right `carthage`.

`which carthage` might be of help, but this isn't a Carthage issue.

**Comment by Sakash** [comment]
Finally after spending a day issue was export path wasn't correct.
which can be set like this
export PATH="/usr/local/bin:$PATH"

[https://github.com/Carthage/Carthage/issues/2267](https://github.com/Carthage/Carthage/issues/2267)
