### ISSUE TITLE
Carthage doesn't handle several frameworks in one github release zip

### ISSUE THREAD

**Issue by SanjoDeundiak** [Carthage/Carthage#2345]
* `carthage version`: 0.28.0
* `xcodebuild -version`: 0.2
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO

**Cartfile**
```
github "VirgilSecurity/virgil-foundation-x" "3.0.0-beta11"
```

**Carthage Output**
```
*** Downloading virgil-cryptoapi-x.framework binary at "1.0.0-beta1"
*** Downloading virgil-foundation-x.framework binary at "3.0.0-beta11"
*** Skipped installing virgil-foundation-x.framework binary due to the error:
	"Parse error: unexpected SDK key "tvos""
*** Checking out virgil-foundation-x at "3.0.0-beta11"
*** xcodebuild output can be found in /var/folders/9w/w3nd1hb547l2jxtqbfbv41g40000gn/T/carthage-xcodebuild.4Fg9Nn.log
*** Building scheme "VirgilCrypto macOS" in VirgilCrypto.xcodeproj
```

zip archive inside virgil-foundation-x repo contains 3 prebuilt frameworks for all 4 platforms (12 in total). xcodeproject contains 12 corresponding shared schemes.

Expected result:
Zip is unarchived and all frameworks can be found under Carthage/Build

P.S. With --no-build or --no-use-binaries works great

**Comment by blender** [comment]
I'm afraid this works as expected. The archive was not created with `carthage archive`

**Comment by SanjoDeundiak** [comment]
@blender it was. https://github.com/VirgilSecurity/virgil-foundation-x/blob/3.0.0-beta11/.travis.yml

**Comment by blender** [comment]
Thanks, I found the problem already.
