### ISSUE TITLE
Failed to read file or folder building framework with carthage build --no-skip-current

### ISSUE THREAD

**Issue by fuzzybinary** [Carthage/Carthage#2350]
Building this repository: 
https://github.com/fuzzybinary/HYPWebSocketServerPlugin

Then running:
carthage update
carthage build --no-skip-current

* `carthage version`: 0.27
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No

**Cartfile**
```
github "willowtreeapps/Hyperion-iOS" "master"
github "fuzzybinary/PocketSocket" "feature/ios_carthage"
```

**Carthage Output**
The following is the output from carthage build --no-skip-current

```
*** Building scheme "AttributesInspector" in HyperionFramework.xcworkspace
*** Building scheme "Measurements" in HyperionFramework.xcworkspace
*** Building scheme "SlowAnimations" in HyperionFramework.xcworkspace
*** Building scheme "HyperionCore" in HyperionFramework.xcworkspace
*** Building scheme "PocketSocket-Mac" in PocketSocket.xcodeproj
*** Building scheme "PocketSocket-iOS" in PocketSocket.xcodeproj
*** Building scheme "HYPWebSocketServerPlugin" in HYPWebSocketServerPlugin.xcodeproj
Failed to read file or folder at /Users/jeffward/Library/Developer/Xcode/DerivedData/HYPWebSocketServerPlugin-cnnpgalxajvdnocnvdhdkkdjbuae/Build/Intermediates.noindex/ArchiveIntermediates/HYPWebSocketServerPlugin/BuildProductsPath/Release-iphoneos/HYPWebSocketServerPlugin.framework
```

the file is a symlink to another folder in DerivedData ending with `IntermediateBuildFilesPath/UninstalledProducts/iphoneos/` but this appears to be where xcode wants to put the framework by default

**Comment by blender** [comment]
Hi,

apparently for some strange reason I can't quite figure out `HYPWebSocketServerPlugin.framework` when read as a `Bundle` contains no information https://github.com/Carthage/Carthage/blob/c21ed7cc47b1e67a1fe36606f34cb2a95d009c8e/Source/CarthageKit/Xcode.swift#L1186

**Comment by blender** [comment]
I have fix, but this is very, very weird. 

The bundle information does not load correctly because of the resource folder your have inside.

The fix is something like:
```
let infoPath = Bundle!.path(forResource: "Info", ofType: ".plist")
let info = NSDictionary.init(contentsOfFile: infoPath!)
// Read all the info from here
```

Maybe @mdiep  has an idea of why?

**Comment by fuzzybinary** [comment]
Good to know about the resources folder. For my own framework for now I've removed that folder from the final framework build and that fixed the build error.

**Comment by blender** [comment]
Thanks @fuzzybinary, would you consider closing the issue please?

**Comment by blender** [comment]
@fuzzybinary  ping

**Comment by fuzzybinary** [comment]
Sure, wasn't sure if you wanted to keep it open for tracking purposes. I'll close it out (sorry for the delay)
