### ISSUE TITLE
Prevent the generation of the Frameworks subfolder

### ISSUE THREAD

**Issue by funkyboy** [Carthage/Carthage#2357]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: 0.28.0
* `xcodebuild -version`: `Xcode 9.2 Build version 9C40b`
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? I tried
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 

**Cartfile**
```
github "facebook/SocketRocket" "28035e1a98a427853e4038ff1b70479fa8374cfa"
github "rvi/msgpack-objective-C" "ad0a627becfd27ca45dfa6684b3fc79f058f5ce9"
github "ably-forks/KSCrash" "1.15.8-ably-1"
```

**Carthage Output**
```
*** Fetching ably-ios
*** Fetching msgpack-objective-C
*** Fetching SocketRocket
*** Checking out msgpack-objective-C at "9e204dd845ca4d3de61d1b87ca21fae17e81476f"
*** Checking out KSCrash at "1.15.8-ably-1"
*** Checking out SocketRocket at "28035e1a98a427853e4038ff1b70479fa8374cfa"
*** Downloading ably-ios.framework binary at "v1.0.11"
*** xcodebuild output can be found in /var/folders/r3/yyh_7qtd7rzb7fdpdtvkcxmh0000gn/T/carthage-xcodebuild.qbHPra.log
*** Building scheme "KSCrash" in Mac.xcworkspace
*** Building scheme "KSCrash-TVOS" in TVOS.xcworkspace
*** Building scheme "KSCrash" in Mac.xcworkspace
*** Building scheme "KSCrash-iOS" in iOS.xcworkspace
*** Building scheme "msgpack" in msgpack.xcodeproj
*** Building scheme "SocketRocket-macOS" in SocketRocket.xcodeproj
*** Building scheme "SocketRocket-tvOS" in SocketRocket.xcodeproj
*** Building scheme "SocketRocket-iOS-Dynamic" in SocketRocket.xcodeproj
```

**Actual outcome**
Carthage did generate these folders.
<img width="411" alt="36543402-b829dcbe-17f4-11e8-90aa-4faa3dd3356b" src="https://user-images.githubusercontent.com/348355/36610072-4134dbdc-18cf-11e8-8849-f4b7f4aec3d7.png">
When dragging `Ably.framework` into the Xcode project it's easy to NOT notice that in contains a `Frameworks` folder. For running or debugging the app it's fine, but when you submit the app to the store it will not validate and throw errors like
```
iTunes Store Operation Failed
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.facebook.socketrocket.ios' under the iOS application 'myApp.app'.

iTunes Store Operation Failed
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.remyvirin.msgpack' under the iOS application 'myApp.app'.

iTunes Store Operation Failed
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.stenerud.KSCrash' under the iOS application 'myApp.app'.
```

**Expected outcome**
Carthage does not generate the subfolder `Frameworks` within `Ably.framework`.
Deleting such `Frameworks` folder is the only "solution" I found to make the app pass the App Store validation.

Is there a way to prevent Carthage from placing frameworks into the `Frameworks` subfolder?

Related issue here: https://github.com/ably/ably-ios/issues/698

**Comment by mdiep** [comment]
This is really a configuration issue on the project you're building. It's possible that we could explicitly work around it, but we try to avoid doing that in general. We don't want to protect project owners from their mistakes.

**Comment by blender** [comment]
I was about to just write the same conclusion. I will look into this a bit more but imho explicit an work around a bad configuration is out of question.

**Comment by funkyboy** [comment]
So I should look for a way to tell my project "hey, don't embed frameworks required by `Ably.framework` into the `Frameworks` subfolder". Correct?

**Comment by mdiep** [comment]
It's a problem with the configuration of `Ably.framework`. It's copying its frameworks into a subfolder but it shouldn't.

**Comment by funkyboy** [comment]
@mdiep Thanks for your help. I had a "copy-frameworks" phase in the Xcode project https://github.com/ably/ably-ios/pull/700/files.
Fixed now.
