### ISSUE TITLE
Carthage update fails for private git repo checkout with Carthage 0.28.0

### ISSUE THREAD

**Issue by paulfreeman** [Carthage/Carthage#2359]
* carthage install method: homebrew 
* `which carthage`: OSX
* `carthage version`: 0.28.0
* `xcodebuild -version`: 9.3 build 9Q107o
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? Don't know

git version : 2.15.1 (Apple Git-101)
  
 I just upgraded to Carthage. 0.28.0 and I'm seeing this error for the first time. I have all my auth set up for normal git access via .ssh and its working fine.

cartfile references private GitHub repo, contents of cartfile follows 

```
github "paulfreeman/cloudpickerframework" ~> 0.6.10
# ObjectiveDropboxOfficial
#github "http://github.com/dropbox/dropbox-sdk-obj-c" ~> 3.2.0
#github "parse-community/Parse-SDK-iOS-OSX"
```

command
`$ carthage update --platform iOS`

unexpected output 
```
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/paulfreeman/cloudpickerframework.git /Users/paul/Library/Caches/org.carthage.CarthageKit/dependencies/cloudpickerframework) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
I have run the following  

`GIT_TERMINAL_PROMPT=0 echo "url=https://github.com"|git credential fill`

and ensured that my correct credentials have been filled prior to running the Carthage update. (I'm on Mac High Sierra, XCode 9.3b2)

Output format of credential fill are, with mock credentials substituted 

```
Username for 'https://github.com': bobthebuilder
Password for 'https://bobthebuilder@github.com': 
protocol=https
host=github.com
username=bobthebuilder
password=bobspasssword
```

**Comment by mdiep** [comment]
What happens if you run this command separately?

```
/usr/bin/env git clone --bare --quiet https://github.com/paulfreeman/cloudpickerframework.git {{some temporary path}}
```

It doesn't look like this error is coming from Carthage. It looks like it's coming from Git directly when Carthage tries to clone it, which is strange. 🤔 

(Carthage only loads these credentials to interact with the GitHub API. That doesn't appear to be the source of the error here.)

**Comment by paulfreeman** [comment]
That worked fine. 

I had downgraded to Carthage 0.26.0 earlier to see if it made a difference, it did not seem to help.  I also switched to Xcode 9.2 for builds, neither of which should be material to this in any case. 

But running this just now everything is perfect. If I run Carthage update --platform iOS again on the same cartfile  it is working correctly.

I upgraded Carthage back to 0.28.0 and its working fine

Perhaps this was a service issue of some kind with Github as my credentials were set correctly prior to the issues occurring?

**Comment by laiso** [comment]
I think the error could occur to have a typo in a repository name on Cartfile. for example:

```
> github "paulfreeman/this-is-typo"

$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Cloning this-is-typo
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/paulfreeman/this-is-typo.git /Users/kstg/Library/Caches/org.carthage.CarthageKit/dependencies/this-is-typo) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

In this case, just run git-clone so I can look the below:

```
git clone --bare --quiet https://github.com/paulfreeman/this-is-typo.git
Username for 'https://github.com':
```

**Comment by yasirmturk** [comment]
is there any investigation on what causes this issue? my creds are stored properly in the keychain and there is no typo... carthage update generates this error for random repos and all of them are on custom git server but public repos
