### ISSUE TITLE
Framework using Carthage is not detected in interface builder inspector.

### ISSUE THREAD

**Issue by fbarraganef** [Carthage/Carthage#2365]
I'm trying to use a framework called M1Checkbox with Carthage and when I try to use it in the interface builder for add it to a view the class that belongs to the framework doesn't appear but I add the module in a class I can use the framework a create the control programatic. I would like to the know the reason of this behavior. 
 
**Carthage framework.
M1Checkbox

in Carthfile 
github "Marxon13/M13Checkbox"

**Actual outcome**
I can't add to a view a class in the interface builder that belongs to the framework added by Carthage. 

![screen shot 2018-03-06 at 3 49 09 pm](https://user-images.githubusercontent.com/28632162/37060449-f5d90a20-2155-11e8-8c1e-2600bff9fb3b.png)

**Expected outcome**
I should be able to add to the custom view a class that belongs to the framework.

Thanks, I will appreciate your help. 
Francisco.

**Comment by blender** [comment]
If you `import` the framework are you able to use the public classes?

**Comment by fbarraganef** [comment]
@blender yes, If I import the framework in any ViewController I don't have any problem. It only happen with the interface builder. 

![screen shot 2018-03-06 at 5 30 42 pm](https://user-images.githubusercontent.com/28632162/37064832-2002c26a-2164-11e8-9f03-a792fe0d2b94.png)

**Comment by blender** [comment]
And @fbarraganef if you run you have no issue?

I don't use IB so I'm just making use that you're linking the library correctly. If you can see the classes when you import then I think that most probably this is an IB problem.

Maybe someone else might know more.

**Comment by mdiep** [comment]
This isn't really a Carthage issue; it's an Xcode issue.
