### ISSUE TITLE
support Debug configurations like cocoapods?

### ISSUE THREAD

**Issue by DotzuX** [Carthage/Carthage#2370]
pod 'xxx', :configurations => ['Debug'] #cocoapods

Can Carthage support like this?
 I just want to import the framework only in DEBUG, not RELEASE.

**Comment by mdiep** [comment]
`carthage` has a `--configuration` flag that lets you build in Debug mode. `carthage bootstrap --configuration Debug`.

**Comment by blender** [comment]
You can optionally link the framework in your link phase and surround use with `#if DEBUG`

**Comment by DotzuX** [comment]
Thanks
