### ISSUE TITLE
Failure to output “no shared framework schemes” error in some instances

### ISSUE THREAD

**Issue by jdhealy** [Carthage/Carthage#2373]
* carthage install method: [ ] .pkg, [ ] homebrew, [✔️] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`:  #2372 → `HEAD-15acb4e`, `HEAD-e0657f7`

**Cartfile**
```
github "bignerdranch/BNRDynamicTypeManager" "be6f1c0c975c80cebffdb3cbf4023f0e29f3b874"
```

**Carthage Output** — fails expectation to see “no shared framework schemes” error output…
```shell
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Cloning BNRDynamicTypeManager
*** Checking out BNRDynamicTypeManager at "be6f1c0c975c80cebffdb3cbf4023f0e29f3b874"
```

**Expected outcome** — seen with [v0.28.0](https://github.com/Carthage/Carthage/releases/tag/0.28.0)
```shell
*** Skipped building BNRDynamicTypeManager due to the error:
Dependency "BNRDynamicTypeManager" has no shared framework schemes
If you believe this to be an error, please file an issue with the maintainers at https://github.com/bignerdranch/BNRDynamicTypeManager/issues/new
```

_Likely, related to #2344._

**Comment by blender** [comment]
@jdhealy can we close this?
