### ISSUE TITLE
Carthage doesn't support SSH authentication with a custom username in GHE URLs

### ISSUE THREAD

**Issue by pettermahlen** [Carthage/Carthage#2379]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.28.0
* `xcodebuild -version`: Xcode 9.2, Build version 9C40b
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "ssh://git@some_host/some_owner/some_repo.git" "master"

# Testing tools
github "Quick/Nimble" ~> 7.0
github "Quick/Quick" ~> 1.2
```

**Carthage Output**
```
*** Cloning some_repo
*** Fetching Quick
A shell task (/usr/bin/env git clone --bare --quiet ssh://some_host/some_owner/some_repo.git /Users/petter/Library/Caches/org.carthage.CarthageKit/dependencies/some_repo) failed with exit code 128:
petter@some_host: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Actual outcome**
Carthage did not use the user name specified in the URL.

**Expected outcome**
Carthage should use that username (`git`), meaning that somewhere around https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/GitHub.swift#L50-L55, it should also extract the user from the URL and if specified, use that in the URL later used for the clone command.

**Comment by blender** [comment]
can you try with

`git "ssh:..."` instead of Github ? I'm not sure specifying Github & ssh scheme is supposed.

**Comment by pettermahlen** [comment]
I was just going to post that `git "git@some_host:some_owner/some_repo.git"` is a workaround. So no scheme, and a `:` instead of a `/` between the host name and owner name. Haven't tried with a scheme as well.

**Comment by blender** [comment]
is there a particular reason you want to specify `github` & ssh scheme? Would you loose any benefit from that?

I'm asking because I don't see the combination supported here https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md

**Comment by pettermahlen** [comment]
I don't think it makes any difference for us which approach we use. When you copy/paste the SSH clone URL from GHE, you in fact get the second version, but that didn't work with `github`, so I tried changing it around a bit - finally I ended up with something that worked from the shell if I only added the `git@` user name to it. 

I guess the most streamlined approach for GHE users would be to support `github "git@some_host:some_owner/some_repo.git"`.

Also, AFAICT, the document doesn't seem to mention that you can specify a username as above using  `git`. At least, I didn't find that information, though I mostly looked at the different examples of how to specify git and github dependencies before I started digging deeper into how Carthage uses the URLs. So even if it's not worth the effort to support user names in the more HTTP-like URL I mentioned in the report, it would be great to add the workaround URL to the documentation, if possible.

**Comment by blender** [comment]
I totally agree that the documentation needs some enhancement.

**Comment by ikesyo** [comment]
`github` origin is for specifying by`ownee/repo` form or using binary download feature through its web API, so using `git` protocol for `github` origin does not make sense.

**Comment by blender** [comment]
@ikesyo are you saying that the combination `github "some_repo_on_github.git"` does not make sense or that `git "some_repo_on_github.git"` does not make sense?

**Comment by ikesyo** [comment]
@blender The former.

**Comment by blender** [comment]
I agree, however this is best specified in the documentation.

Potentially this is also something Carthage could normalize when writing the resolved file.

**Comment by ikesyo** [comment]
> however this is best specified in the documentation.

I can't find it. Where is that?

**Comment by blender** [comment]
It's not there, as intended.

What I mean is that the purpose of `github` could be better explained by just adding a tech sentence from your previous comment :)
