### ISSUE TITLE
Via Mint <= 0.7.1 or Swift Package Manager 4.X.X without `-Xswiftc` flag, v0.29.0 can no longer be built

### ISSUE THREAD

**Issue by LinusU** [Carthage/Carthage#2381]
After this commit (fa290b083b9513ffd5790cf98654f21b79ddc1c5) that dropped support for macOS 10.10 it's no longer possible to build Carthage using [SwiftPM](https://github.com/apple/swift-package-manager).

This breaks usage via [Mint](https://github.com/yonaskolb/Mint).

I'm not sure if this has been explicitly supported, but since the `Package.swift` is committed I figured it should work.

Unfortunately, I haven't found a way to set the deployment target from `Package.swift`. There was this issue, https://bugs.swift.org/browse/SR-2535, but the fix was to allow that as a command line flag. Maybe this could be fixed with some well placed `@available` 🤔 

-----

Full output:

```sh
$ swift build   
Compile Swift Module 'CarthageKit' (30 sources)
/Users/linus/coding/Carthage/Source/CarthageKit/Dependency.swift:133:25: error: 'init(fileURLWithPath:isDirectory:relativeTo:)' is only available on OS X 10.11 or newer
                                                let absoluteURL = URL(fileURLWithPath: url.relativePath, isDirectory: false, relativeTo: base).standardizedFileURL
                                                                  ^
/Users/linus/coding/Carthage/Source/CarthageKit/Dependency.swift:133:25: note: add 'if #available' version check
                                                let absoluteURL = URL(fileURLWithPath: url.relativePath, isDirectory: false, relativeTo: base).standardizedFileURL
                                                                  ^
/Users/linus/coding/Carthage/Source/CarthageKit/Dependency.swift:115:21: note: add @available attribute to enclosing static method
        public static func from(_ scanner: Scanner, base: URL? = nil) -> Result<Dependency, ScannableError> {
                           ^
/Users/linus/coding/Carthage/Source/CarthageKit/Dependency.swift:109:1: note: add @available attribute to enclosing extension
extension Dependency: Scannable {
^
/Users/linus/coding/Carthage/Source/CarthageKit/Dependency.swift:133:25: error: 'init(fileURLWithPath:isDirectory:relativeTo:)' is only available on OS X 10.11 or newer
                                                let absoluteURL = URL(fileURLWithPath: url.relativePath, isDirectory: false, relativeTo: base).standardizedFileURL
                                                                  ^
/Users/linus/coding/Carthage/Source/CarthageKit/Dependency.swift:133:25: note: add 'if #available' version check
                                                let absoluteURL = URL(fileURLWithPath: url.relativePath, isDirectory: false, relativeTo: base).standardizedFileURL
                                                                  ^
/Users/linus/coding/Carthage/Source/CarthageKit/Dependency.swift:115:21: note: add @available attribute to enclosing static method
        public static func from(_ scanner: Scanner, base: URL? = nil) -> Result<Dependency, ScannableError> {
                           ^
/Users/linus/coding/Carthage/Source/CarthageKit/Dependency.swift:109:1: note: add @available attribute to enclosing extension
extension Dependency: Scannable {
^
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/linus/coding/Carthage/.build/debug.yaml main
```

**Comment by dmiluski** [comment]
Hi @LinusU , this was me who changed this per https://github.com/Carthage/Carthage/pull/2360 , which was upgraded to support easier file path construction. I ran into some issues manually supporting a backwards compatible path constructor if you had any alternative recommendations?

**Comment by blender** [comment]
Hi, there are test making sure that building with SwiftPM and they are all passing.

This is how the build is perfomed: https://github.com/Carthage/Carthage/blob/master/Makefile#L99

**Comment by jdhealy** [comment]
Hey, thanks for writing this up; the Mint aspect is interesting, appreciate you opening an issue there.

You seem aware of the `-Xswiftc` flag, I'm just going to retitle this to center it on that flag and Mint.

**Comment by LinusU** [comment]
> I ran into some issues manually supporting a backwards compatible path constructor if you had any alternative recommendations?

The previous workaround seems to compile for me, but I guess the problem manifests when you run it on 10.10?

> This is how the build is perfomed

Ah, the flag for setting the target is included, that explains that 😄 

> I'm just going to retitle this to center it on that flag and Mint.

Thank you 👍 

I had hoped that there would have been a field for this in the `Package.swift`, but alas, there is not. As I see there are a few ways forward:

1) Submit a [Swift Evolution Proposal](https://apple.github.io/swift-evolution/) outlining a new field in the `Package.swift` to specify deployment target. This would, of course, be amazing, but probably a lot of work 😄 

2) Maintain macOS 10.10 compatibility, but it seems a bit silly to do that just because there is no easy way to retarget SwiftPM.

3) Use `#available` and `fatalError` to fail at runtime. We could still maintain the target set to 10.11 in the Xcode project and build for SwiftPM with the `-Xswiftc` flag. But if someone manually builds without that flag, it would still work.

4) Just close this issue as "not a problem in Carthage" which I think it totally fair.

It's super great to see such a fast response, thanks!

**Comment by blender** [comment]
1) would be great and it would be interesting to see if something similar has been proposed before.

2) A conscious decision was made to modernize the development platform and I don't think backtracking is a good  solution. Others may disagree @mdiep

3) I think this is antithetical to the concept of minimum deployment target.

I feel like this is not a Carthage problem. Maybe there is a way to addresses it in Mint?

**Comment by mdiep** [comment]
This definitely seems like a problem with Mint and/or SwiftPM. It's unfortunate that it broke, but maintaining 10.10 compatibility indefinitely isn't really a solution here. 😞

**Comment by LinusU** [comment]
I agree with all of you, I'll close this for now and will continue the discussion in the Mint issue: https://github.com/yonaskolb/Mint/issues/58

Thanks for all the help!
