### ISSUE TITLE
Cartfile.resolved contains local absolute path when using binary

### ISSUE THREAD

**Issue by gabrielmaldi** [Carthage/Carthage#2382]
* carthage install method: homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.29.0
* `xcodebuild -version`: Xcode 7.3.1 Build version 7D1014
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
binary "facebook-ios-sdk.json" == 4.14.0
```

**facebook-ios-sdk.json**
```
{
  "4.14.0": "https://origincache.facebook.com/developers/resources/?id=FacebookSDKs-iOS-4.14.0.zip"
}
```

**Carthage Output**
```
Downloading binary-only framework facebook-ios-sdk at "file:///Users/username/some/path/facebook-ios-sdk.json"
```

**Actual outcome**
Carthage downloads Facebook SDK fine, but `Cartfile.resolved` contains:
```
binary "file:///Users/username/some/path/facebook-ios-sdk.json" "4.14.0"
```

**Expected outcome**
The path inside `Cartfile.resolved` should be relative; otherwise, each developer who runs `carthage update` will modify the file with his local path.

**Comment by blender** [comment]
relates to: #2383

**Comment by blender** [comment]
#2383 was merge so I'm going to close this issue. Please try with `brew install carthage --HEAD`
