### ISSUE TITLE
[Question] Prebuilt binaries without using Github

### ISSUE THREAD

**Issue by binloan** [Carthage/Carthage#2384]
* carthage install method: [x] .pkg, [ ] homebrew, [ ] source
* `carthage version`: 0.29.0
* `xcodebuild -version`: 9.2 - 9C40b
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
No
```

**Carthage Output**
```
No
```

I am a bit lost in the documentation of Carthage. I try to distribute prebuilt binaries, but with our own git not with GitHub. The section
```
Archive prebuilt frameworks into one zip file
Carthage can automatically use prebuilt frameworks, instead of building from scratch, if they are attached to a GitHub Release on your project’s repository or via a binary project definition file.
```
mentions a `binary project definition file`, but it is not further specified how and where I can define that. On top of that it is also not specified how I can tell Carthage to use the prebuilt framework if the system is not GitHub. May anyone clarify this for me? Maybe someone also wants to improve documentation in this section.

Thanks!

**Comment by ikesyo** [comment]
See here: https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-only-frameworks

**Comment by binloan** [comment]
@ikesyo Thank you. A direct link inside the README would be helpful.

**Comment by adesentenac** [comment]
Hi @ikesyo I'm not sure I understand how we can use that and fallback to the sources if the binary version is incompatible, like it seems to work with Github Release.
Is that feasible?

**Comment by ikesyo** [comment]
@adesentenac That may be #722 or #1452.
