### ISSUE TITLE
[Proposal] Podspec Specification

### ISSUE THREAD

**Issue by uny** [Carthage/Carthage#2387]
Carthage is a good dependency manager, but it seems to be difficult for some libraries to support carthage (ex. [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk), [leveldb](https://github.com/google/leveldb) ).
[Binary support](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-only-frameworks) is a good option for these libraries, but I have one more idea.
I wonder if it is acceptable, so I want to hear your opinions.
If it is not bad, I will try to make a pull request.

1. First, start with below Cartfile:
```
pod "FirebaseFirestore" == 0.10.4
```
2. `carthage update`, then carthage makes a dummy project for [CocoaPods](https://cocoapods.org) and Podfile.
```
Carthage/Checkouts
┣ [other projects with shared scheme]
┣ CocoaPods.xcodeproj
┗ Podfile
```
```ruby
# Podfile
platform :ios, '8.0'

target 'CocoaPods' do
  use_frameworks!
  pod 'FirebaseFirestore', '0.10.4'
end
```
3. Next, carthage executes `pod install` in the `Carthage/Checkouts`. When the user does not install CocoaPods, carthage shows an error.
4. The generated Pods.xcodeproj has the targets to build. Carthage runs xcodebuild (as the same as for shared scheme projects) for these targets.
```bash
$ /usr/bin/xcrun xcodebuild -project /path/to/Carthage/Checkouts/CocoaPods/Pods/Pods.xcodeproj/ -scheme BoringSSL -configuration Release -derivedDataPath ~/Libr
ary/Caches/org.carthage.CarthageKit/DerivedData/XXX/BoringSSL/XXX ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath
 /var/folders/xxx/XXX/T/BoringSSL SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO
$ ...
$ /usr/bin/xcrun xcodebuild -project /path/to/Carthage/Checkouts/CocoaPods/Pods/Pods.xcodeproj/ -scheme FirebaseFirestore -configuration Release -derivedDataPath ~/Libr
ary/Caches/org.carthage.CarthageKit/DerivedData/XXX/FirebaseFirestore/XXX ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath
 /var/folders/xxx/XXX/T/FirebaseFirestore SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO
```

**Comment by mdiep** [comment]
Thanks for opening an issue.

We don't want to use CocoaPods from Carthage. That would add additional complexity to Carthage, which we're not willing to accept. It's not difficult for these projects to add Carthage support if they choose to do so.
