### ISSUE TITLE
The file “GPUImage.framework” couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by vicflight** [Carthage/Carthage#2389]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`:/usr/local/bin/carthage
* `carthage version`: 0.29.0
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b
* Are you using `--no-build`?  NO
* Are you using `--no-use-binaries`?  NO
* Are you using `--use-submodules`?  NO
* Are you using `--cache-builds`?  NO
* Are you using `--new-resolver`?  NO

**Cartfile**
```
github "BradLarson/GPUImage"
```

**Carthage Output**
```
*** Fetching GPUImage
*** Checking out GPUImage at "0.1.7"
*** xcodebuild output can be found in /var/folders/hh/p6lz6c4129zg6fl5x4q9rz_40000gn/T/carthage-xcodebuild.VQ120N.log
*** Building scheme "GPUImage" in GPUImageMac.xcodeproj
*** Building scheme "GPUImageFramework" in GPUImage.xcodeproj
Failed to write to /Users/leaf/Projects/VLive/Carthage/Build/iOS/GPUImage.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “GPUImage.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/leaf/Projects/VLive/Carthage/Checkouts/GPUImage/build/ArchiveIntermediates/GPUImageFramework/BuildProductsPath/Release-iphoneos/GPUImage.framework, NSFilePath=/Users/leaf/Projects/VLive/Carthage/Checkouts/GPUImage/build/ArchiveIntermediates/GPUImageFramework/BuildProductsPath/Release-iphoneos/GPUImage.framework, NSUnderlyingError=0x7fbbeaaada90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Actual outcome**
Carthage  did not  generated GPUImage.framework in the file /Carthage/Build/iOS
![image](https://user-images.githubusercontent.com/13941092/37836079-94fcdd9a-2eec-11e8-97cb-44051aad4a13.png)

**Comment by blender** [comment]
Possible related to: #2277

**Comment by vicflight** [comment]
@blender i only use the carthage update.  Only the GPUImage failed

**Comment by blender** [comment]
@vicflight  why did you close? Did you find the problem?

**Comment by vicflight** [comment]
@blender I found the answer in #2220  and fixed the issue by removing the SYMROOT build setting.

**Comment by blender** [comment]
@vicflight Awesome. Good use of the issues archive.

**Comment by vicflight** [comment]
@blender Thank you for your help.
