### ISSUE TITLE
Carthage doesn't install Resources from a binary-only zip

### ISSUE THREAD

**Issue by paulb777** [Carthage/Carthage#2401]
* carthage install method: [ ] .pkg, [X ] homebrew, [ ] source
* `which carthage`: /Users/paulbeusterien/homebrew/bin/carthage
* `carthage version`: 0.29.0
* `xcodebuild -version`: Xcode 9.2
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
binary "https://dl.google.com/dl/firebase/ios/carthage-resources/FirebaseFirestoreBinary.json"
```

**Carthage Output**
```
*** Downloading binary-only framework FirebaseFirestoreBinary at "https://dl.google.com/dl/firebase/ios/carthage-resources/FirebaseFirestoreBinary.json"
*** Downloading binary-only framework FirebaseFirestoreBinary at "https://dl.google.com/dl/firebase/ios/carthage-resources/FirebaseFirestoreBinary.json"
*** xcodebuild output can be found in /var/folders/32/8htqsq1s2xjc00tybsrc453000bzqz/T/carthage-xcodebuild.aXrxCx.log
```

**Actual outcome**
Carthage did not install the Resources directory from [zip](https://dl.google.com/dl/firebase/ios/carthage-resources/4.11.0/Firestore-79ed4b6f1926483e.zip).

**Expected outcome**
Carthage should install the Resources. You can see them if you download the zip url in a browser.

Is there another way to structure the zip so the Resources would get installed?

**Comment by blender** [comment]
Your resources directory is a top level. It's not part of any framework. If you want it copied it should be part of the framework bundle that uses it.

Carthage works with frameworks, not arbitrary resources.

**Comment by paulb777** [comment]
Thanks @blender.

**Comment by paulb777** [comment]
How exactly should the resources be part of the framework bundle? When I put the Resources in gRPC.framework, I get an installer error:

$ cat Cartfile
binary "https://dl.google.com/dl/firebase/ios/carthage-resources/embedded-resources.json"
$ carthage update
*** Downloading binary-only framework embedded-resources at "https://dl.google.com/dl/firebase/ios/carthage-resources/embedded-resources.json"
*** Downloading binary-only framework embedded-resources at "https://dl.google.com/dl/firebase/ios/carthage-resources/embedded-resources.json"
*** xcodebuild output can be found in /var/folders/32/8htqsq1s2xjc00tybsrc453000bzqz/T/carthage-xcodebuild.0deaGl.log
Failed to read file or folder at /Users/paulbeusterien/firebase/carthage/quickstart-ios/storage/Carthage/Build/iOS/gRPC.framework

The resources do get copied though.

**Comment by blender** [comment]
Try at top level inside the .framework directory without the `Resources` subdirectory

Check https://github.com/mattt/FormatterKit for reference
