### ISSUE TITLE
More swift versions in github release?

### ISSUE THREAD

**Issue by olejnjak** [Carthage/Carthage#2403]
I was wondering whether there is a discussion or idea if Carthage could support more swift versions for prebuilt frameworks in github releases? 

I think it is a shame that now it doesn't support that, does it? I think that some projects can legitimately target older dependency version and it could be a shame if it just loses the capability of using prebuilt binary. What do you think?

Also it is a bit inconvenient that we have to create new library version every time new Swift/Xcode version is released.

**Comment by jafara** [comment]
that is the problem of using swift for command line tools. apple has not finished it yet. overall mistake

**Comment by mdiep** [comment]
> I was wondering whether there is a discussion or idea if Carthage could support more swift versions for prebuilt frameworks in github releases?

This is definitely possible. Pull requests are welcome. Carthage would need to detect what versions were available automatically and copy the relevant frameworks.


> Also it is a bit inconvenient that we have to create new library version every time new Swift/Xcode version is released.

You don't need to create a new version FWIW. You can delete the pre-built framework from the GitHub Release and attach a new version that targets a newer Swift.

> that is the problem of using swift for command line tools. apple has not finished it yet. overall mistake

This is completely unrelated to the fact that Carthage is written in Swift.

**Comment by olejnjak** [comment]
> This is definitely possible. Pull requests are welcome. Carthage would need to detect what versions were available automatically and copy the relevant frameworks.
Well I think that it should be discussed how this should work. Right now I can think of at least two ways

1. Have more archives in github release and choose correct version based on its name (something like `<dependency>.<swift_version>.framework.zip`)
2. use still a single archive and have folders inside

> You don't need to create a new version FWIW. You can delete the pre-built framework from the GitHub Release and attach a new version that targets a newer Swift.

I know but I think it's a shame to "break" some older projects which will then need to rebuild those dependencies.

**Comment by mdiep** [comment]
Carthage can already detect what version a framework was built with. We should use that to copy the correct frameworks automatically—no need to use filenames or folders. If the archive contains frameworks with the current version of swift, copy and use them; otherwise, build from scratch.

**Comment by blender** [comment]
@mdiep that is already the current behavior unless I'm missing something.

**Comment by mdiep** [comment]
@blender We currently only support one version within the archive.

Current: If *all* frameworks in the archive were built with the current swift, copy and use them

Proposed: If *any* frameworks in the archive were built with the current swift, copy and use them

**Comment by blender** [comment]
For `binary`dependencies this is ok. But what about github releases?

Should we not trigger a full source build? Carthage doesn't about Framework <-> Target Mapping

**Comment by mdiep** [comment]
I think if any frameworks built with the current of swift are present that we can assume copying just those libraries is sufficient. (That's basically what we do today as well.)

If not, then we should do a source build.
