### ISSUE TITLE
[Proposal] Add timestamp in front of any event print

### ISSUE THREAD

**Issue by PH9** [Carthage/Carthage#2408]
### Current

```
*** No Cartfile.resolved found, updating dependencies
*** Fetching first-dependency
*** Fetching second-dependency
*** Checking out first-dependency at "v2.3.3"
*** Checking out second-dependency at "v2.6.0"
```

### Goal

```
[13:05:01]: *** No Cartfile.resolved found, updating dependencies
[13:05:01]: *** Fetching first-dependency
[13:05:10]: *** Fetching second-dependency
[13:10:55]: *** Checking out first-dependency at "v2.3.3"
[13:15:55]: *** Checking out second-dependency at "v2.6.0"
```

### Motivation

I using fastlane a lot and it always show a clock. 
It kind of helpful when looking at log in my CI.

### Proposed solution

Add timestamp in formatted of `[%H:%M:%S]: ` or `[%Y-%m-%d %H:%M:%S]: ` in front of every print

**Comment by blender** [comment]
carthage update | awk -v date="$(date +"%Y-%m-%d %r")" '{ print "["date"]" " " $0 }'

**Comment by PH9** [comment]
It lost colored style log for that.

**Comment by blender** [comment]
I'm sure you can google for that

**Comment by blender** [comment]
@PH9 there is actually an option to keep the color:

`carthage update --color always | awk -v date="$(date +"%Y-%m-%d %r")" '{ print "["date"]" " " $0 }'`

**Comment by PH9** [comment]
It is not update the time.
It always show the time when command started.

**Comment by mdiep** [comment]
I think this would make sense as a command-line option to Carthage (off by default).

**Comment by blender** [comment]
`carthage update --color always | perl -pe 'print "[", scalar(localtime(time())), "]", " ";'`
