### ISSUE TITLE
Carthage binary swift version check too strict

### ISSUE THREAD

**Issue by danielphillips** [Carthage/Carthage#2411]
* carthage install method: [ ] .pkg, [ x ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.29.0

I have Xcode 9.3 installed with Swift 4.1.

I am bootstrapping my projects dependancies and the frameworks I depend on have been built using Xcode 9.2's default swift toolchain (Swift 4.0.3)
I am receiving the error message saying the swift version used for the binaries is incompatible with the local swift version (4.0.3 vs 4.1) so Carthage then wants to build the dependancies and discard the binaries -- so far so good. 

Then I've installed the Swift 4.0.3 toolchain downloaded from swift.org. I've set it up and I've set my environment to use it (`export TOOLCHAINS=org.swift.40320171205a`). Now running `swift --version` I can see I'm using Swift 4.0.3. Super.

Now I try bootstrapping again, but this time I'm still getting the same error message, except.... in this situation I would have expected Carthage to be more lenient about the difference in swift versions:

```
"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.0.3 (swift-4.0.3-RELEASE)."
```

4.0.3 vs 4.0.3!!!

The default toolchain shipped with Xcode seems to always have a funky name like `swiftlang-900.0.74.1 clang-900.0.39.2` and the one provided as a download from Swift.org usually has a cleaner name `swift-4.0.3-RELEASE`

Would it be a problem for Carthage's swift version check to use semantic versioning of Swift rather then (seemingly) comparing the two swift toolchain name/strings?

**Comment by mdiep** [comment]
> Would it be a problem for Carthage's swift version check to use semantic versioning of Swift rather then (seemingly) comparing the two swift toolchain name/strings?

Swift doesn't guarantee compatibility between any two versions of the `swift` compiler. While it'd usually be safe if the version number was the same, it's not guaranteed to be the case. So sadly using semantic versioning here is not an option.

**Comment by mdiep** [comment]
> but surely Swift 4.0.3 that shipped with Xcode 9.2 and Swift 4.0.3 RELEASE from swift.org are identical and should be interchangeable?

Sure, but Carthage would need to know that those two versions are identical. There's no way for Carthage to know that they're the same.

**Comment by danielphillips** [comment]
Agree. How would you feel about an optional argument instead. Something like:

```
carthage bootstrap --swift-version-check-lenient
```

I could put together a PR?

**Comment by pasin** [comment]
For the provider that provides pre-built binary, this issue is unavoidable, and we have been facing this issue several time in the past year. Is there a workaround or anything that the application can do to get pass this issue?
