### ISSUE TITLE
Carthage update memory leak

### ISSUE THREAD

**Issue by kiokumicu** [Carthage/Carthage#2416]
* carthage install method: [ ] .pkg, [ x ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.29.0
* `xcodebuild -version`: Xcode 9.2 Build version 9C40b
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "Swinject/Swinject"
github "Swinject/SwinjectStoryboard"
git "https://github.com/illabo/AKMaskField.git"
github "dennisweissmann/DeviceKit"
github "Alamofire/Alamofire"
github "peterprokop/SwiftOverlays"
github "marmelroy/Localize-Swift"
github "adamwaite/Validator"
github "luispadron/UICircularProgressRing"
github "SwiftyJSON/SwiftyJSON"
github "malcommac/Hydra"
github "malcommac/SwiftDate"
github "swiftsocket/SwiftSocket"
github "apple/swift-protobuf"
github "realm/realm-cocoa"
github "jonkykong/SideMenu" "master"
github "SwiftKickMobile/SwiftMessages"
github "DaveWoodCom/XCGLogger"
github "SnapKit/SnapKit"
git "https://bitbucket.org/atlassian/jiraconnect-apple" "2.1.0-alamofire3"
```

**Carthage Output**
```
carthage update --platform ios --no-use-binaries
*** Fetching XCGLogger
*** Fetching SideMenu
*** Fetching Validator
*** Fetching SwiftOverlays
*** Fetching Alamofire
*** Fetching SwiftSocket
*** Fetching SnapKit
*** Fetching SwiftMessages
*** Fetching SwiftyJSON
*** Fetching realm-cocoa
*** Fetching SwiftDate
*** Fetching Swinject
*** Fetching UICircularProgressRing
*** Fetching Localize-Swift
*** Fetching swift-protobuf
*** Fetching SwinjectStoryboard
*** Fetching Hydra
*** Fetching DeviceKit
*** Fetching AKMaskField
*** Fetching SDWebImage
```

**Actual outcome**
Memory leak on Fetching SDWebImage without complete.

**Expected outcome**
All packages succeed install.

SDWebImage using in jiraconnect-apple. Installed also with carthage.

**Comment by kiokumicu** [comment]
It's repeat not only for SDWebImage. Now I got leak on
```
carthage update --platform iOS --no-use-binaries
*** Fetching XCGLogger
*** Fetching SideMenu
```

**Comment by blender** [comment]
@kiokumicu Have you tried with `--new-resolver` ?

You're second Cartfile works just fine with that:

```
carthage update --platform iOS --new-resolver
*** Fetching SideMenu
*** Fetching XCGLogger
*** Checking out SideMenu at "175042e2381b48844677ce3e1ae145d70ce105fa"
*** Checking out XCGLogger at "6.0.2"
*** xcodebuild output can be found in /var/folders/pn/14183n6j2bz0s2_qlcqtg5_00000gn/T/carthage-xcodebuild.UQxHHz.log
*** Building scheme "SideMenu" in SideMenu.xcworkspace
*** Building scheme "ObjcExceptionBridging (iOS)" in XCGLogger.xcodeproj
*** Building scheme "XCGLogger (iOS)" in XCGLogger.xcodeproj
09:53:03 blender@deimos ~/Code/lab/issue
```

As a word of advice I believe it's bad practice not to pin your dependencies like I see you doing in your Cartfile.

If you can, always specify a tag with `~>`

**Comment by kiokumicu** [comment]
@blender yep, I tried it (--new-resolver), same result.
I guess problem in jiraconnect-apple, because when I remove it from Cartfile, works fine.

Thx for advising, I added ~>

**Comment by blender** [comment]
@kiokumicu can you try just with `jiraconnect-apple` ? Maybe it's an access problem

**Comment by kiokumicu** [comment]
I had to stop using the jiraconnect-apple, because no actual support of this package.
Maybe problem was in Swift version used in lib, it was 2.x.
Anyway, thx for answers.

**Comment by innoreq** [comment]
I'm observing (with latest carthage version) a massive consumption of memory on my iMac (32 GB Memory, carthage process using 172 GB), with a massive slowdown of the whole machine (i7), near to inoperability. The carthage processor usage goes up to 300%.
