### ISSUE TITLE
[CARTUP] New Carthage binary uploader to Google Cloud and S3  

### ISSUE THREAD

**Issue by mendesbarreto** [Carthage/Carthage#2418]
Hello my people,

I am here to announce one gem I have been working on for Carthage users, who does not use the GITHUB as a host for projects and unfortunately or maybe, they not have the  feature RELEASES to upload the prebuilts binaries.

The main propose of this gem is uploading the Carthage prebuilt frameworks to a cloud storage like google drive, onedrive, dropbox or google cloud.

Currently, Cartup exists because only github projects could upload and distribute prebuilt frameworks automatically, by using the great github tool called "RELEASES". But when you work using Bitbucket like I do (not by choice), the whole process must be done manually: you must upload the prebuilt framework on some sort of cloud storage, manage its version using a JSON file and upload it manually.

Today the Cartup has support to Amazon S3 and Google Cloud, the next steps is make it available to dropbox users.

To know more about follow the link: [https://github.com/mendesbarreto/cartup](https://github.com/mendesbarreto/cartup)

Any contributions will be welcomed.

**Comment by blender** [comment]
Well done. Always nice to see new tools to make life easier.
