### ISSUE TITLE
Carthage update works intermittently on same project

### ISSUE THREAD

**Issue by lucaseverini** [Carthage/Carthage#2423]
* carthage install method: [ ] .pkg, [x ] homebrew, [ ] source
* `which carthage`: macOS
* `carthage version`: 0.29.0
* `xcodebuild -version`: 9.2/9.3
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
github "coteditor/YAML.framework" "coteditor-mod"
github "sparkle-project/Sparkle" "ui-separation-and-xpc"
github "tonyarnold/Differ"
github "1024jp/WFColorCode"

**Carthage command**
carthage update --verbose --platform macOS

**Carthage Output**
*** Fetching WFColorCode
*** Fetching YAML.framework
*** Fetching Sparkle
(stays here forever...)

**Actual outcome**
Carthage did or did not complete the update

**Expected outcome**
Carthage should complete the update as it does 50% of the times...

**Comment by blender** [comment]
Did you try with `--new-resolver` ?

Also, you are not pinning your dependencies to a minimum version number. This is in general bad practice.

**Comment by lucaseverini** [comment]
I will try the new resolver with version numbers today and report here.
However I wonder why sometime it works quickly and perfectly and the next time just hangs...

**Comment by lucaseverini** [comment]
I didn't have the time to try the --new-resolver special version however, following the suggestion to set a minimum version number in the cartfile file, carthage now works flawlessly...
Thank you!

**Comment by lucaseverini** [comment]
I will close the issue after some more testing...

**Comment by lucaseverini** [comment]
The issue disappeared completely once the dependencies have been all pinned to a minimum version number, as suggested above by blender.
Thank you!
