### ISSUE TITLE
Static frameworks - Task failed with exit code 65

### ISSUE THREAD

**Issue by floschliep** [Carthage/Carthage#2425]
* carthage install method: homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.29.0
* `xcodebuild -version`: Xcode 9.3 Build version 9E145
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "onevcat/Kingfisher" ~> 4.0
github "aws/aws-sdk-ios"
github "facebook/facebook-ios-sdk"
github "airbnb/lottie-ios" "master"
github "tonyarnold/Differ"
github "uber/ios-snapshot-test-case"
```

**Carthage Output**
```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/florianschliep/Code/iOS/TryNotToLaugh/Carthage/Checkouts/Differ/Differ.xcodeproj -scheme Differ -configuration Release -derivedDataPath /Users/florianschliep/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/Differ/1.2.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/4t/fg591t79335363zm3b23z9qr0000gn/T/Differ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/florianschliep/Code/iOS/TryNotToLaugh/Carthage/Checkouts/Differ)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/4t/fg591t79335363zm3b23z9qr0000gn/T/carthage-xcodebuild.kxbc67.log
```

**Actual outcome**
Carthage fails to build the `Differ` dependency. I've attached the [log file](https://github.com/Carthage/Carthage/files/1934400/carthage-xcodebuild.kxbc67.log). When running the command (`xcrun codebuild …`) manually, the archive succeeds with [this log](https://github.com/Carthage/Carthage/files/1934401/manual.log).

**Expected outcome**
Carthage should build all dependencies.

I'm using a build script as described [here](https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md) to build static frameworks:
```
#!/bin/sh -e

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

echo "LD = $PWD/ld.py" >> $xcconfig
echo "DEBUG_INFORMATION_FORMAT = dwarf" >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"

carthage build --platform ios --no-use-binaries
```

**Comment by blender** [comment]
Building static frameworks is experimental at best. Also, as pointed out on the page of ld.py there is no need to override `LD` anymore.

**Comment by blender** [comment]
You can build Carthage from this branch  https://github.com/Carthage/Carthage/pull/2415  currently under development and try out static framework support.

**Comment by floschliep** [comment]
@blender Thanks for pointing that out, removing the `LD` overwrite seems to fix this.

I should also mention that everything worked fine before upgrading to Xcode 9.3, in case anyone else ever runs into this.

**Comment by floschliep** [comment]
Forget what I said about removing the `LD` overwrite, as I now discovered this apparently made Carthage build dynamic frameworks.

**Comment by floschliep** [comment]
@blender I'm now using the branch from #2415 but can't get Carthage to build static frameworks. I tried altering my build script to do the following:
```
echo "MACH_O_TYPE = staticlib" >> $xcconfig
```
but with this, Carthage is unable to find the scheme.

**Comment by Aranoledur** [comment]
What if you change Mach-O Type in xcode project at `Carthage/Checkouts/Differ` and then run `carthage build` again?

**Comment by floschliep** [comment]
That doesn't seem to make a difference, I still get the same error:
```
Dependency "Differ" has no shared framework schemes for any of the platforms: iOS
```
If I remove the `--platform ios` option, the error is:
```
Dependency "Differ" has no shared framework schemes
```

**Comment by Aranoledur** [comment]
Ok, will try to find what is wrong here. Thanks for pointing this out

**Comment by Aranoledur** [comment]
Well, I don't know how to debug custom script, but I was able to build static framework by using carthage from branch `Aranoledur:support-building-static-frameworks` and changing `Mach-O Type` in `Differ.xcodeproj`

**Comment by floschliep** [comment]
@Aranoledur That's what I did too. I deleted `Carthage/Checkouts/Differ`, ran `carthage bootstrap --platform ios --no-use-binaries --no-build` and then `carthage build Differ --platform ios --no-use-binaries --verbose`:

```
*** Skipped building Differ due to the error:
Dependency "Differ" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/tonyarnold/Differ/issues/new
```

**Comment by Aranoledur** [comment]
I use carthage built by XCode. Do you call `make install` or use XCode too? They have to be the same, but still

**Comment by floschliep** [comment]
@Aranoledur I used `make install`.

**Comment by Aranoledur** [comment]
commit sha `ce73a6e51362ee30a1c785e2bc26dc39c46f1677`?

**Comment by floschliep** [comment]
Yes.

**Comment by Aranoledur** [comment]
It's a kind of magic 😃 I have bumped carthage version, so pull, `make install` again and check what version do you use, it should be 0.29.1. Think it can help

**Comment by blender** [comment]
@floschliep on this repo, Carthage/Carthage you can check @Aranoledur  PR by:

```
$ git fetch origin pull/2415/head:pull/2415
$ git checkout pull/2415
$ make install
```

**Comment by floschliep** [comment]
@blender That did the trick, thanks! Also my custom script that modifies the config file works now:
```
#!/bin/sh -e

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

echo "MACH_O_TYPE = staticlib" >> $xcconfig
echo "DEBUG_INFORMATION_FORMAT = dwarf" >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"

carthage build --platform ios --no-use-binaries
```
With this you don't need to manually edit the Xcode projects anymore. 

Thanks @Aranoledur for your work 🙌

**Comment by blender** [comment]
@floschliep @Aranoledur awesome.
