### ISSUE TITLE
Bootstrapping binary frameworks with same .json filename overwrites single .version file

### ISSUE THREAD

**Issue by juraj-blahunka** [Carthage/Carthage#2430]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.29.0
* `xcodebuild -version`: Xcode 9.3 Build version 9E145
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes
* Are you using `--new-resolver`? no

**Cartfile**
```
binary "https://raw.githubusercontent.com/kayak/Specs/fabric-1.7.6/Carthage/Fabric.json" "1.7.6"
binary "https://raw.githubusercontent.com/kayak/Specs/fabric-1.7.6/Carthage/tvOS/Fabric.json" "1.7.6"
```

**Carthage Output**
Command: `carthage bootstrap --cache-builds`
```
*** No cache found for Fabric, building with all downstream dependencies
*** No cache found for Fabric, building with all downstream dependencies
*** Downloading binary-only framework Fabric at "https://raw.githubusercontent.com/kayak/Specs/fabric-1.7.6/Carthage/Fabric.json"
*** xcodebuild output can be found in /var/folders/48/sy74dwmd3_n9ym1dc0fh1fhhj37rwj/T/carthage-xcodebuild.fNTiBG.log
*** Downloading binary-only framework Fabric at "https://raw.githubusercontent.com/kayak/Specs/fabric-1.7.6/Carthage/tvOS/Fabric.json"
```

**Actual outcome**
Carthage overwrites the existing .version file and only shows a framework entry for one platform.

```
{
  "Mac" : [

  ],
  "watchOS" : [

  ],
  "tvOS" : [
    {
      "name" : "Fabric",
      "hash" : "e2ce2f8be8375a7089590fd9050a2144a06e85c0ecdfa0b6bb6364acffc94eb1"
    }
  ],
  "commitish" : "1.7.6",
  "iOS" : [

  ]
}
```

**Expected outcome**
Carthage realizes, that multiple `binary` entries in `Cartfile.resolved` represent the same framework and instead of overwriting the same .version file, it appends platform entries:
```
{
  "Mac" : [

  ],
  "watchOS" : [

  ],
  "tvOS" : [
    {
      "name" : "Fabric",
      "hash" : "e2ce2f8be8375a7089590fd9050a2144a06e85c0ecdfa0b6bb6364acffc94eb1"
    }
  ],
  "commitish" : "1.7.6",
  "iOS" : [
    {
      "name" : "Fabric",
      "hash" : "4e547cce245b78762f59767cba46856d15ee5825698aa3adbe4a60dc24529d17"
    }
  ]
}
```

Or each `binary` entry in `Cartfile.resolved` is translated to a unique .version file.

**Comment by blender** [comment]
https://raw.githubusercontent.com/kayak/Specs/fabric-1.7.6/Carthage/Fabric.json should really point to an archive with all platforms

**Comment by juraj-blahunka** [comment]
Sadly the archive, which Fabric publishes for cocoapods and contains all platforms https://kit-downloads.fabric.io/cocoapods/fabric/1.7.6/fabric.zip fails for carthage during bootstrap with
```
Failed to read file or folder at /private/var/folders/48/sy74dwmd3_n9ym1dc0fh1fhhj37rwj/T/carthage-archive.nYzx49/Fabric.framework: Error Domain=com.antitypical.Result Code=0 "could not determine platform neither from DTSDKName key in plist nor from the framework's executable" UserInfo={com.antitypical.Result.file=/tmp/carthage-20180320-87896-1fjmx7r/Source/CarthageKit/Project.swift, com.antitypical.Result.function=readFailed, com.antitypical.Result.line=1218, NSLocalizedDescription=could not determine platform neither from DTSDKName key in plist nor from the framework's executable}
```

**Comment by blender** [comment]
The cocoapods archive won't work because of it's structure. Carthage is trying to read the platform from the top level `Fabric.framework` and that's failing I believe.

Since there is no [Carthage support planned](https://github.com/firebase/firebase-ios-sdk/issues/9#issuecomment-381746071) , which could be easily solved just by packaging the zip according to carthage's requirements, I don't really see a way forward.

How would one determine that: 

https://raw.githubusercontent.com/kayak/Specs/fabric-1.7.6/Carthage/Fabric.json  and https://raw.githubusercontent.com/kayak/Specs/fabric-1.7.6/Carthage/tvOS/Fabric.json are the same framework?

**Comment by juraj-blahunka** [comment]
Either by inferring from the same json filename - which already happens during `bootstrap --cache-builds`, just that the generated `.Fabric.version` file gets overwritten.
Or  the generated .version file should encode the binary URL somehow, so that each binary entry has its own .version file.

**Comment by blender** [comment]
@juraj-blahunka this PR https://github.com/Carthage/Carthage/pull/2436 landed in master. This should allow you to use the archive Fabric provides out of the box

**Comment by juraj-blahunka** [comment]
Great job! Thanks so much.

**Comment by blender** [comment]
FYI you can also use `binary "relative/path/Fabric.JSON"`

**Comment by juraj-blahunka** [comment]
TIL. Thanks a lot @blender , you've been very helpful.
