### ISSUE TITLE
Help description for no-use-binaries

### ISSUE THREAD

**Issue by yhkaplan** [Carthage/Carthage#2433]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: `Carthage 0.29.0`

When looking at `carthage help update`, the description for `--no-use-binaries` says `use downloaded binaries when possible`, but I believe the correct explanation would be the opposite: 
**don't** use downloaded binaries when possible

Please confirm if my understanding is correct. If so, I'll make a PR 😉

**Comment by blender** [comment]
Correct

**Comment by mdiep** [comment]
It's specified that way because `--use-binaries` is the option, but it can be inverted to `--no-use-binaries`
