### ISSUE TITLE
Carthage stuck when using ssh (about known_hosts file)

### ISSUE THREAD

**Issue by leonlu** [Carthage/Carthage#2437]
**Actual outcome**
Nothing happened. Just got stuck when fetching in boostrap.
#
**Expected outcome**
Error or prompt

**Workaround**
Remove the lines that conflicts in ~/.ssh/known_hosts.

**How I find the cause**
I tried to clone the repo manually, then git showed me the message and then prompted me.

```
Warning: the ECDSA host key for 'git.xxx.com' differs from the key for the IP address '34.122.334.70'
Offending key for IP in /Users/leonlu/.ssh/known_hosts:2
Matching host key in /Users/leonlu/.ssh/known_hosts:3
Are you sure you want to continue connecting (yes/no)? 
```

**Comment by blender** [comment]
I think the most appropriate label for this issue would be `self-help`

**Comment by leonlu** [comment]
Is it possible to fail immediately here? Because I cannot know the status, if I encounter the problem. 
It only shows "Fetching XXXRepo"

**Comment by blender** [comment]
@leonlu How would you detect that ssh is stuck waiting for user input?

`yes | command>` does not seem a good idea to me.

**Comment by leonlu** [comment]
@blender I am not professional on command line tools, so is it possible at least print the prompt message out?

**Comment by blender** [comment]
I think it would be possible with a lot of effort. I don't think that the effort is worth is as this is a problem with you ssh configuration and now with carthage.

**Comment by leonlu** [comment]
@blender thanks for your reply. I suggest we can close this issue if any other main contributors agree that we can keep it as-is.
