### ISSUE TITLE
【iOS】Carthage build Framework Auto Disable Bitcode

### ISSUE THREAD

**Issue by josercc** [Carthage/Carthage#2440]
Our project uses some unknown third-party libraries and they don't support Bitcode. In order to be able to compile and package properly, we turned off BitCode functionality. Our latest code uses Carthage to host more than 20 libraries, but the default is to enable Bitcode. This causes the package to force the opening of Bitcode and will fail to pack. I now want to disable Bitcode before the Carthage Build Framework. What should I do?

**Comment by brennantaylor** [comment]
You can add an `xcconfig` file for carthage to add build properties when building the frameworks. I've had to do a similar thing:

`XCODE_XCCONFIG_FILE="somefile.xcconfig" carthage bootstrap --platform iOS`

`somefile.xcconfig` could contain or any other build config you need.
```
ENABLE_BITCODE[sdk=iphoneos*] = NO
```

**Comment by josercc** [comment]
Thanks

**Comment by blender** [comment]
Closing. Please feel free to reopen
