### ISSUE TITLE
The 'copy-frameworks' command fails when archiving an macOS application on an APFS volume

### ISSUE THREAD

**Issue by cmittendorf** [Carthage/Carthage#2444]
We use Carthage 0.29.0 installed via homebrew.

I recently updated our macOS project and added a `carthage copy-frameworks` build step for packaging our application. But Jenkins failed building the project with the following error message:

    Exit status: 65

In the details it showed:

    A shell task (/usr/bin/xcrun codesign --force --sign []…]/Result.framework) failed with exit code 1:
    […]/Contents/Frameworks/Result.framework: 
    bundle format is ambiguous (could be app or framework)

The optional code signing step was failing. The underlying problem was, that the frameworks have not been copied into the target directory and therefore `codesign` found nothing it could sign.

**Comment by blender** [comment]
Closing since #2445 got merged
