### ISSUE TITLE
Cache builds not working in continuous integration (Xcode bot)

### ISSUE THREAD

**Issue by rob-nash** [Carthage/Carthage#2451]
* carthage install method: homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.29.0
* `xcodebuild -version`: Xcode 9.3.1 Build version 9E501
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No

**Cartfile**
```
github "rob-nash/Dequable" == 1.3.0
github "rob-nash/Require" "7cfbd0d8a2dede0e01f6f0d8ab2c7acef1df112e" # same as JohnSundell/Require 2.0.1
github "rob-nash/Records" == 3.1.2
github "facebook/facebook-sdk-swift" == 0.3.0
```

**Script**
Run on Xcode bot as pre-integration trigger
```
#!/bin/sh
/usr/local/bin/carthage bootstrap --platform iOS --project-directory "${XCS_PRIMARY_REPO_DIR}" --cache-builds
```

**Carthage Output**
```
*** Checking out facebook-sdk-swift at "0.3.0"
*** Checking out facebook-ios-sdk at "sdk-version-4.33.0"
*** Checking out Records at "3.1.2"
*** Checking out Require at "7cfbd0d8a2dede0e01f6f0d8ab2c7acef1df112e"
*** Checking out Bolts-ObjC at "1.9.0"
*** Checking out Dequable at "1.3.0"
*** No cache found for Bolts-ObjC, building with all downstream dependencies
*** No cache found for Dequable, building with all downstream dependencies
*** No cache found for Records, building with all downstream dependencies
*** No cache found for Require, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/5d/pj7yq2sj33b0tk58dmcqj81h0000gp/T/carthage-xcodebuild.719lFz.log
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Dequable" in Dequable.xcodeproj
*** Building scheme "FBSDKCoreKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKLoginKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKPlacesKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKShareKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FacebookCore" in FacebookSwift.xcworkspace
*** Building scheme "FacebookLogin" in FacebookSwift.xcworkspace
*** Building scheme "FacebookShare" in FacebookSwift.xcworkspace
*** Building scheme "Records" in Records.xcodeproj
*** Building scheme "Require-iOS" in Require.xcodeproj
```

**Actual outcome**
Carthage did not find a cache of previous builds.

**Expected outcome**
Carthage would find a cache of previous builds.

Xcode bot config
Schedule: On commit
Clean once a day

**Comment by kenji21** [comment]
I this is a duplicate of #2400

**Comment by blender** [comment]
Hi, thanks for opening an issue.

If you delete the `Carthage/Build` folder in between builds, no cache will be found. I'm guessing tough you are not doing that.

can you try `update` instead of `bootstrap` and see if the results are different?

**Comment by rob-nash** [comment]
Hi @blender the CI setup I have configured, performs a clean build, once a day. Several integrations a day and the issue is consistent, so don't think the clean build is the cause. 

Thinking out loud here: the builds may be performed in a fresh directory, each time. Will see if I can verify that now.

**Comment by rob-nash** [comment]
Ah yes, the CI build folder is created dynamically, with each build

```
/Library/Developer/XcodeServer/Integrations/Caches/a3c682dd0c4d569a3bc84e58eab88a48/DerivedData/Build/Products/Debug-iphonesimulator/my.app
```

**Comment by rob-nash** [comment]
Doh, this is why I use an env var for proj dir

```
--project-directory "${XCS_PRIMARY_REPO_DIR}"
```

would be good to do some for cache option

```
--cache-builds PATH
```

Is that possible?

**Comment by blender** [comment]
Carthage checks for a `.version` file and also that your artifacts agree with the information in it.

The artifacts and the version file are expect to be in `Carthage/Build` which is not at a dynamic location. 

The cache is not supposed to be cross project or survive wipes.

If you need something like that maybe this can help you https://github.com/blender/Rome

**Comment by rob-nash** [comment]
Ah ok. Thank you @blender
