### ISSUE TITLE
Is that possible show progress when carthage show just Fetching ***

### ISSUE THREAD

**Issue by jerryzhoujw** [Carthage/Carthage#2457]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.29.0
* `xcodebuild -version`:  Xcode 9.3.1   Build version 9E501
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  no
* Are you using `--new-resolver`? no

**Cartfile**
```
the repo list is internal code in gitLab.

```

**Carthage Output**
```
*** No Cartfile.resolved found, updating dependencies
*** Fetching XXXX(XXXX is one of the internal repo)

```

**Expected outcome**

Is that possible show progress when carthage show just Fetching ***

When I run `carthage bootstrap` It' just show `Fetching ***`, and don't show any other status or progress.

Is there any `carthage log` or something I can digger to find what's going on?

**Comment by blender** [comment]
You can check with Activity monitor. Try ti clone your repo via git clone. If you are using ssh it's probably waiting for credentials to be entered.

**Comment by jerryzhoujw** [comment]
@blender   Thanks, find the root cause,  the current repo is using git clone "http://...",  the repo of XXXX in Cartfile  is using ssh format "git@gitlab...."  and I didn't setup with ssh-key on that website yet.

**Comment by blender** [comment]
No problem. I will close for now, please feel free to comment and I will reopen.

**Comment by jerryzhoujw** [comment]
Thanks, hopefully better message from carthage, I was assuming network slow at the begging since download repo are also need time and show same status.
