### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by Recouse** [Carthage/Carthage#2462]
I built static frameworks as told here https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md

I got "dyld: Library not loaded: @rpath/Realm.framework/Realm" error on app launching until I added `carthage copy-frameworks` in build phases.

**Comment by ikesyo** [comment]
Are you sure that you don't use Realm's prebuilt frameworks with `--no-use-binaries` flag?

**Comment by Recouse** [comment]
Yes, I'm sure.

**Comment by ikesyo** [comment]
Hmm then we are not sure about such errors about specific frameworks.

**Comment by blender** [comment]
This report conflict with #2497

**Comment by nRewik** [comment]
I have the same problem with [IGListKit](https://github.com/Instagram/IGListKit).

From [StaticFrameworks.md](https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md).

I build many static frameworks from my Cartfile. When I check with 

```
file Carthage/Build/iOS/Name.framework/Name
```

Only `IGListKit`, that is still dynamic framework, while the rest are static frameworks.

I already checked to always specify `--no-use-binaries` flag, for every step.

And to double check, `IGListKit` does not provide pre-built binary.
