### ISSUE TITLE
Сopying frameworks with New Build System (Preview) fails

### ISSUE THREAD

**Issue by ianbytchek** [Carthage/Carthage#2467]
While checking out how new xcode build system behaves with latest Xcode 9.3 I was pleased to learn that it builds my project for the first time… Carthage on another hand doesn't like it with `Environment variable not set: EXPANDED_CODE_SIGN_IDENTITY` error. Everything works as expected with the standard build system.

I noticed a few issues related to that, but `EXPANDED_CODE_SIGN_IDENTITY` seems to be new in that tandem? There also seems to be a [commit on that for watchOS](https://github.com/Carthage/Carthage/commit/7cf4297344c92dc2a54ede5d979d8f3428599d8b), not sure if it's related. Any advice or am I the only one with that? Demo project attached – [Carthage-2467.zip](https://github.com/Carthage/Carthage/files/2045702/Carthage-2467.zip).

**Comment by blender** [comment]
See https://github.com/Carthage/Carthage/issues/2472 

`EXPANDED_CODE_SIGN_IDENTITY='' carthage copy-frameworks`

**Comment by blender** [comment]
Closing, lets keep discussion there.

**Comment by jdhealy** [comment]
> with latest Xcode 9.3

Could you post the build version from `xcodebuild -version`?

**Comment by ianbytchek** [comment]
Moved on to 9.4 (9F1027a) – happens there too. 9.3 must have been 9E501.
