### ISSUE TITLE
How to Use With Nested Dependencies / Private Libraries

### ISSUE THREAD

**Issue by bladebunny** [Carthage/Carthage#2470]
**QUESTION**
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.29.0
* `xcodebuild -version`: 9.2
* Are you using `--no-build`? No 
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`?  No
* Are you using `--new-resolver`?  No

TL;DR - I can't figure out how to structure or build our app that uses both nested dependencies and custom build configs.

At work we're currently using Cocoapods and we'd really love to switch to Carthage to simplify our build process; get Cocoapods out of our projects and workspace; and hopefully improve our dev quality of life by reducing build times thru pre-built shared lib/framework re-use.

(I'm using the terms **_libs_** and **_frameworks_** interchangeably but I mostly mean dynamic frameworks below)

Our app looks like:
App ->
  -- 3rd Party dependencies:  RxSwift, SpriteKit, AFNetworking, etc..
  -- 1st Party dependencies: e.g. **Utils**, **Core**, **Network**, **U**I, **ExternalLibs** (wrapper for libs we can't use w/Cocoapods)

Example interdependencies:
**Network**:
-- AFNetworking
-- Swift
-- **Core**

**Core**:
-- **Utils**
-- RxSwift

...etc...basically some of our 1st party dependencies depend on one another as well as external public frameworks. And the app itself may depend either directly on one of our libs (say our **Utils** lib, as well as indirectly, e.g. like our **Networking** lib -- which may also link against **Utils**).

Our app is structured (for this experiment) as a project with its own Cartfile (which incls. our 1stParty libs as well as other public frameworks);  each 1st party dependency has its own project and Cartfile.  Sometimes, as indicated above, these may depend on other 1st party frameworks.) 

To build, I've been building each of our projects separately via Carthage per the instructions on the README.  I have not tried just linking everything up thru Cartfiles and then building the app as a whole reasoning that if it can't build one of the nested libs then there's no point spending too much time on the App target).

- As long as our projects don't depend on one another, ie they only depend on external libs, they build fine.
- I've tried several things to get the projects with interdependencies to build but nothing has worked.
I generally am able to build our 1st party libs that are self-sufficient just fine, but once I link them into another intermediate lib of ours, I get module not found, framework not found, or other errors.  (I have tried several approaches.)

I did follow the README instructions re: frameworks and test targets, but again, no joy.

Is this even possible?  I see pretty mixed opinions about feasibility of using Carthage for doing this with no real substance about exactly how to achieve it.

- We are not using git sub-modules but I would be willing to try that if it made a difference.  We don't use git for source control but I have added git to each lib project and refer to them via a file reference.  Not scalable as is but it does work to find dependencies.
- Challenge has been on building.  Not specific to Carthage as xcodebuild can't build them either.  
- The current errors building one of these nested libs are 'directory not found -F'.  
- I have verified the offending frameworks were built and are in the project local Carthage build dir.
- These libs are using an xconfig file mostly copied from the Cocopoads project -- and to which I also added an additional framework search path to search the build folder recursively -- but still not finding them.
- One last item: i switched to using the xcconfig files because we also use custom build configs for our release and test distro builds.
- So, nested dependencies, custom build configs (macros) and nested dependencies.

If someone has got this working, i would love to know how you structured it all.
I did also try adding the projects as subprojects to the app -- but no more success that way.

I've spent a day and half on this and pretty much assume at this point it won't work or I don't understand the underlying build process well enough to get it working.

Thanks and apologies in advance for the length.  

PS - Thanks so much to the Carthage team for this project and for offering an alternative to Cocoapods (which I also think is an awesome project but one which our team has outgrown).  This post is not meant as criticism in any way.  I understand what I'm trying to do may be off the beaten path or at least not that common -- I'm really just trying to guage, given the time I've already spent on this, whether it makes sense to continue and/or how far I am from a working solution.  There have been a few moments when it seemed I was close to getting it working -- but it always comes down to the nested dependencies either not building and/or not finding their dependencies.

Last word:  I'm pretty sure the framework not found issues are due to how the build process handles the file alias for configs  -- but I'm not quite sure what the solution is. Do we need to dynamically rename the frameworks to match the current build config (which we do with Cocoapods) and if so how would we go about that given how Carthage only creates a single bundle per dependency?

**Comment by blender** [comment]
The setup you're describing seems pretty standard to me.

> To build, I've been building each of our projects separately via Carthage per the instructions on the README

Where in the README does it say to do this?

You should have a Cartfile in each of the projects that have dependencies you want Carthage to manage. If a project does not depend on anything, it does not need a Cartfile.

read `->`  as depends on

So:
App -> (A, B, C, D) (Carfile in App Specifying it depends on A, B, C , D)

A -> Nothing (No Cartfile)
B -> (E, F) (Carfile in B, specifying that it depends on E, F. E, F depend on Nothing)
C -> D (but D is also used directly in the App) (Carfile in C specifying that it depends on  D)
D -> Nothing (No Cartfile)

Go do the App and run

`carthage update`

**Comment by blender** [comment]
> It’s just that some of them won’t build.

In each of your separate projects run `carthage update --no-skip-current`. 

>I can try at the app level but I would have concerns if that worked but we still couldn’t build some of the libs independently - because obviously we want to be able work independently in the sub projects at times.

This is also pretty standard, however there are several ways to achieve this and you have to pick one that fits your team.

> Could the fact that we also have at least one custom build config (other than DEBUG and RELEASE) be part of the problem? I know that could cause issues with Cocoapods.

Carthage builds configuration RELEASE by default I believe. You can specify which configuration to build by passing `--configuration`. This is passed to to `all` dependencies I believe.

It sounds to me that you're project is set up with Cocoapods in a very specific way to how Cocoapods works. I would like to help you more but doing so with Github issues is not the most effective way.

**Comment by bladebunny** [comment]
Thanks again.

> ...Github issues is not the most effective way

I understand.  I will try to build an example app that has some of the same sort of structure and see how that goes.  

I'll have to re-read the README as well.  I've been spoiled by Cocoapods and not had to think too hard about workflow for a while. e.g. We generally don't have to worry about what config we're building because CP dynamically builds and links the right dependency.  

Something I hadn't even thought about with Carthage is I guess we would generally decide ahead of time what config we're building -- eg with the DEBUG switch in dev and then, less commonly, with the RELEASE config when we want to distribute or test a release build.  

Not something we even really think about with CP.  Of course, you live by CP and you die by CP.  
Our biggest pain point at the moment is that we can be editing one line of code in our main app codebase and it'll trigger a full rebuild of all our depedendent libs.  Not completely CP's fault of course -- also an Xcode issue -- but something that CP doesn't really help us solve.  

Anyway, I thank you.  If i get a test app working I'll post it on Github and reply back here so others can hopefully benefit from it.

**Comment by blender** [comment]
> Not completely CP's fault of course -- also an Xcode issue -- but something that CP doesn't really help us solve.

It's not CP's fault. It's Xcode. With Carthage you can work around this and even go further.

Trying with a sample project that mimics the setup you want is the best recommendation I can give you. 

Alternative I suggest you ask at your local meetup for some help.

If you get any further feel free to ask more questions here.

**Comment by bladebunny** [comment]
I put together a sample that has comparable  complexity.  Of course, it worked fine!
Which is awesome.  

Definitely seems to point back at my other app.  I think I'll have to repave the project files but at least now I know I'm on the right path.

I will try to find time to write up how I did it.  But frankly, it was pretty straightforward just following the README guidance.  

The example repo is linked below should it prove useful to anyone else.  It has several layers of dependency as well as at least one lib that just wraps some other third party libs that aren't available via Cartfile.

Thanks again!

https://github.com/bladebunny/CarthageNestedDemo
