### ISSUE TITLE
Skip checkout on valid cache

### ISSUE THREAD

**Issue by srikanth-vm** [Carthage/Carthage#2483]
* carthage install method: [ ] .pkg, [ x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: 0.29.0
* `xcodebuild -version`:  Xcode 9.3 
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No

**Cartfile**
```
github "Quick/Nimble" == 7.0.2
github "facebook/facebook-ios-sdk" == 4.27.1
```

While running `carthage bootstrap --platform iOS --cache-builds` carthage will always checkout from above repositories. It does proceed to pick binaries from local cache folder later on, but as some of the repositories are quite large it does take up a lot of time to checkout. 

Is there an option to skip checkout if cache is valid ?

**Comment by blender** [comment]
No, not at the moment.

**Comment by ikesyo** [comment]
This might be a duplicate of / related ro #2358.

**Comment by srikanth-vm** [comment]
Following #2358
