### ISSUE TITLE
Frameworks which use dependencies built by carthage sometimes don't work well with playgrounds

### ISSUE THREAD

**Issue by kluufger** [Carthage/Carthage#2489]
👋

* carthage install method: homebrew
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: 0.29.0
* `xcodebuild -version`: Xcode 9.4 Build version 9F1027a
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? Yes

### Steps to reproduce
In your shell
```sh
> git clone https://github.com/kluufger/UsingPlayground
> cd UsingPlayground
> carthage bootstrap --platform iOS --new-resolver --no-use-binaries --cache-builds
> open UsingPlayground.xcworkspace
```
Then
- build AppFramework scheme in xcode
- run the MyPlayground/ViewController playground, it should work

<img width="1392" alt="screen shot 2018-06-18 at 12 13 41 pm" src="https://user-images.githubusercontent.com/35971588/41535374-9695998c-72f1-11e8-8aae-486371ba3891.png">

- now close xcode window (it's not necessary to close the xcode application)
- open this workspace again
- build the AppFramework again
- run the playground again, at this point I get

```swift
Playground execution failed:

error: MyPlayground.playground:2:18: error: no such module 'AppFramework'
@testable import AppFramework
```

<img width="1392" alt="screen shot 2018-06-18 at 12 16 34 pm" src="https://user-images.githubusercontent.com/35971588/41535392-a9a99190-72f1-11e8-99da-c88e8e1e23ef.png">

**Cartfile**
```
github "Otbivnoe/Framezilla" ~> 2.0
github "Raizlabs/Anchorage" ~> 4.0
```

**Carthage Output**
```
> carthage bootstrap --platform iOS --new-resolver --no-use-binaries --cache-builds

*** Checking out Anchorage at "4.2.2"
*** Checking out Framezilla at "2.9.1"
*** No cache found for Anchorage, building with all downstream dependencies
*** No cache found for Framezilla, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/sy/tm1zr3s13kz82z2vfyr2m5680000gn/T/carthage-xcodebuild.DaAHMS.log
*** Building scheme "Anchorage-iOS" in Anchorage.xcodeproj
*** Building scheme "Framezilla iOS" in Framezilla.xcodeproj
```

**Expected outcome**
The framework `AppFramework` and other dependencies like `Anchorage` and `Framezilla` work in the playground.

**Actual outcome**
They don't, neither `AppFramework` nor `Anchorage` and `Framezilla` can be found (no such module 'AppFramework').

**Comment by blender** [comment]
This is a problem with the setup of your playground / workspace. Not with Carthage

**Comment by kluufger** [comment]
@blender I guessed so ... could you maybe point me to some resources on how to setup playgrounds so that they work? Just in case, using the same setup with git submodules but without carthage works without any problems.

**Comment by blender** [comment]
You have to open the .xcworkspace and then the playground from there. Standalone the playground will not work.

I have just tried and if I do that everything works fine for me.

**Comment by kluufger** [comment]
@blender 

> You have to open the .xcworkspace and then the playground from there.

I do just that.

> Standalone the playground will not work.

I haven't tried that, but I'd guess so.

> I have just tried and if I do that everything works fine for me.

Have you followed the "steps to reproduce"? It works fine when I just clone my repo, build it and run the playground. The problems begin when I either change something in the project (like add a new dependency) or close and reopen the workspace.

**Comment by blender** [comment]
@kluufger when you add a dependency you have to also add it to the copy-framework phase

**Comment by kluufger** [comment]
@blender I thought it was only necessary for apps which are submitted to the appstore. Anyway, it wouldn’t explain why the playground work for me in the beginning and don’t work after restarting xcode / adding a dependency. Will try to reinstall xcode now ... Maybe that would help.

**Comment by kluufger** [comment]
Hi again!

> Will try to reinstall xcode now ... Maybe that would help.

It didn't.

But I've found some king of resolution for this issue anyway, well, in my particular case, at least: I create a new target which server as a proxy for playgrounds (just like in this case), but copy `*.xccodeproj` files from `Carthage/Checkouts` there instead of built frameworks by carthage (the app itself still uses the frameworks from `Carthage/Build`). This way playgrounds are quite stable and haven't crashed on me yet.
