### ISSUE TITLE
README is missing info about building Swift static libraries 

### ISSUE THREAD

**Issue by isaac-weisberg** [Carthage/Carthage#2497]
There are obvious traces of work happening in this direction ( #1935 , #2285 ), but I personally struggle with accumulating any particular results of it.

**Comment by blender** [comment]
You missed https://github.com/Carthage/Carthage/pull/2415

Do you want to fill in the gap in the Readme? PRs welcome!

**Comment by dimazen** [comment]
@isaac-weisberg what kind of issues are you facing with? 
I do have a repo that combines a shared dynamic lib + linked to it static libraries that come from the Carthage [here](https://github.com/dimazen/static-linking).

**Comment by blender** [comment]
@dimazen I don't think you need the ld.py anymore . There are updated instruction we plan to push https://github.com/Carthage/Carthage/pull/2499

**Comment by dimazen** [comment]
Indeed, @blender. @isaac-weisberg Yes, please pay attention that my repo is a bit outdated. But anyway please post a more concrete question / issue you've faced with so that we can find a way out :)

**Comment by isaac-weisberg** [comment]
That's like... I am sorry, I am maybe caught out of context... but we are not facing any issues here anymore

**Comment by blender** [comment]
All is fine. I just asked @dimazen to take a quick look based on #2442

**Comment by dimazen** [comment]
Looks like thats me was out of the context :) Anyway, I'm curious to go through the #2499 and #2415 on my own.
