### ISSUE TITLE
Jump to source

### ISSUE THREAD

**Issue by AlexanderBollbach** [Carthage/Carthage#2505]
I skipped the template for this issue because I don't think it applies.  I hope thats ok.

I've been using Cocoapods for a while.  I was able to "jump to definition" and it would take me to the source of my library.  I recently switched to Carthage and when I jump to definition it takes me to the "Swift Generated Headers".  Can I somehow have it jump to the actual source located in the checkouts directory?

**Comment by mdiep** [comment]
If you build through Xcode, you can do that. (Look at ReactiveCocoa for an example of how that's done.)

**Comment by blender** [comment]
Also see https://github.com/Carthage/Carthage/issues/2137

**Comment by AlexanderBollbach** [comment]
@mdiep  reading that issue it isn't clear to me how to get the behavior i had in Cocoapods.  I tried one of the simpler recommendations like passing a `debug configuration` argument while building the framework i want to debug, but it didn't work.  Other recommendations were usage of a Workspace (which isn't possible in my case) or a complex Ruby script.  Am I not missing something simpler that allows Xcode to jump to the checkouts source while debugging?

**Comment by blender** [comment]
Cocoapods creates a workspace and pulls in the projects of your dependencies into that workspace so that you can just to the source code.

To get the same behavior, you have to do the same.

**Comment by blender** [comment]
Have also a look at https://github.com/Carthage/workflows

**Comment by AlexanderBollbach** [comment]
I cloned that and ran the `carthage-developer-checkouts` in my project dir and got `Warning: $dependency has not yet been cloned to $dependency_dir, skipping symlink.` for all of my dependencies.  looking in `Carthage/Checkouts` it seems sources have been cloned however.

**Comment by blender** [comment]
@c0diq Maybe can help?
