### ISSUE TITLE
Can't upgrade carthage to 0.30.1 version

### ISSUE THREAD

**Issue by GabrielSilveiraa** [Carthage/Carthage#2506]
I am trying to upgrade carthage with homebrew. I tried to brew upgrade carthage and also with --HEAD option, but none of both worked. Running brew info carthage I got: 

carthage: stable 0.29.0 (bottled), HEAD
Decentralized dependency manager for Cocoa
https://github.com/Carthage/Carthage
/usr/local/Cellar/carthage/HEAD-49c7901 (69 files, 23.9MB) *
  Built from source on 2018-07-02 at 11:01:43
/usr/local/Cellar/carthage/0.25.0 (69 files, 23MB)
  Poured from bottle on 2017-10-06 at 10:03:48
/usr/local/Cellar/carthage/0.26.2 (75 files, 25.9MB)
  Poured from bottle on 2017-11-13 at 13:53:11
/usr/local/Cellar/carthage/0.27.0 (69 files, 26.6MB)
  Poured from bottle on 2017-12-27 at 17:54:10
/usr/local/Cellar/carthage/0.29.0 (69 files, 26.7MB)
  Poured from bottle on 2018-04-03 at 16:34:29
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/carthage.rb
==> Requirements
Build: xcode ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions

**Comment by jdhealy** [comment]
`/usr/local/Cellar/carthage/HEAD-49c7901/INSTALL_RECEIPT.json` — does that file exist, any clues in there?

**Comment by jdhealy** [comment]
Just checked on my machine, I was able to `brew install --HEAD carthage`, read `/usr/local/Cellar/carthage/HEAD-49c7901/INSTALL_RECEIPT.json`, and execute `carthage version` and `carthage help`.

**Comment by blender** [comment]
```
$ brew upgrade carthage
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

==> Upgrading 1 outdated package, with result:
carthage 0.29.0 -> 0.30.1
==> Upgrading carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.30.1.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/dc/dc0027940db2a5017b96228c1b9903a460cafac07e8fa47684805ceb784532cb?__gda__=exp=1530548698~hmac=ad8d0ac570c7ae5c2a986618a903709c22c55dcd11bd3ef5b56c8e9f1e91
######################################################################## 100.0%
==> Pouring carthage-0.30.1.high_sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.30.1: 69 files, 23.9MB
```

Working here

**Comment by GabrielSilveiraa** [comment]
I did it again and it worked. I don't know what was wrong. But thank you, guys!
