### ISSUE TITLE
Support for single-file µframeworks?

### ISSUE THREAD

**Issue by vmanot** [Carthage/Carthage#2511]
There are a lot of open source Swift "µframeworks", i.e. single-file libraries. Carthage could provide support for tracking and mirroring these files from their respective repositories, installation being the usual drag-and-drop.

**Comment by blender** [comment]
Thanks for opening an issue!

I believe since 0.30.1 support is already there.

It's enough for the "µframeworks" to be package as a "Static Framework" i.e. Mach-O type `static lib`.

The artifact will be linked statically thus you won't incur in any run time loading penalties.

**Comment by ikesyo** [comment]
It seems to me that just adding desired repositories to `Cartfile` and drag files from `Carthage/Checkouts` to your Xcode project is what you want. Carthage correctly checkouts repositories in which no Xcode projects or shared schemes don't exist.

**Comment by jdhealy** [comment]
@blender, from what I intuit, this report seems to be referring to repositories without Xcode projects (so, not supported by our recent static framework support).

@vmanot, could you confirm and elaborate? (Also, could you clarify “the usual drag-and-drop”?)

**Comment by vmanot** [comment]
@jdhealy yes, was referring to repositories without Xcode projects; i.e. just a single Swift file. By drag-and-drop I was referring to how frameworks are currently embedded, through the user dragging built frameworks into their project.
