### ISSUE TITLE
Carthage won't build purchases-ios on 0.30.1

### ISSUE THREAD

**Issue by jeiting** [Carthage/Carthage#2512]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.30.1
* `xcodebuild -version`: Xcode 9.4.1 Build version 9F2000
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "revenuecat/purchases-ios"
```

**Carthage Output**
```
*** Fetching purchases-ios
*** Checking out purchases-ios at "1.0.4"
*** xcodebuild output can be found in /var/folders/n1/dqrt9rvs5sjgp8hr4fqvb80r0000gn/T/carthage-xcodebuild.ChCgEG.log
*** Downloading purchases-ios.framework binary at "1.0.4"
```

**Actual outcome**
No contents in Carthage/Build
Xcode build log is empty

**Expected outcome**
Download and build my framework

**Carthage 0.29.0 Output**
```
*** Fetching purchases-ios
*** Checking out purchases-ios at "1.0.0"
*** xcodebuild output can be found in /var/folders/n1/dqrt9rvs5sjgp8hr4fqvb80r0000gn/T/carthage-xcodebuild.HcIXr5.log
*** Downloading purchases-ios.framework binary at "1.0.0"
*** Skipped installing purchases-ios.framework binary due to the error:
	"Failed to write to /Users/jacobeiting/code/CartfileTest/Carthage/Build/.purchases-ios.version: Error Domain=NSCocoaErrorDomain Code=4 "The folder “.purchases-ios.version” doesn’t exist." UserInfo={NSFilePath=/Users/jacobeiting/code/CartfileTest/Carthage/Build/.purchases-ios.version, NSUserStringVariant=Folder, NSUnderlyingError=0x7f96c7d45cc0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}"
*** Building scheme "Purchases (macOS)" in Purchases.xcodeproj
*** Building scheme "Purchases" in Purchases.xcodeproj
```

**Comment by blender** [comment]
You are not specifying `--no-use-binaries` and I think carthage is being picky about the binaries that you have attached.

Have you tried with `--no-use-binaries` ?

**Comment by jeiting** [comment]
Ok, removing `--no-use-binaries` works.

Two questions: 
1. Why the regression?
2. What is particular about my binaries?

**Comment by blender** [comment]
Maybe related to: https://github.com/Carthage/Carthage/issues/2491
