### ISSUE TITLE
Support for avoiding networking from `git fetch` hitting ‘github.com’ (and potentially all types of requests to it) through configuration and not Cartfile modification.

### ISSUE THREAD

**Issue by drekka** [Carthage/Carthage#2513]
I've worked on a number of enterprise projects where internet access is restricted due to security and the enterprise has insisted that dependencies are stored in their repositories instead of Github.

This poses a problem for Carthage because it cannot access the internet and doesn't have an alternative.

In my current project we've been forced to use a enterprise hosted bitbucket, manually copy all the dependency projects into it and create our own branches where we've updated the Cartfiles to point at the local repository. It's a bit of a pain.

I'd like to propose the idea of being able to supply some form of override host file. The idea is that it contains a host/override list which Carthage looks up when it's about to pull a dependency. If the host of the dependency is in the list, Carthage replaces it with the override from the file.  

So rather than having to hack our dependencies to work within the enterprise network, we can simply copy them to the enterprise's repository without change, and then use the host/override list to redirect all requests to the enterprises repository.

If there's a simpler way to address this problem, I'd love to know.

**Comment by ikesyo** [comment]
Is Git's `url.<base>.insteadOf` what you want?

https://git-scm.com/docs/git-config#git-config-urlltbasegtinsteadOf

**Comment by drekka** [comment]
@blender Hosts file won't work for us. I'm looking into @ikesyo 's idea of using git url.insteadof. To give a specific example:

We have a copy of Swinject (https://github.com/Swinject/Swinject.git) stored in the network repo at ssh://git@bitbucket.int.corp:2222/mmas/swinject-swinject.git

So I'm trying to figure out how to get Carthage/git to automatically redirect to the bitbucket server without having to modify they Cartfile.

**Comment by blender** [comment]
I'm in a similar situation but I disagree with your approach

> without having to modify they Cartfile

Again, they are different repositories. You are expected to modify the Cartfile 😄 

Moreover I believe that also your dependency definition would have to change, form "github" to "git" (unless you're already using git for some reason).

**Comment by drekka** [comment]
I've been playing around with this for the last little while and I've not found a answer. The problem is best described as:

- I'm in a corporate network with limited or no internet access.
- Required github repos have been copied into a network based server (bitbucket) so can be accessed from there.
- The names of the repos do not exactly match their GitHub names due to differences between bitbucket and GitHub. ie. `Swinject/Swinject.git` has become `Swinject-swinject.git`.
- In order to make the dependencies work, the people who set them up in bitbucket had to make their own branches and modify any Cartfile's in those repos to point to the bitbucket server for their dependencies. ie. dies-pact-consumer's Cartfile has been customised to point to bitbucket.
- Having to create our own branches in all the dependency repositories is fragile.

I've tried using git's `url.insteadof` as suggested by @ikesyo but it seems to only be useful where the host or scheme need re-writing. When the actual repository names are different I couldn't get it to work.

Using the hosts file of the machine as per @blender 's comment won't work either because it cannot be checked in and against it's just about the hosts, not the full url.

Therefore the solution I'm suggesting is to create an optional file call `Cartfile.local`. The contents of the file would look like this:

````
github "antitypical/Result" -> git "ssh://git@bitbucket.int.corp:2222/mmas/antitypical-result.git"
````

Carthage could read this file and wherever it see's a request to pull a repo from `github "antitypical/Result"`, it would instead pull it from `git "ssh://git@bitbucket.int.corp:2222/mmas/antitypical-result.git"`.

SO:

- No modifications required to any of the Cartfiles either in the main project or any of the dependencies.
- Any external repos can be hosted internally with no change. 
- Repos can be safely updated just by accessing the Internet and doing a pull and push.
