### ISSUE TITLE
Carthage update/bootstrap from private github repo with ssh.

### ISSUE THREAD

**Issue by palusik86** [Carthage/Carthage#2517]
* carthage install method: [ ] .pkg, [X ] homebrew, [ ] source
* `which carthage`: `bootstrap`
* `carthage version`: `0.30.1` 
* `xcodebuild -version`: `Xcode 9.4` 
* Are you using `--no-build`?  `No`
* Are you using `--no-use-binaries`? `No` 
* Are you using `--use-submodules`?  `No` 
* Are you using `--cache-builds`? `No` 
* Are you using `--new-resolver`? `No` 

**Cartfile**
```
github "Hearst-DD/ObjectMapper" "3.1.0"
github "antitypical/Result" "3.2.4"
github "Quick/Nimble" "v7.0.3"
github "Quick/Quick" "v1.2.0"
github "AliSoftware/OHHTTPStubs" "6.1.0"
// or any combination here with HTTPS
git "ssh://git@companyname.github.com:company/repo_name" == 1.0.2
```

**Carthage Output**
```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Actual outcome**

**Expected outcome**
Update carthage using ssh. This is private / enterprise account. As I have also my private account, I use ssh config file like this:
```
	Host companyname.github.com
	HostName github.com
	PreferredAuthentications publickey
	IdentityFile ~/.ssh/id_rsa_github_companyname

	Host github.com
	HostName github.com
	PreferredAuthentications publickey
	IdentityFile ~/.ssh/id_rsa
```

Carthage can't update private repos. How to solve this?

**Comment by ikesyo** [comment]
Are you sure that normal git clone with `git clone ssh://git@companyname.github.com:company/repo_name` works correctly? `companyname.github.com` doesn't seem to be a correct host name to me.

You should also check the GitHub's document: https://help.github.com/articles/connecting-to-github-with-ssh/.

**Comment by PawelPalkaPerform** [comment]
It works, as it is defined in here:
`	Host companyname.github.com
	HostName github.com`
Cloning using git in terminal works perfect, but carthage can't do that, so I removed my private ssh key and set one key for github. 

Here is example how to do this:
https://medium.com/@trionkidnapper/ssh-keys-with-multiple-github-accounts-c67db56f191e

**Comment by palusik86** [comment]
As you see, this is the case, two accounts with ssh :D

**Comment by brennantaylor** [comment]
Are you sure you need the `ssh://` scheme?

`git "git@myaccount.github.com:/Foo/bar.git" == 1.0.0`

**Comment by PawelPalkaPerform** [comment]
I need ssh as it is for CI machine also, so writing password on HTTP isn't very usefull

**Comment by mdiep** [comment]
Have you tried the `--use-ssh` flag?

**Comment by PawelPalkaPerform** [comment]
Yes, my command:
`carthage update --use-ssh --no-use-binaries --platform iOS --cache-builds` or
`carthage bootstrap --use-ssh --no-use-binaries --platform iOS --cache-builds`

**Comment by blender** [comment]
Did you notice you have a typo in the url?
ssh://git@companyname.github.com:company/repo_name 


ssh://git@companyname.github.com/company/repo_name
