### ISSUE TITLE
Dependency graph contains a cycle

### ISSUE THREAD

**Issue by drekka** [Carthage/Carthage#2521]
* carthage install method: .pkg
* carthage version: 0.30.1

**Cartfile**
```
github "Swinject/Swinject"
github "SwInject/SwinjectStoryboard"
github "yonaskolb/Stylist"
github "mxcl/PromiseKit"
```

`yonaskolb/Stylist` didn't have a `Cartfile` so after checking it out I added it's dependencies into a `Cartfile` in it's Checkout directory:

```
github "krzysztofzablocki/KZFileWatchers"
github "jpsim/Yams"
```

**Carthage Output**
```
Bit-Shifter:Crux derekclarkson$ carthage update
*** Fetching SwinjectStoryboard
*** Fetching Stylist
*** Fetching Swinject
*** Fetching PromiseKit
*** Checking out SwinjectStoryboard at "2.0.2"
*** Checking out Swinject at "2.4.1"
*** Checking out Stylist at "0.2.0"
*** Checking out PromiseKit at "6.3.4"
*** xcodebuild output can be found in /var/folders/qn/mdmvqmns1v38s60q7q3my2nc0000gn/T/carthage-xcodebuild.q1djgv.log
The dependency graph contained a cycle:
PromiseKit: 
Swinject: 
Stylist: Yams, KZFileWatchers
SwinjectStoryboard: Swinject
```

The problem started the moment I added `krzysztofzablocki/KZFileWatchers` to the `Cartfile`. But there's no obvious issue.
 
At this point I'm not sure where there could be a cycle. Any ideas?

**Comment by blender** [comment]
1. Pin the version you are using of the dependencies
2. Try `--new-resolver`

**Comment by blender** [comment]
No, not at the moment.

I suspect this is a misleading error, see https://github.com/Carthage/Carthage/issues/1986

**Comment by werner77** [comment]
The cyclic dependency check should be done in the resolve stage (which I fixed in my Pull request regarding --fast-resolver: https://github.com/Carthage/Carthage/pull/2455). What you're running into is the buggy cyclic dependency check during the build phase. With --no-build the error disappears.

**Comment by drekka** [comment]
I've done some testing and vanilla'd the bug. My app contains this Cartfile:

```
github "yonaskolb/Stylist"
```

Stylist doesn't have a Cartfile of it's own, but does actually have a runtime dependency on krzysztofzablocki/KZFileWatchers. So after Carthage checked out Stylist I tried adding a Cartfile to it containing this:

```
github "krzysztofzablocki/KZFileWatchers"
```

So it's something about these two repos.

**Comment by yechunjun** [comment]
I also met this issue when upgrade Carthage to 0.30.1. 
Carthage 0.29.0 is fine for my project.

@werner77  I am going to try your `--fast-resolver` to fix my problem.

**Comment by blender** [comment]
Carthage 0.30.1 is much more strict about Semantic versions, current master will even be more strict. Be sure to read https://semver.org

**Comment by david6p2** [comment]
@yechunjun @drekka did you try the `--fast-resolver` from @werner77 ? Did it solve the problem? Your tests can help to merge this `--fast-resolver` PR #2455

**Comment by drekka** [comment]
Hmm I just checked back with the project where I reported this and it appears to no longer be happening. Can't say why unfortunately.
