### ISSUE TITLE
The command lines "Carthage bootstrap" and "Carthage update" never end

### ISSUE THREAD

**Issue by glassalle59** [Carthage/Carthage#2528]
* carthage install method: homebrew
* `carthage version`: 0.30.1
* `xcodebuild -version`: 9.4.1

**Carthage Output**

1)
carthage update
*** Fetching YYCache

2)
carthage bootstrap
*** Checking out RoutingHTTPServer at "v1.0.1"
*** Checking out YYCache at "1.0.5"

3)
sudo carthage update
*** Cloning YYCache

4)
sudo carthage bootstrap
*** Checking out RoutingHTTPServer at "v1.0.1"
*** Checking out YYCache at "1.0.5"
*** Cloning YYCache
*** Cloning RoutingHTTPServer

**Expected outcome**
All of these Carthage command should finish the execution

I tried to wait all night but it's the same thing, it does not continue...

Any ideas to fix this problem please ?

**Comment by blender** [comment]
Did you try --new-resolver

**Comment by glassalle59** [comment]
Same results :(

**Comment by blender** [comment]
Are you pinning the version of the frameworks you are using? Are you sure there is no conflicting transitive dependency? Can you try brew install carthage --HEAD

**Comment by glassalle59** [comment]
It's OK now thank you :)
