### ISSUE TITLE
Two+ `copy-frameworks` invocations on the same framework can error

### ISSUE THREAD

**Issue by brentleyjones** [Carthage/Carthage#2531]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.28.0
* `xcodebuild -version`: Xcode 9.4.1
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No

**Actual outcome**
```
A shell task (/usr/bin/xcrun lipo -remove armv7 -output /Users/z002wrr/Library/Developer/Xcode/DerivedData/Harmony-dobqplhmutrloybkgkxvysfcinjt/Build/Products/Debug-iphonesimulator/HTMLEntities.framework.dSYM/Contents/Resources/DWARF/HTMLEntities /Users/z002wrr/Library/Developer/Xcode/DerivedData/Harmony-dobqplhmutrloybkgkxvysfcinjt/Build/Products/Debug-iphonesimulator/HTMLEntities.framework.dSYM/Contents/Resources/DWARF/HTMLEntities) failed with exit code 1:
fatal error: /Applications/Xcode-9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: -remove armv7 specified but fat file: /Users/z002wrr/Library/Developer/Xcode/DerivedData/Harmony-dobqplhmutrloybkgkxvysfcinjt/Build/Products/Debug-iphonesimulator/HTMLEntities.framework.dSYM/Contents/Resources/DWARF/HTMLEntities does not contain that architecture
```

**Expected outcome**
Carthage should not strip dSYMs in place, or do something else, to allow concurrent `copy-frameworks` invocations with the same framework to succeed. This isn't an issue with frameworks since they all have specific locations, where dSYMs end up in the `TARGET_BUILD_DIR` folder.

In our setup we have many test targets that all use `copy-frameworks` to copy frameworks into their bundles. When they are built concurrently `copy-frameworks` strips the same dSYM and error out because the previous strip already removed the offending architecture.

**Comment by blender** [comment]
FYI the latest Carthage version is 0.30.1

Carthage does not support concurrent invocations btw.

For discussion about stripping see #2485 

>  When they are built concurrently copy-frameworks strips the same dSYM and error out because the previous strip already removed the offending architecture.

Off the top of my head one way to avoid this would be to check if the architecture to strip is there in the first place.

**Comment by brentleyjones** [comment]
> Off the top of my head one way to avoid this would be to check if the architecture to strip is there in the first place.

I think it does check, but because it's being run concurrently it gets stripped by one process before the new process can strip it.

> Carthage does not support concurrent invocations btw.

Yet Xcode builds in parallel by default. This will come up in normal cases.

**Comment by blender** [comment]
> Yet Xcode builds in parallel by default. This will come up in normal cases.

This is because you have parallelize builds on (maybe I'm wrong)

Do you want to make a proposal on how to fix this?

**Comment by brentleyjones** [comment]
One solution would to be able to specify if it strips, or more smartly detect it. Then for test targets, where it's not needed, it can just not strip them.

**Comment by blender** [comment]
Why do you copy-frameworks in test targets? Are these applications?

**Comment by mdiep** [comment]
Normally you'd only have one `copy-frameworks` invocation—in your app target. So even if you are building in parallel, that step would never be run concurrently.

Can you share more about why you're running `copy-frameworks` concurrently?

**Comment by brentleyjones** [comment]
Right now it's because I'm using XcodeGen and it managed Carthage by default. I'm making a fix over there so it doesn't do it for tests (
https://github.com/yonaskolb/XcodeGen/issues/359). Though I've done this before and so have others based on other issues I've found people filed for test targets.

It's probably best that I, and others, not do this. Maybe the docs can be updated to recommend against this?

**Comment by blender** [comment]
@brentleyjones would you be so kind to make a PR to update the docs?

**Comment by brentleyjones** [comment]
I’ll open a PR tomorrow. 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
