### ISSUE TITLE
"carthage update --platform iOS" first time project "failed with exit code 72"

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [Carthage/Carthage#2539]
I'm a real newbie. I'm on Terminal on Mac mini. I followed instructions for https://github.com/dropbox/SwiftyDropbox.

My Cartfile said:

`# SwiftyDropbox`
`github "https://github.com/dropbox/SwiftyDropbox" ~> 4.6.0`

I typed:

brew update
brew install carthage
carthage update --platform iOS

Result:

*** Cloning SwiftyDropbox
*** Cloning Alamofire
*** Checking out SwiftyDropbox at "4.6.0"
*** Checking out Alamofire at "4.7.3"
*** xcodebuild output can be found in /var/folders/gc/bnd0bmfs5x79n8rnjkc2r06m0000gn/T/carthage-xcodebuild.29i88J.log
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/shinehah/Documents/Xcode\ Projects/IPv4\ Calculator\ folder/IPv4Calculator/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

**Comment by ikesyo** [comment]
That measns that Xcode or its command line tools is not installed. Are you sure that you installed the latest Xcode from App Store?

**Comment by ikesyo** [comment]
You shoul check whether `xcodebuild` command works or not: `xcodebuild -version`.

**Comment by ikesyo** [comment]
Closing this in favor of #2541.
