### ISSUE TITLE
Whenever I run into an error and I have to rerun "carthage update --platform iOS", can I simply rerun statement again?

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [Carthage/Carthage#2540]
Whenever I run into an error running "carthage update --platform iOS" and I have to rerun "carthage update --platform iOS", can I simply rerun "carthage update --platform iOS" after I have made the fix, or do I have to undo what "carthage update --platform iOS" had done before or do anything else extra before I rerun "carthage update --platform iOS"?

**Comment by ikesyo** [comment]
No need to do anything, just reruning should work.
