### ISSUE TITLE
carthage update --platform iOS Task failed with exit code 70: /usr/bin/xcrun xcodebuild

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [Carthage/Carthage#2541]
_I am really new to this._

_Following instructions at https://github.com/dropbox/SwiftyDropbox, my Cartfile says:_

`# SwiftyDropbox`
`github "https://github.com/dropbox/SwiftyDropbox" ~> 4.6.0`

_In Terminal on my Mac mini, I typed the following:_

`brew update`
`brew install carthage`
`carthage update --platform iOS`

_I got the following results on Terminal after the last statement only (I don't show the results after the first two statements):_

*** Fetching SwiftyDropbox
*** Fetching Alamofire
*** Checking out SwiftyDropbox at "4.6.0"
*** Checking out Alamofire at "4.7.3"
*** xcodebuild output can be found in /var/folders/gc/bnd0bmfs5x79n8rnjkc2r06m0000gn/T/carthage-xcodebuild.06AVAd.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -workspace /Users/shinehah/Documents/Xcode\ Projects/IPv4\ Calculator\ folder/New\ Home\ 02/IPv4Calculator/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme Alamofire\ iOS -configuration Release -derivedDataPath /Users/shinehah/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/Alamofire/4.7.3 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=4DC4901C-B822-43E7-AB12-7A811B7C9083 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/shinehah/Documents/Xcode Projects/IPv4 Calculator folder/New Home 02/IPv4Calculator/Carthage/Checkouts/Alamofire)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/gc/bnd0bmfs5x79n8rnjkc2r06m0000gn/T/carthage-xcodebuild.06AVAd.log

_I tried running `carthage update --platform iOS` several times, changing the factors that might affect it._

_I attached the xcodebuild log below._

[carthage-xcodebuild.06AVAd.log](https://github.com/Carthage/Carthage/files/2237699/carthage-xcodebuild.06AVAd.log)

_Any help will be appreciated. I need to know what to do._

**Comment by Shinehah-Gnolaum** [comment]
This is a different issue than the one referenced above. This has to do with xcodebuild not finding iOS Simulators.

I just noticed at the end of the xcodebuild log the following error log:

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:4DC4901C-B822-43E7-AB12-7A811B7C9083 }

	Available destinations for the "Alamofire iOS" scheme:
		{ platform:iOS Simulator, id:02B2EBCF-EF0F-43A2-9DCE-83F2E5E4C5E8, OS:10.0, name:iPad Pro (12.9 inch) }
		{ platform:iOS Simulator, id:761286AE-DF7E-4FD5-9CE7-C681F05253D2, OS:11.4, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:8B4D5025-A3B1-48FB-AEF1-701E9C708F3A, OS:10.0, name:iPhone 5 }
		{ platform:iOS Simulator, id:693D4940-1B91-43E1-B5AD-88E9763046C7, OS:11.4, name:iPhone 8 }

	Ineligible destinations for the "Alamofire iOS" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }

**Comment by ikesyo** [comment]
This should be the same as #2364.

**Comment by ikesyo** [comment]
I'm not saying #2539 is the same as this, since you can now run `xcodebuild` command #2539 is already resolved.

**Comment by blender** [comment]
Your simulator list is broken. Fixit it by opening xcode and purging invalid simulators

**Comment by ikesyo** [comment]
https://github.com/Carthage/Carthage/issues/2364#issuecomment-408585172

Looks like @Shinehah-Gnolaum resolved the issue. Closing.
