### ISSUE TITLE
Dependency resolution gets stuck

### ISSUE THREAD

**Issue by olejnjak** [Carthage/Carthage#2543]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: 0.30.1
* `xcodebuild -version`: Xcode 9.4.1; Build version 9F2000
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no (`--new-resolver` seems to work`)

**Cartfile**
```
github "ReactiveCocoa/ReactiveCocoa" ~> 7.0
github "AckeeCZ/ACKReactiveExtensions" == 3.4.0
```

**Carthage Output**
```
*** Fetching ReactiveCocoa
*** Fetching ACKReactiveExtensions
*** Fetching ReactiveSwift
*** Fetching AlamofireImage
*** Fetching Reachability.swift
*** Fetching Argo
*** Fetching realm-cocoa
*** Fetching SDWebImage
*** Fetching Marshal
*** Fetching Result
```

**Actual outcome**
Carthage did get stuck

**Expected outcome**
Carthage should tell that versions conflict (new resolver does that so it should be fine to make it default?)

**Comment by alex-king-ck** [comment]
I'm having the same problem. I'm also using ReactiveCocoa and ReactiveSwift, and am facing this issue when trying to upgrade them.

**Comment by blender** [comment]
Use --new-resolver
