### ISSUE TITLE
Timeout for version check does not work

### ISSUE THREAD

**Issue by Sebastian-Hojas** [Carthage/Carthage#2544]
* carthage install method: homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.30.1

When invoking any carthage command with a bad network connection (also simulated), the version check blocks operations without respecting the timeout of the version check request.

**Carthage Output**
```bash
# Invoking carthage with a bad network connection
> time carthage help
carthage help  0.06s user 0.05s system 0% cpu 19.325 total
```

Carthage took 19 seconds to complete `carthage help`.

**Expected outcome**

- Carthage correctly times out version check request after 0.5s
- I was also hoping for an invocation flag that would bypass the version check for CI builds. For a build process that would invocate carthage multiple times, even a timeout of 0.5s per call slows our build process down unnecessarily.

**Investigation**

The function `remoteVersion` in `BuildVersion.swift` gets the latest remote version with a timeout:
```swift
.timeout(after: 0.5, raising: CarthageError.gitHubAPITimeout, on: QueueScheduler.main)
```
This timeout doesn't seem to work.

**Comment by blender** [comment]
Do you want to give this a shot?

**Comment by blender** [comment]
And thanks to OP this is closed. 👏
