### ISSUE TITLE
SwiftMessages builds wrong scheme

### ISSUE THREAD

**Issue by wtmoose** [Carthage/Carthage#2549]
I just noticed a problem with Carthage and SwiftMessages. SwiftMessages.xcodeproj defines and shares the SwiftMessages scheme. This is what I expect Carthage to build. However, Carthage builds a different SwiftMessages scheme in Demo.xcworkspace.

````
*** Fetching SwiftMessages
*** Checking out SwiftMessages at "4.1.4"
*** xcodebuild output can be found in /var/folders/mc/662grfnx6cnc_v7tj0prjs7w0000gn/T/carthage-xcodebuild.o7j8ya.log
*** Building scheme "SwiftMessages" in Demo.xcworkspace
````

The problem is that this is a CocoaPods scheme (I CocoaPods with the Demo app to test my .podspec). It isn't the same as the SwiftMessages sheme in SwiftMessages.xcodeproj.

I was surprised by this discovery because the scheme in question isn't shared. Doesn't Carthage strictly built shared schemes?

<img width="759" alt="screen shot 2018-08-04 at 6 01 04 pm" src="https://user-images.githubusercontent.com/2529176/43681116-66310f80-9810-11e8-9c7a-1aaf48282382.png">

Note that SwiftMessages.xcodeproj exists at the top level, while Demo.xcworkspace lives in a sub-folder and doesn't directly reference SwiftMessages.xcodeproj (it only references the .podspec).

It seems that directly integrating SwiftMessages into the Demo project without CocoaPods would solve the problem, but it would be nice to know if there's an issue with my configuration or if there's a workaround. Any ideas?

**Comment by wtmoose** [comment]
Thanks for the clarification. Wouldn't building a non-shared scheme qualify as a bug?

**Comment by mdiep** [comment]
Quite possibly. It sounds like we're mistaking that scheme for a shared scheme of the same name.
