### ISSUE TITLE
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire   Referenced from: /Users/sunil/Library/Developer/CoreSimulator/Devices/DE0206F1-FD44-4D25-BA5A-5FD72BE5E4C6/data/Containers/Bundle/Application/C08F1BD2-9C68-4282-B565-EA1CB0021EBF/karTesting.app/Frameworks/pintFramework.framework/pintFramework   Reason: image not found

### ISSUE THREAD

**Issue by sunil-chayagol** [Carthage/Carthage#2550]
i am getting the above problem for long time. tried everything. i am using xcode 9.4 and alamofire is used inside a framework using cocopods and this framework is being used in a single application . when ever i run the app the app builds successfully and then the above error happens and app crashes.

**Comment by ikesyo** [comment]
> alamofire is used inside a framework using cocopods and this framework is being used in a single application . 

So how does that relate to Carthage?

**Comment by sunil-chayagol** [comment]
sorry posted at the wrong place

**Comment by sunil-chayagol** [comment]
but if you could help then it would be a great help

**Comment by ikesyo** [comment]
I'm sorry but we are not sure about CocoaPods setup issue.
