### ISSUE TITLE
Carthage is trying to build a scheme not in the Cartfile

### ISSUE THREAD

**Issue by sphericalwave** [Carthage/Carthage#2552]
* carthage install method: homebrew, 
* `which carthage`:
* `carthage version`: 0.30.1
* `xcodebuild -version`: 10.0 beta 4

Dunno
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 

**Cartfile**

github "maxkonovalov/MKRingProgressView"
github "dzenbot/DZNEmptyDataSet"
github "hyperoslo/BarcodeScanner"
github "WenchaoD/FSCalendar"
github "Marxon13/M13Checkbox"

**Carthage Output**

 /usr/local/Cellar/carthage/0.30.1: 69 files, 23.9MB
MacBook-Pro:fitwrenchui DarkKnight$ carthage update
*** Fetching DZNEmptyDataSet
*** Fetching ProcedureKit
*** Checking out ProcedureKit at "4.5.0"
*** Checking out DZNEmptyDataSet at "v1.8.1"
*** xcodebuild output can be found in /var/folders/w3/p67pv19524313b_29rrnn2p40000gn/T/carthage-xcodebuild.U29Btt.log
*** Downloading ProcedureKit.framework binary at "4.5.0"
***  Skipped installing ProcedureKit.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.2 (swiftlang-1000.0.29.2 clang-1000.10.39)."

    Falling back to building from the source
*** Building scheme "DZNEmptyDataSet" in DZNEmptyDataSet.xcodeproj
*** Building scheme "ProcedureKit" in ProcedureKit.xcodeproj
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -project /Users/DarkKnight/Documents/FitWrench/FitWrenchUI/Carthage/Checkouts/ProcedureKit/ProcedureKit.xcodeproj -scheme ProcedureKit -configuration Release -derivedDataPath /Users/DarkKnight/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10L213o/ProcedureKit/4.5.0 -sdk watchsimulator -destination platform=watchOS\ Simulator,id=C43FB29F-4BD1-4CBC-BEB0-80B29012BBDC -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/DarkKnight/Documents/FitWrench/FitWrenchUI/Carthage/Checkouts/ProcedureKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/w3/p67pv19524313b_29rrnn2p40000gn/T/carthage-xcodebuild.U29Btt.log
MacBook-Pro:fitwrenchui DarkKnight$ 

**Actual outcome**

Carthage failed with exit code 70
Because "Building scheme "ProcedureKit" in ProcedureKit.xcodeproj
Build Failed"
ProcedureKit is not included in the Cartfile and has never been included in this project. It was in a different project.

**Expected outcome**

Build like it usually does.

**Comment by blender** [comment]
Is it in our Cartfile.resolved ?

**Comment by blender** [comment]
I just tried with the Cartfile you specified and as expected everything works for me. Not sure how I can help. The best you can do is probably to debug it yourself.

Getting started is very easy: https://github.com/Carthage/Carthage/blob/master/CONTRIBUTING.md

**Comment by sphericalwave** [comment]
ProcedureKit is not present in Cartfile.resolved

**Comment by sphericalwave** [comment]
I'm not sure how to debug that's why I posted.

**Comment by sphericalwave** [comment]
Is there a way to clear the carthage files associated with the project and then just download the dependencies again? Perhaps just delete the folders?

**Comment by blender** [comment]
> Is there a way to clear the carthage files associated with the project 

Not sure I understand what you mean, however:

1. You can delete Carthage/ no problem
2. You can delete the Cartfile.resolved
3. Run `carthage bootstrap`

**Comment by sphericalwave** [comment]
Solved the issue.
I had navigated to the wrong project in Terminal.
Which explains why it was loading ProcedureKit because the project that i was callling update on had a reference to that framework.

🖖🏻

**Comment by blender** [comment]
👍
