### ISSUE TITLE
Xcode 10 beta 1-6 fails to export an iOS build correctly due to failing bitcode verification with Carthage-pulled binaries

### ISSUE THREAD

**Issue by croberts22** [Carthage/Carthage#2557]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.30.1
* `xcodebuild -version`: Xcode 10.0, Build version 10L232m
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes 
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No

**Cartfile**
```
github "PureLayout/PureLayout" "v3.0.2"
github "amplitude/Amplitude-iOS" "v3.14.1"
github "stephencelis/SQLite.swift" "0.11.4"
github "SwiftKit/Cuckoo" "0.11.2"
github "danielgindi/Charts" "3.1.1"
github "Alamofire/AlamofireImage" ~> 3.3
github "mattt/Surge" ~> 2.0.0
```

**Carthage Output**
```
➜ carthage bootstrap --platform iOS --no-use-binaries --cache-builds SQLite.swift Amplitude-iOS PureLayout Cuckoo Alamofire AlamofireImage Surge Charts
*** Checking out Cuckoo at "0.11.2"
*** Checking out Amplitude-iOS at "v3.14.1"
*** Checking out SQLite.swift at "0.11.4"
*** Checking out Charts at "3.1.1"
*** Checking out Alamofire at "4.7.3"
*** Checking out AlamofireImage at "3.3.1"
*** Checking out PureLayout at "v3.0.2"
*** Checking out Surge at "2.1.0"
*** xcodebuild output can be found in /var/folders/bx/3r_y1wln5y54wdcsyy98lnnxyc79bn/T/carthage-xcodebuild.aKKhwO.log
*** Valid cache found for Alamofire, skipping build
*** Valid cache found for AlamofireImage, skipping build
*** Valid cache found for Amplitude-iOS, skipping build
*** Valid cache found for Charts, skipping build
*** Valid cache found for Cuckoo, skipping build
*** Valid cache found for PureLayout, skipping build
*** Valid cache found for SQLite.swift, skipping build
*** Valid cache found for Surge, skipping build
```

**Actual outcome**

Carthage successfully builds the correct binaries and the project compiles, however the export phase when we build our app on Xcode 10 beta fails due to an invalidation on Bitcode:

```
[09:45:05]: $ /usr/bin/xcrun /Users/croberts/.rvm/gems/ruby-2.4.0/gems/fastlane-2.100.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/bx/3r_y1wln5y54wdcsyy98lnnxyc79bn/T/gym_config20180817-44378-v7av16.plist' -archivePath /Users/croberts/Library/Developer/Xcode/Archives/2018-08-17/[APP_NAME_REDACTED]\ 2018-08-17\ 09.35.09.xcarchive -exportPath '/var/folders/bx/3r_y1wln5y54wdcsyy98lnnxyc79bn/T/gym_output20180817-44378-1j0y5u8'
RVM detected, forcing to use system ruby
Now using system ruby.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/bx/3r_y1wln5y54wdcsyy98lnnxyc79bn/T/gym_config20180817-44378-v7av16.plist -archivePath '/Users/croberts/Library/Developer/Xcode/Archives/2018-08-17/[APP_NAME_REDACTED] 2018-08-17 09.35.09.xcarchive' -exportPath /var/folders/bx/3r_y1wln5y54wdcsyy98lnnxyc79bn/T/gym_output20180817-44378-1j0y5u8
2018-08-17 09:45:07.139 xcodebuild[65854:1859319] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/bx/3r_y1wln5y54wdcsyy98lnnxyc79bn/T/[APP_NAME_REDACTED]_2018-08-17_09-45-07.138.xcdistributionlogs'.
error: exportArchive: Failed to verify bitcode in Alamofire.framework/Alamofire:
error: Cannot extract bundle from /var/folders/bx/3r_y1wln5y54wdcsyy98lnnxyc79bn/T/XcodeDistPipeline.Qep/Root/Payload/[APP_NAME_REDACTED].app/Frameworks/Alamofire.framework/Alamofire (i386)



Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in Alamofire.framework/Alamofire:
error: Cannot extract bundle from /var/folders/bx/3r_y1wln5y54wdcsyy98lnnxyc79bn/T/XcodeDistPipeline.Qep/Root/Payload/[APP_NAME_REDACTED].app/Frameworks/Alamofire.framework/Alamofire (i386)

" UserInfo={NSLocalizedDescription=Failed to verify bitcode in Alamofire.framework/Alamofire:
error: Cannot extract bundle from /var/folders/bx/3r_y1wln5y54wdcsyy98lnnxyc79bn/T/XcodeDistPipeline.Qep/Root/Payload/[APP_NAME_REDACTED].app/Frameworks/Alamofire.framework/Alamofire (i386)

}

** EXPORT FAILED **
```

**Expected outcome**

Carthage should successfully build and export correctly.

**Additional Notes**

We found it weird that we were seeing i386 near the end of those error messages. We are running all of our frameworks through the copy-frameworks tool a la `/usr/local/bin/carthage copy-frameworks`. We also tried pulling out `Alamofire` thinking there may be an issue with it, but found the same problem show up with `Amplitude`.

We also removed the `--cache-builds` and cleared our all of the cached binaries with the same results. We saw this issue about disabling Bitcode here (https://github.com/Carthage/Carthage/issues/2440) and added an xcconfig to disable bitcode via `ENABLE_BITCODE = NO`. We still were unable to fix the problem. We suspect it's isolated to Xcode 10 beta and have submitted a bug report to them, but we wanted to cross-post here in case anyone else was experiencing a similar issue.

**Comment by croberts22** [comment]
Our issue ended up being simple; the script used to strip out the frameworks was not being applied for a specific configuration. Once we adjusted that, everything started working again. 👍

**Comment by jatazoulja** [comment]
I'm also running into same issue: can you elaborate on this?

> Our issue ended up being simple; the script used to strip out the frameworks was not being applied for a specific configuration. Once we adjusted that, everything started working again. 👍

Cheers!
