### ISSUE TITLE
Parse error: unexpected dependency type in line

### ISSUE THREAD

**Issue by imanhn** [Carthage/Carthage#2558]
I have installed Carthage with "brew install carthage"
and I have Xcode 9.3 and created a xCodeProject and put a Cartfile with the following content :
github "nextgis/ios_maplib"

carthage update --platform "iOS"

I get the following error, I am not sure where should I report this problem-Carthage or [https://github.com/nextgis/ios_maplib](url)

Parse error: unexpected dependency type in line: {\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf400

**Cartfile**
```
github "nextgis/ios_maplib"
```

**Carthage Output**
```
Parse error: unexpected dependency type in line: {\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf400
```

**Actual outcome**
Carthage did nothing

**Expected outcome**
I was expecting Carthage to install Cocoa dependency from the project

**Comment by ikesyo** [comment]
Looks like your `Cartfile` is not a plain text file but RTF file. Please save the file as plain text format.
