### ISSUE TITLE
Linking cross-platform frameworks

### ISSUE THREAD

**Issue by mpangburn** [Carthage/Carthage#2565]
Goal:
- A general-purpose Swift framework with one target supporting multiple platforms
- A second general-purpose Swift framework with one target supporting (the same set of) multiple platforms, with the first framework as a dependency

Running `carthage build` appropriately creates the platform-specific versions of the first framework, but I'm unsure as to the best way to link them to the second. Is there a way to go about linking the first framework without separating out targets for each individual platform in the second framework?

Would appreciate any suggestions.

**Comment by blender** [comment]
> A general-purpose Swift framework with one target supporting multiple platforms

If it's general purpose then you should not need to have platform specific targets in the second framework.

Personal note:
I personally very much dislike project set up with one all-platforms target because it adds a ton of complexity for everyone involved.

**Comment by mpangburn** [comment]
Since the framework is platform-agnostic I don't see a reason to separate out multiple targets.
My confusion comes from trying to link the appropriate binaries; if Xcode builds the target for a specific platform, then my challenge is in linking the binary to the second platform-agnostic framework.

**Comment by mpangburn** [comment]
Resolved by following [the steps in this article](https://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/). Closing.
