### ISSUE TITLE
Can we have an option to skip the 32 bit builds and have 64 bit only?

### ISSUE THREAD

**Issue by chrishulbert** [Carthage/Carthage#2566]
Currently from what i can tell, Carthage makes a fat framework which includes 386, x86_64, arm, and arm64.

Since iOS no longer supports 32-bit apps, it seems there are some speed gains to be had to only supporting 64 bit builds, might make the updates, builds, copy-frameworks, git commits etc faster.

Would you consider such an option?
And if so, could it be in the cartfile so i dont have to remind everyone in the team to specify it on the command line? 

Thanks for making a fantastic package manager 😄

**Comment by blender** [comment]
I'm pretty sure we don't want to make modifications to the Cartfile.

I might be wrong but I think the architecture that Carthage builds for are specified by your project file, not hardcoded in the Carthage's code.

You can remove armv6, armv7, armv7s if you don't want 32 bit support. However I think this will be done by Apple themselves changing the value of `ARCHS_STANDARD`.

What version of Xcode are you using?

**Comment by chrishulbert** [comment]
Thanks for replying :)

I'm totally happy if this is a command-line vs Cartfile change - the latter is a 'nice to have'.
If the architectures built are defined by my project file, i'll check to see it's not including 32-bit. But i'd be surprised if it did given that i'm on the latest Xcode with a freshly-created project and targeting iOS11.
I'm using Xcode 9.4.1.
I can see from your attached image that iOS10 was the last to support 32-bit. Neat chart!
