### ISSUE TITLE
Xcode 10 Cannot build deployment target < iOS 12

### ISSUE THREAD

**Issue by mxcl** [Carthage/Carthage#2570]
* carthage install method: [ ] .pkg, [x] homebrew (duh), [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: 0.30.1
* `xcodebuild -version`: Xcode 10.0 Build version 10L232m
* Are you using `--no-build`?   no
* Are you using `--no-use-binaries`?    no
* Are you using `--use-submodules`?    no
* Are you using `--cache-builds`?    no
* Are you using `--new-resolver`?    no

**Cartfile**
```
github "mxcl/PromiseKit" ~> 6.3.4
```

**Carthage Output**
```
$ carthage bootstrap --platform iOS
*** Checking out PromiseKit at "6.4.0"
*** xcodebuild output can be found in /var/folders/w8/kbmjvx4d60d_dct7h4b18csc0000gn/T/carthage-xcodebuild.ezQ4BZ.log
*** Building scheme "PromiseKit" in PromiseKit.xcodeproj
```

**REPORT**

I have my deployment target set to iOS 11.4 but seemingly (Xcode 10 thinks so at least) that it PromiseKit is built with iOS 12.

**Comment by mxcl** [comment]
<img width="1392" alt="screen shot 2018-09-07 at 6 36 59 pm" src="https://user-images.githubusercontent.com/58962/45246028-06632200-b2cd-11e8-86ca-b71e3b50800c.png">

**Comment by mxcl** [comment]
I have cleaned everything (derived data, Carthage checkout and build) and rebuilt, but it stays the same.

This project *was* 12 only, but I changed it (then cleaned, then re-`carthage bootstrap`‘d) and tried again and again, just in case. It seems to only build iOS 12 deployment target for PromiseKit. I have no other deps as shown above.

Anyway, I know Xcode 10 isn't GM yet, but almost certainly it will be next week, so figured you'd be cool with the report. Thanks.

**Comment by blender** [comment]
@mxcl can you please run `otool -l Carthage/Build/iOS/PromiseKit.framework/PromiseKit | grep LC_VERSION_MIN -A 3` and paste the output

**Comment by mxcl** [comment]
```
$ otool -l Carthage/Build/iOS/PromiseKit.framework/PromiseKit | grep LC_VERSION_MIN -A 3
      cmd LC_VERSION_MIN_IPHONEOS
  cmdsize 16
  version 8.0
      sdk 12.0
```

**Comment by mxcl** [comment]
[carthage-xcodebuild.ezQ4BZ.log](https://github.com/Carthage/Carthage/files/2363472/carthage-xcodebuild.ezQ4BZ.log)

**Comment by mxcl** [comment]
<img width="834" alt="screen shot 2018-09-09 at 12 30 37 pm" src="https://user-images.githubusercontent.com/58962/45266648-4260c900-b42c-11e8-8554-17aeba6ee03d.png">
<img width="624" alt="screen shot 2018-09-09 at 12 30 51 pm" src="https://user-images.githubusercontent.com/58962/45266649-4260c900-b42c-11e8-8002-cf0134b99091.png">
<img width="789" alt="screen shot 2018-09-09 at 12 31 07 pm" src="https://user-images.githubusercontent.com/58962/45266650-42f95f80-b42c-11e8-9664-c5d60be9cb07.png">

**Comment by blender** [comment]
Let's eliminate planet alignments by running

```
rm -rf ~/Library/Caches/carthage/ org.carthage.CarthageKit/
```

cleaning derived data (hello darkness my old friend...), and trying again.

Then, the binary that you have is (no joke) really built with min SDK 12.

Now, from the log I see that `SDKROOT` is 12.

```
    SDKROOT = iphoneos12.0
```

**Comment by blender** [comment]
@ikesyo  `IPHONEOS_DEPLOYMENT_TARGET` is 8.0 in the log. That's not something carthage touches

**Comment by ikesyo** [comment]
Yes, so that is the question as the image in https://github.com/Carthage/Carthage/issues/2570#issuecomment-419584374 says that the PromiseKit's deployment target is ios12.

**Comment by blender** [comment]
So this is the build command:

https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Xcode.swift#L664-L710

I would dump `settings` and `argsForBuilding` to see if there is anything weird going on

**Comment by blender** [comment]
I suspect the binary that gets copied is a leftover of some previous build. 

The build log clearly states that xcode is building with IPHONEOS_DEPLOYMENT_TARGET=8.0

**Comment by mxcl** [comment]
> Let's eliminate planet alignments by running
> 
>     rm -rf ~/Library/Caches/carthage
>     rm -rf ~/Library/Caches/org.carthage.CarthageKit
>
> cleaning derived data (hello darkness my old friend...), and trying again.

Sadly, running the above, then `rm -rf ~/Library/Developer/Xcode/DerivedData` and then `carthage bootstrap --platform iOS` and then rebuilding the iOS target inside Xcode leads to the same error (as above screenshot).

> Yes, so that is the question as the image in #2570 (comment) says that the PromiseKit's deployment target is ios12.

PromiseKit’s xcodeproject for v6.4.0 has a deployment target of 8.

> So this is the build command:
> 
> https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Xcode.swift#L664-L710
> 
> I would dump settings and argsForBuilding to see if there is anything weird going on

I can build my own Carthage and trigger the dumps here if that would help.

**Comment by blender** [comment]
@mxcl that would help, here is how you can get started https://github.com/Carthage/Carthage/blob/master/CONTRIBUTING.md#get-started

**Comment by mxcl** [comment]
K solved, I had another `.xcodeproj` in the root directory that I run `carthage` from and this was auto-generated from SwiftPM (which assigns the deployment target to 12).

This was apparently being used by Carthage to determine the deployment target for PromiseKit.

Would you accept a patch where it outputs which project Carthage has chosen to build against, since I believe this would be useful information for other people that end up in my situation.

**Comment by mxcl** [comment]
FYI The reason it seemed ok with Xcode 9 is because the maximum deployment target for Xcode 9 is 11.4, which was what I was trying to target.

**Comment by mdiep** [comment]
> Would you accept a patch where it outputs which project Carthage has chosen to build against, since I believe this would be useful debugging information for other people that end up in my situation.

That seems like a good idea. 👍 You're thinking of editing the existing `Building scheme "Foo" in Foo.xcodeproj` to include the path?

**Comment by mxcl** [comment]
> That seems like a good idea. 👍 You're thinking of editing the existing Building scheme "Foo" in Foo.xcodeproj message to include the path?

Well in this case that wasn't the problem, because it says building `PromiseKit blah`, the problem was it was building against the settings in `debris.xcodeproj` rather than `Canopy.xcodeproj`, which was unexpected on my part, but understandable since Carthage chooses the xcodeproj to use by itself.

I think my patch would be for situations where there are multiple choices for the xcodeproj that is meant to *receive* the dependencies being built to output the fact it chose one and which one it was.

This was people like myself would realize it was targeting the wrong xcodeproj and could do something to mitigate it.
