### ISSUE TITLE
Moya - dependency cycle weird behaviour 

### ISSUE THREAD

**Issue by wassimseif** [Carthage/Carthage#2576]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.30.1
* `xcodebuild -version`: Xcode 10.0. Build version 10A254a
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? Yes

**Cartfile**
```
github "Hearst-DD/ObjectMapper" ~> 3.0

github "Moya/Moya"

github "SVProgressHUD/SVProgressHUD"

github "flipboard/FLEX" ~> 2.0

github "rs/SDWebImage"

```

**Carthage Output**
```
*** Cloning Moya
*** Cloning SVProgressHUD
*** Cloning ObjectMapper
*** Cloning SDWebImage
*** Cloning FLEX
*** Checking out FLEX at "2.4.0"
*** Checking out SDWebImage at "4.4.2"
*** Checking out ObjectMapper at "3.3.0"
*** Checking out SVProgressHUD at "2.2.5"
*** Checking out Moya at "11.0.2"
*** xcodebuild output can be found in /var/folders/38/fytrk84151jfgntn774nrpzw0000gn/T/carthage-xcodebuild.WmDgx7.log
The dependency graph contained a cycle:
FLEX:
SDWebImage:
ObjectMapper:
SVProgressHUD:
Moya: RxSwift, Alamofire, ReactiveSwift, Result

```

**Expected outcome**
Carthage should succeed

The weird thing is the exact Cartfile is working on another mac with similar config ( Xcode 10 GM, Carthage 0.30.1)

**Comment by wassimseif** [comment]
I created a new directory with Cartfile 

```
github "Moya/Moya"
```
I got this error 

```
*** Fetching Moya
*** Checking out Moya at "11.0.2"
*** xcodebuild output can be found in /var/folders/38/fytrk84151jfgntn774nrpzw0000gn/T/carthage-xcodebuild.mCvWM2.log
The dependency graph contained a cycle:
Moya: RxSwift, Alamofire, ReactiveSwift, Result

```

**Comment by wassimseif** [comment]
After some investigation , I noticed that the `Cartfile` in `Moya` contains `github "antitypical/Result" ~> 3.1` while in `ReactiveSwift` the `Cartfile` contains `github "antitypical/Result" ~> 4.0` & ReactiveSwift is in the `Cartfile` of Moya, Can this be the issue ?

**Comment by blender** [comment]
Please pin the version of  Moya to `~> 11.0.2`

This is Moya's 11.0.2 Cartfile: https://github.com/Moya/Moya/blob/65a726a64cd2f15ea3859da24accc25e6ef2ea9c/Cartfile.resolved

This is ReactiveSwift's 3.1.0 Cartfile:  https://github.com/ReactiveCocoa/ReactiveSwift/blob/46fb4d4a8285286e54929add1d12f384675895c6/Cartfile.resolved

Result is at 3.2.4 in both so it should not be a problem

**Comment by blender** [comment]
Moya builds correctly on CI, https://travis-ci.org/blender/Amphorae/jobs/427911099

https://github.com/blender/Amphorae/blob/master/Amphorae/M/Moya/Moya.bats

**Comment by wassimseif** [comment]
it worked but without this limit, Carthage did use Moya 11.0.2 ( saw it in the Cartfile.resolved), do you know what's the difference?

**Comment by blender** [comment]
It's probably picking up some weird tag
