### ISSUE TITLE
Is it a good idea to add Carthage/Build/[Platform] to the repo?

### ISSUE THREAD

**Issue by shehabic-work** [Carthage/Carthage#2579]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: 
* `carthage version`: 0.30.1
* `xcodebuild -version`: 
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes
* Are you using `--new-resolver`? no

**Cartfile**
```
github "ArtSabintsev/Siren" == 2.0.8
github "xmartlabs/XLPagerTabStrip" == 7.0
github "SiftScience/sift-ios" == 0.9.11
github "BranchMetrics/ios-branch-deep-linking" == 0.12.6
github "jdg/MBProgressHUD" == 0.9.2
github "iziz/libPhoneNumber-iOS" == 0.8.7
github "button/DeepLinkKit" == 1.4.0
github "soffes/SAMKeychain" == 1.5.3
github "launchdarkly/ios-client" == 2.10.1
github "Swinject/Swinject" == 2.4.0
```

**Carthage Output**

```
<OUTPUT>
```

**Actual outcome**
Is it a good idea to add Carthage/Build/[Platform] to the repo?
Our team at work, decided to add it such that when you quickly switch between branches the rebuild process doesn't take long time) cause we often update versions of dependencies, and only the owner takes care of building, then commits the built version to the repo.

**Expected outcome**
Is it a good idea to add Carthage/Build/[Platform] to the repo?
Our team at work, decided to add it such that when you quickly switch between branches the rebuild process doesn't take long time) cause we often update versions of dependencies, and only the owner takes care of building, then commits the built version to the repo.

**Comment by blender** [comment]
It's not recommended, but in the end it's your choice.

You can use this for the same purpose but without committing anything to your repo. https://github.com/blender/Rome

Works only locally too.
