### ISSUE TITLE
Skip `carthage build --no-skip-current` when archiving?

### ISSUE THREAD

**Issue by olejnjak** [Carthage/Carthage#2584]
Hi, 

I've run into an issue with my library on Travis CI. I use Travis to build the library and if new tag is pushed, then create a binary archive and upload it back to Github.

Problem is that public jobs are limited to run 50 minutes at most. The build script on Travis looks something like this
1. `carthage bootstrap --cache-builds`
2. build project
3. `carthage build --no-skip-current`
4. `carthage archive`
5. upload to Github

We use some dependencies whose build takes a long time so compiling them takes like 45 minutes on Travis.

Solution which I came up with would be to update the script to do this
1. `carthage bootstrap --no-build`
2. `carthage build --no-skip-current`
3. build project
4. `carthage archive`
5. upload to Github

But here I lose the caching feature as the dependencies will be always built thanks to `--no-skip-current`. Is there any solution to speed up the archive process? 

This is my [_travis.yml_](https://github.com/AckeeCZ/ACKReactiveExtensions/blob/master/.travis.yml).

Thanks a lot.

* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.30.1
* `xcodebuild -version`: Xcode 10.0 Build version 10A255
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? Yes

**Cartfile**
```
github "rs/SDWebImage" ~> 4.0
github "ReactiveCocoa/ReactiveCocoa" ~> 8.0
github "realm/realm-cocoa" ~> 3.0
github "utahiosmac/Marshal" ~> 1.2
github "thoughtbot/Argo" ~> 4.1
github "ashleymills/Reachability.swift" ~> 4.1
github "Alamofire/AlamofireImage" ~> 3.3
```

**Actual outcome**
Carthage did rebuild or dependencies even though they were previously built.

**Expected outcome**
Carthage would use binaries previously built by bootstrap

**Comment by blender** [comment]
`carthage build --no-skip-current` should use your .version files from the restored cache directory provided it's restored correctly.

Also I'm not sure I understand the full picture. You have a library there and you `archive` it via carthage AND build if directly with xcode?  

If you're uploading the binary from the archive why are you building it again?

**Comment by olejnjak** [comment]
Well I've been playing with the arguments of `carthage build` and I don't know why I thought that `--no-skip-current` and `--cache-builds` are exclusive, running them together does what I want 🙂
