### ISSUE TITLE
After moving from Cocoapods to Carthage, build fails

### ISSUE THREAD

**Issue by audungk** [Carthage/Carthage#2587]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.30.1
* `xcodebuild -version`: Xcode 10.0
Build version 10A255
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "airbnb/lottie-ios" "master"
github "iziz/libPhoneNumber-iOS"
github "Square/Valet"
github "datatheorem/TrustKit" "master"
github "onevcat/Kingfisher" ~> 4.0
github "Alamofire/Alamofire"
github "iwasrobbed/Down" "master"
```

**Carthage Output**
```
SpaceBook:redacted-ios audungk$ carthage bootstrap --platform ios
*** Checking out TrustKit at "86fca2f0e925a930fbe3785a7c6162c462efad3a"
*** Checking out lottie-ios at "21122a769ccc3e43ffd23f80b7c8c48247834900"
*** Checking out Kingfisher at "4.10.0"
*** Checking out Down at "267d8e7e10648d95649e316404877ab42b3435d0"
*** Checking out Alamofire at "4.7.3"
*** Checking out libPhoneNumber-iOS at "0.9.13"
*** Checking out Valet at "3.1.6"
*** xcodebuild output can be found in /var/folders/hm/ty1qdmps3qz9h4ln82dwyl7m0000gn/T/carthage-xcodebuild.yLk4LK.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Down" in Down.xcodeproj
*** Building scheme "Kingfisher" in Kingfisher.xcworkspace
*** Building scheme "libPhoneNumberiOS" in libPhoneNumber.xcodeproj
*** Building scheme "Lottie" in Lottie.xcodeproj
*** Building scheme "TrustKit" in TrustKit.xcodeproj
*** Building scheme "Valet iOS" in Valet.xcodeproj

```

I don't know if this is related to Carthage or not, but it happens after migrating to Carthage, so I hope it is OK to ask the question here:

After moving to Carthage, and resolving all errors related to framework-updates etc. building the app fails with this error message:

```
<unknown>:0: error: 'init' is inaccessible due to 'private' protection level
<unknown>:0: note: 'init' declared here
<unknown>:0: note: 'init' declared here
<unknown>:0: note: 'init' declared here

Command CompileSwift failed with a nonzero exit code

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(3 failures)
```
 I cannot navigate to where init is declared, and the error occurs even in files without init. I have tried to set up a blank project with all the dependencies in it, and it builds fine, so I'm a little lost in regards to what this error actually is. 

I fully understand that this issue might be closed for irrelevancy, as it has nothing to do with Carthage itself, but since it happens after moving to Carthage, I was hoping it might be someone here who had experienced a similar error

**Comment by blender** [comment]
Pin the versions and try again. I see a lot of "master".

This is bad practice.

**Comment by blender** [comment]
Also, disable whole module optimization and enable per file in your app.

**Comment by audungk** [comment]
Thanks for the input!

I'm rebuilding this with -Onone, and Incremental compilation mode, and it still fails. Two of the dependencies fails to build pinned to the latest version, so these are set to master. 

In the project with no code, only dependencies everything works, but in this project it still says 'init' is inaccessible due to 'private' protection level on 24 files (even some without `init` in them)

**Comment by audungk** [comment]
YES! Removing one of the pods building not building from `master` solved this. Thanks again for letting me ask the question, but I guess switching from Valet to something else will sort this out. I don't know the error yet, but at least I know what causes it!

Thank you!

**Comment by dfed** [comment]
@audungk I know it's a little late, but I think I know what caused your compiler issue. See https://github.com/square/Valet/issues/162 for more details.
