### ISSUE TITLE
xcfilelist with input/output files

### ISSUE THREAD

**Issue by artemnovichkov** [Carthage/Carthage#2589]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.30.1
* `xcodebuild -version`: Xcode 10.0 Build version 10A255
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "Otbivnoe/Framezilla"
github "Alamofire/Alamofire"
```

**Actual outcome**
I use xcfilelists with required paths [Archive.zip](https://github.com/Carthage/Carthage/files/2408793/Archive.zip)
```
#inputs
$(SRCROOT)/Carthage/Build/iOS/Alamofire.framework
$(SRCROOT)/Carthage/Build/iOS/Framezilla.framework

#outputs
$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Alamofire.framework
$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Framezilla.framework
```
Here is Build Phase:
![screen shot 2018-09-23 at 20 30 52](https://user-images.githubusercontent.com/5051597/45929161-9a8ce480-bf6f-11e8-9d35-d5be8a4df2ed.png)
I still have this issue:
```
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /Users/artemnovichkov/Library/Developer/CoreSimulator/Devices/A47052F1-365A-49E1-BEC9-CA5B61327ABD/data/Containers/Bundle/Application/19725F46-601C-4460-B956-ED97DEDFD050/Tea.app/Tea
  Reason: image not found
```

**Comment by ikesyo** [comment]
Thanks for filing an issue, this is actually needed for #2477.
