### ISSUE TITLE
Carthage Homebrew formula outdated

### ISSUE THREAD

**Issue by basememara** [Carthage/Carthage#2592]
Please update `brew` to the latest `0.31.0` tag:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/carthage.rb

**Comment by blender** [comment]
Thanks for reporting, we're working on it.

It's easier said than done.

https://github.com/Homebrew/homebrew-core/pull/32403

**Comment by JacobJT** [comment]
Is this why when I run carthage commands it tells me to upgrade to 0.31.0, but when I run `brew upgrade carthage` it says `carthage 0.30.1 already installed`?

**Comment by jdhealy** [comment]
0.30.1 is published to Homebrew, but its successor 0.31.0 has not yet been merged into homebrew-core (see above).

**Comment by Nonnus** [comment]
while updating using `homebrew` is not working, is it ok to just download the binary installer and then "go back" to using brew version, are they interchangeable and installed on same location on the machine?

**Comment by basememara** [comment]
..looks like I had to also `rm '/usr/local/bin/carthage'`, then `brew uninstall carthage`.

**Comment by jdhealy** [comment]
@basememara, you can `brew upgrade https://raw.githubusercontent.com/Carthage/homebrew-core/9bb9251143640cdd49153a6cf3528d640cb3941d/Formula/carthage.rb` (provided you still have `xcode-select`ed Xcode 10) which will build from source, output `brew`’s `Error: Failed changing dylib ID`, and exit with code 1 — but, still leave you with a working carthage executable in Homebrew. 

Despite the message `The formula built, but you may encounter issues using it or linking other formula against it.`, from what we’ve established in https://github.com/Homebrew/homebrew-core/pull/32403 (and some local testing) you shouldn’t encounter any issue using it.

To remove the files installed via the installer through make install, you can download https://github.com/Carthage/Carthage/releases/download/0.31.0/Carthage.pkg, open it in Installer.app, and hit ⌘I to see which files it installs.

**Comment by ikesyo** [comment]
https://github.com/Homebrew/homebrew-core/pull/32544 has been merged.
