### ISSUE TITLE
Carthage installation with installer gives dyld: Symbol not found error 

### ISSUE THREAD

**Issue by tarangpatel** [Carthage/Carthage#2596]
* carthage install method: [x ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.0
* `xcodebuild -version`: Xcode 10.0 Build version 10A255
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

Installing the latest 0.31.0 package of Carthage is not working.

**Actual outcome**
`carthage version` should give the current version installed but it gives 

`dyld: Symbol not found: __T0s19_emptyStringStorages6UInt32Vv
  Referenced from: /usr/local/bin/../Frameworks/libswiftos.dylib
  Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/libswiftCore.dylib
 in /usr/local/bin/../Frameworks/libswiftos.dylib
Abort trap: 6`

**Expected outcome**
Carthage should give the proper version number 0.31.0

**Comment by mdiep** [comment]
Have you previously installed Carthage via homebrew? Usually this happens when `carthage` is picking up incompatible versions of its frameworks from different installations.

**Comment by mdiep** [comment]
Try removing `/Library/Frameworks/CarthageKit.framework` and installing from the `pkg` again.

**Comment by tarangpatel** [comment]
I tried that too. But still the same error.

**Comment by tarangpatel** [comment]
I am not sure why this happened. But when i did `brew install carthage` i was able to install 0.31.0 version now. So its working fine with Homebrew.
