### ISSUE TITLE
"dyld: Symbol not found" in runtime

### ISSUE THREAD

**Issue by webim** [Carthage/Carthage#2603]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: `0.31.0`
* `xcodebuild -version`: Xcode 10.0 Build version 10A255
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "webim/webim-client-sdk-ios"
```

Output in runtime. This error was detected with Xcode 10 and occurs when WebimClientLibrary tries to use SQLite methods.
```
dyld: lazy symbol binding failed: Symbol not found: _$S6SQLite10ConnectionC_8readonlyACSS_SbtKcfcfA0_
  Referenced from: /Users/user/Library/Developer/CoreSimulator/Devices/3BDCB401-57BB-45EC-AC95-CEDCBDCDD167/data/Containers/Bundle/Application/2EFFD61F-740E-41D4-84AA-86BE1DC58C0F/TestApp.app/Frameworks/WebimClientLibrary.framework/WebimClientLibrary
  Expected in: /Users/user/Library/Developer/CoreSimulator/Devices/3BDCB401-57BB-45EC-AC95-CEDCBDCDD167/data/Containers/Bundle/Application/2EFFD61F-740E-41D4-84AA-86BE1DC58C0F/TestApp.app/Frameworks/SQLite.framework/SQLite

dyld: Symbol not found: _$S6SQLite10ConnectionC_8readonlyACSS_SbtKcfcfA0_
  Referenced from: /Users/user/Library/Developer/CoreSimulator/Devices/3BDCB401-57BB-45EC-AC95-CEDCBDCDD167/data/Containers/Bundle/Application/2EFFD61F-740E-41D4-84AA-86BE1DC58C0F/TestApp.app/Frameworks/WebimClientLibrary.framework/WebimClientLibrary
  Expected in: /Users/user/Library/Developer/CoreSimulator/Devices/3BDCB401-57BB-45EC-AC95-CEDCBDCDD167/data/Containers/Bundle/Application/2EFFD61F-740E-41D4-84AA-86BE1DC58C0F/TestApp.app/Frameworks/SQLite.framework/SQLite
```

**Comment by blender** [comment]
This is problem with the library, not carthage. Please report there.

**Comment by blender** [comment]
FYI the name of the method you want to make sure exists in the SQLite is an init

```
SQLite.Connection first-element-marker default argument 1 of readonly.init(Swift.String, Swift.Bool) throws -> SQLite.Connection
```

https://github.com/stephencelis/SQLite.swift/blob/master/Sources/SQLite/Core/Connection.swift#L125

Could it be you're linking the Objective C version instead of the swift one?

**Comment by webim** [comment]
I'm using SQLite in my library and for demonstration of it's work we have "Example" folder in project directory. Its existance causes in Carthage build with an error, but without "Example" everything work's just fine.

Do you have any recommendations for my situation without deleting "Example" folder?

**Comment by webim** [comment]
Removing "Example/Pods/" solved my problem.
