### ISSUE TITLE
[Feature Request] Support for transitive dependencies in Binary only dependencies

### ISSUE THREAD

**Issue by abishek3876** [Carthage/Carthage#2609]
Currently there is no way to specify transitive dependencies on a binary-only carthage dependency. Ideally, binary only dependencies should have complete feature parity with other kinds of dependencies and there should be a way to provide transitive dependencies similar to the others.

**Actual outcome**
There's no way to provide transitive dependencies for binary frameworks.

**Expected outcome**
There should be a way to provide the transitive dependencies for binary dependencies as well.

**Comment by ikesyo** [comment]
Duplicate of #1937.
