### ISSUE TITLE
External Framework

### ISSUE THREAD

**Issue by aabanaag** [Carthage/Carthage#2610]
Hi, this is more of a question really. I have a framework that I use within my app. I would like to have it under Carthage so that I won't have to integrate it manually. The framework does not belong to me actually it is from Brother (_Brother Print SDK_). I've been trying to create a **cocoa-touch-framework** the having the .framework under _link binaries and framework_ but when I try to use i within a project it says **Could not build Objective-C module**. Is it possible to wrap a pre-built framework? Not really sure if its a dynamic or static framework. 

Also is there a slack channel or gitter account for Carthage so questions like this ends up there instead of an issue? Thanks!

**Comment by aabanaag** [comment]
Thanks, but I'm not really sure on how to proceed. I only have access to the .framework file not the actual code itself. Do I have to create cocoa touch framework in order to perform carthage archive projectName?

**Comment by mdiep** [comment]
If you don't have access to the code, then you don't need to use `carthage archive`. You need to create a zip/gz file and a JSON file.

**Comment by blender** [comment]
No structure

**Comment by aabanaag** [comment]
Hi, I now this is already closed but I followed the instructions above. Created a folder {framework} added the .framework file then compressed the folder to create framework.zip which was then uploaded to our google storage. I created a json file with the structure of `{ "3.1.9": "url" }`(3.1.9 was the version of the framework I used) then hosted the json file onto github pages. But I encountered an error running `carthage update --platform iOS`

```
 shell task (/usr/bin/env unzip -uo -qq -d /var/folders/p9/ykn6vpg56t1_rchhdb9ld60h0000gn/T/carthage-archive.sLDGC3 /Users/jongbana
ag/Library/Caches/org.carthage.CarthageKit/binaries/BRPtouchPrinterKit/3.1.9/BRPtouchPrinterKit.zip) failed with exit code 9:
[/Users/jongbanaag/Library/Caches/org.carthage.CarthageKit/binaries/BRPtouchPrinterKit/3.1.9/BRPtouchPrinterKit.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/jongbanaag/Library/Caches/org.carthage.CarthageKit/binaries/BRPtouchPrinterKi
t/3.1.9/BRPtouchPrinterKit.zip or
        /Users/jongbanaag/Library/Caches/org.carthage.CarthageKit/binaries/BRPtouchPrinterKit/3.1.9/BRPtouchPrinterKit.zip.zip, and
cannot find /Users/jongbanaag/Library/Caches/org.carthage.CarthageKit/binaries/BRPtouchPrinterKit/3.1.9/BRPtouchPrinterKit.zip.ZIP,
period.
```

**Comment by blender** [comment]
Looks like your Zip file is corrupted.

**Comment by aabanaag** [comment]
Thanks for the reply. I checked the Caches folder and copied the .zip after opening it it creates a .cpgz file which then opens a new zip file. So I assume the file it not downloaded properly that is when I found out that the storage bucket I'm using is not open for public once I set it up for public access I was able to use `carthage update --platform iOS`with no issues.
