### ISSUE TITLE
Delivering a compiled carthage framework with sub dependencies 

### ISSUE THREAD

**Issue by piggeldi** [Carthage/Carthage#2611]
Hey,

i really love the work you are doing. We are working for about 1 year with carthage in combination with nexus repository to handle our dependencies. Everything works fine, until now. We have reached a point where i need your help. 

Our environment looks like the following: 

We have **Core** framework with subdependencies to Alamofire and Moya and so on. This subdependencies are already prebuilt and hosted by our nexus repository to increase the runtime of **carthage update**. We're integrating them with the **binary**-keyword in the Cartfile. So far so good. Everything works fine. 

Example-Cartfile of the core:
``` 
binary "https://inhouse.nexus.de/repository/ios-binaries/Dependencies/Alamofire.json" ~> 4.6
binary "https://inhouse.nexus.de/repository/ios-binaries/Dependencies/AlamofireImage.json" ~> 3.3
binary "https://inhouse.nexus.de/repository/ios-binaries/Dependencies/Moya.json" ~> 10.0
binary "https://inhouse.nexus.de/repository/ios-binaries/Dependencies/Result.json" ~> 3.2.4 
```

The **Core** in turn gets integrated by several other apps by inhouse developers which have **access** to the source code of the **Core** framework. So nesting frameworks works totally fine, when we reference the **Core**-Framework with the **git**-keyword command in the Cartfile (we have a enterprise gitlab instance running). 

Example-Cartfile of integrating the core:
``` 
git "https://inhouse.gitlab.de/repository/core" ~> 4.6 
```

Now we would like to ship the core to external developers with carthage aswell, but without access to the **Core-Framework** source code. So we want to ship the **Core** compiled as a dynamic framework (carthage archive). But by shipping the core with the **binary**-keyword leads to that subdependencies doesnt get integrated (Alamofire and so on). 

I could of course write all dependencies from the core into the Cartfile for the external developers, but the dependencies in the **Core** could change. And this would mean any external developer would have to manually customize the Cartfile, when the **Core** deletes or add new subframeworks.

I dont want use a umbrella frameworks for this. 

Is there already a solution for this? 

Thank you for your help!

Kind regards, 

piggeldi

**Comment by mdiep** [comment]
There's not currently a way to specify dependencies like this—your users will need to specify all the frameworks. (See #1937.)

**Comment by piggeldi** [comment]
Ok thank you for the info!
