### ISSUE TITLE
Dependencies from different forks

### ISSUE THREAD

**Issue by CosynPa** [Carthage/Carthage#2616]
* carthage install method: [] .pkg, [*] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.1
* `xcodebuild -version`: Xcode 10.0 Build version 10A255
* Are you using `--no-build`? Yes
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "ReactiveCocoa/ReactiveSwift" # This repository depends on antitypical/Result
github "CosynPa/Result" # This is just a dummy repository 
```

**Carthage Output**
```
*** Fetching Result
*** Fetching ReactiveSwift
*** Fetching Result
*** Checking out Result at "4.0.0"
*** Checking out ReactiveSwift at "4.0.0"
*** Checking out Result at "0.0.1"
A shell task (/usr/bin/env git checkout --quiet --force 4.0.0 (launched in /Users/xxx/Library/Caches/org.carthage.CarthageKit/dependencies/Result)) failed with exit code 128:
fatal: Unable to create '/Users/xxx/Library/Caches/org.carthage.CarthageKit/dependencies/Result/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

**Actual outcome**
A fatal error

Cartfile.resolved is
```
github "CosynPa/Result" "0.0.1"
github "ReactiveCocoa/ReactiveSwift" "4.0.0"
github "antitypical/Result" "4.0.0"
```

**Expected outcome**
Carthage should report an error when resolving dependencies, or resolve to a single Result repository.

Although the Cartfile shown above is a contrived one, using a different fork from the standard one is somewhat common practice as in #1987. The dependency resolver should find a compatible version in one fork or report an error if that is impossible. Currently, Carthage resolves out two repositories, but since they have the same name, Carthage tries to check out the same cached repository to 0.0.1 and 4.0.0 simultaneously, that's why a race condition occurs.

**Comment by blender** [comment]
Thanks for opening an issue.

This is well known as repositories are not namespaced by organization or owner.
