### ISSUE TITLE
"Could not find available simulators for ..." - Xcode  10.1 Beta 3 build 10O45e

### ISSUE THREAD

**Issue by RustyKnight** [Carthage/Carthage#2620]
* carthage install method: [X ] .pkg, [ ] homebrew, [ X] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.1
* `xcodebuild -version`: Xcode 10.1 Build version 10O45e
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`?  No
* Are you using `--new-resolver`? No

**Cartfile**
NA - building archive from library which does not contain any dependencies

**Carthage Output**
```
> carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/dw/9cj1xs2n46193dypj3nxc25m0000gn/T/carthage-xcodebuild.wBTZsn.log
*** Building scheme "Hydra-macOS" in Hydra.xcodeproj
*** Building scheme "Hydra-iOS" in Hydra.xcodeproj
Could not find any available simulators for iOS
```

**Actual outcome**
Carthage failed to generate build assets

**Expected outcome**
Carthage should complete building build assets, so they can be archived

**Build logs** 

[carthage-xcodebuild.wBTZsn.log](https://github.com/Carthage/Carthage/files/2498667/carthage-xcodebuild.wBTZsn.log)

Results of `xcrun simctl list devices --json`

[Simulators.txt](https://github.com/Carthage/Carthage/files/2498668/Simulators.txt)

Seems to be related to https://github.com/Carthage/Carthage/issues/2602, I was able to get that working for the previous beta (I think I had 1) by building from source, but for some reason neither building from source or downloading and installing the latest release seems to solve this reemerging issue

I've tried:

- Cycling the terminal session (after reinstalling Carthage)
- Rebooting the machine (after reinstalling Carthage)

**Comment by RustyKnight** [comment]
Okay, after dumping a bunch of `print`s into the code, I have discovered, I have no simulators installed for iOS 12.1 :/

```
    "iOS 12.1" : [

    ],
```

Not sure why this is, but it seems to be a reoccurring issue with Xcode 10. I don't know if this is an "error" per-say, but a better warning message would be helpful :)

**Comment by blender** [comment]
What kind of warning would you like to emit?

**Comment by blender** [comment]
Sounds good. Do you want to give it a shot @rustyknight since you already done some ground work?

**Comment by blender** [comment]
Sounds good to me. Do you want to give it a shot @rustyknight
