### ISSUE TITLE
Could not find any available simulators for iOS (this is not a dup of #2602 or #2620).

### ISSUE THREAD

**Issue by rudedogdhc** [Carthage/Carthage#2629]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.1
* `xcodebuild -version`: Xcode 10.1 / Build version 10B61
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "google/promises" ~> 1.0
github "antitypical/Result" ~> 4.0
github "CocoaLumberjack/CocoaLumberjack" ~> 3.0
```

**Carthage Output**
```
$ carthage build --platform iOS --no-skip-current
*** xcodebuild output can be found in /var/folders/lq/yvbxlp_j64xfh9km1md802x00000gn/T/carthage-xcodebuild.87xgrq.log
*** Building scheme "CocoaLumberjack-iOS" in Lumberjack.xcworkspace
Could not find any available simulators for iOS
```

**Actual outcome**
Carthage refused to build the frameworks.

**Expected outcome**
Carthage should have built the frameworks.

It appears that the fix for #2602 (which worked for Xcode 10.1 Betas) is not working for Xcode 10.1 Release. To recap, 

 * Xcode 10.0 and previous used a field `"availability": "(available)"`
 * Xcode 10.1 betas used a field `"isAvailable": "YES"`
 * Xcode 10.1 release is now using `"isAvailable": true` *and* it has added the `"availability": "(available)"` field back in.

**Comment by blender** [comment]
https://github.com/Carthage/Carthage/pull/2630
and
https://github.com/Carthage/Carthage/pull/2631

**Comment by blender** [comment]
[Carthage 0.31.2 fixes this issue](https://github.com/Carthage/Carthage/releases/tag/0.31.2)

**Comment by skyfouk** [comment]
Thx👍
