### ISSUE TITLE
`carthage build` creates absolute symlink from dependency to main Carthage/Build directory

### ISSUE THREAD

**Issue by rastersize** [Carthage/Carthage#263]
Running `carthage build` after checking out the dependencies results in a symlink with an absolute path from the dependencies’ `Carthage/Build` directory to the project’s `Carthage/Build` directory.

When the checkout command is ran without the `--use-submodules` option and one checks the `Carthage/Checkouts` directory into the git repo (as suggested by the documentation) the repo can’t be shared by multiple persons.

I’m running **Carthage version 0.5.1** (installed via Homebrew).

**Example without submodules**
Given a project at the path `/User/aron/Documents/SomeApp` and a Cartfile of:
```
github "Carthage/Commandant" "master"
```
Running `carthage bootstrap`, `carthage update` or `carthage checkout` _without_ the `--use-submodules` will result in the following on disk after the `carthage build` step has been performed:
```
Carthage/Build/Mac/Commandant.framework
Carthage/Checkouts/Commandant/Carthage/Build -> /Users/aron/Documents/SomeApp/Carthage/Build
```

That is an absolute path in the symlink which becomes problematic if the repo is shared.

----
I tried to resolve this by changing to using submodules instead by removing the checkouts and then running `carthage bootstrap --use-submodules`. This partially works. There’s no longer any need to check in the `Carthage/Build` symlink found in each dependency’s checkout directory. However each dependency’s submodule is marked as dirty by git.

**Example with submodules**
```shell
$ git clone https://github.com/Carthage/Carthage.git && cd Carthage
[…]
$ carthage bootstrap # This will check the dependencies out as submodules as they are in the .gitmodule file
*** Checking out Commandant at "2c0384bfa4d0c66ab0ebf5bc48739f9236ea2e0c"
[…]
*** Building scheme "Commandant" in Commandant.xcworkspace
[…]
$ git status -sb
## master...origin/master
 M Commandant
 M LlamaKit
 M Nimble
 M Quick
 M ReactiveCocoa
 M ReactiveTask
 M xcconfigs
$ git diff
diff --git a/Carthage/Checkouts/Commandant b/Carthage/Checkouts/Commandant
--- a/Carthage/Checkouts/Commandant
+++ b/Carthage/Checkouts/Commandant
@@ -1 +1 @@
-Subproject commit 2c0384bfa4d0c66ab0ebf5bc48739f9236ea2e0c
+Subproject commit 2c0384bfa4d0c66ab0ebf5bc48739f9236ea2e0c-dirty
[…]
$ cd Carthage/Checkouts/Commandant && git status -sb
## HEAD (no branch)
?? Carthage/Build
[…]
```

Dirty forever :crying_cat_face:

**Comment by jspahrsummers** [comment]
Thanks for the great bug report! I agree this is less than ideal.

It sounds like making the symlink relative would solve the above problems. In the meantime, FWIW, I've added Carthage's Build folder to my global gitignore, which helps—although I realize that's suboptimal if you intend to commit it in your repository.

**Comment by rastersize** [comment]
Will add it to my global git ignore file. Thanks for looking and fixing the absolute symlink (tried to look at the code to fix it myself but the source kit service kept crashing so I gave up…). :star2:
