### ISSUE TITLE
Could not find any available simulators for iOS persists for Xcode 9.4.1 and 9.2

### ISSUE THREAD

**Issue by accfews** [Carthage/Carthage#2637]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`:  Xcode 9.4.1 Build version 9F2000
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes
* Are you using `--new-resolver`? no

**Cartfile**
```
github "Alamofire/Alamofire" ~> 4.7
```

**Carthage Output**
```
carthage bootstrap --platform iOS --cache-builds
*** Checking out Alamofire at "4.7.3"
*** xcodebuild output can be found in /var/folders/q3/p7qxvk_j66dc_lz5y2f7prqc0000gn/T/carthage-xcodebuild.3d2P9s.log
*** Invalid cache found for Alamofire, rebuilding with all downstream dependencies
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Could not find any available simulators for iOS
```

**Actual outcome**
Carthage couldn't build the frameworks.

**Expected outcome**
 Carthage should have built the frameworks.

When I change the toolchain to Xcode 10.1 carthage works fine and compiles the frameworks. But for both Xcode 9.4.1 and Xcode 9.2 build fails.

When I run `xcrun simctl list devices --json` I get the attached output.

Uninstalling, reinstalling, restarting terminal session, rebooting none of them helped.

This isn't a duplicate of related issues. I already have the latest version.

[devices.txt](https://github.com/Carthage/Carthage/files/2550005/devices.txt)

**Comment by blender** [comment]
Thanks for opening an issue. 

I have 9.4.1 and I can’t reproduce.

**Comment by azav** [comment]
I have 9.4.1 and just got the same issue on a fresh install of Alamofire through Carthage.

$ `carthage update --platform ios`
*** Fetching Alamofire
*** Checking out Alamofire at "4.7.3"
*** xcodebuild output can be found in /var/folders/f5/yzv30yjn2072b9hg13329yzmt45sll/T/carthage-xcodebuild.X1m8C8.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Could not find any available simulators for iOS

[devices.json.zip](https://github.com/Carthage/Carthage/files/2579886/devices.json.zip)
[carthage-xcodebuild.X1m8C8.log](https://github.com/Carthage/Carthage/files/2579895/carthage-xcodebuild.X1m8C8.log)

**Comment by blender** [comment]
Alamofire is building perfectly fine on 9.2 https://travis-ci.org/blender/Amphorae/jobs/455245368#L1394

**Comment by accfews** [comment]
I almost deleted everything and reinstalled, issue seems fixed.
