### ISSUE TITLE
Carthage with custom framework on physical device

### ISSUE THREAD

**Issue by doronkatz** [Carthage/Carthage#2638]
* carthage install method: [ ] .pkg, [X ] homebrew, [ ] source
* `which carthage`:
* `carthage version`:  0.31.2
* `xcodebuild -version`:  10.1
* Are you using `--no-build`?  N
* Are you using `--no-use-binaries`? N
* Are you using `--use-submodules`? N
* Are you using `--cache-builds`?  N
* Are you using `--new-resolver`?  N

**Cartfile**
```
github "autonomic-ai/AUKisiSDK"
github "chaione/Cely" ~> 2.0.3
github "Orderella/PopupDialog" ~> 0.9
github "KyoheiG3/DynamicBlurView"
```

**Carthage Output**
```
*** Checking out Alamofire at "a8a2827f5c14c9168a0373e948e963d36edfdbc5"
*** Checking out DynamicBlurView at "3.0.1"
*** Checking out SwiftDate at "5.0.13"
*** Checking out Cely at "2.0.3"
*** Checking out Hippolyte at "0.4.0"
*** Checking out AUKisiSDK at "releases/v0.0.6"
*** Checking out PopupDialog at "0.9.1"
```

**Actual outcome**
Everything builds correctly, and runs within simulator. `"autonomic-ai/AUKisiSDK` is a private framework I created and works fine within simulator, however when running via Xcode on device, I get a compiler error. 

Currently, my Build Phase should have the correct settings, including run-script that with input and output files. I have not added my framework as an embedded framework.

<img width="850" alt="screen shot 2018-11-07 at 12 08 00 pm" src="https://user-images.githubusercontent.com/345255/48157901-cfd26500-e285-11e8-9c3b-8b783e21f8cb.png">
<img width="843" alt="screen shot 2018-11-07 at 12 08 30 pm" src="https://user-images.githubusercontent.com/345255/48157922-da8cfa00-e285-11e8-829b-8a61ea76c5ba.png">

The Cartfile of my custom framework is as follows:
```
github "Alamofire/Alamofire" "alamofire5"
github "malcommac/SwiftDate" ~> 5.0
github "doronkatz/Hippolyte"
```

The framework has its target shared as well. When building with target being physical device, the following screenshot illustrates the compiler errors:

<img width="799" alt="screen shot 2018-11-07 at 12 07 16 pm" src="https://user-images.githubusercontent.com/345255/48157878-bdf0c200-e285-11e8-89cf-f876a4c1ccec.png">

**Expected outcome**
To build and run without compilation errors on Xcode, for either simulator or connected device.

**Comment by blender** [comment]
Hi, 
I suspect something is off with your frameworks. At a first glance your setup looks correct.

Please run `file <path/to/the/problematic/framework>` and paste the output here

**Comment by doronkatz** [comment]
Sure thing:
```
12:38 $ file Carthage/Build/iOS/AuKisi.framework/AuKisi
Carthage/Build/iOS/AuKisi.framework/AuKisi: Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by blender** [comment]
Your Frameworks is only built for simulator.

**Comment by doronkatz** [comment]
Oh, so im new to building frameworks as well it seems. Where do you assert whether you are building for simulator or not?

**Comment by blender** [comment]
<img width="687" alt="screen shot 2018-11-07 at 21 42 54" src="https://user-images.githubusercontent.com/196761/48159853-98d86f80-e2d6-11e8-9cb9-24a0d601742e.png">

**Comment by doronkatz** [comment]
So assuming the red mark is to highlight I should confirm those, my settings are the same as yours:

<img width="768" alt="screen shot 2018-11-07 at 12 51 18 pm" src="https://user-images.githubusercontent.com/345255/48160142-ee3b5f00-e28b-11e8-8b85-0b0d4eb21c83.png">

Ill try rebuilding again and seeing if file yields a different response.

**Comment by blender** [comment]
run `carthage build --platform iOS --cache-builds <your-framework-name>`

**Comment by blender** [comment]
I forgot, In Project > Info  make sure that __Use `release` for command-line builds__ is true

**Comment by doronkatz** [comment]
oh thanks, ok well that was set to true already.... Ill try your steps above and report back;. Thanks!

<img width="1104" alt="screen shot 2018-11-07 at 1 01 33 pm" src="https://user-images.githubusercontent.com/345255/48160654-47f05900-e28d-11e8-92eb-3187a789dde6.png">

**Comment by doronkatz** [comment]
Great thanks @blender its working great. I certainly was building for Simulator and now not the case. Great!
