### ISSUE TITLE
Cathage's ShipIt crashes repeatedly more than once per second

### ISSUE THREAD

**Issue by github-12341234** [Carthage/Carthage#2639]
Cathage's ShipIt crashes repeatedly more than once per second

*** Assertion failure in __28-[RACSignal(Operations) and]_block_invoke(), /Users/sattard/projects/Squirrel.Mac/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/RACSignal+Operations.m:1280

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-and must only be used on a signal of RACTuples of NSNumbers. Instead, received: <RACTuple: 0x7f821a7266b0> (
    1,
    1
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2efb623b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff56247c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2efbbfd2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff3114f9cb -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 165
	4   ShipIt                              0x0000000211ad0e37 __28-[RACSignal(Operations) and]_block_invoke + 285
	5   ShipIt                              0x0000000211aadcb8 __29-[RACStream(Operations) map:]_block_invoke + 21
	6   ShipIt                              0x0000000211aad801 __36-[RACStream(Operations) flattenMap:]_block_invoke_2 + 27
	7  <…>

**Comment by ikesyo** [comment]
Looks like you should file an issue on https://github.com/Squirrel/Squirrel.Mac. Closing.

**Comment by ikesyo** [comment]
https://github.com/Squirrel/Squirrel.Mac/issues/233
