### ISSUE TITLE
Dependency has no shared framework schemes

### ISSUE THREAD

**Issue by marbetschar** [Carthage/Carthage#2642]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
None.
```

**Carthage Output**
```
$ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/w8/zwmgcwcn713d13s21t9wjwxm0000gp/T/carthage-xcodebuild.Zj8qgp.log
*** Skipped building TPPDF due to the error:
Dependency "TPPDF" has no shared framework schemes
```

**Xcode build output**
```
$ xcodebuild -scheme TPPDF -workspace Example/TPPDF.xcworkspace build
note: Using new build system
note: Planning build
note: Using build description from disk
....
** BUILD SUCCEEDED **
```

**Source code**
Trying to build TPPDF v1.3.0. Issue also occurs on master branch. It used to work in earlier versions of Carthage, Xcode and TPPDF. Can't figure out, what exactly the root cause is. For more details on the debugging already done, please see the [corresponding issue in the TPPDF issue tracker](https://github.com/Techprimate/TPPDF/issues/98).

**Actual outcome**
Carthage complains, that it cannot find a shared framework scheme; but from what I can tell it's there:

<img width="774" alt="bildschirmfoto 2018-11-13 um 19 55 28" src="https://user-images.githubusercontent.com/392542/48436034-193b1c80-e77e-11e8-9da3-3d65ccb59ef0.png">

**Expected outcome**
Carthage should successfully build the framework.

**Comment by blender** [comment]
The the workspace or project should be at top level I think. This is why it’s not finding it.

**Comment by marbetschar** [comment]
Fixed. The shared Scheme wasn't added to version control. For details see:
https://github.com/Techprimate/TPPDF/issues/98#issuecomment-438406256
