### ISSUE TITLE
Carthage - xcodebuild timed out while trying to read .xcodeproj

### ISSUE THREAD

**Issue by filyakov** [Carthage/Carthage#2645]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`:
* `carthage version`: 0.31.2 
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
git "onedrive@vs-ssh.visualstudio.com:v3/onedrive/Design/fabric-ios"
```

**Carthage Output**
```
Vladislavs-MacBook-Pro:officeuifabric.ios.example.cart vladf$ carthage update --platform iOS --verbose --use-ssh
*** Fetching fabric-ios
*** Checking out fabric-ios at "0.1.4"
xcodebuild timed out while trying to read OfficeUIFabric.xcodeproj 😭
```

**Actual outcome**
xcodebuild timed out while trying to read OfficeUIFabric.xcodeproj 😭

**Expected outcome**
Carthage should build my framework

**Comment by tjprescott** [comment]
@ghost did you ever figure this out? I'm having the same problem. Can't build anything with Carthage because of this.

**Comment by DavidBrunow** [comment]
@tjprescott Do you have a sample project you can share that reproduces the issue?
