### ISSUE TITLE
Carthage -carthage archive failed with time out error

### ISSUE THREAD

**Issue by sunchunqiang** [Carthage/Carthage#2646]
* carthage install method:   carthage archive
* `which carthage`: 
* `carthage version`:   0.31.2
* `xcodebuild -version`:  10.1
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`?  no
* Are you using `--new-resolver`?  no 

run "carthage archive" on circleci. 
output: xcodebuild timed out while trying to read *****.xcodeproj 😭
output of  "time xcodebuild -list" 
real	0m6.406s
user	0m5.781s
sys	0m0.321s

output of "time xcodebuild -showBuildSettings"
real	0m9.707s
user	0m9.457s
sys	0m0.377s

 

 

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```

**Actual outcome**
Carthage did or did not ...

**Expected outcome**
Carthage should ...

**Comment by mdiep** [comment]
This is because `xcodebuild` times out, which we don't have control over. 😞

**Comment by sunchunqiang** [comment]
Hi  @mdiep 
Thanks for your quick response. 
If I change the value 60 to 300 in below code, the command 'carthage archive' can finish successfully. I am wondering if carthage can parameterize the value?  I can submit a PR for the issue. 


https://github.com/Carthage/Carthage/blob/eb80ffdc5226544adb6eb20469500fd0c060359a/Source/CarthageKit/BuildSettings.swift
			.timeout(after: 60, raising: .xcodebuildTimeout(arguments.project), on: QueueScheduler(qos: .default))
			.retry(upTo: 5)
			.map { data in
				return String(data: data, encoding: .utf8)!
}

**Comment by mdiep** [comment]
👍

**Comment by nikolaeu** [comment]
+1 for timeout parameterization. Have to re-build Carthage from source with increased values for some projects. Maybe in form of `--no-timeout` launch arg. @mdiep What do you think ?

**Comment by mdiep** [comment]
I think it'd be better to not make it infinite. Maybe `--xcodebuild-timeout=1000000`?

**Comment by ismetanin** [comment]
@mdiep @nikolaeu Hi! I'd like to add `--xcodebuild-timeout` option but I can't figure out how to pass option from Build/Update to the BuildSettings. Could you help me, please?
