### ISSUE TITLE
failed with exit code 6

### ISSUE THREAD

**Issue by dhavalPithava-infostretch** [Carthage/Carthage#2647]
* carthage install method: [ ] .pkg, [true] homebrew, [ ] source
* `which carthage`:
* `carthage version`: 0.31.2
* `xcodebuild -version`: 10.0
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO
* Are you using `--new-resolver`? NO

**Cartfile**
github "SwiftyJSON/SwiftyJSON" ~> 4.0

**Carthage Output**
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/dhaval.pithava/Documents/SourceTree/OnBoarding/Dependency\ manager/Carthage\ Example/Carthage/Checkouts/SwiftyJSON/SwiftyJSON.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 6:
dyld: Library not loaded: /usr/local/lib/libwep
  Referenced from: /usr/bin/xcrun
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libwep: code signature in (/usr/local/lib/libwep) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/lib/libwep: stat() failed with errno=1

**Comment by mdiep** [comment]
> ```
> dyld: Library not loaded: /usr/local/lib/libwep
Referenced from: /usr/bin/xcrun
> ```

This suggests that your Xcode or your macOS is corrupted.
