### ISSUE TITLE
Carthage Framework in "Link Binary With Libraries" section of App or Framework?

### ISSUE THREAD

**Issue by kirou** [Carthage/Carthage#2649]
For example, I have a iOS project with 3 targets:

- MyApp (main target)
- MyAppDataLayer (Embedded Framework).
- MyAppLibrary (Embedded Framework).

MyAppDataLayer is used by MyApp, and MyAppLibrary is used by both MyApp and MyAppDataLayer

1. If I wanna use a cartage Framework like Alamofire in MyAppDataLayer, should I add Alamofire.framework file to MyApp's "Build Phases/Linked Framework and Library" section, or to MyAppDataLayer's section?

2. If I have a Framework which used by all the targets, do I have to put it in all the targets' section?

3. About the "Build Settings/Framework Search Path" section, I set all the target's Framework Search Path "$(PROJECT_DIR)/Carthage/Build/iOS", and put all the Framework in the main target MyApp. Is this correct?

**Comment by blender** [comment]
I believe the [Quick Start](https://github.com/Carthage/Carthage#quick-start) covers your question. However:

1. To all targets that use Alamofire. Both your Library and the App in this case.
2. See above
3. Sounds good

**Comment by blender** [comment]
It should be all targets since you said your framework depends on Alamofire too.

**Comment by kirou** [comment]
Okay, I got it. Thank you.
