### ISSUE TITLE
Downloading binary framework doesn't get the last version

### ISSUE THREAD

**Issue by miibpa** [Carthage/Carthage#2650]
* carthage install method: [ ] .pkg, [ x] homebrew, [ ] source
* `which carthage`:/usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`: Xcode 10.1\Build version 10B61
* Are you using `--no-build`no 
* Are you using `--no-use-binaries`no 
* Are you using `--use-submodules`no
* Are you using `--cache-builds`no
* Are you using `--new-resolver`no

**Cartfile**
```
github "Alamofire/Alamofire" ~> 4.7
binary "https://s3-eu-west-1.amazonaws.com/spitch-mobile-sdk/iOS/SpitchMobileSdk.json"
```

**Carthage Output**
```
<OUTPUT>
```

**Actual outcome**
Carthage doesn't update to last version of the binary dependency

**Expected outcome**
Carthage should download the last version of the binary dependency

I have a custom framework hosted in amazon s3, it's json definition is:
```
{
	"3.0.0": "https://s3-eu-west-1.amazonaws.com/spitch-mobile-sdk/iOS/3.0.0/SpitchMobileSdk.framework.zip",
	"3.1.0": "https://s3-eu-west-1.amazonaws.com/spitch-mobile-sdk/iOS/3.1.0/SpitchMobileSdk.framework.zip"
}
```

I my app I had the 3.0.0 version and when did `carthage update` didn't update to the 3.1.0 version. This doesn't happen if I have the SpitchMobileSdk.json referenced to a local route like this:
```
github "Alamofire/Alamofire" ~> 4.7
binary "Documents/SpitchMobileSdk.json"
```

Why is this happening?

**Comment by blender** [comment]
The version updates without problems for me.

**Comment by blender** [comment]
You probably have some network equipment caching responses between you and your S3 region.

**Comment by miibpa** [comment]
`--new-resolver` didn't work

**Comment by miibpa** [comment]
Also doing s3cmd get s3://spitch-mobile-sdk/iOS/SpitchMobileSdk.json with two different versions of the file gives me correct updated files, so I don't think that my network equipment is catching the responses.

**Comment by miibpa** [comment]
Deleting manually the folder ~/Library/Caches/carthage is what solved the issue, I don't know if this is a real issue with Carthage or this is caused by another thing related with my environment, I'm using macOs Mojave and Xcode 10.1
