### ISSUE TITLE
Should be able to configure whether build with `-project` or `-workspace`

### ISSUE THREAD

**Issue by ericwlange** [Carthage/Carthage#2653]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`: Xcode 10.1
Build version 10B61
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
git "git@github.com:LiquidPlayer/LiquidCore.git" ~> 0.5.1
```

**Carthage Output**
```
*** xcodebuild output can be found in /var/folders/mm/wgfr73595rsb70jp4mgl5frr0000gn/T/carthage-xcodebuild.4HP9UD.log
*** Building scheme "LiquidCore" in LiquidCoreiOS.xcodeproj
*** Building scheme "ReactNativeSurface" in ReactNativeSurface.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/eric/workspace/LiquidPlayer/ReactNativeSurface/ReactNativeSurface/ReactNativeSurface.xcodeproj -scheme ReactNativeSurface -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/mm/wgfr73595rsb70jp4mgl5frr0000gn/T/ReactNativeSurface SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/eric/workspace/LiquidPlayer/ReactNativeSurface/ReactNativeSurface)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/mm/wgfr73595rsb70jp4mgl5frr0000gn/T/carthage-xcodebuild.4HP9UD.log
```

**Actual outcome**
calling `carthage build --no-skip-current` from my project at https://github.com/LiquidPlayer/ReactNativeSurface.

This isn't necessarily an issue with carthage, per se.  `xcodebuild -project <project>` simply will not build the dependencies correctly.  However, `xcodebuild -workspace <workspace>` does build it correctly.

**Expected outcome**
Carthage should allow me to choose whether I want to invoke the build using the -workspace or -project, rather than only making an educated guess as to which to use.  Is there a way to configure it?  I was unable to find anything in the documentation.

**Comment by blender** [comment]
The is no way to configure this.

How do you propose this would work with the dependency tree?

**Comment by ericwlange** [comment]
I _thought_ that I had found the problem.  I had placed my `.xcworkspace` directory in a directory one up from where the `.xcodeproj` is located, rather than as peers.  Moving the directory at first seemed to fix the issue when calling `carthage build`:

```bash
Erics-MBP:ReactNativeSurface eric$ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/mm/wgfr73595rsb70jp4mgl5frr0000gn/T/carthage-xcodebuild.Mzx50H.log
*** Building scheme "LiquidCore" in LiquidCoreiOS.xcodeproj
*** Building scheme "ReactNativeSurface" in ReactNativeSurface.xcworkspace
```

Note the last line where it is using the **`xcworkspace`**, which is exactly what I want.

However, when I attempted to use the project from another location by calling `carthage udate`, it reverted to using the **project**, which fails:

```bash
Erics-MBP:ReactNativeTest eric$ carthage update
*** Fetching ReactNativeSurface
*** Fetching LiquidCore
*** Checking out LiquidCore at "0.5.1"
*** Checking out ReactNativeSurface at "0.56.0003"
*** xcodebuild output can be found in /var/folders/mm/wgfr73595rsb70jp4mgl5frr0000gn/T/carthage-xcodebuild.BJZUmq.log
*** Building scheme "LiquidCore" in LiquidCoreiOS.xcodeproj
*** Building scheme "ReactNativeSurface" in ReactNativeSurface.xcodeproj
```

Note that now the last line shows it is attempting to use the **`xcodeproj`**.

Why are these behaving differently?  The contents of `ReactNativeSurface/` in the first example and `Checkouts/ReactNativeSurface/` in the second are identical.  Shouldn't the build behavior be deterministic?

**Comment by blender** [comment]
Have you checked a project with a similar setup? Alamofire for example? https://github.com/Alamofire/Alamofire

**Comment by ericwlange** [comment]
Of all the issues, it seems that an upstream `.gitignore`was causing all files named `content.xcworkspace` to not make it into `git`.  Apparently this file is important and if it is not there, carthage ignores the workspace and uses the project instead.

Let me make sure this solves the problem completely and if so I will close this issue.

**Comment by ericwlange** [comment]
After a substantial amount of massaging, I was able to get this to work -- mostly.  Now it seems to require calling `carthage update` twice.  The first time it fails and the second time it succeeds.  This is unlikely due to anything with carthage, but rather the complex structure of repackaging React Native.  So I will close this.
