### ISSUE TITLE
How to support Carthage for Cocoapods Library

### ISSUE THREAD

**Issue by hoangtaiki** [Carthage/Carthage#2656]
I'm trying to support Carthage for my library (relevant https://github.com/hoangtaiki/PlaceholderUITextView).
My project has structure:
- Example
   - iOS Example.xcodeproj
   - iOS Example.xcworkspace
   - Podfile
- PlaceholderUITextView.xcodeproj
- Source

I marked scheme
![Imgur](https://i.imgur.com/a8sdchD.png)
![Imgur](https://i.imgur.com/WbCUhV0.png)

When I try run `carthage build --no-skip-current`. Carthage build framework from `iOS Example.xcworkspace` inside Example folder instead of `PlaceholderUITextView.xcodeproj`
```
hoangtaiki@:~/Work/ios/PlaceholderUITextView (master) $ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/r7/s3k178h91592yh4svv__g95r0000gn/T/carthage-xcodebuild.hMzzXe.log
*** Building scheme "PlaceholderUITextView" in iOS Example.xcworkspace
```
Someone can explain reason for me and how to setup my library supports Carthage, please?

**Comment by mdiep** [comment]
That should be fine?

Carthage will build any shared framework schemes. If a scheme is included in a workspace, it's build through the workspace; otherwise it's built through the project file.

This is important for projects that build with submodules, among other things.

**Comment by hoangtaiki** [comment]
Oh, Thank you. I have fixed my issue.
