### ISSUE TITLE
Carthage build fails for macOS platform when i import CoreImage

### ISSUE THREAD

**Issue by v57** [Carthage/Carthage#2657]
* carthage install method: [ ] .pkg, [•] homebrew, [ ] source
* `which carthage`:
`carthage build --no-skip-current`
* `carthage version`: 
`0.31.2`
* `xcodebuild -version`: 
`Xcode 10.1`
`Build version 10B61`
* Are you using `--no-build`? 
`false`
* Are you using `--no-use-binaries`?
`false`
* Are you using `--use-submodules`? 
`false`
* Are you using `--cache-builds`? 
`false`
* Are you using `--new-resolver`? 
`false`

**Cartfile**
```
github "mxcl/PromiseKit" ~> 6.0
github "attaswift/BigInt" ~> 3.1
```

**Carthage Output**
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CIFilter", referenced from:
      objc-class-ref in EIP67Code.o
  "_OBJC_CLASS_$_CIImage", referenced from:
      objc-class-ref in EIP67Code.o
```

**Actual outcome**
Every platform builds except macOS

* EIP67Code.swift starts with `#if canImport(CoreImage)`
* If i add CoreImage to the `Linked Frameworks and Libraries` i have this error:
`ld: framework not found CoreImage`
> Xcode still can build this
* Swift Package Manager have the same issue with `#if canImport(CoreImage)`
* CocoaPods builds this successfully

**Expected outcome**
Carthage should build

**Comment by v57** [comment]
But i don't have any errors when building project in xcode

**Comment by blender** [comment]
You are not linking CoreImage correctly when building for release.

**Comment by v57** [comment]
When i link CoreImage into my project, macOS platform builds but watchOS stops building because it doesn't support CoreImage. How to link frameworks for specific platforms?

**Comment by blender** [comment]
I think you can optionally require CoreImage linking for your watchOS target. Change the status to "optional".

I am going to close this issue as this is not a problem with Carthage.

**Comment by v57** [comment]
Okay looks like i solved it by adding CoreImage link into `Other Linker Flags` instead of `Linked Frameworks and Libraries`

```
//:configuration = Debug
OTHER_LDFLAGS = -framework CoreImage
OTHER_LDFLAGS[sdk=appletvos*] = -framework CoreImage
OTHER_LDFLAGS[sdk=iphoneos*] = -framework CoreImage
OTHER_LDFLAGS[sdk=iphonesimulator*] = -framework CoreImage
OTHER_LDFLAGS[sdk=watchsimulator*] = 
OTHER_LDFLAGS[sdk=watchos*] = 
OTHER_LDFLAGS[sdk=macosx*] = -framework CoreImage

//:configuration = Release
OTHER_LDFLAGS = -framework CoreImage
OTHER_LDFLAGS[sdk=appletvos*] = -framework CoreImage
OTHER_LDFLAGS[sdk=iphoneos*] = -framework CoreImage
OTHER_LDFLAGS[sdk=iphonesimulator*] = -framework CoreImage
OTHER_LDFLAGS[sdk=watchsimulator*] = 
OTHER_LDFLAGS[sdk=watchos*] = 
OTHER_LDFLAGS[sdk=macosx*] = -framework CoreImage

//:completeSettings = some
OTHER_LDFLAGS
```
