### ISSUE TITLE
Optional dependency using Cartfile.private?

### ISSUE THREAD

**Issue by SteffenL** [Carthage/Carthage#2659]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile.private (MyKit framework)**
```
git "git@github.com:myuser/openssl-carthage.git" ~> 1.1.0-patch.0
```

**Cartfile (MyApp application)**
```
git "git@github.com:myuser/openssl-carthage.git" == 1.1.0-patch.9
git "git@github.com:myuser/MyKit.git" "master"
```

**Carthage Output**
```
*** No Cartfile.resolved found, updating dependencies
*** Fetching openssl-carthage
*** Fetching MyKit
*** Checking out openssl-carthage at "v1.1.0-patch.9"
*** Checking out MyKit at "1ac6dcc525e5c98186da41580996e7ef58b6b742"
*** xcodebuild output can be found in /var/folders/nl/vvcl0r1j0010f6q9_4nz8jnm0000gn/T/carthage-xcodebuild.avIR96.log
*** Building scheme "MyKit macOS" in MyKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/user/code/ih/MyApp/Carthage/Checkouts/MyKit/MyKit.xcodeproj -scheme MyKit\ macOS -configuration Release -derivedDataPath /Users/sl/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/MyKit/e8ebdcc525e5c98186da41580996e7ef58b6b742 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/nl/vvcl0r1j0010f6q9_4nz8jnm0000gn/T/MyKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/user/code/ih/MyApp/Carthage/Checkouts/MyKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/nl/vvcl0r1j0010f6q9_4nz8jnm0000gn/T/carthage-xcodebuild.avIR96.log
```

**Actual outcome**
Carthage builds MyKit before openssl-carthage which causes MyKit to be unable to build.

**Expected outcome**
Carthage should support optional dependencies or the user of a framework should be able to replace a dependency from a different source (e.g. link it manually). It may not be a good idea to do it using Cartfile.private but I wonder if that is somehow possible now.

**Comment by blender** [comment]
Seems like OpenSSL is a dependency for MyKit. So MyKit should declare it as a dependency in its own Cartfile. 

Cartfile.private is only used to avoid passing a dependency upstream, like testing frameworks. In your case you have a direct decency instead.

**Comment by SteffenL** [comment]
I see. Thanks!

Is there another way then to completely replace a dependency (e.g. OpenSSL) either by depending on a different Carthage-enabled repository or by manually compiling OpenSSL and linking it into the project? I think it will be a big problem for users if they are locked into using my version of OpenSSL.

**Comment by blender** [comment]
If the version they want to replace it with is compatible (semantically and interface wise), they can abuse the Cartfile of their app and specify a specific version there even if their app does not directly depend upon it. 

But if they want to use a different version I guess their app does depend upon it.

**Comment by SteffenL** [comment]
I have  tried that and it does work if they specify a different compatible version while using my repository of OpenSSL, e.g the following:

```
git "git@github.com:myuser/openssl-carthage.git" == 1.1.0-patch.9
```

But what if they do not want to use my repository? What if they do not trust it or just want their own configuration of OpenSSL? Or maybe they need custom patches for OpenSSL.

They would either fork my repository to change the build scripts, add patches and what not, or they would want to manually download the OpenSSL sources and built it, then link in the library files in the app. In the first case, the repo URL will change and in the latter there is no Carthage-compatible repo. How would they prevent the OpenSSL framework produced from my repo and instead link in their own (from somewhere)?

**Comment by blender** [comment]
> How would they prevent the OpenSSL framework produced by my repo and instead link in their own (from somewhere)?

Carthage doesn't do any linking for you. A consumer can always replace the binary of the linked framework at any time, provided the module name and the binary are compatible.

> Maybe my main problem is that when adding the MyKit framework in the MyApp application, it automatically also links in OpenSSL from openssl-carthage. 

No it doesn't. You this this by dragging your OpenSSL into "Linked frameworks and libraries" of your app. 

> If I can somehow avoid OpenSSL from automatically being linked into MyApp

Again, there is no automatic linking. No magic.

I am assuming of course that OpenSSL is a dynamic framework and not a static one.

**Comment by SteffenL** [comment]
> No it doesn't. You did this by dragging your OpenSSL binary into "Linked frameworks and libraries" of your app.
But I did not. I only dragged `MyKit.framework` into MyApp's "Embedded Binaries" (macOS) section which also added it into "Linked Frameworks and Libraries".

> I am assuming of course that OpenSSL is a dynamic framework and not a static one.
It is a static framework.

**Comment by blender** [comment]
If OpenSSL is a static framework you should be statically linking it to MyKit.framework. 

At that point there is no replacing OpenSSL with another version, it's fused into MyKit.framework's binary. You should be hiding it via a private .modulemap if you don't want it to be exposed. At that point I believe that a consumer of your framework can link OpenSSL again at another version.

None of this however is a concern of Carthage. Your question is about linking in general.
