### ISSUE TITLE
Build failed without Apple ID

### ISSUE THREAD

**Issue by zhudongfang** [Carthage/Carthage#266]
Build settings from command line:
SDKROOT = iphoneos8.1

=== BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===
 
Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and priva    te key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.1'

Alamofire has the same problem

**Comment by jspahrsummers** [comment]
This is expected behavior. Code signing is [required for iOS frameworks](https://github.com/Carthage/Carthage/issues/235).
