### ISSUE TITLE
a question out of curiosity, what does the release name stand for?

### ISSUE THREAD

**Issue by Yannmm** [Carthage/Carthage#2662]
when i checkout the release list, i can't help wondering where names like "Vocal Vortex", "Ubiquitous Upbeat" come from. 
Meanwhile, it feels like i have seen naming pattern alike, but i don't remember where.
i googled, but nothing useful found. 
can anyone satisfy my curiosity, please. 😂
many thanks.

**Comment by mdiep** [comment]
Whoever makes the release tries to come up with a fun name. They don't necessarily stand for anything. Sometimes they're related to the content of the release. But they're really just for fun. 😄
