### ISSUE TITLE
Ability to specify path to the Cartfile

### ISSUE THREAD

**Issue by Alex293** [Carthage/Carthage#2666]
* carthage install method: [ ] .pkg, [X ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`: Xcode 10.1 - Build version 10B61
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no 
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

I didn't found any information / issue about being able to specify the name / path to the Cartfile.
My project is growing quite a lot and I'm moving as much as possible the tooling into a separate folder. I'm using Xcodegen to link libs from Carthage and everything is working great but I can't update my dependency without moving to the Carthage folder. As most tools allow to specify the path to the conflict file I was wondering if this could be add to Carthage ?

**Comment by blender** [comment]
How would this work for dependencies relying on your projects?

**Comment by Alex293** [comment]
@blender Isn't Carthage used only by the final user ?

**Comment by blender** [comment]
I am not sure what you mean but the final user can be both a framework developer or an application developer. 

So if I develop a library that uses Alamofire I can use Carthage to specify It as a dependency for my library. 

I can then develop an application that makes use of my library as specify just my library as a dependency. 

Carthage will then produce a Cartfile.resolved file for my library that includes both my library and Alamofire.  This is called a transitive dependency.  

When the Cartfile.resolved is generated, for example when running `carthage update`, the Cartfile of all projects is read again to _resolve_ dependencies. In this phase Carthage needs to discover the location of the Cartfile for all projects. Right now the Cartfile is always expected to be at top level.
