### ISSUE TITLE
IBDesignable doesn't work when using frameworks in targets

### ISSUE THREAD

**Issue by Sorix** [Carthage/Carthage#2669]
## Configuration
* carthage install method: homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? yes
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

#### Cartfile
```
github "MoZhouqi/KMPlaceholderTextView" ~> 1.4.0
```

#### Description
I use storyboards, `@IBDesignable` and moduled approach in my application. I have several targets in my app:
* `Application`
* `SelectionUI` (requires `Designables`) → **storyboard is here**
* `Designables` (requires Carthage's `KMPlaceholderTextView`)

I have an issue with `copy-frameworks` command.

#### `copy-frameworks` command is added only at root target (`Application`):
**Storyboards and XIBs doesn't work in XCode (visual editor)**, because XCode tries to compile `SelectionUI` module and couldn't find `KMPlaceholderTextView` framework (it wasn't copied by Carthage) and I receive such errors in XCode:

> file:///.../SelectionUI/Resources/PlaceSelection.storyboard: error: IB Designables: Failed to render and update auto layout status for UIView: dlopen(Designables.framework, 1): Library not loaded: @rpath/KMPlaceholderTextView.framework/KMPlaceholderTextView
>   Referenced from: Designables.framework
>   Reason: image not found

#### `copy-frameworks` command is added for all targets
If I add that command to all targets, including `Application` and `Designables`.

Storyboards and XIBs works perfectly, but **I receive framework's duplication at output executable**. I have `KMPlaceholderTextView` at Application/Frameworks and I have the same `KMPlaceholderTextView` at Application/Designables/Frameworks.

## My minds
When XCode tries to compile Storyboard files it doesn't run Run script phase from the root target `Application`, it runs only scripts from target's framework (that is `SelectionUI`), but SelectionUI doesn't have run script phase, that's why `KMPlaceholderTextView` is not integrated and XCode throws an error. All my Storyboards become just black.

If I specify Run script phase in each framework, visual designer will work, but I will receive duplicated embedded frameworks in my modules.

**Comment by mdiep** [comment]
I'm not sure if there's anything that Carthage can do here.

**Comment by ikesyo** [comment]
Duplicate of #2365.

**Comment by Sorix** [comment]
I've implemented my own solution, tried to do it in the most native way. I can't say that is good solution, but that is the best that I have.

I integrate frameworks in each target (not in main application) when application is run in Debug configuration. At release configuration all frameworks is integrated in main application.

#### Step-by-step
1. Create configuration settings file, e.g.: `Debug.xcconfig` and assign it to Debug configuration.
2. Add copy-frameworks command there: `COPY_FRAMEWORKS_COMMAND = /usr/local/bin/carthage copy-frameworks`
3. Add this command to all targets except main application to *Run script phase*: `${COPY_FRAMEWORKS_COMMAND}`, and add all needed frameworks for each target in Input Files and Output files as desribed at **5 paragraph** in [Carthage guide](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos). For example if **Designables** target requires 2 frameworks, add them, so you will receive framework with integrated frameworks.

After that steps you may receive duplicating framework integration at different targets, but at release stage everything will be okay, because command in `Debug.xcconfig` won't be executed.
