### ISSUE TITLE
Question: Nested Library with carthage dependencies

### ISSUE THREAD

**Issue by pkhodaveissi** [Carthage/Carthage#2674]
Hello
I have a project that has many libraries as dependency but not carthage type of dependencies just drag and drop xcodeproject
one of these libraries has carthage dependencies, when building the library build phase passes just right but the main project outputs:
```
ld: warning: Could not find auto-linked framework 'Cache'
Undefined symbols for architecture x86_64:
  "Cache.DiskConfig.init(name: Swift.String, expiry: Cache.Expiry, maxSize: Swift.UInt, directory: Foundation.URL?, protectionType: __C.NSFileProtectionType?) -> Cache.DiskConfig", referenced from:
```

as you can see [Cashe](https://github.com/hyperoslo/Cache) is one of the dependencies but main project has problem identifying it, I mean if it is resolved in the nested library why should main project go look for it also?
and how I should go about this to solve?

**Comment by blender** [comment]
You should link this library in your main project too.
