### ISSUE TITLE
Build modified library

### ISSUE THREAD

**Issue by PJCSpencer** [Carthage/Carthage#2676]
Hi there,

I have a situation with a library we are using for a project. The situation suggests we need to introduce a small modification which potentially would help mature the library.

My challenge: I would like to make a small change to the local source and have Carthage build that version without checking out any new/existing version.

Can I do this? How can I do this?

**Comment by blender** [comment]
You can point Carthage to a local file path relative or absolute

**Comment by PJCSpencer** [comment]
Hi there,

I have this in my Cartfile:
git "/Users/.../Carthage⁩/Checkouts⁩/IOS-Library" "someVersion"

I'm using the following command:
carthage bootstrap --platform ios

I get this output:
A shell task (/usr/bin/env git fetch --prune --quiet /Users/.../Library refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/.../Library/Caches/org.carthage.CarthageKit/dependencies/IOS-Library)) failed with exit code 128:
fatal: '/Users/.../Carthage⁩/Checkouts⁩/IOS-Library' does not appear to be a git repository
fatal: Could not read from remote repository.

It would be great to understand exactly how I'm supposed to do this correctly.

**Comment by blender** [comment]
Quoting the error you have reported:

```
fatal: '/Users/.../Carthage⁩/Checkouts⁩/IOS-Library' does not appear to be a git repository
```

**Comment by PJCSpencer** [comment]
This builds the original source without the changes?

Is the correct command: 
carthage bootstrap --platform ios

I cloned the repo to my desktop, modified the Cartfile to reflect the path.

**Comment by PJCSpencer** [comment]
Thank you very much!

The solution was to build and include the library manually as the change we made was to illustrate the need for a small evolution of the library. A change which would never be merged into any remote.
