### ISSUE TITLE
Carthage builds framework for iOS 12.1 instead of 10

### ISSUE THREAD

**Issue by aryan-ghassemi-ck** [Carthage/Carthage#2679]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: Private
* `carthage version`: 0.31.2
* `xcodebuild -version`: 10.1 (10B61)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "ck-private/mob_ios-ck-module" == 1.0.3
```

**Carthage Output**
```
*** Building scheme "CKModule" in CKModule.xcodeproj
```

**Actual outcome**
Carthage did not build with the proper minimum deployment target and it's causing an error
`Module file's minimum deployment target is ios 12.1 v12.1`

**Expected outcome**
Carthage should build using 10 as the deployment target

I have deployment target set to 10 , but when I do Carthage update it uses 12.1.

Where does it get that info from? In the info.plist DTPlatformVersion is set to 12.1 I searched my whole project for 12.1 and it's not used anywhere

I know it's not a caching issue because I'm updating the build number and it's getting updated in carthage info,plist file

**Comment by blender** [comment]
This is most likely a problem with your setup. 

I invite you to check the log file and invoke xcodebuild on the command line just like Carthage does.

**Comment by aryan-ghassemi-ck** [comment]
You are correct thanks, will find out what's wrong with my project
