### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by jhonc33** [Carthage/Carthage#268]
This is my Cartfile:

    github "SwiftyJSON/SwiftyJSON" >= 2.1.2

When I run carthage update, the terminal returns:

    *** Building scheme "SwiftyJSON" in SwiftyJSON.xcworkspace
    ** BUILD FAILED **

    The following build commands failed:
	Check dependencies
    (1 failure)

And this is my log file:

Check dependencies

		=== BUILD TARGET SwiftyJSONTests OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

		Check dependencies

		** BUILD SUCCEEDED **

		Build settings from command line:
		    SDKROOT = iphoneos8.1

		=== BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

		Check dependencies
		Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
		CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.1'

Any idea?

**Comment by jspahrsummers** [comment]
You need to have an iOS code signing identity set up.
