### ISSUE TITLE
Occasional recursion and failures during update

### ISSUE THREAD

**Issue by ianbytchek** [Carthage/Carthage#2682]
I want to touch the surface here to figure out if there's an actual problem. I have a feeling that resolvers (using mostly `--new-resolver`, but applies to the standard one too) don't handle very well same dependencies with different case names, like `"foo/bar"` and `"Foo/Bar"`. Carthage enters endless loop when trying to update a single explicit dependency, in my case `carthage update corestore --platform mac --new-resolver`, but also doesn't find it if I use `CoreStore` with cli when it's spelt `corestore` in the cart file. It succeeds when the `update` is ran on all dependencies.

Are there any guidelines or details on naming dependencies? Obviously the name might change or different co-dependencies may use different name format for same sub-dependencies, does Carthage handle these cases?

**Comment by mdiep** [comment]
I think we explicitly ignore case. Also, `Bar` identifies the dependency; you can't have 2 dependencies with the same name from different owners. (This is important because it allows you switch to a different fork of a dependency.)
