### ISSUE TITLE
Endless loop when fetching dependencies

### ISSUE THREAD

**Issue by bswaidner** [Carthage/Carthage#2683]
`carthage version`: 0.31.2

I have run the following commands with the same results. 

`carthage update --platform ios`
`carthage update --platform ios --no-use-binaries`
`carthage update --platform ios --no-use-binaries --cache-builds`
`carthage update --platform ios --cache-builds`
`carthage update --platform ios --no-use-binaries --cache-builds --new-resolver`

If I remove the dependency that loops endlessly, the same thing will happen to another dependency. 

```
*** Fetching XCGLogger
*** Fetching realm-cocoa
*** Fetching Alamofire
*** Fetching AlamofireObjectMapper
*** Fetching Bolts-ObjC
*** Fetching NVActivityIndicatorView
*** Fetching NVActivityIndicatorView
*** Fetching NVActivityIndicatorView
*** Fetching NVActivityIndicatorView
*** Fetching NVActivityIndicatorView
*** Fetching NVActivityIndicatorView
*** Fetching NVActivityIndicatorView
*** Fetching NVActivityIndicatorView
```

**Comment by kenji21** [comment]
Without the Cartfile content the issue can't be reproduced (and maybe a look to Cartfile of some dependencies is necessary too)

**Comment by bswaidner** [comment]
I was able to resolve this issue. One of the dependencies had removed a commit that was being used in the Cartfile. Thanks
