### ISSUE TITLE
static library scheme support

### ISSUE THREAD

**Issue by bootstraponline** [Carthage/Carthage#2685]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  no
* Are you using `--new-resolver`?  no

**Cartfile**
```
github "google/EarlGrey" "earlgrey2"
```

**Carthage Output**
```
$ carthage update
*** Fetching EarlGrey
*** Checking out EarlGrey at "a4d0b3f0309910bc34a7543dd588f680e71f49db"
*** xcodebuild output can be found in /var/folders/14/h2zk5sx1315b__blzdt7hz1m4k0by8/T/carthage-xcodebuild.PKzH6q.log
*** Building scheme "AppFramework" in EarlGrey.xcodeproj
```

**Actual outcome**
Carthage did not build the static library schemes.

**Expected outcome**
Carthage should have built the static library schemes in addition to the framework scheme.

![image](https://user-images.githubusercontent.com/1173057/51286042-4e9ef900-19bf-11e9-8f9b-1a7465dc8a3f.png)

https://github.com/google/EarlGrey/pull/787

I found this in the readme:

> Carthage does not currently support static library schemes, nor are there any plans to introduce their support in the future.

I'd like to understand why static library schemes are not supported. Let me know. Thanks!

**Comment by bootstraponline** [comment]
Thank you!

**Comment by tirodkar** [comment]
Can you explain "static framework" a bit more and how to generate this with Xcode? If I have a dependency that is a static library, but I do not expose the headers (hypothetically), would that not work?

**Comment by tirodkar** [comment]
For clarification from the Carthage folks - 

If I provide a pre-compiled framework (dylib) which has static library dependencies, then there shouldn't be an issue with Carthage as the building is already done?
