### ISSUE TITLE
Carthage --verbose doesn't output when Building scheme

### ISSUE THREAD

**Issue by ggirotto** [Carthage/Carthage#2687]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No

**Cartfile**
```
github "LeoNatan/LNPopupController" == 2.5.24

binary "https://building42.github.io/Specs/Carthage/iOS/Fabric.json" == 1.7.12
binary "https://building42.github.io/Specs/Carthage/iOS/Answers.json" == 1.3.7
binary "https://building42.github.io/Specs/Carthage/iOS/Crashlytics.json" == 3.10.7

github "pkarc/Facebook-SDK-Swift" "update-obj-v"
github "lkzhao/Hero" == 1.3.1

binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 5.4.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDatabaseBinary.json" == 5.4.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" == 5.4.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDynamicLinksBinary.json" == 5.4.0

github "patchthecode/JTAppleCalendar" == 7.1.4
github "jdg/MBProgressHUD" == 1.1
github "MortimerGoro/MGSwipeTableCell" == 1.6.7
github "roberthein/TinyConstraints" == 3.3.0
github "realm/realm-cocoa" ~> 3.10.0
github "Quick/Quick" == 1.3.2
github "Quick/Nimble" == 7.3.1
```

**Carthage Output**
```
...
*** Building scheme "Bolts-iOS" in Bolts.xcodeproj
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Bolts-watchOS" in Bolts.xcodeproj
*** Building scheme "Bolts-watchOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Charts" in Charts.xcworkspace
*** Building scheme "FBSDKCoreKit-Dynamic" in FacebookSDK.xcworkspace
...
```

**Actual outcome**
During the Build process Carthage prints the schemes correctly

**Expected outcome**
Carthage should prompt anything during this Build Scheme process when using `--verbose` (maybe the percentage, or just copy and paste the line after x seconds) in order to avoid that huge Builds - like Realm in my case - reaches the timeout of the CI.

**Comment by mdiep** [comment]
If you're using `--verbose`, you should be seeing all the output from `xcodebuild`. 😕

**Comment by ggirotto** [comment]
@mdiep Sorry about that, I was looking the wrong script. `--verbose` worked as you said. Really sorry about that.
