### ISSUE TITLE
Make bootstrap doesn't exist

### ISSUE THREAD

**Issue by drekka** [Carthage/Carthage#2692]
* carthage install method: [ ] .pkg, [ ] homebrew, [ X] source

Checked out master Carthage branch to see if the suggested fixes would work to get it building under Xcode 10.2 beta.

Looked at the contributing document to see how to start and executed `make bootstrap` which gave me this output:

```
Bit-Shifter:Carthage derekclarkson$ make bootstrap
make: *** No rule to make target `bootstrap'.  Stop.
```

Um. So now what? :-)

**Comment by ikesyo** [comment]
https://github.com/Carthage/Carthage/blob/master/CONTRIBUTING.md should be updated then.

**Comment by drekka** [comment]
Yeah. I tried to use `swift package generate-xcodeproj` and got this:

```
Bit-Shifter:Carthage derekclarkson$ swift package generate-xcodeproj
Updating https://github.com/apple/swift-package-manager.git
Updating https://github.com/Quick/Nimble.git
Updating https://github.com/antitypical/Result.git
Updating https://github.com/Carthage/Commandant.git
Updating https://github.com/mdiep/Tentacle.git
Updating https://github.com/Quick/Quick.git
Updating https://github.com/Carthage/ReactiveTask.git
Updating https://github.com/apple/swift-llbuild.git
Updating https://github.com/jdhealy/PrettyColors.git
Updating https://github.com/ReactiveCocoa/ReactiveSwift.git
Updating https://github.com/thoughtbot/Curry.git
error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies: 
    https://github.com/jdhealy/PrettyColors.git @ 5.0.0..<6.0.0
    https://github.com/thoughtbot/Curry.git @ 4.0.0..<5.0.0
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'Quick' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'Nimble' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'Result' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'ReactiveSwift' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'ReactiveTask' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'Quick' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'Nimble' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'Commandant' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'Curry' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'PrettyColors' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'Tentacle' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'Curry' not found
'Carthage' /Users/derekclarkson/Desktop/Carthage: error: product dependency 'SwiftPM-auto' not found
```

**Comment by mxcl** [comment]
The output @drekka got is for Xcode 10.2-beta (was for me anyway), but it worked with Xcode 10.1.

My problem now is the generated xcodeproject doesn’t build.

<img width="894" alt="screen shot 2019-01-27 at 5 35 23 pm" src="https://user-images.githubusercontent.com/58962/51807829-f0450680-2259-11e9-8ca7-64bb63514543.png">

Though this is presumably because Carthage depends on the `master` ref of `apple/swift-package-manager`. Ouch. Can we choose a specific SHA?

**Comment by mxcl** [comment]
I filed the bug against SwiftPM for failing to build with Xcode 10.2-beta: https://bugs.swift.org/browse/SR-9775

**Comment by mxcl** [comment]
Specifically for this issue though, `CONTRIBUTING.md` needs updating.

**Comment by mxcl** [comment]
I've confirmed it does check out the revision specified in `Package.resolved`.

So I can't create an xcodeproj that builds Carthage without error with Xcode 10.1.

I specified `swift package generate-xcodeproj`, and commented in this thread because the CONTRIBUTING guide says to do `make bootstrap` which doesn't work. Do you want a new ticket?

**Comment by mdiep** [comment]
The switch to build with SwiftPM and the effort to use code from SwiftPM are both new. Evidently we're still working out the kinks. I definitely didn't expect building to break with Xcode 10.2.

I've been editing in Xcode, but building with `swift build`.

CONTRIBUTING could definitely use an update.

**Comment by mdiep** [comment]
Oh, I just realized: I think `PrettyColors` might still be on Swift 3, which is no longer supported. That may be why building broke.

**Comment by mdiep** [comment]
Look like that's tracked in #2694.

**Comment by mxcl** [comment]
To be clear I cannot generate an Xcode project with Xcode 10.1. Is that how *you* work on Carthage? If not do you have a better way? I wanted to tackle that PR.
