### ISSUE TITLE
How to use org.carthage.CarthageKit folder to speed up build?

### ISSUE THREAD

**Issue by ton252** [Carthage/Carthage#2697]
I'm trying to setup Carthage on my CI.

For example I have a project with one dependency. 
I want this dependency will not to rebuild every time,  when CI build start. 
For this feature, as written in the documentation, we need to use `--use-cache` flag.
But my CI clean build folder every time, that it start new build.

I thought, if Carthage try to find builded dependencies in `Carthage/Build` folder, and if he couldn't find dependencies there he try to search them in `org.carthage.CarthageKit` folder. But it don't and start rebuild all dependencies?

Could somebody explain how it works? I and how I can get cached build from `org.carthage.CarthageKit` folder?

**Comment by blender** [comment]
0.32.0 is not caching in that folder.

The flag is --cache-builds that just avoid re-building already built binaries found in Carthage/Checkout

What you want can be achieved with https://github.com/blender/Rome

**Comment by kenji21** [comment]
You can look of what I've implemented to have a "shared cache" accross project for issue https://github.com/Carthage/Carthage/issues/2400

Let's say two projects uses Alamofire 3.0, when bootstrap project A, it will be compiled, it won't need a second compilation when bootstrap-ing project B

**Comment by ton252** [comment]
When we really need org.carthage.CarthageKit folder? And if it doesn't extract .framework files from org.carthage.CarthageKit folder why it store frameworks there? What is the real purpose of this folder?

**Comment by mdiep** [comment]
The `org.carthage.CarthageKit` folder caches:

- Copies of dependency repositories
- Copies of binary dependencies
- Shared derived data folders
