### ISSUE TITLE
copy-framework doesn't strip armv7 architecture if deployment target is iOS 11

### ISSUE THREAD

**Issue by marco-palumbo** [Carthage/Carthage#2700]
* carthage install method: [ ] .pkg, [x ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.32.0
* `xcodebuild -version`: Xcode 10.1 (10B61)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "Moya/Moya" ~> 11.0
```

**Actual outcome**
I've set the deployment target of my project to iOS 11, so the minimum valid architecture should be arm64, but the frameworks copied inside the app bundle does contain also the armv7 architecture.

**Expected outcome**
The framworks copied inside the app bundle should only contain the arm64[e] architecture.

**Comment by ikesyo** [comment]
That is affected by `VALID_ARCHS` build settings: https://github.com/Carthage/Carthage/blob/1c3e23a3dffc7f19ccd6dd8073454bb39fdfafa5/Source/carthage/CopyFrameworks.swift#L166-L170

Changing the target's deployment target does not alter Xcode's `iOS Default` value of `arm64 arm64e armv7 armv7s`. So you should remove `armv7` by yourself.

**Comment by marco-palumbo** [comment]
Couldn't you take into account also the deployment target to deduce the valid architectures?
