### ISSUE TITLE
dyld: Library not loaded: ... Reason: image not found

### ISSUE THREAD

**Issue by meaning-matters** [Carthage/Carthage#2701]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.31.2
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`? N
* Are you using `--no-use-binaries`? Y
* Are you using `--use-submodules`? N
* Are you using `--cache-builds`? Y
* Are you using `--new-resolver`? N

**Cartfile**
```
gtihub "<my own framework>" "<some branch>"
```

**Carthage Output**
Carthage runs fine on the command line.

**Actual outcome**
I followed the Carthage README.md instructions for iOS apps: Dragging my Carthage built framework to General > Linked Frameworks and Libraries and adding the `copy-frameworks` Build Phases > Run Script.

The app builds fine, but when I run it in the Simulator, I get:
```
 dyld: Library not loaded: @rpath/MyFramework.framework/MyFramework
  Referenced from: /Users/<me>/Library/Developer/CoreSimulator/Devices/A3651DD6-F31D-4866-963F-12A57C575BEC/data/Containers/Bundle/Application/B4D47B47-16B0-42EC-8321-5BFD7D58DD45/MyApp.app/MyApp
  Reason: image not found
```

This issue can be resolved by either adding `$(FRAMEWORKS_FOLDER_PATH)` to Build Settings > Runpath Search Paths, or by adding my framework in a Build Phases > Copy Files Phase with Destination set to Frameworks.

**Expected outcome**
The app should just run when following the README.md.

When searching for solutions I find several people having all kinds of issues related to this. Some add frameworks as Embedded Binaries (something the README.md explicitly only says for macOS applications). Others add the frameworks to a Copy Files Phase. I also found a, less related, [Python script](https://github.com/lvillani/carthage-copy-frameworks) to replace `copy-frameworks`.

Some of the work-arounds I found in Carthage issues, but didn't make it to the README.md.

Is the README.md outdated/wrong?

**Comment by blender** [comment]
Dragging & Dropping should work, the alternative method is to manually add the framework to Linked Libraries & Frameworks.

Did you specify the input files to the `carthage copy-frameworks` phase?

**Comment by meaning-matters** [comment]
@blender I've also manually added my framework to Build Phases > Link Binary With Libraries (which is where it of course also shows up now).

Yes, I have the `copy-frameworks` Run Script phase (as I wrote).

**Comment by blender** [comment]
I'll try with a new project myself.

**Comment by meaning-matters** [comment]
My new framework + app work. But when I remove the Run Script Input File, I get the same error as in my original app. So I'm going to double check everything there.

**Comment by meaning-matters** [comment]
@blender It was a silly typo in the Run Script > Input File.  (I thought the Input & Output Files are only by the Xcode build system to determine the scripts 'build' dependencies.)

Apologies for the noise. I've very happy things work as the README.md says!
