### ISSUE TITLE
Error when running copy-frameworks: Could not cast value of type 'NSError' to 'Result.NoError'

### ISSUE THREAD

**Issue by cpowers** [Carthage/Carthage#2702]
* carthage install method: [ ] .pkg, [ x ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.32.0
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "Alamofire/Alamofire" ~> 4.5
github "evgenyneu/keychain-swift" ~> 13.0
```

**Carthage Output**
```
Could not cast value of type 'NSError' (0x10ee29610) to 'Result.NoError' (0x10e95c688).
/Users/<redacted>/Library/Developer/Xcode/DerivedData/Admin-buxxiqqqpttxsebchafbmglwucsk/Build/Intermediates.noindex/Admin.build/Debug-iphonesimulator/Admin.build/Script-9144EEDA218CF5490042F65A.sh: line 2:  9138 Abort trap: 6           /usr/local/bin/carthage copy-frameworks
Command PhaseScriptExecution failed with a nonzero exit code
```

**Actual outcome**
The copy-frameworks fails to run with the above output. Please note that I have multiple Xcode projects on the same machine using Carthage and only one of the projects is failing with the above error.

**Expected outcome**
Carthage should copy/strip frameworks as necessary

**Comment by jdhealy** [comment]
This looks like the bug for when one of `SCRIPT_INPUT_FILE_LIST_…` is not a readable file. You should be able to workaround this by fixing that input.

If that’s the case, this is fixed when we ship https://github.com/Carthage/Carthage/pull/2668/ — could you report back if the workaround is successful for you?

Sorry for not shipping that bug fix yet, and thanks for writing up an issue ✨

**Comment by cpowers** [comment]
Thanks for the info. I found that this project somehow had a blank entry in the input file list for the script build phase that was causing the error.
