### ISSUE TITLE
Q: Is it possible to build/archive a project against a physical device?

### ISSUE THREAD

**Issue by RustyKnight** [Carthage/Carthage#2709]
# Background
I have, yet another, project which has a number of third party lib*.a binaries which do not have simulator slices and which can't be built against the simulators, and must be built against a physical device

I'd like to generate a "binary only" framework from the library so it can easily be included in other projects, without the need to build the library, as it will fail through Carthage.

# Question 
Is it possible to specific the device (uuid) that Carthage should use when building/archiving the project and override the default behaviour (of looking up the simulators)?

I have a "pre-made" process which I use to generate "binary-only" builds and upload them to my server and I would like the ability to continue using it with this project if possible

# Failed attempt...

I did try and look at modifying the source for Carthage to provide me a means to do so, but I just ended up breaking everything ... obviously need more time to understand how the build CLI works and how Carthage works with it

**Comment by blender** [comment]
> I'd like to generate a "binary only" framework from the library so it can easily be included in other projects, without the need to build the library, as it will fail through Carthage.
> I have a "pre-made" process which I use to generate "binary-only" builds and upload them to my server and I would like the ability to continue using it with this project if possible

So why not use the "binary" distribution option? https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-only-frameworks

**Comment by RustyKnight** [comment]
@blender Sorry, I should have pointed out that I've already tried, but because the reliance on the 3rd party libraries, it won't build when built against the simulator.  I can build it manually, but I'm "hoping" there is some way to continue using Carthage, which I've already got setup in a workflow to do this

```
Undefined symbols for architecture arm64:
ld: symbol(s) not found for architecture arm64
//...
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

```

This is why I'd love to be able to point Carthage to a physical device.

This is not an issue with Carthage, but I have an established work flow already working and I'd like to just take advantage of it if I can

**Comment by blender** [comment]
> Is it possible to specific the device (uuid) that Carthage should use when building/archiving the project and override the default behaviour (of looking up the simulators)?

> This is why I'd love to be able to point Carthage to a physical device.

No, I don't think you can do that without changing the source code.

**Comment by RustyKnight** [comment]
@blender This is what I figured, but wanted to be sure before I went to the trouble of trying to "patch" a solution

Thanks
