### ISSUE TITLE
[Question] providing mock/debug frameworks via carthage

### ISSUE THREAD

**Issue by jamezilla** [Carthage/Carthage#2710]
I'm trying to figure out how to provide two targets in some of our internal frameworks: 
1. a real framework
2. a companion mock framework for target 1 (to be used by consumers when writing tests)

Target 2 is really just a single Swift file generated by [Cuckoo](https://github.com/Brightify/Cuckoo), and a build phase which feeds a list of files into Cuckoo. The mock framework needs to link and import the real framework so it can delegate to the real implementation (when needed) and to resolve some types.

Unfortunately, Carthage doesn't easily support this scenario. To really support this scenario, the real 
framework needs to be compiled with `ENABLE_TESTABILITY`, which we obviously don't want in our archived frameworks.

I can only see two solutions to this issue: 

A. have the ability to build debug version of frameworks
B. use `--no-build` and set up an xcode workspace for all the dependencies which can build in debug mode

Option A, I imagine, is too big a shift for the community. It would just output frameworks into a `Debug` folder under `Builds`. Then consumers can set framework search paths in xcode for unit test targets (or app debug builds) appropriately.

For option B, I just need some resolution to #2319, or #2532 (which seems stalled/dead), because we have a bunch of binary dependencies and using `--no-build` isn't sufficient to get them on-disk in a way which I could integrate into an xcode workspace.

Any thoughts/guidance?

**Comment by kenji21** [comment]
You can look at this readme where framework needs to be copied to your xctest bundle : https://github.com/openium/SwiftiumTestingKit
