### ISSUE TITLE
Carthage doesn't see shared schemes in static library.

### ISSUE THREAD

**Issue by kostya-zhidovinov** [Carthage/Carthage#2715]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.32.0
* `xcodebuild -version`: 
```
Xcode 10.1
Build version 10B61
```
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

According to documentation https://github.com/Carthage/Carthage#build-static-frameworks-to-speed-up-your-apps-launch-times I've tried to build a static library for example project https://github.com/kostya-zhidovinov/teststatic
```
$ carthage build --no-skip-current
```

**Carthage Output**
```
*** xcodebuild output can be found in /var/folders/l0/bft2166966320fb6sl3rmg980000gn/T/carthage-xcodebuild.HXkMI9.log
*** Skipped building TestStatic due to the error:
Dependency "TestStatic" has no shared framework schemes
```

```
$ carthage build --archive
*** xcodebuild output can be found in /var/folders/l0/bft2166966320fb6sl3rmg980000gn/T/carthage-xcodebuild.pLbA0W.log
*** Skipped building TestStatic due to the error:
Dependency "TestStatic" has no shared framework schemes
Dependency "TestStatic" has no shared framework schemes
```

**Actual outcome**
Carthage doesn't see shared schemes and it doesn't build a static library.

**Expected outcome**
Carthage should build a static library.

**Comment by blender** [comment]
Carthage builds __static frameworks__ not static libraries.
