### ISSUE TITLE
Create package with several frameworks

### ISSUE THREAD

**Issue by pepone** [Carthage/Carthage#2717]
Hi,

Trying to figure out how to publish my packages using carthage, I have  iOS and macOS separate projects and each build two frameworks with identical names Ice.framework and IceObjec.framework

I added both projects to a workscpace in the top-level directory, all the projects are using shared schemas and are dynamic frameworks

I build with `carthage build --no-skip-current` but only one of the frameworks get build

```
$ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/wx/h0n192c96r1fz21qkn3qgvp40000gn/T/carthage-xcodebuild.Qtx4yN.log
*** Building scheme "IceObjc" in ice.xcworkspace
```

Any ideas how can I get this working, ice.xcworkspace is available at https://github.com/zeroc-ice/ice/tree/swift

**Comment by blender** [comment]
What does `xcodebuild -list` return ?

**Comment by pepone** [comment]
```
xcodebuild -list 
Information about workspace "ice":
    Schemes:
        Ice
        IceObjc
        IceObjc
```

**Comment by blender** [comment]
does `carthage build --no-skip-current` run on `Ice` produce the expected result?

**Comment by pepone** [comment]
I guess the duplicate scheme names it is causing troubles here, I will try renaming schemes

**Comment by pepone** [comment]
So I manage to get to things working but I removing the workspace, and only use projects carthage build all projects and I get the expected result.

```
ls Carthage/Build/Mac/
Ice.framework        Ice.framework.dSYM
$ ls Carthage/Build/iOS/
4DE5EC6F-1932-3AB6-B7EB-2E85015A15AF.bcsymbolmap    Ice.framework Ice.framework.dSYM
```
one last question, are iOS frameworks build for both iphoneos/iphonesimulator, how this work?

I see my iOS framework is a fat binary x86_64/arm64 but it ends including a dependency that is only arm64

```
Carthage/Build/iOS/Ice.framework/Frameworks/IceObjc.framework/IceObjc is architecture: arm64
Architectures in the fat file: Carthage/Build/iOS/Ice.framework/Ice are: x86_64 arm64 
```

any ideas about this? both IceObjc.framework and Ice.framework are build with `carthage build --skip-no-current` but only `Ice.framework` is a shared framework.

**Comment by blender** [comment]
Frameworks include architectures supported by your project. `IceObjc` doesn't seem to specify `iphonesimulaor` or `x84_64` or `i386` in it's supported archs/platforms

Before thinning they are fat binaries.

**Comment by pepone** [comment]
If I change `IceObjc` to be a shared framework I get what I expect
``
Architectures in the fat file: Carthage/Build/iOS/IceObjc.framework/IceObjc are: x86_64 arm64
```

But if I bundle it with Ice.frameworks it doesn't include a fat binary, maybe this is a limitation of how xcodebuild, or how I setup my copyphase to include IceObjc.framework with Ice.framework

**Comment by blender** [comment]
I'm still not sure what you're trying to achieve here. If you would sketch it out somehow that would help.

For one, I don't understand what relationships (if any) there frameworks have to each other. 

Also, there is not such thinks as a cartahge "package" that you quote in the title.

I'm trying to help but I'm a little confused as you can see.

**Comment by pepone** [comment]
I have two dynamic frameworks IceObjc (C++, Objective-c) and Ice (Swift), Ice frameworks links with IceObjc. I want to build Ice framework for macOS and iOS platforms, and keep the IceObjc.framework as an internal dependency in `Ice.framework/Frameworks` directory

In my projects, if I only set up `Ice` as a shared scheme then the IceObjc framework included in `Ice.framework/Frameworks` is not a fat binary

If I set both Ice and IceObjc as shared schemes both `Carthage/Build/iOS/IceObjc.framework` and `Carthage/Build/iOS/Ice.framework` included fat binaries, but the `IceObjc` copy in Ice.framework/Frameworks is not a fat binary.

```
lipo -info Carthage/Build/iOS/Ice.framework/Ice
Architectures in the fat file: Carthage/Build/iOS/Ice.framework/Ice are: x86_64 arm64 
lipo -info Carthage/Build/iOS/Ice.framework/Frameworks/IceObjc.framework/IceObjc 
Non-fat file: Carthage/Build/iOS/Ice.framework/Frameworks/IceObjc.framework/IceObjc is architecture: arm64
lipo -info Carthage/Build/iOS/IceObjc.framework/IceObjc 
Architectures in the fat file: Carthage/Build/iOS/IceObjc.framework/IceObjc are: x86_64 arm64 
```

**Comment by ikesyo** [comment]
> but the IceObjc copy in Ice.framework/Frameworks is not a fat binary.

Carthage don't do anything for such nested frameworks, so that is expected.

> and keep the IceObjc.framework as an internal dependency in Ice.framework/Frameworks directory

Because nested frameworks are prohibited on iOS, that is not achievable. You should do

- Make IceObjc scheme shared
- Don't embed IceObjc.framework into Ice.framework/Frameworks
- Link and embed both Ice.framework and IceObjc.framework on an application side

**Comment by pepone** [comment]
Thanks @ikesyo this makes things clear
