### ISSUE TITLE
Alternative to copy-frameworks is to strip x86 slices

### ISSUE THREAD

**Issue by JetForMe** [Carthage/Carthage#2719]
An alternative to the `copy-frameworks` script is a script that removes x86 slices from embedded dylibs. I do this for a library we assemble in-house:

```
if [ ${PLATFORM_NAME} = "iphoneos" ];
then
    lipo "TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH/ourframework.framework/ourframework" -remove "x86_64" -output "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/ourframework.framework/ourframework" 2> /dev/null
    exit 0
fi
```

A script that iterates all frameworks in `TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH` could do this, and it would avoid the error-prone need to add each new framework to the `copy-frameworks` script.

**Comment by blender** [comment]
copy-frameworks also strips symbols.

**Comment by JetForMe** [comment]
My suggestion would let Xcode embed the frameworks via its normal UI (I think, wouldn't it?), skipping the extra copy step.

> On Mar 4, 2019, at 22:55 , Tommaso Piazza <notifications@github.com> wrote:
> 
> copy-frameworks also strips symbols.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- 
Rick Mann
rmann@latencyzero.com

**Comment by blender** [comment]
I'm not sure what you mean.

`copy-frameworks` also packs `dSYMs` and symbolmaps in the correct way on top of thinning any non necessary architectures and stripping symbols (strip -S) . I would advise against circumventing this step. Do so at your own risk.
