### ISSUE TITLE
Does carthage get binary framework multi-threaded download ?

### ISSUE THREAD

**Issue by devshen** [Carthage/Carthage#2727]
Does carthage get binary framework multi-threaded download ?

**Comment by blender** [comment]
I don't believe so. 
Dependencies are processed in order serially.

**Comment by ikesyo** [comment]
I think that is handled concurrently: https://github.com/Carthage/Carthage/blob/a5f34f431c3fb735826ccd016318c73bbf33273c/Source/CarthageKit/Project.swift#L1068-L1083

**Comment by blender** [comment]
@ikesyo Thanks for finding the right bit!
