### ISSUE TITLE
how to load local repo with relative path

### ISSUE THREAD

**Issue by a5978445** [Carthage/Carthage#2729]
* carthage install method: homebrew
* `which carthage`: 0.32.0
* `carthage version`:  0.32.0
* `xcodebuild -version`:  XCode10.1
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  no
* Are you using `--new-resolver`? no

**Cartfile**
```
#git "file:///Users/litengfang/Desktop/mobile_foundation_ios/Dependencies/MFNetworkKit" "MFNetworkKit/develop"
git "file://../../../Dependencies/MFNetworkKit" "MFNetworkKit/develop"
```

**Carthage Output**
```
A shell task (/usr/bin/env git clone --bare --quiet file://./../../Dependencies/MFNetworkKit /Users/litengfang/Library/Caches/org.carthage.CarthageKit/dependencies/MFNetworkKit) failed with exit code 128:
fatal: '/../../Dependencies/MFNetworkKit' does not appear to be a git repository
fatal: Could not read from remote repository.
```

i want use local repo with relative path , i'm sure the relative path is correct, but is can't load, when i use absolute path ,  it's ok.

**Comment by blender** [comment]
File scheme does not support relative paths. File scheme is always absolute.

**Comment by ikesyo** [comment]
Or maybe you are interested in https://github.com/Carthage/Carthage/issues/968 (without `file` scheme) which is not addressed yet.

**Comment by a5978445** [comment]
May I ask whether this feature will be added in the future

>provide the feature of load repo from local relative path

**Comment by blender** [comment]
@a5978445 maybe you can add it.
