### ISSUE TITLE
External Framework bridging from Objc to Swift

### ISSUE THREAD

**Issue by aabanaag** [Carthage/Carthage#2730]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.32.0
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
binary "https://aabanaag.github.io/Carthage/iOS/BRPtouchPrinterKit.json"
```

**Carthage Output**
```
<OUTPUT>
```

**Actual outcome**
The module installs properly

**Expected outcome**
The module I'm using only supports Objective-C. How should I package the binary framework in order to support swift?

**Comment by blender** [comment]
Obj-C and Swift are compatible by default. There are no extra steps.

**Comment by aabanaag** [comment]
Hi, I know this is closed already but just wondering if is it possible to add a bridging-header file to the zip. Like I previously stated the SDK I would like to use only supports Obj-C and from the sample and also the previous implementation I did I created a bridging-header file.
