### ISSUE TITLE
carthage hangs when git prompt has no where to go

### ISSUE THREAD

**Issue by potrebic** [Carthage/Carthage#2733]
* carthage install method: [ ] .pkg, [ X ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.32.0
* `xcodebuild -version`:  Xcode 10.1 Build version 10B61
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`?  Yes
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
-- SNIP --
git "git@gitenterprise.inside-box.net:Team/some-repo.git" "master"
-- SNIP --
```

**Carthage Output**
```
<Carthage hangs>
```

**Actual outcome**
We use GitHub Enterprise at Box. For a convoluted reason my known_hosts file got into a stale state. And this was causing carthage to silently hang on a git prompt of the the user (me)

Once I figured out the issue in ~/ssh/known_hosts file it was easy to see that git-prompt
```
$ git fetch     # when in the local repo that Carthage was attempting to manage
Warning: the RSA host key for 'gitenterprise.inside-box.net' differs from ' [ -- SNIP --]
Are you sure you want to continue connecting (yes/no)? no
```
Once I fixed the known_hosts file carthage worked fine again.

**Expected outcome**
Could carthage, given that these prompts are hidden, instead gracefully fail. I investigated solutions like `GIT_TERMINAL_PROMPT=0`, but that did NOT this prompt. So some other solution would be needed.

I looked at similar Issues like Issue 1617 and 1705. Those were looking for solutions to avoid prompts. Here I'm saying... if git never the less issues a prompt given that there's no way for a user to respond... carthage will hang. Wouldn't it be better to gracefully fail, giving the user a better picture as to the issue at hand. Thanks!

**Comment by ikesyo** [comment]
- `GIT_TERMINAL_PROMPT=0` is already specified: https://github.com/Carthage/Carthage/blob/0c4c64916f9505fd7fbcded6001e83915c572ecf/Source/CarthageKit/Git.swift#L52
- https://github.com/Carthage/Carthage/issues/1705#issuecomment-435270220 will be a possible solution.

**Comment by jlawton** [comment]
Yeah. It might have been unclear, but the above was saying that `GIT_TERMINAL_PROMPT` doesn't stop the prompt for `known_hosts`. I don't know of an option to prevent it, either.

**Comment by jlawton** [comment]
Ah. I tested the solution you suggest, and that appears to work.

**Comment by potrebic** [comment]
I tried the #1795 solution (env["GIT_SSH_COMMAND"] = "ssh -oBatchMode=yes")... and it didn't work for me. Must have done something incorrectly.

**Comment by potrebic** [comment]
I just tried that solution (apparently correctly this time) and it worked. `git` failed instead of prompting!

**Comment by potrebic** [comment]
Given that https://github.com/Carthage/Carthage/pull/2734 was approved. I'll Close this Issue. Thanks!
