### ISSUE TITLE
Can build with `Scheme.ArchiveAction.buildConfiguration` of xcscheme file?

### ISSUE THREAD

**Issue by sugarwyc** [Carthage/Carthage#2744]
![79D45853-5BF7-439E-AE49-B8A76B71567A](https://user-images.githubusercontent.com/5518603/54968802-eb30d900-4fb6-11e9-83a1-7562d625dbb7.png)

**Comment by mdiep** [comment]
`carthage` has a `--configuration` flag that you can use

**Comment by sugarwyc** [comment]
`--configuration` flag will be applied to all, does not match my needs. There are multiple xcsheme files in a project, they may have different `configuration`.

**Comment by sugarwyc** [comment]
> `carthage` has a `--configuration` flag that you can use

@mdiep thank you for your reply! The `--configuration` flag will be applied to all, does not match my needs. There are multiple xcsheme files in a project, they may have different `configuration`.

**Comment by mdiep** [comment]
You could rebuild that project specifically. `carthage build --configuration Release-Custom custom-project`

**Comment by sugarwyc** [comment]
> You could rebuild that project specifically. `carthage build --configuration Release-Custom custom-project`

@mdiep thank you for your reply! 

But a project may have many different configurations：
- custom-project
     - custom1.xcscheme with configuration `Release-Custom1`
     - custom2.xcscheme with configuration `Release-Custom2`

**Comment by mdiep** [comment]
That's the limit of Carthage's support for this. 🤷🏻‍♂️

**Comment by sugarwyc** [comment]
@mdiep 

Or can it be like this?
`carthage build --scheme custom1 --configuration Release-Custom1 custom-project`
`carthage build --scheme custom2 --configuration Release-Custom2 custom-project`

**Comment by mdiep** [comment]
Carthage does not expose schemes
