### ISSUE TITLE
Swift 5 errors - bridging errors in Dynamic Framework

### ISSUE THREAD

**Issue by agiguere** [Carthage/Carthage#2745]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`:
* `carthage version`: 0.32
* `xcodebuild -version`: 
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

with the new release of Xcode 10.2 and Swift 5, I was able to compile successfully my dynamic framework but my apps that are referencing to it (after a carthage update) failed,

in my project, the xxx-swift.h interface bridging file

I could see my operation subclasses but Xcode don't know if they are related to PSOperations or NSOperations

Example:

```
SWIFT_CLASS("_TtC9Dollarama14ParseOperation")
@interface ParseOperation : Operation
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end
```
Cannot find interface declaration for 'Operation', superclass of 'ParseOperation'; did you mean 'NSOperation'?

thanks

**Comment by paulosaure** [comment]
Hi, why did you close this issue ? Have you find a workaround ?

**Comment by paulosaure** [comment]
@agiguere  Hi, why did you close this issue ? Have you find a workaround ?

**Comment by agiguere** [comment]
I posted in at the wrong place, I am pretty sure it's related to the dependancy PSOperations

I reposted the question here
https://github.com/pluralsight/PSOperations/issues/121

no I did not find a workaround yet, let me know if you find something

thanks

alex

**Comment by paulosaure** [comment]
We also have the same problem with our project ... https://github.com/socketio/socket.io-client-swift/issues/1175

It seems related to carthage

**Comment by DavidBrunow** [comment]
I believe what y'all are seeing is related to this pull request: https://github.com/Carthage/Carthage/pull/2723

The fix was merged to master but there hasn't been a new release yet -- I believe the Carthage folks have one planned for this week.

**Comment by agiguere** [comment]
on my side I was able to replicate the problem in a small project now on my GitHub Account

https://github.com/agiguere/MySwift5Framework

I am not sure yet if it's related to Carthage or my PSOperations dependancy

thanks

**Comment by ikesyo** [comment]
As @DavidBrunow said, this is a dupe of #2718 and addressed in #2723. Please wait a new release for a while or you can build and install a master branch of this repository buy `make install`.

**Comment by DavidBrunow** [comment]
@ikesyo I think that `master` has a different bug that needs to be resolved by merging in the revert in https://github.com/Carthage/Carthage/tree/revert-authorization-header-for-redirected-requests

**Comment by agiguere** [comment]
@DavidBrunow  any news on when the new version of carthage will be available? thanks

**Comment by DavidBrunow** [comment]
@agiguere sorry I don’t have any insight into that — I’ve contributed code but I’m not part of the Carthage team.

**Comment by agiguere** [comment]
@DavidBrunow  np, ok thanks!

**Comment by mdiep** [comment]
We're working on it, but the ABI stability in Swift 5 has ironically made this release a little more difficult. :)
