### ISSUE TITLE
Carthage builds framework with header missing iphonesimulator archs

### ISSUE THREAD

**Issue by Ogerets** [Carthage/Carthage#2747]
* carthage install method: .pkg
* `which carthage`:
/usr/local/bin/carthage
* `carthage version`: 
0.32.0
* `xcodebuild -version`: 
Xcode 10.2
Build version 10E125
* Are you using `--no-build`? 
no
* Are you using `--no-use-binaries`? 
no
* Are you using `--use-submodules`? 
no
* Are you using `--cache-builds`? 
no
* Are you using `--new-resolver`? 
no

**Cartfile**
e.g.
```
github "VirgilSecurity/virgil-cryptoapi-x" ~> 1.0
```

**Actual outcome**
For some reason carthage builds framework with header missing declarations for iphone simulator architecture. So it's impossible to use framework from objc code on simulator.

**Expected outcome**
Carthage should build framework with header with declarations for every architecture.

**Comment by DavidBrunow** [comment]
Hi @Ogerets! This looks like a duplicate of this issue which has been merged to master but hasn't been released yet: https://github.com/Carthage/Carthage/issues/2718

I believe the Carthage team is planning a release this week.

**Comment by xuwenquan** [comment]
I am expecting a new release too. After I upgraded xcode 10.2, I fail to build my codebase.

**Comment by blender** [comment]
Duplicate of #2718
