### ISSUE TITLE
Can't build with Carthage with Xcode 10.2, 10.1, 10

### ISSUE THREAD

**Issue by classified** [Carthage/Carthage#2749]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.32.0 
* `xcodebuild -version`: Xcode 10.2 Build version 10E125
* Are you using `--no-build`? N
* Are you using `--no-use-binaries`? N
* Are you using `--use-submodules`? N
* Are you using `--cache-builds`? N
* Are you using `--new-resolver`? N

**Cartfile**
```
github "particle-iot/particle-setup-ios" ~> 0.9.0
```

**Carthage Output**
```
** Fetching particle-setup-ios
*** Fetching particle-sdk-ios
*** Fetching onepassword-extension
*** Fetching AFNetworking
*** Checking out particle-setup-ios at "0.9.0"
*** Checking out AFNetworking at "3.2.1"
*** Checking out particle-sdk-ios at "0.8.1"
*** Checking out onepassword-extension at "bcc4cc97fed9a6e73fa204f2e61138e353cb3ef7"
*** xcodebuild output can be found in /var/folders/bs/mk37gxpj5vl56b207lsx82x00000gp/T/carthage-xcodebuild.DUgsCL.log
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/rajan.palaniya/Desktop/sample/ios-app-example-carthage/Carthage/Checkouts/AFNetworking/AFNetworking.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 6:
dyld: Library not loaded: /usr/local/lib/libwep
  Referenced from: /usr/bin/xcrun
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libwep: code signature in (/usr/local/lib/libwep) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/lib/libwep: stat() failed with errno=1
```

**Actual outcome**
Build exited with code = 6

**Expected outcome**
Should be able to generate frameworks

<img width="1680" alt="Screenshot 2019-03-29 at 12 17 28 PM" src="https://user-images.githubusercontent.com/1496524/55214544-0dc42b80-521d-11e9-8aaa-fea2f0b2a3c3.png">

**Comment by blender** [comment]
Have you looked into the log file? Have you tried to build the project using the same command Carthage issues to xcodebuild?

**Comment by classified** [comment]
> Have you looked into the log file? Have you tried to build the project using the same command Carthage issues to xcodebuild?

Log file is empty & Yes I tried to build and it worked

**Comment by blender** [comment]
libwebp is not found on your system. This is not a Carthage issue.
