### ISSUE TITLE
carthage update fetches old version of realm/realm-cocoa

### ISSUE THREAD

**Issue by Jachobsen** [Carthage/Carthage#275]
First posted in https://github.com/realm/realm-cocoa/issues/1313

When trying to install realm through Carthage, I get the following error:
```sh
$ carthage update
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "b30"
*** xcodebuild output can be found in /var/folders/rg/9gzvgrx177j1ldg25s71m6d40000gn/T/carthage-xcodebuild.OyBEi0.log
Project "TightDbObjcDyn.xcodeproj" has no shared schemes
```

The log is empty.

My Cartfile only contains this:
```
github "realm/realm-cocoa"
```

[b30](https://github.com/realm/realm-cocoa/releases/tag/b30) is an old tag. If I clone the latest tag ([v0.89.2](https://github.com/realm/realm-cocoa/releases/tag/v0.89.2)) manually and run `carthage build --no-skip-current` it builds the repo just fine.

I've tried changing my Cartfile to:

```
github "realm/realm-cocoa" >= 0.89
```

But it still checks out "b30"

---

Carthage v. 0.5.1 installed via Homebrew on OSX 10.10.2 with XCode 6.1.1

**Comment by jspahrsummers** [comment]
This is because Carthage tries to interpret each tag as a semantic version. If we're talking about semantic versioning, 30[.0.0] is greater than 0.89[.0].

The potential workarounds here include:

 1. Renaming or deleting the tags
 1. Forking the repository and only keeping the tags you want to use
 1. Specifying an exact version in your Cartfile

**Comment by Jachobsen** [comment]
Thank you for the clarification.

I've changed my Cartfile to:

```
github "realm/realm-cocoa" == 0.89.2
```

and `carthage update` builds the specified tag.

**Comment by jpsim** [comment]
I'm looking into whether or not anyone relies on these old b3-b30 tags and if not, we'll rename them to v0.0.3-v0.0.30 to make it compatible with Carthage.

**Comment by jspahrsummers** [comment]
:sparkles:

**Comment by jpsim** [comment]
We've renamed our old releases of the b* format to v0.0.*, which now makes Realm play nice with Carthage's version parsing.

**Comment by jspahrsummers** [comment]
@jpsim Thanks!
