### ISSUE TITLE
'copy-frameworks' command fails when archiving an macOS application

### ISSUE THREAD

**Issue by bafnaparag** [Carthage/Carthage#2750]
* carthage install method: [ ] .pkg, [x] homebrew, [] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.32.0
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "CocoaLumberjack/CocoaLumberjack"
```

I am able to run project via xcode but archive is failing with below error 
```
A shell task (/usr/bin/xcrun codesign --force --sign  --preserve-metadata=identifier,entitlements Path/myApp.app/Contents/Frameworks/CocoaLumberjack.framework) failed with exit code 1:
Path/myApp.app/Contents/Frameworks/CocoaLumberjack.framework: bundle format is ambiguous (could be app or framework)

Command PhaseScriptExecution failed with a nonzero exit code
```

<img width="264" alt="Screen Shot 2019-03-29 at 17 46 37" src="https://user-images.githubusercontent.com/5251877/55232148-a0c78a80-524a-11e9-8112-b246bb2455e0.png">

**Comment by ikesyo** [comment]
You don't need copy-frameworks for macOS application at all.

**Comment by bafnaparag** [comment]
Its Friday.
