### ISSUE TITLE
Can't build Carthage with ReactiveSwift Xcode 10.2

### ISSUE THREAD

**Issue by codepgq** [Carthage/Carthage#2755]
Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos12.2
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Planning build
note: Constructing build description

CompileSwift normal arm64 (in target: ReactiveSwift-iOS)
    cd ...Carthage/Checkouts/ReactiveSwift
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -emit-bc ...Carthage/Checkouts/ReactiveSwift/Sources/Signal.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Optional.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Disposable.swift ...Carthage/Checkouts/ReactiveSwift/Sources/SignalProducer.swift ...Carthage/Checkouts/ReactiveSwift/Sources/ValidatingProperty.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Deprecations+Removals.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Observer.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Reactive.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Flatten.swift ...Carthage/Checkouts/ReactiveSwift/Sources/UninhabitedTypeGuards.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Lifetime.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Property.swift ...Carthage/Checkouts/ReactiveSwift/Sources/FoundationExtensions.swift ...Carthage/Checkouts/ReactiveSwift/Sources/ResultExtensions.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Event.swift ...Carthage/Checkouts/ReactiveSwift/Sources/EventLogger.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Atomic.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Scheduler.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Bag.swift ...Carthage/Checkouts/ReactiveSwift/Sources/Action.swift ...Carthage/Checkouts/ReactiveSwift/Sources/UnidirectionalBinding.swift -supplementary-output-file-map /var/folders/l8/zc8808q119d82s3ybqhfhrqh0000gn/T/supplementaryOutputs-121b5a -target arm64-apple-ios8.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -I /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/BuildProductsPath/Release-iphoneos -F /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/BuildProductsPath/Release-iphoneos -application-extension -g -import-underlying-module -module-cache-path /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/ModuleCache.noindex -warnings-as-errors -swift-version 4 -enforce-exclusivity=checked -O -serialize-debugging-options -Xcc -working-directory -Xcc ...Carthage/Checkouts/ReactiveSwift -enable-anonymous-context-mangled-names -Xcc -I/Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/ReactiveSwift-generated-files.hmap -Xcc -I/Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/ReactiveSwift-own-target-headers.hmap -Xcc -I/Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/ReactiveSwift-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/ReactiveSwift-project-headers.hmap -Xcc -I/Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/UninstalledProducts/include -Xcc -I/Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/DerivedSources-normal/arm64 -Xcc -I/Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/DerivedSources/arm64 -Xcc -I/Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/DerivedSources -Xcc -DNDEBUG=1 -Xcc -ivfsoverlay -Xcc /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/unextended-module-overlay.yaml -module-name ReactiveSwift -num-threads 4 -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Signal.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Optional.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Disposable.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/SignalProducer.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/ValidatingProperty.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Deprecations+Removals.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Observer.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Reactive.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Flatten.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/UninhabitedTypeGuards.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Lifetime.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Property.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/FoundationExtensions.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/ResultExtensions.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Event.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/EventLogger.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Atomic.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Scheduler.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Bag.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/Action.bc -o /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/arm64/UnidirectionalBinding.bc
...Carthage/Checkouts/ReactiveSwift/Sources/Scheduler.swift:187:18: error: 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'DispatchSourceTimerWrapper' to 'Hashable' by implementing 'hash(into:)' instead
        fileprivate var hashValue: Int {
                        ^

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(3 failures)

**Comment by codepgq** [comment]
-scheme ReactiveSwift-iOS -configuration Release -derivedDataPath /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/l8/zc8808q119d82s3ybqhfhrqh0000gn/T/ReactiveSwift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xxx/Carthage/Checkouts/ReactiveSwift)

This usually indicates that project itself failed to compile.

**Comment by ikesyo** [comment]
That is not RxSwift but ReactiveSwift. And also that is already addressed in https://github.com/ReactiveCocoa/ReactiveSwift/pull/707. Please update to ReactiveSwift 5.0.
