### ISSUE TITLE
Sub-10.14.4 Mojave without Xcode 10.2+ at /Applications/Xcode.app built with Swift 5 · Carthage 0.33.0 crashes with homebrew

### ISSUE THREAD

**Issue by petergp** [Carthage/Carthage#2757]
Carthage 0.33.0 crashes when installed with homebrew.

Installing the `.pkg` works fine.

* carthage install method: [ ] .pkg, [x] homebrew, [] source
* `which carthage`:
* `carthage version`:  0.33.0
* `xcodebuild -version`: 10.2

**Actual outcome**
```
brew install carthage
carthage version

dyld: lazy symbol binding failed: Symbol not found: _swift_initClassMetadata2
  Referenced from: /usr/local/bin/carthage
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib

dyld: Symbol not found: _swift_initClassMetadata2
  Referenced from: /usr/local/bin/carthage
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib

Received 'abort trap' signal
```

**Comment by jdhealy** [comment]
Thanks for the report.

This only happens on sub-10.14.4-versions of Mojave, you can workaround this short-tem by placing a copy of Xcode 10.2 at `/Applications/Xcode.app` or long-term by `xcode-select`ing Xcode 10.1 and running `brew uninstall --force carthage && brew install --build-from-source carthage`.

**Comment by jdhealy** [comment]
[Landed a PR](https://github.com/Homebrew/homebrew-core/pull/38656).

Anyone can now `brew update && brew uninstall --force carthage && HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK=true brew install --force-bottle carthage` to remedy this.

**Comment by petergp** [comment]
Thanks for amazingly fast response on this one @jdhealy 

I can confirm that doing a `brew update` fixes the problem.
