### ISSUE TITLE
Fix merging Swift header files for Xcode 10.2 - not (yet) working

### ISSUE THREAD

**Issue by ChristianSteffens** [Carthage/Carthage#2758]
* carthage install method: [x] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 10.2 Build version 10E125
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile MainProject**
```
git "git@git.*.de:ourProject/subProject.git" "develop"
```

**Cartfile SubProject**
```
git "git@git.*.de:ourProject/otherSubProject.git" "develop"
```

**Cartfile OtherSubProject**
```
github "realm/realm-cocoa" == 3.14.0
```

**Carthage Output**
While running `carthage update --platform iOS --configuration Debug` in the MainProject. 

```
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/otherSubProject-Swift.h"
        ^
/Users/csteff/Repositories/mainProject/Carthage/Checkouts/subProject/Carthage/Build/iOS/otherSubProject.framework/Headers/otherSubProject-Swift.h:193:36: error: cannot find interface declaration for 'RealmSwiftObject', superclass of 'MyOwnClass'
@interface MyOwnClass : RealmSwiftObject
...
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(227 failures)
```

**Actual outcome**
Carthage was not able to build / update the framework.

**Expected outcome**
Carthage should - well - build the framework.

So some more details
- MainProject is also a Framework itself
- It uses a SubProject / Framework which itself depends on another framework / OtherSubProject
- The OtherSubProject depends on Realm and that's where the error comes from while building

As I understood Xcode 10.2 changed the way the header files for frameworks are generated. But it seems the latest carthage release should address this issue by merging the simulator and device header files into one generic header file.

This seems to work for (Other)SubProject, but not for the MainProject. Is this some kind of restriction how "far" the PR regarding the header-issue actually works?

It seems the header file for the Realm(Swift) framework in the MainProject Carthage output directory is faulty:

```
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.0 effective-4.1.50 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
...
#endif
```

Instead of `#if 0` there should be `#if TARGET_OS_SIMULATOR`? The Realm frameworks header files for SubProject and OtherSubProject both contain the correct if-statement. But the Realm frameworks header file in the MainProject Carthage output doesn't has this statement.

**Comment by DavidBrunow** [comment]
Would you be able to share the first few lines of “Headers/otherSubProject-Swift.h” in your Carthage/Build folder?

**Comment by ChristianSteffens** [comment]
By now I'm pretty sure the prebuilt Realm Release `3.14` is the problem as the `#if 0` line is already present in there. I'm creating the prebuilt binary / frameworks myself now. I'll give you an update then.

**Comment by ChristianSteffens** [comment]
So I pulled the latest Realm Release (`3.14.1`), then built it and finaly run `carthage build` and this is the final [RealmSwift-Swift.h](https://gist.github.com/ChristianSteffens/402630a28307bef8b607010137f87a44).

**Comment by DavidBrunow** [comment]
I’m looking on my phone so I can’t be sure but the structure of the file looks right.

**Comment by ChristianSteffens** [comment]
Well, the issue has been solved with latest [Realm Release](https://github.com/realm/realm-cocoa/releases/tag/v3.14.1) `3.14.1`. Thanks a lot anyhow.

**Comment by Larmichou** [comment]
Considering the [fix](https://github.com/realm/realm-cocoa/commit/fb9e8bc4448bdc4e7ab4fb36cff4ee676102a9e8#diff-0b83f9dedf40d7356e5ca147a077acb4) being a manual update of headers from Realm parts, due to a [Known issue with XCode 10.2](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes?language=objc#topics):

```
    # Xcode 10.2 merges the generated headers together with ifdef guards for
     # each of the target platforms. This doesn't handle merging
     # device/simulator builds, so we need to take care of that ourselves.
     # Currently all platforms have identical headers, so we just pick one and
     # use that rather than merging, but this may change in the future.
     if [ -f $os_path/Headers/$module_name-Swift.h ]; then
       unique_headers=$(find $build_intermediates_path -name $module_name-Swift.h -exec shasum {} \; | cut -d' ' -f 1 | uniq | grep -c '^')
       if [ $unique_headers != "1" ]; then
         echo "Platform-specific Swift generated headers are not identical. Merging them is required and is not yet implemented."
         exit 1
       fi
       find $build_intermediates_path -name $module_name-Swift.h -exec cp {} $os_path/Headers \; -quit
     fi
```

Should this [commit](https://github.com/Carthage/Carthage/commit/3aad8e7985a38244627d6349069097db2d0fd06f) (or rather the method) be modified on Carthage handle also that case?
