### ISSUE TITLE
how can i generate just one framework file including dependency framework

### ISSUE THREAD

**Issue by tooolkit** [Carthage/Carthage#2769]
i use cocoapods create a library
pod lib create XXXLib
add some dependency in podspec file
like Protobuf, Realm
in Xcode manage scheme i select all to  Shared
then i use `carthage build --no-skip-current  --platform ios `to generate framework
i got XXXLib.framework Protobuf.framework Realm.framework

can i get just one framework XXXLib.framework that including the protobuf and realm?

**Comment by blender** [comment]
No
