### ISSUE TITLE
`carthage help copy-frameworks` tries to execute the command

### ISSUE THREAD

**Issue by mattrubin** [Carthage/Carthage#277]
When I run `carthage help copy-frameworks` (with 0.5.1), I see the following result:
```
In a Run Script build phase, copies each framework specified by an SCRIPT_INPUT_FILE environment variable into the built app bundle

Environment variable not set: SCRIPT_INPUT_FILE_COUNT
```
It appears that when I request help with the `copy-frameworks` command, Carthage tries to run that command, but fails when it can't find the environment variable.

---
Looking closer, I've tracked down the cause of issue: `HelpCommand` [calls `command.run(.Usage)`](https://github.com/Carthage/Commandant/blob/master/Commandant/HelpCommand.swift#L38-40), but `CopyFrameworksCommand` completely [ignores the `mode` argument](https://github.com/Carthage/Carthage/blob/master/Source/carthage/CopyFrameworks.swift#L20-39) and tries to actually execute the command.

**Comment by masterofdaemon** [comment]
i have this error in v0.15

**Comment by masterofdaemon** [comment]
carthage copy-frameworks
Environment variable not set: SCRIPT_INPUT_FILE_COUNT

**Comment by mdiep** [comment]
It looks like you ran `carthage copy-frameworks`, not `carthage help copy-frameworks`.

**Comment by masterofdaemon** [comment]
yes but why am i get this? and here is output with help:
carthage help copy-frameworks
In a Run Script build phase, copies each framework specified by a SCRIPT_INPUT_FILE environment variable into the built app bundle

**Comment by masterofdaemon** [comment]
what is SCRIPT_INPUT_FILE?I can't get why i get error lib don't load because of image, some say i need to enter: carthage copy-frameworks

**Comment by masterofdaemon** [comment]
here https://www.youtube.com/watch?v=NNH8uVvng1w it's not working for me, but i'm trying to make OS X pros

**Comment by mdiep** [comment]
There's some documentation about `copy-frameworks` [in the README](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos).

**Comment by masterofdaemon** [comment]
don't saw how to set: SCRIPT_INPUT_FILE_COUNT

**Comment by karstengresch** [comment]
It's an old entry, but just for others stumbling on this issue: I had to manually delete the project output folder under

`/Users/<myname>/Library/Developer/Xcode/DerivedData/`

e.g. 

`/Users/<myname>/Library/Developer/Xcode/DerivedData/MyProjectName-cylnlgfgbytvangqgvwrnlrxeljc`

to get rid of this problem.
