### ISSUE TITLE
Are there any plans (or interest in contribution) of command line interface allowing to perform actions from command line without creating a Cartfile first? 

### ISSUE THREAD

**Issue by zats** [Carthage/Carthage#2771]
My workflow is typically a mix of several dependency management tools because various libraries/frameworks require massaging before getting integrated into a project.
I was thinking that checking in a build artifact (or submodule with source if nesseseary might be a good solution minimizing footprint carthage leaves on the disk, allowing to download only necessary library, without recording any information about its version on the disk

Something similar to

```
$ carthage-cli github nst/ShapefileReader --no-build
```

I'm guessing it's always possible to fork carthage and create such tool external, but before doing so I was curious if there's interest (maybe even plans) in making it a part of the core tool
Thanks

**Comment by mdiep** [comment]
I don't think that'd be used widely enough to warrant inclusion in Carthage.

But you can use Carthage as a dependency. And if you make a `carthage-foo` binary, then you can call it as `carthage foo`. So I think you could easily build this as an extension of Carthage without forking.

**Comment by zats** [comment]
Makes sense. Thanks!
