### ISSUE TITLE
Best practice for using prebuilt binary dependencies for private repos

### ISSUE THREAD

**Issue by njuxjy** [Carthage/Carthage#2772]
Our project has a bunch of carthage dependencies that are served on our own git repos (not github). For speeding up the building process, we prebuilt a binary version for each framework and maintain a binary repo specifically for all the binaries. 

In Cartfile, all dependencies are specified like below:

##############
#RxSwift
binary "https://gitlab.mycompany.com/iOSPrebuildFramework/raw/master/RxSwift/RxSwift.json"

#SwiftyJSON
binary "https://gitlab.mycompany.com/iOSPrebuildFramework/raw/master/SwiftyJSON/SwiftyJSON.json"
...
##############

This works all good until each time Xcode releases a new version which causes the Swift toolchain version to upgrade as well. Running `carthage bootstrap` will give the `incompatible swift version` error.  I'd have to either upgrade all binaries for all frameworks (which is a pain if manually), or specify dependencies as source code in Cartfile (which is too slow to bear). 

For github repos, we can use `--use-binaries` and `--no-use-binaries` parameters to choose between downloading binaries or source code, not sure if there's such choice for private repos. 
Even if we can use `--use-binaries` for private repos, it is still not as fast as `binary "https://xxx.com/xxx.json"` because it still has to do `git clone` first, while `binary xxx` does not. 

So what might be the best practice for considering both effeciency and maintainence cost?

**Comment by MrNeekReevers** [comment]
We do the same thing as you do with regards to our local frameworks. We even version stuff off of GitHub and put the frameworks into Artifactory and have our Carthage scripts pull based off of version:
`binary "https://ourserver.com/Realm.json" == 3.14.1`
My hope is that with Swift 5's ABI Stability in iOS, this round of rebuilding everything will be the last time we have to do this since all future versions of Swift will be able to read the interface of the frameworks built in Swift 5.x.

**Comment by njuxjy** [comment]
Hopefully ABI stability could save my ass.
For now our project is still in Swift 4.2 and I made all binaries with Xcode 10.2. 
But as soon as Xcode was upgraded to 10.2.1, same error occurred, complaining: "framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)."

I have to keep both versions of Xcode installed and use 10.2 for CLI cuz I don't want previous work to be wasted. Maybe I will try again after upgrading the whole project to Swift 5.

**Comment by blender** [comment]
@njuxjy --use-binaries and --no-use-binaries are only available for Github.com a and enterprise.

If you are looking to speed up your builds you can take a look if this https://github.com/blender/Rome/ can help you.

**Comment by njuxjy** [comment]
@blender Thanks, will check the link

**Comment by njuxjy** [comment]
@blender Forgot to mention that I'm the only dev on that project. Rome seems to be a great tool designed to save other devs' time by downloading prebuilt frameworks from one dev. 
In single dev case, the flow seems to be:

1. use carthage to build from source and upload the cache for the first time.
2. then on the CI machine download the cache and skip the build process. 
3. Then when there's a new version of Xcode which invalidates all the caches, just go to 1. 

In this workflow, the biggest advantage seems to be when there being a need to update all frameworks, Rome can serve as an automation tool, otherwise the dev might have to iterate all frameworks source, build and upload one by one manually.

Also for Rome it seems only s3 can be used to serve the cache, is it possible to serve the cache in-house, like in a private git repo?

**Comment by blender** [comment]
> 3. Then when there's a new version of Xcode which invalidates all the caches, just go to 1
If you build your frameworks on CI on each build you can just upload so switching versions will ve transparent to you as `xcode-select` a new Xcode.

> Also for Rome it seems only s3 can be used to serve the cache, is it possible to serve the cache in-house, like in a private git repo?

You can set up https://www.min.io/ if you want to use a "remote" cache (but not s3) or you can use any part of your local filesystem (or fuse or samba or nfs...)

**Comment by werner77** [comment]
See our fork https://github.com/nsoperations/Carthage which fixes a lot of caching issues. In particular:

- support for custom pluggable caching has been added
- caching now supports different swift versions and both caching of Debug and Release build configurations
- dsym build locations are mapped to the actual source location on the develop's machine to facilitate debugging with pre-built binaries

In short this would allow you to just specify source level dependencies in your Cartfile, while the custom cache script would connect to your private caching repository. 

`carthage bootstrap --cache-command /some/custom/cache-script.sh`

```
[--cache-command (string)]
	custom command to execute to download cached (binary) dependencies from a custom cache store. Five environment variables will be set which can be used by the command if needed: [CARTHAGE_CACHE_DEPENDENCY_NAME, CARTHAGE_CACHE_DEPENDENCY_VERSION, CARTHAGE_CACHE_BUILD_CONFIGURATION, CARTHAGE_CACHE_SWIFT_VERSION, CARTHAGE_CACHE_TARGET_FILE_PATH]. The executable should move the cached file to the targetFilePath if successful and return a non-zero exit code otherwise. The CARTHAGE_CACHE_COMMAND environment variable is read for a default for this value. If not specified, caching will revert to caching based on the GitHub API which only works for GitHub dependencies.
```

**Comment by mdiep** [comment]
@werner77 Please stop commenting on Carthage issues to advertise your fork. This creates additional noise that Carthage maintainers need to wade through.

**Comment by werner77** [comment]
Sure just trying to help people who experience similar problems as us to a working solution.

**Comment by njuxjy** [comment]
@werner77 Thank you for the suggestion.
Unfortunately your forked version doesn't seem to resolve my issue. I still had to pull and build from source for the first time and used caches later. Every member of the team would have to pull and build from source for at least once. 

@MrNeekReevers Unfortunately the issue still exists when upgrading to Swift 5. Today I upgraded all carthage dependencies to Swift 5 with Xcode 10.2.  But it reported the following error when I switched to Xcode 10.2.1 and ran carthage update:

> Incompatible Swift version - framework was built with 5.0 and the local version is 5.0.1.

**Comment by werner77** [comment]
@njuxjy Did you use a cache command and if so how did you implement it? The cached version should exist and be built with the same build configuration/swift toolchain version. Even 5.0 and 5.0.1 cannot be assumed modular compatible (please read my recent question about this here on the Swift forum: https://forums.swift.org/t/swift-org-blog-abi-stability-and-more/20250/18).
