### ISSUE TITLE
How will Carthage work For iOS?

### ISSUE THREAD

**Issue by vermasagar49** [Carthage/Carthage#2773]
Today I found funny issue either in Carthage or in Xcode. 

No Idea either this issue is for Xcode or carthage.

Description : 

1 ) create new project in Xcode
2 ) touch carthage
3) add dependencies in cart file
4) update carthage (code is downloaded and build is generated)
5)  import mouble in any class of Swift
6 ) compile time error module not found
7) link module with Xcode as (linked framework and libraries) 
8) after step 7 code is compiled if I am import the module (dependent module).
///// all good till now
9) remove linked module and clean the project.
10) Now again able to compile the code and using the dependent module inside App (In this I did not understood how things are working). Means If I have removed linked binary then how it is linking to project.

**Comment by blender** [comment]
It's autolinking from derived data.

**Comment by vermasagar49** [comment]
> It's autolinking from derived data.
> 
> I don't however understand your question. Can you be more clear?
> If this is about how to use Carthage, have you followed https://github.com/Carthage/Carthage#quick-start ?

I have deleted the derived data and clean the project then also it is working

**Comment by vermasagar49** [comment]
https://github.com/Carthage/Carthage#quick-start

In this *Adding frameworks to an application*
 *If you're building for OS X*

In new creating project if we follow the providing step all things are working

And I un-link the  Embedded Binaries and also from Linked Framework and Libraries 
then how it is linking after doing un-link the libraries

**Comment by blender** [comment]
You can check yourself by looking at the .swiftdeps files in Object-Normal.

Btw, this has nothing to do with Carthage. You're asking how linking works and how Xcode discovers dependencies.
