### ISSUE TITLE
Listing all dependencies.

### ISSUE THREAD

**Issue by llinardos** [Carthage/Carthage#2775]
This is more a question than an issue. Given a cartfie, is there a way to know all the dependencies, including nested?

As an example, if cartfile declares A, B and C; B has a cartfile declaring D and E; and E has a cartfile declaring F:

`1.` Is there a way of know that all the dependencies are A, B, C, D, E and F?

`2.` Is there a way of know that A has no nested dependencies, B depends on D, E and F, and C has no nested dependencies?

I think that `1.` can be "solved" looking the contents of the /Carthage/Build folder after a `carthage bootstrap` or `carthage update`. No idea of how to solve `2.`.

**Comment by blender** [comment]
If I understand correctly your questions:

1. Yes, it is literally the Cartfile.resolved 
2. No, this information is not exposed

**Comment by kenji21** [comment]
For point 2, I was thinking of a `carthage tree` command that shows an "ASCII art" graph with version

For example, if you have RxAlamofire and AlamofireObjectMapper (on their current master):
https://github.com/RxSwiftCommunity/RxAlamofire/blob/master/Cartfile.resolved "points to" "Alamofire/Alamofire" "4.8.2"
https://github.com/tristanhimmelman/AlamofireObjectMapper/blob/master/Cartfile.resolved "points to" "Alamofire/Alamofire" "5.0.0-beta.2"

So you should point AlamofireObjectMapper  to version 5.2.1 (or 5.x) (https://github.com/tristanhimmelman/AlamofireObjectMapper/blob/5.2.1/Cartfile.resolved), and RxAlamofire to 4.4.1 (4.x) (https://github.com/RxSwiftCommunity/RxAlamofire/blob/4.4.1/Cartfile.resolved) which both "points to" Alamofire 4.8.2 (4.x)

Having the "tree" displayed before the building of each dependencies maybe could help knowing/understanding "solved" version.

**Comment by blender** [comment]
This is overlapping with the resolver diagnostic #2519
