### ISSUE TITLE
Carthage 0.33.0 via pkg on GitHub Release not including TargetConditional.h conditional import.

### ISSUE THREAD

**Issue by edfanhouse** [Carthage/Carthage#2779]
* carthage install method: pkg
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 10.2.1
* `command`: carthage build --no-skip-current

Hello,

We discover an issue with the last Carthage version installed with package method. It would seem the merge of #2718 is not included in the package version. When we build a framework, the 3 lines in header swift file are missing. 

However, when we install Carthage with homebrew method, lines are included in the built framework.

**Comment by jdhealy** [comment]
Thanks for discovering this issue —

The original [Carthage.pkg for 0.33.0](https://github.com/Carthage/Carthage/releases/tag/0.33.0) (md5 `a8c0afaf3bce926eb6cd358d2e6b45fe`) was missing commits included in the tag at c8ac06e.

The only codewise commits missing were from #2748 which deals with `TargetConditionals.h`. Some frameworks compiled via this `a8c0afaf3bce926eb6cd358d2e6b45fe` Carthage.pkg would succeed using the (verified included) code from #2723, while others which necessitated #2748 would hit failures not seen by, say, the homebrew distribution of 0.33.0.

You can check whether the `carthage` in your path includes #2748 with —
```shell
strings "$(which carthage)" | grep --count 'TargetConditionals' || echo 'Carthage pull #2748 not included.'
```

A newly assembled [Carthage.pkg has been uploaded for 0.33.0](https://github.com/Carthage/Carthage/releases/tag/0.33.0) (md5 `e7823fd808de31b2b8ace0f1bab7a800`) and can be installed overwriting the errant release.

Apologies for the mishap.
