### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation) in Xcode Framework Project 

### ISSUE THREAD

**Issue by paulomo** [Carthage/Carthage#2782]
* carthage install method: homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 10.2.1, Build version 10E1001
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  Yes
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
<img width="796" alt="Screen Shot 2019-05-04 at 8 59 15 PM" src="https://user-images.githubusercontent.com/37729297/57186564-87e86f80-6eaf-11e9-903b-941227c09f86.png">

**Carthage Output**
<img width="1052" alt="Screen Shot 2019-05-04 at 9 02 17 PM" src="https://user-images.githubusercontent.com/37729297/57186595-ec0b3380-6eaf-11e9-96b7-854d18b126a8.png">

**Actual outcome**
Project is saying RxSwift and other Rx Framework not found

**Expected outcome**
Is suppose to be added as it did for project.

**Comment by paulomo** [comment]
Project setup and what I have done already:
I need some guidance on how to fix a linker issue I am having after I added RxSwift with Carthage to a framework project. So I started the project by first creating a workspace then added a project to the workspace and then features of the app i am building as frameworks. So when I added RxSwift to the project I got the error. I am using RxSwift 5.0.1, update Carthage to version 0.33.0 with Home brew and ensured that scheme in Rx.workspace is shared. I also set 'Reflective Metadata Level' to None and 'Enable Bitcode' to No. I shared some images here of the error. Any advice or suggestion will be highly appreciated.

**Comment by blender** [comment]
Have you followed the readme?

**Comment by paulomo** [comment]
@blender I did read it. But may i am missing something... Please do let me know?

**Comment by paulomo** [comment]
@blender I am thinking it's the way I setup my project.... I started with a workspace, then added a project and then I added RxSwift with Carthage. Doing this causes the error. I tried it with a new application and I had the same issues.

**Comment by blender** [comment]
Check the framework search paths.

**Comment by paulomo** [comment]
What to do here? See image. 
<img width="1052" alt="Screen Shot 2019-05-05 at 8 58 53 PM" src="https://user-images.githubusercontent.com/37729297/57202904-baaa6a80-6f78-11e9-8e72-2c15d34e2358.png">

**Comment by paulomo** [comment]
I did this... I am not sure. But I still have same error.
<img width="1017" alt="Screen Shot 2019-05-05 at 9 12 07 PM" src="https://user-images.githubusercontent.com/37729297/57203073-889a0800-6f7a-11e9-9813-4a65e076fb38.png">

**Comment by paulomo** [comment]
@mdiep I did that. I think it's a bug.

**Comment by ikesyo** [comment]
`Carthage/Build/RxSwift` is strange, that should be `Carthage/Build/iOS/RxSwift`.

**Comment by paulomo** [comment]
@ikesyo Same error.

**Comment by ikesyo** [comment]
Okay, "Framework Seart Paths" is directories in which frameworks exist. `Carthage/Build/iOS` is correct value. There is no `Carthage/Build/iOS/RxSwift` directory; each frameworks are in `Carthage/Build/iOS` flat (e.g. `Carthage/Build/iOS/RxSwift.framework`).
