### ISSUE TITLE
Support for Kotlin Native iOS Frameworks

### ISSUE THREAD

**Issue by JZDesign** [Carthage/Carthage#2783]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: What? Do you mean location? (saw that in other issues) `usr/local/bin/`
* `carthage version`: 0.33.0 
* `xcodebuild -version`:  *N/A*
* Are you using `--no-build`? *N/A*
* Are you using `--no-use-binaries`? *N/A* 
* Are you using `--use-submodules`?  *N/A*
* Are you using `--cache-builds`?  *N/A*
* Are you using `--new-resolver`?  *N/A*

**Cartfile**
```
gitHub "https://github.com/JZDesign/SharedKotlinStatusCodes.git" "master"
```

**Carthage Output**
```
*** Skipped building SharedKotlinStatusCodes due to the error:
Dependency "SharedKotlinStatusCodes" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/JZDesign/SharedKotlinStatusCodes/issues/new
```

**Actual outcome**
Carthage did not find the framework that was output from a Kotlin Native solution for iOS

**Expected outcome**
Carthage should find *Kotlin Native Built Frameworks* on github

### Suggestion

It would be nice to have some way to delineate in the `Cartfile` that a framework is a non-standard framework. Something like: 

`github kotlin "https://....." "master"`

Kotlin Native generated frameworks do not contain an `xcodeproj` and the `PList` does not contain the `DT` key value pairs

**Comment by blender** [comment]
I see that you have a binary there.

Have you tried the following:

1. Create a SharedKotlinStatusCodes.json in the root of the project you are using it in
2. The .json should contain the following (replace the version with whatever commitish or tag you want)
```
{
"1.0.0" : "https://some.host/some-zip-of-your-framework.zip"
}
```

3. In the Cartfile:
```
binary "SharedKotlinStatusCodes.json" ~> 1.0.0
```

You can point the .json to the releases on github if you don't know where to host your binary. Also you can put the .json itself on github.

**Comment by JZDesign** [comment]
I'm having difficulty with that. I've tried to host the zip in releases but I get some errors. 

Cartfile: `binary "SharedKotlinStatusCodes.json" ~> 0.1`

Json file:
```
{
    "0.1" : "https://github.com/JZDesign/SharedKotlinStatusCodes/releases/download/0.1/StatusCodes.zip"
}

```

I've also tried without `/download` in the path. I'm getting this error 

>Failed to read file or folder at /Users/xxxxxxxx/Documents/GitHub/MyApp/SharedKotlinStatusCodes.json: Error Domain=Result.AnyError Code=1 "The requested URL was not found on this server

I've tried reading the json from git and I get

>Unable to parse binary-only framework JSON at https://github.com/JZDesign/SharedKotlinStatusCodes/blob/master/SharedKotlinStatusCodes.json due to error: invalid JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.})))

**Comment by JZDesign** [comment]
I got closer I think but I'm getting 

>Falling back to building from the source
A shell task (/usr/bin/xcrun dwarfdump --uuid /private/var/folders/q0/f7zg_47505n43g82kyx0g7phw1rzxx/T/carthage-archive.Jxt3xS/StatusCodes.framework.dSYM) failed with exit code 1:
/private/var/folders/q0/f7zg_47505n43g82kyx0g7phw1rzxx/T/carthage-archive.Jxt3xS/StatusCodes.framework.dSYM/Contents/Resources/DWARF: No such file or directory

**Comment by blender** [comment]
You are linking to html pages on GitHub. You need to link to the raw file.

**Comment by JZDesign** [comment]
That last response is when I linked to the raw file.

**Comment by JZDesign** [comment]
I think it may be a problem with my build script. It's zipping the file before DWARF is available.

**Comment by JZDesign** [comment]
Nope. I made changes to the script and confirmed that the `DWARF` directory is there when the archive is opened but I still get that same error.

**Comment by blender** [comment]
The error seems pretty clear. The data is not valid JSON.

**Comment by blender** [comment]
Oh sorry, you have a DWARF but it’s not a valid DWARF.

**Comment by JZDesign** [comment]
I cleared the CarthageKit cache and ran it again. I think I have it working I'm just going to test it quick

**Comment by blender** [comment]
Or could it be that you have two .frameworks with the same name?

**Comment by JZDesign** [comment]
I don't but things are a little unclear with Kotlin Native frameworks so I may be causing this issue.

**Comment by JZDesign** [comment]
I'm not sure what the issue is. The framework I have works if I drag it into the project, but when I use Carthage I get an interesting error.

I link the framework in "General" 
Then in build phases I run a script to copy the framework from the carthage build folder to the framework directory. 

When I run the application I get an error
> ld: symbol(s) not found for architecture arm64

Any ideas?

**Comment by JZDesign** [comment]
I figured out the issue. I wrote a gradle script to zip the framework. Turns out Gradle's archiving != mac's zip. That broke the framework. Thanks for all of your time and patience.

**Comment by nsekhar90** [comment]
@JZDesign how did you solve it ? I think i might be facing similar issue.
