### ISSUE TITLE
Bootstrap fails on CI due to internal dependency not available

### ISSUE THREAD

**Issue by mbogh** [Carthage/Carthage#2787]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`:  0.33.0
* `xcodebuild -version`: Xcode 10.2.1 Build version 10E1001
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes
* Are you using `--new-resolver`? no

**Cartfile**
```
github "openid/AppAuth-iOS" "1.0.0.rc1"
git "https://gitlab.corp.com/path/to/lib.git" ~> 4.1
```

**Carthage Output**
```
carthage bootstrap --platform ios --cache-builds
*** Checking out lib at "4.1.0"
*** Checking out Swinject at "2.6.0"
*** Checking out AppAuth-iOS at "1.0.0.rc1"
*** Fetching lib
A shell task (/usr/bin/env git fetch --prune --quiet https://gitlab.corp.com/path/to/lib.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/x/Library/Caches/org.carthage.CarthageKit/dependencies/lib)) failed with exit code 128:
remote: HTTP Basic: Access denied
remote: You must use a personal access token with 'api' scope for Git over HTTP.
remote: You can generate one at https://gitlab.corp.com/profile/personal_access_tokens
fatal: Authentication failed for 'https://gitlab.corp.com/path/to/lib.git/'
```

**Actual outcome**
`carthage bootstrap` runs as part of our CI pipeline and it fails to fetch an internal dependency since it is unaware about GitLab and its Job Token. Our runners are used for multiple projects and it would be nice to keep them as clean as possible credential-wise.

**Expected outcome**
Carthage should somehow clone the repository like so:
`git clone https://gitlab-ci-token:$CI_JOB_TOKEN/gitlab.corp.com/path/to/lib.git`

**Comment by mdiep** [comment]
Carthage gets credentials from Git. If `echo 'url=https://gitlab.corp.com'|git credential fill` returns the credentials, then Carthage can use it.

**Comment by mbogh** [comment]
Okay thanks, do you have any suggestions on how to make git temporarily use the job token?

**Comment by mdiep** [comment]
That's a `git` question. If you look into credential helpers, there should be a way to add and then remove the credentials.
