### ISSUE TITLE
More modularity

### ISSUE THREAD

**Issue by tinoheth** [Carthage/Carthage#279]
I would like to have the option to leave the build phase for Xcode, preferable in the form of a plugin-system. 

Long explanation:
Recently, I read a complaint about Carthage because it doesn't allow debugging of imported projects (http://blog.saers.com/archives/2014/12/07/carthage/).
I think that statement is valid, but actually, I consider Carthage better suited for such workflows, as cocoapods with its centralized approach makes it harder to contribute to dependencies.

To do so, I just have to take the project file of the dependency and drag it to the project. The effort of that is about the same as dealing with "Carthage/Build", so I'd rather like to have the dependency manager collect all imported projects, and not the finished frameworks.

In some cases, I would even prefer to have no module at all, so that I can use external code without importing it in each source file.

So I would split the whole process into three phases:
1) Fetch dependency (git submodule, git subtree, full checkout to be used with Xcodes "Working copies", mercurial, copy a compiled framework...)
2) Dependency resolution
3) Integration (build and collect frameworks, link project files, link source files... or even modify the parent project, as cocoapods does)

I'm quite sure there are compatibility issues as soon as you include a project which has some dependencies on its own, but I think the topic is at least worth discussion.

**Comment by dodikk** [comment]
>> Firstly, CocoaPods (by default) automatically creates and updates an Xcode workspace for your application and all dependencies. Carthage builds framework binaries using xcodebuild, but leaves the responsibility of integrating them up to the user.

As far as I can see, this is a philosophy of this dependency manager. It pulls your dependencies to the "Carthage.checkout" directory and your sources - to the "Carthage.build" directory respectively. 

It's up to you choosing how to integrate them : 
* Using frameworks (for easier integration and fast builds)
* Using sub-projects  (for debug)
* Drag&drop source code "as is" (for debug and to feel like home with cocoapods)

**Comment by dodikk** [comment]
>> I think the topic is at least worth discussion.

> If you’re interested in using Carthage as part of another tool, or perhaps extending the functionality of Carthage, take a look at the CarthageKit source code to see if the API fits your needs.

The carthage team even provides some API for exactly this purpose : you need something ==> Cool. Feel free building it.
Another option is using cocoapods which [kinda supports frameworks now](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) (Okay. I know those are static ones. But does it make any difference to you?)

**Comment by dodikk** [comment]
>> I think the topic is at least worth discussion.

Okay. Let's discuss. 
Here is my opinion. 

```
Leaving the integration on the user's behalf is the true flexibility and modularity.
```
* You need fast builds ==> use framework binaries for all dependencies.
* You need to debug a particular library or you are actively developing it ==> use a sub-project for this library only and use framework binaries for everything else

P.S. As you might see, it is nothing like forcing only one "automated drag&drop the sources to your project" workflow ( hello, cocoapods ).

**Comment by jspahrsummers** [comment]
> I would like to have the option to leave the build phase for Xcode
> …
> I'd rather like to have the dependency manager collect all imported projects, and not the finished frameworks.

This can be done with the `--no-build` flag already.

> preferable in the form of a plugin-system.

Carthage will not support plugins—that's a source of incredible complexity that we don't need. We'd rather have other tools built on top of or integrate with Carthage instead.

> In some cases, I would even prefer to have no module at all, so that I can use external code without importing it in each source file.

Although I would strongly recommend _against_ this—because modules are a good thing, and `import`s are not a good enough reason to avoid them—you can already get this effect by using the checkouts directly however you want.

> So I would split the whole process into three phases:

This is _already_ how Carthage is designed. Flags or different commands are used to skip the various steps if you don't want those behaviors. Please see `carthage help` and `carthage help update`.

**Comment by tinoheth** [comment]
> This can be done with the --no-build flag already.
That's nice, but why is it a flag and not defined in the config-file? I had the same question with "--use-submodules": I'd consider both choices to stay constant. Or is the intended use case running Carthage in a run-script build phase?

Doing some experiments, I'm once again convinced there must be a team at Apple inventing countermeasures against independent developers who want to extend products ;-):
It wouldn't be hard to collect softlinks to all referenced sub-projects to make it easy to integrate them (that's what I was thinking of), but apparently, Xcode can't deal with anything but "real" bundles (or files - links to source don't work either).

I'm really curious if Apple has any plans for the "Working copies" feature: My first thought when I saw the option to check out "favorites" was that we'll finally get a dependency-resolver that sits where it belongs - but even a year later, it is still a half-backed solution.

**Comment by jspahrsummers** [comment]
> That's nice, but why is it a flag and not defined in the config-file?

Because [that work](https://github.com/Carthage/Carthage/issues/262) hasn't been done yet.
