### ISSUE TITLE
Carthage unable to build nested frameworks

### ISSUE THREAD

**Issue by ashok1089** [Carthage/Carthage#2790]
* carthage install method [ ] homebrew
* `which carthage`:
* `carthage version`:  0.33.0
* `xcodebuild -version`:  10.2.1
* Are you using `--no-build`  no
* Are you using `--no-use-binaries` yes
* Are you using `--use-submodules no
* Are you using `--cache-builds`no
* Are you using `--new-resolver` no

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
Build successful

**Actual outcome**
running into runtime issues.

**Expected outcome**
If I go and build the nested frameworks separately and again build the parent framework as a whole, the app works fine without any runtime issues.

**Comment by blender** [comment]
They way you have formulated this issue is not very helpful. Can you please add some more information?

**Comment by ashok1089** [comment]
My project depends on frameworks A, B where A depends on frameworks C and D. For some reason, running "Carthage bootstrap" in my projects folder does not seem building frameworks C and D and crashes out when I tried to access things from C and D. 

I had to do below steps to get it work:
1. Go to checkouts folder->Framework A folder and do "carthage bootstrap" (which build frameworks C and D) separately and then 
2. Go back to projects folder and do "carthage build --platform iOS --configuration Debug framework A"

**Comment by mdiep** [comment]
Are you trying to embed frameworks inside a framework? (i.e. place a copy of C inside A) That is not supported. You'd need to copy all nested frameworks into the app itself.

**Comment by ashok1089** [comment]
Yes, I am placing all my nested frameworks (C and D) inside my project.

This is how my project's cartfile.resolved look like:
github "framework A" "version no."
github "framework B" "version no."
github "framework C" "version no."
github "framework D" "version no."

And this is how my framework-A's cartfile.resolved look like:
github "framework C" "version no."
github "framework D" "version no."

**Comment by blender** [comment]
This looks fine to me. I suggest you look at the logs and run the same xcodebuild command carthage is running

**Comment by ashok1089** [comment]
thanks for your quick replies, But I do not understand what you mean by "run the same xcodebuild command carthage is running"

**Comment by blender** [comment]
In the log you will see that all the Carthage does, is invoke xcodebuild. 

Start with the lowest framework and backtrack from there. 

I can’t really help you since you’re giving very little details both on the output and on our Cartfile. All I can say is that what you have is a pretty common setup. Carthage is more than capable of handling it. 

I doubt this is an issue with Carthage. It’s most likely an issue with your setup.

**Comment by ashok1089** [comment]
I do not know if this helps to see the cause, I just found that I do not have to go through step 1 that I mentioned before. In my project folder, just doing "carthage bootstrap --platform ios --no-use-binaries" and step 2 fixes the problem.

~~1. Go to checkouts folder->Framework A folder and do "carthage bootstrap" (which build frameworks C and D) separately and then~~
2. Go to projects folder and do "carthage build --platform iOS --configuration Debug framework A"

@blender can you please help me to see what happens during step 2 and how it is fixing the issue.

**Comment by blender** [comment]
In the project's folder run the carthage command. 

The __first__ line carthage outputs is a link to the build log. Check that.
