### ISSUE TITLE
Carthage update failed when try to install framework which has dependencies

### ISSUE THREAD

**Issue by stonezhl** [Carthage/Carthage#2792]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`:
* `carthage version`:  0.33.0
* `xcodebuild -version`:  Xcode 10.2
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? YES
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO
* Are you using `--new-resolver`?  NO

**Cartfile**
```
github "stonezhl/Bookbinder" "dev"
```

**Carthage Output**
```
*** Fetching Bookbinder
*** Checking out Bookbinder at "8b79323bb6b11ceefcad693f93ad95e5e93c547f"
*** xcodebuild output can be found in /var/folders/yq/q3yjq6l54cg35_b60tz6gxb80000gn/T/carthage-xcodebuild.rQv8zC.log
*** Building scheme "Bookbinder" in Bookbinder.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/stonezhl/Projects/BookbinderCarthageDemo/BookbinderCarthageDemo/Carthage/Checkouts/Bookbinder/Bookbinder/Bookbinder.xcodeproj -scheme Bookbinder -configuration Release -derivedDataPath /Users/stonezhl/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/Bookbinder/8b79323bb6b11ceefcad693f93ad95e5e93c547f -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/yq/q3yjq6l54cg35_b60tz6gxb80000gn/T/Bookbinder SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/stonezhl/Projects/BookbinderCarthageDemo/BookbinderCarthageDemo/Carthage/Checkouts/Bookbinder)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/yq/q3yjq6l54cg35_b60tz6gxb80000gn/T/carthage-xcodebuild.rQv8zC.log
```

**More details**
I made a framework "Bookbinder" which using dependencies with Carthage
Cartfile:
```
github "tid-kijyun/Kanna" ~> 5.0.0
github "weichsel/ZIPFoundation" ~> 0.9
```

And I am making a project which is using "Bookbinder".
When using `carthage update`, got a strange output.
It only fetches "Bookbinder", not its dependencies.

I know maybe it is a stupid question, but it took me a lot of time to figure it out and failed in the end.
It will be very helpful if someone can help me.

**Actual outcome**
Carthage did or did not ...

**Expected outcome**
Carthage should ...

**Comment by stonezhl** [comment]
I should move the project to the git root directory

**Comment by tomatobin** [comment]
I have the same problem.
I followed https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md
But failed at the end.
