### ISSUE TITLE
Carthage build umbrella framework

### ISSUE THREAD

**Issue by tolgatanriverdi** [Carthage/Carthage#2793]
We are developing a dynamic umbrella framework which consist of several other frameworks. Our framework structure is in below

- Base.framework
   * SubFramework1
   * SubFramework2
     * SubFramework2.1
     * SubFramework2.2
   * SubFramework3

And our xcode project file for the umbrella framework(Base.framework) is structured like this. But when I execute carthage build command , it finds some of the sub frameworks and doesnt able to find some of the sub frameworks. What should I do in order to compile the framework as its structured in our xcode project

You can see our framework in the below link: https://github.com/Kandy-IO/test-cp

(All the subframeworks are in SubFrameworks folder of CpaaSSDK.framework)

**Comment by blender** [comment]
Nested frameworks are not supported on IOS.

**Comment by tolgatanriverdi** [comment]
So In this case is it not possible for us to use carthage with this infrastructure:

https://github.com/Kandy-IO/test-cp

**Comment by blender** [comment]
Nested frameworks won't pass app validation on iTunes.

**Comment by blender** [comment]
> An umbrella framework is a framework bundle that contains other frameworks. While it is possible to create umbrella frameworks for macOS apps, doing so is unnecessary for most developers and is not recommended. __Umbrella frameworks are not supported on iOS, watchOS, or tvOS.__

https://developer.apple.com/library/archive/technotes/tn2435/_index.html

**Comment by tolgatanriverdi** [comment]
Our framework is not dynamic, it actually a static framework, however within the framework we are using sub frameworks(As I described in first message), is it not supported in carthage?

**Comment by blender** [comment]
Please provide a Cartfile and a project to check.

**Comment by tolgatanriverdi** [comment]
As far as I know, cartfile is similar to podfile so it works when I try to use the framework in an application project. However I'm now trying to create a carthage build with using **carthage build --no-skip** command to this framework: https://github.com/Kandy-IO/test-cp.
And our infrastructure is same as the description in my first message.
Am I missing something?

**Comment by blender** [comment]
I only see the binary. I would need to see the project file to check. However you can check yourself by checking the log finale that carthage produces.

You don't need to run carthage if you plan to distribute your framework as binary only.
