### ISSUE TITLE
Use Binary compatible with swift5 or later.

### ISSUE THREAD

**Issue by engnakagawa** [Carthage/Carthage#2794]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: ```/usr/local/bin/carthage```
* `carthage version`: ```0.33.0```
* `xcodebuild -version`: ```Xcode 10.2.1 Build version 10E1001```
* Are you using `--no-build`? no 
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes
* Are you using `--new-resolver`? yes

**Cartfile**
```
github "realm/realm-cocoa"
github "Moya/Moya"
github "malcommac/Hydra"
```

**Carthage Output**
```
[I] > carthage update --platform iOS --cache-builds --new-resolver
*** Fetching Moya
*** Fetching Hydra
*** Fetching realm-cocoa
*** Fetching ReactiveSwift
*** Fetching Alamofire
*** Fetching Result
*** Fetching RxSwift
*** Checking out realm-cocoa at "v3.15.0"
*** Checking out Alamofire at "4.8.2"
*** Checking out ReactiveSwift at "5.0.1"
*** Checking out RxSwift at "4.5.0"
*** Checking out Hydra at "2.0.0"
*** Checking out Result at "4.1.0"
*** Checking out Moya at "13.0.1"
*** xcodebuild output can be found in /var/folders/dd/7m1l3xm56zvd1w8476vpccyw0000gn/T/carthage-xcodebuild.sFfH2M.log
*** Valid cache found for Alamofire, skipping build
*** Valid cache found for Hydra, skipping build
*** Valid cache found for realm-cocoa, skipping build
*** Valid cache found for Result, skipping build
*** Valid cache found for ReactiveSwift, skipping build
*** Invalid cache found for RxSwift, rebuilding with all downstream dependencies
*** Downloading RxSwift.framework binary at "[4,5]"
***  Skipped installing RxSwift.framework binary due to the error:
        "Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)."

    Falling back to building from the source

...
```

**Actual outcome**
Carthage did not use RxSwfit.framework binary

**Expected outcome**
Carthage use RxSwift.ramework(5.0) binary, in 5.0.1

Because swift5 has [Stable ABI and Binary Compatibility].
https://swift.org/blog/swift-5-released/

**Comment by blender** [comment]
Swift doesn’t yet have module stability.

**Comment by joshrl** [comment]
@blender can you be more specific? I think with ABI Carthage should not care about the version the binary was built with (as long as its 5.0+). There are cases where this is a real issue (not just performance) in cases where a framework is not distributed with source.

**Comment by blender** [comment]
Carthage cares about both ABI (runtime) and module (compile time) stability. 

This is achievable in Swift 5.1 with `Build libraries for distribution`. Please refer to  https://developer.apple.com/videos/play/wwdc2019/416/

**Comment by ikesyo** [comment]
And also https://swift.org/blog/abi-stability-and-more/.
