### ISSUE TITLE
Alamofire Build Error with Swift 5

### ISSUE THREAD

**Issue by leonhelg5** [Carthage/Carthage#2803]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `carthage version`: 0.33.0
* `xcodebuild -version`:  10.2.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**What did I do**
I am migrating a custom NetworkFoundation that is based on Alamofire to Swift 5.

"carthage update" (to alamofire 5.0.0-beta.5)-> success
build in Xcode -> success

"carthage build --no-skip-current" -> error

**Cartfile**
```
> github "Alamofire/Alamofire" "5.0.0-beta.5"
```

**Carthage Output**
```
xxx xcodebuild output can be found in /var/folders/1m/qjb4gks13d54rqmn9ptwjmmw0000gp/T/carthage-xcodebuild.bg5VCR.log
xxx Building scheme "Alamofire macOS" in Alamofire.xcworkspace
xxx Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
xxx Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
xxx Building scheme "Alamofire iOS" in Alamofire.xcworkspace
xxx Building scheme "MyNetworkFoundation" in MyNetworkFoundation.xcodeproj
xxx Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/MyUser/Documents/Projects/MyNetworkFoundation/MyNetworkFoundation/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme Alamofire\ iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/1m/qjb4gks13d54rqmn9ptwjmmw0000gp/T/MyNetworkFoundation SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/MyUser/Documents/Projects/MyNetworkFoundation)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/1m/qjb4gks13d54rqmn9ptwjmmw0000gp/T/carthage-xcodebuild.bg5VCR.log
```

**Actual outcome**
Carthage did not build my framework. In the logfile, this is stated: 
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Alamofire iOS') ** ARCHIVE FAILED

What confuses me is that in my project under "Build Settings" the Swift version is set to 5. When I check in "/MyNetworkFoundation/Carthage/Checkouts/Alamofire/Alamofire.xcodeproj", the Swift version of all targets of is set to 5 too. I cannot spot Swift 3 anywhere in my framework nor Alamofire.

**Expected outcome**
The framework to build to then archive it with "carthage archive".

**Comment by blender** [comment]
Could it be that you have an the variable `SWIFT_VERSION` set?

**Comment by blender** [comment]
I'm building Alamofire `master` and I don't encounter this problem.

**Comment by haithngn** [comment]
@blender 
carthage version: 0.33.0
xcodebuild -version: 11 Beta
Are you using --no-build? no
Are you using --no-use-binaries? no
Are you using --use-submodules? no
Are you using --cache-builds? no
Are you using --new-resolver? no

But when I imported the framework from the result the Xcode say:
module compiled with Swift 4.1.2 cannot be imported by the Swift 5.1 compiler.

Could we solve that ?

**Comment by blender** [comment]
You are using a prebuilt binary. specify --no-use-binaries

**Comment by catluc** [comment]
Same here with Xcode 11 beta 4 and and trying out the 5.0.0 beta 6 of Alamofire

**Comment by tmspzz** [comment]
@catluc you're probably encountering this issue: https://github.com/Carthage/Carthage/issues/2825
