### ISSUE TITLE
W/w character not allowed in version parameter

### ISSUE THREAD

**Issue by drakerr** [Carthage/Carthage#2805]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.32.0
* `xcodebuild -version`: Xcode 10.1 Build version 10B61
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
binary "xxxSDK.json" == 1.0.3-SNAPSHOT-Swift5.1-featuredevconst-test
```

**Carthage Output**
```
Parse error: Pre-release contains invalid characters, in "1.0.3"
```

**Actual outcome**
Carthage did not download the binary

**Expected outcome**
Carthage should download the binary. We searched the error and we found that the issue may be located in the file `Version.swift`. The static variable `asciiAlphabeth` does not contain the 'w/W' character.

```
fileprivate static let asciiAlphabeth = CharacterSet(
    charactersIn: "abcdefghijklmnopqrstuvxyzABCDEFGHIJKLMNOPQRSTUVXYZ"
)
```

**Comment by drakerr** [comment]
I opened a PR: https://github.com/Carthage/Carthage/pull/2806

**Comment by blender** [comment]
Very much appreciated 🙇
