### ISSUE TITLE
Code Sign error: No code signing identities found

### ISSUE THREAD

**Issue by refried** [Carthage/Carthage#281]
Hi — first time Carthaging here, and having a bit of trouble.  It looks like it's related to code signing, but as far as I can tell, my signing profile is set up fine.
```
*** Fetching SwiftyJSON
*** Checking out SwiftyJSON at "2.1.3"
*** xcodebuild output can be found in /var/folders/kl/tdsq1jgx3_b33877x8vkmk480000gn/T/carthage-xcodebuild.MLdkEs.log
*** Building scheme "SwiftyJSON" in SwiftyJSON.xcworkspace
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
```
The log file shows:
```
** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.1

=== BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) 
matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.1'
```

**Comment by refried** [comment]
I guess a distribution profile is needed in addition to a development profile.  Might want to update the readme, if it isn't there already?

**Comment by mattrubin** [comment]
Carthage uses a project's own release build settings when building frameworks. It looks like SwiftyJSON has [`CODE_SIGN_IDENTITY = "iPhone Distribution"` set in its Release configuration](https://github.com/SwiftyJSON/SwiftyJSON/blob/f5347e5a90dfe00c32fa1fe228472291cacb386a/SwiftyJSON.xcodeproj/project.pbxproj#L497).

Instead of setting up a distribution signing identity, you might be able to just change this build setting to "iOS Developer" in the SwiftyJSON project. I *think* that a custom framework embedded in an iOS app will be re-signed when it's copied into the app bundle, so signing for distribution on initial build may not be necessary.

**Comment by refried** [comment]
Oh. Thanks!

**Comment by jspahrsummers** [comment]
You could also pass `--configuration Debug` to Carthage, to select the Debug codesigning settings.

**Comment by jspahrsummers** [comment]
I don't want to support simulator-only builds as a configuration option, but maybe that's something Carthage can do automatically if it fails to detect a code signing identity.

@Carthage/carthage Thoughts?

**Comment by jspahrsummers** [comment]
If we wanted to do this, I think something like this would work:

1. Check whether the scheme being built has a value for the `CODE_SIGN_IDENTITY` build setting when using the iOS device SDK.
1. If no identity is specified in that setting, skip building for device (and, therefore, also skip the fat binary steps).
1. Log a warning, so users know that their build doesn't include iOS device slices.

We would need to confirm that building works when no certificate has been installed.

That may also be the wrong build setting—perhaps `CODE_SIGNING_REQUIRED` instead? I'm not well-versed in it, so this would require some investigation.

**Comment by robb** [comment]
I think simulator-only builds that don't require code signing would be nice for using Carthage on travis et al. Not sure what the best approach is, but skipping device builds if there's no `CODE_SIGN_IDENTITY` sounds reasonable :+1:

**Comment by jspahrsummers** [comment]
:+1: Let's do this.

**Comment by mattrubin** [comment]
I've also been wanting unsigned sim-only builds for Travis et al, and this sounds like a good way to go about it.
As I understand your proposal, there will be no way to explicitly specify you want a sim-only build (which could cause problems if you then tried to use those builds on device), but instead Carthage will only create a sim-only build if there's no way to create a device build - a situation in which you won't be able to run the app on device or ship to the store regardless. This seems like a good balance of giving users an option without giving them a way to use that option to shoot themselves in the foot. :+1:

**Comment by jspahrsummers** [comment]
> As I understand your proposal, there will be no way to explicitly specify you want a sim-only build … but instead Carthage will only create a sim-only build if there's no way to create a device build

Yep, that's correct.

I'm still worried about users shipping or uploading simulator-only binaries (for example, if they set up a device certificate too late), but a warning message might help with that.

**Comment by flovilmart** [comment]
I fixed the same error on cocoa pods a while ago: https://github.com/flovilmart/CocoaPods/commit/f3fe8e716590bbb87008f2b3cfadbacff01f4738 it will only sign code with the proper identity if required

**Comment by rromanchuk** [comment]
@jspahrsummers hmmm,  this is beyond the scope of my build system knowledge, but as a carthage user, responding to  `CODE_SIGN_IDENTITY` set in the scheme makes absolutely no sense to me.  Frameworks should be signed at runtime in whatever context the host is running.  Steps 1-3 are already dancing around way too much. If they must be signed at build, there should be a simple, flagless way of responding.  Or make an opinionated decision like "To use carthage you must have have valid development and distribution code signing before using"

** BUILD FAILED **  Definitely needs to go though, ideally it should be replaced with actionable steps the user can take 

I really liked the idea that with carthage i can say "Give me framework Foo at branch Bar" but `CODE_SIGN_IDENTITY` is starting to remind me of a Spec. I'm sending pull requests to modify developer schemes just to suppress error warnings :sob:

**Comment by flovilmart** [comment]
@rromanchuk Every framework need to be signed upon copy, not upon building. The carthage build doesn't have to product signed fraweworks, however, the frameworks have to be signed just after they are copied: 

/usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" --preserve-metadata=identifier,entitlements "${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/$1 where $1 is the framework name.

This will ensure the frameworks are signed with the proper identity

**Comment by rromanchuk** [comment]
@flovilmart this is 100% the way to go then. I know part of the pitch of carthage is to not mess with project settings, but the VERY last thing developers want to be dealing with is signing issues, especially  when their own project is already properly configured. 

Some projects have multiple bundle identifiers, with special signing depending on environments pulled from `xcconfig` .   This scheme setting should be completely ignored, I honestly can't think of a scenario where this makes sense.

**Comment by flovilmart** [comment]
@rromanchuk the explained method is the way I managed to make it dumb proof for cocoa pods, it's working properly and 100%

**Comment by rromanchuk** [comment]
At the very least, we should offer a  --no-sign that doesn't try to pretend how the user wants their framework signed

**Comment by flovilmart** [comment]
You mean for the carthage build ?

The framework should never be signed upon build as you have no idea what is the environment of the current projet, so that would render the —no-sign useless




For the carthage copy-frameworks, that could actually make sense, but that could leave the project unable to run or compile properly.




I’m more in favour of leveraging the proper env variables:




EXPANDED_CODE_SIGN_IDENTITY and CODE_SIGNING_REQUIRED that are defined by the project and that Xcode itself uses in order to produce valid packages

**Comment by flovilmart** [comment]
Now the env variable that is checked is CODE_SIGNING_ALLOWED, we should also check CODE_SIGNING_REQUIRED as it provides another piece of information

**Comment by rromanchuk** [comment]
@flovilmart yeah thats what i mean,  it should use `EXPANDED_CODE_SIGN_IDENTITY` and `CODE_SIGNING_REQUIRED` by the *host* project. But with the current state of the union,  i want a --no-sign, so I can at least have carthage just dump the unsigned frameworks and then I will create my own build phase to sign on copy

**Comment by flovilmart** [comment]
Makes sense :)

**Comment by flovilmart** [comment]
Want me to take care of it?

**Comment by rromanchuk** [comment]
@flovilmart yes please :smile: :fireworks: :100:

**Comment by flovilmart** [comment]
So to sum up:

- add Check on CODE_SIGN_REQUIRED

- add CLI flag to for no signing




Do we want a flag to provide code signing identity? Like --force-sign IDENTITY

**Comment by jspahrsummers** [comment]
This thread seems to have gotten really off-track.

Let me clarify a couple things:

 1. The _only_ thing Carthage will be doing is **disabling code signing when a valid identity does not exist** for the target being built.
 1. Codesigning with the _correct_ identity will happen when the frameworks are copied into an app bundle anyways.
 1. The _recommended_ way to use Carthage is still to have all necessary certificates installed.

I'm not really interested in adding flags that control this behavior, since it's meant to be a graceful fallback mechanism only.

**Comment by rromanchuk** [comment]
Why would Carthage need to concern itself with 1 and 3 if 2 is true?  I'm not trying to be combative, i'm just trying to understand your thinking. I don't understand why code signing is even in the scope of appropriate responsibilities during framework builds.

**Comment by jspahrsummers** [comment]
Framework projects come with codesigning enabled by default. When certificates are not installed—for example, because the user isn't signed up with the Developer Program, and only testing in the simulator for now—builds fail constantly, with cryptic errors.

This is a means to get folks to a _minimally working state_ without asking them to pay $100 for the privilege.

**Comment by flovilmart** [comment]
Frameworks should never be signed at build time, only at copy time, and only if CODE_SIGN_REQUIRED=YES




Wether or not a proper identity is found is not our issue as the app sign will fail if no identity is provided.

**Comment by rromanchuk** [comment]
@jspahrsummers i have a feeling i don't understand how carthage works anymore, or something is getting lost in translation. You basically described what i exactly want. I want  `carthage update` to do nothing but dump the framework, this is what i'm arguing should be the *only* way carthage builds frameworks.

**Comment by rromanchuk** [comment]
![ios](https://cloud.githubusercontent.com/assets/102188/6681563/cb0617a8-cc25-11e4-988b-b676e07522b8.png)

**Comment by jspahrsummers** [comment]
> Frameworks should never be signed at build time, only at copy time

@flovilmart This isn't true. Dynamic frameworks are _required_ to be signed by Xcode.

> I want  `carthage update` to do nothing but dump the framework, this is what i'm arguing should be the *only* way carthage builds frameworks.  

@rromanchuk If you already have your codesigning identities set up correctly, then the behavior of Carthage will not change with the fix to this issue.

![](http://4.bp.blogspot.com/-u7AvKzWUFFM/UQoozJhAi2I/AAAAAAAAIpQ/GLiJDlGSk9M/s1600/no-need-upset.jpg)

**Comment by flovilmart** [comment]
@jspahrsummers THE code sign require flag is set to false while building for simulator... So That's not required

**Comment by jspahrsummers** [comment]
It is required for device frameworks, though, which is why this issue was opened in the first place, and why we want to skip code signing if the user isn't certified to build for device.

**Comment by flovilmart** [comment]
But how do you think it's gonna go on device if no identity is found? 

I don't see the point of Carthage trying to be smarter. Sign as late as possible and there won't be any issue. If a code sign identity is missing, while it is required it should fail. If it silently goes, the build will fail after...

**Comment by jspahrsummers** [comment]
I've expressed my reasoning—and how this will work—here already. I'm always open to feedback and contrary opinions, but we're just talking in circles now.

Let's focus this discussion on _solving the issue described_, which is users not having certificates to build for device. Unless you have a different solution that we can talk about here, we're going to pursue the one I proposed.

**Comment by flovilmart** [comment]
But without a certificate there's no reason to build for device, you can't run on device! 

If your concern is CI servers, you can always provide your signing identity from the CLI. This is a non issue to me, an Anti-Feature! 




Why don't you solve running apps on device without a signing identity when you're at it?

**Comment by jspahrsummers** [comment]
I doubt this really qualifies as an “anti-feature,” because it will affect _zero percent_ of your use case.

This discussion is no longer productive, so I'm going to lock it to collaborators only.

**Comment by mdiep** [comment]
This was done in #583.
