### ISSUE TITLE
When using --cache-builds with different platforms cache gets overridden

### ISSUE THREAD

**Issue by demosten** [Carthage/Carthage#2810]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: 0.33.0
* `xcodebuild -version`: any since at least Xcode 9
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? YES 
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? YES
* Are you using `--new-resolver`? NO

**Cartfile**
```
github "stenographer/stenographer"
```

**Carthage Output**
```
$ carthage bootstrap --platform ios --no-use-binaries --use-ssh --cache-builds
*** Checking out stenographer at "v1.0.0"
*** No cache found for stenographer, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/60/y02t9f0j08j2_fvzj43881gr0000gp/T/carthage-xcodebuild.Lo1hRf.log
*** Building scheme "Stenographer iOS" in Stenographer.xcodeproj

$ carthage bootstrap --platform ios --no-use-binaries --use-ssh --cache-builds
*** Checking out stenographer at "v1.0.0"
*** xcodebuild output can be found in /var/folders/60/y02t9f0j08j2_fvzj43881gr0000gp/T/carthage-xcodebuild.hvcOrT.log
*** Valid cache found for stenographer, skipping build

$ carthage bootstrap --platform watchOS --no-use-binaries --use-ssh --cache-builds
*** Checking out stenographer at "v1.0.0"
*** xcodebuild output can be found in /var/folders/60/y02t9f0j08j2_fvzj43881gr0000gp/T/carthage-xcodebuild.uz48F1.log
*** Invalid cache found for stenographer, rebuilding with all downstream dependencies
*** Building scheme "Stenographer watchOS" in Stenographer.xcodeproj

$ carthage bootstrap --platform watchOS --no-use-binaries --use-ssh --cache-builds
*** Checking out stenographer at "v1.0.0"
*** xcodebuild output can be found in /var/folders/60/y02t9f0j08j2_fvzj43881gr0000gp/T/carthage-xcodebuild.ckDoef.log
*** Valid cache found for stenographer, skipping build

$ carthage bootstrap --platform ios --no-use-binaries --use-ssh --cache-builds
*** Checking out stenographer at "v1.0.0"
*** xcodebuild output can be found in /var/folders/60/y02t9f0j08j2_fvzj43881gr0000gp/T/carthage-xcodebuild.09BgwA.log
*** Invalid cache found for stenographer, rebuilding with all downstream dependencies
*** Building scheme "Stenographer iOS" in Stenographer.xcodeproj
```

**Actual outcome**
Please look at the specified platforms and cache hits in the above commands and their outputs. Commands were executed in sequence. Using or not using of `--no-use-binaries` does not affect the outcome. 

Every time I build for different platform it overrides the other platform cache

**Expected outcome**
Every time I build for different platform it goes to platform specific cache

**Comment by blender** [comment]
I would argues this is expected.

**Comment by demosten** [comment]
The project I work on has 40+ non binary Carthage modules to build for the iOS target. Cache is quite important in this case. watchOS target uses only 3 of them and it is ran after the iOS Carthage using command like: 

`$ carthage bootstrap --platform watchOS --no-use-binaries --use-ssh --cache-builds module1 module2 module3`. 

Because of this issue these 3 modules are rebuilt every time. If caches for iOS builds go into one folder while watchOS ones into another this wouldn't happen.

**Comment by blender** [comment]
@demosten I can't offer you a fix, but what I can do is offer you two workarounds:

1. include iOS and watchOS when building those modules
2 and/or use https://github.com/blender/Rome

**Comment by demosten** [comment]
I see. Workaround 1 partially works for us. We are using Rome at our CI. It is great when you have the environment missing all the modules to get the prebuilt versions. However verifying with Rome locally that all 40+ modules you already have are up to date takes 40+ seconds every build. We are using different tricks there.

With that being said I see no point to keep this issue open and closing it. Thanks @blender and all others involved in Carthage and Rome, great tools!
