### ISSUE TITLE
Carthage fetches and checks out same repository multiple times

### ISSUE THREAD

**Issue by psparago** [Carthage/Carthage#2813]
Synopsis: Carthage is fetching and checking out the same repository twice and failing to create the index.lock file (I assume) the second time.

Details: I use my own shared framework (AngelshareKit below) between two of my iOS/Swift applications. I am not an iOS expert and I followed these instructions in order to create and use my own shared framework:

https://stackoverflow.com/questions/38470517/swift-ios-8-framework

So, I may be using Carthage incorrectly, however, this formula has worked in the past. 

The issue began when I recently changed my Cartfile to use 'parse-community/Parse-SDK-iOS-OSX'. The dependency used to be "ParsePlatform/Parse-sdk-iOS-OSX".

I have removed both the shared framework and app's Carthage directory before performing the Carthage update: 

```carthage update --platform iOS --configuration Debug --no-use-binaries```

* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 10.2.1 Build version 10E100
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? YES 
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO
* Are you using `--new-resolver`? NO

**My Shared Framework Cartfile**
```
github "Alamofire/Alamofire"
github "OAuthSwift/OAuthSwift"
github "hkellaway/Gloss"
github "Thomvis/BrightFutures"
github "parse-community/Parse-SDK-iOS-OSX"
```
**My App Cartfile**
```
github "Alamofire/Alamofire"
github "OAuthSwift/OAuthSwift"
github "hkellaway/Gloss"
github "Thomvis/BrightFutures"
github "parse-community/Parse-SDK-iOS-OSX"
github "Alamofire/AlamofireImage"
git "file:///Users/peter/code/code-ios/AngelshareKit"
```

**Carthage Output**
```
*** Fetching OAuthSwift
*** Fetching AngelshareKit
*** Fetching Alamofire
*** Fetching AlamofireImage
*** Fetching Gloss
*** Fetching Parse-SDK-iOS-OSX
*** Fetching BrightFutures
*** Fetching Parse-SDK-iOS-OSX
*** Fetching facebook-ios-sdk
*** Fetching Bolts-ObjC
*** Checking out BrightFutures at "8.0.1"
*** Checking out Parse-SDK-iOS-OSX at "1.17.2"
*** Checking out Gloss at "2.1.1"
*** Checking out Parse-SDK-iOS-OSX at "1.17.2"
A shell task (/usr/bin/env git checkout --quiet --force 1.17.2 (launched in /Users/peter/Library/Caches/org.carthage.CarthageKit/dependencies/Parse-SDK-iOS-OSX)) failed with exit code 128:
fatal: Unable to create '/Users/peter/Library/Caches/org.carthage.CarthageKit/dependencies/Parse-SDK-iOS-OSX/./index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

**Actual outcome**
Carthage fetches and checks out Parse-SDK-iOS-OSX at "1.17.2" twice.

**Expected outcome**
Carthage should check out Parse-SDK-iOS-OSX only once.

**Comment by psparago** [comment]
This is not an issue. This was my fault. I failed to build and tag my shared framework, so Carthage was using the previous tag/commit that had the old repository name. Sorry for my ignorance.

**Comment by blender** [comment]
No problem. Glad you figured it out!
