### ISSUE TITLE
Feature request: Pass --no-build in Cartfile

### ISSUE THREAD

**Issue by BowdusBrown** [Carthage/Carthage#2818]
It would be cool if we could specify `--no-build` on a per dependency basis.

Something like

```bash
github "BowdusBrown/Dequeue" == 1.0.0
github "BowdusBrown/Records" == 1.0.0 --no-build
github "JohnSundell/Require" == 2.0.1
```

**Comment by blender** [comment]
You can use --cache-buids

**Comment by BowdusBrown** [comment]
Hi @blender thanks for prompt response.

The documentation suggests `--cache-builds` prevents _rebuilding_ a dependency. I'm looking to avoid building a dependency at all and just checkout source.

**Comment by blender** [comment]
If the dependency doens't have a shared scheme, carthage won't build it

**Comment by BowdusBrown** [comment]
I want to build it as a binary dependency in other projects :(

**Comment by blender** [comment]
Sorry then. I ran out of suggestions :\
