### ISSUE TITLE
No Shared Schemes Error

### ISSUE THREAD

**Issue by jamescmartinez** [Carthage/Carthage#282]
When trying to build AFNetworking via Carthage, I get the following: `Project "AFNetworking OS X Example.xcodeproj" has no shared schemes`. Obviously this isn't a part of the project I need. I can go into `Checkouts/AFNetworking` and remove this project as well as the tests project, but this is quite a pain. Am I missing something? Logs are empty, by the way.

Carthage 0.5.1
AFNetworking 2.5.0

**Comment by jspahrsummers** [comment]
Carthage will only try to build a single project from the chosen repository, and can only build shared schemes from there.

In other words, AFNetworking isn't really set up for Carthage. If you'd like to add support, please submit a pull request to the project, based on the instructions in the [Carthage README](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework).

**Comment by jamescmartinez** [comment]
Got it. Thanks, @jspahrsummers

**Comment by jspahrsummers** [comment]
No problem!

**Comment by doronkatz** [comment]
Has anyone managed to create a fork of AFNetworking that does work?

**Comment by jspahrsummers** [comment]
cc @robb @erichoracek

**Comment by erichoracek** [comment]
We have a working one at https://github.com/automatic/AFNetworking/tree/carthage-support (thanks to @robb!)
