### ISSUE TITLE
Fail to install Alamofire-5.0.0-beta.5 in XCode 11.0 beta 4 by Carthage

### ISSUE THREAD

**Issue by nah89** [Carthage/Carthage#2827]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: 
* `carthage version`: 0.33.0 
* `xcodebuild -version`: XCode 11.0 beta 4 (11M374r)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "Alamofire/Alamofire" "5.0.0-beta.5"
```
**Command line**
```
$ carthage update --no-use-binaries
```

**Carthage Output**
```
*** Checking out Alamofire at "5.0.0-beta.5"
*** xcodebuild output can be found in /var/folders/jt/r5hvh14x24s_j29jlqp2tz7r0000gn/T/carthage-xcodebuild.JEkZm9.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/nah/Projects/Test/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme Alamofire\ iOS -configuration Release -derivedDataPath /Users/nah/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11M374r/Alamofire/5.0.0-beta.5 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/jt/r5hvh14x24s_j29jlqp2tz7r0000gn/T/Alamofire SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/nah/Projects/Test/Carthage/Checkouts/Alamofire)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/jt/r5hvh14x24s_j29jlqp2tz7r0000gn/T/carthage-xcodebuild.JEkZm9.log
MacBook-Pro:Test nah$ 
```

**Actual outcome**
Carthage did not run properly..

**Expected outcome**
Carthage should run and build Alamofire framework successfully

Ref: 
[Test.zip](https://github.com/Carthage/Carthage/files/3408705/Test.zip)

**Comment by lijie121210** [comment]
Struggling since last night. . .

**Comment by nah89** [comment]
I've spent 2 hours for this one. Tried several things include delete Carthage cache, but still face with this problem. 
This issue isn't addressed anywhere therefore I decide to post here.

**Comment by jdhealy** [comment]
There's a wide-ranging issue with Xcode 11 Beta 4 — Apple [calls it out in their release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_4_release_notes):

> Targets that contain Swift code with the Enable Bitcode build setting set to Yes fail to link correctly when built with the Archive action. (52804818)
> Workaround: Add a custom build setting with the name LD_VERIFY_BITCODE, and set it to NO. Make a note to yourself to delete this custom build setting once this issue is resolved.

To more easily apply the workaround to Carthage, see https://github.com/Carthage/Carthage/issues/2825#issuecomment-512706836.

**Comment by nah89** [comment]
Thank @jdhealy, I can build for now!
