### ISSUE TITLE
carthage build --no-skip-current cannot exclude simulator architectures

### ISSUE THREAD

**Issue by yamazaki-sensei** [Carthage/Carthage#2828]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 10.2.1 Build version 10E1001
* Are you using `--no-build`? : No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`?  No
* Are you using `--new-resolver`?  No

**Cartfile**
```
github "ReactiveX/RxSwift" ~> 5.0
github "kean/Nuke"
github "mac-cain13/R.swift.Library"
```

**Carthage Output**
```
*** xcodebuild output can be found in /var/folders/zd/k918zwj14h74z6zr_lrk298w0000gn/T/carthage-xcodebuild.xuSPXu.log
*** Downloading RxSwift.framework binary at "ShaiTheBravest"
*** Building scheme "Nuke" in Nuke.xcodeproj
*** Building scheme "Rswift-iOS" in R.swift.Library.xcodeproj
*** Building scheme "Rswift-tvOS" in R.swift.Library.xcodeproj
*** Building scheme "my-lib-name" in my-lib.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/hira/Documents/weekend/my-lib/my-lib.xcodeproj -scheme my-lib-name -configuration Release -sdk iphonesimulator -destination platform=iOS\ Simulator,id=8F7A6834-AFB9-4C8E-84BA-56C0CA7BD0A1 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/hira/Documents/weekend/my-lib)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/zd/k918zwj14h74z6zr_lrk298w0000gn/T/carthage-xcodebuild.xuSPXu.log
```

→ `carthage-xcodebuild.xuSPXu.log` suggests that some CoreVideo and Metal features are not found, which simulator does not supports.

**Actual outcome**
Because of some CoreVideo or Metal features, My framework cannot be build with simulator architectures.
In xcodeproj, I excluded x86 architectures as below, but `carthage build --no-skip-current` command does not exclude them, and build fails.
My project settings are pasted below.

<img width="642" alt="スクリーンショット 2019-07-21 18 06 38" src="https://user-images.githubusercontent.com/1329902/61589253-5182dc80-abe2-11e9-9861-a7308a039fd0.png">

Additional info: `xcodebuild -scheme my-lib-name -project my-lib.xcodeproj/ build` finished without any errors.

**Expected outcome**
`carthage build --no-skip-current` finishes without failure.

**Comment by ikesyo** [comment]
Removing `iphonesimulator` from `SUPPORTED_PLATFORMS` is a right thing to do.

See #2712.

**Comment by coreyd303** [comment]
#2530 about 2/3 of the way down has information about how to update supported platforms values. This seems to work
