### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by 441088327** [Carthage/Carthage#283]
Build settings from command line:
    SDKROOT = iphonesimulator8.1

=== BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

Check dependencies

=== BUILD TARGET SwiftyJSONTests OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.1

=== BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.1'

**Comment by mattrubin** [comment]
Building for iOS requires you to have an iOS code signing identity set up.

SwiftyJSON has [`CODE_SIGN_IDENTITY = "iPhone Distribution"` set in its Release configuration](https://github.com/SwiftyJSON/SwiftyJSON/blob/f5347e5a90dfe00c32fa1fe228472291cacb386a/SwiftyJSON.xcodeproj/project.pbxproj#L497) -- the configuration Carthage uses by default -- so you'll need a distribution signing identity.

If you'd rather, you can pass `--configuration Debug` to Carthage to use the Debug code signing settings. This can save time now if you don't have a distribution signing identity set up, but the debug builds produced aren't optimized in the way you'd want when actually shipping an app.
