### ISSUE TITLE
Carthage update freeze after version bumped

### ISSUE THREAD

**Issue by billypchan** [Carthage/Carthage#2833]
Hi all, I encounter an freeze issue recently when trying to update one of the project's framework. I googled quited a lot of similar issues and does not help (tried remove the cache, with --new-resolver and etc.). Finally I chnaged the line `github "wireapp/wire-ios-sync-engine" ~> 271.0` to `github "wireapp/wire-ios-sync-engine" "271.0.0"` and `Carthage update` works correctly again. Change it back to original version syntax and the issue does not occur again. 

---

* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 10.3 Build version 10G8
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`?  No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "wireapp/wire-ios-ziphy" ~> 13.0
github "wireapp/Cartography" "4.0.0"
github "wireapp/wire-ios-sync-engine" ~> 271.0
github "wireapp/wire-ios-share-engine" ~> 153.0
github "wireapp/FormatterKit" "1.8.1-swift3.0.2"
github "wireapp/wire-ios-canvas" ~> 10.0
github "wireapp/HockeySDK-iOS" ~> 5.1.4
github "wireapp/FLAnimatedImage" "1.0.12-wire"
github "wireapp/Down" "v2.1.3"
github "wireapp/DifferenceKit" "1.1.1"

```

**Carthage Output**
```
carthage update --platform ios --verbose
*** Fetching wire-ios-testing
*** Fetching wire-ios-canvas
*** Fetching HockeySDK-iOS
*** Fetching swift-snapshot-testing
*** Fetching wire-ios-sync-engine
*** Fetching wire-ios-ziphy
*** Fetching wire-ios-share-engine
*** Fetching wire-ios-system
*** Fetching ocmock
*** Fetching wire-ios-request-strategy
*** Fetching wire-ios-data-model
*** Fetching wire-ios-cryptobox
*** Fetching wire-ios-link-preview
*** Fetching wire-ios-images
*** Fetching wire-ios-transport
*** Fetching wire-ios-protos
*** Fetching swift-protobuf
*** Fetching wire-ios-utilities
*** Fetching protobuf-objc
*** Fetching avs-ios-binaries
*** Fetching wire-ios-message-strategy
^C
```

**Actual outcome**
Carthage update did not ends and freezes after *** Fetching wire-ios-message-strategy

**Expected outcome**
Actually `wire-ios-message-strategy` is retired and current version does not require it.

**Comment by tmspzz** [comment]
Have you tried `—new-resolver`

**Comment by billypchan** [comment]
Yes, I tried it several times but it does not solve the issue.

**Comment by tmspzz** [comment]
The most common reason is a bad tag confusing the resolver.

**Comment by hallelujahbaby** [comment]
Same issue. Using Xcode 10.3 & Carthage 0.33.0.

CartFile
```
# One Signal
github "OneSignal/OneSignal-iOS-SDK"

# RxSwift
github "ReactiveX/RxSwift" ~> 4.0

# IQKeyboardManager
github "hackiftekhar/IQKeyboardManager"

# Hero
github "lkzhao/Hero"

# Localize-Swift
github "marmelroy/Localize-Swift"

# RxGesture
github "RxSwiftCommunity/RxGesture"

# Hue
github "hyperoslo/Hue"

# SwiftIcons
github "ranesr/SwiftIcons" ~> 2.3.2

# Moya
github "Moya/Moya" ~> 13.0.0

# ObjectMapper
github "Hearst-DD/ObjectMapper" ~> 3.4

# Moya-ObjectMapper
github "bmoliveira/Moya-ObjectMapper"

# Reachability
github "ashleymills/Reachability.swift"

# RxReachability
github "bmoliveira/RxReachability"

# RxDataSources
github "RxSwiftCommunity/RxDataSources" ~> 3.0

# SDWebImage
github "SDWebImage/SDWebImage"

# BWWalkthrough
github "ariok/BWWalkthrough"

# ImageViewer
github "MailOnline/ImageViewer"

# CBPinEntryView
github "Fawxy/CBPinEntryView"

# SkyFloatingLabelTextField
github "Skyscanner/SkyFloatingLabelTextField"

# RxAlertController
github "evgeny-sureev/RxAlertController"

# SideMenu
github "jonkykong/SideMenu" "master"

# ImageSlideshow
github "zvonicek/ImageSlideshow" ~> 1.6

# FSPagerView
github "WenchaoD/FSPagerView"

# TagListView
github "ElaWorkshop/TagListView" ~> 1.0

# XLPagerTabStrip
github "xmartlabs/XLPagerTabStrip" ~> 8.1

# Sheriff
github "gemr/Sheriff"

# PINRemoteImage
github "pinterest/PINRemoteImage"

# Cache
github "hyperoslo/Cache"

# MBProgressHUD
github "jdg/MBProgressHUD" ~> 1.1.0

# Mixpanel
github "mixpanel/mixpanel-swift"
```

Freeze at fetching, then end up  error `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRunLoop addPort:forMode:]: port argument cannot be nil'` after about 15 minutes.

**Comment by tmspzz** [comment]
Try —new-resolver. Again, the most probable cause is there either is a confusing tag or something it pointing to a branch.

**Comment by kenji21** [comment]
Got the same issue today, the issue was :
RxSwift pointing to 5.0
RxSwiftExt pointing to 4.0 (so looking for RxSwift 4.x)

The fix was to make RxSwiftExt pointing to 5.x (and other Rx libs, RxBluetoothKit for example)

All CPU cores were at 100%, so you have to Ctrl-C

**Comment by avinashdongarwar** [comment]
> Got the same issue today, the issue was :
> RxSwift pointing to 5.0
> RxSwiftExt pointing to 4.0 (so looking for RxSwift 4.x)
> 
> The fix was to make RxSwiftExt pointing to 5.x (and other Rx libs, RxBluetoothKit for example)
> 
> All CPU cores were at 100%, so you have to Ctrl-C

Same problem for me.
