### ISSUE TITLE
CarthageKitTests fails on 3 Tests

### ISSUE THREAD

**Issue by relikd** [Carthage/Carthage#2837]
This issue is regarding the Carthage compilation itself (contributing).  
Not all test cases in `CarthageKitTests` pass sucessfully.

### Failed test No. 1:

> should create and read a version file for a project with no shared schemes

I do not understand why the first expeced result should be `TestFramework1_iOS`.

```
let result = buildNoSharedSchemesTest(platforms: [.iOS])
expect(result) == ["TestFramework1_iOS"]

let result2 = buildNoSharedSchemesTest(platforms: [.iOS])
expect(result2) == []
```

### Failed test No. 2:

> should build all subprojects for all platforms by default

```
Build FailedTask failed with exit code 65.  
This usually indicates that project itself failed to compile.
```

I do not see that Carthage is able to build subproject.  
E.g., if I run the latest release 0.33.0 on the `SampleMultipleSubprojects` folder Carthage exits with `"The file “Cartfile” couldn’t be opened because there is no such file."`

### Failed Test No. 3:

The folder `NoCartfile` does not exist due to git. Git only manages files, not folders.  
Fix: add an empty file to the folder.

### Additionally

Can we add a `Copy Bundle Resources` phase to the `make xcodeproj` directive?  
That phase should include everything from the `.build/debug/CarthagePackageTests.xctest/Resources` folder. So that tests can be run from within Xcode.

**Comment by tmspzz** [comment]
did you run https://github.com/Carthage/Carthage/blob/master/Makefile#L51

**Comment by relikd** [comment]
Yes, you're right, the NoCartfile gets extracted from the zip, my fault. But the test directive still returned 5 errors (3 of which are part of Test No. 2). I did copy the Resources folder manually to test within Xcode for a second time.

**Comment by tmspzz** [comment]
the test you mention do pass on CI, so most probably you have a problem with the setup

**Comment by relikd** [comment]
Ahh! my log suggests that Test No. 2 is failing because I can't build the tvOS framework. I deleted that framework, so no wonder it fails. But Test No. 1 is still weird. Why is the exact same code returning different results?

Also, why is the CI failing for my PR? If run it locally, everything compiles fine.

**Comment by relikd** [comment]
Integration Tests, e.g., [archive.bats][1] run `carthage` on the [Result][2] repository. How is this even possible if there is no Cartfile?

[1]: https://github.com/Carthage/Carthage/blob/master/IntegrationTests/archive.bats#L21
[2]: https://github.com/antitypical/Result
