### ISSUE TITLE
dsyms missing in archive folder

### ISSUE THREAD

**Issue by Sohil** [Carthage/Carthage#2840]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 10.3, Build version 10G8
* Are you using `--no-build`? Yes
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? No

When we fetch a binary framework via carthage. For Dynamic frameworks we see the `Carthage/Build/iOS/` folder has the required dsyms However when xcode archives we dont see the dsyms present in the archive folder with other dsyms

**Actual outcome**
When we fetch a binary framework via carthage. For Dynamic frameworks we see the `Carthage/Build/iOS/` folder has the required dsyms However when xcode archives we dont see the dsyms present in the archive folder with other dsyms

**Expected outcome**
Dsyms pulled via carthage should be present in archive folder. 

M i missing a configuration step here ?

**Comment by relikd** [comment]
Stating the readme file, have you added the Copy Files phase?

```
Additionally, you'll need to copy debug symbols for debugging and crash reporting on OS X.

1. On your application target’s Build Phases settings tab, click the + icon and choose New Copy Files Phase.
2. Click the Destination drop-down menu and select Products Directory.
3. For each framework you’re using, drag and drop its corresponding dSYM file.
```

**Comment by Sohil** [comment]
Thank you! @relikd for pointing me to the right direction
