### ISSUE TITLE
Carthage and Catalyst: How to proceed?

### ISSUE THREAD

**Issue by vincent-pradeilles** [Carthage/Carthage#2841]
Hello,

I’m trying to port my iPad app to the Mac using Catalyst and Xcode 11 beta. 

My app uses Carthage to handle its dependencies, and I’m not sure as to how I should proceed in order to build them in the new *.xcframework format. 

Can you set me in the right direction?

Thanks 🙂

**Comment by DavidBrunow** [comment]
This PR is an effort towards adding support for XCFrameworks to Carthage: https://github.com/Carthage/Carthage/pull/2801
