### ISSUE TITLE
Carthage Build works, but Carthage Update fails with: "Dependency ... has no shared framework schemes"

### ISSUE THREAD

**Issue by Li-Andy** [Carthage/Carthage#2846]
I am trying to add Carthage support for an existing Cocoapods framework. 
Currently I am trying to integrate the local framework to a project.
Seeing as `carthage build` was successful, as well as the fact that the target scheme is marked as shared, I don't know why `carthage update` is failing.

* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: 10E1001
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No 
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
git "/local/path/to/cardscan-ios" "master"
```

**Carthage Build Output (Works)**
```
$ carthage build --no-skip-current --platform ios
*** xcodebuild output can be found in /var/folders/p3/q_w2tbj95bv5ck5f8x6r2nv80000gn/T/carthage-xcodebuild.hPDopW.log
*** Building scheme "CardScan" in CardScan.xcworkspace
```

**Carthage Update Output (Failing)**
```
$ carthage update --platform iOS
*** Fetching cardscan-ios
*** Checking out cardscan-ios at "81327c60fa7945b16eba06d820214cc07cb074dd"
*** xcodebuild output can be found in /var/folders/p3/q_w2tbj95bv5ck5f8x6r2nv80000gn/T/carthage-xcodebuild.Srter2.log
*** Skipped building cardscan-ios due to the error:
Dependency "cardscan-ios" has no shared framework schemes for any of the platforms: iOS
```

**Actual outcome**
Carthage did not build dependency, claiming there are no shared frameworks available. 
However, the framework builds with `carthage build --no-skip-current` in its local directory.

**Expected outcome**
`carthage update` should successfully build framework.

If it helps, here is the framework directory structure:

- **_Pods.xcodeproj** (symlink to /Example/Pods/CardScan.xcodeproj)

- CardScan
- Example
    - build
    - CardScan
    - Pods (directory created from `pod install`)
        - **CardScan.xcodeproj** (symlinked by /_Pods.xcodeproj)
            - **xcshareddata/xcschemes/CardScan.xcscheme** (`carthage update` is unable to find this)
        - CardScan.xcworkspace 
- Carthage (created from `carthage build --no-skip-current`)
    - Build
        - iOS
            - **CardScan.framework** (Cannot get this to build in project using `carthage update)

**Comment by tmspzz** [comment]
The project file must be top level. From that I understand this is not the case in the directory structure you have linked.

**Comment by Li-Andy** [comment]
@tmspzz Is it not enough to have the symlink at the top level?

**Comment by ikesyo** [comment]
> The project file must be top level.

This is not true. Carthage finds project/workspace files recursively.

**Comment by ApricumMedia** [comment]
The issue in my case was that I had `xcuserdata` in my repository ignore file (e.g. `.gitignore`) to exclude constant workspace updates in another project. The *scheme* was part of this, within the project file, so it was available when calling `carthage build --no-skip-current` in the framework directory but not available after installing from Git.

Removing anything with `xcuserdata` and properly checking in the schema solved the issue for obvious reasons.
