### ISSUE TITLE
Incompatible Swift version

### ISSUE THREAD

**Issue by AlexisQapa** [Carthage/Carthage#2848]
* carthage install method: mint
* `which carthage`: n/a
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 10.3 / Build version 10G8 (no other install)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
binary "https://building42.github.io/Specs/Carthage/iOS/Fabric.json"
binary "https://building42.github.io/Specs/Carthage/iOS/Answers.json"
binary "https://building42.github.io/Specs/Carthage/iOS/Crashlytics.json"
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/5.0.1/CommonUISDK/CommonUISDK.json"== 1.0.1
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/5.0.1/ZendeskCoreSDK/ZendeskCoreSDK.json" == 2.1.0
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/5.0.1/ZendeskProviderSDK/ZendeskProviderSDK.json" == 3.0.1
binary "https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/5.0.1/ZendeskSDK/ZendeskSDK.json" == 3.0.1
```

**Carthage Output**
```
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.257.2 clang-1100.0.31.3) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5).
```

**Actual outcome**
Carthage raise a swift incompatibility error but there isn't as per: 
All -swift.h and  grep -r swiftlang ./Carthage/Build/iOS/*.bcsymbolmap gives
Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) or Swift version 5.0.1 effective-4.1.50 (swiftlang-1001.0.82.4 clang-1001.0.46.5). 
The strangest thing being there is no mention of Swift 5.1 in any file in the project.

Also:
Only the Zendesk framework is having issues removing all of it make it passes.
I can build it because it's private

**Expected outcome**
Carthage should passes

**Comment by AlexisQapa** [comment]
Solved by removing ~/Library/Caches/org.carthage.CarthageKit. Closing this but I don't have any idea how Carthage output a Swift 5.1 issue when Swift 5.1 has never been installed on the system.

**Comment by tmspzz** [comment]
https://github.com/Carthage/Carthage/blob/c47beba3e243ca8ba4d85065ae9da9279a3043bf/Source/CarthageKit/VersionFile.swift#L154

**Comment by JAIRMG** [comment]
I tried what @AlexisQapa Alexis suggested but I'm still getting problems. The output still the same:
`"Incompatible Swift version - framework was built with 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."`
