### ISSUE TITLE
[Catalyst] Carthage pick wrong scheme

### ISSUE THREAD

**Issue by parfeon** [Carthage/Carthage#2849]
* carthage install method: [x] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 10.3 (Build version 10G8)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "pubnub/objective-c"
```

**Carthage Output**
```
carthage update --platform mac
*** Fetching objective-c
*** Checking out objective-c at "v4.9.0"
*** xcodebuild output can be found in /var/folders/6y/l_rp8dq937jbx9q_jh7bplmm0000gp/T/carthage-xcodebuild.mOHosN.log
*** Building scheme "Framework (Fabric)" in PubNub.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/sergey/<...>/Carthage/Checkouts/objective-c/PubNub.xcworkspace -scheme Framework\ (Fabric) -configuration Release -derivedDataPath /Users/sergey/Library/Caches/org.carthage.CarthageKit/DerivedData/10.3_10G8/objective-c/v4.9.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/6y/l_rp8dq937jbx9q_jh7bplmm0000gp/T/objective-c SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/sergey/<...>/Carthage/Checkouts/objective-c)
```

**Actual outcome**
Carthage for macOS platform use Catalyst compatible target (`Supported Platforms` contain both `iOS` and `macOS`).

**Expected outcome**
I would expect. that for `Mac` target Carthage will find target, where `Supported Platforms` contain only one entry: `macOS` - pick proper schema called "Framework (OSX)"

**Comment by tmspzz** [comment]
please try https://github.com/Carthage/Carthage/pull/2801
