### ISSUE TITLE
Carthage：This application’s bundle identifier does not match its code signing identifier

### ISSUE THREAD

**Issue by wongshouxin** [Carthage/Carthage#2850]
I used Carthage github "NordicSemiconductor/IOS-Pods-DFU-Library" ~> 4.5.0
next，run my code allows appear：This application’s bundle identifier does not match its code signing identifier
can everyOne help me
![image](https://user-images.githubusercontent.com/20502147/63156353-1b9d1080-c047-11e9-9c74-7ba5b82a510e.png)

**Comment by tmspzz** [comment]
This is not an issue with Carthage. You're code signing settings are off or your application's bundle id has been modified after code signing.

**Comment by wongshouxin** [comment]
could  you please  tell me how  to  dealth with this problem? I am in a hurry，I have search for this problem  long time。thanks very much！

**Comment by tmspzz** [comment]
You either are using the wrong certificates. Try disabling code signing for development or just set it to "iOS Developer".

Also, let Xcode fix you code signing issues
