### ISSUE TITLE
Question about static lib

### ISSUE THREAD

**Issue by caiovncius** [Carthage/Carthage#2851]
Hi guys,

I have a beginner doubt. You can generate a * .framework file that has included all dependency * .frameworks files. So I can just include just my framework file. So you don't have multiple .frameworks files. That would be for static structures.

**Comment by tmspzz** [comment]
Yes.

However Carthage won't do that for you. [Cocoapods](https://cocoapods.org/) will.

**Comment by caiovncius** [comment]
Following this steps https://thoughtbot.com/blog/creating-your-first-ios-framework, will I get it?

**Comment by tmspzz** [comment]
I'm not sure what you're asking. That is a basic guide on how to create a framework.

Your initial question was about combining different frameworks into a static one.

**Comment by caiovncius** [comment]
You're right. Thanks.
 Do you know any tutorials for generating this static framework?
