### ISSUE TITLE
how to remove Carthage from my computer

### ISSUE THREAD

**Issue by Aiamjay** [Carthage/Carthage#2852]
* carthage install method: [1] .pkg, [ ] homebrew, [ ] source
* `which carthage`:the org file version
* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
no
```

**Carthage Output**
```
no
```

**Actual outcome**
I installed Carthage by using PKG file to temporarily build a project. So, after finished, I wanna to remove it from my computer. But on you README file, I could not find how to do it. Please tell me.

**Expected outcome**
Completely remove it from my computer.

**Comment by tmspzz** [comment]
`rm /usr/local/bin/carthage`

**Comment by lolgear** [comment]
![](https://media.tenor.com/images/9b1d6e08195517c0f98e63aba4fed4e3/tenor.gif)
