### ISSUE TITLE
How to depend on local file?

### ISSUE THREAD

**Issue by Oklahomawhore** [Carthage/Carthage#2855]
Im currently developing a framework for others to use which has some accounts and IAP features, and I have to build a demo as well for our testing team to test.

Now Im confusing with the cart file, it can reference a local binary which is a json file which points to https urls? Can  I reference the binary that was build on my computer. 

I need to integrate the whole process into gitlab CI ,  in which first build the framework I have developed and then build the demo to depend on the framework, and I'm using carthage to do it.

any help? Thank you.

**Comment by tmspzz** [comment]
you can use `file:///some/abosute/path/repo.git`

Relative paths are only supported for `binary`dependency definitions

**Comment by Oklahomawhore** [comment]
I don't want it to build twice by depending on a repo.  there's already a built framework from the previous stage. :(  Is there way to solve that?
