### ISSUE TITLE
Can I place frameoworks with the same name on Carthage/Build?

### ISSUE THREAD

**Issue by kazuhiro4949** [Carthage/Carthage#2856]
My app has a third-party binary only framework which divides .framework files by Configuration. (DEBUG, RELEASE etc.)

We wanna manage it with Carthage and install by Configuration. 

To do that, using the following setting should be best.

https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-only-frameworks

But  file names in Carthage/Build directory have to be unique. 
So we cannot install .framework files by Configuration.

https://github.com/Carthage/Carthage/issues/1769

Could you tell me the best practice to the case?

Thanks

* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`:   0.33.0
* `xcodebuild -version`:  Xcode 10.3
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`? no 
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  no 
* Are you using `--new-resolver`?  no

**Cartfile**
```

```

**Carthage Output**
```
```

**Actual outcome**
nothing

**Expected outcome**
Carthage should place frameworks with same name onto Carthage/Build.

**Comment by tmspzz** [comment]
This is not supported. Frameworks are not namespaced.

**Comment by kazuhiro4949** [comment]
@tmspzz 
Thanks for your reply.
Is there a way to change some urls in Cartfile with an arguments or environment variable?
