### ISSUE TITLE
Travis CI and Carthage: how should we configure our .travis.yml file to get Quick and Nimble frameworks to work?

### ISSUE THREAD

**Issue by connected-akhan** [Carthage/Carthage#2858]
Hi, we use the Quick and Nimble frameworks, installed via carthage. 
We use Travis CI, but are having trouble with the build, when we git push. Please see error below. How should we configure our .travis.yml file to get Quick and Nimble frameworks to work?

The .travis.yml file:
![image](https://user-images.githubusercontent.com/45395977/64198145-ace8f100-ce55-11e9-96d9-e1063dd139d8.png)

The error in the log file:
<img width="821" alt="Screen Shot 2019-09-03 at 2 22 17 PM" src="https://user-images.githubusercontent.com/45395977/64198485-4dd7ac00-ce56-11e9-8502-ff87529d8b9c.png">

The root directory where the .travis.yml file is:
<img width="966" alt="Screen Shot 2019-09-03 at 2 23 46 PM" src="https://user-images.githubusercontent.com/45395977/64198546-72cc1f00-ce56-11e9-8b77-a831954a3804.png">

cd UnItSpecsHost from root directory:
<img width="810" alt="Screen Shot 2019-09-03 at 2 25 44 PM" src="https://user-images.githubusercontent.com/45395977/64198679-b9217e00-ce56-11e9-8dfd-929127ed7ed8.png">

**Comment by tmspzz** [comment]
There is no special configuration. 

I see you have a Cartfile.private so everything looks fine. In your test target make sure you have a "Copy Frameworks Phase"
<img width="1034" alt="Screenshot 2019-09-03 at 22 57 35" src="https://user-images.githubusercontent.com/196761/64208139-7a171b00-ce9e-11e9-912d-7ad74c2448e2.png">

**Comment by connected-akhan** [comment]
Thanks! Also, we had to run `carthage update` in both directories: the root directory and the `UnItSpecsHost` directory, which has our sample app. It works now. See new .yml file below:
<img width="500" alt="Screen Shot 2019-09-27 at 10 32 53 PM" src="https://user-images.githubusercontent.com/45395977/65810323-1b7c4e80-e177-11e9-97cd-a050a107e9da.png">
