### ISSUE TITLE
Build swiftyjson failed

### ISSUE THREAD

**Issue by haolong886** [Carthage/Carthage#286]
i can build Alamofire successfully, but build swiftyjson failed, error messages below:

>     SDKROOT = iphonesimulator8.1
>   
> === BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===
> 
> Check dependencies
> 
> Write auxiliary files
> write-file /Users/coolhand/Library/Developer/Xcode/DerivedData/SwiftyJSON-fremfbacgegukqfhjwfehvcuninn/Build/Intermediates/SwiftyJSON.build/all-product-headers.yaml
> 
> === BUILD TARGET SwiftyJSONTests OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===
> 
> Check dependencies
> 
> ** BUILD SUCCEEDED **
>  
> Build settings from command line:
>     SDKROOT = iphoneos8.1 
>   
> === BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===
> 
> Check dependencies
> 
> Write auxiliary files
> write-file /Users/coolhand/Library/Developer/Xcode/DerivedData/SwiftyJSON-fremfbacgegukqfhjwfehvcuninn/Build/Intermediates/SwiftyJSON.build/all-product-headers.yaml
> 
> === BUILD TARGET SwiftyJSONTests OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===
> 
> Check dependencies
> Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
> CodeSign error: code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 8.1'
>

**Comment by jspahrsummers** [comment]
See https://github.com/Carthage/Carthage/issues/281#issuecomment-70126876.
