### ISSUE TITLE
RPC failed; curl 18 transfer closed with outstanding read data

### ISSUE THREAD

**Issue by zhumj** [Carthage/Carthage#2873]
carthage install method: [ ] .pkg
which carthage: /usr/local/bin/carthage
carthage version: 0.33.0
xcodebuild -version: Xcode 10.3
Are you using --no-build? No
Are you using --no-use-binaries? No
Are you using --use-submodules? No
Are you using --cache-builds? No
Are you using --new-resolver? No

This error was reported when I added "github "danielgindi/Charts" == 3.2.2" and "Carthage update --platform iOS". 
Setting Git config --global http.postbuffer 524288000 or higher still won't work.

**Comment by tmspzz** [comment]
This is a problem with git on your side.

**Comment by zhumj** [comment]
What do I need to do?Upgrade the Git?

**Comment by zhumj** [comment]
> This is a problem with git on your side.
What do I need to do?Upgrade or reinstall Git?

**Comment by vpeschenkov** [comment]
For those who has the same issue, I've solved this by updating the git to the latest version. The following article explains how you can do this https://medium.com/@katopz/how-to-upgrade-git-ff00ea12be18. Hope it saves you some time 🙂
