### ISSUE TITLE
fatal: destination path already exists and is not an empty directory

### ISSUE THREAD

**Issue by eimantas** [Carthage/Carthage#2874]
* carthage install method: [x] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0 
* `xcodebuild -version`: 10.3
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? yes
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "company/feature-01" "develop"
github "company/feature-02" "develop"
github "company/feature-03" "develop"
github "company/feature-04" "develop"
github "company/feature-05" "develop"
```

**Carthage Output**
```
% carthage update --platform ios --use-submodules                                                                                     
*** Cloning feature-01
*** Cloning feature-02
*** Cloning feature-03
*** Cloning feature-04
*** Cloning feature-05
*** Cloning core
*** Cloning core
*** Cloning core
*** Cloning core
*** Cloning core
*** Cloning braintree-ios-drop-in
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/company/core.git /Users/eimantas/Library/Caches/org.carthage.CarthageKit/dependencies/core) failed with exit code 128:
fatal: destination path '/Users/eimantas/Library/Caches/org.carthage.CarthageKit/dependencies/core' already exists and is not an empty directory.
```

**Actual outcome**
Carthage fails and stops the update process.

**Expected outcome**
Carthage doesn't fail.

The actual graph for the dependencies is that application has many feature dependencies (feature-01 ...  -05) that all depend on same core. (so you can say we have a diamond shaped dependency tree:

```
    Project
   / / | \  \
 F1 F2 F3 F4 F5
   \ \ | /  /
      Core
```

Also I'm calling the command after explicitly removing the caches from `~/Library/Caches/org.carthage.carthagekit` as well as removing the `Carthage` folder from project directory. How can I fix this?

**Comment by eimantas** [comment]
There are binaries, but they are being built from source due to incompatible compiler versions. Would this still be an issue?

**Comment by tmspzz** [comment]
Try `--no-use-binaries`

**Comment by eimantas** [comment]
This seems to have solved my problems.
