### ISSUE TITLE
Carthage stuck while downloading repos in Swift 5.1

### ISSUE THREAD

**Issue by GDXRepo** [Carthage/Carthage#2883]
* carthage install method: [X] .pkg, [ ] homebrew, [ ] source
* which carthage: /usr/local/bin/carthage
* carthage version: 0.33.0
* xcodebuild -version: Xcode 11.0 | Build version 11A420a
* Are you using --no-build? NO
* Are you using --no-use-binaries? NO
* Are you using --use-submodules? NO
* Are you using --cache-builds? NO
* Are you using --new-resolver? YES

[The issue](https://github.com/Carthage/Carthage/issues/2737) comes back with Xcode 11 & Swift 5.1. Executing without the `--new-resolver` option leads to 247% CPU usage and infinite execution. If I add the `--new-resolver` than Carthage begins doing some cycled calls, and it never finishes. 

Cartfile:

```
github "onmyway133/DeepDiff"
github "tristanhimmelman/ObjectMapper"
github "daltoniam/Starscream"
github "realm/realm-cocoa"
github "Alamofire/Alamofire"
github "CocoaLumberjack/CocoaLumberjack"
github "onevcat/Kingfisher"
github "iziz/libPhoneNumber-iOS"
github "caravaneer404/swift-sodium"
github "SwiftKickMobile/SwiftMessages"
github "HHK1/PryntTrimmerView"
github "Asana/Drawsana"
github "gizmosachin/ColorSlider"
github "Ava8/RealmBrowser"
github "Ava8/Mantis"
```

Carthage log:

```
$ carthage update --platform iOS --new-resolver
*** Fetching PryntTrimmerView
*** Fetching Kingfisher
*** Fetching ObjectMapper
*** Fetching Starscream
*** Fetching AssetsPicker
*** Fetching ImageResizeExtension
*** Fetching SwiftMessages
*** Fetching ColorSlider
*** Fetching ProgressView
*** Fetching libPhoneNumber-iOS
*** Fetching Keychain
*** Fetching Drawsana
*** Fetching Alamofire
*** Fetching realm-cocoa
*** Fetching DeepDiff
*** Fetching RealmBrowser
*** Fetching CocoaLumberjack
*** Fetching Mantis
*** Fetching swift-sodium
*** Fetching SnapKit
*** Fetching Device
....................
and it never finishes
```
Also I tried to clear Carthage cache or remove *.resolved file - it has no effect.

**Comment by michaelosity** [comment]
Same issue here.

**Comment by mendesbarreto** [comment]
Hello guys!

My problem is the same as described by @GDXRepo , someone has some workaround? 

carthage install method: [] .pkg, [x ] homebrew, [ ] source
which carthage: /usr/local/bin/carthage
carthage version: 0.34.0
xcodebuild -version: Xcode 11.2.1 | Build version 11B500
Are you using --no-build? NO
Are you using --no-use-binaries? NO
Are you using --use-submodules? NO
Are you using --cache-builds? NO
Are you using --new-resolver? YES / NO (I tried both)

My Cartfile is:
```
# Network
github "Moya/Moya" ~> 13.0

#UI
github "SnapKit/SnapKit"


#Utils
github "evgenyneu/keychain-swift"
github "RxSwiftCommunity/RxGesture"
github "ReactiveX/RxSwift"
github "krzyzanowskim/CryptoSwift"

#test
github "Quick/Quick"
github "Quick/Nimble"
```

Carthage log:
```
*** Fetching CryptoSwift
*** Fetching RxSwift
*** Fetching Nimble
*** Fetching RxGesture
*** Fetching SnapKit
*** Fetching keychain-swift
*** Fetching Moya
*** Fetching Quick
*** Fetching ReactiveSwift
*** Fetching Result
*** Fetching Alamofire
```

**Comment by mendesbarreto** [comment]
Hey @GDXRepo I took a look at our Cartfiles to see which dependencies are similar and maybe is causing the problem and it seems the Alamofire is the one!  I removed it as a dependency and the  Carthage was able to build the others. The question is WHY?

**Comment by Aranoledur** [comment]
@mendesbarreto technically you can download latest Carthage from master, build it with the connected debugger in XCode and pass your Cartfile. So you will see what causes a problem. 
And try `--no-use-binaries` flag, maybe it will help

**Comment by mendesbarreto** [comment]
Hey! Thank you @Aranoledur for the response =) . I really want to start to contribute to carthage, maybe it's the opportunity ahahaha. 

But I already tried every single command included ```--no-use-binaries``` and it does not work.

I saw the problem and I am sure, it is not on the build step. For instance, when the carthage enter on the situation described above the Cartfile.resolved was never generated, because it not capable of get the versions from repositories, i.e, Carthage was stuck forever on fetching or cloning step.

Thank you

**Comment by DavidBrunow** [comment]
@mendesbarreto Have you also tried `--new-resolver`? Carthage can get stuck when trying to determine the dependency tree which is improved by that flag.

**Comment by mendesbarreto** [comment]
Yeap I tried the ```--new-resolver``` as well, but the problem seems to happen only for the Alamofire/Moya, when I removed them from Cartfile everything was resolved and build for good.

**Comment by mendesbarreto** [comment]
I did another test, when I inserted Moya dependency alone on Cartfile, the problem above occurs, it seems the Alamofire version could not be defined:
```
github "Moya/Moya"
```
But if I change the Cartfile to:
```
github "Moya/Moya" "14.0.0-beta.5"
github "Alamofire/Alamofire" "5.0.0-rc.3"
```
Carthage was capable to build without problems.

**Comment by DavidBrunow** [comment]
Carthage's resolver (and new resolver) does not always work out the dependency tree properly. There is work to improve this on the roadmap (https://github.com/Carthage/Carthage/issues/2890) but the workaround, as you found, is to be more explicit with the dependencies to give the resolver the extra information it needs.

**Comment by jdhealy** [comment]
What you’re hitting is the ‘escape hatches feature of Carthage where it can treat any non-semantically-versioned tag name as satisfying any dependency.

Coming at it from the trying-to-work-a-bugfix-branch-into-already-existing-series-of-Cartfiles angle, it provides ease and utility; but definite downside from the specified-tightly-scopes-dependency-specification angle where it can resort to grabbing a pretty random-seeming non-semantically-versioned tag when either resolver can’t solve with the set of semantically-versioned tags.

Definite downsides but as it’s so relied-upon and baked-in-to-its-nature of Carthage, it won’t be changing.
