### ISSUE TITLE
Wrong version requirement resolution when updating

### ISSUE THREAD

**Issue by niorko** [Carthage/Carthage#2889]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 11.0; Build version 11A420a
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes
* Are you using `--new-resolver`? no

I have multiple SDKs built by the Carthage and they also contain some nested dependencies. I am using semantic versioning. When I try to update my dependency from `0.4.2` to `0.5.0` it is telling me, that some nested dependency has an incompatible requirement, but I've only bumped minor version, not the major one. And every dependency us using `~>` operator.

Please help, it is frustrating to update every framework from our SDK every time we add new features into one of them.

It works only when we bump the last fix version (0.4.X).

**Project Cartfile**
```
git "git@one-repo" ~> 0.5.0
```

**Carthage Output**
```
Could not pick a version for git "git@one-dependency", due to mutually incompatible requirements:
    ~> 0.5.1
    ~> 0.4.0 (git "git@another-dependency")
```

**Actual outcome**
Carthage did not update the project.

**Expected outcome**
Carthage should update the project to the right version.

**Comment by beatrob** [comment]
Same issue here

**Comment by niorko** [comment]
https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#version-requirement

My fault.. I didn't read the README correctly.

> According to SemVer, any 0.x.y release may completely break the exported API, so it's not safe to consider them compatible with one another. Only patch versions are compatible under 0.x, meaning 0.1.1 is compatible with 0.1.2, but not 0.2. This isn't according to the SemVer spec but keeps ~> useful for 0.x.y versions

So it works as expected. Closing the issue.
