### ISSUE TITLE
--xcodebuild-timeout option

### ISSUE THREAD

**Issue by ismetanin** [Carthage/Carthage#2891]
Hi! I'd like to add `--xcodebuild-timeout` option which was described in #2646. But I can't figure out how to pass option from `Build`/`Update` to the `BuildSettings`, could you help me a little?

**Comment by ismetanin** [comment]
So pity 😢

**Comment by tmspzz** [comment]
I don't think build arguments is the right place since it isn't strictly a parameter for Xcode but rather for carthage itself.

**Comment by ismetanin** [comment]
@tmspzz Then maybe you have some suggestions?

**Comment by tmspzz** [comment]
`BuildOptions` ?

**Comment by ismetanin** [comment]
@tmspzz Okay, `BuildOptions` looks good, but here is the question: how could I pass build options to `BuildSettings.load(with:for:)`? Or at least I should pass there my new `xcodebuildTimeout` property from `BuildOptions`. For me, it looks like we don't have a direct connection between these parts :(
