### ISSUE TITLE
Invalid cache when using --cache-builds for dependencies that have common sub dependencies

### ISSUE THREAD

**Issue by edulpn** [Carthage/Carthage#2892]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: 10.3
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  yes
* Are you using `--new-resolver`? no

**Cartfile**
```
github "kustomer/customer-ios" ~> 0.2.4
github "Appboy/appboy-ios-sdk" ~> 3.20
```

**Carthage Output**
```
carthage bootstrap appboy-ios-sdk --cache-builds --platform iOS
*** Checking out appboy-ios-sdk at "3.20.4"
*** xcodebuild output can be found in /var/folders/0t/4lpgbc8x09d3cm540qq49kpc38kfsx/T/carthage-xcodebuild.81x4rz.log
*** Invalid cache found for appboy-ios-sdk, rebuilding with all downstream dependencies
*** Installing appboy-ios-sdk binary at "3.20.4"

carthage bootstrap --cache-builds --no-use-binaries --platform iOS
*** Checking out customer-ios at "0.2.4"
*** Checking out appboy-ios-sdk at "3.20.4"
*** xcodebuild output can be found in /var/folders/0t/4lpgbc8x09d3cm540qq49kpc38kfsx/T/carthage-xcodebuild.PwazP7.log
*** Valid cache found for appboy-ios-sdk, skipping build
*** Invalid cache found for customer-ios, rebuilding with all downstream dependencies
*** Building scheme "Kustomer" in Kustomer.xcworkspace
*** Building scheme "FLAnimatedImage" in Kustomer.xcworkspace
*** Building scheme "SDWebImage" in Kustomer.xcworkspace
*** Building scheme "libPusher" in Kustomer.xcworkspace
*** Building scheme "NYTPhotoViewer" in Kustomer.xcworkspace
*** Building scheme "TTTAttributedLabel" in Kustomer.xcworkspace
*** Building scheme "TSMarkdownParser" in Kustomer.xcworkspace
*** Building scheme "SocketRocket" in Kustomer.xcworkspace
```

**Actual outcome**
Carthage always rebuild `customer-ios` (uses Cocoapods for its dependencies, so the project has a shared scheme for each of its dependencies, so Carthage generates the frameworks for them) and re-download the pre built binary for `appboy-ios-sdk` (devs of this dependency do not support `--no-use-binaries` for some reason, so they don't share a scheme, I have to download the pre-built binary). Both of them have `SDWebImage` as a dependency, so I guess (please correct me if  the version files for them have different hashes and Carthage is not recognizing a valid cache. Because `appboy-ios-sdk` doesn't build `SDWebImage`, I'm using/linking the one that is built through `customer-ios` Cocoapods shared scheme and it works fine because both dependencies use compatible versions of `SDWebImage`,  but it needs to be rebuilt everytime I run `carthage bootstrap`

**Expected outcome**
I'm not sure what the expected outcome should be, because dependencies can, and often do, have the same sub dependencies which in turn can be, and often are, conflicting in terms of versions, but I guess I would expect Carthage to be able to check cache validation in a way that I don't need to rebuild dependencies that have the same dependency every time I run  `carthage bootstrap  --cache-builds`.

**Comment by kenji21** [comment]
Tried to use only appboy-ios-sdk without success:

```
kenji@macboo:~/Desktop/cart-issue-2892
carthage bootstrap appboy-ios-sdk --cache-builds --platform iOS --no-use-binaries
*** No Cartfile.resolved found, updating dependencies
*** Cloning appboy-ios-sdk
*** Checking out appboy-ios-sdk at "3.20.4"
*** No cache found for appboy-ios-sdk, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.sQ9UNh.log
*** Skipped building appboy-ios-sdk due to the error:
Dependency "appboy-ios-sdk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Appboy/appboy-ios-sdk/issues/new

kenji@macboo:~/Desktop/cart-issue-2892
cat Cartfile
github "Appboy/appboy-ios-sdk" ~> 3.20
```

Can you provide your Cartfile.resolved, as I got an error while trying to build appboy.

Then, for customer-ios, can you try with current master, it works with my current fork (having some commits for creating a shared cache, cf issue #2400):

```
kenji@macboo:~/Desktop/cart-issue-2892
cat Cartfile
#github "Appboy/appboy-ios-sdk" ~> 3.20
github "kustomer/customer-ios" ~> 0.2.4

kenji@macboo:~/Desktop/cart-issue-2892
carthage update customer-ios --cache-builds --platform iOS --no-use-binaries
*** Cloning customer-ios
*** Checking out customer-ios at "0.2.4"
*** No cache found for customer-ios, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.d7VX1Y.log
*** Building scheme "Kustomer" in Kustomer.xcworkspace
*** Building scheme "FLAnimatedImage" in Kustomer.xcworkspace
*** Building scheme "SDWebImage" in Kustomer.xcworkspace
*** Building scheme "libPusher" in Kustomer.xcworkspace
*** Building scheme "NYTPhotoViewer" in Kustomer.xcworkspace
*** Building scheme "SocketRocket" in Kustomer.xcworkspace
*** Building scheme "TTTAttributedLabel" in Kustomer.xcworkspace
*** Building scheme "TSMarkdownParser" in Kustomer.xcworkspace

kenji@macboo:~/Desktop/cart-issue-2892
carthage bootstrap customer-ios --cache-builds --platform iOS --no-use-binaries
*** Checking out customer-ios at "0.2.4"
*** xcodebuild output can be found in /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.STXIcH.log
*** Valid cache found for customer-ios, skipping build
```

**Comment by edulpn** [comment]
As stated on my "question"/"report" `appboy-ios-sdk` doesn't share a scheme "by design", so `--no-use-binaries` will not work with it. To go around that, I run `carthage bootstrap appboy-ios-sdk --cache-builds --platform iOS` and `carthage bootstrap --cache-builds --no-use-binaries --platform iOS` (which skips building `appboy-ios-sdk` for the first time because the cache is valid. On subsequent runs it'll fail to validate).

**Comment by edulpn** [comment]
About caching, I'm already using Rome, but this shouldn't be interfering with the different `SDWebImage` hashes on both `.customer-ios.version` and `.appboy-ios-sdk.version`

**Comment by kenji21** [comment]
```
grep -H -A 1 SDWebImage Carthage/Build/.*.version
Carthage/Build/.appboy-ios-sdk.version:      "name" : "SDWebImage",
Carthage/Build/.appboy-ios-sdk.version-      "hash" : "4b7f5a31de5f3d48a8f07b4db09ccd0f894b0d78201cd8b0c409310f484aff9a"
--
Carthage/Build/.customer-ios.version:      "name" : "SDWebImage",
Carthage/Build/.customer-ios.version-      "hash" : "c965e189ba171fb5c654bdcff06d8ad7d5ab685fc34884d847b043b272ae3d9f"
```

the hash is (from hashForFileAtURL in VersionFile.swift):

```
	let task = Task("/usr/bin/shasum", arguments: ["-a", "256", frameworkFileURL.path])
```

So after a clean `carthage update --cache-builds --platform iOS` with both dependencies in the Cartfile:

```
shasum -a 256 Carthage/Build/iOS/SDWebImage.framework/SDWebImage
c965e189ba171fb5c654bdcff06d8ad7d5ab685fc34884d847b043b272ae3d9f  Carthage/Build/iOS/SDWebImage.framework/SDWebImage
```

it's SDWebImage from customer-ios which is taken... but it is not added as a submodule in customer-ios... https://github.com/kustomer/customer-ios/tree/master/Pods/SDWebImage, so we can't determine which version is used (or if it contains custom patches), but last commit show it uses 5.0 version.

Then, Apply uses https://github.com/Appboy/appboy-ios-sdk/blob/master/Appboy-iOS-SDK.podspec also show version to be a 5.x...

So they uses the same major...

```
kenji@macboo:~/Desktop/cart-issue-2892
rm -rf Carthage/

kenji@macboo:~/Desktop/cart-issue-2892
carthage update --cache-builds --platform iOS
*** Fetching customer-ios
*** Fetching appboy-ios-sdk
*** Checking out appboy-ios-sdk at "3.20.4"
*** Checking out customer-ios at "0.2.4"
*** No cache found for appboy-ios-sdk, building with all downstream dependencies
*** No cache found for customer-ios, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.3AvThU.log
*** Copying from shared cache for customer-ios, skipping build
*** Downloading appboy-ios-sdk.framework binary at "3.20.4"

kenji@macboo:~/Desktop/cart-issue-2892
carthage bootstrap --cache-builds --platform iOS
*** Checking out appboy-ios-sdk at "3.20.4"
*** Checking out customer-ios at "0.2.4"
*** xcodebuild output can be found in /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.D9vnV7.log
*** Valid cache found for appboy-ios-sdk, skipping build
*** Invalid cache found for customer-ios, rebuilding with all downstream dependencies
*** Copying from shared cache for customer-ios, skipping build
```

If you run carthage bootstrap twice, one is invalid (due to the hash of SDWebImage), then it's the other one... 

```
kenji@macboo:~/Desktop/cart-issue-2892
carthage bootstrap --cache-builds --platform iOS
*** Checking out appboy-ios-sdk at "3.20.4"
*** Checking out customer-ios at "0.2.4"
*** xcodebuild output can be found in /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.FcwQjS.log
*** Valid cache found for appboy-ios-sdk, skipping build
*** Invalid cache found for customer-ios, rebuilding with all downstream dependencies
*** Copying from shared cache for customer-ios, skipping build

kenji@macboo:~/Desktop/cart-issue-2892
carthage bootstrap --cache-builds --platform iOS
*** Checking out customer-ios at "0.2.4"
*** Checking out appboy-ios-sdk at "3.20.4"
*** xcodebuild output can be found in /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.t5wDn1.log
*** Invalid cache found for appboy-ios-sdk, rebuilding with all downstream dependencies
*** Valid cache found for customer-ios, skipping build
*** Downloading appboy-ios-sdk.framework binary at "3.20.4"
```

These two dependencies are not using a dependency manager for their deps... so carthage can't be aware of them, and can't compile them with the same options / produce exactly the same build (and so the same hash)

**Comment by edulpn** [comment]
Yeah, I get it. As I mentioned before, I'm not really sure what were my expectations, especially because both dependencies don't use Carthage for their own management, so it's only natural Carthage can't know for sure what's happening. Anyway, as you also pointed out, everything is using compatible versions, so linking the `SDWebImage` framework generated by `customer-ios` works alright. I tweaked my scripts to be more reliant on the Rome cache and it's `list --missing` feature, which works for me (I'm actually trying to use fewer dependencies, instead of adding more).
Thanks @kenji21 for the thorough explanations, I was not actually far off on my first theories, this is golden material for people with similar problems in the future.

**Comment by edulpn** [comment]
@tmspzz this was the remaining issue I had after I got the repository map working. I'd like to talk to you a bit about `rome list --missing`, if you had some time.

**Comment by tmspzz** [comment]
@edulpn please [open an new issue in Rome](https://github.com/tmspzz/Rome/issues/new)
