### ISSUE TITLE
AFNetworking

### ISSUE THREAD

**Issue by ydlsl** [Carthage/Carthage#2895]
Building scheme "AFNetworking iOS" in AFNetworking.xcworkspace
Build Failed
	Task failed with exit code 65:

**Comment by ikesyo** [comment]
Please file an issue on AFNetworking repository.

**Comment by ydlsl** [comment]
This is a problem that occurs after building AFNetworking after carthage update

**Comment by ydlsl** [comment]
> Could you please file an issue on AFNetworking repository.

This is a problem that occurs after building AFNetworking after carthage update

**Comment by ikesyo** [comment]
It would be a duplicate of https://github.com/AFNetworking/AFNetworking/issues/4445 if you are using Xcode 11.
