### ISSUE TITLE
Cartfile does not resolve patch versions as expected when using ~>

### ISSUE THREAD

**Issue by maiteko** [Carthage/Carthage#2896]
* carthage install method: [ ] .pkg, [x ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: 
* Are you using `--no-build`? yes
* Are you using `--no-use-binaries`? no 
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes
* Are you using `--new-resolver`? no

**Cartfile**
```
git "{private company repo}" ~> 6.11.0
```

**Cartfile.resolved output**
```
git "{private company repo}" "6.12.0"
```

**Actual outcome**
Carthage selected next minor version, rather than limiting to patch releases

**Expected outcome**
Coming from a ruby background with gemfiles, we expected the ~> symbol to work more like this:
```
~> 6.11 : => 6.11, < 7.0 (would resolve to 6.12)
~> 6.11.0 : => 6.11.0, < 6.12 (would resolve to 6.11.28358 in our environment)
```

**Comment by tmspzz** [comment]
I don't think we intend to change this. `~>` mean compatible with and 6.12 is compatible with 6.11.x
