### ISSUE TITLE
How to use Carthage to implement subspec like Cocoapods

### ISSUE THREAD

**Issue by ydlsl** [Carthage/Carthage#2899]
I have a framework named A, and a sub framework named A-Core in it, A is dependented on A-Core, they are in the same repo.

in Cocoapods, just create a subspec, and how to write the Cartfile in Carthage at this case

**Comment by tmspzz** [comment]
There is no such thing as a subspec, but Carthage will build any .xcodeproj or .xcworkspace and all the relevant targets in them.

**Comment by noobs2ninjas** [comment]
I so wish this could be added. I'm a member of [Parse](http://parseplatform.org) and one of our MAJOR iOS/macOS sdk dependencies Bolts has been abandoned by its maintainer(Facebook) After upgrading Xcode build environments, the only way to get it to keep building without completely replacing it is by using one of its subspecs. Easy enough on cocoapods but unfortunately our CircleCI integration uses Carthage. Which means well have to fork and maintain the repo ourselves and do some massive work. Also, I might point out that our iOS framework itself is pretty massive and could really benefit from incorporating some type of carthage subspec like we do with Cocoapods. 

+1 for adding subspec functionality

**Comment by tmspzz** [comment]
This is not a feature we plan to support, at least in the close future. See the roadmap for reference https://github.com/Carthage/Carthage/issues/2890

**Comment by tmspzz** [comment]
That said

> There is no such thing as a subspec, but Carthage will build any .xcodeproj or .xcworkspace and all the relevant targets in them.

so you can make a xcodeproj representing your subspec and carthage will build it

**Comment by noobs2ninjas** [comment]
Good idea. Which gives me ideas about doing multi-target(iOS, WatchOS, macOS) project builds in Circle which is setting specific dependency targets from those projects prior to having carthage build it out. Not sure if I made any sense but trust me your suggestion just helped a ton.
