### ISSUE TITLE
Carthfile.resolved not created

### ISSUE THREAD

**Issue by RuiAAPeres** [Carthage/Carthage#290]
After running `carthage update` as stated:

> After running the carthage update command, a file named `Cartfile.resolved` will be created alongside the Cartfile in the working directory.

But on LlamaKit that doesn't happen (the file is never created). The framework is created and I am able to use it successfully, but as recommended I would like to keep  `Cartfile.resolved` on the repo.

**Comment by RuiAAPeres** [comment]
Wouldn't make sense to use `Cartfile.lock` instead?

**Comment by robrix** [comment]
> Wouldn't make sense to use `Cartfile.lock` instead?

It used to be named that, see #107 for why it was changed.

**Comment by RuiAAPeres** [comment]
@robrix thanks for the reference. The reason why I asked that, was because that file (`Cartfile.lock`) is created, but no the `Cartfile.resolved`, hence my question.

**Comment by mdiep** [comment]
If `Cartfile.lock` is created, you must be using an older version of Carthage.

**Comment by RuiAAPeres** [comment]
@mdiep I am using the brew one.

**Comment by robrix** [comment]
@RuiAAPeres Can you please do `carthage version` and let us know what that says? You may need to `brew update` and `brew install carthage` to upgrade it.

**Comment by jspahrsummers** [comment]
Also, do _not_ use [homebrew-cask](https://github.com/caskroom/homebrew-cask). It has an outdated version of Carthage, for some reason.

**Comment by RuiAAPeres** [comment]
@robrix this is embarassing but `carthage version` doesn't even work: `Unrecognized command: 'version'. See `carthage help`.`

**Comment by jspahrsummers** [comment]
@RuiAAPeres That's definitely an old version then. Please try `brew update` and `brew install carthage` to get the latest.

If that still doesn't fix it, you may want to [install manually](https://github.com/Carthage/Carthage#installing-carthage).

**Comment by RuiAAPeres** [comment]
@jspahrsummers installed it manually, it's working as expected. Could be beneficial for future users to warn them about brew potentially having an old version?

**Comment by jspahrsummers** [comment]
Well, it doesn't. :stuck_out_tongue_closed_eyes: I don't know what happened to your local formula.
