### ISSUE TITLE
Content is duplicated inside generate Swift header

### ISSUE THREAD

**Issue by sirghi** [Carthage/Carthage#2906]
When generating a framework using:

    carthage build  --platform ios --no-skip-current
The generated swift header file located at `SDK.framework/Headers/SDK-Swift.h` contains the same symbols multiplied 4 times, as if copy-pasting the contents of the file 4 times. Presumably it's related to the 4 arch types that carthage builds and lipo's the framework into.

Anyone else experiencing this?

**Comment by DavidBrunow** [comment]
@sirghi Are each of the symbols inside `#if` statements?

**Comment by sirghi** [comment]
Hm, indeed it is, according to the architectures - `__i386__`, `__arm64__`, `__ARM_ARCH_7A__`, `__x86_64__`. So this means it's expected?

I wonder why does it do it like that. Can the code declarations be different for different architectures?

**Comment by DavidBrunow** [comment]
This is a change that was introduced in Xcode 10.2 and yes, the declarations can be different for different architectures. Here is the pull request that added functionality to Carthage to work around this issue: https://github.com/Carthage/Carthage/pull/2723. That pull request has a link to an issue with more details.

**Comment by sirghi** [comment]
Ok, read and understood. Thanks for the explanation.
