### ISSUE TITLE
`carthage build --archive` and `carthage build --no-skip-current` build my framework twice

### ISSUE THREAD

**Issue by iAgentur** [Carthage/Carthage#2911]
* carthage install method: homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`: Xcode 10.3 Build version 10G8
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
empty

**Carthage Output**
1. xcodebuild output: [carthage-xcodebuild.8gQHDW.log](https://github.com/Carthage/Carthage/files/3892499/carthage-xcodebuild.8gQHDW.log)

```
$ carthage build --archive --platform iOS --project-directory . 
*** xcodebuild output can be found in /var/folders/__/js0rr6z55353tb66xy87rt6h0000gn/T/carthage-xcodebuild.8gQHDW.log
*** Building scheme "TDASDK" in TDASDK.xcworkspace
*** Building scheme "TDASDK" in TDASDK.xcworkspace
*** Found Carthage/Build/iOS/TDASDK.framework
*** Found Carthage/Build/iOS/TDASDK.framework.dSYM
*** Found Carthage/Build/iOS/9090E39C-7187-337D-A75B-CAAA5FF265C3.bcsymbolmap
*** Found Carthage/Build/iOS/2E5FD94F-72F2-3E20-B25B-710E5DE98AF0.bcsymbolmap
*** Found Carthage/Build/iOS/CFDCD8B6-FEE3-3F34-81D9-B4112ED28344.bcsymbolmap
*** Found Carthage/Build/iOS/53759780-881A-3C6D-A317-FAAA5FC872DD.bcsymbolmap
*** Created TDASDK.framework.zip
```

2. xcodebuild output: [carthage-xcodebuild.Q3ZrSU.log](https://github.com/Carthage/Carthage/files/3892503/carthage-xcodebuild.Q3ZrSU.log)

```
$ carthage build --no-skip-current --platform iOS --project-directory .
*** xcodebuild output can be found in /var/folders/__/js0rr6z55353tb66xy87rt6h0000gn/T/carthage-xcodebuild.Q3ZrSU.log
*** Building scheme "TDASDK" in TDASDK.xcworkspace
*** Building scheme "TDASDK" in TDASDK.xcworkspace
```

```
$ carthage archive TDASDK
*** Found Carthage/Build/iOS/TDASDK.framework
*** Found Carthage/Build/iOS/TDASDK.framework.dSYM
*** Found Carthage/Build/iOS/CFDCD8B6-FEE3-3F34-81D9-B4112ED28344.bcsymbolmap
*** Found Carthage/Build/iOS/9090E39C-7187-337D-A75B-CAAA5FF265C3.bcsymbolmap
*** Found Carthage/Build/iOS/2E5FD94F-72F2-3E20-B25B-710E5DE98AF0.bcsymbolmap
*** Found Carthage/Build/iOS/53759780-881A-3C6D-A317-FAAA5FC872DD.bcsymbolmap
*** Created TDASDK.framework.zip
```

**Actual outcome**

- Carthage built my framework twice.
- output produced symbol maps that aren't present on the disk

**Expected outcome**

- Carthage should build my framework once.
- not present symbol maps aren't printed

**Extra info**

My project tree:
```
$ ls -1p
CHANGELOG.md
Cartfile
Cartfile.private
Cartfile.resolved
Carthage/
Carthage 2/
Gemfile
Gemfile.lock
README.md
Review.txt
TDA-integration-test/
TDASDK/
TDASDK-demo/
TDASDK.framework.zip
TDASDK.podspec
TDASDK.xcodeproj/
TDASDK.xcworkspace/
TDASDKTests/
fastlane/
set_new_version.sh
sonar-project.properties
```

`Carthage/` contains the built framework, `Carthage 2/` is unzipped `TDASDK.framework.zip` (it's identical to the contents of the former directory).

Contents of `Cartfile.private`:
```
github "AliSoftware/OHHTTPStubs" ~> 8.0
```

This library is used only in Tests, so I use `--project-directory .` to skip building it. (edit: now I understand that this option actually makes no sense)

Xcode project:
```
$ xcodebuild -list
Information about project "TDASDK":
    Targets:
        TDASDK
        TDASDKTests

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        TDASDK
```

```
$ xcodebuild -list -workspace TDASDK.xcworkspace
Information about workspace "TDASDK":
    Schemes:
        TDASDK
```

**Comment by iAgentur** [comment]
In `TDA-integration-test/` folder I have Xcode project that has `Cartfile` pointed to the git repo of my framework. Is it possible that Carthage picks that up too, which results in double build?

**Comment by DavidBrunow** [comment]
I believe that Carthage searches recursively for any `.xcodeproj` files so yes I believe that is the source of this issue.

**Comment by iAgentur** [comment]
so the only way to resolve the issue is to move subfolder(s) containing their own `Cartfile`s into a separate repo?

**Comment by DavidBrunow** [comment]
Could you specify `--project-directory` to build the folder you need and have the current subfolder located at the same level as the folder you need to build? Or does the subfolder have to be insider the folder you want to build with Carthage?

**Comment by iAgentur** [comment]
@DavidBrunow yes, that would probably solve the issue, thanks!

but in the end I decided to move `TDA-integration-test/` to a separate repo.
