### ISSUE TITLE
xcodebuild timed out trying to read Alamofire.xcodeproj when following QuickStart

### ISSUE THREAD

**Issue by tjprescott** [Carthage/Carthage#2912]
I cannot build any dependency frameworks using Carthage. I am trying to follow a simple tutorial: https://www.raywenderlich.com/416-carthage-tutorial-getting-started. I am also trying to follow the steps of the QuickStart, but cannot get past step 4 (running `carthage update`). It doesn't matter what the framework is or how trivial the project, running carthage update always fails for the same reasons. 

I've consulted similarly named issues and they aren't matching my scenario. I can run Xcodebuild manually without issue. Opening the Xcodeproj and re-running the build does not succeed.

* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`: Xcode 11.2.1 Build version 11B500
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "Alamofire/Alamofire" == 4.5
github "Alamofire/AlamofireImage" ~> 3.2

```

**Carthage Output**
```
travisprescott$ carthage update --platform ios

*** Fetching Alamofire
*** Fetching AlamofireImage
*** Checking out AlamofireImage at "3.6.0"
*** Checking out Alamofire at "5.0.0.beta.1"
*** xcodebuild output can be found in /var/folders/ss/8mw44zjj7l11pqgn2xwtcl100000gn/T/carthage-xcodebuild.oCWvZc.log
xcodebuild timed out while trying to read Alamofire.xcodeproj 😭
```

**Actual outcome**
Carthage did not successfully build the dependency. It only has the Checkouts folder. If I run with `--verbose`, it adds no additional output.

**Expected outcome**
Carthage should build the dependency.

**Comment by tjprescott** [comment]
Consulting https://github.com/Carthage/Carthage/issues/2002, I can confirm that the following commands succeed (about about 70 sec):

```
xcrun xcodebuild clean -showBuildSettings -skipUnavailableActions
xcrun xcodebuild -list
```

I tried building Carthage from source and increasing the timeout from 60 to 300, but that did not help...it just ran a LOT longer before failing.

Running `carthage update --verbose` did not output anything from xcodebuild either.

**Comment by DavidBrunow** [comment]
@tjprescott The part of Carthage that resolves the dependencies (the resolver) is failing -- the tell-tale sign of that happening is this line from the output:

```
*** Checking out Alamofire at "5.0.0.beta.1"
```

Notice that the `Cartfile` specifies that Alamofire must be version 4.5 (`github "Alamofire/Alamofire" == 4.5`) but Carthage is looking for version 5.0.0.beta.1. This means that there is either 1) something a little off with the dependency chain or 2) the dependency chain is too complicated for Carthage's resolver.

Carthage also has a new resolver that you can enable with the flag `--new-resolver`.

In this situation I'd recommend thinking about whether pinning Alamofire to the exact version of 4.5 is a hard requirement or whether it makes more sense to loosen that version requirement -- changing it to `~> 4.5`, meaning that any version before 5.0 is OK, resolves the issue you are seeing.

**Comment by tjprescott** [comment]
Thanks @DavidBrunow I'll give that a shot and report back.
