### ISSUE TITLE
Does Carthage support `static SDK library` build ?

### ISSUE THREAD

**Issue by hantao-flurrydev** [Carthage/Carthage#2913]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`: xcode 10.0
* Are you using `--no-build`?  N
* Are you using `--no-use-binaries`? N
* Are you using `--use-submodules`? N
* Are you using `--cache-builds`?  N
* Are you using `--new-resolver`? N

**Cartfile**

Empty

**Carthage Output**
```
*** Skipped building carthage due to the error:
Dependency "carthage" has no shared framework schemes
```

**Actual outcome**
*** Skipped building carthage due to the error:
Dependency "carthage" has no shared framework schemes

**Expected outcome**
Successfully build static library

**Comment by tmspzz** [comment]
> Dependency "carthage" has no shared framework schemes

**Comment by hantao-flurrydev** [comment]
The schemes were shared and build succeed using `xcodebuild -scheme SCHEME -workspace WORKSPACE build` or `xcodebuild -scheme SCHEME -project PROJECT build` but Carthage couldn't find them.

**Comment by DavidBrunow** [comment]
Are you trying to build a version of Carthage statically so you can use the binary standalone without any dependencies?

**Comment by hantao-flurrydev** [comment]
I am trying to build a `static library` with `.h` file exposed and I only found Carthage started to support `static framework`, so don't know whether this failure is due to that?

**Comment by tmspzz** [comment]
@hantao-flurrydev Carthage supports __static frameworks__ not static libraries. I.E. a framework who's mach-o type is Static Library.
