### ISSUE TITLE
Carthage is unable to determine the platform for frameworks built with gomobile for iOS 12.0

### ISSUE THREAD

**Issue by jasonboyle** [Carthage/Carthage#2915]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.33.0
* `xcodebuild -version`: Xcode 11.2.1 Build version 11B500
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes
* Are you using `--new-resolver`? no

We are using gomobile to compile Go code into an iOS framework.  The framework is compiled with the following command:

`gomobile bind -v -target "ios/arm64,ios/amd64" -iosversion "11.0" -o Goframework.framework <GOPATH package names>`

The produced framework works fine with Carthage.  However, when we set `-iosversion "12.0"`, Carthage is no longer able to determine the platform for the resulting framework:

`Failed to read file or folder at /private/var/folders/zb/d5lp696n27z9bqkx1v6pg1x00000gp/T/carthage-archive.9SssO9/Goframework.framework: Error Domain=com.antitypical.Result Code=0 "could not determine platform neither from DTSDKName key in plist nor from the framework's executable" UserInfo={com.antitypical.Result.file=/private/tmp/carthage-20190404-81602-19n056u/Source/CarthageKit/Project.swift, com.antitypical.Result.function=readFailed, com.antitypical.Result.line=1291, NSLocalizedDescription=could not determine platform neither from DTSDKName key in plist nor from the framework's executable}`

Neither of the frameworks appears to have a DTSDKName key in its plist.  However, the output of `otool -lv` differs significantly between the frameworks.  The "11.0" framework contains the string `cmd LC_VERSION_MIN_IPHONEOS` which appears to be what Carthage is looking for, while the "12.0" framework does not (see attached files).

[otool_ios11.txt](https://github.com/Carthage/Carthage/files/3929081/otool_ios11.txt)
[otool_ios12.txt](https://github.com/Carthage/Carthage/files/3929084/otool_ios12.txt)

**Comment by DavidBrunow** [comment]
I may be wrong but this sounds like a problem with gomobile rather than Carthage. What do you expect Carthage to do?
