### ISSUE TITLE
How to use carthage in XCodeServer triggers? I can not push carthage builds folder to my repo.

### ISSUE THREAD

**Issue by varunrathi28** [Carthage/Carthage#2916]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`:
* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```

**Actual outcome**
Carthage did or did not ...

**Expected outcome**
Carthage should ...

**Comment by tmspzz** [comment]
Please state your issue more clearly and provide some description of the problem.
