### ISSUE TITLE
Add unique identifiers for dependencies.

### ISSUE THREAD

**Issue by 1oo7** [Carthage/Carthage#2919]
The main flaw of Carthage is the lack of a way to tell Carthage what source maps to what dependency. 

Let me give you an example.

Imagine an app which has 26 framework dependencies in 26 github repos, some public, some internal. They comprise a graph of interrelated dependencies.

So lets say I want to update two frameworks that are in the middle of this graph. While I'm developing I want to point my app at local git repos on my laptop for those two only. So I change the `cartfile.resolved` source for those two dependencies in my app's `Cartfile.resolved` from pointing to a github, to pointing to the repos on my laptop. 

However this breaks Carthage, because there is no unique identifier for each dependency, so the only way Carthage can identify what a dependency is, is by the source—so if you change the source, now it thinks "this is a different dependency" and it breaks. 

Except instead of giving you a useful error message, Carthage gives you gobbledegook about there existing some mythical "dependency cycle", a wild goose chase that will waste you many hours because in reality no cycle exists and this error message is, itself, in error.

The easy solution would be to let you give a name (like, the framework's actual name) for each dependency, to let carthage know it should treat `git "file:///path/to/my/local/fork/of/Alamofire"` as the same thing as `github "https://github.com/whatever/alamofire"`.

**Comment by DavidBrunow** [comment]
The other situation where this happens is when using forks of a repo.

How would you expect to define the unique identifier for each dependency -- what would your proposed `Cartfile` look like?

**Comment by mac-daddie** [comment]
Instead of this: 

```
github "soffes/SAMKeychain" == 1.5.3
github "AliSoftware/OHHTTPStubs" == 7.0.0
github "Square/Valet" == 3.2.3
github "apple/swift-protobuf" ~> 1.3.1
```

It might look like this:

```
SAMKeychain 
    @ github "soffes/SAMKeychain" == 1.5.3
OHHTTPStubs 
    @ github "AliSoftware/OHHTTPStubs" == 7.0.0
Valet 
    @ github "Square/Valet" == 3.2.3
swift-protobuf 
    @ github "apple/swift-protobuf" ~> 1.3.1
```

Then you just swap out the second line after the @ sign to point wherever you want, and it knows that's the same dependency.

The reason to use a second line is so git diffs don't show any change to the unique name for each dependency, and so you could have multiple second lines and just comment out all the ones except for the one you want to use, like:

```
SAMKeychain 
    #@ github "soffes/SAMKeychain" == 1.5.3
    @ git "file:///path/to/my/local/dev/repo/of/samkeychain" "a76f98s7ef98s7ef987s8s79fe89s"
OHHTTPStubs 
    @ github "AliSoftware/OHHTTPStubs" == 7.0.0
Valet 
    @ github "Square/Valet" == 3.2.3
swift-protobuf 
    @ github "apple/swift-protobuf" ~> 1.3.1
```

That way it would be very obvious if you had enabled a local repo and you preserve the remote repo so it's easy to re-enable.

**Comment by DavidBrunow** [comment]
Looks like a breaking change to the `Cartfile` format -- how would you handle that?

**Comment by mac-daddie** [comment]
> Looks like a breaking change to the `Cartfile` format -- how would you handle that?

`brew update carthage`

Then update your cartfiles.

Then file some JIRAs with the CI/CD team ;D

**Comment by DavidBrunow** [comment]
A prior conversation about the Cartfile format: https://github.com/Carthage/Carthage/issues/2627
