### ISSUE TITLE
Carthage generate .framework folder, not file.

### ISSUE THREAD

**Issue by tiagoamaralinfoglobo** [Carthage/Carthage#2926]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`: Xcode 11.3.1 - Build version 11C504
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO
* Are you using `--new-resolver`? NO

**Cartfile**
```
github "Alamofire/Alamofire" "5.0.0-rc.1"
```

**Carthage Output**
```
git:(master) ✗ carthage update
*** Checking out Alamofire at "5.0.0-rc.1"
*** xcodebuild output can be found in /var/folders/2g/0hwzrq8j4b71wslg8k03yjkm0000gp/T/carthage-xcodebuild.oKbjm6.log
*** Building scheme "Alamofire macOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
```

xcodebuild output file: [carthage-xcodebuild.oKbjm6.log](https://github.com/Carthage/Carthage/files/4142153/carthage-xcodebuild.oKbjm6.log)

**Actual outcome**
The carthage build not generate `.framework` file, but one folder with same name.
![Captura de Tela 2020-02-01 às 01 46 11](https://user-images.githubusercontent.com/47675235/73587020-b2924380-4494-11ea-998e-fefd61f1a597.png)

**Expected outcome**
Expect output file Alamofire.framework.

**Comment by DavidBrunow** [comment]
What is inside the folder? A .framework is really just a folder that is treated specially by macOS.

**Comment by tiagoamaralinfoglobo** [comment]
This is the contents of the folder:

<img width="282" alt="Captura de Tela 2020-02-01 às 22 30 45" src="https://user-images.githubusercontent.com/47675235/73601599-14a98200-4543-11ea-8f74-c9fcca7e8472.png">

Yes, the framework is a folder treated in a special way by OSX, but why in this case he is not doing this?
In this format (folder), I can't import the framework into Xcode.
Does anyone know if this is a necessary configuration on OSX or some kind of bug in Carthage?

**Comment by tmspzz** [comment]
Your folder is named Alamofire1framework, not `Alamofire.framework`. I am positive this isn't a carthage bug.

**Comment by ikesyo** [comment]
https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-WHAT_IS_A_FRAMEWORK_

> **A framework is a hierarchical directory** that encapsulates a dynamic library, header files, and resources, such as storyboards, image files, and localized strings, into a single package.

Closing.
