### ISSUE TITLE
How to install a 0.11 version of carthage using Xcode 7.2.1?

### ISSUE THREAD

**Issue by shahzadkhan7860** [Carthage/Carthage#2932]
Carthage version: 0.11
xcodebuild -version: 7.2.1
Are you using --no-build? no
Are you using --no-use-binaries? yes
Are you using --use-submodules? no
Are you using --cache-builds? no
I am trying to install Carthage v0.11. I used brew install carthage@0.11 but I receive the error:
Error: No available formula with the name "carthage@0.11"

**Comment by tmspzz** [comment]
There is no such formula. The homebrew formula is always at the latest version.

You should check out the tag from Carthage's repo and build locally.

**Comment by Cyberbeni** [comment]
Look up the forumla in git history and copy it to your own repo, like how I do it with Reveal: https://github.com/Cyberbeni/homebrew-brews/blob/master/Casks/reveal.rb
