### ISSUE TITLE
How: Please update to the latest Carthage version

### ISSUE THREAD

**Issue by fulldecent** [Carthage/Carthage#2933]
When running Carthage, you can receive this warning:

> Please update to the latest Carthage version

It will be helpful if this warning also explains HOW to update to the latest Carthage.

**Comment by tmspzz** [comment]
Well, how did you install it in the first place?

I would update it following the same procedure

**Comment by fulldecent** [comment]
I don't remember. But if that is the answer then I propose changing 

> Please update to the latest Carthage version

to

> Please update to the latest Carthage version. To do this you will need to remember how you originally installed Carthage.

**Comment by tmspzz** [comment]
The install procedures as listed here https://github.com/Carthage/Carthage#installing-carthage if you used a system package manager like homebrew or macports you'll have to refer to their specific documentation on how to update a package.

For example if you used homebrew you can run `brew update carthage`. 

Thanks for suggesting the change to the update notice.

**Comment by muhasturk** [comment]
This command updates brew itself, and does not take formula names.

the command should be `brew upgrade carthage`

**Comment by Kaushal0812** [comment]
## As  of writing this comment the current version is 0.35.0



If `brew upgrade carthage` command is not working for you, then it means you have not used `homebrew` during Carthage installation.

So to upgrade using `homebrew`, use the following steps:


Use `which carthage` command. 

It will show the current path of carthage
In my case it is ***"/usr/local/bin/carthage"***. Delete the existing carthage here.

Then use 
`brew install carthage
`

This will install the latest version of carthage.

**Comment by mr-fixit** [comment]
> ## As of writing this comment the current version is 0.35.0

I'm confused. When I ask carthage what version it is, it tells me 0.35 **but also tells me the latest is 036**
```
$ carthage version
Please update to the latest Carthage version: 0.36.0. You currently are on 0.35.0
0.35.0
```

**Comment by mr-fixit** [comment]
looks like 0.36 is coming https://github.com/Carthage/Carthage/commit/499c9cf8dafe5979e761397721f319db8bbe5859

**Comment by tmspzz** [comment]
You can already get `0.36.0` from the .pkg attached to to the release or wait for brew.

**Comment by mr-fixit** [comment]
Thanks @tmspzz. I see that from [the source](https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/RemoteVersion.swift#L13) that 'the latest' is 'the latest tag in the repo', not 'the latest available via brew'.

**Comment by mr-fixit** [comment]
FWIW, 0.35.1 reports its version incorrectly.

```$ /usr/local/Cellar/carthage/0.35.1/bin/carthage version
Please update to the latest Carthage version: 0.36.0. You currently are on 0.35.0
0.35.0
```

**Comment by NSExceptional** [comment]
When is a new version coming to `brew`? `brew` reports that the latest version os `0.34.0`.

**Comment by DavidMurphy1088** [comment]
this is a fucking nightmare
