### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by varunknarayanswamy** [Carthage/Carthage#2934]
carthage install method: homebrew
`carthage version`: 0.34.0
`xcodebuild -version`: 11.3.1
I am using`--no-use-binaries`

**Cartfile**
github "flowsprenger/RxLifx-Swift" "master"
github "ReactiveX/RxSwift"

So here is my issue. I've been coding using several carthage based APIs and frameworks. It works totally fine on the simulator and worked on the actual device last week. However, now I am getting this error. 

<img width="440" alt="Screen Shot 2020-02-12 at 6 52 12 PM" src="https://user-images.githubusercontent.com/32069048/74394003-d0cb3e00-4dc8-11ea-85ae-f6ede5d5b502.png">

Here is an image of my build phase

<img width="1253" alt="Screen Shot 2020-02-12 at 6 53 29 PM" src="https://user-images.githubusercontent.com/32069048/74394065-053efa00-4dc9-11ea-8082-770e1d449742.png">
<img width="1250" alt="Screen Shot 2020-02-12 at 6 53 40 PM" src="https://user-images.githubusercontent.com/32069048/74394068-07a15400-4dc9-11ea-87ff-f06fffdd6e57.png">

I have tried cleaning my project, deleting my derived folder, updating my cartfile. I am now checking an older project that used the same dependencies and am getting the same issues. Any ideas on what could be causing it? If anymore information is needed please let me know.

**Comment by tmspzz** [comment]
You're @rpath seems wrong. Also it's seems you have a problem with codesigning. It's all there in the error message.

**Comment by DavidBrunow** [comment]
@varunknarayanswamy Are those frameworks being embedded by Xcode anywhere or only through the `copy-frameworks` command?

**Comment by varunknarayanswamy** [comment]
They are being embedded but I actually figured out my issue. I ran my program on a phone with iOS 13.3 and on a device with iOS 13.3.1. It worked on the first and broke on the second. Seems like apple has messed up dynamic frameworks for free apple developer accounts on the newest update. I looked up the error online afterward and several uses of alamofire and similar dependency builders. I actually spent the 100 dollars on a paid apple developer account and it ended up fixing the issue. You can also look into making the frameworks static I think but I haven't explored it much. Definitely something to keep an eye on and let apple know.
