### ISSUE TITLE
Fatal error due to excessive memory consumption performing carthage update --platform ios

### ISSUE THREAD

**Issue by pushian** [Carthage/Carthage#2937]
* carthage install method: homebrew
* `carthage version`: 0.34.0
* `xcodebuild -version`: Version 11.3.1 (11C504)
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  no
* Are you using `--new-resolver`?  no

**Cartfile**
```
github "raphaelmor/Polyline" ~> 4.0
github "KyoheiG3/TableViewDragger"
github "SnapKit/SnapKit" ~> 5.0.0
github "Alamofire/Alamofire"
github "Alamofire/AlamofireImage"
github "SVProgressHUD/SVProgressHUD"
github "SwiftyJSON/SwiftyJSON" ~> 4.0
github "jverdi/JVFloatLabeledTextField"
github "skywinder/ActionSheetPicker-3.0"
github "michaeltyson/TPKeyboardAvoiding"
github "MortimerGoro/MGSwipeTableCell"
```

**Carthage Output**
```
*** Fetching TableViewDragger
*** Fetching JVFloatLabeledTextField
*** Fetching TPKeyboardAvoiding
*** Fetching ActionSheetPicker-3.0
*** Fetching SVProgressHUD
*** Fetching Alamofire
*** Fetching MGSwipeTableCell
*** Fetching SnapKit
*** Fetching SwiftyJSON
*** Fetching AlamofireImage
*** Fetching Polyline
Killed: 9
```

**MAC System**
```
MacBook Pro (Retina, 15-inch, Mid 2015)
Processor 2.2 GHz Intel Core i7
Memory 16 GB 1600 MHz DDR3
```

**Actual outcome**
fatal error due to excessive memory consumption

**Expected outcome**
Carthage should successfully build

**Comment by tmspzz** [comment]
Have you tried `--new-resolver`?

Also, consider pinning your dependencies as it looks like carthage is entering a loop while trying to resolve compatible versions.

**Comment by pushian** [comment]
> Have you tried `--new-resolver`?
> 
> Also, consider pinning your dependencies as it looks like carthage is entering a loop while trying to resolve compatible versions.

Hi @tmspzz thanks for the reply. --new-resolver doesn't solve the issue. However, the issue is solved by indicating the specific version for all the dependencies so that carthage won't enter a loop while trying to resolve compatible versions by itself.

**Comment by pushian** [comment]
@tmspzz I am unsure whether this is the proper resolution or a workaround so will leave to you whether this issue should be closed or not.
