### ISSUE TITLE
Failed to write to "No such file or directory" for MacOS only

### ISSUE THREAD

**Issue by christinasund** [Carthage/Carthage#2940]
* carthage install method: [ ] .pkg, [ x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: `0.34.0`
* `xcodebuild -version`: `Xcode 11.3.1 Build version 11C504`
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? Something I tried, but not normally
* Are you using `--new-resolver`? NO

**Cartfile**
```
github repo-owner/product
```

**Carthage Output**
```
Failed to write to /Users/....../Carthage/Build/Mac/.......framework: Error Domain=NSCocoaErrorDomain Code=260 "The file .......framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/....../Library/Caches/org.carthage.CarthageKit/DerivedData/11.3.1_11C504/....../....../Build/Intermediates.noindex/ArchiveIntermediates/....../BuildProductsPath/Release-iphoneos/.......framework, NSFilePath=/Users/....../Library/Caches/org.carthage.CarthageKit/DerivedData/11.3.1_11C504/....../....../Build/Intermediates.noindex/ArchiveIntermediates/....../BuildProductsPath/Release-iphoneos/.......framework, NSUnderlyingError=0x7fa830faa1b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Actual outcome**
I am getting the above error when trying to install my framework for macOS using Carthage. I am able to install for iOS, watchOS and tvOS without a problem but having issues with Mac. Any help with this would be appreciated. Let me know if you need any more info. Thanks!

**Expected outcome**
install my framework for macOS

Cleared Carthage Cache
Cleared Derived Data
Uninstalled and Reinstalled Carthage

Commands Tried:
carthage update --platform macos
carthage bootstrap --platform macos
carthage update --platform macos --cache-buildes

Carthage Version = 0.34.0

Base SDK = iOS

Supported Platforms = iOS MacOS tvOS watchOS 

Valid Archs = arm64 arm64e armv7 armv7s

macOS Deployment Target = macOS 10.11

Target Device Family = 1,2,3,4

**Comment by tmspzz** [comment]
Can you share your Cartfile.resolved ?

**Comment by tmspzz** [comment]
Could be related to `SYMROOT` being set https://github.com/Carthage/Carthage/issues/2703#issuecomment-461624978

See also https://github.com/Carthage/Carthage/issues/2220

**Comment by christinasund** [comment]
@tmspzz Thanks for your response! I tried to remove my SYMROOT locally and unfortunately it did not fix the problem. I also tried removing the SDKROOT as I read in some other threads. I was trying to avoid posting any company info here, but the repo is public so I guess it will not do any harm. Here are the contents of the Cartfile.resolved:

`binary "https://tags.tiqcdn.com/dle/tealiummobile/tealium-ios-carthage/tealium-carthage-plcrashreporter.json" "1.3.6"
github "tealium/tealium-swift" "1.9.1"`

Thanks again for your help!

**Comment by tmspzz** [comment]
It is most probably a bug in Carthage. This patch might help https://github.com/Carthage/Carthage/issues/2777#issuecomment-493489141 

I don't have a time to look into this at the moment. If would be great if you could take a look and submit a fix

**Comment by s2mr** [comment]
The problem continues to occur in carthage 0.39.0

**Comment by s2mr** [comment]
I have found a way to increase the probability of success and will report it.

I was trying with Firebase 10.2.0 and it didn't work,
I have updated to 10.7.0 and it seems to be working.

Also, the --new-resolver option seems to increase the probability of success considerably, though not 100%.
