### ISSUE TITLE
Carthage Installation trying to get sources from github when built from source

### ISSUE THREAD

**Issue by sergioRMM** [Carthage/Carthage#2946]
* carthage install method: [ ] .pkg, [ ] homebrew, [ x] source
* `carthage version`: 0.34.0
* `xcodebuild -version`: 10.3 and 11.3

Hi all, we are working with carthage in a place which doesn't have access to external resources, we only have access to artifactory and we get the source code as a tar.gz using a remote. Previously when installing carthage from source (make install), process used to run smoothly, however now it tries to connect to github, which is a non-negotiable no for us. Am I missing something, is there any other way to install carthage "offline".

Thank you for you help.

**Carthage Output**
```
Fetching https://github.com/jdhealy/PrettyColors.git
error: failed to clone; Cloning into bare repository '/private/tmp/carthage/.build/repositories/Result-0ec432bc'...
fatal: unable to access 'https://github.com/antitypical/Result.git/': Failed to connect to github.com port 443: Operation timed out
```

**Actual outcome**
Carthage wasn't installed and reported a time out.

**Expected outcome**
Carthage should be installed without issues.

**Comment by tmspzz** [comment]
This is because carthage is using SwiftPM.  If you want to avoid refreshing dependencies you have to pass `--skip-update` to swiftPM

**Comment by sergioRMM** [comment]
When trying **swift build --skip-update** inside the source directory, it still looks for the dependencies: 
`Fetching https://github.com/Carthage/ReactiveTask.git
Fetching https://github.com/antitypical/Result.git
Fetching https://github.com/mdiep/Tentacle.git
Fetching https://github.com/ReactiveCocoa/ReactiveSwift.git
Fetching https://github.com/Quick/Nimble.git
Fetching https://github.com/Quick/Quick.git
Fetching https://github.com/jdhealy/PrettyColors.git
Fetching https://github.com/Carthage/Commandant.git
Fetching https://github.com/thoughtbot/Curry.git`

**Comment by sergioRMM** [comment]
Could you please advise? Thank you.

**Comment by tmspzz** [comment]
You have to at least clone those repositories once.
