### ISSUE TITLE
Documentation fix regarding static/dynamic frameworks

### ISSUE THREAD

**Issue by nugmanoff** [Carthage/Carthage#2949]
Documentation states that
`Note that Carthage only supports dynamic frameworks, which are only available on iOS 8 or later (or any version of OS X).`

But I think this is quite misleading, and should rather be something like:
`Carthage supports both dynamic & static frameworks, but latter are only available on iOS 8 or later (or any version of OS X).`

**Comment by tmspzz** [comment]
Carthage only supports frameworks. Not static libraries.

**Comment by DavidBrunow** [comment]
I agree that this documentation is misleading — I’ve thought the same thing when I’ve seen it before.
