### ISSUE TITLE
Targets with same product name overwrite each other

### ISSUE THREAD

**Issue by a2** [Carthage/Carthage#295]
Realm has both "iOS" and "iOS 8" targets, and when Carthage builds them, it builds one, and then when it builds the other, it overwrites the first built framwork. (Moved from realm/realm-cocoa#1447).

**Comment by jspahrsummers** [comment]
Carthage shouldn't be building both targets unless they both build _dynamic frameworks_—in which case, why do two schemes exist?

What types are the targets? Can you attach `carthage` output?

**Comment by a2** [comment]
The targets are both dynamic frameworks. Here's the `carthage` output: http://a2.d.pr/1geRm.

**Comment by jspahrsummers** [comment]
Why are there two dynamic framework targets? What does `iOS` do vs. `iOS 8`?

If they really must both exist, there are a few workarounds available:

 1. Unshare one of the schemes
 1. Rename one of the products
 1. Move one of the schemes to a different project file, or up to the workspace level

**Comment by jpsim** [comment]
The `iOS` target is static, whereas the `iOS 8` target is dynamic. Hence the naming. What's confusing (to me, anyway) is that the `iOS 8` target builds in the `iOS` directory, which happens to be the name of our other target. Why not name those directories by the name of the target? Separate targets are necessary for each platform anyway, AFAIK.

**Comment by jspahrsummers** [comment]
The folders are named after the platform, because all of your dependencies are meant to end up there for easy linking (and easy Framework Search Paths).

If your `iOS` target is _actually_ a static framework, it should not be building. What's the product Uniform Type Identifier?

**Comment by jpsim** [comment]
> If your iOS target is actually a static framework, it should not be building.

Yes, the `iOS` target is static and is not being built. The confusion stems from `Realm.xcodeproj` containing an `iOS` target that isn't built, and an `iOS 8` target that's being built in the `iOS` directory, despite that also being the name of a different target in our project by pure coincidence.

I think Carthage is doing the right thing here, and *perhaps* Realm should rename its targets `s/iOS/iOS-static` and `s/iOS 8/iOS-dynamic`, but that's debatable and isn't an improvement IMHO.

**Comment by jspahrsummers** [comment]
Ah, I see. Yeah, this is peculiar.

In our typical usage, our frameworks are named after the project itself—for example, `ReactiveCocoa.framework` on both OS X and iOS. Thus, the resulting directory structure looks like:

```
Carthage/
  Build/
    Mac/
      ReactiveCocoa.framework/
    iOS/
      ReactiveCocoa.framework/
```

With several frameworks being built, it becomes really handy to have all your platform-specific stuff in the same place.

That's the motivation, anyways. Although it's somewhat confusing in this case, I do think Carthage is doing the right thing here. Thanks for hashing it out!
