### ISSUE TITLE
Monorepository setup with carthage shared artifacts

### ISSUE THREAD

**Issue by nugmanoff** [Carthage/Carthage#2950]
I have carefully looked through several issues with similar concern. But most of them either outdated or didn't come to successful conclusion for others to follow.

Let's assume that I want to structure my monorepository (containing multiple apps) as follows:
```
AppX
AppY
Development Frameworks
Third-party Frameworks
```
Where development frameworks are my privately developed and reusable across applications pieces of functionality.

**What do I want to achieve?** 

1. I want to have Carthage build artifacts to be shared among applications and development frameworks. Something like this:
```
AppX
AppY
Carthage (Third-party Frameworks)
Development Frameworks
```
The best way to do it that I found so far is this [gist](https://gist.github.com/tmspzz/ddf64f679f4a862c4e3279e7294d8a58). But how reliable & scalable is it?

2. I want to be able to use Rome caching on top of shared build artifacts. Some advice on this would appreciated :)

3. There is one last (but big problem). Let's suppose I have following dependency graph:
```
AppX/
AppY/
- Third-party framework A
Development Frameworks/
- Development Framework Z
- - Third-party framework A
Carthage/
```
I want to be to do it the way that both **AppY** and **Development Framework Z** leverage the usage of the same version of **Third-party framework A**.

**Comment by tmspzz** [comment]
I don't maintain that gist, but the ideas are scalable. Here is a similar approach https://github.com/Ancestry/CartTool

I don't understand your directory structure. What does the directory "Carthage" contain and what does the direcotry "Development Frameworks" contain ? 

Is there only one Cartfile.resolved? Is the "Carthage" directory the directory produced by Carthage itself?

**Comment by nugmanoff** [comment]
• Both AppX and AppY have different Cartfile & Cartfile.resolved
• Carthage is the directory produced by Carthage itself (with Checkouts/ and Build/)
• Development Frameworks contain my private local frameworks that are shared between AppX & AppY. They are just basically .xcodeproj projects. But they can have their own Cartfile & Cartfile.resolved.

Idea is that Third-party Dependencies that are added using Carthage will be stored in one folder only and shared across Apps & Development Frameworks that refer to them using Cartfile.

**Comment by tmspzz** [comment]
Seems doable to me. What exactly is your question?

If you're looking for ways to refer to the Development Frameworks you can use "git" and a file url in the Cartfile

**Comment by nugmanoff** [comment]
> Seems doable to me. What exactly is your question?
> 
> If you're looking for ways to refer to the Development Frameworks you can use "git" and a file url in the Cartfile

In order to do that I need to have git repository setup inside each of Development Frameworks. I believe that I can do that through git submodules or git subtree but using them implies increased complexity on performing basic git operations, which I obviously don't need. Because git operations are quite common and I would opt for "simplicity of use" with them here.

I would love to have something similar to `path => "local/folder/"` from Podfile.

**Comment by tmspzz** [comment]
> I would love to have something similar to path => "local/folder/" from Podfile.

I'm afraid there is no such option. You can find the references in the documentation at https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfile
