### ISSUE TITLE
Warn library authors when "Build for distribution" is disabled

### ISSUE THREAD

**Issue by michaeleisel** [Carthage/Carthage#2953]
Now that Swift module stability is a thing, it would be great to warn library authors when they're publishing libraries but don't have "Build for distribution" enabled in the settings. Without that being enabled, module stability is not possible for that library. Many libraries that I've come across do not have this enabled currently.

**Comment by Cyberbeni** [comment]
Build for distribution is for distributing libraries separately from the app that uses them, which is rarely the case.
