### ISSUE TITLE
Why does Carthage use VALID_ARCHS and not ARCHS in copy-frameworks?

### ISSUE THREAD

**Issue by jerbob92** [Carthage/Carthage#2956]
I skipped the first few questions because I'm not a direct user of Carthage.

We created an SDK for Android and iOS. Our iOS  SDK supports both CocoaPods and Carthage, our SDK is delivered both ways as a fat framework. 

Today one of our customers tried to integrate using Carthage, everything worked fine until he uploaded the app to TestFlight. The app was rejected with the following error:

```
ITMS-90381: Too many symbol files - These symbols have no corresponding slice in any binary
```

After some researching we found out that the resulting binary of our SDK in the app had architectures that the app does not use. I looked into the code of Carthage, and noticed that the `copy-frameworks` step does do stripping of the binary, but it bases the stripping on the `VALID_ARCHS` environment variable. Our customer had more archs in `VALID_ARCHS` than he had in `ARCHS`, which resulted in Carthage keeping the archs in our SDK binary that were in `VALID_ARCHS`, but the app itself was not build for those archs, because `ARCHS` contains less archs than `VALID_ARCHS`, which causes TestFlight to reject it.

Is there a good reason for Carthage to only strip archs that are not in `VALID_ARCHS`, and not the archs that are not in  `ARCHS`?

**Actual outcome**
Carthage keeps architectures in frameworks that the app is not compiled for, because it looks at the `VALID_ARCHS` variable.

**Expected outcome**
Carthage should strip the architectures based on `ARCHS` because those are the architectures the app is compiled for.

**Comment by tmspzz** [comment]
I don't know the background of the decision but valid_archs is subset of archs valid for this target. https://xcodebuildsettings.com/#valid_archs

**Comment by jerbob92** [comment]
Sounds to me that xcode internally intersects VALID_ARCHS and ARCHS, so Carthage should probably be the same?

**Comment by tmspzz** [comment]
It would make sense. PRs welcome.

**Comment by jerbob92** [comment]
I'd love to, but this fix seems almost too easy to be true.
Pinging the original author @robb to see whether he knows the thinking behind it. It's been a long time (2014), so he might not remember.

**Comment by robb** [comment]
It has been a while, I don't remember any particular reason and it may very well have been a misconception on my part. Skimming #188 doesn't mention anything `$ARCHS` related.

**Comment by jerbob92** [comment]
Thanks! I'll see what I can do. I'm not a Swift developer so we will see how that goes :)

**Comment by jerbob92** [comment]
I'm sorry but it's impossible for me to create a PR for this. I'm not a Swift developer and I don't have access to OSX due to Corona so I can't even test the code that I created, however, it shouldn't be that complicated, something like this should work:

```
private func validArchitectures() -> Result<[String], CarthageError> {
	let validArchs = getEnvironmentVariable("VALID_ARCHS").map { architectures -> [String] in
		return architectures.components(separatedBy: " ")
	}

        if validArchs == .failure {
          return validArchs
        }

	let archs = getEnvironmentVariable("ARCHS").map { architectures -> [String] in
		return architectures.components(separatedBy: " ")
	}

	if archs == .failure {
          return archs
        }

	return .success(validArchs.filter(archs.contains))
}
```
Someone that can test this and turn into a PR for me?

**Comment by jerbob92** [comment]
I created a PR for this issue in #2987

**Comment by jerbob92** [comment]
@tmspzz could you do a review?

**Comment by jerbob92** [comment]
Notstale

**Comment by simonpierreroy** [comment]
Yes, so basically always read `EXCLUDED_ARCHS` and `VALID_ARCHS`, but `EXCLUDED_ARCHS` wins if present? I am not certain what Xcode 12 does when both are there based on the [release note](https://github.com/Carthage/Carthage/issues/2956)!

*The Build Settings editor no longer includes the Valid Architectures build setting (VALID_ARCHS), and its use is discouraged. Instead, there is a new Excluded Architectures build setting (EXCLUDED_ARCHS). If a project includes VALID_ARCHS, the setting is displayed in the User-Defined section of the Build Settings editor. (15145028)*
