### ISSUE TITLE
Dependency has no shared framework schemes T^T

### ISSUE THREAD

**Issue by Linyuyu** [Carthage/Carthage#2957]
* carthage install method: [ ] .pkg, [x ] homebrew, [ ] source
* `which carthage`:  /usr/local/bin/carthage
* `carthage version`:  0.34.0
* `xcodebuild -version`: Build version 11C504
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO
* Are you using `--new-resolver`? NO

**Cartfile**
```
github "SnapKit/SnapKit" ~> 5.0.0
```

**Carthage Output**
```
carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/js/vj89d2bn5x5brgxcv7mc2xym0000gn/T/carthage-xcodebuild.nlvcFH.log
*** Skipped downloading SnapKit.framework binary due to the error:
	"Bad credentials"
*** Building scheme "SnapKit" in SnapKit.xcworkspace
*** Skipped building carthage-demo due to the error:
Dependency "carthage-demo" has no shared framework schemes
```

**Actual outcome**
I create .xcodeproj  by `xcodegen` like my sample and running project as well as my expected.
but I got failed when I executed command `carthage build --no-skip-current` to wrap `MyFramework`

sample here: https://github.com/Linyuyu/carthage-demo

**Expected outcome**
Carthage should ...

**Comment by DavidBrunow** [comment]
I don't use Xcodegen but I'd guess you need to add a key for `scheme` like this example does: https://github.com/toshi0383/Bitrise-iOS/blob/master/project.yml#L50

**Comment by Linyuyu** [comment]
Thanks a lot, I've solved my problem. It's really my scheme setting issue.
