### ISSUE TITLE
Xcode 11.4 - Carthage skipped installing a binary framework built with 5.1.3 compiler

### ISSUE THREAD

**Issue by wacumov** [Carthage/Carthage#2958]
* carthage install method: [ ] .pkg, [x ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`: Xcode 11.4, 11E146
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "vvorld/getid-ios-ocr"
```

**Carthage Output**
```
*** Cloning getid-ios-ocr
*** Checking out getid-ios-ocr at "0.1.3"
*** xcodebuild output can be found in /var/folders/kd/jk25qft53ylc8_pblxn720040000gn/T/carthage-xcodebuild.plsmgO.log
*** Downloading getid-ios-ocr.framework binary at "0.1.3"
***  Skipped installing getid-ios-ocr.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15) and the local version is 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)."

    Falling back to building from the source
*** Skipped building getid-ios-ocr due to the error:
Dependency "getid-ios-ocr" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/vvorld/getid-ios-ocr/issues/new
```

**Actual outcome**
Carthage skipped installing a binary framework that built with the previous version of compiler

**Expected outcome**
Carthage should install a binary framework even if it built with the previous version of compiler (5.1+) and with `Build Libraries for Distribution: YES`

**Comment by wacumov** [comment]
If one manually downloads the binary [framework](https://github.com/vvorld/getid-ios-ocr/releases/tag/0.1.3), it works with Swift 5.2 compiler. But the installation via Carthage fails.

**Comment by tmspzz** [comment]
This should be fixed on master.

**Comment by wacumov** [comment]
Ok, I'll try a little bit later. If it works, I'll close the issue.

**Comment by mendesbarreto** [comment]
Hey @tmspzz, how is it going? 

I downloaded the master version and did a ```make install```

The problem now is the following:

```
Please update to the latest Carthage version: 0.34.0. You currently are on 0.33.0
```

The master has not the last version of Carthage? I should look in another branch..

Thank you

**Comment by DavidBrunow** [comment]
That is the correct branch -- I believe that a different branch was used for the last build due to some build pipeline issues and I'm guessing that the version information on `master` is out of date. If you change the version in this file then you'll no longer receive that message:

https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/CarthageKitVersion.swift#L7

**Comment by mendesbarreto** [comment]
Thank you.. after I bumped the version manually like you said it worked well.

**Comment by CraigSiemens** [comment]
Are there any plans to make a new release from master? Running from master works for a single dev but it's a bit of a hassle to get a team to do it or to setup CI to clone and build master.

**Comment by DavidBrunow** [comment]
Unfortunately I cannot answer that, maybe @tmspzz or @jdhealy could.

You could share a pre-built binary in some way, maybe in a separate "tooling" repo that you can clone on CI machines. I know that's not optimal but it might be an improvement.

**Comment by wacumov** [comment]
I've checked the master and it works. So I'll close this issue.
