### ISSUE TITLE
Carthage build ignores specified platform

### ISSUE THREAD

**Issue by Granfalloner** [Carthage/Carthage#2959]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`: Xcode 11.2.1 Build version 11B500
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes 
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "CocoaLumberjack/CocoaLumberjack"
```

**Carthage Output**
```
*** Building scheme "CocoaLumberjack" in Demos.xcworkspace
Build Failed
	Task failed with exit code 64:
	/usr/bin/xcrun xcodebuild -workspace /path/to/Demos.xcworkspace -scheme CocoaLumberjack -configuration Release -derivedDataPath /path/to/derData -sdk appletvsimulator CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -showBuildSettings -skipUnavailableActions
```

**Actual outcome**
Command `carthage build --platform iOS --no-use-binaries` fails. 
It happens because carthage attempts to build for `-sdk appletvsimulator` (as shown in output above), which is not present in my setup.

**Expected outcome**
Carthage builds CocoaLumberjack successfully. Carthage builds only for iOS platform.

**Comment by winterwd** [comment]
me too
