### ISSUE TITLE
Carthage fail at update is call

### ISSUE THREAD

**Issue by ViniciusDeep** [Carthage/Carthage#2962]
* carthage install method: [ ] .pkg, [ x ] homebrew, [ ] source
* `which carthage`:
* `carthage version`: 0.34.0
* `xcodebuild -version`: 11.4
* Are you using `--no-build`? no 
* Are you using `--no-use-binaries`? no 
* Are you using `--use-submodules`? no 
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`?  no

**Cartfile**
```
github "private-repo/private"
```

**Carthage Output**
```
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/stone-payments/emerald-components-ios.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/ViniciusCorreia/Library/Caches/org.carthage.CarthageKit/dependencies/private)) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

I'm use SSH, I can clone the repo from git and use, but when I try to run the update at Carthage this output appear, github with SSH work fine for me, but carthage no

**Comment by tmspzz** [comment]
This is not a carthage issue. This is an issue with your tooling
