### ISSUE TITLE
Carthage copy-frameworks build step always execute even with input and output files

### ISSUE THREAD

**Issue by raphaeloliveira** [Carthage/Carthage#2963]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`: Xcode 11.4 Build version 11E146
* Are you using `--no-build`?  NA
* Are you using `--no-use-binaries`? NA
* Are you using `--use-submodules`? NA
* Are you using `--cache-builds`? NA
* Are you using `--new-resolver`? NA

**Cartfile**
```
github "Alamofire/Alamofire" ~> 4.7.2
```

**Actual outcome**
Carthage run script phase always runs even with the input and output files as per documentation [here](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application).

**Expected outcome**
I expected that Carthage run script phase would only run when the frameworks have changed as per mention in the documentation:
> With output files specified alongside the input files, Xcode only needs to run the script when the input files have changed or the output files are missing. This means dirty builds will be faster when you haven't rebuilt frameworks with Carthage.

![Screen Shot 2020-04-07 at 5 55 50 pm](https://user-images.githubusercontent.com/2700131/78644345-130c8980-78f9-11ea-8990-dbde21d3ffa4.png)

Could this be an Xcode issue or have I wrongly declared the input or output files?

**Comment by nugmanoff** [comment]
Seems really strange to me. Can you please elaborate on how are you checking the fact that script is being executed every time?

**Comment by tmspzz** [comment]
@nugmanoff @DavidBrunow @evandcoleman can anyone triage this bug?

**Comment by nugmanoff** [comment]
@tmspzz not really, I think we should wait for @raphaeloliveira to describe how he is tracing the fact that script is being run every time. 
AFAIK build phase script with input file specified is not being executed on incremental builds, but surely it is being executed on clean build.

@raphaeloliveira are you checking this fact by looking at this tab and then going looking for `Run custom shell script "your script name"` entry?
![Screen Shot 2020-04-07 at 16 17 22](https://user-images.githubusercontent.com/20473743/78657948-54963800-78eb-11ea-92b6-3459788b62c4.png)

**Comment by raphaeloliveira** [comment]
Hey @nugmanoff, yes, I'm checking on the latest build log tab and checking that the script is run. Also, I added an echo before `carthage copy-frameworks` and I can see the message being printed on every build. Should I test differently?

**Comment by raphaeloliveira** [comment]
Is anyone able to shed some light, please?

**Comment by tmspzz** [comment]
@raphaeloliveira unfortunately I don't have time atm to look into this. Maybe you can give it shot yourself  [Getting started is quite easy](https://github.com/Carthage/Carthage/blob/master/CONTRIBUTING.md)

**Comment by elliottwilliams** [comment]
Have you verified that the output file you specify actually exists when copy-frameworks exits? It might also be worth verifying that the input file is _older_ than the output file when this script phase runs (I believe Xcode checks modification times of files, like Make does).
