### ISSUE TITLE
CarthageKitVersion is incorrect 0.33.0 => 0.34.0

### ISSUE THREAD

**Issue by mozeryansky** [Carthage/Carthage#2964]
Running `carthage version` prints:
```
Please update to the latest Carthage version: 0.34.0. You currently are on 0.33.0
0.33.0
```
However, I've checked out master, which is above the latest release of `0.34.0`. It'd be nice to fix this as part of a new release as well.

**Comment by jdhealy** [comment]
Closed by #2966.

Thanks for reaching out, note taken on the last part.
