### ISSUE TITLE
Improper behavior when using `project-directory` option after "Prevent directory traversal" change

### ISSUE THREAD

**Issue by DavidBrunow** [Carthage/Carthage#2969]
Carthage users have the ability to choose the project directory using the `project-directory` command line option here:

https://github.com/Carthage/Carthage/blob/de66acf88f/Source/carthage/Checkout.swift#L39

This option is not currently respected in the fix for "Prevent directory traversal" implemented in https://github.com/Carthage/Carthage/pull/2907 on this line -- `FileManager.default.currentDirectoryPath` is always used:

https://github.com/Carthage/Carthage/commit/de66acf88f32ace83fe99b04fd14565290711ea9#diff-c7185b99f1dc561a5cda81c155590601R52

**Comment by tmspzz** [comment]
Would be great to add a test to prevent future regressions

**Comment by DavidBrunow** [comment]
Looking into this now -- will look into a test for the `project-directory` at the same time.

**Comment by jdhealy** [comment]
Closed by https://github.com/Carthage/Carthage/commit/f656edfe35651b54eec50d814e79d079f8eea7c4.
