### ISSUE TITLE
[Question] Use environment variable in Cartfile

### ISSUE THREAD

**Issue by WoodySlum** [Carthage/Carthage#2974]
Hi

Just a question : is there's a way to use environment variable in Cartfile ?

Here is a  working example :

`binary "https://username:password@nexus.some.fr/repository/carthage/public/Carthage.json" == 6.6.0`

I would like to use something like :

`binary "https://$NEXUS_USERNAME:$NEXUS_PASSWORD@nexus.some.fr/repository/carthage/public/Carthage.json" == 6.6.0`

Any way to do this ?

**Comment by elliottwilliams** [comment]
There is not. Would you be able to generate .netrc files for each user with these credentials? Carthage got support for reading from netrc and doing HTTP Basic auth recently in https://github.com/Carthage/Carthage/commit/84d068bb06df04241fb366b3250645d9b9fbbd9d

**Comment by WoodySlum** [comment]
Hi, netrc file should match ! Thanks.
