### ISSUE TITLE
[Question] Can we make the option `--no-use-binaries` optional?

### ISSUE THREAD

**Issue by Beniamiiin** [Carthage/Carthage#2976]
If I try to install [Intercom framework](https://github.com/intercom/intercom-ios) in this way:
```
carthage update intercom-ios --platform iOS --cache-builds --no-use-binaries
```
I'll get an error:
```
Dependency "intercom-ios" has no shared framework schemes for any of the platforms: iOS
```

It happens, because it's the private library and it distributes without sources, so we can't build a framework from them.

Can we make the option `--no-use-binaries` optional? I mean the option just try to no use binaries, but if it can't, it'll use a binary.

**Comment by ikesyo** [comment]
I recommend you to use binary project specifications: https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification

**Comment by Beniamiiin** [comment]
Thanks, I got it.
