### ISSUE TITLE
Carthage build failed

### ISSUE THREAD

**Issue by faustperic** [Carthage/Carthage#2978]
I am trying to build Carthage locally for https://github.com/mapp-digital/MappIntelligence-iOS-v5
via this command: **carthage build --no-skip-current**

*** xcodebuild output can be found in /var/folders/mw/g629gkts25g00t_1c8d2v2xrljwr95/T/carthage-xcodebuild.IRPP96.log
*** Skipped building MappIntelligence-iOS-v5 due to the error:
Dependency "MappIntelligence-iOS-v5" has no shared framework schemes

But there is shared schemes selected into Xcode see [image](https://ibb.co/vmY4tDN)

Then as it suggested at [link](https://github.com/Carthage/Carthage#resolve-build-failures) I run command **xcodebuild -scheme SCHEME -workspace WORKSPACE build**  and it build successfully. Whole log you can se [here](https://we.tl/t-YrIvtkeMbV) 

I don't know what I am missing, can anyone help me?

**Comment by ikesyo** [comment]
Those schems are for static libraies (.a)/aggregate targets, not for framework targets. Carthage does not support static libraries.

**Comment by faustperic** [comment]
But I read [documentation](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework) : Additionally, since version 0.30.0 Carthage supports static frameworks.

**Comment by elliottwilliams** [comment]
@faustperic Static frameworks are different from static libraries. You probably want to set up a framework target in Xcode, and set `MACH_O_TYPE = staticlib` in its build settings to link it as a static framework.
