### ISSUE TITLE
Carthage Build Failing

### ISSUE THREAD

**Issue by jamescmartinez** [Carthage/Carthage#298]
Hey all,

I'm working on getting Carthage setup for this framework: https://github.com/jamescmartinez/Swifter

The scheme is shared, but when trying to build this project via Carthage and add to an app I'm developing, I receive the following error:

```
*** Building scheme "Swifter" in Swifter.xcodeproj
2015-02-04 13:27:05.034 xcodebuild[33989:637523]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/jamescmartinez/Library/Developer/Xcode/DerivedData/Swifter-esijzdjzyhsxoecwssjvjcfkbugc/Build/Intermediates/Swifter.build/Release-iphonesimulator/SwifterTests.build/Objects-normal/x86_64/SwifterTests.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “SwifterTests.d” couldn’t be opened because there is no such file." UserInfo=0x7f9d52db21f0 {NSFilePath=/Users/jamescmartinez/Library/Developer/Xcode/DerivedData/Swifter-esijzdjzyhsxoecwssjvjcfkbugc/Build/Intermediates/Swifter.build/Release-iphonesimulator/SwifterTests.build/Objects-normal/x86_64/SwifterTests.d, NSUnderlyingError=0x7f9d52da58d0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/jamescmartinez/Library/Developer/Xcode/DerivedData/Swifter-esijzdjzyhsxoecwssjvjcfkbugc/Build/Intermediates/Swifter.build/Release-iphonesimulator/SwifterTests.build/Objects-normal/x86_64/SwifterTests.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f9d52da5930>{number = 8, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
```

From what I can tell, it's trying to build the tests but the file is not found. Why is it trying to build the tests?

I've tried deleting DerivedData, but that doesn't help. Also, if I clone the project locally and try to build it using `xcodebuild -scheme Swifter -project Swifter.xcodeproj build`, the build succeeds.

**Comment by jamescmartinez** [comment]
xcodebuild -version
Xcode 6.1.1
Build version 6A2008a

**Comment by mattrubin** [comment]
There was [another issue](https://github.com/Carthage/Carthage/issues/294#issuecomment-72532999) where xcodebuild was trying to build the tests along with the framework. Editing the scheme fixed the issue.

In the framework's scheme, in the "Build" section, make sure the check boxes next to SwifterTests are *unchecked* for all actions besides "Test" (specifically, try turning it off for "Run"). This may prevent xcodebuild from trying to build the tests.

**Comment by jamescmartinez** [comment]
@mattrubin  Thanks, this worked. Should this be added to the Readme under "Supporting Carthage for your framework" or is this somehow specific to my project?

https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

**Comment by jspahrsummers** [comment]
Building the tests is not necessarily wrong, so it's not important for support, but your build-with-tests appears to fail for some reason.
