### ISSUE TITLE
Issue with Github API

### ISSUE THREAD

**Issue by VinnyScorsatto** [Carthage/Carthage#2990]
Hello,

I have been receiving this email, not sure how to deal with it. Any clues?

On May 21st, 2020 at 00:41 (UTC) you used a password to access an endpoint through the GitHub API using org.carthage.CarthageKit/0.34.0:

https://api.github.com/repositories/22458259/releases/tags/5.2.0

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

Thanks

**Comment by TofPlay** [comment]
Same issue:

```
Subject : [GitHub] Deprecation Notice

Hi @TofPlay,

On May 28th, 2020 at 06:09 (UTC) you used a password to access an endpoint through the GitHub API using org.carthage.CarthageKit/0.34.0:

https://api.github.com/repositories/41873203/releases/tags/1.1.0

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

Thanks,
The GitHub Team
```

**Comment by tmspzz** [comment]
This is an issue on your end. Carthage doesn't do authenticated requests by default

**Comment by VinnyScorsatto** [comment]
@tmspzz thanks, that is true. @TofPlay, I end up finding the solution. You need to generate a token on GitHub and use this instead of the password.
