### ISSUE TITLE
Frameworks are not building with arm64e architecture

### ISSUE THREAD

**Issue by ynieSalesforce** [Carthage/Carthage#2994]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`: 11.3.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no 
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "ReactiveCocoa/ReactiveCocoa" ~> 10.1
github "pointfreeco/swift-overture" "0.5.0"
github "layoutBox/PinLayout" "1.8.7"
github "layoutBox/FlexLayout" "1.3.12"
github "SDWebImage/SDWebImage" "5.0.6"
github "airbnb/lottie-ios" "3.1.5"
github "pointfreeco/swift-snapshot-testing" ~> 1.6
```

**Carthage Output**

Using: 
build using: `carthage update --platform iOS`
`xcrun -sdk iphoneos lipo -info CocoaLumberjack.framework/CocoaLumberjack`

```
Architectures in the fat file: CocoaLumberjack.framework/CocoaLumberjack are: i386 x86_64 armv7 arm64 
```

**Actual outcome**
Build did not include Architecture arm64e

**Expected outcome**
Build should include arm64e Architecture

Hi everyone, this maybe a missing config issue, but we're trying to add support to the arm64e architecture to our app. When following instructions from [Apple](https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication) and building for a device with a A12 chip (like an iPhone XR), it results in the `missing required architecture arm64e in file...[framework]`.

**Comment by tmspzz** [comment]
Check that `VALID_ARCHS` contains your desired architecture.

**Comment by tmspzz** [comment]
I don't think `ARCHS_STANDARD` contains `arm64e` for iOS. You have to pass a custom .xcconfig file to include your desired architecture since I don't think you want to modify CocoaLumberjack's .xcodeproj 

I'm sorry but this is not a Carthage issue.

**Comment by ynieSalesforce** [comment]
Thanks for the response. I see arm64e as one of the valid architectures. 

Also, sorry for the dumb question, but is there an example of how to create a custom .xcconfig file and pass that in?

**Comment by ynieSalesforce** [comment]
Nevermind, I think I found a good example. Thanks for the tip!

**Comment by ynieSalesforce** [comment]
@tmspzz Do you happen to know what the field that xcodebuild for carthage is looking at when determining which architectures to build?

Here's my output for xcodebuild on my current project:

```
xcodebuild -showBuildSettings  -sdk iphoneos | grep ARCHS

    ARCHS = armv7 armv7s arm64 arm64e
    ARCHS_STANDARD = arm64
    ARCHS_STANDARD_32_64_BIT = armv7 arm64
    ARCHS_STANDARD_32_BIT = armv7
    ARCHS_STANDARD_64_BIT = arm64
    ARCHS_STANDARD_INCLUDING_64_BIT = arm64
    ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64 arm64e
    VALID_ARCHS = arm64e arm64 armv7s armv7
```

But it's still resulting in a fat architectures of `i386 x86_64 armv7 arm64`

**Comment by tmspzz** [comment]
There is no build by architecture, it always builds by sdk for Release configuration. So iphoneos or iphoneSimulator.

**Comment by ynieSalesforce** [comment]
Got it, thank you for the response
