### ISSUE TITLE
How to pin prebuilt frameworks with hash?

### ISSUE THREAD

**Issue by Kentzo** [Carthage/Carthage#2996]
Carthage can automatically download and use prebuilt frameworks if properly the are named and placed in a pre-defined place.

However I cannot figure out how to provide a list of allowed zip files via hashes, similar to pip's [hash-checking mode](https://pip.pypa.io/en/stable/reference/pip_install/#hash-checking-mode).

**Comment by tmspzz** [comment]
There is no pinning by hash.

Carthage can use GitHub releases or binary definitions https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-only-frameworks

**Comment by Kentzo** [comment]
The idea is to detect and fail when author binary is replaced, how either option achieves this? As far as I know repo's maintainer can replace files at will.

**Comment by tmspzz** [comment]
You would have to write your own scripts to detect that.

**Comment by Kentzo** [comment]
Would the maintainers be interested in a PR adding this?

**Comment by tmspzz** [comment]
You might want to first check how .version files currently work.

It would be nice to have but:
1) It shouldn't change/add anything to the Cartfile
2) It shouldn't required additional files

At the moment the list of features we want is described here: https://github.com/Carthage/Carthage/issues/2890

**Comment by Kentzo** [comment]
Hashes need to be specified somewhere.

I guess alternative approach is to prebuilt all dependencies and use a private repository.

**Comment by tmspzz** [comment]
@Kentzo You can also pick binaries for a separate cache, for example using [this](https://github.com/tmspzz/Rome)

**Comment by Kentzo** [comment]
For the reference, here's how SPM does it: https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md
