### ISSUE TITLE
My project had more than 20.framework files and was about to be managed with Carthage, but I ran into some problems.

### ISSUE THREAD

**Issue by JsonRight** [Carthage/Carthage#2998]
My project had more than 20.framework files and was about to be managed with Carthage, but I ran into some problems. Because the CarthageKit content is too deep to know where to start the transformation, so I feed back the problem here and hope to get help:
1. These frameworks come with resources like XIB. If bundles are built, Carthage doesn't automatically package bundles. Do you have any good plans?
2. Since my project has many frameworks, but they are not the base library, and there are multi-layer framework dependencies, Carthage will compile multiple frameworks down every time the dependent framework is modified, which is a waste of time.
3. Part of the Framework is compiled by the mixed compilation of Object-C Framework and Swift Framework, and the Dynamic Framework is dependent on the Staticframework. Xcode Console will print: "Objc [16049]: Class XXX is implemented in both XXXXXXXX and XXXXXXXXXXXXXX. One of the two will be used. Which One is undefined." although no crash was detected
I may be a little verbose in my description, but I hope someone can guide me. thank you

**Comment by kientux** [comment]
How do you resolve this issue? I had the same problem with `RxDataSources`. It has `RxSwift` as dependency but my app also has `RxSwift` as dependency.

**Comment by JsonRight** [comment]
In fact, Carthage allows framework to depend on other frameworks, only need to add cartfile and update in their own framework as the project depends on framework, then they can complete their own framework debugging, if only their own private framework is dependent on RxSwift, it makes you confused. My problem is more complicated than that. Carthage doesn't consider the ease of use of framework developers, or even with bundles. Unfortunately, I was not able to sort through the Carthage source code, had to address their own problems, wrote a simple command line tool.




| |
姜奎
|
|
邮箱：jk601539674@163.com
|

签名由 网易邮箱大师 定制

On 07/09/2020 22:06, Kien Nguyen wrote:

How do you resolve this issue? I had the same problem with RxDataSources. It has RxSwift as dependency but my app also has RxSwift as dependency.
