### ISSUE TITLE
Using a pinnedversion or branch specifier in Cartfile does not work

### ISSUE THREAD

**Issue by jantuitman** [Carthage/Carthage#300]
Any of these variants, though they have been documented, don't appear to work:

```
git "https://github.com/stephencelis/SQLite.swift.git" "8f29fc56e005b1a89bfa52eda96c07f9e321832f" 
git "https://github.com/stephencelis/SQLite.swift.git" "master"
github ""https://github.com/stephencelis/SQLite.swift" 
github ""https://github.com/stephencelis/SQLite.swift" "master"
github ""https://github.com/stephencelis/SQLite.swift" "8f29fc56e005b1a89bfa52eda96c07f9e321832f" 
```

the project in question is not tagged and cannot be checked out in any way as far as  I have discovered.

Sample output for the topmost variant:

```
*** Fetching SQLite.swift
Failed to check out repository into /Users/jantuitman/Library/Caches/org.carthage.CarthageKit/dependencies/SQLite.swift: No object named "8f29fc56e005b1a89bfa52eda96c07f9e321832f" exists
```

**Comment by mdiep** [comment]
Can you check which version of carthage you're running with `carthage version`?

The topmost variant does work for me with Carthage 0.5.2.

**Comment by jgerardo-velez** [comment]
this worked for me
git "https://github.com/stephencelis/SQLite.swift.git" "master"

I'm using carthage version 0.6.3
