### ISSUE TITLE
Refer to an Xcode project file in Cartfile

### ISSUE THREAD

**Issue by FranklinYu** [Carthage/Carthage#3000]
Is there currently any way to refer to an Xcode file in a GitHub repository? For example

https://github.com/omnigroup/OmniGroup/tree/master/Frameworks/OmniAppKit/OmniAppKit.xcodeproj

I would like something similar to

```Cartfile
github "omnigroup/OmniGroup/Frameworks/OmniAppKit" "master"
```

but this is invalid Cartfile syntax (as expected). If I simply refer to

```Cartfile
github "omnigroup/OmniGroup" "master"
```

Carthage seems to be building all Xcode projects in it (which may fail and I don’t want to care about other projects).

**Comment by elliottwilliams** [comment]
Carthage doesn't give you a way to express this via Cartfile syntax. What you're asking for sounds a lot like the "skip schemes" behavior that's been a source of heated discussion. #2529 has a decent overview of the problem and links to other issues where it's been discussed. Being able to conditionally-build parts of a dependency would be a big change to Carthage's conceptual model and I don't expect it to happen any time soon :-\

I think your options are:

* In the dependency's repo (i.e. omnigroup/OmniGroup), delete the xcschemes for schemes you don't want Carthage to build. If you can't make upstream changes in the repo, you could at least delete the undesired schemes after you run `carthage checkout`.
* Build all the projects in the dependency anyway, and ignore the ones you don't want. Use framework caching (optionally with a remote cache tool like [Rome](https://github.com/tmspzz/Rome)) to avoid the added build-time cost.
* Fork the repo and delete the projects/schemes you don't care about.
* Set up a [binary package](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification) for this dependency that only vends the frameworks you care about.

**Comment by FranklinYu** [comment]
> * Build all the projects in the dependency anyway, and ignore the ones you don't want.

How does this option work? Carthage seems to abort at failure. For example, when I `carthage build OmniGroup`, it fails with

> xcodebuild: error: Unable to read project 'OAColorPaletteTest.pbproj'

but I can manually build target `OmniBase` in `OmniGroup/Frameworks/OmniBase/OmniBase.xcodeproj` without issue. (By “manual build” I mean opening the Xcode project.)

**Comment by tmspzz** [comment]
As you can see, `xcodebuild` is failing with error. Check the logs for why.

**Comment by FranklinYu** [comment]
@tmspzz Yes, I understand that `xcodebuild` cannot build `OAColorPalleteTest`, but can I *skip* this target? I don’t think I would need a *test target* of my dependency.

**Comment by tmspzz** [comment]
Test targets are normally skipped if setup correctly.

**Comment by FranklinYu** [comment]
True, but for example that repository contains many non-test targets that I don’t need. Actually in https://github.com/omnigroup/OmniGroup/tree/master/Frameworks there are 17 Xcode projects, and I want to use only three of them. Even if they set up the targets correctly, Carthage will still build all the `.xcodeproj`s even if most of them are not used in my project at all.

Hosting multiple projects in one GitHub repository isn’t really uncommon. The JavaScript community even has [a dedicated tool to manage such repositories](https://lerna.js.org). In the specific case of OmniGroup, it makes sense to them because they are synchronizing from their internal SVN repository, which is monorepo by design. I didn’t mean to “demand” anything, but I think it’s at least a valid feature request to build only some of the projects in a GitHub repository.

**Comment by tmspzz** [comment]
I understand your issue but @elliottwilliams has already outlined all the relevant discussion and the options you have.

**Comment by FranklinYu** [comment]
I think I misread #2529, which seems exactly the problem I was describing. I subscribed that issue. May comment in #1227 if I have new ideas in future.

Sorry for the noise I created! In addition, thanks a lot for maintaining Carthage.
