### ISSUE TITLE
Xcode 12 fails with cryptic linker error when certain frameworks target «armv7-apple-ios8.0»

### ISSUE THREAD

**Issue by boctor** [Carthage/Carthage#3004]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.35.0
* `xcodebuild -version`: Xcode 12.0 Build version 12A6159 
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "matthewpalmer/Locksmith
```

**Carthage Output**
```
Ld /Users/pb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6159/Locksmith/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/Locksmith\ iOS/IntermediateBuildFilesPath/Locksmith.build/Release-iphoneos/Locksmith\ iOS.build/Objects-normal/armv7/Binary/Locksmith normal armv7 (in target 'Locksmith iOS' from project 'Locksmith')
    cd /Users/pb/Desktop/CarthageTest/Carthage/Checkouts/Locksmith
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target armv7-apple-ios8.0 -dynamiclib -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk -L/Users/pb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6159/Locksmith/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/Locksmith\ iOS/BuildProductsPath/Release-iphoneos -F/Users/pb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6159/Locksmith/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/Locksmith\ iOS/BuildProductsPath/Release-iphoneos -filelist /Users/pb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6159/Locksmith/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/Locksmith\ iOS/IntermediateBuildFilesPath/Locksmith.build/Release-iphoneos/Locksmith\ iOS.build/Objects-normal/armv7/Locksmith.LinkFileList -install_name @rpath/Locksmith.framework/Locksmith -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/pb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6159/Locksmith/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/Locksmith\ iOS/IntermediateBuildFilesPath/Locksmith.build/Release-iphoneos/Locksmith\ iOS.build/Objects-normal/armv7/Locksmith_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/pb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6159/Locksmith/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/Locksmith\ iOS/BuildProductsPath/Release-iphoneos -fapplication-extension -fobjc-link-runtime -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/pb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6159/Locksmith/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/Locksmith\ iOS/IntermediateBuildFilesPath/Locksmith.build/Release-iphoneos/Locksmith\ iOS.build/Objects-normal/armv7/Locksmith.swiftmodule -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/pb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6159/Locksmith/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/Locksmith\ iOS/IntermediateBuildFilesPath/Locksmith.build/Release-iphoneos/Locksmith\ iOS.build/Objects-normal/armv7/Locksmith_dependency_info.dat -o /Users/pb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6159/Locksmith/4.0.0/Build/Intermediates.noindex/ArchiveIntermediates/Locksmith\ iOS/IntermediateBuildFilesPath/Locksmith.build/Release-iphoneos/Locksmith\ iOS.build/Objects-normal/armv7/Binary/Locksmith
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in Locksmith.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Actual outcome**
Carthage failed to build, but succeeds using Xcode 11.5 command line tools

**Expected outcome**
Carthage should successfully build with Xcode 12 just as it does with Xcode 11.5

**Comment by jdhealy** [comment]
Could you locate and post (from your Cartfile.resolved file, is the probably place) the version number or commit-ish of `matthewpalmer/Locksmith` you're seeing issues with?

**Comment by boctor** [comment]
4.0.0 is the version in Cartfile.resolved.

Also of note is that the command I used is `carthage update —platform ios`

**Comment by jdhealy** [comment]
Looks like it's the attempt at `armv7-apple-ios8.0` that’s causing this failure —

…in some completely different work I was just doing, had Xcode 12A6159 warn at me: `warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.`

**Comment by boctor** [comment]
You’re right. I had suspected the same and had bumped the deployment target to 9.0 in a fork but saw the same error. I just tried again but this time to 12.0 and was able to successfully build

**Comment by boctor** [comment]
When the deployment target is 9.0 the target changes to `armv7-apple-ios9.0` which produced the same error, but when the deployment target is 12.0 the target changes to `arm64-apple-ios12.0` and no error. What’s interesting is that other projects with a deployment target of 8.0 build fine with Xcode 12 (one example is emaloney/CleanroomLogger) so I think there is a bug in Xcode 12’s armv7-* targets related to Swift strings that is only getting triggered by some projects.

**Comment by Paladinfeng** [comment]
Can you manual archive framework by xcode? Maybe It's Xcode 12 bugs

**Comment by craigrouse** [comment]
Working on the same issue for our project, I've found that in the project settings, changing "Swift Compiler - Code Generation > Optimization Level" to "No Optimization" solves this problem, so I conclude that it's a Swift compiler/optimizer bug. If you try and build the project in Xcode with the scheme set to "Release" mode, you'll see this same issue appear in Xcode. Change the optimizer setting to none, and you can build again. These are just my initial findings - thought they might be useful.

**Comment by craigrouse** [comment]
I've just used the Feedback Assistant to report the issue to Apple. I'd suggest anyone else experiencing this issue does the same. I think it's safe to say this isn't a Carthage bug any more.

**Comment by marcelofabri** [comment]
Related: https://github.com/Alamofire/Alamofire/issues/3240 and https://developer.apple.com/forums/thread/649918

**Comment by datacosmos** [comment]
I think this is still an issue - for podfiles there is a workaround via a postinstall script which sets the deployment target to 9. Would that also be possible to do something like that in carthage?

**Comment by tmspzz** [comment]
@datacosmos maybe by supplying a custom xcconfig file

**Comment by datacosmos** [comment]
But that would would not be a generic solution? What I meant is sth. like [this](https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d) :

> You can setup your podfile to automatically match the deployment target of all the podfiles to your current project deployment target like this ...
