### ISSUE TITLE
Carthage does not support URL redirects

### ISSUE THREAD

**Issue by fabian-guerra** [Carthage/Carthage#3005]
* carthage install method: [ ] .pkg, [ X ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.35.0
* `xcodebuild -version`: Xcode 11.4 Build version 11E146
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
Is a private file in a secured URL

binary "https://path/framework.json" == 0.0.0
```

**Carthage Output**
```
A shell task (/usr/bin/env unzip -uo -qq -d /var/folders/d3/nr3q6h9j47g7fy8smbj0q7y40000gq/T/carthage-archive.kgguqq /Users/myUser/Library/Caches/org.carthage.CarthageKit/binaries/organization/version/framework.zip) failed with exit code 9:
[/Users/myUser/Library/Caches/org.carthage.CarthageKit/binaries/organization/version/framework.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/myUser/Library/Caches/org.carthage.CarthageKit/binaries/organization/version/framework.zip or
        /Users/myUser/Library/Caches/org.carthage.CarthageKit/binaries/organization/version/framework.zip.zip, and cannot find /Users/myUser/Library/Caches/org.carthage.CarthageKit/binaries/organization/version/framework.zip.ZIP, period.
```

**Actual outcome**
I could not install the library

**Expected outcome**
Library installed.

### Context

In an HTTP server when you secure an URL with credentials. The server receives the request and matches the URL with an access list. Since the URL is secured with credentials it will return the “Login URL” instead. Once you provide your credentials the server validates then redirects to the original request. 

Is the last step: when the authenticated request returns to the original request that Carthage does not support it. Carthage uses Apple's network stack and this stack requires to handle [manually](https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1411626-urlsession) redirections.

**Comment by ikesyo** [comment]
It seems that this is a duplicate of #1868 and #2711.
