### ISSUE TITLE
Code object is not signed at all in subcomponent

### ISSUE THREAD

**Issue by sbeff** [Carthage/Carthage#3007]
* carthage install method: [x] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.35.0
* `xcodebuild -version`: Xcode 11.5 Build version 11E608c
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No 
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
git "my/framework/path"
```

**Carthage Output**
```
*** Fetching MyFramework
*** Fetching Reachability.swift
*** Checking out Reachability.swift at "v5.0.0"
*** Checking out MyFramework at "0.1.1"
*** xcodebuild output can be found in /var/folders/31/42k9xs7x4sl3n1l1dsghy_d40000gn/T/carthage-xcodebuild.1SjuxN.log
*** Building scheme "Reachability" in Reachability.xcodeproj
*** Building scheme "MyFramework" in MyFramework.xcodeproj
```

**Actual outcome**
Everything working as expected, with Carthage building my framework and its dependency

**Expected outcome**
I created a macOS framework that has Reachability.swift as a dependency (added in the framework's Cartfile), but when I try to compile the app, I get the following output:
```
A shell task (/usr/bin/xcrun codesign --force --sign 4CDE47469EC16E4DD86D65974F30D402C2475434 --preserve-metadata=identifier,entitlements /Users/user/Library/Developer/Xcode/DerivedData/ReachabilityApp-aiizihgmjilichcrxouknzapitvx/Build/Products/Debug/ReachabilityApp.app/Contents/Frameworks/MyFramework.framework) failed with exit code 1:
/Users/user/Library/Developer/Xcode/DerivedData/ReachabilityApp-aiizihgmjilichcrxouknzapitvx/Build/Products/Debug/ReachabilityApp.app/Contents/Frameworks/MyFramework.framework: code object is not signed at all
In subcomponent: /Users/user/Library/Developer/Xcode/DerivedData/ReachabilityApp-aiizihgmjilichcrxouknzapitvx/Build/Products/Debug/ReachabilityApp.app/Contents/Frameworks/MyFramework.framework/Versions/Current/Frameworks/Reachability.framework
```
This is my run script build phase:

![Screenshot 2020-07-03 at 11 33 28](https://user-images.githubusercontent.com/15926323/86455637-2cb74480-bd21-11ea-948e-78281cecf348.png)

I have already tried to follow the steps in #2866 and #2187, but I haven't solved it yet. What can I try to do to fix it? Thanks.

**Comment by tmspzz** [comment]
If you codesign the framework manually does it work?
