### ISSUE TITLE
What is Cartfile.project and is there documentation on it?

### ISSUE THREAD

**Issue by arnopoulos** [Carthage/Carthage#3009]
I was recently looking at the [Kingfisher](https://github.com/onevcat/Kingfisher) framework and I noticed a Cartfile.project file. I tried to look up some documentation here but I couldn't find anything on it. Does anyone know where to find more documentation on this?

**Comment by ikesyo** [comment]
Looks like `Cartfile.project` is for https://github.com/nsoperations/Carthage. That is not supported in this original tool. Closing.
