### ISSUE TITLE
Xcode 12 beta 2 - Segmentation fault: 11 (in target 'Eureka' from project 'Pods')

### ISSUE THREAD

**Issue by johnlietzke** [Carthage/Carthage#3010]
Cocoapods - Eureka 5.2.1

Xcode complier error - Segmentation fault: 11 (in target 'Eureka' from project 'Pods')

1.	Apple Swift version 5.3 (swiftlang-1200.0.16.13 clang-1200.0.22.25)
2.	While evaluating request TypeCheckSourceFileRequest(source_file "/Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/SelectableSection.swift")
3.	While evaluating request TypeCheckFunctionBodyUntilRequest(Eureka.(file).SelectableSectionType extension.selectedRows()@/Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/SelectableSection.swift:76:17, )
4.	While type-checking statement at [/Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/SelectableSection.swift:76:51 - line:79:5] RangeText="{
        let selectedRows: [BaseRow] = self.filter { $0 is SelectableRow && $0.baseValue != nil }
        return selectedRows.map { $0 as! SelectableRow }
    "
5.	While type-checking declaration 0x7fd0ad992150 (at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/SelectableSection.swift:77:9)
6.	While type-checking expression at [/Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/SelectableSection.swift:77:39 - line:77:96] RangeText="self.filter { $0 is SelectableRow && $0.baseValue != nil "
0  swift                    0x00000001143a4f25 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  swift                    0x00000001143a3f25 llvm::sys::RunSignalHandlers() + 85
2  swift                    0x00000001143a54df SignalHandler(int) + 111
3  libsystem_platform.dylib 0x00007fff713715bd _sigtramp + 29
4  libsystem_platform.dylib 0x00007fd0af91f1a0 _sigtramp + 18446743872892230656
5  swift                    0x00000001111d1fb8 swift::GenericSignatureBuilder::PotentialArchetype::getDependentType(swift::ArrayRefView<swift::Type, swift::GenericTypeParamType*, swift::GenericTypeParamType* swift::staticCastHelper<swift::GenericTypeParamType>(swift::Type const&), true>) const + 56
6  swift                    0x00000001111d0e4a swift::GenericSignatureBuilder::EquivalenceClass::getAnchor(swift::GenericSignatureBuilder&, swift::ArrayRefView<swift::Type, swift::GenericTypeParamType*, swift::GenericTypeParamType* swift::staticCastHelper<swift::GenericTypeParamType>(swift::Type const&), true>) + 106
7  swift                    0x00000001111d209c swift::GenericSignatureBuilder::EquivalenceClass::getTypeInContext(swift::GenericSignatureBuilder&, swift::GenericEnvironment*) + 44
8  swift                    0x00000001111d724a swift::ArchetypeType::resolveNestedType(std::__1::pair<swift::Identifier, swift::Type>&) const + 202
9  swift                    0x000000011126e18f swift::ArchetypeType::getNestedType(swift::Identifier) const + 319
10 swift                    0x000000011126ed0b getMemberForBaseType(llvm::function_ref<swift::ProtocolConformanceRef (swift::CanType, swift::Type, swift::ProtocolDecl*)>, swift::Type, swift::Type, swift::AssociatedTypeDecl*, swift::Identifier, swift::SubstOptions) + 491
11 swift                    0x0000000111277cc1 llvm::Optional<swift::Type> llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>::callback_fn<substType(swift::Type, llvm::function_ref<swift::Type (swift::SubstitutableType*)>, llvm::function_ref<swift::ProtocolConformanceRef (swift::CanType, swift::Type, swift::ProtocolDecl*)>, swift::SubstOptions)::$_25>(long, swift::TypeBase*) + 2241
12 swift                    0x0000000111271b69 swift::Type::transformRec(llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>) const + 57
13 swift                    0x000000011126f414 substType(swift::Type, llvm::function_ref<swift::Type (swift::SubstitutableType*)>, llvm::function_ref<swift::ProtocolConformanceRef (swift::CanType, swift::Type, swift::ProtocolDecl*)>, swift::SubstOptions) + 308
14 swift                    0x0000000110d112a5 swift::Type llvm::function_ref<swift::Type (swift::Type)>::callback_fn<swift::constraints::ConstraintSystem::simplifyTypeImpl(swift::Type, llvm::function_ref<swift::Type (swift::TypeVariableType*)>) const::$_17>(long, swift::Type) + 725
15 swift                    0x000000011127ec72 llvm::Optional<swift::Type> llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>::callback_fn<swift::Type::transform(llvm::function_ref<swift::Type (swift::Type)>) const::$_20>(long, swift::TypeBase*) + 18
16 swift                    0x0000000111271b69 swift::Type::transformRec(llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>) const + 57
17 swift                    0x0000000111271d48 swift::Type::transformRec(llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>) const + 536
18 swift                    0x0000000111271d48 swift::Type::transformRec(llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>) const + 536
19 swift                    0x0000000110c54ca9 swift::constraints::ConstraintSystem::matchTypesBindTypeVar(swift::TypeVariableType*, swift::Type, swift::constraints::ConstraintKind, swift::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder, llvm::function_ref<swift::constraints::ConstraintSystem::TypeMatchResult ()>) + 201
20 swift                    0x0000000110c4b39d swift::constraints::ConstraintSystem::matchTypes(swift::Type, swift::Type, swift::constraints::ConstraintKind, swift::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder) + 3053
21 swift                    0x0000000110c72de0 swift::constraints::ConstraintSystem::addConstraintImpl(swift::constraints::ConstraintKind, swift::Type, swift::Type, swift::constraints::ConstraintLocatorBuilder, bool) + 96
22 swift                    0x0000000110c49fb2 swift::constraints::ConstraintSystem::addConstraint(swift::constraints::ConstraintKind, swift::Type, swift::Type, swift::constraints::ConstraintLocatorBuilder, bool) + 66
23 swift                    0x0000000110d024c1 swift::constraints::ConstraintSystem::resolveOverload(swift::constraints::ConstraintLocator*, swift::Type, swift::constraints::OverloadChoice, swift::DeclContext*) + 11105
24 swift                    0x0000000110c74307 swift::constraints::ConstraintSystem::simplifyConstraint(swift::constraints::Constraint const&) + 1207
25 swift                    0x0000000110c74d32 swift::constraints::ConstraintSystem::simplifyDisjunctionChoice(swift::constraints::Constraint*) + 18
26 swift                    0x0000000110c950bb swift::constraints::DisjunctionStep::attempt(swift::constraints::DisjunctionChoice const&) + 139
27 swift                    0x0000000110c9493c swift::constraints::BindingStep<swift::constraints::DisjunctionChoiceProducer>::take(bool) + 540
28 swift                    0x0000000110c81c14 swift::constraints::ConstraintSystem::solveImpl(llvm::SmallVectorImpl<swift::constraints::Solution>&) + 356
29 swift                    0x0000000110c84b84 swift::constraints::ConstraintSystem::solve(llvm::SmallVectorImpl<swift::constraints::Solution>&, swift::FreeTypeVariableBinding) + 52
30 swift                    0x0000000110c83fa4 swift::constraints::ConstraintSystem::solve(swift::constraints::SolutionApplicationTarget&, swift::FreeTypeVariableBinding) + 1140
31 swift                    0x0000000110dc1e41 swift::TypeChecker::typeCheckExpression(swift::constraints::SolutionApplicationTarget&, bool&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 833
32 swift                    0x0000000110dc35b7 swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*, swift::Type, swift::PatternBindingDecl*, unsigned int) + 151
33 swift                    0x0000000110dc37a0 swift::TypeChecker::typeCheckPatternBinding(swift::PatternBindingDecl*, unsigned int, swift::Type) + 256
34 swift                    0x0000000110e18b35 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 5237
35 swift                    0x0000000110ea74f7 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 8695
36 swift                    0x0000000110ea2e4a bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 314
37 swift                    0x0000000110ea171e swift::TypeCheckFunctionBodyUntilRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*, swift::SourceLoc) const + 2398
38 swift                    0x0000000110eaa6cd llvm::Expected<swift::TypeCheckFunctionBodyUntilRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckFunctionBodyUntilRequest, (void*)0>(swift::TypeCheckFunctionBodyUntilRequest const&) + 925
39 swift                    0x0000000110ea2898 swift::TypeCheckFunctionBodyUntilRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyUntilRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyUntilRequest, swift::TypeCheckFunctionBodyUntilRequest::OutputType) + 440
40 swift                    0x0000000110edff84 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 1252
41 swift                    0x0000000110ee2b99 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequest const&) + 953
42 swift                    0x0000000110edf914 swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType) + 164
43 swift                    0x0000000110062c3b swift::CompilerInstance::performSemaUpTo(swift::SourceFile::ASTStage_t) + 6859
44 swift                    0x000000010ff24d81 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 6849
45 swift                    0x000000010fea9967 main + 1255
46 libdyld.dylib            0x00007fff7114ec71 start + 1
error: Segmentation fault: 11 (in target 'Eureka' from project 'Pods')

**Comment by tmspzz** [comment]
As written in the log, this is a compiler error. Not a carthage issue. It would be better reported to the swift compiler team.
