### ISSUE TITLE
Support XCFrameworks?

### ISSUE THREAD

**Issue by Droppix** [Carthage/Carthage#3012]
Hi,

Is XCFrameworks already supported by carthage 0.35.0?
If yes, how to use it?

Thanks

**Comment by ikesyo** [comment]
Duplicate of #2799, #2801, #2881.

**Comment by Droppix** [comment]
Sorry to raise you again, but it's not clear to me! I see you've been working on it, but when will it be available?

**Comment by tmspzz** [comment]
XCFrameworks are not supported in `0.35.0` . The closet thing to a release schedule is this document atm but there aren't enough contributions to hit the goals. https://github.com/Carthage/Carthage/issues/2890
