### ISSUE TITLE
Make dependencies sorted in the version file

### ISSUE THREAD

**Issue by peteranny** [Carthage/Carthage#3013]
* carthage install method: [ ] .pkg, [v] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`:
Xcode 10.1
Build version 10B61
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`?  NO
* Are you using `--use-submodules`?  NO
* Are you using `--cache-builds`?  NO
* Are you using `--new-resolver`?  NO

**Cartfile**
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 6.27.0
```

**Carthage Output**
Run the bootstrapping for two times
```
# The first time
carthage bootstrap # The first bootstrap
cat Carthage/Build/.FirebaseAnalyticsBinary.version

# The second time
carthage bootstrap # The first bootstrap
cat Carthage/Build/.FirebaseAnalyticsBinary.version
```

Compare the version file **.FirebaseAnalyticsBinary.version** before and after.
```
{
  "Mac" : [

  ],
  "watchOS" : [

  ],
  "tvOS" : [

  ],
  "commitish" : "6.28.1",
  "iOS" : [
    {
      "name" : "nanopb",
      "hash" : "bd968d91c019c9f06c723ce8252f45ef15363b592d61bba2f56a3e1f943bbd6a",
      "linking" : "dynamic"
    },
    {
      "name" : "FirebaseCore",
      "hash" : "e9f35f56b1b2ffe905c1cb0cc716591507a8963e838488967fe5edcf9f16c32f",
      "linking" : "dynamic"
    },
    {
      "name" : "Firebase",
      "hash" : "a8669248da9519e9955e00448e518e1ca6becb32689eedddde237e19ad1136ae",
      "linking" : "dynamic"
    },
    {
      "name" : "FirebaseCoreDiagnostics",
      "hash" : "b9325775b24af655755a4cd25e7c74c7e69096900d48735b9e6633e52cff2796",
      "linking" : "dynamic"
    },
    {
      "name" : "FIRAnalyticsConnector",
      "hash" : "10dc1b7749e8dba04866da992c916b8a58c3254865f39e7b373896a287334c90",
      "linking" : "dynamic"
    },
    {
      "name" : "FirebaseAnalytics",
      "hash" : "bec39b92ec2d8a4898ce94e52a90deaf5075a48785194d95fea288ba9f13fcf3",
      "linking" : "dynamic"
    },
    {
      "name" : "PromisesObjC",
      "hash" : "3a912f7f0ca44e2cab2b2d671ce3c706fbe684320d915d10fd5a8c2e4daf81c2",
      "linking" : "dynamic"
    },
    {
      "name" : "FirebaseInstallations",
      "hash" : "4f7da76100bb73eb63f35cf622851ebee282335c881260cc4837269d1ffd1e64",
      "linking" : "dynamic"
    },
    {
      "name" : "GoogleDataTransport",
      "hash" : "953e417388c371ac40dd3461b0fe9f6d0b360a6bfc80f39904e80bba5af0e516",
      "linking" : "dynamic"
    },
    {
      "name" : "GoogleUtilities",
      "hash" : "c5e3f794b5444ab99f88b2d454914f27d69f5c6f716c4930ac04bb2c720c8d31",
      "linking" : "dynamic"
    },
    {
      "name" : "GoogleAppMeasurement",
      "hash" : "12147d5214b152b7514d6c12947a66e76888b10b709908c611b79bb9cc522a46",
      "linking" : "dynamic"
    }
  ]
}
```

**Actual outcome**
Carthage did not sort the dependencies in the version file. (The `{"name" : "...", "hash" : "...", "linking" : "..." }` part)
The order of the dependencies is random after each bootstrapping.

It is inconvenient if they are not sorted because we can hardly tell which framework is added and which one is removed.
For example, changing FirebaseAnalyticsBinary from 6.27.0 to 6.28.1 makes two frameworks removed.
We need to know they are removed so we need to remove the two from our app (or linkage will fail).

In my use case, the version file as well as the prebuilt frameworks are included in my repository with Git LFS
If the version file is sorted, I can use `git diff` to immediately tell which frameworks are altered.

**Expected outcome**
Carthage should sort the dependencies in the version file
I'd like to ask if this update is acceptable?

**Comment by tmspzz** [comment]
I think this makes sense. I don't see any harm in sorting the dependencies. Good call.
