### ISSUE TITLE
build fails with Xcode 14 beta 2

### ISSUE THREAD

**Issue by jessryaan** [Carthage/Carthage#3016]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`: Xcode 12.0 Build version 12A6163b
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
github "SnapKit/SnapKit"
github "ph4r05/MBProgressHUD" ~> 1.1.1
github "onevcat/Kingfisher"
github "Alamofire/Alamofire"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 6.28.1
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json" == 6.28.1
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json" == 6.28.1
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionBinary.json" == 6.28.1
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionTextModelBinary.json" == 6.28.1
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json" == 6.28.1
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json" == 6.28.1

**Carthage Output**
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/jryan/Documents/lead/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme Alamofire\ iOS -configuration Release -derivedDataPath /Users/jryan/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6163b/Alamofire/5.2.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/k6/j798zchs4n1_njk8j0n4w6xr0000gp/T/Alamofire SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/jryan/Documents/lead/Carthage/Checkouts/Alamofire)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/k6/j798zchs4n1_njk8j0n4w6xr0000gp/T/carthage-xcodebuild.o2K0QO.log

**Actual outcome**
Carthage did not update

**Expected outcome**
Carthage should update

CONTEXT:
While working in Xcode 14 beta 2 SnapKit gives the error (Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler). so inorder an attempt to fix this Carthage needs to be updated but as stated above it fails.

**Comment by tmspzz** [comment]
> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/k6/j798zchs4n1_njk8j0n4w6xr0000gp/T/carthage-xcodebuild.o2K0QO.log

**Comment by nikolaitarasov** [comment]
I got the same problem in Carthage 0.35.0 as well.
Error: Failed to build module 'MMDB' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.22.4 clang-1200.0.25.1)'

**Comment by nikolaitarasov** [comment]
Can you please take a look into this issue? As it is blocking us from compiling the code in Xcode 12 beta.

**Comment by digas** [comment]
First to clarify Xcode is now on Xcode 12 beta 3 (not 14 , iOS is Beta 14 ). 
The error you see i'm having it too and is not fault of Carthage (which is a management tool for cocoapods) but your problem is with some cocoapod , and in this case like me it is Alamofire 5.2.2 , which is not being able to compile
Probably only when Almofire 5.3.0 comes out it will work .
BTW have you check in side you project folder , in a terminal :

Some things you should check:
   you should have a file called Cartfile with lines like this:
   github "Alamofire/Alamofire" 
   ....
If so and you installed Carthage via brew:
  brew update && brew upgrade  (at this moment you should end on version 0.35.0 )
Then 
carthage update --platform iOS (which will update the build of your cocoapods to the iOS platform to the versions mentions on the Cartfile or if no version mention there to the latest)

At the end i'm stuck too with Almofire but i'm aware that this is Xcode BETA , and i'm just testing .

**Comment by tmspzz** [comment]
There is a pinned issue with regards to Xcode 12 beta. This could well be related, please check the issue at the top of the issues tab.

However, any failure compiler is not Carthage's fault. Carthage is not a compiler, it just uses your currently selected version of Xcode. It is the responsibility of the maintainers to update library code to be compatible with the latest swift compiler.

**Comment by digas** [comment]
In both cocoapods i used i found that . 
boths  recommend some other repos as a workaround :
github "tattn/Alamofire" "hotfix-xcode12"
github "tattn/SwiftyJSON" "hotfix-xcode12"

I was finally able to build my project
