### ISSUE TITLE
Support bearer tokens for Azure

### ISSUE THREAD

**Issue by mcharland-ims** [Carthage/Carthage#3018]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.35.0 
* `xcodebuild -version`: Xcode 11.6 Build version 11E708
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
git "https://company.visualstudio.com/DefaultCollection/AMS_SDK/_git/iOS_Toomba" "master"
```

**Carthage Output**
```
*** Checking out iOS_Toomba at "abc95257fb46c117b837bc7160fc4c"
*** Cloning iOS_Toomba
A shell task (/usr/bin/env git clone --bare --quiet https://company.visualstudio.com/DefaultCollection/AMS_SDK/_git/iOS_Toomba /Users/runner/Library/Caches/org.carthage.CarthageKit/dependencies/iOS_Toomba) failed with exit code 128:
fatal: could not read Username for 'https://company.visualstudio.com': terminal prompts disabled

```

**Actual outcome**
Azure uses bearer tokens and I can't figure out a way to pass that into a Carthage command to build.
I had to add ```git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" clone https://company.visualstudio.com/DefaultCollection/AMS_SDK/_git/iOS_Toomba $(projectDir)/Carthage/Checkouts/iOS_Toomba ```

**Expected outcome**
It should be possible to pass in the bearer token to Carthage, so iOS_Toomba can build.

**Comment by adoblas** [comment]
Is there any response (out of this issue) regarding this topic?? I'm facing the same problem @mcharland-ims

**Comment by ikesyo** [comment]
https://github.com/Carthage/Carthage/issues/1456#issuecomment-374201635 would be a help.
