### ISSUE TITLE
I think you  start  from one,no zero. how to create cart file ,such so the command of  pod init.    cart file name is Carthage Or cartfile？

### ISSUE THREAD

**Issue by huicang800** [Carthage/Carthage#3026]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`:
* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```

**Actual outcome**
Carthage did or did not ...

**Expected outcome**
Carthage should ...

**Comment by huicang800** [comment]
touch cartfile

**Comment by tmspzz** [comment]
The filename is `Cartfile` as described in the documentation https://github.com/Carthage/Carthage#getting-started
