### ISSUE TITLE
Dependency "..." has no shared framework schemes

### ISSUE THREAD

**Issue by philips77** [Carthage/Carthage#3027]
* carthage install method: [ ] .pkg, [X ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.35.0
* `xcodebuild -version`: Xcode 11.6 Build version 11E708
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`?  No
* Are you using `--new-resolver`?  No

**Cartfile**
Not included, as no dependencies are required.

**Carthage Output**
```
*** Skipped building CoreBluetoothMock due to the error:
Dependency "CoreBluetoothMock" has no shared framework schemes
```

**Actual outcome**
I'm trying to share https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock on Carthage, but still getting the above error while doing `carthage build --no-skip-current` from the project directory.

![image](https://user-images.githubusercontent.com/6576580/89187280-5cb26b80-d59d-11ea-8052-e1fad64283b1.png)

When I created a dummy project and configured `Cartfile` as:
```
github "https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock"
```
I got 
```
*** No Cartfile.resolved found, updating dependencies
*** Cloning IOS-CoreBluetooth-Mock
*** Checking out IOS-CoreBluetooth-Mock at "0.8.1"
*** xcodebuild output can be found in /var/folders/0b/rjytdgdx7fv8jzyh_5bdbykc0000gn/T/carthage-xcodebuild.UUlwYT.log
*** Skipped building IOS-CoreBluetooth-Mock due to the error:
Dependency "IOS-CoreBluetooth-Mock" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/issues/new
```

**Expected outcome**
I have shared the project in Xcode. It should build, according to my knowledge. There are no dependencies.

Can you spot what I'm missing? Thank you.

**Comment by philips77** [comment]
Ok, I see a difference. My target is a static library, not a framework type of target.

**Comment by tmspzz** [comment]
Carthage does not support static libraries. It supports dynamic & static __Frameworks__

**Comment by philips77** [comment]
My solution, if someone has similar issue. 

My project supports both CocoaPods and Carthage (since now). The library is included as development pod in Pods project. I have modified my *Podfile* to include `use_frameworks!` and did `pod update`, which regenerated the project to have framework instead of a static library. Here's the commit: https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/commit/fd9c04ef25f5d2344440c1aa8d6b628de32aee18
With that completed, the command `carthage build --no-skip-current` started building correctly.
