### ISSUE TITLE
Dependency "project" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by panncherry** [Carthage/Carthage#3028]
* carthage install method: [x ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.35.0 
* `xcodebuild -version`: Xcode 11.6
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No

**Cartfile**
```
github "SnapKit/SnapKit" ~> 4.0
github "Alamofire/Alamofire" "5.0.0-rc.2"
github "SwiftyJSON/SwiftyJSON" ~> 4.0
github "JonasGessner/JGProgressHUD"
github "realm/realm-cocoa"
github "Square/Valet"
github "onevcat/Kingfisher" ~> 5.0
github "Instagram/IGListKit" ~> 3.4.0
github "Skyscanner/SkyFloatingLabelTextField"
binary "https://raw.githubusercontent.com/plaid/plaid-link-ios/master/LinkKit.json"
github "pusher/push-notifications-swift"
github "hackiftekhar/IQKeyboardManager"
github "segmentio/analytics-ios" "master"
github "chronotruck/FlagPhoneNumber"
```

**Carthage Output**
```
carthage bootstrap --platform iOS
```

**Actual outcome**
```
#!/bin/bash --login -eo pipefail
carthage build --archive --verbose --cache-builds --platform iOS --project-directory .

Please update to the latest Carthage version: 0.35.0. You currently are on 0.34.0
*** Valid cache found for Alamofire, skipping build
*** Valid cache found for analytics-ios, skipping build
*** Valid cache found for FlagPhoneNumber, skipping build
*** Valid cache found for IGListKit, skipping build
*** Valid cache found for IQKeyboardManager, skipping build
*** Valid cache found for JGProgressHUD, skipping build
*** Valid cache found for Kingfisher, skipping build
*** Valid cache found for LinkKit, skipping build
*** Valid cache found for push-notifications-swift, skipping build
*** Valid cache found for realm-cocoa, skipping build
*** Valid cache found for SkyFloatingLabelTextField, skipping build
*** Valid cache found for SnapKit, skipping build
*** Valid cache found for SwiftyJSON, skipping build
*** Valid cache found for Valet, skipping build
*** Skipped building project due to the error:
Dependency "project" has no shared framework schemes for any of the platforms: iOS
Dependency "project" has no shared framework schemes

Exited with code exit status 1
CircleCI received exit code 1
```
**Expected outcome**
In XCode -> Product -> Scheme -> checked Shared.
Carthage should not produce the following error since I do not have a dependency "project" at all.

I used xcodebuild -scheme project.framework -project XYZ.xcodeproj/ build
The project named "XYZ" does not contain a scheme named "project.framework". The "-list" option can be used to find the names of the schemes in the project.

```
*** Skipped building project due to the error:
Dependency "project" has no shared framework schemes for any of the platforms: iOS
Dependency "project" has no shared framework schemes
```

**Comment by tmspzz** [comment]
You're staring you're using `bootstrap` but in your script there you're using `build --archive` 

Which one is it?

**Comment by tmspzz** [comment]
I'm not sure what you're trying to do here. 

You say you don't have `project.framework` but you're mentioning a build command that reference a project.xcodeproj?

**Comment by panncherry** [comment]
> You're staring you're using `bootstrap` but in your script there you're using `build --archive`
> 
> Which one is it?

Sorry for the confusion. I did carthage bootstrap --platform iOS before the archive step.

**Comment by panncherry** [comment]
> I'm not sure what you're trying to do here.
> 
> You say you don't have `project.framework` but you're mentioning a build command that reference a project.xcodeproj?

That's right. That's what it got me confused. I do not have a framework named "project" at all and it is trying to build and gave me the following error: 

```
*** Skipped building project due to the error:
Dependency "project" has no shared framework schemes for any of the platforms: iOS
Dependency "project" has no shared framework schemes
```
