### ISSUE TITLE
Build fails when specifying the iOS simulator target with -destination

### ISSUE THREAD

**Issue by otri** [Carthage/Carthage#3030]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`:
 /usr/local/bin/carthage

* `carthage version`:
0.35.0

* `xcodebuild -version`: 
Xcode 11.6
Build version 11E708

* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 

carthage bootstrap --use-ssh --platform ios

**Cartfile**
```
<confidential>
```

**Carthage Output**
```
*** Building scheme "CMMeshKit-iOS" in CMMeshKit.xcodeproj
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -project /Users/otri/Projects/xxx/xxx/Frameworks/Carthage/Checkouts/xxx/xxx.xcodeproj -scheme xxx-iOS -configuration Release -derivedDataPath /Users/otri/Library/Caches/org.carthage.CarthageKit/DerivedData/11.6_11E708/xxx/v1.9.0 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=55BCF8FD-0AE5-4792-8BCE-5D6E3E264E78 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/otri/Projects/xxx/xxx/Frameworks/Carthage/Checkouts/xxx)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/j2/t4_653ld1mn78dljdkp8ypyc0000gn/T/carthage-xcodebuild.S9NaYR.log
```

**Actual outcome**
Carthage is specifying these parameters, `-sdk iphonesimulator -destination platform=iOS\ Simulator,id=55BCF8FD-0AE5-4792-8BCE-5D6E3E264E78`, which can cause compiler failure.

```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:55BCF8FD-0AE5-4792-8BCE-5D6E3E264E78 }

	Available destinations for the "GLTF" scheme:
		{ platform:macOS, arch:x86_64, id:44D98490-193A-5670-90B0-63B797CC6300 }
		{ platform:iOS Simulator, id:17B73EE6-C463-4CC9-BFA0-786CF0F121DF, OS:13.6, name:iPad Pro (12.9-inch) (2nd generation) }
		{ platform:iOS Simulator, id:0F871F98-66BA-4EDA-B6A8-F653206588A4, OS:13.6, name:iPad Pro (12.9-inch) (4th generation) }
		{ platform:iOS Simulator, id:62AA4002-6762-4CFE-A66A-AB30E0E6BA55, OS:13.6, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:028C8268-C536-4AC0-ACD0-59207CFE2774, OS:13.6, name:iPhone 11 Pro Max }

	Ineligible destinations for the "GLTF" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
		{ platform:iOS, id:00008027-001418AC1106802E, name:OTriDAR, error:OTriDAR is not available. You can see OTriDAR’s console log and other details in the Devices window. }
```

Reducing the above two parameters to only `-sdk iphonesimulator` works to complete the build.

**Expected outcome**
Carthage should build successfully.

**Comment by tmspzz** [comment]
I don't think this is a workable solution. I advice you to clean your simulators instead.

**Comment by inamiy** [comment]
cf. https://twitter.com/inamiy/status/1363086974328872961

FYI if anyone faces with iOS simulator destination issue while `carthage build`, **try deleting it from Xcode IDE**:

<img width="1018" src="https://user-images.githubusercontent.com/138476/108593961-41347400-73ba-11eb-96d8-5a583ef2d000.png">

Note that **`rm -rf ~/Library/Developer/CoreSimulator/Devices/*` doesn't work** as Xcode internally keeps the cache somewhere.
