### ISSUE TITLE
Add dependency in Development pod via Carthage 

### ISSUE THREAD

**Issue by GOKUXGOD** [Carthage/Carthage#3036]
* carthage install method:  homebrew
* `which carthage`:
* `carthage version`: 0.35.0
* `xcodebuild -version`: xcode 11.6
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?  no 
* Are you using `--cache-builds`?  no 
* Are you using `--new-resolver`?  no

**Cartfile**
```
<YOUR CARTFILE>
github "Alamofire/Alamofire" ~> 5.2

**Carthage Output**
```
<OUTPUT>
Building scheme "Alamofire iOS" in Alamofire.xcworkspac

**Actual outcome**
Build successful

**Expected outcome**
Build successful

I have a codebase which is distributed via pod 
Suppose a Network Pod, as of now its podSpec has Alamofire as a dependency,

Now I want to integrate Alamofire via Carthage in my Network pod 
so I have removed Alamofire pod by removing Alamofire from Network Pod's podspec 
and run pod install

Next I have added Cartfile and its content are just plain:
github "Alamofire/Alamofire" ~> 5.2

I have run Carthage update --platform iOS
Carthage successfully produced framework in Build/iOS folder

Now trying to add Alamofire via Carthage followed all steps:

https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

I have added frameworks search path:
$(SRCROOT)/Carthage/Build/iOS
 
But when I import Alamofire in my Dev pod it triggers error :
No such module 'Alamofire'

Please help or suggest that what I am doing is right or this is completely useless 

As this is just a beginning for a particular task in which I have to give both CocoaPods and Carthage support to all my dev pods

**Comment by zmian** [comment]
Try using pods script to expose the frameworks to pods. 

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == "<FRAMEWORK_NAME>" then
                # Exposing Carthage frameworks `Vendor` to pods 
                config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)', '${PODS_ROOT}/../Vendor']
            end
        end
    end
end
```

Replace `'${PODS_ROOT}/../Vendor'` with location of your frameworks directory.
