### ISSUE TITLE
An SSL error occurred and a secure connection to the server cannot be made

### ISSUE THREAD

**Issue by dalu93** [Carthage/Carthage#3037]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`:  0.35.0
* `xcodebuild -version`: Xcode 11.6 (11E708)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No

**Cartfile**
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
```

**Carthage Output**
```
*** xcodebuild output can be found in /var/folders/84/6tqqcb_x0pq34rt1q0mmfc1w0000gq/T/carthage-xcodebuild.MLs6Ap.log
*** No cache found for FirebaseAnalyticsBinary, building with all downstream dependencies
*** Downloading binary-only framework FirebaseAnalyticsBinary at "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
Failed to read file or folder at /dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json: Error Domain=Result.AnyError Code=1 "An SSL error has occurred and a secure connection to the server cannot be made."
```

**Actual outcome**
Carthage fails because of failed SSL handshake

**Expected outcome**
Carthage should succeed?

## Additional info

I'm running Carthage under proxy, but this specific domain certificate chain is not being rewritten (it keeps the original GlobalSign CA rather than my self signed one). Some of my Mac machines can download the binary just fine.
I believe that some of the Macs are not trusting this CA and I wonder what is the path of the `cacert` Carthage looks for. I tried to trust the CA in:

- /etc/ssl
- /private/etc/ssl (OpenSSL)
- Through `Keychain Access` application, by importing the certificates in the `System` keychain.

None of them worked so far. On the same machines where the error occurs, downloading the json file through cURL works using the `curl https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json --verbose` command

**Comment by tmspzz** [comment]
Carthage doesn't look for any cacert itself, it's all done under the hood by a plain URLSession
