### ISSUE TITLE
Cannot find Carthage.framework when using alternate homebrew prefix

### ISSUE THREAD

**Issue by jkubicek** [Carthage/Carthage#304]
Our office uses an alternative Homebrew directory, not `/usr/local/`. Carthage.framework is installed into `/opts/twitter/Frameworks/` and cannot be found by the Carthage command line tool. Symlinking Carthage.framework into the correct place isn't sufficient, as the carthage tool isn't able to find any of the dependent libraries. 

For enhanced search results, here is the error when trying to run `/usr/local/bin/carthage`

    dyld: Library not loaded: @rpath/CarthageKit.framework/CarthageKit
      Referenced from: /usr/local/bin/carthage
      Reason: image not found

**Comment by robrix** [comment]
Why is `carthage` itself not also in `/opts`…?

**Comment by jkubicek** [comment]
Good question. I suppose that's a remnant of me installing Carthage via the Xcode project. Removing the `/usr/local/bin` Carthage and and referencing the correct `/opts` Carthage fixes the issue. Thanks!
