### ISSUE TITLE
--platform macOS is ignored on DTK

### ISSUE THREAD

**Issue by silverhammermba** [Carthage/Carthage#3041]
I'm running Carthage on a Developer Transition Kit. I know this isn't supported yet but I'm trying to work through the kinks so I'm reporting this to keep track of it.

* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.35.0
* `xcodebuild -version`: Xcode 12.0 Build version 12A8158a
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

Running this command
```
git clone https://github.com/instacart/TrueTime.swift.git && \
cd TrueTime.swift && git submodule update --init && \
carthage bootstrap --platform macOS
```

**Actual outcome**
After cloning:
```
*** Checking out Nimble at "v8.0.1"
*** Checking out Quick at "v2.1.0"
*** Checking out SwiftCheck at "0.12.0"
*** xcodebuild output can be found in /var/folders/vj/9jzz5m017x143xpc1ltdnj5h0000gn/T/carthage-xcodebuild.YvO3iK.log
*** Building scheme "Nimble-tvOS" in Nimble.xcodeproj
```
This is blocking because the DTK can only build macOS targets at this time. The tvOS build fails.

**Expected outcome**
On my normal Mac with Xcode 12.0 Build version 12A8189n
```
*** Checking out Nimble at "v8.0.1"
*** Checking out Quick at "v2.1.0"
*** Checking out SwiftCheck at "0.12.0"
*** xcodebuild output can be found in /var/folders/6z/cs5xj2kn5gj3_8ddxkrzq3k00000gq/T/carthage-xcodebuild.NyGRO4.log
*** Building scheme "Nimble-macOS" in Nimble.xcodeproj
```

**Comment by silverhammermba** [comment]
Actually this may not be a carthage issue. I cloned Nimble directly, and on my normal mac

    $ xcrun xcodebuild -project Nimble.xcodeproj -scheme Nimble-tvOS -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -showBuildSettings -skipUnavailableActions | grep SUPPORTED_PLATFORMS
    SUPPORTED_PLATFORMS = appletvos appletvsimulator

but on the DTK

    SUPPORTED_PLATFORMS = macos

**Comment by silverhammermba** [comment]
I think the issue here is that the tvOS SDK is entirely missing on DTK, so the build settings look kinda weird for it. Some of them look valid, some are clearly copied from macOS. This seems to be the relevant section for macOS that is missing for tvOS

```
SDK_DIR = /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
SDK_DIR_macosx11_0 = /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
SDK_NAME = macosx11.0
SDK_NAMES = macosx11.0
SDK_PRODUCT_BUILD_VERSION = 20A5299v
SDK_VERSION = 11.0
SDK_VERSION_ACTUAL = 110000
SDK_VERSION_MAJOR = 110000
SDK_VERSION_MINOR = 000
```

None of these are defined when you try to build a tvOS target.

I could see Carthage handling this case; basically use some of these vars to determines if an SDK is actually available before trying to build it. Or I could it seen not being realistic. Probably all real Xcode versions will support all SDKs?

**Comment by tmspzz** [comment]
If this is a problem with missing SDK I think it's more appropriate just to throw and error and stop.

**Comment by silverhammermba** [comment]
@tmspzz why throw an error for the missing tvOS SDK if `--platform macOS` is specified?

**Comment by tmspzz** [comment]
I'm confused about what you're trying to do.

> This is blocking because the DTK can only build macOS targets at this time. The tvOS build fails.
> I think the issue here is that the tvOS SDK is entirely missing on DTK

This is why I suggested throwing an error and stopping.

Anyways I don't think this scenario is realistic in any stable Xcode release.

**Comment by silverhammermba** [comment]
When Carthage queries the targets with Xcode to determine which are macOS targets, Xcode cannot correctly determine the supported platforms for tvOS (because the SDK is missing), and apparently it falls back to saying the supported platform is macOS. So if you were trying to only build macOS targets, the tvOS one will also be included by Carthage.

This would not be an issue if the tvOS build could succeed, because at least then I would be unblocked, but it fails (no SDK) so Carthage gives up and does not try to finish the macOS build, which is what I actually want.

**Comment by tmspzz** [comment]
>  Xcode cannot correctly determine the supported platforms for tvOS (because the SDK is missing), and apparently it falls back to saying the supported platform is macOS.

If we can catch that, I'm up for a PR
