### ISSUE TITLE
Dependencies in a Carthage framework not on root level are not installed

### ISSUE THREAD

**Issue by breferrari** [Carthage/Carthage#3042]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: 
* `carthage version`: 0.35.0
* `xcodebuild -version`: Xcode 11.5
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "stripe/stripe-ios"
```

**Actual outcome**
This is a project for a Carthage framework which has third party dependencies provided through Carthage. In this case, Stripe SDK. It is also present on a monorepo with other platforms. The project itself is not on root level, but in a `iOS/source` folder.
Carthage builds and works perfectly locally to create the framework. I also have CI working which runs just fine and completes the build.

When creating a test project to point to my framework, it finds the project and proceeds to build, but completely ignores the Cartfile and doesn't fetch the dependencies. If fails to build because it doesn't have Stripe SDK.

I've tried to move the project to a exclusive repo, on root level, and it works just fine.
So it seems the issue relies on having it in a not root level folder situation. Carthage seems to be ignoring or not finding the present Carfile.

**Carthage Output**
```
*** Fetching paykit
*** Checking out paykit at "183bab29e6d4d2d4a9327a3601cd3ae0a48c0309"
*** xcodebuild output can be found in /var/folders/bn/f5s27zk576q5jc25zymjm5l400h8sk/T/carthage-xcodebuild.am8MKc.log
*** Building scheme "PayKit" in PayKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/brenno/dev/PayKitCarthageTest/Carthage/Checkouts/paykit/ios/source/PayKit.xcodeproj -scheme PayKit -configuration Release -derivedDataPath /Users/brenno/Library/Caches/org.carthage.CarthageKit/DerivedData/11.7_11E801a/paykit/183bab29e6d4d2d4a9327a3601cd3ae0a48c0309 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/bn/f5s27zk576q5jc25zymjm5l400h8sk/T/paykit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/brenno/dev/PayKitCarthageTest/Carthage/Checkouts/paykit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/bn/f5s27zk576q5jc25zymjm5l400h8sk/T/carthage-xcodebuild.am8MKc.log
```

**xcodebuild log**
```
/Users/brenno/dev/PayKitCarthageTest/Carthage/Checkouts/paykit/ios/source/PayKit/SourceCode/PaymentProviders/Stripe/StripeSDKWrapper.swift:1:8: error: no such module 'Stripe'
import Stripe
       ^

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

```

**Expected outcome**
Carthage should find the Cartfile together with the xcodeproj file, fetch and build the dependencies before trying to build the framework.

Like so:
```
*** Fetching stripe-ios
*** Checking out paykit-ios at "7d4f4ee8053746b432c540ed66988c9981d3b0e0"
*** Checking out stripe-ios at "v19.4.0"
*** xcodebuild output can be found in /var/folders/bn/f5s27zk576q5jc25zymjm5l400h8sk/T/carthage-xcodebuild.kb5l7P.log
*** Downloading stripe-ios.framework binary at "Version 19.4.0"
*** Building scheme "PayKit" in PayKit.xcodeproj
```

**Comment by tmspzz** [comment]
I'm not sure I understand your setup. The Cartfile for dependencies must be at root level, but your "starting" cart file can be anywhere.

**Comment by breferrari** [comment]
The project and Cartfile/Cartfile.resolved are not at root level, but instead inside a `iOS/source` folder.

When importing my framework through Carthage, it only finds the `xcodeproj` and the framework scheme, but ignores the Cartfile setup altogether, resulting in build failure.
I've also tried moving Carthage to root level while keeping the project into `iOS/source` folder, but the problem still occurs. Carthage ignore the presence of the Cartfile and doesn't build the needed dependencies.

**Comment by tmspzz** [comment]
Yes

**Comment by breferrari** [comment]
> What do you mean by "importing"?
> No you can run point it to where the staring project file is, have you tried `--project-directory`? Both the project and the Cartfile, Cartfile.resolved must be in the same directory tho.

I don't know if I made it clear enough, but the situation is that I'm creating a framework that is supporting Carthage. The framework is on a repository shared with other platforms, so it's not on the root level, but inside a folder.
It has one another Carthage dependency called Stripe and it is working just fine. Carthage runs, gets the dependency, the dependency is imported and used. I also have a CI which runs everything just fine.

The issue I'm having is consuming my framework, which is the end product. Having a project set up with my framework pointed as a dependency in the Cartfile.
So, there's no `--project-directory` command, it's `carthage update/bootstrap`, the situation is the final user trying to consume it.

I know Carthage looks for the root-most folder which contains an `xcodeproj` and a shared framework scheme. This *is* working.
What is not is that it's not looking or finding the `Cartfile` which specifies the dependencies that this framework consumes, leading to build failure. This is the issue.

What I'm trying to sort out is: is it a bug or am I doing something wrong?

**Comment by tmspzz** [comment]
Ok, now I understand.

Cartfile Carfile.resolved and .xcodeproj or workspace must be at the same level I believe but not necessarily at the root directory.

**Comment by tmspzz** [comment]
So after some investigation, I believe that as I mentioned [here](https://github.com/Carthage/Carthage/issues/3042#issuecomment-689699663) dependencies must have Cartifle, Cartfile.resolved and project file at root level. 

Relevant bit is here I think: https://github.com/Carthage/Carthage/blob/0143edc190db9689b594f4515178f1935989ca12/Source/CarthageKit/Project.swift#L340-L383

**Comment by breferrari** [comment]
Thanks for taking the time to investigate this for me @tmspzz.
I'll move the solution to a stand-alone repo as this fix the issue I have, as moving the files to the root level would not make sense in the mono-repo our team have.
