### ISSUE TITLE
CarthageKitVersion is incorrect 0.35.0 => 0.35.1 

### ISSUE THREAD

**Issue by mozeryansky** [Carthage/Carthage#3048]
```
$ brew list carthage             
/usr/local/Cellar/carthage/0.35.1/bin/carthage
/usr/local/Cellar/carthage/0.35.1/etc/bash_completion.d/carthage
/usr/local/Cellar/carthage/0.35.1/share/fish/vendor_completions.d/carthage.fish
/usr/local/Cellar/carthage/0.35.1/share/zsh/site-functions/_carthage
$ /usr/local/bin/carthage version
Please update to the latest Carthage version: 0.35.1. You currently are on 0.35.0
0.35.0
```

https://github.com/Carthage/Carthage/issues/2964

**Comment by aeberbach** [comment]
same here - tried deleting the bottle from cache, uninstalling and reinstalling

adam@vogel lfs % rm /Users/adam/Library/Caches/Homebrew/downloads/82b0239287ff3c4217fafc6a5ba3ebbfd6dcfd2dbf5c1ed76a13322d1a5f4389--carthage-0.35.1.catalina.bottle.tar.gz
adam@vogel lfs % brew uninstall carthage
Uninstalling /usr/local/Cellar/carthage/0.35.1... (8 files, 7.6MB)
adam@vogel lfs % brew reinstall carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.35.1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/ecbd3a41f0f0852c2733ce0cff6d8fac21267d742a9fc25b5096bec67f3115a5?response
######################################################################## 100.0%
==> Reinstalling carthage
==> Pouring carthage-0.35.1.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.35.1: 8 files, 7.6MB
adam@vogel lfs % carthage
Please update to the latest Carthage version: 0.35.1. You currently are on 0.35.0

**Comment by mozeryansky** [comment]
@aeberbach It's just a manual step to change the file that can easily be missed. You can see master has the 0.35.0 version hardcoded: https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/CarthageKitVersion.swift

**Comment by tmspzz** [comment]
My bad. Don't know how this happened. Will release asap.

**Comment by tmspzz** [comment]
https://github.com/Carthage/Carthage/releases/tag/0.36.0
