### ISSUE TITLE
Carthage build for UnrarKit failing with Xcode 12 while Xcode build succeeds

### ISSUE THREAD

**Issue by abbeycode** [Carthage/Carthage#3063]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.36.0
* `xcodebuild -version`: Xcode 12.0.1, Build version 12A7300
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
git clone https://github.com/abbeycode/UnrarKit.git --branch xcode12 UnrarKit-Xcode12
cd UnrarKit-Xcode12
carthage build --no-skip-current
```

**Carthage Output**
```
*** xcodebuild output can be found in /var/folders/rq/5_xw4bcd7n5fbxhv_4pffj4h0000gp/T/carthage-xcodebuild.9U6r4A.log
*** Building scheme "UnrarKit" in UnrarKit.xcworkspace
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/dfrankel/Library/Developer/Xcode/DerivedData/UnrarKit-gdigivukwtpfesgjkffcsszxuwoq/Build/Intermediates.noindex/ArchiveIntermediates/UnrarKit/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UnrarKit.framework/UnrarKit /Users/dfrankel/Library/Developer/Xcode/DerivedData/UnrarKit-gdigivukwtpfesgjkffcsszxuwoq/Build/Products/Release-iphonesimulator/UnrarKit.framework/UnrarKit -output /Users/dfrankel/Source\ Code/UnrarKit-Xcode12/Carthage/Build/iOS/UnrarKit.framework/UnrarKit

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/rq/5_xw4bcd7n5fbxhv_4pffj4h0000gp/T/carthage-xcodebuild.9U6r4A.log
```

[carthage-xcodebuild.9U6r4A.log](https://github.com/Carthage/Carthage/files/5315713/carthage-xcodebuild.ZV1vfR.log)

**Actual outcome**
Carthage returned unsuccessfully, including when run from Travis CI. It indicates a likely error to build, but the logs it produces show no error, and a manual run of xcodebuild using the same scheme and workspace completes successfully.

**Expected outcome**
Build the project successfully, since it builds in Xcode successfully.

**Comment by tmspzz** [comment]
same as https://github.com/Carthage/Carthage/issues/3019
