### ISSUE TITLE
Incorrect path for virtual filesystem overlay file

### ISSUE THREAD

**Issue by cbestow** [Carthage/Carthage#3068]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.36.0
* `xcodebuild -version`: Xcode 12.0 Build version 12A7209
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Tried with and without
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "SwiftyJSON/SwiftyJSON" == 5.0.0
```

**Carthage Output**
```
*** Cloning SwiftyJSON
*** Checking out SwiftyJSON at "5.0.0"
*** xcodebuild output can be found in /var/folders/jp/tpm38fkx72qg1w51b8ly6gjr0000gp/T/carthage-xcodebuild.eyXPwS.log
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace

```

**Context**

To give some background, we (my company) have a large codebase that is split across two Xcode projects. One is and SDK project that builds a framework. The other project is an app that uses the SDK framework. Both projects use Carthage for dependencies. The client project currently uses Carthage to get the latest SDK, but we want to change this and use a workspace instead.

However, to prepare for this migration, I created a sample workspace to work out some of the difficulties. I took these steps:

- Created a new workspace.
- Created a new TestFramework project and added to the workspace.
- Created a new TestApp project and added to the workspace.
- Added the above Cartfile to the framework project.
    - I chose SwiftyJSON as it is a relatively small dependency that we currently use in the SDK.
- Got the app running. The framework is using SwiftyJSON classes and the app is using framework classes.

**Actual outcome**

The issue I see is when I try to use LLDB (in the app project). I see an error that looks like this:

```
error: virtual filesystem overlay file '/Users/[REDACTED]/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/SwiftyJSON/5.0.0/Build/Intermediates.noindex/SwiftyJSON.build/Release-iphonesimulator/SwiftyJSON iOS.build/all-product-headers.yaml' not found
```

I have redacted my colleague's username. If I search change that path to use my username I can locate the file.

I have seen references to `/Users/[REDACTED]/` in the bcsymbolmap files.

**Expected outcome**

I expect the paths to be correct and include my username instead of a colleague's username.

**Comment by tmspzz** [comment]
A quick search on stackoverflow brings up a bunch of results for this error. I don't believe this is relate to carthage.

**Comment by tmspzz** [comment]
https://bugs.swift.org/browse/SR-12783?focusedCommentId=56548&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-56548

**Comment by tmspzz** [comment]
https://steipete.com/posts/couldnt-irgen-expression/

**Comment by cbestow** [comment]
Ok, thank you for the pointers.

I was thinking there may be some cache on Carthage's part that I was missing (other than ~/Library/Caches/org.carthage.CarthageKit). But doesn't seem to be the case.

I will keep on reading about this issue.

**Comment by hien352911** [comment]
i have a same problem. I have fixed it.
Because I use clean my mac. It remove all folder carthage's cache. 
I run carthage update to generate folder cache.
It is ok
