### ISSUE TITLE
Supporting single scheme and multi platform project

### ISSUE THREAD

**Issue by norio-nomura** [Carthage/Carthage#307]
Will Carthage support single scheme and multi platform configuration like Alamofire/Alamofire#326?

For OS X, iOS and iOS Simulator build command lines are following:
```sh
xcodebuild -project Alamofire.xcodeproj -scheme Alamofire build -sdk macosx …
xcodebuild -project Alamofire.xcodeproj -scheme Alamofire build -sdk iphoneos …
xcodebuild -project Alamofire.xcodeproj -scheme Alamofire build -sdk iphonesimulator …
```

"SDKROOT = macosx;" will be used from Alamofire.xcodeproj if -sdk option is missing.

There will be,
- Current project is single scheme and multi platform, calling carthage inside run_script.
- Dependent to single scheme and multi platform projects.
- Both of them

it maybe related to #302?

**Comment by jspahrsummers** [comment]
Sorry, but I don't think we want to support this. The correct way to support multiple platforms is to create separate targets for each, not reuse the same target with different settings.

I'd recommend bringing this feedback to the Alamofire project instead.

**Comment by robrix** [comment]
I was initially intrigued, but ended up agreeing with @jspahrsummers. Unless/until this is officially supported by Apple, I’d prefer to avoid it.

**Comment by norio-nomura** [comment]
Thank you.
I will feedback to the Alamofire project and keep my projects to using separate targets.

**Comment by swizzlr** [comment]
If I'm not mistaken, Apple has done this in the past, with a shared target and different schemes? I think refusing to support this could be detrimental to Carthage's flexibility of "taking any project."

**Comment by jspahrsummers** [comment]
@swizzlr See also #340.

> If I'm not mistaken, Apple has done this in the past, with a shared target and different schemes?

I'd love to see that, if you could dig it up.

> I think refusing to support this could be detrimental to Carthage's flexibility of "taking any project."

That's not really the goal, nor has it been. Even today, there are some (small) [requirements](https://github.com/Carthage/Carthage/blob/d845de500eb783acee892716ccb83d7a1657dd19/README.md#supporting-carthage-for-your-framework) that projects must meet, so we can't really say that we “take any project.”

**Comment by regexident** [comment]
>> If I'm not mistaken, Apple has done this in the past, with a shared target and different schemes?

> I'd love to see that, if you could dig it up.

The following Google search shows that the universal framework approach via xcconfigs is not entirely foreign to Apple:

    site:opensource.apple.com "SUPPORTED_PLATFORMS = macosx iphoneos"

Turns out `libsyscall`, `libdispatch`, `libc`, `libmalloc`, `liblaunch` all seem to use it. They are dylibs, not frameworks, sure, but then again Apple's frameworks hardly ever are open source, so there's no way to tell how those are built.

They might not publicly endorse it, but they certainly are using it internally.

Turns out even WebKit2 uses it:

    https://github.com/WebKit/webkit/blob/master/Source/WebKit2/Configurations/Base.xcconfig

**Comment by mdiep** [comment]
> They might not publicly endorse it, but they certainly are using it internally.

Internal use shouldn't be taken as an endorsement of any kind. Apple is a large company, and individual teams often have the freedom to do things the wrong way.

**Comment by robrix** [comment]
And if Xcode breaks those other teams’ builds, those other teams will have access to Xcode team members to fix them that we won’t have.

**Comment by jpsim** [comment]
Just chiming in here that support for multi-platform schemes in Carthage would be greatly appreciated. For large projects with lots of targets, *ahem* Realm *ahem*, deduplicating framework targets is extremely useful. [SQLite.swift](https://github.com/stephencelis/SQLite.swift) is another example of a project that makes use of multi-platform framework targets.

**Comment by jspahrsummers** [comment]
@jpsim Yep—we're tracking actually doing this in #340.

**Comment by jpsim** [comment]
Wonderful, sorry I didn't find that issue, I'll subscribe to that.
