### ISSUE TITLE
Dependency cycle detected only when use SSH

### ISSUE THREAD

**Issue by arkasas** [Carthage/Carthage#3074]
* carthage install method: [ ] .pkg, [x ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: /usr/local/bin/carthage
* `xcodebuild -version`:  Xcode 11.4.1/ 11E503a
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  no
* Are you using `--new-resolver`? no

**Cartfile**
```
git "git@repo/A"
git "git@repo/B"
git "git@repo/C"
```

**Carthage Output**
```
The dependency graph contained a cycle:
B: 
C: B, A
A: 
```

**Actual outcome**
When I use ssh to build Carthage it prints "The dependency graph contained a cycle". But when I used Carthage over HTTPS it works fine. Version of frameworks is this same.
Framework A and B is without other libraries, but framework C contains A and B. 

**Expected outcome**
Carthage should build package over ssh as well as over https.

**Comment by tmspzz** [comment]
try --new-resolver

**Comment by arkasas** [comment]
> try --new-resolver

Unfortunately, it doesn't works
