### ISSUE TITLE
Environment variable not set: ARCHS

### ISSUE THREAD

**Issue by sorinc03** [Carthage/Carthage#3077]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/Homebrew/bin/carthage
* `carthage version`: 0.36.0
* `xcodebuild -version`: Xcode 12.1 (12A7403)
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

I’m using the Xcode 12 workaround script to update my carthage dependencies and when I build in Xcode with the new dependencies, I get an error stating “Environment variables not set: ARCHS”. I’ve excluded arm64 from simulator builds but not sure how to deal with this last one. How can I set ARCHS on carthage builds?

**Comment by tmspzz** [comment]
They are part of your build settings in your project.

**Comment by sorinc03** [comment]
> They are part of your build settings in your project.

Thanks @tmspzz. I do have ARCHS and VALID_ARCHS defined in my project though, although they don’t seem to be passed forward to Carthage. The issue specifically happens at the Carthage build step rather than for my project code.

**Comment by sorinc03** [comment]
@tmspzz I got it to work now by setting ARCHS in the workaround script.

**Comment by BucekJiri** [comment]
@sorinc03 Could you share the adjusted workaround script please? I am struggling with this issue as well.

**Comment by volbap-mobomo** [comment]
What worked for me was making sure that in Build Settings > Excluded Architectures I set `arm64` **only for the iOS Simulator SDK**, and not when compiling on device.

![image](https://user-images.githubusercontent.com/32488550/106906734-39977e80-66dc-11eb-8038-46f8bb8927ab.png)

**Comment by Bruce9487** [comment]
How to solve this problem. Xcode12.2 & carthage 0.38, meet the same issue.
I try to add `arm64`, and not work.
![截圖 2021-08-03 18 23 00](https://user-images.githubusercontent.com/19691907/128000264-b6094be6-029f-45c7-9e0c-acd6578cd601.png)
