### ISSUE TITLE
iOS 8.3 beta carthage update fails

### ISSUE THREAD

**Issue by SaidSikira** [Carthage/Carthage#308]
As you probably know, Apple released iOS beta 3 with Swift 1.2 and Xcode 6.3 beta. I switched command line tools to Xcode 6.3 and the ```carthage update``` fails. I'm guessing that projects need to be converted to Swift 1.2 in order to use them, but just in case i'm sticking [xcodebuild log](https://gist.github.com/SaidSikira/bae52a0a146f264a9d71)

**Comment by sticksen** [comment]
...and I´m adding: if you don´t switch the compiler to Xcode 6.3, it says
![screen shot 2015-02-10 at 12 38 54](https://cloud.githubusercontent.com/assets/2657113/6126522/cd11d29a-b121-11e4-92ea-40df7d8950d4.png)
Module file was created by an older version of the compiler

**Comment by mdiep** [comment]
> I'm guessing that projects need to be converted to Swift 1.2 in order to use them

Yes, that's the case. Alamofire failed to build because it's not yet compatible with Swift 1.2.
