### ISSUE TITLE
Carthage skips rebuilding a cached version while Xcode wants it rebuilt

### ISSUE THREAD

**Issue by GRiMe2D** [Carthage/Carthage#3086]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: `0.36.0`
* `xcodebuild -version`: Xcode 12.1 Build version 12A7403
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No

**Cartfile**
```
github "jonreid/OCMockito"
github "Quick/Quick"
github "Quick/Nimble"
```

**Cartfile.resolved**
```
github "Quick/Nimble" "v9.0.0"
github "Quick/Quick" "v3.0.0"
github "hamcrest/OCHamcrest" "v7.1.2"
github "jonreid/OCMockito" "v5.1.3"

```

**Carthage Output**
```
*** Valid cache found for Nimble, skipping build
*** Valid cache found for OCHamcrest, skipping build
*** Valid cache found for OCMockito, skipping build
*** Valid cache found for Quick, skipping build
```

**Actual outcome**
Carthage will rebuild the `Quick` framework

**Expected outcome**
Carthage skips `Quick` framework building

**How to reproduce**
```console
$ xcversion select 11.7
$ carthage bootstrap --platform iOS --cache-builds --no-use-binaries
$ xcversion select 12.1 
$ carthage bootstrap --platform iOS --cache-builds --no-use-binaries
```

**Version file for Quick**
```json
{
  "commitish" : "v3.0.0",
  "iOS" : [
    {
      "hash" : "56f1d75e32824ed2af4f996b41bbf20353dfd7d3334ddeb56762025a669b3b9f",
      "name" : "Quick",
      "linking" : "dynamic",
      "swiftToolchainVersion" : "5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)"
    }
  ]
}
```

**Xcode 12.1 swift version**
```console
$ swift -version
Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
Target: x86_64-apple-darwin19.6.0
```

**Xcode 12.1 Project error**
Failed to build module 'Quick' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'

**Comment by GRiMe2D** [comment]
I think problem lies here https://github.com/Carthage/Carthage/blob/158dacdd5626dd00190180c5c0aec598f61a2b22/Source/CarthageKit/Xcode.swift#L147-L161

**Comment by GRiMe2D** [comment]
Also some info here https://developer.apple.com/forums/thread/660578

**Comment by elliottwilliams** [comment]
@GRiMe2D Not sure I understand the issue. Nimble and Quick ship with `BUILD_LIBRARY_FOR_DISTRIBUTION = YES`, which means that they can be imported by _more recent_ compilers than the one they were built on. OCHamcrest and OCMockito are objc-only and can be imported by any swift compiler. Carthage honors this and does not rebuild these frameworks when your swift version goes up.

I couldn't reproduce your build error in Xcode 12.2 (I don't have 12.1 installed right now). LMK if there's something I'm missing: 
[carthage-3086.zip](https://github.com/Carthage/Carthage/files/5718433/carthage-3086.zip)
