### ISSUE TITLE
Shared schemes validation failed in zsh

### ISSUE THREAD

**Issue by xHunter** [Carthage/Carthage#309]
`carthage update` in zsh always return Project '*/*' has no shared schemes.

**Comment by mdiep** [comment]
Can you share the output of `carthage version` and the contents of your `Cartfile`?

**Comment by xHunter** [comment]
I'm using `0.5.3` and my Cartifle only includes
```github "realm/realm-cocoa"```

After run `carthage update` in bash everything started to working ok, also in zsh. And I haven't been able to reproduce it. So I closed the issue and if something arise I'll reopen it.
