### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by mbondoso** [Carthage/Carthage#3090]
* carthage install method: [X] .pkg, [ ] homebrew, [ ] source
* `which carthage`:
* `carthage version`: 0.36
* `xcodebuild -version`: 12.2 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 

**Cartfile**
```
github "AzureAD/microsoft-authentication-library-for-objc" "master"
```

**Carthage Output**
```
A shell task (/usr/bin/xcrun lipo -remove x86_64 -output /var/folders/gk/yy0jdqss6q9g2cbg50vr77w00000gn/T/TemporaryItems/(A\ Document\ Being\ Saved\ By\ carthage\ 18)/carthage-lipo-q5Lvjd/MSAL.framework.dSYM/Contents/Resources/DWARF/MSAL /var/folders/gk/yy0jdqss6q9g2cbg50vr77w00000gn/T/TemporaryItems/(A\ Document\ Being\ Saved\ By\ carthage\ 18)/carthage-lipo-q5Lvjd/MSAL.framework.dSYM/Contents/Resources/DWARF/MSAL) failed with exit code 1:
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: input file (/var/folders/gk/yy0jdqss6q9g2cbg50vr77w00000gn/T/TemporaryItems/(A Document Being Saved By carthage 18)/carthage-lipo-q5Lvjd/MSAL.framework.dSYM/Contents/Resources/DWARF/MSAL) must be a fat file when the -remove option is specified
```

**Actual outcome**
Carthage did not build

**Expected outcome**
Carthage should have built

**Comment by kentwinder** [comment]
Just run this command to open TemporaryItems folder, then delete everything inside this folder
`cd ${TMPDIR}/TemporaryItems && open .`
I don't remember where I got this solution but it works, after a while you have to clean this folder if the error occurs again, or you can add this script to your run script to clear this folder automatically

**Comment by 1oo7** [comment]
@kentwinder That's the same workaround I've been using when this happens. 

However I'm not sure why this is necessary.. this never used to happen on Carthage 0.34 that I can recall. Perhaps someone could explain why this has recently become a problem?

**Comment by mbondoso** [comment]
@kentwinder and @1oo7 it does not work. after deleting everything it still does not archive successfully.

any other thoughts?

**Comment by kentwinder** [comment]
@mbondoso if you say so, then it is not related to carthage issue that I'm talking about. I think there is might be some things wrong in your build scripts. Please recheck your build phases configurations. Or you can try these first:
- Clear derived data folder
- Restart Xcode
- Restart MacOS

**Comment by mcany** [comment]
I remember, I saw a commit that triggers this error and it is reverted but not released yet. You are right this problem came with 0.36. I hope this issue will be solved with the new release. But I am not the owner/contributor of the repo so I can not be sure. This is what I saw.
