### ISSUE TITLE
Unrecognized arguments: --use-xcframeworks (carthage update --use-xcframeworks)

### ISSUE THREAD

**Issue by anatoliykant** [Carthage/Carthage#3097]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.36.0
* `xcodebuild -version`: Xcode 12.3; Build version 12C33
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no
* `macOS version`: Catalina 10.15.7

**Cartfile**
```
github "ReactiveX/RxSwift"
github "RxSwiftCommunity/RxDataSources"
github "SnapKit/SnapKit"
github "scenee/FloatingPanel"
github "pkluz/PKHUD"
github "layoutBox/PinLayout"

binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"

github "yagiz/Bagel"
```

**Carthage Output**
```
$ carthage update --use-xcframeworks
Unrecognized arguments: --use-xcframeworks
```

**Actual outcome**
`Unrecognized arguments: --use-xcframeworks`

**Expected outcome**
Frameworks have been successfully pulled into the project

**Comment by ARGAMX** [comment]
The same problem.
After update to Xcode 12.3 it refusing to link fat binaries with Error:

`Building for iOS Simulator, but the linked and embedded framework '***.framework' was built for iOS + iOS Simulator.`

**Comment by samchang8826** [comment]
I met the same problem, As 0.36.0 is out of date, I think this feature is on master only.

From source: If you’d like to run the latest development version (which may be highly unstable or incompatible), simply clone the master branch of the repository, then run make install. Requires Xcode 10.0 (Swift 4.2).

**Comment by yuconora** [comment]
> I met the same problem, As 0.36.0 is out of date, I think this feature is on master only.
> 
> From source: If you’d like to run the latest development version (which may be highly unstable or incompatible), simply clone the master branch of the repository, then run make install. Requires Xcode 10.0 (Swift 4.2).


yes, you are right, it is work well, I build it in Xcode Version 12.3 (12C33)

**Comment by 1oo7** [comment]
Someone needs to do a release with the new xcframeworks change!

**Comment by jlott1** [comment]
> I met the same problem, As 0.36.0 is out of date, I think this feature is on master only.
>
>From source: If you’d like to run the latest development version (which may be highly unstable or incompatible), simply clone >the master branch of the repository, then run make install. Requires Xcode 10.0 (Swift 4.2).

@samchang8826 Thanks for info.
Just for anyone else who was coming across this issue, after looking at the Carthage code, I realized that this still works fine:

`$ carthage update --create-xcframework`

OR

`$ carthage build --create-xcframework`

**Comment by haofanning** [comment]
still happens
