### ISSUE TITLE
Carthage does not use $HOME for Caches folder when run from macports

### ISSUE THREAD

**Issue by Janosch** [Carthage/Carthage#3101]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source, [x] macports
* `which carthage`: /opt/local/bin/carthage
* `carthage version`: 0.35.0
* `xcodebuild -version`: Xcode 12.3 (Build version 12C33)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No 
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No

**Cartfile**
This is the cartfile from [MacPass](https://github.com/MacPass/MacPass).
```
github "sparkle-project/Sparkle" ~> 1.22
github "mattt/TransformerKit" ~> 1.1.1
github "MacPass/KeePassKit" "e22b8f2e5b4f8bccdea7630318e42eeb6eec23b5" 
github "mstarke/HNHUi" ~> 4.0
```

**Carthage Output**
This is the relevant output when carthage is run from macports:
```
echo HOME=/opt/local/var/macports/build/_Users_janosch_Dev_macports-ports_security_MacPass/MacPass/work/.home
2021-01-01 11:03:38.579 carthage[39332:663446] NetworkStorageDB:_openDBReadConnections: failed to open read connection to DB @ /opt/local/var/macports/home/Library/Caches/carthage/Cache.db.  Error=14. Cause=unable to open database file
```

**Actual outcome**
Carthage did not use $HOME when trying to create the Caches folder. It uses some other path for which it has no write permission. This happens when carthage is run by the package manager [macports](https://www.macports.org/) (which runs it using its user 'macports'). Carthage completes succesful, but does not create a Cache and produces a lot of errors due to the permission conflict.

Note: Running the same cartfile directly with my own user works. In this case the Caches folder is created somewhere in my $HOME.

**Expected outcome**
Carthage should use some path below $HOME for all files it creates. No matter who runs it.

**Macports portfile**
This is how carthage is called from macports (snippet from a [portfile](https://guide.macports.org/chunked/development.html), in [TCL](https://www.tcl.tk/about/language.html)):
```
build {
  ui_msg "echo HOME=$::env(HOME)"
  system -W ${worksrcpath} "${prefix}/bin/carthage bootstrap --platform macOS \
  --cache-builds --derived-data ${worksrcpath}/DerivedData"
}
```

**Comment by tmspzz** [comment]
Thanks for reporting the issue, I'm afraid that your best chance is either investigate this yourself or use other installation methods.
