### ISSUE TITLE
How do I vendor pre-built XCFrameworks using Carthage

### ISSUE THREAD

**Issue by joesus** [Carthage/Carthage#3103]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: latest master cdc5eaa0
* `carthage version`:  unreleased
* `xcodebuild -version`: Xcode 12.3 Build version 12C33
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? NO
* Are you using `--new-resolver`? NO
* Are you using `--use-xcframeworks`? YES

**Cartfile**
```
git "https://github.com/joesus/facebook-ios-sdk.git"
```

**Carthage Output**
```
../Carthage/.build/release/carthage update --use-xcframeworks
*** Fetching facebook-ios-sdk
*** Checking out facebook-ios-sdk at "v9.0.0"
*** xcodebuild output can be found in /var/folders/83/8hn7kn6n0nn9sgg5y6k6dn180000gn/T/carthage-xcodebuild.2AjqPw.log
*** Downloading facebook-ios-sdk.framework binary at "v9.0.0"
***  Skipped installing facebook-ios-sdk.framework binary due to the error:
	"Invalid archive - Found multiple frameworks with the same unarchiving destination:
* 	file:///var/folders/83/8hn7kn6n0nn9sgg5y6k6dn180000gn/T/carthage-archive.uudUaq/Carthage/Build/FBSDKCoreKit.xcframework/ios-arm64_i386_x86_64-simulator/FBSDKCoreKit.framework/
	file:///var/folders/83/8hn7kn6n0nn9sgg5y6k6dn180000gn/T/carthage-archive.uudUaq/Carthage/Build/FBSDKCoreKit.xcframework/ios-arm64_armv7/FBSDKCoreKit.framework/
		to:
	file:///Users/joesusnick/Projects/iOS/CarthageXCFrameworkIntegration/Carthage/Build/iOS/FBSDKCoreKit.framework/
```

**Actual outcome**
I used the new command:
`carthage update --use-xcframeworks` to successfully generate a directory of XCFrameworks.

I zipped the directory as 'carthage.framework.zip' and uploaded it to a new release. 

Then ran `carthage update --use-xcframeworks`

**Expected outcome**

The README states:

> Run carthage update --use-xcframeworks. This will fetch dependencies into a Carthage/Checkouts folder and build each one or download a pre-compiled xcframework

I expected Carthage to download the prebuilt XCFrameworks.

Apologies for the noob questions. 

1. Is there a different naming convention to use for a zipped directory of prebuilt xcframeworks vs prebuilt frameworks? I'm guessing not since I tried a few variations. 😅 
2. Would it make sense to implement something like "foo.xcframework.zip" to delineate the two?

**Comment by tmspzz** [comment]
That is not implemented yet.

**Comment by joesus** [comment]
@tmspzz thanks for the quick response! I'll close the issue for now and check back in a bit. Is there a rough timeline for when you think this will be available?

**Comment by tmspzz** [comment]
@joesus since Carthage development is community base, the answer to data is "when someone decides to implement it".

As I repeated multiple times, I would love to work full time on carthage but I can't. Maybe you @joesus would be the kind soul adding support for this feature?

**Comment by joesus** [comment]
@tmspzz - This would be a really nice feature to have. At some point I might have the time but at the moment I can't commit to working on it. Happy to help review code and test changes though. :D
