### ISSUE TITLE
Carthage update --use-xcframework fails on Xcode 12.3

### ISSUE THREAD

**Issue by pouty18** [Carthage/Carthage#3104]
* carthage install method: [ ] .pkg, [ ] homebrew, [x ] source
* `which carthage`:  /usr/local/bin/carthage
* `carthage version`: 0.36.0
* `xcodebuild -version`: Xcode 12.3 - Build version 12C33
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "Alamofire/Alamofire" "5.2.2"
github "Rightpoint/BonMot" "5.5.1"
github "Nirma/SFSymbol" "1.0.0"
github "sunshinejr/SwiftyUserDefaults" "5.0.0"
github "malcommac/SwiftDate" "6.2.0"
github "SnapKit/SnapKit" "5.0.0"
github "daltoniam/Starscream" "3.1.1"
github "nextlevel/NextLevel" "0.16.4"
github "onevcat/APNGKit" "1.2.2"
github "SVProgressHUD/SVProgressHUD" "2.2.5"
github "PureLayout/PureLayout" "v3.1.6"
github "airbnb/lottie-ios" "3.1.8"
github "mixpanel/mixpanel-iphone" "v3.6.3"
github "danielgindi/Charts" "4.0.0"
github "BranchMetrics/ios-branch-deep-linking" "0.36.0"
github "snowplow/snowplow-objc-tracker" "1.6.1"
github "0xced/XCDYouTubeKit" "2.15.1"
github "ccgus/fmdb" "2.7.7"
github "scenee/FloatingPanel" "2.0.1"
github "OneSignal/OneSignal-iOS-SDK" "2.16.0"

github "adventam10/AMColorPicker" "3.0.1"

github "ethanhuang13/CupertinoJWT" "v0.2.1"
github "auth0/JWTDecode.swift" "2.4.1"
github "SDWebImage/SDWebImage" "5.9.1"
github "realm/realm-cocoa" "v10.2.0"

github "KennethTsang/GrowingTextView" "0.7.2"

github "Juanpe/SkeletonView" "1.10.0"

git "https://bitbucket.org/rmonkey/papertraillumberjack.git" "0.1.9"
github "CocoaLumberjack/CocoaLumberjack" "3.7.0"

binary "https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/Carthage/appsflyer-ios.json" == 6.1.1

github "facebook/pop" "1.0.12"

```

**Carthage Output**
```
*** Downloading binary-only framework appsflyer-ios at "https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/Carthage/appsflyer-ios.json"
*** Fetching Charts
*** Fetching CocoaLumberjack
*** Fetching CocoaAsyncSocket
*** Fetching fmdb
*** Checking out NextLevel at "0.16.4"
*** Checking out Starscream at "3.1.1"
*** Checking out XCDYouTubeKit at "2.15.1"
*** Checking out AMColorPicker at "3.0.1"
*** Checking out mixpanel-iphone at "v3.6.3"
*** Checking out lottie-ios at "3.1.8"
*** Checking out papertraillumberjack at "0.1.9"
*** Checking out GrowingTextView at "0.7.2"
*** Checking out JWTDecode.swift at "2.4.1"
*** Checking out realm-cocoa at "v10.2.0"
*** Checking out BonMot at "5.5.1"
*** Checking out APNGKit at "1.2.2"
*** Checking out SFSymbol at "1.0.0"
*** Checking out OneSignal-iOS-SDK at "2.16.0"
*** Checking out Alamofire at "5.2.2"
*** Checking out SDWebImage at "5.9.1"
*** Checking out pop at "1.0.12"
*** Checking out CocoaAsyncSocket at "7.6.5"
*** Checking out ios-branch-deep-linking at "0.36.0"
*** Checking out PureLayout at "v3.1.6"
*** Checking out SkeletonView at "1.10.0"
*** Checking out SwiftyUserDefaults at "5.0.0"
*** Checking out fmdb at "2.7.7"
*** Checking out Charts at "9275d373136dfc98cdb365bff5280c37066df4dc"
*** Checking out SwiftDate at "6.2.0"
*** Checking out FloatingPanel at "2.0.1"
*** Checking out SnapKit at "5.0.0"
*** Checking out snowplow-objc-tracker at "1.6.1"
*** Checking out SVProgressHUD at "2.2.5"
*** Checking out CupertinoJWT at "v0.2.1"
*** Checking out CocoaLumberjack at "3.7.0"
*** xcodebuild output can be found in /var/folders/yh/_rd1fly57rq7jbr980nyr1gm0000gn/T/carthage-xcodebuild.j04nSl.log
*** Downloading binary-only framework appsflyer-ios at "https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/Carthage/appsflyer-ios.json"
*** Downloading ios-branch-deep-linking.framework binary at "Branch iOS SDK 0.36.0"
*** Downloading realm-cocoa.framework binary at "v10.2.0"
***  Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8) and the local version is 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)."

    Falling back to building from the source
*** Building scheme "Alamofire macOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "AMColorPicker" in AMColorPicker.xcodeproj
*** Building scheme "APNGKit-macOS" in APNGKit.xcworkspace
*** Building scheme "APNGKit-iOS" in APNGKit.xcworkspace
*** Building scheme "BonMot-OSX" in BonMot.xcodeproj
*** Building scheme "BonMot-iOS" in BonMot.xcodeproj
*** Building scheme "BonMot-watchOS" in BonMot.xcodeproj
*** Building scheme "BonMot-tvOS" in BonMot.xcodeproj
*** Building scheme "Charts" in Charts.xcworkspace
*** Building scheme "tvOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "Mac Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "CocoaLumberjack" in Demos.xcworkspace
*** Building scheme "CocoaLumberjackSwift" in Demos.xcworkspace
*** Building scheme "CupertinoJWT watchOS" in CupertinoJWT.xcodeproj
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -project /Users/richard/workspace/iOS/Carthage/Checkouts/CupertinoJWT/CupertinoJWT.xcodeproj -scheme CupertinoJWT\ watchOS -configuration Release -derivedDataPath /Users/richard/Library/Caches/org.carthage.CarthageKit/DerivedData/12.3_12C33/CupertinoJWT/v0.2.1 -sdk watchsimulator -destination platform=watchOS\ Simulator,id=8A33B74B-D453-4180-8B78-CE5791DC8AC2 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build VALIDATE_WORKSPACE=NO (launched in /Users/richard/workspace/iOS/Carthage/Checkouts/CupertinoJWT)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/yh/_rd1fly57rq7jbr980nyr1gm0000gn/T/carthage-xcodebuild.j04nSl.log
```

**Actual outcome**
Carthage failed to build the CupertinoJWT watch target xcframework.

**Expected outcome**
Carthage should properly build all dependencies into XCFrameworks.

**Comment by pouty18** [comment]
If there's anything else I can provide, please let me know. 

For context, the reason I'm referencing carthage's master branch is because I'm trying to configure my unit testing bundle to build however, Xcode compilation fails with this error: `/Users/rich/workspace/iOS/proj.xcodeproj Building for iOS Simulator, but the linked and embedded framework 'Alamofire.framework' was built for iOS + iOS Simulator.` 

This issue is also directly related to https://github.com/Carthage/Carthage/issues/3019#issuecomment-745054322_ 

I would love to receive any suggestions on ways that I can resolve this issue. Thanks!

**Comment by eseay** [comment]
@pouty18 If you're using Carthage v0.36.0, that release does not yet include the XCFrameworks support changes that are merged into `master` and referenced in the README. The maintainers have indicated that a new release that includes those changes will be coming soon. There are a handful of other threads you can follow related to that progress:

- #3102 
- https://github.com/Carthage/Carthage/issues/3019#issuecomment-755754794
- #3097

**Comment by pouty18** [comment]
@eseay I'm using carthage from master though? Shouldn't this work since I'm using carthage from source? 

What I did: 
- Uninstalled 0.36.0 from my machine, then cloned the carthage repo, ran `make install` and then `carthage update --use-xcframeworks`.

**Comment by pouty18** [comment]
@elliottwilliams any idea on why this might be occurring or what's causing the issue?

**Comment by stefanomondino** [comment]
@pouty18 I've read somewhere that `binary` in Cartfile is not supported yet through frameworks (I remember @elliottwilliams mentioning here #3102 ). Not sure that's related, but since you're using Appsflyer through binary AND the `--use-xcframeworks` flag I'm not sure what could happen. 

Also, CupertinoJWT was last updated 2 years ago, before xcframeworks were stable. I'm not an expert about this, but what is the expected behavior with the `--use-xcframeworks` flag and without the `BUILD_LIBRARY_FOR_DISTRIBUTION` in the actual source? Can you try to integrate CupertinoJWT in some other way (with pods or manually) and see if this fix the issue?

**Comment by pouty18** [comment]
Hey @stefanomondino that's a great callout. I'm _newer_ to the carthage world, so still trying to adjust. I've just tried moving CupertinoJWT to pods, and that's all fine now. However `carthage update --use-frameworks` now fails to build PapertrailLumberjack. 

The expected behavior is that the command will correctly build XCFrameworks for the dependencies listed in the cartfile, so that I can import them into my project for unit-testing. Right now, my test bundle is failing because the linked & embedded carthage frameworks were build for iOS + iOS Simulators

**Comment by stefanomondino** [comment]
@pouty18 I agree with you, but if you're using outdated dependencies, I'm afraid there's almost nothing that the Carthage maintainers can do for you. 
If you're used to Cocoapods (like me, after all), it should be "normal" for you to see the package manager (cocoapods) to "change settings in projects", either *your* project or your dependencies.

Carthage is not supposed to do that (at least from what I've understood about their philosophy): it takes the dependency xcproject as-is and compiles it. If that project is somehow messed up, outdated or whatsoever, it's not up to Carthage to fix that (with cocoapods, with post_install hooks and stuff, you can always try to "mess around"). 

Again, PapertrailLumberjack seems to be a very old dependency (updated mid-2019). There's a flag in their project (`BUILD_LIBRARY_FOR_DISTRIBUTION`) that didn't exist back then: someone from their team needs to turn this feature on and only then you should be able to have it working. Otherwise, stick to cocoapods and use whatever you can via Carthage and cocoapods for the rest. You have a huge amount of dependencies: unfortunately the more you have, the more trouble you get.

**Comment by pouty18** [comment]
Trust me, I know we have a large number of dependencies. And we're actively looking to drop that number.

Are you saying that the older dependencies need to be configured for the `--use-xcframeworks` to work?  Specifically specifying the `BUILD_LIBRARY_FOR_DISTRIBUTION` flag?

**Comment by 1oo7** [comment]
@pouty18 What works best for us to build all our existing Carthage dependencies as XCFrameworks, is to continue using a "workaround script" similar to the one that we have been using up to this point, but modified to override certain project settings within our dependencies: 

```
#!/usr/bin/env bash

# carthage-build.sh
# Usage example: ./carthage-build.sh --platform iOS

set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# override minimum os target to clear certain warnings

echo 'IPHONEOS_DEPLOYMENT_TARGET=9.0' >> $xcconfig

# override other build settings to resolve certain 
# build issues with older dependencies whose projects haven't
# been updated to be compatible with Xcode 12 and later

echo 'GCC_TREAT_WARNINGS_AS_ERRORS=NO' >> $xcconfig
echo 'GCC_C_LANGUAGE_STANDARD=compiler-default' >> $xcconfig
echo 'SWIFT_TREAT_WARNINGS_AS_ERRORS=NO' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
_carthage "$@"
```

If that doesn't work for you, then you could also try setting `BUILD_LIBRARY_FOR_DISTRIBUTION = YES` in this workaround script.

**Comment by 1oo7** [comment]
@pouty18 Also note, `--use-xcframeworks` doesn't actually work in the current release of carthage because this project's maintainers are, to put it mildly, utterly neglectful.
