### ISSUE TITLE
Copy-frameworks failed to support XCFramwork 

### ISSUE THREAD

**Issue by mikeli82** [Carthage/Carthage#3105]
* carthage install method: [ ] .pkg, [ ] homebrew, [x] source
* `which carthage`:
* `carthage version`: 0.35.0
* `xcodebuild -version`: 12.0.1
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 

**Cartfile**

**Carthage Output**
```
Failed to read file or folder at /mobile-client/Carthage/Build/iOS/SciChart.xcframework: Error Domain=NSCocoaErrorDomain Code=259 "Cannot retrive binary file from bundle at file:///mobile-client/Carthage/Build/iOS/SciChart.xcframework/" UserInfo={NSLocalizedDescription=Cannot retrive binary file from bundle at file:///mobile-client/Carthage/Build/iOS/SciChart.xcframework/, NSLocalizedRecoverySuggestion=Does the bundle contain an Info.plist?}
Command PhaseScriptExecution failed with a nonzero exit code
```

**Actual outcome**

copy-frameworks command fails with above error.

**Expected outcome**

copy-frameworks should work properly.

**Note**
The root case should relate to method `func binaryURL(_ packageURL: URL) -> Result<URL, CarthageError>`, this method doesn't contain the code to recognize the executable from a .xcframework.

**Comment by tmspzz** [comment]
You don't need copy-frameworks when using xcframeworks.

**Comment by mikeli82** [comment]
> You don't need copy-frameworks when using xcframeworks.

You mean when we are using xcframeworks, Xcode will strip the code for different architecture, then we don't need to use copy-frameworks to strip the code, just embed them in our project, right?

**Comment by tmspzz** [comment]
correct

**Comment by mikeli82** [comment]
Thanks @tmspzz

**Comment by zubairahmad2** [comment]
> You don't need copy-frameworks when using xcframeworks.

Thanks a lot

**Comment by musesfish** [comment]
Maybe these erros I got is cause by "Copy-frameworks failed to support XCFramwork" ? Has anyone knows ?
error build: Unable to load contents of file list: '/Target Support Files/FirebaseAnalytics/FirebaseAnalytics-xcframeworks-input-files.xcfilelist'
error build: Unable to load contents of file list: '/Target Support Files/FirebaseAnalytics/FirebaseAnalytics-xcframeworks-output-files.xcfilelist'
error build: Unable to load contents of file list: '/Target Support Files/GoogleAppMeasurement/GoogleAppMeasurement-xcframeworks-input-files.xcfilelist'
error build: Unable to load contents of file list: '/Target Support Files/GoogleAppMeasurement/GoogleAppMeasurement-xcframeworks-output-files.xcfilelist'
