### ISSUE TITLE
/usr/local/bin/carthage: No such file or directory Command PhaseScriptExecution

### ISSUE THREAD

**Issue by shift00** [Carthage/Carthage#3110]
* carthage install method: [ ] .pkg, [x ] homebrew, [ ] source
* `which carthage`:
* `carthage version`:  0.36.1
* `xcodebuild -version`: 
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`? no 
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
(doesn't matter)
```

**Actual outcome**
/usr/local/bin/carthage: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Expected outcome**
Working project

So far the project was running on xcode 11.7, but after i change my computer i need to install xcode 12.3. unfortunately, despite the installation of everything as it should, I cannot build frameworks from xcframework and after manual rebuilding I get information that there is "/usr/local/bin/carthage: No such file or directory Command PhaseScriptExecution"

help.

**Comment by tmspzz** [comment]
`brew install carthage`

**Comment by carlosefonseca** [comment]
If you got an M1 Mac, Homebrew installs stuff in a different place, that's why they ask you to add `which carthage`…
```
❯ which carthage
/opt/homebrew/bin/carthage
```

Not sure what's the advisable process for supporting both paths but if you're only using your computer on a project, maybe just change the path.

**Comment by kruperfone** [comment]
I had the same issue and fixed that with symlink:
`ln -s /opt/homebrew/bin/carthage /usr/local/bin/carthage`
But make sure you have `/usr/local/bin` folder first

Or you can use full path in your build phase script

I also tried to update my PATH everywhere without any positive result so for now I just use symlinks to fix that

**Comment by Juanpam** [comment]
I used something like:

```bash
CARTHAGEP="$(which carthage) copy-frameworks 
$CARTHAGE
```

so the build script works on both Intel and M1 macs and also in that way the path is not hardcoded but retrieved at runtime :)

**Comment by nicopuri** [comment]
> I used something like:
> 
> ```shell
> CARTHAGEP="$(which carthage) copy-frameworks"
> $CARTHAGE
> ```
> 
> so the build script works on both Intel and M1 macs and also in that way the path is not hardcoded but retrieved at runtime :)

There is a typo, an extra `P` letter, it should be `CARTHAGE="$(which carthage) copy-frameworks"`
Thanks a lot for the fix

**Comment by GianmarcoSalerno** [comment]
> I had the same issue and fixed that with symlink: `ln -s /opt/homebrew/bin/carthage /usr/local/bin/carthage` But make sure you have `/usr/local/bin` folder first
> 
> Or you can use full path in your build phase script
> 
> I also tried to update my PATH everywhere without any positive result so for now I just use symlinks to fix that

This is the right answer.

**Comment by ThomasAWRaku** [comment]
Using `$(which carthage)` only works when carthage is in the PATH, however, for the standard Xcode PATH value, carthage will not be available.
