### ISSUE TITLE
Carthage failed to support binary archive that contains prebuilt xcframework

### ISSUE THREAD

**Issue by mikeli82** [Carthage/Carthage#3111]
* carthage install method: [ ] .pkg, [ ] homebrew, [X] source
* `which carthage`:  /usr/local/bin/carthage
* `carthage version`:  0.36.0
* `xcodebuild -version`:   Xcode 12.0.1
* Are you using `--no-build`?  N
* Are you using `--no-use-binaries`?  Y
* Are you using `--use-submodules`?  N
* Are you using `--cache-builds`?  N
* Are you using `--new-resolver`?  N

**Cartfile**
```
binary "Eikon/Dependencies/SciChart.json" == 4.1.0
```

**Carthage Output**
```
*** Downloading SciChart.framework binary at "4.1.0"
Invalid archive - Found multiple frameworks with the same unarchiving destination:
* 	file:///var/folders/x9/q3vff67543b_n1x935blrpnm0000gn/T/carthage-archive.v1YdJn/SciChart.xcframework/macos-arm64_x86_64/SciChart.framework/
	file:///var/folders/x9/q3vff67543b_n1x935blrpnm0000gn/T/carthage-archive.v1YdJn/SciChart.xcframework/ios-arm64_x86_64-maccatalyst/SciChart.framework/ 
		to:
	file:///mobile-client/Carthage/Build/Mac/SciChart.framework/

file:///var/folders/x9/q3vff67543b_n1x935blrpnm0000gn/T/carthage-archive.v1YdJn/SciChart.xcframework/ios-arm64_i386_x86_64-simulator/SciChart.framework/
	file:///var/folders/x9/q3vff67543b_n1x935blrpnm0000gn/T/carthage-archive.v1YdJn/SciChart.xcframework/ios-arm64_armv7/SciChart.framework/ 
		to:
	file:///mobile-client/Carthage/Build/iOS/SciChart.framework/
```

**Actual outcome**
Carthage didn't resolve the dependency. 

**Expected outcome**
Carthage should resolve the dependency. 

**Note**
SciChart.json is pointing to a URL where stores an archive containing SciChart.xcframework.
I also checked the source code of Carthage, it seems that method `unarchiveAndCopyBinaryFrameworks` doesn't support xcframework.

**Comment by tmspzz** [comment]
Please read the release notes.

**Comment by mikeli82** [comment]
I see this from release notes, 
_This release does not include forthcoming support for building XCFrameworks. Expect XCFrameworks in the next release, 0.37.0._
Thanks @tmspzz
