### ISSUE TITLE
Unrecognized arguments: --use-xcframeworks in 0.36.1 installed via Homebrew

### ISSUE THREAD

**Issue by avdyushin** [Carthage/Carthage#3116]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`:  `0.36.1`
* `xcodebuild -version`:  `Xcode 12.3` `Build version 12C33`
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no
* I am using `--use-xcframeworks`

**Cartfile**
```
github "avdyushin/FreshchatSDK" "main"
```

Command: `carthage update --use-xcframeworks`

**Carthage Output**
```
Unrecognized arguments: --use-xcframeworks
```

**Actual outcome**
Can't find arguments

**Expected outcome**
Carthage should build XCFramework

**Comment by matopeto** [comment]
xcframeworks support is not in 0.36.1

**Comment by avdyushin** [comment]
> xcframeworks support is not in 0.36.1

This parameter noticed in many places of main readme, but I can't find which version does it support

**Comment by matopeto** [comment]
Readme is from master, where xcframework support is. Docs for 0.36.1 is in 0.36.1 branch: https://github.com/Carthage/Carthage/tree/release/0.36.1

**Comment by avdyushin** [comment]
Ah I see, thanks for pointing out
