### ISSUE TITLE
carthage copy-frameworks seems to be broken with 0.36.1

### ISSUE THREAD

**Issue by benjohnde** [Carthage/Carthage#3118]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.36.1
* `xcodebuild -version`: Xcode 12.4, Build version 12D4e
* Are you using `--no-build`? No.
* Are you using `--no-use-binaries`? Yes.
* Are you using `--use-submodules`? No.
* Are you using `--cache-builds`? No.
* Are you using `--new-resolver`? Yes.

**Cartfile**
```
github "SVProgressHUD/SVProgressHUD" ~> 2.2
github "ivanbruel/MarkdownKit" ~> 1.5
github "pocketsvg/PocketSVG" ~> 2.5.0
```

**Carthage Output**
```
*** Checking out PocketSVG at "2.5.0"
*** Checking out MarkdownKit at "1.6"
*** Checking out SVProgressHUD at "2.2.5"
*** Building scheme "MarkdownKit" in MarkdownKit.xcworkspace
*** Building scheme "PocketSVG (iOS)" in Demos.xcworkspace
*** Building scheme "SVProgressHUD-Framework" in SVProgressHUD.xcodeproj
```

**Actual outcome**
`carthage copy-frameworks` fails with the following error message:
```
In attempt to read NSBundle «file:///Users/john/git/appsmono/ios/Apps/Calprotectin/Carthage/Build/iOS/PocketSVG.framework/»'s binary url, could not relativize «file:///Users/john/git/appsmono/ios/Carthage/Build/iOS/PocketSVG.framework/PocketSVG» against «file:///Users/john/git/appsmono/ios/Apps/Calprotectin/Carthage/Build/iOS/PocketSVG.framework/».
```

You can replace the framework with an arbitrary one. It does not solve the problem.

**Expected outcome**
Carthage should copy the frameworks correctly.

I could trace that back the problem to the changes in the current version. Rolling carthage version back to 0.36.0 fixes the problem.

https://github.com/Carthage/Carthage/compare/0.36.0...0.36.1

We are using the recommended shell script since a few weeks and updated the contents with the ones in the [Documentation/Xcode12Workaround.md](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md). Did also not help! Caches were cleared accordingly and we also used a brand-new machine to simulate a build from scratch.

**Comment by mfreiwald** [comment]
Same here, I setup a new buildserver with carthage 0.36.1 -> the build fails.
On my laptop I first had 0.36.0 installed, the build succeeded, now after the upgrade to 0.36.1, the build also works.

**Comment by benjohnde** [comment]
> Same here, I setup a new buildserver with carthage 0.36.1 -> the build fails.
> On my laptop I first had 0.36.0 installed, the build succeeded, now after the upgrade to 0.36.1, the build also works.

Did you also clear the `Build` folder and remove `DerivedData`? I cannot successfully build our project with 0.36.1 😞🧐🤔.

**Comment by mfreiwald** [comment]
No. You‘re right. I was happy that it still works on my laptop.
I also installed version 0.36.0 on our buildserver and it works now.

**Comment by benjohnde** [comment]
> No. You‘re right. I was happy that it still works on my laptop.
> I also installed version 0.36.0 on our buildserver and it works now.
> 
> I see, you also have a symlink to a shared Carthage-folder right?
> This is also on our buildserver. Have you tried it without it?

Hm that's indeed a good idea! Thanks @mfreiwald! Haven't thought about that one but given the fact, that the release is out for a few days without any other report of that type of problem, this could be the solution. I am going to give it a shot tomorrow!

**Comment by msubel** [comment]
I had the same issue as the OP on 0.36.1 and downgrading to 0.36.0 solved the issue for me.

**Comment by mfreiwald** [comment]
Any news about that with Version 0.37.0?

**Comment by benjohnde** [comment]
Still got the same issue with version `0.37.0`. As far as I can trace that issue down, it seems related to the symlinks. Still, I need those symlinks :/.

**Comment by anton-plebanovich** [comment]
Copy script should work if you just remove all `Input Files` and `Output Files` and remove the checkmark for `Base on dependency analysis`

**Comment by Vitalii-Gozhenko** [comment]
After further investigation I found source of the problem, but I'm not sure how to solve it:
Precondition: main project has custom framework and both of them has dependency on the same framework (AFNetworking in my example)
```
public func nonDestructivelyStripArchitectures(_ frameworkURL: URL, _ architectures: Set<String>) -> SignalProducer<(Data, URL), CarthageError> {
	return SignalProducer(value: frameworkURL)
		.attemptMap(binaryURL)
		.attemptMap {
			let frameworkPathComponents = sequence(state: frameworkURL.absoluteURL.pathComponents.makeIterator(), next: {
				$0.next() ?? ""
			})
      // frameworkURL:
      // file:///Users/vitaliigozhenko/Work/test-carthage-issue-project/Carthage/Checkouts/MyAnotherFramework/Carthage/Build/iOS/AFNetworking.framework/
      // binaryURL:
      // file:///Users/vitaliigozhenko/Work/test-carthage-issue-project/Carthage/Build/iOS/AFNetworking.framework/AFNetworking

      let suffix = zip(frameworkPathComponents, $0.pathComponents).drop(while: { $0 == $1 })
      // suffix has 2 path components that was not dropped: Optional(("Checkouts", "Build")))

      if suffix.contains(where: { $0.0 != "" }) { // And it fails here because there is 2 more elements 
				return .failure(CarthageError.internalError(description: "In attempt to read NSBundle «\(frameworkURL.absoluteString)»'s binary url, could not relativize «\($0.debugDescription)» against «\(frameworkURL.absoluteString)»."))
			}
...
```

**Comment by LondonAtlas** [comment]
My team and I are also seeing this issue with 0.36.1 and 0.37.0

**Comment by mfreiwald** [comment]
Does someone testet it with 0.38?

**Comment by benjohnde** [comment]
> Does someone testet it with 0.38? #3152

Sry, we just cut out the last pieces of Carthage from our repository and solely rely on SwiftPM.

**Comment by JonSalerno** [comment]
> Does someone testet it with 0.38? #3152

I have and I am seeing the same issue.

**Comment by atlassian-gaustin** [comment]
The issue is if a portion of the path doesn't match _exactly_ - so if you're using symbolic links to change which Carthage directory to pick based upon Xcode version, then `copy-frameworks` will fail with this error.

**Comment by destryteeter** [comment]
I was able to workaround around this by removing the referenced directory at `./Carthage/Checkout/_Package_/Carthage/Build` then copying the Build directory `./Carthage/Build` directly into the Checkouts `./Carthage/Checkout/_Package_/Carthage/Build`.  Hack solution, and has to timed so that you copy immediately after running `carthage build`.
