### ISSUE TITLE
Carthage 0.36.1 Unrecognized arguments: --use-xcframeworks

### ISSUE THREAD

**Issue by pbmorton** [Carthage/Carthage#3119]
The use-xcframeworks argument is not being recognized. Please see the log below. Perhaps the dependency isn't compatible? The error message leads me to think this is not the issue because it says "unrecognized arguments" but I cannot be sure. Thank you in advance for your help.

```
macOS BigSur Vision 11.1 Mac mini (M1, 2020)

paul@Pauls-Mac-mini nannup % brew install carthage
Updating Homebrew...
Warning: carthage 0.36.1 is already installed and up-to-date.
To reinstall 0.36.1, run:
  brew reinstall carthage
paul@Pauls-Mac-mini nannup % which git
/usr/bin/git
paul@Pauls-Mac-mini nannup % git version
git version 2.24.3 (Apple Git-128)
paul@Pauls-Mac-mini nannup % cat Cartfile
github "CocoaLumberjack/CocoaLumberjack" == 3.7.0
paul@Pauls-Mac-mini nannup % 
paul@Pauls-Mac-mini nannup % sudo rm -rf ~/Library/Caches/org.carthage.CarthageKit
paul@Pauls-Mac-mini nannup % carthage update --use-xcframeworks                   
Unrecognized arguments: --use-xcframeworks
```

**Comment by pbmorton** [comment]
I have just noticed your 0.36.1 release notes say "This release does not include forthcoming support for building XCFrameworks. Expect XCFrameworks in the next release, 0.37.0". But your documnetation on your main github page says:

> Building platform-independent xcframeworks (Xcode 12 and above)
> Create a Cartfile that lists the frameworks you’d like to use in your project.
> Run carthage update --use-xcframeworks. This will fetch dependencies into a Carthage/Checkouts folder and build each one or download a pre-compiled xcframework.

So is the problem that you documentation is ahead of your latest release?

**Comment by vanthanhtran245** [comment]
You can check on [@elliottwilliams comment](https://github.com/Carthage/Carthage/pull/3106#issuecomment-766475368)
