### ISSUE TITLE
Why does Carthage build binaries?

### ISSUE THREAD

**Issue by thebnich** [Carthage/Carthage#312]
Naive question here. Why do I need to use Carthage/Build at all if I can import the .xcodeproj from Carthage/Checkouts? I'm currently doing the latter for projects that don't yet build with Carthage (<a href="https://github.com/kif-framework/KIF">KIF</a>, for example). Basically, I set up the imported project as if I had just downloaded the project manually.

It seems like this approach would have a few advantages:
* It works for projects that don't have a dynamic framework target (like KIF).
* There's no need for the <code>copy-frameworks</code> workaround script for universal binaries.

Using Carthage/Checkouts, I can still use Carthage for pulling in dependencies with versioning, so what am I missing?

**Comment by mdiep** [comment]
> Why do I need to use Carthage/Build at all if I can import the .xcodeproj from Carthage/Checkouts?

You don't. That's why there's a `--no-build` option. :relaxed:

Different people have different preferences, so Carthage gives you options. But I think most people find it easier to have Carthage handle the building and just copy in the pre-built frameworks.

Similarly, you can have Carthage add dependencies as submodules.

**Comment by thebnich** [comment]
Well then. I had no idea <code>--no-build</code> even existed!

Thanks to that pointer, I came across #174. To answer my original question on why someone would choose Carthage building over importing .xcodeproj, it sounds like building frameworks is more of a long-term goal, even if it doesn't work well right now. <code>--no-build</code> looks like a reasonable choice in the meantime.

Thanks!

**Comment by dodikk** [comment]
>> You don't. That's why there's a --no-build option. :relaxed:

@mdiep is it possible to specify this flag (or a similar one) on a per-project basis?
```
github "ccgus/fmdb" --no-build
github "ReactiveCocoa/ReactiveCocoa"
```


For example, I'd like to use ReactiveCocoa that supports carthage and FMDB which does not. An obvious solution is adding frameworks with Carthage while adding all other stuff manually with submodules (or even just commit the sources "as is" which I hate).
However, having FMDB in ```Carthage.checkout``` will ensure there is only one correct version of FMDB in case some other library depends on it.

**Comment by dodikk** [comment]
@mdiep sorry. I think the "per-project --no-build" idea is not that good since carthage operates only with dynamic libraries. If a library has a dynamic framework target, it should be easy to add carthage compatibility.

**Comment by thebnich** [comment]
> I think the "per-project --no-build" idea is not that good since carthage operates only with dynamic libraries.

That's what the Carthage docs say, but is this a necessary restriction? Carthage/Checkouts can include any Github project, dynamic framework or not, so it seems reasonable to take advantage of that. I use a number of projects that don't build frameworks at all.

Additionally, being able to specify <code>--no-build</code> directly in the Cartfile means that contributors don't need to specify that <code>--no-build</code> themselves. Since <code>--no-build</code> means you'll be using a completely different project setup, Cartfile, not the user, should be specifying it IMO.

**Comment by jspahrsummers** [comment]
> Carthage/Checkouts can include any Github project, dynamic framework or not, so it seems reasonable to take advantage of that. I use a number of projects that don't build frameworks at all.

Carthage will only _try_ to build dynamic frameworks. If there are projects that don't expose them, nothing will happen.

> Additionally, being able to specify <code>--no-build</code> directly in the Cartfile means that contributors don't need to specify that <code>--no-build</code> themselves.

This sort of thing is already being discussed elsewhere. See https://github.com/Carthage/Carthage/issues/262.

**Comment by thebnich** [comment]
> Carthage will only try to build dynamic frameworks. If there are projects that don't expose them, nothing will happen.

There are some projects where I would prefer Carthage even trying to build frameworks. <a href="https://github.com/drmohundro/SWXMLHash">SWXMLHash</a>, for example, builds Quick/Nimble for its unit tests. But SWXMLHash itself doesn't use a framework, so there's no reason to build it.

**Comment by jspahrsummers** [comment]
@thebnich I'm not really sure what you're proposing. The current behavior should be that nothing from that project gets built with Carthage. If you're seeing something else, could you please open a new issue?

**Comment by thebnich** [comment]
Thanks, I wasn't sure whether this was intended behavior or not. Opened #313.
