### ISSUE TITLE
Embedding XCFrameworks inside another framework with Carthage 0.37

### ISSUE THREAD

**Issue by agiguere** [Carthage/Carthage#3121]
* carthage install method: [ ] .pkg, [ ] homebrew, [ x] source
* `which carthage`:
* `carthage version`:  0.37
* `xcodebuild -version`: 12.4
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```

**Actual outcome**
I am testing a sample framework with the new carthage 0.37

I am able to create my xcframework and call some API

however, if I am adding binary dependencies as XCFramework into my Framework, the framework compiles without problem
and I can push my changes to GitHub,

let say's I have this setup

MyFramework
Dependencies
   FrameworkA
   FrameworkB

Framework A & B have been added to MyFramework and Framework B depend on Framework A

I run the CLI to build my xcframework, embed the framework into my App

in my app project I could type import and import FrameworkA or B however when I tried to call API from these frameworks I got the following errors:

ld: warning: Could not find or use auto-linked framework 'SAPOData'
ld: warning: Could not find or use auto-linked framework 'SAPFoundation'
ld: warning: Could not find or use auto-linked framework 'SAPCommon'

Undefined symbols for architecture x86_64:

thanks

**Expected outcome**
Carthage should ...

**Comment by DmitriyBagrov92** [comment]
+1, it's really necessary to be able embed binary dependency (already compiled xcframework) to some framework, attached via Carthage.
Right now I forced to use Makefile with some code like this:
`
#Install Carthage dependencies
.PHONY: install
install: ## Install required dependencies for development.
	carthage update --use-xcframeworks

	#Download archived .zip with .xcframeworks inside
	curl $(external_xcframeworks_url) -O -J -L

	#Unzip and move to other dependencies
	unzip -o $(external_xcframeworks_zip) -d $(Thage_result_dir)

	#Remove source zip
	rm $(external_xcframeworks_zip)

Thage_result_dir=Carthage/Build

external_xcframeworks_zip=NAME_OF_ZIP_WITH_XCFRAMEWORKS

external_xcframeworks_url=URL_TO_DOMAIN/$(external_xcframeworks_zip)
`

**Comment by elliottwilliams** [comment]
Not sure I'm following, are you both sure you're talking about the same thing?

@agiguere: It sounds like your situation is that you need FrameworkB to link against FrameworkA. With xcframeworks, you'd do this by dragging `FrameworkA.xcframework` into FrameworkB's "Frameworks and Libraries" pane and select "Do Not Embed". It's your app project's responsibility to embed each framework into its build product – the frameworks themselves only need to refer to each other.

@DmitriyBagrov92: you're asking for `binary` dependencies to be able to vend xcframeworks, right? This is acknowledged in the [release's known issues](https://github.com/Carthage/Carthage/releases/tag/0.37.0). We definitely need this before XCFramework support can be considered "complete".

**Comment by agiguere** [comment]
@elliottwilliams Let's say I have another xcframework (without dependencies), I just want to embed it inside my own framework to create API on top of it

Adding the framework (with either Embed & Sign or Do Not Embed) works, my custom frameworks compile successfully 

When I add this framework to another app, if I tried to reference an API from the embedded framework and it failed

ld: warning: Could not find or use auto-linked framework 'SAPOData'
Undefined symbols for architecture x86_64:

thanks

**Comment by tmspzz** [comment]
You cannot embed a framework inside another framework, No matter if it's an xcframework or other packaging.

**Comment by agiguere** [comment]
@tmspzz ok thanks, but it's possible to embed a static library, I already tried an it works

ok I will close this incident
