### ISSUE TITLE
xcframework download precompiled binaries from github

### ISSUE THREAD

**Issue by Blackjacx** [Carthage/Carthage#3125]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: 0.37.0
* `carthage version`:  0.37.0
* `xcodebuild -version`: 
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "Blackjacx/Columbus"
github "stripe/stripe-ios"
github "urbanairship/ios-library"
github "braintree/braintree-ios-drop-in"

binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDatabaseBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json"
binary "https://dl.google.com/geosdk/GoogleMaps.json"
binary "https://dl.google.com/geosdk/GooglePlaces.json"%
```

**Actual outcome**
Carthage is not downloading the file *.xcframework.zip from a Github release. Binary distributed frameworks like Google Maps or Firebase are otherwise not distributable as XCFramework via Carthage.

**Expected outcome**
It should download the zip file like it did it with the *.framework.zip files.

**Comment by tmspzz** [comment]
Please read the release notes for version 0.37.0
