### ISSUE TITLE
Carthage update error with Pre-compiled xcframework

### ISSUE THREAD

**Issue by Zag42** [Carthage/Carthage#3127]
* carthage install method: [ ] .pkg, [ x] homebrew, [ ] source
* `which carthage`:/usr/local/bin/carthage
* `carthage version`: 0.37.0
* `xcodebuild -version`: Xcode 12.2 Build version 12B45b 
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No 
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
binary "https://nexus.adaptive-channel.com/repository/ios-snapshots/AdaptiveDigitalReader/AdaptiveDigitalReader.json"
```

**Carthage Output**
```
$ carthage update --use-xcframeworks --use-netrc
*** Downloading binary-only framework AdaptiveDigitalReader at "https://nexus.adaptive-channel.com/repository/ios-snapshots/AdaptiveDigitalReader/AdaptiveDigitalReader.json"
*** xcodebuild output can be found in /var/folders/0g/b3w4qd113qg8cq041pt9blyr0000gn/T/carthage-xcodebuild.C82owD.log
*** Downloading binary-only framework AdaptiveDigitalReader at "https://nexus.adaptive-channel.com/repository/ios-snapshots/AdaptiveDigitalReader/AdaptiveDigitalReader.json"
*** Downloading AdaptiveDigitalReader.framework binary at "1.3.1"
Invalid archive - Found multiple frameworks with the same unarchiving destination:
* 	file:///var/folders/0g/b3w4qd113qg8cq041pt9blyr0000gn/T/carthage-archive.AejmN7/AdaptiveDigitalReader.xcframework/ios-x86_64-simulator/AdaptiveDigitalReader.framework/
	file:///var/folders/0g/b3w4qd113qg8cq041pt9blyr0000gn/T/carthage-archive.AejmN7/AdaptiveDigitalReader.xcframework/ios-arm64/AdaptiveDigitalReader.framework/ 
		to:
	file:///Users/williamsantos/Documents/Workspace/adaptive-digital-reader/ADRDemo/Carthage/Build/iOS/AdaptiveDigitalReader.framework/
```

**Actual outcome**
Instead of just putting the pre-compiled xcframework in the build folder, carthage tries to move the individual framewoks it contains to the build folder.
Notes: 
- The xcframework contains two subfolders: "ios-arm64" and "ios-x86_64-simulator"
- It is zipped as `AdaptiveDigitalReader.xcframework.zip`
- I am using `--use-netrc`, but it does not seem to matter
- I tried with and without `--use-xcframeworks`

**Expected outcome**
Carthage should put the pre-compiled xcframework in the build folder

**Comment by vanthanhtran245** [comment]
Read more release note for version 0.3.70. Currently carthage not support yet xcframework binary.

**Comment by Zag42** [comment]
Ok thank you, i missed that part!
