### ISSUE TITLE
Incompatible Swift version 

### ISSUE THREAD

**Issue by jaywadhwani** [Carthage/Carthage#3128]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: homebrew
* `carthage version`:  0.37.0
* `xcodebuild -version`:  12.4
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`?  --no-use-binaries
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`? no

**Cartfile**
```
<YOUR CARTFILE>
github "ashleymills/Reachability.swift" == 5.0.0
github "onevcat/Kingfisher" == 5.13.0
github "Square/Valet" == 4.1.1
github "realm/realm-cocoa" == 4.3.2
github "Alamofire/Alamofire" == 4.9.1
github "konkab/AlamofireNetworkActivityLogger" == 2.4.0
binary "https://medallia.bintray.com/digital-generic/com/medallia/digital/ios-sdk/3.6.1/ios-sdk-3.6.1-12.2-carthage.json"
github "krzyzanowskim/CryptoSwift" == 1.3.0
github "mxcl/PromiseKit" == 6.13.1
github "microsoft/appcenter-sdk-apple" == 3.3.4
github "bazaarvoice/bv-ios-sdk" == 8.3.0
github "optonaut/ActiveLabel.swift" == 1.1.0

**Carthage Output**
```
<OUTPUT>
*** Downloading binary-only framework ios-sdk-3.6.1-12.2-carthage at "https://medallia.bintray.com/digital-generic/com/medallia/digital/ios-sdk/3.6.1/ios-sdk-3.6.1-12.2-carthage.json"
*** Fetching realm-cocoa
*** Fetching Reachability.swift
*** Fetching Kingfisher
*** Fetching ActiveLabel.swift
*** Fetching Alamofire
*** Fetching PromiseKit
*** Fetching AlamofireNetworkActivityLogger
*** Fetching CryptoSwift
*** Fetching Valet
*** Fetching appcenter-sdk-apple
*** Checking out PromiseKit at "6.13.1"
*** Checking out Reachability.swift at "v5.0.0"
*** Checking out Alamofire at "4.9.1"
*** Checking out Kingfisher at "5.13.0"
*** Checking out bv-ios-sdk at "8.3.0"
*** Checking out Valet at "4.1.1"
*** Checking out ActiveLabel.swift at "1.1.0"
*** Checking out appcenter-sdk-apple at "3.3.4"
*** Checking out realm-cocoa at "v4.3.2"
*** Checking out CryptoSwift at "1.3.0"
*** Checking out AlamofireNetworkActivityLogger at "2.4.0"
*** xcodebuild output can be found in /var/folders/cz/xylzf5y168g9dp4_3502gzw80000gn/T/carthage-xcodebuild.rFp5AC.log
*** Downloading binary-only framework ios-sdk-3.6.1-12.2-carthage at "https://medallia.bintray.com/digital-generic/com/medallia/digital/ios-sdk/3.6.1/ios-sdk-3.6.1-12.2-carthage.json"
*** Downloading ios-sdk-3.6.1-12.2-carthage.framework binary at "3.6.1"
Incompatible Swift version - framework was built with 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8) and the local version is 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28).

**Actual outcome**
*** Downloading ios-sdk-3.6.1-12.2-carthage.framework binary at "3.6.1"
Incompatible Swift version - framework was built with 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8) and the local version is 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28).

**Expected outcome**
Carthage should ...

**Comment by tmspzz** [comment]
Please fill in the provided form and provided more details to help the investigation

**Comment by jaywadhwani** [comment]
@tmspzz updated

**Comment by pbartolome** [comment]
Same issue with a different framework, what is the reasoning behind this check? The framework works properly if added manually without Carthage, even if it's compiled for 5.3.2 and used in Xcode 12.2 with swift 5.3.1
