### ISSUE TITLE
`Error Domain=NSCocoaErrorDomain Code=512` when update

### ISSUE THREAD

**Issue by korstudio** [Carthage/Carthage#3129]
* carthage install method: [ ] .pkg, [ x ] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: 0.37.0
* `xcodebuild -version`: `12.4.0 on CircleCI`
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No
* Using `--use-xcframeworks` - Yes
* Working on CircleCI

**Cartfile**
```
github "Alamofire/Alamofire" ~> 5.2.1
github "omise/omise-ios" ~> 3.5.0
github "scalessec/Toast-Swift" ~> 5.0.1
...
```

**Carthage Output**
```
*** Cloning TPInAppReceipt
*** Cloning omise-ios
*** Cloning HGPlaceholders
*** Cloning L10n-swift
*** Cloning SDWebImage
*** Cloning BWWalkthrough
*** Cloning SKPhotoBrowser
*** Cloning lottie-ios
*** Cloning Alamofire
*** Cloning Sheeeeeeeeet
*** Cloning Toast-Swift
*** Cloning Localize-Swift
*** Cloning SwifterSwift
*** Cloning KMPlaceholderTextView
*** Cloning Parchment
*** Cloning SkeletonView
*** Checking out lottie-ios at "3.2.1"
*** Checking out omise-ios at "v3.8.0"
*** Checking out Parchment at "v2.4.0"
*** Checking out SkeletonView at "1.12.1"
Failed to check out repository into /Users/distiller/project/Carthage/Checkouts/Parchment: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=512 "The file “Carthage” couldn’t be saved in the folder “project”." UserInfo={NSFilePath=/Users/distiller/project/Carthage, NSUnderlyingError=0x7fa20a5e9810 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}})
CircleCI received exit code 0
```

**Actual outcome**
Carthage did not checkout and compile libraries

**Expected outcome**
Carthage should checkout and compile libraries and put `*.xcframeworks` into `Carthage/Build`

I'm struggling with setting up CircleCI with new Carthage right now. Before, I got `Error=260` using Xcode 12 workaround script but when I updated to 0.37.0 and remove workaround, I still get an error.

What should I do about configuring the CI?

**.circleci/config.yml**
```
- run:
          name: Install Carthage's Dependencies
          command: carthage update --platform iOS --use-xcframeworks
```

**Comment by vanthanhtran245** [comment]
I have same issue
