### ISSUE TITLE
Subproject frameworks are built for projects without frameworks

### ISSUE THREAD

**Issue by thebnich** [Carthage/Carthage#313]
I'm seeing this issue with <a href="https://github.com/drmohundro/SWXMLHash">SWXMLHash</a>. Steps:

1. Add <code>github "drmohundro/SWXMLHash"</code> to Cartfile.
1. Execute <code>cartfile update</code>.

Output:
```
*** Fetching SWXMLHash
*** Checking out SWXMLHash at "0.6.2"
*** xcodebuild output can be found in /var/folders/gj/37fglw7j6m9d5pmy3jcm95rc0000gn/T/carthage-xcodebuild.JDJhax.log
*** Building scheme "Nimble-iOS" in SWXMLHash.xcworkspace
*** Building scheme "Nimble-OSX" in SWXMLHash.xcworkspace
*** Building scheme "Quick" in SWXMLHash.xcworkspace
```

From <code>ls Carthage/Build/*</code>:
```
Carthage/Build/Mac:
Nimble.framework Quick.framework

Carthage/Build/iOS:
Nimble.framework
```

**Comment by jspahrsummers** [comment]
It looks like `SWXMLHash.xcodeproj` doesn't [share its schemes](https://github.com/Carthage/Carthage#share-your-xcode-schemes), which is probably why Carthage is looking at the `xcworkspace` instead.
