### ISSUE TITLE
Carthage Didn't Build the Frameworks as Expected.

### ISSUE THREAD

**Issue by owenzhao** [Carthage/Carthage#3139]
* carthage install method: [ ] .pkg, [*] homebrew, [ ] source
* `which carthage`:
* /usr/local/bin/carthage
* `carthage version`: 
* 0.37.0
* `xcodebuild -version`: 
* Xcode 12.5
* Build version 12E5234g
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`? no 
* Are you using `--new-resolver`?  no

**Cartfile**
```
github "realm/realm-cocoa"
```

**Carthage Output**
```
carthage update --platform iOS,watchOS --use-xcframeworks
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "v10.7.0"
*** xcodebuild output can be found in /var/folders/q0/w56_y2yx51bglz9x36r1hmgh0000gn/T/carthage-xcodebuild.h91Frg.log
*** Downloading realm-cocoa.framework binary at "v10.7.0"
***  Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28) and the local version is 5.4 (swiftlang-1205.0.24.6 clang-1205.0.19.54)."

    Falling back to building from the source
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "Realm iOS static" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
```

**Actual outcome**
<img width="1043" alt="截屏2021-03-02 下午4 28 03" src="https://user-images.githubusercontent.com/2182896/109620164-8738c700-7b74-11eb-9500-7c086eae7670.png">

**Expected outcome**
There are many issues. I am a beginner for Carthage. Here are my questions.

1. I have specified the platforms to be iOS and watchOS by "--platform iOS,watchOS". But the results were **macOS** and watchOS. Why this happened?
2. On help of Carthage, it says that 

> [--use-xcframeworks]
> create xcframework bundles instead of one framework per platform (requires Xcode 12+)

But in fact, Carthage creates xcframework bundles along with "one framework per platform". So if I only need xcframework, which command should I use? That will save me some building time.

3. For watchOS simulator with Xcode 12, a watchOS arm64 simulator framework is required. Carthage didn't built it. Which command should I use to get it?

Thanks.

**Comment by owenzhao** [comment]
For the first two questions, now I know the answers and agree with this issue report [Downloading .framework instead of building a .xcframework](https://github.com/Carthage/Carthage/issues/3134).

**Comment by owenzhao** [comment]
I compared the xcframework that Carthage build and the xcframework that is downloaded from RealmCocoa. 

<img width="1243" alt="截屏2021-03-03 上午2 00 51" src="https://user-images.githubusercontent.com/2182896/109694665-06a2b680-7bc6-11eb-844c-42d7cb5bb5dd.png">

My building Mac is an Intel based iMac. The left is from Realm and the right is Carthage.

The Realm downloaded xcframework contains an extra framework for maccatalyst and for every simulator, it has arm64. Carthage doesn't contain any arm64 for simulator. Maybe that is because my Mac is Intel based. However, there is an issue here. Now with Xcode 12 with watchOS simulators, arm64 is required even on an Intel based Mac.

So is there a way to build arm64 for simulators on an Intel based Mac using Carthage?

**Comment by ddaddy** [comment]
Hi,
Firstly, Carthage does not yet support building maccatalyst builds 😞
Hopefully it won't be too long before this is added.

I had a go at building `realm-cocoa` using `carthage update --use-xcframeworks --no-use-binaries` and it didn't build the `arm64` slice for the simulators. I looked into the project and found this in `Build.xcconfig`:

```
// Disable building the arm64 simulators when using Carthage as it doesn't support them yet
REALM_ARM_ARCHS_YES = arm64 arm64e;
REALM_ARM_ARCHS = $(REALM_ARM_ARCHS_$(CARTHAGE))

EXCLUDED_ARCHS[sdk=watchsimulator*] = $(REALM_ARM_ARCHS);
EXCLUDED_ARCHS[sdk=iphonesimulator*] = $(REALM_ARM_ARCHS);
EXCLUDED_ARCHS[sdk=appletvsimulator*] = $(REALM_ARM_ARCHS);
```

So it looks like realm specifically excludes the building of the `arm64` slice for simulators when using Carthage. Perhaps you could tell them it is now fine to build `arm64` when using the `--use-xcframeworks` flag, and they can update the project.

I commented out these `EXCLUDED_ARCHS` lines in the checkout and it built everything fine, including the `arm64` slice, as expected.

(Damn that project takes a long time to build!)

**Comment by owenzhao** [comment]
@ddaddy Thank you for your reply. Though it was not so clear for someone new to Carthage like me, it really pointed out the good direction.

## Facts

### Build.xcconfig
This file's real url is "Carthage/Checkouts/realm-cocoa/Configuration/Base.xcconfig".

### Steps to Rebuild
Here is how to building the arm64 simulators Realm/RealmSwift from zero.

#### 1. Create a Cartfile
Create a Cartfile with content `github "realm/realm-cocoa"`.

#### 2. Get Cartfile Resolved 
I didn't find a clean way to resolve only with Carthage. I have to use `carthage update` and `cmd+c` to stop the process when I saw the `Cartfile.resolved` file was created.

#### 3. Checkout
run `carthage checkout` will download the realm/realm-swift source files.

#### 4. Commented "EXCLUDED_ARCHS"

![commented_lines](https://user-images.githubusercontent.com/2182896/110747405-48dc8f80-8279-11eb-8464-c87cfe41376a.png)

#### 5. Build
You must use `carthage build --platform macOS,iOS,watchOS --no-use-binaries --use-xcframeworks` to build the xcframework. 

> If you use "updated" instead of "build", Carthage will checkout and override the commented lines.
> If you use "--cache-builds", Carthage may skip the build as Carthage doesn't know you commented lines and thinks nothing is changed.
> If you do not use "--no-use-binaries", Carthage will download the prebuilt binary frameworks for individual platforms, or it will build extra old frameworks alone with xcframeworks. Even worse, the build may fail as `lipo` couldn't merge the fat frameworks.

### Finally 
I tested the xcframeworks with an iOS with watchOS app companion project, and it worked.

### One More Thing
It is a Xcode 12's bug to request arm64 simulator framework on an Intel based Mac for me. For Apple, I think it knows it and it wants it. As it keeps the compatibility of the development for teams who use both Intel based and Apple silicon based Macs.

**Comment by owenzhao** [comment]
@ddaddy Unfortunately, it seems in this way, the built xcframeworks for iOS and iOS simulator are extra large. The app could be built, but when ran, Xcode showed an error.

> dyld: Library not loaded: @rpath/Realm.framework/Realm

<img width="1512" alt="截屏2021-03-12 下午5 41 21" src="https://user-images.githubusercontent.com/2182896/110922126-49008c00-835a-11eb-9b6c-bf2e20178487.png">

```swift
import UIKit
import RealmSwift

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let realm = try! Realm()
        let bar = Bar()
        
        try! realm.write {
            realm.add(bar, update: .all)
        }
    }
}

class Bar:Object {
    @objc dynamic var id = 0
    
    override class func primaryKey() -> String? {
        return "id"
    }
}
```

The downloaded xcframeworks from Realm works. 

<img width="1969" alt="截屏2021-03-12 下午5 32 29" src="https://user-images.githubusercontent.com/2182896/110922507-b9a7a880-835a-11eb-9e1a-3a0b3b11f319.png">
