### ISSUE TITLE
Should Carthage support/inherit custom build configurations?

### ISSUE THREAD

**Issue by st3fan** [Carthage/Carthage#314]
I am not sure if this is something Carthage should support or if this is something we should deal with in our local project.

But, the problem is as follows: Instead of the regular `Debug` and `Release` build configurations, we have configurations like `Firefox`, `FirefoxBeta` and `FennecNightly`. This allows us to customize our different build flavors / release channels. Like specify different product names, signing identities or entitlements files for each build configuration.

We just started playing with Carthage and the problem is that when we for example build our FennecNightly target, Carthage still builds with the `Release` target. This means that intermediates go into separate directories with the result that a Swift `import` fails because the compiler simply does not see the frameworks we pull in.

Previously we had these dependencies directly in our project. So I simply added build configurations to them and that worked all fine. But with Carthage I cannot do that because we import them as-is and I cannot easily make changes like that anymore. (They would not persist)

Is this is a common issue? Is this something Carthage could make easier? Or should we simplify our builds in some way?

(Note that we are using `carthage update --no-build` if that makes any difference)

**Comment by jspahrsummers** [comment]
If all of your projects have the specified configuration, it should be built. Otherwise, `xcodebuild` defaults to `Release` (this isn't an artifact of Carthage).

It sounds like you added the correct build configurations before, but are now unable to do so? Why can't they be added and pushed to the dependency projects?

**Comment by st3fan** [comment]
@jspahrsummers All my projects have the custom build configuration and I use a custom Scheme that sets the build config for Archive to my custo mbuild configation. That all works well and as intended.

The problem is that the frameworks that Carthage added don't know anything about this custom build configuration. So our own projects are built with for example `FennecNightly` while things like Snap and Alamofire are built with `Release`.

Because Snap and Alamofire are pulled in by Carthage, I have no option to change their defaults. Unless I do it manually every time we open the project. But that is not an option because it kills all automation we have around builds.

Am I missing something obvious here?

**Comment by jspahrsummers** [comment]
> The result of those different build configs is that intermediates are placed in different directories so that includes and imports fail.

You shouldn't need intermediates if you're using Carthage to build, since you should just be using the binaries that Carthage places in `Carthage/Build`.

Are you using the `--configuration` build flag?

**Comment by marcinkuptel** [comment]
Using `--configuration "Configuration name"` does not work for me. Carthage defaults to Release.
