### ISSUE TITLE
Question on xcframework

### ISSUE THREAD

**Issue by keithcml** [Carthage/Carthage#3150]
I got this when using xcframework from Carthage
`module 'xxx' was not compiled with library evolution support; using it means binary compatibility for 'xxx' can't be guaranteed`

Will Carthage build xcframework with 
`BUILD_LIBRARIES_FOR_DISTRIBUTION=YES` ?

Seems the xcframework from Carthage won't support library evolution.

**Comment by jenhausu** [comment]
seems not, we need to turn it on manually right now.
there is an issue discuss this #2992

**Comment by Hilliy024** [comment]
How do I do that

**Comment by jenhausu** [comment]
Open project in Carthage/Checkouts, go to build settings section, and turn `Build Libraries for Distribution` to Yes.
After that, regenerate the XCFramework with command `carthage build --use-xcframeworks --platform ios`, dont' use bootstrap, the project setting will be reset to default.

**Comment by disbelief** [comment]
@jenhausu I've been trying to do what you suggest but the `carthage build --use-xcframeworks --platform ios` command simply wipes my local changes from the Carthage/Checkouts directory. Is there another option to pass to `carthage`?
