### ISSUE TITLE
Skipped building XXX due to the error: Dependency "XXX" has no shared framework schemes

### ISSUE THREAD

**Issue by ravi-ios** [Carthage/Carthage#3153]
* carthage install method: homebrew
* `which carthage`: 0.37.0
* `carthage version`: 
* `xcodebuild -version`:  12.2
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`?  Yes
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 

I have XCFramework which is shared by some proprietary software company
Steps I made
1) Created a folder structure like **Carthage/Build/iOS/XXX.xcframework**
2) Compressed as **XXX.xcframework.zip**
3) Published on github
4) Added link in project's **Cartfile**
5) run the command **carthage update --use-xcframeworks** or **carthage update --no-use-binaries --use-xcframeworks**

Error as below

**Carthage Output**
```
carthage update --no-use-binaries --use-xcframeworks
*** Checking out XXX at "3.2.2"
*** xcodebuild output can be found in /var/folders/c4/T/carthage-xcodebuild.LQYKLd.log
*** Skipped building XXX due to the error:
Dependency "XXX" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at ABC repo

```

**Expected outcome**
My XCFramework should download with out any issues.

**Comment by Ricardo1980** [comment]
Perhaps this is the same issue I have here:
https://github.com/Carthage/Carthage/issues/3156
But I see that you are using 0.37.0, which in theory does not have xcframework support:
https://github.com/Carthage/Carthage/pull/3152

**Comment by tmspzz** [comment]
Please read the release notes of 0.37.0
