### ISSUE TITLE
Carthage bootstrap faild on private dependencies

### ISSUE THREAD

**Issue by GautierLouis** [Carthage/Carthage#3157]
I'm building a Teamcity agent on a mac. On TC configuration page, we set up a SSH key so that agent can clone the projects 
The agent can clone the repository, commit and push. 
But when I do `carthage bootstrap --platform ios` the following error appear.

* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.37.0
* `xcodebuild -version`: 
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
git "git@bitbucket.org:XXX/YYY.git" "master"
```

**Carthage Output**
```
A shell task (/usr/bin/env git submodule --quiet sync --recursive /Users/teamcityagent/Downloads/buildAgentFull/work/b357a344b48935eb/Carthage/Checkouts/YYY (launched in /Users/teamcityagent/Downloads/buildAgentFull/work/b357a344b48935eb)) failed with exit code 1:
error: pathspec '/Users/teamcityagent/Downloads/buildAgentFull/work/b357a344b48935eb/Carthage/Checkouts/YYY' did not match any file(s) known to git
Process exited with code 1
```

**Actual outcome**
Carthage seems to not have access to my private lib

**Expected outcome**
Carthage should have access

**Comment by vanthanhtran245** [comment]
Did you try with additional command --use-ssh?

**Comment by GautierLouis** [comment]
Yes. It's not working. Sorry I missed this in description

**Comment by Ricardo1980** [comment]
You can also try using `--use-netrc`
Add the file .netrc to your user folder with this content:
```
machine github.com
login your-user-name
password your-access-token
machine api.github.com
login your-user-name
password your-access-token
```

In my case, both options work (ssh and netrc)
