### ISSUE TITLE
Carthage copy-frameworks fails with error: truncated or malformed fat file

### ISSUE THREAD

**Issue by damirdavletov** [Carthage/Carthage#3158]
### Context

We have a project setup where we have 2 unit-test targets that build test bundles which run within test host application. Both unit test bundles link and embed OCMock dynamic framework as a dependency. Embedding is done via `carthage copy-frameworks` script. This build phase fails intermittently with an error.

* carthage install method: [ ] homebrew
* `which carthage`:/usr/local/bin/carthage
* `carthage version`: 0.37.0
* `xcodebuild -version`: Xcode 12.1

**Cartfile**
```
github "erikdoe/ocmock" == 3.4.1
```

**Actual outcome**
Compilation error on copy-framework run script build phase
```
A shell task (/usr/bin/xcrun lipo /Users/<>/Library/Developer/Xcode/DerivedData/<>/Build/Products/Debug-iphonesimulator/<>.app/PlugIns/OCMock.framework.dSYM/Contents/Resources/DWARF/OCMock -remove arm64 -remove armv7 -remove i386 -output /Users/<>/Library/Developer/Xcode/DerivedData/<>/Build/Products/Debug-iphonesimulator/<>.app/PlugIns/OCMock.framework.dSYM/Contents/Resources/DWARF/OCMock) failed with exit code 1:
fatal error: /Applications/Xcode-12.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: truncated or malformed fat file (offset plus size of cputype (12) cpusubtype (9) extends past the end of the file) /Users/<>/Library/Developer/Xcode/DerivedData/<>/Build/Products/Debug-iphonesimulator/<>.app/PlugIns/OCMock.framework.dSYM/Contents/Resources/DWARF/OCMock
```

**Expected outcome**

Carthage does not fail copying frameworks and copies dSYM bundle to the appropriate place

### Observations
It seems that there are 2 issues. 

1. dSYM bundle being copied into wrong location. It should not be in the application's `Plugins` folder, but rather in BUILT_PRODUCTS_DIR.
2. The two simultaneous copy-frameworks operations interfere with each other and while one copies the bundle the second tries to strip it (lipo) the contents and fails.

So the fix would presumably be:

1. Copy dSYM to BUILT_PRODUCTS_DIR.
2. Stripping and copying should be made atomic operations e.g. strip the bundle in temp directory and only then move it.

**Comment by vanthanhtran245** [comment]
If you build ưith xcframework just embed and no need copy carthage framework script
