### ISSUE TITLE
Missing context in messaging for incompatible requirements

### ISSUE THREAD

**Issue by paulyoung** [Carthage/Carthage#317]
```
Could not pick a version for github "Quick/Quick", due to mutually incompatible requirements:
	== 0.3.0
	== 0.2.0
```

It would be really helpful if this message provided some additional information so that users would know which dependencies have conflicting versions.

**Comment by chml** [comment]
I went into the same issue:
```
Could not pick a version for github "ReactiveCocoa/ReactiveCocoa", due to mutually incompatible requirements:
	"v3.0-beta.1"
	"v3.0-alpha.3"
```
This is my Cartfile:
```
github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.1"
```

**Comment by paulyoung** [comment]
![687474703a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3435323336342f676966732f6361626c652d64616e63652e676966](https://cloud.githubusercontent.com/assets/84700/12861782/c288d214-cc1a-11e5-9e90-b59600ecbfe6.gif)
