### ISSUE TITLE
Incorrect workspace used during bootstrap for DeviceKit

### ISSUE THREAD

**Issue by jahorton** [Carthage/Carthage#3181]
* carthage install method: `brew`
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: `0.38.0`
* `xcodebuild -version`: `Xcode 12.2 Build version 12B45b`
* Are you using `--no-build`? ❌ 
* Are you using `--no-use-binaries`? ❌
* Are you using `--use-submodules`? ❌
* Are you using `--cache-builds`? ❌
* Are you using `--new-resolver`? ❌

**Cartfile**
```
github "marmelroy/Zip"
github "DaveWoodCom/XCGLogger" ~> 6.1.0
github "devicekit/DeviceKit" ~> 2.3
github "ashleymills/Reachability.swift"
github "getsentry/sentry-cocoa" ~> 4.4.3
```

**Carthage Output**

<img width="585" alt="Screen Shot 2021-05-17 at 2 15 58 PM" src="https://user-images.githubusercontent.com/25213402/118446980-6c5d0400-b71a-11eb-86e5-3475adf00695.png">

I have tried updating to the latest version of DeviceKit (4.4), but experienced the same issues.

**Actual outcome**

Note the line:

`*** Building scheme "DeviceKit" in` _**`CocoaPodsVerification.xcworkspace`**_

**Expected outcome**

`*** Building scheme "DeviceKit" in` _**`DeviceKit.xcworkspace`**_

--------

The version in `CocoaPodsVerification.xcworkspace` is far older and seems to have been designed as a deployment test, while the root folder's DeviceKit.xcworkspace has the "true", current version of the framework I want.  There are fields and declared enum values missing in the compiled version of the framework as a result of this error.

Worth noting:  the old pre-0.37 `.framework` approach does not have this error; I ran into this while following [the framework -> XCFramework migration instructions](https://github.com/Carthage/Carthage#migrating-a-project-from-framework-bundles-to-xcframeworks).

Is there some workaround via parameter that I can supply to Carthage to ensure the correct workspace is used to build the dependency?  I've tried deleting both the Checkouts and Build folder a few times already to no avail.

--------

When searching for similar issues, I did find this old one:  #2549.

**Comment by jahorton** [comment]
If I go into the checked-out version and remove the "Shared" property from the `CocoaPodsVerification` workspace, the correct workspace does build.  The issues with that:

- I'm not a contributor to the DeviceKit project
- We use continuous integration, with our build agents re-downloading the dependencies each run.  We cannot constantly babysit the affected builds.

So, what's the best way to prevent Carthage from using the wrong workspace during a CI run?

**Comment by jahorton** [comment]
In the meantime, it does seem I can work around this by splitting my `bootstrap` into a few steps:
1. `checkout` 
2. deleting the incorrect .xcworkspace
3. `build`

That said, it's definitely, at minimum, _odd_ and inconsistent for the default `build` (for .framework) and the `--use-xcframework` `build` to pick different compilation targets.  This workaround _should_ either be needed in neither or in both, but not in only one.

**Comment by akaffenberger** [comment]
I'm experiencing this issue as well. Imo the onus falls on DeviceKit to remove the outdated workspace from their repo, OR bring it up to date.

That said, I can also see how it makes sense to check the root level project files before searching sub directories. A lot of frameworks have example/test projects in a subfolder next to their root project. While test projects _typically_ just hold references to the root project (rather than copying the source entirely), it's not necessarily a safe assumption to make.

I will take a look at this and see if I can whip up a PR.

**Comment by akaffenberger** [comment]
As it turns out, the project files closer to the root directory were already being prioritized (sorted by directory level). However, there is a bug in the reactive signal logic that was causing the schemes to be processed out of order.

**Comment by akaffenberger** [comment]
In case anyone is blocked, feel free to use my fork where the issue is fixed:
https://github.com/akaffenberger/Carthage#install
