### ISSUE TITLE
Using cached framework when trying to build xcframework

### ISSUE THREAD

**Issue by icedice** [Carthage/Carthage#3188]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`:  0.38
* `xcodebuild -version`: 12E262
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`?  NO
* Are you using `--cache-builds`? YES
* Are you using `--new-resolver`?  NO

If you first bootstrap/update a .framework with the `--use-cache` flag and then bootstraps/updates again with `--use-xcframework` and -`-use-cache` flags Carthage uses the cached .framework instead of building a .xcframework 

This is generally not going to be an issue, but it did give me a headache to figure out what was going on with our CI when we switched from using .framework to .xcframework

**Comment by elliottwilliams** [comment]
Yeah, that's right. We made the decision to have --cache-builds not discriminate between frameworks and xcframeworks. Does that feel like a bug / unexpected behavior?

Even if you have CI clear your Carthage/Build folder at the start of every job, I can imagine this behavior causes problems if, for instance, you update a project to integrate xcframeworks, and then a colleague pulls in your changes while the still have plain framework bundles in Carthage/Build.

**Comment by icedice** [comment]
It's not really an issue it's just something to be aware of.. is is documented anywere?

**Comment by elliottwilliams** [comment]
The only place I'm aware of is in [Migrating a project from framework bundles to XCFrameworks](https://github.com/Carthage/Carthage#migrating-a-project-from-framework-bundles-to-xcframeworks):

> 1. Delete your Carthage/Build folder to remove any existing framework bundles.

**Comment by icedice** [comment]
That should be enough, I have no idea how I missed that.
