### ISSUE TITLE
Support GitHub Enterprise as a first-class citizen

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#319]
Now that we support downloading binaries from GitHub Releases, there's a potentially significant difference between the `github` and `git` specifiers in a `Cartfile`.

Enterprise repositories can only be used over `git` right now, so we should find a way to make them more first-class.

**Comment by jspahrsummers** [comment]
Perhaps we could accommodate this by accepting URLs with the `github` specifier:

```
github "https://enterprise.local/desktop/git-error-translations"
```

This would be a superset of `git` behavior, because it would also fetch releases on the repository.

**Comment by mdiep** [comment]
That seems fine to me. :+1:

**Comment by angerman** [comment]
I've to admit I've not yet looked at the code, but it would be nice if the binary download feature would work with arbitrary repositories.
Could it not be sufficient, to point to a storage location, and have a fixed naming scheme for the release files?

**Comment by jspahrsummers** [comment]
@angerman GitHub Releases offers a nice API for introspecting release metadata and fetching binary assets. We're not interested in adding support for arbitrary download sources—see the previous discussion in https://github.com/Carthage/Carthage/issues/134.

**Comment by angerman** [comment]
@jspahrsummers I see. Fair enough. Would a proposal with a pull request be up for debate or, is this something that decision to never support anything but github releases set in stone?

**Comment by jspahrsummers** [comment]
Alternatives aren't _completely_ off the table, but they'd have to offer something worth the tradeoff in complexity (because supporting anything additional results in complexity). Note that there's currently a workaround available too: just [create a mirror repository that only hosts Releases](https://github.com/Carthage/Carthage/issues/134#issuecomment-64248664).

Anyways, if you're interested in discussing it more, could we maybe talk about it in #134 instead? Let's leave this issue specifically about GitHub Enterprise support.
