### ISSUE TITLE
binary download failure

### ISSUE THREAD

**Issue by springlo** [Carthage/Carthage#3190]
* `carthage version`:  0.38.0
* `xcodebuild -version`:  12.5
* Are you using `--no-build`? N 
* Are you using `--no-use-binaries`? N
* Are you using `--use-submodules`? N
* Are you using `--cache-builds`? N
* Are you using `--new-resolver`? N

**Cartfile**
```
binary "https://raw.githubusercontent.com/springlo/PubLibs/master/MTCobwebs.json"
```

**Carthage Output**
```
*** Downloading binary-only framework MTCobwebs at "https://raw.githubusercontent.com/springlo/PubLibs/master/MTCobwebs.json"
*** xcodebuild output can be found in /var/folders/t8/s_1wry8n6751ngplnwhzh__h0000gn/T/carthage-xcodebuild.kkYLH6.log
*** Downloading binary-only framework MTCobwebs at "https://raw.githubusercontent.com/springlo/PubLibs/master/MTCobwebs.json"
```

Build folder have nothing。

**Comment by datwelk** [comment]
Same issue here. Perhaps a compiler version mismatch between remote binary version and local compiler?

**Comment by springlo** [comment]
The compilation environment is consistent.

**Comment by Saravia83c** [comment]
#- - ```

```

**Comment by springlo** [comment]
Is there any solution?

**Comment by elliottwilliams** [comment]
Are you using --use-xcframeworks? I think we may have a bug in how the new binary version resolver selects what to download.

**Comment by elliottwilliams** [comment]
Hmm, I'm having trouble reproducing :( I can run:

```
emw@C02FC0RBQ05Q ~/Carthage> echo 'binary "https://raw.githubusercontent.com/springlo/PubLibs/master/MTCobwebs.json"' > Cartfile
emw@C02FC0RBQ05Q ~/Carthage> carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Downloading binary-only framework MTCobwebs at "https://raw.githubusercontent.com/springlo/PubLibs/master/MTCobwebs.json"
*** Downloading binary-only framework MTCobwebs at "https://raw.githubusercontent.com/springlo/PubLibs/master/MTCobwebs.json"
*** xcodebuild output can be found in /var/folders/qt/83cpf99j101_gkm4n6d67x68z90dks/T/carthage-xcodebuild.lkayXa.log
*** Downloading MTCobwebs binary at "5.4.2"
```

and it downloads to `Carthage/Build/iOS/MTCobwebs.framework`. Same works if I use `carthage bootstrap --use-xcframeworks`. Is there something I'm missing?

My system:
macOS 11.2 20D64 arm64
Xcode 12.4 12D4e

**Comment by springlo** [comment]
The zip was downloaded to the cache, but it was not unzip successfully.

**Comment by springlo** [comment]
```
*** No Cartfile.resolved found, updating dependencies
*** Downloading binary-only framework MTCobwebs at "https://raw.githubusercontent.com/springlo/PubLibs/master/MTCobwebs.json"
*** Downloading binary-only framework MTCobwebs at "https://raw.githubusercontent.com/springlo/PubLibs/master/MTCobwebs.json"
*** xcodebuild output can be found in /var/folders/t8/s_1wry8n6751ngplnwhzh__h0000gn/T/carthage-xcodebuild.hCsTiA.log
*** Downloading MTCobwebs binary at "5.4.2"
```
And nothing in `Carthage/Build/`.

**Comment by elliottwilliams** [comment]
Ah, I think @datwelk got it. When I switch to Xcode 12.5, it fails:

```
DEVELOPER_DIR=/Applications/Xcode-12.5.app/Contents/Developer/ carthage build --use-xcframeworks
*** Downloading binary-only framework MTCobwebs at "https://raw.githubusercontent.com/springlo/PubLibs/master/MTCobwebs.json"
*** xcodebuild output can be found in /var/folders/qt/83cpf99j101_gkm4n6d67x68z90dks/T/carthage-xcodebuild.atPoyp.log
*** Downloading MTCobwebs binary at "5.4.2"
Incompatible Swift version - framework was built with 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28) and the local version is 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55).
```

I'm not sure why you aren't seeing the error – maybe your stderr is being redirected somewhere weird? Regardless, this is an intentional limitation documented in the README: https://github.com/Carthage/Carthage#swift-binary-framework-download-compatibility

If you control this framework, you can make it work with Xcode 12.5 by rebuilding and uploading it. You can make the framework binary work with arbitrary Swift versions by building with module stability. See "Prefer building with module stability" https://github.com/Carthage/Carthage/releases/tag/0.38.0.

Closing now, if I missed something and you think this is a problem with Carthage, feel free to reopen!
