### ISSUE TITLE
Carthage Build error

### ISSUE THREAD

**Issue by ManjunathIOS** [Carthage/Carthage#3192]
Hi Team,

While building dependency through Carthage  I am getting  below error.

I am using Carthage Version : 0.38 and Xcode version : 12.5.
I have attached  terminal output file (Carthage_terminalError) and error log file (carthage-xcodebuild.r0HEqA.log).

Can anyone suggest  how to fix these..?

Thanks in Advance.

Error Details:

*** Building scheme "r2-shared-swift" in r2-shared-swift.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/manjunatha/MANJU\ DATA/WORKING/TESTING\ R2\ MANJU/XCODE\ 12.5/DUMMY\ PRJ/TestLibrarYFrmwrk/Carthage/Checkouts/r2-shared-swift/r2-shared-swift.xcodeproj -scheme r2-shared-swift -configuration Release -derivedDataPath /Users/manjunatha/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/r2-shared-swift/41ed31afbbf8b8baa9579a22db031e8d386ea1f5 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/fd/4tsd7t5j15s0z9k7098532y40000gp/T/r2-shared-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/manjunatha/MANJU DATA/WORKING/TESTING R2 MANJU/XCODE 12.5/DUMMY PRJ/TestLibrarYFrmwrk/Carthage/Checkouts/r2-shared-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/fd/4tsd7t5j15s0z9k7098532y40000gp/T/carthage-xcodebuild.r0HEqA.log

[Carthage_terminalError.docx](https://github.com/Carthage/Carthage/files/6582780/Carthage_terminalError.docx)
[carthage-xcodebuild.r0HEqA.log](https://github.com/Carthage/Carthage/files/6582783/carthage-xcodebuild.r0HEqA.log)

**Comment by muhasturk** [comment]
problem releated with `r2-shared-swift`. check that dependecy, seems not releated with carthage.

```
.../Carthage/Checkouts/r2-shared-swift/r2-shared-swift/Toolkit/XML/Fuzi.swift:13:8: error: no such module 'Fuzi'
```

**Comment by elliottwilliams** [comment]
I can't reproduce this. Here's the output of me running the same command: 
[carthage-update.txt](https://github.com/Carthage/Carthage/files/6601626/carthage-update.txt)

My system:
macOS 11.2 20D64 arm64
Xcode 12.4 12D4e

@ManjunathIOS are you still having trouble? I agree with the above, if there's a failure it looks like a problem with the project, not with Carthage.

**Comment by ManjunathIOS** [comment]
@elliottwilliams 
 yes. I am still facing issue. it was working fine before with older (Xcode,carthage,Mac OS) version.

but in (Carthage Version : 0.38, Xcode version : 12.5, Mac OS :11.4  ) version I am facing issue. its blocker for me .

**Comment by luesp15** [comment]
Same problem
