### ISSUE TITLE
How to use password for json file on remote?

### ISSUE THREAD

**Issue by eddysnjack** [Carthage/Carthage#3195]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.38.0
* `xcodebuild -version`: 12.5 (12E262)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
binary "https://<username>:<password>@<domain>/repository/myFramework.json" >= 2.0
```

**Command used**
```
carthage update --use-xcframeworks
```

**Carthage Output**
```
Parse error: invalid URL found for dependency type `binary` in line: binary "htt...
```

**Actual outcome**
Carthage can't access json file on private repo.

**Expected outcome**
Carthage should be able to access the file.

------
This method of authentication is suggested in #1973 and it worked for downloading zip files but it fail with carthage file. And i tried keychain but it didn't worked (not sure if i add it correctly though[I tried: File -> new pasword item -> filled out the fields -> Add]), also i have `.netrc` file in my user folder. i tried --use-netrc` but that one failed too. its content is something like:
```
machine my.domain.name
login <username>
password <password>
```
note:
machine value (my.domain.name) has no `http` prefix or something. just plain domain name. (google wasn't helpful about this detail so i am pointing to be sure if i am doing it right)

**Carthage Output --use-netrc**
```
Unable to parse binary-only framework JSON at https://<domain>/repository/myFramework.json due to error: invalid JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.})))

```

**Comment by elliottwilliams** [comment]
I'm not an expert on how Carthage's netrc implementation works, but I can see in the code that it _is_ used to download the binary spec json when `--use-netrc` is passed: https://github.com/Carthage/Carthage/blob/9a3d1799ba8f8b9e2d4514cfa53a2cca6064136e/Source/CarthageKit/Project.swift#L242

Are you sure you're successfully authenticating to the server? One way to check would be with curl: `curl --netrc "https://<domain>/repository/myFramework.json"` should get the json object.

You could also test by storing the json spec locally, and pointing to it with a file:// URL in your Cartfile like:

```
binary "file:///path/to/myFrameworks.json" > 2.0
```

That should reveal any other problems with the json spec (bad formatting, problems downloading the binary, etc). If it works there, then we've narrowed the problem down to Carthage talking to your server.
