### ISSUE TITLE
Submodules are not being re-fetched from Carthage's cache

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#320]
**Version:** 0.6

[ReactiveTask](https://github.com/Carthage/ReactiveTask) has a `Cartfile` that pins RAC to `swift-development`:

```
github "ReactiveCocoa/ReactiveCocoa" "swift-development"
github "Quick/Quick" == 0.2.0
github "Quick/Nimble"
github "Carthage/LlamaKit" == 0.1.1
github "jspahrsummers/xcconfigs" >= 0.6
```

Apparently because `swift-development` has changed since Carthage originally pinned it, updating to the latest fails:

```
$ carthage update --no-build --use-submodules
*** Fetching ReactiveCocoa
*** Fetching Quick
*** Fetching Nimble
*** Fetching LlamaKit
*** Fetching xcconfigs
*** Checking out LlamaKit at "v0.5.0"
*** Checking out Nimble at "v0.3.0"
*** Checking out Quick at "v0.2.2"
*** Checking out xcconfigs at "0.7.1"
*** Checking out ReactiveCocoa at "15c2c9a473f5bf09b79061f603cb122a257162e1"
fatal: reference is not a tree: 15c2c9a473f5bf09b79061f603cb122a257162e1
```

Carthage's cache does have that commit:

```
$ git --git-dir="$HOME/Library/Caches/org.carthage.CarthageKit/dependencies/ReactiveCocoa" show 15c2c9a473f5bf09b79061f603cb122a257162e1
commit 15c2c9a473f5bf09b79061f603cb122a257162e1
Merge: 5bc0ec0 0894d15
Author: Justin Spahr-Summers <jspahrsummers@github.com>
Date:   Fri Feb 13 20:42:30 2015 -0800

    Merge pull request #1746 from ReactiveCocoa/pr/1739
    
    zipWith (redux)
```

It's just the submodule repository that does not. This suggests that we're not correctly fetching from the global cache into the submodule.

One workaround is to `rm -rf Carthage/` and re-run `carthage update --use-submodules`.

**Comment by robrix** [comment]
That looks like it.

**Comment by mattrubin** [comment]
I ran into this as well. Running `git fetch` in the submodule is enough to make the next `carthage update` work correctly.

**Comment by fabiomassimo** [comment]
I'm having the same issue.
Even after I have deleted the `Carthage/` folder and the Carthage's Cache, the issue keeps showing up. The command I'm running is: 

`carthage update --platform iOS --use-submodules --no-use-binaries`

**Comment by mdiep** [comment]
@fabiomassimo Please open a new issue with the details of your problem. Thanks!
