### ISSUE TITLE
Even though I use --use-xcframeworks, .framework binary could be downloaded??

### ISSUE THREAD

**Issue by ryu1sazae** [Carthage/Carthage#3205]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`:/usr/local/bin/carthage
* `carthage version`: 0.38.0
* `xcodebuild -version`: Xcode 12.4 Build version 12D4e
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes
* Are you using `--new-resolver`? no
* Are you using `--new-resolver`? no
* Are you using `--use-xcframeworks`? yes

**Cartfile**
```
github "adjust/ios_sdk" == 4.26
```

**Carthage Output**
```
*** Fetching ios_sdk
*** Downloading ios_sdk binary at "Version 4.29.2"
```

**Actual outcome**
Even though I use --use-xcframeworks option at command and the selected library at Cartfile doesn't prepare .xcframework binary, if it has prepared .framework binary, Carthage try to download .framework binary.

This was the unexpected situation for me, but is this the expected situation for everyone other than me??

**Expected outcome**
In the case of using --use-xcframeworks option at command and the selected library at Cartfile doesn't prepare .xcframework binary, Carthage try to checkout framework which is not binary and  build as xcframework.
Carthage should not download .framework binary.

**command**
`$ carthage update --platform iOS --use-ssh --use-xcframeworks --cache-builds`

**Comment by iostiny** [comment]
@ryu1sazae I tried your Cartfile and execute `carthage update --platform iOS --use-ssh --use-xcframeworks --cache-builds`, and yes it get an .framework but not a .xcframeworks.

Don't know what's wrong with it. I am either against it issue.

**Comment by ikesyo** [comment]
That's because `adjust/ios_sdk`'s binaries don't contain xcframeworks. See https://github.com/adjust/ios_sdk/issues/505.
