### ISSUE TITLE
Don't build from Cartfile.private of fetched dependencies

### ISSUE THREAD

**Issue by Gurpartap** [Carthage/Carthage#321]
From `Artifacts.md`:

#### Cartfile.private
> Frameworks that want to include dependencies via Carthage, but **do not want to force those dependencies on parent projects**, can list them in the optional Cartfile.private file, identically to how they would be specified in the main Cartfile.
> 
> Anything listed in the private Cartfile will not be seen by dependent (parent) projects, which is useful for dependencies that may be important during development, but not when building releases—for example, test frameworks.

I'm sure a project with only ReactiveCocoa in its `Cartfile` doesn't need to build `Quick, Nimble or xcconfigs`, which are specified in ReactiveCocoa's `Cartfile.private` file (and are required for its tests target only).

Isn't building private sub-deps something we can skip, sticking with the reasoning of `Cartfile.private`'s existence defined above?

**Comment by Gurpartap** [comment]
Right now, Nimble is failing to build on my system for whatever reason. To counteract, I'm manually updating `Cartfile.resolved` to remove it and other private sub-dependencies, and then building with `carthage build`.

**Comment by jspahrsummers** [comment]
The behavior you're describing _is_ the behavior of `Cartfile.private`.

What's most likely happened is that you haven't specified any version constraint for ReactiveCocoa, so it's picking the unsupported [`swift-on-carthage-3.0.2`](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/swift-on-carthage-3.0.2). You can constrain to `~> 2.0` to fix that.

As a general rule of thumb, it's highly recommended that you have at least some sort of version constraint on your dependencies.

**Comment by Gurpartap** [comment]
Ah, I see. ReactiveCocoa v`swift-on-carthage-3.0.2`'s Cartfile includes all those deps. While off topic here, why is it set as such, if I may ask?

**Comment by Gurpartap** [comment]
Never mind, I see it has been fixed on `swift-development` branch!

**Comment by jspahrsummers** [comment]
No problem!
