### ISSUE TITLE
Dependency has no shared framework schemes. 

### ISSUE THREAD

**Issue by invinciible** [Carthage/Carthage#3229]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`:  0.38.0
* `xcodebuild -version`:  Xcode 12.5, Build version 12E262
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No 
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`?  No
* Are you using `--use-xcframeworks`? No 

**Cartfile**
```
git "https://private-repo-location.git" "master"
```

**Carthage Output**
```
Dependency "<Name>" has no shared framework schemes
```

**Actual outcome**
Unable to locate the scheme

**Expected outcome**
Should build and generate the framework file.

I'm trying to set up a couple of private repos with Carthage support. While I have updated the scheme to be shared but the `.xcodeproj` and `.xcworkspace" are in the nested folder of the repo and due to that reason it's not able to read the scheme to build the project. Is there a way to update the Cartfile to build the project from the nested folder of the repo after checking out? or any other setup can be done to avoid moving the files to the root directory of the repo?

**Comment by vanthanhtran245** [comment]
Edit your scheme and uncheck share and check again share scheme
