### ISSUE TITLE
.swiftsourceinfo is either malformed or generated by a different Swift version

### ISSUE THREAD

**Issue by jayahariv** [Carthage/Carthage#3238]
* `which carthage`: /usr/local/bin/carthage
* `carthage version`:  0.38.0
* `xcodebuild -version`: Xcode 13.0 13A233
* Are you using `--use-xcframeworks`?  YES

command used: 
```
carthage build archive --project-directory <dir> --platform "ios, macos" --no-skip-current --configuration <config>  --use-xcframeworks
```

**Actual outcome**
xcframework > ios-arm64_i386_x86_64-simulator > Modules > .swiftmodule > Project > .swiftsourceinfo 

which causes the warning when used in Xcode 13
```
.swiftmodule/Project/x86_64-apple-ios-simulator.swiftsourceinfo' is either malformed or generated by a different Swift version.
```

<img width="838" alt="Screen Shot 2021-10-21 at 5 56 09 AM" src="https://user-images.githubusercontent.com/10448770/138282570-534d5b03-df70-4dc6-a756-d991fa218850.png">

**Expected outcome**
No warning in Xcode, probably without the .swiftsourceinfo? When creating the XCFramework with `xcodebuild archive` is not including the swift-source-info files. 
https://stackoverflow.com/a/69379126

Could you please share your thoughts?

**Comment by GermanVelibekovHouzz** [comment]
Same here. @3232 However, I can't see the `baseArguments` command shown in build logs. 
This is a `xcodebuild` command from logs:

```
/usr/bin/xcrun xcodebuild 
-project <path-to-project>Carthage/Checkouts/Starscream/Starscream.xcodeproj 
-scheme Starscream 
-configuration Release 
-derivedDataPath <my-user>/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/Starscream/3.1.0 
-sdk iphoneos 
ONLY_ACTIVE_ARCH=NO 
CODE_SIGNING_REQUIRED=NO 
CODE_SIGN_IDENTITY= CARTHAGE=YES 
archive # <---- archive
VALIDATE_WORKSPACE=NO 
-archivePath /var/folders/2s/c8z_jl_j0r14sh5nzq1gtwq80000gn/T/Starscream 
SKIP_INSTALL=YES 
GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO 
CLANG_ENABLE_CODE_COVERAGE=NO 
STRIP_INSTALLED_PRODUCT=NO 
```
