### ISSUE TITLE
No xcframework without --use-xcframeworks

### ISSUE THREAD

**Issue by battlmonstr** [Carthage/Carthage#3239]
* carthage install method: [ x ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.38.0
* `xcodebuild -version`: Xcode 13.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes
* Are you using `--new-resolver`? no
* Are you using `--use-xcframeworks`? no

**Cartfile**
```
binary "https://raw.githubusercontent.com/krzyzanowskim/OpenSSL/master/OpenSSL.json" ~> 1.1.1200
```

**Carthage Output**
```
$ carthage build --cache-builds OpenSSL
*** xcodebuild output can be found in /var/folders/10/tb7r35sd2yqdykptkm3tqhcw0000gn/T/carthage-xcodebuild.IN4yes.log
*** Invalid cache found for OpenSSL, rebuilding with all downstream dependencies
*** Downloading binary-only framework OpenSSL at "https://raw.githubusercontent.com/krzyzanowskim/OpenSSL/master/OpenSSL.json"
```

**Actual outcome**
The Carthage/Build directory doesn't contain OpenSSL.xcframework.

**Expected outcome**
Carthage should copy OpenSSL.xcframework into the Carthage/Build directory as if running with "--use-xcframeworks". This works:

    carthage build --cache-builds --use-xcframeworks OpenSSL

**Reasoning**

This json contains only xcframework (no `?alt=`). If we build everything with `carthage bootstrap`, the xcframework is not copied.
AFAIK if the `--use-xcframeworks` option is passed, but .xcframework is not found, carthage tries to use .framework.
So this is the reverse situation: if `--use-xcframeworks` is not passed, but .framework is not found, it should try to use .xcframework.

We'd like to switch to `--use-xcframeworks` for all dependencies, but this is a big task. Ideally we'd like to upgrade to `--use-xcframeworks` piecemeal where we can control this preference per dependency. I haven't found such an option.

**Comment by tmspzz** [comment]
Run the command twice. Once with --use-xcframeworks and once without.

**Comment by tmspzz** [comment]
More precisely altering the behavior of a "vanilla" command isn't advisable. It might be a behavior that you expect, but that many others will not.

**Comment by battlmonstr** [comment]
👌 we've migrated to `--use-xcframeworks` for all.
