### ISSUE TITLE
Review CarthageKit API organization

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#324]
Are there instance/class/static methods which should instead be functions, or vice-versa? We should make sure that it all fits together conceptually.

**Comment by flovilmart** [comment]
That would be interesting as well to not expose ReactiveCocoa signals outside the CarthageKit API so one programmer could easily extend the CarthageKit without the need of ReactiveCocoa

**Comment by jspahrsummers** [comment]
ReactiveCocoa is going to be a CarthageKit dependency, no matter what. If it's not exposed in the API, then you still have the dependency, but you've lost all the composability it provides.

**Comment by robrix** [comment]
Yeah, anything we’d use in place of RAC in the interfaces would be much worse than RAC.
