### ISSUE TITLE
Unable to parse binary-only framework JSON

### ISSUE THREAD

**Issue by ankit0409** [Carthage/Carthage#3240]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`:
* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 
* Are you using `--use-xcframeworks`? 

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```

**Actual outcome**
Carthage did or did not ...

**Expected outcome**
Carthage should ...

**Comment by ankit0409** [comment]
Xcode version is 12.5
Carthage version 0.38.0

**Comment by tmspzz** [comment]
Neither jsons are public. Can you provide a sample?

**Comment by ankit0409** [comment]
Yes It is my private repository on gitpub

**Comment by ankit0409** [comment]
> Neither jsons are public. Can you provide a sample?
Yes It is my private repository on gitpub

**Comment by ankit0409** [comment]
> Neither jsons are public. Can you provide a sample?

Yes It is my private repository on gitpub

**Comment by tmspzz** [comment]
> > Neither jsons are public. Can you provide a sample?
> 
> Yes It is my private repository on gitpub

So you can't provide a sample?

**Comment by ankit0409** [comment]
> > > Neither jsons are public. Can you provide a sample?
> > 
> > 
> > Yes It is my private repository on gitpub
> 
> So you can't provide a sample?

Yes, Could you provide some solution or any idea.

**Comment by vanthanhtran245** [comment]
Seems it's your private host to store json file. You should using addtional command --use-netrc. Also you must be setup .netrc file first

**Comment by ankit0409** [comment]
Hello Carthage/Carthage

Could you please give proper steps for this. I do not understand what I
should do here. I using only below command
*carthage update --platform iOS*
It will be great if you provide me proper steps.

**Comment by ankit0409** [comment]
> curl -X GET https://where-your-json.is.com/file.json

I got following error 404: Not Found
