### ISSUE TITLE
Need help adding carthage dependencies to a React Native package I am authoring.

### ISSUE THREAD

**Issue by sinewave440hz** [Carthage/Carthage#3241]
* carthage install method: [ ] .pkg, [*] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthageca`
* `carthage version`: 0.38.0
* `xcodebuild -version`: Xcode 13.1, Build version 13A1030d
* Are you using `--no-build`? no 
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no
* Are you using `--use-xcframeworks`? yes

**Cartfile**

Similar to actual proprietary file:
```
github "Company/iOSClientPlayer"
github "Company/iOSClientSupport"
github "Company/iOSClientSupportPlayback" "master"
```

**Carthage Output**

I have generated this project, as I usually do using [create-react-native-library](https://github.com/callstack/react-native-builder-bob). I have adapted this to work correctly with tvOS.

I then followed the instructions for adapting carthage to tvOS. I set up the cartfile in the iOS directory of the package (not it's example app). However, there is no possibility to add the frameworks in the package's Xcode project, it doesn't have that option - there is no General tab or any possibility anywhere that I can see for adding the frameworks.

Carthage builds without errors  when installing into the package's subdirectory.

**Actual outcome**
I have previously used the same cartfile in a new (non-react-native) tvOS project and got it successfully building.
When trying to add the same cartfile into my package's iOS folder I get build errors to do with missing files inside one of the xcframework dependencies.

**Expected outcome**
Without getting too specific in my proprietary code, I'm hoping to get help as to how to go about using a cocoa pods based library project such as that generated by create-react-native-library (the option I used was a UI component with swift and an embedded example project) with dependencies made available by carthage. I will open a related issue on the create-react-native-library repo and hopefully get help from both sides. I am convinced that this will be of value to others, given the popularity of all related technologies. Thanks, and let me know if you need any more specific info.

**Comment by tmspzz** [comment]
Can you post a screenshot of where you are trying to add the frameworks?
