### ISSUE TITLE
Invalid Bundle when processing to TestFlight with Carthage framework added

### ISSUE THREAD

**Issue by alekkania** [Carthage/Carthage#3242]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.38.0
* `xcodebuild -version`: Xcode 12.5 Build version 12E262
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no
* Are you using `--use-xcframeworks`? yes

**Cartfile**
```
Can't share - private framework
```

**Actual outcome**
I have an my own framework added by Carthage to the project. Everything build and works fine until I want to send my project to TestFlight. 
I receive an error from AppStoreConnect:
`TMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.`
It was happen after I start to use --use-xcframeworks option in Carthage. 

**Expected outcome**
I am able to pass processing phase in AppStore

**Comment by tmspzz** [comment]
Have you checked `FRAMEWORK_SEARCH_PATHS`?

Carthage doesn't touch your project files, at a first glance this is a problem with your setup.

**Comment by alekkania** [comment]
@tmspzz Yes, I have „Carthage/Build” in Search paths.

**Comment by tmspzz** [comment]
> @tmspzz Yes, I have „Carthage/Build” in Search paths.

Did you Drag and Drop the .xcframework in your project as specified in the readme https://github.com/Carthage/Carthage#adding-frameworks-to-an-application
