### ISSUE TITLE
Carthage build produces random results with RxSwift

### ISSUE THREAD

**Issue by BaptisteSansierra** [Carthage/Carthage#3243]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.38.0
* `xcodebuild -version`: Xcode 13.0
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no
* Are you using `--use-xcframeworks`? yes

**Cartfile**
```
github "ReactiveX/RxSwift" "6.2.0"
```

**Carthage Output**
```
*** Checking out RxSwift at "6.2.0"
*** xcodebuild output can be found in /var/folders/6q/vtm_kkc90mg94gnfcy977bkr0000gp/T/carthage-xcodebuild.QJSPzy.log
*** Downloading RxSwift binary at "Ethan.2"
```

**Actual outcome**
Carthage randomly creates one of the following :
- RxBlocking.xcframework
- RxCocoa.xcframework
- RxCocoaRuntime.xcframework
- RxRelay.xcframework
- RxSwift.xcframework

**Expected outcome**
Carthage should behaves the same at each call, RxSwift.xcframework should be created always.

_Note_ : I can produce expected framework by adding --no-use-binaries

**Comment by tokou** [comment]
I have the same issue.
This seems to be due to 

- Carthage deciding to download binaries instead of building from source (expected)
- Binaries failing to download because of rate limiting (happens often on Bitrise)
- Carthage skipping the binaries entirely instead of fallbacking on building from source
- It's obviously fixed when using `--no-use-binaries` as there's no failing download

```
*** No cache found for realm-cocoa, building with all downstream dependencies
...
*** Skipped downloading realm-cocoa binary due to the error:
	"API rate limit exceeded for 207.254.33.184. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"
...
(No mention of building scheme realm-cocoa below) 
```
