### ISSUE TITLE
[Question] Will `carthage update [framework]` rebuild from scratch? 

### ISSUE THREAD

**Issue by heefan** [Carthage/Carthage#3247]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: `0.38.0`
* `xcodebuild -version`:  `Xcode 12.5.1`
* Are you using `--no-build`?   No
* Are you using `--no-use-binaries`?  No
* Are you using `--use-submodules`?  No
* Are you using `--cache-builds`?  No
* Are you using `--new-resolver`? No
* Are you using `--use-xcframeworks`?  Yes

**Cartfile**
```
binary "https://somewhere/xxx.framework.json" == 2.3.0
```

**Carthage Output**
```
Downloading binary-only framework.....
....
Building scheme
.....
```

**Actual outcome**
Build all the dependencies. 

**Expected outcome**
Only build the one I gave. 

-------
I supposed to add a **xxx** framework to my project with the following command, 
`$carthage update xxxx --platform iOS --use-xcframeworks` 
By right, it should only download the **xxx** framework binary, however, it took long time to download, rebuild everything.  

Do I miss out something?  Is it caused by `--use-xcframeworks` flag?

**Comment by tmspzz** [comment]
`--cache-builds`
