### ISSUE TITLE
React Native Android Build Failure. A problem occurred configuring project ':react-native-vector-icons'

### ISSUE THREAD

**Issue by Avinashreddy777** [Carthage/Carthage#3249]
For the last few days React native Android build getting failed. Build stops with error while configuring react-native-vector-icons.
Tried different solutions like upgrading to the latest version. Changing the Android  project level build.gradle (Replacing mavenlocal() to mavenCentral() and jcenter() to mavenCentral()).

Complete error detials:

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details. Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

What went wrong: A problem occurred configuring project ':react-native-vector-icons'.
Could not resolve all artifacts for configuration ':react-native-vector-icons:classpath'. Could not resolve com.android.tools.build:gradle:3.3.1. Required by: project :react-native-vector-icons > Could not resolve com.android.tools.build:gradle:3.3.1. > Could not get resource 'https://dl.bintray.com/android/android-tools/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.pom'. > Could not GET 'https://dl.bintray.com/android/android-tools/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.pom'. Received status code 502 from server: Bad Gateway.

Project level build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        // googlePlayServicesVersion = "16.0.0" //Add this
        // firebaseVersion = "17.0.0" //Add this
    }
    repositories {
        google()
        maven { url 'https://maven.google.com' }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

// https://github.com/react-native-community/react-native-image-picker/issues/999#issuecomment-445501130
subprojects {project ->
    if (project.name.contains('react-native-svg') ||
        project.name.contains('react-native-vector-icons') ||
        project.name.contains('rn-fetch-blob')) {
            buildscript {
                repositories {
                maven { url "https://dl.bintray.com/android/android-tools/"  }
            }    
        }
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
            maven { url 'https://maven.google.com' }
            maven { url "https://jitpack.io" }
        }
    }
}

Any comments and solutions are appreciated .
please help me to come out of it.

**Comment by tmspzz** [comment]
This is not the correct repo for this question. Closing.
