### ISSUE TITLE
Carthage GitHub issue Git unauthenticated

### ISSUE THREAD

**Issue by jesus-mg-ios** [Carthage/Carthage#3250]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: 
* `carthage version`:  0.38
* `xcodebuild -version`: 
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`?  no
* Are you using `--new-resolver`?  no
* Are you using `--use-xcframeworks`? no

**Cartfile.resolved**
```
github "facebookincubator/SocketRocket" "0.5.1"
```

**Carthage Output**
```
A shell task (/usr/bin/env git clone --quiet git://github.com/square/SocketRocket.git path/path) failed with exit code 128:
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

![image](https://user-images.githubusercontent.com/85997060/148983980-30680cf5-9b70-4e58-af62-e7c004c5af43.png)

**Comment by tmspzz** [comment]
```
git://github.com/square/SocketRocket.git
```

The url that is failing is not directly related to the dependency you pasted. Carthage is resolving 

```
github "facebookincubator/SocketRocket" "0.5.1"
```

by default to `https:\\...`


I cannot reproduce the problem.

**Comment by jesus-qt** [comment]
Thanks for your response @tmspzz it only was reproduced in January 11th, Seems that it is going to fail always starting from march of this year.

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/85997060/150524215-00d8c661-24a7-445e-9b00-0172f625d4c1.png">

**Comment by tmspzz** [comment]
@jesus-qt yes, I understand. 

However it does not seem to be the case that Carthage is using `git://` as scheme (unless instructed to do so, e.g. There in an explicit `"git"` dependency).

In the Cartfile you have shown as example the dependency is 

```
github "facebookincubator/SocketRocket" "0.5.1"
```

This makes it so that Carthage accesses the repo via `https:\\`


moreover, in you report there is a discrepancy. If you check the dependency, it says

__facebookincubator__/SocketRocket
But the access error is from 
__square__/SocketRocket

**Comment by jesus-qt** [comment]
In whatever case, there was a bug with it, if carthage made a git to another repository in that case, sounds weird but it happened.

**Comment by tmspzz** [comment]
I see. I don't beloved this is Carthage issue tho. You need to change the access scheme to ssh in the submodule file.
