### ISSUE TITLE
Building ThinkingDataAnalytics/ios-sdk fails

### ISSUE THREAD

**Issue by pen110** [Carthage/Carthage#3252]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`:/usr/local/bin/carthage
* `carthage version`: 0.38.0
* `xcodebuild -version`: 13.2.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  no
* Are you using `--new-resolver`?  no
* Are you using `--use-xcframeworks`?  yes

**Cartfile**
github "ThinkingDataAnalytics/ios-sdk" ~> 2.7.4

**Carthage Output**

*** Building scheme "ThinkingSDK" in ThinkingSDK.xcworkspace Build Failed 	Task failed with exit code 65: 	

/usr/bin/xcrun xcodebuild -workspace /Users/panxin/Desktop/Testcarthage/Carthage/Checkouts/ios-sdk/ThinkingSDK.xcworkspace -scheme ThinkingSDK -configuration Release -derivedDataPath /Users/panxin/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2.1_13C100/ios-sdk/v2.7.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/pj/4ttjb5cn5b9dq5_2ytllcysc0000gn/T/ios-sdk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/panxin/Desktop/Testcarthage/Carthage/Checkouts/ios-sdk)  This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/pj/4ttjb5cn5b9dq5_2ytllcysc0000gn/T/carthage-xcodebuild.er8HYX.log

<OUTPUT>
*** Building scheme "ThinkingSDK" in ThinkingSDK.xcworkspace Build Failed 	Task failed with exit code 65: 
	/usr/bin/xcrun xcodebuild -workspace /Users/panxin/Desktop/Testcarthage/Carthage/Checkouts/ios-sdk/ThinkingSDK.xcworkspace -scheme ThinkingSDK -configuration Release -derivedDataPath /Users/panxin/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2.1_13C100/ios-sdk/v2.7.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/pj/4ttjb5cn5b9dq5_2ytllcysc0000gn/T/ios-sdk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/panxin/Desktop/Testcarthage/Carthage/Checkouts/ios-sdk)  This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/pj/4ttjb5cn5b9dq5_2ytllcysc0000gn/T/carthage-xcodebuild.er8HYX.log

**Actual outcome**
Carthage did or did not ...

**Expected outcome**
Carthage should ...

**Comment by tmspzz** [comment]
Have you checked the build log at 

`/var/folders/pj/4ttjb5cn5b9dq5_2ytllcysc0000gn/T/carthage-xcodebuild.er8HYX.log`

for what is going wrong?
