### ISSUE TITLE
carthage build fails because "error: use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'"

### ISSUE THREAD

**Issue by arielelkin** [Carthage/Carthage#3257]
* carthage install method: homebrew
* `which carthage`: /usr/local/bin/carthage
* `carthage version`:  0.38.0
* `xcodebuild -version`:  Xcode 13.2.1

I'm trying to support Carthage in my open source library [PocketSVG](https://github.com/pocketsvg/PocketSVG/). This is what happens if I run `carthage build` in its root:

```
$ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/13/jh62fb214m394xbztdjkl2vm0000gn/T/carthage-xcodebuild.IlipHm.log
*** Building scheme "PocketSVG-Package" in PocketSVG.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/me/PocketSVG/derived_data/PocketSVG.xcodeproj -scheme PocketSVG-Package -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/13/jh62fb214m394xbztdjkl2vm0000gn/T/PocketSVG SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/arielelkin/PocketSVG)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/13/jh62fb214m394xbztdjkl2vm0000gn/T/carthage-xcodebuild.IlipHm.log
```

[Note that the project compiles and archives fine](https://github.com/pocketsvg/PocketSVG/runs/4506047661?check_suite_focus=true) without Carthage. 

Carthage's log shows that the compilation error happened here:

```
SVGEngine.mm:886:23: error: use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'
```

[Here's the specific line](https://github.com/pocketsvg/PocketSVG/blob/master/Sources/SVGEngine.mm#L886).

Seems like Carthage is defining the `SWIFT_PACKAGE` macro but not the `SWIFTPM_MODULE_BUNDLE` macro... I would expect either both or none to be defined by Carthage..

Any thoughts?

**Comment by tmspzz** [comment]
A quick code search reveals no mention in the code of neither macros. 

Have you checked the build log for the complete invocation?

**Comment by arielelkin** [comment]
These two macros are normally set by SPM when you build a Swift package (eg when using `swift build`). Looks like Carthage is somehow setting one of them?

**Comment by tmspzz** [comment]
> These two macros are normally set by SPM when you build a Swift package (eg when using `swift build`). Looks like Carthage is somehow setting one of them?

To my knowledge, it's not. Unless these can be specified somehow in your .xcproj or .xcworkspace and added to the default invocations

**Comment by arielelkin** [comment]
Even if it is a new behaviour in Xcode 13, it's not viable to use for us to Xcode 12 just to support Carthage.

This macro is definitely added when using SPM:
https://github.com/apple/swift-package-manager/blob/559fe961cca060727fac17c7f3876af884438b89/Documentation/Usage.md#packaging-legacy-code

This is a problem as building a package with Carthage and SPM simultaneously doesn't make sense.

**Comment by tmspzz** [comment]
> Even if it is a new behaviour in Xcode 13, it's not viable to use for us to Xcode 12 just to support Carthage. 

I never said it should be viable 😅 I was trying to get to HOW/WHO is adding this macro.

**Comment by arielelkin** [comment]
what if Carthage were to just do an `#undef SWIFT_PACKAGE` ?

**Comment by tmspzz** [comment]
> what if Carthage were to just do an `#undef SWIFT_PACKAGE` ?

Well, I guess that would be the most direct path. I'm not sure of the consequences for others tho.

**Comment by arielelkin** [comment]
OK, what do you suggest can be done for `carthage build` to work with https://github.com/pocketsvg/PocketSVG/ ?

**Comment by tmspzz** [comment]
If I remember correctly, Carthage does pass a `-D CARTHAGE` to all invocations.

Have you tried `#if CARTHAGE` ?

**Comment by arielelkin** [comment]
I ended up editing it thus:

```swift
#ifdef SWIFTPM_MODULE_BUNDLE
        NSURL *url = [SWIFTPM_MODULE_BUNDLE URLForResource:@"SVGColors" withExtension:@"plist"];
```

thanks for your help!
