### ISSUE TITLE
Binary xcframework is not linked in Xcode project

### ISSUE THREAD

**Issue by krzyzanowskim** [Carthage/Carthage#3258]
* carthage install method: [ ] .pkg, [x] homebrew, [x] source
* `which carthage`:
* `carthage version`: 0.38.0, I tried today's `master` branch too.
* `xcodebuild -version`: Xcode 13.2.1
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No
* Are you using `--use-xcframeworks`? Yes 

**Cartfile**
```
binary "/Users/marcinkrzyzanowski/Devel/foo/test/framework-spec.json" == 0.0.0-dummy20220202
```

**Carthage Output**

```
*** Downloading binary-only framework framework-spec at "file:///Users/marcinkrzyzanowski/Devel/foo/test/framework-spec.json"
*** xcodebuild output can be found in /var/folders/5b/s1q90k655dg41bwfvwrmkw_c0000gn/T/carthage-xcodebuild.0HCcYR.log
*** Downloading binary-only framework framework-spec at "file:///Users/marcinkrzyzanowski/Devel/foo/test/framework-spec.json"
```

**Actual outcome**
Xcode project links a non-existing `.framework` instead of downloaded `.xcframework`

<img width="956" alt="Screen Shot 2022-02-02 at 21 41 07" src="https://user-images.githubusercontent.com/758033/152234040-de700f70-98a5-48f1-a9e8-da41b75745a2.png">

<img width="325" alt="Screen Shot 2022-02-02 at 21 42 22" src="https://user-images.githubusercontent.com/758033/152234126-6fdd1fc6-949d-4acb-b300-ad23f8e824e7.png">

**Expected outcome**
Carthage should link to downloaded `.xcframework`

**Comment by tmspzz** [comment]
I'm not sure I follow. It's for the user to drag & drop the correct framework/xcframework

https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

**Comment by krzyzanowskim** [comment]
I got confused and my issue is not due to Carthage. My apology. Closing this one.
