### ISSUE TITLE
Carthage can modify the target version?

### ISSUE THREAD

**Issue by ShenYj** [Carthage/Carthage#3265]
* carthage install method: homebrew
* `which carthage`:
* `carthage version`: 0.38.0
* `xcodebuild -version`: 13.3
* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  yes
* Are you using `--new-resolver`?  no
* Are you using `--use-xcframeworks`?  no

**Cartfile**
```
set -euo pipefail

## For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
## the build will fail on lipo due to duplicate architectures.

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

CURRENT_XCODE_VERSION="$(xcodebuild -version | grep "Xcode" | cut -d' ' -f2 | cut -d'.' -f1)00"
CURRENT_XCODE_BUILD=$(xcodebuild -version | grep "Build version" | cut -d' ' -f3)

echo "EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_${CURRENT_XCODE_VERSION}__BUILD_${CURRENT_XCODE_BUILD} = i386 arm64 arm64e armv7 armv7s armv6 armv8" >> $xcconfig

echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_'${CURRENT_XCODE_VERSION}' = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_$(XCODE_VERSION_MAJOR)__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage "$@"
```

used by

```
./scripts/carthage.sh bootstrap --platform iOS --cache-builds
```

**Actual outcome**

the xcframework builded by Carthage modify the mimimum target to 12.0

here is the information:
https://github.com/RxSwiftCommunity/RxGesture/issues/131

**Comment by ikesyo** [comment]
RxGestures's deployment target is 12.0 since [4.0.0](https://github.com/RxSwiftCommunity/RxGesture/releases/tag/4.0.0).

ref: https://github.com/RxSwiftCommunity/RxGesture/pull/117

**Comment by ShenYj** [comment]
> RxGestures's iOS deployment target is 12.0 since [4.0.0](https://github.com/RxSwiftCommunity/RxGesture/releases/tag/4.0.0).
> 
> ref: [RxSwiftCommunity/RxGesture#117](https://github.com/RxSwiftCommunity/RxGesture/pull/117)

thanks!

but I can use RxGesture by CocoaPods，why Carthage can not?  
And the compatible tweaks this time around are weird

Let me check it out myself, and finally thanks again！

**Comment by ikesyo** [comment]
Carthage builds the framework using `RxGesture.xcodeproj` and it's `IPHONEOS_DEPLOYMENT_TARGET` is `12.0`: https://github.com/RxSwiftCommunity/RxGesture/blob/1b137c576b4aaaab949235752278956697c9e4a0/RxGesture/RxGesture.xcodeproj/project.pbxproj#L504.

On the other hand, CocoaPods uses the configuration defined in `RxGesture.podspec` and it's deployment target setting is `9.0`: https://github.com/RxSwiftCommunity/RxGesture/blob/1b137c576b4aaaab949235752278956697c9e4a0/RxGesture.podspec#L25.

I recommend you for requesting the maintainers to lower the deployment target.
