### ISSUE TITLE
In Xcode 14, Carthage does not create tvOS & watchOS builds when Bitcode is disabled

### ISSUE THREAD

**Issue by daltonclaybrook** [Carthage/Carthage#3292]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/opt/homebrew/bin/carthage`
* `carthage version`: 0.38.0
* `xcodebuild -version`: Xcode 14.0 - Build version 14A5270f
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No
* Are you using `--use-xcframeworks`? Yes

**Actual outcome**
The final XCFramework produced by Carthage contains a `tvos-arm64_x86_64-simulator` folder, but not a `tvos-arm64` folder. This is occurring because Bitcode is disabled by default on tvOS targets in Xcode 14, but Carthage [filters out the `appletvos` sdk](https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Xcode.swift#L696-L701) if Bitcode is disable because it assumes Bitcode is required for Apple TV. This is no longer true in Xcode 14.

**Expected outcome**
Carthage should still build products for the `appletvos` and `watchos` sdks when Bitcode is disabled and Xcode 14 is selected.

**Comment by lukegardiner** [comment]
Can this PR get merged and released soon now that Xcode 14 is officially out and auto-updating through the Mac App Store?

**Comment by giginet** [comment]
Sorry for waiting for you to merge #3293. This issue would be fixed.

**Comment by Aburupa1389** [comment]
> * carthage install method: [ ] .pkg, [x] homebrew, [ ] source
> * `which carthage`: `/opt/homebrew/bin/carthage`
> * `carthage version`: 0.38.0
> * `xcodebuild -version`: Xcode 14.0 - Build version 14A5270f
> * Are you using `--no-build`? No
> * Are you using `--no-use-binaries`? No
> * Are you using `--use-submodules`? No
> * Are you using `--cache-builds`? No
> * Are you using `--new-resolver`? No
> * Are you using `--use-xcframeworks`? Yes
> 
> **Actual outcome** The final XCFramework produced by Carthage contains a `tvos-arm64_x86_64-simulator` folder, but not a `tvos-arm64` folder. This is occurring because Bitcode is disabled by default on tvOS targets in Xcode 14, but Carthage [filters out the `appletvos` sdk](https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Xcode.swift#L696-L701) if Bitcode is disable because it assumes Bitcode is required for Apple TV. This is no longer true in Xcode 14.
> 
> **Expected outcome** Carthage should still build products for the `appletvos` and `watchos` sdks when Bitcode is disabled and Xcode 14 is selected.

**Comment by Sanatech09** [comment]
![Uploading 17251253324705545580070049064761.jpg…]()
