### ISSUE TITLE
xcframework error when xcode upgrade

### ISSUE THREAD

**Issue by TsnumiDC** [Carthage/Carthage#3298]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: /opt/homebrew/bin/carthage
* `carthage version`: 0.38.0
* `xcodebuild -version`: 
* Are you using `--no-build`? Xcode 13.1
Build version 13A1030d
* Are you using `--no-use-binaries`? yes
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 
* Are you using `--use-xcframeworks`? yes

**Cartfile**
```
github "ReactiveX/RxSwift" == 5.1.1
```

**Carthage Output**
```
all success
```

**Actual outcome**
i build xcframework , but when i upgrade xcode ,  it still have a error that 
'module compiled with swift 5.5.1 cannot be imported by the swift 5.7 compiler'

**Expected outcome**
xcframework is stable for swift version, why have this error?
i try build 'rxswift' by my self and make a xcframework, in high swfit version is build success

**Comment by mikchmie** [comment]
Swift 5.7 is part of Xcode 14 beta. If you want to use binaries built by Carthage in Xcode 14, you need to make Carthage use Xcode 14's compiler. You can do this either in Xcode: `Preferences -> Locations -> Command Line Tools` or in Terminal using `xcode-select` command, e.g.: 
```
xcode-select -s <path_to_xcode_14_beta>
```

**Comment by TsnumiDC** [comment]
thanks for your reply
framework which need support mutable swift version need set 'build librarys for distribution' in build setting
so i change it in the target's build setting then it work

**Comment by TsnumiDC** [comment]
thanks for your reply
framework which need support mutable swift version need set 'build librarys for distribution' in build setting
so i change it in the target's build setting then it work
so the error not make by carthage
