### ISSUE TITLE
Weird issue when using Homebrew to install 0.6

### ISSUE THREAD

**Issue by remaerd** [Carthage/Carthage#330]
Hello,

I experienced weird issues when trying to use the homebrew version of carthage. When the install is completed, it shows ```0.5.3``` when I type ```carthage version```. But I'm actually installing 0.6.

And when I try to update my dependencies. It occurs following errors.

```
dyld: lazy symbol binding failed: Symbol not found: __TFC11CarthageKit7Project44buildCheckedOutDependenciesWithConfigurationfS0_FTSS11forPlatformGSqOS_8Platform__TGC13ReactiveCocoa9HotSignalCSo6NSData_GVS2_10ColdSignalGS5_TOS_14ProjectLocatorSS____
  Referenced from: /usr/local/bin/carthage
  Expected in: /Library/Frameworks/CarthageKit.framework/CarthageKit

dyld: Symbol not found: __TFC11CarthageKit7Project44buildCheckedOutDependenciesWithConfigurationfS0_FTSS11forPlatformGSqOS_8Platform__TGC13ReactiveCocoa9HotSignalCSo6NSData_GVS2_10ColdSignalGS5_TOS_14ProjectLocatorSS____
  Referenced from: /usr/local/bin/carthage
  Expected in: /Library/Frameworks/CarthageKit.framework/CarthageKit
```

After reinstall carthage 0.6 with the pkg file. Problem solved. I think maybe there's some issue about the homebrew/carthage.

**Comment by jspahrsummers** [comment]
Did you previously install Carthage using the `.pkg`? If so, you might still have remnants of it on your system.

Can you please try:

```sh
rm -rf /Library/Frameworks/CarthageKit.framework
rm -f /usr/local/bin/carthage
```

… and then try `brew update && brew install carthage` again? Does that fix the issue?

**Comment by remaerd** [comment]
Yes, I do install Carthage using .pkg before. And I only delete the /usr/local/bin/carthage but unaware of the CarthageKit.framework. Problem solved.

I assume homebrew do not allow us to delete these two files when installing carthage with homebrew? It would be nice to check if they're exist. And delete them when updating to a new version.

Thank you.

**Comment by jspahrsummers** [comment]
> I assume homebrew do not allow us to delete these two files when installing carthage with homebrew? It would be nice to check if they're exist. And delete them when updating to a new version.

Hmm, I don't know if this would be accepted or not. You could always try submitting a pull request [to the formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/carthage.rb) and seeing what they say. :smile:
