### ISSUE TITLE
Missing Intel Architecture for 0.39.0 Package

### ISSUE THREAD

**Issue by rmigneco** [Carthage/Carthage#3323]
* carthage install method: [x] .pkg, [ ] homebrew, [ ] source
* `which carthage`: `usr/local/bin/carthage`
* `carthage version`: `0.39.0`
* `xcodebuild -version`:  n/a
* Are you using `--no-build`?  
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 
* Are you using `--new-resolver`? 
* Are you using `--use-xcframeworks`? 

**Actual outcome**
Running `carthage --version` produces terminal error for Bad CPU

**Expected outcome**
Running `carthage --version` should produce the version number as expected

**Notes **
- Reverting back to 0.38.0 indicates that it is an issue with the .pkg for 0.39.0
- There is no issue installing via homebrew

**Comment by snayrouz** [comment]
Same issue

**Comment by giginet** [comment]
I released this. I guess `make package` doesn't care about architecture.
I'll fix this.

**Comment by giginet** [comment]
Use homebrew bottles or install with Swift Package Manager instead in the meantime.

**Comment by jdhealy** [comment]
v0.39.1 release has an Intel slice.

Thanks for reporting.

No plans to re-upload anything for the v0.39.0 release.
