### ISSUE TITLE
bad CPU type in executable: carthage

### ISSUE THREAD

**Issue by Rain-dew** [Carthage/Carthage#3332]
I installed  latest  carthage.pkg in my Mac

When I check on the command line：

raindew@raindew-2 ~ % carthage version 
zsh: bad CPU type in executable: carthage

**Comment by DeveloperLinus** [comment]
me to

**Comment by BMinas** [comment]
I just had the same problem.  The package installs ARM64 on an Intel Macbook.

**Comment by J-Swift** [comment]
Yep, when you run `file` on it, it reports:

`Mach-O 64-bit executable arm64`

**Comment by jdhealy** [comment]
Duplicate of https://github.com/Carthage/Carthage/issues/3323
