### ISSUE TITLE
Xcode 15: make can't install carthage, -static-stdlib not supported

### ISSUE THREAD

**Issue by balavor** [Carthage/Carthage#3348]
## Description

Hey folks, during the preparation of our project for Xcode 15 migration, we found out that we are not able to install `carthage` with brew anymore. `make` retuns the following error `error: -static-stdlib is no longer supported for Apple platforms`, while this flag is passed in the Makefile as `SWIFT_BUILD_FLAGS+= -Xswiftc -static-stdlib`.

```
==> Fetching grammarly-mobile/tools/carthage@0.39.0
==> Cloning https://github.com/Carthage/Carthage.git
Updating /Users/ec2-user/Library/Caches/Homebrew/carthage@0.39.0--git
==> Checking out tag 0.39.0
HEAD is now at 187a78c6 Merge pull request #3318 from giginet/release-0.39.0
HEAD is now at 187a78c6 Merge pull request #3318 from giginet/release-0.39.0
==> Installing carthage@0.39.0 from grammarly-mobile/tools
==> make prefix_install PREFIX=/opt/homebrew/Cellar/carthage@0.39.0/0.39.0
Building for production...
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
error: -static-stdlib is no longer supported for Apple platforms
error: -static-stdlib is no longer supported for Apple platforms
error: -static-stdlib is no longer supported for Apple platforms
make: *** [installables] Error 1
```

## Info

* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: usr/local/bin/carthage
* `carthage version`: 0.39.0
* `xcodebuild -version`: Xcode 15, 15A5229m
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No
* Are you using `--use-xcframeworks`? Yes

**Comment by jdhealy** [comment]
Thanks for the write up and making us aware of this!

`brew reinstall --HEAD carthage` should allow you to test https://github.com/Carthage/Carthage/commit/0dc17e76612b605dfefeb6d2df5abebd1cc82ec2

**Comment by balavor** [comment]
Wow, huge thanks for such a quick input, @jdhealy

**Comment by balavor** [comment]
> brew reinstall --HEAD carthage

Only works with `install` ;)
