### ISSUE TITLE
[Xcode 16.0 Beta] Carthage fails during dsym step

### ISSUE THREAD

**Issue by HeEAaD** [Carthage/Carthage#3374]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/opt/homebrew/bin/carthage`
* `carthage version`:  `0.39.1`
* `xcodebuild -version`: `Xcode 16.0
Build version 16A5171c`
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  No 
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No
* Are you using `--use-xcframeworks`?  Yes

**Cartfile**
```
github "weichsel/ZIPFoundation" == 0.9.12
```

**Carthage Output**
```sh
$ carthage bootstrap --platform ios --use-xcframeworks
*** Checking out ZIPFoundation at "0.9.12"
*** xcodebuild output can be found in /var/folders/5y/qxh283h12bb2xx2v0w0__2gh0000gp/T/carthage-xcodebuild.txyBtz.log
*** Building scheme "ZIPFoundation" in ZIPFoundation.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun dsymutil /Users/steffen/Library/Caches/org.carthage.CarthageKit/DerivedData/16.0_16A5171c/ZIPFoundation/0.9.12/Build/Intermediates.noindex/ArchiveIntermediates/ZIPFoundation/IntermediateBuildFilesPath/ArchiveIntermediates/ZIPFoundation/BuildProductsPath/Release-iphoneos/ZIPFoundation.framework/ZIPFoundation -o /Users/steffen/Library/Caches/org.carthage.CarthageKit/DerivedData/16.0_16A5171c/ZIPFoundation/0.9.12/Build/Intermediates.noindex/ArchiveIntermediates/ZIPFoundation/IntermediateBuildFilesPath/ArchiveIntermediates/ZIPFoundation/BuildProductsPath/Release-iphoneos/ZIPFoundation.framework.dSYM

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/5y/qxh283h12bb2xx2v0w0__2gh0000gp/T/carthage-xcodebuild.txyBtz.log
```

[carthage-xcodebuild.txyBtz.log](https://github.com/user-attachments/files/15783416/carthage-xcodebuild.txyBtz.log)

**Actual outcome**
Carthage `dsymutil` invocation fails because the directory `/Users/steffen/Library/Caches/org.carthage.CarthageKit/DerivedData/16.0_16A5171c/ZIPFoundation/0.9.12/Build/Intermediates.noindex/ArchiveIntermediates/ZIPFoundation/IntermediateBuildFilesPath/ArchiveIntermediates` does not exist. 

**Expected outcome**
Carthage builds the xcframework and its dsyms successfully.

```sh
$ carthage bootstrap --platform ios --use-xcframeworks
*** Checking out ZIPFoundation at "0.9.12"
*** xcodebuild output can be found in /var/folders/5y/qxh283h12bb2xx2v0w0__2gh0000gp/T/carthage-xcodebuild.csuR22.log
*** Building scheme "ZIPFoundation" in ZIPFoundation.xcodeproj
```

### Context:
The content of `/Users/steffen/Library/Caches/org.carthage.CarthageKit/DerivedData/16.0_16A5171c/ZIPFoundation/0.9.12/Build/Intermediates.noindex/ArchiveIntermediates/ZIPFoundation/IntermediateBuildFilesPath/` is:
```sh
EagerLinkingTBDs
UninstalledProducts
XCBuildData
ZIPFoundation.build
```

A `ZIPFoundation` binary is located at `/Users/steffen/Library/Caches/org.carthage.CarthageKit/DerivedData/16.0_16A5171c/ZIPFoundation/0.9.12/Build/Intermediates.noindex/ArchiveIntermediates/ZIPFoundation/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ZIPFoundation.framework/ZIPFoundation`.

**Comment by jdhealy** [comment]
Put up [a commit](https://github.com/Carthage/Carthage/commit/87fedfbcee0c64958bb0d74ce0447dd731d592ea). Commit description details more. Try it out (at one’s own discretion) with `brew uninstall carthage; brew install --head carthage`.

〜 Carthage maintainers will have to restore CI (to test, unit and integration style) before we ship it. Details [in the commit description](https://github.com/Carthage/Carthage/commit/87fedfbcee0c64958bb0d74ce0447dd731d592ea). We have a plan in mind.

**Comment by HeEAaD** [comment]
@jdhealy Tested commit `cf0639251faf780d5214eb3227182302415bb13e`:

The issue is not reproducible anymore:
```shell
$ carthage bootstrap --platform ios --use-xcframeworks:
*** Checking out ZIPFoundation at "0.9.12"
*** xcodebuild output can be found in /var/folders/5y/qxh283h12bb2xx2v0w0__2gh0000gp/T/carthage-xcodebuild.xVoQ7W.log
*** Building scheme "ZIPFoundation" in ZIPFoundation.xcodeproj
```

Thank you for implementing a (temporary) solution that fast! 👍
