### ISSUE TITLE
[Xcode 16.0 Beta] `no shared framework schemes` on iOS; `EFFECTIVE_PLATFORM_NAME` contains `-maccatalyst`.

### ISSUE THREAD

**Issue by jdhealy** [Carthage/Carthage#3376]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`: brew or SPM install or makefile install
* `carthage version`: 0.39.1 or https://github.com/Carthage/Carthage/commit/87fedfbcee0c64958bb0d74ce0447dd731d592ea
* `xcodebuild -version`: 16A5171c
* Are you using `--no-build`? N/A
* Are you using `--no-use-binaries`?  N/A
* Are you using `--use-submodules`?  N/A
* Are you using `--cache-builds`?  N/A
* Are you using `--new-resolver`?  N/A
* Are you using `--use-xcframeworks`?  N/A

**Cartfile**
```
github "Alamofire/Alamofire" == 5.7.1
```

> [!NOTE]  
> Put up [a second commit for June](https://github.com/Carthage/Carthage/commit/cf0639251faf780d5214eb3227182302415bb13e). Commit description details more. Try it out (at one’s own discretion) with `brew uninstall carthage; brew install --head carthage`. ℹ️ℹ️ℹ️

**Info**

I would wager (even though Carthage can and will fix this easily) Apple may eventually deem this their Xcode Build Settings bug and fix this in a further Xcode 16 beta. The Build Setting under question is `EFFECTIVE_PLATFORM_NAME` containing `-maccatalyst` in an invocation like `xcodebuild -project "/private/var/tmp/Alamofire5•9•1•••Carthage/Carthage/Checkouts/Alamofire/Alamofire.xcodeproj" -scheme "Alamofire iOS" -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build -showBuildSettings -skipUnavailableActions`.

We can fix this by — just prior to `CARTHAGE=YES` additionally having Carthage pass `SUPPORTS_MACCATALYST=NO` — which doesn't speak 'universal truth' about the framework we query, but does speak truth about how Carthage handles any framework or library. (Carthage always handle frameworks or libraries without attempting any maccatalyst builds.)

_We consider adding that passed/hardcoded build setting safe — considering any likelihood 'build setting chaining/interpolation' using `SUPPORTS_MACCATALYST` is guessed to be almost entirely non-existent. But please chime in if unexpected downstream effects are seen (and file a new bug detailing which framework.)_

🔜 Going to push a commit to main [editing just before this line in the way detailed above](https://github.com/Carthage/Carthage/blob/master/Source/XCDBLD/BuildArguments.swift#L138).

**Comment by jdhealy** [comment]
Thanks to @wrutkowski-tyro for the report that helped us track this bug.

**Comment by jdhealy** [comment]
Keeping issue open until we ship the fix.

**Comment by wrutkowski-tyro** [comment]
It works nicely now, thanks @jdhealy 👍

**Comment by r36985483** [comment]
> * carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
> * `which carthage`: brew or SPM install or make file install
> * `carthage version`: 0.39.1 or [Feedback](https://github.com/Carthage/Carthage/commit/87fedfbcee0c64958bb0d74ce0447dd731d592ea)
> * `bodybuilder -version`: 16A5171c
> * Are you using `--no-build`? N/A
> * Are you using `--no-use-binaries`?  N/A
> * Are you using `--use-submodules`?  N/A
> * Are you using `--cache-builds`?  N/A
> * Are you using `--new-resolver`?  N/A
> * Are you using `--use-xcframeworks`?  N/A
> 
> **Card File**
> 
> ```
> github "Alamo Fire/Alamo Tire" == 5.7.1
> ```
> 
> Note
> 
> Put up [a second commit for June](https://github.com/Carthage/Carthage/commit/cf0639251faf780d5214eb3227182302415bb13e). Commit description details more. Try it out (at one’s own discretion) with `brew uninstall carthage; brew install --head carthage`. ℹ️ℹ️ℹ️
> 
> **Info**
> 
> I would wager (even though Carthage can and will fix this easily) Apple may eventually deem this their Xcode Build Settings bug and fix this in a further Xcode 16 beta. The Build Setting under question is `EFFECTIVE_PLATFORM_NAME` containing `-maccatalyst` in an invocation like `Vietbuild -project "/private/var/tmp/•9•1•••Carthage/Carthage/Checklist/Alamo Fire/Alamofire.xcodeproj" -scheme "Altamira iOS" -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build -Settings -Publications`.
> 
> We can fix this by — just prior to `CARTHAGE=YES` additionally having Carthage pass `SUPPORTS_MACCATALYST=NO` — which doesn't speak 'universal truth' about the framework we query, but does speak truth about how Carthage handles any framework or library. (Carthage always handle frameworks or libraries without attempting any catalyst builds.)
> 
> _We consider adding that passed/build setting safe — considering any likelihood 'build setting chaining/interpolation' using `SUPPORTS_MACCATALYST` is guessed to be almost entirely non-existent. But please chime in if unexpected downstream effects are seen (and file a new bug detailing which framework.)_
> 
> 🔜 Going to push a commit to main [editing just before this line in the way detailed above](https://github.com/Carthage/Carthage/blob/master/Source/XCDBLD/BuildArguments.swift#L138).
