### ISSUE TITLE
[Xcode 16.6 beta] Failed to build framework `Found no destinations for the scheme ...`

### ISSUE THREAD

**Issue by xuzhaocheng** [Carthage/Carthage#3382]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`:  /opt/homebrew/bin/carthage
* `carthage version`:  built with the head commit
* `xcodebuild -version`: 
```
Xcode 16.0
Build version 16A5230g
```
* Are you using `--no-build`?  No
* Are you using `--no-use-binaries`?  Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`?  No
* Are you using `--new-resolver`?  No
* Are you using `--use-xcframeworks`?  Yes

**Cartfile**
```
github "ReactiveX/RxSwift" ~> 6.2.0
```

**Carthage Output**
```
$ carthage update --use-xcframeworks --no-use-binaries
*** Fetching RxSwift
*** Checking out RxSwift at "6.7.1"
*** xcodebuild output can be found in /var/folders/jl/sb944q4n62gf1k28l6_6y__06g5d4h/T/carthage-xcodebuild.hmycqa.log
A shell task (/usr/bin/xcrun xcodebuild -project /Users/test/Desktop/xcode16/Carthage/Checkouts/RxSwift/Rx.xcodeproj -scheme AllTests-macOS -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= SUPPORTS_MACCATALYST=NO CARTHAGE=YES build -showBuildSettings -skipUnavailableActions) failed with exit code 64:
2024-08-30 15:42:20.279 xcodebuild[43368:157917392]  DVTDeviceOperation: Encountered a build number "" that is incompatible with DVTBuildVersion.
2024-08-30 15:42:20.349 xcodebuild[43368:157917324] [MT] DVTDeviceOperation: Encountered a build number "" that is incompatible with DVTBuildVersion.
2024-08-30 15:42:20.428 xcodebuild[43368:157917324] Writing error result bundle to /var/folders/jl/sb944q4n62gf1k28l6_6y__06g5d4h/T/ResultBundle_2024-30-08_15-42-0020.xcresult
xcodebuild: error: Could not configure request to show build settings: Found no destinations for the scheme 'AllTests-macOS' and action build.
```

**Actual outcome**

**Expected outcome**
Carthage should build without error

**Comment by vldalx** [comment]
I've faced this problem as well trying to build my project that has similar dev environment setup.
Builds of some dependencies fail due to unit test schemes in the dependency projects as shown above.

I could work around the problem by removing the test schemes/targets from the projects where builds are failed. All dependency projects can be found under the Carthage `Checkouts` folder.
Of course, this is far from ideal, but it helped to build my project with xcode 16

**Comment by apoltix** [comment]
#3375.
