### ISSUE TITLE
Prefer Cartfile.resolved over Cartfile for resolving dependencies

### ISSUE THREAD

**Issue by felixjendrusch** [Carthage/Carthage#339]
[Argo@v0.3.3](https://github.com/thoughtbot/Argo/tree/v0.3.3) does not pin [Runes](https://github.com/thoughtbot/Runes) in its `Cartfile`. However, it's resolved to [v1.1](https://github.com/thoughtbot/Argo/blob/v0.3.3/Cartfile.resolved).

When adding Argo@v0.3.3 to a Cartfile, Runes is resolved to v1.2.0, which is provided as Swift 1.2-compatible framework binary. This results in mixed Swift 1.1 and 1.2 dependencies that do not compile.

I suggest preferring versions specified in a project's `Cartfile.resolved` over its `Cartfile`, if available. Nonetheless, I will also open an issue for Argo.

**Comment by gfontenot** [comment]
Oops. We should really be fixing this on our end.

**Comment by felixjendrusch** [comment]
@gfontenot :+1:

**Comment by jspahrsummers** [comment]
> I suggest preferring versions specified in a project's `Cartfile.resolved` over its `Cartfile`, if available. 

Carthage prefers the newest version that satisfies all constraints, because this is almost always what you want. Otherwise, we might as well just be using Git submodules. :wink:

**Comment by felixjendrusch** [comment]
So the only point of committing the `Cartfile.resolved` is knowing one exact configuration in which a project works *when bootstrapped*, but it's not guaranteeing anything when a project is used as dependency? Why not make it more like [npm-shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap)?

**Comment by jspahrsummers** [comment]
> So the only point of committing the `Cartfile.resolved` is knowing one exact configuration in which a project works *when bootstrapped*, but it's not guaranteeing anything when a project is used as dependency?

Correct. `Cartfile.resolved` doesn't even need to be committed to a dependency (for example, if the maintainer prefers a different dependency manager).

> Why not make it more like [npm-shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap)?

Based on my reading of that page, that's exactly how Carthage works—it's just that the shrinkwrap applies only to the top-level project. After you've run `carthage update`, your dependencies cannot shift unexpectedly.

From that page:

> If shrinkwrapped package A depends on shrinkwrapped package B, B's shrinkwrap will not be used as part of the installation of A.

I think Carthage is behaving correctly and sensibly here.

**Comment by felixjendrusch** [comment]
Except for that if *not* shrinkwrapped package A depends on shrinkwrapped package B, B's shrinkwrap will actually be used, whereas Carthage's `Cartfile.resolved` won't, right?

**Comment by jspahrsummers** [comment]
Correct. This is by design, since IME users typically prefer to have the latest, (ostensibly) compatible version of the libraries they use.

**Comment by felixjendrusch** [comment]
Which is exactly what happens if you don't commit your `.resolved`, because there is still going to be the regular `Cartfile`. It's just that it doesn't make a difference for projects that are used as dependency while it could make a meaningful one.

**Comment by jspahrsummers** [comment]
My [point above](https://github.com/Carthage/Carthage/issues/339#issuecomment-74725902) wasn't entirely tongue-in-cheek. If you always want to honor the pinned versions of your dependencies, Git submodules can do that exceptionally well.

IMO, a dependency manager should offer more dynamic version selection, or else it's not really yielding any benefit.

**Comment by felixjendrusch** [comment]
I completely agree, just thought about supporting both.

**Comment by jspahrsummers** [comment]
That would impact the tool's [simplicity](https://github.com/Carthage/Carthage/blob/cebdc57e77bbf704c94e4f5d20e8ec6c71a2dfc7/CONTRIBUTING.md#carthage-is-simple), unfortunately.

**Comment by virusman** [comment]
Does this mean that developers checking out a Carthage-enabled project from source control at different times will end up with different versions of dependencies on their machines? While most developers prefer latest versions, consistency and predictability is also important. No one wants to deal with version inconsistencies across developers' machines.

**Comment by BobElDevil** [comment]
@virusman this is a very old issue. Carthage today does use Cartfile.resolved for build order.

**Comment by virusman** [comment]
@BobElDevil Perfect, thanks!
