### ISSUE TITLE
Universal Framework Schemes Unsupported?

### ISSUE THREAD

**Issue by stephencelis** [Carthage/Carthage#340]
The following project implements a single scheme that can be built for Mac, iOS, and the simulator:

https://github.com/stephencelis/SQLite.swift

With the following Cartfile:

```
github "stephencelis/SQLite.swift"
```

I only get output into `Carthage/Build/Mac`. The built binary cannot be used in an iOS app.

Can Carthage use `SUPPORTED_PLATFORMS` to figure out which frameworks can be built?

**Comment by jspahrsummers** [comment]
We might support this in the future, but I haven't seen any evidence that Apple is really interested in supporting this case.

I'll leave this open so we can think about using `SUPPORTED_PLATFORMS`.

/cc https://github.com/Carthage/Carthage/issues/307

**Comment by stephencelis** [comment]
Good point. The fact that it works at all (via `.xcconfig`) significantly simplifies my project's structure and documentation, though I'm sure Apple will force me to revisit this again in a future update :)

**Comment by regexident** [comment]
+1 for supporting universal frameworks.

**Comment by jspahrsummers** [comment]
Please don't leave +1s—they're not helpful to the project’s maintainers.

If you wish to follow future discussions and implementations for this issue, please click the Subscribe button instead. Or, if you want to submit a pull request as a way to increase the visibility of this issue, we'd be more than happy to review it. :sparkles:

**Comment by regexident** [comment]
What would have to be added to/changed in Carthage in order to support said universal frameworks?
From my understanding it should be enough to detect the use of a `.xcconfig` (and the value provided for `SUPPORTED_PLATFORMS` within in particular), no?
The rest—the actual building steps—should be automatically handled by xcodebuild anyway, shouldn't they?

**Comment by robrix** [comment]
I don’t think anyone has properly investigated what would be required.

Given some of the recent headaches we’ve had surrounding [things that _should_ be handled by `xcodebuild`](https://github.com/Carthage/Carthage/issues/418#issuecomment-91645760), I’m personally cautious. That said, if you’d like to submit a PR we’d be happy to review it.

**Comment by regexident** [comment]
> That said, if you’d like to submit a PR we’d be happy to review it.

That's why I'm asking.  
If it was merely necessary to detect the `SUPPORTED_PLATFORMS`, then I'd consider writing a PR. For anything more build-config-heavy however I'd rather not (for lack of experience with `xcodebuild`). That being said I'd love to see this supported either way.

**Comment by robrix** [comment]
Ah, gotcha.

**Comment by stephencelis** [comment]
A fat binary could work as long as lipo is invoked in a build phase, which I think it is? I haven't dug into Carthage lately.

**Comment by jspahrsummers** [comment]
@regexident I think the main change that would need to occur is looking at `SUPPORTED_PLATFORMS` to figure out which SDK(s) to use, rather than `PLATFORM` (which is only the “current” SDK).

**Comment by ManhattanKkww2015** [comment]
ManhattanKkww2015

**Comment by regexident** [comment]
@jspahrsummers / @robrix:

I've just written a simple Swift parser for parsing `.xcconfig` files: [XCConfig](https://github.com/regexident/XCConfig)

The most basic usage is this:
```swift
let fileURL = NSURL(fileURLWithPath: ...)
if let xcconfig = XCConfig(fileURL: fileURL!) {
	let supportedPlatforms = xcconfig.attributes["SUPPORTED_PLATFORMS"] ?? defaultPlatforms
}
```

Having no personal experience with ReactiveCocoa (and currently no spare time to change it) however I'd probably do more damage than good if I was to try to hack it into Carthage. :smile:

So, if anybody wants give it a go… :wink:

**Comment by jspahrsummers** [comment]
We shouldn't need to parse `.xcconfig` files. Carthage can already read build settings normally. The issue is changing which settings are used for which steps.

**Comment by regexident** [comment]
Oh, then that's even better.

**Comment by jeeftor** [comment]
So does this work now?  Release notes for version 0.9 seem to imply so?

**Comment by robrix** [comment]
Should do as of #622.
