### ISSUE TITLE
--platform still sometimes builds platforms not specified

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#347]
This appears to be an `xcodebuild` issue, because sometimes implicit dependency lookup in a workspace results in the wrong platform being chosen for a dependency, which then causes `carthage build` to fail or do unnecessary work.

For example, `ReactiveCocoa.xcodeproj` depends on `LlamaKit.xcodeproj`, but they're siblings in a workspace together. Sometimes, building ReactiveCocoa's Mac target will result in LlamaKit's iOS target being picked up as a dependency. :worried:

**Comment by jspahrsummers** [comment]
This has an effect without the use of `--platform` too, but it's just more egregious when you've asked to only build a specific platform.

**Comment by robrix** [comment]
If we can find a reduced case where `xcodebuild` chooses implicit dependencies poorly, we ought to file a radar on it (and I volunteer :stuck_out_tongue:).

It’s not clear to me how we can work around this short of turning off implicit dependency lookup.

**Comment by jspahrsummers** [comment]
There might be additional command-line build settings that we can pass to force `xcodebuild` to do the proper resolution. Not sure yet.

**Comment by jspahrsummers** [comment]
On ReactiveCocoa/ReactiveCocoa@2112fd2, with clean builds:

```sh
xctool -scheme 'ReactiveCocoa Mac' -workspace ReactiveCocoa.xcworkspace -configuration Release build
```

works fine. But adding an explicit OS X SDK flag:

```sh
xctool -scheme 'ReactiveCocoa Mac' -workspace ReactiveCocoa.xcworkspace -configuration Release -sdk macosx build
```

causes the failure I've described here (with LlamaKit, specifically).

Maybe the SDK flag is somehow trumping the inherent target properties, forcing an iOS target to build as if it worked on OS X. We could potentially fix this by never passing in `-sdk macosx`, since I haven't seen it error when trying to build iOS yet.

**Comment by jspahrsummers** [comment]
@robrix This might be relevant in light of Recent Developments™.
