### ISSUE TITLE
Dealing with different iOS Deployment Target(s)

### ISSUE THREAD

**Issue by lvillani** [Carthage/Carthage#351]
I'm trying to migrate a project from CocoaPods to Carthage and decided to try it by pulling Alamofire with Carthage instead of CocoaPods.

My project has an iOS Deployment Target of 8.0 but Alamofire, by default, builds the iOS framework targeting iOS 7.

This difference in deployment targets irks iTunes Connect which rejects my .ipa with messages like:

```
ERROR [2015-02-20 13:31:21.69]: [Transporter Error Output]: ERROR ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle PuliziaStrade.app/Frameworks/Alamofire.framework is invalid. The minimum value is 8.0"
ERROR [2015-02-20 13:31:21.69]: [Transporter Error Output]: ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'PuliziaStrade.app/Frameworks/Alamofire.framework/Alamofire' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
ERROR [2015-02-20 13:31:21.69]: [Transporter Error Output]: ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
```

If I change Alamofire's minimum deployment target (after Carthage fetched the source code) my binary uploads just fine.

I'm not sure how to tackle this issue. Should I file a bug report against Alamofire? Should Carthage somehow "override" dependencies' deployment targets to match the parent project?

**Comment by robrix** [comment]
I’d file a bug against Alamofire. As I understand it, iOS 7 doesn’t support dynamic frameworks, full stop.
