### ISSUE TITLE
Error submitting Alamofire to App Store, using Carthage

### ISSUE THREAD

**Issue by danramteke** [Carthage/Carthage#352]
I get the following errors when submitting to the App Store. I've followed all the instructions in the Carthage Readme and the Alamofire Readme. My iOS version is set to Latest (8.1).

Everytime I search for these errors, people say, it doesn't work for iOS 7. That isn't helpful to me because  I'm building for iOS 8.

Here is my GitHub repo illustrating this problem, along with screenshots. I made a blank Single Page App, and added Alamofire via Carthage 0.5.3. I added all files. https://github.com/danramteke/EmbeddedFrameworkTestApp

Can you tell me what I'm doing wrong here? Imgur link to errors screen shot: http://imgur.com/6lQDvyE

This is a duplicate of http://stackoverflow.com/questions/28485302/error-submitting-alamofire-to-app-store-using-carthage?noredirect=1#comment45340308_28485302. I'm duplicating it here because a comment on that question asked me to.

Thank you for your time.

**Comment by jspahrsummers** [comment]
This sounds like the same issue as #351. You can either modify Alamofire's deployment target directly, or wait for Alamofire/Alamofire#352.

**Comment by Nonnus** [comment]
i have the exact same issue even specifying alamofire deployment target of 8.3,
itunes connect won't allow upload
