### ISSUE TITLE
Only mac target is built during carthage update/build with Carthage 6.2

### ISSUE THREAD

**Issue by alanf** [Carthage/Carthage#354]
None of the projects I listed in the Cartfile were built when I specify `--platform iOS` with Carthage .62.

However, if I allow all platforms, the Mac target of one of these projects is built.

Both the iOS and the Mac target schemes are shared. When looking at the Xcode output log, it has no output listed when performing on iOS only. 

I've tried both Release and Debug configurations with the same result.

Any ideas what the issue could be?

**Comment by jspahrsummers** [comment]
Can you please share the contents of your `Cartfile`, your `Cartfile.resolved`, and which Carthage command(s) you're running?

**Comment by alanf** [comment]
* `carthage update --verbose --platform iOS --configuration Debug`
* `carthage build --verbose --platform iOS`

All of the repos are internal to Square, so I stripped out some URL and repo name specifics: 
```
git "ssh://git@git.redacted.com/A/foobar1.git" "master"
git "ssh://git@git.redacted.com/A/foobar2.git" "master"
git "ssh://git@git.redacted.com/A/foobar3.git" "master"
<10 more similar lines>
```

```
git "ssh://git@redacted.com/ios/foobar1.git" "c2c76ce41716384daf6fcf0691992b21e800a13f"
git "ssh://git@redacted.com/ios/foobar2.git" "fb3d1ef38bd9a0a1f0708a95ba36bce28742edcd"
git "ssh://git@redacted.com/ios/foobar3.git" "ce272f173c501340a705c7c1911b0b4234d33907"
<10 more similar lines>
```

**Comment by jspahrsummers** [comment]
Hm, well, without knowing how the projects are configured, it's hard to guess what the issue might be.

Are the iOS targets building dynamic frameworks? Static frameworks aren't supported.

**Comment by alanf** [comment]
Ok, I did know the frameworks would have to be linked dynamically, but somehow thought that the projects could be configured for static libs and that a dynamic framework would be produced. In retrospect this makes no sense, thanks for clarifying!

**Comment by jspahrsummers** [comment]
No problem!
