### ISSUE TITLE
Submodules problems with swift 1.2 support

### ISSUE THREAD

**Issue by iCodesign** [Carthage/Carthage#363]
I'm new here. Now that ```Llamkit```, ```Argo```, ```Either``` has upgraded to support swift 1.2,  I cloned the ```Carthage``` source code and ```bootstrap``` it, but those repos are still the old versions not compatible with Xcode 6.3 Beta2 and Swift 1.2. I wonder if I've done anything wrong.

**Comment by robrix** [comment]
Nope, you haven’t done anything wrong; it’s just that Carthage hasn’t been updated to support Swift 1.2 yet: #326.
