### ISSUE TITLE
OMGHTTPURLRQ problems

### ISSUE THREAD

**Issue by mxcl** [Carthage/Carthage#370]
I keep getting users submitting that they cannot build OMGHTTPURLRQ with Carthage. I don't really understand why. Here's the ticket:

https://github.com/mxcl/OMGHTTPURLRQ/issues/6

Here's the build settings:

![screen shot 2015-03-03 at 5 17 14 pm](https://cloud.githubusercontent.com/assets/58962/6474744/27f2fd80-c1c9-11e4-867e-c8555567b7c7.png)

I have read through linked tickets from the other ticket I opened and I can't figure out what I am expected to do. I can't find any documentation that has more detail in this area either.

![screen shot 2015-03-03 at 5 17 33 pm](https://cloud.githubusercontent.com/assets/58962/6474751/31c8c556-c1c9-11e4-9299-92c760033029.png)

Thanks.

**Comment by jspahrsummers** [comment]
Hmm, is it possible that those users don't have a _distribution_ certificate? Carthage builds for Release by default.

If they don't, and don't want to install one, they could use `carthage build --configuration Debug` to work around that.

**Comment by mxcl** [comment]
The last guy said that Carthage built two other projects successfully, just not OMG.

**Comment by arieljake** [comment]
How do I verify my certificate is a "distribution" certificate?

**Comment by arieljake** [comment]
For one of the successful builds, I see:

CodeSign /Users/.../Dollar.framework
...
Signing Identity: "iPhone Developer: ..."
...
** BUILD SUCCEEDED **

But for OMGHTTPURLRQ, I see:

Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.

**Comment by LinusU** [comment]
Hi, I'm the one who opened the bug. Just wanted to chime in and say that I'm using `"daltoniam/starscream"` thru Carthage and that it's only `OMGHTTPURLRQ` that doesn't work...

**Comment by mxcl** [comment]
I cloned starscream and their provisioning settings are:
![screen shot 2015-03-04 at 11 06 08 am](https://cloud.githubusercontent.com/assets/58962/6488651/83712340-c25e-11e4-8bda-7af9cfc8ce78.png)

Team is none. I'll set the same if you think it'll work. Any quick way that @LinusU can test such things? As I can use Carthage to get OMGHTTPURLRQ np. Thanks.

**Comment by jspahrsummers** [comment]
OMGHTTPURLRQ has an “iOS Distribution” certificate set for its Release configuration—that's what I was referring to.

It can safely be set to “Developer,” because frameworks get re-codesigned when copied into the final application bundle.

**Comment by jspahrsummers** [comment]
Alternatively, building with `--configuration Debug` should work too.

**Comment by mxcl** [comment]
@jspahrsummers great. Thanks.

**Comment by jspahrsummers** [comment]
No problem!

**Comment by arieljake** [comment]
Um, are you serious?

Ok, so the project builds, but several users for no clear reason can't build it. So the issue lies not in OMG but perhaps there is an issue in our configuration.

Is there a way for us to compare your settings that you are using to build with ours?

**Comment by mxcl** [comment]
I think there is a misunderstanding here. @jspahrsummers pointed out a fix I could make, and I made it. If you have time, please try to install OMG again, you may need to delete the Carthage cache.

**Comment by arieljake** [comment]
I apologize, I was following the conversation by email and missed the solution post.

Yes, I can confirm that OMG builds successfully.
