### ISSUE TITLE
code object is not signed at all

### ISSUE THREAD

**Issue by terinjokes** [Carthage/Carthage#373]
#### Cartfile
```
github "Squirrel/Squirrel.Mac" ~>0.1.5
```

#### commands.sh
```
$ carthage bootstrap --platform Mac
*** Downloading ReactiveCocoa at "v2.4.7"
*** Downloading Mantle at "1.5.4"
*** Downloading Squirrel.Mac at "0.1.5"
*** xcodebuild output can be found in /var/folders/bf/yf_3gpbj6r3c65rj63dlyzc80000gn/T/carthage-xcodebuild.D3jEpt.log
```

#### carthage-xcodebuild.D3jEpt.log
```

```
*(this section intentionally left blank)*

#### Xcode build
```
CodeSign /Users/terin/Library/Developer/Xcode/DerivedData/Hanglow-fujvjswqschqbjcjqaeumwdcqetf/Build/Products/Debug/Hanglow.app
    cd /Users/terin/Development/Hanglow
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "Mac Developer: Terin Stock (6J5A94DMMZ)"

    /usr/bin/codesign --force --sign 605E228431FD2423B2D1A8F61ACDBD4AE38E37B5 /Users/terin/Library/Developer/Xcode/DerivedData/Hanglow-fujvjswqschqbjcjqaeumwdcqetf/Build/Products/Debug/Hanglow.app

/Users/terin/Library/Developer/Xcode/DerivedData/Hanglow-fujvjswqschqbjcjqaeumwdcqetf/Build/Products/Debug/Hanglow.app: code object is not signed at all
In subcomponent: /Users/terin/Library/Developer/Xcode/DerivedData/Hanglow-fujvjswqschqbjcjqaeumwdcqetf/Build/Products/Debug/Hanglow.app/Contents/Frameworks/ReactiveCocoa.framework
Command /usr/bin/codesign failed with exit code 1
```

**Comment by jspahrsummers** [comment]
Have you checked the “Code Sign on Copy” checkbox for `ReactiveCocoa.framework` in your app's target settings?

**Comment by terinjokes** [comment]
It was checked by default.
![screenshot 2015-03-04 23 28 11](https://cloud.githubusercontent.com/assets/273509/6500884/3fde6f6c-c2c6-11e4-831b-6b23f0f66559.png)

**Comment by jspahrsummers** [comment]
Hm, I don't know, then.

Can you try `carthage bootstrap --platform Mac --no-use-binaries` and see if the binaries built from scratch will install correctly?

**Comment by terinjokes** [comment]
Yep, that did the trick.

**Comment by jspahrsummers** [comment]
@robrix There's still an issue here, because it's not clear why the downloaded binaries are missing signatures.

**Comment by jspahrsummers** [comment]
@terinjokes If you download and install the framework for the [RAC v2.4.7](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v2.4.7) release manually (replacing your locally-built copy), does it still work?

**Comment by robrix** [comment]
:sweat: apologies!

**Comment by jspahrsummers** [comment]
No worries!

**Comment by terinjokes** [comment]
Woops, sorry for the delay. Will try today.
