### ISSUE TITLE
Expected submodule commit SHA in ls-tree output - error

### ISSUE THREAD

**Issue by richardPFisk** [Carthage/Carthage#374]
Hi,

What version of git does Carthage run successfully against? 

The command ```carthage update``` with git version 2.3.1 seems to always give the result, ```expected submodule commit SHA in ls-tree output``` regardless of which package or version of package is referenced in the Cartfile.

Any ideas welcome before I dive further into the code.

Thanks,
Richard

**Comment by jspahrsummers** [comment]
This sounds like #135, which is a repository configuration issue. If your repository [contains a `.gitmodules` file](https://github.com/Carthage/Carthage/issues/135#issuecomment-703065070), make sure that it only lists submodules which should actually exist.

**Comment by richardPFisk** [comment]
Wow, that was fast. I can confirm that a clean directory runs ```cathage update``` perfectly fine. I will try to find the offending file or directory causing the error.

Thanks very much.

**Comment by jspahrsummers** [comment]
No problem!

**Comment by avdwerff** [comment]
I use Carthage 0.6.4 and do have submodules in the project, checking the .submodules file it shows that is only lists the submodules existing in the project. However running; 'carthage update' gives me after fetching: 
Parse error: expected submodule commit SHA in ls-tree output:

**Comment by pyrtsa** [comment]
@avdwerff Check that you don't have uncommitted changes to the `.gitmodules` file. We got some grey hairs just minutes ago with this, and Carthage wasn't very helpful.

**Comment by avdwerff** [comment]
There were no uncommitted files, ended up building the dependancies in some other folder outside the project for now.

**Comment by zdavison** [comment]
I'm seeing the same issue, no uncommitted changes to .gitmodules file, there are 2 submodules, however they both exist and clone fine.

**Comment by chrisco314** [comment]
In my case, I had to delete existing carthage entries from my .gitmodules file.  I am using carthage 0.8.0.

**Comment by derpoliuk** [comment]
@chrisco314 Deleting all entries from `.gitmodules` didn't help until I commited changes as @pyrtsa said. Thank you guys!
