### ISSUE TITLE
How to support users who don’t want to use Carthage when there are dependencies

### ISSUE THREAD

**Issue by mxcl** [Carthage/Carthage#377]
I have a user who wants to manually manage their PromiseKit dependency manually without Carthage. PromiseKit depends on OMGHTTPURLRQ.

PromiseKit.xcodeproj links to OMG, but it doesn't include the xcodeproj, as this imposes conditions on where the xcodeproj should be (unless there's a way around that).

As a result PromiseKit’s build phases cannot depend on OMGHTTPURLRQ.framework (unless there is a way around that) which means when the user builds their final app Xcode does not know to build OMG first and builds PromiseKit first, the build then fails because PromiseKit cannot link against OMG.

What should I do here? I have been considering making the carthage checkouts use submodules, but if the user wants to manage the submodules themselves, I don't want to stop them.

**Comment by robrix** [comment]
I solve this by having an xcworkspace alongside the xcodeproj for every lib with dependencies. I’d do something like this:

- `PromiseKit.xcworkspace` contains `PromiseKit.xcodeproj` as well as `OMGHTTPURLRQ.xcodeproj`.
- `PromiseKit.xcodeproj` does _not_ contain `OMGHTTPURLRQ.xcodeproj`.
- The `PromiseKit.framework` target links against `OMGHTTPURLRQ.framework`.
- When I want to work on PromiseKit in isolation, or build it on CI, I’d use the workspace.
- When I want to use PromiseKit as a dependency, I’d add the xcodeproj to the dependent workspace/project.

I do this with all of my µframeworks, and I set it up with RAC &c as well. There are a couple of quirks w.r.t. Xcode initially assigning frameworks relative paths from SRCROOT to the build folder, and then adding the build folder to `FRAMEWORK_SEARCH_PATHS` but those are easily resolved via the File Inspector & build settings pane.

As a concrete example, [Either’s `.xcworkspace`](https://github.com/robrix/Either/blob/master/Either.xcworkspace/contents.xcworkspacedata) includes `Either.xcodeproj` as well as the `.xcodeproj`s for `Box` and `Prelude`. In `Either.xcodeproj`, [linkage is the usual](https://github.com/robrix/Either/blob/master/Either.xcodeproj/project.pbxproj#L70-L78); the [`.framework`s are included](https://github.com/robrix/Either/blob/master/Either.xcodeproj/project.pbxproj#L63-L64), but the `.xcodeproj`s are not.

**Comment by robrix** [comment]
(I should note that Xcode resolves the dependencies fine for build order with this setup, i.e. it always builds Box & Prelude before Either.)

**Comment by mxcl** [comment]
Thanks Rob.

Looking over Either I saw that I was not explicitly linking against OMGHTTPURLRQ from PromiseKit, thus Xcode didn’t detect the dependency and wouldn't build OMG first.

The dangers of `import`.

**Comment by robrix** [comment]
Automatic linking of dependencies: It really works!™
