### ISSUE TITLE
Submodules are set up with HTTP instead of SSH

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#378]
Is there a reason for this? SSH would be useful to be able to contribute to dependencies inside of `Carthage/Checkouts` more easily :)

**Comment by delasteve** [comment]
I wouldn't mind this, but what happens when someone is behind a work proxy that blocks SSH?

**Comment by robrix** [comment]
Our experience has been that HTTPS is much better-supported on average (especially factoring in proxies and the like). I’m curious why that wouldn’t be the case here, too—are your dependencies not available via HTTPS?

**Comment by NachoSoto** [comment]
They are in Github, I guess I'll just use [this](https://help.github.com/articles/caching-your-github-password-in-git/) :)

You're right, HTTPS is probably a better default. It might be nice to have the option at some point to set them up with SSH. What do you think?

**Comment by robrix** [comment]
Maybe; in the meantime, does editing the .gitmodules file suffice?

**Comment by NachoSoto** [comment]
Yeah I did that :) this isn't blocking or anything

**Comment by jspahrsummers** [comment]
There's a `--use-ssh` command line flag.

**Comment by NachoSoto** [comment]
Thanks @jspahrsummers! I created #379 :)

**Comment by robrix** [comment]
Hah. TIL.
