### ISSUE TITLE
Submodule project schemes are being picked up which override library Cartfile

### ISSUE THREAD

**Issue by cnoon** [Carthage/Carthage#380]
Hello,

I could really use some help trying to figure out how to properly create a dependency `Cartfile` in my third party library without picking up the submodules in my project. Here's the structure of my current library.

**AlamofireImage**

* Alamofire (@1d9932f6) (contains Alamofire iOS and Alamofire OSX schemes)
* AlamofireImage.xcodeproj
* Cartfile

**AlamofireImage Cartfile**

```
github "Alamofire/Alamofire" ~> 1.1.4
```

I then created a new project called `Image Loader` and added another Cartfile there.

**Image Loader Cartfile**

```
github "cnoon/AlamofireImage" "project/deployment_files"
```

Then here's what I see when I run `carthage update`.

```
cnoon:~/Desktop/Image Loader Carthage$ carthage update
*** Cloning AlamofireImage
*** Cloning Alamofire
*** Checking out Alamofire at "1.1.4"
*** Checking out AlamofireImage at "46e31815ee05afe8d7b90d8e566d40c6a1f42504"
*** xcodebuild output can be found in /var/folders/s7/qpm0b2pn3d56rjlpl7g3_4fh0000gn/T/carthage-xcodebuild.tatPNh.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in AlamofireImage.xcodeproj
*** Building scheme "Alamofire OSX" in AlamofireImage.xcodeproj
*** Building scheme "AlamofireImage iOS" in AlamofireImage.xcodeproj
*** Building scheme "AlamofireImage OSX" in AlamofireImage.xcodeproj
```

It appears that my AlamofireImage Cartfile version of Alamofire is being compiled first, then the Alamofire version from the submodule is stomping the previous version. This is definitely not what I want to have happen. I want to be able to use the AlamofireImage Cartfile semantic versioning to be able to automatically pick up new versions without having to update the submodule in the project. I'm a bit surprised that Carthage actually builds both versions. It seems to me it should only ever build the last one listed since it's going to stomp the previous versions.

I'm assuming that the solution here is to remove the xscheme files from the submodule, but that would require me to fork Alamofire which I don't really want to do. This seems like a pretty common use case for Carthage, so hopefully there's a workaround that I'm not aware of.

Thanks for your help in advance...it's greatly appreciated as is your fantastic toolset!

**Comment by jspahrsummers** [comment]
I wrote [a Quora answer](http://qr.ae/j2zSc) related to this just today.

The TLDR is that you want to create a project _and_ a workspace for your library, and only include dependency projects in the latter. Then, they won't show up as schemes of the project.

**Comment by cnoon** [comment]
Thanks @jspahrsummers...it took me a while to get everything all switched over, but I managed to get everything working properly. The "Relative to Build Products" change took me way longer to figure out than it should have.

Thanks for the great article walking all of us through it!

**Comment by jspahrsummers** [comment]
No problem, glad it helped! :sparkles:
