### ISSUE TITLE
In a framework dependency list, frameworks are duplicated

### ISSUE THREAD

**Issue by Vaseltior** [Carthage/Carthage#382]
Let's say I have the framework `a` which on `b` which rely on `c`.

If `c` is about 10Mo, then
`c` is embedded in `b` so that `b` reaches 10+Mo

Next, `a` contains `c` and `b` and `a` reaches 20++Mo

In the final app I will put all together and I'll get a Huge app with a lot of duplicates. Do you have any ideas?

**Comment by jspahrsummers** [comment]
Generally speaking, frameworks should _not_ copy their dependencies into the framework bundle. Instead, the application should be responsible for linking one copy of each dependency together.

See some previous discussion in https://github.com/Carthage/Carthage/issues/353#issuecomment-75454334.

**Comment by Vaseltior** [comment]
Ok thanks
