### ISSUE TITLE
copy-frameworks script should strip Swift modules too

### ISSUE THREAD

**Issue by Vaseltior** [Carthage/Carthage#383]
When the framework are built, it includes (for iOS) arm, arm64, i386, x86_64.
Which is great when using the simulator.

Is there a way, considering the final app is intended to be run on devices only to select only arm and arm64?

**Comment by jspahrsummers** [comment]
All architectures are built so that you can check the frameworks into your VCS, or distribute them as binaries to users.

If only specific architectures were built, you would have to rebuild a lot more frequently.

**Comment by Vaseltior** [comment]
Ok I understand that, and you're right about that.
But I'd like that the final app does not contain unnecessary files in order to reduce the final package size.

**Comment by jspahrsummers** [comment]
You should be adding a [`copy-frameworks` build phase](https://github.com/Carthage/Carthage/blob/cd6d4237d77c22559a8f6dc92c09ef297be91ea5/README.md#if-youre-building-for-ios) to any iOS application target, which will take care of that for you.

**Comment by Vaseltior** [comment]
So we have a bug here, since the final archive contains the simulator frameworks, even with the build phase (I have read your doc ;-) )

![capture d ecran 2015-03-11 a 19 18 10](https://cloud.githubusercontent.com/assets/915156/6603622/85356284-c823-11e4-95dd-586146212af0.png)

**Comment by jspahrsummers** [comment]
@Vaseltior Good catch! I'll reopen this.

**Comment by robb** [comment]
Could you attach a build log for one of these?

**Comment by Vaseltior** [comment]
Here is an example project [https://dl.dropboxusercontent.com/u/13403001/Test.zip](https://dl.dropboxusercontent.com/u/13403001/Test.zip)

> Carthage 0.6.3 is used.

Open it, then go to Product->Archive (Select iOS Device in order to be able to Archive)
You'll have all the logs you need by archiving the product.

Once done,
- locate the archive in ~/Library/Developer/Xcode/Archives.
- show content package of the archive, 
- go to Products/Contents/Test
- show content package of the Test application
- then go to Frameworks/Snap.framework/Modules/Snap.swiftmodule

**Comment by robb** [comment]
Hmm, it would seem that simply removing those files would be enough, but I wonder if their semantics are documented somewhere?

**Comment by Vaseltior** [comment]
I'll try the next time I'll build an archive. Any side effect will be I guess... instantaneous. 

But it would be really great if these files were by default not added to the modules. Indeed, for one added framework, this is ok, but if you have a dozen of frameworks and if the delivery frequency is high, this could become a real pain.

**Comment by robb** [comment]
Oh, I meant that if simply removing the files is enough, `copy-frameworks` should do it (at least until Xcode gets itself together…)

**Comment by jspahrsummers** [comment]
@robb Removing the files is fine. All we do to create the universal framework is copy them all into the `Modules` folder.

**Comment by Vaseltior** [comment]
Up to what I've been able to trace. The carthage code looks ok at the lipo remove step... The carthage code is able to efficiently find out what are not the valid architectures to include.

Two launches of a lipo remove calls are done, one for i386 and one for x86_64, but since it is working with intermediate files I couldn't figure out if it was a lipo error or anything else. I should send an exit here to prevent the files from being deleted and fetch information about what the lipo really does... Since it's late here in France, I hope this could help you.
