### ISSUE TITLE
Indenpendant module build, checkout and update

### ISSUE THREAD

**Issue by flovilmart** [Carthage/Carthage#384]
Hi that would be helpful to be able to rebuild only a subset of the checked-out frameworks, for development that would incredibly speed-up build time:

The command line could add:

carthage build FramworkName(.framework)

AND/OR

CarthageKit could properly split the build, update, checkout functions per module

**Comment by jspahrsummers** [comment]
`carthage build` will not need to do significant work if you've already built a project and kept its intermediates in your DerivedData folder. In other words, it should take much less time to re-run `carthage build` after it's already been run.

We already have an incremental update idea captured in #218.
