### ISSUE TITLE
Provide guidance for .gitignore

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#386]
Could the documentation be updated to add guidance for what should be included and what should be ignored by git?

**Comment by robb** [comment]
[That already exists.](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfileresolved) :sparkles:

**Comment by robb** [comment]
Closing this one out, but feel free to reopen if you think the documentation could be improved :-)
