### ISSUE TITLE
Project has no shared schemes

### ISSUE THREAD

**Issue by laeryn** [Carthage/Carthage#387]
I'm trying to install Nimbus with Carthage in my iOS project so I imported it to my Cartfile like this:

```
github "jverkoey/nimbus"
```

Then I run ``` carthage update ``` and I get this:

```
*** Cloning nimbus
*** Checking out nimbus at "1.2.1"
*** xcodebuild output can be found in /var/folders/wt/9ybjncb141930trrcn1hqsb80000gp/T/carthage-xcodebuild.SZUHZY.log
Project "Nimbus.xcodeproj" has no shared schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/jverkoey/nimbus/issues/new
```

Can I do anything to fix this?

**Comment by jspahrsummers** [comment]
What specifically are you looking for, beyond what the error message says?

**Comment by laeryn** [comment]
Well the Checkouts folder contains the cloned project, but the Build folder remains completely empty. I've tried running ```carthage build``` after opening up the Nimbus project and checking the "Shared" checkbox next to all the schemes, but that still doesn't work. What am I not doing correctly? Thanks!

**Comment by jspahrsummers** [comment]
> I've tried running carthage build after opening up the Nimbus project and checking the "Shared" checkbox next to all the schemes, but that still doesn't work.

Does the error message remain the same? Also, are you opening the project file or the workspace?

**Comment by laeryn** [comment]
When I run ```carthage build``` all i get is:
```
*** xcodebuild output can be found in /var/folders/wt/9ybjncb141930trrcn1hqsb80000gp/T/carthage-xcodebuild.RMqz4J.log
```

But nothing is added to the build folder. I am opening the Nimbus project file, I don't think it has a workspace file.

**Comment by jspahrsummers** [comment]
Sorry for the delay in responding to this issue.

It doesn't look like Nimbus contains any framework targets. Carthage will not build static libraries—only dynamic frameworks.

**Comment by emanuelef** [comment]
Hi, 
I have the same issue with AlamoFire and SwiftyJSON.

*** Fetching Alamofire
*** Fetching SwiftyJSON
*** Checking out SwiftyJSON at "2.1.3"
*** Checking out Alamofire at "1.1.4"
*** xcodebuild output can be found in /var/folders/my/krw3_wc513v27_05rd8dgwzw0000gq/T/carthage-xcodebuild.ruuS8d.log
Project "Alamofire.xcodeproj" has no shared schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Alamofire/Alamofire/issues/new

**Comment by el-eleven** [comment]
I see the same issue as emanuelef mentioned. I see the "no shared schemes" error sometimes on Alamofire, but I try running `carthage update` again (or try a few times), the error disappears and installation completes.

**Comment by emanuelef** [comment]
I tried again with carthage update and now I get:

**Comment by jspahrsummers** [comment]
@el-eleven @emanuelef Thanks for the heads up! The “no shared schemes” errors sound like https://github.com/Carthage/Carthage/issues/299.

It's impossible to say what the build failure is, without seeing the `xcodebuild` log.

**Comment by ctava** [comment]
i've run into the no shared schemes for after this commit which has a dynamic libary. https://github.com/dodikk/ESDatabaseWrapper/commit/d0f7ac8de503807bf50a68bfb64186f2dc4cf98b

**Comment by dodikk** [comment]
@ctava thanks for looking at ESDatabaseWrapper. Unfortunately, I have not completed adding Carthage support to ESDatabaseWrapper. The library depends on FMDB which does not support carthage. Please file me an issue and let's continue the discussion there.

**Comment by jspahrsummers** [comment]
@ctava As mentioned in #299, the error is unfortunately nondeterministic.

We'd be super grateful if anyone wants to investigate and submit a fix! :pray:
