### ISSUE TITLE
If HTTPS requires Authentication - No notice given just will change

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#391]
I had the following line in my Cartfile
    
    git "https://jstein@mustache.mitre.org/scm/otto/gdl90.git" "master"

And I couldn't figure out what was going on.

When I did
 
    git clone https://jstein@mustache.mitre.org/scm/otto/gdl90.git

it prompted me for a password.  No indication on the UI for this.

**Comment by jspahrsummers** [comment]
Thanks! I think this is the same issue as https://github.com/Carthage/Carthage/issues/219, though.
