### ISSUE TITLE
Suggested .gitignore

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#393]
What are the suggested entries to add to `.gitignore`

I'd be happy to add them to the realm as well...

**Comment by delasteve** [comment]
https://github.com/github/gitignore/blob/master/Swift.gitignore#L28 is probably all that's needed.

I choose to ignore the entire `Carthage` dir to not check in other repositories, but that's a personal preference. This leaves `Cartfile`, `Cartfile.private`, and `Cartfile.resolved` to be committed.

**Comment by jspahrsummers** [comment]
This information is already covered in the [Artifacts](https://github.com/Carthage/Carthage/blob/83bbffd25172df767cf578ca17b0cfbbbf913d35/Documentation/Artifacts.md) document. There isn't one blanket recommendation that will work for all projects.

**Comment by muhammad-zohaib-ehsan** [comment]
**You are not required to commit this folder to your repository, but you may wish to, if you want to guarantee that the built versions of each dependency will always be accessible at a later date.**
This is applicable when i do not use strict versions in my Cartfile?Like == 1.0. This means whenever and from anywhere i will get the same source code and binary frameworks f the dependencies. Thanks
