### ISSUE TITLE
Issues building SwiftyJSON with Carthage

### ISSUE THREAD

**Issue by kevinmlong** [Carthage/Carthage#394]
See issue on SwiftyJSON repo here:
https://github.com/SwiftyJSON/SwiftyJSON/issues/177

##### Output message when "carthage update" is run:
<hr/>
*** xcodebuild output can be found in /var/folders/zq/7zcr7kc905739r9kjnzqvt11ywzxl0/T/carthage-xcodebuild.JyfcZM.log
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal i386 /Users/klong/Development/test/Carthage/Checkouts/SwiftyJSON/Tests/BaseTests.swift
	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(2 failures)

<hr/>
Xcode 6.3
Build version 6D543q

Carthage v0.6.3

**Comment by jeeftor** [comment]
I'm having the same issue.

**Comment by kevinmlong** [comment]
See SwiftyJSON/SwiftyJSON#177 for solution I used to remedy this.
