### ISSUE TITLE
Nested dependencies build multiple times and fail with submodules+workspaces

### ISSUE THREAD

**Issue by neilpa** [Carthage/Carthage#396]
Ran into this problem when trying to create a new project that depends on [neilpa/Termios](https://github.com/neilpa/Termios). After some debugging I came up with barebones projects that isolate the problem.

* [CarthageBug/AAA](https://github.com/CarthageBug/AAA)
  - depends on LlamaKit
  - no workspace
* [CarthageBug/BBB](https://github.com/CarthageBug/BBB)
 - depends on AAA
 - includes AAA in a workspace
* [CarthageBug/CCC](https://github.com/CarthageBug/CCC)
 - depends on BBB
 - no workspace (yet)

The issue occurs when trying to `carthage update --use-submodules` on CCC. It attempts to build BBB via the workspace, not the project.

```
> carthage update --use-submodules
...
*** Building scheme "LlamaKit-Mac" in LlamaKit.xcodeproj
*** Building scheme "AAA" in AAA.xcodeproj
*** Building scheme "BBB" in BBB.xcworkspace
```

This fails trying to build the nested project at `Carthage/Checkouts/BBB/Carthage/Checkouts/AAA` since it can't find the LLamaKit dependency.

AFAICT, there's no way to "un-share" the AAA scheme from the BBB workspace. All that does is update the shared scheme in the included AAA.xcodeproj.

This is probably related to #395 but figured I'd write this up separately since I've got a min repro.

**Comment by neilpa** [comment]
After playing with this more it appears that workspaces are all-or-nothing when it comes to dependencies. Adding LlamaKit to the BBB workspace (or removing AAA from the BBB workspace) allow CCC to depend on BBB and build it. This also results in carthage attempting to build LlamaKit 3 times and AAA twice when updating CCC.

Ideally I only want to include subprojects in the workspace that I expect to edit inline with the main project.

**Comment by jspahrsummers** [comment]
Insofar as I understand the issue, the behavior you're described sounds correct (or at least “as intended”).

Carthage uses workspaces to build dependencies because:

 1. `xcodebuild -list` on a project file will list shared schemes of subprojects too—therefore, we can't recommend subprojects as the means of including nested dependencies.
 1. If a target has a dependency on something in the workspace, it assumably _needs_ it to build. Carthage doesn't pick or introspect what those dependencies are, it just relies on `xcodebuild` to find dependencies across the whole workspace automatically.

There are some previous discussions about this approach in https://github.com/Carthage/Carthage/issues/108 and https://github.com/Carthage/Carthage/issues/377 that may be relevant.

Does that clarify anything?

**Comment by neilpa** [comment]
I probably wasn't clear, but I'm using workspaces and top level projects only, no subprojects.

```
AAA.xcworkspace
  - AAA.xcodeproj
  - Cartfile: LlamaKti

BBB.xcworkspace
  - BBB.xcodeproj
  - AAA.xcodeproj
  - Cartfile: AAA

CCC.xcworkspace
 - CCC.xcodeproj
 - BBB.xcodeproj
 - Cartfile: BBB
```

As for your second point, this gets back to my comment about workspaces being all or nothing. I want workspaces to contain a subset of my dependencies, e.g. the ones I'm likely to work on in tandem. Those will be listed in the Cartfile along with potentially more dependencies. When some other project includes it I want carthage to build everything from the Cartfile first and then only the "main" scheme from the "main" project file.

The above could be achieved if there were a way to limit which schemes carthage built when including a dependent project. Something like an optional `export: <schemes>` node in the Cartfile. If absent it would evaluate to all shared schemes in the workspace.

**Comment by jspahrsummers** [comment]
Thanks for the explanation!

I agree that such a feature could be useful in some cases, but it sounds like a decent amount of complexity for something that is probably not needed super often.

I'm going to tentatively say we won't do this, but we can revisit it if others encounter the same obstacles too.
