### ISSUE TITLE
carthage build --no-skip-current fails with "working directory doesn't exist."

### ISSUE THREAD

**Issue by frowing** [Carthage/Carthage#397]
When trying to add `Carthage` support to `FCModel` https://github.com/marcoarment/FCModel I ran `carthage build --no-skip-current` and failed. Looking at the console the whole error message was `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'working directory doesn't exist.'` 

I ran `xcodebuild -scheme FCModelTest` and it built successfully.

**Comment by robertjpayne** [comment]
I'm getting this as well, inspection in the log results in these sorts of errors:

`could not build Objective-C module 'SwiftShims'`

**Comment by robertjpayne** [comment]
Hmm interesting the error in the logs starts around:

`
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/shims/shims.h:13:10: note: while building module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/shims/shims.h:13:
#include <stddef.h>        // for size_t
`

Going to dig deeper.

**Comment by robertjpayne** [comment]
Ok for my library I was relying on implicit linking using `import UIKit` even though these will build and work fine from Xcode / xcodebuild for some reason the carthage builder breaks them.

To fix I had to explicitly add `UIKit.framework` under build phases.

What's weird is my project has an iOS and OS X framework and once the UIKit.framework is added to the iOS target the OS X target starts to work just fine without needing a explicit link to AppKit.framework.

From my perspective looks like Xcode is just getting a bit confused with the ModuleCache and implicit linking.

**Comment by jspahrsummers** [comment]
Thanks for the bug report! Can you please detail the _exact steps_ that lead to this error, and what suggests the bug lies with Carthage?

**Comment by robertjpayne** [comment]
@jspahrsummers unsure about original poster but in my view this is/was an Xcode bug not a Carthage bug.

**Comment by jspahrsummers** [comment]
@robertjpayne Thanks for clarifying!

I'll tentatively close this out, but we can always reopen it if need be.
