### ISSUE TITLE
Local Git Repos?

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#398]
I thought it was working, but then I deleted my .carthage directory and ... NO MORE.

I'd like the ability to do:

`git "~/testProj" "develop"`

as an option for Cartfile

**Comment by neilpa** [comment]
This works but you have to qualify your URL with the file scheme

```
git "file:///Users/neilpa/code/project" "branch"
```

**Comment by jeeftor** [comment]
Ok so what am I doing wrong here?

My Cartfile is:
    `git "file:///Users/jstein/devel/GDL90/" "master"`

I can type:

   ` git clone file:///Users/jstein/devel/GDL90/`

No problem.

When I try to use Carthage it reports:

    fatal: Not a git repository (or any of the parent directories): .git


![screen shot 2015-03-24 at 5 22 47 am](https://cloud.githubusercontent.com/assets/6491743/6798669/e7053fb8-d1e5-11e4-9271-139df2602ea1.png)

**Comment by jeeftor** [comment]
Ok so I've fixed the problem - but I'm not exactly sure what it means.

I removed my `/users/jstein/Library/Caches/org.carthage.CarthageKit` directory and suddenly everything started working.  I'm not sure how i got into this situation but I wonder if its a bug of some sort?

**Comment by jspahrsummers** [comment]
Carthage's repository cache probably still had a remote set up using the previous path. Deleting the caches folder would force it to re-clone, resolving the problem.

Sorry about the trouble! But it sounds like everything is good to go here now. :sparkles:

**Comment by jeeftor** [comment]
Is there a way to add an option to "reset cache" or something?

**Comment by jspahrsummers** [comment]
We'd rather not do that, and instead fix any issues that arise from using the repository cache. An explicit command to clear it seems like a workaround for a bug. :wink:

I don't know what the specific bug is here, or else we could look into it.
