### ISSUE TITLE
Document how to set up code signing for iOS and Mac frameworks

### ISSUE THREAD

**Issue by cnoon** [Carthage/Carthage#399]
Hello!

I've run into a tricky issue and I need to call in the experts.

#### Problem

I'm trying to figure out what the recommended way to code sign third party libraries is at the moment with Carthage. There's nothing in the docs that I can find and there are a large amount of changes to this going into the OSS libraries at the moment. I'm not sure which approach is the proper one to use and need some assistance from the Carthage gurus.

#### Solution Options

IMO, it seems like the best approach is to set all third party frameworks to `iPhone Developer` for iOS libraries and `Mac Developer` for OS X libraries. The problem is that those of us that don't have a `Mac Developer` account, we can't properly test our third party libraries against a OS X test target because it will fail to sign since it can't find a valid code signing identity. That totally makes sense, but is not what I want. I'm not at all concerned about code signing, and simply want to test that my third party library is valid on OS X through my test targets.

This starts to really break down when pulling in multiple dependencies for your third party library. If any of them set their OS X target to `Mac Developer`, then you won't be able to build their frameworks unless you nest their project within yours. For example...

#### Project Nesting Approach

```
NewLibrary OSX
    - OSSLib1-OSX (don't code sign)
    - OSSLib2-OSX (mac developer)

// Compiles just fine since it appears to ignore the code signing values if nested
```

#### Workspace No-Nesting Approach

```
NewLibrary OSX
OSSLib1-OSX (don't code sign) (not nested in NewLibrary project)
OSSLib2-OSX (mac developer) (not nested in NewLibrary project)

// Compiler error...no code signing identity found for OSSLib2-OSX
```

The only solution I can see is to avoid signing altogether in OSS libs and rely on Carthage and CocoaPods to handle all the settings for us. That would allow us to avoid code signing completely for all our test targets. Then, after a library is pulled in through CocoaPods or compiled using Carthage, you should have everything signed the way you need it. My question is whether Carthage can support OSS frameworks whose code signing identity is set to `Don't Code Sign`?

**Comment by jspahrsummers** [comment]
OS X frameworks don't need to be codesigned at build, and Carthage is completely fine with that.

Unfortunately, Xcode requires that _iOS_ frameworks are codesigned at build time. We're discussing potential workarounds for that in https://github.com/Carthage/Carthage/issues/281.

**Comment by cnoon** [comment]
Thanks @jspahrsummers. I was finally able to figure out how exactly you want to set up a cross-platform set of library targets and frameworks based on your reply. For anyone else that reads through this thread, here's the solution that all third party libraries on Github should be using.

* iOS Framework (CODE_SIGN_IDENTITY = `iPhone Developer`)
* iOS Framework Tests (CODE_SIGN_IDENTITY = `iPhone Developer`)
* OSX Framework (CODE_SIGN_IDENTITY = `Don't Code Sign`)
* OSX Framework Tests (CODE_SIGN_IDENTITY = `Don't Code Sign`)

If you use these settings in combination with the solution in #281, that should cover all the use cases. 

Would it be possible to get this into the README once it is finalized @jspahrsummers? For those of us working on cross-platform libraries, we're just trying to make sure we properly support both Carthage and CocoaPods which has been a tricky thing to get right.

**Comment by jspahrsummers** [comment]
> Would it be possible to get this into the README once it is finalized @jspahrsummers?

@cnoon Sure! I'll leave this open as a documentation enhancement, and would love it if someone could submit a pull request for that. :pray::heart:

**Comment by mdiep** [comment]
Codesigning is no longer required for building frameworks with Carthage (#583). :tada:
