### ISSUE TITLE
Refactor `copy-frameworks` into `strip-frameworks`

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#402]
Instead of our existing `copy-frameworks` command, which requires the specification of every framework that should be copied and stripped, we could have a `strip-frameworks` command, which digs into the app bundle and strips any incorrect architectures found in the frameworks there.

This would offer a few advantages:

 1. The rest of the workflow becomes the same for iOS and OS X (right now, iOS users shouldn't put stuff in the “Embedded Binaries” section)
 1. There's no manual work required to list frameworks—we can find them automatically
 1. If the App Store submission bug gets fixed in the future, the Run Script phase can just be deleted (no other changes necessary)

/cc @robb

**Comment by robrix** [comment]
I dig it.

**Comment by robrix** [comment]
Will stripping architectures affect code signatures?

**Comment by robb** [comment]
👍 

I think we need to resign after stripping, but that's not too bad.

**Comment by jspahrsummers** [comment]
Ah, right—that's kinda gross. :confused: 

Unfortunately, this would happen _after_ copying into the app bundle too (I think), which means we'd have to re-sign the app correctly. I don't want to get into that business. :fearful:
