### ISSUE TITLE
Update command appears to ignore --platform argument

### ISSUE THREAD

**Issue by rcedwards** [Carthage/Carthage#403]
While the build command will honor the --platform argument and only build the specified platforms, the update command will build both mac and iOS and ignore the supplied argument.

**Comment by jspahrsummers** [comment]
Can you please attach console output demonstrating the issue?

**Comment by rcedwards** [comment]
Sure thing.

```carthage build --platform iOS```

console output:
*** xcodebuild output can be found in /var/folders/xy/7mr66d6x40d625cw577ydsyw0000gn/T/carthage-xcodebuild.y2x80b.log

Directory Contents:
![screenshot 2015-03-30 20 12 01](https://cloud.githubusercontent.com/assets/573823/6909892/7f503f92-d719-11e4-9fa2-feba6a38f0b6.png)


```carthage update --platform iOS```

console output:
*** Fetching Mantle
*** Fetching MTLManagedObjectAdapter
*** Downloading Mantle at "1.5.4"
*** Downloading MTLManagedObjectAdapter at "0.1: Eternal Recurrence of the Same"
*** xcodebuild output can be found in /var/folders/xy/7mr66d6x40d625cw577ydsyw0000gn/T/carthage-xcodebuild.YLSjBH.log

Directory Contents:
![screenshot 2015-03-30 20 12 37](https://cloud.githubusercontent.com/assets/573823/6909899/9340cf76-d719-11e4-96d3-2438af72758f.png)

**Comment by jspahrsummers** [comment]
You're seeing Mac binaries because Carthage was able to _download_ them instead of building them. If they had to be built from scratch (for example, if you passed the `--no-use-binaries` option), you would only see iOS frameworks.

No bug here—just some extra files. :smile:

**Comment by rcedwards** [comment]
gotcha.

thanks.
