### ISSUE TITLE
Single platform building?

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#406]
I'm trying to build the Xcode 6.3 branch of SwiftyJSON and it has two shared schemes, one for mac and one for iOS.  I only have an iOS developer certificate and I think the build is failing because its trying to build the mac scheme.  

Is there support in Carthage to limit what platform it builds to?? --platform = iOS or something like that?
![screen shot 2015-04-02 at 9 51 30 am](https://cloud.githubusercontent.com/assets/6491743/6965240/02cfd21e-d91e-11e4-9811-2364e034062f.png)

**Comment by mdiep** [comment]
Yes, there is.

```
$ carthage help build
Build the project's dependencies

[--configuration Release]
	the Xcode configuration to build

[--platform all]
	the platform to build for (one of ‘all’, ‘Mac’, or ‘iOS’)

[--no-skip-current]
	don't skip building the Carthage project (in addition to its dependencies)

[--color auto]
	whether to apply color and terminal formatting (one of ‘auto’, ‘always’, or ‘never’)

[--verbose]
	print xcodebuild output inline

[/Users/mdiep/Repositories/Test]
	the directory containing the Carthage project
```

**Comment by jeeftor** [comment]
OOPS!  Thanks.

**Comment by tcurdt** [comment]
is there a way to set this in the cartfile?

**Comment by mdiep** [comment]
No there isn't. But I'm pretty sure there's an open issue that discusses doing that.

**Comment by tcurdt** [comment]
Hm - at least I didn't find it.

**Comment by ikesyo** [comment]
#262 would be the one.
