### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by rotespferd** [Carthage/Carthage#407]
When I want to install Quick with Carthage through *carthage update* I get the following output:
```
*** Fetching ReactiveCocoa
*** Fetching realm-cocoa
*** Fetching Nimble
*** Fetching Quick
fatal: Not a git repository (or any of the parent directories): .git
```
When I remove Quick from the Cartfile.private everything works fine.

I created an issue in the Quick repository, but maybe it is an error in Carthage: Quick/Quick#275

My setup ist:
- OSX 10.10
- Xcode Version 6.3 (6D554n)
- Swift 1.2
- Carthage 0.6.3

My Cartfile content is
```
github "ReactiveCocoa/ReactiveCocoa"
github "realm/realm-cocoa" >= 0.89.2
```

My Cartfile.private content is
```
github "Quick/Nimble"
github "Quick/Quick"
```

**Comment by jspahrsummers** [comment]
This may be an issue with Carthage's repository cache. See the very similar report and resolution in https://github.com/Carthage/Carthage/issues/398.

**Comment by rotespferd** [comment]
You are right. I deleted the repository cache ```~/Library/Caches/org.carthage.CarthageKit``` and now everything works.
Thank you for your help!

**Comment by devSC** [comment]
Fix my problem. Thanks.

**Comment by beamaster** [comment]
it also fix my problem,but i have a new question.
`Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.`

**Comment by mostafaberg** [comment]
@beamaster This is not carthage related, you are cloning a repo hosted on this IP address and this is a warning from SSH letting you know that your key has been added to this host in known hosts list, you'll only see that warning once unless you clear the known hosts

**Comment by webninjabilal** [comment]
asdf
