### ISSUE TITLE
Add logging and a verbose mode to help diagnose problems

### ISSUE THREAD

**Issue by rogernolan** [Carthage/Carthage#408]
Carthage dumps xcodebuild output but it's difficult to debug when it is failing in some of its tasks. Verbose mode would help that.

**Comment by robrix** [comment]
I’m not really sure what would be more verbose than `xcodebuild`’s complete output?

**Comment by jspahrsummers** [comment]
There is a `--verbose` flag.

**Comment by rogernolan** [comment]
doh.
