### ISSUE TITLE
`carthage update` build command is failing while adding dependencies

### ISSUE THREAD

**Issue by manojmahapatra** [Carthage/Carthage#409]
Hi,

I tried to add couple of dependencies to my project (Alamofire and SwiftyJSON) and when I run `carthage update` it's failing to add those dependency framework to `Build` folder. 

below is the error what I'm getting --

The following build commands failed:
	`CompileSwift normal arm64 /Users/z013hyb/TestCarthage/Carthage/Checkouts/Alamofire/Source/Alamofire.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)`

Is it only me or happening to others as well ?

Thanks in advance!

**Comment by jspahrsummers** [comment]
Can you please include the full `xcodebuild` log?

**Comment by manojmahapatra** [comment]
`
*** Fetching Alamofire
*** Fetching SwiftyJSON
*** Checking out Alamofire at "1.1.5"
*** Checking out SwiftyJSON at "2.1.3"
*** xcodebuild output can be found in /var/folders/3b/txhj7_rj2hqdm9q_rq3y0k0mdgbp24/T/carthage-xcodebuild.Mr8uqW.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
2015-04-07 23:51:17.543 xcodebuild[78469:1007] [MT] PluginLoading: Required plug-in compatibility UUID A16FF353-8441-459E-A50C-B071F53F51B7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RevealPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-04-07 23:51:17.544 xcodebuild[78469:1007] [MT] PluginLoading: Required plug-in compatibility UUID A16FF353-8441-459E-A50C-B071F53F51B7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-04-07 23:51:17.545 xcodebuild[78469:1007] [MT] PluginLoading: Required plug-in compatibility UUID A16FF353-8441-459E-A50C-B071F53F51B7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-04-07 23:51:17.982 xcodebuild[78469:1007] [MT] iPhoneSimulator: SimVerifier returned: Error Domain=NSPOSIXErrorDomain Code=53 "Simulator verification failed." UserInfo=0x7fd96c020520 {NSLocalizedFailureReason=A connection to the simulator verification service could not be established., NSLocalizedRecoverySuggestion=Ensure that Xcode.app is installed on a volume with ownership enabled., NSLocalizedDescription=Simulator verification failed.}
2015-04-07 23:51:21.424 xcodebuild[78469:5103]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6728/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from /Users/z013hyb/Library/Developer/Xcode/DerivedData/Alamofire-dlsfoijgyjgjiphdozsaamzyormt/Build/Intermediates/Alamofire.build/Release-iphoneos/Alamofire iOS.build/Objects-normal/arm64/Alamofire.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Alamofire.d” couldn’t be opened because there is no such file." UserInfo=0x7fd96f0d0190 {NSFilePath=/Users/z013hyb/Library/Developer/Xcode/DerivedData/Alamofire-dlsfoijgyjgjiphdozsaamzyormt/Build/Intermediates/Alamofire.build/Release-iphoneos/Alamofire iOS.build/Objects-normal/arm64/Alamofire.d, NSUnderlyingError=0x7fd96c4d3790 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/z013hyb/Library/Developer/Xcode/DerivedData/Alamofire-dlsfoijgyjgjiphdozsaamzyormt/Build/Intermediates/Alamofire.build/Release-iphoneos/Alamofire iOS.build/Objects-normal/arm64/Alamofire.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd96c4e3130>{name = (null), num = 9}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **`

`The following build commands failed:
	CompileSwift normal arm64 /Users/z013hyb/TestCarthage/Carthage/Checkouts/Alamofire/Source/Alamofire.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)`

**Comment by manojmahapatra** [comment]
hope that should help! Thank you!

**Comment by robrix** [comment]
@manojmahapatra I think @jspahrsummers was referring to the build log which is mentioned in that log as being at this path:

```
/var/folders/3b/txhj7_rj2hqdm9q_rq3y0k0mdgbp24/T/carthage-xcodebuild.Mr8uqW.log
```

**Comment by manojmahapatra** [comment]
@robrix Thanks for pointing, my bad! completely overlooked @jspahrsummers message. 
here is the complete transcript from xcodebuild log:

Build settings from command line:
    SDKROOT = iphonesimulator8.2

=== BUILD TARGET Alamofire iOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/z013hyb/Library/Developer/Xcode/DerivedData/Alamofire-dlsfoijgyjgjiphdozsaamzyormt/Build/Intermediates/Alamofire.build/all-product-headers.yaml

=== BUILD TARGET Alamofire iOS Tests OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.2

=== BUILD TARGET Alamofire iOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/z013hyb/Library/Developer/Xcode/DerivedData/Alamofire-dlsfoijgyjgjiphdozsaamzyormt/Build/Intermediates/Alamofire.build/all-product-headers.yaml

=== BUILD TARGET Alamofire iOS Tests OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

=== BUILD TARGET Alamofire OSX OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/z013hyb/Library/Developer/Xcode/DerivedData/Alamofire-dlsfoijgyjgjiphdozsaamzyormt/Build/Intermediates/Alamofire.build/all-product-headers.yaml

=== BUILD TARGET Alamofire OSX Tests OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphonesimulator8.2

=== BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

Check dependencies

=== BUILD TARGET SwiftyJSONTests OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.2

=== BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.2'`

**Comment by jspahrsummers** [comment]
@manojmahapatra That error means that you don't have the right certificate to codesign SwiftyJSON. In the case of that library specifically, it (incorrectly) requires a Distribution certificate for the Release configuration.

You can do any of the following to fix it:

 1. Install a Distribution certificate
 1. Build with `--configuration Debug`
 1. Fix SwiftyJSON to use a normal Developer certificate even for Release builds

Hope that helps!

**Comment by manojmahapatra** [comment]
@jspahrsummers thanks that did the trick.
