### ISSUE TITLE
Carthage does not parse release names with 'strings' or 'special characters'

### ISSUE THREAD

**Issue by choiceforyou** [Carthage/Carthage#411]
Added only one package to Cartfile:
github "Alecrim/AlecrimCoreData" == 3.0-beta.1
> carthage update
Parse error: unexpected trailing characters in line: github "Alecrim/AlecrimCoreData" == 3.0-beta.1

Following line from the same package works
github "Alecrim/AlecrimCoreData" == 2.1
> carthage update
*** Fetching AlecrimCoreData
*** Checking out AlecrimCoreData at "2.1"
*** xcodebuild output can be found in /var/folders/4q/5fkt_mwd62d02wq402p1mkrw0000gn/T/carthage-xcodebuild.ea1P8X.log
*** Building scheme "AlecrimCoreData iOS" in AlecrimCoreData.xcodeproj
*** Building scheme "AlecrimCoreData OS X" in AlecrimCoreData.xcodeproj

Installed Carthage with brew
> brew install carthage
> carthave version
0.6.3

**Comment by neilpa** [comment]
If you want exactly version 3.0-beta.1 you can specify the tag name (or any commitish) in quotes

```
github "Alecrim/AlecrimCoreData" "3.0-beta.1"
```

If the most recent 3.0 version is fine you can use the `~>` operator

```
github "Alecrim/AlecrimCoreData" ~> 3.0
```

**Comment by jspahrsummers** [comment]
As mentioned in the [README](https://github.com/Carthage/Carthage/blob/83bbffd25172df767cf578ca17b0cfbbbf913d35/README.md#tag-stable-releases), version numbers that are followed by any characters are currently not supported.
