### ISSUE TITLE
Ongoing development of Carthage-injected framework

### ISSUE THREAD

**Issue by edwardaux** [Carthage/Carthage#412]
I have my own Swift framework that I plan on using Carthage to inject into my Mac app. As is always the way, though, my framework is not yet complete so as I develop the Mac app, I know that I will need to make changes to my framework.

The way I read the doco, it seems that the way to go is to the `--use-submodules` flag. Is this correct?  I assume that this is a project-wide setting... ie. if I pass that flag, then *all* other carthage-referenced projects will be added as submodules.  

Apologies if this has been asked/answered already. Thanks.

**Comment by jspahrsummers** [comment]
Yep, `--use-submodules` works well for that workflow, and it is not supported per-project (for simplicity's sake).

**Comment by edwardaux** [comment]
Thanks for confirming I'm on the right track.  Love your work!

**Comment by jspahrsummers** [comment]
Thanks! :blush:
