### ISSUE TITLE
Problem when submitting to the AppStore ITMS-90205 & ITMS-90206

### ISSUE THREAD

**Issue by edwardIshaq** [Carthage/Carthage#416]
I have a project setup with the following Targets:

1- PopFramework: iOS 8.1 framework containing ReactiveCocoa.framework as instructed in the Carthage readme section
	* it has ReactiveCocoa.framework in the "Link Frameworks and Libraries"  under "Build Settings" 
	* it has ReactiveCocoa.framework in the "Link Binaries With Libraries" under "Build Phases" 
	* got the "carthage copy-framework" run script build phase with the input files
	"$(SRCROOT)/Carthage/Build/iOS/ReactiveCocoa.framework"

2- Pop.app: iOS 8.1 Target 
	* it has ReactiveCocoa.framework in the "Link Frameworks and Libraries" 
	* got the "carthage copy-framework" run script build phase

the Pop target builds and runs on Simulator and Device no problem.
Also it archives successfully.

The problem appears when submitting to the AppStore:
i get two errors:

Archive submission failed due to the issues listed below.
(1) ERROR ITMS-90205: "Invalid Bundle. The bundle at 'Pop.app/Frameworks/PopFramework.framework' contains disallowd nested bundles."
(2) ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Pop.app/Frameworks/PopFramework.framework' contains disallowd file 'Frameworks'"

**Comment by edwardIshaq** [comment]
Pop.app
	 Frameworks\
	 	libswiftCore.dylib
		...
		PopFramework.framework
			Frameworks\
				ReactiveCocoa.framework (Included once in the PopFramework.framework)
		ReactiveCocoa.framework (Included a SECOND time in the Frameworks folder)

![screen shot 2015-04-07 at 1 05 28 pm](https://cloud.githubusercontent.com/assets/356324/7032323/d1035e38-dd26-11e4-9731-1d6951d35ca4.png)

**Comment by robb** [comment]
The `PopFramework.framework` should not include the `copy-framework`, you'll want to link them but copy them at the app level.

**Comment by edwardIshaq** [comment]
Hi @robb I now have the "carthage copy-frameworks" only on the Pop.app level.
That seems to have done the trick :)

Thank you so much, I've been working on this all morning :+1:

**Comment by AlexKorovyansky** [comment]
I'm experiencing the same issue. This is my Cartfile:
github "Alamofire/Alamofire" >= 1.2.3
github "tristanhimmelman/AlamofireObjectMapper" >= 0.4

> The PopFramework.framework should not include the copy-framework, you'll want to link them but copy them at the app level.

@robb What exact action do you mean by it?

**Comment by robb** [comment]
@AlexKorovyansky I don't think my suggestion applies to your problem. But generally, if you have transitive dependencies, you still want to link all of them at the app level and have your `copy-frameworks` step there.

@mdiep I've been out of the loop for way too long, is `copy-frameworks` needed still with Xcode 7?

**Comment by AlexKorovyansky** [comment]
I'm using XCode6. What do you mean by this phrase?
> should not include the `copy-framework`

**Comment by mdiep** [comment]
AFAIK `copy-framework` is still needed. It's a limitation of the App Store that binaries aren't allowed to contain the simulator architecture.

**Comment by AlexKorovyansky** [comment]
FYI, for me this workaround looks working https://github.com/Carthage/Carthage/issues/353
