### ISSUE TITLE
Submodule checkouts interact poorly with binary downloads

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#419]
If a project uses Carthage with the `--use-submodules` option and _also_ relies upon Carthage for building, binary downloads can complicate things.

The primary problem is: if a binary is downloaded, the submodule will be removed (and incompletely, at that). This means that _whether a submodule exists_ can change with every `carthage bootstrap`.

We should do one or both of the following things:

 1. Disable binary downloads by default when using submodules
 1. Still check out submodules even if binaries are available

**Comment by mdiep** [comment]
This is complicated by the current code structure, which builds all checkout out dependencies.

**Comment by paulyoung** [comment]
I just ran into this and was pretty confused.
