### ISSUE TITLE
Provide CarthageKit Framework as Part of Releases

### ISSUE THREAD

**Issue by jeffreybergier** [Carthage/Carthage#422]
Hi, Its really nice being able to get the PKG file for Carthage command line interface. It would also be nice if there was a fully selfcontained framework that could be downloaded from there for CarthageKit. That way it would be super easy to drag that into a new Xcode project and start using CarthageKit in a new app.

label: enhancement

**Comment by jspahrsummers** [comment]
Great idea, thanks! It'd be great to see this added to our `Makefile` and/or `.travis.yml`.

**Comment by jspahrsummers** [comment]
In the meantime, I've manually uploaded CarthageKit for the [0.6.5 release](https://github.com/Carthage/Carthage/releases/tag/0.6.5).

**Comment by ikesyo** [comment]
This seems already done in #573 and 5d40d32. :sparkles:
