### ISSUE TITLE
Carthage only builds iOS version of framework

### ISSUE THREAD

**Issue by c0diq** [Carthage/Carthage#425]
I am building a single framework target for both iOS and OSX. But when I run carthage build, it only builds the iOS version. Is Carthage assuming one single platform per target?

**Comment by robb** [comment]
Which repo are we talking about?

**Comment by robrix** [comment]
Is this the universal frameworks thing? i.e. #340

**Comment by c0diq** [comment]
robb, it's https://github.com/plutinosoft/Neptune which has one single Neptune.framework target.
robrix, no it's not a universal framework. It's a single target that can build a framework for either iOS or OSX depending on the sdk chosen. 
Having to maintain multiple separate targets should not be required. If it is, I'll have to look at using xcconfig I guess.

**Comment by neilpa** [comment]
> … one single Neptune.framework target.
robrix, no it's not a universal framework. It's a single target that can build a framework for either iOS or OSX depending on the sdk chosen. 

I believe that's what @robrix meant by universal framework. See also #307.

**Comment by robrix** [comment]
Yep, that’s exactly what I meant. Those are currently unsupported, so closing this out for the time being.
