### ISSUE TITLE
Discuss the pitfalls of using prebuilt Swift frameworks

### ISSUE THREAD

**Issue by jpsim** [Carthage/Carthage#433]
Since Swift does not have a stable ABI across versions (see "Binary Compatibility and Frameworks” in https://developer.apple.com/swift/blog/?id=2), prebuilt Swift frameworks should be avoided. Unless they were built with the same version of Xcode and Swift as the project integrating them.

I don't think Carthage should be recommending that binary Swift frameworks be uploaded to GitHub releases or checked in to source control (as is kinda done [here](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) and [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#carthagebuild)).

Perhaps GitHub releases should continue to be supported for Swift frameworks, but a warning could be logged to the console? A warning could also be logged when `carthage archive` is run?

I'm certainly not advocating for GitHub releases to be removed for Swift frameworks, by the way. I think when used carefully, it can be very powerful. But it has to be used carefully.

So far, I don't think this has been a major issue in practice, because Swift typically breaks in bigger ways across versions, but it's feasible that Apple release ABI incompatible versions of Swift (between say Xcode 6.4 and 6.4.1) and this could really bite someone unexpectedly.

**Comment by robrix** [comment]
I personally think this is a non-issue. The lack of ABI compat. means that all your dependencies should get a new major version every time Apple ships a new Swift compiler.

Hypothetically you should get linker errors if ABI compat. has been broken, but if we don’t trust that to actually be the case (ha ha ha ha ha) we could leverage the clues left in `Info.plist` files:

	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>6D1002</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>14D125</string>
	<key>DTSDKName</key>
	<string>macosx10.10</string>
	<key>DTXcode</key>
	<string>0631</string>
	<key>DTXcodeBuild</key>
	<string>6D1002</string>

**Comment by gfontenot** [comment]
> Unless they were built with the same version of Xcode and Swift as the project integrating them.

This seems like it falls to the framework maintainer to deal with the issue (if you want to consider it one). With Argo and Runes, we bumped the version for Swift 1.2 support and explicitly built those dependencies with the proper version of Xcode. I was fine taking on that responsibility, and preferred the experience from both a framework producer and consumer of being able to use the prebuilt binaries.

**Comment by jpsim** [comment]
Thanks for chiming in, @robrix and @gfontenot! I mostly wanted a public forum to discuss these things with others who have thought it through.

As far as falling on the framework maintainer to update to the latest Swift version, that only really works if the consumers of these frameworks use the same version of Swift as you.

In any case, prebuilt binaries are pretty great for some cases and this is really just a theoretical issue. Now if only Apple could fix [rdar://19209161](http://openradar.me/19209161)!
