### ISSUE TITLE
How to use Carthage with submodules correctly?

### ISSUE THREAD

**Issue by tomassliz** [Carthage/Carthage#435]
I have these lines in .gitignore file:
- Carthage/Checkouts
- Carthage/Build

Can I then use `carthage update --use-submodules`? Because when I tried to use this command, directory `Carthage/Checkouts` is staged in git repository even though is declared in .gitignore file.

When I unstage content of this repository and run `carthage update --use-submodules` again, this error is throwed:
```
*** Fetching Alamofire
*** Fetching VaultKit
Parse error: expected submodule commit SHA in ls-tree output: 
```
Another question: If I want to use submodules, must I use flag `--use-submodules` with every `carthage update` command? Or should I use it only with first `carthage update`?

**Comment by jspahrsummers** [comment]
That error you're seeing is https://github.com/Carthage/Carthage/issues/135.

In general, if you want Carthage to manage your submodules, it _doesn't_ make sense to ignore them. Submodules are part of your repository and should be committed as such, except in very rare cases.

You should pass `--use-submodules` to any command that may add additional checkouts. Existing checkouts will be updated as submodules even if the flag isn't present.

**Comment by tomassliz** [comment]
That makes sense, thank you!

**Comment by jspahrsummers** [comment]
No problem! :sparkles:
