### ISSUE TITLE
carthage bootstrap deletes existing submodules for projects with release binaries

### ISSUE THREAD

**Issue by neilpa** [Carthage/Carthage#439]
I hit this when updating my ReactiveCocoa repo to the change that replaced LllamaKit with Result+Box. I experimented some and even `carthage bootstrap --use-submodules` prefers binaries while deleting the submodule entries for Box and Result.

**Comment by mdiep** [comment]
Release binaries shouldn't affect what Carthage does with submodules. It's an optimization on top of everything else.

If I'm understanding you correctly, that sounds like the correct behavior. Carthage should update submodules even if it's using release binaries.

**Comment by gfontenot** [comment]
I actually ran into this today. If you _don't_ specify `--no-use-binaries` then when it finds a binary it will remove the directory for the submodule. Not sure if this is intended or not, but it is a little confusing.

**Comment by neilpa** [comment]
> when it finds a binary it will remove the directory for the submodule

Definitely confusing and probably incorrect. It also breaks any workspaces that reference projects under Carthage/Checkouts.

**Comment by mdiep** [comment]
So Carthage is removing the submodule when the project is still in your `Cartfile.resolved`? If so, that sounds like a bug.

**Comment by neilpa** [comment]
@mdiep Exactly

**Comment by gfontenot** [comment]
I can reproduce this in the `gf-fucking-submodules` branch of [Argo]:

```
$ tree Carthage/Checkouts
Carthage/Checkouts
├── Box
└── runes

2 directories, 0 files
$ carthage bootstrap
*** Downloading Box at "1.2.1"
*** Downloading runes at "1.2.2: Extension compatibility"
*** xcodebuild output can be found in /var/folders/ym/cjv2ctc130v3slskyn7zw_2r0000gn/T/carthage-xcodebuild.U4bhte.log
$ tree Carthage/Checkouts
Carthage/Checkouts

0 directories, 0 files
```

[Argo]: https://github.com/thoughtbot/Argo

**Comment by jspahrsummers** [comment]
This is “by design”—not really a deliberate outcome, but understood to be the case based on design choices made—because Carthage will build any checkouts that exist, negating the benefit of prebuilt binaries.

**Comment by jspahrsummers** [comment]
See #419.
