### ISSUE TITLE
Empty folders in Carthage/Checkouts after clone

### ISSUE THREAD

**Issue by tomassliz** [Carthage/Carthage#441]
I'm using Carthage with submodules and in the .gitignore file I have only `Carthage/Build` folder. When I try to do clean clone from repository, `Carthage/Checkouts` folder contains only empty folder for each framework listed in the Cartfile.

Is this behaviour correct? If yes, should I call after clean clone `carthage build` command? And should I call it with `--use-submodules` flag?

**Comment by jspahrsummers** [comment]
You need to use `git clone --recursive` or `git submodule update --init --recursive` to pull down submodules in addition to the base repository.

**Comment by tomassliz** [comment]
I tried `git submodule update --init --recursive` to pull down submodules, but I get this error:
> No submodule mapping found in .gitmodules for path 'Carthage/Checkouts/Alamofire'

I checked the `.gitmodules` file and I noticed, that all my submodules (except one) dont have `path`. So I set `path` for each submodule in `.gitmodules` file and now it works. Thank you for your advice.
```
```
