### ISSUE TITLE
Document usage of local repository in Cartfile

### ISSUE THREAD

**Issue by flovilmart** [Carthage/Carthage#452]
During the development of a Carthage module, that would actually make sense to be able to reference a local repository. 
Instead of remotely checking a repo out, Carthage could simply copy the local repo in the Checkout folder or Symlink the repo in the checkouts folder

**Comment by MichaelMcGuire** [comment]
You can specify a local repository using a file URL:
```
git "file:///directory/to/project" "branch"
```
Check out #398 for more info

**Comment by flovilmart** [comment]
Perfect thanks!

**Comment by flovilmart** [comment]
Please update the documentation to reflect that possibility :)

**Comment by mdiep** [comment]
I'm going to reopen this because I think it needs to be documented. This question has come up a lot.

**Comment by flovilmart** [comment]
Want me to document it an PR?




Is there any other additional reference possible that this one?

**Comment by mdiep** [comment]
A PR would be fantastic! An example should be added [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#example-cartfile). I don't think we're missing any other possibilities.
