### ISSUE TITLE
Carthage update fails for unknown reason

### ISSUE THREAD

**Issue by vojtechvrbka** [Carthage/Carthage#456]
I am trying to use Carthage, but I have problems with libraries which doesn't support Carthage yet. I have no problems with `Alamofire` or `SwiftyJSON`

For example *FieryCrucible*:

I made a [fork](https://github.com/fireflyexperience/FieryCrucible) and I set the main scheme as shared

I added it to the *cartfile*

    github "fireflyexperience/FieryCrucible"

When I call `carthage update`

    *** Fetching FieryCrucible
    *** Checking out FieryCrucible at "1.1.1"
    *** xcodebuild output can be found in /var/folders/br/fd2dcx0d3x7fxfw_kp18twsw0000gn/T/carthage-    xcodebuild.7bhBEt.log
    *** Building scheme "FieryCrucible" in FieryCrucible.xcodeproj
    A shell task failed with exit code 65

End of the log file
 
	..........
	/Users/vojta/dev/ios/alpha Carthage/iOS/Build/Alpha/Carthage/Checkouts/FieryCrucible/FieryCrucible/FieryCrucible.h:26:9: note: while building module 'UIKit' imported from /Users/vojta/dev/ios/alpha Carthage/iOS/Build/Alpha/Carthage/Checkouts/FieryCrucible/FieryCrucible/FieryCrucible.h:26:
	#import <UIKit/UIKit.h>
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UICollectionViewLayout.h:11:9: note: while building module 'QuartzCore' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UICollectionViewLayout.h:11:
	#import <QuartzCore/CATransform3D.h>
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAEAGLLayer.h:7:9: note: while building module 'OpenGLES' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAEAGLLayer.h:7:
	#import <OpenGLES/EAGLDrawable.h>
	        ^
	<module-includes>:1:9: note: in file included from <module-includes>:1:
	#import "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h"
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h:8:10: error: could not build module 'Foundation'
	#include <Foundation/Foundation.h>
	         ^
	<module-includes>:1:9: note: in file included from <module-includes>:1:
	#import "/Users/vojta/dev/ios/alpha Carthage/iOS/Build/Alpha/Carthage/Checkouts/FieryCrucible/FieryCrucible/FieryCrucible.h"
	        ^
	/Users/vojta/dev/ios/alpha Carthage/iOS/Build/Alpha/Carthage/Checkouts/FieryCrucible/FieryCrucible/FieryCrucible.h:26:9: error: could not build module 'UIKit'
	#import <UIKit/UIKit.h>
	        ^
	<unknown>:0: error: could not build Objective-C module 'FieryCrucible'

I cloned it and I am able build it in xcode or using `xcodebuild`, but when I run `carthage build --no-skip-current` I get:

	*** xcodebuild output can be found in /var/folders/br/fd2dcx0d3x7fxfw_kp18twsw0000gn/T/carthage-xcodebuild.6edf6w.log
    *** Building scheme "FieryCrucible" in FieryCrucible.xcodeproj
    A shell task failed with exit code 65:
    2015-05-14 18:04:42.268 xcodebuild[31106:5266060] [MT] PluginLoading: Required plug-in compatibility UUID 9F75337B-21B4-4ADC-B558-F9CADF7073A7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMQuickHelp.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2015-05-14 18:04:42.269 xcodebuild[31106:5266060] [MT] PluginLoading: Required plug-in compatibility UUID 9F75337B-21B4-4ADC-B558-F9CADF7073A7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2015-05-14 18:04:42.485 xcodebuild[31106:5266060] [MT] iPhoneSimulator: SimVerifier returned: Error Domain=NSPOSIXErrorDomain Code=53 "Simulator verification failed." UserInfo=0x7fa2726a43b0 {NSLocalizedFailureReason=A connection to the simulator verification service could not be established., NSLocalizedRecoverySuggestion=Ensure that Xcode.app is installed on a volume with ownership enabled., NSLocalizedDescription=Simulator verification failed.}
    ** BUILD FAILED **

    The following build commands failed:
    CompileSwift normal arm64 /Users/vojta/dev/ios/FieryCrucible/FieryCrucible/DependencyFactory.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    (2 failures)

    Segmentation fault: 11

In the log there is a lot of errors like this:

     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/usr/include/objc/objc-load.h:33:10: note: while building module 'MachO' imported from     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/usr/include/objc/objc-load.h:33:
    #include <mach-o/loader.h>
         ^

With a lot of mentions of `iPhoneSimulator8.3.sdk`
`
Any Idea how to solve it ?

**Comment by mdiep** [comment]
You might try the instructions [here](https://github.com/Carthage/Carthage/issues/424#issuecomment-99551625) to fix the SimVerifier error. But it's hard to know what went wrong without seeing the entire log file. The end of the log isn't necessarily helpful because the primary error may be further up.

**Comment by vojtechvrbka** [comment]
Thanks!
It was the SimVerifier error. This [StackOverflow solution](http://stackoverflow.com/a/29923005/1121716) worked for me.
