### ISSUE TITLE
Missing symbol error when attempting to run carthage.

### ISSUE THREAD

**Issue by derrh** [Carthage/Carthage#457]
Looks like there may be a mismatch in the version of `libswiftCore` that `Result` was built against and what Carthage includes. The version I installed was 0.7.3 via homebrew. Here's the error message I'm getting:

    dyld: Symbol not found: __TWPSuSs21BitwiseOperationsTypeSs
      Referenced from: /usr/local/Cellar/carthage/0.7.3/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks//Result.framework/Versions/A/Result
      Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/libswiftCore.dylib
     in /usr/local/Cellar/carthage/0.7.3/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks//Result.framework/Versions/A/Result
    Trace/BPT trap: 5

**Comment by jspahrsummers** [comment]
This can occur if you have an old version of `/Library/Frameworks/CarthageKit.framework`. If you're using the Homebrew version of Carthage, you don't need that copy of the framework, so it can be safely deleted.

**Comment by derrh** [comment]
:+1: Thanks, that solved the problem.
