### ISSUE TITLE
Build with private, per-project DerivedData

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#459]
`carthage build` could use its own private DerivedData folder for each project built, and separate out those folders for each project as well.

This could theoretically allow us to parallelize builds (to the extent allowed by the dependency graph), since they'd no longer be modifying the same global location. It might also alleviate rebuilding issues like #432.

We could also purge this private folder automatically whenever we build a different dependency version, which could obviate the need for a [`carthage clean` command](https://github.com/Carthage/Carthage/pull/427).

**Comment by robrix** [comment]
I’ve been thinking about this a bit and came to approx. the same conclusion. I think it’s worth a shot.

**Comment by jspahrsummers** [comment]
N.B. `xcodebuild` provides a `-derivedDataPath` for this.
