### ISSUE TITLE
Carthage is including deleted header file from git history

### ISSUE THREAD

**Issue by simX** [Carthage/Carthage#463]
I've got a weird one here.  If you download the "carthage2" branch for my fork of kif here <https://github.com/simx/kif>, it compiles the framework successfully and without incident.  My most recent commit changed the name of the framework from "KIFFramework" to "KIF", and changed the name of the umbrella header file from KIFFramework.h to KIF.h.

However, when I build this branch using Carthage, Carthage somehow includes the old KIFFramework.h umbrella header file in the compiled framework!!  Building it normally via the xcodeproj file does not.  I can see of no other way Carthage can be including this file except from the git history, as there is literally no reference to "KIFFramework" anymore except a containing folder and the scheme name.  If you build it using Carthage, you'll notice that it's literally the old file -- my new umbrella header framework file includes an additional public header file that the old umbrella header framework file did not, and the name of the framework for all the includes has changed too, which it hasn't in the spurious KIFFramework.h.  So I think that rules out some build setting being wrong that causes the old-named header file to be automatically generated.

Has anybody seen similar issues with deleted/renamed files in git history?

I'm hoping that I'm just being super-dumb and that this issue is my fault, but I'm pretty sure it isn't.

**Comment by robrix** [comment]
Could you please paste the Cartfile you’re using to compile it? It could be that it’s building an older tag or commit because the Cartfile/Cartfile.resolved hasn’t pinned it to a newer one.

**Comment by simX** [comment]
Entire contents of cartfile: github "simx/KIF" "carthage2"
Entire contents of cartfile.resolved: github "simx/KIF" "8115475e2d0cbff8a6d43123fbdaaf05c752ba54"

**Comment by simX** [comment]
It doesn't seem to be building an older commit, though, because Carthage sees and is including my latest changes, and includes the latest KIF.h umbrella header file.  But it just also includes the spurious old KIFFramework.h file.  (The effect is that it produces a warning when you build in Xcode, saying that the umbrella header framework is not including KIFFramework.h, even though it shouldn't be necessary because that file shouldn't be there in the first place.)

**Comment by robrix** [comment]
Well, it’s definitely pinned to the correct commit, so let’s see if I can repro…

**Comment by robrix** [comment]
It doesn’t include `KIFFramework.h` when I bootstrap. Maybe something’s awry with the cache? Try removing `Carthage/Build` and `~/Library/Caches/org.carthage.CarthageKit/dependencies/KIF` and the DerivedData dir for KIF and see if that fixes it.

**Comment by simX** [comment]
That fixed it!  I had definitely deleted all the DerivedData dirs for kif before, but hadn't deleted the dependencies folder for kif in the Carthage cache.

**Comment by robrix** [comment]
You’re welcome!
