### ISSUE TITLE
Changing tag doesn't change the fetched version

### ISSUE THREAD

**Issue by samgrover** [Carthage/Carthage#464]
I'm currently using version 0.7.3.

I'm setting up Carthage for the first time and tagged a dependency's repo with a tag called "v1.0". The dependency is a framework named 'Excalibur'.
I added the Excalibur repo to the Cartfile of the parent, which is another framework of the name Camelot, so the Cartfile has only one line: `github "TheHolyGrail/Excalibur"`
I ran Carthage update and Excalibur v1.0 was fetched and built and all was good.
Now I decided to delete the v1.0 tag on Excalibur and made a new tag called v0.0.1 at the same commit. Pushed it to github and all looks good there.
Running `carthage update` on Camelot still says that it is fetching v1.0. And even if I delete the Cartfile and Cartfile.resolved and the Carthage folder completely, the behavior of `carthage update` doesn't change. It seems to be fetching the non-existent v1.0.
The only way it fetches v0.0.1 is if I change the line in the Cartfile to: `github "TheHolyGrail/Excalibur" == 0.0.1` but I don't want to specify a particular version.

Is this an issue or did I do something wrong? Did I not clean up properly? Am I going crazy?

Thanks!

**Comment by robrix** [comment]
Carthage expects tags to follow semantic versioning. In particular it doesn’t expect the version to go backwards :smile: I think in this case the solution is probably going to be to remove the cache of the repo from `~/Library/Caches/org.carthagekit.Carthage/dependencies/Excalibur`. (You might also need to remove the binary if there is one.)

**Comment by samgrover** [comment]
Ah, I missed that cache! And yea, it's not everyday that I go backwards. Was wondering that it had something to with that. Thanks Rob!

**Comment by robrix** [comment]
You’re welcome!

**Comment by pxlshpr** [comment]
This was a bit of a lifesaver, so thank you!
I'm wondering if this behaviour is unexpected enough to be considered a bug. Maybe some official documentation or preference over the remote set of tags over the cached ones would help others avoid this?
