### ISSUE TITLE
Rate limiting in binary downloads should be a warning, not an error

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#465]
https://github.com/Carthage/Carthage/pull/434 fixed our authentication with the GitHub API, and added proper error reporting for it.

Unfortunately, this has the effect that API rate limiting errors are now fatal, even though binary downloads shouldn't be strictly necessary for building. This can come up in automated workflows, or CI servers, where many requests might be made in a short period of time.

I still want to log rate limiting issues, but I think they should be warnings instead of errors.

**Comment by mdiep** [comment]
Good call. :+1:

**Comment by jberkel** [comment]
> By contrast, Carthage has been created as a decentralized dependency manager. 

By requiring the Github API and causing build failures if it is not accessible? Maybe binary downloads should be opt-in, not opt-out.

**Comment by jspahrsummers** [comment]
@jberkel You’ve read the issue description, right?

> Unfortunately, this has the effect that API rate limiting errors are now fatal, even though binary downloads shouldn't be strictly necessary for building.

We only enjoy snarkiness from those who contribute. Thanks!

**Comment by jberkel** [comment]
Ok, will see if I can come up with a patch to get the snark bit.
