### ISSUE TITLE
Support a --no-checkout flag for bootstrap/update?

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#466]
I've previously been (in a thread I can't find) against adding another command that can resolve dependencies without checking them out. I still am against adding a command besides `update`, but it occurs to me that we could add a flag (disabled by default) that skips the checkout step.

This could be useful in cases where you want to perform some sort of custom checkout logic, a la the [`carthage-developer-checkouts` workflow](https://github.com/Carthage/workflows/blob/142231860c72b99a965af73dc649fdf330dcdf20/carthage-developer-checkouts).

**Comment by robrix** [comment]
Would be _very_ useful when testing bugs apparently occurring with `update` but not `bootstrap`.
