### ISSUE TITLE
Dependencies’ Carthage checkouts are not populated when checking out parent projects

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#467]
If a dependency project B uses Carthage to add projects like [jspahrsummers/xcconfigs](https://github.com/jspahrsummers/xcconfigs), and _is not using submodules_, this can cause issues when B is integrated in a parent project A.

Specifically, `Carthage/Checkouts/xcconfigs` will be created if you run `carthage bootstrap` within project B, but not when run from project A. Since project B requires those files to build, the overall build will fail.

There are a couple of workarounds for this right now:

1. Commit affected checkouts directly into the Git repository, so they’re always available when Carthage clones it.
1. Skip Carthage for the affected checkouts, and add them as submodules outside of the `Carthage` folder.
1. Enable `--use-submodules` when using Carthage in project B.

All of these have certain drawbacks, and it feels like having to structure a workflow to work around a flaw in the tool.

What if we symlinked `Carthage/Checkouts` into every dependency, much like `Carthage/Build`? That wouldn’t solve this problem for private dependencies (because those won’t get checked out by the parent), but would allow other checkouts to be shared. If we wanted to do that, we would need to think about the behavior in the face of existing checkout folders.

**Comment by robrix** [comment]
I think symlinking `Carthage/Checkouts` is a good solution, but I don’t have any intuition for the best way to handle extant directories. Move the old one aside?

**Comment by jspahrsummers** [comment]
It might be best to symlink `Carthage/Checkouts/*` instead of `Carthage/Checkouts/` (compare with how we symlink `Carthage/Build/`), so we can create links for checkouts that don’t already exist, but leave others untouched.

**Comment by robrix** [comment]
Good thought. Maybe we should log about extant non-link entries in `--verbose` mode?

**Comment by jspahrsummers** [comment]
:+1:
