### ISSUE TITLE
Unable to build ReactiveCocoa v3.0-beta.4 with carthage: no such module 'Box'

### ISSUE THREAD

**Issue by memmons-ntst** [Carthage/Carthage#468]
This is the entirety of my cart file:
`github "ReactiveCocoa/ReactiveCocoa" ~> 3.0`

I wasn't sure if this should be filed as a Carthage issue or ReactiveCocoa issue, so I did both:
https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2013

The non-verbose output can be found here: 
https://gist.github.com/memmons-ntst/201af8aa111b8b3e9ad7
 
The relevant part of the build log can be found here:
https://gist.github.com/memmons-ntst/d2b8fb9b3bd2bb4a13fc

The error I see in the build log is :
`Carthage/Checkouts/Result/Result/Result.swift:200:8: error: no such module 'Box'`

This is on a new install of xcode 6.3.1 (6D1002) running on OS 10.10.4.

**Comment by memmons-ntst** [comment]
Note: The only way I could get this to work was to manually clone the Box repo. I tried updating via carthage with the latest version and version 0.6.4 and in both cases the /Carthage/Checkouts/Box directory always remained empty, even though carthage indicated that Box was fetched every time.

**Comment by robrix** [comment]
The hangs are probably the same issue as #449. Not fetching is weird O_o

**Comment by memmons-ntst** [comment]
Just tried again with a clean directory only containing a cartfile. 
```
carthage update --platform ios
*** Fetching ReactiveCocoa
*** Fetching Result
*** Fetching Box
*** Checking out Result at "0.4.3"
*** Downloading Box at "1.2.2"
*** Checking out ReactiveCocoa at "v3.0-beta.5"
*** xcodebuild output can be found in /var/folders/4g/xch3276j5dq2p52njjj4k72h0000gn/T/carthage-xcodebuild.XMoMHT.log
*** Building scheme "Result-iOS" in Result.xcworkspace
** BUILD FAILED **


The following build commands failed:
...
```
```
:$ cd Carthage
:$ cd Checkouts
:$ cd ReactiveCocoa
:$ carthage update --platform ios
*** Fetching Result
*** Fetching xcconfigs
*** Fetching Quick
*** Fetching Nimble
*** Fetching Box
*** Downloading Box at "1.2.2"
*** Checking out Result at "0.4.3"
*** Downloading Quick at "v0.3.1"
*** Checking out xcconfigs at "0.8"
*** Checking out Nimble at "v0.4.2"
*** xcodebuild output can be found in /var/folders/4g/xch3276j5dq2p52njjj4k72h0000gn/T/carthage-xcodebuild.glcogs.log
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Result-iOS" in Result.xcworkspace
** BUILD FAILED **

The following build commands failed:
...
```
```
:$ cd Carthage
:$ cd Checkouts/
:$ ls
Nimble		Result		xcconfigs
```
If I go back up to the root directory where I started from:
```
:$ cd Carthage
:$ cd Checkouts
:$ ls
ReactiveCocoa   Result
:$ cd Result/Carthage/Checkouts/Box
:$ ls
<empty>
```

**Comment by jspahrsummers** [comment]
Box is not being checked out because it is available as a binary. That's what the “Downloading” step means.

Unfortunately, I can't speak as to why that's causing Result's build to fail. Seems like Result should either have Box as a submodule, or be able to find it as a binary. @robrix?

**Comment by robrix** [comment]
`Result` includes [`Box` as a submodule](https://github.com/antitypical/Result/blob/master/.gitmodules#L3).

**Comment by robrix** [comment]
So sounds like it’s not getting checked out?

**Comment by jspahrsummers** [comment]
@memmons-ntst Could you please run `git config --global --list` and share the results?

**Comment by memmons-ntst** [comment]
```
olor.diff=true
color.status=auto
color.branch=auto
merge.tool=textedit
aslias.last=log -1 HEAD
alias.unstage=reset HEAD --
alias.visual=gitk
core.editor=open -W -n
core.excludesfile=/Users/mgemmons/.gitignore_global
difftool.sourcetree.cmd=opendiff "$LOCAL" "$REMOTE"
difftool.sourcetree.path=
mergetool.sourcetree.cmd=/Applications/SourceTree.app/Contents/Resources/opendiff-w.sh "$LOCAL" "$REMOTE" -ancestor "$BASE" -merge "$MERGED"
mergetool.sourcetree.trustexitcode=true
credential.helper=osxkeychain
push.default=simple
filter.media.required=true
filter.media.clean=git media clean %f
filter.media.smudge=git media smudge %f
filter.hawser.clean=git hawser clean %f
filter.hawser.smudge=git hawser smudge %f
filter.hawser.required=true
filter.lfs.clean=git lfs clean %f
filter.lfs.smudge=git lfs smudge %f
filter.lfs.required=true
```

**Comment by memmons-ntst** [comment]
@jspahrsummers Any update on this?

**Comment by jspahrsummers** [comment]
Sorry, no. So far, it doesn't seem to be occurring for anyone else. Without more information, it's hard for any of us to debug it (and furthermore, obtain the _free time_ to).

We'll happily accept a pull request if you can figure out what's going on, though!

**Comment by memmons-ntst** [comment]
I moved back to Carthage version 0.6.4, cloned RAC v3.0-beta.8 into a new directory and ran `carthage udpate`. At least it provides new/different errors. I'll try installing the official hombrew 0.7.4 version next. I don't think I've tried the final version of it.

```
*** Downloading Box at "1.2.2"
2015-06-11 07:48:45.134 carthage[76437:2079547] NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9812)
2015-06-11 07:48:45.267 carthage[76437:2079547] NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9812)
Error Domain=NSURLErrorDomain Code=-1202 "The operation couldn’t be completed. (NSURLErrorDomain error -1202.)" UserInfo=0x7fa8a3e52840 {NSURLErrorFailingURLPeerTrustErrorKey=<SecTrust 0x7fa8a3c81560 [0x7fff77ff4ed0]>, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9812, NSUnderlyingError=0x7fa8a3e0f4d0 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1202.)", NSErrorPeerCertificateChainKey=(
    "<SecCertificate 0x7fa8a3c8f310 [0x7fff77ff4ed0]>",
    "<SecCertificate 0x7fa8a3ccda30 [0x7fff77ff4ed0]>"
), NSErrorFailingURLKey=https://github.com/robrix/Box/releases/download/1.2.2/Box.framework.zip, NSErrorFailingURLStringKey=https://github.com/robrix/Box/releases/download/1.2.2/Box.framework.zip, NSErrorClientCertificateStateKey=0}
```

**Comment by zipme** [comment]
@memmons-ntst Which git version do you use? I got the same issue when I was using git 1.8.x, after upgrading to git 2.4.3 it built successfully.

**Comment by jdhealy** [comment]
@memmons-ntst The way carthage is designed, [version range requirements like `~>` or `==` aren't meant to specify versions with labels like "v3.0-beta.8"](https://github.com/Carthage/Carthage/pull/499#issuecomment-106657963). In addition, there are also some ["oddities with the resolver and tag names"](https://github.com/Carthage/Carthage/issues/469).

You might want to specify a tag name like `github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.8"`.

Trashing the `~/Library/Caches/org.carthage.CarthageKit` directory helps with some problems too.

**Comment by paulbruneau** [comment]
@jdhealy your tip to trash that directory just got Carthage working for me after 2 days of trying. Previously, every repo I tried to add with it just gave me "No such module". Thank you.

**Comment by ikesyo** [comment]
@memmons-ntst Do you have any updates on this with removing the cache `~/Library/Caches/org.carthage.CarthageKit/dependencies/Result` or using latest release 0.8?

**Comment by memmons-ntst** [comment]
@ikesyo Removing the caches didn't work. I finally just downloaded git 2.5 from https://git-scm.com/download/mac, nuked my existing version and installed git 2.5. ReactiveCocoa will now build properly.

This is both :+1: :sparkles:  and :interrobang: :boom: .

**Comment by patgdut** [comment]
I use this Cartfile config:
github "antitypical/Result" == 0.5
github "ReactiveCocoa/ReactiveCocoa"

It's working on xCode 7 GM
