### ISSUE TITLE
Carthage and Travis-CI (Xcode 6.3)

### ISSUE THREAD

**Issue by Francescu** [Carthage/Carthage#473]
I can't manage to install `carthage` in a travis-ci using xcode 6.3.

Here is the `.travis.yml`:

```
osx_image: xcode63
language: objective-c
xcode_project: TV.xcodeproj
before_install: 
  - brew update
  - brew upgrade xctool
  - brew install carthage
  - carthage bootstrap --verbose
xcode_scheme: TV
```

Here is the error:
```
$ brew install carthage
carthage: A full installation of Xcode.app 6.3 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.
```

It seems to work with older releases (Xcode611) as I look on other repos (like `mozilla/firefox-ios`)

**Comment by neilpa** [comment]
I didn't think Travis supports Xcode 6.3 yet - travis-ci/travis-ci#3216

**Comment by robrix** [comment]
@neilpa is [correct](http://blog.travis-ci.com/2015-04-20-state-of-the-mac-infrastructure-on-travis-ci/), unfortunately.

**Comment by Francescu** [comment]
You're alright, my bad.

**Comment by msanders** [comment]
Travis [officially](http://blog.travis-ci.com/2015-05-29-this-week-in-travis-ci/) supports Xcode 6.3 now and it still fails with this error :-(

**Comment by robrix** [comment]
@msanders I’m not sure that it does, but Swift releases are paired with Xcode releases, i.e. Swift 1.2 ships with Xcode 6.3, and Xcode 6.3—and its CLI tools—are OS X 10.10+, hence the holdup for Travis.

**Comment by jspahrsummers** [comment]
Sounds like an error in the Homebrew formula. Carthage itself only requires the command line tools.

**Comment by msanders** [comment]
Turns out I had the wrong `osx_image` set. When changed to `beta-xcode6.3`, I get this error instead (from #381, which strangely doesn't happen on my machine anymore even with an iOS 7 simulator installed):

```
+carthage checkout
*** Cloning Nimble
*** Downloading Quick at "v0.3.1"
*** Checking out Nimble at "v0.4.2"
+carthage build
*** xcodebuild output can be found in /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/carthage-xcodebuild.UMZEN7.log
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
A shell task failed with exit code 65:
2015-06-06 04:23:27.511 xcodebuild[2051:5327] [MT] iPhoneSimulator: SimVerifier returned: Error Domain=NSPOSIXErrorDomain Code=53 "Simulator verification failed." UserInfo=0x7fd93d32b810 {NSLocalizedFailureReason=A connection to the simulator verification service could not be established., NSLocalizedRecoverySuggestion=Ensure that Xcode.app is installed on a volume with ownership enabled., NSLocalizedDescription=Simulator verification failed.}
```

**Comment by msanders** [comment]
FWIW, this seems to have been fixed in Xcode 6.4 (which is now supported by Travis).

**Comment by samskiter** [comment]
I've just had this issue for xcode 7.3, which Travis supposedly supports.

is there any workaround?

**Comment by bobsummerwill** [comment]
Me too, @samskiter.

See https://travis-ci.org/ethereum/cpp-ethereum/jobs/153117742

Which is part of https://travis-ci.org/ethereum/cpp-ethereum/builds/153117739.

It is just the xcode7.1 project which is failing (the TravisCI Yosemite image).

So doing a `brew update && brew upgrade` within TravisCI is now broken there.   I am digging into the issue right now.   It just appeared today.

**Comment by bobsummerwill** [comment]
See https://github.com/Homebrew/homebrew-core/issues/3996.  I've logged a Homebrew issue about this too.
