### ISSUE TITLE
carthage update randomly hangs

### ISSUE THREAD

**Issue by schwa** [Carthage/Carthage#478]
Latest version of Carthage (0.7.3) seems to hang at random when building/checking out repositories

Gist of a sample process here: https://gist.github.com/schwa/5953442a2066ff0f5984

**Comment by mdiep** [comment]
There are already several issues for this (#445 and #455 are still open), as well as a WIP PR that hopefully fixes it (#474).

Sorry for the inconvenience, but we are trying to track down the cause.

**Comment by jspahrsummers** [comment]
I've tagged [0.7.4](https://github.com/Carthage/Carthage/releases/tag/0.7.4), which should fix all the hanging and crashing issues that we know about. The update should [become available in Homebrew](https://github.com/Homebrew/homebrew/pull/40450) soon.

**Comment by JetForMe** [comment]
I'm still seeing random hangs in Carthage, at various stages of running `carthage update`. Sometimes I get nothing at all, sometimes it checks out a repo or two, sometimes it makes it through a build. In all cases, interrupting it with `ctrl-C` and running it again lets it get farther along (it sometimes takes more than two invocations). Version 0.17.1.

**Comment by tolikvasylyk** [comment]
Did you find a solution?
