### ISSUE TITLE
carthage update silently fails after prompting to accept connection to a new ssh host

### ISSUE THREAD

**Issue by akitchen** [Carthage/Carthage#480]
```
*** Checking out some_repo at "d55468dd027169a1295013461685143061ea8fd1"
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes


^C
```
if I ```ssh git@github.com``` then ```carthage update``` again, this issue doesn't happen and installation continues.

**Comment by akitchen** [comment]
by "silently fails", what I really mean is that it hangs indefinitely

**Comment by robrix** [comment]
We’re probably not passing stdin along.

**Comment by jspahrsummers** [comment]
Yeah, this is the same issue as https://github.com/Carthage/Carthage/issues/219. Sorry about that!

**Comment by akitchen** [comment]
Thanks, I searched but didn't notice that one. Sorry for the dupe.

**Comment by jspahrsummers** [comment]
No problem!
