### ISSUE TITLE
`carthage copy-framework` not copying folders in frameworks for watchkit extension

### ISSUE THREAD

**Issue by simonyangme** [Carthage/Carthage#481]
I get the following error when I try to install my app via xcode:

    Signed resources have been added, removed, or modified

Running `codesign` to verify the watchkit extension results in:

    /Users/lokisnake/Library/Developer/Xcode/DerivedData/SomeApp-dsmkwtskmzgijgeuqlthcfbmbtqm/Build/Products/Debug-iphoneos/SomeApp.app/PlugIns/SomeApp WatchKit Extension.appex: a sealed resource is missing or invalid
    file missing: /Users/lokisnake/Library/Developer/Xcode/DerivedData/SomeApp-dsmkwtskmzgijgeuqlthcfbmbtqm/Build/Products/Debug-iphoneos/SomeApp.app/PlugIns/SomeApp WatchKit Extension.appex/Frameworks/ReactiveCocoa.framework/Headers/UIImagePickerController+RACSignalSupport.h

and many more of the file missing errors.

My current setup has a `carthage copy-framework` run script build phase for both the main app and the watch extension.

**Comment by jspahrsummers** [comment]
Hmm, I don't think we've tested `copy-frameworks` with an extension. I'm not sure what its behavior would be.

Could you share a screenshot of that Run Script build phase?

**Comment by simonyangme** [comment]
This is what I had for the Run Script Build Phase for the watch app extension (Really the same as what I had for my main app):

![screen shot 2015-05-19 at 4 14 03 pm](https://cloud.githubusercontent.com/assets/48696/7715968/31fb138e-fe42-11e4-8cfe-ddd6f1bfcbad.png)

P.S. I've since switched to using CocoaPods as this was blocking some of my work. I'll try to provide as much info as I can.

**Comment by jspahrsummers** [comment]
I'm glad you have a workaround for this, as I'm not immediately certain what's causing the issue.

If you could get a chance, could you please share the ReactiveCocoa.framework bundle that actually got copied into the WatchKit extension (missing files as it may)?

**Comment by Thomvis** [comment]
As far as I know you shouldn't copy frameworks into the Watch Extension. Instead, add those frameworks to the copy phase of the main target. The watch extension will be able to find them there. (It's in the runtime search paths.)

Fun fact: I actually moved from CocoaPods to Carthage because CocoaPods did not work for me in this case. It looks like they've fixed it since.

**Comment by simonyangme** [comment]
@Thomvis Looks like that worked! Thanks!

@jspahrsummers, sorry for the wild goose chase. 😳

**Comment by jspahrsummers** [comment]
No worries! I learned something. :smile:

**Comment by MarcoSero** [comment]
I believe with the new Watch App architecture on watchOS 2 this has changed. 
I managed to make the frameworks visible and get rid of the error `"No such module 'X'"` by adding `$(PROJECT_DIR)/Carthage/Build/iOS` to the Framework Search Paths of the Watch Extension and adding the `copy frameworks` phase.

Unfortunately I'm now stuck on the error:
```
Module file was created for incompatible target i386-apple-ios8.0
```
The app and the extension are targeting iOS 9 and `xcode-select -p` gives me the latest Xcode 7 beta.
Any ideas anyone?

**Comment by neilpa** [comment]
@MarcoSero I haven't built anything for the watch yet, but shouldn't you be linking against a watchOS version of the framework and not iOS, e.g. `$(PROJECT_DIR)/Carthage/Build/watchOS`?

**Comment by MarcoSero** [comment]
@neilpa Thanks, that makes sense. Does Carthage support building frameworks for the watchOS arch yet?

**Comment by blender** [comment]
The error seems to tell me that those frameworks are for the wrong architecture

Try:
`file Carthage/Build/watchOS/RxCocoa.framework`

**Comment by Fr3qu3ntFly3r** [comment]
I think that's not a problem. I am already using the files from the watchOS folder.

![screenshot 2018-07-05 at 18 52 45](https://user-images.githubusercontent.com/26151031/42312822-9d271a8c-8084-11e8-9adf-075dcb093bbb.png)
![screenshot 2018-07-05 at 18 48 25](https://user-images.githubusercontent.com/26151031/42312715-667a759c-8084-11e8-83e5-e6f86c7d5cdd.png)
