### ISSUE TITLE
Stuck at random step while trying to install Squirrel through Carthage

### ISSUE THREAD

**Issue by psequel** [Carthage/Carthage#482]
I have Carthage v0.7.3 installed via `homebrew`. There is only one line in my Cartfile, `github "Squirrel/Squirrel.Mac" == 0.1.6`. Tried `cart update` a few times and it never succeed -- stuck at a different step each time. Removing `carthage` and `org.carthage.CarthageKit` directories in `~/Library/Caches` doesn't help.

PS: I created this issue under [Squirrel/Squirrel.Mac](/Squirrel/Squirrel.Mac/issues/146) initially but it seems like a Carthage issue.

**Comment by jspahrsummers** [comment]
Sorry about that. This sounds like the same underlying problem as https://github.com/Carthage/Carthage/issues/455 or https://github.com/Carthage/Carthage/issues/445.

**Comment by jspahrsummers** [comment]
I've tagged [0.7.4](https://github.com/Carthage/Carthage/releases/tag/0.7.4), which should fix all the hanging and crashing issues that we know about. The update should [become available in Homebrew](https://github.com/Homebrew/homebrew/pull/40450) soon.
