### ISSUE TITLE
Build successfully but there is no framework in build folder

### ISSUE THREAD

**Issue by Draveness** [Carthage/Carthage#484]
How to support my framework for Carthage?

I make the scheme status to shared and then run 

```
xcodebuild -scheme DKChainableAnimationKit -project DKChainableAnimationKit.xcodeproj build
```

This BUILD SUCCESSDED

But when I run `carthage update` in my test project.

```
*** Fetching DKChainableAnimationKit
*** Checking out DKChainableAnimationKit at "1.1.2"
*** xcodebuild output can be found in /var/folders/b_/zmq01c3j3fqd0nc7n75pylm40000gn/T/carthage-xcodebuild.7ZXBfb.log
```

The Carthage/Build folder is empty.

This is my cartfile.

```
github "Draveness/DKChainableAnimationKit"
```

**Comment by freak4pc** [comment]
I was actually just trying to build your project unsuccessfully :)

**Comment by jspahrsummers** [comment]
@Draveness Your project does not build a dynamic framework. Carthage only supports dynamic framework targets.

**Comment by Draveness** [comment]
And how can I build a dynamic framework... I don't know how to do that. I just followed the instruction is README. But I failed..

**Comment by ikesyo** [comment]
@Draveness Your project has only application target and test target, not have a dynamic framework target. You should add a "Cocoa Touch Framework" target to your project, then add the necessary source files to the target.

**Comment by Draveness** [comment]
@ikesyo  Thank you very much. Follow your suggestion, I have already supported my library for Carthage. :+1:
