### ISSUE TITLE
carthage update stuck on 0.7.3

### ISSUE THREAD

**Issue by freak4pc** [Carthage/Carthage#485]
Carthage newbie here.
Here's my super-simple Cartfile:

```
github "realm/realm-cocoa"
github "Alamofire/Alamofire" >= 1.2
github "facebook/pop"
github "Draveness/DKChainableAnimationKit"
```

It seems to get stuck after the clon/checkout... Have been waiting for a while now.
Is it supposed to be this slow? 

![image](https://cloud.githubusercontent.com/assets/605076/7749273/bd2dad3e-ffd4-11e4-8fef-96ce38931046.png)

Thanks
Shai

**Comment by freak4pc** [comment]
After running the same command for about 4 times it gets here, and then stuck as well

![image](https://cloud.githubusercontent.com/assets/605076/7749304/24d71790-ffd5-11e4-9987-32c088744a8c.png)

**Comment by mdiep** [comment]
Unfortunately, this is due to a deadlock. There are already several issues for this (#445 and #455 are still open), as well as a WIP PR that hopefully fixes it (#474).

Sorry for the inconvenience, but we are trying to track down the cause. In the meantime, I believe you can work around the issue by running `checkout` and `build` as separate steps.

**Comment by freak4pc** [comment]
Thanks @mdiep , 
When I try to do `carthage checkout` I get

Failed to read file or folder at /Users/freak4pc/Work/DreamDate/DreamDate-iOS/Cartfile.resolved: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile.resolved” couldn’t be opened because there is no such file." UserInfo=0x7ff9bbc23620 {NSFilePath=/Users/freak4pc/Work/DreamDate/DreamDate-iOS/Cartfile.resolved, NSUnderlyingError=0x7ff9bbc1cfd0 "The operation couldn’t be completed. No such file or directory"}

**Comment by freak4pc** [comment]
Doing carthage update before sorted that out... 
But now something else is weird. Its building only Alamofire and ignores the other two .. Am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/605076/7750532/75f1f886-ffdd-11e4-819c-96bef3edc6f8.png)

**Comment by mdiep** [comment]
It downloaded a pre-built copy of realm-cocoa, so it doesn't need to build it. I'm not why `DKChainableAnimationKit` wouldn't build.

**Comment by freak4pc** [comment]
Guess I'll step back for a bit until this is resolved and is stable enough ...
Following one of the issues above would be a good enough indication?

Thanks again for the huge help.
Shai

**Comment by jspahrsummers** [comment]
I've tagged [0.7.4](https://github.com/Carthage/Carthage/releases/tag/0.7.4), which should fix all the hanging and crashing issues that we know about. The update should [become available in Homebrew](https://github.com/Homebrew/homebrew/pull/40450) soon.

**Comment by oinsider** [comment]
Just enter carthage and hit enter. It worked for me ;)
