### ISSUE TITLE
Carthage with dependencies pulled in using CocoaPods

### ISSUE THREAD

**Issue by priteshshah1983** [Carthage/Carthage#486]
I wanted to add Carthage support for [Rest2Mobile](https://github.com/magnetsystems/r2m-sdk-ios). ````Rest2Mobile```` depends on other open-source libraries like ````AFNetworking```` and ````CocoaLumberjack````. AFAIK, these libraries don't support Carthage yet. ````Rest2Mobile```` also uses ````Mantle```` which supports Carthage. I would like to continue to use CocoaPods to bring in these external dependencies, but distribute ````Rest2Mobile```` itself using Carthage, if that makes sense.

I had a question:
- Will/Should the Carthage generated ````Rest2Mobile```` framework embed all its dependencies?

Any suggestions will be really appreciated.

**Comment by jspahrsummers** [comment]
Unfortunately, this is a recipe for pain. Because other tools have no understanding of CocoaPods’ format, it becomes impossible for those dependencies to be pulled down (or included into a dependency resolution graph) automatically.

In other words, whether someone wants to use Carthage or just plain Xcode, they would not be able to do so without first invoking CocoaPods.

I would instead suggest distributing your project as a standard Xcode project—with or without using Carthage—then using CocoaPods at the consumer site if desired.

**Comment by priteshshah1983** [comment]
Thanks for the quick response @jspahrsummers! This is what threw me off:

When I run ````carthage build --no-skip-current```` in a test project with the same setup, the generated framework contains ````AFNetworking.framework````

![](https://dl.dropboxusercontent.com/u/25131624/Shared/Carthage-issue-486.png)

This is my ````Podfile```` if it helps:
````
$ cat Podfile
platform :ios, '8.0'
use_frameworks!

pod 'AFNetworking', '~> 2.5'
````

But, the architectures are not correct for the ````AFNetworking.framework````

````
$ lipo -info Carthage/Build/iOS/MobileKit.framework/MobileKit
Architectures in the fat file: Carthage/Build/iOS/MobileKit.framework/MobileKit are: i386 x86_64 armv7 arm64 

$ lipo -info Carthage/Build/iOS/MobileKit.framework/Frameworks/AFNetworking.framework/AFNetworking 
Architectures in the fat file: Carthage/Build/iOS/MobileKit.framework/Frameworks/AFNetworking.framework/AFNetworking are: armv7 arm64

**Comment by jspahrsummers** [comment]
That will also be a problem, but consider that `carthage build` only worked because you had installed the CocoaPods dependencies already.

Other users will _also_ need to `pod install` for building to even complete successfully, meaning that you are requiring CocoaPods even if you want to support other distribution mechanisms.

**Comment by priteshshah1983** [comment]
> I would instead suggest distributing your project as a standard Xcode project—with or without using Carthage—then using CocoaPods at the consumer site if desired.

If I had to go down this path, is there a way to exclude these external dependencies from ````carthage build````? i.e. exclude ````AFNetworking.framework```` in this case. Then, ````AFNetworking```` will continue to be pulled in using CocoaPods or some other approach.

I assume I need to do that to avoid duplicate symbols, or am I missing something?

**Comment by jspahrsummers** [comment]
No, you shouldn't need to do that to avoid duplicate symbols. As long as only one copy of symbols _ends up in the app bundle_, you'll be fine.

So, you can build `AFNetworking.framework` but link using CocoaPods and everything should be fine.

**Comment by priteshshah1983** [comment]
Thanks for all your help @jspahrsummers! I am planning to get rid of the ````Frameworks```` directory and resign it to reduce the size of my framework binary.

I guess it wouldn't hurt.

**Comment by thebugcode** [comment]
Could it be that even if you're using Cocoapods for your own project, embedding the .framework as part of the release on github, would allow anyone to download your framework, regardless of how it was built, cocoapods or not?

Or am I missing something

**Comment by YuryBogdanov** [comment]
Has anything changed regarding this issue? 
I have a private CocoaPod which depends on other private cocoapods and now I have to support Carthage as well. However, I'm not sure if this will ever work, since my dependencies do not support Carthage...
