### ISSUE TITLE
No shared scheme error

### ISSUE THREAD

**Issue by alec-c4** [Carthage/Carthage#487]
Hi,
Could you please help me with following - i'm attempting to add Carthage support to my fork of [SwiftyUserDefaults](https://github.com/alec-c4/SwiftyUserDefaults), but see error

```
Project "SwiftyUserDefaults.xcodeproj" has no shared schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/alec-c4/SwiftyUserDefaults/issues/new
Build settings from command line:
    SDKROOT = iphoneos8.3
```

How to fix it? And could you please add to wiki how-to and faqs for developers who want to add Carthage support for their projects?

You can try to add my for to your test project and reproduce error

**Comment by ikesyo** [comment]
@alec-c4 You should follow the steps (1 and 2) in [the document](https://developer.apple.com/library/ios/recipes/xcode_help-scheme_editor/Articles/SchemeShare.html) which is [referenced in this repository's README](https://github.com/Carthage/Carthage#share-your-xcode-schemes).

**Comment by alec-c4** [comment]
Yeah!!!! Thanks a lot!!! I've missed this step :(
