### ISSUE TITLE
Wrong version number reported

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#490]
It seems carthage 0.7.3 is reporting the wrong version number

```bash
@~ $ brew install carthage
Warning: carthage-0.7.3 already installed
@~ $ carthage version
0.7.1
@~ $ ls -l /usr/local/bin/carthage
lrwxr-xr-x  1 jstein  admin  37 May 25 09:01 /usr/local/bin/carthage@ -> ../Cellar/carthage/0.7.3/bin/carthage
```

**Comment by mdiep** [comment]
You must have a 0.7.1 version of CarthageKit on your system. Since you're using homebrew, check if you have a copy of CarthageKit at `/Library/Frameworks/CarthageKit.framework`. If you do, delete that copy and you should be fine.

**Comment by jeeftor** [comment]
Thanks!
