### ISSUE TITLE
Github issues with 0.7.3 (reporting as 0.7.1)

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#491]
I'm running what i believe is `0.7.3` (as installed from home-brew) although it does report its own version as `0.7.1` (see issue #490).

I'm running into some sort of credential issue where it stalls out when I try to use the GitHub thing such as:

`github "daltoniam/SwiftHTTP"`

If i switch to:  `git "https://github.com/daltoniam/SwiftHTTP.git" "0.9.4"` in my cartfile I have no issues.

**Comment by mdiep** [comment]
This was resolved for most people in 0.7.2. Even though you installed 0.7.3 via homebrew, `carthage` is finding the 0.7.1 version of CarthageKit, which holds all of the logic. In effect, you're using 0.7.1.
