### ISSUE TITLE
Carthage does not fail with non-existent realm version

### ISSUE THREAD

**Issue by pietbrauer** [Carthage/Carthage#494]
Given a Cartfile

```bash
github "realm/realm-cocoa" ~> 0.96.0 # 0.92.4 is the latest
```

You get the following output:

```bash
$ carthage update
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "v0.0.24b"
*** xcodebuild output can be found in /var/folders/9v/9z2qkhhx57zbdn9876mq__497d7w_y/T/carthage-xcodebuild.eyXsxV.log
Project "TightDbExample.xcodeproj" has no shared schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/realm/realm-cocoa/issues/new
```

The same thing with SSKeychain does fail correctly.

```bash
github "soffes/SSKeychain" ~> 3.0.0 # 1.2.3 is the latest
```
```bash
$ carthage update
*** Fetching SSKeychain
No available version for github "soffes/SSKeychain" satisfies the requirement: ~> 3.0.0
```

Related to: https://github.com/realm/realm-cocoa/issues/1949

**Comment by pietbrauer** [comment]
Expected outcome is of course that it fails for realm the same way as it does for `SSKeychain`.

**Comment by jpsim** [comment]
We're happy to consider updating/removing our old tags if this isn't a Carthage issue.

**Comment by neilpa** [comment]
@jpsim We did this with a few defunct [RAC tags](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1910) but I think the version parser should handle this. Strictly speaking there should be a dash in there (`0.0.24-b`) but it's not uncommon to see it missing in the wild.

**Comment by jspahrsummers** [comment]
This sounds like https://github.com/Carthage/Carthage/issues/469. I'm not sure exactly how our version parser is seeing strings like this, but something's definitely funky.
