### ISSUE TITLE
/Library/Frameworks takes priority over Homebrew installation

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#495]
If you've installed Carthage from [the Homebrew formula](https://github.com/Homebrew/homebrew/blob/d1f70d44369de4d4998af351428f2b72e3dbf29d/Library/Formula/carthage.rb), you might expect that `carthage` would always use the version of CarthageKit installed from Homebrew.

Unfortunately, it seems like the executable always prioritizes loading frameworks from `/Library/Frameworks`, even though that's only populated from our package installer. This results in issues like #490.

We should update the formula and/or `Makefile` to prioritize custom framework locations over the “base” ones.

**Comment by robrix** [comment]
Would this be a `LD_RUNPATH_SEARCH_PATHS` thing?

**Comment by jspahrsummers** [comment]
Sorta, but there are actual values for `@rpath` injected into the executable, and IIRC the Homebrew prefix is used for one of those. I think the priority of that additional path is just wrong.

**Comment by robrix** [comment]
Oh right! I forgot we did that :+1:

**Comment by deadlyfingers** [comment]
With homebrew `brew install carthage` it seems there is only carthage-0.16.2 available - how can I update to the lastest release?

**Comment by ikesyo** [comment]
Run `brew update` first.
