### ISSUE TITLE
Add bash completion

### ISSUE THREAD

**Issue by larryonoff** [Carthage/Carthage#500]

**Comment by yoichitgy** [comment]
I wrote bash/zsh completion scripts as WIP PR #731.

For now, I added the scripts and a draft version of README to script/completion/ directory in the Carthage repository. I think still the following things are remained to do.

- Decide where to store the scripts in the Carthage repository.
- Modify installer settings (.pkg and brew) to include the scripts.
- Update README to mention the bash/zsh completion.

Would you give me advice about them?

**Comment by mdiep** [comment]
#731 has been merged. :fireworks:
