### ISSUE TITLE
Add betas to homebrew

### ISSUE THREAD

**Issue by aschuch** [Carthage/Carthage#502]
Are you planning to add beta versions of Carthage to homebrew as well?

I think it would be nice to be able to quickly test and verify betas via homebrew instead of installing from the provided .pkg file. Using homebrew as the single choice to install Carthage would also make it easier to test new versions and switch back to a stable release afterwards.

**Comment by robrix** [comment]
I don’t think there’s anything preventing anybody from submitting betas to homebrew, but I don’t know if homebrew would be interested in taking them.

**Comment by jspahrsummers** [comment]
We shouldn't need to release many betas. The current beta cycle is because we have some nondeterministic bugs to iron out, so wider-spread testing is more valuable.

Also, there's always `brew install --HEAD` to get whatever's on `master`.

**Comment by aschuch** [comment]
Oh, I was unaware of `brew install --HEAD`, thanks for the heads up.
