### ISSUE TITLE
Preserve debug symbols when building

### ISSUE THREAD

**Issue by sharplet** [Carthage/Carthage#507]
This was touched on in the discussion of https://github.com/Carthage/Carthage/issues/169.

It would be great if Carthage placed dSYM files in the `Carthage/Build/` directory after building. (Or anywhere where it's available to the project, really.)

**Comment by nomothetis** [comment]
I take it from this that it is currently not possible to get frameworks (specifically Swift frameworks) to have debug symbols?

**Comment by blender** [comment]
dSYMs are there just  they are not copied to known location with Carthage atm. If you are the owner of the framework you're trying to build with Cathage, It's possible work around this buy adding and extra step in your build phase and copy the dSYMs somewhere known where you can retrieve them. Example below. 

BASE_DIR=$SRCROOT/ios-base
mkdir -p $BASE_DIR
cp -R $DWARF_DSYM_FOLDER_PATH/* $BASE_DIR

**Comment by nomothetis** [comment]
Thank you! I will see how this all plays into what I'm trying to do, which is to archive an app that has dSYMs for both the app itself (working) and the frameworks declared in Carthage (not working).

**Comment by sharplet** [comment]
In case it helps anyone, I'll describe how I'm copying the Carthage dSYMs into the `BUILT_PRODUCTS_DIR` during my Embed Carthage Frameworks build phase (so I have access to the list of frameworks in the app via the script input files):

```
/usr/local/bin/carthage copy-frameworks
ruby bin/copy_carthage_dsyms.rb
```

And here's the script:

```ruby
# bin/copy_carthage_dsyms.rb

require "fileutils"

built_products_dir = ENV.fetch("BUILT_PRODUCTS_DIR") { fail "BUILT_PRODUCTS_DIR not set" }
input_file_count = ENV.fetch("SCRIPT_INPUT_FILE_COUNT") { fail "SCRIPT_INPUT_FILE_COUNT not set" }.to_i

dsym_files = input_file_count.times.lazy
  .map { |i|
    ENV.fetch("SCRIPT_INPUT_FILE_#{i}") { fail "SCRIPT_INPUT_FILE_#{i} not set" }
  }
  .map { |f| "#{f}.dSYM" }
  .select { |dsym| File.directory?(dsym) }

dsym_files.each do |dsym|
  FileUtils.cp_r(dsym, "#{built_products_dir}/")
end
```

I'm considering working on extending the `copy-frameworks` command to do this for you automatically, or adding a `copy-dsyms` command that you can use if you're not using `copy-frameworks`.
