### ISSUE TITLE
Add an `outdated` command

### ISSUE THREAD

**Issue by neilpa** [Carthage/Carthage#510]
Homebrew and cocoa pods both have an `outdated` command that is useful when considering what's available and what to update. It should probably split explicit vs transient dependencies and only show the latter in a `--verbose` scenario.

**Comment by neilpa** [comment]
It may also be useful to integrate this into `bootstrap`

**Comment by jspahrsummers** [comment]
:+1: Good idea.

**Comment by guidomb** [comment]
Is there any chance that #598 to be reviewed and maybe get merged for the next release?

**Comment by mdiep** [comment]
#598 is marked as a work-in-progress. It won't be reviewed until that designation is removed and @mattprowse signals that it's ready for review. :smile:

**Comment by guidomb** [comment]
@mdiep sorry my bad, didn't realize about the WIP.
