### ISSUE TITLE
Automatic rebuilding per-dependency

### ISSUE THREAD

**Issue by hamsterdam** [Carthage/Carthage#511]
Hey Justin,

Thanks for building and maintaining Carthage. Hooray for simplicity!

Is there any way to specify some, but not all, [dependencies for automatic rebuilding](https://github.com/Carthage/Carthage#automatically-rebuilding-dependencies)?

Aaron

**Comment by jspahrsummers** [comment]
See the previous discussion in https://github.com/Carthage/Carthage/issues/432.
