### ISSUE TITLE
Why Carthage compiles all the depenecies everytime I run carthage update?

### ISSUE THREAD

**Issue by guidomb** [Carthage/Carthage#513]
I would like to know if there is a particular reason on why carthage compiles all the dependencies every time the `carthage update` command is executed even though only a subset of thoese dependenies where updated. Could this be optimized to detect the dependecies that were updated and only compile those?

Thanks

**Comment by mdiep** [comment]
There was some previous discussion of this in #432 and #459.

**Comment by guidomb** [comment]
@mdiep Thanks I'll close this issue then.
