### ISSUE TITLE
Framework with private depenencies not builds correctly

### ISSUE THREAD

**Issue by tomassliz** [Carthage/Carthage#515]
I have framework project and this project is using Carthage for its dependencies (without submodules). They are listed in Cartfile.private.
When I try to use this framework in project (with submodules) where are dependencies managed by Carthage too, framework can't see its dependencies and can't import them. It looks like dependency for framework is not builded.

When i tried to build framework project directly (carthage update was called before), everything was ok.

**Comment by guidomb** [comment]
I think I am having a similar problem. I have a (framework)[http://github.com.Wolox/WLXBluetoothDevice] that builds fine when running `carthage build --no-skip-current`. But when I include this framework in another project It fails on the building step.

**Cartfile**
```
github "Wolox/WLXBluetoothDevice" "master"
``` 

What I don't understand is why it fails trying to build a test bundle. In my case the error is

```
/Users/guidomb/Documents/projects/guidomb/Carthage/Checkouts/WLXBluetoothDevice/WLXBluetoothDeviceTests/SpecHelper.h:16:9: fatal error: 'Specta/Specta.h' file not found
```

Appararently it cannot find the Specta files which makes sense because Specta is in `Cartfile.private` (because is a testing framework).

Should carthage build test bundle when installing dependencies? I think that that could be skipped because when you install a library dependency you don't care about the tests. You asume that you are using a stable version of the lib. Appart from that carthage does not run the tests so I don't see the point of building the tests bundle. Probably though this is a different conversation from the bug being reported here.

**Comment by ikesyo** [comment]
@tomassliz `Cartfile.private` is mainly used for testing dependencies, I think. If you need the dependencies for the parent project (which uses/depends on your framework), those should be listed in `Cartfile`, not a private one.

**Comment by guidomb** [comment]
@ikesyo Yeah but in my case is failing for the same reason and my `Cartfile.private` only has test frameworks

**Comment by guidomb** [comment]
If I create a `Cartfile.private` file in the parent project including the test frameworks everything works fine but I feel I should not need to do this. In this particular I don't want to include those testing frameworks. 

I think that Carthage should not build test bundle at all. Should I open a new issue for this?

**Comment by ikesyo** [comment]
@guidomb I checked your project, and the reason for your case seems that `buildForRunning = "YES"` was set for your test target. In the case, just building the framework target would also build the test target at the same time.

**Comment by tomassliz** [comment]
@ikesyo So if I use SWXMLHash only inside my framework I must add it in Cartfile? I don't want that my project can use SWXMLHash too...

**Comment by guidomb** [comment]
@ikesyo Ohh I didn't even know about that. Thanks for the tip!!! Gonna try that now.

**Comment by tomassliz** [comment]
@ikesyo And what if I wish to use one version of SWXMLHash in framework and different version in project? It's weird.

**Comment by guidomb** [comment]
@tomassliz I think you would probably have the same issue with Cocoapods. If you have different versions but they are compatible (using semantic version definitions of compatibility) you would be fine.

**Comment by guidomb** [comment]
@ikesyo Sorry if I am asking a dumb question but by `buildForRunning` do you mean this:

![screen shot 2015-06-02 at 10 39 17 pm](https://cloud.githubusercontent.com/assets/390645/7938489/555bafc8-0978-11e5-9af5-ac9a956a2086.png)

Because if I uncked that I cannot run my tests in XCode

**Comment by tomassliz** [comment]
@guidomb You must uncheck everything item for tests target, except `Test` checkbox. This helped me.

**Comment by guidomb** [comment]
Yes it actually worked and was having other config issues that is why the test were not running.

Thanks @ikesyo @tomassliz

**Comment by tomassliz** [comment]
When I had public dependency, I had to add this dependency to tests target too, otherwise framework was not build correctly under test. Maybe this would be helpful for someone.

**Comment by jspahrsummers** [comment]
> So if I use SWXMLHash only inside my framework I must add it in Cartfile? I don't want that my project can use SWXMLHash too...

@tomassliz If you use SWXMLHash inside your framework, the version _must_ be compatible with any version that the application decides to use. This is why it needs to be a public dependency—hiding the version information would permit two incompatible versions both being linked.
