### ISSUE TITLE
Carthage should not build dependencies' test targets

### ISSUE THREAD

**Issue by guidomb** [Carthage/Carthage#517]
I started this discussion in #515 but I think is better if I move it to its own issue. As far as I am concerned Carthage should not build test bundle when building depencies for project because it makes the build process slower and the result is not going to be used. 

As a side effect of building test bundles when installing dependencies if a dependency has depencies specified in the `Cartfile.private` like test frameworks the build fails. @ikesyo suggested setting `buildForRunning` to `NO` in the test target but that (I think) has the problem of not being able to run test from XCode (cmd + U) because the actual test bundle is not being compiled.

A possible hack would be to duplicate the Scheme make it not shared and then I would a shared scheme with the test target disabled for running and another not shared scheme with the test target enabled for running. But this does not sound like a good approach.

What do you guys think?

**Comment by robrix** [comment]
> @ikesyo suggested setting `buildForRunning` to `NO` in the test target

@ikesyo’s suggestion is correct. There’s no two ways about this—if the scheme is configured to make Xcode build the tests, Xcode is gonna build the tests.

> that (I think) has the problem of not being able to run test from XCode (cmd + U) because the actual test bundle is not being compiled.

That sounds like something else is going awry. I turn `buildForRunning` and `buildForArchiving` off for the test target every time and am still able to run the tests with ⌘U even from a clean build.

**Comment by guidomb** [comment]
Well after a while I realized that I was having other issues in the project config and that was actual cause of why the test bundle was not running. Sorry for the noise.

Maybe it would help to have this tip in the Carthage documentation for library authors. I know it has nothing to do with Carthage but I wasn't aware of such property and thought it was Carthage's fault.

Thanks for your help!
