### ISSUE TITLE
Bad version number for Carthage installed via Homebrew

### ISSUE THREAD

**Issue by tomassliz** [Carthage/Carthage#520]
I tried to install Carthage with Homebrew and this is the output:

```
$ brew install carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.7.3.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/carthage-0.7.3.yosemite.bottle.tar.gz
==> Pouring carthage-0.7.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/carthage/0.7.3: 124 files, 37M

$ carthage version
0.7.0
```

So maybe version command shows bad version number?

**Comment by mdiep** [comment]
You must have a `0.7.0` version of CarthageKit on your system. Since you're using homebrew, check if you have a copy of CarthageKit at `/Library/Frameworks/CarthageKit.framework`. If you do, delete that copy and you should be fine.

/cc #495

**Comment by tomassliz** [comment]
Thank you 👍
