### ISSUE TITLE
Document flag to always checkout code

### ISSUE THREAD

**Issue by gsimmons** [Carthage/Carthage#523]
In some situations, I would like the option to check out the repo, even if there's a pre-built binary.

**Comment by mdiep** [comment]
You can use `--no-use-binaries` if you don't want to use pre-built binaries.

**Comment by gsimmons** [comment]
Just what I want. So I suppose this should be a documentation bug? :)

**Comment by mdiep** [comment]
@gsimmons This does exist in `carthage help`. Where were you hoping to see it?

**Comment by gsimmons** [comment]
Apparently somewhere else? :) I guess I wasn't thinking like a CLI guy. Didn't think to do "carthage help update". I looked in the Documentation folder and googled around. Maybe something in the Readme about using the help on the command line for the less clueful like me?

**Comment by gsimmons** [comment]
Oh, and thanks for the quick responses and for a very cool and useful project.

**Comment by jspahrsummers** [comment]
I think I'd prefer to keep the canonical documentation about flags on the command line. Right now, that means `carthage help`, but in the future it may mean [a manpage](https://github.com/Carthage/Carthage/issues/498) as well.
