### ISSUE TITLE
Support invoke `carthage copy-frameworks` out of Xcode

### ISSUE THREAD

**Issue by cybertk** [Carthage/Carthage#527]
It worked well when call `carthage copy-frameworks` in Xcode **Run Script** of **Build Phases**. As `copy-frameworks` is a workaround for App Store submission bug, we do not need run this script except for App Store submission when in a CI process.

At this moment, when we call `carthage copy-frameworks` directly in CI, it will complained that `SCRIPT_INPUT_FILE_COUNT` and `SCRIPT_INPUT_FILE_X`s undefined.

It's better if `copy-frameworks` supports pass those info thru CLI args. such as

 ```
carthage copy-frameworks --scheme Scheme Carthage/Build/iOS/*.framework
```

**Comment by jspahrsummers** [comment]
It doesn't make sense to conditionally run `copy-frameworks`, since (as the name indicates) it is responsible for copying the frameworks into your app bundle.

You shouldn't chain a normal Copy Frameworks build phase with the Carthage script. One or the other should be used.
