### ISSUE TITLE
Caught signal triggered by the Swift runtime!

### ISSUE THREAD

**Issue by p709723778** [Carthage/Carthage#528]
Soto@SotodeMacBook-Pro ~/SwiftFrameWork (master*) $ carthage update
*** Fetching ReactiveCocoa
*** Fetching Alamofire
*** Fetching SwiftyJSON
*** Fetching Result
*** Fetching Box
*** Downloading Box at "1.2.2"
*** Checking out SwiftyJSON at "2.2.0"
*** Checking out Alamofire at "f3c50ae7b20e507f35dee337cfe656052880fbae"
*** Checking out Result at "0.4.3"
*** Checking out ReactiveCocoa at "12110113b02b22c7d3a1e7aa423d76340eb19157"
*** xcodebuild output can be found in /var/folders/jp/1fvpggz90m3dm9l0f56bhsy00000gp/T/carthage-xcodebuild.YQJjjs.log
*** Building scheme "Alamofire" in Alamofire.xcworkspace
2015-06-05 17:24:21.510 xcodebuild[60914:452996] XFunnyEditor Plugin loaded
2015-06-05 17:24:21:524 xcodebuild[60914:c0f] BBUncrustifyPlugin Version 2.1.1 loaded
2015-06-05 17:24:21.532 xcodebuild[60914:452996] +[MCLog load], env: (null)
2015-06-05 17:24:21.533 xcodebuild[60914:452996] +[MCLog pluginDidLoad:], NSBundle </Users/Soto/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MCLog.xcplugin> (loaded)
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:383:14: warning: parameters of 'URLSession(_:didBecomeInvalidWithError:)' have different optionality than expected by protocol 'NSURLSessionDelegate'
        func URLSession(session: NSURLSession!, didBecomeInvalidWithError error: NSError!) {
  @objc optional func URLSession(session: NSURLSession, didBecomeInvalidWithError error: NSError?)
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:387:14: warning: parameters of 'URLSession(_:didReceiveChallenge:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:395:14: warning: parameter of 'URLSessionDidFinishEventsForBackgroundURLSession' has different optionality than expected by protocol 'NSURLSessionDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:401:14: warning: parameters of 'URLSession(A shell task failed with exit code 65:
2015-06-05 17:24:21.510 xcodebuild[60914:452996] XFunnyEditor Plugin loaded
2015-06-05 17:24:21:524 xcodebuild[60914:c0f] BBUncrustifyPlugin Version 2.1.1 loaded
2015-06-05 17:24:21.532 xcodebuild[60914:452996] +[MCLog load], env: (null)
2015-06-05 17:24:21.533 xcodebuild[60914:452996] +[MCLog pluginDidLoad:], NSBundle </Users/Soto/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MCLog.xcplugin> (loaded)
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
Car
_:task:willPerformHTTPRedirection:newRequest:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:410:14: warning: parameters of 'URLSession(_:task:didReceiveChallenge:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:418:14: warning: parameters of 'URLSession(_:task:needNewBodyStream:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:424:14: warning: parameters of 'URLSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:430:14: warning: parameters of 'URLSession(_:task:didCompleteWithError:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
        func URLSession(session: NSURLSession!, task: NSURLSessionTask!, didCompleteWithError error: NSError!) {
  @objc optional func URLSession(session: NSURLSession, task: NSURLSessionTask, didCompleteWithError error: NSError?)
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:440:14: warning: parameters of 'URLSession(_:dataTask:didReceiveResponse:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionDataDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:450:14: warning: parameters of 'URLSession(_:dataTask:didBecomeDownloadTask:)' have different optionality than expected by protocol 'NSURLSessionDataDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:455:14: warning: parameters of 'URLSession(_:dataTask:didReceiveData:)' have different optionality than expected by protocol 'NSURLSessionDataDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:463:14: warning: parameters of 'URLSession(_:dataTask:willCacheResponse:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionDataDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:720:14: warning: parameters of 'URLSession(_:task:willPerformHTTPRedirection:newRequest:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:729:14: warning: parameters of 'URLSession(_:task:didReceiveChallenge:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:757:14: warning: parameters of 'URLSession(_:task:needNewBodyStream:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:766:14: warning: parameters of 'URLSession(_:task:didCompleteWithError:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
        func URLSession(session: NSURLSession!, task: NSURLSessionTask!, didCompleteWithError error: NSError!) {
  @objc optional func URLSession(session: NSURLSession, task: NSURLSessionTask, didCompleteWithError error: NSError?)
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:720:14: warning: parameters of 'URLSession(_:task:willPerformHTTPRedirection:newRequest:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:729:14: warning: parameters of 'URLSession(_:task:didReceiveChallenge:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:757:14: warning: parameters of 'URLSession(_:task:needNewBodyStream:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:766:14: warning: parameters of 'URLSession(_:task:didCompleteWithError:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
        func URLSession(session: NSURLSession!, task: NSURLSessionTask!, didCompleteWithError error: NSError!) {
  @objc optional func URLSession(session: NSURLSession, task: NSURLSessionTask, didCompleteWithError error: NSError?)
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:798:14: warning: parameters of 'URLSession(_:dataTask:didReceiveResponse:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionDataDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:810:14: warning: parameters of 'URLSession(_:dataTask:didBecomeDownloadTask:)' have different optionality than expected by protocol 'NSURLSessionDataDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:814:14: warning: parameters of 'URLSession(_:dataTask:didReceiveData:)' have different optionality than expected by protocol 'NSURLSessionDataDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:824:14: warning: parameters of 'URLSession(_:dataTask:willCacheResponse:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionDataDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:720:14: warning: parameters of 'URLSession(_:task:willPerformHTTPRedirection:newRequest:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:729:14: warning: parameters of 'URLSession(_:task:didReceiveChallenge:completionHandler:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:757:14: warning: parameters of 'URLSession(_:task:needNewBodyStream:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:766:14: warning: parameters of 'URLSession(_:task:didCompleteWithError:)' have different optionality than expected by protocol 'NSURLSessionTaskDelegate'
        func URLSession(session: NSURLSession!, task: NSURLSessionTask!, didCompleteWithError error: NSError!) {
  @objc optional func URLSession(session: NSURLSession, task: NSURLSessionTask, didCompleteWithError error: NSError?)
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1196:14: warning: parameters of 'URLSession(_:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:)' have different optionality than expected by protocol 'NSURLSessionDownloadDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1205:14: warning: parameters of 'URLSession(_:downloadTask:didResumeAtOffset:expectedTotalBytes:)' have different optionality than expected by protocol 'NSURLSessionDownloadDelegate'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:82:91: error: 'AnyObject' is not convertible to 'NSMutableURLRequest'; did you mean to use 'as!' to force downcast?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:156:16: error: 'CFString!' is not convertible to 'String'
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:190:16: error: value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:232:94: error: '[AnyObject]' is not convertible to '[String]'; did you mean to use 'as!' to force downcast?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:254:57: error: 'NSString' is not implicitly convertible to 'String'; did you mean to use 'as' to explicitly convert?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:639:24: error: missing argument for parameter 'serializer' in call
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:776:59: error: 'NSURLSessionTask' is not convertible to 'NSURLSessionDataTask'; did you mean to use 'as!' to force downcast?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1064:63: error: 'NSURLSessionTask' is not convertible to 'NSURLSessionUploadTask'; did you mean to use 'as!' to force downcast?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1101:63: error: 'NSURLResponse?' is not convertible to 'NSHTTPURLResponse'; did you mean to use 'as!' to force downcast?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1172:67: error: 'NSURLSessionTask' is not convertible to 'NSURLSessionDownloadTask'; did you mean to use 'as!' to force downcast?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1224:35: error: value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1245:62: error: value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1245:79: error: value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1245:120: error: value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1245:140: error: value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1258:58: error: value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?
/Users/Soto/SwiftFrameWork/Carthage/Checkouts/Alamofire/Source/Alamofire.swift:1294:32: error: value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?

Caught signal triggered by the Swift runtime!
Segmentation fault: 11

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.

[1]    60403 segmentation fault  carthage update

**Comment by neilpa** [comment]
This should be fixed by #519

**Comment by jspahrsummers** [comment]
I've tagged [0.7.4](https://github.com/Carthage/Carthage/releases/tag/0.7.4), which should fix all the hanging and crashing issues that we know about. The update should [become available in Homebrew](https://github.com/Homebrew/homebrew/pull/40450) soon.
