### ISSUE TITLE
Build error when I try to use Carthage to involve SwiftHTTP library

### ISSUE THREAD

**Issue by coolgeng** [Carthage/Carthage#534]
My Carthage file:

github "daltoniam/SwiftHTTP" "master"

When I run script:

carthage update

Error log:

*** Building scheme "SwiftHTTP" in SwiftHTTP.xcodeproj
*** Building scheme "SwiftHTTPOSX" in SwiftHTTP.xcodeproj
2015-06-08 15:56:52.513 xcodebuild[80469:7702550] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-06-08 15:56:52.514 xcodebuild[80469:7702550] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdjustFontSize.xcplugin' not present in DVTPlugInCompatibilityUUIDs
** BUILD FAILED **

The following build commands failed:
CompileSwift normal x86_64 /Users/application/myApplication/Carthage/Checkouts/SwiftHTTP/Tests/SwiftHTTPTests.swift
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

Does anybody have the same issue?

I also create a ticket under SwiftHTTP and Alcatraz project below :
https://github.com/daltoniam/SwiftHTTP/issues/115
https://github.com/supermarin/Alcatraz/issues/290

**Comment by jspahrsummers** [comment]
Please paste the error from the actual `xcodebuild` log.

**Comment by coolgeng** [comment]
Build settings from command line:
    SDKROOT = iphonesimulator8.3

=== BUILD TARGET Alamofire iOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/developer/Library/Developer/Xcode/DerivedData/Alamofire-eiievvoutopghncbnzclxgxftuea/Build/Intermediates/Alamofire.build/all-product-headers.yaml

=== BUILD TARGET Alamofire iOS Tests OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.3

=== BUILD TARGET Alamofire iOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/developer/Library/Developer/Xcode/DerivedData/Alamofire-eiievvoutopghncbnzclxgxftuea/Build/Intermediates/Alamofire.build/all-product-headers.yaml

=== BUILD TARGET Alamofire iOS Tests OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = macosx10.10

=== BUILD TARGET Alamofire OSX OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/developer/Library/Developer/Xcode/DerivedData/Alamofire-eiievvoutopghncbnzclxgxftuea/Build/Intermediates/Alamofire.build/all-product-headers.yaml

=== BUILD TARGET Alamofire OSX Tests OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphonesimulator8.3

=== BUILD TARGET Starscream OF PROJECT Starscream WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/developer/Library/Developer/Xcode/DerivedData/Starscream-agpvmfqipczwgbbvfysbkqlwoylg/Build/Intermediates/Starscream.build/all-product-headers.yaml

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.3

=== BUILD TARGET Starscream OF PROJECT Starscream WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/developer/Library/Developer/Xcode/DerivedData/Starscream-agpvmfqipczwgbbvfysbkqlwoylg/Build/Intermediates/Starscream.build/all-product-headers.yaml

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = macosx10.10

=== BUILD TARGET StarscreamOSX OF PROJECT Starscream WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/developer/Library/Developer/Xcode/DerivedData/Starscream-agpvmfqipczwgbbvfysbkqlwoylg/Build/Intermediates/Starscream.build/all-product-headers.yaml

=== BUILD TARGET StarscreamOSXTests OF PROJECT Starscream WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphonesimulator8.3

=== BUILD TARGET SwiftHTTP OF PROJECT SwiftHTTP WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/all-product-headers.yaml

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.3

=== BUILD TARGET SwiftHTTP OF PROJECT SwiftHTTP WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/all-product-headers.yaml

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = macosx10.10

=== BUILD TARGET SwiftHTTPOSX OF PROJECT SwiftHTTP WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/all-product-headers.yaml

=== BUILD TARGET SwiftHTTPOSXTests OF PROJECT SwiftHTTP WITH CONFIGURATION Release ===

Check dependencies

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    cd /Users/developer/Documents/myCompany/github/ios-app/iOS_App/Carthage/Checkouts/SwiftHTTP
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -target x86_64-apple-macosx10.10 -incremental -module-name SwiftHTTPOSXTests -O -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -g -module-cache-path /Users/developer/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -I /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Products/Release -F /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Products/Release -F /Applications/Xcode.app/Contents/Developer/Library/Frameworks -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -parse-as-library -c -j8 /Users/developer/Documents/myCompany/github/ios-app/iOS_App/Carthage/Checkouts/SwiftHTTP/Tests/SwiftHTTPTests.swift -output-file-map /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/Objects-normal/x86_64/SwiftHTTPOSXTests-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/Objects-normal/x86_64/SwiftHTTPOSXTests.swiftmodule -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/SwiftHTTPOSXTests-generated-files.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/SwiftHTTPOSXTests-own-target-headers.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/SwiftHTTPOSXTests-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/SwiftHTTPOSXTests-project-headers.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Products/Release/include -Xcc -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/DerivedSources/x86_64 -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/Objects-normal/x86_64/SwiftHTTPOSXTests-Swift.h -Xcc -working-directory/Users/developer/Documents/myCompany/github/ios-app/iOS_App/Carthage/Checkouts/SwiftHTTP -Xfrontend -serialize-debugging-options

CompileSwift normal x86_64 /Users/developer/Documents/myCompany/github/ios-app/iOS_App/Carthage/Checkouts/SwiftHTTP/Tests/SwiftHTTPTests.swift
    cd /Users/developer/Documents/myCompany/github/ios-app/iOS_App/Carthage/Checkouts/SwiftHTTP
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/developer/Documents/myCompany/github/ios-app/iOS_App/Carthage/Checkouts/SwiftHTTP/Tests/SwiftHTTPTests.swift -target x86_64-apple-macosx10.10 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -I /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Products/Release -F /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Products/Release -F /Applications/Xcode.app/Contents/Developer/Library/Frameworks -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -module-cache-path /Users/developer/Library/Developer/Xcode/DerivedData/ModuleCache -serialize-debugging-options -serialize-debugging-options -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/SwiftHTTPOSXTests-generated-files.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/SwiftHTTPOSXTests-own-target-headers.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/SwiftHTTPOSXTests-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/SwiftHTTPOSXTests-project-headers.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Products/Release/include -Xcc -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/DerivedSources/x86_64 -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/DerivedSources -Xcc -working-directory/Users/developer/Documents/myCompany/github/ios-app/iOS_App/Carthage/Checkouts/SwiftHTTP -emit-module-doc-path /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/Objects-normal/x86_64/SwiftHTTPTests~partial.swiftdoc -O -parse-as-library -module-name SwiftHTTPOSXTests -emit-module-path /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/Objects-normal/x86_64/SwiftHTTPTests~partial.swiftmodule -serialize-diagnostics-path /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/Objects-normal/x86_64/SwiftHTTPTests.dia -emit-dependencies-path /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/Objects-normal/x86_64/SwiftHTTPTests.d -emit-reference-dependencies-path /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/Objects-normal/x86_64/SwiftHTTPTests.swiftdeps -o /Users/developer/Library/Developer/Xcode/DerivedData/SwiftHTTP-aegnnbtkqrltqafvyonjysxqwwor/Build/Intermediates/SwiftHTTP.build/Release/SwiftHTTPOSXTests.build/Objects-normal/x86_64/SwiftHTTPTests.o
/Users/developer/Documents/myCompany/github/ios-app/iOS_App/Carthage/Checkouts/SwiftHTTP/Tests/SwiftHTTPTests.swift:10:8: error: no such module 'UIKit'
import UIKit
       ^

**Comment by neilpa** [comment]
You're trying to include `UIKit` while build for OSX. That import should be a conditional include.

**Comment by coolgeng** [comment]
@neilpa How to fix this? Like the article mentioned. I need import it in the source code, right? http://stackoverflow.com/questions/24664649/conditional-compiling-of-objective-c-in-a-swift-project

**Comment by neilpa** [comment]
http://stackoverflow.com/a/24003457/1999152

**Comment by coolgeng** [comment]
I already send a PR for SwiftHTTP to remove unused UIKit from test case. I will close this issue once PR accepted. I appreciate for your help. Thanks.
