### ISSUE TITLE
Can `carthage update` only builds updated deps

### ISSUE THREAD

**Issue by cybertk** [Carthage/Carthage#537]
When I add a new dep into **Cartfile**,  I will invoke `carthage update` to build the new dep. Actually, `carthage update` will checkouts and rebuild all existing deps. It's time-consuming and will change all compiled frameworks build previously.

Is there a way to update only changed parts in **Cartfile**, maybe `carthage update --change-only`

**Comment by jspahrsummers** [comment]
See https://github.com/Carthage/Carthage/issues/432.
