### ISSUE TITLE
Github API rate limit

### ISSUE THREAD

**Issue by olarivain** [Carthage/Carthage#540]
I feel like I missed something, but I've been over the doc a few times and can't seem to find the answer.

I've been playing with carthage a bit in the last couple of days, with a rapid try/fail/fix cycle, e.g. running carthage update a lot, and ended up being rate limited by github.com.
Now my bots are also rate limited (we can push quite a bit), which is somewhat annoying. The error message mentions being authenticated offers a bigger rate limit, but I couldn't figure out how to provide credentials?
Seems like I should be using git-credentials, been playing with that but couldn't get it to work. Is there any doc/hints on this somewhere?

**Comment by mdiep** [comment]
Carthage does use the builtin git credential system. You may need to set a credential helper. But if you can pull from a private GitHub repo without reentering your credentials, then Carthage should use the authenticated API.

**Comment by olarivain** [comment]
yeah, indeed.
In case somebody runs into the same issue I did:
git credential-osxkeychain get
press enter, always allow git credentials to use the keychain

then
git credential-osxkeychain store
host=github.com
protocol=https
username=user
password=password
press enter

try and git clone a private https repo should "just work".

it's a wee bit more complicated for Bots users, as the _xcsbuildd bots run as doesn't have a shell. Will try a couple of different approaches and report back.

**Comment by olarivain** [comment]
eventually moved to --use-ssh.
Anyway, closing, since it's not really an issue.
