### ISSUE TITLE
Add flag to Cartfile to indicate if lib can be used on non-Apple platforms. 

### ISSUE THREAD

**Issue by stevemoser** [Carthage/Carthage#542]
i.e. It only uses the standard library. 

This might be a bit early but with Swift coming to non-Apple platforms it would be useful to know some how if a dependency and its dependences only used the Standard Library.

**Comment by stevemoser** [comment]
Of course this all assumes that Carthage will grow into something that supports non-Xcode non-Cocoa projects. Or maybe a new Swift only dependency manager needs to be created since this is probably outside the scope of this project.

**Comment by neilpa** [comment]
Seems extremely given the dependency xcodebuild. Don't expect xcode on other platforms anytime soon.

**Comment by robrix** [comment]
Yes, this would require a non-Xcode build tool which does not exist yet and which we can’t write or plan for.
