### ISSUE TITLE
GitHub API request failed: API rate limit exceeded

### ISSUE THREAD

**Issue by evgenyneu** [Carthage/Carthage#545]
Hi, I get this error when running `carthage update` with `--use-ssh` flag. It does work without this flag but I can not use my private repositories this way. Carthage version: 0.7.4.

```
$ carthage update --use-ssh

*** Fetching Dodo
*** Fetching BrightFutures
*** Fetching Result
*** Fetching Box
GitHub API request failed: API rate limit exceeded for  (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

**Comment by jspahrsummers** [comment]
This [shouldn’t be an error](https://github.com/Carthage/Carthage/issues/465), but [setting up a credential cache](https://help.github.com/articles/caching-your-github-password-in-git/) in the meantime should work around it.

**Comment by evgenyneu** [comment]
Reached the Github API limit today on `carthage update` command (without --use-ssh flag). With many lines in Cartfile it is becoming an issue for us.

**Comment by jspahrsummers** [comment]
If the errors are still an issue after setting up a credential cache, you can add the `--no-use-binaries` flag, which will disable the only GitHub API calls in use by Carthage.

**Comment by maelp** [comment]
Note for some users who might have troubles: after setting the credential cache, you seem to have to pull a private repo on HTTPS (not ssh) so it prompts for the keys. I had to use `mitmproxy` to understand what happened, it would be great at least to have human error messages :)

**Comment by NxSoftware** [comment]
I'm hitting this issue when running `carthage bootstrap` or `carthage update` on Azure Pipelines, even when passing an access token via the `GITHUB_ACCESS_TOKEN` environment variable. Using `--no-use-binaries` is not really an option because some of our dependencies are very large and take a significant amount of time to build from source. `--use-ssh` also seems to have no effect on the behaviour.

Is anyone successfully using Carthage in a hosted CI environment?

**Comment by ThePragmaticArt** [comment]
> I'm hitting this issue when running `carthage bootstrap` or `carthage update` on Azure Pipelines, even when passing an access token via the `GITHUB_ACCESS_TOKEN` environment variable. Using `--no-use-binaries` is not really an option because some of our dependencies are very large and take a significant amount of time to build from source. `--use-ssh` also seems to have no effect on the behaviour.
> 
> Is anyone successfully using Carthage in a hosted CI environment?

I have similar issues here.

**Comment by thisisthekap** [comment]
I had the same issue with azure pipelines. I ended up adding the xcframework folder to the git repository. Not ideal, but working.
