### ISSUE TITLE
Code-signing Issue with Subcomponent

### ISSUE THREAD

**Issue by jeffreybergier** [Carthage/Carthage#546]
Hi,

I didn't previously have a Mac Developer certificate. I paid the $100 for the iOS one long ago but didn't see the need for the Mac one since I was just playing around with Mac Programming. Now that Apple is giving all paid members certificates for both platforms, I used Xcode 7 to grab the various developer certificates for the Mac. After grabbing them in Xcode 7, Xcode 6 can use the certificates and sign apps with them.

I'm currently building an app that builds on top of CarthageKit. Now that I'm telling Xcode to sign my app, I am getting an error that says a submodule is not signed at all inside CarthageKit. Its the argo submodule. The full error is pasted below:

```
CodeSign /Users/jeffberg/Library/Developer/Xcode/DerivedData/Cartwheel-ccadlvekthbkhmgrrvonizcoqfnp/Build/Products/Debug/Cartwheel.app/Contents/Frameworks/CarthageKit.framework/Versions/A
    cd /Users/jeffberg/Documents/SaturdayApps/Cartwheel/Cartwheel
    export CODESIGN_ALLOCATE=/Applications/Xcode-6.4-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "Mac Developer: Jeffrey Bergier (V78MM83472)"

    /usr/bin/codesign --force --sign EAE69B21A5DC4B4D165FE4A3B4DFE3E9910C95C9 --preserve-metadata=identifier,entitlements,resource-rules /Users/jeffberg/Library/Developer/Xcode/DerivedData/Cartwheel-ccadlvekthbkhmgrrvonizcoqfnp/Build/Products/Debug/Cartwheel.app/Contents/Frameworks/CarthageKit.framework/Versions/A

Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
/Users/jeffberg/Library/Developer/Xcode/DerivedData/Cartwheel-ccadlvekthbkhmgrrvonizcoqfnp/Build/Products/Debug/Cartwheel.app/Contents/Frameworks/CarthageKit.framework/Versions/A: code object is not signed at all
In subcomponent: /Users/jeffberg/Library/Developer/Xcode/DerivedData/Cartwheel-ccadlvekthbkhmgrrvonizcoqfnp/Build/Products/Debug/Cartwheel.app/Contents/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Argo.framework
Command /usr/bin/codesign failed with exit code 1
```

I tried all of the suggestions in Issue #373 but nothing is working. I know you're busy and this is an open source project, so I really appreciate any help you can offer.

Thanks!
-Jeff

**Comment by jspahrsummers** [comment]
How did you obtain and/or build this copy of `CarthageKit.framework`? `Versions/A` should be a folder, not a file, so I'm not sure how it _could_ even get signed.

**Comment by jeffreybergier** [comment]
I just performed "carthage bootstrap" and/or "carthage update"

My cartfile is here: https://github.com/jeffreybergier/Cartwheel/blob/dev/Cartwheel/cartfile
Cartfile.resolved is here: https://github.com/jeffreybergier/Cartwheel/blob/dev/Cartwheel/Cartfile.resolved

**Comment by jeffreybergier** [comment]
Oh and my version number for carthage command line utility is 0.6.5. I see that your now at 0.7.4. I'll try to upgrade the command line utility and do a carthage bootstrap to see if that changes anything.

**Comment by jeffreybergier** [comment]
I updated carthage command line utility. Deleted Derived Data, and the Carthage folder and Cartfile.resolved in my repo and ran carthage boot strap. It downloaded everything fine and compiled everything. However, the app was crashing until I added Commandant and PrettyColors (listed in your cartfile.private) to my Cartfile. After it built everything the app runs and opens when there is no code signing. However, when I ask it to sign, I see the same error as in the Original Post.

**Comment by jspahrsummers** [comment]
I'm not sure what the issue might be. The only thing I can suggest is looking at `Carthage.xcworkspace` and trying to match the build settings/phases of the main Carthage application target. :confused:

**Comment by jeffreybergier** [comment]
Hey Justin, I know you're probably super busy with Swift 2.0 stuff. However, I did have some time to play around. I started fresh so I could really test things.

1. I created a brand new Xcode Mac Project.
1. I verified I can sign the app as a developer ID or mac app store ID with my certs and run it just fine.
1. I put the same cartfile in it as I did before (shown below)
    ``` 
    github "smileyborg/PureLayout" ~> 2.0.0
    github "Carthage/Carthage" ~> 1.0.0
    github "DaveWoodCom/XCGLogger" ~> 2.0.0

    ## Private frameworks that need to be built for CarthageKit to work
    github "Carthage/Commandant" ~> 0.6
    github "jdhealy/PrettyColors" ~> 2.0 
    ```
1. I performed carthage bootstrap. Everything built fine
1. I added all the frameworks into the project file but not into the target.
1. Then I added them one by one, building and running at each step and it always worked and every framework was able to be signed with no issues.
1. Until I added CarthageKit. Then the signing would fail
1. As a troubleshooting step, I also downloaded the CarthageKit framework from the releases tab in Github and got the same error.
1. Lastly, I opened the Carthage workspace from the checkouts folder, changed the carthagekit target to be signed with my cert and then built it.
1. After building it from the workspace, I replaced the framework that the carthage command line built for me with the Xcode built one that was signed and now my Mac app signs and works just fine.

So I'm not sure exactly what is going on, but there seems be something wrong with CarthageKit that when its not signed, it can't be signed when placed into another app. I found my workaround for now. I wish i knew more about signing so I can fix it and give a pull request :(

You can see this fresh project here: http://jeffburg.com/skitch/CarthageKitSignatureTest.zip
To test it, just configure the target to use your team certificate, then try to build. It will fail. Then clean the build folder and remove CarthageKit from the Embedded Binaries section and then build and run and it will work just fine.

Thanks for your hard work on carthage and helping with n00bs like me. I love the project.

**Comment by jeffreybergier** [comment]
Hey Justin,

I spent some time playing with the repo today to try and fix this signing issue. I forked the repo into my account. Then I cloned it and basically tried to make it work like a project that uses carthage for its dependencies. I removed all the git submodules and told the .gitignore file to ignore the carthage checkouts. I also removed the XCWorkspace because without the submodules, only the xcproject is needed. Now when I tell my own app to use my forked repo of carthage, it works properly and my app can sign the carthagekit framework.

You can checkout the changes here: https://github.com/jeffreybergier/Carthage-TryingToFixSigningIssue/commit/c9656ff4cb3b642071e0ef91195f769230843935

I changed so much I doubt you want to accept a pull request :-/. I think I'll just try to manually integrate all the changes you make into in the future into my fork. I'm not sure what else to do.

**Comment by ikesyo** [comment]
I examined the project structure, and really `CarthageKit` have dependencies of `Commandant` and `PrettyColors`. Those dependencies should be in `carthage` app target. I will open a pull request to address the issue.
