### ISSUE TITLE
[Question] Why name `Carthage`?

### ISSUE THREAD

**Issue by dhilipsiva** [Carthage/Carthage#549]
May be it is obvious. May be it is not because I am from a different culture. But why name the repo `Carthage`? I googled and found that the city fell for roman empire. But nothing more than that. Was it just a random name? Or is there a connection? Can anyone explain?

Sorry to create an Issue. Didn't know where else to ask!

**Comment by robrix** [comment]
I suggested “Carthage,” because it’s vaguely like “package” with some consonants swapped out.

When we released people thought it might be a reference to “carthago delenda est” (approximately, “Carthage must be destroyed”) which is a much, much better story so let’s go with that one.

**Comment by dhilipsiva** [comment]
:+1:
