### ISSUE TITLE
carthage can't detect the change of scheme in xcproject

### ISSUE THREAD

**Issue by IamAlchemist** [Carthage/Carthage#553]
Recently, I need to use SDWebImage. But at it latest tag 3.7.2, the project didn't mark its schema "shared". So carthage omit building of it. 
So I just `carthage checkout` the project, then change the schema to "shared" locally with xcode, then `carthage build`.
The problem is, I manually open the SDWebImage project locally, and manually marked its schema "shared", but carthage still can't find the scheme...

how to solve this problem?

**Comment by mdiep** [comment]
To solve this, you should open a PR against SDWebImage that shares the scheme. :smile:

**Comment by jspahrsummers** [comment]
You can also create a fork and use that.

Note that Carthage also requires a _dynamic framework_ target. Any other targets are ignored.

**Comment by IamAlchemist** [comment]
Thank you a looooooot
