### ISSUE TITLE
Support local project directories in Cartfile

### ISSUE THREAD

**Issue by abbeycode** [Carthage/Carthage#557]
It would be helpful to be able to point to an absolute or relative file path in a `Cartfile`, which could help with local builds and automated test builds

**Comment by neilpa** [comment]
You can use a raw `git` origin for this

```
git "~/path/to/repo" "some-branch"
```

**Comment by abbeycode** [comment]
Great, thanks!

**Comment by abbeycode** [comment]
What about relative paths? I can't seem to get it to work right. For example:

    git  ".." "branch-name"

This would be nice to have for my Travis script to be able to verify that Carthage builds aren't broken. I have a demo project with a `Cartfile` inside the main project's repo.

**Comment by neilpa** [comment]
You could try `git "./.." "branch-name"`. But if that doesn't work there's nothing carthage can do here since it just shells out to git.

**Comment by abbeycode** [comment]
It didn't work - I'm going to have to use a Travis environment variable and dynamically create the Cartfile as part of the build.

**Comment by ekurutepe** [comment]
@abbeycode did you have any success with your approach. If yes please consider looking at https://github.com/facebook/AsyncDisplayKit/pull/1262

**Comment by abbeycode** [comment]
You can see the approach I ended up taking here: https://github.com/abbeycode/UnzipKit/blob/master/Scripts/carthage-validate.sh

Basically, I generate the cart file dynamically like so:

``` bash
echo "git \"$TRAVIS_BUILD_DIR\" \"$TRAVIS_BRANCH\"" > Cartfile
```

**Comment by ekurutepe** [comment]
@abbeycode :100:

**Comment by baarde** [comment]
Imho, relative Git URLs should not be resolved relative to the current directory but relative to the current origin. This would be consistent with the way relative URLs are handled in [Git submodules](https://git-scm.com/docs/git-submodule).

I can see two benefits :
* When most of (all) your dependencies are stored on the same Git server, the Cartfile looks nicer.
* GitLab CI now supports submodules. However that requires to use relative URLs. ([Documentation](https://docs.gitlab.com/ce/user/project/new_ci_build_permissions_model.html#git-submodules))
