### ISSUE TITLE
Can't get iOS build of framework

### ISSUE THREAD

**Issue by abbeycode** [Carthage/Carthage#559]
I'm trying to get my framework to work with Carthage. It's a cross-platform (Mac+iOS) framework, which has previously used CocoaPods. The only framework target had been OS X specific, but I added the iOS platforms and architectures to it. If you use the line below in your `Cartfile`, inside an iOS project, it still only produces a Mac build. I also tried calling `carthage update --platform iOS` and that didn't have any effect.

    git  "https://github.com/abbeycode/UnzipKit.git" "carthage"

What am I doing wrong?

**Comment by mdiep** [comment]
Has the scheme been shared from the `xcodeproj` for the iOS framework target?

**Comment by abbeycode** [comment]
There isn't a separate target - there's a shared target that supports both platforms.

**Comment by mdiep** [comment]
Ah, Carthage doesn't currently support universal framework targets (#340).
