### ISSUE TITLE
0.7.5 Request

### ISSUE THREAD

**Issue by soffes** [Carthage/Carthage#563]
Can we get a 0.7.5 release? It would be great to get the watchOS stuff. I've been working from c53ac721b10e1c40202d5638ebef4ee7549a7948 without issue.

**Comment by jspahrsummers** [comment]
[Release](https://github.com/Carthage/Carthage/releases/tag/0.7.5) created, and [submitted to Homebrew](https://github.com/Homebrew/homebrew/pull/40844).

Travis should be uploading the build artifacts shortly.

**Comment by soffes** [comment]
Thanks Justin! <3
