### ISSUE TITLE
Carthage not building

### ISSUE THREAD

**Issue by abbeycode** [Carthage/Carthage#564]
I cloned the repo, ran a `carthage update`, and then opened the workspace. The Commandant, Quick, Argo, Runes, and Box projects all show up red. I see the frameworks built in the `Carthage/Build/Mac` directory, but I don't see the projects anywhere in `Carthage/Checkouts`, nor do I see any but Argo in the `Cartfile`. It looks like the rest must be upstream dependencies, but I'm not sure what's going on. I installed the 0.7.4 release ("Time Desk").

What am I missing? I'm trying to get a pull request started.

**Comment by neilpa** [comment]
You should be running `bootstrap` not `update` when setting up a repo unless you're explicitly updating the dependencies. In this case you also need to specify `--no-use-binaries` to ensure all the workspace dependencies get checked out. Otherwise carthage will default to the binary framework releases.

**Comment by abbeycode** [comment]
Thanks, I reset the repo, then ran `carthage bootstrap` now, and then I got a build error when building Nimble:

> Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'

Should the `CONTRIBUTING.md` file have instructions for first-time setup, including using the `bootstrap` command?

**Comment by neilpa** [comment]
> Should the CONTRIBUTING.md file have instructions for first-time setup, including using the bootstrap command?

Probably not because that's how it works when cloning any project that uses carthage to manage it's dependencies, including carthage itself. This is already covered in the README.

**Comment by neilpa** [comment]
As for the codesigning error, you can specify `--platform mac` when bootstrapping since you don't need to build for ios.

**Comment by abbeycode** [comment]
Okay, thanks, I'm still getting up to speed with it all. Now, having run `carthage bootstrap --platform mac`, I've still got 5 red projects. I did find their source - they're a few levels deep inside the `carthage` directory

**Comment by abbeycode** [comment]
Actually, looking more closely, I see (e.g. for Commandant) a framework in `Carthage/Build/Mac`, but I don't see any source checkout for it. When I do a Finder search for "Commandant", all I see are a couple of headers in the framework, and the `Cartfile.private` and `Cartfile.resolved` files.

**Comment by mdiep** [comment]
Commandant uses binaries releases. So a pre-built copy of the framework is downloaded directly from GitHub.

**Comment by abbeycode** [comment]
Right, but I'm trying to open the Carthage workspace, which refers to Commandant, and 4 other `xcodeproj` files that don't seem to be downloaded after I bootstrap.

**Comment by mdiep** [comment]
If you use the `--no-use-binaries` flag, then Carthage will download and checkout the source.

**Comment by abbeycode** [comment]
Ah ok, that did it. May I submit a pull request to add that full command to the CONTRIBUTING.md file?

    carthage bootstrap --platform mac --no-use-binaries

**Comment by mdiep** [comment]
That would be great. :smile:

**Comment by abbeycode** [comment]
@mdiep I submitted a pull request for that
