### ISSUE TITLE
why SwiftyJSON is not building

### ISSUE THREAD

**Issue by ch-hui** [Carthage/Carthage#566]
i wanna use Carthage to Integrate SwiftyJSON,but when i executed the carthage update command there is no .framework file in the Build catalog.somebody who knows how to fix it?

**Comment by ikesyo** [comment]
This seems a duplicate of #532.

**Comment by ikesyo** [comment]
[0.8](https://github.com/Carthage/Carthage/releases/tag/0.8) is released, it should fix the issue.
