### ISSUE TITLE
No way to avoid code signing?

### ISSUE THREAD

**Issue by abbeycode** [Carthage/Carthage#576]
I'm trying to validate my project's Carthage compatibility with a script on Travis, and I can't get it to succeed there or locally for iOS. With the default code signing ("iOS Developer"), it complains:

> Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
> CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'

When I set it to "Don't Code Sign", then I just get the second "code signing is required" error. Is there any way around this? This is the way I'm calling Carthage:

    carthage bootstrap --configuration Debug --verbose

The project is [UnzipKit](https://github.com/abbeycode/UnzipKit), with Carthage output [on Travis here](https://travis-ci.org/abbeycode/UnzipKit/jobs/67438706#L1109). It looks like this is related to issue #281, but comments are closed on that one with no update.

**Comment by mdiep** [comment]
I believe this is an Xcode limitation that Carthage can't anything about.

**Comment by abbeycode** [comment]
The problem is that Carthage forces building for the device in addition to building for the simulator. For some purposes, though, the simulator is enough. Not specifying a signing identity could be taken as a signal that no device build is required. As long as a warning is logged, that shouldn't be a problem, right?

**Comment by abbeycode** [comment]
@mdiep @jspahrsummers Any thoughts?

**Comment by robrix** [comment]
@abbeycode As we’re all pretty busy with our day-jobs and Carthage is a spare time thing, it can take a little while for us to get around to responding. It’s not a sign of disinterest, just that time are short and obligations are many. I promise they’ll get to this issue when they have a chance :smile:

**Comment by abbeycode** [comment]
@robrix Of course, apologies

**Comment by jspahrsummers** [comment]
@abbeycode See #235 and specifically my conclusions in https://github.com/Carthage/Carthage/issues/235#issuecomment-68114529.

**Comment by abbeycode** [comment]
Is it a lot of effort to support simulator-only builds, though? Point me in the right direction and I can submit a pull request. It's worth it to me, because otherwise my CI setup won't be able to tell me if my iOS build using Carthage is broken.

**Comment by abbeycode** [comment]
I think I've got a solution, and I'm working on testing it now. I basically added an associated value to the `iOS` and `watchOS` enum values for `Platform` and `BuildPlatform`. When true, it strips out the device SDKs from the list of SDKs it provides. It's set to `true` via a `--simulator-only` flag, or if the `--platform` value is `iphonesimulator` or `watchsimulator`. The latter two values were already supported, and just became the same as `iOS` or `watchOS`. They now will have semantic meaning.

**Comment by abbeycode** [comment]
I updated that pull request so it detects whether the build machine has any iOS identities installed, and skips the device builds when none are found.
