### ISSUE TITLE
Developer ID sign releases

### ISSUE THREAD

**Issue by soffes** [Carthage/Carthage#577]
It would be awesome if releases were signed :heart:

![screen shot 2015-06-22 at 1 48 15 am](https://cloud.githubusercontent.com/assets/52870/8278512/cf42d1d8-1880-11e5-8baa-10ac8824205f.png)

**Comment by jspahrsummers** [comment]
You already opened this issue: https://github.com/Carthage/Carthage/issues/142

**Comment by soffes** [comment]
Oh ya. Sorry.

I still really wish this was a thing.
