### ISSUE TITLE
Resolving to an invalid version

### ISSUE THREAD

**Issue by dpettigrew** [Carthage/Carthage#578]
My Cartfile is this

github "TheHolyGrail/Shrubbery" ~> 0.0.3
github "TheHolyGrail/Zoot" ~> 0.0.4

It was resolving Shubbery as `Checking out Shrubbery at “v0.0.4" for Shrubbery` but the highest version of Shrubbery is v0.0.3.

**Comment by neilpa** [comment]
I just tried the same cartfile and see the expected output

```
❯ cat Cartfile
github "TheHolyGrail/Shrubbery" ~> 0.0.3
github "TheHolyGrail/Zoot" ~> 0.0.4

❯ carthage update --no-build
*** Cloning Zoot
*** Cloning Shrubbery
*** Cloning BridgeOfDeath
*** Cloning Excalibur
*** Checking out Excalibur at "v0.0.2"
*** Checking out Shrubbery at "v0.0.3"
*** Checking out BridgeOfDeath at "v0.0.2"
*** Checking out Zoot at "v0.0.4"
```

**Comment by mdiep** [comment]
@dpettigrew What's the output of `carthage version`?

**Comment by dpettigrew** [comment]
0.7.3

**Comment by ikesyo** [comment]
Closing this for now. Feel free to reopen if you have any updates or further information!
