### ISSUE TITLE
Distributing IBDesignable views with Carthage

### ISSUE THREAD

**Issue by evgenyneu** [Carthage/Carthage#579]
Hi, is there a way to distribute a custom IBDesignable / IBInspectable UIView control in a framework with Carthage?

Here is a demo framework:

https://github.com/exchangegroup/MyCustomView

It has a [designable `MyCustomView`](https://github.com/exchangegroup/MyCustomView/blob/master/MyCustomView/MyCustomView.swift) with an inspectable property `myBorderWidth`.

![custom_class](https://cloud.githubusercontent.com/assets/880411/8298809/687c06cc-19b1-11e5-8dd1-585237aa39a3.png)

The designable view shows in the storyboard of the the framework project.

![inspectable_works](https://cloud.githubusercontent.com/assets/880411/8298803/5e4e9c00-19b1-11e5-8daa-aadbd3459917.png)

But, if I include this framework in another app with Carthage, the storyboard does not allow to design the `MyCustomView`.

Here is a demo app that [uses it with Carthage](https://github.com/exchangegroup/UsingMyCustomView/blob/master/Cartfile):

https://github.com/exchangegroup/UsingMyCustomView

![inspectable_does_not_work](https://cloud.githubusercontent.com/assets/880411/8298832/bc8e5382-19b1-11e5-8059-6a9fc9161135.png)

Is there a way to way to distribute designable UIView with carthage?

Tested  in Xcode 6.4 and Xcode 7.

Carthage: 0.6.4

**Comment by jspahrsummers** [comment]
See https://github.com/Carthage/Carthage/issues/335.
