### ISSUE TITLE
How do I use my local build of Carthage?

### ISSUE THREAD

**Issue by abbeycode** [Carthage/Carthage#581]
I'm working on creating a pull request, and I'd like to use my local build of carthage with a Cartfile for another project. What's the easiest way to do this? I'll add the answer to the CONTRIBUTING.MD file

**Comment by ikesyo** [comment]
It's just `$ make install` in your Carthage repository.

**Comment by abbeycode** [comment]
Thanks, and then to go back, just run `brew install carthage` again?

**Comment by ikesyo** [comment]
In that case, you should run `sudo make uninstall` at first, I think.

**Comment by abbeycode** [comment]
Great, that all worked. What's the easiest way to run through the debugger?
