### ISSUE TITLE
"make install" failing with Result compilation error

### ISSUE THREAD

**Issue by abbeycode** [Carthage/Carthage#582]
I'm trying to build Carthage's `master` branch. It's building fine in Xcode, plus a few changes, which compile in Xcode. I'm getting the following when I `make install`:

```
$ ./script/bootstrap
...
$ make install
...

 ** INSTALL FAILED **


The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal x86_64 /Users/Dov/Source Code/Carthage/Carthage/Checkouts/Result/Result/Result.swift
(2 failures)
make: *** [installables] Error 65
```

Am I doing something wrong? I'm using Xcode 6.3.2, and that's my current version of the command line tools also.

**Comment by ikesyo** [comment]
The thread/answer might be related to that issue: https://github.com/Carthage/Carthage/issues/424#issuecomment-99551625

**Comment by abbeycode** [comment]
Thanks, but it actually turns out it was because I had my iOS simulator running. After quitting Xcode and the simulator, it ran successfully.
