### ISSUE TITLE
Missing build with zipzap

### ISSUE THREAD

**Issue by pixelglow** [Carthage/Carthage#585]
I'm trying to get my framework [zipzap](https://github.com/pixelglow/zipzap) working with Carthage (see pixelglow/zipzap#100), but while the repository downloads correctly, nothing gets built. I'm pretty sure it's because zipzap doesn't produce dynamic libraries, but I have no way of checking this. So a couple of questions:

* Does the current zipzap not build because of the lack of dynamic libraries? I don't see any error messages with `carthage build --verbose --no-skip-current` or in the `xcodebuild` log which is empty.
* Can I dump out what Carthage determines to be the `xcodebuild` command line it would use?
* Can I point this at some non-master or non-public github source, or even at my local git? (I'm loathe to make a lot of speculative commits to a public repo.)
* How does it determine which target + scheme to build? This is the dump from `xcodebuild -list`:

```
Information about project "zipzap":
    Targets:
        zipzap (OS X)
        zipzap (iOS)
        zipzapTests

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        zipzap (iOS)
        zipzap (OS X)
```

**Comment by mdiep** [comment]
Yes, Carthage only supports dynamic frameworks. It looks through the targets for any that create dynamic frameworks.

You can specify a branch or non-github source in your `Cartfile` as described [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md).

**Comment by remaerd** [comment]
You need to mark your dynamic frameworks targets as 'Shared'. Than you need to create a tag for the commit. If you are testing it. You should try this

```
git "https://github.com/pixelglow/zipzap" "master"
```

It should work.

**Comment by pixelglow** [comment]
No worries, managed to figure most of it out.
