### ISSUE TITLE
OAStackView Carthage Support

### ISSUE THREAD

**Issue by calebd** [Carthage/Carthage#586]
I'm trying to add a framework target (and Carthage support) to [oarrabi/OAStackView](https://github.com/oarrabi/OAStackView). It is using the `pod lib create` project structure which makes things difficult.

I followed the [TTTAttributedLabel](https://github.com/TTTAttributedLabel/TTTAttributedLabel) setup by adding a new project in a `Carthage` folder. You can see the modifications at [calebd/OAStackView](https://github.com/calebd/OAStackView).

There is exactly one shared framework scheme in all of the Xcode projects, but Carthage fails to discover the correct scheme. I get the following error if I run `carthage build --no-skip-current` at the root of my OAStackView fork:

```
A shell task failed with exit code 65:
xcodebuild: error: The workspace 'OAStackView' does not contain a scheme named 'OAStackView'.
```

Likewise, adding `github "calebd/OAStackView" "master"` to my `Cartfile` and running `carthage update` shows the same error.

**Comment by mdiep** [comment]
The CocoaPods template doesn't really work with anything except CocoaPods. But I think those folks were trying to find something that works with Carthage (#476).

**Comment by calebd** [comment]
It works fine for TTTAttributedLabel though with the exact same project configurations. Why is this different?

**Comment by calebd** [comment]
Carthage just needs to discover all shared scheme targets and find the first framework one. Which is what I thought it already did. It gets tripped up on the `xcworkspace` in `Example` when it should not.

**Comment by mdiep** [comment]
If you move `OAStackView.xcodeproj` to the top level, then things should work.

**Comment by ikesyo** [comment]
@calebd I tried building with your fork and Carthage v0.7.5, and it worked well. The `OAStackView` shared scheme in `OAStackView.xcodeproj` was found and built correctly.

**Comment by ikesyo** [comment]
The project seems to be Carthage-compatible now by your PR oarrabi/OAStackView#24, so closing this out.
