### ISSUE TITLE
watchOS 2.0 no identity found

### ISSUE THREAD

**Issue by bassrock** [Carthage/Carthage#587]
I am working on converting my current watch app to a native watchOS app. I did this by adding a watchOS framework target to all the frameworks I use on Github i.e.:

https://github.com/bassrock/Alamofire/tree/watchOS
https://github.com/bassrock/IGInterfaceDataTable/tree/watchOSFramework
https://github.com/bassrock/SwiftyJSON/tree/watchOSFramework

However when I tried adding them to my target with the copy script phase for just the iOS app (i.e. no copying watchOS frameworks):

I get the error on app load:
```
dyld: Library not loaded: @rpath/IGInterfaceDataTable.framework/IGInterfaceDataTable

Reason: image not found
```

However if I try adding the copy frameworks to the WatchExtension specifying the watchOS frameworks i get the following error on the run script phase:

```
A shell task failed with exit code 1:
: no identity found
```

Has anyone used carthage successfully with watchOS 2.0 frameworks yet?

**Comment by bassrock** [comment]
#481 discussion may be relevant for watchOS 2.0 now

**Comment by jmacmullin** [comment]
If you embed the frameworks your watch extension depends upon it seems to work (ie. no need to add the Carthage copy frameworks run script phase for the watch extension).
<img width="995" alt="embed" src="https://cloud.githubusercontent.com/assets/96165/8537980/68a43ba8-24a9-11e5-886b-0d714d7a39d0.png">

**Comment by bassrock** [comment]
Awesome! I totally missed that!!! Thanks!!!!!

**Comment by MSchmidt** [comment]
I've tried @jmacmullin method and while it worked in development it seems to cause issues while submitting to the App Store with the error ``Invalid segment Alignment``. I think we need a way to run the ``copy-frameworks`` script for the watchOS target. Any ideas?

**Comment by NachoSoto** [comment]
Yeah, frameworks need to be stripped for this target as well.

> A shell task failed with exit code 1:
: no identity found

Where is that error coming from? Looks like the `copy-frameworks` script might need to be updated to support this.

**Comment by NachoSoto** [comment]
> A shell task failed with exit code 1:
> : no identity found

I just ran into this, and I didn't change anything... suddenly `copy-frameworks` started failing. I tried:
- Restarting computer
- Removing Derived Data
- Deleting private key from Keychain and reading it
- Updating identities in Xcode

Nothing works... I'm running Carthage 0.9.2.

SO. TIRED. OF. XCODE :fire:

**Comment by NachoSoto** [comment]
Turns out Xcode isn't setting `EXPANDED_CODE_SIGN_IDENTITY` **only** for one target. The signing identity is correctly configured... (and `CODE_SIGN_IDENTITY` is correct too).

Has anyone seen this?
