### ISSUE TITLE
Multiple platforms

### ISSUE THREAD

**Issue by soffes** [Carthage/Carthage#592]
It would be great if there was a way to only build for a set of platforms (i.e. iOS & watchOS but not OS X). Even better, it would be great if the default was `--platform auto` and it looked at your project and figured out which platforms you needed.

**Comment by mdiep** [comment]
I don't think we'll do an `auto` setting because we'd like to keep things simple. But allowing multiple platforms seems like a good idea now that there are 3 platforms.

**Comment by soffes** [comment]
Almost didn't suggest it at first, but you look at relevant schemes when building already so you don't build app schemes per #141 :)

**Comment by mdiep** [comment]
But that's schemes in the framework project. Aren't you suggesting that we look in your app's project to decide which platforms to build your dependencies for?

**Comment by soffes** [comment]
Correct. No worries either way. It is something I type every time though :)

**Comment by natan** [comment]
I agree that attempting to implement an `auto` setting would not be simple. But I definitely side with @soffes that this area of Carthage's UI could be improved (I bet the majority of app projects are for one specific platform and not `all`, ie. the majority of Carthage customers' updates are much slower than they should be if they `carthage update` per the README).

Some simple suggestions for achieving this enhancement:
- add an optional `platform` section of the Cartfile that allows overriding the default of `all`
- a per-repository `CarthageOptions` which allows overriding default options

If interested, I'd be willing to contribute to fixing this!

**Comment by neilpa** [comment]
@natan See #359 which started the per-project config settings.
