### ISSUE TITLE
Nested dependencies not being built

### ISSUE THREAD

**Issue by drekka** [Carthage/Carthage#593]
I have a very simple project structure

Main project depends on Story Teller depends on PegKit

The Main Project CartFile:
`github "drekka/StoryTeller" >= 0.2`

The Story Teller CartFile:
`github "drekka/pegkit" "develop"`

When I attempt to run any carthage commands (checkout, build, bootstrap), then the dependencies of the Story Teller project are managed. In other words I have to manually cd into the checked out Story Teller directory and run the command, before going back to the Main Project directory and running the same command.

Is this correct? I thought carthage could recurse into nested projects.

**Comment by ikesyo** [comment]
It seems that in your `drekka/StoryTeller` repository you have `CartFile`, not `Cartfile`. If you rename the file, it should work.

**Comment by ikesyo** [comment]
This is because `git show` command, used in Carthage for nested dependencies handling, treats the file name as case sensitive. You can rename the file with `$ git mv CartFile Cartfile`.

**Comment by drekka** [comment]
Ahh. For some crazy reason I had it in my file that the file had to have a capital 'T'. Did some messing around on the Mac because even though I had it renamed locally, git didn't recognise the case change. Anyway, all fixed and building now. Thanks.

**Comment by drekka** [comment]
Double oops. Just noticed your git mv command - Doh!
