### ISSUE TITLE
Simulator verification failed.

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Carthage/Carthage#594]
I have Xcode 6.3.1 and Carthage 0.7.5 installed.

When I run `carthage update`, i get the following error.

**2015-06-30 18:19:36.946 xcodebuild[2315:28128] [MT] iPhoneSimulator: SimVerifier returned: Error Domain=NSPOSIXErrorDomain Code=53 "Simulator verification failed." UserInfo=0x7fcc02cc4d60 {NSLocalizedFailureReason=A connection to the simulator verification service could not be established., NSLocalizedRecoverySuggestion=Ensure that Xcode.app is installed on a volume with ownership enabled., NSLocalizedDescription=Simulator verification failed.}**

I saw this issue has been discussed here before so I followed instructions mentioned in this [post](https://github.com/Carthage/Carthage/issues/424#issuecomment-93434921) but unfortunately the error message still persists. 

Weird thing is sill the build actually progress and creates the frameworks in the `Carthage/Build` folder even though the error message appears.

Any reason for this?

**Comment by mdiep** [comment]
I think [this fix](https://github.com/Carthage/Carthage/issues/424#issuecomment-99551625) is a better one. But ultimately this an Xcode issue, not a Carthage one.

As for why you'd get the error but still have the frameworks… I'm not sure. I'd look in the log that Carthage uses for the xcodebuild output to look for more clues.

**Comment by Isuru-Nanayakkara** [comment]
That worked! Thank you.
