### ISSUE TITLE
'carthage bootstrap' will not run on CircleCI

### ISSUE THREAD

**Issue by jamesdo** [Carthage/Carthage#595]
After getting to 'carthage bootstrap', I get an error message:
```
Username for 'https://github.com': Username for 'https://github.com':
```
How can I fix this?

**Comment by mdiep** [comment]
You need to make sure `git` and `carthage` can access your credentials to authenticate with GitHub.

**Comment by jamesdo** [comment]
Hey @mdiep , I forgot to mention I'm running in CircleCI, how do I go about configuring it for that?

**Comment by mdiep** [comment]
I've never used CircleCI, so I have no idea. You might want to talk to them about it.

**Comment by tonyd256** [comment]
Also, having this issue. @jamesdo did you figure it out?

**Comment by ikesyo** [comment]
[0.8](https://github.com/Carthage/Carthage/releases/tag/0.8) is released. #605 and #648 merged in that release would help.

**Comment by jschmid** [comment]
Did anyone succeeded to run Carthage on CircleCI ?

Even with v0.8 and the `GITHUB_ACCESS_TOKEN` variable, I get an error when trying to clone a private repo.

**Comment by Danappelxx** [comment]
Updates?

**Comment by jschmid** [comment]
I personally solved my problem with the private repo by adding a "Checkout SSH key" in my project settings.

**Comment by garnett** [comment]
Same here, even after adding "Checkout SSH key" in circle ci settings

**Comment by weissazool** [comment]
Recently got this on CircleCI:
```
A shell task failed with exit code 128:
fatal: could not read Username for 'github.com': terminal prompts disabled
carthage bootstrap returned exit code 1
Action failed: carthage bootstrap
```
Seems like a similar issue. Other CircleCI projects using Carthage are fine, however this one includes a private dependency. Tried adding the "Checkout SSH key" in project settings, but no luck.

**Comment by mdiep** [comment]
Carthage uses HTTPS by default. You'll also need to use the `--use-ssh` flag if you add an SSH key.

**Comment by weissazool** [comment]
Telling Carthage to use SSH in my `circle.yml` configuration file resolved the issue for me. Thanks!
