### ISSUE TITLE
0.7.5 hangs on carthage update after asking for GitHub username

### ISSUE THREAD

**Issue by ayanonagon** [Carthage/Carthage#596]
I hadn’t seen this issue before, but the only thing that is different from my other scenarios is that it’s for a framework that is private on GitHub but I have access to. I can clone it just fine, so my (kind of) workaround was to clone the framework repo and use the local project reference in the `Cartfile`.

Let me know what other info I can give to help debug. Thank you! :octocat:

**Comment by mdiep** [comment]
Is this on your local machine? Or on a CI server?

What's the output of `git --version` and `carthage version`?

**Comment by ayanonagon** [comment]
Local machine.
`git version` => 2.1.1
`carthage version` => 0.7.5

**Comment by mdiep** [comment]
What's the output of `git config --get credential.helper`?

If you run `echo "url=https://github.com"|git credential fill`, does it prompt you for your password or print out credentials? **Don't paste the output of this command**

**Comment by ayanonagon** [comment]
`git config --get credential.helper` outputs nothing
`echo "url=https://github.com"|git credential fill` asks for my password

**Comment by mdiep** [comment]
> `git config --get credential.helper` outputs nothing

That explains it. :smile: If you follow [these instructions](https://help.github.com/articles/caching-your-github-password-in-git/) to set up a credential helper, then Carthage should be able to access your credentials.

**Comment by ayanonagon** [comment]
That worked. Thank you @mdiep! :dancer:

**Comment by mdiep** [comment]
:dancers:
