### ISSUE TITLE
Frameworks built both for iOS and OSX despite specifying platform

### ISSUE THREAD

**Issue by zats** [Carthage/Carthage#597]
When building with carthage, one particular framework is being built for both iOS and OS X despite specifying `--platform Mac`.
As a disclaimer, I should acknowledge, I'm not entirely sure if it's an issue with my configuration, carthage or the framework itself. 
Here is my Cartfile:
```
github "zats/google-diff-match-patch" "master"
github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.8"
```
Cartfile.resolved:
```
github "robrix/Box" "1.2.2"
github "zats/google-diff-match-patch" "5059ff1fdbc0f79dfdfc8f976e7e200d37470de1"
github "antitypical/Result" "0.4.4"
github "ReactiveCocoa/ReactiveCocoa" "b89e1b73f2d1c6a99e0916f699ab6dcda71c74b5"
```
The command I'm running `$ carthage update --use-submodules --platform Mac`
The framework that is built for both iOS and OS X is Box. 
It doesn't bother me that much, but it might be a sign of a bigger issue :scream_cat: 
Let me know if I can provide any more information, or if you think the issue is not in Carthage.

Thank you!

**Comment by ikesyo** [comment]
Box 1.2.2 release has an attached prebuilt framework binary, then that was unzipped and placed into `Carthage/Build`. So the framework was not built, but just downloaded.

If you don't want those prebuilt frameworks, you could add `--no-use-binaries` flag.

**Comment by zats** [comment]
Oh that makes sense now, thanks! I'll definitely use the flag you mentioned!
A curiosity question: shouldn't the fact of having binary be mutually exclusive with building the framework from the sources? I'm trying to think of a case when the current behaviour would be desirable…
Is the mismatching binary kept by design or is it the current implementation waiting for pull request? 😃

**Comment by neilpa** [comment]
> shouldn't the fact of having binary be mutually exclusive with building the framework from the sources?

It is. That's why it's downloading the release package and not building the framework.

> Is the mismatching binary kept by design or is it the current implementation waiting for pull request? 

I don't see any reason to add code to delete the non-matching, pre-built frameworks when specifying `--platform`.

**Comment by zats** [comment]
got it, thanks
