### ISSUE TITLE
Add configuration in Cartfile to config the path for Carthage

### ISSUE THREAD

**Issue by NicholasTD07** [Carthage/Carthage#599]
Right now the location of Carthage defaults `./Carthage`. When you are working on multiple versions of Swift or you have different versions of dependencies in different branches, and you need to constantly switch between them, you either have to do `carthage bootstrap` every time or before checking out another branch, copy the `Carthage` folder to something else to keep it for later when you are switching back. 

It would be nice to have a config in `Cartfile` to config the path of the folder that Carthage uses. So it's easier to work with different versions of Swift or even just different branches and won't need to do `carthage bootstrap` every time when switching the version of swift or the branch. Because the Cartfile has the path for the Carthage folder and it is being tracked by version control.

For example, let's say I have a branch where I am using Swift 2, my Cartfile looks like this:

```
path "./Carthage-Swift-2.0"

github "Quick/Nimble" ~> 2.0
```

But for my Swift 1.2 branch,
```
path "./Carthage-Swift-1.2"

github "Quick/Nimble" ~> 1.0
```

When I am switching between Swift 1.2 and 2.0 branches, with the path config, I wouldn't need to do `carthage bootstrap` again. Because all dependencies are kept in different folders.

**Comment by neilpa** [comment]
This probably isn't worth the added complexity. One easy workaround that I've been using is a local repo per swift version. That way you don't have to keep bootstrapping back and forth.

**Comment by NicholasTD07** [comment]
@neilpa Thank you for your solution. Why I didin't thought of it, HA.
