### ISSUE TITLE
Carthage not building Sparrow framework and log file is empty

### ISSUE THREAD

**Issue by max1701** [Carthage/Carthage#609]
### Setup

Carthage 0.6.5, 0.7.3, 0.7.5
Xcode Version 6.4 (6E35b)

### Project

Sparrow 
├── .gitignore
├── Classes
├── Fixtures
├── Sparrow.xcodeproj
├── UnitTests
└── build

Sparrow is an open source game engine for iOS: http://gamua.com/sparrow/
Its available on github: https://github.com/Gamua/Sparrow-Framework
however, the xcodeproj cannot be found in the root directory, so i cloned the relevant part on bitbucket AND marked the scheme as SHARED to try to build it with carthage:

https://max1701@bitbucket.org/max1701/sparrow.git

The Cartfile has only one entry:

git "https://max1701@bitbucket.org/max1701/sparrow.git" "master"

### Error

Running "carthage update" returns 

*** Fetching sparrow
*** Checking out sparrow at "10da0764b47df873dca17dd42a0243c276d9a001"
*** xcodebuild output can be found in /var/folders/mp/g01_pfvd55l5lhmjz3tztzx00000gn/T/carthage-xcodebuild.ztnn14.log

with an empty log file (size is 0) and an empty Build directory.

As suggested in the docs, i ran "xcodebuild -scheme SCHEME -project PROJECT build" as well, which succeeded without any errors.

I tried carthage version 0.6.5, 0.7.3 and 0.7.5, since in issue #589 a somehow similar behaviour was described (e.g. empty log file)

Thanks in advance for any ideas!

**Comment by ikesyo** [comment]
The forked project on your Bitbucket does not have a dynamic framework target, but only have a static library target. Carthage targets only building dynamic frameworks, so you should setup a dynamic framework target for that project.

**Comment by max1701** [comment]
Thanks a lot! I didn't pay attention to that aspect, although carthage's documentation is very clear about that ;)
