### ISSUE TITLE
Pre-built libraries don't link if they're the wrong Swift version

### ISSUE THREAD

**Issue by therealbnut** [Carthage/Carthage#612]
For the full epic journey take a look here (#611).

If Carthage fetches pre-built frameworks with an old swift version then Xcode returns the following error:
```
error: module file was created by an older version of the compiler: <TheProjectPath>/Carthage/Build/iOS/Nimble.framework/Modules/Nimble.swiftmodule/x86_64.swiftmodule
```

I bypassed this issue by forking the remote and running Xcode's swift migration, the only change in the project was:
```diff
- LastSwiftUpdateCheck = 0600;
+ LastSwiftUpdateCheck = 0700;
```

It would be good to either:
 * Detect if a pre-built framework is the wrong swift version, perhaps try substituting `LastSwiftUpdateCheck` in the project for the `xcode-select` version, and then attempt using `xcodebuild`.
 * Provide a `carthage` argument to bypass the pre-built frameworks, this alone probably won't fix the issue though.

**Comment by ikesyo** [comment]
> Provide a carthage argument to bypass the pre-built frameworks, this alone probably won't fix the issue though.

FYI: There is already the `--no-use-banaries` option for that purpose.

**Comment by therealbnut** [comment]
Ah thanks, I couldn't find any documentation for arguments. Although I just found it while typing this, I'm used to typing something like `carthage update --help` rather than `carthage help update`.

Unfortunately I think this still requires you to migrate the dependency to build it properly, but I guess that's not really a Carthage problem.

`carthage update --no-use-binaries` should do it.

**Comment by therealbnut** [comment]
Re-opened in case the `LastSwiftUpdateCheck` option is worthwhile, I think matching versions is probably something a dependency manager should be doing.

**Comment by ikesyo** [comment]
> I bypassed this issue by forking the remote and running Xcode's swift migration, the only change in the project was:

I think that isn't/should not be related to the issue you encountered. That was becase of jus thet Swift's binary compatibility between some Xcode/Swift versions.

In the situation, you should use or wait a new release of some libarires what is compatible with the Xcode version you are using.

**Comment by therealbnut** [comment]
I agree, waiting works, but not knowing that the problem was version incompatibility of an old pre-built binary took a while to do the detective work for.

I don't think that it's my decision to close what I consider to be an ongoing issue as I'm only a casual Carthage user. I'd be satisfied if someone that contributes to the codebase saw this and said "no it's not in the scope of what we want Carthage to do", or "we should provide better console output if the binary is incompatible with the current xcode version".

Personally I think the console output should be better.

I spent a good deal of time today tracking down why this didn't work, and a good part of that was because Carthage was unclear on where it was getting its build products from and how that meant they were incompatible.

For example, if xcodebuild is not run, why put an xcodebuild log path in the console output? Perhaps instead log that the binaries are being copied from the remote. If the cache (`binaries`) is not compatible, perhaps a dependency manager should at least warn the user.

**Comment by mdiep** [comment]
We can probably make the use of prebuilt binaries a bit more clear in our output. But the main issue here is that xcodebuild's output is unclear. That's definitely beyond the scope of this project—we don't want to be in the business of parsing and interpreting xcodebuild's output.
