### ISSUE TITLE
Add Build annotation to Cartfile

### ISSUE THREAD

**Issue by AndrewSB** [Carthage/Carthage#614]
I use Carthage to keep all of my dependencies up to date - a good deal of them do not have shared schemes or framework support and can't be built with Carthage

On every `carthage update` or `bootstrap`, I get errors saying "the project does not have any shared schemes, or xcodebuild never returned"...
I was wondering if there was any way to specify - in my `Cartfile` - that I just want to checkout these libraries and not build them?

Thank you

**Comment by mdiep** [comment]
There's not, no. We assume that projects are correctly configured with shared schemes and dynamic frameworks.

Your options are:

1. Submit PRs to add shared schemes and dynamic frameworks
2. Maintain a fork of the dependency that adds them
3. Use carthage with `--no-build` and add dependencies' `xcodeproj`s to your Xcode project

**Comment by AndrewSB** [comment]
That makes sense - thank you for all of your work @mdiep 😀
