### ISSUE TITLE
Library not loaded: @rpath/Alamofire.framework/Alamofire

### ISSUE THREAD

**Issue by jdecarlo** [Carthage/Carthage#616]
I am not having trouble building or linking, but get this error near startup:

dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /Users/josephdecarlo/Library/Developer/CoreSimulator/Devices/0EFCC13F-38B8-441B-926A-D823057C5E80/data/Containers/Bundle/Application/F3F33C21-8DE0-4651-8B71-E906E48A4827/goref-ios.app/goref-ios
  Reason: image not found

I have several libraries I've added with Carthage, but it fails on this one first.  I imagine, the other ones would also fail if I were to remove references to Alamofire.

I'm new to Carthage, but am not seeing how to resolve this...

Things I have verified from other issues on here:
- Framework Search paths includes:  $(PROJECT_DIR)/Carthage/Build/iOS (and the directory is the correct one)
- Runpath Search Paths includes: $(inherited) and @executable_path/Frameworks

I am really excited to get this going, but am not sure where to go from here.  I get the same behavior in the simulator and on device.  (iOS 8.3 SDK, XCode 6.3.2)

Any help is appreciated.

Joe

**Comment by ikesyo** [comment]
Did you check this?: https://github.com/Carthage/Carthage/issues/615#issuecomment-120927579

> Are there the `Embed Frameworks` build phase? If there isn't, you should add a new "Copy Files Phase", then select "Framrworks" for Destination, add frameworks to the list, and check "Code Sign On Copy" checkboxes.

**Comment by jdecarlo** [comment]
I had looked at that issue, but missed the Embed Frameworks part.  My apologies.  Thank you for your quick reply.  This seems to have solved my issue.

**Comment by ikesyo** [comment]
No problem! :sparkles:

**Comment by tetriscode** [comment]
I'm getting this error on running my unit tests for a Static Library project. 
```
Library not loaded: @rpath/ReactiveCocoa.framework/ReactiveCocoa
  Referenced from: /Users/wesr/Library/Developer/Xcode/DerivedData/SpatialConnect-flewyfsgpffsjvgrrmjgyezsyujb/Build/Products/Debug-iphonesimulator/SpatialConnectTests.xctest/SpatialConnectTests
  Reason: image not found, NSBundlePath=/Users/wesr/Library/Developer/Xcode/DerivedData/SpatialConnect-flewyfsgpffsjvgrrmjgyezsyujb/Build/Products/Debug-iphonesimulator/SpatialConnectTests.xctest, NSLocalizedDescription=The bundle “SpatialConnectTests” couldn’t be loaded because it is damaged or missing necessary resources.}
```
I have ReactiveCocoa linked in the Unit Tests but since there is no ```Embed Frameworks``` option for static libraries, I'm at a loss. 

if I copy Frameworks, I get preprocessor errors
![screen shot 2015-07-24 at 8 28 49 am](https://cloud.githubusercontent.com/assets/242747/8875333/1984064c-31de-11e5-8500-23dac7c6fc47.png)
