### ISSUE TITLE
Installation fails on El Capitan 10.11b3 (15A216g)

### ISSUE THREAD

**Issue by avioli** [Carthage/Carthage#620]
System: Mac OS X El Capitan (10.11 Beta 3 - 15A216g)

```
$ xcode-select -p
/Applications/Xcode-beta.app/Contents/Developer
$ brew update
Already up-to-date.
$ brew install -vd carthage
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Cloning https://github.com/Carthage/Carthage.git
Cloning into '/Library/Caches/Homebrew/carthage--git'...
# ... continues in the Install Log below...
```

Install Log: https://gist.github.com/avioli/0efa961fba5f5cced477
Make Log: https://gist.github.com/avioli/6efa802db909974aa2e7
Make log is from /Users/avioli/Library/Logs/Homebrew/carthage/01.make

**Comment by mdiep** [comment]
Your system tried to build Carthage with Swift 2, when Carthage still uses Swift 1.2. You should be able to use the `pkg` installer available under Carthage's releases on GitHub.

**Comment by avioli** [comment]
Ah, totally forgot about Swift 2. Cheers.

**Comment by codeOfRobin** [comment]
Thanks for the tip @mdiep . I have a question though. I prefer using homebrew for my command line tools, so is there any way to uninstall it once I use the pkg?
