### ISSUE TITLE
[feature] Preserve headers layout

### ISSUE THREAD

**Issue by dodikk** [Carthage/Carthage#623]
As a **framework maintainer**
I want carthage to **keep the headers physical layout**
![screen shot 2015-07-16 at 3 41 25 pm](https://cloud.githubusercontent.com/assets/396451/8722838/3b796b9c-2bd1-11e5-98a3-6225185b9753.png)
![screen shot 2015-07-16 at 3 42 46 pm](https://cloud.githubusercontent.com/assets/396451/8722879/b79baee2-2bd1-11e5-9e18-00410b2dc12a.png)

So that my **include statements** would be the **same**
Either if I build from sources or if I use a framework.

**Comment by mdiep** [comment]
You can configure this in Xcode. Carthage doesn't handle this itself; it just asks Xcode to build the framework.

**Comment by dodikk** [comment]
[Copy-framework](https://github.com/Carthage/Carthage/pull/208) could be configured in Xcode as well. 
Nevertheless, it ships with Carthage now.

**Comment by dodikk** [comment]
Same thing for [Copy dSYM files alongside built frameworks](https://github.com/Carthage/Carthage/pull/516)

**Comment by dodikk** [comment]
Here is a script that does the job for the [kstenerud/iOS-Universal-Framework](
https://github.com/kstenerud/iOS-Universal-Framework/pull/37)

Would you consider adopting it to Carthage?

```bash
INLINED_PYHON_SCRIPT="import sys; import os.path; headerPathFromFind = sys.argv[2]; srcRoot = sys.argv[1]; headerPathFromFindWithoutFilename = os.path.dirname( headerPathFromFind ); relatedPathForDirectory = os.path.relpath( headerPathFromFindWithoutFilename, srcRoot ); print( relatedPathForDirectory );"

HEADERS_ROOT=$SRCROOT/$PRODUCT_NAME
FRAMEWORK_HEADERS_DIR="$BUILT_PRODUCTS_DIR/$WRAPPER_NAME/Headers"

## only header files expected at this point
PUBLIC_HEADERS=$( ls -1 "$FRAMEWORK_HEADERS_DIR" )


for PUBLIC_HEADER in $PUBLIC_HEADERS; do

   FIND_RESULT=$( find "$HEADERS_ROOT" -name "$PUBLIC_HEADER" )
   RELATIVE_PATH=$( python -c "$INLINED_PYHON_SCRIPT" "$HEADERS_ROOT" "$FIND_RESULT" )

   mkdir -p "$FRAMEWORK_HEADERS_DIR/$RELATIVE_PATH"
   mv "$FRAMEWORK_HEADERS_DIR/$PUBLIC_HEADER" "$FRAMEWORK_HEADERS_DIR/$RELATIVE_PATH/$PUBLIC_HEADER"
done
```
https://github.com/EmbeddedSources/iOS-Universal-Framework/commit/a2c01b2b7a6b9f92af7930ce2481e56c31b6dd9b

**Comment by mdiep** [comment]
`copy-framework` works around a limitation in Apple's tooling that Carthage hits. Copying the dSYM is different because it's not altering the end product in any way.

I don't think this is a good fit for Carthage. Sorry.

**Comment by dodikk** [comment]
>> copy-framework works around a limitation in Apple's tooling

Xcode's "copy headers" build step making headers hierarchy flat is Apple's tooling limitation as well.

**Comment by dodikk** [comment]
Actually, this limitation prevents from organising the framework project files in separate directories.
I guess, this is the reason why ReactiveCocoa is flat.
https://github.com/ReactiveCocoa/ReactiveCocoa/tree/swift-development/ReactiveCocoa/Objective-C

However, it may be hard to add Carthage support for frameworks like MagicalRecord
https://github.com/magicalpanda/MagicalRecord/tree/master/MagicalRecord

Since each maintainer will have to write or search for the directory layout script.

**Comment by dodikk** [comment]
https://github.com/magicalpanda/MagicalRecord/issues/1047
https://github.com/dodikk/MagicalRecord-filesystem-bug

Here is an example of the pain the maintainers face porting their libraries to Carthage.

**Comment by mdiep** [comment]
> Xcode's "copy headers" build step making headers hierarchy flat is Apple's tooling limitation as well.

`copy-framework` works around a limitation that would prevent applications from being submitted to the App Store, which is far more serious.

> Actually, this limitation prevents from organising the framework project files in separate directories.
> I guess, this is the reason why ReactiveCocoa is flat.

ReactiveCocoa's structure on disk is flat because the authors believe it to be unimportant, not because of any limitation. (And they're mostly right.)

> Since each maintainer will have to write or search for the directory layout script.

If maintainers want to do this, they can still share a script somewhere else. It wouldn't need to be in Carthage.

---

This isn't going to happen. The directory structure in the built framework is unimportant. If you want to do it anyway, you can and Carthage won't stop you.

**Comment by dodikk** [comment]
>> This isn't going to happen. 

Sad. Feels like https://github.com/AFNetworking/AFNetworking/pull/2552
Thank you for your time, anyway.

**Comment by robb** [comment]
Isn't the apple-blessed future module map and an `@import` statement anyhow?
