### ISSUE TITLE
Question: How to get the very latest (most recent commit) version of a given repository?

### ISSUE THREAD

**Issue by chrisco314** [Carthage/Carthage#624]
The Cartfile documentation makes the assertion:

> If no version requirement is given, any version of the dependency is allowed.

with the contradictory example:

> \# Use the latest version
> github "jspahrsummers/xcconfigs"

Furthermore, it is not stated, but from testing, I infer that latest, is actually the version of the latest tag.  Is this interpretation correct?  And if so, how does one specify the very latest commit - do you have to manually check and specify the latest commit, or is there a simpler way?

And as a side point, it would help to give an example of checking out based on a commit hash, on my first pass, I didn't realize that the quotes were significant, and this foiled me.

**Comment by mdiep** [comment]
The latest version refers to something that has an actual _version_—a release or tag. If you want the most latest commit, you need to specify the branch you want to pin to.

**Comment by chrisco314** [comment]
Closed - thanks for the quick response.

(Though the documentation / example inconsistency could / should still be fixed).

**Comment by chrisco314** [comment]
Actually, it turns out that you can achieve this by specifying "head" as the version (insert proper nomenclature):

    github "jspahrsummers/xcconfigs" "head"

per my cross post to Stackoverflow:

http://stackoverflow.com/questions/31459847/carthage-how-to-get-the-very-latest-version-of-a-given-repository/31460014#31460014
