### ISSUE TITLE
Problem with submodules

### ISSUE THREAD

**Issue by HeMet** [Carthage/Carthage#625]
I have a project where I using Carthage with submodules. Each project in workspace accosiated with folder in `Carthage/Checkout`. 
If I make changes in one of my submodules and commit it, then run `carthage update --use-submodules`, it's just reset Checkout subfolder to commit from `Cartfile.resolved`. What I need is update `Cartfile.resolved` so it points to latest commit from submodule. How to do that?

**Comment by mdiep** [comment]
Running `update` should update `Cartfile.resolved` to the last _release_ from each dependency that matches the version you listed. If you want to use the latest commit, you need to specify a branch in your `Cartfile`.

**Comment by HeMet** [comment]
Thank you, it works!
