### ISSUE TITLE
Module file was created by an older version of the compiler

### ISSUE THREAD

**Issue by matthewcheok** [Carthage/Carthage#633]
Module file was created by an older version of the compiler: /Users/`user`/Library/Developer/Xcode/DerivedData/`project`-bqbyywemjnvvodecjidroebdmlnu/Build/Products/Debug-iphonesimulator/`library`.framework/Modules/`library `.swiftmodule/x86_64.swiftmodule

I'm getting the above error after building via `carthage update`. Xcode 7 beta complains that the swift module is built with an older version of the compiler. Any ideas?

**Comment by gfontenot** [comment]
Are you using the right version of `xcodebuild`? What do you see when you run `xcode-select -p`? It should be pointed at Xcode 7 if you want to use the frameworks in Xcode 7.

**Comment by matthewcheok** [comment]
Yes I'm pointed at Xcode 7

**Comment by matthewcheok** [comment]
The framework contains Swift 2.0 so I couldn't built it otherwise

**Comment by marlowcharite** [comment]
Any word on this yet?

**Comment by matthewcheok** [comment]
looks like it's fixed by a later version of Xcode

**Comment by ramirez** [comment]
Hi. I updated to XCode 7.1 and I'm getting the same error when trying to build: 
error: module file was created by an older version of the compiler; rebuild 'Alamofire' and try again.

Any ideas why this can be happening?

Thx!

L.

**Comment by ikesyo** [comment]
@ramirez Did you rebuild the framework by `carthage build` with the command line tools of Xcode 7.1? If the framework was built with Xcode 7.0, the error would happen.

**Comment by ramirez** [comment]
@ikesyo : Yes, I used carthage build --platform iOS and it worked for all but one of the frameworks that I included

**Comment by ikesyo** [comment]
How about `rm -rf ~/Library/Developer/Xcode/DerivedData/Alamofire-*` then redo `carthage build`? I have no idea other than that.

**Comment by ramirez** [comment]
It didn't work. The only difference I can see in the log file is that Alamofire uses one SDKROOT:

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphonesimulator9.1

=== BUILD TARGET Alamofire iOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

and the failing framework uses a different one:

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos9.1

=== BUILD TARGET MyKitiOS OF PROJECT MyKit WITH CONFIGURATION Release ===


Could that be the problem? How can I change the used SDKROOT?

Thx!

**Comment by ikesyo** [comment]
Alamofire is not the problematic one, right? If so, you might have to `rm -rf ~/Library/Developer/Xcode/DerivedData/MyKit-*` instead of Alamofire. I'm not sure what the issue you are facing is... 

> The only difference I can see in the log file is that Alamofire uses one SDKROOT

That is because Carthage builds both for simulator archs (`SDKROOT = iphonesimulator`) and device archs (`SDKROOT = iphoneos`). There should be `SDKROOT = iphoneos` lines for building Alamofire. I don't think that is related to the problem.

**Comment by ramirez** [comment]
The:

`rm -rf ~/Library/Developer/Xcode/DerivedData/MyKit-*`

 did the trick, thanks!

**Comment by kiliankoe** [comment]
Just in case someone comes along scratching their head at this issue as I was today:

My problem was occurring when using antitypical/Result. A normal `carthage build` finished rather quickly and even though `xcode-select -p` was totally on my side, I couldn't figure out why Xcode was complaining about an older version of the compiler.
A few hours later it hit me that Result was being used by Carthage as a prebuilt binary and was never built with my version of the Xcode-beta. Running `carthage update --no-use-binaries` saved my sanity 🙃

**Comment by BenchR267** [comment]
Thanks @kiliankoe! That was the option I was looking for!

**Comment by IamAlchemist** [comment]
Thanks @kiliankoe ! it save me

**Comment by d0f** [comment]
ubuntu 15.4 error: module file was created by an older version of the compiler; rebuild 'PackageDescription' and t

**Comment by adniosdwqs** [comment]
Don't worry about this issue. I found this same problem, however I have resolved it. I used about 10 third party library (Alamofire, SwiftyJSON, etc., ) , it works on Xcode7.2. 
After I upgraded Xcode7.2 to XCode7.3,  I found this issue : Module file was created by an older version of the compiler; rebuild and try again

Solution: You only need to rebuild this carthage file again using terminal:
carthage update --platform iOS, that's all.

**Comment by karstenlitsche** [comment]
Have this problem too.
I think the problem is when using the download binary feature. Then you get a prebuild framework from github that may be build with another XCode version. It makes sense that the "--no-use-binaries" param solve this.

**Comment by itsshahidsk** [comment]
Had this same issue ...as suggested using the param "--no-use-binaries" fixes it but make sure to add the platform param to checkout only the platform you are using since it takes lot of memory/time
(carthage bootstrap --platform iOS --no-use-binaries)

**Comment by BilalReffas** [comment]
@kiliankoe I ❤️ U 😂

**Comment by richtastic** [comment]
# XCode Version 7.3.1 (7D1014)
cmd+r
import Alamofire // Module file was created by an older version of the compiler; rebuild 'Alamofire' and try again: /Users/.../Alamofire.framework/Modules/Alamofire.swiftmodule/x86_64.swiftmodule

cmd+opt+shf+k
$ rm -rf ./DerivedData/
$ rm -rf ./Carthage/
$ carthage update --platform iOS --no-use-binaries
cmd+r

Module file was created by an older version of the compiler; rebuild 'Alamofire' and try again: /Users/.../Alamofire.framework/Modules/Alamofire.swiftmodule/x86_64.swiftmodule

?

**Comment by shuklaalok7** [comment]
XCode 8 and same error, trying the fixes suggested here.

**Comment by jap99** [comment]
Hi, I too have the same error with Xcode 8. Not sure how to implement some of these solutions above.
![image](https://cloud.githubusercontent.com/assets/17307316/18808414/bd2af664-8216-11e6-95be-7615ea1e0654.png)

**Comment by woshiccm** [comment]
Hi,i have the same error with Xcode 8 ,Carthage 0.18.

**Comment by jose920405** [comment]
For me Cleaning up the Build folder <kbd>Cmd &#x2318;</kbd> + <kbd>Alt &#x2325;</kbd> + <kbd>Shift &#x21E7;</kbd> + <kbd>K</kbd> worked.

**Comment by danstepanov** [comment]
So I ran into this issue specifically with adding ReactiveCocoa. I fixed the issue by using the most recent pre-release version of ReactiveCocoa. That is, I replaced `github "ReactiveCocoa/ReactiveCocoa"` with `github "ReactiveCocoa/ReactiveCocoa" "5.0.0-alpha.3"` in my `Cartfile`

**Comment by nitesh-iosdev** [comment]
How to resolve this issue if the library is setup by pods?

**Comment by anujsyal02** [comment]
I am facing same problem but not with an external library or pod but with apple's PassKit and EventKit

**Comment by gsalve** [comment]
jus "rm -rf " the given Passkit and EventKit files. And just clean the xocde and rerun. Passkit and EventKit location will be in the error. (For me the the location is '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/x86_64/PassKit.swiftmodule')

just use following
 rm -rf /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/x86_64/PassKit.swiftmodule
