### ISSUE TITLE
Question - Build inner frameworks with correct architecture (universal architecture) using carthage build --no-skip-current

### ISSUE THREAD

**Issue by avnerbarr** [Carthage/Carthage#638]
I have a framework target with an inner dependency of another framework target.

So something like:
![screen shot 2015-07-26 at 9 33 40 am](https://cloud.githubusercontent.com/assets/2404795/8892830/74fdb33c-3379-11e5-9d7f-524d08edfd1e.png)

The scheme for the outer framework is "shared"

![screen shot 2015-07-26 at 9 34 34 am](https://cloud.githubusercontent.com/assets/2404795/8892831/8b8afdc6-3379-11e5-9b01-99ea41636fb3.png)

When I run the command 

```carthage build --no-skip-current```

The architecture for the "outer" framework is :

```
~/Developer/Testing/FrameworkTesting/Carthage/Build/iOS : lipo -info FrameworkTesting.framework/FrameworkTesting 
Architectures in the fat file: FrameworkTesting.framework/FrameworkTesting are: i386 x86_64 armv7 arm64
```

But the inner framework is only arm:

```
~/Developer/Testing/FrameworkTesting/Carthage/Build/iOS : lipo -info FrameworkTesting.framework/Frameworks/InnerFramework.framework/InnerFramework 
Architectures in the fat file: FrameworkTesting.framework/Frameworks/InnerFramework.framework/InnerFramework are: armv7 arm64 
```

So if I try to use this framework in another project I can not compile.

Should I be doing something to make this work?

P.S. 
I also have other frameworks (3rd party) embedded into this framework derived directly from carthage build which also have the same architecture problems.

**Comment by mdiep** [comment]
It looks like the inner target is part of the same Xcode project. My guess is that you'd need to move the inner framework to a separate repository and manage that dependency with Carthage.

**Comment by avnerbarr** [comment]
That wouldn't be practical for me. I need the source code in one project but have the ability to create separate framework when necessary. 

Why do you think it is it not compiled together correctly? I also have additional compiled frameworks inside the project (universal lipo frameworks without the sources ) that get the x86 part removed when Carthage builds the outer framework

**Comment by mdiep** [comment]
> Why do you think it is it not compiled together correctly?

I don't know. You'd have to do some investigation.

**Comment by ikesyo** [comment]
> Why do you think it is it not compiled together correctly?

Your InnerFramework isn't built by Carthage since the scheme is not shared. That is built by Xcode.

And also nested frameworks embeded in other frameworks are not supported by Carthage nor by iOS/watchOS/tvOS playforms (those would be rejected by App Store submittion validation).
