### ISSUE TITLE
BrightFutures 

### ISSUE THREAD

**Issue by siskaj** [Carthage/Carthage#639]
I experience a problem when I try to use Carthage for BrightFutures v 3.0 (Swift 2.0)

Here is what I get in terminal:
pc3:TestFutures jsiska3$ carthage update
*** Fetching BrightFutures
*** Fetching Result
*** Checking out Result at "0.6-beta.1"
*** Checking out BrightFutures at "18315983cfe2c716edacc78e12082eaad67ceb79"
*** xcodebuild output can be found in /var/folders/ql/gtsmwj8d4lnddnk66z0gkq8r0000gn/T/carthage-xcodebuild.yu8rG2.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "Result-Mac" in Result.xcodeproj
*** Building scheme "Result-watchOS" in Result.xcodeproj
Parse error: unexpected SDK key "(string)"
Segmentation fault: 11
pc3:TestFutures jsiska3$ 

In ../Cartage/Build/iOS/ folder i get only Result.framework (embedded framework). The BrightFutures.framework is not created.

I use Xcode 7 b4, and OSX 10.10.4
My cartfile contains - github "Thomvis/BrightFutures"  "18315983cfe2c716edacc78e12082eaad67ceb79"

I am not able identify what error means. Is it a bug or do I something wrong

Thank you

Jaromir

**Comment by mdiep** [comment]
Is there anything useful in the xcodebuild output?

It sounds like `carthage` may have segfaulted. Which version of Carthage are you using? You can check by running `carthage version`.

**Comment by siskaj** [comment]
Carthage version is - 0.7.3

I enclose log from the xcodebuild - 




Thanx

J.

**Comment by mdiep** [comment]
Can you try updating to the current version of Carthage to see if you still get a segfault?

**Comment by siskaj** [comment]
With the new version there is no problem with a segfault.

Thank you very much for your help!

J.
