### ISSUE TITLE
Please add support for Bitbucket

### ISSUE THREAD

**Issue by saheljalal** [Carthage/Carthage#643]
Similar to github support in Cartfiles, please add a bitbucket shortcut.

**Comment by andyyhope** [comment]
Would also love this!

**Comment by sdgandhi** [comment]
Can't you use the git url for the bitbucket repo: https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#origin

**Comment by mdiep** [comment]
Yes, you _can_ use the `git` keyword to add BitBucket repositories. :smile:

**Comment by sdgandhi** [comment]
Close?

**Comment by tylerlong** [comment]
Why not add a new keyword `bitbucket`? Just like the keyword `github`.

I vote for reopening this issue.
