### ISSUE TITLE
Force code signing setting to "iOS development" in release configuration for built dependencies

### ISSUE THREAD

**Issue by jeremiegirault** [Carthage/Carthage#647]
Hey,

I noticed that some dependencies set their xcodeproj to use "iOS distribution" in their code signing settings in Release mode.

More than often developers have access to development certificates / provisionning but not necessarily distribution certificates with their private key.

As frameworks are later stripped/resigned when embedded it would be great to force code signing settings to use development certificates

What do you think ?

**Comment by akolov** [comment]
I'd prefer if we could specify which certificate to use. I for one wouldn't like to have my development certificates on a CI server that we use for building and pushing to App Store.

**Comment by tomlokhorst** [comment]
I wrote a small bash script, to get Carthage to work on our CI server that creates release builds:

```
#
# First checkout all repos

carthage checkout --verbose

#
# Set the code sign identities of all Carthage repos to "iPhone Distribution"

find Carthage -name *.pbxproj -exec sed -i .bak 's/CODE_SIGN_IDENTITY = "-"/CODE_SIGN_IDENTITY = "iPhone Distribution"/' '{}' +
find Carthage -name *.pbxproj -exec sed -i .bak 's/CODE_SIGN_IDENTITY = "iPhone Developer"/CODE_SIGN_IDENTITY = "iPhone Distribution"/' '{}' +
find Carthage -name *.pbxproj -exec sed -i .bak 's/"CODE_SIGN_IDENTITY\[sdk=iphoneos\*\]" = "iPhone Developer"/CODE_SIGN_IDENTITY = "iPhone Distribution"/' '{}' +

#
# Build all repos

carthage build --platform iOS --verbose
```

This simply replaces the Developer code sign identities in third party libraries with Distribution (for which there is a signing identity).

It would be nice if we could pass this as an argument to `carthage` instead of modifying the project file.

**Comment by mdiep** [comment]
As of 0.11, Carthage disables code signing for all dependencies. :tada:
