### ISSUE TITLE
Build failed when installing Carthage via 'make install'

### ISSUE THREAD

**Issue by rjourde** [Carthage/Carthage#652]
After cloning the `master` branch and then executing make install, I have a build failure:

CompileSwift normal x86_64 /Carthage/Carthage/Checkouts/Box/Box/MutableBox.swift
...
/Carthage/Carthage/Checkouts/Box/Box/MutableBox.swift:8:51: error: 'Printable' has been renamed to 'CustomStringConvertible'
public final class MutableBox<T>: MutableBoxType, Printable {
                                                  ^~~~~~~~~
                                                  CustomStringConvertible
/Carthage/Carthage/Checkouts/Box/Box/MutableBox.swift:25:10: error: 'toString' has been renamed to 'String'
                return toString(value)
                       ^~~~~~~~
                       String
Swift.toString:1:48: note: 'toString' has been explicitly marked unavailable here
@available(*, unavailable) @inline(never) func toString<T>(x: T) -> String

I'm using Xcode beta 4 and `xcode-select` is set to the beta version.

Do I miss something in order to have Carthage properly installed from the cloned `master` branch ?

**Comment by neilpa** [comment]
Carthage hasn't been updated to Swift 2 yet. You need to switch back to Xcode 6 for Swift 1.2

**Comment by rjourde** [comment]
Ok. Thanks!
