### ISSUE TITLE
Use Carthage to build an executable

### ISSUE THREAD

**Issue by AndrewSB** [Carthage/Carthage#660]
I'm trying to add Carthage support to [R.swift](https://github.com/mac-cain13/R.swift), ([PR](https://github.com/mac-cain13/R.swift/pull/46)).

Was wondering if it was possible to tell Carthage to build an executable (which is the scheme currently in the project) or if I need to expose a shared dynamic framework and thats the only thing it would build. 

Thanks for the work with Carthage!

**Comment by mdiep** [comment]
Carthage only supports building dynamic frameworks. It's meant to manage and build dependencies, not for building executables.

**Comment by mac-cain13** [comment]
For people surfing by, please also check the discussion in this PR: https://github.com/mac-cain13/R.swift/pull/46
