### ISSUE TITLE
copy-frameworks: recursive stripping of architectures?

### ISSUE THREAD

**Issue by nickygerritsen** [Carthage/Carthage#662]
I am creating a framework for iOS for which I'd like to use Carthage as the main way of distributing it.

However, I am using other projects as dependencies.
This gives a user-facing problem, because `carthage copy-frameworks` does not strip the frameworks I depend on.

So I have a few options now, which are all not ideal:

* Don't add the frameworks I depend on as a *copy files* or *run script* (using `carthage copy-frameworks`) phase. By doing this I require the end-user of my framework to add all dependent frameworks to their projects themselves and also add a *run script* phase.
* Add a *run script* phase for my dependencies. This will strip off all non-simulator parts of the frameworks as soon as someone runs `carthage bootstrap` (or similar). This makes sure they can use the framework on a real device, but for a simulator they still have to add the frameworks and a *run script* phase themselves
* Add a *copy files* phase. This will **not** strip of anything and therefore I think this will give errors when end-users try to submit their apps to the app store.

First of all, am I right in assuming that the above is all correct?

If so, is it an idea to modify the `copy-frameworks` command to do its work recursively? I.e. it would see if each framework has a `frameworks` folder and if so, loop over all `.framework` directories in that folder and again strip it (and recurse again).

I'm not sure if this is easy to do and I'm not sure if this would give any problems, but I think that if this would be possible it would make using frameworks with dependencies easier, right?

**Comment by mdiep** [comment]
That all sounds correct to me.

We typically encourage the first option. It does require the end-user to add all dependent frameworks. But it has the _huge_ advantage of allowing the end-user to choose the version for all the nested dependencies—including when multiple dependencies have the same dependency.

We run into this a lot with ReactiveCocoa. It's used in projects like ReactiveViewModel and octokit.objc. By not copying ReactiveCocoa into those frameworks, the user/Carthage can select a version of ReactiveCocoa that's compatible with both projects (and the requirements for their own project).

So in general we find this to be the best approach. I'd be open to a pull request that modifies `copy-frameworks` to operate recursively. But I'd like to have a better understanding of your situation before we go down that road. If you feel that it's compelling, would you mind providing some more specifics about your situation?

**Comment by nickygerritsen** [comment]
I think I can understand your reasoning as to why not do it, it does make sense with different versions.

Does option 1 also mean that I need to link the frameworks in my test target if I want to test my framework? I assume it does as the framework target itself does not have the dependencies copied.

I do see some minor issue: my project depends on CommonCrypto and I found a really great project at

**Comment by nickygerritsen** [comment]
Ok typing on my phone fails, sorry I tapped the comment button.

Anyway I wanted to paste https://github.com/soffes/Crypto for the project I use. That project exposes two frameworks of which I only use one.

As far as I know there is no real way to indicate only one framework is requires for my project. So if people need to link frameworks themselves they will probably link a useless framework. Or am I wrong in this assumption?

**Comment by mdiep** [comment]
> I think I can understand your reasoning as to why not do it, it does make sense with different versions.

Like I said, I'm open to it. But I want to make sure there's a compelling reason. :smile:

> Does option 1 also mean that I need to link the frameworks in my test target if I want to test my framework? I assume it does as the framework target itself does not have the dependencies copied.

Yes, that's correct.

> As far as I know there is no real way to indicate only one framework is requires for my project.

That's true.

> So if people need to link frameworks themselves they will probably link a useless framework. Or am I wrong in this assumption?

Carthage will certainly build it. There's nothing to make people link extraneous frameworks, but there's also nothing to stop them from doing so.

**Comment by nickygerritsen** [comment]
So for now the only reason I can think of as to why to do it (besides the "useless" framework) is that it is easier for a user to only add the direct dependency instead of all of them. I'm not sure if this is a real big issue

**Comment by mdiep** [comment]
In that case, I'm going to close this for now. But feel free to reopen if you think there's a good reason to do this. I'm happy to discuss it more. :relaxed:
