### ISSUE TITLE
Excluding testing dependencies from a Carthage compatible framework

### ISSUE THREAD

**Issue by rpowelll** [Carthage/Carthage#664]
In my framework's testing bundle I use _Quick_ and _Nimble_ built through Carthage, but those aren't linked with the framework itself. Ideally I'd want to make it so that people installing my project via Carthage don't have to download those dependencies. Is there a straightforward way to go about that?

**Comment by mdiep** [comment]
Yes! [`Cartfile.private`](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfileprivate) exists for that very purpose. :smile:

**Comment by rpowelll** [comment]
Thanks!
