### ISSUE TITLE
[Crash — Xcode 7 beta 5] dyld: Symbol not found: __TMPdO12ReactiveTask9TaskEvent

### ISSUE THREAD

**Issue by jessesquires** [Carthage/Carthage#665]
### Setup

Installed via brew

````
Carthage 0.8
Xcode 7.0 beta 5 (7A176x)
````

### Cartfile

````bash
github "ReactiveCocoa/ReactiveCocoa"
````

### Command

````bash
$ carthage update
````

### Error

````bash
dyld: Symbol not found: __TMPdO12ReactiveTask9TaskEvent
  Referenced from: /usr/local/bin/carthage
  Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveTask.framework/ReactiveTask
 in /usr/local/bin/carthage
Trace/BPT trap: 5
````

### Related issues

Couldn't find any similar issues reported!

**Comment by mdiep** [comment]
Did you previously install Carthage outside of homebrew? If so, `carthage` might be finding an older version of `CarthageKit.framework`, in which case you need to remove `/Library/Frameworks/CarthageKit.framework`.

**Comment by jessesquires** [comment]
No, only installed via homebrew. I also ran `brew uninstall carthage` and then did a fresh install.

**Comment by jessesquires** [comment]
Oh — just removed `/Library/Frameworks/CarthageKit.framework` and it's all good.

Thanks! :+1:

**Comment by salehmasum** [comment]
how to remove /Library/Frameworks/CarthageKit.framework
could you please explain ? facing same issue. 
I installed carthage from .pkg file not from home brew.
