### ISSUE TITLE
dSYMs from precompiled binaries are not copied to Carthage/Build/

### ISSUE THREAD

**Issue by erichoracek** [Carthage/Carthage#671]
Currently, we host private frameworks built with `carthage archive` on github to speed up build times. Since Carthage 0.8, these uploads now include `.dSYM` files. However, when performing `carthage checkout`, the `.dSYM` files included within the `.zip` archive are not added to the Carthage/Build directory (unlike those that are built from source).

cc'ing @sharplet, as he was the one that worked on this feature.

I can take a stab at fixing this, if desired :+1:

**Comment by sharplet** [comment]
Ah right, I think I assumed that as long as everything is in the archive it would be automatically placed in the correct location, because the path information is retained.

If you're keen to have a go then be my guest! 👏🏻

**Comment by mdiep** [comment]
> I can take a stab at fixing this, if desired

Yes, please! :smile:
