### ISSUE TITLE
How to use CarthageKit as a module with Carthage?

### ISSUE THREAD

**Issue by MrTwo** [Carthage/Carthage#673]
I try to create a Cartfile file:
```
github "Carthage/Carthage" == 0.8
```
then
```
carthage bootstrap
```

Then drag the built `CarthageKit.framework` to project and try to
```
import CarthageKit
```

Error comes: `main.swift:10:8: No such module 'CarthageKit'`

Where's wrong? Am I missing something?

**Comment by ikesyo** [comment]
This is related to an issue of using `CarthageKit` as a dependency, which is described in #546 and #672. If possible, could you check the `slim-down-carthagekit` branch of #672?

**Comment by MrTwo** [comment]
@ikesyo It works! Thanks!

**Comment by ikesyo** [comment]
Glad to hear that! :smile:
