### ISSUE TITLE
How to  only download framework 

### ISSUE THREAD

**Issue by zhongwuayst** [Carthage/Carthage#676]
Cartfile  content is   github "Quick/Quick" ~> 0.3
carthage only download  Quick.framework,   Quick.framework is in build/IOS inside 。
This is what I want。 

I have a framework in github。 It's just a framework, no code。
my Cartfile  content is     github "***/test.framework" ~> 1.0。

when carthage update 

test.framework  is in the  "Carthage/Checkouts/***/" 

Carthage/build/IOS  is empty

I want test.framework   in the  "Carthage/build/IOS" directory。   hao to do?

**Comment by mdiep** [comment]
`Quick.framework` is downloaded from GitHub because it's attached to [recent releases](https://github.com/Quick/Quick/releases/tag/v0.5.1).

If there's a release with a binary available, Carthage will download it. Otherwise it will clone the repository and attempt to build the framework.
