### ISSUE TITLE
Command /bin/sh failed with exit code 139

### ISSUE THREAD

**Issue by S-Shimotori** [Carthage/Carthage#680]
I tried to install ReactiveCocoa for swift2 with Result
```github "ReactiveCocoa/ReactiveCocoa" "swift2"```
then got an error about the custom shell script. 
I already set  those frameworks to "Linked Frameworks and Libraries" and "Run Script" with [If you're building for iOS](https://github.com/Carthage/Carthage#if-youre-building-for-ios).

```
dyld: Library not loaded: @rpath/ReactiveCocoa.framework/ReactiveCocoa
  Referenced from: /Users/S-Shimotori/Library/Developer/CoreSimulator/Devices/227FB972-B413-4626-A5C5-FCC01B0048BC/data/Containers/Bundle/Application/A0A1E188-7353-462D-9041-1D8BA7BE6974/ReactiveNSHipster.app/ReactiveNSHipster
  Reason: image not found
```

```
Caught signal triggered by the Swift runtime!
Illegal instruction: 4

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
[4mhttps://github.com/Carthage/Carthage/issues/new[0m

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.

/path/to/project/ReactiveNSHipster/DerivedData/Build/Intermediates/ReactiveNSHipster.build/Debug-iphonesimulator/ReactiveNSHipster.build/Script-B5495B8E1B7F14570098DCBA.sh: line 2:  5968 Segmentation fault: 11  /usr/local/bin/carthage copy-frameworks
Command /bin/sh failed with exit code 139
```

Carthage: ```0.7.5```
Xcode: ```Version 7.0 beta 5 (7A176x)```

What settings do I forget? Or does 7A176x cause it?

**Comment by ikesyo** [comment]
It might be that you are forgetting to add the following to “Input Files” of the “Run Script” phase:

```swift
$(SRCROOT)/Carthage/Build/iOS/Result.framework
$(SRCROOT)/Carthage/Build/iOS/ReactiveCocoa.framework
```

The crash case should be already fixed in Carthage [0.8](https://github.com/Carthage/Carthage/releases/tag/0.8) by #526.

**Comment by ikesyo** [comment]
Ah, `dyld: Library not loaded: @rpath/ReactiveCocoa.framework/ReactiveCocoa` means that the framework is not copied into your app bundle. You should drag & drop the framework to “Embedded Binaries” section, instead of “ Linked Frameworks and Libraries” section. If “Embed Frameworks” section exists in “Build Phases” tab, and your dependencies is listed in the phase, it should be OK.

**Comment by S-Shimotori** [comment]
I succeeded in building and running my project. Thank you!
