### ISSUE TITLE
watchOS targets not building

### ISSUE THREAD

**Issue by jurvis** [Carthage/Carthage#685]
running `carthage build --platform watchOS` produces the following error message:
```
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task failed with exit code 65
```

When I looked into the log files, the following is shown:
```
Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchos2.0

=== BUILD TARGET Alamofire watchOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/jurvistan/Library/Developer/Xcode/DerivedData/Alamofire-giuxdschbqsymscojpimobtahmgq/Build/Intermediates/Alamofire.build/all-product-headers.yaml

** BUILD SUCCEEDED **

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchsimulator2.0

=== BUILD TARGET Alamofire watchOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies
target 'Alamofire watchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform
```

Looks like it's trying to build itself twice?

Oddly enough, this problem doesn't exist for iOS or OS X. Only after submitting this issue on Alamofire (https://github.com/Alamofire/Alamofire/issues/689), did I realise it also happens for all the other libraries I attempt to build on the watchOS target. Any idea what might be the reason? 

Thanks!

**Comment by mdiep** [comment]
> `target 'Alamofire watchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform`

It seems like the targets you're trying to build aren't correctly configured. In the Alamofire/Alamofire#689 issue you linked, it was noted that the "swift-2.0" Alamofire branch works.

If you believe there's a carthage bug, can you provide a `Cartfile` that reproduces the issue and the version from `carthage version`?

**Comment by jurvis** [comment]
@mdiep 
I've since been able to figure out the issue - turns out it's not a problem with Carthage or any of the libraries. I noticed from the log above that it kept failing when trying to build for the simulator, then I found out watch simulator was somehow missing from Xcode. Recreated my simulators and that solved it!

Thanks for the help!

**Comment by ricburton** [comment]
@jurvis how did you recreate the simulators? I’ve tried a few methods but I am still getting the error. Thanks!

**Comment by emaloney** [comment]
I was able to get a watchOS simulator installed by creating a dummy watchOS app project in Xcode, and then running the WatchKit app with an "iPhone 6 + Apple Watch" simulator run destination.

**Comment by jurvis** [comment]
@ricburton sorry for the late reply, you can recreate the simulators manually in Xcode by going to Window > Devices, delete all the simulators and create them with the tiny + button at the bottom left.

Alternatively (also my most preferred way), will be to user [Snapshot](https://github.com/KrauseFx/snapshot) and just run `snapshot reset_simulators` in Terminal :)
