### ISSUE TITLE
Strip exited with 1

### ISSUE THREAD

**Issue by blender** [Carthage/Carthage#687]
I am using carthage 0.8 and trying to get dSYMs from frameworks I build with Carthage into my app's dSYM folder.

As suggested on in Carthage README.md I have added a Copy Phase to 'Products Dir' in my build steps.

Unfortunately this does not work for release builds where I have COPY_PHASE_STRIP = YES and
STRIP_INSTALLED_PRODUCT = YES in my build settings.

~~COPY_PHASE_STRIP = YES is the default value for Xcode > 6 for the release configuration.~~ Turning this off does not seems like a good idea to me. As far as I understand my application binary will not be stripped of debug symbols if I turn this off.

So seems to my like dSYM have to be packed manually in a second step. Can anyone confirm this?

**Comment by magnus-staberg** [comment]
Same here. COPY_PHASE_STRIP must be turned off.

**Comment by blender** [comment]
@magnus-staberg Thanks for confirming.

Setting COPY_PHASE_STRIP = NO is not a viable option for me.
While COPY_PHASE_STRIP = NO does not apply for the executable you're building, it applies to everything you copy into your app. Third party frameworks for example. See this [thread](http://lists.apple.com/archives/xcode-users/2009/Aug/msg00432.html).

I solved this buy wrapping carthage in a shell script and copying the dSYMs over myself.
See this gist [https://gist.github.com/blender/e5254ed20f228796f6eb](https://gist.github.com/blender/e5254ed20f228796f6eb). This is works for binaries attaches to git tags but it should be easy enough to adapt for the normal build process.

Maybe this problem should be addressed in carthage itself?

**Comment by bgerstle** [comment]
Getting this too. What about Carthage dependencies in Release mode (`--configuration Release`)? Shouldn't that remove any debug symbols, obviating the `COPY_PHASE_STRIP`?

**Comment by bgerstle** [comment]
Now when I disable `COPY_PHASE_STRIP`, I get:

```
PBXCp Carthage/Build/iOS/OMGHTTPURLRQ.framework.dSYM Build/Intermediates/ArchiveIntermediates/Wikipedia/BuildProductsPath/Release-iphoneos/OMGHTTPURLRQ.framework.dSYM
    cd /Users/bgerstle/Code/wikipedia-ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -bitcode-strip all -bitcode-strip-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip -resolve-src-symlinks /Users/bgerstle/Code/wikipedia-ios/Carthage/Build/iOS/OMGHTTPURLRQ.framework.dSYM /Users/bgerstle/Code/wikipedia-ios/Build/Intermediates/ArchiveIntermediates/Wikipedia/BuildProductsPath/Release-iphoneos

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip /Users/bgerstle/Code/wikipedia-ios/Carthage/Build/iOS/OMGHTTPURLRQ.framework.dSYM/Contents/Resources/DWARF/OMGHTTPURLRQ -r -o /Users/bgerstle/Code/wikipedia-ios/Build/Intermediates/ArchiveIntermediates/Wikipedia/BuildProductsPath/Release-iphoneos/OMGHTTPURLRQ.framework.dSYM/Contents/Resources/DWARF/OMGHTTPURLRQ
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip: string table not at the end of the file (can't be processed) in file: /Users/bgerstle/Code/wikipedia-ios/Carthage/Build/iOS/OMGHTTPURLRQ.framework.dSYM/Contents/Resources/DWARF/OMGHTTPURLRQ (for architecture i386)
error: bitcode_strip /Users/bgerstle/Code/wikipedia-ios/Carthage/Build/iOS/OMGHTTPURLRQ.framework.dSYM/Contents/Resources/DWARF/OMGHTTPURLRQ:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip exited with 1
```

**Comment by bgerstle** [comment]
Ah my bad, I had **Code Sign On Copy** enabled on the dSYM copy phase. Disabling that fixed the issue!

**Comment by ikesyo** [comment]
I believe this is suppressed by https://github.com/Carthage/Carthage/pull/1023.

**Comment by t0rst** [comment]
To COPY_PHASE_STRIP, or not, is a separate decision, so instead of using a copy files phase, make it work both ways with a run script phase as follows...

```bash
#!/bin/bash
if [ ${COPY_PHASE_STRIP} -ne 0 ] ; then
    exit 0
fi

for var in ${!SCRIPT_INPUT_FILE_*} ; do
    path="${!var}"
    if [ -e "${path}" ] ; then
        cp -r "${path}" "${BUILT_PRODUCTS_DIR}"
    fi
done
```

...and add your dSYMs paths as input files to the script; Xcode passes them via env vars `SCRIPT_INPUT_FILE_COUNT`, `SCRIPT_INPUT_FILE_1`, etc.
