### ISSUE TITLE
Project "Project.xcodeproj" has no shared schemes

### ISSUE THREAD

**Issue by basvankuijck** [Carthage/Carthage#691]
When i run `carthage build --no-skip-current` I get:

```
*** xcodebuild output can be found in /var/folders/cg/151bxykj4q9g1p_qpmk9pl300000gn/T/carthage-xcodebuild.r6bFvH.log
Project "Project.xcodeproj" has no shared schemes
```
The log (carthage-xcodebuild.r6bFvH.log) is empty (ofcourse)

Carthage version `0.6.3`
Xcode `6.4`

The thing is that the "Project.xcodeproj" actually has only 1 scheme and it is checked as "Shared".
So I don't know how else to fix this.

I tried removing the scheme and re-adding it, I even tried removing the project and starting from scratch. Same result...

**UPDATE:**
I installed both Xcode7beta5 and Xcode6.4 on my machine.
If I switch (with `xcode-select`) to Xcode7 the `carthage build --no-skip-current` doesn't return the error. But the build fails, because of swift 2.0

But if I switch to Xcode6.4 through `xcode-select` I stil get "no shared schemes" error.
Eventhough I actually created the project with Xcode6.4

Even creating a complete empty (xcode6.4) framework project and turning on `Shared` for the scheme will still return the "no shared schemes" error

**Comment by mdiep** [comment]
That's a pretty old version of Carthage. Can you try with a newer version and report back?

**Comment by basvankuijck** [comment]
Hmm strange.
I installed it through homebrew, but brew said my version was up to date.
Didn't bother to double check that.
Now I installed it through the pkg and everything works fine
