### ISSUE TITLE
Question: Cartfile.private?

### ISSUE THREAD

**Issue by bruceflowers** [Carthage/Carthage#693]
I may have missed something in the docs; if so, apologies in advance - but what's the intention of the file Cartfile.private?

**Comment by ikesyo** [comment]
Did you see [the section in Artifacts.md](https://github.com/Carthage/Carthage/blob/9d1a67f47c7231eb2f1c33a719634ec4281b65c1/Documentation/Artifacts.md#cartfileprivate)?

**Comment by bruceflowers** [comment]
Thanks - did not see that earlier. Wondering: does this mean that those artifacts get built into the .framework bundle for the dependent library?

**Comment by ikesyo** [comment]
> Wondering: does this mean that those artifacts get built into the .framework bundle for the dependent library?

My understanding is no, in testing frameworks case those are only needed for building the test target, not needed for bulding its main framework target.

**Comment by rob-nash** [comment]
Dependencies that don't need to be declared in the parent? How is this possible? How does Carthage do it?

**Comment by andersio** [comment]
Test dependencies in general. Say if you are depending on ReactiveCocoa, Carthage doesn't need to pull Nimble and Quick at all because these are meant for tests of ReactiveCocoa only, but not the final products.

**Comment by rob-nash** [comment]
Hi @andersio yes I understand the concept I just don't know how to do it in code. Are you moving one framework inside another ?

**Comment by andersio** [comment]
No. It is just like using any other framework, but only linked by test targets.
