### ISSUE TITLE
`carthage update` not installing frameworks

### ISSUE THREAD

**Issue by justinmakaila** [Carthage/Carthage#698]
Hey,
I'm noticing a strange bug on `0.8.0`. When attempting to run `carthage update`, all dependencies are fetched and "checked out", but only 2 of 4 are built.

My `Carthage/Checkouts` dir is empty, aside from `Alamofire` and `OHHTTPStubs`.

Cartfile:
```
github "Alamofire/Alamofire"
```

Cartfile.private:
```
github "Quick/Quick" ~> 0.3.1
github "Quick/Nimble"
github "AliSoftware/OHHTTPStubs"
```

Cartfile.resolved
```
github "Alamofire/Alamofire" "1.3.1"
github "Quick/Nimble" "v1.0.0"
github "AliSoftware/OHHTTPStubs" "4.2.0"
github "Quick/Quick" "v0.3.1"
```
`carthage update` Output:
```
j ~/W/S/Moya> carthage update
*** Fetching OHHTTPStubs
*** Fetching Nimble
*** Fetching Quick
*** Fetching Alamofire
*** Checking out Alamofire at "1.3.1"
*** Downloading Quick at "v0.3.1"
*** Checking out OHHTTPStubs at "4.2.0"
*** Downloading Nimble at "Nimble v1.0.0 Final"
*** xcodebuild output can be found in /var/folders/vl/66bmt4h568z1w4fvyjlvmsdw0000gn/T/carthage-xcodebuild.ZIYZvE.log
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "OHHTTPStubs Mac Framework" in OHHTTPStubs.xcworkspace
*** Building scheme "OHHTTPStubs iOS Framework" in OHHTTPStubs.xcworkspace
j ~/W/S/Moya> carthage version
0.8.0
```

This has been blocking me for a few days, any advice?

**Comment by mdiep** [comment]
The `Carthage/Checkouts` directory doesn't include Quick or Nimble because binary releases were downloaded for those repositories from GitHub. If you look in `Carthage/Build/`, you should see `Quick.framework` and `Nimble.framework`.

If you don't want to use binary releases, you can use the `--no-use-binaries` flag.

**Comment by justinmakaila** [comment]
@mdiep Word, thanks! I feel a bit ridiculous for not checking the `Build` dir, but things happen.
