### ISSUE TITLE
I can't add frameworks for test target (Xcode 7 beta 5)

### ISSUE THREAD

**Issue by mstfy** [Carthage/Carthage#700]
Hello. I installed Quick framework with carthage 8.0. But in testing test fails and and prints out this to the console. Any idea?

    The bundle “SampleTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
    2015-08-20 23:52:29.929 Sample[13703:286251] (dlopen_preflight(/Users/mustafayusuf/Library/Developer/Xcode/DerivedData/Sample-ftrqmapojmxoukaofbbeykstcpry/Build/Products/Debug-iphonesimulator/SampleTests.xctest/SampleTests): Library not loaded: @rpath/libswiftSecurity.dylib
      Referenced from: /Users/mustafayusuf/Library/Developer/Xcode/DerivedData/Sample-ftrqmapojmxoukaofbbeykstcpry/Build/Products/Debug-iphonesimulator/SampleTests.xctest/Frameworks/Quick.framework/Quick
      Reason: image not found)

**Comment by mdiep** [comment]
I _think_ you might need to add a swift file to your test target to get Quick to work.

**Comment by furyu-ikeda-sho** [comment]
> I think you might need to add a swift file to your test target to get Quick to work.

Or setting the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting to “Yes” might help.

**Comment by ikesyo** [comment]
> I think you might need to add a swift file to your test target to get Quick to work.

Or setting the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting to “Yes” might help.

**Comment by mstfy** [comment]
@mdiep There is already one swift file that comes with testing template.

**Comment by mdiep** [comment]
I'm not sure. It sounds like you have a project configuration issue. Maybe try some of [these](http://stackoverflow.com/questions/26024100/dyld-library-not-loaded-rpath-libswiftcore-dylib) ideas.

**Comment by zirinisp** [comment]
Added "$(PROJECT_DIR)/Carthage/Build/iOS" to your test target Runpath Search Path and it worked
