### ISSUE TITLE
Carthage Archive

### ISSUE THREAD

**Issue by calebd** [Carthage/Carthage#710]
If I want to add a precompiled framework to a release but my library has carthage-installed dependencies, do I include those in my `.framework.zip`? Same question applies to the generated `dSYM` files.

Put another way, should I simply zip my `Build` folder or should I remove everything that isn't the target framework itself?

**Comment by mdiep** [comment]
If you run `carthage archive FrameworkName`, Carthage will create a `.framework.zip` with the correct files for you.

But it should include only the target framework and its `dSYM`.

**Comment by calebd** [comment]
Awesome, I didn't know about that. Thanks!
