### ISSUE TITLE
Build fails for architecture watchsimulator2.0

### ISSUE THREAD

**Issue by bentrengrove** [Carthage/Carthage#716]
I am trying to build my framework which includes a watchos2.0 target. The framework is private so unfortunately I can't share it. I have Xcode 7 Beta 6 selected as my current installation. The build fails with the following error

```
Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchsimulator2.0

=== BUILD TARGET BOMAPIClientWatch OF PROJECT BOMAPIClient WITH CONFIGURATION Release ===

Check dependencies
target 'BOMAPIClientWatch' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform

** BUILD FAILED **
```

Bitcode is enabled in Xcode though.
![screen shot 2015-08-26 at 4 26 55 pm](https://cloud.githubusercontent.com/assets/19445/9497945/4b37d36c-4c0f-11e5-9fe6-aed1c0d40eac.png)
![screen shot 2015-08-26 at 4 29 21 pm](https://cloud.githubusercontent.com/assets/19445/9498009/a41fbc2e-4c0f-11e5-9686-4baec510ebdb.png)

The phone target builds fine. Also building with xcodebuild succeeds as well.

Does anyone have any ideas?

**Comment by mdiep** [comment]
What's the output from `carthage`? Maybe it's building it through a different project or workspace than you are?

**Comment by bentrengrove** [comment]
```
*** Building scheme "BOMAPIClientWatch" in BOMAPIClient.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

Is there anyway to get carthage to print what xcodebuild options its using? I have tried every combination I can think of and they all build.

**Comment by kazmasaurus** [comment]
Might you be running into the same problem as #685? I just finished chasing this same issue, and found I had the same simulator issue [he mentions](https://github.com/Carthage/Carthage/issues/685#issuecomment-131670394)

**Comment by bentrengrove** [comment]
This was my problem! Thank you so much.

**Comment by MSchmidt** [comment]
And how do you recreate the simulator @kazmasaurus & @bentrengrove? I have no issues with the the watch simulator, but get the same error.

**Comment by spenrose** [comment]
I am having same problem with SwiftyJSON but Alamofire will build the watch framework.

Any other ideas?

**Comment by MSchmidt** [comment]
@spenrose try my fork at MSchmidt/SwiftyJSON (master). That should work for now.
