### ISSUE TITLE
Sort Cartfile.resolved

### ISSUE THREAD

**Issue by schwa** [Carthage/Carthage#717]
Any operation that outputs Cartfile.resolved should save it using a line based sort.

This would really help with git diffs and merging. Currently the order of the file seems to be pretty arbitrary and random.

**Comment by mdiep** [comment]
The current order only serves to specify the build order, to ensure that dependencies are built first. But we could improve the sorting to make it stable based on the name.

**Comment by schwa** [comment]
Ah ok - didn't realise it was ordered at all

Would manually sorts cause problems?

**Comment by mdiep** [comment]
If you change the order so a framework is built before its dependency, it will cause problems.

**Comment by schwa** [comment]
So one problem with relying on the order of this to order dependencies is that it makes it _very_ tricky to merge this file while preserving the "correct" order. Something to be aware of. Maybe best to abandon the preservation of build order in this file and regenerate the order as needed on the fly?

**Comment by mdiep** [comment]
> Maybe best to abandon the preservation of build order in this file and regenerate the order as needed on the fly?

That sounds like a good idea to me. :+1:

**Comment by mdiep** [comment]
#974 made the order of `Cartfile.resolved` unimportant. But we're going to wait sometime before generating `Cartfile.resolved` in lexicographical order so that we maintain compatibility between recent versions of Carthage.

**Comment by schwa** [comment]
Wonderful. Thank you
