### ISSUE TITLE
Carthage is including public header file that is not even included in the framework target

### ISSUE THREAD

**Issue by simX** [Carthage/Carthage#718]
This is very similar to #463 but isn't quite the same.

I have a number of .m and .h files that are not included in my framework target in my project file.  When I build normally using the project file, these header files are not included in the Headers folder in the built framework.

However, when built via Carthage, these header files are still be including in the Headers folder even though the .m file isn't even being included and compiled in the binary?!  That is really weird.

I've made sure to check that the commit in Cartfile.resolved is pinned to the correct commit from my GitHub repository.  I've also cleared out all DerivedData from the project and to clear out all Carthage cache (~/Library/Caches/carthage and ~/Library/Caches/org.carthage.CarthageKit).

**Comment by mdiep** [comment]
If you build your framework with `xcodebuild` on the command line, does it include those headers?

**Comment by simX** [comment]
Sorry for the delay.  If I build with `xcodebuild`, the extra headers are NOT included.  So, yeah, it seems to be something specific to how Carthage is building it.

**Comment by mdiep** [comment]
Is this a public repository? What's the project structure? Is there an `xcodeproj`? An `xcworkspace`? Where is the scheme shared from? There's not much detail here for anyone to be able to figure out the issue.

**Comment by skunkworks** [comment]
I'm seeing the same issue with the [Braintree iOS SDK](https://github.com/braintree/braintree_ios). The key seems to be that the Cartfile I'm using is pointed to the local file system:

`git "file:///Users/rishin/bt/braintree-ios" "master"`

When I run `carthage update`, the BraintreeCore framework ends up with a bunch of outdated header files that are no longer part of the `master` branch.

When the Cartfile uses our GitHub repo, it works fine:

`github "braintree/braintree_ios"`

**Comment by mdiep** [comment]
> ends up with a bunch of outdated header files that are no longer part of the master branch.

They're no longer a part of the local master, the remote master, or both?

**Comment by skunkworks** [comment]
Both. Their timestamps are two months old.

**Comment by neilpa** [comment]
If it's from a local repo their may be stale stuff in DerivedData that's somehow getting pulled in.

**Comment by skunkworks** [comment]
Tried cleaning out `~/Library/Caches/org.carthage.CarthageKit/dependencies` and `Carthage/Build`, and that didn't work. However, cleaning out `~/Library/Developer/Xcode/DerivedData` did the trick. I also tried cleaning out the DerivedData for the project itself, but it wasn't until I blew everything away from DerivedData that it worked.

Thanks!

**Comment by mdiep** [comment]
Ah, yup! This is an Xcode thing. Xcode won't remove removed files from products—you need to clean the build in order to get rid of them.
