### ISSUE TITLE
Select specific scheme per dependency in Cartfile

### ISSUE THREAD

**Issue by lukescott** [Carthage/Carthage#728]
I'm using [SQLite.swift](https://github.com/stephencelis/SQLite.swift) in my project. It has two targets: SQLite and SQLiteCipher. First one builds with iOS's sqlite and the ladder build it itself, both end up creating the same framework, one clobbering the other. They also take a long time to build individually, which can be frustrating. I only want to build what I'm using.

Now the immediate solution that the author is looking into is separating SQLiteCipher into another repo. But this situation can come up for any number of reasons: You only want one build scheme.

How about something like this:

```
github https://github.com/stephencelis/SQLite.swift "master" "SQLite"
```
```
[location] [url] [version/branch] [scheme,...]
```

Choosing a theme could also be used to select platform since those are scheme based as well, right? Unless it's a universal framework, in which case the build only happens once anyway, correct?

**Comment by kukushi** [comment]
+1.
No every scheme is needed.

**Comment by torstenlehmann** [comment]
+1

Especially useful if a scheme's platform is not supported. E.g. Xcode 7.0 does not support platforms of Xcode 7.1. A tvOS scheme defaults to "My Mac", which leads to failing builds even if I use `--platform mac`.

**Comment by mdiep** [comment]
I don't think Carthage will ever add support for this. Recent platform additions notwithstanding, this isn't something you should need to do.

**Comment by lukescott** [comment]
@mdiep 
> this isn't something you should need to do
In most cases perhaps. But when you have different types of builds beyond platform (a different set of build flags), Carthage is impossible to use when more than one scheme build to the same location causing one the globber the other. Is it so unreasonable to specify in the Cartfile which scheme to resolve to?

It's also kind of silly to have to specify the platform on the command line every time. But I can specify it, so I just move on. But in the above case there is nothing I can do without expecting the author to split his project up.

**Comment by mdiep** [comment]
> In most cases perhaps. But when you have different types of builds beyond platform (a different set of build flags), Carthage is impossible to use when more than one scheme build to the same location causing one to globber the other. Is it so unreasonable to specify in the Cartfile which scheme to resolve to?

The issue is that it (a) adds complexity to Carthage and (b) encourages framework developers to make bad choices. It's easier and simpler for framework developers to use a different `.framework` name if they need to do something like SQLite.swift's Cipher support.

> It's also kind of silly to have to specify the platform on the command line every time.

#356 is open to discuss this.
