### ISSUE TITLE
Adding run script to build phases generates "Shell Script Invocation Error"

### ISSUE THREAD

**Issue by andrewcl** [Carthage/Carthage#732]
Adding in a new Run Script for libraries built with Carthage generates a "Shell Script Invocation Error".
```Bash
Command /bin/sh failed with exit code 1
```

Removing the Run Script and then building does not generate any errors. The README markdown recommends adding in a Run Script in order to avoid an App Store submission bug so I'm reluctant to continue without adding the Run Script

Is anyone seeing this, and does anyone have any suggestions regarding how to resolve it?

**bold Notes:**
* ```Cartfile:```
  * ```github "Alamofire/Alamofire```
  * ```github "SwiftyJSON/SwiftyJSON" >= 2.1.2```
* ```Cartfile.resolved:```
  * ```github "Alamofire/Alamofire" "1.3.1"``` 
  * ```github "SwiftyJSON/SwiftyJSON" "2.2.1```
* Device Information
  * Running Mac OS X 10.10.5 (14F27)
  * Using Xcode 6.4 (6E35b) and Carthage 0.8.0.
  * MacBook Pro (Retina, 15-inch, Mid 2014)

**Comment by jlawton** [comment]
What's the actual script you're running?

**Comment by andrewcl** [comment]
It's the one listed in the README: ```/usr/local/bin/carthage copy-frameworks```

**Comment by ikesyo** [comment]
Are you really adding the frameworks' paths to “Input Files”?

**Comment by andrewcl** [comment]
So far as I know, yes
![screen shot 2015-09-04 at 2 16 43 pm](https://cloud.githubusercontent.com/assets/6520870/9691302/a09a9d4c-530f-11e5-9a80-bdee87037340.png)

**Comment by mdiep** [comment]
Is there any more output if you navigate to the Report Navigator (Cmd-8), click on the build, and expand the failure?

**Comment by andrewcl** [comment]
Yes. Here we go: 
```Failed to write to /Users/andrewliu/Library/Developer/Xcode/DerivedData/Evaluate-dhcdekogvzvqnfememkngemquzgz/Build/Products/Debug-iphonesimulator/Evaluate.app/Frameworks/Alamofire.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “Alamofire.framework” couldn’t be opened because there is no such file." UserInfo=0x7fce3a40fcd0 {NSFilePath=/Users/andrewliu/Developer/Evaluate/Evaluate/Carthage/Build/iOS/Alamofire.framework, NSUnderlyingError=0x7fce3a40fb20 "The operation couldn’t be completed. No such file or directory"}```

**Comment by ikesyo** [comment]
The reason is clearly in the log: `"The file “Alamofire.framework” couldn’t be opened because there is no such file." UserInfo=0x7fce3a40fcd0 {NSFilePath=/Users/andrewliu/Developer/Evaluate/Evaluate/Carthage/Build/iOS/Alamofire.framework, NSUnderlyingError=0x7fce3a40fb20 "The operation couldn’t be completed. No such file or directory"}`

You should examine/modify the path of the input files to meet your project/repository directory structure.

**Comment by MichaelMcGuire** [comment]
I hit this same issue.  I copy/pasted the exact path in the error and it appeared the file was there.  I ended up deleting the build script phase entirely and recreating it.  It worked after that.  My guess was that copy/pasting the initial Input File paths from the web may have either messed something up or perhaps I had a space somewhere that was affecting the output.  Either way, try recreating the Build Script phase and see if that helps.

**Comment by andrewcl** [comment]
Turns out @ikesyo was indeed correct. I was not running at the correct path and thus Xcode had no idea where the framework was. Thanks for your help!
