### ISSUE TITLE
Facebook SDK

### ISSUE THREAD

**Issue by lucasderraugh** [Carthage/Carthage#734]
I've added the facebook/facebook-ios-sdk github entry to my Cartfile, however I always get this as output:
```
*** Building scheme "Bolts" in FacebookSDK.xcworkspace
A shell task failed with exit code 1:
error: cannot parse the debug map for "/Users/username/Developer/Spring 2015/project/Carthage/Build/iOS/Bolts.framework/Bolts": The file was not recognized as a valid object file
```
Is there a way around this issue? Does it have something to do with Bolts being a submodule of the Facebook SDK? Thanks for the help.

**Comment by tomco** [comment]
+1 
Having the same problem. 

Also completely unsure why Carthage is compiling Bolts:
```
*** Building scheme "MacBolts" in FacebookSDK.xcworkspace
*** Building scheme "Bolts" in FacebookSDK.xcworkspace
```
Since when opening `FacebookSDK.xcworkspace` no shared scheme for Bolts can be found.

**Comment by collindonnell** [comment]
Also seeing this exact same issue.

**Comment by nathanhosselton** [comment]
This is still an issue in 0.9.2 (in my case I am only building Bolts, not the entire Facebook SDK). Using xcodebuild works fine. So it seems to be an issue with Carthage even though Bolts is (as far as I know) the only framework currently exposing the issue.

**Comment by nathanhosselton** [comment]
The "Bolts" file which is the point of failure is a binary file that is also generated (without issue) by the Mac version of Bolts. I'm not sure what the purpose of these files are or what specifically is generating them. I have mentioned this in the open issue at https://github.com/BoltsFramework/Bolts-iOS/issues/152.

**Comment by lucasderraugh** [comment]
Looking into it more, it comes down to the fact that Bolts is a static library, not dynamic. I'm going to close this as a Carthage issue as it is not. [Bolts Issue](https://github.com/BoltsFramework/Bolts-iOS/issues/152)

**Comment by sirvine** [comment]
FYI — It looks like Bolts is Carthage-ready now (https://github.com/BoltsFramework/Bolts-iOS/issues/152#issuecomment-167904234), but the FB SDK does not seem to be.

**Comment by fatuhoku** [comment]
What's the latest on this?  Will the FBSDK ever be manageable by Carthage?

**Comment by mdiep** [comment]
Can you open a new issue with information about what you're seeing? The specific issue here seems to have been addressed.

**Comment by jamesone** [comment]
Any update on the FBSDK setup with carthage?
