### ISSUE TITLE
What exactly is the process for creating a Framework that is composed of other Frameworks?

### ISSUE THREAD

**Issue by aventurella** [Carthage/Carthage#735]
Having read the docs on the README, and spent the last 2 days trying variations of said docs, it's clear to me I am missing something.

I execute `carthage update` as follows for my Framework with Frameworks:

`carthage update --use-ssh --no-use-binaries --platform ios`

I'm using a private repo, hence using ssh.

So it will build all of the other dependencies then fail for my framework with a `cannot find module`. Error.

So here's what I have tried:
- In all cases I am in a Workspace

1) **Linking the frameworks via Linked Frameworks and Libraries -> Add Other**
 
- This causes compile time errors in the Xcode build that it can't find the frameworks

2) **Dragging the xcodeproj files from Carthage/Checkouts/ into the workspace**

- The project will compile just fine in Xcode, but when I try to use Carthage to build it I get my `module not found1 error

3) **Using style 1 above, I have tried including a copy files build phase which includes the frameworks I need. aka embedding the frameworks in the framework.**

- This fails during the Xcode build.

4) **Using style #2 above, create a Run Script phase that uses carthage copy-frameworks**

- This fails

5) **[!! APPEARS TO WORK !!] Using style #2 above, I amend the `Framework Search Paths` of the final framework project with: `$(SRCROOT)/../Carthage/Build/iOS`**

- This appears to work! Is this always required when making a framework that uses other carthage built frameworks? `ReactiveCocoa` does not appear to have this and it seems to work just fine.

- I just added this on my Framework that was failing however, and it was still failing. So I built a new xcworkspace and moved all my code over and added this and it works.

I have done numerous minor variations of all of these as well, each failing. So what is EXACTLY the way this is supposed to be done? Every time I run my attempts I clear my derived data, clear my Carthage/ directory AND clear my Carthage Cache in case something in there was interfering. 

Anyway, I would really like to know the community approved way to do this. I enjoy using carthage a bunch and it's clear to me that I am just missing some obvious in all of this that I think a quick answer might be able to help me with. I know whatever it is has to be related to my own ignorance about something with xcode or something with carthage.

I see in this answer that `FRAMEWORK_SEARCH_PATHS` is indeed important:

http://stackoverflow.com/questions/31106411/no-such-module-on-xcode-7-beta-2

But something like ReactiveCocoa, which also builds with Carthage, does not have this set at all, even though Carthage checks out and builds `Box` and `Result`. 

I even reviewed, copied, and included the `xcconfigs` from here https://github.com/jspahrsummers/xcconfigs

How does `ReactiveCocoa` locate `Box` and `Result` during it's Carthage build?

**Comment by mdiep** [comment]
ReactiveCocoa uses submodules and then adds the `xcodeproj`s to its `xcworkspace`. Add a framework search path also works, as you've discovered. There's some more detail on this in #678.

I do think that Carthage needs to clarify what the recommended setup is in its documentation. It should maybe also take some steps to make this easier for framework authors.

Does that answer your question?
