### ISSUE TITLE
How to avoid rebuilding of the frameworks in /Build folder after adding a new one?

### ISSUE THREAD

**Issue by AlexanderKaraberov** [Carthage/Carthage#736]
Are there any ways to tell `Carthage` not to build already fetched frameworks if there wasn't any updates? Because now after adding any new framework to my `Cartfile` and running `carthage update`  it also rebuilds already builded ones and it takes additional time. May we can optimise this process in some way?

**Comment by neilpa** [comment]
See #218

**Comment by chrisco314** [comment]
@neilpa, @AlexanderKaraberov:  Is this not a separate issue?  #218 seems to be directed at filtering frameworks that may have changed, but this question is asking how to avoid rebuilding dependencies that have not changed at all.  Am I missing something?

**Comment by AlexanderKaraberov** [comment]
@chrisco314  I have already asked about the status in another issue:
https://github.com/Carthage/Carthage/issues/610#issuecomment-138633491
You can see an answer. Also the status of it here: https://github.com/Carthage/Carthage/pull/618
May be I will begin to work on this feature if there won't be any progress.
