### ISSUE TITLE
Replace `carthage copy-frameworks` with a very small shell script…

### ISSUE THREAD

**Issue by schwa** [Carthage/Carthage#741]
We use Travis CI with our (freshly ported to Swift 2/Xcode 7) iOS app. Our travis script looks a little like:

```
osx_image: xcode7

before_script:
- brew update
- brew outdated xctool || brew upgrade xctool
- brew install carthage
```

However carthage cannot compile and build with Xcode 7 and our app obviously cannot compile with Xcode 6.4 any more. And travis (and probably most CI) isn't able to switch between 7 and 6 on the fly.

The only portion of carthage required by the build system currently is `carthage copy-frameworks` - to speed up development (amongst other reasons) the .frameworks built by Carthage are in git…

So I suggest replacing `carthage copy-frameworks` with a (presumably) very small shell script that duplicates carthage's functionality.

An additional benefit to this is anyone consuming a project, like ours, that has binary frameworks in .git _could_ distribute the shell script with the xcodeproj. This would simplify the initial setup of the project for our other devs (from "go install Xcode 6, then install brew, then go install carthage…", just open this project in Xcode 7).

Anyway - another road bump in the schizophrenic Xcode 6.4/Xcode 7 world we live in now.

**Comment by swizzlr** [comment]
Totally agree, but some workarounds:

1. I think Travis keeps regular Xcode sitting alongside;
2. For Travis I've been brew installing it and it loads the prebuilt binary from homebrew? (I'm in the same situation so I'm surprised it's an issue.

**Comment by schwa** [comment]
Yeah - definitely hitting us.

I've tried building without the brew install phase and carthage copy-frameworks is puking on us… But if it's working for you it definitely is worth us investigating more.

I'm probably going to end up making the shell script anyways - it'll be useful to limit the dependency exposure…

**Comment by schwa** [comment]
Here's the "very small (python) script" we're now using:

```
__author__ = 'schwa'

import os
import subprocess
import re
import shutil

def main():

    valid_architectures = set(os.environ["VALID_ARCHS"].split(" "))
    input_file_count = int(os.environ["SCRIPT_INPUT_FILE_COUNT"])
    input_files = [os.environ["SCRIPT_INPUT_FILE_{}".format(index)] for index in range(0, input_file_count )]
    expanded_identity = os.environ["EXPANDED_CODE_SIGN_IDENTITY_NAME"]
    built_products_dir = os.environ["BUILT_PRODUCTS_DIR"]
    frameworks_folder_path = os.environ["FRAMEWORKS_FOLDER_PATH"]
    frameworks_path = os.path.join(built_products_dir, frameworks_folder_path)
    code_signing_allowed = os.environ["CODE_SIGNING_ALLOWED"] == "YES"

    for input_path in input_files:
        # We don't modify the input frameworks but rather the ones in the built products directory
        output_path = os.path.join(frameworks_path, os.path.split(input_path)[1])

        framework_name = os.path.splitext(os.path.split(input_path)[1])[0]

        print "# Copying framework {}".format(framework_name)
        shutil.copytree(input_path, output_path)

        framework_path = output_path

        if not code_signing_allowed:
            continue

        binary_path = os.path.join(framework_path, framework_name)


        # Find out what architectures the framework has
        output = subprocess.check_output(["/usr/bin/xcrun", "lipo", "-info", binary_path])
        match = re.match(r"^Architectures in the fat file: (.+) are: (.+)".format(binary_path), output)
        assert(match.groups()[0] == binary_path)
        architectures = set(match.groups()[1].strip().split(" "))

        # Produce a list of architectures that are not valid
        excluded_architectures = architectures.difference(valid_architectures)



        # Skip if all architectures are valid
        if not excluded_architectures:
            continue





        # For each invalid architecture strip it from framework
        for architecture in excluded_architectures:
            print "# Stripping {} from {}".format(architecture, framework_name)
            output = subprocess.check_output(["/usr/bin/xcrun", "lipo", "-remove", architecture, "-output", binary_path, binary_path])
            print output

        # Resign framework
        print "# Resigning {} with {}".format(framework_name, expanded_identity)
        result = subprocess.check_call(["/usr/bin/xcrun", "codesign", "--force", "--sign", expanded_identity, "--preserve-metadata=identifier,entitlements", binary_path])

if __name__ == "__main__":
    main()```

**Comment by swizzlr** [comment]
@schwa I think I would like to use this as I'd love to decouple the framework installation method from the build process.

Of note, and I just realized: you only need to call copy-frameworks for an app store build. I think on mine it's only calling copy-frameworks iff it's the App Store config. Otherwise it just plain copies them. It's only for app store validation that the stripping occurs.

**Comment by schwa** [comment]
You need to call copy frameworks for all targets. UNLESS you use a traditional copy phase in your non-appstore targets.

I think it's best to use the same phases for _all_ targets for consistency's sake.

**Comment by kballard** [comment]
As of Carthage 0.9.4 `copy-frameworks` now copies the relevant `bcsymbolmap` files for each copied framework (the `bcsymbolmap`s go into the built products directory). The file basenames are just the UUIDs from `dwarfdump -u`. You'll want to add that to your script as well.

**Comment by schwa** [comment]
Thanks @kballard, at the moment we disable bitcode for the project we're using this script with… But yeah that will be a problem. (Also the script above is somewhat out of date - other fixes were put in)

**Comment by ikesyo** [comment]
Carthage is pre-installed in Travis now and if you do `brew upgrade carthage` or `brew uninstall carthage && brew install carthage`, a prebuilt bottle will be downloaded and installed. Closing.
