### ISSUE TITLE
tvOS not supported

### ISSUE THREAD

**Issue by emaloney** [Carthage/Carthage#743]
I've got a project with tvOS support, but apparently Carthage has hard-coded platform support and the current version does not recognize tvOS.

Attempting to build a project containing tvOS support fails with the error:

*** Building scheme "CleanroomASL-tvOS" in CleanroomASL.xcodeproj
Parse error: unexpected SDK key "appletvos"

This can be tested by adding the following line to the `Cartfile`:

```
github "emaloney/CleanroomASL" == 1.3.0
```

and then running `carthage update` using the latest version of Carthage (0.8.0).

**Comment by furyu-ikeda-sho** [comment]
Could you watch #742?

**Comment by NachoSoto** [comment]
Yup, just implemented this there!

**Comment by emaloney** [comment]
Very cool, thanks a lot!

**Comment by ikesyo** [comment]
Closed by #742.
