### ISSUE TITLE
Carthage 0.8.0 asking for GitHub username/pass for public repos

### ISSUE THREAD

**Issue by alexbepple** [Carthage/Carthage#746]
This is basically the same issue as with 0.7.1: #447

The workaround described by @elliottsj still works: https://github.com/Carthage/Carthage/issues/447#issuecomment-100682109

**Comment by ikesyo** [comment]
Could you share your Cartfile and the console log?

**Comment by ikesyo** [comment]
And also the output of `git --version` and `xcodebuild -version`.

**Comment by alexbepple** [comment]
`Cartfile`:
```
github "Quick/Quick" ~> 0.3.0
github "Quick/Nimble" ~> 1.0.0
```

When I run `carthage update`:
```
*** Fetching Nimble
*** Fetching Quick
Username for 'https://github.com': Username for 'https://github.com': ^C
```

git version 2.2.2
Xcode 6.4
Build version 6E35b

**Comment by mdiep** [comment]
Have you checked that `carthage version` returns 0.8? There have been a few issues before where people installed one version with home-brew and another with the package installer.

**Comment by alexbepple** [comment]
I did not even download the pkg installer. Output of `carthage version`: `0.8.0`.

**Comment by mdiep** [comment]
What happens if you try to clone Quick with `git`?

**Comment by DenHeadless** [comment]
This happens on both 0.8.0 and 0.9.0 for me.

**Comment by alexbepple** [comment]
@mdiep Even with the git credential helper, `git clone https://github.com/Quick/Quick.git` succeeds.

**Comment by ikesyo** [comment]
@alexbepple The `GIT_TERMINAL_PROMPT=0` fix from #450 and #648 is [effective from Git 2.3](https://github.com/blog/1957-git-2-3-has-been-released), so you should update your Git version.

**Comment by alexbepple** [comment]
@ikesyo That helps. Thanks. I suggest that Carthage forces the user to update Git if it finds a version <2.3.

**Comment by neilpa** [comment]
It can't "force" users, but it should warn about the incompatibility.

**Comment by alexbepple** [comment]
It can force by quitting otherwise. ;)
