### ISSUE TITLE
Objective C missing .m files

### ISSUE THREAD

**Issue by eeekari** [Carthage/Carthage#750]
Hi - 
I'm trying to add the Meteor iOS framework:
github "martijnwalraven/meteor-ios"

This is a framework written in objective c and I need to modify some of its .m files for a project I'm working on, however there are no .m files included in the framework.
Are these files not included in the framework built by carthage by design or is there a way to modify implementation files when using carthage?

**Comment by mdiep** [comment]
The most common way to use Carthage is to use the built frameworks, which doesn't include the editable source code.

If you'd like to make changes that you include in your app, you should fork the framework and make your changes there. (And hopefully open a pull request!) If you'd just like to _try_ changes against your app, you can use `carthage checkout --use-submodules --no-build` and add the `xcodeproj` from the dependencies directly to your app's `xcodeproj`.

**Comment by eeekari** [comment]
Great - cheers mate
