### ISSUE TITLE
Scheme tvOS is not currently configured for the build action.

### ISSUE THREAD

**Issue by avalanched** [Carthage/Carthage#754]
My cartfile generates the following error on `0.9.1`

`Scheme Result-tvOS is not currently configured for the build action.`

cartfile:
```
github "Alamofire/Alamofire" >= 2.0
github "neilpa/Rex" "explicit-rac-dep"
```
resolved:
```
github "Alamofire/Alamofire" "2.0.0"
github "antitypical/Result" "0.6-beta.1"
github "ReactiveCocoa/ReactiveCocoa" "5e75726bf232b76b17169b3d9c9c64d1fd6bffbe"
github "neilpa/Rex" "bf1a994f330582179167cf325385eaf31177f040"
```

I'm not using any tvOS scheme in my project.
Seems that 0.8.0 doesn't experience that error: https://github.com/neilpa/Rex/issues/31#issuecomment-140203349

**Comment by NachoSoto** [comment]
Are you building with Xcode 7.0 or 7.1?
7.0 won't understand the `tvOS` scheme (which you can filter out by using the `--platform` setting)

**Comment by neilpa** [comment]
That's the problem, the `--platform ios` doesn't seem to be working when building with 7.0

**Comment by neilpa** [comment]
At least not on `0.9.1`. I was able to build on `0.8.0` just fine though.

**Comment by avalanched** [comment]
I indeed used the platform filter, was building with 7.0 GM

**Comment by NachoSoto** [comment]
> xcodebuild: error: Scheme Result-tvOS is not currently configured for the build action.

I wonder if `Carthage` is parsing all schemes before filtering for the specified platform/s, so failing early because Xcode 7.0 can't parse the `tvOS` scheme.

**Comment by ikesyo** [comment]
The situation seems to be similar to #704.

**Comment by mdiep** [comment]
I'm not seeing that, although I do get a puzzling error about Result-watchOS. :confused:

**Comment by ikesyo** [comment]
> although I do get a puzzling error about Result-watchOS.

That would be related to antitypical/Result#78.

**Comment by NachoSoto** [comment]
Okay I think I see the problem.
Xcode 7.0 is defaulting to "OSX" when it can't understand `tvOS` in the target settings:
<img width="923" alt="screen shot 2015-09-14 at 19 24 28" src="https://cloud.githubusercontent.com/assets/685609/9866349/493754d2-5b16-11e5-98b7-65f7c6dc2138.png">

So `Carthage` is picking it up...

**Comment by mdiep** [comment]
I'm not sure what to do about this. Does anyone have a good idea?

**Comment by ikesyo** [comment]
I'm not sure too...

Regarding to https://github.com/Carthage/Carthage/issues/754#issuecomment-140258114, if we use `--platform mac`, the following error appears:

```sh
xcodebuild: error: Failed to build project Result with scheme Result-tvOS.
	Reason: The run destination My Mac is not valid for Running the scheme 'Result-tvOS'.
A shell task failed with exit code 70:
xcodebuild: error: Failed to build project Result with scheme Result-tvOS.
	Reason: The run destination My Mac is not valid for Running the scheme 'Result-tvOS'.
```

**Comment by NachoSoto** [comment]
Right, this only happens when building for Mac (thus why I never saw this) because Xcode defaults the unknown platform to Mac...

We'll have to take the schemes out for now.

**Comment by ikesyo** [comment]
Regarding to the original error `Scheme Result-tvOS is not currently configured for the build action.`, that would happen when:

1. There is `Result-tvOS` _scheme_ in the project.
2. But `Result-tvOS` _target_ does not exist.

**Comment by avalanched** [comment]
Shouldn't carthage ignore shemes as well if the don't fall in to the platform filter?

**Comment by zhuhaow** [comment]
Maybe carthage can detect the target platform by Base SDK, it seems that the tvOS uses 'appletvos' and Xcode 7.0 is not changing it.

**Comment by mdiep** [comment]
This shouldn't be a problem with Xcode 7.1+.

**Comment by aterribili** [comment]
It's still happening on xCode 8.0 😢

**Comment by ikesyo** [comment]
@aterribili What you said is clearly the duplicate of #1542.
