### ISSUE TITLE
carthage copy-frameworks does not work for watchOS 2 target

### ISSUE THREAD

**Issue by MSchmidt** [Carthage/Carthage#755]
With Xcode 7 and watchOS 2 it's necessary to include frameworks built for watchOS inside the watchOS target. Unfortunately the copy-frameworks script fails for this target with ``no identity found`` as described here: https://github.com/Carthage/Carthage/issues/587

For successful submission to the App Store it is needed to use this script or something else that slims the frameworks down to the required release architectures only.

**Comment by NachoSoto** [comment]
Are you getting `Invalid segment Alignment` as well? I think that's due to something about `BITCODE` support. Did you try submitting without `BITCODE` enabled?

**Comment by ikesyo** [comment]
Bitcode is requird, not optional for watchOS 2 apps, so disabling it should not work.

**Comment by NachoSoto** [comment]
Oh good point.
I misread this actually, you're right @MSchmidt, frameworks need to be stripped for the `watchOS 2` target as well.

**Comment by MSchmidt** [comment]
Yes ``Invalid segment Alignment`` is what I get. Along with some other errors but they all come down to the same issue. As a short term fix I've built the needed frameworks myself in Xcode with the release-ARM configuration and copied them into my project just for App Store Submission.

**Comment by NachoSoto** [comment]
I'm not familiar with how `copy-frameworks` was implemented, but maybe someone in @Carthage/Carthage can shed some light?

**Comment by jurvis** [comment]
@MSchmidt seems like I'm facing the same issue as you. mind sharing how to build the frameworks manually in Xcode? Thanks!

**Comment by MSchmidt** [comment]
Sure no problem @jurvis - but keep in mind that this basically eliminates the whole point of Carthage :)

For each of your used Frameworks ($framework):
* open ``Carthage/Checkouts/$framework/$framework.xcodeproj``
* Change active scheme to ``$framework watchOS > watchOS Device`` (or name of currently connected iPhone)
* ``Product`` > ``Archive``
* go into your ``DerivedData`` folder (default is ``/Users/username/Library/Developer/Xcode/DerivedData``)
* within the derived data from your framework: ``./Build/Products/Release-watchos``
* copy ``$framework.framework`` to ``Carthage/Build/watchOS``

For your watchOS target use the frameworks as ``Embedded Binaries`` and you are good to go for App Store Submission. With this setup you cannot build for Watch Simulator anymore. Run ``carthage update`` to build simulator compatible versions of your frameworks again.

**Comment by jurvis** [comment]
@MSchmidt thanks! that worked perfectly! (had to open .xcodeworkspace instead for some reason else Release-watchos refused to build)

Right now I guess this temporary solution will have to do for submitting apps to the store. Thanks again :)

**Comment by frankrausch** [comment]
@MSchmidt Thanks for sharing your temporary solution! 
I had to turn off “include app symbols” to make it submit successfully: Xcode couldn’t find the `.bcsymbolmap` file even though I copied it (along with the dSYM package) to `/Carthage/Build/watchOS`.
Does anyone know how I can point Xcode to the `.bcsymbolmap` file so I can include the app symbols and keep getting crash reports?

**Comment by jurvis** [comment]
@frankrausch I had the same issue. Will be nice if someone who had this figured out can share their solution :)

**Comment by nickygerritsen** [comment]
I'm guessing this same issue will hold for tvOS frameworks right? I.e. we can not just embed the frameworks as normal but we need to strip them for iOS, tvOS and watchOS. Hope `copy-frameworks` can be modified to handle this :)

**Comment by MSchmidt** [comment]
Most likely the same situation for tvOS, yes. We need to strip them for the release architecture thought. Builds are already separated between iOS, tvOS and watchOS but always contain files for the simulator which is not allowed to submit to the App Store.

**Comment by MSchmidt** [comment]
Any news here? Is someone looking into this?

**Comment by carlossless** [comment]
+1

**Comment by ikesyo** [comment]
Fixed in #829.
