### ISSUE TITLE
Precompiled watchOS binaries result in crashes during checkout

### ISSUE THREAD

**Issue by erichoracek** [Carthage/Carthage#757]
Currently, the logic that copies binaries from an archive does not properly handle watchOS binaries, instead crashing when it encounters one with failures during the copy. It currently attempts to infer its platform from the architecture, but this fails as both watchOS and iOS architectures have a prefix of `arm`. See https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Project.swift#L406-L414

This currently affects the [ReactiveCocoa 4.0 alpha](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v4.0-alpha.1), but would likely affect any precompiled binaries that include both watchOS and iOS binaries.

cc @neilpa @NachoSoto

**Comment by erichoracek** [comment]
It would appear that the SDK of a framework is available within its `Info.plist`, for the key `CFBundleSupportedPlatforms`. For example, for in the ReactiveCocoa precompile binaries mentioned above it's:

- Mac: `MacOSX`
- iOS: `iPhoneOS`
- watchOS: `WatchOS`

This might be a better way to infer the platform of a precompiled binary, rather than the architecture.

**Comment by erichoracek** [comment]
Also, I should be able to take a stab at fixing this, if desired :+1:

**Comment by NachoSoto** [comment]
> It would appear that the SDK of a framework is available within its Info.plist, for the key CFBundleSupportedPlatforms. This might be a better way to infer the platform of a precompiled binary, rather than the architecture.

That makes a lot of sense to me :+1:

**Comment by mdiep** [comment]
:+1:
