### ISSUE TITLE
[Idea] carthage playground

### ISSUE THREAD

**Issue by izqui** [Carthage/Carthage#761]
Hi! 

I'm working on a HTTP framework for Swift and a really interesting way to let people try your framework is using a xCode Playground, this way they can play with the framework and get visual feedback as they change the code. 

For my library I custom made a [branch](http://github.com/izqui/taylor/tree/playground) that has a playground inside and a [build script](https://github.com/izqui/Taylor/blob/playground/setup.sh) for downloading the dependencies and building them. (The `.xcodeprojs` of the dependencies were previously added to the workspace) 

Then I got the idea of making a new command for carthage, `carthage playground` that could download and build your dependencies and then open a Playground file with the frameworks linked ([Apple way](https://developer.apple.com/library/ios/recipes/Playground_Help/Chapters/ImportingaFrameworkIntoaPlayground.html)).

The reason I opened this issue is that I'm not sure if you would like to see something like this integrated into Carthage, because it would make it more complicated.

If you think it is a good idea I can start working on it.

**Comment by mdiep** [comment]
I don't think this is a good fit for inclusion in `carthage` itself, but IMO it'd make a great standalone tool that utilizes Carthage!
