### ISSUE TITLE
Module Name Unavailable In Interface Builder

### ISSUE THREAD

**Issue by pazzer** [Carthage/Carthage#763]
Not a massive issue, but Interface Builder doesn't appear to offer any code completion hints when you're filling out the **Module** text field in the *Identify Inspector* for classes originating in frameworks imported via Carthage. The classes themselves are available, but when I tab into the next text field, there's no autocomplete at any point, and I have to manually type out the modules. Like I say, don't file it under critical, but it is a bit annoying.

**Comment by mdiep** [comment]
Is this unique to Carthage? Or is it an issue with any prebuilt framework that you add to an Xcode project?

**Comment by pazzer** [comment]
I had considered that possibility, but I've never added a prebuilt framework to a project before - I don't know how to do that manually.

**Comment by pazzer** [comment]
Okay, I figured out the source of the problem: If the framework includes a Swift extension you'll get behaviour I describe above. On reflection, it's actually a little more problematic than I thought, because in addition to losing code-complete, you also lose all access to the connections (outlets/actions) defined in the framework. Anyway, It's clearly nothing to do with Carthage, so I've filed a bug report with Apple.

**Comment by neilpa** [comment]
Care to share the radar?

**Comment by pazzer** [comment]
Happy to share, you'll just need to tell me how. I filed it using 'Apple Bug Reporter'; is there a way to link to the page, or do you want me to copy and paste the gist here?

**Comment by neilpa** [comment]
The original radar number and then a lot of people in the community dupe them at http://openradar.me/ so that people can publicly see them.

**Comment by mdiep** [comment]
> Anyway, It's clearly nothing to do with Carthage, so I've filed a bug report with Apple.

Thanks for figuring that out! I'll go ahead and close this issue then.

**Comment by towry** [comment]
Use cocoapods instead of Carthage fix my issue.

**Comment by danqing** [comment]
On top of what @jbg said, if you want to have `IBInspectable`s you too have to override them in your subclass.
