### ISSUE TITLE
Question: implementing tvOS support in a framework

### ISSUE THREAD

**Issue by bruceflowers** [Carthage/Carthage#764]
This is probably off topic here, but I haven't been able to find a straightforward walkthrough for it yet.

Does anyone here have pointers/links for how to add tvOS support to what currently happens to be an iOS framework project? My goal state would be to build it using Carthage.

**Comment by drekka** [comment]
I've built tvOS frameworks by simply adding a shared tvOS framework target. Having said that, I'm still experimenting to figure out the best way to handle frameworks in tvOS projects. It's complicated by the fact that tvOS apps seem to be able to use iOS frameworks, yet issue warnings about doing so. Further complicates are around frameworks (such as AFNetworking) which contain code which is incompatible with tvOS.

**Comment by bruceflowers** [comment]
@drekka  I ended up having to fork AFNetworking and add #if checks for tvOS. It didn't take much work actually, and seems to work well. Try it if you like: https://github.com/bruceflowers/AFNetworking/tree/tvOS-support

**Comment by drekka** [comment]
Thanks. We forked too. Just didn't add in the AFNetworking UI stuff as we don't need it. :-)
