### ISSUE TITLE
Potential issue with determining mutually incompatible requirements

### ISSUE THREAD

**Issue by paulyoung** [Carthage/Carthage#765]
I'm receiving the following message but I'm not sure how to approach it since `c704777e4b6d3a5c2a4778a36fca393ff94b1ffa` is a commit on the `td-swift-2` branch of Argo.

```
Could not pick a version for github "thoughtbot/Argo", due to mutually incompatible requirements:
	"c704777e4b6d3a5c2a4778a36fca393ff94b1ffa"
	"td-swift-2"
```

**Comment by paulyoung** [comment]
To clarify, `c704777e4b6d3a5c2a4778a36fca393ff94b1ffa` is the latest commit on the `td-swift-2` branch.

**Comment by neilpa** [comment]
This is a general problem with transitive, pre-release dependencies. Tagging alpha/beta releases can help some, but it still requires identity equality since there's no versions.

**Comment by neilpa** [comment]
> To clarify, c704777e4b6d3a5c2a4778a36fca393ff94b1ffa is the latest commit on the td-swift-2 branch.

So this could be made to work, but will break on the next commit to that branch so I'm not sure how valuable it is to fix this.

**Comment by paulyoung** [comment]
> This is a general problem with transitive, pre-release dependencies.

This makes sense, thanks for the reminder.

**Comment by neilpa** [comment]
The real (but hard to enforce) answer is framework authors shouldn't use branch names in their cartfiles. They need to use versions, tags are commit SHAs since those are immutable from the point of creation unlike a branch. The only time you should use a branch name is for app targets where it's guaranteed you're the top of the food chain.

**Comment by paulyoung** [comment]
> So this could be made to work, but will break on the next commit to that branch so I'm not sure how valuable it is to fix this.

I can see _some_ benefit since if this currently worked I wouldn't need to add a more permissive version in my `Cartfile` right now (`"c704777e4b6d3a5c2a4778a36fca393ff94b1ffa"` -> `"td-swift-2"`)

I agree with the limited benefit to this though so please feel free to keep this issue open or close it as you see fit.

Thanks again.

**Comment by paulyoung** [comment]
Completely agree with your comments.

**Comment by paulyoung** [comment]
FWIW, I think this who situation is a by-product of transitioning to Swift 2.0 and shouldn't be an issue much longer.

**Comment by neilpa** [comment]
For now, but it's likely to come back again at some point in the future. At a minimum, there should be clearly prescribed guidelines in the README. I hadn't given it much thought until recently when I discovered [I had made the same mistake](https://github.com/neilpa/Rex/issues/31).

**Comment by kballard** [comment]
> The real (but hard to enforce) answer is framework authors shouldn't use branch names in their cartfiles. 

I disagree.

Authors of *public* frameworks shouldn't do this. But Carthage can be used for private frameworks as well, where the author maintains complete control over the entire chain, and there it's reasonable to depend on branches like this. That's the case I have, where I depend on a private framework of mine, which itself depends on the `master` branch of another private framework.

**Comment by neilpa** [comment]
Sure, private frameworks have the same caveat I already called out for app targets

> The only time you should use a branch name is for app targets where it's guaranteed you're the top of the food chain.

But this discussion wasn't about private frameworks.

**Comment by kballard** [comment]
I just posted that because the existing conversation on this ticket makes it sound like this was being considered as not necessarily very important, and yet this issue turns out to be a breaking change in Carthage 0.12.
