### ISSUE TITLE
Permissions error under El Cap Beta 8

### ISSUE THREAD

**Issue by adly-holler** [Carthage/Carthage#767]
When using Carthage under the latest beta that dropped today, I get something like the error below. It might be related to the rootlessness under El Cap?

```
Failed to write to /Users/adly/Development/Tripstr/ios-three/Carthage/Build/iOS/ReactiveCocoa.framework: Error Domain=NSCocoaErrorDomain Code=513 "“ReactiveCocoa.framework” couldn’t be removed because you don’t have permission to access it." UserInfo={NSFilePath=/Users/adly/Development/Tripstr/ios-three/Carthage/Build/iOS/ReactiveCocoa.framework, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7f94a3725790 {Error Domain=NSPOSIXErrorDomain Code=66 "Directory not empty"}}
```

**Comment by almassapargali** [comment]
Seeing this under Yosemite. Exact same error.

**Comment by mdiep** [comment]
I don't think it's related to rootlessness. It sounds like you previously built the framework with different permissions. Can you try removing the directory or changing the permissions?

**Comment by adly-holler** [comment]
I tried removing the directory a couple of times but nothing worked except reverting to 0.8.0

**Comment by mdiep** [comment]
Can you share your `Cartfile` and the full output from whichever `carthage` command you're using?

**Comment by almassapargali** [comment]
I discovered that my issue was cause by ReactiveCocoa's archive, and this issue helped to resolve it: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2365

**Comment by adly-holler** [comment]
Ah! That must be the same issue. Thanks @almassapargali !
