### ISSUE TITLE
Please update home-brew formula for Carthage (still 0.8)

### ISSUE THREAD

**Issue by gunterhager** [Carthage/Carthage#769]
The homebrew formula for Carthage is still for the 0.8 version. It would be great if you could update it to the latest version of.

**Comment by tonyarnold** [comment]
It has been submitted: https://github.com/Homebrew/homebrew/pull/43884

**Comment by ikesyo** [comment]
This is already in progress: https://github.com/Homebrew/homebrew/pull/43884 and #766.

**Comment by gunterhager** [comment]
Cool, thanks. Didn't check homebrew's issues before submitting this. Hope this gets sorted out soon.

**Comment by guidomb** [comment]
@ikesyo The failing tests in #766 should be fixed with #770?

**Comment by ReDetection** [comment]
Sorry, what is the progress?

**Comment by mdiep** [comment]
I think we have the tests fixed to work on the sandboxed homebrew CI, but now we need to cut a release. I should be able to get to it on Tuesday.

**Comment by ReDetection** [comment]
Cool. Installed with `--HEAD` option until this will be done.

**Comment by guidomb** [comment]
I think that before cutting a new release [this](https://github.com/Carthage/Carthage/issues/776) should be fixed. Are there any other critical issues that should be fixed for `0.9.2`?

**Comment by mdiep** [comment]
I just released [0.9.2](https://github.com/Carthage/Carthage/releases/tag/0.9.2). :tada:

**Comment by guidomb** [comment]
Cool! Thanks @mdiep. I've just updated the homebrew release. Tests are failing now because travis uses xcode 7 to build. Now tying to figure out next steps with homebrew maintainers.

**Comment by mdiep** [comment]
It looks like we need to update to Swift 2 / Xcode 7 before releasing a homebrew build. :unamused:

**Comment by neilpa** [comment]
The Xcode 7 tooling debacle continues...

**Comment by jeeftor** [comment]
That would explain why i couldn't do a raw build of carthage ....

**Comment by yoichitgy** [comment]
I installed Carthage by .pkg to use in Travis, and my tests passed. The feature #766 added by @guidomb works great!

**.travis.yml**
```
before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.9.2/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - carthage bootstrap --verbose --no-use-binaries --use-submodules
```

**Comment by kballard** [comment]
Until such time as this is fixed, it might be nice to update the project README to indicate that the Homebrew version is out of date. My coworker didn't even realize he had an outdated version because he never checked the Releases tab.

**Comment by guidomb** [comment]
Either that or drop official support for homebrew. I personally decided not to use homebrew anymore to install carthage. GitHub releases and the `.pkg` is simpler and more reliable.

**Comment by guidomb** [comment]
The bad thing about not using homebrew is that you loose the ability to update and easily detect that you are running an outdated version. Nothing that cannot be solved with some bash scripting. I have some build scripts that I use in all my project and now I check if I am using the correct version of carthage for my project (defined in a project's config variable) everytime tests are run, project is built or bootstrapped.

https://github.com/guidomb/ios-scripts/blob/master/script/common/carthage

**Comment by kballard** [comment]
I don't suppose we could make the Homebrew package actually just install the .pkg?

Maybe as a Caskroom keg instead of a regular one?

**Comment by aexmachina** [comment]
I've just lost several days trying to get this issue resolved. It wasn't clear to me that Homebrew didn't have an up-to-date version of Carthage. I think that we need to make it _much_ clearer that Carthage is **completely broken** for CI if you use the version that's currently on Homebrew.

For anyone in the same position as me, the solution is to use the [current version from a .pkg installer](https://github.com/Carthage/Carthage/issues/769#issuecomment-143480298)

**Comment by bfontaine** [comment]
This can now be closed: https://github.com/Homebrew/homebrew/commit/c4e4043fb856741b117bed96d5cb37206713937b

**Comment by ikesyo** [comment]
@bfontaine Thank you for the update! Closing this now. :tada:
