### ISSUE TITLE
Copy Frameworks.sh

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#771]
If i have frameworks of frameworks etc do I only need the copy frameworks build task on my top level application that includes all the frameworks?  or do the frameworks themselves need to implement the script in their build process (assuming they have nested dependencies)

**Comment by mdiep** [comment]
I'm not sure that `copy-frameworks` will work with embedded frameworks. Carthage is designed to use top-level frameworks so that versions of those dependencies can be resolved in ways that meet the requirements for all dependencies.
