### ISSUE TITLE
Carthage does not handle several precompiled frameworks per release.

### ISSUE THREAD

**Issue by guidomb** [Carthage/Carthage#772]
In the case of having more than one target by platform therefor generating more than one framework. When the precompiled frameworks are attached to the release Carthage only downloads one of those frameworks instead of building it. Which is fine but the problem is that it does not build the remaining frameworks.

I am using several targets in a project because the library I am making optionally exposes and API that uses ReactiveCocoa. For those who don't want to use ReactiveCocoa they only have to include the main framework. For those who want the RectiveCocoa extensions they can include the second target that adds extensions to the classes to expose Signal based method.

I decided not to attach the precompiled binaries to the realease but I would like to do so to reduce general build time. Is this an issue that should be addresses or a design decission? I think the current behavior is inconsitent because it should either donwload all pre-compiled frameworks or build them all.

**Comment by neilpa** [comment]
The de-facto Carthage way is one framework per repo. Multiple frameworks can sort of work, but breaks transitive dependencies in cases like yours. You've now made ReactiveCocoa a dependency of the base framework even though it doesn't depend on RAC.

**Comment by guidomb** [comment]
@neilpa Yeah that is true and I am aware of that. I did this because the lib was using CocoaPods sub specs and I thought that having several targets / frameworks was the way to port it to Carthage. What is the equivalent of subspec for Carthage? Different projects?

**Comment by neilpa** [comment]
There isn't an equivalent concept in Carthage which is why I mentioned one framework per project/repo. I haven't used cocoa pods since they added dynamic framework support so I can't speak to how well subspecs work versus just making new projects. The latter being more compatible with carthage transitive dependencies in general.

**Comment by guidomb** [comment]
OK I will got with that approch then. Thanks!
