### ISSUE TITLE
Nested Frameworks causing issues with iTunes connect

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#773]
I suspect this is similar to #768.

I have a set of frameworks.

`DataManager` includes `GDL90`,`EGM96`, `ConvertibleUnits` and `CocoaAsyncSocket`
`GDL90` includes `EGM96`

My app includes just `DataManager` (which in turn means I get all these other frameworks)

My issues is that when I run the **archive** step I'm getting an invalid `.xarchive` file.

Inside my `*.xarchive/Products/Application/xxx.app` I have a bunch of frameworks

`Frameworks/GDL90.framework`
`Frameworks/EGM96.framework`
`Frameworks/DataManager.framework`
etc.

My problem is that both the `GLD90.framework` and `DataManager.framework` have an additional nested `Frameworks` directory inside them with their dependencies.

When I try to upload to **ItunesConnect** I get an error.  If i manually delete the nested `Frameworks` directories from these two frameworks everything "seems" to upload correctly.

Is there something obvious I've forgotten to do with my Carthage setup to "fix" this issue - either in the nested frameworks or the parent applications?

**Comment by neilpa** [comment]
The carthage way is to [avoid nested frameworks and rely on `Cartfile` to specify dependencies](https://github.com/Carthage/Carthage/tree/52249f46f370d8fbb82fdd71fe8b043b3b625061#nested-dependencies).

**Comment by jeeftor** [comment]
The nesting is *because* if the `Cartfile`    

Example: 

`GDL90`'s  `Cartfile` pulls in `EGM96` 

`DataManager`'s `Cartfile` pulls in `GDL90` and so i end up somehow with a nesting situation.

**Comment by neilpa** [comment]
From what you describe, `DataManager` and `GDL90` are explicitly embedding dependent frameworks in their framework target. This is set in the Xcode project and is not specific to carthage.

**Comment by jeeftor** [comment]
I may have fixed my issues:

1) Verify there is no `copy-frameworks` build task
2) Make sure that **Embeded Content Contains Swift** is set to **NO**

This seems to clear out the `/frameworks` directory

**Comment by neilpa** [comment]
> Make sure that Embeded Content Contains Swift is set to NO

Yea, this is confusing and poorly named build setting. It should only be set for top level application targets which are the ones that should be embedding the frameworks.

**Comment by Radhika-Geek** [comment]
Please suggest some solution if not using carthage. Also dont want to add internal frameworks to App level.
