### ISSUE TITLE
Building Carthage with Xcode 7 GM Seed

### ISSUE THREAD

**Issue by mojojoseph** [Carthage/Carthage#781]
Howdy, I'm trying to build Carthage 0.9.1.  The steps I use are git clone followed by git checkout 0.9.1 and then make.  

When trying to build Carthage (so I can get access to tvOS support without waiting on homebrew), I'm met with:

```
/Users/joe/Desktop/Carthage/Carthage/Checkouts/Runes/Source/Array.swift:78:24: error: 'T' has been renamed to 'Element'
    func apply<U>(fs: [T -> U]) -> [U] {
                       ^
                       Element
```

What are the build requirements for building Carthage 0.9.1?  Is it not Swift 2.0 ready?

**Comment by neilpa** [comment]
Carthage still targets Swift 1.2 so you can't use Xcode 7. You'll have to build it with Xcode 6.4 since Swift version is tightly coupled to Xcode version.

**Comment by mojojoseph** [comment]
Thanks @neilpa.  I want to make sure I have this right - to build a project that supports tvOS (Alamofire) I'll need Xcode 7.1 and Carthage 0.9.1, but to get Carthage 0.9.1 I'll need Xcode 6.4.  Just making sure.

**Comment by neilpa** [comment]
You don't have to build carthage from source. You can use the [release pkg](https://github.com/Carthage/Carthage/releases/tag/0.9.1) or install it via homebrew.

**Comment by neilpa** [comment]
But yes, in order to build carthage from source you'll need Xcode 6.4

**Comment by mojojoseph** [comment]
Hot damn, .pkg installed and worked like a charm.
