### ISSUE TITLE
Unable to Install Frameworks Built with Carthage Via Jenkins and HockeyApp

### ISSUE THREAD

**Issue by bladebunny** [Carthage/Carthage#782]
Have spent several hours troubleshooting this and getting nowhere.  Hoping the collective experience here can be some help.

I have a standalone iOS dynamic framework - and a separate iOS app that consumes it using Carthage.  The 'normal' case when i build manually and install on sim or device works perfectly.  Very nice.

Problem comes in when i build via Jenkins and install on HockeyApp (though I think HockeyApp is possibly not relevant).

App fails on launch after over the air install.  The specific error is:
"Failed to verify code signature of ... (Signed resources have been added, removed, or modified)"

If I then codesign verify, I see:
...app: a sealed resource is missing or invalid
file added: file1.h
file added: file2.h
file modified: .../CodeResources
file modified: /path-to/MyFramework.framework/MyFramework

..where the added or modified files are all the files in my framework.
I am code signing  the framework with my developer profile (but have tried with my distribution profile as well)

As for HockeyApp -- I can manually build the app on my machine and the build server and successfully install from HockeyApp.  So guessing its something in my Jenkins build setup.

I have also configured the build server for Carthage. Bootstrapped and updated.  And have also tried deleting Derived Data just before a CI build - unsuccessfully.

Anyone with any guidance or lessons learned viz Jenkins?

Cheers
tim

**Comment by mdiep** [comment]
This is just a wild guess, but… do you have "Code Sign on Copy" turned on in the Copy Frameworks build phase of your application target?

**Comment by bladebunny** [comment]
Yes.  "Code Sign on Copy" is on.  Have also tried explicitly adding the framework to the app target as an embedded framework and not doing so - same result. I did follow the Readme so in either case added as a linked framework.  I didn't create the original Jenkins build script - there is some modification of the plist going on but it's never caused an issue before. Wondering if there's something about the framework code signing that's different enough to cause this. Going to create a minimal build tomorrow to try and eliminate that as a problem source.

**Comment by navisingh** [comment]
Is this issue resolved?

**Comment by bladebunny** [comment]
Yes.  Sorry forgot to update.  Issue turned out to be duplicate package commands on Jenkins that resulted in the app being signed twice -- and then causing install to fail.  Solution was to change Jenkins Xcode plugin settings.  Under the 'General Build Settings' - we found you can't check both "Generate Archive" and "Pack application and build .ipa?" settings.  The plugin issues log seems to suggest the former setting is being deprecated. We use the latter setting and are now able to successfully deploy the app with our custom dynamic framework.

**Comment by sadhiappan** [comment]
Sorry to reopen this. I'm running into this exact issue. But I'm building my ipa `xcodebuild archive` and `xcodebuild -exportArchive`.
I can't seem to find a way to prevent the build script from signing the Framework again. Any advice on it? 

In my case
Framework1 depends on Framework2, Framework3 and Alamofire.
Framework2, Framework3 and Alamofire are signed properly but I think Framework1 is signed first and the rest are being signed laster causing the changes.
