### ISSUE TITLE
Xcode build different from Carthage Update (embedded frameworks)

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#783]
*Applies to: Carthage Version 0.8.0*

I've been having a hell of a time tracking down an issue (probably) in one of my projects involving an embedded framework:

I have an Objective C Framework `EGM96` and my Swift Framework `GDL90`.  `GDL90` includes `EGM96` via a `Cartfile` that reads:

    git "ssh://git@localServer:7999/emg96.git" "Release-1.0"

This version of `GDL90` is on the branch **feature/embed** and can be accessed via `Cartfile` entry: 

    git "ssh://git@localServer:7999/gdl90.git" "feature/embed

So here is where I'm getting confused.

**VERSION1 - Raw Checkout & Build**

I check out `GDL90`

    git clone ssh://git@localserver:7999/gdl90.git
    git checkout feature/embed

 do a `carthage update`

> *** Fetching emg96
> *** Checking out emg96 at "Release-1.0"
> *** xcodebuild output can be found in /var/folders/ml/mr4ytz0s4rs8n3dgvzwvdn0hkfl0lv/T/carthage-xcodebuild.utLL8S.log
> *** Building scheme "EGM96GeoidCalculator OSX" in EGM96GeoidCalculator.xcodeproj
> *** Building scheme "EGM96GeoidCalculator iOS" in EGM96GeoidCalculator.xcodeproj
> ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks'
> ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
> ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'

Then i do `xcodebuild` which builds 

`build/Release-iphoneos/GDL90.framework`
and inside are the directories:

*  /GDL90*
* /Headers/
* /Info.plist
* /Modules/
* /_CodeSignature/

**Version 2 - Carthage Build**

First I make a new directory

    mkdir tmp
    cd tmp
    touch Cartfile

I then put the same git line as above into my cart file

    git "ssh://git@localServer:7999/gdl90.git" "feature/embed

I do `carthage update` and `ls -1 Carthage/Build/iOS/GDL90.framework` and lo and behold we get this:

* **Frameworks/**
* GDL90*
* Headers/
* Info.plist
* Modules/
* _CodeSignature/

What I'm confused about is **WHERE DID THE FRAMEWORKS DIRECTORY COME FROM????**.

How do i figure out what is different here?

I'm at a loss.

**Comment by mdiep** [comment]
I would guess that it's build a different scheme or building it from a different project/workspace. It's also possible that Carthage isn't fetching a newer version of the branch—I would compare the revisions.
