### ISSUE TITLE
Strange behavior for multiple targets in one package

### ISSUE THREAD

**Issue by nickygerritsen** [Carthage/Carthage#784]
I am using Carthage 0.9.1. With the following Cartfile:

```ruby
github "nickygerritsen/Crypto" "add-tvos-target"
```
(which is just a fork of soffes/Crypto with a tvOS target) strange things happen.

I just use `carthage update` after creating an empty directory with the above Cartfile in it. Now three things can happen:

* Carthage tries to build the OSX version when building the watchOS scheme. The output of `carthage update` then looks like:
```bash
$ carthage update
*** Fetching Crypto
*** Checking out Crypto at "51a599dfba24e071a981a45bbca83e48f69ffc63"
*** xcodebuild output can be found in /var/folders/ml/m9ry2pvd58j86jy3v6pycmfw0000gn/T/carthage-xcodebuild.lRdMMk.log
*** Building scheme "CommonCrypto-OSX" in Crypto.xcodeproj
*** Building scheme "Crypto-OSX" in Crypto.xcodeproj
*** Building scheme "CommonCrypto-watchOS" in Crypto.xcodeproj
*** Building scheme "CommonCrypto-iOS" in Crypto.xcodeproj
*** Building scheme "CommonCrypto-tvOS" in Crypto.xcodeproj
*** Building scheme "Crypto-tvOS" in Crypto.xcodeproj
*** Building scheme "Crypto-watchOS" in Crypto.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task failed with exit code 65
```

The end of the xcodebuild output log file is:
```
Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchos2.0

=== BUILD TARGET CommonCrypto-OSX OF PROJECT Crypto WITH CONFIGURATION Release ===

Check dependencies
target 'CommonCrypto-OSX' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform
```

* Carthage / XCode complains that it will drop all bitcode because a dependency does not have bitcode enabled:

```bash
$ carthage update                                                                     
*** Fetching Crypto
*** Checking out Crypto at "51a599dfba24e071a981a45bbca83e48f69ffc63"
*** xcodebuild output can be found in /var/folders/ml/m9ry2pvd58j86jy3v6pycmfw0000gn/T/carthage-xcodebuild.SiWHGW.log
*** Building scheme "Crypto-OSX" in Crypto.xcodeproj
*** Building scheme "CommonCrypto-OSX" in Crypto.xcodeproj
*** Building scheme "CommonCrypto-watchOS" in Crypto.xcodeproj
*** Building scheme "Crypto-tvOS" in Crypto.xcodeproj
*** Building scheme "CommonCrypto-iOS" in Crypto.xcodeproj
*** Building scheme "Crypto-iOS" in Crypto.xcodeproj
*** Building scheme "CommonCrypto-tvOS" in Crypto.xcodeproj
*** Building scheme "Crypto-watchOS" in Crypto.xcodeproj
ld: warning: URGENT: all bitcode will be dropped because '/Users/nicky/Desktop/wtf/Carthage/Checkouts/Crypto/DerivedData/Crypto/Build/Products/Release-appletvos/CommonCrypto.framework/CommonCrypto' was built without bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE) or obtain an updated library from the vendor. Note: This will be an error in the future.
```

* Or no errors at all Sometimes it just works.

There is no logic in when what will happen (it seems) so I find this very strange. I have the feeling something is wrong with one of the Crypto or CommonCrypto targets but I can not seem to find it.

**Comment by ikesyo** [comment]
This might be the same situaion as https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2319#issuecomment-139199127.

**Comment by nickygerritsen** [comment]
I'm not sure. I have the feeling it is more related to #790 maybe?

It is quite annoying as I now sometimes need to build up to three / four times before it works...

**Comment by nickygerritsen** [comment]
Would the full verbose `carthage` output be useful? It seemed it didn't contain anything useful, because it only outputs xcodebuild commands and not _why_ it wants to run these commands.

**Comment by jeeftor** [comment]
What happens if you do a build in the `/Carthage/Checkouts` directory by typing xcodeubild?

**Comment by nickygerritsen** [comment]
You mean in the library subfolder?

**Comment by nickygerritsen** [comment]
OK it seems that after recreating all OSX and watchOS targets for the library the problem has gone away. Although not 100% sure it is gone, I assume it is for now.

Still a bit strange though.

**Comment by ikesyo** [comment]
Closing this for now. Feel free to reopen if you have any updates or further information!
