### ISSUE TITLE
Releases from Private Github repository

### ISSUE THREAD

**Issue by flovilmart** [Carthage/Carthage#786]
I'm trying to setup sub projects as carthage dependencies.

Everything is fine till I try to fetch the uploaded tagged release from Github.

I've tried multiple strategies and each one of them is either not working (prompts for username and password) or just checking out the code.

- git "git@github.com:[slug].git" == 1.0.0  
  checkout properly but doesn't fetch the release

- github "[slug]" == 1.0.0 
    dosen't checkout

- export GITHUB_ACCESS_TOKEN="token" + same as above
     doesn't checkout

- github "https://[token]@github.com/[slug]" == 1.0.0

In a general way, all GITHUB_ACCESS_TOKEN related functionalities doesn't seem to be functional.

Any idea? Suggestions?

**Comment by marcoconti83** [comment]
It took me a while too to get this working correctly.
My Cartfile uses this format:

     github "organization/repository" ~> 1.0.0

For authentication I am using HTTPS authentication as a workaround as SSH doesn't seem to work. Just add an internet password to the keychain, pointing to `github.com`. Carthage will pick it up.

**Comment by flovilmart** [comment]
it's on my machine so that's fine, with those lines the repo check out but I want to have the releases binaries, which are not downloading...

**Comment by marcoconti83** [comment]
With the setup I described, I correctly download the binaries instead of building. Without the entry in the keychain, it will only check out instead of downloading.
Maybe it's a problem with how you upload the binaries? How do you generate the binary file?

**Comment by flovilmart** [comment]
I

**Comment by flovilmart** [comment]
Actually it seems to be the reading of environment variables that is problematic with El Capitan. 
When running from source, and setting environment vars in the run settings it works fine

**Comment by flovilmart** [comment]
Superseded by #815
