### ISSUE TITLE
Better handling of derived data directory.

### ISSUE THREAD

**Issue by drekka** [Carthage/Carthage#787]
We have had this occur a couple of times now. We make changes to an API framework project. In this case I was removing the step that copied the projects dependencies as nested frameworks. 

I then go back to the main app project that uses the API and do a `carthage update`. I see the commits I made to the project come down and it builds. However when I look at the built dependency artifacts, they are still built using the old settings. i.e. there are nested frameworks present. 

I've gone through this a couple of times now. The only way to get the changes to reflect correctly seems to be to completely clear out the derived data directory. 

Is there some way to tell carthage to clear the directory? It appears that despite pulling changes, it is still using old code. Presumably something stored in the derived data path.

**Comment by neilpa** [comment]
This is captured in #459
