### ISSUE TITLE
Crash on Device: Library not loaded

### ISSUE THREAD

**Issue by skajake** [Carthage/Carthage#788]
I am using carthage to load ios-charts:

`github "danielgindi/ios-charts" "4e3b48d"`

Works fine in the simulator, but when an ad-hoc build is deployed through hockeyapp.net, the app crashes on launch with the following log:

`Dyld Error Message:
Dyld Message: Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: /var/mobile/Containers/Bundle/Application/C62A9B97-42D3-421E-9551-EACD5F2449B3/FieldSense.app/FieldSense
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/C62A9B97-42D3-421E-9551-EACD5F2449B3/FieldSense.app/Frameworks/Charts.framework/Charts: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/C62A9B97-42D3-421E-9551-EACD5F2449B3/FieldSense.app/Frameworks/Charts.framework/Charts'
  Dyld Version: 369.12`

Any ideas?

**Comment by blender** [comment]
Can it be that you forgot to add the build phase script to invoke copy-frameworks?
