### ISSUE TITLE
Build failing with signing identity issues with 0.9.1, but Xcode can build (and sign) fine.

### ISSUE THREAD

**Issue by mluisbrown** [Carthage/Carthage#789]
I'm trying to make [this lib](https://github.com/danielamitay/DACircularProgress) compatible with Carthage. I've created a [fork](https://github.com/mluisbrown/DACircularProgress) where I've put the Xcode project files that were missing in order to build it as a framework.

The framework builds fine in Xcode and also using xcodebuild (including code signing).

When I run `carthage build --no-skip-current` in the directory of the project (to test that Carthage can build it) I get:

> WARNING: Skipping build for "iphoneos" SDK because the necessary signing identity "iPhone Developer" is not installed

I definitely have a developer certificate and signing identify, and if I run `xcodebuild -scheme DACircularProgress -project DACircularProgress.xcodeproj build` in the same directory it builds fine, including the final code signing step which picks up my signing identify.

I'm using Xcode 7 and Carthage 0.9.1. I should note that I was previously using Carthage 0.8.0 (because I had installed using homebrew) and with 0.8.0 I wasn't getting this problem.

**Comment by mluisbrown** [comment]
I'm getting exactly the same problem with the [Cartography](https://github.com/robb/Cartography) repo, so it's not specific to the new framework project I setup.

**Comment by mluisbrown** [comment]
And to add to the problem, when it tries to build the Cartography repo Carthage crashes with:

> fatal error: No valid SDKs found to build (you're missing one or more signing identities): file /Users/mdiep/Repositories/Carthage/Carthage/Source/CarthageKit/Xcode.swift, line 912

And then triggers:
> Caught signal triggered by the Swift runtime!
Illegal instruction: 4

And has to be terminated by Ctrl-C

**Comment by mluisbrown** [comment]
Just confirmed that reverting to v0.8 solves the problem, so it's something specific to 0.9.1 (haven't checked 0.9.0)

**Comment by mdiep** [comment]
If you run `security find-identity -v -p codesigning`, what are the identity types? (The portion inside the `"`s before the `:`.)

**Comment by mluisbrown** [comment]
`iOS Development` and `iPhone Distribution`.
I wondered about that (none of them matching `iPhone Developer`), but AFAICR those names can be set by the developer to whatever they want when the certificate is created. Also, it doesn't prevent Xcode from being able to find the correct identity, even if the project file refers to `iPhone Developer` or `iOS Developer`.

**Comment by mdiep** [comment]
> Also, it doesn't prevent Xcode from being able to find the correct identity, even if the project file refers to iPhone Developer or iOS Developer.

Oh, Xcode. :disappointed: 

How does Xcode determine whether it has a compatible certificate then?

**Comment by mluisbrown** [comment]
> How does Xcode determine whether it has a compatible certificate then?
I have absolutely no idea. Contrary to what I said above, the name of the identity `iPhone Developer` that appears in the certificate is put there by Apple, and not chosen by the user. I have no clue how my development identity came to have the name `iOS Development`. I still have the certificate downloaded from the Apple Dev Member Center and it's right there: **iOS Development**.

However, as the cert was going to expire in November I revoked it and generated a new development certificate and that has the name `iPhone Developer`.

That fixed everything. Not sure what to suggest. If it happened to me, it could happen to others.

**Comment by mdiep** [comment]
> Not sure what to suggest. If it happened to me, it could happen to others.

I'm not sure either. :confused:

**Comment by mluisbrown** [comment]
Two questions though:
1. Why did´t this problem occur in 0.8? What does 0.9.1 do differently that makes it look up the signing identities?
2. Why is Carthage getting involved with looking up signing identities at all? Why not just leave it to `xcodebuild,` which seems to be able to handle weird signing identity names?

**Comment by mdiep** [comment]
Starting with 0.9, Carthage will build for the simulator only if the correct certificates aren't installed (#583). Because code signing is required for dynamic frameworks on iOS, you can't build for the device without a certificate. People don't have certificates on CI, so they want to build for the simulator only in that case.

**Comment by csjones** [comment]
Xcode does code signing on copy under Build Phases in Embed Frameworks by default. Why does Carthage perform an additional code sign?

**Comment by mdiep** [comment]
Xcode requires code signing when building a framework, even though it's code signed on copy. It's stupid, but that's Xcode.

**Comment by guidomb** [comment]
Same is happening to me. I have an open source repository for my build scripts (https://github.com/guidomb/ios-scripts) that I use in every iOS project and when I updated the scripts to use Carthage 0.9.2 I've got the same error in Travis Ci. You can check the failing build [here](https://travis-ci.org/guidomb/ios-scripts/builds/82543859)

**Comment by guidomb** [comment]
@mdiep Just tests Carthage 0.9.3 is Travis CI without certificates and I am getting the following warning followed by a failure

```
*** WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "iPhone Developer" is not installed
```
```
⌦  ld: framework not found Result
```

Did I miss something of is this a bug? Shouldn't carthage only build for iossimulator given that it does not have certificates in travis?

You can check the complete build [here](https://travis-ci.org/guidomb/ios-scripts/builds/84026218)

**Comment by ikesyo** [comment]
@guidomb That is because of https://github.com/antitypical/Result/pull/78.

**Comment by guidomb** [comment]
@ikesyo I updated my test project to use `master` version of Result which includes the patch you mentions and I am getting the same error.

You can check the build [here](https://travis-ci.org/guidomb/ios-scripts/builds/84152934)

**Comment by ikesyo** [comment]
You may be misunderstanding, the commits of the PR is included in 0.6.0-beta.3. So using `master` would not change anything. (The PR set code signing for iphonesimulator SDK too)

**Comment by guidomb** [comment]
@ikesyo Oh I thought the bug was fixed in that PR when it was actually introduced there.

**Comment by gambcl** [comment]
I'm getting the same problem with 0.9.3 it just refuses to build my iOS framework targets giving the errors:

*** WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "iPhone Developer: Charles Gamble (R5RCU3B9M5)" is not installed
*** WARNING: Skipping build for "iphoneos" SDK because the necessary signing identity "iPhone Developer: Charles Gamble (R5RCU3B9M5)" is not installed

However when I run the xcodebuild command manually it succeeds. I can see the mentioned entry in my keychain, not sure what else to check.

Any ideas?

Is this a Carthage bug or a problem with my project?

**Comment by aexmachina** [comment]
I've just lost several days trying to get this issue resolved. It wasn't clear to me that Homebrew didn't have an up-to-date version. I think that we need to make it _much_ clearer that Carthage is **completely broken** for CI if you use the version that's currently on Homebrew.

**Comment by jeffreybergier** [comment]
FWIW, I was having this issue just now and it turned out to be a certificate trust issue. My Keychain was missing the "Apple Worldwide Developer Relations Certification Authority" CA Cert. I exported it from another Mac and imported it into the System and Login keychains of the problematic Mac and it resolved all the issues.

**Comment by fikeminkel** [comment]
@jeffreybergier Thanks! That was my issue too.

You can download the intermediate certs directly from Apple: http://www.apple.com/certificateauthority/

**Comment by jeffreybergier** [comment]
@fikeminkel cool. Thanks for the link. I'm glad it worked. I should have mentioned that I could tell because when I ran 

find-identity -p codesigning (notice no -v)

then it listed all the identities and below it it listed all the valid ones. I noticed the vast majority were there but not valid. Then I checked the keychain.

Glad it worked :+1:

**Comment by ikesyo** [comment]
It seems that https://github.com/Carthage/Carthage/issues/789#issuecomment-153536722 and https://github.com/Carthage/Carthage/issues/789#issuecomment-153868597 should fix the problem. Closing this.

**Comment by AAverin** [comment]
I'm gettting this error for one of the libraries (AlamofireObjectMapper)
Skipping build for "iphonesimulator" SDK because the necessary signing identity "iPhone Developer" is not installed

I have no release signature yet, do I really need one to build for simulator?

**Comment by fikeminkel** [comment]
@AAverin: Another thing that seems to have helped is that for local dev builds we now pass the Debug configuration option to carthage:
```
carthage bootstrap --configuration Debug
```

You probably don't want to do that on your CI server though.

**Comment by AAverin** [comment]
Thanks, I've resolved the issue - the problem was in the library, it was forcing signature for simulator builds
