### ISSUE TITLE
Default binary path is tricky to set up in parent projects

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#79]
Apparently Xcode can't figure out that it can locate modules in `Carthage.build/{Mac,iOS}`, even if you drag a framework from the folder into the parent project.

That means the current installation steps look like:
1. `carthage {bootstrap,update,build}` on the command line.
2. For a framework `ReactiveCocoa`, drag platform-specific `ReactiveCocoa.framework`s into the project, or add `-framework ReactiveCocoa` to the linker flags.
3. Add `Carthage.build/Mac` to the Framework Search Paths for any OS X target(s), and `Carthage.build/iOS` to the Framework Search Paths for any iOS target(s). Sharing the path between both targets fails spectacularly.

I'd love to make that final step unnecessary, or at least use some Xcode [build setting](https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html) that lets the user add just one Framework Search Path—something like `Carthage.build/$(SDKROOT)`, but not as fragile.

**Comment by nheagy** [comment]
Not a peep, but I had this very problem with Xcode 7 today. Wouldn't compile until I added Carthage/Build/iOS to framework search paths.

**Comment by aventurella** [comment]
I was having this same problem with Xcode 6.4. I was actually trying to figure out how on earth ReactiveCocoa builds with carthage given it's dependency on `Result` aka another Framework.  When I try this with my own framework that depends on a framework my carthage build fails with `cannot find module` until I update the `Framework Search Paths`.  `ReactiveCocoa`, as far as I can tell, does not have this issue even though it depends on another Framework from Carthage and it does not have a `Framework Search Path` set.

You can see my path of failures here:
#735

This has been causing me much consternation, should we always set the search paths or do we not need to? What kind of sorcery does `ReactiveCocoa` use to build without specifying that =)

**Comment by fbartho** [comment]
I'm exhibiting this exact same problem when using `github "ParsePlatform/Parse-SDK-iOS-OSX" "master"` which depends on a framework called Bolts. Does anybody have a solution here?

Is ParsePlatform setup wrong, or is my Xcode broken in some way? I'd rather not fork ParsePlatform just to include my own custom `Framework Search Paths` setting of `${PROJECT_DIR}/Carthage/Build/**`

[Disclaimer: this is my first time trying to use Carthage, please explain my noobishness if I'm failing somewhere]

Using:
- Clean New Swift Project & Workspace
- Carthage 0.10.0
- Xcode 7.1.1
- OSX 10.11.2

**Comment by mdiep** [comment]
Please open a new issue with which version of Carthage you're using, an example Cartfile, and the output from Carthage.

**Comment by fbartho** [comment]
@mdiep Issue Created: #1053, thanks!
