### ISSUE TITLE
Alamofire 2.0.2 failing to build on watchOS

### ISSUE THREAD

**Issue by cnoon** [Carthage/Carthage#790]
Hey everyone,

I'm fairly certain I have everything in the Alamofire project configured correctly, but carthage seems to be a bit unhappy about building our `watchOS` target. I figured I'd try to pull in the experts to help get it sorted out. Here's all the info I can think to provide:

### Cartfile

```bash
github "Alamofire/Alamofire" "2.0.2"
```

### Carthage Version

```bash
$ carthage version
0.8.0
```

### Xcodebuild Version

```bash
$ xcodebuild -version
Xcode 7.0
Build version 7A220
```

### Carthage Update Output

```bash
$ carthage update --platform watchos

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchos2.0

=== BUILD TARGET Alamofire watchOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

... lots of build details ...
...code signing

** BUILD SUCCEEDED **

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchsimulator2.0

=== BUILD TARGET Alamofire watchOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies
target 'Alamofire watchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform
```

Please let me know if there are any other details I can provide that would be of use. More details about our filed issues can be found in [Alamofire #689](https://github.com/Alamofire/Alamofire/issues/689).

**Comment by marcpalmer** [comment]
I am seeing exactly this problem with CocoaLumberjack's "swift_2.0" branch.

If I open the Lumberjack xcodeproj in Xcode 7.1 beta, I can build all the watchOS targets and they show bitcode "YES" in Build Settings. 

However Carthage seems to fail to carry the bitcode option through. xcode-select has been run in the shell to point at the 7.1 beta tools.

**Comment by cnoon** [comment]
Apologies for not including this originally, but Alamofire also has bitcode enabled on the `watchOS` target.

**Comment by guidomb** [comment]
Could this be related with https://github.com/antitypical/Result/issues/71 ?

**Comment by jurvis** [comment]
hi all, I was the OP of https://github.com/Alamofire/Alamofire/issues/689, if I recall correctly, I solved the problem by re-creating the watchOS 2 Simulators. (see https://github.com/Carthage/Carthage/issues/685)

not sure if that's an entirely separate issue on it's own.

**Comment by cnoon** [comment]
I can confirm this did in fact fix the issue. It appears that you need to have an iPhone + watch simulator configured for this to work properly. I previously did not which seems to be the problem. It would be great if someone from the Carthage team could confirm this is expected behavior. Either way, I'm going to close this issue out since it has been resolved.

Thanks everyone!

**Comment by marcpalmer** [comment]
FYI I have also fixed this problem.

I had to:
1. Manually create in Xcode 7.1 "Devices" a simulator device paired with a Watch simulator
2. Rebuild all my own frameworks and all their carthage dependencies
3. Update the dependencies in my app (which has bitcode enabled)

What is puzzling me at the moment is why the linker fails to link framework X that depends on Y, when building with Carthage. Carthage has already done clean build of Y, but seems to link the app-local copy of X with an embedded version of Y. i.e. you can fix the bitcode/watchOS simulator thing in your app but that won't fix your problem even though Carthage rebuilds everything. The transitive dependencies of my framework X are set to include Y.

**Comment by stigi** [comment]
I'm on Xcode 7.2 beta (7C62b I think it's beta 7, but the About dialog won't show).
The solution is not working for me. I deleted all my devices, recreated the default devices and created an iPhone 6s simulator with watch. I updated carthage (now at 0.10.0) and updated all dependencies. Then I ran `carthage build` and It still leaves me with:
```
=== BUILD TARGET Alamofire watchOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies
target 'Alamofire watchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform
```

One thing I noticed when opening the Alamofire workspace and inspecting the watchOS target was, there is no Bitcode option. The iOS target does have that option. Maybe they don't show it for watchOS since it's mandatory...
<img width="781" alt="screen shot 2015-11-24 at 9 31 56 am" src="https://cloud.githubusercontent.com/assets/13815/11375111/3e8517d6-928e-11e5-95d7-a8c080a7c019.png">
I'm wondering if that's a problem with the Xcode beta. I'll download and try with the release build as soon as I have better Wifi

**Comment by igagen** [comment]
@stigi did you ever get past this? I am also on XCode 7.2 (7C68) and have installed and run the watch simulator but am still unable to build Alamofire. Are there any other workarounds for this?

**Comment by ikesyo** [comment]
@igagen Please update to [0.11](https://github.com/Carthage/Carthage/releases/tag/0.11) for Xcode 7.2 compatibility. The related fix (#941) is included in that release.

**Comment by igagen** [comment]
@ikesyo Thanks! That did the trick, it's working now.

**Comment by pixelogik** [comment]
@ikesyo Version 0.11 of carthage also fixed the issue for us. Should be in brew :) Thanks!
