### ISSUE TITLE
Carthage failing nondeterministically while bootstrapping repos with prebuilt frameworks

### ISSUE THREAD

**Issue by iosdevzone** [Carthage/Carthage#794]
So this is a strange one. Carthage is failing (nondeterministically) when bootstrapping repos with prebuilt frameworks. I have tested on two systems, one running OS X 10.9.5, the other running 10.10.4, with two different repos Runes and ReactiveCocoa. 

I am using carthage 0.9.1 on both systems.

Here's a look at what happens for Runes. It *did* eventually succeed, but "fifth time lucky" does not seem like a desirable tag line for carthage!

The problem does not occur if the `--no-use-binaries` flag is used.

It kinda feels like a some file operations are being executed concurrently that should not be. I haven't tried to dive into the code just yet, not being fluent in `ReactiveCocoa`  ;-)

```bash
github "thoughtbot/Runes"
```

```bash
inu:idz$ carthage bootstrap
*** Downloading Runes.framework binary at "3.0: The Applickening"
Failed to read file or folder at /tmp/idz/Carthage/Build/iOS/Runes.framework
inu:idz$ carthage bootstrap
*** Downloading Runes.framework binary at "3.0: The Applickening"
Failed to read file or folder at /tmp/idz/Carthage/Build/iOS/Runes.framework
inu:idz$ carthage bootstrap
*** Downloading Runes.framework binary at "3.0: The Applickening"
Failed to write to /tmp/idz/Carthage/Build/iOS/Runes.framework: Error Domain=NSCocoaErrorDomain Code=513 "“Runes.framework” couldn’t be removed because you don’t have permission to access it." UserInfo=0x7ff620f14f00 {NSFilePath=/tmp/idz/Carthage/Build/iOS/Runes.framework, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7ff620f0dda0 "The operation couldn’t be completed. Directory not empty"}
inu:idz$ carthage bootstrap
*** Downloading Runes.framework binary at "3.0: The Applickening"
Failed to read file or folder at /tmp/idz/Carthage/Build/iOS/Runes.framework
inu:idz$ carthage bootstrap
*** Downloading Runes.framework binary at "3.0: The Applickening"
*** xcodebuild output can be found in /var/folders/gf/xxcylc490693yp158lxb67lh0000gn/T/carthage-xcodebuild.9WCf1H.log
```

**Comment by ikesyo** [comment]
I believe this is already fixed in #760, and that should be included in the next release (probably 0.9.2).
