### ISSUE TITLE
Issue with `carthage update` 

### ISSUE THREAD

**Issue by Baza207** [Carthage/Carthage#795]
When I run `carthage update` on my project with the Cartfile that has `github "Alamofire/Alamofire" ~> 2.0` in it I get the following error.

```
$ carthage update
dyld: lazy symbol binding failed: Symbol not found: __TZF10Commandantoi2loUS_12ArgumentType___FTOS_11CommandModeGVS_6OptionQ___GO6Result6ResultQ_GOS_15CommandantErrorQ0___
  Referenced from: /usr/local/bin/carthage
  Expected in: /Library/Frameworks/Commandant.framework/Commandant

dyld: Symbol not found: __TZF10Commandantoi2loUS_12ArgumentType___FTOS_11CommandModeGVS_6OptionQ___GO6Result6ResultQ_GOS_15CommandantErrorQ0___
  Referenced from: /usr/local/bin/carthage
  Expected in: /Library/Frameworks/Commandant.framework/Commandant

Trace/BPT trap: 5
```

I'm using Carthage 0.8.0 installed via brew, though I did try using 0.9.1 from the .pkg install from GitHub, but I get the same issue.

I've tried several solutions as well from slightly related issues on SO but nothing seems to fit my error exactly, and none solve it.

I'd love to start using Carthage but this is an instant stopper for me. I'm not sure if it's related to the issues currently with getting the brew version to 0.9.X from 0.8.0 or something else.

**Comment by mdiep** [comment]
It sounds like you may have a bum installation—perhaps from trying to install both the homebrew version and the `.pkg`. Can you try removing `/Library/Frameworks/CarthageKit.framework` and `/Library/Frameworks/Commandant.framework`?

**Comment by Baza207** [comment]
Ah amazing that worked.

For reference, `/Library/Frameworks/CarthageKit.framework` didn't exist, but removing `/Library/Frameworks/Commandant.framework` then uninstalling and reinstalling via brew seems to have fixed it.

Thanks for the quick response, and sorry this probably should have been an SO post.

**Comment by mdiep** [comment]
Issues here are fine. :smile:
