### ISSUE TITLE
Crash during build

### ISSUE THREAD

**Issue by zachwaugh** [Carthage/Carthage#797]
I'm seeing a crash using version 0.9.2 similar to #776, but I'm not getting any error messages. You can reproduce with Nimble:

```
github "Quick/Nimble" "master"
```

```
➜ ~/dev/scratch/carthage-test: carthage version
0.9.2
➜ ~/dev/scratch/carthage-test: carthage bootstrap --platform ios --verbose
*** Checking out nimble at "70b901e55bad427d211b93586a83e0e3bca32034"
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj

Caught signal triggered by the Swift runtime!
Illegal instruction: 4

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.
...
```

That is repeated a bunch of times and never finishes. I can build Nimble successfully with `xcodebuild`. The only thing that sticks out with that repo is the `SUPPORTED_PLATFORMS` setting on Nimble, but that may be unrelated:

```
SUPPORTED_PLATFORMS = "iphonesimulator iphoneos appletvsimulator appletvos"
```

Let me know if I can provide any other information

**Comment by mdiep** [comment]
If I change `SUPPORTED_PLATFORMS`, then it builds, so I think you're right. :smile:

I'm not sure what would be required from Carthage to support this. PRs welcome. :relaxed:

**Comment by ikesyo** [comment]
[`buildableSDKs() |> first`](https://github.com/Carthage/Carthage/blob/c82c3d1cb6f35a146793a914f1fae0e14d95ce0c/Source/carthage/Build.swift#L109-L110) returns the result:

```swift
Optional(.Failure(A shell task failed with exit code 64:
xcodebuild: error: SDK "appletvsimulator" cannot be located.
))
```

**Comment by mdiep** [comment]
Ah, it probably just requires Xcode 7.1 then?

**Comment by ikesyo** [comment]
I think so, or we can add `|> catch { _ in .empty }` to [this](https://github.com/Carthage/Carthage/blob/c82c3d1cb6f35a146793a914f1fae0e14d95ce0c/Source/carthage/Build.swift#L222) then remove or reconsider [this line](https://github.com/Carthage/Carthage/blob/c82c3d1cb6f35a146793a914f1fae0e14d95ce0c/Source/CarthageKit/Xcode.swift#L898).

**Comment by ikesyo** [comment]
Using Xcode 7.1, the build was successful.

**Comment by mdiep** [comment]
We should try to detect these failures and print a warning instead of crashing.

**Comment by zachwaugh** [comment]
Thanks for looking into this! I can build Nimble successfully with Xcode 7.0 from Xcode and `xcodebuild`, so I don't think Xcode 7.1 is required necessarily, so I'm assuming `xcodebuild` skips platforms that it can't locate the SDK for?

**Comment by ikesyo** [comment]
> I can build Nimble successfully with Xcode 7.0 from Xcode and xcodebuild, so I don't think Xcode 7.1 is required necessarily, so I'm assuming xcodebuild skips platforms that it can't locate the SDK for?

That is because you don't specify `-sdk appletvos` or `-sdk appletvsimulator`, but we are picking up SDK list to build from the `SUPPORTED_PLATFORMS` setting, so Carthage encounters the error with using the unknown SDKs.

**Comment by raudabaugh** [comment]
Possible regression- I am seeing the same issue trying to build mxcl/PromiseKit with Xcode 9.2 and Carthage 0.27.
