### ISSUE TITLE
App Store Submission fails due to bitcode

### ISSUE THREAD

**Issue by Padarom** [Carthage/Carthage#799]
I'm trying to submit my app to iTunes Connect to make it available through Testflight, however it automatically gets rejected by Apple.

I have already tried disabling bitcode, which doesn't change anything. The build phase that executes `/usr/local/bin/carthage copy-frameworks` for each package is also included, so I don't think it's because of that.

> __Invalid Bundle__ - Failed to verify bitcode in Alamofire.framework/Alamofire: error: Bundle only contains bitcode-marker MyAppName.app/Frameworks/Alamofire.framework/Alamofire (armv7) ... 
__Invalid Bundle__ - Failed to verify bitcode in Haneke.framework/Haneke: error: Bundle only contains bitcode-marker MyAppName.app/Frameworks/Haneke.framework/Haneke (armv7) ... 
...

Also when I try to validate my archive while having "_Include app symbols for your application to receive symbolicated crash logs from Apple._" it fails with the message 

>__Unable to validate your application__
The archive is invalid. /var/folders/6c/1zqyqhzs7t14xn2nlnk884940000gp/T/XCodeDistPipeline.S9E/Packages/MyAppName.ipa does not exist.

I just recently switched from CocoaPods to Carthage, so I guess I did something wrong while setting it up. How am I able to fix this and submit the app?

**Comment by MSchmidt** [comment]
I did not switch from CocoaPods to Carthage but instead did a clean install with Carthage and have the exact same issue. Maybe we are still doing something wrong but at least it's not related to switching between package managers.

**Comment by mdiep** [comment]
There are a few other open issues about bitcode that you should read through. I haven't done anything with bitcode yet, so I'm not very knowledgable about it or what settings are required.

**Comment by Padarom** [comment]
@MSchmidt I used [`cocoapods-deintegrate`](https://github.com/kylef/cocoapods-deintegrate) to remove CocoaPods from my project and did a clean install of the Carthage dependencies as well (as explained in the Readme). I just meant to say that before, when I used CocoaPods everything worked and I could submit it successfully.

Might very well be an issue with Carthage itself then. @carlossless has already suggested a potential fix in #800, but I couldn't tell whether that would work.

**Comment by mluisbrown** [comment]
Please read the thread of https://github.com/Carthage/Carthage/issues/535 in full. Basically, you need to ensure that any Carthage framework you use has `BITCODE_GENERATION_MODE=bitcode` for Release builds and `BITCODE_GENERATION_MODE=marker` for Debug builds. You need to add this as a User-Defined build setting. 

As for the problem with app symbols when validating your archive, it's not clear how to deal with the problem, take a look at [this thread](https://forums.developer.apple.com/thread/14729) on the Apple Dev Forums. It would appear that "Include App Symbols" and "Include Bitcode" may be mutually exclusive options all though nothing prevents you from selecting both.
