### ISSUE TITLE
Converting bitcode frameworks to native frameworks when bitcode is not enabled.

### ISSUE THREAD

**Issue by carlossless** [Carthage/Carthage#800]
So I this relates to #799, a problem which I had myself.

Basically, Itunes Connect fails to process your application if it contains bitcode frameworks, but wasn't built with bitcode enabled itself. The only remedy I found to this is to rebuild the frameworks without bitcode support, but that requires changing the project settings in each of the depedencies.

As a fix I would propose adding an additional step to `copy-frameworks`. This step would just convert frameworks built with bitcode support to native frameworks, based on whether the dependant project has bitcode enabled.

Sadly I wasn't yet able to find the tools and options on clang/llvm or lipo to implement this myself. Maybe there's anyone who's more familiar with llvm and has this problem also?

**Comment by carlossless** [comment]
SO Question: http://stackoverflow.com/questions/32780788/converting-llvm-bitcode-library-to-a-native-code-library

**Comment by Padarom** [comment]
Your workaround seems to be working, previously I had it rejected due to 7 incorrect frameworks, now it's just 1 after recompiling them without bitcode. One of the frameworks ([uacaps/PageMenu](https://github.com/uacaps/PageMenu)) does not include an `.xcodeproj` though, so I don't know where to change it there. 

Any thoughts?

**Comment by carlossless** [comment]
Well since that's not a framework and you're probably including it via CocoaPods, can you just change that setting on the cocoapods target for that depedency? Also, I'd rather we continue discussing it in your original issue, as I intended this one to contribute to a more long term solution for carthage frameworks.

**Comment by carlossless** [comment]
After doing more research and figuring out the specific case I had, I'm closing this because bitcode gets more or less reliably stripped when submitting apps through xCode.
