### ISSUE TITLE
copy-framework failed when targeting OS X command line application

### ISSUE THREAD

**Issue by skyline75489** [Carthage/Carthage#808]
I'm trying to build an OS X command line application. When trying to add dependencies using Carthage, the build failed with:

```
Environment variable not set: FRAMEWORKS_FOLDER_PATH
Command /bin/sh failed with exit code 1
```

If I don't add `copy framework` in custom `Run Script`, the program failed with:

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
```

I'm using Xcode 7, OS X 10.10.5.

**Comment by skyline75489** [comment]
Currently I'm using @jpsim 's solution [here](https://github.com/realm/realm-cocoa/issues/975#issuecomment-58056819) as workaround.

**Comment by poseidonsw** [comment]
this seems to work for me as well
