### ISSUE TITLE
Cannot find schemes due to timeout xcodebuild -list

### ISSUE THREAD

**Issue by avalanched** [Carthage/Carthage#809]
For some unknown reason

xcodebuild -list is taking +8seconds for it to find all schemes (on certain projects).
I guess its an xcode bug, but since carthage is limited to 8 seconds timeout on finding schemes I cannot overcome this issue, (if i time it it takes about 10seconds to find the schemes which is just a couple of seconds to short) is there any way to extend this timeout ?

I was thinking about using my own Carthage build where i bump the timout to 15seconds or so, but in order to build carthage i need to bootstrap it with carthage to get all the dependencies which at the moment feels a bit like i'm stuck in a limbo.

**Comment by mdiep** [comment]
I'd be okay with bumping up the timeout to 15s if you want to open a PR. :smile:

**Comment by avalanched** [comment]
I made it work with using xcode 6.3.2 as command line tools, seems like a weird defect on 6.4, even though it worked fine last week. but bumping it surely won't do no harm

**Comment by mdiep** [comment]
Fixed by #810.
