### ISSUE TITLE
Should I place Carthage folder (with /Build subdirectory) in the $(SRCROOT)?

### ISSUE THREAD

**Issue by AlexanderKaraberov** [Carthage/Carthage#811]
`(Should be marked with "question" label)`:
My current workflow with Carthage is next: in my Home directory I have an iOS_Frameworks folder with `Cartfile`, `/Build` and `/Checkouts` folders inside it. I periodically update frameworks there with `carthage update`. Then for each my new iOS project I just drag and drop in the project's directory tree the framework I currently need e.g. Alamofire.framework (this action copies this framework from `/Users/~/Documents//iOS_Frameworks/Carthage/Build/iOS` right to my `$(SRCROOT)` ). After this I add this input file: `$(SRCROOT)/Alamofire.framework`  to `carthage copy-frameworks` run script.
So, I'm interested is this a correct (idiomatic to Carthage) approach? 

P.S. Because as I understood from README.md: Carthage/Build folder is added to each project root (in examples i see `$(SRCROOT)/Carthage/Build/iOS/ReactiveCocoa.framework` for run script).

**Comment by mdiep** [comment]
That sounds fine. You could use the `.framework`s directly from the `Carthage/Build/` directory if you wanted to. But copying them to a different directory is fine too.

If you're developing a framework, then it's a little less flexible. But for application projects, there's not really a wrong way to do things.
