### ISSUE TITLE
Installer pkg is not code signed

### ISSUE THREAD

**Issue by kballard** [Carthage/Carthage#813]
The installer package for 0.9.2 (I didn't check the others) is not code signed. This results in the following alert when attempting to open it with the default Gatekeeper settings:

![screen shot 2015-09-30 at 3 06 09 pm](https://cloud.githubusercontent.com/assets/714/10207991/d0bf6bf4-6784-11e5-93fa-896a16fcbad9.png)

It can be bypassed by right-clicking the .pkg and selecting Open, but many people don't know that.

**Comment by ikesyo** [comment]
Let's move to #1186.
