### ISSUE TITLE
"lipo: can't move temporary file" when building child framework in a framework

### ISSUE THREAD

**Issue by Baza207** [Carthage/Carthage#816]
I have a project that is a Framework (let's call it MyKit). This Framework has iOS and watchOS targets. It also has AlamofireImage, which in turn has Alamofire in it.

When I build this directly using Carthage, it works fine, it builds, no errors, all my unit tests run and pass.

However, when I use Carthage to use this Framework in a main project (iOS app with watchOS 2 app target as well) I get the following error.

```
*** Fetching MyKit
*** Fetching AlamofireImage
*** Fetching Alamofire
*** Checking out MyKit at "1.0"
*** Checking out AlamofireImage at "1.1.2"
*** Checking out Alamofire at "2.0.2"
*** xcodebuild output can be found in /var/folders/4p/s_pjk09s7hsblkl8flw7thp00000gn/T/carthage-xcodebuild.D4RRMc.log
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "AlamofireImage watchOS" in AlamofireImage.xcworkspace
*** Building scheme "AlamofireImage OSX" in AlamofireImage.xcworkspace
*** Building scheme "AlamofireImage iOS" in AlamofireImage.xcworkspace
*** Building scheme "MyKit watchOS" in MyKit.xcodeproj
*** Building scheme "MyKit iOS" in MyKit.xcodeproj

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't move temporary file: /Users/<user>/Library/Developer/Xcode/DerivedData/MyKit-fkfshkcchjjeswaxxtonejlcjdbd/Build/Products/Release-iphonesimulator/Alamofire.framework/Alamofire to file: /Users/<user>/Library/Developer/Xcode/DerivedData/MyKit-fkfshkcchjjeswaxxtonejlcjdbd/Build/Products/Release-iphonesimulator/Alamofire.framework/Alamofire.lipo (No such file or directory)
```

Any help with this would be great, and thanks in advance.

This is running Carthage 0.9.2, Xcode 7.0.1 and happens on OS X 10.10 and 10.11.

**Comment by mdiep** [comment]
Carthage doesn't support embedded frameworks. The correct way to do this is not copy the dependencies into the framework, but to copy them into the app target instead. I've written up some more details around this in other issues like #768.

**Comment by Baza207** [comment]
Ah, my bad. Thanks for the reference, I'll have a read through.
