### ISSUE TITLE
Build frameworks without BITCODE

### ISSUE THREAD

**Issue by pieterclaerhout** [Carthage/Carthage#820]
Hi there,

I'm using Carthage in a project that should be compiled without bitcode enabled (as there are some of the dependencies don't support bitcode).

Is there any way to specify that the frameworks should be built with the setting ENABLE_BITCODE set to NO? Currently, I'm manually overriding this in the project settings, but it would be much handier if this could be a command line argument in the build / update commands.

Kind regards,

pieter

**Comment by schwa** [comment]
We've just had our app rejected by Apple for this (seems to be a new thing, another build built the same way was accepted).

**Comment by schwa** [comment]
Possible (but untested) solution:

Create an xcconfig file that disables BITCODE and then export this in the `XCODE_XCCONFIG_FILE` environment variable (see xcodebuild's manage for XCODE_XCCONFIG_FILE)

**Comment by mdiep** [comment]
There's some more information about this in #535.

**Comment by diejmon** [comment]
@schwa I think this little hint can be in the documentation. 
For example I need to make sure all dependencies are compiled with APPLICATION_EXTENSION_API_ONLY. The only way I found to accomplish this in Carthage is to use XCODE_XCCONFIG_FILE env variable.

**Comment by ikesyo** [comment]
Setting `ENABLE_BITCODE` to `NO` on your project would be the right thing to do. Closing.
