### ISSUE TITLE
Apple does not allow submitting Apple TV apps with frameworks that include 'appletvsimulator' in SUPPORTED_PLATFORMS

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#824]
I just filed this radar: http://www.openradar.me/22967941

This is a very similar scenario to the bug that lead to implementing `copy-framework` to strip extra architectures, except now, `AppleTV` apps should only have `appletvos` as `SUPPORTED_PLATFORMS`.

I think `Carthage` (and libraries) should continue building with both `appletvos` and `appletvsimulator`, obviously, so that these frameworks are usable in both simulator and device. However, would it be possible to make `copy-frameworks` remove `appletvsimulator` from the framework `.plist`, to workaround this issue?

![there is always a way](https://cloud.githubusercontent.com/assets/685609/10273088/eb94f76a-6adf-11e5-9f98-b8e795c1613e.jpg)

### EDIT October 8th:
Apple closed my radar as a dupe, and after I asked for more information they replied the following:
> Xcode does not support frameworks which are fat across multiple platforms. A framework which specifies that it supports the simulator platform, but lacks the architectures for it, as you've constructed, is an invalid framework; it's a bug that iOS and watchOS validation does not catch this. We're marking your bug as a duplicate of the general bug we have about providing a better workflow for distributing built simulator frameworks. We appreciate the detailed bug report!

So yeah, we need to make `copy-frameworks` strip simulator platforms from `SUPPORTED_PLATFORMS`.

**Comment by mdiep** [comment]
Updating `copy-frameworks` seems like the right way to go. :+1: I blindly assumed that it already worked, but I haven't done any AppleTV apps, so I wouldn't know.

**Comment by NachoSoto** [comment]
I blindly assumed so too 😓

**Comment by NachoSoto** [comment]
I'll give this a try this evening.

**Comment by NachoSoto** [comment]
Except I don't have `Xcode 6.4` anymore :/ I guess I'll wait for #822.

**Comment by NachoSoto** [comment]
I just edited the issue summary with a response from Apple which basically confirms this will need to be done in `copy-frameworks`.

**Comment by NachoSoto** [comment]
I'll verify this soon!

**Comment by NachoSoto** [comment]
Verified fixed! :)
