### ISSUE TITLE
`carthage archive` spewed black smoke and machine parts, then worked

### ISSUE THREAD

**Issue by pcantrell** [Carthage/Carthage#827]
Trying to use `carthage archive`, I got a huge wad of build fail:

    $ carthage build --no-skip-current --platform ios && carthage archive Siesta
    *** xcodebuild output can be found in /var/folders/ct/_03srt6h8xj44m00r6bfmd400000gn/T/carthage-xcodebuild.ZbBK0U.log
    *** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
    *** Building scheme "Nocilla" in Nocilla.xcworkspace
    *** Building scheme "Quick-iOS" in Quick.xcworkspace
    *** Building scheme "Siesta" in Siesta.xcodeproj
    ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
    ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
    ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
    ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
    /tmp/xcode/DerivedData/Siesta-fmtangndjykefibpcpwtscgcpvep/Build/Intermediates/Siesta.build/Release-iphonesimulator/Siesta.build/unextended-module.modulemap:2:19: error: umbrella header 'Siesta.h' not found
    <unknown>:0: error: underlying Objective-C module 'Siesta' not found
    /Users/paul/work/bustout/siesta/Source/Networking-NSURLSession.swift:49:11: error: use of undeclared type 'NSURLSession'
    /Users/paul/work/bustout/siesta/Source/Networking-NSURLSession.swift:55:11: error: use of undeclared type 'NSURLSessionConfiguration'
    /Users/paul/work/bustout/siesta/Source/Support/Regex+Siesta.swift:39:20: error: use of undeclared type 'NSRegularExpression'

…etc….

Notice that the archive build coudn't even find platform classes.

After jiggling things and rebuilding in Xcode — but no actual changes to code or project config — the same command worked just fine.

I'm unable to reproduce the error, so this is just an annoying “could not reproduce” — but I wanted to get it on your radar. I'll report if I encounter the problem again.

**Comment by mdiep** [comment]
I'm going to close this until there's another report. Thanks!
