### ISSUE TITLE
Using Carthage makes app way bigger than with Cocoapods

### ISSUE THREAD

**Issue by benjamincombes** [Carthage/Carthage#831]
I made an empty test project, with a few dependencies (RealmSwift, Swinject, SwiftyJSON, Alamofire, RxSwift and Kingfisher).
However, just compiling this empty application makes an app of about 130Mb.
If I do the same test using Cocoapods to manage dependencies, application weight falls to about 30Mb.
Do you think I could have done something wrong? If not, is there something we can do about this?
Thanks a lot for your help, let me know if you need any additional information.

**Comment by swizzlr** [comment]
Would love to see this test project on Github; are you using the `copy-frameworks` phase to strip unnecessary symbols?

**Comment by mdiep** [comment]
I bet this will be fixed by #837.

**Comment by mdiep** [comment]
Are you still seeing that the size is much larger in the current version of Carthage?
