### ISSUE TITLE
Error when linking bitcode frameworks compiled with Carthage in Xcode 7.1 beta 3

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#833]
```
ld: bitcode bundle could not be generated because '/Users/NachoSoto/Library/Developer/Xcode/DerivedData/Build/Products/Release-watchos/Result.framework/Result' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7k
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

> All frameworks and dylibs for bitcode must be generated from **Xcode Archive or Install build for architecture armv7k**

But `Result` **was** built with full bitcode support (https://github.com/antitypical/Result/pull/94).
See #535 for more details.

I wonder if it's time for Carthage to build frameworks with `archive` instead? :/

**Comment by mdiep** [comment]
> I wonder if it's time for Carthage to build frameworks with `archive` instead?

Sounds like it.

I'd like to make the switch, but was unsure how to test the behavior. Should I just do it and cut a release?

**Comment by NachoSoto** [comment]
I'm happy to test that myself before merging :)

**Comment by NachoSoto** [comment]
Maybe if we're lucky this will even fix http://www.openradar.me/22993940

**Comment by NachoSoto** [comment]
Closing this: turns out my problem was a discrepancy between `ReactiveCocoa`'s `Cartfile` and the submodules pointed to by `.gitmodules`. I didn't realize until now that since `ReactiveCocoa` is building the dependencies inside, what's in `Cartfile` is only relevant when it comes to fetching those frameworks, but what `RAC` will actually build depends on the submodules.

That's a separate conversation to have, but it seems to me that this deserves some consideration. Let me know if that has been thought about before, otherwise I'm happy to open a separate issue!

**Comment by aventurella** [comment]
I'm actually seeing this same issue, but I am using Alamofire (also ReactiveCocoa, but you already called out that issue). This only happens during archiving, not during Build and Run on a device or Simulator.
