### ISSUE TITLE
Support for .bundles and other additions to the project?

### ISSUE THREAD

**Issue by kgn** [Carthage/Carthage#845]
How are additional things besides the `.framework` intended to be included in the project? I'm using [NSDate-TimeAgo](https://github.com/kevinlawler/NSDate-TimeAgo) in an app and I'd like to submit a pull request to add Carthage support. But I don't see anything in the Carthage README about supporting additional things like the `NSDateTimeAgo.bundle` in this project. How should this be handled?

**Comment by swizzlr** [comment]
A framework is a bundle, so I think you'd be able to just add the files to the framework target :)

**Comment by kgn** [comment]
Good point, thanks! I'll test that out to confirm and close the ticket once I know it's working.

**Comment by kgn** [comment]
I've confirmed it works, I had to change how the files are loaded from the Framework. But in doing so I wrote some tests and found some other issues with the library ;) Yeah TDD: https://github.com/kevinlawler/NSDate-TimeAgo/pull/92
