### ISSUE TITLE
carthage copy-frameworks should copy dSYMs too

### ISSUE THREAD

**Issue by kballard** [Carthage/Carthage#854]
I'd love to see `carthage copy-frameworks` copy the relevant dSYMs into the build products folder as well. My PR #853 for bcsymbolmaps adds a flag `--copy-bcsymbolmaps` that defaults to enabled for archive builds, and I think it makes sense to add a similar flag for dSYMs. That way archives always have the dSYMs, and the user can use `carthage copy-frameworks --copy-dsyms` to get dsyms in non-archive builds too (which we should also recommend, just as we recommend today that a Copy Files build phase be added for dSYMs).

**Comment by kballard** [comment]
Although we may want to consider not automatically copying dSYMs for watchOS, because any framework used in both iOS and watchOS that has the same name for both platforms can cause problems in archiving. #830 describes a situation where having a dSYM named the same for both platforms fails to archive, and I believe the only solution there is to not copy watchOS dSYMs.

**Comment by ikesyo** [comment]
Closed by #1023.
