### ISSUE TITLE
command prompt of "carthage update" works incorrectly when github account logged off

### ISSUE THREAD

**Issue by arbipher** [Carthage/Carthage#857]
I run "carthage update" on my project directory, but find that it get stunk after prompting me to enter my github account. "Username for 'https://github.com': " appears three times before I do anything. I don't press any key before I input my account "arbipher@gmail.com". After input I press enter, it seems nothing going on.

于 zhuan/ 吾曰: carthage update
*** Cloning ReactiveCocoa
*** Cloning Result
*** Cloning Box
Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': arbipher@gmail.com

Though the problem can be solved easily, I wonder there're sth wrong in the updating script.

**Comment by mdiep** [comment]
What's the output of `carthage version` and `git --version`?

This shouldn't happen if you're on a newer version of both.

**Comment by arbipher** [comment]
`carthage version 0.8.0`
`git version 1.8.3.1`

I use [`git credential`](https://git-scm.com/docs/git-credential-cache) to save my github password. I don't know whether it's relevant to the problem.

in my .gitconfig
[credential]
    helper = cache --timeout=36000

**Comment by mdiep** [comment]
Upgrading to a recent version of `git` (>= 2.3) will fix this issue.

**Comment by arbipher** [comment]
Thanks. I will update my git soon.

**Comment by mdiep** [comment]
Feel free to reopen this issue if you experience issues after updating!

**Comment by arbipher** [comment]
I update OS X to El Capitan and git to to `version 2.4.9 (Apple Git-60)`. Problem solved.
