### ISSUE TITLE
Carthage create feature

### ISSUE THREAD

**Issue by pepibumur** [Carthage/Carthage#858]
### What?
I think it would be great to have a command for Carthage like:

```
carthage create MyLib
```
That would guide the developer across the creation of a library project with the following components:
- XCode project with framework targets for each platform
- A test target for the library
- Automatically created README file with steps to integrate the library in your projects using Carthage
- Travis.yml script

### Why?
It would make it easier for developers to setup the project quickly and start working on the library/framework.

I've started working on it in this fork https://github.com/gitdoapp/Carthage.
If you have any ideas or proposal to make it as closes as possible to the Carthage philosophy, please let me know.

**Comment by NachoSoto** [comment]
I like the idea, but to me it seems a bit out of the scope of Carthage.

**Comment by taiheng** [comment]
This sounds like it could be done in an Xcode project template instead of creating a carthage command for it.

**Comment by pepibumur** [comment]
Alright @NachoSoto , I'll create a command line tool for it instead.
@taiheng it involves something more apart from a simple XCode template: project configuration, target, schemes, ..
