### ISSUE TITLE
🔥 iTunes Connect breaks Carthage frameworks for yet another reason 🔥

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#859]
I haven't had time to file a radar yet (not that it's going to matter):
<img width="797" alt="screen shot 2015-10-21 at 22 35 55" src="https://cloud.githubusercontent.com/assets/685609/10657736/b5d8d444-7844-11e5-9361-ef092060bab6.png">

Now `frameworks`' versions in their `plist`s must match the version of the app being archived (or at least be higher than the last released version (?) for whatever reason)
![angry bear](https://cloud.githubusercontent.com/assets/685609/10657756/e73bf57a-7844-11e5-9686-e157c56c441e.gif)

*Also, which is "this bundle" and "the `Info.plist`"?*

So together with #824, this is yet another thing that will need to be changed in Carthage for 7.1 releases...

**Comment by NachoSoto** [comment]
This reminds me of [this other radar](http://www.openradar.me/20395191). Who doesn't love Xcode?

**Comment by norio-nomura** [comment]
Is this related document?
[Technical Note TN2420: Version Numbers and Build Numbers](https://developer.apple.com/library/prerelease/ios/technotes/tn2420/_index.html#//apple_ref/doc/uid/DTS40016603-CH1-WATCHKIT_APPS_AND_APPS_WITH_SUB_FRAMEWORKS) said:
> - WatchKit Apps and apps with sub-frameworks
>
> For WatchKit apps, and apps including sub-frameworks, you must use the same Version Number for all of your targets in your Xcode project. You must also use the same Build Number for all of the targets in your Xcode project.

**Comment by NachoSoto** [comment]
Is that new?

**Comment by norio-nomura** [comment]
> Document Revision History
> 2015-10-08
New document that talks about the Version Numbers and Build Numbers used in App Store submissions.

**Comment by heiberg** [comment]
Not only this, but they are also enforcing that versions are now (at most 3) dot-separated numbers:

`ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString 'HEAD based on 0.1.0' in the Info.plist file must be a period-separated list of at most three non-negative integers.", ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '4.0.2-alpha-1' in the Info.plist file must be a period-separated list of at most three non-negative integers.", ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '0.6-beta.1' in the Info.plist file must be a period-separated list of at most three non-negative integers."
`

**Comment by abiaad** [comment]
Same here https://forums.developer.apple.com/thread/23581

**Comment by Thomvis** [comment]
@heiberg thanks for mentioning this! I noticed this a few weeks ago and thought that I was misremembering that it was once allowed to have alphanumeric version numbers.

Apart from the debatable change that framework versions must match the app version, would you say that frameworks should have their up to date version in the info.plist? I think a lot of frameworks just have the default version number in there and only use the git tag / podspec version.

**Comment by RuiAAPeres** [comment]
>  you must use the same Version Number for all of your targets in your Xcode project.

It mentions the targets versions, but not the sub frameworks themselves.

**Comment by heiberg** [comment]
I'd say that's just sloppy technical writing. Those targets are defined somewhere. In the different framework repos if you're using Carthage, in the generated Pods.* files if you're using Cocoapods or in your own project if they are yours to build. Regardless, they now have to have a version matching your app.

**Comment by RuiAAPeres** [comment]
@heiberg for a moment I was hoping for it to be a bug. But if this behaviour is "as intended" it makes absolutely no sense. Why would I have to care about the version a 3rd party framework? :/

**Comment by emiliopavia** [comment]
I think this can be related to this:

> Binary Compatibility and Frameworks
> While your app’s runtime compatibility is ensured, the Swift language itself will continue to evolve, and the binary interface will also change. To be safe, all components of your app should be built with the same version of Xcode and the Swift compiler to ensure that they work together.
>
> This means that frameworks need to be managed carefully. For instance, if your project uses frameworks to share code with an embedded extension, you will want to build the frameworks, app, and extensions together. It would be dangerous to rely upon binary frameworks that use Swift — especially from third parties. As Swift changes, those frameworks will be incompatible with the rest of your app. When the binary interface stabilizes in a year or two, the Swift runtime will become part of the host OS and this limitation will no longer exist.

**Comment by fatuhoku** [comment]
+1 I've run into this, but with Cocoapods. Pretty annoying if you ask me.

**Comment by zats** [comment]
I think it's more or less clear by now, that the issue is not localised to Xcode 7.1, it happened to me while using `iTMSTransporter -m verify` (Xcode 7.0.1) so it's most likely coming from iTC.
A good point by Peter Steinberger: modifying Info.plist (especially when dealing with proprietary 3rd party frameworks) might result in unpredictable behaviour, as frameworks might use the version number to workaround particular bugs, conditionally enable features, use different dialect communicating to server API etc.
Any chance anyone ran into a workaround not involving modifying frameworks versions?

**Comment by joshdholtz** [comment]
Haven't found a workaround yet but definitely not tied to Xcode 7.1. I'm still on Xcode 6.4 (sadly because of Swift 1 stuff) and I'm also having the exact same issues.

**Comment by jeremiegirault** [comment]
I just managed to build and deploy a version on iTunes connect with 7.0.1.
I did not need to change my dependencies versions.
We use a keyboard extension and it was required to use the same version/build number in the .app and .appex, but not on .framework dependencies. 

Can you make sure that it is about a .framework and not a .appex where it is enforced ?

**Comment by swizzlr** [comment]
If you're satisfied modifying the plist works in your case, give this a crack, passing in the version number you want for the frameworks:

```bash
#!/bin/bash

for plist in ./Carthage/Build/iOS/*/*.plist ; do
  if [ -e "$plist" ] ; then   # Check whether file exists.
     plutil -replace 'CFBundleShortVersionString' -string $1 $plist
  fi
done
```

**Comment by swizzlr** [comment]
This technique worked for me today.

**Comment by kballard** [comment]
Yesterday I was getting errors about this (frameworks whose versions were lower than my previously-submitted application version):

![screen shot 2015-10-21 at 3 37 17 pm](https://cloud.githubusercontent.com/assets/714/10673781/8dcc0832-78ac-11e5-9c07-21e38458eb54.png)

Today, when resubmitting the exact same archive, the only error is that CocoaLumberjack's build version is "2.0.0-rc":

![screen shot 2015-10-22 at 10 26 08 am](https://cloud.githubusercontent.com/assets/714/10673794/9bfd3d86-78ac-11e5-8353-7ca5a8cc24e5.png)

So it sounds like they reverted the change that compares embedded framework versions to the previous app version, and are instead only validating that the embedded framework version string is parseable.

I will find out in a few minutes as to whether changing CocoaLumberjack's version to "2.0.0" is sufficient to submit.

**Comment by kballard** [comment]
I have now confirmed, after changing just CocoaLumberjack's version from "2.0.0-rc" to "2.0.0", I was able to successfully upload a build.

**Comment by NachoSoto** [comment]
We'd have to change how we do versioning in lots of frameworks like `RAC` and `Result`.
Many people are confirming that the framework versioning change was reverted, but [I can't confirm this yet](https://twitter.com/nachosoto/status/657268227156762624) :fire:

**Comment by joshdholtz** [comment]
I have `RAC` and `Result` in my app and a version just uploaded and processed in ITC successfully for me (for the versions I was using) :ok_hand:

**Comment by NachoSoto** [comment]
Which versions were you using? Based on the other feedback, something like `v4.0-alpha.1` would no longer be accepted.

**Comment by joshdholtz** [comment]
**RAC** - `v3.0-RC.1` (the Info.plist has a short version of `1.0`)
**Result** - `0.4.4` (the Info.plist has a short version of `0.0.1`)

**Comment by NachoSoto** [comment]
Ooooh right, we don't actually change those versions in the `plist`s (because why would we)

**Comment by neilpa** [comment]
> Ooooh right, we don't actually change those versions in the plists (because why would we)

Maybe we should match the git tags in the future (sans pre-release info)

**Comment by NachoSoto** [comment]
Confirmed: this issue has been resolved (for the time being)
![huh](https://cloud.githubusercontent.com/assets/685609/10677848/a2f6f84a-78c3-11e5-9642-0c06362e468a.gif)

**Comment by mdiep** [comment]
![](https://media.giphy.com/media/ReImZejkBnqYU/giphy.gif)

**Comment by lucasmilin** [comment]
I manage to submit my app with the following steps:

```shell
carthage checkout
```

Write a scrit Shell and run sh script.sh 1.0 1.0
```shell
#!/bin/bash
for i in `find . -name "*.plist"`; do
  echo $i;

  plutil -replace 'CFBundleShortVersionString' -string $1 $i
  plutil -replace 'CFBundleVersion' -string $2 $i
done;
```

```shell
carthage build
```
