### ISSUE TITLE
Archive failed with Xcode 7.1

### ISSUE THREAD

**Issue by tomassliz** [Carthage/Carthage#863]
When I try to archive project with one library which is built with Carthage I get this error:
```
ld: bitcode bundle could not be generated because '/Users/Deny/Desktop/MyProject/
Carthage/Build/iOS/SWXMLHash.framework/SWXMLHash' was built without full bitcode.
All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install
build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I can fix that if I add library's project file in workspace, but this is weird. Project is clean a bitcode is enabled by default.

**Comment by ikesyo** [comment]
See #535 and #839.

**Comment by tomassliz** [comment]
@ikesyo I read both issues but I'm still confused. It's something bad with 3rd party library? It has `ENABLE_BITCODE = true`. Why is everything OK after adding library's project file to project's workspace?

**Comment by ikesyo** [comment]
Carthage using `xcodebuild build`, so the built frameworks do not contain _full bitcode_ (contain only _bitcode marker_) if `BITCODE_GENERATION_MODE=bitcode` is not set at v0.9.3.

> Why is everything OK after adding library's project file to project's workspace?

In that case, I think, the framework embedded in your app archive should be built by Xcode, not by Carthage, so the framework was built by `archive` command and that contains _full bitcode_.

**Comment by tomassliz** [comment]
And how can I set BITCODE_GENERATION_MODE=bitcode ? I have to add it directly in project file? Because I did not find option like this in project settings.

**Comment by ikesyo** [comment]
As a user-defined setting in `SWXMLHash`.

**Comment by tomassliz** [comment]
Can you be more specific? I don't know where is user-defined settings in Xcode. Sorry for this stupid question :-(

**Comment by ikesyo** [comment]
<img width="1440" alt="2015-10-25 10 20 34" src="https://cloud.githubusercontent.com/assets/909674/10713585/14852c58-7b02-11e5-9386-224127e68266.png">

**Comment by tomassliz** [comment]
Thank you :+1:

**Comment by tomassliz** [comment]
@ikesyo And do you know something about AppStore export error?
```
The archive did not contain <DVTFilePath:0x7fdfa842de00:'/Users/Deny/Library/Developer/Xcode/Archives/2015-10-25/MyProject 25-10-15 02.27.xcarchive/BCSymbolMaps/8F19A6B0-90DB-3FC2-A816-586F63199D29.bcsymbolmap'> as expected.
```

**Comment by ikesyo** [comment]
That is already tracked in #853. Or you should off "Include App Symbols".
