### ISSUE TITLE
Failure of one build component fails the entire cartfile

### ISSUE THREAD

**Issue by weaksauce** [Carthage/Carthage#864]
issuing a `carthage update` does not build all the targets because one of the github projects fails to build in a platform I don't care about. 

cartfile of:

```
github "a2/MessagePack.swift" "master"
github "alexeyxo/protobuf-swift"
github "robbiehanson/CocoaAsyncSocket" "master"
github "izqui/Taylor"
```

fails because CocoaAsyncSocket doesn't build correctly for the tv os. 

I would hope to see a link to the logfile of the broken build inside the broken framework and continue on building all that it can build. Or some indication that carthage stopped prematurely and there wasn't some missing build target or something missing from the repo similar to a podspec that stopped the build for those targets. 

all I get is a parse error which can be fatal or not. 

`Parse error: unexpected SDK key "appletvos"`

Ideally I would like to only build for the platforms I care about and have carthage try to build as much as possible.

**Comment by ikesyo** [comment]
> Ideally I would like to only build for the platforms I care about and have carthage try to build as much as possible.

There is `--platform` option: ``

**Comment by ikesyo** [comment]
> continue on building all that it can build.

This makes sense to me, if we can control the behavior with an option.

**Comment by ikesyo** [comment]
> `Parse error: unexpected SDK key "appletvos"`

This is because you are using Carthage 0.8 or older. 0.9 and newer support tvOS platform.

**Comment by mdiep** [comment]
> continue on building all that it can build

I actually think it's best to stop when a component fails to build.

1. Presumably if it's in the Cartfile, you need it—having every dependency but one won't help you

2. Continuing to build would obscure the error

In the above, `--platform` is the way to go.

**Comment by weaksauce** [comment]
Thanks for the info. perhaps adding a summary at the end of what was successful or not would make things clearer? 

> Presumably if it's in the Cartfile, you need it—having every dependency but one won't help you

perhaps. When doing some exploratory coding I might put a few things in the the cart file
