### ISSUE TITLE
Carthage hangs then fails on strange nested dependency fetch

### ISSUE THREAD

**Issue by JRHeaton** [Carthage/Carthage#867]
**EDIT**: I _was_ in fact making an error. See the https://github.com/Carthage/Carthage/issues/867#issuecomment-151291642.

Hi, I'm having some issues with Carthage. Hoping it's just me doing something wrong; any help is great 😊. I'm working on a framework, "framework A", a project that resolves its dependencies through Carthage. Two of those dependencies(Mantle and a local fork of another library, "framework B") have their own Cartfiles for dependencies. To clarify: A depends on B and Mantle.

**IMPORTANT NOTE**: I am using a version of `carthage` built right off of `swift2` this morning, using this script:
```sh
cd /tmp
git clone https://github.com/Carthage/Carthage.git
cd Carthage
git checkout swift2
make package
sudo installer -pkg Carthage.pkg -target /
```

This is because the latest actual release of Carthage still has the issue where you have to manually nuke `Carthage/Checkouts` before every single bootstrap/update/checkout, which was eating a lot of my time.

### `Cartfile` in framework A:
```
git "file:///Users/j/dev/ProjectB"
github "Mantle/Mantle" ~> 2.0
```

### `Cartfile` in local fork framework B:
```
github "Alamofire/Alamofire" ~> 3.0
github "ReactiveCocoa/ReactiveCocoa"	"v4.0.0-alpha.3"
github "ReactiveX/RxSwift" "2.0.0-beta.1"
```

So I'm in the directory of framework A, and run `carthage update ...`. This is what happens:
```sh
➤ carthage update --platform iOS --no-use-binaries --use-submodules
*** Fetching Mantle
*** Fetching Moya
*** Fetching Alamofire
*** Checking out Alamofire at "3.1.0"
*** Checking out Mantle at "2.0.5"
*** Checking out Moya at "4.0.3"
*** xcodebuild output can be found in /var/folders/p0/bkngm_y52t9f0kk9c_p2hkkc0000gn/T/carthage-xcodebuild.fLBzK0.log
*** Fetching ReactiveCocoa
*** Fetching Result
*** Fetching Box
*** Fetching LlamaKit
Failed to discover shared schemes in project iOS Example.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/Alamofire/Alamofire/issues/new
```

And note that it hangs on `*** Fetching LlamaKit` for a few minutes.

### Issue
 I can't seem to find out what's going on here. Project B has no dependency on Box/LlamaKit, nor does project A. I also don't see a Cartfile on RxSwift's repo, and RAC/Mantle don't depend on it either. Where are these dependencies coming from? And also, what's going on that's causing Carthage to not be able to successfully resolve A and B's deps and build them like normal?

For reference, here is the log of `carthage update ...` within project B's directory:
```sh
➤ carthage update --platform iOS --no-use-binaries --use-submodules
*** Fetching RxSwift
*** Fetching ReactiveCocoa
*** Fetching Alamofire
*** Fetching Result
*** Checking out Alamofire at "3.1.0"
*** Checking out Result at "0.6.0-beta.5"
*** Checking out RxSwift at "2.0.0-beta.1"
*** Checking out ReactiveCocoa at "v4.0.0-alpha.3"
*** xcodebuild output can be found in /var/folders/p0/bkngm_y52t9f0kk9c_p2hkkc0000gn/T/carthage-xcodebuild.gjN7Gq.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "RxBlocking-iOS" in Rx.xcworkspace
*** Building scheme "RxCocoa-iOS" in Rx.xcworkspace
*** Building scheme "RxSwift-iOS" in Rx.xcworkspace
*** Building scheme "ReactiveCocoa-iOS" in ReactiveCocoa.xcworkspace
```

**Comment by mdiep** [comment]
Hmm… that's weird. It sounds like the resolver might be having problems. If you pass the `--no-checkout` option to `carthage update`, does the same thing happen?

**Comment by JRHeaton** [comment]
@mdiep 
```sh
➤ carthage update --platform iOS --no-use-binaries --use-submodules --no-checkout
*** Fetching Mantle
*** Fetching Moya
*** Fetching Alamofire
```

It can't know the nested deps until it checks out the first ones, understandably.

**Comment by JRHeaton** [comment]
Okay, so I've figured out the issue, and where the mysterious dependencies came from. Framework B as mentioned was a forked repository. I was making changes on a branch that wasn't master, and thus the first `Cartfile` should look like this:
```
git "file:///Users/j/dev/ProjectB" "myBranch"
github "Mantle/Mantle" ~> 2.0
```

And it works as expected. Sorry for the false alarm.

**Comment by qwertywer** [comment]
[ git "file:///Users/j/dev/ProjectB" "myBranch" ]
 @JRHeaton Can you please explain the above line because I am completely new to this stuff .
Actually I was trying to instal SwiftyJSON older version via cathage and got the same error
[ Failed to discover shared schemes in project Example.xcodeproj — either the project does not have any shared schemes, or xcodebuild timed out.]
