### ISSUE TITLE
What is the right way to specify transitive dependencies?

### ISSUE THREAD

**Issue by marcpalmer** [Carthage/Carthage#868]
I'm puzzled by Carthage's dependency resolution or lack thereof. 

Here's my scenario:

I had Carthage working, migrated all my internal libs to frameworks with their own Cartfiles, and found/forked 3rd party OSS dependencies to make them play with Carthage.

My app built, all was good, I was happy with Carthage.

Now I try to build my app dependencies with Carthage and it crashes / errors (depends...) trying to fetch CocoaLumberjack branch "swift_2.0", because that no longer exists.

Obviously that is bad. Tags shouldn't go away. However the issue is more that my internal libs had to depend on that specific "swift_2.0" branch because CocoaLumberjack was not Swift 2 compatible on any releases.

_Anyway_... now I am in a position where I have to update all of my transitive dependencies' `Cartfile` to remove the dependency on the defunct branch. This is quite onerous. It is correct of course, but it seems weird that there is apparently no way for my *project* to override the dependency with the correct one.

Am I Carthaging wrong?

**Comment by mdiep** [comment]
I think this is all as-expected. It's just a major disadvantage to using tags. (One that should probably be documented.)

If you were on proper versions, then Carthage would let you specify a more specific version in your app target—so long as it was compatible with all the versions specified by your dependencies. But with tags, there's no way for Carthage to know that different versions are compatible.

**Comment by marcpalmer** [comment]
Surely in this case however, the app's declared (or resolved) version should win?

**Comment by marcpalmer** [comment]
This also implies that any 3rd party framework that has a Cartfile containing tags is essentially a viral liability for your build.

**Comment by mdiep** [comment]
> Surely in this case however, the app's declared (or resolved) version should win?

There's a general rule: All cartfiles must be compatible. You can't specify a version in your app targets that's incompatible with other version requirements for that dependency. Tags follow that rule, but a tag is only compatible with itself.

> This also implies that any 3rd party framework that has a Cartfile containing tags is essentially a viral liability for your build.

Yup. Tags are essentially unversioned. Unversioned dependencies are a liability.

**Comment by marcpalmer** [comment]
OK. Thanks for the detail, much appreciated. Personally I'd be in favour of a warning when updating dependencies "Dependency X contains a tag dependency on Y with tag Z instead of a semantic version. Your builds will break if your app needs to move to a different version of Y". That's if I've understood you correctly.
