### ISSUE TITLE
Carthage hangs when trying to determine compatibility

### ISSUE THREAD

**Issue by paulyoung** [Carthage/Carthage#869]
When running `carthage update --no-build --use-submodules --no-use-binaries` on a particular branch of our project, it consistently hangs during the cloning phase.

There's no issue when using `git submodule update` instead.

FWIW, I've been removing `Carthage/Checkouts` beforehand because #835 hasn't made it into a release yet. I've also tried removing any directories referencing carthage in `~/Library/Caches`.

I'd love to provide more info if possible.

**Comment by paulyoung** [comment]
I figured out that there was only one difference to the `Cartfile` on the branch in question and created a standalone project that contained the new dependency, along with ReactiveCocoa since they both depend on Result in one way or another.

Here's the output:

```
Could not pick a version for github "antitypical/Result", due to mutually incompatible requirements:
	"0.6.0-beta.5"
	"0.6.0-beta.3"
```

I think the real issue here is not in fact cloning but with trying to determine if the dependencies can be satisfied within a reasonable time.

There are a lot more entries in the `Cartfile` of the actual project, so maybe that's a factor. I don't think any of the others are related though.

**Comment by mdiep** [comment]
That sounds right to me. Since there's not an obvious set of versions that satisfies all constraints, the resolver tries increasingly more arcane versions. It takes a while to exhaust all options. I think tags behave particularly bad currently.

**Comment by mdiep** [comment]
That sounds right to me. Since there's not an obvious set of versions that satisfies all constraints, the resolver tries increasingly more arcane versions. It takes a while to exhaust all options. I think tags behave particularly bad currently.
