### ISSUE TITLE
Can't link app with CocoaLumberjack with bitcode enabled

### ISSUE THREAD

**Issue by marcpalmer** [Carthage/Carthage#870]
I'm trying to build a small framework that depends on CocoaLumberjack.

Carthage is downloading the CocoaLumberjack binary, and then fails to link:

```
ld: bitcode bundle could not be generated because '/Library/Developer/XcodeServer/Integrations/Caches/3212366d3753e1ead6e227f55d0076a2/Source/MetaprogrammingFramework/Carthage/Build/iOS/CocoaLumberjack.framework/CocoaLumberjack' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

...I am guessing this is because the CocoaLumberjack binary does not contain bitcode. Running `otool -o` on the framework binary includes no output containing "bitcode" or "LLVM" which are believe are indicators of its presence.

Is this because they have archived + released CocoaLumberjack without bitcode enabled?

If so, how do we force Carthage to build that dependency from source instead of the binary archive. Also, if this is the actual problem, Carthage should really pick up on this and choke on the binary if we are building for bitcode and there's no bitcode in the binary archive, right?

Thanks in advance....

**Comment by marcpalmer** [comment]
The one confounding factor here is that Archiving my framework works locally (7.1 beta 3). Its only my Xcode 7.1 GM server that it fails on. Any clues?

**Comment by marcpalmer** [comment]
Ok more info. CocoaLumberjack's watchOS binary includes bitcode it seems:
```
Marcs-MBP:CocoaLumberjack.framework marc$ otool -l CocoaLumberjack | grep LLVM
  segname __LLVM
   segname __LLVM
```
Whereas the iOS does not.

So it would seem that binary distributions are problematic in that Carthage choses these over source by default even if they are binary incompatible with what you are trying to link (in Xcode archiving terms).

Is this a fair assessment? What is the solution?

**Comment by marcpalmer** [comment]
Unsurprisingly, setting `Enable Bitcode` to NO in my framework's project allows it to build on the 7.1 server. So I can build, but not with bitcode for non-watchOS targets.

**Comment by ikesyo** [comment]
Sorry for the very late response. Looks like the prebuilt binary was built using older Carthage release and only contained bitcode marker, not actual bitcode. This should not be issue anymore if binaries are built using today's Carthage. Closing.
