### ISSUE TITLE
Even with .pkg Carthage seems to still not work

### ISSUE THREAD

**Issue by KacheFlowe** [Carthage/Carthage#876]
Hi there. I installed the .pkg files as suggested since a Swift 2.0 version hasn't been released. But when I got to build my project, it still can't find its modules (in this case, Nimble). Any input on this?

**Comment by mdiep** [comment]
Can you post the output with the error?

**Comment by KacheFlowe** [comment]
??? I simply ran the package. Was there more I was supposed to do? *facePalm*

**Comment by KacheFlowe** [comment]
"module file was created by an older version of the compiler; rebuild nimble and try again..."

**Comment by mdiep** [comment]
It sounds like you need to clear Xcode's derived data.

**Comment by KacheFlowe** [comment]
Tried that. Still got the same error.

**Comment by mdiep** [comment]
Maybe try the `--no-use-binaries` flag? Or try removing all of `~/Library/Developer/Xcode/DerivedData/`?

**Comment by KacheFlowe** [comment]
I'm not sure how to use the --no-use-binaries flag. May you please explain? Also, I already tried the latter.

**Comment by mdiep** [comment]
`carthage bootstrap --no-use-binaries`

**Comment by KacheFlowe** [comment]
Alright, so that removed the cartfile...

**Comment by KacheFlowe** [comment]
This worked! Thank you very much @mdiep !!!
