### ISSUE TITLE
Specify the schemes to build.

### ISSUE THREAD

**Issue by kgn** [Carthage/Carthage#877]
I recently ran `Carthage update` and one of the frameworks I'm using added tvOS support and was causing the update to fail do to a code signing error. I've filed a bug for this to let them know, but the app I'm working on is iOS only so I don't care about the tvOS framework.

In anther issue I found there is a `--platform` argument that can be passed to `update`. Running `carthage update --platform iOS` works, but is there a way to specify in the `Cartfile` to only build the specified schemes?

i.e.

```
github "kgn/KGNUserInterface"

github "duemunk/Async" iOS
```

^ like the `--platform` argument this would cause only the iOS scheme to be built for `duemunk/Async`.

**Comment by mdiep** [comment]
No, there isn't. Sorry. You can use `--platform` to filter out schemes, but that's it.

**Comment by kgn** [comment]
Is this something you'd be open to adding to the Cartfile spec? I think it would be really useful for frameworks that build for multiple platforms to save on `update` times and to avoid issues like this.

**Comment by kgn** [comment]
Or, probably better than per framework would be a way to specify the platform at the top of the `Cartfile`:

```
platform iOS

github "kgn/KGNUserInterface"

github "duemunk/Async"
```

**Comment by mdiep** [comment]
#356 is open to discuss that idea.
