### ISSUE TITLE
Document `carthage update` and other call arguments

### ISSUE THREAD

**Issue by kgn** [Carthage/Carthage#878]
I recently discovered `carthage update --platform iOS` by reading through issues. This fixed the issue I was encountering but I would have not know about this argument if I hadn't stumbled across it. I don't see any documentation currently that defines what the additional arguments are to the `update` and other commands. I tried `carthage update --help` but that just started an update.

**Comment by NachoSoto** [comment]
You can do `carthage help` and `carthage help update`.

**Comment by kgn** [comment]
Thanks @NachoSoto!
