### ISSUE TITLE
how to load Carthage into Xcode, by Terminal ?

### ISSUE THREAD

**Issue by javakian** [Carthage/Carthage#881]
Hello I am  creating a Rest API and trying to load the module binaries so SwiftSon will operate.

any suggestions.

thank you,

James Avakian, iOS Mobile Developer
Optical Automation

**Comment by mdiep** [comment]
Were you able to figure out how to add the frameworks to Xcode?

**Comment by ikesyo** [comment]
Closing this for now. Feel free to reopen if you have any updates or further information!
