### ISSUE TITLE
Carthage update specific framework

### ISSUE THREAD

**Issue by pepibumur** [Carthage/Carthage#882]
Hi!
I was thinking about implementing a feature like
```
carthage update ReactiveCocoa
```
That looks for that dependency in your `Cartfile` and if it's there it updates **only** that dependency. I've faced problems before with some dependencies and I ended up commenting the rest in order to make Carthage only compiling the one I needed.

Has the Carthage team thought about it? What do you think? I could help you with it.
Thanks in advance

**Comment by ikesyo** [comment]
I think this is already captured in #610 and #618.

**Comment by pepibumur** [comment]
Yeah, it's the same, closing this.
