### ISSUE TITLE
Don't code sign iOS simulator builds if iphonesimulator code sign identity not found

### ISSUE THREAD

**Issue by JRHeaton** [Carthage/Carthage#887]
iOS framework targets built for the simulator don't need code signed, and in situations where you want to run build/unit tests on CI on your project but 1 or more of the dependency frameworks don't have `CODE_SIGN_IDENTITY[sdk=iphonesimulator*] = ""`, this becomes impossible, since they will not be built for any sdk. It shouldn't need to be a manual configuration requirement in order to have Carthage build frameworks for simulator on machines that don't have the set simulator identity; ideally, it could be aware that it could fall back.

**Comment by mdiep** [comment]
I'm pretty :-1: on this idea.

Xcode does magic crap like this all the time. It yields incomprehensible results. It's impossible to discern the rules, which inevitably leads to confusion down the road.

Carthage favors simplicity over ease. For the minor, one-time cost of adding that setting to dependent frameworks, Carthage retains simpler behavior and a simpler implementation.

**Comment by JRHeaton** [comment]
Sure, but you don't necessarily have control over dependencies' projects. _If_ they want to make the change (or accept a PR), then you're okay, and at the expense of time, and for no reason (Any iOS framework target should be build-able for the simulator, with codesign worries out of the mind). Since there is no actual _need_ to code sign a simulator framework target, what's the harm in just not requiring it?

At the very least, what about adding documentation on how you can properly set up your projects that you want to make available via Carthage as a compromise?

**Comment by NachoSoto** [comment]
> Sure, but you don't necessarily have control over dependencies' projects.

Thanks to Carthage ease, you can simply fork the project, make the change, update your `Cartfile`, and build :)

**Comment by JRHeaton** [comment]
> Thanks to Carthage ease, you can simply fork the project, make the change, update your Cartfile, and build :)

Ah, true I didn't consider that option. Though for the case where you depend on a framework that itself has dependencies in a `Cartfile`, and the issue is with a dependency in that `Cartfile`, you're then looking at forking both projects, fixing the code signing in one, and pointing the Cartfile in the other to your fork of it. This can of course extend to more levels than 2. Then if they won't merge your fork, you're looking at keeping yours up to date.

All of that extra work for _every_ person using that library through Carthage on a machine where CS identities can't be installed, because of someone else's lack of specific configuration to _exclude_ a build setting that is present by default but unnecessary and problematic. Sounds not like cutting down on complexity to me 😥

**Comment by mdiep** [comment]
> What about adding documentation on how you can properly set up code signing in your projects that you want to make available via Carthage as a compromise?

That sounds like a great idea to me. :+1: Would you be interested in opening a PR?

> Feels not like cutting down on total complexities to me

I'm definitely sympathetic to that. But tackling this inside Carthage could become an issue down the road.  Carthage has required framework owners to make some changes to their projects, which is annoying at the outset. But it requires people to have properly configured projects, which is a good thing overall IMO.

Our stance has been that building with Carthage shouldn't really be different than building yourself inside Xcode. That's served us pretty well so far, and I think it will serve us well going forward.
