### ISSUE TITLE
Improve locating shared framework targets

### ISSUE THREAD

**Issue by chbeer** [Carthage/Carthage#888]
Some framework projects contain more than one Xcode project / workspace for framework and samples.

Carthage sometimes fails to find the correct project/workspace because it seems to limit the discovery to the first project file it finds (where the projects even don't seem to be ordered in some kind).

This should be improved to take all project files into account and maybe even iterate over all that contain shared frameworks.

**Comment by ikesyo** [comment]
This is captured in #892. :wink:

**Comment by ikesyo** [comment]
Closed by #892.
