### ISSUE TITLE
Invalid architecture UUIDs: Could not parse UUIDs using dwarfdump

### ISSUE THREAD

**Issue by Palleas** [Carthage/Carthage#889]
**Disclaimer**: I've posted this issue in realm/realm-cocoa#2785 thinking it was Realm-related but it seems it may have something to do with Carthage's `copy-framework`

I'm getting the following error when I try to setup Realm in my iOS application using Carthage:

```
$ carthage update --use-submodules --platform ios
*** Fetching realm-cocoa
*** Fetching keychain-swift
*** Fetching SwiftyJSON
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out Result at "0.6.0-beta.3"
*** Checking out SwiftyJSON at "2.3.0"
*** Checking out keychain-swift at "3.0.7"
*** Checking out ReactiveCocoa at "9af5f32b4f9f908ae5f26904fbaf49d0a9039e24"
*** Checking out realm-cocoa at "v0.96.2"
*** xcodebuild output can be found in /var/folders/tk/cw93k7v928qf21kppt47d_380000gn/T/carthage-xcodebuild.0HflvL.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
*** Building scheme "KeychainSwift" in KeychainSwift.xcodeproj
*** Building scheme "iOS" in Realm.xcodeproj
Invalid architecture UUIDs: Could not parse UUIDs using dwarfdump from /Users/Romain/Library/Developer/Xcode/DerivedData/Realm-acrmeedomupvqhcepjsgrlqtlowg/Build/Products/Release-iphoneos/Realm.framework/Realm
```

Any idea what could be causing this? I've attached the [xcodebuild full log here](https://gist.github.com/Palleas/7567e783a235ef1dde54) and here is my Cartfile:

```
github "ReactiveCocoa/ReactiveCocoa" "swift2"
github "SwiftyJSON/SwiftyJSON" "2.3.0"
github "exchangegroup/keychain-swift" "3.0.7"
github "realm/realm-cocoa"
```

This doesn't seem to be an issue with Carthage because it really fails as soon as I add Realm in my Cartfile and run cartage update.

I'm using Xcode 7.1:  
```
xcodebuild -version
Xcode 7.1
Build version 7B91b
```

and Carthage 0.9.4:
```
carthage version
0.9.4
```

Thanks !

**Comment by gilazo** [comment]
I'm have the same issue with Parse-SDK

**Comment by ikesyo** [comment]
Carthage does not support static frameworks. See #734 and #894.

@gilazo Parse-SDK and Facebook SDK are not Carthage-compatible since Bolts is using a static framework for iOS platform.
