### ISSUE TITLE
Fat Framework XCTest dependency

### ISSUE THREAD

**Issue by alan-honeycutt** [Carthage/Carthage#890]
1) Create a custom framework (Cocoa Touch Framework) that uses XCGLogger (managed by Carthage)
2) Build the framework for iOS using Carthage --no-skip-current
3) Create a client project that uses the custom framework
4) Attempt to build the client project

At this point, you will be faced with a "framework not found XCTest for architecture x86_64" error. The reason for this is that Carthage is building the Test target for XCGLogger and including that in the fat library, creating an XCTest link dependency.

Is there a way to make Carthage not build the XCGLogger test target when creating the .framework file for that project? I am able to build and use my custom framework and XCGLogger using xcodebuild and lipo, but I'd like to let Carthage handle that instead of having to roll my own shell script solution.

**Comment by ikesyo** [comment]
https://github.com/Carthage/Carthage/issues/515#issuecomment-107914969 would be the help?

**Comment by alan-honeycutt** [comment]
I don't think that's the issue. I've created a couple of projects to demonstrate this issue:

https://github.com/alan-honeycutt/CarthageDynamicFrameworkWithDependency
https://github.com/alan-honeycutt/CarthageDynamicFrameworkClient

I'm using carthage to build the framework and then using the resulting framework in the client as an embedded binary. If you open the client project and try to build it, you'll see the linker error "framework not found XCTest for architecture x86_64".

If you go into the framework project, download the XCGLogger dependency and uncheck the "Run" build option for XCGLoggerTests (iOS) [which is indeed checked by default in that project], you will still get this linker error using the framework. Even if that worked, I wouldn't want to have to edit dependency projects to build my framework.

Please let me know if you need further info to reproduce the issue.

**Comment by Aleksion** [comment]
Hi - did you figure out how to solve this. I've run into the exact same issue.

**Comment by alan-honeycutt** [comment]
Negative, @Aleksion. I'm going down the CocoaPods route at the moment to see if it "just works" out of the box. I prefer the "dependency management without the magic" that Carthage offers, but if it doesn't allow me to package my own dynamic frameworks, it's not an option.

**Comment by alan-honeycutt** [comment]
Update: Turns out it's very easy to create your own dynamic frameworks using CocoaPods, so I'm abandoning Carthage for my current project. "Lots of magic that works" beats "A little magic that doesn't."

**Comment by kweinmeister** [comment]
FYI, there was a similar issue filed recently in the XCGLogger project: https://github.com/DaveWoodCom/XCGLogger/issues/103

**Comment by ikesyo** [comment]
It seems that this should be fixed now in its [3.1.1](https://github.com/DaveWoodCom/XCGLogger/releases/tag/Version_3.1.1) release with https://github.com/DaveWoodCom/XCGLogger/pull/102.

**Comment by ikesyo** [comment]
Closing this, https://github.com/DaveWoodCom/XCGLogger/pull/102 is merged and https://github.com/DaveWoodCom/XCGLogger/issues/103 is closed.
