### ISSUE TITLE
error while carthage update

### ISSUE THREAD

**Issue by zixun** [Carthage/Carthage#896]
I add the neon to my  Cartfile,but while Im  run  carthage update commond，terminal show an error:

      *** Fetching Neon
      *** Checking out Neon at "v0.0.2"
      *** xcodebuild output can be found in /var/folders/5y/x8t9wb3d1t33b77ckz509p_w0000gn/T/carthage-xcodebuild.JEhAhQ.log
     A shell task failed with exit code 66:
     xcodebuild: error: Scheme NeonMacDemo is not currently configured for the build action.

**Comment by mdiep** [comment]
Which version of Carthage are you using?

This sounds like a project configuration issue. What's the URL for Neon?

**Comment by zixun** [comment]
I install Carthage by .pkg file today,so it's the last version,
this is the repo url:    [Neon](https://github.com/mamaral/Neon)

**Comment by ikesyo** [comment]
That is because the project contains the `NeonMacDemo` scheme, but there is no corresponding `NeonMacDemo` target in the project. The scheme should be removed.

It is really a configuration issue on that repo as @mdiep said.

**Comment by zixun** [comment]
@ikesyo  OK,thank you

**Comment by zixun** [comment]
@ikesyo  buy the way,I have a question:

is carthage will auto build all scheme ? how to tell carthage not build one of the schemes. such as [xxx-ios,xxx-osx],how to not build xxx-osx

**Comment by ikesyo** [comment]
@zixun In that case, you can pass `--platform` options as follows:

```bash
carthage build --platform ios // you can also use comma separated values "--platform ios,osx"
```

**Comment by zixun** [comment]
@ikesyo I see, thank you .and another question:
I have a repo, and it depends on some of other repos. and my application is using my repo by carthage.
while I run the carthage update,  other repos will build success,but my repo is not.show me an error in console:

**Comment by ikesyo** [comment]
I'm not sure what the build failure is. You should check the log file at first.

**Comment by zixun** [comment]
@ikesyo  how to check the log file

**Comment by ikesyo** [comment]
Just open the pass of ` xcodebuild output can be found in ...`.

**Comment by zixun** [comment]
@ikesyo  I cant find the path of xcodebuild output,where is it?

**Comment by dcaunt** [comment]
@zixun Carthage outputs the path, in your console output above it was 

>*** xcodebuild output can be found in /var/folders/5y/x8t9wb3d1t33b77ckz509p_w0000gn/T/carthage-     xcodebuild.Uh3CE2.log

**Comment by zixun** [comment]
@dcaunt  thank you ~ I found it

**Comment by zixun** [comment]
@dcaunt @ikesyo  is there any <option> at carthage build  to only build current scheme,not build dependence scheme?
