### ISSUE TITLE
Skipping build for "macosx" SDK because the necessary signing identity "-" is not installed

### ISSUE THREAD

**Issue by tylerlong** [Carthage/Carthage#897]
Just updated to 0.10.0, I got the following warning:

> *** WARNING: Skipping build for "macosx" SDK because the necessary signing identity "-" is not installed

It worked with 0.8.0. 

Some libraries have this warning while some don't. Could some one give me some hints on how to fix this?

**Comment by mdiep** [comment]
I think you need to set the `Code Signing Identity` build setting to `Don't Code Sign`.

Carthage should probably recognize `-` as meaning no signing identity.

**Comment by tylerlong** [comment]
@mdiep it works!

By the way, after setting `Code Signing Identity` build setting to `Don't Code Sign`. I did a git diff:


```
Tylers-Mac-mini:ENTabBarView tylerlong$ git diff
diff --git a/ENTabBarView.xcodeproj/project.pbxproj b/ENTabBarView.xcodeproj/project.pbxproj
index e47b2f8..c1d90af 100644
--- a/ENTabBarView.xcodeproj/project.pbxproj
+++ b/ENTabBarView.xcodeproj/project.pbxproj
@@ -244,6 +244,7 @@
                D4AE180F1BECE6AA00DA933D /* Debug */ = {
                        isa = XCBuildConfiguration;
                        buildSettings = {
+                               CODE_SIGN_IDENTITY = "";
                                COMBINE_HIDPI_IMAGES = YES;
                                DEFINES_MODULE = YES;
                                DYLIB_COMPATIBILITY_VERSION = 1;
@@ -263,6 +264,7 @@
                D4AE18101BECE6AA00DA933D /* Release */ = {
                        isa = XCBuildConfiguration;
                        buildSettings = {
+                               CODE_SIGN_IDENTITY = "";
                                COMBINE_HIDPI_IMAGES = YES;
                                DEFINES_MODULE = YES;
                                DYLIB_COMPATIBILITY_VERSION = 1;
```


By default, Xcode new project doesn't have `CODE_SIGN_IDENTITY` settings. I think it just means no  signing identity. Carthage should be smart enough to recognize.

**Comment by mdiep** [comment]
> By default, Xcode new project doesn't have CODE_SIGN_IDENTITY settings. I think it just means no signing identity. Carthage should be smart enough to recognize.

I'm going to reopen this to track that issue. :+1:
