### ISSUE TITLE
Brew installation failing for 0.10

### ISSUE THREAD

**Issue by Abizern** [Carthage/Carthage#898]
After installation: when I try to get the version I get an error message:

```
~ ❯❯❯ carthage version
dyld: Symbol not found: __TWPO11CarthageKit13CarthageErrorSs9ErrorTypeS_
  Referenced from: /usr/local/bin/carthage
  Expected in: /Library/Frameworks/CarthageKit.framework/CarthageKit
 in /usr/local/bin/carthage
[1]    11336 trace trap  carthage version
```

**Comment by mdiep** [comment]
Did you previously install Carthage from the `.pkg` installer? It looks like you did, in which case you'll need to remove `/Library/Frameworks/CarthageKit.framework`. The homebrew version of `carthage` is trying to use the `.pkg` version of `CarthageKit.framework`.

**Comment by Abizern** [comment]
I had indeed. Sorted.

Is it worth me doing a PR with an updated README?
