### ISSUE TITLE
module was not compiled for testing error

### ISSUE THREAD

**Issue by aleph7** [Carthage/Carthage#903]
If I enable compiling the testing target every time I build I get the following error when running `carthage update`:

```
The following build commands failed:
	CompileSwift normal x86_64 .../Carthage/Checkouts/HDF5Kit/Tests/FileTests.swift
	CompileSwift normal x86_64 .../Carthage/Checkouts/HDF5Kit/Tests/Helpers.swift
	CompileSwift normal x86_64 .../Carthage/Checkouts/HDF5Kit/Tests/GroupTests.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(4 failures)
.../Carthage/Checkouts/HDF5Kit/Tests/FileTests.swift:8:18: error: module 'HDF5Kit' was not compiled for testing
.../Carthage/Checkouts/HDF5Kit/Tests/FileTests.swift:8:18: error: module 'HDF5Kit' was not compiled for testing
.../Carthage/Checkouts/HDF5Kit/Tests/FileTests.swift:8:18: error: module 'HDF5Kit' was not compiled for testing
A shell task failed with exit code 65:
** BUILD FAILED **
```

Cartfile contents:
```
github "aleph7/HDF5Kit" ~> 0.0.6
```

Setting I'm referring to:
<img width="898" alt="screen shot 2015-11-06 at 12 09 49 pm" src="https://cloud.githubusercontent.com/assets/167236/11007532/5d35d8c2-847f-11e5-92a9-c88587bd2bb7.png">

**Comment by ikesyo** [comment]
Carthage uses Release configuration to build frameworks, and normally "Enable Testability" is yes only for Debug configuration. I recommend not to build the test target on other than Test action for the library users.

**Comment by ikesyo** [comment]
Closing this for now. Feel free to reopen if you have any updates or further information!
