### ISSUE TITLE
An option to skip bootstraping and building dependencies from Cartfile.private

### ISSUE THREAD

**Issue by carlossless** [Carthage/Carthage#904]
So I'm currently using carthage to automate bootstraping, building and archiving my frameworks. However using `--no-skip-current` is pretty wasteful because it builds the dependencies for targets in the project that are not necessary for the main Framework scheme, which I keep in `Cartfile.private`. Maybe it would make sense to add another option that builds the current framework only?

I also believe that this might be a problem in `carthage update` because it locks in public and private dependencies in one `Cartfile.resolved` and there's not really any nice way to know which should be built for "private" builds and "public" ones, everything is presumed public.

**Comment by carlossless** [comment]
Closing due to this not getting any outside interest.

**Comment by jeeftor** [comment]
you are too impatient

**Comment by carlossless** [comment]
Issues can always be reopened. Is this something that you want implemented?
