### ISSUE TITLE
Setting up carthage for a repo containing just binaries

### ISSUE THREAD

**Issue by RonanMcH** [Carthage/Carthage#907]
Hi,
this is more of a question than an issue.  If I want to set up carthage for a framework in a repo but the repo only contains the binaries (closed source), how do I get carthage to still pplace the binaries into the carthage build folder as it would normally when someone links our framework with carthage?
Thanks in advance,
Ronan.

**Comment by mdiep** [comment]
The only way to get Carthage to download binaries is to attach them to GitHub Releases.
