### ISSUE TITLE
Carthage should print exact task invocations for debugging

### ISSUE THREAD

**Issue by swizzlr** [Carthage/Carthage#91]
Also, what exactly are the heuristics for picking which of the many shared schemes a workspace might have?

**Comment by jspahrsummers** [comment]
Generalized this to include Git tasks too, because [some](https://github.com/Carthage/Carthage/issues/135) of its errors can be pretty opaque, especially if you have no idea what Carthage was doing when the problem occurred.

**Comment by mdiep** [comment]
Fixed by #986. Git aren't printed, but that's covered by #630.
