### ISSUE TITLE
Carthage hangs after asking for GitHub username

### ISSUE THREAD

**Issue by jasonsilberman** [Carthage/Carthage#911]
I am using Carthage version `0.10.0` and when I try to login to GitHub after running `carthage update` it asks me for my username and after I enter it and hit enter it just hangs. When I run `git config --get credential.helper` I get `osxkeychain` which is correct.

Any idea how to get this to work? Thanks

**Comment by furyu-ikeda-sho** [comment]
What is your `git --version`?

**Comment by ikesyo** [comment]
What is your `git --version`?

**Comment by jasonsilberman** [comment]
I am using `git version 2.1.3.36.g8e36a6d`

**Comment by ikesyo** [comment]
Could you upgrade to 2.3 or later? We are using the `GIT_TERMINAL_PROMPT` feature of git 2.3.

https://github.com/blog/1957-git-2-3-has-been-released#the-credential-subsystem-is-now-friendlier-to-scripting
