### ISSUE TITLE
Segmentation fault: 11 - No object named "Swift-2.0" exists

### ISSUE THREAD

**Issue by mahmoud-cliqz** [Carthage/Carthage#913]
I am getting this error when trying to run `carthage update` on `firefox-ios` repository: https://github.com/mozilla/firefox-ios 

    *** Fetching ios_sdk
    *** Fetching google-breakpad-ios
    *** Fetching XCGLogger
    *** Fetching SWXMLHash
    *** Fetching SWTableViewCell
    *** Fetching SQLite.swift
    *** Fetching Snap
    *** Fetching SDWebImage
    *** Fetching readability
    Failed to check out repository into ~/Library/Caches/org.carthage.CarthageKit/dependencies/Snap: No object named "Swift-2.0" exists

    Caught signal triggered by the Swift runtime!
    Segmentation fault: 11

Here is the `Cartfile`

    github "Alamofire/Alamofire"        "swift-2.0"
    github "mozilla/Base32"             "swift-2.0"        # So we don't have to tag a release for Emily's fixes.
    github "mozilla/Deferred"           "master"           # Making Deferred extensible in swift 2.0
    github "swisspol/GCDWebServer"                         # Implicit: latest tag.
    github "kif-framework/KIF"          "master"
    github "ZaBlanc/RaptureXML"         "master"
    github "mozilla/readability"        "master"
    github "rs/SDWebImage"              "master"           # To get the fix for libwebp
    github "Masonry/Snap"               "Swift-2.0"
    github "st3fan/SQLite.swift"        "swift-2"
    github "CEWendel/SWTableViewCell"                      # Implicit: latest tag.
    github "st3fan/SWXMLHash"           "xcode-7.0"        # So we get Swift 2.0 fixes.
    github "DaveWoodCom/XCGLogger"      "swift_2.0"        # Previously: swift_1.2
    github "sleroux/google-breakpad-ios" "master"
    github "adjust/ios_sdk"             "v4.3.0"

I am working with Xcode `Version 7.0.1 (7A1001)`

**Comment by ikesyo** [comment]
`Masonry/Snap` (now it is [`SnapKit/SnapKit`](https://github.com/SnapKit/SnapKit)) has `swift-2.0` branch, but does not have `Swift-2.0` branch. This should be the issue on the `firefox-ios` repo.

**Comment by ikesyo** [comment]
And also the branch is already merged in master and its latest releases are Swift 2 compatible. There is no need to use that branch.

**Comment by ikesyo** [comment]
You should check the pull request: https://github.com/mozilla/firefox-ios/pull/1208

**Comment by mahmoud-cliqz** [comment]
Thanks it is working now but I have another problem now, I am getting this error now

    Failed to read file or folder at /private/var/folders/75/l87skls57_929plzg7tsx0100000gn/T/carthage-archive.YSZCkG/Adjust.framework

I have deleted this folder and tried again then got the same error

**Comment by ikesyo** [comment]
[adjust/ios_sdk](https://github.com/adjust/ios_sdk) does not support Carthage (it does not have dynamic framework targets) and the attached framework binaries are invalid format (they don't contain `Info.plist`). So you should use `carthage update --no-use-binaries` as [`checkout.sh`](https://github.com/mozilla/firefox-ios/blob/168d786dc9648554b4475a2c461cd4485a07e05a/checkout.sh) of the repo does.

**Comment by mahmoud-cliqz** [comment]
thanks
