### ISSUE TITLE
Archive upload fails with nested dependencies

### ISSUE THREAD

**Issue by heyalexchoi** [Carthage/Carthage#916]
Carthage seems to be creating directories that cause archived build uploads to fail.

![invalid_bundle_error](https://cloud.githubusercontent.com/assets/4961047/11105676/753817fa-889e-11e5-8dbe-1bed83aed052.png)

In my case, the issue seems to come from a 'Frameworks' folder generated by carthage for my application's subdependency. 

![screen shot 2015-11-11 at 6 17 03 pm](https://cloud.githubusercontent.com/assets/4961047/11105975/7d347c30-88a0-11e5-9733-3004999f6024.png)

I've been able to 'fix' the problem by deleting the dependency's 'Frameworks' folder, but I was wondering if there was a more correct way of handling this. I believe Cocoapods' build script searches for this folder and deletes it. If Carthage doesn't already have a correct way of dealing with this, then I am reporting this as an issue.

My app's cartfile includes:
```
github "spenrose/AmazonS3RequestManager" "feature/carthage"
```

which has a cartfile in turn that includes:
```
github "Alamofire/Alamofire" == 3.0.0
github "drmohundro/SWXMLHash" ~> 2.0
```

Build Setting Embedded Content Contains Swift Code is set to No in the dependency as well as the application.

**Comment by NachoSoto** [comment]
Which version of `carthage` are you using?

**Comment by ikesyo** [comment]
It seems that this is because `spenrose/AmazonS3RequestManager` is embedding its dependencies in itself. This should be avoided and the dependencies should be embedded / linked at an application level.

**Comment by heyalexchoi** [comment]
@NachoSoto 0.10.0
@ikesyo I fixed my issue. thanks for your help!

**Comment by NachoSoto** [comment]
@heyalexchoi glad to hear!
