### ISSUE TITLE
Is the section on Copying dSYMs required anymore / outdated?

### ISSUE THREAD

**Issue by Abizern** [Carthage/Carthage#918]
Following #853 Do the dysms need to be manually copied over anymore?

**Comment by NachoSoto** [comment]
They don't! Thanks for bringing it up :)

**Comment by Abizern** [comment]
I wouldn't mind - but I'd also like to add documentation for the flags for showing when running `carthage help copy-frameworks` If you could point me to where I can start for that I'd like to take a stab at adding that documentation as well.

**Comment by ikesyo** [comment]
IIRC #853 didn't add copying dSYM files functionality.

**Comment by ikesyo** [comment]
That is captured in #854.

**Comment by Abizern** [comment]
It didn't - I got mixed up with bcsymbolmap stuff.

**Comment by ikesyo** [comment]
Closing this with the reasons: https://github.com/Carthage/Carthage/issues/918#issuecomment-156197985 and https://github.com/Carthage/Carthage/pull/919#issuecomment-156210353
