### ISSUE TITLE
0.10.0 hangs during build, uses max CPU

### ISSUE THREAD

**Issue by bcattle** [Carthage/Carthage#926]
Hey guys,  I looked through the issues and I believe this is a new one. Running `carthage update` causes a situation where the first several schemes build, then the `carthage` process hangs with CPU consumption 100%. I've run it several times and it's hung on two different schemes ("OCMock" and "MacBolts"). 

My `Cartfile`: 

    git "../ISUtils" "master"
    github "rs/SDWebImage"
    github "kishikawakatsumi/UICKeyChainStore"
    github "Mantle/Mantle"
    github "plausiblelabs/plcrashreporter"
    github "facebook/facebook-ios-sdk"
    github "TTTAttributedLabel/TTTAttributedLabel"
    github "slackhq/SlackTextViewController"
    github "getsentry/raven-objc"
    github "erikdoe/ocmock"

Output from running `carthage update`:

    $ carthage update
    *** Fetching ocmock
    *** Fetching raven-objc
    *** Fetching SlackTextViewController
    *** Fetching TTTAttributedLabel
    *** Fetching facebook-ios-sdk
    *** Fetching plcrashreporter
    *** Fetching Mantle
    *** Fetching UICKeyChainStore
    *** Fetching SDWebImage
    *** Fetching ISUtils
    *** Checking out ISUtils at "ba1870806c9c7850b82009e02b6a1cebf673dd12"
    *** Downloading UICKeyChainStore.framework binary at "v2.1.0"
    *** Checking out plcrashreporter at "1.2"
    *** Checking out SlackTextViewController at "v1.7.2"
    *** Downloading Mantle.framework binary at "2.0.5"
    *** Checking out facebook-ios-sdk at "sdk-version-4.8.0"
    *** Checking out SDWebImage at "3.7.3"
    *** Checking out TTTAttributedLabel at "1.13.4"
    *** Checking out raven-objc at "1.0.1"
    *** Downloading ocmock.framework binary at "OCMock 3.2"
    *** Checking out ocmock at "v3.2"
    *** xcodebuild output can be found in /var/folders/9g/m814156n0k1bgh4vndpzhx_w0000gn/T/carthage-xcodebuild.CkJDDv.log
    *** Building scheme "ISUtils" in ISUtils.xcodeproj
    *** Building scheme "WebImage" in SDWebImage.xcworkspace
    *** Building scheme "SlackTextViewController" in SlackTextViewController.xcodeproj
    *** Building scheme "TTTAttributedLabel" in TTTAttributedLabel.xcodeproj
    *** Building scheme "MacBolts" in FacebookSDK.xcworkspace
    ^C

The end of the build log file:

    $ tail -f  /var/folders/9g/m814156n0k1bgh4vndpzhx_w0000gn/T/carthage-xcodebuild.CkJDDv.log

    ProcessPCH /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/PrecompiledHeaders/Bolts-Prefix-dgjnokxiklhurngujknxobhqhirt/Bolts-Prefix.pch.pch Bolts/Bolts-Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/bryan/Documents/koowalla-ios/Carthage/Checkouts/facebook-ios-sdk/Bolts-IOS
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c-header -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/bryan/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/bryan/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Xclang -fmodule-implementation-of -Xclang Bolts -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wdocumentation -Wunreachable-code -Wimplicit-atomic-properties -Warc-repeated-use-of-weak -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wunknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wselector -Wstrict-selector-match -Wundeclared-selector -Wdeprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.7 -g -Wno-sign-conversion -iquote /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Bolts-generated-files.hmap -I/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Bolts-own-target-headers.hmap -I/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Bolts-all-non-framework-target-headers.hmap -ivfsoverlay /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/all-product-headers.yaml -iquote /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Bolts-project-headers.hmap -I/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Products/Release/include -I/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/DerivedSources/x86_64 -I/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/DerivedSources -F/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Products/Release -MD -MT dependencies -MF /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/PrecompiledHeaders/Bolts-Prefix-dgjnokxiklhurngujknxobhqhirt/Bolts-Prefix.pch.d -c /Users/bryan/Documents/koowalla-ios/Carthage/Checkouts/facebook-ios-sdk/Bolts-IOS/Bolts/Bolts-Prefix.pch -o /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/PrecompiledHeaders/Bolts-Prefix-dgjnokxiklhurngujknxobhqhirt/Bolts-Prefix.pch.pch --serialize-diagnostics /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/PrecompiledHeaders/Bolts-Prefix-dgjnokxiklhurngujknxobhqhirt/Bolts-Prefix.pch.dia

    CompileC /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Objects-normal/x86_64/BFTaskCompletionSource.o Bolts/Common/BFTaskCompletionSource.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/bryan/Documents/koowalla-ios/Carthage/Checkouts/facebook-ios-sdk/Bolts-IOS
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/bryan/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/bryan/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Xclang -fmodule-implementation-of -Xclang Bolts -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wdocumentation -Wunreachable-code -Wimplicit-atomic-properties -Warc-repeated-use-of-weak -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wunknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wselector -Wstrict-selector-match -Wundeclared-selector -Wdeprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.7 -g -Wno-sign-conversion -iquote /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Bolts-generated-files.hmap -I/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Bolts-own-target-headers.hmap -I/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Bolts-all-non-framework-target-headers.hmap -ivfsoverlay /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/all-product-headers.yaml -iquote /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Bolts-project-headers.hmap -I/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Products/Release/include -I/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/DerivedSources/x86_64 -I/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/DerivedSources -F/Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Products/Release -include /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/PrecompiledHeaders/Bolts-Prefix-dgjnokxiklhurngujknxobhqhirt/Bolts-Prefix.pch -MMD -MT dependencies -MF /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Objects-normal/x86_64/BFTaskCompletionSource.d --serialize-diagnostics /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Objects-normal/x86_64/BFTaskCompletionSource.dia -c /Users/bryan/Documents/koowalla-ios/Carthage/Checkouts/facebook-ios-sdk/Bolts-IOS/Bolts/Common/BFTaskCompletionSource.m -o /Users/bryan/Library/Developer/Xcode/DerivedData/FacebookSDK-chupncdfphhzjgdrttxpavvwygty/Build/Intermediates/Bolts.build/Release/MacBolts.build/Objects-normal/x86_64/BFTaskCompletionSource.o

Output of `sample` while the carthage process was in its hung state: 

https://gist.github.com/bcattle/eb951537ccb9b038bab7

Please let me know if there's any more information I can provide. Thanks for all your hard work so far, I love the library. It was sorely needed. :)

**Comment by NachoSoto** [comment]
Thanks for opening an issue!

Can you try with `carthage update --verbose`?

**Comment by bcattle** [comment]
Hey @NachoSoto, thanks for the followup. You were right, XCode is hanging when it tries to build one of the dependencies of the `plcrashreporter` package. Specifically, the issue is with the command 

    $ /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/bryan/Documents/koowalla-ios/Carthage/Checkouts/plcrashreporter/Tools/google-toolbox-for-mac-trunk-r582/SpotlightPlugins/Installer/DeveloperSpotlightImporters.xcodeproj -list
    Information about project "DeveloperSpotlightImporters":
        Targets:
            Build DeveloperSpotlightImporters

        Build Configurations:
            Release

        If no build configuration is specified and -scheme is not passed then "Release" is used.

What was throwing me off was the fact that the `carthage` executable was showing 100% CPU utilization in `top`, but that must have been bogus. 

Thanks for the help!
