### ISSUE TITLE
Realm framework is missing in carthage/build/iOS file after cloning my rep. in another path.

### ISSUE THREAD

**Issue by crazyart** [Carthage/Carthage#934]

**Comment by mdiep** [comment]
Can you provide the output of `carthage version`, your `Cartfile`, and the output of running `carthage bootstrap`?

**Comment by crazyart** [comment]
carthage version = 0.10.0

CARTFILE  
# Use the latest version
github "Alamofire/Alamofire"

# Use the latest version
github "bitstadium/HockeySDK-iOS"

# Use the latest version
github "realm/realm-cocoa"
END CARTFILE

carthage bootstrap
*** Checking out Alamofire at "3.1.2"
*** Downloading realm-cocoa.framework binary at "v0.96.2"
*** Downloading HockeySDK-iOS.framework binary at "Version 3.8.5"
*** Checking out HockeySDK-iOS at "3.8.5"
*** xcodebuild output can be found in /var/folders/pm/2pz7tq2s06x5wq4_mj2898d40000gp/T/carthage-xcodebuild.fRrhlZ.log
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "HockeySDK Framework" in HockeySDK.xcodeproj

**Comment by mdiep** [comment]
Hmm… this works for me. I see `Realm.framework` and `RealmSwift.framework` in `Carthage/Build/iOS`. Are you sure that it's not there on your machine? Note that Realm won't be in `Carthage/Checkouts` because Carthage is downloading a binary copy of the framework that's attached to the GitHub release.

**Comment by crazyart** [comment]
I'm also see it when do carthage update, but when i try to push my project changes on git, there is missing realm framework from Carthage/Build/iOS

**Comment by mdiep** [comment]
> but when i try to push my project changes on git, there is missing realm framework from Carthage/Build/iOS

I'm not sure what you mean. Can you elaborate on what you're doing?

**Comment by ikesyo** [comment]
Closing this for now. Feel free to reopen if you have any updates or further information!
