### ISSUE TITLE
Carthage and Xcode Server - copy-frameworks error

### ISSUE THREAD

**Issue by mkutrifork** [Carthage/Carthage#939]
I'm trying to get Xcode Server to build a project which uses Carthage. I've added a script which runs before every integration:

`/usr/local/bin/carthage build ./MyProject --platform iOS --configuration Release`

Unfortunately I get an error when this command gets run:

```
bin/sh -c \"/Library/Developer/XcodeServer/Integrations/Caches/47ae21afe2d4291d13dab0d5e5002c37/DerivedData/Build/Intermediates/MyProject.build/MyProject\ Release-iphoneos/MyProject.build/Script-1DE505241BE3CCB400479092.sh\"
```

Script `Script-1DE505241BE3CCB400479092.sh` contains only one line:

`/usr/local/bin/carthage copy-frameworks`

Here is the error I get:

```
A shell task failed with exit code 1:
/Library/Developer/XcodeServer/Integrations/Caches/47ae21afe2d4291d13dab0d5e5002c37/DerivedData/Build/Products/MyProject Release-iphoneos/MyProject.app/Frameworks/Alamofire.framework: replacing existing signature
/Library/Developer/XcodeServer/Integrations/Caches/47ae21afe2d4291d13dab0d5e5002c37/DerivedData/Build/Products/MyProject Release-iphoneos/MyProject.app/Frameworks/Alamofire.framework: User canceled the operation.
```

I have no problems running the same `carthage build` command on my dev machine.

**Comment by mdiep** [comment]
I'm not sure what would case that error.

**Comment by ikesyo** [comment]
Closing this for now.
