### ISSUE TITLE
Ensuring built frameworks are identical to resolved dependencies?

### ISSUE THREAD

**Issue by tomtaylor** [Carthage/Carthage#942]
We'd like ensure that the built frameworks in `Carthage/Build/iOS` are identical to the dependencies specified in `Cartfile.resolved`, as part of our build process (probably in a build phase). Is there a mechanism for doing this, without using `carthage build` in a build phase (which is incredibly slow)?

Ideally we'd have a script that returned 0 or 1, which we could use to tell the developer they need to rebuild their dependencies before continuing.

**Comment by NachoSoto** [comment]
Did you consider including `Carthage/Build` in your repo? That way other users will automatically get updated versions of the frameworks.

**Comment by tomtaylor** [comment]
We did, it's just very big (142MB for us), and there's going to be a lot of churn on the binaries in it.

**Comment by NachoSoto** [comment]
If this is really important for you I would consider doing that, otherwise they're never going to be exactly *identical*.

**Comment by tomtaylor** [comment]
Yeah, I appreciate that, and I can see there's nothing obvious to hook into at the moment. I wonder if there's an approach which drops a file into the Build folder containing the revision that each framework was built with, which can be compared with `Cartfile.resolved`?

**Comment by mdiep** [comment]
If you did `carthage checkout --use-submodules`, you could check whether the SHA of the submodule changed.

**Comment by ikesyo** [comment]
See https://github.com/Carthage/workflows/pull/1.
