### ISSUE TITLE
Carthage: Can't import Quick/Nimble from within files in my test target

### ISSUE THREAD

**Issue by dcunited001** [Carthage/Carthage#946]
I'm working on a library [Spectra](https://github.com/dcunited001/SpectraNu) and I'm using carthage to pull down Quick/Nimble.  

Within my workspace, I've created two projects for OSX and iOS.  I've got a test target within each project.  I've followed the instructions in the [Quick docs for carthage](https://github.com/Quick/Quick/blob/master/Documentation/InstallingQuick.md).  I've added the Quick/Nimble frameworks to the build steps, but I can't seem to get the compiler to recognize `import Quick` and `import Nimble`.  The symbols aren't available to my test files.  

How do I set up my build steps for my test targets so the compiler recognizes that symbols from these frameworks should be available?  

Thank you! 

Also, Quick/Nimble aren't showing up in my workspace as projects. That's normal for carthage, right?

![preview](https://camo.githubusercontent.com/9bce0aab9dbb09af267fbe5ce79dc1e44635c5d6/687474703a2f2f662e636c2e6c792f6974656d732f32623252306531683039303033753266305a33552f53637265656e25323053686f74253230323031352d30322d32372532306174253230322e31392e3337253230504d2e706e67)

**Comment by mdiep** [comment]
It looks like you need to set the `Framework Search Paths` build setting to point to `$(PROJECT_DIR)/../Carthage/Build/Mac`, etc.

There are a few other issues with your setup that might need to be addressed as well. (I only looked at the OS X target in detail, but I'm guessing iOS has the same problems.)

1. The unit test target has the same `PRODUCT_NAME` as the framework target. This makes the module names collide, resulting in a warning from the `@testable import`.

2. `Spectra.swift` doesn't appear to actually be a part of the framework target.

3. `Spectra.xcworkspace/contents.xcworkspacedata` has absolute paths to the projects. This is an unfortunate Xcode bug. You'll probably need to hand-edit the file.

> Also, Quick/Nimble aren't showing up in my workspace as projects. That's normal for carthage, right?

It depends on how you configure the project. The way you've set it up is a valid configuration, but it's not one I use, so I'm not sure what limitations it has.

For frameworks, I like to use Carthage's `--use-submodules` flag and then add my dependencies' `.xcodeproj`s directly to my workspace. Then the project will get built as part of Xcode.

**Comment by dcunited001** [comment]
@mdiep hey, thanks so much for the advice.  i just read your comment, so i'm in the middle of trying this out.  i'm used to cocoapods, so i don't know much about the specifics of setting up an xcode workspace.

i love carthage so far though, especially the git submodules integration.  i think that makes it easier to give back to open source projects, since the repo's right there in your project.  that's awesome!

**Comment by dcunited001** [comment]
by the way, i was following [this guide](http://www.swift-studies.com/blog/2014/6/30/creating-a-pure-swift-framework-for-both-ios-and-mac) to set up a multi-project workspace, so my project works for both OSX & iOS.  

Basically, like you said, i hadn't set the `FRAMEWORK_SEARCH_PATHS` correctly.  Fixing this allowed me to import Quick/Nimble into my project

1. also, my `PRODUCT_NAME` build setting was borked.  i've fixed those and almost everything is addressed. 

2. I'm working on addressing this.  i linked in the Spectra folder to both the SpectraOSX and SpectraiOS projects.  But for some reason, i can't select targets for these files.  I'm working on figuring this out, then i should be able to `import SpectraOSX` and access those classes. 

3. I've addressed the absolute paths.  I'm guessing this was causing problems for other people who checked my project out.   

Again, thanks for helping me work through this @mdiep.  I've spent so much time on this project and i've rewritten this [Spectra](https://github.com/dcunited001/Spectra) graphics library like five times and spent so much time organizing the project files.  You can even check out the original repo -- there are completely detached trees in there, from where i wiped everything out and force pushed! lulz

though i don't think ppl will use it, i still want to set it up to work for both iOS and OSX.  yet, i imagine i might have some problems down the road, as there are some symbols for the Metal framework which prevent compilation without iOS hardware.

**Comment by mdiep** [comment]
> I'm working on addressing this. i linked in the Spectra folder to both the SpectraOSX and SpectraiOS projects. But for some reason, i can't select targets for these files. I'm working on figuring this out, then i should be able to import SpectraOSX and access those classes.

The spectra folder is included as a _reference_, which means that you can't select targets for those files. You'll need to delete the reference and re-add it as a group.

I'm going to close this since it sounds like your Carthage issues have been resolved!

**Comment by dcunited001** [comment]
@mdiep Can you give me some quick advice for structuring my library? 

- Is there a good project where I can check out the XCode workspace setup?  
- Instead of setting up a project for each framework, can I use preprocessor directives like `@available(OSX 10.11, *)`?  Yet, if I use this approach, classes can't be redeclared and extensions are problematic because they don't support certain features in swift.

So I'm running into some issues structuring my library in XCode.  Also, I'm not sure it will build if someone pulls it with carthage, since there are separate projects for iOS & OSX.  The Metal framework has different capabilities for each platform and this is the source of my confusion.  

What's the best way to get this set up within a single project? 
- Where it can be built/ran/tested on both platforms 
- To be included as a framework with carthage on either iOS/OSX
- While allowing slightly different implementations of classes and methods for a small set of features

I'm also running into naming issues.  When the Spectra-OSX project is built, i use `import SpectraOSX` and similar for iOS.  But then I can't have a common set of test files for both frameworks.  And any top level references to `SpectraOSX` or `SpectraiOS` are problematic. I could change the name of the framework that's built for each.

Thanks!

**Comment by mdiep** [comment]
https://github.com/ReactiveCocoa/ReactiveCocoa has a good Xcode workspace setup.

Since Metal is a built-in framework, I would add it directly to the target/project.

When I'm creating a framework, I usually:

 1. Create one `.xcodeproj`
 2. Create one framework target for each platform as part of that `.xcodeproj` (You can also find information about so-called universal frameworks.)
 3. Give each framework target a different platform-specific name, but override the actual `PRODUCT_NAME` to be the same (`Spectra` in this case.)
 4. Create one `.xcworkspace` that creates the above `.xcodeproj` and the `.xcodeproj`s from all your dependencies
 5. Add each source file to each framework target. (This is easy to do if you select them all in the project navigator (Cmd-1) and select the `Target Membership` in the file inspector (Cmd-Opt-1)).
6. Create unit tests frameworks in the `.xcodeproj` that target each platform and include the platform framework
