### ISSUE TITLE
Copy frameworks without carthage

### ISSUE THREAD

**Issue by ivan-ushakov** [Carthage/Carthage#948]
I'm faced with requirement to have project working on machine without carthage installed. As I understand the only problem is `copy-framework` phase. Could you please guide me how to do this step just with Xcode tools?

**Comment by mdiep** [comment]
You'll probably want to look over [the code](https://github.com/Carthage/Carthage/blob/master/Source/carthage/CopyFrameworks.swift).

**Comment by ikesyo** [comment]
Closing this for now. Feel free to reopen if you have any updates or further information!
