### ISSUE TITLE
Carthage 0.11 via homebrew:

### ISSUE THREAD

**Issue by flovilmart** [Carthage/Carthage#958]
dyld: Symbol not found: __TMdO13ReactiveCocoa7NoError
  Referenced from: /usr/local/bin/carthage
  Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
 in /usr/local/bin/carthage
Trace/BPT trap: 5

**Comment by mdiep** [comment]
You must have previously installed the .pkg or run make install or something. Delete `/Library/Frameworks/CarthageKit.framework` and you should be good to go.

**Comment by flovilmart** [comment]
Ok thanks :) reinstalled via the pkg
