### ISSUE TITLE
Project with both a static lib and dynamic lib target, carthage should skip the static lib

### ISSUE THREAD

**Issue by bstrull** [Carthage/Carthage#959]
Bolts (https://github.com/BoltsFramework/Bolts-iOS) has two iOS targets, one that builds a static lib and one that builds a dynamic lib.  carthage build --platform iOS will find the static lib target first and fail.

Either carthage should skip the static lib target, or provide an option to help identify which targets should be built.

**Comment by mdiep** [comment]
Which version of Carthage are you using? I thought we improved this in a recent release.

**Comment by ikesyo** [comment]
Closing this since it is already implemented in [0.10](https://github.com/Carthage/Carthage/releases/tag/0.10).
