### ISSUE TITLE
Verbose isn't verbose enough

### ISSUE THREAD

**Issue by mpurland** [Carthage/Carthage#960]
This is especially the case when fetching, checking out, and the very beginning of the update process.

**Comment by mdiep** [comment]
#630 is tracking that `--verbose` should print the output from `git`. Is there something else you think that Carthage should print? Or does that cover it?

**Comment by mpurland** [comment]
Yes, that would do it I think. Didn't see the other issue when I created this one.

**Comment by mdiep** [comment]
:+1:
