### ISSUE TITLE
carthage with xcode 7.1.1 won't copy frameworks to Build folder

### ISSUE THREAD

**Issue by chainone** [Carthage/Carthage#964]
Take "github "ankurp/Dollar.swift" ~> 4.0.1" for example
there are two shared schemas, however only Cent.framework shows up in Build folder for iOS platform

command line I use:  carthage update --platform ios --use-submodules

**Comment by chainone** [comment]
Any update?

**Comment by ikesyo** [comment]
This is a dupe of #644 and already tackled in #892.
