### ISSUE TITLE
Cartfile that references current repository

### ISSUE THREAD

**Issue by groue** [Carthage/Carthage#965]
Hello,

I want to test Carthage integration. For that, I wish I had, in my main repo, a directory which contains a test app, and a Cartfile that references the **local sources**.

For the context, I'm struggling with shared schemes vs. test targets. People complain when a shared scheme references test targets, but I need to share test targets if I want a stable working environment. And you do not provide any guidance about this topic. So I'm struggling. And testing. End of the context.

OK so I need a Cartfile that references the **local sources**. So far, I can't make it work. Sample failing Tests/Carthage/Cartfile:

```
# A shell task failed with exit code 128:
# fatal: destination path '/Users/groue/Library/Caches/org.carthage.CarthageKit/dependencies/..' already exists and is not an empty directory.
git "../.." "master"

# A shell task failed with exit code 128:
# fatal: '../../../GRDB' does not appear to be a git repository
# fatal: Could not read from remote repository.
# (NB): this is false: ../../../GRDB/.git indeed exist.
git "../../../GRDB" "master"

# Parse error: expected submodule commit SHA in ls-tree output: 
git "~/Documents/git/groue/GRDB" "master"
```

The last error is surprising, since `cd /tmp && git clone ~/Documents/git/groue/GRDB` works perfectly.

Do you have any advice? Of course, the only good path is "../..", the only one that does not depend on the actual checkout of the repository (no dependency on username, no dependency on home folder organization, no dependency on the path of the checkout, etc.)

**Comment by ikesyo** [comment]
It seems that you don't need a Cartfile in this case and you could just run `carthage build --no-skip-current`.

**Comment by groue** [comment]
Thanks for the help, @ikesyo, it does build the local sources indeed!

Is there a way to move the product Carthage directory somewhere else than at the top level? I guess I can live with it there, if there is no way to specify the output directory.

**Comment by groue** [comment]
Anyway, I had my answer. Thanks again @ikesyo.

**Comment by ikesyo** [comment]
> Is there a way to move the product Carthage directory somewhere else than at the top level? I guess I can live with it there, if there is no way to specify the output directory.

There isn't.

Additionally, if you'd really like to use local git repository in a Cartfile, #398 would help.
