### ISSUE TITLE
Carthage not downloading a fork of previously built repo

### ISSUE THREAD

**Issue by richlowenberg** [Carthage/Carthage#967]
I've made a fork of CryptoSwift (https://github.com/krzyzanowskim/CryptoSwift), and would like Carthage to check out my fork instead, at https://github.com/richlowenberg/CryptoSwift, however every time it fetches it seems to get the original. A git clone call with the same url gets the correct data. I am verifying by watching the checkouts folder during the update call. I previously checked out and built the original.

Could this be a caching issue?

**Comment by robertmryan** [comment]
And you made your Cartfile point to your repo? And did you add a tag for your version so Carthage knows to use the new committed/pushed code?

**Comment by richlowenberg** [comment]
The Cartfile points to my repo, but I didn't add a tag - I guess that's the problem? By adding the specific commit hash I was able to get it to work. Apologies if I missed that in the docs.

**Comment by robertmryan** [comment]
Yep, tag it. This is mentioned casually in the documentation regarding what one "should" do with stable releases, and it fails to make it absolutely clear that this is central to what carthage will pull.

Anyway, to upgrade from 1.0 to 1.0.1, you do:

    git tag "1.0.1"
    git push --tags

**Comment by richlowenberg** [comment]
Ah yes, I see that. Thanks! All makes sense now.
