### ISSUE TITLE
Fetching repositories won't finish during `carthage update`

### ISSUE THREAD

**Issue by minhoryang** [Carthage/Carthage#976]
used command:
`carthage update --verbose --platform iOS`

used Cartfile:

``` Cartfile
github "Alamofire/Alamofire" ~> 3.0
github "Hearst-DD/ObjectMapper" ~> 1.0
github "tristanhimmelman/AlamofireObjectMapper" ~> 2.1
github "realm/realm-cocoa"
github "nickoneill/PermissionScope" ~> 1.0
github "ReactiveX/RxSwift" "2.0.0-beta.3"
github "Moya/Moya" "5.1.0"
```

I cleaned Carthage's caches repository and retried several times.
But tiny changes resolved this issue :) ...?

``` Cartfile
github "Alamofire/Alamofire" ~> 3.0
github "Hearst-DD/ObjectMapper" ~> 1.0
github "tristanhimmelman/AlamofireObjectMapper" ~> 2.1
github "realm/realm-cocoa"
github "nickoneill/PermissionScope" ~> 1.0
#github "ReactiveX/RxSwift" "2.0.0-beta.3"  # TODO : WTF?!
github "Moya/Moya" "5.1.0"
```

Perhaps, ReactiveX/RxSwift is needed to build Moya/Moya as dependency chain.
But Alamofire & ObjectMapper is also needed for AlamofireObjectMapper.
I don't know why, but It resolved and gave the relax to me.

Want to know it, Thanks!

**Comment by minhoryang** [comment]
Carthage 0.11.0 (homebrew-ed)
Brew 0.9.5 (git revision aeee; last commit 2015-12-03)
git version 2.6.3 (homebrew-ed)

**Comment by ikesyo** [comment]
I'm not sure why it hangs, but `github "ReactiveX/RxSwift" "2.0.0-beta.3"` and `github "Moya/Moya" "5.1.0"` are incompatible, since Moya 5.1.0 depends on RxSwift 2.0.0-beta.2: https://github.com/Moya/Moya/blob/5.1.0/Cartfile

**Comment by akolov** [comment]
I have a similar issue: Carthage never finishes either checking out or downloading binaries and spins at full cpu usage, as soon as I add specific repository to Cartfile. This issue started appearing with 0.11.0.

My Cartfile: 
```
github "akolov/Bureaucracy" ~> 1.3
github "akolov/cloudinary_ios" "framework"
github "akolov/SwiftHelpers" ~> 1.3
github "akolov/XCTestCaseExtensions" ~> 1.0.4
github "akolov/adjust" "dynamic-framework"
github "akolov/YouTubePlayer" ~> 1.3.1
github "akolov/VimeoPlayer" ~> 1.3
github "akolov/Swell" "master"
github "akolov/TSMessages" "framework"
github "robb/Cartography" ~> 0.6.0
github "stylight/stylight-ios-lib" ~> 1.5.5
github "stylight/stylight-ios-lib-2" ~> 2.4.9 # this library causes infinite spin
```

Cartfile for stylight-ios-lib-2:
```
github "alamofire/Alamofire" ~> 3.0
github "akolov/Swell" "master"
github "realm/realm-cocoa" ~> 0.96.2
github "SwiftyJSON/SwiftyJSON" ~> 2.3.0
```

**Comment by minhoryang** [comment]
@ikesyo Oh! That's Why!!!!! Now I get it +1 !!!!

**Comment by marcvanolmen** [comment]
I'm new to carthage and using version 0.11 and I have seen it a few times a day that the carthage update just is stuck and has high cpu usage, can't compare with other versions...

**Comment by cocoahero** [comment]
This may be related to #940

**Comment by adamstener** [comment]
Seeing the problem here too.  Will fetch and build most dependencies, but anything that has a sub-dependency is failing to fetch the child.

**Comment by adamstener** [comment]
I was seeing this before 0.11, figured I would do an upgrade to fix the issue, got 0.11 and seeing the same issue.

**Comment by adamstener** [comment]
Deleted everything and started over and everything works now with 0.11

**Comment by guidomb** [comment]
I keep seeing the high CPU usage and hang in version `0.11.0` even after deleting the `Carthage` folder. Here is my `Cartfile.resolved`

```
github "Wolox/WLXBluetoothDevice" ~> 0.6.1
github "Wolox/WLXBluetoothDeviceReactiveExtensions" ~> 0.7.0
github "ReactiveCocoa/ReactiveCocoa" "v4.0.0-alpha.5"
github "CocoaLumberjack/CocoaLumberjack" ~> 2.2.0
```

**Comment by ssarangi** [comment]
This issue is still happening with 0.18.0... I have a Cartfile which works with 0.11.0 but doesn't with 0.18.0...

**Comment by ajaysinghthakur** [comment]
same problem here stuck with Braintree repo

github "braintree/braintree_ios" ~> 4.7.2

**Comment by OscarDPan** [comment]
same problem here stuck with card.io

github "card-io/card.io-iOS-source"

It's supposed to be open source not sure why it prompts for my credentials.

**Comment by adc-amatosov** [comment]
I am trying to migrate my existing Podfile with 60+ pods to Cartfile  and I experience this issue. Update hangs at `*** Fetching CocoaLumberjack`

**Comment by guidomb** [comment]
In my experience when Carthage hangs, is due to not being able to choose a version for transitive dependencies. This usually happens when two dependencies depend on the the dependency but slightly (usually compatible) different versions.

**Comment by dhoerl** [comment]
What really helped me was while it hung, running "ps -aef | grep git" - I could then see the exact git actions. I copied the clone command, killed carthage, then tried to run it via terminal, and could see what happened. If any git command prompts you for anything, carthage hangs with no indication of why.

**Comment by mdiep** [comment]
@dhoerl What was git prompting you for?

**Comment by marcvanolmen** [comment]
I have seen similar things for example when you try to access a private repo and you don't have the right access permission for that machine or don't use ssh etc... For example:

```
git clone https://github.com/<company><my private repo>.git
Cloning into '<my private repo>'...
Username for 'https://github.com': 
```

**Comment by dhoerl** [comment]
I wrote a [StackOverflow Q&A](http://stackoverflow.com/questions/42935038/how-do-i-resolve-macos-carthage-hangs-when-running-update/42935039) on this issue.

It would really be useful to have a "real" verbose option in Carthage, where it outputted to standard error the various git commands it was exec'ing - would have really helped me get to the root of my problems.

**Comment by mdiep** [comment]
Git isn't supposed to prompt in this circumstances. We set an environment variable that's supposed to disable it.

> It would really be useful to have a "real" verbose option in Carthage, where it outputted to standard error the various git commands it was exec'ing - would have really helped me get to the root of my problems.

Absolutely. There's an open issue for this. It just hasn't happened yet.

**Comment by ParulThoughtworks** [comment]
Command: 
`carthage update --verbose --platform iOS`

Cartfile:
`github "Quick/Quick" "v0.5.0"
github "Quick/Nimble"
github "realm/realm-cocoa"`

I cleaned Carthage cache repository several times

Problem - carthage update hungs up forever while cloning/fetching Quick framework

**Comment by dhoerl** [comment]
ParulThoughtworks,

Did you see my post of March 20th? You can also check out an answer I posted on [StackOverflow](https://stackoverflow.com/a/42935039/1633251)

**Comment by frederic-adda** [comment]
2 years later, still open, still not working ... :-(

**Comment by frederic-adda** [comment]
In my experience, this happens when 2 libraries have a dependency to a third lib but with different versions.
I usually try to identify libs with `~> 1.0` and try to remove "forced" versions to see if that makes things better ...

**Comment by amjad-Alhusseini** [comment]
I have the same issue but on certain machines, i try to do 
> carthage update --no-use-binaries --platform iOS
it works on my personal machine but hangs on the CI server while doing it.

is there any configurations need to be done on the machine itself to make it work? since it works on certain machines.

**Comment by yoching** [comment]
I have same error, so I investigated the conditions a little.
I couldn't figure it out completely, but I think I caught some hints.
So I add comments about it.

## Condition 1
- Cartfile:
  ```
  github "ReactiveCocoa/ReactiveCocoa"
  github "ReactiveCocoa/ReactiveObjCBridge" "master"
  github "inamiy/ReactiveAutomaton"
  ```

- Result:
`carthage update` doesn't finish.
  
  I was checking the carthage codebase and understood that dependency resolving does not finish.
  In this case, in `updatedResolvedCartfile` in `Project`, `ResolvedCartfile.init` ([here](https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Project.swift#L413)) will not be called after a while.

## Condition 2
- Cartfile
  ```
  github "ReactiveCocoa/ReactiveObjCBridge" "master"
  github "inamiy/ReactiveAutomaton"
  ```
  (`ReactiveCocoa` removed from Condition 1)

- Result
  `carthage update` aborted and this error shown

  ```
  Could not pick a version for github "ReactiveCocoa/ReactiveSwift", due to mutually incompatible requirements:
  	~> 1.0.0 (github "inamiy/ReactiveArray")
  	~> 3.0.0 (github "ReactiveCocoa/ReactiveObjCBridge")
  ```

So, I guess this error is related to Cartfile that has "mutually incompatible requirements" plus some library around it.

**Comment by blender** [comment]
@yoching are you using --new-resolver?

**Comment by yoching** [comment]
@blender 
With `--new-resolver`, the problems with cartfile above was fixed. Thank you.

But, with this catfile below, build didn't finish even with `--new-resolver` option.

```
github "ReactiveCocoa/ReactiveCocoa"
github "ReactiveCocoa/ReactiveObjCBridge" "master"
github "inamiy/ReactiveArray" "master"
github "inamiy/ReactiveAutomaton"
github "ishkawa/APIKit"
github "thoughtbot/Curry"
github "thoughtbot/Argo"
```

**Comment by yoching** [comment]
@amjad-Alhusseini 

I don't know much about the implementation detail, but in my case, cartfile which was not resolved was resolved with `--new-resolver` option.

**Comment by issuran** [comment]
Maybe your rsa associated was created with password, try to create new rsa with no password, then insert it to your GitHub account

**Comment by qalandarov** [comment]
Thanks to @dhoerl, I remembered that I had a passphrase for my SSH key and this is what I did to fix it:

1. Cancel the Carthage command
2. Add SSH key to the ssh agent (`ssh-add -K ~/.ssh/id_rsa`)
3. Run the Carthage command again
4. Profit...

**Comment by muhasturk** [comment]
Same issue on fetching firefox-ios deps.

![Screen Shot 2021-04-30 at 17 17 49](https://user-images.githubusercontent.com/4077401/117054233-8e21b880-ad22-11eb-9c97-484ce3eb9835.png)

**Comment by whatimjustlearning** [comment]
I have found that setting your git credentials within XCode might help. run '/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git config --global credential.https://github.com.username <your username>'
