### ISSUE TITLE
carthage update always stuck at 'Fetching LlamaKit'

### ISSUE THREAD

**Issue by vulgur** [Carthage/Carthage#980]
I'm use carthage for the first time to get the ReactiveCocoa. 
There is only one line in Cartfile: `github "ReactiveCocoa/ReactiveCocoa"`.
But after I running `carthage update`, it always stuck at 'Fetching LlamaKit' and cannot go further.

Is there some command options like '--verbose' to check what's going on when updating?

**Comment by mdiep** [comment]
What's the output of `carthage version`? Can you share the output from running `carthage update`?

This doesn't get stuck for me. You may need to delete `~/Library/Caches/org.carthage.CarthageKit/`. We have occasional caching issues.

As an aside, the current stable release of Reactive Cocoa targets Swift 1.2 (Xcode 6.4). If you're looking to use Swift 2 (Xcode 7+), you'll need to explicitly specify a tag for a RAC 4.0 alpha release.

**Comment by soffes** [comment]
I was having a similar issue with a different library and clearing the cache fixed my issue. Thanks @mdiep :)

**Comment by vulgur** [comment]
Well, after I change version of RAC to 4, problem solved. Sorry I didn't find the reason, maybe it just caused by my bad network condition. Please close the issue, thanks for your suggestions!
