### ISSUE TITLE
carthage update fails

### ISSUE THREAD

**Issue by philipheinser** [Carthage/Carthage#985]
```
carthage update
*** Cloning RunKit
A shell task failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

My Cartfile
```
github "khoiln/RunKit"
```

Just installed the lastest version of carthage from pkg.

**Comment by jlawton** [comment]
Does `git clone https://github.com/khoiln/RunKit.git` ask for your credentials when run directly?

**Comment by philipheinser** [comment]
Yes.

> Am 10.12.2015 um 00:24 schrieb jlawton <notifications@github.com>:
> 
> git clone https://github.com/khoiln/RunKit.git <https://github.com/khoiln/RunKit.git>

**Comment by mdiep** [comment]
Carthage clones over HTTPS by default, so you'll need to be able to clone from the command-line without entering credentials. Otherwise you can use the `--use-ssh` flag if you'd like to clone over ssh instead.

**Comment by philipheinser** [comment]
@mdiep Thanks didn't notice that flag.
