### ISSUE TITLE
Build multiple schemes from same project

### ISSUE THREAD

**Issue by diegosanchezr** [Carthage/Carthage#991]
Hi,

I'm struggling to add Carthage support to https://github.com/badoo/Chatto. After reading https://github.com/Carthage/Carthage/issues/210 it looks like building multiple schemes from the same project should work. However that's not happening for me. Carthage will just take the first shared scheme in ./ChattoApp/Pods/Pods.xcodeproj/xcshareddata/xcschemes and stop there.

Any ideas?
Cheers

**Comment by rlopezdiez** [comment]
+1

**Comment by Chiliec** [comment]
+1

**Comment by zwang** [comment]
+1

**Comment by ikesyo** [comment]
See https://github.com/badoo/Chatto/pull/18.
