### ISSUE TITLE
Suggestion: Option to notify if not the latest version

### ISSUE THREAD

**Issue by jeeftor** [Carthage/Carthage#994]
We are using Carthage internally with multiple libraries and occasionally somebody forgets to update a `Cartfile` to the latest tagged release

It would be nice if there was an option you could pass some of the carthage calls the would notify if there was a newer tagged version available

`carthage update --notify-if-newer` for example would repot:

> You are using 0.3 of library X  there is a newer version

Just an idea.

**Comment by ikesyo** [comment]
What you want would be already captured in #510 and #598, I think.
