### ISSUE TITLE
Building PubNub SDK

### ISSUE THREAD

**Issue by mjdev** [Carthage/Carthage#995]
Hey guys,

I cannot build the PubNub iOS SDK (https://github.com/pubnub/objective-c) with carthage, I added this to my Carthage file:

```github "pubnub/objective-c" ~> 4.2````

Carthage fetches the correct release, but does not even try to build it. I checked the schemes, and everything seems to be marked as shared in the Xcode project/workspace.

Do you habe some tips?

Thanks in advance,
Magnus

**Comment by ikesyo** [comment]
It seems that the library does not support Carthage since that uses CocoaPods for its dependency management: https://github.com/pubnub/objective-c/blob/v4.2.2/PubNub.podspec#L55

**Comment by mjdev** [comment]
So no workaround? I mean Carthage could just build the dependencies using pod, right?

**Comment by ikesyo** [comment]
Carthage could build the project if there are no missing files or directories. In this case, `Pods` directory doesn't exist in the repo.

So you could run `pod install` in the dependency's root by yourself, or `Pods` dir should be committed in the repo.

Please contact the maintainer if you really need Carthage support for that. :pray:

**Comment by mjdev** [comment]
Cool thanks ;)
