### ISSUE TITLE
Change -destination values to use "generic/platform=..."

### ISSUE THREAD

**Issue by NachoSoto** [Carthage/Carthage#999]
After [the *in*famous radar](http://www.openradar.me/22993940), @ikesyo added `-destination` for all simulator builds (#941). However, that was never great because it relies on [`/usr/bin/xcrun simctl list devices`](https://github.com/Carthage/Carthage/blob/67e69aa72549f82dabb3c650a210d12575a395a6/Source/CarthageKit/Xcode.swift#L895). 

`@joar_at_work` [pointed out on Twitter](https://twitter.com/joar_at_work/status/677211396375887872) that the new "generic device" option available in Xcode is also accessible from the CLI!

![screen shot 2015-12-16 at 11 43 48 am](https://cloud.githubusercontent.com/assets/685609/11851962/4a2742f4-a3ea-11e5-9a73-31e7c68c3dfc.png)

So I think we should update that implementation to use this, which would make `Carthage` more robust :)

**Comment by mdiep** [comment]
:+1:

**Comment by NachoSoto** [comment]
@neonichu might find this interesting too!

**Comment by ikesyo** [comment]
I've just tried that, and it seems that the setting works for device builds, but not for simulator builds.

The description is about for actual devices, not for simulators:

> Some  actions  (such  as building) may be performed without an actual device present.  To build against a platform generically instead of a specific device, the destination specifier may be prefixed with the optional string "generic/", indicating that the platform should be targeted  generically.   An  example of a generic destination is the "Generic iOS Device" destination displayed in Xcode's UI when no physical iOS device is present.

**Comment by NachoSoto** [comment]
Oh of course :/ I just replied to the tweet.

**Comment by mdiep** [comment]
Gonna close this unless/until we hear that a change has been made. :disappointed:
